[Doc Improvement][Task module to dialog integrate explicit files][3457835]
MicrosoftDocs/msteams-docs pull request #10007
Opened 2023-11-26 09:43 UTC by v-npaladugu

2023-11-26 09:44 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/people-picker-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6dd0317272dcabd7d94d0fc7d87295e8402cfe06/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fpeople-picker-capability.md) | 92 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c2340a0c-1beb-473a-a4f9-dcc9122846dc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/integrating-web-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6dd0317272dcabd7d94d0fc7d87295e8402cfe06/msteams-platform%2Fsamples%2Fintegrating-web-apps.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d4bb395e-f286-46f9-8a53-4972bc3f687b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-12-01 13:58 UTC, surbhigupta12 submitted a review, later dismissed

2023-12-02 00:19 UTC, erikadoyle requested changes
Looks good, but could we update "TeamsJS v.1.0" to "TeamsJS v1.x" to generalize across all minor versions?

2023-12-13 11:48 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/people-picker-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cb670b2fcdfe71a0dd5627449fedd577def592dd/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fpeople-picker-capability.md) | 92 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f0c2b88b-fce9-4450-92a4-beed79d82405) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/integrating-web-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cb670b2fcdfe71a0dd5627449fedd577def592dd/msteams-platform%2Fsamples%2Fintegrating-web-apps.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/05049fb3-f1cd-4600-b8b6-dd585467e529) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-12-28 07:10 UTC, surbhigupta12 approved these changes

2023-12-28 07:12 UTC, merged