Add B2C app page
MicrosoftDocs/msteams-docs pull request #10491
Opened 2024-03-01 23:21 UTC by tophpalmer

Adds business-to-consumer applications as a new class to Teams platform documentation.

2024-03-01 23:21 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/9016152a35c0a3e1093af65eda453c711b461e2f/msteams-platform%2FTOC.yml) | 97 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f5008ac6-3cb9-4446-aab8-fe6fc03fcb15) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/b2c-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9016152a35c0a3e1093af65eda453c711b461e2f/msteams-platform%2Fget-started%2Fb2c-apps.md) | 81 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/39d4c22a-6ff2-48de-ac93-9774db1bee5d) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-03-01 23:42 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/9e955b4b2a2ef5d1b7489c0d747cf92e0cf8afc0/msteams-platform%2FTOC.yml) | 97 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bbe930e1-5d76-4eb3-a4eb-b3496d313af5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/b2c-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9e955b4b2a2ef5d1b7489c0d747cf92e0cf8afc0/msteams-platform%2Fget-started%2Fb2c-apps.md) | 92 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/09d5c16c-a2c8-4e7e-abd0-f618eefef9bf) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-03-02 03:56 UTC, vac0224 commented on msteams-platform/get-started/b2c-apps.md
> +1. Plan and configure Teams autoattendants and call queues.
```suggestion
1. Plan and configure Teams auto attendants and call queues.
```

2024-03-02 03:57 UTC, vac0224 commented on msteams-platform/get-started/b2c-apps.md
> +[Azure Communication Services client libraries](https://learn.microsoft.com/azure/communication-services/concepts/sdk-options) are available for various platforms and languages, including Web browser
```suggestion
[Azure Communication Services client libraries](https://learn.microsoft.com/azure/communication-services/concepts/sdk-options) are available for various platforms and languages, including Web browsers (JavaScript), iOS (Swift), Android (Java), Windows (.NET). The client libraries support both mobile and desktop web browsers. An open-source [UI library](https://learn.microsoft.com/azure/communication-services/concepts/ui-library/ui-library-overview) can accelerate development for Web, iOS, and Android apps. Azure Communication Services is identity-agnostic, and you control how end users are identified and authenticated.
```

2024-03-02 03:58 UTC, vac0224 commented on msteams-platform/get-started/b2c-apps.md
> +- **Organizational approach.** Most businesses have employees operate as agents using Teams or a licensed contact center as a service software (CCaaS). Other businesses may out-source the agent role
```suggestion
- **Organizational approach.** Most businesses have employees operate as agents using Teams or a licensed contact center as a service software (CCaaS). Other businesses may outsource the agent role or use specialized service providers who fully operate contact centers as a service.
```

2024-03-02 03:59 UTC, vac0224 commented on msteams-platform/get-started/b2c-apps.md
> +Contact center applications are focused on unscheduled communication between consumers and agents. The unscheduled nature of the interaction is a key attribute of contact center applications. The ter
```suggestion
Contact center applications focus on unscheduled communication between consumers and agents. The unscheduled nature of the interaction is a key attribute of contact center applications. The term "contact center" captures a large family of applications diverse across scale, channels, and organizational approach:
```

2024-03-04 19:53 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/58d0b9f47d1bcee24073340c19d521b20da0c68b/msteams-platform%2FTOC.yml) | 97 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/52f53796-a056-48b7-b6d4-da0fa792c53d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/b2c-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/58d0b9f47d1bcee24073340c19d521b20da0c68b/msteams-platform%2Fget-started%2Fb2c-apps.md) | 92 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/12aa22fd-59ea-4cfb-b35a-fb4e691d3f60) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-03-04 19:53 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/58d0b9f47d1bcee24073340c19d521b20da0c68b/msteams-platform%2FTOC.yml) | 97 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8fe644eb-4795-4182-8e0b-d3668c580bf0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/b2c-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/58d0b9f47d1bcee24073340c19d521b20da0c68b/msteams-platform%2Fget-started%2Fb2c-apps.md) | 92 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/476518bb-511a-472e-8230-530e4b0b7d6e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-03-05 05:33 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/4c9f9fd49e58a81525d2896b52c32b8767d9551f/msteams-platform%2FTOC.yml) | 97 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/58549cac-bfcf-43e4-9d57-5462fe1f44ae) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/b2c-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4c9f9fd49e58a81525d2896b52c32b8767d9551f/msteams-platform%2Fget-started%2Fb2c-apps.md) | 92 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d5c2d897-4392-42aa-a498-984376057bbf) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-03-05 05:34 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/500f40b21bbc5abc12c6e1120f2f5e6ab235cb18/msteams-platform%2FTOC.yml) | 97 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d949dbac-f272-493f-8277-fd02d2a9afed) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/b2c-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/500f40b21bbc5abc12c6e1120f2f5e6ab235cb18/msteams-platform%2Fget-started%2Fb2c-apps.md) | 92 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0d8ac357-cc51-49c6-933e-0fc762ca2a13) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-03-06 17:53 UTC, vac0224 commented on msteams-platform/get-started/b2c-apps.md
> +[Azure Communication Services client libraries](https://learn.microsoft.com/azure/communication-services/concepts/sdk-options) are available for various platforms and languages, including Web browser
```suggestion
[Azure Communication Services client libraries](../../../azure/communication-services/concepts/sdk-options) are available for various platforms and languages, including Web browsers (JavaScript), iOS (Swift), Android (Java), Windows (.NET). The client libraries support both mobile and desktop web browsers. An open-source [UI library](../../../azure/communication-services/concepts/ui-library/ui-library-overview) can accelerate development for Web, iOS, and Android apps. Azure Communication Services is identity-agnostic, and you control how end users are identified and authenticated.
```

2024-03-06 17:55 UTC, vac0224 reviewed
Testing relative link paths on line 35.

2024-03-06 20:10 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/cd074c905ab84284c3e2f26f5b6ff48e9b043183/msteams-platform%2FTOC.yml) | 97 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3516d36a-944a-4b18-b6dc-c716d893b871) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/b2c-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cd074c905ab84284c3e2f26f5b6ff48e9b043183/msteams-platform%2Fget-started%2Fb2c-apps.md) | 92 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/43ab60f9-ac29-40d2-910b-7bbb45bfd8f9) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-03-06 20:41 UTC, vac0224 commented on msteams-platform/get-started/b2c-apps.md
> +- [Concept: Virtual visit apps with Azure Communication Services](https://learn.microsoft.com/azure/communication-services/tutorials/virtual-visits)
```suggestion
- [Concept: Virtual visit apps with Azure Communication Services](../../../azure/communication-services/tutorials/virtual-visits.md)
```

2024-03-06 20:41 UTC, vac0224 commented on msteams-platform/get-started/b2c-apps.md
> +- [Concept: Azure & Teams interoperability](https://learn.microsoft.com/azure/communication-services/concepts/interop/guest/overview)
```suggestion
- [Concept: Azure & Teams interoperability](/azure/communication-services/concepts/interop/guest/overview.md)
```

2024-03-06 20:41 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/5f7d5f149937184c025a62c05ac1e5315326afcf/msteams-platform%2FTOC.yml) | 97 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/11b59ac3-f35d-43f4-bb92-5ea49dd08d8f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/b2c-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5f7d5f149937184c025a62c05ac1e5315326afcf/msteams-platform%2Fget-started%2Fb2c-apps.md) | 92 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3c45d98e-8f2c-45b0-919a-ff01c77d307e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-03-06 20:42 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/2c0e4f99a1d27cd6654378dc99e4f739dcf13ba9/msteams-platform%2FTOC.yml) | 97 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6399fca1-bf66-4598-97e2-fb1933bce527) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/b2c-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2c0e4f99a1d27cd6654378dc99e4f739dcf13ba9/msteams-platform%2Fget-started%2Fb2c-apps.md) | 92 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/34f9ffca-8b75-4106-818c-79859160a24b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-03-06 21:08 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/0c7844ceb282fffd3c48b8849403a9622eec4262/msteams-platform%2FTOC.yml) | 97 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c92bbef7-35a0-4efb-842f-b72489498e0a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/b2c-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0c7844ceb282fffd3c48b8849403a9622eec4262/msteams-platform%2Fget-started%2Fb2c-apps.md) | 92 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/85dd5e8e-6021-4ead-81d6-80efe9f6eda6) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-03-06 21:28 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/2d4b6f61f4c59e0a2ea8ce1c8392aebd53172432/msteams-platform%2FTOC.yml) | 97 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f69c6fb4-2bd6-4db2-9457-63283c71140e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/b2c-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2d4b6f61f4c59e0a2ea8ce1c8392aebd53172432/msteams-platform%2Fget-started%2Fb2c-apps.md) | 92 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ce5a84ec-077e-4ac5-944f-a603f0ef2251) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-03-06 21:40 UTC, vac0224 approved these changes
LGTM

2024-03-12 20:51 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/3d1cbfd7214164c6302f357346bc62ea009ebccd/msteams-platform%2FTOC.yml) | 97 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f9b5c568-83d9-44e2-a9da-14c21ede3559) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/b2c-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3d1cbfd7214164c6302f357346bc62ea009ebccd/msteams-platform%2Fget-started%2Fb2c-apps.md) | 92 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5693b93b-d9c8-4bf6-9f08-70f317eca652) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-03-18 20:13 UTC, vac0224 commented
#sign-off

2024-03-18 20:14 UTC, vac0224 commented
@v-sdhakshina can you review? Thanks

2024-03-20 16:17 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/7f2e790efb1bbde5bf897c849a81e4afeccd4f16/msteams-platform%2FTOC.yml) | 97 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ddbf9f27-e691-48cc-bc63-b9bb08b0add3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/b2c-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7f2e790efb1bbde5bf897c849a81e4afeccd4f16/msteams-platform%2Fget-started%2Fb2c-apps.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aba858d1-6352-44fd-a3dd-6f75c7f353e8) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-03-20 16:56 UTC, vac0224 commented on msteams-platform/get-started/b2c-apps.md
> +[Azure Communication Services client libraries](../../../azure/articles/communication-services/concepts/sdk-options) are available for various platforms and languages, including Web browsers (JavaScr
```suggestion
[Azure Communication Services client libraries](../../../azure/articles/communication-services/concepts/sdk-options.md) are available for various platforms and languages, including Web browsers (JavaScript), iOS (Swift), Android (Java), Windows (.NET). The client libraries support both mobile and desktop web browsers. An open-source [UI library](../../../azure/communication-services/concepts/ui-library/ui-library-overview.md) can accelerate development for Web, iOS, and Android apps. Azure Communication Services is identity-agnostic, and you control how end users are identified and authenticated.
```

2024-03-20 16:57 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/b7ee8d97b9ad3047e932e862e08b046ff9127aee/msteams-platform%2FTOC.yml) | 97 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5aa73683-4a05-4d49-ac07-77866e4c69bb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/b2c-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b7ee8d97b9ad3047e932e862e08b046ff9127aee/msteams-platform%2Fget-started%2Fb2c-apps.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/df9517a6-f329-4726-9103-7881b4ea0be1) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-03-20 18:42 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ba3053447590beb57299f5d5fb486ab5e531a696/msteams-platform%2FTOC.yml) | 97 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/991bcee3-ef92-4db9-a59b-563e084cba14) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/b2c-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ba3053447590beb57299f5d5fb486ab5e531a696/msteams-platform%2Fget-started%2Fb2c-apps.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1780ffa9-04d2-4ba2-b7af-9d47cf126673) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-03-20 21:34 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/6360a785ede1250f157da8651856192f0f6129a7/msteams-platform%2FTOC.yml) | 97 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c3c76b28-a659-417d-84f1-89c4377b0185) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/b2c-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6360a785ede1250f157da8651856192f0f6129a7/msteams-platform%2Fget-started%2Fb2c-apps.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fb125143-5268-40bf-87f6-6a3f11e3ee66) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-03-20 21:53 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/fb526a9e6d6f82ae0533f77f37c59172cbe8620b/msteams-platform%2FTOC.yml) | 97 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e51bba49-0207-40e2-ba98-aeba8ef241e6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/b2c-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fb526a9e6d6f82ae0533f77f37c59172cbe8620b/msteams-platform%2Fget-started%2Fb2c-apps.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fd3f0ad5-925a-4687-abe8-c5c1f27e9c46) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-03-28 17:09 UTC, vac0224 approved these changes
LGTM

2024-03-28 17:10 UTC, vac0224 approved these changes
Approved

2024-03-28 17:11 UTC, vac0224 commented
#sign-off

2024-03-28 20:56 UTC, vac0224 commented
@v-sdhakshina and @tophpalmer I approved and signed off, but not able to merge. Maybe one of you can also approve? Thanks

2024-03-29 07:12 UTC, surbhigupta12 commented
> @v-sdhakshina and @tophpalmer I approved and signed off, but not able to merge. Maybe one of you can also approve? Thanks

This PR is under review.

2024-04-01 13:06 UTC, v-sdhakshina requested changes

2024-04-01 13:07 UTC, v-sdhakshina commented on msteams-platform/get-started/b2c-apps.md
> +3. Embed Azure Communication Services Calling and Chat into your website or native app.
Global: Request you to check the reference link added.

2024-04-02 14:53 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/8a20d934b21ee54029dddf42824e9468e2e7947b/msteams-platform%2FTOC.yml) | 97 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/78ee6f89-3228-4f58-b371-d536de87a62c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/b2c-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8a20d934b21ee54029dddf42824e9468e2e7947b/msteams-platform%2Fget-started%2Fb2c-apps.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/99eac044-ed33-49b0-954a-81ad682a77b9) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-04-02 14:53 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/84c92c82cd1501b232c266b40eef1159e2d3e415/msteams-platform%2FTOC.yml) | 97 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fa8023c3-dec5-4a59-8a7f-14ce24c27cce) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/b2c-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/84c92c82cd1501b232c266b40eef1159e2d3e415/msteams-platform%2Fget-started%2Fb2c-apps.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/162b9e81-910c-4cb4-8245-6ab8bae3964c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-04-02 14:53 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/426a6eceef7f1cdf097ff891c60386605700475d/msteams-platform%2FTOC.yml) | 97 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/75305fa6-d22d-4640-8fc3-49342e2e3f16) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/b2c-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/426a6eceef7f1cdf097ff891c60386605700475d/msteams-platform%2Fget-started%2Fb2c-apps.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1db4ae9b-f046-461a-9088-c70854c75894) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-04-02 14:54 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/fd94a7f2286e73a6cf4a4ac44ab5f95647b30db7/msteams-platform%2FTOC.yml) | 97 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1368b25c-a114-40ca-9c9e-347b878543e1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/b2c-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fd94a7f2286e73a6cf4a4ac44ab5f95647b30db7/msteams-platform%2Fget-started%2Fb2c-apps.md) | 92 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a3c1b0a9-ea9b-44df-ae02-18fe41ba7921) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-04-02 14:56 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/75d95314c2dd6e588639d5ef8c24a9e81d95d302/msteams-platform%2FTOC.yml) | 97 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fe8e08c1-e37f-4976-86c8-b5860dd656b3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/b2c-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/75d95314c2dd6e588639d5ef8c24a9e81d95d302/msteams-platform%2Fget-started%2Fb2c-apps.md) | 94 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4f7e1bae-124a-4b7d-bb61-dd615d75214f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-04-02 14:56 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/5b62cc3222d5cf3db2d5d4da6757a9d26434a1dc/msteams-platform%2FTOC.yml) | 97 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a0d94715-4dd7-4f54-b0c6-bf4d50aa4ff2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/b2c-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5b62cc3222d5cf3db2d5d4da6757a9d26434a1dc/msteams-platform%2Fget-started%2Fb2c-apps.md) | 94 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e3fec28c-3093-459e-90bb-6490d4ff09e2) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-04-02 14:57 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/0004786fd319e3dde4747d1576f6e1f23d2ceba0/msteams-platform%2FTOC.yml) | 97 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2c46ac88-47b0-4e52-ba1e-6d39c8538ead) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/b2c-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0004786fd319e3dde4747d1576f6e1f23d2ceba0/msteams-platform%2Fget-started%2Fb2c-apps.md) | 94 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2a679411-4342-4a0f-bcb9-f14aeb8243e3) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-04-02 14:57 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/d9ac6851139dd188b433e85c3b2e98cc3ecb55b8/msteams-platform%2FTOC.yml) | 97 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/652ce484-e812-4d46-b7f1-e6e2097e15ea) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/b2c-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d9ac6851139dd188b433e85c3b2e98cc3ecb55b8/msteams-platform%2Fget-started%2Fb2c-apps.md) | 94 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/93c8dfd7-9817-4d9f-8557-2357d4687929) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-04-02 15:01 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/cf0fc645f894999991d52eae2efdd87c018a1b1d/msteams-platform%2FTOC.yml) | 97 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d11337d5-cfc2-4439-8ffa-b759b0b82319) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/b2c-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cf0fc645f894999991d52eae2efdd87c018a1b1d/msteams-platform%2Fget-started%2Fb2c-apps.md) | 94 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/90dcf9ed-84c7-458b-8d19-2f92f402e1e6) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-04-02 15:13 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/f30d16f1e5d4800fb246c54bdd69977c263c8816/msteams-platform%2FTOC.yml) | 97 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/239d7680-5491-4cde-b0c3-f4705a1a494f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/b2c-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f30d16f1e5d4800fb246c54bdd69977c263c8816/msteams-platform%2Fget-started%2Fb2c-apps.md) | 94 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/574f4ca0-125b-49b7-b2e1-32bb19255b99) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-04-02 15:14 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/2db5a781f4dbbaa23b28aab9a14c8eb7f1b2f7aa/msteams-platform%2FTOC.yml) | 97 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/05674e19-b5a9-4f28-b7f8-92e9c1885fe6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/b2c-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2db5a781f4dbbaa23b28aab9a14c8eb7f1b2f7aa/msteams-platform%2Fget-started%2Fb2c-apps.md) | 94 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/21d869e4-8cb7-4774-b813-baa26ffc116d) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-04-02 15:21 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/f39f3d713e69cd7c15423a2afee1dcd46370ee2e/msteams-platform%2FTOC.yml) | 97 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4b7239b2-ec83-44df-8421-4df21938522d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/b2c-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f39f3d713e69cd7c15423a2afee1dcd46370ee2e/msteams-platform%2Fget-started%2Fb2c-apps.md) | 92 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2e950c38-6818-4eb1-90ec-eccb31800e4a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-04-02 15:22 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a5a402ffa026de76ab4eeff3e531c490213176b1/msteams-platform%2FTOC.yml) | 97 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/212aa541-d0a8-46d8-a523-d3fcb2642b71) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/b2c-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a5a402ffa026de76ab4eeff3e531c490213176b1/msteams-platform%2Fget-started%2Fb2c-apps.md) | 90 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e352a7db-3263-4d6b-a85c-d176e9e91a06) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-04-02 19:07 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c8596dbbddc60a0c41d6ae1ce5a9e027da47af9f/msteams-platform%2FTOC.yml) | 97 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cad5b9cf-39da-4dad-a80f-095b7b8b7b74) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/b2c-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c8596dbbddc60a0c41d6ae1ce5a9e027da47af9f/msteams-platform%2Fget-started%2Fb2c-apps.md) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/27df3041-e8d2-4271-aace-e0d681977d56) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-04-02 19:48 UTC, vac0224 approved these changes
LGTM

2024-04-02 19:49 UTC, vac0224 commented
@v-sdhakshina let me know if I covered all of your requested changes. Awaiting your review and approval, thanks!

2024-04-03 22:04 UTC, vac0224 commented
#sign-off

2024-04-04 14:25 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ba458ea83b885bb6280124e90d648349f9633474/msteams-platform%2FTOC.yml) | 95 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e1d44cd7-971d-4966-8c45-479ef1c66b88) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ba458ea83b885bb6280124e90d648349f9633474/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/de17601d-cebc-4bad-9d36-f282e3133edc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/b2c-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ba458ea83b885bb6280124e90d648349f9633474/msteams-platform%2Fget-started%2Fb2c-apps.md) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2f140aba-a651-4b1a-9544-a239cd47acf3) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-04-04 17:28 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/62417e8d570d51d7e28c7c8792c03e77537d0c89/msteams-platform%2FTOC.yml) | 95 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8642e123-7d52-4c67-a52f-cbbfbac5ce14) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/62417e8d570d51d7e28c7c8792c03e77537d0c89/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ada2d135-06b2-4fb9-8363-7820d340bef1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/b2c-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/62417e8d570d51d7e28c7c8792c03e77537d0c89/msteams-platform%2Fget-started%2Fb2c-apps.md) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d69be1ca-dab5-44d1-9e89-6f7a7520c268) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-04-04 17:46 UTC, vac0224 commented
@v-sdhakshina I made all the changes from you suggested. Maybe you can review and approve?

2024-04-08 15:40 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/fd5f008cc8c2e5868d99a3a746282dfc406f9db9/msteams-platform%2FTOC.yml) | 95 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3d0129ac-5cc6-47d1-a96d-e06e28004a55) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fd5f008cc8c2e5868d99a3a746282dfc406f9db9/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/40cb5fe3-8803-49e6-87bc-d35dfda8ca76) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/b2c-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fd5f008cc8c2e5868d99a3a746282dfc406f9db9/msteams-platform%2Fget-started%2Fb2c-apps.md) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d36ce0dc-9779-46e9-b293-de0f08805d50) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-04-08 15:43 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/db6fcf0b267ee946478ff7fe8c4b967bbaebe060/msteams-platform%2FTOC.yml) | 95 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a991da4b-ec87-4e0f-897e-3032fbe6328b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/db6fcf0b267ee946478ff7fe8c4b967bbaebe060/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/50022768-8562-482c-8b33-b9d15c62fead) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/b2c-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/db6fcf0b267ee946478ff7fe8c4b967bbaebe060/msteams-platform%2Fget-started%2Fb2c-apps.md) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/96a23b5a-5b98-4fb5-9a16-6e6cf2f91090) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-04-08 15:56 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e6a54a45383581f524403a1eb340f39452116829/msteams-platform%2FTOC.yml) | 95 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4ee9a73f-9070-4d7c-b21b-aa2e85bb8263) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e6a54a45383581f524403a1eb340f39452116829/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/44087285-73ce-40b3-bf88-f23782ca0391) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/b2c-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e6a54a45383581f524403a1eb340f39452116829/msteams-platform%2Fget-started%2Fb2c-apps.md) | 96 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5b4ac382-1dfb-4d4b-a70b-1179ece99d49) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-04-10 03:35 UTC, tophpalmer commented
#sign-off

2024-04-10 03:42 UTC, tophpalmer commented
Thank you @v-sdhakshina for the time and suggested changes, please publish at your soonest convenience.

2024-04-10 05:25 UTC, v-sdhakshina approved these changes

2024-04-11 02:14 UTC, vac0224 commented
#sign-off

2024-04-12 08:16 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ae1fb944f8e461174445344594df67d814780f2f/msteams-platform%2FTOC.yml) | 95 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8399c236-68c1-4a0f-bafe-51e2529cde85) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ae1fb944f8e461174445344594df67d814780f2f/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1e9e316b-aa65-499e-b3a4-e6edea2477d7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/b2c-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ae1fb944f8e461174445344594df67d814780f2f/msteams-platform%2Fget-started%2Fb2c-apps.md) | 96 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6fbe1551-cee8-4e14-81a6-10d93b457f38) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-04-12 08:30 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1244abab96a8f8a799b478c9b32771cd4ecee553/msteams-platform%2FTOC.yml) | 95 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4ad69d2a-2a4e-47fc-a061-b25abc52df28) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1244abab96a8f8a799b478c9b32771cd4ecee553/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a0a708e9-c539-4cca-8501-d262a7679417) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/b2c-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1244abab96a8f8a799b478c9b32771cd4ecee553/msteams-platform%2Fget-started%2Fb2c-apps.md) | 96 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/70e42bc9-8ca6-4e26-9d93-a6a807af44ba) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-04-12 10:05 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/0bfa68d884c8f7d193a2771adfc772c93f003292/msteams-platform%2FTOC.yml) | 96 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/be3beb28-1040-4e79-8707-5accbdff5ad7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0bfa68d884c8f7d193a2771adfc772c93f003292/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/812b7b58-e89e-465a-85c3-313aebcdaf37) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/b2c-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0bfa68d884c8f7d193a2771adfc772c93f003292/msteams-platform%2Fget-started%2Fb2c-apps.md) | 96 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1bc2b59f-fa5a-4fba-abb1-860858aff1d8) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-04-12 13:56 UTC, vac0224 approved these changes
LGTM

2024-04-12 13:59 UTC, vac0224 commented
@v-sdhakshina can you approve your changes? Maybe then we can merge. 😎

2024-04-15 11:52 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/32c738e9c9d61c42a4a8715421a0f3960171df96/msteams-platform%2FTOC.yml) | 96 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/40f6a0a0-4b64-48c9-8416-d42380a7b953) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/32c738e9c9d61c42a4a8715421a0f3960171df96/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a61e6274-4871-4ae8-b301-645200c74524) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/b2c-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/32c738e9c9d61c42a4a8715421a0f3960171df96/msteams-platform%2Fget-started%2Fb2c-apps.md) | 96 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/54a4c87e-2e87-454c-bb69-cd5e55877349) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-04-15 11:53 UTC, surbhigupta12 approved these changes

2024-04-15 11:57 UTC, merged