Update sbs-api-based-message-extensions.yml
MicrosoftDocs/msteams-docs pull request #10773
Opened 2024-04-24 12:36 UTC by Benjiiim

Fix some typos and upgrade from DevPreview version to 1.17

2024-04-24 12:38 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-api-based-message-extensions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c0cda0354435d02a65a9665fc46b624c090d368c/msteams-platform%2Fsbs-api-based-message-extensions.yml) | 72 | 124 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dd310086-4ef9-4625-a050-aac9b319e70c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-04-24 12:40 UTC, Benjiiim commented
@microsoft-github-policy-service agree

2024-04-24 12:44 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-api-based-message-extensions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ad5b590c1ea085ee3e0b32550c3ca1a4ff20144f/msteams-platform%2Fsbs-api-based-message-extensions.yml) | 72 | 124 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/81208ca6-e5e7-4a28-9103-dd6adad92c01) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2025-03-06 09:19 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-api-based-message-extensions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/2eb9db03d212cc467fec308021ba4b7b698bc599/msteams-platform%2Fsbs-api-based-message-extensions.yml) | 76 | 117 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ead2f9fe-6451-408d-93c0-fe6a309f9a28) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2025-03-12 07:23 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-api-based-message-extensions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c6872c93e933db6864b36c66ede92e4610dcf4b4/msteams-platform%2Fsbs-api-based-message-extensions.yml) | 76 | 117 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dcc0323f-427e-4eae-ab8c-a517a117aa90) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2025-03-12 12:29 UTC, ChetanSharma-msft requested changes
Added my review comments.

2025-03-12 12:29 UTC, ChetanSharma-msft commented on msteams-platform/sbs-api-based-message-extensions.yml
> +    The response rendering template must conform to the schema hosted at [`https://developer.microsoft.com/json-schemas/teams/v1.17/MicrosoftTeams.ResponseRenderingTemplate.schema.json`](https://deve
Please update these changes to use latest schema: v1.20

2025-03-12 14:06 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-api-based-message-extensions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/962223563afd18dcfa5f34409ea3b4b2a21c24ec/msteams-platform%2Fsbs-api-based-message-extensions.yml) | 76 | 117 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/273dd9f1-ebc6-44ac-a885-debe7f5b8fcd) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2025-03-13 05:54 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-api-based-message-extensions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/cd752ce097dd8d5b3a2a8e8a075540b6e63ddcdc/msteams-platform%2Fsbs-api-based-message-extensions.yml) | 76 | 117 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/57b10fad-a825-44e9-9786-afebeb0fc71c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2025-03-13 05:55 UTC, v-kushals commented on msteams-platform/sbs-api-based-message-extensions.yml
> +    The response rendering template must conform to the schema hosted at [`https://developer.microsoft.com/json-schemas/teams/v1.17/MicrosoftTeams.ResponseRenderingTemplate.schema.json`](https://deve
Done, @ChetanSharma-msft.

2025-03-17 09:56 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-api-based-message-extensions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1f32d32011fc9c95e7528b3024e04c23f6e42a0e/msteams-platform%2Fsbs-api-based-message-extensions.yml) | 76 | 117 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2cae7380-1a0e-42fc-9b62-b4f70c8be179) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2025-03-19 11:48 UTC, ChetanSharma-msft approved these changes
Changes looks fine, approving it.

2025-03-21 05:30 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-api-based-message-extensions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1a4236e9748aeec392047df61d4086ebbe1f23dc/msteams-platform%2Fsbs-api-based-message-extensions.yml) | 76 | 117 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5e5d871d-5a64-46af-bb40-db4f46591670) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2025-03-21 05:32 UTC, v-kushals approved these changes

2025-03-21 09:13 UTC, v-srmurugan approved these changes

2025-03-21 09:16 UTC, surbhigupta12 approved these changes

2025-03-21 09:16 UTC, merged