[Doc Improvement][Document localization schema v1.17]
MicrosoftDocs/msteams-docs pull request #11099
Opened 2024-06-18 19:59 UTC by samantharamon

Documents [v1.17](https://developer.microsoft.com/en-us/json-schemas/teams/v1.17/MicrosoftTeams.Localization.schema.json) of the localization schema.

2024-06-18 19:59 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/schema/localization-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/937a64a1b8c10ed3f4188269b5653f2231627cd4/msteams-platform%2Fresources%2Fschema%2Flocalization-schema.md) | 99 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6a813b4f-6812-4ca5-8775-e31e57256dd7) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-06-24 09:05 UTC, v-ypalikila commented on msteams-platform/resources/schema/localization-schema.md
> +|`extensions\\[[0]\\]\\.audienceClaimUrl$`|String|2048|Replaces the corresponding string from the app manifest with the value provided here.||
```suggestion
|`extensions\\[[0]\\]\\.audienceClaimUrl$`|String|2048|Replaces the corresponding strings from the app manifest with the value provided here.||
```

2024-06-24 17:04 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/schema/localization-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8c9951d53acb310e95321ece6400668eebce3fc8/msteams-platform%2Fresources%2Fschema%2Flocalization-schema.md) | 99 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8c6dc813-f621-424a-a68e-5f698678b7ea) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-09-26 21:24 UTC, erikadoyle commented on msteams-platform/resources/schema/localization-schema.md
> +|`meetingExtensionDefinition.scenes\\[[0-9]\\]\\.name`|String|128|Replaces the corresponding strings from the app manifest. ||
```suggestion
|`meetingExtensionDefinition.scenes\\[[0-9]\\]\\.name$`|String|128|Replaces the corresponding strings from the app manifest. ||
```

2024-09-26 21:25 UTC, erikadoyle commented on msteams-platform/resources/schema/localization-schema.md
> +|`extensions\\[[0]\\]\\.ribbons\\[[0-9]\\]\\.tabs\\[[1]?[0-9]\\]\\.label`|String|64|Replaces the corresponding strings from the app manifest with the value provided here.||
```suggestion
|`extensions\\[[0]\\]\\.ribbons\\[[0-9]\\]\\.tabs\\[[1]?[0-9]\\]\\.label$`|String|64|Replaces the corresponding strings from the app manifest with the value provided here.||
```

2024-09-26 21:38 UTC, erikadoyle approved these changes
I checked this against the published v1.17 loc schema; looks good!

2024-09-26 21:40 UTC, erikadoyle commented
@surbhigupta12 as this is simply a reflection of the already approved/published v1.17 loc schema, could we move forward with publishing? (I verified that it matches the schema XPaths and limits.) Thanks!

2024-10-08 09:31 UTC, Wajeed-msft requested changes

2024-10-08 09:31 UTC, Wajeed-msft commented on msteams-platform/resources/schema/localization-schema.md
>  ## Example
```suggestion
## Localization schema v1.17
```

Could you please change this? Looking at "In this Article" section, developer might just navigate to 1.16 schema version. 
![image](https://github.com/user-attachments/assets/a607bea9-9d4d-4ee0-9991-cc6186074a43)

2024-10-08 10:44 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/schema/localization-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/31623e7a9367c6b3ddd9aaaa6918154ed9aac14e/msteams-platform%2Fresources%2Fschema%2Flocalization-schema.md) | 99 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/adcaf026-bb25-454b-b59e-82d9568fd4de) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-10-08 11:29 UTC, Wajeed-msft submitted a review, later dismissed

2024-10-14 06:33 UTC, v-npaladugu approved these changes

2024-10-29 12:58 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/schema/localization-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/90255da47187e99b3aed8eb690f3e550fed287ab/msteams-platform%2Fresources%2Fschema%2Flocalization-schema.md) | 99 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3e3c2f5c-c885-49df-ac23-0bace5731cb9) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-11-27 12:46 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/schema/localization-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/98164f07686bf844bfdcb1ded0bad478f68b9d5c/msteams-platform%2Fresources%2Fschema%2Flocalization-schema.md) | 99 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2a68ecc2-e0f5-417b-88f0-084351bed27e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-11-27 12:59 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/schema/localization-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/833766dc27f7b903a044e7e21b0e81934f9409da/msteams-platform%2Fresources%2Fschema%2Flocalization-schema.md) | 99 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6c197b46-5122-4d41-be7f-3fa95d28f550) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-11-28 08:37 UTC, Wajeed-msft approved these changes

2024-11-29 11:52 UTC, v-deabira approved these changes

2024-11-29 11:55 UTC, merged