Update grant-resource-specific-consent.md
MicrosoftDocs/msteams-docs pull request #11238
Opened 2024-07-10 20:23 UTC by MSFTRickyCastaneda

Removed dates around changes to Team RSC for production and government clouds. Added note warning users to keep default ManagedByMicrosoft state for RSC settings.

2024-07-10 20:24 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/graph-api/rsc/grant-resource-specific-consent.md](https://github.com/MicrosoftDocs/msteams-docs/blob/72bf2e4e75ac149367e41b505b7f2cb093fe91b3/msteams-platform%2Fgraph-api%2Frsc%2Fgrant-resource-specific-consent.md) | 90 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fe78c7cc-3037-4105-931d-1bec5cf0ed86) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-07-10 20:25 UTC, MSFTRickyCastaneda commented
@v-sdhakshina This is the new PR for the one we recently closed :) 

@AkJo @subray2014 - Please review the note added to line 379 and let me know if appropriate for this update.

2024-08-07 17:03 UTC, MSFTRickyCastaneda commented
@subray2014 @v-sdhakshina. Please review to remove dates mentioned in RSC consent docs now that we have passed the Team RSC default-on rollout period.

2024-08-14 09:21 UTC, Wajeed-msft submitted a review, later dismissed

2024-08-14 09:25 UTC, v-sdhakshina requested changes

2024-09-10 13:07 UTC, v-sdhakshina commented on msteams-platform/graph-api/rsc/grant-resource-specific-consent.md
> +> It is recommended that you leave your RSC consent settings in the default ManagedByMicrosoft state unless your organization requires a customized consent policy for RSC enabled applications
@MSFTRickyCastaneda , Gentle reminder, kindly look into the suggestion.

2025-03-13 14:15 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/graph-api/rsc/grant-resource-specific-consent.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ad4b55ae5918f7e0f538674c2e9658a8486c821d/msteams-platform%2Fgraph-api%2Frsc%2Fgrant-resource-specific-consent.md) | 89 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d3bb09f6-98c4-4e82-941e-d94eec1f6c5e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2025-03-13 14:18 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/graph-api/rsc/grant-resource-specific-consent.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4b4b3d44c956580122c9fdd4f8d86a6e780ed1c5/msteams-platform%2Fgraph-api%2Frsc%2Fgrant-resource-specific-consent.md) | 90 | 28 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d387599c-8ab7-479a-b4e7-311661db0d70) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2025-03-13 14:27 UTC, surbhigupta12 approved these changes

2025-03-13 14:27 UTC, merged