Update Teams-Toolkit-CLI.md
MicrosoftDocs/msteams-docs pull request #11479
Opened 2024-08-16 12:09 UTC by therealjohn

Add a note about GCC environments

2024-08-16 12:10 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/Teams-Toolkit-CLI.md](https://github.com/MicrosoftDocs/msteams-docs/blob/48316f7c2400a025180f35eb8c2f319d46ac5f75/msteams-platform%2Ftoolkit%2FTeams-Toolkit-CLI.md) | 89 | 74 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5ea21ef1-46c2-4c08-b961-5c41a9652728) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-08-22 11:17 UTC, v-npaladugu requested changes

2024-08-22 11:17 UTC, v-npaladugu commented on msteams-platform/toolkit/Teams-Toolkit-CLI.md
> +> * Teams Toolkit CLI isn't supported in Government Community Cloud (GCC) and GCC-High environments.
```suggestion
> * Teams Toolkit CLI isn't supported in [Government Community Cloud (GCC), GCC-High, and Department of Defense (DOD)](https://review.learn.microsoft.com/en-us/microsoftteams/platform/concepts/app-fundamentals-overview#government-community-cloud) environments.

2024-08-22 11:17 UTC, v-npaladugu commented on msteams-platform/toolkit/Teams-Toolkit-CLI.md
> +> * Teams Toolkit CLI isn't supported in Government Community Cloud (GCC) and GCC-High environments.
@therealjohn

2024-09-10 12:11 UTC, v-npaladugu commented on msteams-platform/toolkit/Teams-Toolkit-CLI.md
> +> * Teams Toolkit CLI isn't supported in Government Community Cloud (GCC) and GCC-High environments.
@therealjohn, kindly look into these suggestions.

2025-03-05 10:03 UTC, v-preethah commented on msteams-platform/toolkit/Teams-Toolkit-CLI.md
> +> * Teams Toolkit CLI isn't supported in Government Community Cloud (GCC) and GCC-High environments.
@therealjohn 

The Note isn't required.

Response from Junjie:
Teams Toolkit isn't a cloud specific thing, the answer will likely depend on what specific features & capabilities of Teams / MetaOS app you are working on, availability differs per capability for different clouds.

Teams Toolkit CLI is not cloud-specific.

2025-06-17 08:10 UTC, surbhigupta12 commented
@therealjohn,

We are closing this PR based on the feedback from engineering team:

Response from @MuyangAmigo:
Teams Toolkit isn't a cloud specific thing, the answer will likely depend on what specific features & capabilities of Teams / MetaOS app you are working on, availability differs per capability for different clouds.

Teams Toolkit CLI is not cloud-specific.

2025-06-17 08:18 UTC, closed without merging