Update prerequisites.md
MicrosoftDocs/msteams-docs pull request #11817
Opened 2024-11-15 06:54 UTC by LuyiH

add WXP content, expect to be published with MetaOS WXP public preview 100%, ETA: 12/19/2024

2024-11-15 06:54 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/m365-apps/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5020fcfedb0eb36f597da0e13a914d8dbfc5d148/msteams-platform%2Fm365-apps%2Fprerequisites.md) | 91 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a4907b7a-5afd-4220-ae3b-71b4793288d2) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-11-22 20:31 UTC, erikadoyle commented on msteams-platform/m365-apps/prerequisites.md
> +1. Open **File** > **Office Account** > **About Outlook** to confirm you're running a Microsoft 365 *Current Channel* build of Outlook. Open **File** > **Account** > **Update Channel** to confirm you
Appending this sentence makes it sound like it's possible to run different update channels for different Office applications . . . is that true? If not, could we reword this more generally to cover both cases (Outlook GA / WXP preview)? For example:

1. If you're testing in Outlook, open **File** > **Office Account** > **About Outlook** to confirm you're running a Microsoft 365 *Current Channel* build of Outlook. If you're testing in Word, Excel, or PowerPoint, open **File** > **Account** > **Update Channel** to confirm you're running a Microsoft 365 *Beta Channel* build.

2024-11-22 20:33 UTC, erikadoyle commented on msteams-platform/m365-apps/prerequisites.md
> +For Word, Excel and PowerPoint Add-ins development, see [Create Office Add-in projects using Teams Toolkit](office-js-docs/docs/develop/teams-toolkit-overview.md).
As this is a separate docset, relative links won't work here. Here's the format you'll want to use:

`/office/dev/add-ins/develop/teams-toolkit-overview`

2024-12-03 06:16 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/m365-apps/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5b70816cf7971a58d48bcee37b2a5ca32b01fc31/msteams-platform%2Fm365-apps%2Fprerequisites.md) | 91 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3bcba4da-18a2-4852-9ae9-341917936399) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2025-02-11 06:46 UTC, Rick-Kirkham requested changes

2025-02-11 06:46 UTC, Rick-Kirkham commented on msteams-platform/m365-apps/prerequisites.md
> +1. If you're testing in Outlook, open **File** > **Office Account** > **About Outlook** to confirm you're running a Microsoft 365 *Current Channel* build. If you're testing in Word, Excel, or PowerPo
```suggestion
1. If you are testing in Outlook, take the following steps:
    1. Open the Outlook desktop client and set up the mail account using your test tenant credentials.
    1. In Outlook, open **File** > **Office Account** > **About Outlook** to confirm you're running a Microsoft 365 *Current Channel* build. 
1. If you're testing in Word, Excel, or PowerPoint, open **File** > **Account** > **Update Channel** to confirm you're running a Microsoft 365 *Beta Channel* build.
```

2025-02-11 07:40 UTC, Wajeed-msft submitted a review, later dismissed

2025-02-11 18:00 UTC, erikadoyle approved these changes

2025-02-12 22:25 UTC, Rick-Kirkham commented on msteams-platform/m365-apps/prerequisites.md
> +1. If you're testing in Outlook, open **File** > **Office Account** > **About Outlook** to confirm you're running a Microsoft 365 *Current Channel* build. If you're testing in Word, Excel, or PowerPo
> 

I cannot approve unless this change is made. The current step 7 says "Open Outlook, Word, Excel and PowerPoint (desktop client) and set up the mail account using your test tenant credentials." There's no reason to open all 4 of them. Also, it makes no sense to open Word, Excel, or PowerPoint and then do something with a **mail** account.

2025-02-13 07:17 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/m365-apps/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b83139340158ea71311645dbf845500c127f0380/msteams-platform%2Fm365-apps%2Fprerequisites.md) | 91 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9172254c-2e2f-4b95-9970-dfd620fb271d) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2025-02-13 16:39 UTC, erikadoyle commented on msteams-platform/m365-apps/prerequisites.md
> +1. If you're testing in Outlook, open **File** > **Office Account** > **About Outlook** to confirm you're running a Microsoft 365 *Current Channel* build. If you're testing in Word, Excel, or PowerPo
@LuyiH had approved this change (via Teams conversation), @V-bvishnu5 are you able to accept the change so we can unblock @Rick-Kirkham's approval? (I don't have permissions). Thanks!

2025-02-14 06:51 UTC, Rick-Kirkham requested changes

2025-02-14 06:51 UTC, Rick-Kirkham commented on msteams-platform/m365-apps/prerequisites.md
> +1. If you're testing in Outlook, open **File** > **Office Account** > **About Outlook** to confirm you're running a Microsoft 365 *Current Channel* build. If you're testing in Word, Excel, or PowerPo
@v-shalinir  This change has been marked "resolved" twice now without anyone actually making the change. For the reasons I gave, the change has to be made.

2025-02-14 08:00 UTC, surbhigupta12 commented on msteams-platform/m365-apps/prerequisites.md
> +1. If you're testing in Outlook, open **File** > **Office Account** > **About Outlook** to confirm you're running a Microsoft 365 *Current Channel* build. If you're testing in Word, Excel, or PowerPo
@Rick-Kirkham, apologies, the comment was marked resolved by mistake. Requesting @LuyiH to please update the comment asap. We will only merge this PR after @Rick-Kirkham's approval.

2025-02-20 02:24 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/m365-apps/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/632b31d4b9aa3fc679a27235221399bbbe8ff224/msteams-platform%2Fm365-apps%2Fprerequisites.md) | 91 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/25bae0a0-820c-4e07-95aa-39519891d712) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2025-02-20 02:25 UTC, LuyiH reviewed
Updated based on Ricky's suggestion

2025-02-20 07:49 UTC, Rick-Kirkham approved these changes

2025-02-24 10:56 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/m365-apps/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9f16be5d05e23d57a4ce2626a05b485ac75dc29b/msteams-platform%2Fm365-apps%2Fprerequisites.md) | 91 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f27b7897-dce1-41b0-be9d-1cdc748a67a9) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2025-02-24 11:14 UTC, surbhigupta12 approved these changes

2025-02-24 11:28 UTC, merged