[Doc Improvement][Bot revamp CEA-UX structure]
MicrosoftDocs/msteams-docs pull request #11928
Opened 2024-12-12 12:50 UTC by v-shalinir

2024-12-12 12:50 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/3300bba9ccee4ba27870bef74730dde2d0ac0a3e/msteams-platform%2FTOC.yml) | 91 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6adf01c6-eefe-4ef9-8ac8-8c737630afcc) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-12-12 13:02 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/256caaf1093d67462c1b182781e9139ff18e2e2d/msteams-platform%2FTOC.yml) | 91 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/14a81aa0-96b6-4ee9-872e-d0b2248e66e3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/teams-conversational-ai/ai-ux.md](https://github.com/MicrosoftDocs/msteams-docs/blob/256caaf1093d67462c1b182781e9139ff18e2e2d/msteams-platform%2Fbots%2Fhow-to%2Fteams-conversational-ai%2Fai-ux.md) | 89 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4d0db7c0-c95b-4366-a3a9-2f0541267fed) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-12-18 05:12 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/42cc677bd62ffc48881424f6f1f7cd0cff8354fb/msteams-platform%2FTOC.yml) | 93 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/305943b8-95e6-4732-9ad3-29e6f46c656f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/teams-conversational-ai/ai-ux.md](https://github.com/MicrosoftDocs/msteams-docs/blob/42cc677bd62ffc48881424f6f1f7cd0cff8354fb/msteams-platform%2Fbots%2Fhow-to%2Fteams-conversational-ai%2Fai-ux.md) | 89 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ba86b3ec-1981-4ae2-a720-54ed57c1f142) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2025-01-13 20:41 UTC, girliemac requested changes

2025-01-13 20:41 UTC, girliemac commented on msteams-platform/bots/how-to/teams-conversational-ai/ai-ux.md
Can you include the screenshots for each feature for clarity? You should be able to grab the embedded screenshots in pages 10 - 12 in the [Custom Engine Copilots in Bizchat.docx](https://microsoft-my.sharepoint-df.com/:w:/p/kavempar/EcUk-ZUto-dCkdq-jZ2FdIUB3kp8-DpPrrP-uS0NiU9NYw?e=apcped)? if you can't grab the images, please contact the author for the images.

2025-01-17 07:55 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/81dd3498e134ef709e87b4200a49d76b9e0ca6e5/msteams-platform%2FTOC.yml) | 92 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e377a51c-daf1-493e-bb1b-851ea62f368e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/teams-conversational-ai/ai-ux.md](https://github.com/MicrosoftDocs/msteams-docs/blob/81dd3498e134ef709e87b4200a49d76b9e0ca6e5/msteams-platform%2Fbots%2Fhow-to%2Fteams-conversational-ai%2Fai-ux.md) | 89 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8bfaf9a3-af82-4277-83bc-283451f52c49) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2025-01-17 08:55 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/5458680d3b139097acc1fa0765602e2ef3c84d67/msteams-platform%2FTOC.yml) | 92 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/907258f2-7b37-4e75-87a9-243c1f44e608) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/teams-conversational-ai/ai-ux.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5458680d3b139097acc1fa0765602e2ef3c84d67/msteams-platform%2Fbots%2Fhow-to%2Fteams-conversational-ai%2Fai-ux.md) | 89 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8b0572c3-fff0-42e7-aa55-b7d755f538fe) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2025-01-17 10:17 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/348195014e03a5e25409cab16bb6190c1eba2372/msteams-platform%2FTOC.yml) | 92 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/45539902-0ab2-41ba-875b-0dc047e25185) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/teams-conversational-ai/ai-ux.md](https://github.com/MicrosoftDocs/msteams-docs/blob/348195014e03a5e25409cab16bb6190c1eba2372/msteams-platform%2Fbots%2Fhow-to%2Fteams-conversational-ai%2Fai-ux.md) | 90 | 33 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6d8bf6f6-b656-471b-b5ac-bc996c2b6ebe) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2025-01-17 10:35 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/36dc580ec5bffebd77caeb21a43745e48bb2a02b/msteams-platform%2FTOC.yml) | 92 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6537fb77-2772-4b1f-85f9-c71646f2a91c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/teams-conversational-ai/ai-ux.md](https://github.com/MicrosoftDocs/msteams-docs/blob/36dc580ec5bffebd77caeb21a43745e48bb2a02b/msteams-platform%2Fbots%2Fhow-to%2Fteams-conversational-ai%2Fai-ux.md) | 90 | 33 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a23e740e-1382-433b-bd63-9e89c545fe8f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2025-01-17 10:45 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/8c2d307dd69628793c6535590029a3c2951e1fd7/msteams-platform%2FTOC.yml) | 92 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dc1f2288-fe83-4d85-825d-d28086d0015c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/teams-conversational-ai/ai-ux.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8c2d307dd69628793c6535590029a3c2951e1fd7/msteams-platform%2Fbots%2Fhow-to%2Fteams-conversational-ai%2Fai-ux.md) | 90 | 33 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e57232e1-bd64-4ff1-8d5c-f20e1250ecdc) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2025-01-17 11:09 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/787776a134a6148ebe18c0e0945ac22da22b8be0/msteams-platform%2FTOC.yml) | 92 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9cf73e2e-ee29-4c19-8b60-59d464eedce8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/teams-conversational-ai/ai-ux.md](https://github.com/MicrosoftDocs/msteams-docs/blob/787776a134a6148ebe18c0e0945ac22da22b8be0/msteams-platform%2Fbots%2Fhow-to%2Fteams-conversational-ai%2Fai-ux.md) | 90 | 33 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/841075df-e206-4d9e-8f04-2269d31fe978) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2025-01-17 11:18 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1734580a8564c6722fa201193ddb749c90d0ca3a/msteams-platform%2FTOC.yml) | 92 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/946c33a1-2ec0-4d84-830f-3c6da1f424e8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/teams-conversational-ai/ai-ux.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1734580a8564c6722fa201193ddb749c90d0ca3a/msteams-platform%2Fbots%2Fhow-to%2Fteams-conversational-ai%2Fai-ux.md) | 90 | 33 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3a138d4f-4603-4f49-ba3d-febc4f2190af) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2025-01-17 11:42 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/d7942f9c7e00b0de2cf118fef08479d05d01afc4/msteams-platform%2FTOC.yml) | 92 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5aec2901-fa0b-4b17-8fc7-3efbc63ef5ce) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/teams-conversational-ai/ai-ux.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d7942f9c7e00b0de2cf118fef08479d05d01afc4/msteams-platform%2Fbots%2Fhow-to%2Fteams-conversational-ai%2Fai-ux.md) | 90 | 33 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ad5356f4-a4eb-46b2-81b8-e96f68360315) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2025-01-17 19:46 UTC, girliemac requested changes
Hi Shalini, can you mention some of the features are still in preview? It seems that Citations (in adaptive cards), Feedback, and Stream responses are under public preview.

2025-01-20 04:16 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1da707092104cd1f3a0bf9aa099e19c7f42e8a93/msteams-platform%2FTOC.yml) | 92 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/57635207-7d81-4ef8-9b58-e1aa4a1e93e4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/teams-conversational-ai/ai-ux.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1da707092104cd1f3a0bf9aa099e19c7f42e8a93/msteams-platform%2Fbots%2Fhow-to%2Fteams-conversational-ai%2Fai-ux.md) | 90 | 33 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/11981be5-8d59-4f27-9f09-473c031d072b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2025-01-20 04:54 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/f46cd7466e39177ad2c9d75ad0a28b4ec6131498/msteams-platform%2FTOC.yml) | 92 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/788ea2be-8b11-464a-8f9a-b7e1f0903bc6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/teams-conversational-ai/ai-ux.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f46cd7466e39177ad2c9d75ad0a28b4ec6131498/msteams-platform%2Fbots%2Fhow-to%2Fteams-conversational-ai%2Fai-ux.md) | 90 | 33 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3ff096b4-788d-4b9b-b461-794051c8ffd6) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2025-01-21 05:56 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/72fa0cedb6b500d39739fda1d86ed39c79c06e4a/msteams-platform%2FTOC.yml) | 92 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/42ce9bbb-0fd2-4dd3-84d2-0caf70967954) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/teams-conversational-ai/ai-ux.md](https://github.com/MicrosoftDocs/msteams-docs/blob/72fa0cedb6b500d39739fda1d86ed39c79c06e4a/msteams-platform%2Fbots%2Fhow-to%2Fteams-conversational-ai%2Fai-ux.md) | 90 | 33 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7bb730f5-2faa-4246-bdb9-41740469d627) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2025-01-22 03:52 UTC, girliemac approved these changes

2025-01-24 22:22 UTC, erikadoyle reviewed
Nice improvements! I know this is not related to your changes, but while you're in the source, there are a couple of errors in the app manifest snippet:

- "registrationInfo" object (and child properties): This is not part of the public schema (neither PP or GA) and should be removed from the snippet.
- "copilotExtensions" / "customEngineCopilots": These have been renamed to "copilotAgents" and "customEngineAgents". See [copilotAgents](https://learn.microsoft.com/en-us/microsoft-365/extensibility/schema/root-copilot-agents?view=m365-app-prev&tabs=syntax) reference for details

2025-01-27 08:49 UTC, v-shalinir commented
@erikadoyle @surbhigupta12 As it's a manifest file update and we'll need more approvals for it, we will take it up in a separate PR.

2025-02-03 06:21 UTC, Wajeed-msft approved these changes

2025-02-03 11:44 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/44bcae98da0d6f749bc60d86eb2602e27762a43c/msteams-platform%2FTOC.yml) | 92 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ae90b9bc-91bc-41c6-a5cd-557dc1242290) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/teams-conversational-ai/ai-ux.md](https://github.com/MicrosoftDocs/msteams-docs/blob/44bcae98da0d6f749bc60d86eb2602e27762a43c/msteams-platform%2Fbots%2Fhow-to%2Fteams-conversational-ai%2Fai-ux.md) | 90 | 33 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/246bc3bb-a82d-4399-8030-33cafd18226d) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2025-02-03 13:05 UTC, surbhigupta12 approved these changes

2025-02-03 13:07 UTC, merged