Changes description of the samples
MicrosoftDocs/msteams-docs pull request #11975
Opened 2024-12-27 04:30 UTC by Pawank-MSFT

The description of the samples needs to be revised for clarity and conciseness, aligning it with the format used in the sample repository.

2024-12-27 04:31 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/51adc6a3ffcb7c5d44d7ee5e35bb01cce36f01cc/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1f15e114-8cc8-470f-a6ab-a098dcd1c629) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-anonymous-user.md](https://github.com/MicrosoftDocs/msteams-docs/blob/51adc6a3ffcb7c5d44d7ee5e35bb01cce36f01cc/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-anonymous-user.md) | 89 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8366c997-a374-49c9-a2d7-4f6a39d989a1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-teams-meeting-stage.md](https://github.com/MicrosoftDocs/msteams-docs/blob/51adc6a3ffcb7c5d44d7ee5e35bb01cce36f01cc/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-teams-meeting-stage.md) | 92 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f17b5237-af58-4af5-b6eb-6fb42c709076) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-extensible-conversation-for-meeting-chat.md](https://github.com/MicrosoftDocs/msteams-docs/blob/51adc6a3ffcb7c5d44d7ee5e35bb01cce36f01cc/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-extensible-conversation-for-meeting-chat.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/79447ebf-9427-4802-a45e-fd76fda6421e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/51adc6a3ffcb7c5d44d7ee5e35bb01cce36f01cc/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 88 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0b19927e-20f5-456f-bc36-fd2e744c1a4f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-concepts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/51adc6a3ffcb7c5d44d7ee5e35bb01cce36f01cc/msteams-platform%2Fbots%2Fbot-concepts.md) | 91 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/908a2785-be67-4ca6-8ede-b7e6283e793a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/51adc6a3ffcb7c5d44d7ee5e35bb01cce36f01cc/msteams-platform%2Fbots%2Fbot-features.md) | 91 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ce25f3c1-916e-4892-a946-6515d2659bf2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/calls-and-meetings/registering-calling-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/51adc6a3ffcb7c5d44d7ee5e35bb01cce36f01cc/msteams-platform%2Fbots%2Fcalls-and-meetings%2Fregistering-calling-bot.md) | 90 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/282acce8-e324-4029-8848-3c6734f15e71) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/add-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/51adc6a3ffcb7c5d44d7ee5e35bb01cce36f01cc/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fadd-authentication.md) | 91 | 59 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6606f705-a9cd-4ef1-8e57-d350d43a74de) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/bot-sso-code.md](https://github.com/MicrosoftDocs/msteams-docs/blob/51adc6a3ffcb7c5d44d7ee5e35bb01cce36f01cc/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-code.md) | 86 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4f3ccc68-9335-4992-ad73-25c5904b9e2c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bot-configuration-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/51adc6a3ffcb7c5d44d7ee5e35bb01cce36f01cc/msteams-platform%2Fbots%2Fhow-to%2Fbot-configuration-experience.md) | 92 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c0ee362c-e712-4a41-884e-01b04b10df0c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/51adc6a3ffcb7c5d44d7ee5e35bb01cce36f01cc/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 81 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7288c3be-f799-4933-a8ef-2e0fc9847bb0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/prompt-suggestions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/51adc6a3ffcb7c5d44d7ee5e35bb01cce36f01cc/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fprompt-suggestions.md) | 93 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/96c2e5b2-e6fa-4ca9-905d-da591def7cfe) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/51adc6a3ffcb7c5d44d7ee5e35bb01cce36f01cc/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 89 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7f61c6ba-e4a1-4fb4-a5cb-594b6a1e4fca) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/51adc6a3ffcb7c5d44d7ee5e35bb01cce36f01cc/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsubscribe-to-conversation-events.md) | 89 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/41138457-9682-4309-ae28-fbcf65316d37) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/update-and-delete-bot-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/51adc6a3ffcb7c5d44d7ee5e35bb01cce36f01cc/msteams-platform%2Fbots%2Fhow-to%2Fupdate-and-delete-bot-messages.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f09cc555-5bda-4a06-acbd-05097356038d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/streaming-ux.md](https://github.com/MicrosoftDocs/msteams-docs/blob/51adc6a3ffcb7c5d44d7ee5e35bb01cce36f01cc/msteams-platform%2Fbots%2Fstreaming-ux.md) | 89 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5145fd7a-518c-4aee-aec1-496acece505d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/authentication/nested-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/51adc6a3ffcb7c5d44d7ee5e35bb01cce36f01cc/msteams-platform%2Fconcepts%2Fauthentication%2Fnested-authentication.md) | 92 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/577fad2f-f106-43aa-b57e-618f7808b8bc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/51adc6a3ffcb7c5d44d7ee5e35bb01cce36f01cc/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fapps-localization.md) | 88 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/de79e96c-263b-4fe4-872f-c69da1358c88) | [:white_check_mark [...]

2024-12-27 05:34 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5a9e0d5eccab7dbf90d7cfd53ec730326cc122e2/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/26c9e61c-90f3-46de-969b-903ec93e90a9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-anonymous-user.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5a9e0d5eccab7dbf90d7cfd53ec730326cc122e2/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-anonymous-user.md) | 89 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3b7bea1d-5e02-4685-8c9c-f5815182c85d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-teams-meeting-stage.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5a9e0d5eccab7dbf90d7cfd53ec730326cc122e2/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-teams-meeting-stage.md) | 92 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f4447a4d-dffb-4664-9c07-ea2902361848) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-extensible-conversation-for-meeting-chat.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5a9e0d5eccab7dbf90d7cfd53ec730326cc122e2/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-extensible-conversation-for-meeting-chat.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a9d1cefb-5830-43b1-95b3-a3029c7ad46b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5a9e0d5eccab7dbf90d7cfd53ec730326cc122e2/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 88 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d248c710-18bb-48ee-bdce-7dab09a60e11) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-concepts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5a9e0d5eccab7dbf90d7cfd53ec730326cc122e2/msteams-platform%2Fbots%2Fbot-concepts.md) | 91 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/309755f9-92da-4644-a56c-376e741f6bea) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5a9e0d5eccab7dbf90d7cfd53ec730326cc122e2/msteams-platform%2Fbots%2Fbot-features.md) | 91 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b499756c-c5cf-43be-90fe-270d609717d6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/calls-and-meetings/registering-calling-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5a9e0d5eccab7dbf90d7cfd53ec730326cc122e2/msteams-platform%2Fbots%2Fcalls-and-meetings%2Fregistering-calling-bot.md) | 90 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5b12f155-4d0d-492d-ae5b-1ea0a5f604b1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/add-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5a9e0d5eccab7dbf90d7cfd53ec730326cc122e2/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fadd-authentication.md) | 91 | 59 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/58f0fb7c-3320-4f95-97d7-f88baaa66fe1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/bot-sso-code.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5a9e0d5eccab7dbf90d7cfd53ec730326cc122e2/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-code.md) | 86 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fe768fc1-fa1a-4334-a6cb-c0fea75bc030) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bot-configuration-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5a9e0d5eccab7dbf90d7cfd53ec730326cc122e2/msteams-platform%2Fbots%2Fhow-to%2Fbot-configuration-experience.md) | 92 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c1f6cb13-f779-470f-bd84-90252f93265e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5a9e0d5eccab7dbf90d7cfd53ec730326cc122e2/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 81 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/eabcc99c-ca5f-4932-983d-b703b8c463d1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/prompt-suggestions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5a9e0d5eccab7dbf90d7cfd53ec730326cc122e2/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fprompt-suggestions.md) | 93 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/835c43bf-0bab-43d6-9f23-83dbac8c7785) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5a9e0d5eccab7dbf90d7cfd53ec730326cc122e2/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 89 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8c546fe3-d35e-430a-ab8c-252e48007a6a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5a9e0d5eccab7dbf90d7cfd53ec730326cc122e2/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsubscribe-to-conversation-events.md) | 89 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/553b199d-dec3-4452-ab59-ef181f7aaaf2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/update-and-delete-bot-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5a9e0d5eccab7dbf90d7cfd53ec730326cc122e2/msteams-platform%2Fbots%2Fhow-to%2Fupdate-and-delete-bot-messages.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8d482f7c-72ab-4a69-9d25-a7f36f9d419a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/streaming-ux.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5a9e0d5eccab7dbf90d7cfd53ec730326cc122e2/msteams-platform%2Fbots%2Fstreaming-ux.md) | 89 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7cea9fea-9baa-49f6-bab9-e9f188d8bbc1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/authentication/nested-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5a9e0d5eccab7dbf90d7cfd53ec730326cc122e2/msteams-platform%2Fconcepts%2Fauthentication%2Fnested-authentication.md) | 92 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f85e6ddb-1341-4994-b688-19e9a8648ca6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5a9e0d5eccab7dbf90d7cfd53ec730326cc122e2/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fapps-localization.md) | 88 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f90fb14b-952e-46a8-9485-6ed9354f1fb4) | [:white_check_mark [...]

2024-12-27 12:06 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b7f8a2b8bbb6e5e9ce0cd222722ff162f046848d/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/14960041-134d-4813-9223-84690e8759bc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-anonymous-user.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b7f8a2b8bbb6e5e9ce0cd222722ff162f046848d/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-anonymous-user.md) | 89 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e04ab353-7956-49e3-ae4d-930a31b7fe16) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-teams-meeting-stage.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b7f8a2b8bbb6e5e9ce0cd222722ff162f046848d/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-teams-meeting-stage.md) | 92 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dfba2e44-e2bb-4305-976c-52a5e6f0877b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-extensible-conversation-for-meeting-chat.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b7f8a2b8bbb6e5e9ce0cd222722ff162f046848d/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-extensible-conversation-for-meeting-chat.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fc41c5f5-104b-463c-b30f-e585ab8e20a1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b7f8a2b8bbb6e5e9ce0cd222722ff162f046848d/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 88 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4394ba57-1b27-4667-ae9d-a449c96e7b69) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-concepts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b7f8a2b8bbb6e5e9ce0cd222722ff162f046848d/msteams-platform%2Fbots%2Fbot-concepts.md) | 91 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3f8f4daf-4df7-4887-a5c0-fd06acd8d03e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b7f8a2b8bbb6e5e9ce0cd222722ff162f046848d/msteams-platform%2Fbots%2Fbot-features.md) | 91 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/70ea9c5e-7814-4d89-acc1-73d0d6ab7ceb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/calls-and-meetings/registering-calling-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b7f8a2b8bbb6e5e9ce0cd222722ff162f046848d/msteams-platform%2Fbots%2Fcalls-and-meetings%2Fregistering-calling-bot.md) | 90 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/09a108cb-8ded-4a3d-b17c-a545019d704e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/add-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b7f8a2b8bbb6e5e9ce0cd222722ff162f046848d/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fadd-authentication.md) | 91 | 59 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/403a7ad6-6fc9-4000-bd11-fc0759ed3006) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/bot-sso-code.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b7f8a2b8bbb6e5e9ce0cd222722ff162f046848d/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-code.md) | 86 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/54c477c0-8a29-4f3f-a220-9b3a5b2fda3b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bot-configuration-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b7f8a2b8bbb6e5e9ce0cd222722ff162f046848d/msteams-platform%2Fbots%2Fhow-to%2Fbot-configuration-experience.md) | 92 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/011b21eb-af3d-4da3-9f59-4ec4058a3ca8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b7f8a2b8bbb6e5e9ce0cd222722ff162f046848d/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 81 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a3c1e3bc-7d5f-43a5-a363-f3996b8ddec8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/prompt-suggestions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b7f8a2b8bbb6e5e9ce0cd222722ff162f046848d/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fprompt-suggestions.md) | 93 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/88dfcde8-d0f3-4478-ae26-44a354edfe37) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b7f8a2b8bbb6e5e9ce0cd222722ff162f046848d/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 89 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/13f3229b-7ffc-40f4-a3a7-12087b9435f8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b7f8a2b8bbb6e5e9ce0cd222722ff162f046848d/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsubscribe-to-conversation-events.md) | 89 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1897cad5-521b-45e8-a36a-dce97bf487da) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/update-and-delete-bot-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b7f8a2b8bbb6e5e9ce0cd222722ff162f046848d/msteams-platform%2Fbots%2Fhow-to%2Fupdate-and-delete-bot-messages.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3ce62508-9d1f-41d3-b7bf-0436c96bd079) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/streaming-ux.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b7f8a2b8bbb6e5e9ce0cd222722ff162f046848d/msteams-platform%2Fbots%2Fstreaming-ux.md) | 89 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/693fc7c7-9a63-462d-9f1f-d4c55e5b7372) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/authentication/nested-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b7f8a2b8bbb6e5e9ce0cd222722ff162f046848d/msteams-platform%2Fconcepts%2Fauthentication%2Fnested-authentication.md) | 92 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1835f98d-e471-408b-9c7f-868bd8d037a0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b7f8a2b8bbb6e5e9ce0cd222722ff162f046848d/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fapps-localization.md) | 88 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1bce8af6-ea94-46cf-af81-af87a650d37f) | [:white_check_mark [...]

2024-12-31 08:53 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fcf1c3914b1a067cc861d7a425f729cf0a7f81f6/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 86 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6b32d141-b606-49e1-8b6f-639b9c16dbe0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-anonymous-user.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fcf1c3914b1a067cc861d7a425f729cf0a7f81f6/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-anonymous-user.md) | 89 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bd55137b-7aed-45bb-8fcc-d2965ddeb175) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-teams-meeting-stage.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fcf1c3914b1a067cc861d7a425f729cf0a7f81f6/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-teams-meeting-stage.md) | 92 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/be0d1d9b-040c-431e-ab00-419cfee1ae36) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-extensible-conversation-for-meeting-chat.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fcf1c3914b1a067cc861d7a425f729cf0a7f81f6/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-extensible-conversation-for-meeting-chat.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7bf4487f-8d9f-43d2-9177-8a63173e7863) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fcf1c3914b1a067cc861d7a425f729cf0a7f81f6/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 88 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ee70bc4c-8966-40cb-83da-e2989d4bba0e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-concepts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fcf1c3914b1a067cc861d7a425f729cf0a7f81f6/msteams-platform%2Fbots%2Fbot-concepts.md) | 91 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/58f9e89b-76a7-4c85-86bb-0abc6c57b828) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fcf1c3914b1a067cc861d7a425f729cf0a7f81f6/msteams-platform%2Fbots%2Fbot-features.md) | 91 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9c9f42e8-17a3-4d74-8c16-a98bc6b765e8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/calls-and-meetings/registering-calling-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fcf1c3914b1a067cc861d7a425f729cf0a7f81f6/msteams-platform%2Fbots%2Fcalls-and-meetings%2Fregistering-calling-bot.md) | 90 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f9e03af7-5339-41e1-bec2-6282d61b7cb0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/add-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fcf1c3914b1a067cc861d7a425f729cf0a7f81f6/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fadd-authentication.md) | 91 | 59 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/af7f729f-9e47-459d-9a09-4c2157d82b25) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/bot-sso-code.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fcf1c3914b1a067cc861d7a425f729cf0a7f81f6/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-code.md) | 86 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/465c2bfd-1338-46ed-b88a-921bc0d73b17) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bot-configuration-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fcf1c3914b1a067cc861d7a425f729cf0a7f81f6/msteams-platform%2Fbots%2Fhow-to%2Fbot-configuration-experience.md) | 92 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d9cf2e9d-856b-44cf-bf3e-21fece9a4db3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fcf1c3914b1a067cc861d7a425f729cf0a7f81f6/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 81 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/96d21500-aa35-4b09-af49-cb4c04482c56) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/prompt-suggestions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fcf1c3914b1a067cc861d7a425f729cf0a7f81f6/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fprompt-suggestions.md) | 93 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c6d331b9-4bfe-4d12-9f4f-a240e497204a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fcf1c3914b1a067cc861d7a425f729cf0a7f81f6/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 89 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2989a323-879d-4aa9-bad4-02bc8a3e9308) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fcf1c3914b1a067cc861d7a425f729cf0a7f81f6/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsubscribe-to-conversation-events.md) | 89 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4836af36-3be1-4b5a-b40c-56b991c58f8f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/update-and-delete-bot-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fcf1c3914b1a067cc861d7a425f729cf0a7f81f6/msteams-platform%2Fbots%2Fhow-to%2Fupdate-and-delete-bot-messages.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fe8221e0-7cb1-4c9e-8613-70454552e4f3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/streaming-ux.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fcf1c3914b1a067cc861d7a425f729cf0a7f81f6/msteams-platform%2Fbots%2Fstreaming-ux.md) | 89 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9bf4f834-2aba-41c0-b1fb-eba9e2274bbf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/authentication/nested-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fcf1c3914b1a067cc861d7a425f729cf0a7f81f6/msteams-platform%2Fconcepts%2Fauthentication%2Fnested-authentication.md) | 92 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/48cf3c25-df20-49ec-80e0-0372a26d2e17) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fcf1c3914b1a067cc861d7a425f729cf0a7f81f6/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fapps-localization.md) | 88 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/912914af-1c2f-46ec-9d7c-a6e811ce9e87) | [:white_check_mark [...]

2025-01-02 07:25 UTC, Wajeed-msft requested changes

2025-01-02 07:25 UTC, Wajeed-msft commented on msteams-platform/apps-in-teams-meetings/build-apps-for-teams-meeting-stage.md
>  * Use **Share** and not **Present** or **Screenshare**, if your experience offers simple sharing of app content to the stage. This sets the right expectation for users as **Share** consistently means
What was changed here? Can we take the latest from main branch and check?

2025-01-02 11:27 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/59d95fc08fc986cbfcd8b7a6b914c5b445b31531/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 86 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/31195f95-ae7d-4912-a5f5-87a39db6c955) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-anonymous-user.md](https://github.com/MicrosoftDocs/msteams-docs/blob/59d95fc08fc986cbfcd8b7a6b914c5b445b31531/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-anonymous-user.md) | 87 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e86134ad-579e-4cd7-8e47-ac68693077b8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-teams-meeting-stage.md](https://github.com/MicrosoftDocs/msteams-docs/blob/59d95fc08fc986cbfcd8b7a6b914c5b445b31531/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-teams-meeting-stage.md) | 91 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ba4c0e49-4183-45d0-a127-3f46f028af52) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-extensible-conversation-for-meeting-chat.md](https://github.com/MicrosoftDocs/msteams-docs/blob/59d95fc08fc986cbfcd8b7a6b914c5b445b31531/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-extensible-conversation-for-meeting-chat.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ca40e1ab-f567-4e17-a1c1-e97057856877) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/59d95fc08fc986cbfcd8b7a6b914c5b445b31531/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 88 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/807bbb4f-2ee8-4580-b1ac-d04e26b17dae) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-concepts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/59d95fc08fc986cbfcd8b7a6b914c5b445b31531/msteams-platform%2Fbots%2Fbot-concepts.md) | 91 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e20c413b-c060-46c0-8eba-b2080fc5e1d3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/59d95fc08fc986cbfcd8b7a6b914c5b445b31531/msteams-platform%2Fbots%2Fbot-features.md) | 91 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/38d4feac-3565-4036-b529-33eebf381afe) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/calls-and-meetings/registering-calling-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/59d95fc08fc986cbfcd8b7a6b914c5b445b31531/msteams-platform%2Fbots%2Fcalls-and-meetings%2Fregistering-calling-bot.md) | 85 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/41eea00b-6512-4153-aa54-27a0ed1b8a6d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/add-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/59d95fc08fc986cbfcd8b7a6b914c5b445b31531/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fadd-authentication.md) | 89 | 71 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/eded45b3-b1fe-48b4-bcd1-dc186ed8c8a5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/bot-sso-code.md](https://github.com/MicrosoftDocs/msteams-docs/blob/59d95fc08fc986cbfcd8b7a6b914c5b445b31531/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-code.md) | 84 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/83e02663-4301-45c6-9c40-e99617a3d96a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bot-configuration-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/59d95fc08fc986cbfcd8b7a6b914c5b445b31531/msteams-platform%2Fbots%2Fhow-to%2Fbot-configuration-experience.md) | 91 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f9397e84-07be-4135-978b-6952197aca22) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/59d95fc08fc986cbfcd8b7a6b914c5b445b31531/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 81 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7c4d8030-4e63-4b0a-b901-277b1f19554e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/prompt-suggestions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/59d95fc08fc986cbfcd8b7a6b914c5b445b31531/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fprompt-suggestions.md) | 90 | 40 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fcdf0d0a-7aa3-4b9d-ac52-22a7bfdcdbfc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/59d95fc08fc986cbfcd8b7a6b914c5b445b31531/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 89 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/35c2233c-08fb-411c-b987-6e736b11ac8d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/59d95fc08fc986cbfcd8b7a6b914c5b445b31531/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsubscribe-to-conversation-events.md) | 88 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2737400f-8cd0-449e-b705-6b172028ae80) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/update-and-delete-bot-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/59d95fc08fc986cbfcd8b7a6b914c5b445b31531/msteams-platform%2Fbots%2Fhow-to%2Fupdate-and-delete-bot-messages.md) | 91 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f4281ffb-f300-4f46-8570-856af398616d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/streaming-ux.md](https://github.com/MicrosoftDocs/msteams-docs/blob/59d95fc08fc986cbfcd8b7a6b914c5b445b31531/msteams-platform%2Fbots%2Fstreaming-ux.md) | 88 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2bc9a59f-c4c0-4e58-af68-919445bf2202) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/authentication/nested-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/59d95fc08fc986cbfcd8b7a6b914c5b445b31531/msteams-platform%2Fconcepts%2Fauthentication%2Fnested-authentication.md) | 91 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/580968ef-de1a-46b3-8d75-09b120e30cfd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/59d95fc08fc986cbfcd8b7a6b914c5b445b31531/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fapps-localization.md) | 88 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/294f3378-70c5-4d4f-bad6-080c6bc8f296) | [:white_check_mark [...]

2025-01-02 12:20 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0c31876449e6823ae94d958ee19b314caa4859ee/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 86 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3169bdeb-4a1c-4740-886d-68aab35d81c8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-anonymous-user.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0c31876449e6823ae94d958ee19b314caa4859ee/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-anonymous-user.md) | 87 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1673f1bd-e444-4917-bc02-dfa688ff153e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-teams-meeting-stage.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0c31876449e6823ae94d958ee19b314caa4859ee/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-teams-meeting-stage.md) | 91 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6a5fed61-4267-40a9-be6f-e75e324a5070) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-extensible-conversation-for-meeting-chat.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0c31876449e6823ae94d958ee19b314caa4859ee/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-extensible-conversation-for-meeting-chat.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/809bf4f1-55e2-4ea8-8322-3bfe27ece2ba) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0c31876449e6823ae94d958ee19b314caa4859ee/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 88 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/86fc718a-c960-4fd1-a96e-648d9954f8d4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-concepts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0c31876449e6823ae94d958ee19b314caa4859ee/msteams-platform%2Fbots%2Fbot-concepts.md) | 91 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f0228403-5265-4b26-828c-7a19b296909d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0c31876449e6823ae94d958ee19b314caa4859ee/msteams-platform%2Fbots%2Fbot-features.md) | 91 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a7a0afee-7920-4c47-8a61-1c8366a162e7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/calls-and-meetings/registering-calling-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0c31876449e6823ae94d958ee19b314caa4859ee/msteams-platform%2Fbots%2Fcalls-and-meetings%2Fregistering-calling-bot.md) | 85 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ee91f104-cb13-4f32-ba87-5bcc357d3d32) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/add-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0c31876449e6823ae94d958ee19b314caa4859ee/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fadd-authentication.md) | 89 | 71 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b14e0518-9e7b-43a3-81fe-79f9c6fe187d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/bot-sso-code.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0c31876449e6823ae94d958ee19b314caa4859ee/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-code.md) | 84 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bdeb19b4-ca62-4f08-a474-8e1926190d65) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bot-configuration-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0c31876449e6823ae94d958ee19b314caa4859ee/msteams-platform%2Fbots%2Fhow-to%2Fbot-configuration-experience.md) | 91 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/078a5a58-f031-4b3e-80d0-14db8b3c8b13) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0c31876449e6823ae94d958ee19b314caa4859ee/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 81 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0a90a310-675a-46db-b77f-dd84ac9c4e52) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/prompt-suggestions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0c31876449e6823ae94d958ee19b314caa4859ee/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fprompt-suggestions.md) | 90 | 40 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/28124375-670f-4ab3-8ff7-806eba2978a9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0c31876449e6823ae94d958ee19b314caa4859ee/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 89 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6e92f12f-f300-4b8e-875c-aea67082d0e8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0c31876449e6823ae94d958ee19b314caa4859ee/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsubscribe-to-conversation-events.md) | 88 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a81ac24b-1d0e-42c1-9a59-efe535f49b85) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/update-and-delete-bot-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0c31876449e6823ae94d958ee19b314caa4859ee/msteams-platform%2Fbots%2Fhow-to%2Fupdate-and-delete-bot-messages.md) | 91 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5d1a05b0-ac55-4b56-a218-e99f3d09c59c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/streaming-ux.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0c31876449e6823ae94d958ee19b314caa4859ee/msteams-platform%2Fbots%2Fstreaming-ux.md) | 88 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/be631b38-2a57-4912-8992-718f71862d71) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/authentication/nested-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0c31876449e6823ae94d958ee19b314caa4859ee/msteams-platform%2Fconcepts%2Fauthentication%2Fnested-authentication.md) | 91 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/967200b8-ca43-4b68-b0b8-b661ae3252b7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0c31876449e6823ae94d958ee19b314caa4859ee/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fapps-localization.md) | 88 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fdd30749-9046-49ea-a50d-4162e6c0771b) | [:white_check_mark [...]

2025-01-02 14:34 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ab9b0ae6bf2d3fb9bfe2289eb089f78e2fa4308a/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 86 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dbf610b2-4744-4811-aea1-e16d7c5d32cd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-anonymous-user.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ab9b0ae6bf2d3fb9bfe2289eb089f78e2fa4308a/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-anonymous-user.md) | 87 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/54da096f-2cbf-4b3c-80ba-3be50c9272f4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-teams-meeting-stage.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ab9b0ae6bf2d3fb9bfe2289eb089f78e2fa4308a/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-teams-meeting-stage.md) | 91 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/83067c32-075b-4f0a-9940-eefd9c406110) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-extensible-conversation-for-meeting-chat.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ab9b0ae6bf2d3fb9bfe2289eb089f78e2fa4308a/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-extensible-conversation-for-meeting-chat.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/921b0f9f-a05f-4ecb-b2df-5f0056e230ee) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ab9b0ae6bf2d3fb9bfe2289eb089f78e2fa4308a/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 88 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4c0d43e8-58c5-4856-b8d9-39da3bc2a736) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-concepts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ab9b0ae6bf2d3fb9bfe2289eb089f78e2fa4308a/msteams-platform%2Fbots%2Fbot-concepts.md) | 91 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/68b00e74-6508-42e9-bdaf-c278611ebe66) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ab9b0ae6bf2d3fb9bfe2289eb089f78e2fa4308a/msteams-platform%2Fbots%2Fbot-features.md) | 91 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/925514d1-3783-406a-a4bf-8a4d4db76748) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/calls-and-meetings/registering-calling-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ab9b0ae6bf2d3fb9bfe2289eb089f78e2fa4308a/msteams-platform%2Fbots%2Fcalls-and-meetings%2Fregistering-calling-bot.md) | 85 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e7911f05-fcb2-4fb9-9a08-01ba7c5032e1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/add-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ab9b0ae6bf2d3fb9bfe2289eb089f78e2fa4308a/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fadd-authentication.md) | 89 | 71 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cdcd8b8f-7450-4791-a8bb-599d22783cd9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/bot-sso-code.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ab9b0ae6bf2d3fb9bfe2289eb089f78e2fa4308a/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-code.md) | 84 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/24e976a1-a07c-4af7-bde1-5ee7c8bcf417) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bot-configuration-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ab9b0ae6bf2d3fb9bfe2289eb089f78e2fa4308a/msteams-platform%2Fbots%2Fhow-to%2Fbot-configuration-experience.md) | 91 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/137fa6c5-768c-4209-a15a-8be2defc276b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ab9b0ae6bf2d3fb9bfe2289eb089f78e2fa4308a/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 81 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/48f3984a-d905-4137-a763-1fa4f03d014f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/prompt-suggestions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ab9b0ae6bf2d3fb9bfe2289eb089f78e2fa4308a/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fprompt-suggestions.md) | 90 | 40 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/595a3b19-78d7-4858-b0e6-727145e730a4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ab9b0ae6bf2d3fb9bfe2289eb089f78e2fa4308a/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 89 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8b0bcd9a-d6cf-4ce3-9744-c331e5d3a983) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ab9b0ae6bf2d3fb9bfe2289eb089f78e2fa4308a/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsubscribe-to-conversation-events.md) | 88 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f5c75af8-73f4-417c-8d7d-7ee95b8ad2de) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/update-and-delete-bot-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ab9b0ae6bf2d3fb9bfe2289eb089f78e2fa4308a/msteams-platform%2Fbots%2Fhow-to%2Fupdate-and-delete-bot-messages.md) | 91 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bc8e04dc-cbd1-4e78-8edc-978101b003e8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/streaming-ux.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ab9b0ae6bf2d3fb9bfe2289eb089f78e2fa4308a/msteams-platform%2Fbots%2Fstreaming-ux.md) | 88 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e1159804-f4bc-4721-a391-773a7f78f415) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/authentication/nested-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ab9b0ae6bf2d3fb9bfe2289eb089f78e2fa4308a/msteams-platform%2Fconcepts%2Fauthentication%2Fnested-authentication.md) | 91 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e54c4ec3-8a4b-4d03-8d78-a3e18579df2b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ab9b0ae6bf2d3fb9bfe2289eb089f78e2fa4308a/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fapps-localization.md) | 88 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3a1a5fda-5683-449c-9e14-dfb0798bcde2) | [:white_check_mark [...]

2025-01-02 14:39 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9f4548cfb8dc095f3827461d3f88f6c203f2e4a0/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 86 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7c2f36eb-fa23-459f-a091-62a2db69c08a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-anonymous-user.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9f4548cfb8dc095f3827461d3f88f6c203f2e4a0/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-anonymous-user.md) | 87 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3f7a72a3-4b02-42ca-8920-79551a3db3f8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-extensible-conversation-for-meeting-chat.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9f4548cfb8dc095f3827461d3f88f6c203f2e4a0/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-extensible-conversation-for-meeting-chat.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ab62fcc7-b414-47a4-8dd7-865fd9521271) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9f4548cfb8dc095f3827461d3f88f6c203f2e4a0/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 88 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/76dbc089-3e28-4502-9b01-f09ee1cdc626) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-concepts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9f4548cfb8dc095f3827461d3f88f6c203f2e4a0/msteams-platform%2Fbots%2Fbot-concepts.md) | 91 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/604926fb-5fa4-479c-a43d-660972e5ca47) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9f4548cfb8dc095f3827461d3f88f6c203f2e4a0/msteams-platform%2Fbots%2Fbot-features.md) | 91 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b8746580-d014-4d85-9579-9259728b2386) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/calls-and-meetings/registering-calling-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9f4548cfb8dc095f3827461d3f88f6c203f2e4a0/msteams-platform%2Fbots%2Fcalls-and-meetings%2Fregistering-calling-bot.md) | 85 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3f850365-4d00-4e00-a2d9-109fc5080886) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/add-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9f4548cfb8dc095f3827461d3f88f6c203f2e4a0/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fadd-authentication.md) | 89 | 71 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4b621902-3faa-4373-9c3e-849a3aa6d010) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/bot-sso-code.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9f4548cfb8dc095f3827461d3f88f6c203f2e4a0/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-code.md) | 84 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/174bd9f9-6de3-4dac-82ee-c097f086f94b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bot-configuration-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9f4548cfb8dc095f3827461d3f88f6c203f2e4a0/msteams-platform%2Fbots%2Fhow-to%2Fbot-configuration-experience.md) | 91 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c2f260d3-6141-4531-ba31-6123a23d82b7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9f4548cfb8dc095f3827461d3f88f6c203f2e4a0/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 81 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a27f83b7-0dd1-4260-bc33-80aec21a71ca) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/prompt-suggestions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9f4548cfb8dc095f3827461d3f88f6c203f2e4a0/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fprompt-suggestions.md) | 90 | 40 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9ace20b1-3ad2-490f-96eb-555637a5eedf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9f4548cfb8dc095f3827461d3f88f6c203f2e4a0/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 89 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e2f2f73f-5256-4579-97a6-c73b361efb4f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9f4548cfb8dc095f3827461d3f88f6c203f2e4a0/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsubscribe-to-conversation-events.md) | 88 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/beba4684-e68f-42e8-933c-094bb2853322) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/update-and-delete-bot-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9f4548cfb8dc095f3827461d3f88f6c203f2e4a0/msteams-platform%2Fbots%2Fhow-to%2Fupdate-and-delete-bot-messages.md) | 91 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/787c8650-5f15-4da7-95f1-29061e54733f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/streaming-ux.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9f4548cfb8dc095f3827461d3f88f6c203f2e4a0/msteams-platform%2Fbots%2Fstreaming-ux.md) | 88 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/51803095-3f11-4dc8-b32b-3c92289b10c8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/authentication/nested-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9f4548cfb8dc095f3827461d3f88f6c203f2e4a0/msteams-platform%2Fconcepts%2Fauthentication%2Fnested-authentication.md) | 91 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7eb8f8ad-dd88-4f69-8cca-b7d1aa77323c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9f4548cfb8dc095f3827461d3f88f6c203f2e4a0/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fapps-localization.md) | 88 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5cffb8a3-c2bd-4fd5-8be7-ba182171eb3b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-application.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9f4548cfb8dc095f3827461d3f88f6c203f2e4a0/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-application.md) | 92 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d38add6c-aa80-40b8-af12-0629ad6b78b3) | [:white_check_mark:](# "Successfully pro [...]

2025-01-02 14:45 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6cc33f3d9614901f9622ddc6d61e9da4357a6ebc/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 86 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aa700567-dd05-4255-b678-0fb00b524d90) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-anonymous-user.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6cc33f3d9614901f9622ddc6d61e9da4357a6ebc/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-anonymous-user.md) | 87 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/82f0f7b8-82f9-45aa-92dc-fdd0550ff167) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-teams-meeting-stage.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6cc33f3d9614901f9622ddc6d61e9da4357a6ebc/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-teams-meeting-stage.md) | 90 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f0b318f8-f3cc-4957-a60f-2155a53006b6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-extensible-conversation-for-meeting-chat.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6cc33f3d9614901f9622ddc6d61e9da4357a6ebc/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-extensible-conversation-for-meeting-chat.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/022a67c3-ed98-412d-b24f-578ede5ae1a3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6cc33f3d9614901f9622ddc6d61e9da4357a6ebc/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 88 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dc2aecd6-3072-4320-a893-b82fc34e0e1c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-concepts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6cc33f3d9614901f9622ddc6d61e9da4357a6ebc/msteams-platform%2Fbots%2Fbot-concepts.md) | 91 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1c819ecd-ad24-4c85-9c01-3b4fae8f15d9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6cc33f3d9614901f9622ddc6d61e9da4357a6ebc/msteams-platform%2Fbots%2Fbot-features.md) | 91 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9c034f3b-7149-48b9-af4e-e0b4ed3cdb46) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/calls-and-meetings/registering-calling-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6cc33f3d9614901f9622ddc6d61e9da4357a6ebc/msteams-platform%2Fbots%2Fcalls-and-meetings%2Fregistering-calling-bot.md) | 85 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2a1d24b3-95cd-4ac3-ad55-c904a4ad70d9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/add-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6cc33f3d9614901f9622ddc6d61e9da4357a6ebc/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fadd-authentication.md) | 89 | 71 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/46238e30-bceb-4f35-91a7-69cf3665ed15) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/bot-sso-code.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6cc33f3d9614901f9622ddc6d61e9da4357a6ebc/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-code.md) | 84 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f1450df6-2b1e-4a58-ac43-b2e00506ca96) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bot-configuration-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6cc33f3d9614901f9622ddc6d61e9da4357a6ebc/msteams-platform%2Fbots%2Fhow-to%2Fbot-configuration-experience.md) | 91 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/722cef88-97f0-42ae-bb10-c4209a623282) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6cc33f3d9614901f9622ddc6d61e9da4357a6ebc/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 81 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ca00dfb8-f8ef-45c3-ab2c-58f415e64984) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/prompt-suggestions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6cc33f3d9614901f9622ddc6d61e9da4357a6ebc/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fprompt-suggestions.md) | 90 | 40 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d7d75bf8-e84f-4169-a527-46bf15fe5fe5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6cc33f3d9614901f9622ddc6d61e9da4357a6ebc/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 89 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/32966cf2-556d-4756-b001-293974434d85) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6cc33f3d9614901f9622ddc6d61e9da4357a6ebc/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsubscribe-to-conversation-events.md) | 88 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8000f4a4-eaea-4f91-834e-7c911d35e9f8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/update-and-delete-bot-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6cc33f3d9614901f9622ddc6d61e9da4357a6ebc/msteams-platform%2Fbots%2Fhow-to%2Fupdate-and-delete-bot-messages.md) | 91 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0725b41d-67b0-41f0-87a0-9a7dade9867b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/streaming-ux.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6cc33f3d9614901f9622ddc6d61e9da4357a6ebc/msteams-platform%2Fbots%2Fstreaming-ux.md) | 88 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/70e76563-3ae1-42d3-ac33-4b539cd9bda4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/authentication/nested-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6cc33f3d9614901f9622ddc6d61e9da4357a6ebc/msteams-platform%2Fconcepts%2Fauthentication%2Fnested-authentication.md) | 91 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1d4fc53f-3972-4013-9ab6-68a59fea2734) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6cc33f3d9614901f9622ddc6d61e9da4357a6ebc/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fapps-localization.md) | 88 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2bef4891-1a71-4781-b25d-37230c39eb8f) | [:white_check_mark [...]

2025-01-02 14:47 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/57f2326bfbab3892088e0ae367c6ab52288fd110/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 86 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/37b1793e-81d0-470f-9781-9acad36a30d6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-anonymous-user.md](https://github.com/MicrosoftDocs/msteams-docs/blob/57f2326bfbab3892088e0ae367c6ab52288fd110/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-anonymous-user.md) | 87 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ad498d58-2e88-4c5c-8aa7-aaf93f1fb291) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-teams-meeting-stage.md](https://github.com/MicrosoftDocs/msteams-docs/blob/57f2326bfbab3892088e0ae367c6ab52288fd110/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-teams-meeting-stage.md) | 91 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/85ed97ad-1618-4a5b-9988-5f52adddc73a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-extensible-conversation-for-meeting-chat.md](https://github.com/MicrosoftDocs/msteams-docs/blob/57f2326bfbab3892088e0ae367c6ab52288fd110/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-extensible-conversation-for-meeting-chat.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ebf2cad1-d1ea-489e-bde2-aed6a6f14c40) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/57f2326bfbab3892088e0ae367c6ab52288fd110/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 88 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a6e38ae0-29b2-4995-b3e7-bd1b9614c496) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-concepts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/57f2326bfbab3892088e0ae367c6ab52288fd110/msteams-platform%2Fbots%2Fbot-concepts.md) | 91 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b63a421f-609e-4b77-92c8-31d4862e39c8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/57f2326bfbab3892088e0ae367c6ab52288fd110/msteams-platform%2Fbots%2Fbot-features.md) | 91 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bd6e224a-b171-49e6-9214-fdcb83c33f19) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/calls-and-meetings/registering-calling-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/57f2326bfbab3892088e0ae367c6ab52288fd110/msteams-platform%2Fbots%2Fcalls-and-meetings%2Fregistering-calling-bot.md) | 85 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8f55f8c1-dc0a-41bb-b333-bc278e9bd01c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/add-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/57f2326bfbab3892088e0ae367c6ab52288fd110/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fadd-authentication.md) | 89 | 71 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/924d0674-ed19-48e9-914f-a4e78c584abc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/bot-sso-code.md](https://github.com/MicrosoftDocs/msteams-docs/blob/57f2326bfbab3892088e0ae367c6ab52288fd110/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-code.md) | 84 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a1cd021a-4cdd-44f7-983b-bcb57ea96f74) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bot-configuration-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/57f2326bfbab3892088e0ae367c6ab52288fd110/msteams-platform%2Fbots%2Fhow-to%2Fbot-configuration-experience.md) | 91 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/15e7b8dd-cc33-4d6d-a906-992e5e4b8c83) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/57f2326bfbab3892088e0ae367c6ab52288fd110/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 81 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2d087c39-0d6d-476d-9afe-befdb913fe49) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/prompt-suggestions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/57f2326bfbab3892088e0ae367c6ab52288fd110/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fprompt-suggestions.md) | 90 | 40 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3ece7c4d-77e6-4c41-ad23-8682efb30527) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/57f2326bfbab3892088e0ae367c6ab52288fd110/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 89 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/736f5d48-b35a-42cc-8362-63521bcd7b66) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/57f2326bfbab3892088e0ae367c6ab52288fd110/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsubscribe-to-conversation-events.md) | 88 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7fc35a11-1c33-4f75-a665-9e9e3a9fdbab) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/update-and-delete-bot-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/57f2326bfbab3892088e0ae367c6ab52288fd110/msteams-platform%2Fbots%2Fhow-to%2Fupdate-and-delete-bot-messages.md) | 91 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c2163dea-c7da-446a-b1b1-642c092b9574) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/streaming-ux.md](https://github.com/MicrosoftDocs/msteams-docs/blob/57f2326bfbab3892088e0ae367c6ab52288fd110/msteams-platform%2Fbots%2Fstreaming-ux.md) | 88 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ef197cdb-debd-45ae-8d41-1f21984ed7a9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/authentication/nested-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/57f2326bfbab3892088e0ae367c6ab52288fd110/msteams-platform%2Fconcepts%2Fauthentication%2Fnested-authentication.md) | 91 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d7b8cac2-8286-4278-8ca7-7d2d700206e9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/57f2326bfbab3892088e0ae367c6ab52288fd110/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fapps-localization.md) | 88 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a5506d7d-784d-4d9e-8e34-2590998caf90) | [:white_check_mark [...]

2025-01-02 14:52 UTC, Pawank-MSFT commented on msteams-platform/apps-in-teams-meetings/build-apps-for-teams-meeting-stage.md
>  * Use **Share** and not **Present** or **Screenshare**, if your experience offers simple sharing of app content to the stage. This sets the right expectation for users as **Share** consistently means
Fixed

2025-02-26 08:46 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4d611b1c2c2a4b3fd0683a204cae996c348356ab/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6a2206cd-19bc-488c-b0d9-781155a342de) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-anonymous-user.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4d611b1c2c2a4b3fd0683a204cae996c348356ab/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-anonymous-user.md) | 87 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/833b18c0-472c-40c2-98d3-3178b79dd234) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-teams-meeting-stage.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4d611b1c2c2a4b3fd0683a204cae996c348356ab/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-teams-meeting-stage.md) | 91 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8d0460c4-48a8-4997-9456-7f4d4fea79df) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-extensible-conversation-for-meeting-chat.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4d611b1c2c2a4b3fd0683a204cae996c348356ab/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-extensible-conversation-for-meeting-chat.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b58418d0-a422-4044-9a69-b2bf949133ff) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4d611b1c2c2a4b3fd0683a204cae996c348356ab/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 88 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0b2d9187-aad5-41c3-8c06-c883bd7cb8fb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-concepts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4d611b1c2c2a4b3fd0683a204cae996c348356ab/msteams-platform%2Fbots%2Fbot-concepts.md) | 91 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6afd8186-2247-4357-92c1-fe01fc7ca2c4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4d611b1c2c2a4b3fd0683a204cae996c348356ab/msteams-platform%2Fbots%2Fbot-features.md) | 91 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f30e4927-730d-44a9-be4c-668afcfa6433) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/calls-and-meetings/registering-calling-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4d611b1c2c2a4b3fd0683a204cae996c348356ab/msteams-platform%2Fbots%2Fcalls-and-meetings%2Fregistering-calling-bot.md) | 85 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bb39b076-6f54-42df-978c-787cd7bb3fb9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/add-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4d611b1c2c2a4b3fd0683a204cae996c348356ab/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fadd-authentication.md) | 89 | 70 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/424fadc7-bbea-462c-a44d-21108e655dea) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/bot-sso-code.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4d611b1c2c2a4b3fd0683a204cae996c348356ab/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-code.md) | 84 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cda71824-620d-49e4-a99f-18e38b754e3d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bot-configuration-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4d611b1c2c2a4b3fd0683a204cae996c348356ab/msteams-platform%2Fbots%2Fhow-to%2Fbot-configuration-experience.md) | 91 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/01fe02a1-9214-4595-8173-0fb1b6e2772b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4d611b1c2c2a4b3fd0683a204cae996c348356ab/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 81 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/64a38b80-9aa2-4ab6-bd8c-eb29449102cf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/prompt-suggestions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4d611b1c2c2a4b3fd0683a204cae996c348356ab/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fprompt-suggestions.md) | 90 | 40 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a476b82f-8cbf-4098-8151-0f22649cc973) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4d611b1c2c2a4b3fd0683a204cae996c348356ab/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 90 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/99433771-fb9c-4e0d-b56e-e5baea367e4b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4d611b1c2c2a4b3fd0683a204cae996c348356ab/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsubscribe-to-conversation-events.md) | 88 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bd605d91-b35e-4a11-8e27-64a45c2005b6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/streaming-ux.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4d611b1c2c2a4b3fd0683a204cae996c348356ab/msteams-platform%2Fbots%2Fstreaming-ux.md) | 86 | 33 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a4a813ce-0585-4218-b6f9-c242bd996bd5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/authentication/nested-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4d611b1c2c2a4b3fd0683a204cae996c348356ab/msteams-platform%2Fconcepts%2Fauthentication%2Fnested-authentication.md) | 91 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a94796d7-9483-4323-9391-d0a4d939141a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4d611b1c2c2a4b3fd0683a204cae996c348356ab/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fapps-localization.md) | 88 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/84f1246b-fcd8-405e-8df4-eac2bf4fa5ef) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-application.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4d611b1c2c2a4b3fd0683a204cae996c348356ab/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-application.md) | 92 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3967eb5e-335f-4045-9a24-c955cc7073c4) | [:white_che [...]

2025-02-26 10:58 UTC, Wajeed-msft submitted a review, later dismissed

2025-03-19 06:26 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f336e5c8e379939a6d01c0f53ed0cd7838143113/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/487619d6-da04-4838-b983-4822a3355cde) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-anonymous-user.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f336e5c8e379939a6d01c0f53ed0cd7838143113/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-anonymous-user.md) | 87 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6c733ab6-7f9a-4c7a-a82e-41dc00853dec) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-teams-meeting-stage.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f336e5c8e379939a6d01c0f53ed0cd7838143113/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-teams-meeting-stage.md) | 91 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b53543a4-4be3-4db5-8c9f-e9e7ec1fe65a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-extensible-conversation-for-meeting-chat.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f336e5c8e379939a6d01c0f53ed0cd7838143113/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-extensible-conversation-for-meeting-chat.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c3e2af9d-08c2-4a09-84b9-f47fa370d284) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f336e5c8e379939a6d01c0f53ed0cd7838143113/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 88 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6f45901f-562c-415c-982d-53c1212f4bcf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-concepts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f336e5c8e379939a6d01c0f53ed0cd7838143113/msteams-platform%2Fbots%2Fbot-concepts.md) | 91 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fb96d55c-16cb-4dfb-8647-8b3fd178f4c1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/calls-and-meetings/registering-calling-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f336e5c8e379939a6d01c0f53ed0cd7838143113/msteams-platform%2Fbots%2Fcalls-and-meetings%2Fregistering-calling-bot.md) | 85 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/571764d5-5c45-4c28-989e-7a87767eacc2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/add-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f336e5c8e379939a6d01c0f53ed0cd7838143113/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fadd-authentication.md) | 89 | 70 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/96870a7d-861d-4c59-a069-0a26d8940f4e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/bot-sso-code.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f336e5c8e379939a6d01c0f53ed0cd7838143113/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-code.md) | 84 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c5de7382-0dbb-484d-a398-641b90677141) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bot-configuration-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f336e5c8e379939a6d01c0f53ed0cd7838143113/msteams-platform%2Fbots%2Fhow-to%2Fbot-configuration-experience.md) | 91 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9b64f34c-aa21-48c3-b694-132bcd23b99b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f336e5c8e379939a6d01c0f53ed0cd7838143113/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 81 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/46a0a082-4a66-452a-b419-96d9e645267a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/prompt-suggestions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f336e5c8e379939a6d01c0f53ed0cd7838143113/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fprompt-suggestions.md) | 90 | 40 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a81127db-b913-43d0-9fcd-7ec197850102) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f336e5c8e379939a6d01c0f53ed0cd7838143113/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 90 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/46f8585c-72b2-45c8-b42b-26ded0cb4581) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f336e5c8e379939a6d01c0f53ed0cd7838143113/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsubscribe-to-conversation-events.md) | 88 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c259806b-3c7e-49c8-a675-056ed65bff29) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/streaming-ux.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f336e5c8e379939a6d01c0f53ed0cd7838143113/msteams-platform%2Fbots%2Fstreaming-ux.md) | 87 | 30 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fd40d4d8-06a3-4ae8-9286-ecec3b3f2799) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/authentication/nested-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f336e5c8e379939a6d01c0f53ed0cd7838143113/msteams-platform%2Fconcepts%2Fauthentication%2Fnested-authentication.md) | 91 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/825f4e49-2ce9-4f45-8da9-1fbd171bb1ef) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f336e5c8e379939a6d01c0f53ed0cd7838143113/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fapps-localization.md) | 88 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4cedf410-c444-4d28-a92b-bd188f261db6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-application.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f336e5c8e379939a6d01c0f53ed0cd7838143113/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-application.md) | 92 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/51224ebd-e7c5-4eda-aea0-6bcf6525d128) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f336e5c8e379939a6d01c0f53ed0cd7838143113/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-teams.md) | 89 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c77b6 [...]

2025-03-21 11:50 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/857a65f4c555319ab13313413aa21d4016809c06/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/755e6160-88ab-484a-87af-4e945f11e4b0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-anonymous-user.md](https://github.com/MicrosoftDocs/msteams-docs/blob/857a65f4c555319ab13313413aa21d4016809c06/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-anonymous-user.md) | 87 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0f8055b9-726b-4e0f-91d3-4f4e00ebd965) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-teams-meeting-stage.md](https://github.com/MicrosoftDocs/msteams-docs/blob/857a65f4c555319ab13313413aa21d4016809c06/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-teams-meeting-stage.md) | 91 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/62fcc4fa-3c91-478b-99f9-b3c4b09e144c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-extensible-conversation-for-meeting-chat.md](https://github.com/MicrosoftDocs/msteams-docs/blob/857a65f4c555319ab13313413aa21d4016809c06/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-extensible-conversation-for-meeting-chat.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/95f48b85-4d6a-4b98-af0e-f372dd20682a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/857a65f4c555319ab13313413aa21d4016809c06/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 88 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/86ed14ce-e3bf-4b1e-bc8a-cb820d03e40c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-concepts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/857a65f4c555319ab13313413aa21d4016809c06/msteams-platform%2Fbots%2Fbot-concepts.md) | 91 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/134e3c2a-5dec-4d93-8892-5804f9e498ac) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/calls-and-meetings/registering-calling-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/857a65f4c555319ab13313413aa21d4016809c06/msteams-platform%2Fbots%2Fcalls-and-meetings%2Fregistering-calling-bot.md) | 86 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a2aeaa84-9f73-4ed6-a242-f1e6638781ef) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/add-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/857a65f4c555319ab13313413aa21d4016809c06/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fadd-authentication.md) | 89 | 70 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5a9f0877-694c-4475-8b0d-78275040a8b9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/bot-sso-code.md](https://github.com/MicrosoftDocs/msteams-docs/blob/857a65f4c555319ab13313413aa21d4016809c06/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-code.md) | 84 | 33 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c52fbdca-26b1-47b4-845e-ea5845d97344) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bot-configuration-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/857a65f4c555319ab13313413aa21d4016809c06/msteams-platform%2Fbots%2Fhow-to%2Fbot-configuration-experience.md) | 91 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/534d84c3-4bce-40a5-8173-03ae3333cb4e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/857a65f4c555319ab13313413aa21d4016809c06/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 81 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/051d9da7-6325-43ee-8ab9-46d2f899442f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/prompt-suggestions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/857a65f4c555319ab13313413aa21d4016809c06/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fprompt-suggestions.md) | 90 | 40 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5b6c5444-44db-45bb-b7ba-054c0e5d1622) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/857a65f4c555319ab13313413aa21d4016809c06/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 90 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f3439afe-b67d-4f9f-932d-3a737e3f35c5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/857a65f4c555319ab13313413aa21d4016809c06/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsubscribe-to-conversation-events.md) | 88 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8d6d5879-9f06-4653-b016-f1e975b377b7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/streaming-ux.md](https://github.com/MicrosoftDocs/msteams-docs/blob/857a65f4c555319ab13313413aa21d4016809c06/msteams-platform%2Fbots%2Fstreaming-ux.md) | 87 | 30 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cbdaa97a-ce24-4931-886c-34301e8d3b95) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/authentication/nested-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/857a65f4c555319ab13313413aa21d4016809c06/msteams-platform%2Fconcepts%2Fauthentication%2Fnested-authentication.md) | 91 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ea32f962-e4f0-4f93-a422-3074f18afd64) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/857a65f4c555319ab13313413aa21d4016809c06/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fapps-localization.md) | 88 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a82f6ca0-fdb2-43c5-b15d-38600f4118e8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-application.md](https://github.com/MicrosoftDocs/msteams-docs/blob/857a65f4c555319ab13313413aa21d4016809c06/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-application.md) | 92 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d6b2b813-ddec-42c8-b417-ca7eea7bdcc4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/857a65f4c555319ab13313413aa21d4016809c06/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-teams.md) | 89 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ead28 [...]

2025-03-24 05:47 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9496eb6a0b71361169819de381aeed9ccbd4519b/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/793fec62-c312-46e8-a8c7-02e90a5fb111) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-anonymous-user.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9496eb6a0b71361169819de381aeed9ccbd4519b/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-anonymous-user.md) | 87 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1eeddf56-94c5-44f9-9cdf-7581b2ef0ee8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-teams-meeting-stage.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9496eb6a0b71361169819de381aeed9ccbd4519b/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-teams-meeting-stage.md) | 90 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cb8984e0-b0dd-4a79-9a23-89a0312f7c8f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-extensible-conversation-for-meeting-chat.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9496eb6a0b71361169819de381aeed9ccbd4519b/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-extensible-conversation-for-meeting-chat.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3098bdda-c431-4937-b7af-931b4a1c3b0b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9496eb6a0b71361169819de381aeed9ccbd4519b/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 88 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e7f97798-3eb0-4a3d-875f-ee2c6db4ea20) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-concepts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9496eb6a0b71361169819de381aeed9ccbd4519b/msteams-platform%2Fbots%2Fbot-concepts.md) | 91 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/33ba1d5b-8af7-4019-b0bf-e218e3cca6df) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/calls-and-meetings/registering-calling-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9496eb6a0b71361169819de381aeed9ccbd4519b/msteams-platform%2Fbots%2Fcalls-and-meetings%2Fregistering-calling-bot.md) | 86 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0ac38816-8a9a-4bba-a602-93a771623e20) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/add-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9496eb6a0b71361169819de381aeed9ccbd4519b/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fadd-authentication.md) | 89 | 70 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fcee4e17-4e97-417e-8451-728e466a5598) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/bot-sso-code.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9496eb6a0b71361169819de381aeed9ccbd4519b/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-code.md) | 84 | 33 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f10ac409-9148-46f4-8ba3-152072b97e72) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bot-configuration-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9496eb6a0b71361169819de381aeed9ccbd4519b/msteams-platform%2Fbots%2Fhow-to%2Fbot-configuration-experience.md) | 91 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f52120bd-7118-46c0-b050-ba017ce52402) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9496eb6a0b71361169819de381aeed9ccbd4519b/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 81 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/34b04edc-7b53-4bf5-af75-37732cf30cc7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/prompt-suggestions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9496eb6a0b71361169819de381aeed9ccbd4519b/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fprompt-suggestions.md) | 90 | 40 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0a8494b6-d0ba-4b8e-bddb-f374779545de) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9496eb6a0b71361169819de381aeed9ccbd4519b/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 90 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d0a156e5-ebda-4f13-88ad-8eb40758748e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9496eb6a0b71361169819de381aeed9ccbd4519b/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsubscribe-to-conversation-events.md) | 88 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/617cf95c-96be-4618-a901-1b993a326784) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/streaming-ux.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9496eb6a0b71361169819de381aeed9ccbd4519b/msteams-platform%2Fbots%2Fstreaming-ux.md) | 87 | 30 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/948ec066-3a98-483e-8319-33ea9188d4af) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/authentication/nested-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9496eb6a0b71361169819de381aeed9ccbd4519b/msteams-platform%2Fconcepts%2Fauthentication%2Fnested-authentication.md) | 91 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/20a70527-a281-4602-9ef3-6d6f006a5ecc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9496eb6a0b71361169819de381aeed9ccbd4519b/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fapps-localization.md) | 88 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4eac5374-0d4d-459c-8f7a-632f576c5ae9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-application.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9496eb6a0b71361169819de381aeed9ccbd4519b/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-application.md) | 92 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/90442515-28af-4d76-bac5-9f96d977673c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9496eb6a0b71361169819de381aeed9ccbd4519b/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-teams.md) | 89 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d088b [...]

2025-03-24 06:24 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8980c7d2521c47d53c2529576bc20e9740fba342/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7ce86603-3bc2-4c62-b68a-15febb14ead6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-anonymous-user.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8980c7d2521c47d53c2529576bc20e9740fba342/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-anonymous-user.md) | 88 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ac94356d-4ba1-4c09-92ba-625168840f67) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-teams-meeting-stage.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8980c7d2521c47d53c2529576bc20e9740fba342/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-teams-meeting-stage.md) | 90 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f618f1fb-46c5-491b-9e3c-84d16f8be9d7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-extensible-conversation-for-meeting-chat.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8980c7d2521c47d53c2529576bc20e9740fba342/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-extensible-conversation-for-meeting-chat.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/27048d52-6143-44db-92e2-998fd3739a01) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8980c7d2521c47d53c2529576bc20e9740fba342/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 88 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aa8dafc8-1358-4de4-896d-bdcc126dbf2b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-concepts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8980c7d2521c47d53c2529576bc20e9740fba342/msteams-platform%2Fbots%2Fbot-concepts.md) | 91 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2320feef-688b-4101-9b0b-4d4d50b2dac1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/calls-and-meetings/registering-calling-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8980c7d2521c47d53c2529576bc20e9740fba342/msteams-platform%2Fbots%2Fcalls-and-meetings%2Fregistering-calling-bot.md) | 86 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6e163fe1-40e7-408a-ba7c-fd97e424bd62) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/add-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8980c7d2521c47d53c2529576bc20e9740fba342/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fadd-authentication.md) | 89 | 69 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c15e07ed-895f-41b7-9b2a-828a27821322) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/bot-sso-code.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8980c7d2521c47d53c2529576bc20e9740fba342/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-code.md) | 84 | 33 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/334d218f-b262-42f3-83e4-82a44bd67176) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bot-configuration-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8980c7d2521c47d53c2529576bc20e9740fba342/msteams-platform%2Fbots%2Fhow-to%2Fbot-configuration-experience.md) | 91 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/faefaec3-9f51-4ff0-a731-aee371d5f2b8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8980c7d2521c47d53c2529576bc20e9740fba342/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 81 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1ac89250-390d-4e88-8f12-21cdcd50016f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/prompt-suggestions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8980c7d2521c47d53c2529576bc20e9740fba342/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fprompt-suggestions.md) | 90 | 40 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f08b9976-0293-437e-a043-e85af4cd313e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8980c7d2521c47d53c2529576bc20e9740fba342/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 90 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/87cc9c2b-0347-46fb-a55c-35c736eba062) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8980c7d2521c47d53c2529576bc20e9740fba342/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsubscribe-to-conversation-events.md) | 88 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/819cde11-6daa-43bd-999e-b5464f1ee1d5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/streaming-ux.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8980c7d2521c47d53c2529576bc20e9740fba342/msteams-platform%2Fbots%2Fstreaming-ux.md) | 87 | 30 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b0b6ff0c-a3fd-41ef-a765-dff7f558d3e3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/authentication/nested-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8980c7d2521c47d53c2529576bc20e9740fba342/msteams-platform%2Fconcepts%2Fauthentication%2Fnested-authentication.md) | 91 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dff8e770-678c-42b5-9f69-6324a83d89f9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8980c7d2521c47d53c2529576bc20e9740fba342/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fapps-localization.md) | 88 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dbd67886-96b9-4a1b-aa86-9214e8476219) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-application.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8980c7d2521c47d53c2529576bc20e9740fba342/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-application.md) | 92 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e2c12a26-3cf6-46a2-a00b-355f8ca9d940) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8980c7d2521c47d53c2529576bc20e9740fba342/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-teams.md) | 89 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b5918 [...]

2025-03-24 06:35 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a823ce4c68d4b32a8e8ffaf6ea9e3462bb90df42/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d5aeaa84-137a-4244-955d-309eadc289c7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-anonymous-user.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a823ce4c68d4b32a8e8ffaf6ea9e3462bb90df42/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-anonymous-user.md) | 88 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/78cffe62-b0be-49f0-8629-e7e06162692b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-teams-meeting-stage.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a823ce4c68d4b32a8e8ffaf6ea9e3462bb90df42/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-teams-meeting-stage.md) | 90 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9ec3b906-cf2b-470b-b398-4ae5a2d54a1c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-extensible-conversation-for-meeting-chat.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a823ce4c68d4b32a8e8ffaf6ea9e3462bb90df42/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-extensible-conversation-for-meeting-chat.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/18772f9c-97b7-4730-ae96-d622c8c98c90) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a823ce4c68d4b32a8e8ffaf6ea9e3462bb90df42/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 88 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/34e1540d-46e1-441c-9b6c-be85db188c95) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-concepts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a823ce4c68d4b32a8e8ffaf6ea9e3462bb90df42/msteams-platform%2Fbots%2Fbot-concepts.md) | 91 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ff95797f-2146-4d71-8321-8279c1304ec4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/calls-and-meetings/registering-calling-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a823ce4c68d4b32a8e8ffaf6ea9e3462bb90df42/msteams-platform%2Fbots%2Fcalls-and-meetings%2Fregistering-calling-bot.md) | 86 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5657ffed-3071-4b7e-b517-d9810a3a7ac9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/add-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a823ce4c68d4b32a8e8ffaf6ea9e3462bb90df42/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fadd-authentication.md) | 89 | 69 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b670b2f2-1c66-46c5-a14f-f8404a70ce5f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/bot-sso-code.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a823ce4c68d4b32a8e8ffaf6ea9e3462bb90df42/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-code.md) | 84 | 33 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5b76f7f9-76fc-42e4-a3a1-9fe90018bac3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bot-configuration-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a823ce4c68d4b32a8e8ffaf6ea9e3462bb90df42/msteams-platform%2Fbots%2Fhow-to%2Fbot-configuration-experience.md) | 91 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/33762c25-1072-4738-a14f-e2f6aa3e064d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a823ce4c68d4b32a8e8ffaf6ea9e3462bb90df42/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 81 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e2b5bfcc-be58-4b6f-9912-ed96fa83109d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/prompt-suggestions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a823ce4c68d4b32a8e8ffaf6ea9e3462bb90df42/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fprompt-suggestions.md) | 90 | 40 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/51c98baf-3b59-48da-8053-265ca2c9c7b9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a823ce4c68d4b32a8e8ffaf6ea9e3462bb90df42/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 90 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/174ac98a-3211-46ff-8632-eb9576c6ae5e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a823ce4c68d4b32a8e8ffaf6ea9e3462bb90df42/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsubscribe-to-conversation-events.md) | 88 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/914f44b4-c81f-480a-b730-2da09e59a4bc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/streaming-ux.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a823ce4c68d4b32a8e8ffaf6ea9e3462bb90df42/msteams-platform%2Fbots%2Fstreaming-ux.md) | 87 | 30 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0d67356b-f6c7-40a2-81d9-c5648b1097cb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/authentication/nested-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a823ce4c68d4b32a8e8ffaf6ea9e3462bb90df42/msteams-platform%2Fconcepts%2Fauthentication%2Fnested-authentication.md) | 91 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9ef26644-2943-4672-8b70-c2d9ca993182) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a823ce4c68d4b32a8e8ffaf6ea9e3462bb90df42/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fapps-localization.md) | 88 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d91af33e-7bc8-4c21-87ff-8a9e127b168d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-application.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a823ce4c68d4b32a8e8ffaf6ea9e3462bb90df42/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-application.md) | 92 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6e6b3846-79d5-48d1-815a-3acfc2bdefb2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a823ce4c68d4b32a8e8ffaf6ea9e3462bb90df42/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-teams.md) | 89 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/793f2 [...]

2025-03-24 06:47 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2abe9519ac15380e6f5c739159d1de8d47108c9f/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a3f849b3-c1de-41a9-99cb-1d9cdacde88d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-anonymous-user.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2abe9519ac15380e6f5c739159d1de8d47108c9f/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-anonymous-user.md) | 88 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/718fa7d8-26c8-4b9f-b188-3a39b0209c2b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-teams-meeting-stage.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2abe9519ac15380e6f5c739159d1de8d47108c9f/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-teams-meeting-stage.md) | 90 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b9d74794-a4a6-4ef7-9cab-500ea0dd62a6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-extensible-conversation-for-meeting-chat.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2abe9519ac15380e6f5c739159d1de8d47108c9f/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-extensible-conversation-for-meeting-chat.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/05195689-5788-4e87-a16a-8dbff327980b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2abe9519ac15380e6f5c739159d1de8d47108c9f/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 88 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b8db3497-3a24-48f4-8e9f-a2cdb0171e04) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-concepts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2abe9519ac15380e6f5c739159d1de8d47108c9f/msteams-platform%2Fbots%2Fbot-concepts.md) | 91 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dfd22d1a-4f44-4966-ae74-becf6ed46d6b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/calls-and-meetings/registering-calling-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2abe9519ac15380e6f5c739159d1de8d47108c9f/msteams-platform%2Fbots%2Fcalls-and-meetings%2Fregistering-calling-bot.md) | 86 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/37a5fe41-eba0-40e2-8f05-c04989496acf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/add-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2abe9519ac15380e6f5c739159d1de8d47108c9f/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fadd-authentication.md) | 89 | 67 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9071d1ff-8981-4fc3-8d64-22e32dde9ceb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/bot-sso-code.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2abe9519ac15380e6f5c739159d1de8d47108c9f/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-code.md) | 84 | 33 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/95efc3b8-6e25-489e-b69b-356bc8003d14) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bot-configuration-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2abe9519ac15380e6f5c739159d1de8d47108c9f/msteams-platform%2Fbots%2Fhow-to%2Fbot-configuration-experience.md) | 91 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bf7455ed-ea2c-49a1-bbf0-cf16c6cdcf64) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2abe9519ac15380e6f5c739159d1de8d47108c9f/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 81 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ef2ebfc3-397b-45fe-8953-59daeb64f767) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/prompt-suggestions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2abe9519ac15380e6f5c739159d1de8d47108c9f/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fprompt-suggestions.md) | 90 | 40 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d66d8dc4-1bcb-41eb-a370-5b3eee17a622) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2abe9519ac15380e6f5c739159d1de8d47108c9f/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 90 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dc2c87c3-caf5-4ae0-9d66-93b11e250369) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2abe9519ac15380e6f5c739159d1de8d47108c9f/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsubscribe-to-conversation-events.md) | 88 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5e3a6c3e-8772-43d5-9e82-ef0b4cc96092) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/streaming-ux.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2abe9519ac15380e6f5c739159d1de8d47108c9f/msteams-platform%2Fbots%2Fstreaming-ux.md) | 87 | 30 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/483b13c0-def3-48d9-9387-c44a4d29a931) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/authentication/nested-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2abe9519ac15380e6f5c739159d1de8d47108c9f/msteams-platform%2Fconcepts%2Fauthentication%2Fnested-authentication.md) | 91 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/02bbf888-e715-4255-bfad-e0f857da320f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2abe9519ac15380e6f5c739159d1de8d47108c9f/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fapps-localization.md) | 88 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/29719a5a-3146-4e5c-850b-88bcdc93b8ee) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-application.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2abe9519ac15380e6f5c739159d1de8d47108c9f/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-application.md) | 92 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0cc739c2-2375-4da8-8234-43cac22b552f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2abe9519ac15380e6f5c739159d1de8d47108c9f/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-teams.md) | 89 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9721d [...]

2025-04-17 10:12 UTC, acrolinx-at-msft2 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d184a0453ea3a9bee82431818d40e518ee35e939/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/de200ac1-bfe9-46f0-a044-f82b3a41cb21) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-anonymous-user.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d184a0453ea3a9bee82431818d40e518ee35e939/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-anonymous-user.md) | 88 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9819166c-2dbe-42ad-b88a-7b3223c29b47) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-teams-meeting-stage.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d184a0453ea3a9bee82431818d40e518ee35e939/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-teams-meeting-stage.md) | 90 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b95c7ef0-9fd8-4e8b-9187-6a3f568e49aa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-extensible-conversation-for-meeting-chat.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d184a0453ea3a9bee82431818d40e518ee35e939/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-extensible-conversation-for-meeting-chat.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3f16b417-6f49-4319-8bf8-0c90db224cc1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d184a0453ea3a9bee82431818d40e518ee35e939/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 88 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/31cf4ffe-6c3e-4184-95a5-d17612ab6407) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-concepts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d184a0453ea3a9bee82431818d40e518ee35e939/msteams-platform%2Fbots%2Fbot-concepts.md) | 91 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d08f9404-a96b-4305-810e-be49c9b3fe09) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/calls-and-meetings/registering-calling-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d184a0453ea3a9bee82431818d40e518ee35e939/msteams-platform%2Fbots%2Fcalls-and-meetings%2Fregistering-calling-bot.md) | 86 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4ccac07c-4d6b-4320-9425-2762908638e2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/add-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d184a0453ea3a9bee82431818d40e518ee35e939/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fadd-authentication.md) | 89 | 67 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7a628ce5-8374-40cc-9c5e-a10539c13166) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/bot-sso-code.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d184a0453ea3a9bee82431818d40e518ee35e939/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-code.md) | 84 | 33 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d6851e3d-be39-43a7-ba61-356705d43c14) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bot-configuration-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d184a0453ea3a9bee82431818d40e518ee35e939/msteams-platform%2Fbots%2Fhow-to%2Fbot-configuration-experience.md) | 91 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/363300aa-f6a8-413d-b16c-8b42aee6b8c3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d184a0453ea3a9bee82431818d40e518ee35e939/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 81 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1321cf91-c62b-447f-9746-6ebcbd80b95a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/prompt-suggestions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d184a0453ea3a9bee82431818d40e518ee35e939/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fprompt-suggestions.md) | 90 | 40 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/57051bb3-9eb1-4b18-91eb-d35f9d8dab24) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d184a0453ea3a9bee82431818d40e518ee35e939/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsubscribe-to-conversation-events.md) | 88 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1c559a27-1f1c-4185-a124-2861cac68c2f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/streaming-ux.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d184a0453ea3a9bee82431818d40e518ee35e939/msteams-platform%2Fbots%2Fstreaming-ux.md) | 87 | 30 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dbcf072c-cd05-448a-b62f-1c5d99d31360) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/authentication/nested-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d184a0453ea3a9bee82431818d40e518ee35e939/msteams-platform%2Fconcepts%2Fauthentication%2Fnested-authentication.md) | 92 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/eba1614e-15de-4183-a195-676168a307c9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d184a0453ea3a9bee82431818d40e518ee35e939/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fapps-localization.md) | 88 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7161d71a-3147-4d7a-8f41-83ccdd6c41e0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-application.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d184a0453ea3a9bee82431818d40e518ee35e939/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-application.md) | 92 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d1116238-200a-4c04-bd28-146b54b69b10) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d184a0453ea3a9bee82431818d40e518ee35e939/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-teams.md) | 89 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/78a5d65a-7cec-428a-ba2a-e69d89d0aa3d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-workflow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d184a0453ea3a9bee82431818d40e518ee35e939/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-workflow.md) | 93 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f839304c-a724-4908-8f [...]

2025-04-17 10:39 UTC, acrolinx-at-msft2 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c15156afa34678f045319f95b9b159df7c0a0147/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c1785ad7-8135-4315-a324-359303c49eb5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-anonymous-user.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c15156afa34678f045319f95b9b159df7c0a0147/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-anonymous-user.md) | 88 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6b2b241d-4c7c-4876-ad02-971611415d0e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-teams-meeting-stage.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c15156afa34678f045319f95b9b159df7c0a0147/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-teams-meeting-stage.md) | 90 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/142f6661-f906-4687-a5f3-a8a91a4329e7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-extensible-conversation-for-meeting-chat.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c15156afa34678f045319f95b9b159df7c0a0147/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-extensible-conversation-for-meeting-chat.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c8a60b60-2660-4bfd-b4b2-4980656982f8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c15156afa34678f045319f95b9b159df7c0a0147/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 88 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/88c0b4d4-74a3-4f49-9c75-6aff8f829328) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-concepts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c15156afa34678f045319f95b9b159df7c0a0147/msteams-platform%2Fbots%2Fbot-concepts.md) | 91 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bfacfbd8-6af5-4f4d-9d4d-640e62ab67c5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/calls-and-meetings/registering-calling-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c15156afa34678f045319f95b9b159df7c0a0147/msteams-platform%2Fbots%2Fcalls-and-meetings%2Fregistering-calling-bot.md) | 86 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1ffd0dfd-2cb6-4b87-8d22-4a643afd8b8a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/add-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c15156afa34678f045319f95b9b159df7c0a0147/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fadd-authentication.md) | 89 | 67 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/42e562f3-630e-456e-9f5f-180eef1b14db) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/bot-sso-code.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c15156afa34678f045319f95b9b159df7c0a0147/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-code.md) | 84 | 33 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/16267a4a-f895-4e61-8575-883237ad9078) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bot-configuration-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c15156afa34678f045319f95b9b159df7c0a0147/msteams-platform%2Fbots%2Fhow-to%2Fbot-configuration-experience.md) | 91 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2306323f-c19d-467c-8583-60c51b66cb77) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c15156afa34678f045319f95b9b159df7c0a0147/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 81 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/44d098c6-3629-44e1-bfa4-9b2af44eac1d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/prompt-suggestions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c15156afa34678f045319f95b9b159df7c0a0147/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fprompt-suggestions.md) | 91 | 41 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9e3ee793-0ef9-4bf2-adfd-af4c539dfb73) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c15156afa34678f045319f95b9b159df7c0a0147/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsubscribe-to-conversation-events.md) | 88 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/394f29b5-609b-430c-bd63-c9876a930657) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/streaming-ux.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c15156afa34678f045319f95b9b159df7c0a0147/msteams-platform%2Fbots%2Fstreaming-ux.md) | 87 | 30 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e9e7f9a8-ea39-4ef1-9232-3635a6e74acc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/authentication/nested-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c15156afa34678f045319f95b9b159df7c0a0147/msteams-platform%2Fconcepts%2Fauthentication%2Fnested-authentication.md) | 92 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3ad391e0-0237-4d7c-9e00-40c08b105f38) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c15156afa34678f045319f95b9b159df7c0a0147/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fapps-localization.md) | 88 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/264c972e-34a6-4da3-a108-a54c04692d8f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-application.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c15156afa34678f045319f95b9b159df7c0a0147/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-application.md) | 92 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/965894be-bfd8-4a07-853f-2a5d09b35894) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c15156afa34678f045319f95b9b159df7c0a0147/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-teams.md) | 89 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b2d9e995-a9e7-4c4b-9bb7-4809ba1669de) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-workflow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c15156afa34678f045319f95b9b159df7c0a0147/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-workflow.md) | 93 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/54f5bdc3-7acf-4fd3-b1 [...]

2025-04-24 11:48 UTC, acrolinx-at-msft2 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cf14d202c67eaad5691dc0def500aff75e0fe857/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0fb2cabd-91bd-469e-a978-f3033fe8e853) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-anonymous-user.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cf14d202c67eaad5691dc0def500aff75e0fe857/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-anonymous-user.md) | 88 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b1c72535-7205-489d-b56a-a9ee8ca14f51) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-teams-meeting-stage.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cf14d202c67eaad5691dc0def500aff75e0fe857/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-teams-meeting-stage.md) | 90 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9c159329-3171-4a56-ab2a-26d25d591d41) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-extensible-conversation-for-meeting-chat.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cf14d202c67eaad5691dc0def500aff75e0fe857/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-extensible-conversation-for-meeting-chat.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/caa1a2bd-516a-4acb-a9fc-edeff5ac23a4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cf14d202c67eaad5691dc0def500aff75e0fe857/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 88 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2d73ddd8-cf30-4e87-bfa6-9706a5cda879) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-concepts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cf14d202c67eaad5691dc0def500aff75e0fe857/msteams-platform%2Fbots%2Fbot-concepts.md) | 91 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bdbf5a11-758c-4e5d-83ef-e0ab7bd8e77a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/calls-and-meetings/registering-calling-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cf14d202c67eaad5691dc0def500aff75e0fe857/msteams-platform%2Fbots%2Fcalls-and-meetings%2Fregistering-calling-bot.md) | 86 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/339516ad-11be-4821-bd53-2c3216b49305) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/add-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cf14d202c67eaad5691dc0def500aff75e0fe857/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fadd-authentication.md) | 89 | 67 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3a445433-511a-4444-bcad-16255b47e119) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/bot-sso-code.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cf14d202c67eaad5691dc0def500aff75e0fe857/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-code.md) | 84 | 33 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f7eef106-18a6-4696-862a-d7383674131a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bot-configuration-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cf14d202c67eaad5691dc0def500aff75e0fe857/msteams-platform%2Fbots%2Fhow-to%2Fbot-configuration-experience.md) | 91 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bf53996a-8f06-498b-a33a-5e7f1b0b3b85) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cf14d202c67eaad5691dc0def500aff75e0fe857/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 81 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4dd2c90a-4704-4c64-8b54-51369bd58839) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/prompt-suggestions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cf14d202c67eaad5691dc0def500aff75e0fe857/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fprompt-suggestions.md) | 91 | 41 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7a015024-249b-48a5-b4bd-b68ae6796df9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cf14d202c67eaad5691dc0def500aff75e0fe857/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsubscribe-to-conversation-events.md) | 88 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ee653e73-c60d-4054-821e-9d1cdaed29d2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/streaming-ux.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cf14d202c67eaad5691dc0def500aff75e0fe857/msteams-platform%2Fbots%2Fstreaming-ux.md) | 87 | 30 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5514a4d1-2132-432a-a88c-d6586402326c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/authentication/nested-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cf14d202c67eaad5691dc0def500aff75e0fe857/msteams-platform%2Fconcepts%2Fauthentication%2Fnested-authentication.md) | 92 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a3cb2897-970b-49dd-a498-562b816ddc60) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cf14d202c67eaad5691dc0def500aff75e0fe857/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fapps-localization.md) | 88 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ef7b934a-460d-4c5f-9e5a-4e6fc1a70ada) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-application.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cf14d202c67eaad5691dc0def500aff75e0fe857/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-application.md) | 92 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dcc0631a-5a78-4d27-88d9-f09d57432544) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cf14d202c67eaad5691dc0def500aff75e0fe857/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-teams.md) | 89 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4f3310e2-e919-4279-8d87-5fac20dbed4f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-workflow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cf14d202c67eaad5691dc0def500aff75e0fe857/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-workflow.md) | 93 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3f072e1e-5578-4e64-8d [...]

2025-04-24 11:53 UTC, acrolinx-at-msft2 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/28e236812cfb1e613fa5e71e19eef950f460a48e/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6052ca5a-6632-4e10-8136-2e46275dd413) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-anonymous-user.md](https://github.com/MicrosoftDocs/msteams-docs/blob/28e236812cfb1e613fa5e71e19eef950f460a48e/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-anonymous-user.md) | 88 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/02461e73-f363-44c2-96d2-278ba4669189) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-teams-meeting-stage.md](https://github.com/MicrosoftDocs/msteams-docs/blob/28e236812cfb1e613fa5e71e19eef950f460a48e/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-teams-meeting-stage.md) | 90 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/59470306-be54-4b05-86ea-2d66e06dd950) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-extensible-conversation-for-meeting-chat.md](https://github.com/MicrosoftDocs/msteams-docs/blob/28e236812cfb1e613fa5e71e19eef950f460a48e/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-extensible-conversation-for-meeting-chat.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/10f84194-6879-4009-860d-d394dbb7aa47) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/28e236812cfb1e613fa5e71e19eef950f460a48e/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 88 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cc20d2c8-dc7b-422e-a2f0-bb62bbf513b1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-concepts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/28e236812cfb1e613fa5e71e19eef950f460a48e/msteams-platform%2Fbots%2Fbot-concepts.md) | 91 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b25aef9e-55aa-4e19-a6a8-e75215e8ce5c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/calls-and-meetings/registering-calling-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/28e236812cfb1e613fa5e71e19eef950f460a48e/msteams-platform%2Fbots%2Fcalls-and-meetings%2Fregistering-calling-bot.md) | 86 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/21d5dbb8-048a-4cfa-974e-0dcb0125428a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/add-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/28e236812cfb1e613fa5e71e19eef950f460a48e/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fadd-authentication.md) | 89 | 67 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9b590e71-7b88-46e0-a17d-b6f88fdb7d05) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/bot-sso-code.md](https://github.com/MicrosoftDocs/msteams-docs/blob/28e236812cfb1e613fa5e71e19eef950f460a48e/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-code.md) | 84 | 33 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e9363df2-156c-4ba5-b77f-fcff72088b6d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bot-configuration-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/28e236812cfb1e613fa5e71e19eef950f460a48e/msteams-platform%2Fbots%2Fhow-to%2Fbot-configuration-experience.md) | 91 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b4ae25d3-db3e-4ea2-a160-2bb5dd3e9e9f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/28e236812cfb1e613fa5e71e19eef950f460a48e/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 81 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/393be856-4a99-4837-9771-a12a9c4f3461) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/prompt-suggestions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/28e236812cfb1e613fa5e71e19eef950f460a48e/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fprompt-suggestions.md) | 91 | 41 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5c3f5b9d-b3de-4bb2-a80a-ed2df3b1d1db) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/28e236812cfb1e613fa5e71e19eef950f460a48e/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsubscribe-to-conversation-events.md) | 88 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3672c640-00c8-49e9-ab15-8ef1929f5043) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/streaming-ux.md](https://github.com/MicrosoftDocs/msteams-docs/blob/28e236812cfb1e613fa5e71e19eef950f460a48e/msteams-platform%2Fbots%2Fstreaming-ux.md) | 87 | 30 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f50c1e0b-6346-4159-920c-f592ef470700) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/authentication/nested-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/28e236812cfb1e613fa5e71e19eef950f460a48e/msteams-platform%2Fconcepts%2Fauthentication%2Fnested-authentication.md) | 92 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cd23a311-5f41-4296-9d9f-ac2924f98f22) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/28e236812cfb1e613fa5e71e19eef950f460a48e/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fapps-localization.md) | 88 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0263ccbe-570f-4abe-bee4-fb6bc5aaa051) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-application.md](https://github.com/MicrosoftDocs/msteams-docs/blob/28e236812cfb1e613fa5e71e19eef950f460a48e/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-application.md) | 92 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e71c2679-61b7-4b90-bc94-ce99938e8640) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/28e236812cfb1e613fa5e71e19eef950f460a48e/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-teams.md) | 89 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/846fb41b-f070-4a93-8e6e-8751209b185e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-workflow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/28e236812cfb1e613fa5e71e19eef950f460a48e/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-workflow.md) | 93 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/61c0c259-8e79-44e4-ba [...]

2025-04-25 07:30 UTC, acrolinx-at-msft2 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8aeeb8aa582dca1581a313b54cda2420af73fed1/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/968c7291-c0b6-4fbe-af2c-88d0cd36e271) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-anonymous-user.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8aeeb8aa582dca1581a313b54cda2420af73fed1/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-anonymous-user.md) | 88 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/016bbbf4-69c4-423e-998b-0887fca267b2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-teams-meeting-stage.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8aeeb8aa582dca1581a313b54cda2420af73fed1/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-teams-meeting-stage.md) | 90 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/14ac095f-720a-4143-bc86-fb0100d2ea43) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-extensible-conversation-for-meeting-chat.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8aeeb8aa582dca1581a313b54cda2420af73fed1/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-extensible-conversation-for-meeting-chat.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ffa4564b-ea23-4a10-93c1-2753a4f75fa1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8aeeb8aa582dca1581a313b54cda2420af73fed1/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 88 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/16a062f6-39e4-468a-9ffb-b529356ea4ff) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-concepts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8aeeb8aa582dca1581a313b54cda2420af73fed1/msteams-platform%2Fbots%2Fbot-concepts.md) | 91 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b14c82d9-9991-47c4-a8bb-e97300e3f773) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/calls-and-meetings/registering-calling-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8aeeb8aa582dca1581a313b54cda2420af73fed1/msteams-platform%2Fbots%2Fcalls-and-meetings%2Fregistering-calling-bot.md) | 86 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4429eed1-ab1d-4bfa-bec4-b2afbadc0955) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/add-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8aeeb8aa582dca1581a313b54cda2420af73fed1/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fadd-authentication.md) | 89 | 67 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/eb5dda80-e970-4248-81e8-bd67e72639c9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/bot-sso-code.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8aeeb8aa582dca1581a313b54cda2420af73fed1/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-code.md) | 84 | 33 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e6ed2366-7dda-4801-91b8-f52eb82240eb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bot-configuration-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8aeeb8aa582dca1581a313b54cda2420af73fed1/msteams-platform%2Fbots%2Fhow-to%2Fbot-configuration-experience.md) | 91 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/051adc8e-af91-4d68-b289-1584546e7495) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8aeeb8aa582dca1581a313b54cda2420af73fed1/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 81 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e87b48aa-ba88-4a8b-845d-a351b0ad65b7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/prompt-suggestions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8aeeb8aa582dca1581a313b54cda2420af73fed1/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fprompt-suggestions.md) | 91 | 41 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/192a0b0f-f9f7-4eb4-a778-707e71b85b1d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8aeeb8aa582dca1581a313b54cda2420af73fed1/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsubscribe-to-conversation-events.md) | 88 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dde4859f-c14c-4628-9eab-76d9ab204181) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/streaming-ux.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8aeeb8aa582dca1581a313b54cda2420af73fed1/msteams-platform%2Fbots%2Fstreaming-ux.md) | 87 | 30 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1a9728e5-9d8c-410e-acac-5cd66d1bfe28) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/authentication/nested-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8aeeb8aa582dca1581a313b54cda2420af73fed1/msteams-platform%2Fconcepts%2Fauthentication%2Fnested-authentication.md) | 92 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/94655c18-945b-4436-9007-ad368d35f73e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8aeeb8aa582dca1581a313b54cda2420af73fed1/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fapps-localization.md) | 88 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f2063139-a0f3-441a-b9f8-19b597f188a4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-application.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8aeeb8aa582dca1581a313b54cda2420af73fed1/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-application.md) | 92 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f21701ee-ac2f-4658-ae66-a946aa721274) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8aeeb8aa582dca1581a313b54cda2420af73fed1/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-teams.md) | 89 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b05a2e7d-9631-478b-9ce6-1062c9971de0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-workflow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8aeeb8aa582dca1581a313b54cda2420af73fed1/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-workflow.md) | 93 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e5c8c70f-6c05-47b2-91 [...]

2025-04-25 10:18 UTC, acrolinx-at-msft2 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/aba450c853bd993a2cf9d1918f97d00ebcb479b7/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1e0df51f-44e2-4f22-b555-1dfa26ebc519) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-anonymous-user.md](https://github.com/MicrosoftDocs/msteams-docs/blob/aba450c853bd993a2cf9d1918f97d00ebcb479b7/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-anonymous-user.md) | 88 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9ed1f4d6-e484-40e8-a16a-9c386a14bae5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-teams-meeting-stage.md](https://github.com/MicrosoftDocs/msteams-docs/blob/aba450c853bd993a2cf9d1918f97d00ebcb479b7/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-teams-meeting-stage.md) | 90 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/db560df7-bc26-42f7-8e63-983d22e0a254) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-extensible-conversation-for-meeting-chat.md](https://github.com/MicrosoftDocs/msteams-docs/blob/aba450c853bd993a2cf9d1918f97d00ebcb479b7/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-extensible-conversation-for-meeting-chat.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4809643b-bf79-4042-89e4-53ef95ba2411) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/aba450c853bd993a2cf9d1918f97d00ebcb479b7/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 88 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1e1b6f10-3811-4f78-b487-1c267d5d9650) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-concepts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/aba450c853bd993a2cf9d1918f97d00ebcb479b7/msteams-platform%2Fbots%2Fbot-concepts.md) | 91 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ab42e011-d5aa-4f85-a0b5-b86c8f33a8b4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/calls-and-meetings/registering-calling-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/aba450c853bd993a2cf9d1918f97d00ebcb479b7/msteams-platform%2Fbots%2Fcalls-and-meetings%2Fregistering-calling-bot.md) | 86 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/548830c1-6cf1-4168-a097-8ad7b95ac81c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/add-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/aba450c853bd993a2cf9d1918f97d00ebcb479b7/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fadd-authentication.md) | 89 | 67 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/63c4ed08-d9a7-42f1-aa7b-f1ac87825021) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/bot-sso-code.md](https://github.com/MicrosoftDocs/msteams-docs/blob/aba450c853bd993a2cf9d1918f97d00ebcb479b7/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-code.md) | 84 | 33 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a8a6f280-6047-4648-b379-49e461c5c73d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bot-configuration-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/aba450c853bd993a2cf9d1918f97d00ebcb479b7/msteams-platform%2Fbots%2Fhow-to%2Fbot-configuration-experience.md) | 91 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e3003a53-27cb-4f7b-9bf2-8388fc22a38d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/aba450c853bd993a2cf9d1918f97d00ebcb479b7/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 81 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0f70ac70-78ea-43a3-bd6a-d408f1cb5dbc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/prompt-suggestions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/aba450c853bd993a2cf9d1918f97d00ebcb479b7/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fprompt-suggestions.md) | 91 | 41 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2a416221-863b-4760-b700-e507341cbd79) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/aba450c853bd993a2cf9d1918f97d00ebcb479b7/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsubscribe-to-conversation-events.md) | 88 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1de698c3-6172-4a18-8fda-1b20f5d3ef88) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/streaming-ux.md](https://github.com/MicrosoftDocs/msteams-docs/blob/aba450c853bd993a2cf9d1918f97d00ebcb479b7/msteams-platform%2Fbots%2Fstreaming-ux.md) | 87 | 30 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/37d7659a-8eab-4597-b745-b1227b3594a9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/authentication/nested-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/aba450c853bd993a2cf9d1918f97d00ebcb479b7/msteams-platform%2Fconcepts%2Fauthentication%2Fnested-authentication.md) | 92 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6402d790-40df-44bb-85ba-7923c7b99bff) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/aba450c853bd993a2cf9d1918f97d00ebcb479b7/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fapps-localization.md) | 88 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1b0d10aa-849f-495a-a403-b370bb1efedb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-application.md](https://github.com/MicrosoftDocs/msteams-docs/blob/aba450c853bd993a2cf9d1918f97d00ebcb479b7/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-application.md) | 92 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a4250dbd-9bff-4bed-ae48-c35130d25901) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/aba450c853bd993a2cf9d1918f97d00ebcb479b7/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-teams.md) | 89 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/43b34be4-fb2a-426c-b94c-4e020f906730) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-workflow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/aba450c853bd993a2cf9d1918f97d00ebcb479b7/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-workflow.md) | 93 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7d85d61b-0493-42c4-89 [...]

2025-04-25 10:35 UTC, acrolinx-at-msft2 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a6d3ba192a5cf8348037926263b345bdf582acbb/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dc7f5d75-dd4f-44eb-8719-1e5c4550db08) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-anonymous-user.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a6d3ba192a5cf8348037926263b345bdf582acbb/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-anonymous-user.md) | 88 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bfc55fa0-76e6-4fea-8302-b13d5cf49bd2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-teams-meeting-stage.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a6d3ba192a5cf8348037926263b345bdf582acbb/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-teams-meeting-stage.md) | 90 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7338e82b-5250-49ae-be04-759ef2e75a77) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-extensible-conversation-for-meeting-chat.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a6d3ba192a5cf8348037926263b345bdf582acbb/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-extensible-conversation-for-meeting-chat.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6f7b5fc4-76d0-48f2-80e7-8e14feba6745) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a6d3ba192a5cf8348037926263b345bdf582acbb/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 88 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/88d8bef2-a4bb-4cde-8a07-67012829712d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-concepts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a6d3ba192a5cf8348037926263b345bdf582acbb/msteams-platform%2Fbots%2Fbot-concepts.md) | 91 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7fe1999e-839b-430a-9612-dc8bdf192aa1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/calls-and-meetings/registering-calling-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a6d3ba192a5cf8348037926263b345bdf582acbb/msteams-platform%2Fbots%2Fcalls-and-meetings%2Fregistering-calling-bot.md) | 86 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4005382b-9ec3-4cfe-9018-1b66f5b0c59e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/add-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a6d3ba192a5cf8348037926263b345bdf582acbb/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fadd-authentication.md) | 89 | 67 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/62da27fa-091b-4f51-bb11-c693202be01f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/bot-sso-code.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a6d3ba192a5cf8348037926263b345bdf582acbb/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-code.md) | 84 | 33 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d54565b7-a74b-493a-810d-93cc12464cd9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bot-configuration-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a6d3ba192a5cf8348037926263b345bdf582acbb/msteams-platform%2Fbots%2Fhow-to%2Fbot-configuration-experience.md) | 91 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/16de3de4-f3ff-4f6a-a370-83111500352e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a6d3ba192a5cf8348037926263b345bdf582acbb/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 81 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/11b517cb-0314-4df6-82ad-2cb6715a4ef0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/prompt-suggestions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a6d3ba192a5cf8348037926263b345bdf582acbb/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fprompt-suggestions.md) | 91 | 41 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6070ff06-f26c-4469-83d5-f9e2cbc0378e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a6d3ba192a5cf8348037926263b345bdf582acbb/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsubscribe-to-conversation-events.md) | 88 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dde27bdf-c013-422a-81e9-9a9a8853aac7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/streaming-ux.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a6d3ba192a5cf8348037926263b345bdf582acbb/msteams-platform%2Fbots%2Fstreaming-ux.md) | 87 | 30 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/81c8928f-8d44-4ecc-9377-7de6d85cad68) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/authentication/nested-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a6d3ba192a5cf8348037926263b345bdf582acbb/msteams-platform%2Fconcepts%2Fauthentication%2Fnested-authentication.md) | 92 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/efe65a57-09d7-4727-aa48-ebcb98b15a2c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a6d3ba192a5cf8348037926263b345bdf582acbb/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fapps-localization.md) | 88 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9c1c33e0-8b7d-4bf9-8309-1b4d2ca4b392) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-application.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a6d3ba192a5cf8348037926263b345bdf582acbb/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-application.md) | 92 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d1cf2201-4188-45cc-bf43-b89afe773ec8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a6d3ba192a5cf8348037926263b345bdf582acbb/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-teams.md) | 89 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a7a1fd96-1588-4f2a-a1bf-bbdda3c03047) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-workflow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a6d3ba192a5cf8348037926263b345bdf582acbb/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-workflow.md) | 93 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4d9c50c1-f1f3-45de-a6 [...]

2025-05-15 07:54 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d5e9560191b8828d7352ce96c252de86159beec1/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9d514d2b-eefa-402e-a902-2393d402b9da) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-anonymous-user.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d5e9560191b8828d7352ce96c252de86159beec1/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-anonymous-user.md) | 88 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/693c1afa-5e32-430f-98ca-d88a0c71a73f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-teams-meeting-stage.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d5e9560191b8828d7352ce96c252de86159beec1/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-teams-meeting-stage.md) | 90 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/30fea69a-6dfa-438e-963e-e175a57f2e34) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-extensible-conversation-for-meeting-chat.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d5e9560191b8828d7352ce96c252de86159beec1/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-extensible-conversation-for-meeting-chat.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/94b59102-04b3-4eed-a257-268769f67fe5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d5e9560191b8828d7352ce96c252de86159beec1/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 88 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/22e02621-8a68-4012-afab-ab3835f96bb5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-concepts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d5e9560191b8828d7352ce96c252de86159beec1/msteams-platform%2Fbots%2Fbot-concepts.md) | 91 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6526e576-58ba-46cc-85e2-e68291cfafdb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/calls-and-meetings/registering-calling-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d5e9560191b8828d7352ce96c252de86159beec1/msteams-platform%2Fbots%2Fcalls-and-meetings%2Fregistering-calling-bot.md) | 86 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/be94b5c6-db1f-4980-aee6-22fc6ab653a4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/add-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d5e9560191b8828d7352ce96c252de86159beec1/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fadd-authentication.md) | 89 | 67 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/01cb9850-0fe7-4361-bc30-2fec9cca0662) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/bot-sso-code.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d5e9560191b8828d7352ce96c252de86159beec1/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-code.md) | 85 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/134dadf7-830e-4d21-a5e5-210ebfe58d67) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bot-configuration-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d5e9560191b8828d7352ce96c252de86159beec1/msteams-platform%2Fbots%2Fhow-to%2Fbot-configuration-experience.md) | 91 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0b8e2135-bf29-4ca0-99a1-d2b686173d74) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d5e9560191b8828d7352ce96c252de86159beec1/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 81 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f60ede45-3044-4b2a-81ff-2a009cdf9463) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/prompt-suggestions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d5e9560191b8828d7352ce96c252de86159beec1/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fprompt-suggestions.md) | 91 | 41 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c83c8aa9-dfa8-40bf-bd6b-2a136d9abcc4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d5e9560191b8828d7352ce96c252de86159beec1/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsubscribe-to-conversation-events.md) | 88 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0ccc2cea-ebd2-424f-a00d-3a08a93ca627) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/streaming-ux.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d5e9560191b8828d7352ce96c252de86159beec1/msteams-platform%2Fbots%2Fstreaming-ux.md) | 85 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1787bc3c-55a0-4ebd-9d1a-eb618b4b2fe4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/authentication/nested-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d5e9560191b8828d7352ce96c252de86159beec1/msteams-platform%2Fconcepts%2Fauthentication%2Fnested-authentication.md) | 92 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/59e4edfe-da1b-46e9-a557-f68b6042f09c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d5e9560191b8828d7352ce96c252de86159beec1/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fapps-localization.md) | 88 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b32eb159-2af2-4db8-9a37-f6a86f7a5ac7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-application.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d5e9560191b8828d7352ce96c252de86159beec1/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-application.md) | 92 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/980caa48-0532-42c7-832e-605afccb2c30) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d5e9560191b8828d7352ce96c252de86159beec1/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-teams.md) | 89 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0664398f-c629-48af-b0e6-0a139b0c2bac) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-workflow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d5e9560191b8828d7352ce96c252de86159beec1/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-workflow.md) | 93 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7ad97f1e-ebaf-4e8e-ad [...]

2025-06-04 09:53 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bc2ea7b15dc99ee9971c67952684cb6fb91c3396/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/afbb8c1b-087a-4ad8-8806-3a329be750a6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-anonymous-user.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bc2ea7b15dc99ee9971c67952684cb6fb91c3396/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-anonymous-user.md) | 88 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/18f88551-7b6f-49f3-9584-a3e7d8a17b88) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-teams-meeting-stage.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bc2ea7b15dc99ee9971c67952684cb6fb91c3396/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-teams-meeting-stage.md) | 90 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dc3b2271-ec38-46d5-af77-2e20e0746b29) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-extensible-conversation-for-meeting-chat.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bc2ea7b15dc99ee9971c67952684cb6fb91c3396/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-extensible-conversation-for-meeting-chat.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e0f47aad-2809-4524-9bdd-4190af501a57) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bc2ea7b15dc99ee9971c67952684cb6fb91c3396/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 88 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/32088ac2-cbff-43b3-ac52-ddf80a45c45d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-concepts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bc2ea7b15dc99ee9971c67952684cb6fb91c3396/msteams-platform%2Fbots%2Fbot-concepts.md) | 91 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9b506783-f470-4aff-a20b-0877d562bf91) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/calls-and-meetings/registering-calling-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bc2ea7b15dc99ee9971c67952684cb6fb91c3396/msteams-platform%2Fbots%2Fcalls-and-meetings%2Fregistering-calling-bot.md) | 86 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6af5a146-b211-4680-afa9-4f42a4577d43) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/add-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bc2ea7b15dc99ee9971c67952684cb6fb91c3396/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fadd-authentication.md) | 89 | 67 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/070eef93-4e47-4757-96f8-05b0dfdc6526) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/bot-sso-code.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bc2ea7b15dc99ee9971c67952684cb6fb91c3396/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-code.md) | 85 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a8429fb2-c940-4f49-835e-7c18db44f521) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bot-configuration-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bc2ea7b15dc99ee9971c67952684cb6fb91c3396/msteams-platform%2Fbots%2Fhow-to%2Fbot-configuration-experience.md) | 91 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7b7a579d-b343-4071-a25e-f9b3abcacd9e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bc2ea7b15dc99ee9971c67952684cb6fb91c3396/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 81 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a80e4012-7824-46d9-ace9-17af1d75a59d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/prompt-suggestions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bc2ea7b15dc99ee9971c67952684cb6fb91c3396/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fprompt-suggestions.md) | 91 | 41 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7744d917-2f6b-4cd1-b9fe-263f4c6c0316) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bc2ea7b15dc99ee9971c67952684cb6fb91c3396/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsubscribe-to-conversation-events.md) | 88 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bbb9e4ad-6f9d-4abb-846f-44fd4b67f920) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/streaming-ux.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bc2ea7b15dc99ee9971c67952684cb6fb91c3396/msteams-platform%2Fbots%2Fstreaming-ux.md) | 85 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/686d482f-9656-4abf-a578-18ad0eff9ab4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/authentication/nested-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bc2ea7b15dc99ee9971c67952684cb6fb91c3396/msteams-platform%2Fconcepts%2Fauthentication%2Fnested-authentication.md) | 92 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/968a3ab5-5e8e-4cd4-aadf-0e9f97daad79) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bc2ea7b15dc99ee9971c67952684cb6fb91c3396/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fapps-localization.md) | 88 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/24bb6771-7594-4a02-8d5a-bb81e7ea5058) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-application.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bc2ea7b15dc99ee9971c67952684cb6fb91c3396/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-application.md) | 92 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2720c217-5122-4afc-8fd2-8fd10fc92f05) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bc2ea7b15dc99ee9971c67952684cb6fb91c3396/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-teams.md) | 89 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8c05befd-8ab2-416e-bbe2-461deef7f853) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-workflow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bc2ea7b15dc99ee9971c67952684cb6fb91c3396/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-workflow.md) | 93 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7d064340-ba7c-4874-a5 [...]

2025-06-10 07:16 UTC, SatyaReddy-MSFT approved these changes
Approved

2025-06-10 10:39 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4bd852794ce13ed18b00da068efc0e3b756019d7/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c3cc331d-eb73-424d-a632-0e9cacbc3a0e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-anonymous-user.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4bd852794ce13ed18b00da068efc0e3b756019d7/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-anonymous-user.md) | 88 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/89992506-90de-42b8-bfdc-c14b03e52a91) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-teams-meeting-stage.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4bd852794ce13ed18b00da068efc0e3b756019d7/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-teams-meeting-stage.md) | 90 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/533c462b-1ddc-4be7-82d1-7811c64cc8cf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-extensible-conversation-for-meeting-chat.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4bd852794ce13ed18b00da068efc0e3b756019d7/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-extensible-conversation-for-meeting-chat.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/94ad1e58-841d-4474-b31a-bee5e18f6197) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4bd852794ce13ed18b00da068efc0e3b756019d7/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 88 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0bf186bb-633d-49fc-a81b-3b6c611590ee) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-concepts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4bd852794ce13ed18b00da068efc0e3b756019d7/msteams-platform%2Fbots%2Fbot-concepts.md) | 91 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/686b717e-31b6-4aca-a5d6-e0468bdf50d2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/calls-and-meetings/registering-calling-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4bd852794ce13ed18b00da068efc0e3b756019d7/msteams-platform%2Fbots%2Fcalls-and-meetings%2Fregistering-calling-bot.md) | 86 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dacf3184-9954-4678-be7e-196b79eeec48) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/add-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4bd852794ce13ed18b00da068efc0e3b756019d7/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fadd-authentication.md) | 89 | 67 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4d0c3aeb-ac54-43e8-ba6f-aa57e120742d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/bot-sso-code.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4bd852794ce13ed18b00da068efc0e3b756019d7/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-code.md) | 85 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c4c799a9-a86f-45bb-a229-d6cd069f9870) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bot-configuration-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4bd852794ce13ed18b00da068efc0e3b756019d7/msteams-platform%2Fbots%2Fhow-to%2Fbot-configuration-experience.md) | 91 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/78ba6105-d821-4092-8f25-1210d54524e9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4bd852794ce13ed18b00da068efc0e3b756019d7/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 81 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1be1662f-7cb7-4882-ba15-d59f882b8fe9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/prompt-suggestions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4bd852794ce13ed18b00da068efc0e3b756019d7/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fprompt-suggestions.md) | 91 | 41 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f83a9bcf-d7d4-458b-a425-e62c44d741e5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4bd852794ce13ed18b00da068efc0e3b756019d7/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsubscribe-to-conversation-events.md) | 88 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/49e45405-368c-4531-8a01-d6590e413ad5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/streaming-ux.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4bd852794ce13ed18b00da068efc0e3b756019d7/msteams-platform%2Fbots%2Fstreaming-ux.md) | 85 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2c3abb7c-6669-4350-8747-1b18e95a2981) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/authentication/nested-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4bd852794ce13ed18b00da068efc0e3b756019d7/msteams-platform%2Fconcepts%2Fauthentication%2Fnested-authentication.md) | 92 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c91abfff-d686-49b3-b2cc-585497ebf1df) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4bd852794ce13ed18b00da068efc0e3b756019d7/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fapps-localization.md) | 88 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8088200f-5332-4188-a303-0439dbe8be7a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-application.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4bd852794ce13ed18b00da068efc0e3b756019d7/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-application.md) | 92 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b2d4221c-1124-4f0e-90eb-4b6bf276f15a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4bd852794ce13ed18b00da068efc0e3b756019d7/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-teams.md) | 89 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0f2f0fef-6f77-493e-bf56-2650a3500837) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-workflow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4bd852794ce13ed18b00da068efc0e3b756019d7/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-workflow.md) | 93 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/53421eee-4568-47ee-a4 [...]

2025-06-10 10:41 UTC, surbhigupta12 approved these changes

2025-06-10 10:41 UTC, merged