1382987 update content
MicrosoftDocs/msteams-docs pull request #2419
Opened 2020-12-04 09:21 UTC by Mahesh2516

Updated document with a new section. Please review

2020-12-04 09:22 UTC, opbld31 commented
Docs Build status updates of commit _[5745c52](https://github.com/MicrosoftDocs/msteams-docs/commits/5745c52751ffa3371d29ea4d19ad8287ef913414)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1382987-Update-content/msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases?branch=pr-en-us-2419) | [Details](#user-content-5fe43b86-dbb1867c)

<a id="5fe43b86-dbb1867c"></a>
### [msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1382987-Update-content/msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md)
 - **Line 209, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/microsoft-365-app-certification/docs/attestation' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 210, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/microsoft-365-app-certification/docs/userguide#3publisher-attestation-workflow' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 211, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/azure/active-directory/develop/troubleshoot-publisher-verification' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C4%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202012040921168211-2419%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=LjDwdb95cu1Qj3FnzsE93nTX%2BB2I2W3OQI231sY%2Bg9A%3D&st=2020-12-04T09%3A17%3A06Z&se=2021-01-04T09%3A22%3A06Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-04 09:29 UTC, opbld31 commented
Docs Build status updates of commit _[9c7e271](https://github.com/MicrosoftDocs/msteams-docs/commits/9c7e27106062cf9a61f84cd031d78c2359c74958)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1382987-Update-content/msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases?branch=pr-en-us-2419) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C4%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202012040928364988-2419%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=LUoByVDipNBvKH9nW643T4bX%2F5xmPBYt2VfCTHm2ijA%3D&st=2020-12-04T09%3A24%3A23Z&se=2021-01-04T09%3A29%3A23Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-07 18:51 UTC, laujan requested changes

2020-12-08 05:27 UTC, opbld31 commented
Docs Build status updates of commit _[af36a81](https://github.com/MicrosoftDocs/msteams-docs/commits/af36a819761d5aaeab0d58f62e140cf13318447b)_: 

:clock10: **Pending**: waiting for processors ([9](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 9 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-12-08 05:28 UTC, opbld31 commented
Docs Build status updates of commit _[af36a81](https://github.com/MicrosoftDocs/msteams-docs/commits/af36a819761d5aaeab0d58f62e140cf13318447b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1382987-Update-content/msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases?branch=pr-en-us-2419) | [Details](#user-content-5fe43b86-32ccdd73)

<a id="5fe43b86-32ccdd73"></a>
### [msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1382987-Update-content/msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md)
 - **Line 209, Column 16**: **[Warning-file-not-found]** `````Invalid file link: '../../microsoft-365-app-certification/docs/attestation'.`````
 - **Line 210, Column 14**: **[Warning-file-not-found]** `````Invalid file link: '../../microsoft-365-app-certification/docs/userguide'.`````
 - **Line 211, Column 16**: **[Warning-file-not-found]** `````Invalid file link: '../../azure/active-directory/develop/troubleshoot-publisher-verification'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C8%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202012080527337718-2419%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=c5WbZi2anAFonDfyIjZRS9Oo%2BzkkGzZebu00FzZxeF4%3D&st=2020-12-08T05%3A23%3A13Z&se=2021-01-08T05%3A28%3A13Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-08 05:42 UTC, opbld32 commented
Docs Build status updates of commit _[f84b546](https://github.com/MicrosoftDocs/msteams-docs/commits/f84b546f7daa48b459383244acaee2abd5400119)_: 

:clock10: **Pending**: waiting for processors ([9](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 9 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-12-08 05:43 UTC, opbld30 commented
Docs Build status updates of commit _[f84b546](https://github.com/MicrosoftDocs/msteams-docs/commits/f84b546f7daa48b459383244acaee2abd5400119)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1382987-Update-content/msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases?branch=pr-en-us-2419) | [Details](#user-content-5fe43b86-5378542f)

<a id="5fe43b86-5378542f"></a>
### [msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1382987-Update-content/msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md)
 - **Line 209, Column 16**: **[Warning-file-not-found]** `````Invalid file link: '../../microsoft-365-app-certification/docs/attestation'.`````
 - **Line 210, Column 27**: **[Warning-file-not-found]** `````Invalid file link: '../../microsoft-365-app-certification/docs/userguide'.`````
 - **Line 211, Column 16**: **[Warning-file-not-found]** `````Invalid file link: '../../azure/active-directory/develop/troubleshoot-publisher-verification'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C8%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202012080542414393-2419%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=n8ifCSZhknuVvo%2Fh08G4mbiVWHWuRtMuvg7axmyQN1w%3D&st=2020-12-08T05%3A38%3A34Z&se=2021-01-08T05%3A43%3A34Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-08 06:36 UTC, KirtiPereira commented on msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md
> +* Refer to the documentation for more details about the [attestation program](https://docs.microsoft.com/microsoft-365-app-certification/docs/attestation).
Hi @Mahesh2516. Please do the changes to the file path as discussed. Also, please incorporate the points shared by Priya for this requirement. Thank you.

2020-12-09 07:58 UTC, opbld33 commented
Docs Build status updates of commit _[4c33351](https://github.com/MicrosoftDocs/msteams-docs/commits/4c3335151714916184c1397e9d1e332a6fc844ee)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1382987-Update-content/msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases?branch=pr-en-us-2419) | [Details](#user-content-5fe43b86-c78d8391)

<a id="5fe43b86-c78d8391"></a>
### [msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1382987-Update-content/msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md)
 - **Line 209, Column 16**: **[Warning-file-not-found]** `````Invalid file link: '../../microsoft-365-app-certification/docs/attestation'.`````
 - **Line 210, Column 27**: **[Warning-file-not-found]** `````Invalid file link: '../../microsoft-365-app-certification/docs/userguide'.`````
 - **Line 210, Column 233**: **[Warning-file-not-found]** `````Invalid file link: 'appcert@microsoft.com'.`````
 - **Line 211, Column 16**: **[Warning-file-not-found]** `````Invalid file link: '../../azure/active-directory/develop/troubleshoot-publisher-verification'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C9%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202012090757238631-2419%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=F%2Ba%2BCs%2Ftt5vbWAJNKlmbX8xjD%2FkoYoDHUllPGyJ6vG4%3D&st=2020-12-09T07%3A53%3A22Z&se=2021-01-09T07%3A58%3A22Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-09 09:56 UTC, opbld31 commented
Docs Build status updates of commit _[6948ac9](https://github.com/MicrosoftDocs/msteams-docs/commits/6948ac9094b2bdb4013e498cd6db3d567a2a6b72)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1382987-Update-content/msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases?branch=pr-en-us-2419) | [Details](#user-content-5fe43b86-1ba08230)

<a id="5fe43b86-1ba08230"></a>
### [msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1382987-Update-content/msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md)
 - **Line 210, Column 228**: **[Warning-file-not-found]** `````Invalid file link: 'appcert@microsoft.com'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C9%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202012090955505062-2419%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=fZ%2FDJpEVfPNJPMMd%2FBItymz3SMoQa6RmHlAAajF3%2BWo%3D&st=2020-12-09T09%3A51%3A41Z&se=2021-01-09T09%3A56%3A41Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-09 10:00 UTC, opbld32 commented
Docs Build status updates of commit _[a1c9bf7](https://github.com/MicrosoftDocs/msteams-docs/commits/a1c9bf7df2381c932dafee460150907642d388d5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1382987-Update-content/msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases?branch=pr-en-us-2419) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C9%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202012090959450003-2419%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=f9LuqsUqM74kSWQW4A9i8EYO5HCM%2B9x6wTM0W%2BxTJvQ%3D&st=2020-12-09T09%3A55%3A35Z&se=2021-01-09T10%3A00%3A35Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-09 10:15 UTC, opbld32 commented
Docs Build status updates of commit _[886123f](https://github.com/MicrosoftDocs/msteams-docs/commits/886123f76fd1b6f185da530c096bdd48d92a0e49)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1382987-Update-content/msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases?branch=pr-en-us-2419) | [Details](#user-content-5fe43b86-e4ef1950)

<a id="5fe43b86-e4ef1950"></a>
### [msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1382987-Update-content/msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md)
 - **Line 212, Column 95**: **[Warning-file-not-found]** `````Invalid file link: '../../microsoft-365-app-certification/media/picture5.png'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C9%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202012091014388783-2419%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=vi7e5zyQSttTuqPCabHaZydoI56Wif7Bvq1fogkM4hM%3D&st=2020-12-09T10%3A10%3A29Z&se=2021-01-09T10%3A15%3A29Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-09 10:17 UTC, opbld30 commented
Docs Build status updates of commit _[1083031](https://github.com/MicrosoftDocs/msteams-docs/commits/108303174249964fcabd3bbcd5eb9e065a0266d1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1382987-Update-content/msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases?branch=pr-en-us-2419) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C9%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202012091016373776-2419%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=I1NI65jwv3aA%2FuJE07YYBzSKnaC0%2BzhEZ80h3NlpQ%2BQ%3D&st=2020-12-09T10%3A12%3A36Z&se=2021-01-09T10%3A17%3A36Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-09 10:19 UTC, opbld33 commented
Docs Build status updates of commit _[fd51921](https://github.com/MicrosoftDocs/msteams-docs/commits/fd51921f8f1a61e0f37169f363547b5edb09cd7f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1382987-Update-content/msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases?branch=pr-en-us-2419) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C9%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202012091018302505-2419%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=raYeM0CkKDD8FgtkEn7tMc57kvRcOYylAzv%2Be4HS%2Fd8%3D&st=2020-12-09T10%3A14%3A19Z&se=2021-01-09T10%3A19%3A19Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-09 10:22 UTC, Mahesh2516 commented on msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md
> +* Refer to the documentation for more details about the [attestation program](https://docs.microsoft.com/microsoft-365-app-certification/docs/attestation).
@laujan and @KirtiPereira, I have added the points and corrected the links. Please review.

2020-12-09 12:51 UTC, opbld31 commented
Docs Build status updates of commit _[f432265](https://github.com/MicrosoftDocs/msteams-docs/commits/f432265bec02cccbf015802128a04eab29648129)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1382987-Update-content/msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases?branch=pr-en-us-2419) | [Details](#user-content-5fe43b86-cd234bfa)

<a id="5fe43b86-cd234bfa"></a>
### [msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1382987-Update-content/msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md)
 - **Line 209, Column 16**: **[Warning-file-not-found]** `````Invalid file link: '../microsoft-365-app-certification/docs/attestation.md'.`````
 - **Line 210, Column 27**: **[Warning-file-not-found]** `````Invalid file link: '../microsoft-365-app-certification/docs/userguide'.`````
 - **Line 211, Column 16**: **[Warning-file-not-found]** `````Invalid file link: '../azure/active-directory/develop/troubleshoot-publisher-verification.md'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C9%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202012091250276656-2419%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ac4G8O6ZdBEPZOqK8y1Iw6BowTWWxGHk1cAT8%2BAW1J4%3D&st=2020-12-09T12%3A46%3A09Z&se=2021-01-09T12%3A51%3A09Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-09 21:52 UTC, opbld33 commented
Docs Build status updates of commit _[f5b4715](https://github.com/MicrosoftDocs/msteams-docs/commits/f5b47154abdb7f1c57258c5d3187e4d1afaf4060)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1382987-Update-content/msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases?branch=pr-en-us-2419) |
[wiki](https://github.com/MicrosoftDocs/msteams-docs/blob/1382987-Update-content/wiki) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C9%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202012092151238799-2419%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=hqf5QuR8EdrgjmRpPmR%2FOxOpV8RYOb%2FX6qvMy2X141I%3D&st=2020-12-09T21%3A47%3A09Z&se=2021-01-09T21%3A52%3A09Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-10 03:39 UTC, KirtiPereira reviewed
@Mahesh2516 - please change the label to ready-to-merge.

2020-12-10 03:57 UTC, Mahesh2516 commented
All updates have been done and it is ready-to-merge.

2020-12-10 04:06 UTC, opbld33 commented
Docs Build status updates of commit _[03885a3](https://github.com/MicrosoftDocs/msteams-docs/commits/03885a33e1a12ff64f701e978405efb2a682e90d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1382987-Update-content/msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases?branch=pr-en-us-2419) |
[wiki](https://github.com/MicrosoftDocs/msteams-docs/blob/1382987-Update-content/wiki) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C10%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202012100405063754-2419%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=HHeLfe4enS6jN2sMIYRu4krUw5jXxvuarFzUQd3EhIU%3D&st=2020-12-10T04%3A01%3A00Z&se=2021-01-10T04%3A06%3A00Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-10 19:08 UTC, laujan approved these changes

2020-12-10 19:08 UTC, opbld30 commented
Docs Build status updates of commit _[1278f49](https://github.com/MicrosoftDocs/msteams-docs/commits/1278f49a1fff6070921a5d36c177bc487846c91b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1382987-Update-content/msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases?branch=pr-en-us-2419) |
[wiki](https://github.com/MicrosoftDocs/msteams-docs/blob/1382987-Update-content/wiki) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C10%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202012101907586528-2419%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=b7oJkDvyrTe1wtFijDhGivde1QkCNOOO%2FPcOmoicFxc%3D&st=2020-12-10T19%3A03%3A42Z&se=2021-01-10T19%3A08%3A42Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-10 19:13 UTC, merged