Addition
MicrosoftDocs/msteams-docs pull request #2481
Opened 2020-12-17 11:08 UTC by Mahesh2516

Added properties. Please review.

2020-12-17 11:09 UTC, opbld30 commented
Docs Build status updates of commit _[f8126ef](https://github.com/MicrosoftDocs/msteams-docs/commits/f8126ef553ae2a07a3872528fad441fc25449251)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/tabs/how-to/access-teams-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1360657---Update-1318467-content-comments-/msteams-platform/tabs/how-to/access-teams-context.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/access-teams-context?branch=pr-en-us-2481) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C17%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202012171109000685-2481%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=K4C1i%2BBwiIqhMczgW%2FQYSx45LfFL%2BgxVF6Q1IUuSHtA%3D&st=2020-12-17T11%3A04%3A38Z&se=2021-01-17T11%3A09%3A38Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-18 14:43 UTC, KirtiPereira requested changes
@Mahesh2516 

"teamType": "The type of the team",
KP: Correct usage of article.

"frameContext": "The context where tab url is loaded (content, task, setting, remove, sidePanel)",
"isPSTNCallingAllowed": "Represents whether PSTN calling is allowed for the current logged in User",
"isCallingAllowed": "Represents whether calling is allowed for the current logged in User",
KP: Correct the capitalization in the above sentences.

Meeting Id
KP: Meeting ID

2020-12-21 09:43 UTC, opbld33 commented
Docs Build status updates of commit _[69dc8fc](https://github.com/MicrosoftDocs/msteams-docs/commits/69dc8fc4a868cf4dffe760c051853b20ea84220f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/tabs/how-to/access-teams-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1360657---Update-1318467-content-comments-/msteams-platform/tabs/how-to/access-teams-context.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/access-teams-context?branch=pr-en-us-2481) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C21%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202012210942553517-2481%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=A1JSUQWyy%2Fzx1taZmhzcEUfj94tT4PSJ44orwIDg8U0%3D&st=2020-12-21T09%3A38%3A49Z&se=2021-01-21T09%3A43%3A49Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-21 09:46 UTC, Mahesh2516 commented
@KirtiPereira I have made the necessary changes. Please review.

2020-12-21 15:02 UTC, opbld31 commented
Docs Build status updates of commit _[c697ad4](https://github.com/MicrosoftDocs/msteams-docs/commits/c697ad48899e3e0b3b22e0231d73ffda8f13788f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/tabs/how-to/access-teams-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1360657---Update-1318467-content-comments-/msteams-platform/tabs/how-to/access-teams-context.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/access-teams-context?branch=pr-en-us-2481) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C21%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202012211501219074-2481%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=y4jsah9XhWUJRBUIaAMqUbc2Z8vDf9GMSjbDujXb3AQ%3D&st=2020-12-21T14%3A57%3A47Z&se=2021-01-21T15%3A02%3A47Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-21 15:03 UTC, KirtiPereira submitted a review, later dismissed
Hi @surbhigupta12 - please approve and merge the PR.
Thank you.

2020-12-22 07:55 UTC, surbhigupta12 requested changes
Minor comments. Please verify.

2020-12-22 09:38 UTC, Mahesh2516 commented on msteams-platform/tabs/how-to/access-teams-context.md
> +    "frameContext": "The context where tab URL is loaded (content, task, setting, remove, sidePanel)",
added "for example"

2020-12-22 09:45 UTC, Mahesh2516 commented on msteams-platform/tabs/how-to/access-teams-context.md
> +    "userLicenseType": "The license type for a current user",
Corrected

2020-12-22 09:53 UTC, opbld32 commented
Docs Build status updates of commit _[3df4e63](https://github.com/MicrosoftDocs/msteams-docs/commits/3df4e638382f73ee4b2cff4ad1594bea998fe6ee)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/tabs/how-to/access-teams-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1360657---Update-1318467-content-comments-/msteams-platform/tabs/how-to/access-teams-context.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/access-teams-context?branch=pr-en-us-2481) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C22%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202012220952280023-2481%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=R6Q5mkZb9YeAPjNoZ87hfmxnef3ZUyPdAdahFFDI2tc%3D&st=2020-12-22T09%3A48%3A11Z&se=2021-01-22T09%3A53%3A11Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-22 10:08 UTC, surbhigupta12 reviewed
Minor comment. Please verify.

2020-12-22 10:08 UTC, surbhigupta12 commented on msteams-platform/tabs/how-to/access-teams-context.md
> +    "userLicenseType": "The license type for a current user",
Please fix the article usage.

2020-12-22 11:50 UTC, Mahesh2516 commented on msteams-platform/tabs/how-to/access-teams-context.md
> +    "teamSiteDomain": "The domain of the root SharePoint site associated with the team",
In this case, it has to be "the".

2020-12-22 12:01 UTC, opbld31 commented
Docs Build status updates of commit _[56d3f7d](https://github.com/MicrosoftDocs/msteams-docs/commits/56d3f7d069db957865da846b43004f442aee6b79)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/tabs/how-to/access-teams-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1360657---Update-1318467-content-comments-/msteams-platform/tabs/how-to/access-teams-context.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/access-teams-context?branch=pr-en-us-2481) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C22%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202012221200137849-2481%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=94FpUQGy7nO6P0VAdL0UpTm95uFbOkQhRgrPxBt01Cc%3D&st=2020-12-22T11%3A56%3A08Z&se=2021-01-22T12%3A01%3A08Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-22 12:16 UTC, KirtiPereira approved these changes
Hi @surbhigupta12 - please approve and merge the PR.
Thank you.

2020-12-22 12:49 UTC, surbhigupta12 approved these changes
Thank you for incorporating the comments. Approving the PR.

2020-12-22 12:52 UTC, merged