Added Gitter.IM to the options to communicate
MicrosoftDocs/msteams-docs pull request #2492
Opened 2020-12-21 12:03 UTC by Wajeed-msft

2020-12-21 12:04 UTC, opbld31 commented
Docs Build status updates of commit _[1672dab](https://github.com/MicrosoftDocs/msteams-docs/commits/1672dabb2f23a5d98359fec7b1a1ee22bec03dbc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Wajeed-msft-added-gitter/msteams-platform/feedback.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/feedback?branch=pr-en-us-2492) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C21%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202012211203117608-2492%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ZxmEfqCfEq393cTDFgKzlWaw32BpL0nSQnkvYuZV2hc%3D&st=2020-12-21T11%3A59%3A35Z&se=2021-01-21T12%3A04%3A35Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-21 12:52 UTC, opbld33 commented
Docs Build status updates of commit _[aa670b9](https://github.com/MicrosoftDocs/msteams-docs/commits/aa670b99cad430365bec35b6fcd2cc7a404234a1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Wajeed-msft-added-gitter/msteams-platform/feedback.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/feedback?branch=pr-en-us-2492) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C21%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202012211252011138-2492%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=UrA0aiqVgjp88WDkP8YFZIIXoJ6mXXZoemmIvuP0K4U%3D&st=2020-12-21T12%3A47%3A35Z&se=2021-01-21T12%3A52%3A35Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-21 14:32 UTC, opbld32 commented
Docs Build status updates of commit _[dc3a86b](https://github.com/MicrosoftDocs/msteams-docs/commits/dc3a86b70aa59d04f95a90c1068d7abc7f32289c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Wajeed-msft-added-gitter/msteams-platform/feedback.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/feedback?branch=pr-en-us-2492) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C21%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202012211432021716-2492%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=NDAjQBG2RX0LeLUvuzHvHMF9b7tkw%2BQS8P3kCDzI29Y%3D&st=2020-12-21T14%3A27%3A33Z&se=2021-01-21T14%3A32%3A33Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-21 15:17 UTC, surbhigupta12 requested changes
Minor comment. Please verify and update.

2020-12-21 15:17 UTC, surbhigupta12 commented on msteams-platform/feedback.md
> +|       **Community chat group**        | Informal community chat room for [Microsoft Teams app developers](https://gitter.im/OfficeDev/MicrosoftTeamsAppDev)|
To maintain parallelism, suggest rephrasing to the following:

```suggestion
|       **Community chat group**        | Select **SIGN IN TO START TALKING** to join the informal community chat room for [Microsoft Teams app developers](https://gitter.im/OfficeDev/MicrosoftTeamsAppDev).|
```

2020-12-21 15:55 UTC, opbld30 commented
Docs Build status updates of commit _[d2943ab](https://github.com/MicrosoftDocs/msteams-docs/commits/d2943abf54701f92d02d4bac32433d85c09c8466)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Wajeed-msft-added-gitter/msteams-platform/feedback.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/feedback?branch=pr-en-us-2492) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C21%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202012211554368069-2492%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=AYbkHnbfycVzVaSVnC1Muhtlft8zG4mzWe845eD0JQ4%3D&st=2020-12-21T15%3A50%3A09Z&se=2021-01-21T15%3A55%3A09Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-21 16:13 UTC, surbhigupta12 approved these changes
The changes seem fine. Approving it.

2020-12-21 16:22 UTC, opbld30 commented
Docs Build status updates of commit _[89cc682](https://github.com/MicrosoftDocs/msteams-docs/commits/89cc682fb51fdd7515410acaebc0c7c5a61e25d6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Wajeed-msft-added-gitter/msteams-platform/feedback.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/feedback?branch=pr-en-us-2492) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C21%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202012211621414202-2492%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=DMoxgWz4jRvJhdK%2FpyOGlo44p0pbCqbx6Qv9Drcbcqk%3D&st=2020-12-21T16%3A17%3A25Z&se=2021-01-21T16%3A22%3A25Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-21 16:24 UTC, surbhigupta12 requested changes
Minor change, please verify.

2020-12-21 16:24 UTC, surbhigupta12 commented on msteams-platform/feedback.md
> +|       **Community chat group**        | Select **SIGN IN TO START TALKING** to join the informal community chat room for [Microsoft Teams app developers](https://gitter.im/OfficeDev/MicrosoftTeamsA
Please change to:

```suggestion
|       **Community chat group**        | Select **SIGN IN TO START TALKING** to join the informal community chat room for [Microsoft Teams app developers](https://gitter.im/OfficeDev/MicrosoftTeamsAppDev), if you are logging in for the first time. Select **JOIN ROOM**, if you are already logged in. |
```

2020-12-22 03:43 UTC, KirtiPereira submitted a review, later dismissed
@surbhigupta12 - approved

2020-12-22 04:05 UTC, opbld33 commented
Docs Build status updates of commit _[adb1eac](https://github.com/MicrosoftDocs/msteams-docs/commits/adb1eacc571759195309d79f33eecf3ef87e1d88)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Wajeed-msft-added-gitter/msteams-platform/feedback.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/feedback?branch=pr-en-us-2492) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C22%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202012220404582043-2492%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=JkwNqkMm0YsgZQYJPegwJ97Lmv65NNNR21tSzMw4wfk%3D&st=2020-12-22T04%3A00%3A54Z&se=2021-01-22T04%3A05%3A54Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-22 04:06 UTC, surbhigupta12 approved these changes
Thank you for incorporating the comments.

2020-12-22 04:06 UTC, surbhigupta12 commented
Merging this file.

2020-12-22 04:06 UTC, merged