[Tabs][Review and update content][1427069]
MicrosoftDocs/msteams-docs pull request #2524
Opened 2020-12-30 13:00 UTC by Rajeshwari-v

Formatting changes. Please review

2020-12-30 13:01 UTC, opbld31 commented
Docs Build status updates of commit _[5174c7f](https://github.com/MicrosoftDocs/msteams-docs/commits/5174c7faa99da4576d4af89c23fc2ff1e890cea9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/tabs-Review-and-update-content-1427069/msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/configuration-page?branch=pr-en-us-2524) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C30%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202012301300080445-2524%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=IZ1YSQwtG%2Bl2e3op3XvO2EG9YlAI%2FDgKrhYbE7NIhvE%3D&st=2020-12-30T12%3A56%3A07Z&se=2021-01-30T13%3A01%3A07Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-31 05:40 UTC, opbld31 commented
Docs Build status updates of commit _[e046c97](https://github.com/MicrosoftDocs/msteams-docs/commits/e046c97be724828a3a03624e52f0fb7faec9a705)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/tabs-Review-and-update-content-1427069/msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/configuration-page?branch=pr-en-us-2524) | [Details](#user-content-536f405a-f4025dd8)

<a id="536f405a-f4025dd8"></a>
### [msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/tabs-Review-and-update-content-1427069/msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md)
 - **Line 93, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /javascript/api/@microsoft/teams-js/context?view=msteams-client-js-latest`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C31%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202012310540038732-2524%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=M7RrtT8CypG8sOUzwgrAWTZ96YXVVEhDE5RbXMGG2iA%3D&st=2020-12-31T05%3A35%3A37Z&se=2021-01-31T05%3A40%3A37Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-31 05:50 UTC, opbld32 commented
Docs Build status updates of commit _[214a416](https://github.com/MicrosoftDocs/msteams-docs/commits/214a4161ed742773b353ee1f398a9bc6c1c50182)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/tabs-Review-and-update-content-1427069/msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/configuration-page?branch=pr-en-us-2524) | [Details](#user-content-536f405a-6cd2fa71)

<a id="536f405a-6cd2fa71"></a>
### [msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/tabs-Review-and-update-content-1427069/msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md)
 - **Line 93, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /javascript/api/@microsoft/teams-js/context?view=msteams-client-js-latest`````
 - **Line 136, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /javascript/api/@microsoft/teams-js/context?view=msteams-client-js-latest`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C31%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202012310550181580-2524%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=dTgRywd%2Bye8UY0%2FrPlxayPYa27NcrVzUxzZ63xEOZTA%3D&st=2020-12-31T05%3A45%3A49Z&se=2021-01-31T05%3A50%3A49Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-31 07:15 UTC, opbld33 commented
Docs Build status updates of commit _[d000f22](https://github.com/MicrosoftDocs/msteams-docs/commits/d000f22ee2a3da1c840f419ac0ae6460992aaf43)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/tabs-Review-and-update-content-1427069/msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/configuration-page?branch=pr-en-us-2524) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C31%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202012310714277095-2524%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ppV1gh3yXMEzAzwqJEYx6yLKYwkaExwh98q%2B9VvkY4g%3D&st=2020-12-31T07%3A10%3A01Z&se=2021-01-31T07%3A15%3A01Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-05 08:44 UTC, opbld33 commented
Docs Build status updates of commit _[7d34446](https://github.com/MicrosoftDocs/msteams-docs/commits/7d3444653e554c5c534cdc2173c3811ee7af0ef8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/tabs-Review-and-update-content-1427069/msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/configuration-page?branch=pr-en-us-2524) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C5%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202101050843341952-2524%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=U%2FS5bn2BOlF9KEGD3esHdD1OrDjD6JZ87u0PGugPreY%3D&st=2021-01-05T08%3A39%3A14Z&se=2021-02-05T08%3A44%3A14Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-06 12:18 UTC, opbld31 commented
Docs Build status updates of commit _[630636f](https://github.com/MicrosoftDocs/msteams-docs/commits/630636f5e17cf7356dc5f473f50ba2251db766e7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/tabs-Review-and-update-content-1427069/msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/configuration-page?branch=pr-en-us-2524) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C6%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202101061217506139-2524%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=tbN3MNm3NmklGFwAL0M1WuPJKgzJc0aPpimVIu%2FXB9w%3D&st=2021-01-06T12%3A13%3A24Z&se=2021-02-06T12%3A18%3A24Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-11 12:39 UTC, KirtiPereira requested changes

2021-01-12 09:39 UTC, opbld32 commented
Docs Build status updates of commit _[1ad0d21](https://github.com/MicrosoftDocs/msteams-docs/commits/1ad0d214ce4a94940a64d678413b627f81669118)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/tabs-Review-and-update-content-1427069/msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/configuration-page?branch=pr-en-us-2524) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C12%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202101120938498500-2524%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=6V7%2FiBGsGd7RwK31n82LmhxgH2Q7HWEnRFVffrsWUh0%3D&st=2021-01-12T09%3A34%3A37Z&se=2021-02-12T09%3A39%3A37Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-12 09:47 UTC, Rajeshwari-v commented on msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md
> +A configuration page is a special type of [content page](content-page.md) that allows your users to configure some aspects of Microsoft Teams app. It allows you to collect the information from your u
Content page is in TOC under Tabs>how to > create tab pages > create a content page

2021-01-12 09:55 UTC, opbld30 commented
Docs Build status updates of commit _[43a6658](https://github.com/MicrosoftDocs/msteams-docs/commits/43a665893aa11bddce0199cbc43c60b56eefd71e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/tabs-Review-and-update-content-1427069/msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/configuration-page?branch=pr-en-us-2524) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C12%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202101120954337835-2524%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=GSS3eiorqWF%2BOB1kqMN%2FwzUR6As16zO1USxQ8TCplvw%3D&st=2021-01-12T09%3A50%3A20Z&se=2021-02-12T09%3A55%3A20Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-12 10:07 UTC, opbld31 commented
Docs Build status updates of commit _[74b2465](https://github.com/MicrosoftDocs/msteams-docs/commits/74b24659d0376a7a5cc1e3547e3d3f41ce42ec5d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/tabs-Review-and-update-content-1427069/msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/configuration-page?branch=pr-en-us-2524) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C12%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202101121006155008-2524%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=0CfqVQwarYQZUsO01ELlNi6Z09PR57Sxx1ahRAC%2FYQY%3D&st=2021-01-12T10%3A02%3A03Z&se=2021-02-12T10%3A07%3A03Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-12 10:07 UTC, opbld31 commented
Docs Build status updates of commit _[33da681](https://github.com/MicrosoftDocs/msteams-docs/commits/33da681403595b3dd0520ee75fff5b89345b5ccf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/tabs-Review-and-update-content-1427069/msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/configuration-page?branch=pr-en-us-2524) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C12%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202101121007153122-2524%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Bj5bgIzrXiVpMLFXo4kVm822IHaqXmEOj4%2BOBhpbTJY%3D&st=2021-01-12T10%3A02%3A50Z&se=2021-02-12T10%3A07%3A50Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-12 10:12 UTC, opbld30 commented
Docs Build status updates of commit _[419d489](https://github.com/MicrosoftDocs/msteams-docs/commits/419d4892cdd06f14010397d46829fd03f287ef9b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/tabs-Review-and-update-content-1427069/msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/configuration-page?branch=pr-en-us-2524) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C12%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202101121011282764-2524%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=0hftJAH4GsClHfeQhPiNchMczOLsueylcMMTolkzoQo%3D&st=2021-01-12T10%3A06%3A59Z&se=2021-02-12T10%3A11%3A59Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-12 10:12 UTC, opbld32 commented
Docs Build status updates of commit _[1f27959](https://github.com/MicrosoftDocs/msteams-docs/commits/1f2795916e3786375c7d4bdf39e6803fe1433cb7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/tabs-Review-and-update-content-1427069/msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/configuration-page?branch=pr-en-us-2524) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C12%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202101121012051583-2524%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=t6CQDuYy7tQSDbkIfS2IG57mGzhKxpXjpolQAkmG44s%3D&st=2021-01-12T10%3A07%3A36Z&se=2021-02-12T10%3A12%3A36Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-12 10:16 UTC, opbld31 commented
Docs Build status updates of commit _[cdb5db4](https://github.com/MicrosoftDocs/msteams-docs/commits/cdb5db4d1144ea9411ff871693265d4038f6ea09)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/tabs-Review-and-update-content-1427069/msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/configuration-page?branch=pr-en-us-2524) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C12%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202101121015369319-2524%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=6WR%2Fajwq1rqMrZ0up44eACv6zuZJEPlyTizdmMTq%2FPY%3D&st=2021-01-12T10%3A11%3A09Z&se=2021-02-12T10%3A16%3A09Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-12 10:18 UTC, opbld30 commented
Docs Build status updates of commit _[4b84230](https://github.com/MicrosoftDocs/msteams-docs/commits/4b84230c092d241f7e7eb6dd719c4ecd9408ea0f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/tabs-Review-and-update-content-1427069/msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/configuration-page?branch=pr-en-us-2524) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C12%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202101121018157645-2524%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=c%2BFeFE5CE%2Fpg9tNh7aDnGUFY0IwzGcs46kRtyyZugBU%3D&st=2021-01-12T10%3A13%3A52Z&se=2021-02-12T10%3A18%3A52Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-12 10:21 UTC, opbld30 commented
Docs Build status updates of commit _[5dee004](https://github.com/MicrosoftDocs/msteams-docs/commits/5dee0043ab606426a48bf269c1ec76a029849f99)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/tabs-Review-and-update-content-1427069/msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/configuration-page?branch=pr-en-us-2524) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C12%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202101121020284543-2524%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=qb%2FGoDYj6bs4ObldHFb7k2dFEF1FwvGyEod7kdQ%2BEMk%3D&st=2021-01-12T10%3A16%3A04Z&se=2021-02-12T10%3A21%3A04Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-12 10:57 UTC, opbld32 commented
Docs Build status updates of commit _[bd4dc50](https://github.com/MicrosoftDocs/msteams-docs/commits/bd4dc50f225ca6e5a14bfe3786640aa15d603819)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/tabs-Review-and-update-content-1427069/msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/configuration-page?branch=pr-en-us-2524) | [Details](#user-content-536f405a-73beb880)

<a id="536f405a-73beb880"></a>
### [msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/tabs-Review-and-update-content-1427069/msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md)
 - **Line 119, Column 1**: **[Warning-[merge-conflict](https://aka.ms/merge-conflict)]** `````File contains merge conflict markers.`````
 - **Line 121, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** 
`````
Multiple H1s(H1 '<<<<<<< Updated upstream
After your page uploads, the Teams updates the query string placeholders with relevant values. Include logic in your configuration page to retrieve and use those values. For more information on working with URL query strings, see URLSearchParams in MDN web docs. The following example describes the way to extract a value from the  property:') are not allowed. You can only have one top-level heading.
`````
 - **Line 165, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** 
`````
Multiple H1s(H1 '<<<<<<< Updated upstream
Supported removal options further refine the user experience. Allow users to modify, reconfigure, or rename a group or channel tab by setting your manifest's  property to . In addition, indicate what happens to the content when a tab is removed by including a removal options page in the app and setting a value for the  property in the   configuration, see Mobile clients. User can uninstall the Personal tabs but cannot modify it. For more information, see Create a removal page for your tab.') are not allowed. You can only have one top-level heading.
`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C12%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202101121057209931-2524%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=YwJGn9bt%2BRhOW6fnY4wXzpcMo4shdvjvYPv7rYfEYl8%3D&st=2021-01-12T10%3A52%3A52Z&se=2021-02-12T10%3A57%3A52Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-12 11:08 UTC, opbld32 commented
Docs Build status updates of commit _[bb59b0a](https://github.com/MicrosoftDocs/msteams-docs/commits/bb59b0a5614d6a031f17374b0c098f46688be49c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/tabs-Review-and-update-content-1427069/msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/configuration-page?branch=pr-en-us-2524) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C12%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202101121107493408-2524%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=qY2q9nt8bfI5lYHcrileJVQjd5KnuaarbwLDYME5eow%3D&st=2021-01-12T11%3A03%3A21Z&se=2021-02-12T11%3A08%3A21Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-15 05:42 UTC, KirtiPereira requested changes
@Rajeshwari-v - please do a thorough self-review.
Following is an example of what I see in the review page:
..., see [Mobile clients](./../tabs/how-to/create-tab-pages/configuration-page.md#Mobile clients).

2021-01-18 08:52 UTC, Nikitha-MSFT approved these changes
Reviewed and  approved

2021-01-18 10:43 UTC, KirtiPereira approved these changes
Approved

2021-01-18 10:46 UTC, surbhigupta12 approved these changes
Approving the PR.

2021-01-18 10:47 UTC, merged