Virtual Rounding app template
MicrosoftDocs/msteams-docs pull request #2541
Opened 2021-01-01 18:14 UTC by adityachallapally

2021-01-01 18:14 UTC, opbld30 commented
Docs Build status updates of commit _[b93b965](https://github.com/MicrosoftDocs/msteams-docs/commits/b93b965c5a382aaae463349e6052204a13a9df51)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/samples/app-templates.md](https://github.com/MicrosoftDocs/msteams-docs/blob/adityachallapally-patch-2/msteams-platform/samples/app-templates.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/samples/app-templates?branch=pr-en-us-2541) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C1%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202101011814250179-2541%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=o9nhaDYzzGG5gHyY7cNRJEvTVAd3y%2BN7w44AibdwS%2Fw%3D&st=2021-01-01T18%3A09%3A57Z&se=2021-02-01T18%3A14%3A57Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-04 07:17 UTC, surbhigupta12 requested changes
Please verify and update the comments.

2021-01-04 17:02 UTC, opbld31 commented
Docs Build status updates of commit _[86b8711](https://github.com/MicrosoftDocs/msteams-docs/commits/86b87112c19b5888bd93fca81e36f09306359f53)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/samples/app-templates.md](https://github.com/MicrosoftDocs/msteams-docs/blob/adityachallapally-patch-2/msteams-platform/samples/app-templates.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/samples/app-templates?branch=pr-en-us-2541) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C4%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202101041701293100-2541%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=QzpS5%2BjlP6vHuURIrAhHln%2FeE7W4m%2FEzkHj88pvsX3k%3D&st=2021-01-04T16%3A57%3A08Z&se=2021-02-04T17%3A02%3A08Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-04 17:02 UTC, opbld30 commented
Docs Build status updates of commit _[fa29488](https://github.com/MicrosoftDocs/msteams-docs/commits/fa294887c1688076522b488406ad4ae82511f469)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/samples/app-templates.md](https://github.com/MicrosoftDocs/msteams-docs/blob/adityachallapally-patch-2/msteams-platform/samples/app-templates.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/samples/app-templates?branch=pr-en-us-2541) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C4%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202101041701431324-2541%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=x0QgmGiTrg8xqSlm1Tl6TAnYJODWu%2FYx%2F%2FP77JiWWy4%3D&st=2021-01-04T16%3A57%3A51Z&se=2021-02-04T17%3A02%3A51Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-04 18:09 UTC, opbld32 commented
Docs Build status updates of commit _[b51dd7a](https://github.com/MicrosoftDocs/msteams-docs/commits/b51dd7ade9d085d81daa863486783e96ad6d668e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/samples/app-templates.md](https://github.com/MicrosoftDocs/msteams-docs/blob/adityachallapally-patch-2/msteams-platform/samples/app-templates.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/samples/app-templates?branch=pr-en-us-2541) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C4%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202101041808448211-2541%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=UwGQANn99l61DN4syiRUXnWs4SdBQQHn%2Fo1D0CTs4aw%3D&st=2021-01-04T18%3A04%3A25Z&se=2021-02-04T18%3A09%3A25Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-05 08:20 UTC, surbhigupta12 reviewed
Minor comment, please update.

2021-01-05 08:20 UTC, surbhigupta12 commented on msteams-platform/samples/app-templates.md
> +This is the Virtual Rounding solution referenced in the Microsoft Health and Life Sciences [blog post](https://aka.ms/teamsvirtualrounding).
Suggest rephrasing this to:

```suggestion
The Virtual Rounding solution is also referenced in the Microsoft Health and Life Sciences [blog post](https://aka.ms/teamsvirtualrounding).
```

2021-01-05 15:33 UTC, opbld30 commented
Docs Build status updates of commit _[f0f3f31](https://github.com/MicrosoftDocs/msteams-docs/commits/f0f3f31e5cedea6524cb82c2f516aa127dbb7b82)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/samples/app-templates.md](https://github.com/MicrosoftDocs/msteams-docs/blob/adityachallapally-patch-2/msteams-platform/samples/app-templates.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/samples/app-templates?branch=pr-en-us-2541) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C5%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202101051532554580-2541%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=giD6J9%2F0cgEr7BGJXAQVx3hufiZE9AVpunN5w9tXAds%3D&st=2021-01-05T15%3A28%3A36Z&se=2021-02-05T15%3A33%3A36Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-05 15:35 UTC, surbhigupta12 approved these changes
Thank you for incorporating the comments. Approving the PR.

2021-01-06 03:39 UTC, KirtiPereira approved these changes
Approving the PR for merging.
Thank you.

2021-01-06 03:50 UTC, surbhigupta12 approved these changes
Changes seem fine. Approving the PR.

2021-01-06 03:50 UTC, merged