[Bots][Reviewandupdatecontent][1427059]
MicrosoftDocs/msteams-docs pull request #2588
Opened 2021-01-11 06:27 UTC by v-rodriguezd

Reviewed document for grammar and language issues. Please review.

2021-01-11 06:28 UTC, opbld31 commented
Docs Build status updates of commit _[f2901f8](https://github.com/MicrosoftDocs/msteams-docs/commits/f2901f8940c4dddda182fee4bef57ed697420718)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1427059-Reviewandupdatecontent/msteams-platform/bots/bot-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-basics?branch=pr-en-us-2588) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C11%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202101110627211837-2588%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=X4RyhKdyFRT0Xu5kLEr1HlTdwMkHXD7ivlQzwR1oozc%3D&st=2021-01-11T06%3A23%3A07Z&se=2021-02-11T06%3A28%3A07Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-15 11:05 UTC, KirtiPereira requested changes
@v-rodriguezd - Have shared my comments. Please verify and commit the suggestions.
Thank you.

2021-01-15 11:05 UTC, KirtiPereira commented on msteams-platform/bots/bot-basics.md
> +The invoke activities listed in this section are for conversational bots in Teams. The Bot Framework SDK also supports invoke activities specific to messaging extensions. For more information see [Wh
```Suggestion
The invoke activities listed in this section are for conversational bots in Teams. The Bot Framework SDK also supports invoke activities specific to messaging extensions. For more information, see [What are messaging extensions](https://aka.ms/azure-bot-what-are-messaging-extensions).
```

2021-01-15 12:05 UTC, opbld32 commented
Docs Build status updates of commit _[6f76734](https://github.com/MicrosoftDocs/msteams-docs/commits/6f767343a5a36ffbbb9c2bc20abc7c28acbd9522)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1427059-Reviewandupdatecontent/msteams-platform/bots/bot-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-basics?branch=pr-en-us-2588) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C15%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202101151204271597-2588%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=IunxUHMmXTv0U4%2FLBEAP%2FsX9kdDGt1cEiohEIqfgmcQ%3D&st=2021-01-15T12%3A00%3A37Z&se=2021-02-15T12%3A05%3A37Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-20 08:54 UTC, opbld30 commented
Docs Build status updates of commit _[a8904de](https://github.com/MicrosoftDocs/msteams-docs/commits/a8904de0c22ddac30ab06914cb1e399ce86f2d74)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1427059-Reviewandupdatecontent/msteams-platform/bots/bot-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-basics?branch=pr-en-us-2588) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C20%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202101200853430192-2588%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=XlqatllWo%2Fur6sSV6hc3eZQ9wUpaGQVv%2BYckIwV7AlE%3D&st=2021-01-20T08%3A49%3A28Z&se=2021-02-20T08%3A54%3A28Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-25 04:22 UTC, Manish-MSFT approved these changes
Everything looks good, no changes from my side.

2021-01-27 05:13 UTC, KirtiPereira approved these changes
Approved for merging.

2021-01-27 06:13 UTC, surbhigupta12 approved these changes
Approving this PR.

2021-01-27 06:14 UTC, merged