[Messaging-extensions][Add-sections][1439845]
MicrosoftDocs/msteams-docs pull request #2597
Opened 2021-01-12 08:45 UTC by Rajeshwari-v

Added missing sections. Please review.

2021-01-12 08:46 UTC, opbld32 commented
Docs Build status updates of commit _[9fa40b6](https://github.com/MicrosoftDocs/msteams-docs/commits/9fa40b6f18c1f34fb52a981f5e9136cbb49e6984)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/messaging-extensions/how-to/action-commands/create-task-module.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Messaging-extensions-Add-sections-1439845/msteams-platform/messaging-extensions/how-to/action-commands/create-task-module.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/action-commands/create-task-module?branch=pr-en-us-2597) |
[msteams-platform/messaging-extensions/how-to/create-messaging-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Messaging-extensions-Add-sections-1439845/msteams-platform/messaging-extensions/how-to/create-messaging-extension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/create-messaging-extension?branch=pr-en-us-2597) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C12%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202101120845523214-2597%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=zn6UgmoLFJqm%2BYn%2Bgnhp0Xrw3%2FSBnS6hF43iHePyQaY%3D&st=2021-01-12T08%3A41%3A24Z&se=2021-02-12T08%3A46%3A24Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-12 09:49 UTC, KirtiPereira requested changes
Thorough self-review required.

2021-01-12 12:21 UTC, opbld33 commented
Docs Build status updates of commit _[31723c4](https://github.com/MicrosoftDocs/msteams-docs/commits/31723c411743da292549c7f4f4b24ff8c684f66f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/messaging-extensions/how-to/action-commands/create-task-module.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Messaging-extensions-Add-sections-1439845/msteams-platform/messaging-extensions/how-to/action-commands/create-task-module.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/action-commands/create-task-module?branch=pr-en-us-2597) |
[msteams-platform/messaging-extensions/how-to/create-messaging-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Messaging-extensions-Add-sections-1439845/msteams-platform/messaging-extensions/how-to/create-messaging-extension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/create-messaging-extension?branch=pr-en-us-2597) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C12%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202101121220526196-2597%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=UfzuV2f80dkWtege5Oc58kxeXnF%2BQB%2Fke4LLLqU1%2F2s%3D&st=2021-01-12T12%3A16%3A25Z&se=2021-02-12T12%3A21%3A25Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-12 13:07 UTC, opbld30 commented
Docs Build status updates of commit _[75577d1](https://github.com/MicrosoftDocs/msteams-docs/commits/75577d1537fb95bc255e58e6ecdec8a8a21d0547)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/messaging-extensions/how-to/action-commands/create-task-module.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Messaging-extensions-Add-sections-1439845/msteams-platform/messaging-extensions/how-to/action-commands/create-task-module.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/action-commands/create-task-module?branch=pr-en-us-2597) |
[msteams-platform/messaging-extensions/how-to/create-messaging-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Messaging-extensions-Add-sections-1439845/msteams-platform/messaging-extensions/how-to/create-messaging-extension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/create-messaging-extension?branch=pr-en-us-2597) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C12%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202101121307034491-2597%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=5ZUgXYHGESMdexReQiWNfsveAOvaPNaOFJupPIm6eaY%3D&st=2021-01-12T13%3A02%3A37Z&se=2021-02-12T13%3A07%3A37Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-13 07:52 UTC, opbld33 commented
Docs Build status updates of commit _[d35fc02](https://github.com/MicrosoftDocs/msteams-docs/commits/d35fc02a6d566101dbfacd35d49447e492f021a8)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-b5fa7569)

<a id="b5fa7569"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C13%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202101130752087578-2597%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=729YMy04IyAVsZCI8Oj1WdunpMgjTtVTyggvF6l9ge4%3D&st=2021-01-13T07%3A47%3A23Z&se=2021-02-13T07%3A52%3A23Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-13 08:44 UTC, opbld32 commented
Docs Build status updates of commit _[4cf0c0c](https://github.com/MicrosoftDocs/msteams-docs/commits/4cf0c0c7916fce4cd08f592308abeebed679b443)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-60415f9c)

<a id="60415f9c"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C13%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202101130844173479-2597%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2Bmcq%2F2%2BUTsT%2F%2FKGaX4Xi5nlxeUrqIHxRrwdNJuGVOUE%3D&st=2021-01-13T08%3A39%3A44Z&se=2021-02-13T08%3A44%3A44Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-13 10:34 UTC, opbld31 commented
Docs Build status updates of commit _[9463049](https://github.com/MicrosoftDocs/msteams-docs/commits/9463049d823b4ff2aa5dc2a67726bca80ce87afc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/messaging-extensions/how-to/action-commands/create-task-module.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Messaging-extensions-Add-sections-1439845/msteams-platform/messaging-extensions/how-to/action-commands/create-task-module.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/action-commands/create-task-module?branch=pr-en-us-2597) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C13%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202101131033539178-2597%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=hoo7ajQPi1rI7u%2FPHyTPIeiqkALjozyh%2BH8%2F78iKDLQ%3D&st=2021-01-13T10%3A29%3A48Z&se=2021-02-13T10%3A34%3A48Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-13 11:52 UTC, opbld31 commented
Docs Build status updates of commit _[81737f8](https://github.com/MicrosoftDocs/msteams-docs/commits/81737f8c0dfdd01c3c501497d97c0c9e61a8265d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :warning:Warning | | [Details](#user-content-c9d2d1b0)
[msteams-platform/messaging-extensions/how-to/action-commands/create-task-module.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Messaging-extensions-Add-sections-1439845/msteams-platform/messaging-extensions/how-to/action-commands/create-task-module.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/action-commands/create-task-module?branch=pr-en-us-2597) |
[msteams-platform/messaging-extensions/how-to/create-messaging-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Messaging-extensions-Add-sections-1439845/msteams-platform/messaging-extensions/how-to/create-messaging-extension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/create-messaging-extension?branch=pr-en-us-2597) |

<a id="c9d2d1b0"></a>
###
 - **Line 0, Column 0**: **[Warning-[redirected-file-not-removed](https://review.docs.microsoft.com/help/contribute/validation-ref/redirected-file-not-removed?branch=main)]** `````Redirected file 'messaging-extensions/how-to/create-messaging-extension.md [redirection]' is still in the repo. After adding a file to the redirection JSON file, you must delete the original file from the repo.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C13%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202101131151270219-2597%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=5ODV0UFz50Kuc4%2BRm7QhCdW%2B%2FbS3t7z%2FJOIhMRgfx64%3D&st=2021-01-13T11%3A47%3A07Z&se=2021-02-13T11%3A52%3A07Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-13 12:12 UTC, opbld33 commented
Docs Build status updates of commit _[c9f183d](https://github.com/MicrosoftDocs/msteams-docs/commits/c9f183d83a6a7943b217fdef4cfc17ed9c035f40)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :warning:Warning | | [Details](#user-content-48dae30d)
[msteams-platform/messaging-extensions/how-to/action-commands/create-task-module.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Messaging-extensions-Add-sections-1439845/msteams-platform/messaging-extensions/how-to/action-commands/create-task-module.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/action-commands/create-task-module?branch=pr-en-us-2597) |
[msteams-platform/messaging-extensions/how-to/create-messaging-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Messaging-extensions-Add-sections-1439845/msteams-platform/messaging-extensions/how-to/create-messaging-extension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/create-messaging-extension?branch=pr-en-us-2597) |

<a id="48dae30d"></a>
###
 - **Line 0, Column 0**: **[Warning-[redirected-file-not-removed](https://review.docs.microsoft.com/help/contribute/validation-ref/redirected-file-not-removed?branch=main)]** `````Redirected file 'messaging-extensions/how-to/create-messaging-extension.md [redirection]' is still in the repo. After adding a file to the redirection JSON file, you must delete the original file from the repo.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C13%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202101131212027752-2597%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=yKv619qS7MGdcZUGxSYrToTnX5ooLqTbyDNQ5iIwK58%3D&st=2021-01-13T12%3A07%3A44Z&se=2021-02-13T12%3A12%3A44Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-13 12:27 UTC, opbld30 commented
Docs Build status updates of commit _[06d012a](https://github.com/MicrosoftDocs/msteams-docs/commits/06d012adb565fbe1848e1248a4ef5124c3d2a44c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :warning:Warning | | [Details](#user-content-2d044983)
[msteams-platform/messaging-extensions/how-to/action-commands/create-task-module.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Messaging-extensions-Add-sections-1439845/msteams-platform/messaging-extensions/how-to/action-commands/create-task-module.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/action-commands/create-task-module?branch=pr-en-us-2597) |
[msteams-platform/messaging-extensions/how-to/create-messaging-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Messaging-extensions-Add-sections-1439845/msteams-platform/messaging-extensions/how-to/create-messaging-extension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/create-messaging-extension?branch=pr-en-us-2597) |

<a id="2d044983"></a>
###
 - **Line 0, Column 0**: **[Warning-[redirected-file-not-removed](https://review.docs.microsoft.com/help/contribute/validation-ref/redirected-file-not-removed?branch=main)]** `````Redirected file 'messaging-extensions/how-to/create-messaging-extension.md [redirection]' is still in the repo. After adding a file to the redirection JSON file, you must delete the original file from the repo.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C13%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202101131227196434-2597%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=kru3dC%2BUMyJ4kWHuVLucQsobbJQ4qQryM33NAFRSHb4%3D&st=2021-01-13T12%3A22%3A58Z&se=2021-02-13T12%3A27%3A58Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-15 03:55 UTC, opbld32 commented
Docs Build status updates of commit _[9b6ebc9](https://github.com/MicrosoftDocs/msteams-docs/commits/9b6ebc9a64d0244fbe9ea2dcf91fe9f8946f833d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :warning:Warning | | [Details](#user-content-244b4ad1)
[msteams-platform/messaging-extensions/how-to/action-commands/create-task-module.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Messaging-extensions-Add-sections-1439845/msteams-platform/messaging-extensions/how-to/action-commands/create-task-module.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/action-commands/create-task-module?branch=pr-en-us-2597) |
[msteams-platform/messaging-extensions/how-to/create-messaging-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Messaging-extensions-Add-sections-1439845/msteams-platform/messaging-extensions/how-to/create-messaging-extension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/create-messaging-extension?branch=pr-en-us-2597) |

<a id="244b4ad1"></a>
###
 - **Line 0, Column 0**: **[Warning-[redirected-file-not-removed](https://review.docs.microsoft.com/help/contribute/validation-ref/redirected-file-not-removed?branch=main)]** `````Redirected file 'messaging-extensions/how-to/create-messaging-extension.md [redirection]' is still in the repo. After adding a file to the redirection JSON file, you must delete the original file from the repo.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C15%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202101150354543383-2597%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=BHfv2FeLAWYFGivyAxmhhGpl3mtPS%2FE13BkNOPIELuk%3D&st=2021-01-15T03%3A50%3A42Z&se=2021-02-15T03%3A55%3A42Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-15 05:05 UTC, Wajeed-msft commented on msteams-platform/messaging-extensions/how-to/action-commands/create-task-module.md
> +  "actions": [
Could you please add C# version as well, please work with Nikitha?  Here is the link to the sample code: https://github.com/microsoft/BotBuilder-Samples/blob/main/samples/csharp_dotnetcore/51.teams-messaging-extensions-action

2021-01-15 12:37 UTC, opbld33 commented
Docs Build status updates of commit _[6bfc8fa](https://github.com/MicrosoftDocs/msteams-docs/commits/6bfc8faa36b1d19f50d3f9160cccd9539d0fc5b2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/messaging-extensions/how-to/action-commands/create-task-module.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Messaging-extensions-Add-sections-1439845/msteams-platform/messaging-extensions/how-to/action-commands/create-task-module.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/action-commands/create-task-module?branch=pr-en-us-2597) | [Details](#user-content-301abe3d-e7d5242d)
[]() | :warning:Warning | | [Details](#user-content-e7d5242d)
[msteams-platform/messaging-extensions/how-to/create-messaging-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Messaging-extensions-Add-sections-1439845/msteams-platform/messaging-extensions/how-to/create-messaging-extension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/create-messaging-extension?branch=pr-en-us-2597) |

<a id="301abe3d-e7d5242d"></a>
### [msteams-platform/messaging-extensions/how-to/action-commands/create-task-module.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Messaging-extensions-Add-sections-1439845/msteams-platform/messaging-extensions/how-to/action-commands/create-task-module.md)
 - **Line 474, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/en-us/new-hope/specs/conceptual/tabbed-conceptual?branch=master#feature-design)]** `````Duplicate tab id: (json, 2).`````
 - **Line 474, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/en-us/new-hope/specs/conceptual/tabbed-conceptual?branch=master#feature-design)]** `````Tab group with different tab id set.`````
 - **Line 532, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** `````Multiple H1s(H1 'C#') are not allowed. You can only have one top-level heading.`````
 - **Line 532, Column 3**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#tab/c#' in 'messaging-extensions/how-to/action-commands/create-task-module.md', did you mean '#c'?`````

<a id="e7d5242d"></a>
###
 - **Line 0, Column 0**: **[Warning-[redirected-file-not-removed](https://review.docs.microsoft.com/help/contribute/validation-ref/redirected-file-not-removed?branch=main)]** `````Redirected file 'messaging-extensions/how-to/create-messaging-extension.md [redirection]' is still in the repo. After adding a file to the redirection JSON file, you must delete the original file from the repo.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C15%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202101151237116508-2597%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=T81gHCUdUwzeP6ZypEXwLZmrzkQXZA6mlGaW%2FipeHzM%3D&st=2021-01-15T12%3A32%3A43Z&se=2021-02-15T12%3A37%3A43Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-15 12:41 UTC, opbld33 commented
Docs Build status updates of commit _[be74f3f](https://github.com/MicrosoftDocs/msteams-docs/commits/be74f3fce1ef35195131ba5f19b5eafcb0ea1ef9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/messaging-extensions/how-to/action-commands/create-task-module.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Messaging-extensions-Add-sections-1439845/msteams-platform/messaging-extensions/how-to/action-commands/create-task-module.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/action-commands/create-task-module?branch=pr-en-us-2597) | [Details](#user-content-301abe3d-9bc9dd43)
[]() | :warning:Warning | | [Details](#user-content-9bc9dd43)
[msteams-platform/messaging-extensions/how-to/create-messaging-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Messaging-extensions-Add-sections-1439845/msteams-platform/messaging-extensions/how-to/create-messaging-extension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/create-messaging-extension?branch=pr-en-us-2597) |

<a id="301abe3d-9bc9dd43"></a>
### [msteams-platform/messaging-extensions/how-to/action-commands/create-task-module.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Messaging-extensions-Add-sections-1439845/msteams-platform/messaging-extensions/how-to/action-commands/create-task-module.md)
 - **Line 474, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** `````Multiple H1s(H1 'JSON') are not allowed. You can only have one top-level heading.`````
 - **Line 474, Column 3**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#tab' in 'messaging-extensions/how-to/action-commands/create-task-module.md', did you mean '#c'?`````
 - **Line 504, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** `````Multiple H1s(H1 'JSON') are not allowed. You can only have one top-level heading.`````
 - **Line 504, Column 3**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#tab' in 'messaging-extensions/how-to/action-commands/create-task-module.md', did you mean '#c'?`````
 - **Line 532, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** `````Multiple H1s(H1 'C#') are not allowed. You can only have one top-level heading.`````
 - **Line 532, Column 3**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#tab' in 'messaging-extensions/how-to/action-commands/create-task-module.md', did you mean '#c'?`````
 - **Line 474, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'JSON' is duplicated with other articles: 'messaging-extensions/how-to/action-commands/create-task-module.md(474,1), messaging-extensions/how-to/action-commands/create-task-module.md(504,1)'. First level headings must be unique within a docset.`````
 - **Line 504, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'JSON' is duplicated with other articles: 'messaging-extensions/how-to/action-commands/create-task-module.md(474,1), messaging-extensions/how-to/action-commands/create-task-module.md(504,1)'. First level headings must be unique within a docset.`````

<a id="9bc9dd43"></a>
###
 - **Line 0, Column 0**: **[Warning-[redirected-file-not-removed](https://review.docs.microsoft.com/help/contribute/validation-ref/redirected-file-not-removed?branch=main)]** `````Redirected file 'messaging-extensions/how-to/create-messaging-extension.md [redirection]' is still in the repo. After adding a file to the redirection JSON file, you must delete the original file from the repo.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C15%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202101151241039756-2597%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=9U9diSJ32P69fX8rgZi1Mo2BhijwJ0IEf7j9BegYjkA%3D&st=2021-01-15T12%3A36%3A40Z&se=2021-02-15T12%3A41%3A40Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-15 12:48 UTC, opbld31 commented
Docs Build status updates of commit _[f719ed6](https://github.com/MicrosoftDocs/msteams-docs/commits/f719ed661fdf6cdf4d6b5f05c88ec7427c3cdf47)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-aca99f07)
[]() | :x:Error | | [Details](#user-content-aca99f07)

<a id="aca99f07"></a>
###
 - **[Error-RuningBuildFailed]** `````Some unexpected errors happened when running build, please open a ticket in https://SiteHelp and include the error report for our team to troubleshoot`````
 - **Line 0, Column 0**: **[Warning-[redirected-file-not-removed](https://review.docs.microsoft.com/help/contribute/validation-ref/redirected-file-not-removed?branch=main)]** `````Redirected file 'messaging-extensions/how-to/create-messaging-extension.md [redirection]' is still in the repo. After adding a file to the redirection JSON file, you must delete the original file from the repo.`````

<a id="aca99f07"></a>
###
 - **[Error-RuningBuildFailed]** `````Some unexpected errors happened when running build, please open a ticket in https://SiteHelp and include the error report for our team to troubleshoot`````
 - **Line 0, Column 0**: **[Warning-[redirected-file-not-removed](https://review.docs.microsoft.com/help/contribute/validation-ref/redirected-file-not-removed?branch=main)]** `````Redirected file 'messaging-extensions/how-to/create-messaging-extension.md [redirection]' is still in the repo. After adding a file to the redirection JSON file, you must delete the original file from the repo.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C15%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202101151247135223-2597%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=5eBPAyNpLM6NeUAQydjMsfNTKuTvZAWzt6jCIrvz2%2Fo%3D&st=2021-01-15T12%3A43%3A11Z&se=2021-02-15T12%3A48%3A11Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-15 13:01 UTC, opbld30 commented
Docs Build status updates of commit _[741ba4a](https://github.com/MicrosoftDocs/msteams-docs/commits/741ba4a54a39ccad52379bc10ed08fe057ba9431)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :warning:Warning | | [Details](#user-content-bc2894cf)
[msteams-platform/messaging-extensions/how-to/action-commands/create-task-module.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Messaging-extensions-Add-sections-1439845/msteams-platform/messaging-extensions/how-to/action-commands/create-task-module.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/action-commands/create-task-module?branch=pr-en-us-2597) |
[msteams-platform/messaging-extensions/how-to/create-messaging-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Messaging-extensions-Add-sections-1439845/msteams-platform/messaging-extensions/how-to/create-messaging-extension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/create-messaging-extension?branch=pr-en-us-2597) |

<a id="bc2894cf"></a>
###
 - **Line 0, Column 0**: **[Warning-[redirected-file-not-removed](https://review.docs.microsoft.com/help/contribute/validation-ref/redirected-file-not-removed?branch=main)]** `````Redirected file 'messaging-extensions/how-to/create-messaging-extension.md [redirection]' is still in the repo. After adding a file to the redirection JSON file, you must delete the original file from the repo.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C15%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202101151300066789-2597%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=xwSWI8GCwsVRJIkQe7Mdv32Z1z2ZdtqpcaLEJrG2Mrk%3D&st=2021-01-15T12%3A55%3A59Z&se=2021-02-15T13%3A00%3A59Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-18 08:53 UTC, Nikitha-MSFT approved these changes
Reviewed and approved

2021-01-29 04:49 UTC, opbld30 commented
Docs Build status updates of commit _[7f50829](https://github.com/MicrosoftDocs/msteams-docs/commits/7f50829a5606f75a0d3340f365254fc086953b1a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/messaging-extensions/how-to/action-commands/create-task-module.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Messaging-extensions-Add-sections-1439845/msteams-platform/messaging-extensions/how-to/action-commands/create-task-module.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/action-commands/create-task-module?branch=pr-en-us-2597) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C29%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202101290448495776-2597%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=XJY2Znj%2FaevaPB0z9K0SFKZcenqkh7V2I1Ni%2BzxICt4%3D&st=2021-01-29T04%3A44%3A26Z&se=2021-03-01T04%3A49%3A26Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-29 05:09 UTC, Rajeshwari-v commented
@surbhigupta12 , @KirtiPereira - Closing this PR as create-messaging-extension.md file details will be re-structured and updated in respective files. 
Information updated in create-task-module.md file for this PR is combined with PR #2664.

2021-01-29 05:09 UTC, closed without merging