Updated ms.topic type
MicrosoftDocs/msteams-docs pull request #2615
Opened 2021-01-14 09:26 UTC by surbhigupta12

Updated the ms.topic type for various files.

2021-01-14 09:26 UTC, opbld30 commented
Docs Build status updates of commit _[1c11bf2](https://github.com/MicrosoftDocs/msteams-docs/commits/1c11bf20f2313eae574a16e66cd3d0f50d068dad)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-f1ace650)

<a id="f1ace650"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C14%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202101140926289510-2615%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=BgdPHOZOfl08REHOOnsUiA%2FsYqx5lB5mlUrM3BR%2BWtU%3D&st=2021-01-14T09%3A21%3A55Z&se=2021-02-14T09%3A26%3A55Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-15 07:54 UTC, opbld33 commented
Docs Build status updates of commit _[df5bb9f](https://github.com/MicrosoftDocs/msteams-docs/commits/df5bb9f1523370905f447132dcc887929f509a06)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/build-and-test/share-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/share-to-teams.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/share-to-teams?branch=pr-en-us-2615) | [Details](#user-content-9b7bb6a9-e0aa79cf)
[msteams-platform/concepts/build-and-test/test-data.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/test-data.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/test-data?branch=pr-en-us-2615) | [Details](#user-content-e6544f21-e0aa79cf)
[msteams-platform/graph-api/rsc/test-rsc-json-file.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/graph-api/rsc/test-rsc-json-file.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/graph-api/rsc/test-rsc-json-file?branch=pr-en-us-2615) | [Details](#user-content-1e54d419-e0aa79cf)
[msteams-platform/resources/bot-v3/bot-conversations/bots-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/resources/bot-v3/bot-conversations/bots-conversations.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bot-conversations/bots-conversations?branch=pr-en-us-2615) | [Details](#user-content-a440589b-e0aa79cf)
[msteams-platform/resources/bot-v3/bots-create.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/resources/bot-v3/bots-create.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bots-create?branch=pr-en-us-2615) | [Details](#user-content-277fabd2-e0aa79cf)
[msteams-platform/resources/dev-preview/developer-preview-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/resources/dev-preview/developer-preview-features.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/dev-preview/developer-preview-features?branch=pr-en-us-2615) | [Details](#user-content-090bc781-e0aa79cf)
[msteams-platform/samples/shifts-wfm-connectors.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/samples/shifts-wfm-connectors.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/samples/shifts-wfm-connectors?branch=pr-en-us-2615) | [Details](#user-content-0aa593ad-e0aa79cf)
[msteams-platform/samples/virtual-assistant.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/samples/virtual-assistant.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/samples/virtual-assistant?branch=pr-en-us-2615) | [Details](#user-content-dc23a873-e0aa79cf)
[msteams-platform/tabs/how-to/developer-tools.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/tabs/how-to/developer-tools.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/developer-tools?branch=pr-en-us-2615) | [Details](#user-content-a1ca09f1-e0aa79cf)
[msteams-platform/bots/calls-and-meetings/debugging-local-testing-calling-meeting-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/bots/calls-and-meetings/debugging-local-testing-calling-meeting-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/calls-and-meetings/debugging-local-testing-calling-meeting-bots?branch=pr-en-us-2615) |
[msteams-platform/bots/calls-and-meetings/requirements-considerations-application-hosted-media-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/bots/calls-and-meetings/requirements-considerations-application-hosted-media-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/calls-and-meetings/requirements-considerations-application-hosted-media-bots?branch=pr-en-us-2615) |
[msteams-platform/concepts/authentication/authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/authentication/authentication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/authentication/authentication?branch=pr-en-us-2615) |
[msteams-platform/concepts/authentication/configure-identity-provider.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/authentication/configure-identity-provider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/authentication/configure-identity-provider?branch=pr-en-us-2615) |
[msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/apps-localization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/apps-localization?branch=pr-en-us-2615) |
[msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/deep-links.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links?branch=pr-en-us-2615) |
[msteams-platform/concepts/build-and-test/prepare-your-o365-tenant.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/prepare-your-o365-tenant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/prepare-your-o365-tenant?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/deploy-and-publish/apps-upload.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/apps-upload?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/appsource/post-publish/application-certification.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/deploy-and-publish/appsource/post-publish/application-certification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/post-publish/application-certification?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/appsource/post-publish/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/deploy-and-publish/appsource/post-publish/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/post-publish/overview?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/appsource/prepare/app-manifest-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/deploy-and-publish/appsource/prepare/app-manifest-checklist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/app-manifest-checklist?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/appsource/prepare/detail [...]

2021-01-18 10:25 UTC, opbld33 commented
Docs Build status updates of commit _[1cd53a5](https://github.com/MicrosoftDocs/msteams-docs/commits/1cd53a5c13fd55642f1ee99be6ba89b1459b91fb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/build-and-test/share-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/share-to-teams.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/share-to-teams?branch=pr-en-us-2615) | [Details](#user-content-9b7bb6a9-a48657d8)
[msteams-platform/concepts/build-and-test/test-data.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/test-data.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/test-data?branch=pr-en-us-2615) | [Details](#user-content-e6544f21-a48657d8)
[msteams-platform/graph-api/rsc/test-rsc-json-file.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/graph-api/rsc/test-rsc-json-file.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/graph-api/rsc/test-rsc-json-file?branch=pr-en-us-2615) | [Details](#user-content-1e54d419-a48657d8)
[msteams-platform/resources/bot-v3/bot-conversations/bots-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/resources/bot-v3/bot-conversations/bots-conversations.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bot-conversations/bots-conversations?branch=pr-en-us-2615) | [Details](#user-content-a440589b-a48657d8)
[msteams-platform/resources/bot-v3/bots-create.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/resources/bot-v3/bots-create.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bots-create?branch=pr-en-us-2615) | [Details](#user-content-277fabd2-a48657d8)
[msteams-platform/resources/dev-preview/developer-preview-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/resources/dev-preview/developer-preview-features.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/dev-preview/developer-preview-features?branch=pr-en-us-2615) | [Details](#user-content-090bc781-a48657d8)
[msteams-platform/samples/shifts-wfm-connectors.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/samples/shifts-wfm-connectors.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/samples/shifts-wfm-connectors?branch=pr-en-us-2615) | [Details](#user-content-0aa593ad-a48657d8)
[msteams-platform/samples/virtual-assistant.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/samples/virtual-assistant.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/samples/virtual-assistant?branch=pr-en-us-2615) | [Details](#user-content-dc23a873-a48657d8)
[msteams-platform/tabs/how-to/developer-tools.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/tabs/how-to/developer-tools.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/developer-tools?branch=pr-en-us-2615) | [Details](#user-content-a1ca09f1-a48657d8)
[msteams-platform/bots/calls-and-meetings/debugging-local-testing-calling-meeting-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/bots/calls-and-meetings/debugging-local-testing-calling-meeting-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/calls-and-meetings/debugging-local-testing-calling-meeting-bots?branch=pr-en-us-2615) |
[msteams-platform/bots/calls-and-meetings/requirements-considerations-application-hosted-media-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/bots/calls-and-meetings/requirements-considerations-application-hosted-media-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/calls-and-meetings/requirements-considerations-application-hosted-media-bots?branch=pr-en-us-2615) |
[msteams-platform/concepts/authentication/authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/authentication/authentication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/authentication/authentication?branch=pr-en-us-2615) |
[msteams-platform/concepts/authentication/configure-identity-provider.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/authentication/configure-identity-provider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/authentication/configure-identity-provider?branch=pr-en-us-2615) |
[msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/apps-localization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/apps-localization?branch=pr-en-us-2615) |
[msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/deep-links.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links?branch=pr-en-us-2615) |
[msteams-platform/concepts/build-and-test/prepare-your-o365-tenant.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/prepare-your-o365-tenant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/prepare-your-o365-tenant?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/deploy-and-publish/apps-upload.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/apps-upload?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/appsource/post-publish/application-certification.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/deploy-and-publish/appsource/post-publish/application-certification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/post-publish/application-certification?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/appsource/post-publish/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/deploy-and-publish/appsource/post-publish/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/post-publish/overview?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/appsource/prepare/app-manifest-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/deploy-and-publish/appsource/prepare/app-manifest-checklist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/app-manifest-checklist?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/appsource/prepare/detail [...]

2021-01-21 17:36 UTC, heath-hamilton commented on msteams-platform/bots/calls-and-meetings/debugging-local-testing-calling-meeting-bots.md
>  title: How to develop calling and online meeting bots on your local PC
```suggestion
title: Debug your calling and meeting bot locally
```

2021-01-21 17:40 UTC, heath-hamilton commented on msteams-platform/concepts/authentication/authentication.md
>  title: Authenticate a user in Teams
Authenticating app users

2021-01-21 17:42 UTC, opbld31 commented
Docs Build status updates of commit _[8b2a7bc](https://github.com/MicrosoftDocs/msteams-docs/commits/8b2a7bce20a374eee076941b10d5af0266ff074f)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-67703e8f)

<a id="67703e8f"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C21%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202101211741569340-2615%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=alVFLlrkEXvfqxnMSyU8jmWf21cjS%2FObpRz3MVZb21w%3D&st=2021-01-21T17%3A37%3A11Z&se=2021-02-21T17%3A42%3A11Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-21 19:41 UTC, heath-hamilton requested changes
@surbhigupta12 Please let me know if you want to discuss my proposed changes.

2021-01-21 19:41 UTC, heath-hamilton commented on msteams-platform/concepts/deploy-and-publish/appsource/publish.md
>  title: Microsoft Teams app approval submission process guidance
```suggestion
title: Understanding the Teams store submission process
```

2021-01-21 19:41 UTC, heath-hamilton commented on msteams-platform/concepts/deploy-and-publish/appsource/publish.md
> +ms.topic: conceptual
```suggestion
ms.topic: overview
```

2021-01-21 19:41 UTC, heath-hamilton commented on msteams-platform/concepts/device-capabilities/native-device-permissions.md
>  title: Request device permissions for your Microsoft Teams tab
```suggestion
title: Request device permissions for your tab
```

2021-01-21 19:41 UTC, heath-hamilton commented on msteams-platform/concepts/device-capabilities/native-device-permissions.md
> +ms.topic: conceptual
```suggestion
ms.topic: how-to
```

2021-01-21 19:41 UTC, heath-hamilton commented on msteams-platform/resources/bot-v3/bots-create.md
> +ms.topic: reference
```suggestion
ms.topic: how-to
```

2021-01-21 19:41 UTC, heath-hamilton commented on msteams-platform/resources/bot-v3/bots-overview.md
> +ms.topic: reference
```suggestion
ms.topic: conceptual
```

2021-01-21 19:41 UTC, heath-hamilton commented on msteams-platform/resources/dev-preview/developer-preview-intro.md
> +ms.topic: reference
```suggestion
ms.topic: conceptual
```

2021-01-21 19:41 UTC, heath-hamilton commented on msteams-platform/samples/virtual-assistant.md
> +ms.topic: conceptual
```suggestion
ms.topic: how-to
```

2021-01-21 19:41 UTC, heath-hamilton commented on msteams-platform/tabs/how-to/authentication/auth-flow-tab.md
> +ms.topic: how-to
```suggestion
ms.topic: conceptual
```

2021-01-21 19:41 UTC, heath-hamilton commented on msteams-platform/tutorials/code-samples.md
>  title: Microsoft Teams code samples
```suggestion
title: App code samples
```

2021-01-21 19:41 UTC, heath-hamilton commented on msteams-platform/tutorials/code-samples.md
> +s.topic: tutorial
```suggestion
ms.topic: reference
```
To me, this is more of a collection of links than a guided tutorial.

2021-01-21 19:41 UTC, heath-hamilton commented on msteams-platform/whats-new.md
> +ms.topic: overview
```suggestion
ms.topic: reference
```

2021-01-22 08:43 UTC, opbld32 commented
Docs Build status updates of commit _[f00181f](https://github.com/MicrosoftDocs/msteams-docs/commits/f00181f69016c88c0624a46a7801fafe8f4d9492)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/build-and-test/share-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/share-to-teams.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/share-to-teams?branch=pr-en-us-2615) | [Details](#user-content-9b7bb6a9-22ecf11a)
[msteams-platform/concepts/build-and-test/test-data.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/test-data.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/test-data?branch=pr-en-us-2615) | [Details](#user-content-e6544f21-22ecf11a)
[msteams-platform/graph-api/rsc/test-rsc-json-file.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/graph-api/rsc/test-rsc-json-file.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/graph-api/rsc/test-rsc-json-file?branch=pr-en-us-2615) | [Details](#user-content-1e54d419-22ecf11a)
[msteams-platform/resources/bot-v3/bot-conversations/bots-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/resources/bot-v3/bot-conversations/bots-conversations.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bot-conversations/bots-conversations?branch=pr-en-us-2615) | [Details](#user-content-a440589b-22ecf11a)
[msteams-platform/resources/bot-v3/bots-create.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/resources/bot-v3/bots-create.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bots-create?branch=pr-en-us-2615) | [Details](#user-content-277fabd2-22ecf11a)
[msteams-platform/resources/dev-preview/developer-preview-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/resources/dev-preview/developer-preview-features.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/dev-preview/developer-preview-features?branch=pr-en-us-2615) | [Details](#user-content-090bc781-22ecf11a)
[msteams-platform/samples/shifts-wfm-connectors.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/samples/shifts-wfm-connectors.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/samples/shifts-wfm-connectors?branch=pr-en-us-2615) | [Details](#user-content-0aa593ad-22ecf11a)
[msteams-platform/samples/virtual-assistant.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/samples/virtual-assistant.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/samples/virtual-assistant?branch=pr-en-us-2615) | [Details](#user-content-dc23a873-22ecf11a)
[msteams-platform/tabs/how-to/developer-tools.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/tabs/how-to/developer-tools.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/developer-tools?branch=pr-en-us-2615) | [Details](#user-content-a1ca09f1-22ecf11a)
[msteams-platform/bots/calls-and-meetings/debugging-local-testing-calling-meeting-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/bots/calls-and-meetings/debugging-local-testing-calling-meeting-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/calls-and-meetings/debugging-local-testing-calling-meeting-bots?branch=pr-en-us-2615) |
[msteams-platform/bots/calls-and-meetings/requirements-considerations-application-hosted-media-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/bots/calls-and-meetings/requirements-considerations-application-hosted-media-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/calls-and-meetings/requirements-considerations-application-hosted-media-bots?branch=pr-en-us-2615) |
[msteams-platform/concepts/authentication/authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/authentication/authentication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/authentication/authentication?branch=pr-en-us-2615) |
[msteams-platform/concepts/authentication/configure-identity-provider.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/authentication/configure-identity-provider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/authentication/configure-identity-provider?branch=pr-en-us-2615) |
[msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/apps-localization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/apps-localization?branch=pr-en-us-2615) |
[msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/deep-links.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links?branch=pr-en-us-2615) |
[msteams-platform/concepts/build-and-test/prepare-your-o365-tenant.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/prepare-your-o365-tenant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/prepare-your-o365-tenant?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/deploy-and-publish/apps-upload.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/apps-upload?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/appsource/post-publish/application-certification.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/deploy-and-publish/appsource/post-publish/application-certification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/post-publish/application-certification?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/appsource/post-publish/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/deploy-and-publish/appsource/post-publish/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/post-publish/overview?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/appsource/prepare/app-manifest-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/deploy-and-publish/appsource/prepare/app-manifest-checklist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/app-manifest-checklist?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/appsource/prepare/detail [...]

2021-01-22 08:45 UTC, opbld33 commented
Docs Build status updates of commit _[6863a7a](https://github.com/MicrosoftDocs/msteams-docs/commits/6863a7a90d9156d03743c1fa2eb50194cac1f34f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/build-and-test/share-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/share-to-teams.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/share-to-teams?branch=pr-en-us-2615) | [Details](#user-content-9b7bb6a9-d52a6fa2)
[msteams-platform/concepts/build-and-test/test-data.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/test-data.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/test-data?branch=pr-en-us-2615) | [Details](#user-content-e6544f21-d52a6fa2)
[msteams-platform/graph-api/rsc/test-rsc-json-file.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/graph-api/rsc/test-rsc-json-file.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/graph-api/rsc/test-rsc-json-file?branch=pr-en-us-2615) | [Details](#user-content-1e54d419-d52a6fa2)
[msteams-platform/resources/bot-v3/bot-conversations/bots-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/resources/bot-v3/bot-conversations/bots-conversations.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bot-conversations/bots-conversations?branch=pr-en-us-2615) | [Details](#user-content-a440589b-d52a6fa2)
[msteams-platform/resources/bot-v3/bots-create.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/resources/bot-v3/bots-create.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bots-create?branch=pr-en-us-2615) | [Details](#user-content-277fabd2-d52a6fa2)
[msteams-platform/resources/dev-preview/developer-preview-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/resources/dev-preview/developer-preview-features.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/dev-preview/developer-preview-features?branch=pr-en-us-2615) | [Details](#user-content-090bc781-d52a6fa2)
[msteams-platform/samples/shifts-wfm-connectors.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/samples/shifts-wfm-connectors.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/samples/shifts-wfm-connectors?branch=pr-en-us-2615) | [Details](#user-content-0aa593ad-d52a6fa2)
[msteams-platform/samples/virtual-assistant.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/samples/virtual-assistant.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/samples/virtual-assistant?branch=pr-en-us-2615) | [Details](#user-content-dc23a873-d52a6fa2)
[msteams-platform/tabs/how-to/developer-tools.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/tabs/how-to/developer-tools.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/developer-tools?branch=pr-en-us-2615) | [Details](#user-content-a1ca09f1-d52a6fa2)
[msteams-platform/bots/calls-and-meetings/debugging-local-testing-calling-meeting-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/bots/calls-and-meetings/debugging-local-testing-calling-meeting-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/calls-and-meetings/debugging-local-testing-calling-meeting-bots?branch=pr-en-us-2615) |
[msteams-platform/bots/calls-and-meetings/requirements-considerations-application-hosted-media-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/bots/calls-and-meetings/requirements-considerations-application-hosted-media-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/calls-and-meetings/requirements-considerations-application-hosted-media-bots?branch=pr-en-us-2615) |
[msteams-platform/concepts/authentication/authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/authentication/authentication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/authentication/authentication?branch=pr-en-us-2615) |
[msteams-platform/concepts/authentication/configure-identity-provider.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/authentication/configure-identity-provider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/authentication/configure-identity-provider?branch=pr-en-us-2615) |
[msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/apps-localization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/apps-localization?branch=pr-en-us-2615) |
[msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/deep-links.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links?branch=pr-en-us-2615) |
[msteams-platform/concepts/build-and-test/prepare-your-o365-tenant.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/prepare-your-o365-tenant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/prepare-your-o365-tenant?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/deploy-and-publish/apps-upload.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/apps-upload?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/appsource/post-publish/application-certification.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/deploy-and-publish/appsource/post-publish/application-certification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/post-publish/application-certification?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/appsource/post-publish/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/deploy-and-publish/appsource/post-publish/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/post-publish/overview?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/appsource/prepare/app-manifest-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/deploy-and-publish/appsource/prepare/app-manifest-checklist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/app-manifest-checklist?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/appsource/prepare/detail [...]

2021-01-22 08:45 UTC, opbld30 commented
Docs Build status updates of commit _[2db3133](https://github.com/MicrosoftDocs/msteams-docs/commits/2db31331e4760407fceda9afd2688fa9d248d3ab)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/build-and-test/share-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/share-to-teams.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/share-to-teams?branch=pr-en-us-2615) | [Details](#user-content-9b7bb6a9-ab6c13fc)
[msteams-platform/concepts/build-and-test/test-data.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/test-data.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/test-data?branch=pr-en-us-2615) | [Details](#user-content-e6544f21-ab6c13fc)
[msteams-platform/graph-api/rsc/test-rsc-json-file.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/graph-api/rsc/test-rsc-json-file.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/graph-api/rsc/test-rsc-json-file?branch=pr-en-us-2615) | [Details](#user-content-1e54d419-ab6c13fc)
[msteams-platform/resources/bot-v3/bot-conversations/bots-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/resources/bot-v3/bot-conversations/bots-conversations.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bot-conversations/bots-conversations?branch=pr-en-us-2615) | [Details](#user-content-a440589b-ab6c13fc)
[msteams-platform/resources/bot-v3/bots-create.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/resources/bot-v3/bots-create.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bots-create?branch=pr-en-us-2615) | [Details](#user-content-277fabd2-ab6c13fc)
[msteams-platform/resources/dev-preview/developer-preview-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/resources/dev-preview/developer-preview-features.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/dev-preview/developer-preview-features?branch=pr-en-us-2615) | [Details](#user-content-090bc781-ab6c13fc)
[msteams-platform/samples/shifts-wfm-connectors.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/samples/shifts-wfm-connectors.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/samples/shifts-wfm-connectors?branch=pr-en-us-2615) | [Details](#user-content-0aa593ad-ab6c13fc)
[msteams-platform/samples/virtual-assistant.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/samples/virtual-assistant.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/samples/virtual-assistant?branch=pr-en-us-2615) | [Details](#user-content-dc23a873-ab6c13fc)
[msteams-platform/tabs/how-to/developer-tools.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/tabs/how-to/developer-tools.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/developer-tools?branch=pr-en-us-2615) | [Details](#user-content-a1ca09f1-ab6c13fc)
[msteams-platform/bots/calls-and-meetings/debugging-local-testing-calling-meeting-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/bots/calls-and-meetings/debugging-local-testing-calling-meeting-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/calls-and-meetings/debugging-local-testing-calling-meeting-bots?branch=pr-en-us-2615) |
[msteams-platform/bots/calls-and-meetings/requirements-considerations-application-hosted-media-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/bots/calls-and-meetings/requirements-considerations-application-hosted-media-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/calls-and-meetings/requirements-considerations-application-hosted-media-bots?branch=pr-en-us-2615) |
[msteams-platform/concepts/authentication/authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/authentication/authentication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/authentication/authentication?branch=pr-en-us-2615) |
[msteams-platform/concepts/authentication/configure-identity-provider.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/authentication/configure-identity-provider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/authentication/configure-identity-provider?branch=pr-en-us-2615) |
[msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/apps-localization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/apps-localization?branch=pr-en-us-2615) |
[msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/deep-links.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links?branch=pr-en-us-2615) |
[msteams-platform/concepts/build-and-test/prepare-your-o365-tenant.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/prepare-your-o365-tenant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/prepare-your-o365-tenant?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/deploy-and-publish/apps-upload.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/apps-upload?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/appsource/post-publish/application-certification.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/deploy-and-publish/appsource/post-publish/application-certification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/post-publish/application-certification?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/appsource/post-publish/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/deploy-and-publish/appsource/post-publish/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/post-publish/overview?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/appsource/prepare/app-manifest-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/deploy-and-publish/appsource/prepare/app-manifest-checklist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/app-manifest-checklist?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/appsource/prepare/detail [...]

2021-01-22 08:46 UTC, opbld31 commented
Docs Build status updates of commit _[df6e2e1](https://github.com/MicrosoftDocs/msteams-docs/commits/df6e2e1b9e208e69f13fc545e029bb6da1f08323)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/build-and-test/share-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/share-to-teams.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/share-to-teams?branch=pr-en-us-2615) | [Details](#user-content-9b7bb6a9-e536e2a7)
[msteams-platform/concepts/build-and-test/test-data.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/test-data.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/test-data?branch=pr-en-us-2615) | [Details](#user-content-e6544f21-e536e2a7)
[msteams-platform/graph-api/rsc/test-rsc-json-file.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/graph-api/rsc/test-rsc-json-file.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/graph-api/rsc/test-rsc-json-file?branch=pr-en-us-2615) | [Details](#user-content-1e54d419-e536e2a7)
[msteams-platform/resources/bot-v3/bot-conversations/bots-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/resources/bot-v3/bot-conversations/bots-conversations.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bot-conversations/bots-conversations?branch=pr-en-us-2615) | [Details](#user-content-a440589b-e536e2a7)
[msteams-platform/resources/bot-v3/bots-create.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/resources/bot-v3/bots-create.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bots-create?branch=pr-en-us-2615) | [Details](#user-content-277fabd2-e536e2a7)
[msteams-platform/resources/dev-preview/developer-preview-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/resources/dev-preview/developer-preview-features.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/dev-preview/developer-preview-features?branch=pr-en-us-2615) | [Details](#user-content-090bc781-e536e2a7)
[msteams-platform/samples/shifts-wfm-connectors.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/samples/shifts-wfm-connectors.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/samples/shifts-wfm-connectors?branch=pr-en-us-2615) | [Details](#user-content-0aa593ad-e536e2a7)
[msteams-platform/samples/virtual-assistant.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/samples/virtual-assistant.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/samples/virtual-assistant?branch=pr-en-us-2615) | [Details](#user-content-dc23a873-e536e2a7)
[msteams-platform/tabs/how-to/developer-tools.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/tabs/how-to/developer-tools.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/developer-tools?branch=pr-en-us-2615) | [Details](#user-content-a1ca09f1-e536e2a7)
[msteams-platform/bots/calls-and-meetings/debugging-local-testing-calling-meeting-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/bots/calls-and-meetings/debugging-local-testing-calling-meeting-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/calls-and-meetings/debugging-local-testing-calling-meeting-bots?branch=pr-en-us-2615) |
[msteams-platform/bots/calls-and-meetings/requirements-considerations-application-hosted-media-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/bots/calls-and-meetings/requirements-considerations-application-hosted-media-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/calls-and-meetings/requirements-considerations-application-hosted-media-bots?branch=pr-en-us-2615) |
[msteams-platform/concepts/authentication/authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/authentication/authentication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/authentication/authentication?branch=pr-en-us-2615) |
[msteams-platform/concepts/authentication/configure-identity-provider.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/authentication/configure-identity-provider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/authentication/configure-identity-provider?branch=pr-en-us-2615) |
[msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/apps-localization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/apps-localization?branch=pr-en-us-2615) |
[msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/deep-links.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links?branch=pr-en-us-2615) |
[msteams-platform/concepts/build-and-test/prepare-your-o365-tenant.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/prepare-your-o365-tenant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/prepare-your-o365-tenant?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/deploy-and-publish/apps-upload.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/apps-upload?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/appsource/post-publish/application-certification.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/deploy-and-publish/appsource/post-publish/application-certification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/post-publish/application-certification?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/appsource/post-publish/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/deploy-and-publish/appsource/post-publish/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/post-publish/overview?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/appsource/prepare/app-manifest-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/deploy-and-publish/appsource/prepare/app-manifest-checklist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/app-manifest-checklist?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/appsource/prepare/detail [...]

2021-01-22 08:47 UTC, opbld32 commented
Docs Build status updates of commit _[e6f0808](https://github.com/MicrosoftDocs/msteams-docs/commits/e6f0808824b8b6381bad45b186098d6f1d470962)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/build-and-test/share-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/share-to-teams.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/share-to-teams?branch=pr-en-us-2615) | [Details](#user-content-9b7bb6a9-cfbf8838)
[msteams-platform/concepts/build-and-test/test-data.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/test-data.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/test-data?branch=pr-en-us-2615) | [Details](#user-content-e6544f21-cfbf8838)
[msteams-platform/graph-api/rsc/test-rsc-json-file.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/graph-api/rsc/test-rsc-json-file.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/graph-api/rsc/test-rsc-json-file?branch=pr-en-us-2615) | [Details](#user-content-1e54d419-cfbf8838)
[msteams-platform/resources/bot-v3/bot-conversations/bots-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/resources/bot-v3/bot-conversations/bots-conversations.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bot-conversations/bots-conversations?branch=pr-en-us-2615) | [Details](#user-content-a440589b-cfbf8838)
[msteams-platform/resources/bot-v3/bots-create.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/resources/bot-v3/bots-create.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bots-create?branch=pr-en-us-2615) | [Details](#user-content-277fabd2-cfbf8838)
[msteams-platform/resources/dev-preview/developer-preview-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/resources/dev-preview/developer-preview-features.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/dev-preview/developer-preview-features?branch=pr-en-us-2615) | [Details](#user-content-090bc781-cfbf8838)
[msteams-platform/samples/shifts-wfm-connectors.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/samples/shifts-wfm-connectors.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/samples/shifts-wfm-connectors?branch=pr-en-us-2615) | [Details](#user-content-0aa593ad-cfbf8838)
[msteams-platform/samples/virtual-assistant.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/samples/virtual-assistant.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/samples/virtual-assistant?branch=pr-en-us-2615) | [Details](#user-content-dc23a873-cfbf8838)
[msteams-platform/tabs/how-to/developer-tools.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/tabs/how-to/developer-tools.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/developer-tools?branch=pr-en-us-2615) | [Details](#user-content-a1ca09f1-cfbf8838)
[msteams-platform/bots/calls-and-meetings/debugging-local-testing-calling-meeting-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/bots/calls-and-meetings/debugging-local-testing-calling-meeting-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/calls-and-meetings/debugging-local-testing-calling-meeting-bots?branch=pr-en-us-2615) |
[msteams-platform/bots/calls-and-meetings/requirements-considerations-application-hosted-media-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/bots/calls-and-meetings/requirements-considerations-application-hosted-media-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/calls-and-meetings/requirements-considerations-application-hosted-media-bots?branch=pr-en-us-2615) |
[msteams-platform/concepts/authentication/authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/authentication/authentication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/authentication/authentication?branch=pr-en-us-2615) |
[msteams-platform/concepts/authentication/configure-identity-provider.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/authentication/configure-identity-provider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/authentication/configure-identity-provider?branch=pr-en-us-2615) |
[msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/apps-localization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/apps-localization?branch=pr-en-us-2615) |
[msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/deep-links.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links?branch=pr-en-us-2615) |
[msteams-platform/concepts/build-and-test/prepare-your-o365-tenant.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/prepare-your-o365-tenant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/prepare-your-o365-tenant?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/deploy-and-publish/apps-upload.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/apps-upload?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/appsource/post-publish/application-certification.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/deploy-and-publish/appsource/post-publish/application-certification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/post-publish/application-certification?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/appsource/post-publish/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/deploy-and-publish/appsource/post-publish/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/post-publish/overview?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/appsource/prepare/app-manifest-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/deploy-and-publish/appsource/prepare/app-manifest-checklist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/app-manifest-checklist?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/appsource/prepare/detail [...]

2021-01-22 08:48 UTC, opbld31 commented
Docs Build status updates of commit _[f08dd24](https://github.com/MicrosoftDocs/msteams-docs/commits/f08dd243d58937fb56433534f0f29d57d5d11e06)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/build-and-test/share-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/share-to-teams.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/share-to-teams?branch=pr-en-us-2615) | [Details](#user-content-9b7bb6a9-cf66fe44)
[msteams-platform/concepts/build-and-test/test-data.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/test-data.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/test-data?branch=pr-en-us-2615) | [Details](#user-content-e6544f21-cf66fe44)
[msteams-platform/graph-api/rsc/test-rsc-json-file.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/graph-api/rsc/test-rsc-json-file.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/graph-api/rsc/test-rsc-json-file?branch=pr-en-us-2615) | [Details](#user-content-1e54d419-cf66fe44)
[msteams-platform/resources/bot-v3/bot-conversations/bots-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/resources/bot-v3/bot-conversations/bots-conversations.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bot-conversations/bots-conversations?branch=pr-en-us-2615) | [Details](#user-content-a440589b-cf66fe44)
[msteams-platform/resources/bot-v3/bots-create.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/resources/bot-v3/bots-create.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bots-create?branch=pr-en-us-2615) | [Details](#user-content-277fabd2-cf66fe44)
[msteams-platform/resources/dev-preview/developer-preview-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/resources/dev-preview/developer-preview-features.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/dev-preview/developer-preview-features?branch=pr-en-us-2615) | [Details](#user-content-090bc781-cf66fe44)
[msteams-platform/samples/shifts-wfm-connectors.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/samples/shifts-wfm-connectors.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/samples/shifts-wfm-connectors?branch=pr-en-us-2615) | [Details](#user-content-0aa593ad-cf66fe44)
[msteams-platform/samples/virtual-assistant.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/samples/virtual-assistant.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/samples/virtual-assistant?branch=pr-en-us-2615) | [Details](#user-content-dc23a873-cf66fe44)
[msteams-platform/tabs/how-to/developer-tools.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/tabs/how-to/developer-tools.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/developer-tools?branch=pr-en-us-2615) | [Details](#user-content-a1ca09f1-cf66fe44)
[msteams-platform/bots/calls-and-meetings/debugging-local-testing-calling-meeting-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/bots/calls-and-meetings/debugging-local-testing-calling-meeting-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/calls-and-meetings/debugging-local-testing-calling-meeting-bots?branch=pr-en-us-2615) |
[msteams-platform/bots/calls-and-meetings/requirements-considerations-application-hosted-media-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/bots/calls-and-meetings/requirements-considerations-application-hosted-media-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/calls-and-meetings/requirements-considerations-application-hosted-media-bots?branch=pr-en-us-2615) |
[msteams-platform/concepts/authentication/authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/authentication/authentication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/authentication/authentication?branch=pr-en-us-2615) |
[msteams-platform/concepts/authentication/configure-identity-provider.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/authentication/configure-identity-provider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/authentication/configure-identity-provider?branch=pr-en-us-2615) |
[msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/apps-localization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/apps-localization?branch=pr-en-us-2615) |
[msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/deep-links.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links?branch=pr-en-us-2615) |
[msteams-platform/concepts/build-and-test/prepare-your-o365-tenant.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/prepare-your-o365-tenant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/prepare-your-o365-tenant?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/deploy-and-publish/apps-upload.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/apps-upload?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/appsource/post-publish/application-certification.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/deploy-and-publish/appsource/post-publish/application-certification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/post-publish/application-certification?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/appsource/post-publish/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/deploy-and-publish/appsource/post-publish/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/post-publish/overview?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/appsource/prepare/app-manifest-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/deploy-and-publish/appsource/prepare/app-manifest-checklist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/app-manifest-checklist?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/appsource/prepare/detail [...]

2021-01-22 08:49 UTC, opbld33 commented
Docs Build status updates of commit _[cf38d2a](https://github.com/MicrosoftDocs/msteams-docs/commits/cf38d2a9f9595481f73501e0fe37ebdcce732d68)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/build-and-test/share-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/share-to-teams.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/share-to-teams?branch=pr-en-us-2615) | [Details](#user-content-9b7bb6a9-72fd217a)
[msteams-platform/concepts/build-and-test/test-data.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/test-data.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/test-data?branch=pr-en-us-2615) | [Details](#user-content-e6544f21-72fd217a)
[msteams-platform/graph-api/rsc/test-rsc-json-file.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/graph-api/rsc/test-rsc-json-file.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/graph-api/rsc/test-rsc-json-file?branch=pr-en-us-2615) | [Details](#user-content-1e54d419-72fd217a)
[msteams-platform/resources/bot-v3/bot-conversations/bots-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/resources/bot-v3/bot-conversations/bots-conversations.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bot-conversations/bots-conversations?branch=pr-en-us-2615) | [Details](#user-content-a440589b-72fd217a)
[msteams-platform/resources/bot-v3/bots-create.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/resources/bot-v3/bots-create.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bots-create?branch=pr-en-us-2615) | [Details](#user-content-277fabd2-72fd217a)
[msteams-platform/resources/dev-preview/developer-preview-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/resources/dev-preview/developer-preview-features.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/dev-preview/developer-preview-features?branch=pr-en-us-2615) | [Details](#user-content-090bc781-72fd217a)
[msteams-platform/samples/shifts-wfm-connectors.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/samples/shifts-wfm-connectors.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/samples/shifts-wfm-connectors?branch=pr-en-us-2615) | [Details](#user-content-0aa593ad-72fd217a)
[msteams-platform/samples/virtual-assistant.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/samples/virtual-assistant.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/samples/virtual-assistant?branch=pr-en-us-2615) | [Details](#user-content-dc23a873-72fd217a)
[msteams-platform/tabs/how-to/developer-tools.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/tabs/how-to/developer-tools.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/developer-tools?branch=pr-en-us-2615) | [Details](#user-content-a1ca09f1-72fd217a)
[msteams-platform/bots/calls-and-meetings/debugging-local-testing-calling-meeting-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/bots/calls-and-meetings/debugging-local-testing-calling-meeting-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/calls-and-meetings/debugging-local-testing-calling-meeting-bots?branch=pr-en-us-2615) |
[msteams-platform/bots/calls-and-meetings/requirements-considerations-application-hosted-media-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/bots/calls-and-meetings/requirements-considerations-application-hosted-media-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/calls-and-meetings/requirements-considerations-application-hosted-media-bots?branch=pr-en-us-2615) |
[msteams-platform/concepts/authentication/authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/authentication/authentication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/authentication/authentication?branch=pr-en-us-2615) |
[msteams-platform/concepts/authentication/configure-identity-provider.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/authentication/configure-identity-provider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/authentication/configure-identity-provider?branch=pr-en-us-2615) |
[msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/apps-localization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/apps-localization?branch=pr-en-us-2615) |
[msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/deep-links.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links?branch=pr-en-us-2615) |
[msteams-platform/concepts/build-and-test/prepare-your-o365-tenant.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/prepare-your-o365-tenant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/prepare-your-o365-tenant?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/deploy-and-publish/apps-upload.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/apps-upload?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/appsource/post-publish/application-certification.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/deploy-and-publish/appsource/post-publish/application-certification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/post-publish/application-certification?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/appsource/post-publish/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/deploy-and-publish/appsource/post-publish/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/post-publish/overview?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/appsource/prepare/app-manifest-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/deploy-and-publish/appsource/prepare/app-manifest-checklist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/app-manifest-checklist?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/appsource/prepare/detail [...]

2021-01-22 08:50 UTC, opbld30 commented
Docs Build status updates of commit _[8793b09](https://github.com/MicrosoftDocs/msteams-docs/commits/8793b097be56a3ad4076d0aa8ea7780490de1e14)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/build-and-test/share-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/share-to-teams.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/share-to-teams?branch=pr-en-us-2615) | [Details](#user-content-9b7bb6a9-d36d102d)
[msteams-platform/concepts/build-and-test/test-data.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/test-data.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/test-data?branch=pr-en-us-2615) | [Details](#user-content-e6544f21-d36d102d)
[msteams-platform/graph-api/rsc/test-rsc-json-file.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/graph-api/rsc/test-rsc-json-file.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/graph-api/rsc/test-rsc-json-file?branch=pr-en-us-2615) | [Details](#user-content-1e54d419-d36d102d)
[msteams-platform/resources/bot-v3/bot-conversations/bots-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/resources/bot-v3/bot-conversations/bots-conversations.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bot-conversations/bots-conversations?branch=pr-en-us-2615) | [Details](#user-content-a440589b-d36d102d)
[msteams-platform/resources/bot-v3/bots-create.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/resources/bot-v3/bots-create.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bots-create?branch=pr-en-us-2615) | [Details](#user-content-277fabd2-d36d102d)
[msteams-platform/resources/dev-preview/developer-preview-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/resources/dev-preview/developer-preview-features.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/dev-preview/developer-preview-features?branch=pr-en-us-2615) | [Details](#user-content-090bc781-d36d102d)
[msteams-platform/samples/shifts-wfm-connectors.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/samples/shifts-wfm-connectors.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/samples/shifts-wfm-connectors?branch=pr-en-us-2615) | [Details](#user-content-0aa593ad-d36d102d)
[msteams-platform/samples/virtual-assistant.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/samples/virtual-assistant.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/samples/virtual-assistant?branch=pr-en-us-2615) | [Details](#user-content-dc23a873-d36d102d)
[msteams-platform/tabs/how-to/developer-tools.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/tabs/how-to/developer-tools.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/developer-tools?branch=pr-en-us-2615) | [Details](#user-content-a1ca09f1-d36d102d)
[msteams-platform/bots/calls-and-meetings/debugging-local-testing-calling-meeting-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/bots/calls-and-meetings/debugging-local-testing-calling-meeting-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/calls-and-meetings/debugging-local-testing-calling-meeting-bots?branch=pr-en-us-2615) |
[msteams-platform/bots/calls-and-meetings/requirements-considerations-application-hosted-media-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/bots/calls-and-meetings/requirements-considerations-application-hosted-media-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/calls-and-meetings/requirements-considerations-application-hosted-media-bots?branch=pr-en-us-2615) |
[msteams-platform/concepts/authentication/authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/authentication/authentication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/authentication/authentication?branch=pr-en-us-2615) |
[msteams-platform/concepts/authentication/configure-identity-provider.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/authentication/configure-identity-provider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/authentication/configure-identity-provider?branch=pr-en-us-2615) |
[msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/apps-localization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/apps-localization?branch=pr-en-us-2615) |
[msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/deep-links.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links?branch=pr-en-us-2615) |
[msteams-platform/concepts/build-and-test/prepare-your-o365-tenant.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/prepare-your-o365-tenant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/prepare-your-o365-tenant?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/deploy-and-publish/apps-upload.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/apps-upload?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/appsource/post-publish/application-certification.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/deploy-and-publish/appsource/post-publish/application-certification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/post-publish/application-certification?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/appsource/post-publish/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/deploy-and-publish/appsource/post-publish/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/post-publish/overview?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/appsource/prepare/app-manifest-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/deploy-and-publish/appsource/prepare/app-manifest-checklist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/app-manifest-checklist?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/appsource/prepare/detail [...]

2021-01-22 08:50 UTC, opbld32 commented
Docs Build status updates of commit _[6645b7b](https://github.com/MicrosoftDocs/msteams-docs/commits/6645b7ba2544342268a7edb54cfb6c55d62c6b67)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/build-and-test/share-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/share-to-teams.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/share-to-teams?branch=pr-en-us-2615) | [Details](#user-content-9b7bb6a9-aa46b758)
[msteams-platform/concepts/build-and-test/test-data.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/test-data.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/test-data?branch=pr-en-us-2615) | [Details](#user-content-e6544f21-aa46b758)
[msteams-platform/graph-api/rsc/test-rsc-json-file.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/graph-api/rsc/test-rsc-json-file.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/graph-api/rsc/test-rsc-json-file?branch=pr-en-us-2615) | [Details](#user-content-1e54d419-aa46b758)
[msteams-platform/resources/bot-v3/bot-conversations/bots-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/resources/bot-v3/bot-conversations/bots-conversations.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bot-conversations/bots-conversations?branch=pr-en-us-2615) | [Details](#user-content-a440589b-aa46b758)
[msteams-platform/resources/bot-v3/bots-create.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/resources/bot-v3/bots-create.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bots-create?branch=pr-en-us-2615) | [Details](#user-content-277fabd2-aa46b758)
[msteams-platform/resources/dev-preview/developer-preview-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/resources/dev-preview/developer-preview-features.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/dev-preview/developer-preview-features?branch=pr-en-us-2615) | [Details](#user-content-090bc781-aa46b758)
[msteams-platform/samples/shifts-wfm-connectors.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/samples/shifts-wfm-connectors.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/samples/shifts-wfm-connectors?branch=pr-en-us-2615) | [Details](#user-content-0aa593ad-aa46b758)
[msteams-platform/samples/virtual-assistant.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/samples/virtual-assistant.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/samples/virtual-assistant?branch=pr-en-us-2615) | [Details](#user-content-dc23a873-aa46b758)
[msteams-platform/tabs/how-to/developer-tools.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/tabs/how-to/developer-tools.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/developer-tools?branch=pr-en-us-2615) | [Details](#user-content-a1ca09f1-aa46b758)
[msteams-platform/bots/calls-and-meetings/debugging-local-testing-calling-meeting-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/bots/calls-and-meetings/debugging-local-testing-calling-meeting-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/calls-and-meetings/debugging-local-testing-calling-meeting-bots?branch=pr-en-us-2615) |
[msteams-platform/bots/calls-and-meetings/requirements-considerations-application-hosted-media-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/bots/calls-and-meetings/requirements-considerations-application-hosted-media-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/calls-and-meetings/requirements-considerations-application-hosted-media-bots?branch=pr-en-us-2615) |
[msteams-platform/concepts/authentication/authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/authentication/authentication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/authentication/authentication?branch=pr-en-us-2615) |
[msteams-platform/concepts/authentication/configure-identity-provider.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/authentication/configure-identity-provider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/authentication/configure-identity-provider?branch=pr-en-us-2615) |
[msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/apps-localization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/apps-localization?branch=pr-en-us-2615) |
[msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/deep-links.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links?branch=pr-en-us-2615) |
[msteams-platform/concepts/build-and-test/prepare-your-o365-tenant.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/prepare-your-o365-tenant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/prepare-your-o365-tenant?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/deploy-and-publish/apps-upload.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/apps-upload?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/appsource/post-publish/application-certification.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/deploy-and-publish/appsource/post-publish/application-certification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/post-publish/application-certification?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/appsource/post-publish/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/deploy-and-publish/appsource/post-publish/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/post-publish/overview?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/appsource/prepare/app-manifest-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/deploy-and-publish/appsource/prepare/app-manifest-checklist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/app-manifest-checklist?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/appsource/prepare/detail [...]

2021-01-22 08:51 UTC, opbld32 commented
Docs Build status updates of commit _[8f72f31](https://github.com/MicrosoftDocs/msteams-docs/commits/8f72f31f84b20cda3060fc02f3330ab056e14819)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/build-and-test/share-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/share-to-teams.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/share-to-teams?branch=pr-en-us-2615) | [Details](#user-content-9b7bb6a9-6f79442c)
[msteams-platform/concepts/build-and-test/test-data.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/test-data.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/test-data?branch=pr-en-us-2615) | [Details](#user-content-e6544f21-6f79442c)
[msteams-platform/graph-api/rsc/test-rsc-json-file.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/graph-api/rsc/test-rsc-json-file.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/graph-api/rsc/test-rsc-json-file?branch=pr-en-us-2615) | [Details](#user-content-1e54d419-6f79442c)
[msteams-platform/resources/bot-v3/bot-conversations/bots-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/resources/bot-v3/bot-conversations/bots-conversations.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bot-conversations/bots-conversations?branch=pr-en-us-2615) | [Details](#user-content-a440589b-6f79442c)
[msteams-platform/resources/bot-v3/bots-create.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/resources/bot-v3/bots-create.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bots-create?branch=pr-en-us-2615) | [Details](#user-content-277fabd2-6f79442c)
[msteams-platform/resources/dev-preview/developer-preview-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/resources/dev-preview/developer-preview-features.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/dev-preview/developer-preview-features?branch=pr-en-us-2615) | [Details](#user-content-090bc781-6f79442c)
[msteams-platform/samples/shifts-wfm-connectors.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/samples/shifts-wfm-connectors.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/samples/shifts-wfm-connectors?branch=pr-en-us-2615) | [Details](#user-content-0aa593ad-6f79442c)
[msteams-platform/samples/virtual-assistant.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/samples/virtual-assistant.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/samples/virtual-assistant?branch=pr-en-us-2615) | [Details](#user-content-dc23a873-6f79442c)
[msteams-platform/tabs/how-to/developer-tools.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/tabs/how-to/developer-tools.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/developer-tools?branch=pr-en-us-2615) | [Details](#user-content-a1ca09f1-6f79442c)
[msteams-platform/bots/calls-and-meetings/debugging-local-testing-calling-meeting-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/bots/calls-and-meetings/debugging-local-testing-calling-meeting-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/calls-and-meetings/debugging-local-testing-calling-meeting-bots?branch=pr-en-us-2615) |
[msteams-platform/bots/calls-and-meetings/requirements-considerations-application-hosted-media-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/bots/calls-and-meetings/requirements-considerations-application-hosted-media-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/calls-and-meetings/requirements-considerations-application-hosted-media-bots?branch=pr-en-us-2615) |
[msteams-platform/concepts/authentication/authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/authentication/authentication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/authentication/authentication?branch=pr-en-us-2615) |
[msteams-platform/concepts/authentication/configure-identity-provider.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/authentication/configure-identity-provider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/authentication/configure-identity-provider?branch=pr-en-us-2615) |
[msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/apps-localization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/apps-localization?branch=pr-en-us-2615) |
[msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/deep-links.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links?branch=pr-en-us-2615) |
[msteams-platform/concepts/build-and-test/prepare-your-o365-tenant.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/prepare-your-o365-tenant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/prepare-your-o365-tenant?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/deploy-and-publish/apps-upload.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/apps-upload?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/appsource/post-publish/application-certification.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/deploy-and-publish/appsource/post-publish/application-certification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/post-publish/application-certification?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/appsource/post-publish/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/deploy-and-publish/appsource/post-publish/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/post-publish/overview?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/appsource/prepare/app-manifest-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/deploy-and-publish/appsource/prepare/app-manifest-checklist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/app-manifest-checklist?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/appsource/prepare/detail [...]

2021-01-22 08:52 UTC, opbld31 commented
Docs Build status updates of commit _[04ef42b](https://github.com/MicrosoftDocs/msteams-docs/commits/04ef42b696abb30b570c7fc408d02b361ccf7c0d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/build-and-test/share-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/share-to-teams.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/share-to-teams?branch=pr-en-us-2615) | [Details](#user-content-9b7bb6a9-976f05d2)
[msteams-platform/concepts/build-and-test/test-data.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/test-data.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/test-data?branch=pr-en-us-2615) | [Details](#user-content-e6544f21-976f05d2)
[msteams-platform/graph-api/rsc/test-rsc-json-file.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/graph-api/rsc/test-rsc-json-file.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/graph-api/rsc/test-rsc-json-file?branch=pr-en-us-2615) | [Details](#user-content-1e54d419-976f05d2)
[msteams-platform/resources/bot-v3/bot-conversations/bots-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/resources/bot-v3/bot-conversations/bots-conversations.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bot-conversations/bots-conversations?branch=pr-en-us-2615) | [Details](#user-content-a440589b-976f05d2)
[msteams-platform/resources/bot-v3/bots-create.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/resources/bot-v3/bots-create.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bots-create?branch=pr-en-us-2615) | [Details](#user-content-277fabd2-976f05d2)
[msteams-platform/resources/dev-preview/developer-preview-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/resources/dev-preview/developer-preview-features.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/dev-preview/developer-preview-features?branch=pr-en-us-2615) | [Details](#user-content-090bc781-976f05d2)
[msteams-platform/samples/shifts-wfm-connectors.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/samples/shifts-wfm-connectors.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/samples/shifts-wfm-connectors?branch=pr-en-us-2615) | [Details](#user-content-0aa593ad-976f05d2)
[msteams-platform/samples/virtual-assistant.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/samples/virtual-assistant.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/samples/virtual-assistant?branch=pr-en-us-2615) | [Details](#user-content-dc23a873-976f05d2)
[msteams-platform/tabs/how-to/developer-tools.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/tabs/how-to/developer-tools.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/developer-tools?branch=pr-en-us-2615) | [Details](#user-content-a1ca09f1-976f05d2)
[msteams-platform/bots/calls-and-meetings/debugging-local-testing-calling-meeting-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/bots/calls-and-meetings/debugging-local-testing-calling-meeting-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/calls-and-meetings/debugging-local-testing-calling-meeting-bots?branch=pr-en-us-2615) |
[msteams-platform/bots/calls-and-meetings/requirements-considerations-application-hosted-media-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/bots/calls-and-meetings/requirements-considerations-application-hosted-media-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/calls-and-meetings/requirements-considerations-application-hosted-media-bots?branch=pr-en-us-2615) |
[msteams-platform/concepts/authentication/authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/authentication/authentication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/authentication/authentication?branch=pr-en-us-2615) |
[msteams-platform/concepts/authentication/configure-identity-provider.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/authentication/configure-identity-provider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/authentication/configure-identity-provider?branch=pr-en-us-2615) |
[msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/apps-localization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/apps-localization?branch=pr-en-us-2615) |
[msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/deep-links.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links?branch=pr-en-us-2615) |
[msteams-platform/concepts/build-and-test/prepare-your-o365-tenant.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/prepare-your-o365-tenant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/prepare-your-o365-tenant?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/deploy-and-publish/apps-upload.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/apps-upload?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/appsource/post-publish/application-certification.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/deploy-and-publish/appsource/post-publish/application-certification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/post-publish/application-certification?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/appsource/post-publish/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/deploy-and-publish/appsource/post-publish/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/post-publish/overview?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/appsource/prepare/app-manifest-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/deploy-and-publish/appsource/prepare/app-manifest-checklist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/app-manifest-checklist?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/appsource/prepare/detail [...]

2021-01-22 08:52 UTC, opbld30 commented
Docs Build status updates of commit _[b9fd43a](https://github.com/MicrosoftDocs/msteams-docs/commits/b9fd43a6788d5a4b632fdcd4477d1e516293cad0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/build-and-test/share-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/share-to-teams.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/share-to-teams?branch=pr-en-us-2615) | [Details](#user-content-9b7bb6a9-939770cd)
[msteams-platform/concepts/build-and-test/test-data.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/test-data.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/test-data?branch=pr-en-us-2615) | [Details](#user-content-e6544f21-939770cd)
[msteams-platform/graph-api/rsc/test-rsc-json-file.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/graph-api/rsc/test-rsc-json-file.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/graph-api/rsc/test-rsc-json-file?branch=pr-en-us-2615) | [Details](#user-content-1e54d419-939770cd)
[msteams-platform/resources/bot-v3/bot-conversations/bots-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/resources/bot-v3/bot-conversations/bots-conversations.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bot-conversations/bots-conversations?branch=pr-en-us-2615) | [Details](#user-content-a440589b-939770cd)
[msteams-platform/resources/bot-v3/bots-create.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/resources/bot-v3/bots-create.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bots-create?branch=pr-en-us-2615) | [Details](#user-content-277fabd2-939770cd)
[msteams-platform/resources/dev-preview/developer-preview-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/resources/dev-preview/developer-preview-features.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/dev-preview/developer-preview-features?branch=pr-en-us-2615) | [Details](#user-content-090bc781-939770cd)
[msteams-platform/samples/shifts-wfm-connectors.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/samples/shifts-wfm-connectors.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/samples/shifts-wfm-connectors?branch=pr-en-us-2615) | [Details](#user-content-0aa593ad-939770cd)
[msteams-platform/samples/virtual-assistant.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/samples/virtual-assistant.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/samples/virtual-assistant?branch=pr-en-us-2615) | [Details](#user-content-dc23a873-939770cd)
[msteams-platform/tabs/how-to/developer-tools.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/tabs/how-to/developer-tools.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/developer-tools?branch=pr-en-us-2615) | [Details](#user-content-a1ca09f1-939770cd)
[msteams-platform/bots/calls-and-meetings/debugging-local-testing-calling-meeting-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/bots/calls-and-meetings/debugging-local-testing-calling-meeting-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/calls-and-meetings/debugging-local-testing-calling-meeting-bots?branch=pr-en-us-2615) |
[msteams-platform/bots/calls-and-meetings/requirements-considerations-application-hosted-media-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/bots/calls-and-meetings/requirements-considerations-application-hosted-media-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/calls-and-meetings/requirements-considerations-application-hosted-media-bots?branch=pr-en-us-2615) |
[msteams-platform/concepts/authentication/authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/authentication/authentication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/authentication/authentication?branch=pr-en-us-2615) |
[msteams-platform/concepts/authentication/configure-identity-provider.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/authentication/configure-identity-provider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/authentication/configure-identity-provider?branch=pr-en-us-2615) |
[msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/apps-localization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/apps-localization?branch=pr-en-us-2615) |
[msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/deep-links.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links?branch=pr-en-us-2615) |
[msteams-platform/concepts/build-and-test/prepare-your-o365-tenant.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/prepare-your-o365-tenant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/prepare-your-o365-tenant?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/deploy-and-publish/apps-upload.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/apps-upload?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/appsource/post-publish/application-certification.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/deploy-and-publish/appsource/post-publish/application-certification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/post-publish/application-certification?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/appsource/post-publish/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/deploy-and-publish/appsource/post-publish/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/post-publish/overview?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/appsource/prepare/app-manifest-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/deploy-and-publish/appsource/prepare/app-manifest-checklist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/app-manifest-checklist?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/appsource/prepare/detail [...]

2021-01-22 08:53 UTC, opbld31 commented
Docs Build status updates of commit _[5b6c61b](https://github.com/MicrosoftDocs/msteams-docs/commits/5b6c61b61c4231f61d73a0c564667c517e1c7624)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/build-and-test/share-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/share-to-teams.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/share-to-teams?branch=pr-en-us-2615) | [Details](#user-content-9b7bb6a9-d5bf91f5)
[msteams-platform/concepts/build-and-test/test-data.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/test-data.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/test-data?branch=pr-en-us-2615) | [Details](#user-content-e6544f21-d5bf91f5)
[msteams-platform/graph-api/rsc/test-rsc-json-file.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/graph-api/rsc/test-rsc-json-file.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/graph-api/rsc/test-rsc-json-file?branch=pr-en-us-2615) | [Details](#user-content-1e54d419-d5bf91f5)
[msteams-platform/resources/bot-v3/bot-conversations/bots-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/resources/bot-v3/bot-conversations/bots-conversations.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bot-conversations/bots-conversations?branch=pr-en-us-2615) | [Details](#user-content-a440589b-d5bf91f5)
[msteams-platform/resources/bot-v3/bots-create.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/resources/bot-v3/bots-create.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bots-create?branch=pr-en-us-2615) | [Details](#user-content-277fabd2-d5bf91f5)
[msteams-platform/resources/dev-preview/developer-preview-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/resources/dev-preview/developer-preview-features.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/dev-preview/developer-preview-features?branch=pr-en-us-2615) | [Details](#user-content-090bc781-d5bf91f5)
[msteams-platform/samples/shifts-wfm-connectors.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/samples/shifts-wfm-connectors.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/samples/shifts-wfm-connectors?branch=pr-en-us-2615) | [Details](#user-content-0aa593ad-d5bf91f5)
[msteams-platform/samples/virtual-assistant.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/samples/virtual-assistant.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/samples/virtual-assistant?branch=pr-en-us-2615) | [Details](#user-content-dc23a873-d5bf91f5)
[msteams-platform/tabs/how-to/developer-tools.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/tabs/how-to/developer-tools.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/developer-tools?branch=pr-en-us-2615) | [Details](#user-content-a1ca09f1-d5bf91f5)
[msteams-platform/bots/calls-and-meetings/debugging-local-testing-calling-meeting-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/bots/calls-and-meetings/debugging-local-testing-calling-meeting-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/calls-and-meetings/debugging-local-testing-calling-meeting-bots?branch=pr-en-us-2615) |
[msteams-platform/bots/calls-and-meetings/requirements-considerations-application-hosted-media-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/bots/calls-and-meetings/requirements-considerations-application-hosted-media-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/calls-and-meetings/requirements-considerations-application-hosted-media-bots?branch=pr-en-us-2615) |
[msteams-platform/concepts/authentication/authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/authentication/authentication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/authentication/authentication?branch=pr-en-us-2615) |
[msteams-platform/concepts/authentication/configure-identity-provider.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/authentication/configure-identity-provider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/authentication/configure-identity-provider?branch=pr-en-us-2615) |
[msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/apps-localization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/apps-localization?branch=pr-en-us-2615) |
[msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/deep-links.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links?branch=pr-en-us-2615) |
[msteams-platform/concepts/build-and-test/prepare-your-o365-tenant.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/prepare-your-o365-tenant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/prepare-your-o365-tenant?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/deploy-and-publish/apps-upload.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/apps-upload?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/appsource/post-publish/application-certification.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/deploy-and-publish/appsource/post-publish/application-certification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/post-publish/application-certification?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/appsource/post-publish/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/deploy-and-publish/appsource/post-publish/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/post-publish/overview?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/appsource/prepare/app-manifest-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/deploy-and-publish/appsource/prepare/app-manifest-checklist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/app-manifest-checklist?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/appsource/prepare/detail [...]

2021-01-22 08:54 UTC, opbld30 commented
Docs Build status updates of commit _[d0c8e9e](https://github.com/MicrosoftDocs/msteams-docs/commits/d0c8e9e6dced3866500ed81043c0f3b99702f0da)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/build-and-test/share-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/share-to-teams.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/share-to-teams?branch=pr-en-us-2615) | [Details](#user-content-9b7bb6a9-fa3451d1)
[msteams-platform/concepts/build-and-test/test-data.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/test-data.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/test-data?branch=pr-en-us-2615) | [Details](#user-content-e6544f21-fa3451d1)
[msteams-platform/graph-api/rsc/test-rsc-json-file.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/graph-api/rsc/test-rsc-json-file.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/graph-api/rsc/test-rsc-json-file?branch=pr-en-us-2615) | [Details](#user-content-1e54d419-fa3451d1)
[msteams-platform/resources/bot-v3/bot-conversations/bots-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/resources/bot-v3/bot-conversations/bots-conversations.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bot-conversations/bots-conversations?branch=pr-en-us-2615) | [Details](#user-content-a440589b-fa3451d1)
[msteams-platform/resources/bot-v3/bots-create.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/resources/bot-v3/bots-create.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bots-create?branch=pr-en-us-2615) | [Details](#user-content-277fabd2-fa3451d1)
[msteams-platform/resources/dev-preview/developer-preview-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/resources/dev-preview/developer-preview-features.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/dev-preview/developer-preview-features?branch=pr-en-us-2615) | [Details](#user-content-090bc781-fa3451d1)
[msteams-platform/samples/shifts-wfm-connectors.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/samples/shifts-wfm-connectors.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/samples/shifts-wfm-connectors?branch=pr-en-us-2615) | [Details](#user-content-0aa593ad-fa3451d1)
[msteams-platform/samples/virtual-assistant.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/samples/virtual-assistant.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/samples/virtual-assistant?branch=pr-en-us-2615) | [Details](#user-content-dc23a873-fa3451d1)
[msteams-platform/tabs/how-to/developer-tools.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/tabs/how-to/developer-tools.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/developer-tools?branch=pr-en-us-2615) | [Details](#user-content-a1ca09f1-fa3451d1)
[msteams-platform/bots/calls-and-meetings/debugging-local-testing-calling-meeting-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/bots/calls-and-meetings/debugging-local-testing-calling-meeting-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/calls-and-meetings/debugging-local-testing-calling-meeting-bots?branch=pr-en-us-2615) |
[msteams-platform/bots/calls-and-meetings/requirements-considerations-application-hosted-media-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/bots/calls-and-meetings/requirements-considerations-application-hosted-media-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/calls-and-meetings/requirements-considerations-application-hosted-media-bots?branch=pr-en-us-2615) |
[msteams-platform/concepts/authentication/authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/authentication/authentication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/authentication/authentication?branch=pr-en-us-2615) |
[msteams-platform/concepts/authentication/configure-identity-provider.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/authentication/configure-identity-provider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/authentication/configure-identity-provider?branch=pr-en-us-2615) |
[msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/apps-localization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/apps-localization?branch=pr-en-us-2615) |
[msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/deep-links.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links?branch=pr-en-us-2615) |
[msteams-platform/concepts/build-and-test/prepare-your-o365-tenant.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/prepare-your-o365-tenant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/prepare-your-o365-tenant?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/deploy-and-publish/apps-upload.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/apps-upload?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/appsource/post-publish/application-certification.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/deploy-and-publish/appsource/post-publish/application-certification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/post-publish/application-certification?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/appsource/post-publish/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/deploy-and-publish/appsource/post-publish/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/post-publish/overview?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/appsource/prepare/app-manifest-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/deploy-and-publish/appsource/prepare/app-manifest-checklist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/app-manifest-checklist?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/appsource/prepare/detail [...]

2021-01-22 08:54 UTC, opbld32 commented
Docs Build status updates of commit _[2c04b18](https://github.com/MicrosoftDocs/msteams-docs/commits/2c04b18469d47e7a2b65c2541656e979d9384e40)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/build-and-test/share-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/share-to-teams.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/share-to-teams?branch=pr-en-us-2615) | [Details](#user-content-9b7bb6a9-5743ad09)
[msteams-platform/concepts/build-and-test/test-data.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/test-data.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/test-data?branch=pr-en-us-2615) | [Details](#user-content-e6544f21-5743ad09)
[msteams-platform/graph-api/rsc/test-rsc-json-file.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/graph-api/rsc/test-rsc-json-file.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/graph-api/rsc/test-rsc-json-file?branch=pr-en-us-2615) | [Details](#user-content-1e54d419-5743ad09)
[msteams-platform/resources/bot-v3/bot-conversations/bots-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/resources/bot-v3/bot-conversations/bots-conversations.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bot-conversations/bots-conversations?branch=pr-en-us-2615) | [Details](#user-content-a440589b-5743ad09)
[msteams-platform/resources/bot-v3/bots-create.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/resources/bot-v3/bots-create.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bots-create?branch=pr-en-us-2615) | [Details](#user-content-277fabd2-5743ad09)
[msteams-platform/resources/dev-preview/developer-preview-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/resources/dev-preview/developer-preview-features.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/dev-preview/developer-preview-features?branch=pr-en-us-2615) | [Details](#user-content-090bc781-5743ad09)
[msteams-platform/samples/shifts-wfm-connectors.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/samples/shifts-wfm-connectors.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/samples/shifts-wfm-connectors?branch=pr-en-us-2615) | [Details](#user-content-0aa593ad-5743ad09)
[msteams-platform/samples/virtual-assistant.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/samples/virtual-assistant.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/samples/virtual-assistant?branch=pr-en-us-2615) | [Details](#user-content-dc23a873-5743ad09)
[msteams-platform/tabs/how-to/developer-tools.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/tabs/how-to/developer-tools.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/developer-tools?branch=pr-en-us-2615) | [Details](#user-content-a1ca09f1-5743ad09)
[msteams-platform/bots/calls-and-meetings/debugging-local-testing-calling-meeting-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/bots/calls-and-meetings/debugging-local-testing-calling-meeting-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/calls-and-meetings/debugging-local-testing-calling-meeting-bots?branch=pr-en-us-2615) |
[msteams-platform/bots/calls-and-meetings/requirements-considerations-application-hosted-media-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/bots/calls-and-meetings/requirements-considerations-application-hosted-media-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/calls-and-meetings/requirements-considerations-application-hosted-media-bots?branch=pr-en-us-2615) |
[msteams-platform/concepts/authentication/authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/authentication/authentication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/authentication/authentication?branch=pr-en-us-2615) |
[msteams-platform/concepts/authentication/configure-identity-provider.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/authentication/configure-identity-provider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/authentication/configure-identity-provider?branch=pr-en-us-2615) |
[msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/apps-localization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/apps-localization?branch=pr-en-us-2615) |
[msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/deep-links.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links?branch=pr-en-us-2615) |
[msteams-platform/concepts/build-and-test/prepare-your-o365-tenant.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/prepare-your-o365-tenant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/prepare-your-o365-tenant?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/deploy-and-publish/apps-upload.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/apps-upload?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/appsource/post-publish/application-certification.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/deploy-and-publish/appsource/post-publish/application-certification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/post-publish/application-certification?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/appsource/post-publish/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/deploy-and-publish/appsource/post-publish/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/post-publish/overview?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/appsource/prepare/app-manifest-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/deploy-and-publish/appsource/prepare/app-manifest-checklist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/app-manifest-checklist?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/appsource/prepare/detail [...]

2021-01-22 08:55 UTC, opbld31 commented
Docs Build status updates of commit _[ab29411](https://github.com/MicrosoftDocs/msteams-docs/commits/ab294114460fcc3df49aab3d82738e4831356d20)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/build-and-test/share-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/share-to-teams.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/share-to-teams?branch=pr-en-us-2615) | [Details](#user-content-9b7bb6a9-07f74e35)
[msteams-platform/concepts/build-and-test/test-data.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/test-data.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/test-data?branch=pr-en-us-2615) | [Details](#user-content-e6544f21-07f74e35)
[msteams-platform/graph-api/rsc/test-rsc-json-file.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/graph-api/rsc/test-rsc-json-file.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/graph-api/rsc/test-rsc-json-file?branch=pr-en-us-2615) | [Details](#user-content-1e54d419-07f74e35)
[msteams-platform/resources/bot-v3/bot-conversations/bots-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/resources/bot-v3/bot-conversations/bots-conversations.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bot-conversations/bots-conversations?branch=pr-en-us-2615) | [Details](#user-content-a440589b-07f74e35)
[msteams-platform/resources/bot-v3/bots-create.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/resources/bot-v3/bots-create.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bots-create?branch=pr-en-us-2615) | [Details](#user-content-277fabd2-07f74e35)
[msteams-platform/resources/dev-preview/developer-preview-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/resources/dev-preview/developer-preview-features.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/dev-preview/developer-preview-features?branch=pr-en-us-2615) | [Details](#user-content-090bc781-07f74e35)
[msteams-platform/samples/shifts-wfm-connectors.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/samples/shifts-wfm-connectors.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/samples/shifts-wfm-connectors?branch=pr-en-us-2615) | [Details](#user-content-0aa593ad-07f74e35)
[msteams-platform/samples/virtual-assistant.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/samples/virtual-assistant.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/samples/virtual-assistant?branch=pr-en-us-2615) | [Details](#user-content-dc23a873-07f74e35)
[msteams-platform/tabs/how-to/developer-tools.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/tabs/how-to/developer-tools.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/developer-tools?branch=pr-en-us-2615) | [Details](#user-content-a1ca09f1-07f74e35)
[msteams-platform/bots/calls-and-meetings/debugging-local-testing-calling-meeting-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/bots/calls-and-meetings/debugging-local-testing-calling-meeting-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/calls-and-meetings/debugging-local-testing-calling-meeting-bots?branch=pr-en-us-2615) |
[msteams-platform/bots/calls-and-meetings/requirements-considerations-application-hosted-media-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/bots/calls-and-meetings/requirements-considerations-application-hosted-media-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/calls-and-meetings/requirements-considerations-application-hosted-media-bots?branch=pr-en-us-2615) |
[msteams-platform/concepts/authentication/authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/authentication/authentication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/authentication/authentication?branch=pr-en-us-2615) |
[msteams-platform/concepts/authentication/configure-identity-provider.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/authentication/configure-identity-provider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/authentication/configure-identity-provider?branch=pr-en-us-2615) |
[msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/apps-localization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/apps-localization?branch=pr-en-us-2615) |
[msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/deep-links.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links?branch=pr-en-us-2615) |
[msteams-platform/concepts/build-and-test/prepare-your-o365-tenant.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/build-and-test/prepare-your-o365-tenant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/prepare-your-o365-tenant?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/deploy-and-publish/apps-upload.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/apps-upload?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/appsource/post-publish/application-certification.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/deploy-and-publish/appsource/post-publish/application-certification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/post-publish/application-certification?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/appsource/post-publish/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/deploy-and-publish/appsource/post-publish/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/post-publish/overview?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/appsource/prepare/app-manifest-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/testmd/msteams-platform/concepts/deploy-and-publish/appsource/prepare/app-manifest-checklist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/app-manifest-checklist?branch=pr-en-us-2615) |
[msteams-platform/concepts/deploy-and-publish/appsource/prepare/detail [...]

2021-01-22 08:59 UTC, KirtiPereira approved these changes
Approved.

2021-01-22 09:01 UTC, surbhigupta12 commented
@heath-hamilton, I've incorporated your suggestions. Please approve the PR if everything is fine.

2021-01-22 16:58 UTC, heath-hamilton approved these changes

2021-01-27 06:14 UTC, merged