(policy)(doc enhancement)(1462062)
MicrosoftDocs/msteams-docs pull request #2650
Opened 2021-01-21 08:02 UTC by Mahesh2516

Updated the content. Please review

2021-01-21 08:03 UTC, opbld32 commented
Docs Build status updates of commit _[ab276c8](https://github.com/MicrosoftDocs/msteams-docs/commits/ab276c8e9db317bc603126f1a2141acbac0b5d92)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/faq/Sampleapp1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/(Policy)(Doc-Enhancement)(1462062)/msteams-platform/assets/images/faq/Sampleapp1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases?branch=pr-en-us-2650) |
[msteams-platform/assets/images/faq/Sampleapp2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/(Policy)(Doc-Enhancement)(1462062)/msteams-platform/assets/images/faq/Sampleapp2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases?branch=pr-en-us-2650) |
[msteams-platform/assets/images/faq/helpcommand.png](https://github.com/MicrosoftDocs/msteams-docs/blob/(Policy)(Doc-Enhancement)(1462062)/msteams-platform/assets/images/faq/helpcommand.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases?branch=pr-en-us-2650) |
[msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md](https://github.com/MicrosoftDocs/msteams-docs/blob/(Policy)(Doc-Enhancement)(1462062)/msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases?branch=pr-en-us-2650) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C21%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202101210803029529-2650%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=zwZ0%2Fedyd7Z1yyGIF%2FVPpfXnU%2BiKCCIO%2FZX7eYiuuIE%3D&st=2021-01-21T07%3A58%3A53Z&se=2021-02-21T08%3A03%3A53Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-26 04:42 UTC, opbld32 commented
Docs Build status updates of commit _[0bdfe1b](https://github.com/MicrosoftDocs/msteams-docs/commits/0bdfe1b114a36c365fa93b1ff36b1228636c96d6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/faq/Sampleapp1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/(Policy)(Doc-Enhancement)(1462062)/msteams-platform/assets/images/faq/Sampleapp1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases?branch=pr-en-us-2650) |
[msteams-platform/assets/images/faq/Sampleapp2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/(Policy)(Doc-Enhancement)(1462062)/msteams-platform/assets/images/faq/Sampleapp2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases?branch=pr-en-us-2650) |
[msteams-platform/assets/images/faq/helpcommand.png](https://github.com/MicrosoftDocs/msteams-docs/blob/(Policy)(Doc-Enhancement)(1462062)/msteams-platform/assets/images/faq/helpcommand.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases?branch=pr-en-us-2650) |
[msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md](https://github.com/MicrosoftDocs/msteams-docs/blob/(Policy)(Doc-Enhancement)(1462062)/msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases?branch=pr-en-us-2650) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C26%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202101260441152432-2650%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2BEq0wsX3%2B9D8yNAFSFwCcSSt8ipXV0bZw5EBpJJqYzs%3D&st=2021-01-26T04%3A37%3A07Z&se=2021-02-26T04%3A42%3A07Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-26 08:04 UTC, opbld31 commented
Docs Build status updates of commit _[b3231f1](https://github.com/MicrosoftDocs/msteams-docs/commits/b3231f1c0cc70eb1c3b66c0a8884fdf554131068)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/faq/Sampleapp1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/(Policy)(Doc-Enhancement)(1462062)/msteams-platform/assets/images/faq/Sampleapp1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases?branch=pr-en-us-2650) |
[msteams-platform/assets/images/faq/Sampleapp2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/(Policy)(Doc-Enhancement)(1462062)/msteams-platform/assets/images/faq/Sampleapp2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases?branch=pr-en-us-2650) |
[msteams-platform/assets/images/faq/helpcommand.png](https://github.com/MicrosoftDocs/msteams-docs/blob/(Policy)(Doc-Enhancement)(1462062)/msteams-platform/assets/images/faq/helpcommand.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases?branch=pr-en-us-2650) |
[msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md](https://github.com/MicrosoftDocs/msteams-docs/blob/(Policy)(Doc-Enhancement)(1462062)/msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases?branch=pr-en-us-2650) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C26%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202101260804063734-2650%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=qLwz9sdiSAgDPm%2FzMT5r8c5j7rdB4Yd%2BbbLk%2Fxwy4Mo%3D&st=2021-01-26T07%3A59%3A36Z&se=2021-02-26T08%3A04%3A36Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-26 11:33 UTC, opbld30 commented
Docs Build status updates of commit _[e770ae5](https://github.com/MicrosoftDocs/msteams-docs/commits/e770ae5b90319c71f59703556fca6e00fa06430a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/faq/Sampleapp1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/(Policy)(Doc-Enhancement)(1462062)/msteams-platform/assets/images/faq/Sampleapp1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases?branch=pr-en-us-2650) |
[msteams-platform/assets/images/faq/Sampleapp2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/(Policy)(Doc-Enhancement)(1462062)/msteams-platform/assets/images/faq/Sampleapp2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases?branch=pr-en-us-2650) |
[msteams-platform/assets/images/faq/helpcommand.png](https://github.com/MicrosoftDocs/msteams-docs/blob/(Policy)(Doc-Enhancement)(1462062)/msteams-platform/assets/images/faq/helpcommand.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases?branch=pr-en-us-2650) |
[msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md](https://github.com/MicrosoftDocs/msteams-docs/blob/(Policy)(Doc-Enhancement)(1462062)/msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases?branch=pr-en-us-2650) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C26%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202101261132497385-2650%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ahsm6eNbZsAQv5wARW8OsKyHdjKpr6o5oM8BYWm9Njk%3D&st=2021-01-26T11%3A28%3A23Z&se=2021-02-26T11%3A33%3A23Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-27 03:33 UTC, opbld30 commented
Docs Build status updates of commit _[82825e0](https://github.com/MicrosoftDocs/msteams-docs/commits/82825e07f395bf415f6b54f8350304a33e6a7699)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/faq/Sampleapp1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/(Policy)(Doc-Enhancement)(1462062)/msteams-platform/assets/images/faq/Sampleapp1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases?branch=pr-en-us-2650) |
[msteams-platform/assets/images/faq/Sampleapp2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/(Policy)(Doc-Enhancement)(1462062)/msteams-platform/assets/images/faq/Sampleapp2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases?branch=pr-en-us-2650) |
[msteams-platform/assets/images/faq/helpcommand.png](https://github.com/MicrosoftDocs/msteams-docs/blob/(Policy)(Doc-Enhancement)(1462062)/msteams-platform/assets/images/faq/helpcommand.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases?branch=pr-en-us-2650) |
[msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md](https://github.com/MicrosoftDocs/msteams-docs/blob/(Policy)(Doc-Enhancement)(1462062)/msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases?branch=pr-en-us-2650) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C27%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202101270333019978-2650%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=7qhLCyisalP%2FlpE5L9B6WtcBD5BB6WBwp6xvJYFub%2BE%3D&st=2021-01-27T03%3A28%3A35Z&se=2021-02-27T03%3A33%3A35Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-27 03:42 UTC, opbld33 commented
Docs Build status updates of commit _[d3b1887](https://github.com/MicrosoftDocs/msteams-docs/commits/d3b1887ea446c85c5eb1679a5e6899aed0db05c1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/faq/Sampleapp1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/(Policy)(Doc-Enhancement)(1462062)/msteams-platform/assets/images/faq/Sampleapp1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases?branch=pr-en-us-2650) |
[msteams-platform/assets/images/faq/Sampleapp2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/(Policy)(Doc-Enhancement)(1462062)/msteams-platform/assets/images/faq/Sampleapp2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases?branch=pr-en-us-2650) |
[msteams-platform/assets/images/faq/helpcommand.png](https://github.com/MicrosoftDocs/msteams-docs/blob/(Policy)(Doc-Enhancement)(1462062)/msteams-platform/assets/images/faq/helpcommand.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases?branch=pr-en-us-2650) |
[msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md](https://github.com/MicrosoftDocs/msteams-docs/blob/(Policy)(Doc-Enhancement)(1462062)/msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases?branch=pr-en-us-2650) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C27%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202101270341489489-2650%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=G4CZghz%2BoFOWxBMZpwJPgndunDGB5XlbKrX35ebVLqM%3D&st=2021-01-27T03%3A37%3A36Z&se=2021-02-27T03%3A42%3A36Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-27 06:28 UTC, opbld30 commented
Docs Build status updates of commit _[55b7710](https://github.com/MicrosoftDocs/msteams-docs/commits/55b7710baaf43e968756d9e9d63c89b9dd5c9c34)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-3f3e9534)

<a id="3f3e9534"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C27%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202101270628041161-2650%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=3UWZohpr632EpDjzRlV2DNK9%2FckO7wIzKX%2BSN0L8fQw%3D&st=2021-01-27T06%3A23%3A30Z&se=2021-02-27T06%3A28%3A30Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-27 06:32 UTC, opbld32 commented
Docs Build status updates of commit _[5f9474f](https://github.com/MicrosoftDocs/msteams-docs/commits/5f9474fffd49774449f8988cfb8cce62f1ca749b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/faq/Sampleapp1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/(Policy)(Doc-Enhancement)(1462062)/msteams-platform/assets/images/faq/Sampleapp1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases?branch=pr-en-us-2650) |
[msteams-platform/assets/images/faq/Sampleapp2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/(Policy)(Doc-Enhancement)(1462062)/msteams-platform/assets/images/faq/Sampleapp2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases?branch=pr-en-us-2650) |
[msteams-platform/assets/images/faq/helpcommand.png](https://github.com/MicrosoftDocs/msteams-docs/blob/(Policy)(Doc-Enhancement)(1462062)/msteams-platform/assets/images/faq/helpcommand.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases?branch=pr-en-us-2650) |
[msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md](https://github.com/MicrosoftDocs/msteams-docs/blob/(Policy)(Doc-Enhancement)(1462062)/msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases?branch=pr-en-us-2650) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C27%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202101270631556899-2650%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=xFBISDqP2C7MTrXPXaTR3MNmRhw1QoAx6XfayXuXO9c%3D&st=2021-01-27T06%3A27%3A25Z&se=2021-02-27T06%3A32%3A25Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-27 08:38 UTC, KirtiPereira requested changes
@Mahesh2516 - verify and commit the suggestions. Incorporate the review comments. Add the SME and Surbhi Gupta as reviewers.

2021-01-27 08:38 UTC, KirtiPereira commented on msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md
> +* Your app must not stop responding, end unexpectedly, or contain programming errors. If an issue occurs, your app must fail and provide valid way-forward information to the user.
```Suggestion
* Your app must not stop responding, end unexpectedly, or contain programming errors. If an issue occurs, your app must fail and provide valid information for the way-forward to the user.
```

2021-01-27 08:38 UTC, KirtiPereira commented on msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md
> +* If your app or add-in depends on external accounts or services, the sign-in, sign-out and sign-up experience must be apparent and reachable across all capabilities in your app.
Add the missing leading comma.
```suggestion
* If your app or add-in depends on external accounts or services, the sign-in, sign-out, and sign-up experience must be apparent and reachable across all capabilities in your app.
```

2021-01-27 08:38 UTC, KirtiPereira commented on msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md
> +* Provide clear way-forward guidance to a new user on how to sign-up to use your app services. If a ready sign-up link is not available, provide precise guidance in the following areas:
```suggestion
* Provide clear guidance on the way-forward to a new user on how to sign-up to use your app services. If a ready sign-up link is not available, provide precise guidance in the following areas:
```

2021-01-27 08:38 UTC, KirtiPereira commented on msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md
> +* **Do not push sensitive data**. Bots must not push sensitive data to a team, a group chat or a 1:1 conversation where there is an audience who should not be able to view that data.
missing leading comma

2021-01-27 08:38 UTC, KirtiPereira commented on msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md
> +A welcome messages is the best way to set the tone for your personal chat bot. This is the first interaction a user has with the bot. A good welcome message can encourage the user to keep exploring t
```suggestion
A welcome message is the best way to set the tone for your personal chat bot. This is the first interaction a user has with the bot. A good welcome message can encourage the user to keep exploring the app. If the welcome or introductory message is confusing or unclear, users won't see the value of the app immediately and lose interest.
```

2021-01-27 08:38 UTC, KirtiPereira commented on msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md
> +See the following section for welcome message requirements.
```suggestion
See the following section for welcome message requirements:
```

2021-01-27 08:38 UTC, KirtiPereira commented on msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md
> +* **Make your message concise and informative**.  Most likely, user experience with and knowledge of your app will vary. A user may have used your app on another platform or know nothing about your a
Please rephrase "Most likely, user experience with and knowledge of your app will vary."

2021-01-27 10:46 UTC, SonalNigam28 requested changes
Added few changes, kindly fix  them before merging

2021-01-27 10:46 UTC, SonalNigam28 commented on msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md
> +* All core and non-core scenarios must be completed within the Teams environment except for:
The point at line number 41 and line number 27 seems to be repetitive and a subset of line number 42. Can we merge them all.

2021-01-27 10:49 UTC, opbld31 commented
Docs Build status updates of commit _[a6d7a1a](https://github.com/MicrosoftDocs/msteams-docs/commits/a6d7a1a782c7f1bff5050b1be9943423c47d0fc5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/faq/Sampleapp1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/(Policy)(Doc-Enhancement)(1462062)/msteams-platform/assets/images/faq/Sampleapp1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases?branch=pr-en-us-2650) |
[msteams-platform/assets/images/faq/Sampleapp2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/(Policy)(Doc-Enhancement)(1462062)/msteams-platform/assets/images/faq/Sampleapp2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases?branch=pr-en-us-2650) |
[msteams-platform/assets/images/faq/helpcommand.png](https://github.com/MicrosoftDocs/msteams-docs/blob/(Policy)(Doc-Enhancement)(1462062)/msteams-platform/assets/images/faq/helpcommand.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases?branch=pr-en-us-2650) |
[msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md](https://github.com/MicrosoftDocs/msteams-docs/blob/(Policy)(Doc-Enhancement)(1462062)/msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases?branch=pr-en-us-2650) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C27%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202101271048265131-2650%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=wgQ3yrzsADpTNrjBAr0iUiqRqSvN%2B3ddByI4d9xMQI8%3D&st=2021-01-27T10%3A44%3A00Z&se=2021-02-27T10%3A49%3A00Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-27 10:50 UTC, opbld30 commented
Docs Build status updates of commit _[9f4fed5](https://github.com/MicrosoftDocs/msteams-docs/commits/9f4fed5f7067c479e281665f5ea8078beabe2e47)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/faq/Sampleapp1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/(Policy)(Doc-Enhancement)(1462062)/msteams-platform/assets/images/faq/Sampleapp1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases?branch=pr-en-us-2650) |
[msteams-platform/assets/images/faq/Sampleapp2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/(Policy)(Doc-Enhancement)(1462062)/msteams-platform/assets/images/faq/Sampleapp2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases?branch=pr-en-us-2650) |
[msteams-platform/assets/images/faq/helpcommand.png](https://github.com/MicrosoftDocs/msteams-docs/blob/(Policy)(Doc-Enhancement)(1462062)/msteams-platform/assets/images/faq/helpcommand.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases?branch=pr-en-us-2650) |
[msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md](https://github.com/MicrosoftDocs/msteams-docs/blob/(Policy)(Doc-Enhancement)(1462062)/msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases?branch=pr-en-us-2650) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C27%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202101271049399288-2650%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=65oApVPhQZKEs7dYiBD%2FDyUoxicyLK92xSMUeH9jyQ8%3D&st=2021-01-27T10%3A45%3A17Z&se=2021-02-27T10%3A50%3A17Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-27 10:50 UTC, opbld31 commented
Docs Build status updates of commit _[ed3284d](https://github.com/MicrosoftDocs/msteams-docs/commits/ed3284dbc87118e9e3870be063eb070cf860558e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/faq/Sampleapp1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/(Policy)(Doc-Enhancement)(1462062)/msteams-platform/assets/images/faq/Sampleapp1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases?branch=pr-en-us-2650) |
[msteams-platform/assets/images/faq/Sampleapp2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/(Policy)(Doc-Enhancement)(1462062)/msteams-platform/assets/images/faq/Sampleapp2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases?branch=pr-en-us-2650) |
[msteams-platform/assets/images/faq/helpcommand.png](https://github.com/MicrosoftDocs/msteams-docs/blob/(Policy)(Doc-Enhancement)(1462062)/msteams-platform/assets/images/faq/helpcommand.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases?branch=pr-en-us-2650) |
[msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md](https://github.com/MicrosoftDocs/msteams-docs/blob/(Policy)(Doc-Enhancement)(1462062)/msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases?branch=pr-en-us-2650) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C27%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202101271050231762-2650%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=BniSpdzG6QGLqXBPN1XlUm%2BZD4B7OmeaTDwNxgu05UE%3D&st=2021-01-27T10%3A45%3A55Z&se=2021-02-27T10%3A50%3A55Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-27 10:52 UTC, opbld30 commented
Docs Build status updates of commit _[6a8d401](https://github.com/MicrosoftDocs/msteams-docs/commits/6a8d401cd6ba3e8ec1828eb241bdec6f77b7fedc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/faq/Sampleapp1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/(Policy)(Doc-Enhancement)(1462062)/msteams-platform/assets/images/faq/Sampleapp1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases?branch=pr-en-us-2650) |
[msteams-platform/assets/images/faq/Sampleapp2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/(Policy)(Doc-Enhancement)(1462062)/msteams-platform/assets/images/faq/Sampleapp2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases?branch=pr-en-us-2650) |
[msteams-platform/assets/images/faq/helpcommand.png](https://github.com/MicrosoftDocs/msteams-docs/blob/(Policy)(Doc-Enhancement)(1462062)/msteams-platform/assets/images/faq/helpcommand.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases?branch=pr-en-us-2650) |
[msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md](https://github.com/MicrosoftDocs/msteams-docs/blob/(Policy)(Doc-Enhancement)(1462062)/msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases?branch=pr-en-us-2650) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C27%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202101271051491401-2650%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=5SniaJpUiiMiAeQTX9DKt3bJpg%2FTk17alAZFlOZHmeY%3D&st=2021-01-27T10%3A47%3A25Z&se=2021-02-27T10%3A52%3A25Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-27 10:53 UTC, opbld32 commented
Docs Build status updates of commit _[12b3eae](https://github.com/MicrosoftDocs/msteams-docs/commits/12b3eae3cd503207490426168cd11302b70e625b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/faq/Sampleapp1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/(Policy)(Doc-Enhancement)(1462062)/msteams-platform/assets/images/faq/Sampleapp1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases?branch=pr-en-us-2650) |
[msteams-platform/assets/images/faq/Sampleapp2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/(Policy)(Doc-Enhancement)(1462062)/msteams-platform/assets/images/faq/Sampleapp2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases?branch=pr-en-us-2650) |
[msteams-platform/assets/images/faq/helpcommand.png](https://github.com/MicrosoftDocs/msteams-docs/blob/(Policy)(Doc-Enhancement)(1462062)/msteams-platform/assets/images/faq/helpcommand.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases?branch=pr-en-us-2650) |
[msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md](https://github.com/MicrosoftDocs/msteams-docs/blob/(Policy)(Doc-Enhancement)(1462062)/msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases?branch=pr-en-us-2650) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C27%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202101271053019199-2650%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=aKpILKJj2den6rPOIjnzOsj1CwwgDOg1NzMsBKyUfr0%3D&st=2021-01-27T10%3A48%3A31Z&se=2021-02-27T10%3A53%3A31Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-27 11:06 UTC, opbld31 commented
Docs Build status updates of commit _[a01b1b0](https://github.com/MicrosoftDocs/msteams-docs/commits/a01b1b0e85675f0e3d0853962fdfdb169e32b113)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/faq/Sampleapp1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/(Policy)(Doc-Enhancement)(1462062)/msteams-platform/assets/images/faq/Sampleapp1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases?branch=pr-en-us-2650) |
[msteams-platform/assets/images/faq/Sampleapp2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/(Policy)(Doc-Enhancement)(1462062)/msteams-platform/assets/images/faq/Sampleapp2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases?branch=pr-en-us-2650) |
[msteams-platform/assets/images/faq/helpcommand.png](https://github.com/MicrosoftDocs/msteams-docs/blob/(Policy)(Doc-Enhancement)(1462062)/msteams-platform/assets/images/faq/helpcommand.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases?branch=pr-en-us-2650) |
[msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md](https://github.com/MicrosoftDocs/msteams-docs/blob/(Policy)(Doc-Enhancement)(1462062)/msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases?branch=pr-en-us-2650) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C27%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202101271105569105-2650%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ELPrPK6f4Xcd1Ag5uXosEgLiMiNLlvoxqf%2FClLAECqw%3D&st=2021-01-27T11%3A01%3A29Z&se=2021-02-27T11%3A06%3A29Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-27 11:58 UTC, opbld32 commented
Docs Build status updates of commit _[08f3fbf](https://github.com/MicrosoftDocs/msteams-docs/commits/08f3fbfcf31e1f40dbb21ecfcfe2ad26c03d32c1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/faq/Sampleapp1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/(Policy)(Doc-Enhancement)(1462062)/msteams-platform/assets/images/faq/Sampleapp1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases?branch=pr-en-us-2650) |
[msteams-platform/assets/images/faq/Sampleapp2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/(Policy)(Doc-Enhancement)(1462062)/msteams-platform/assets/images/faq/Sampleapp2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases?branch=pr-en-us-2650) |
[msteams-platform/assets/images/faq/helpcommand.png](https://github.com/MicrosoftDocs/msteams-docs/blob/(Policy)(Doc-Enhancement)(1462062)/msteams-platform/assets/images/faq/helpcommand.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases?branch=pr-en-us-2650) |
[msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md](https://github.com/MicrosoftDocs/msteams-docs/blob/(Policy)(Doc-Enhancement)(1462062)/msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases?branch=pr-en-us-2650) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C27%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202101271157448442-2650%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=tC6jYhoobbzjehDfROlL2KkSd%2BB9aAx1dYLRUzFleug%3D&st=2021-01-27T11%3A53%3A16Z&se=2021-02-27T11%3A58%3A16Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-27 12:12 UTC, opbld31 commented
Docs Build status updates of commit _[a6249cf](https://github.com/MicrosoftDocs/msteams-docs/commits/a6249cf9cca83aecd711112f408fa7e80418bf64)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/faq/Sampleapp1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/(Policy)(Doc-Enhancement)(1462062)/msteams-platform/assets/images/faq/Sampleapp1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases?branch=pr-en-us-2650) |
[msteams-platform/assets/images/faq/Sampleapp2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/(Policy)(Doc-Enhancement)(1462062)/msteams-platform/assets/images/faq/Sampleapp2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases?branch=pr-en-us-2650) |
[msteams-platform/assets/images/faq/helpcommand.png](https://github.com/MicrosoftDocs/msteams-docs/blob/(Policy)(Doc-Enhancement)(1462062)/msteams-platform/assets/images/faq/helpcommand.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases?branch=pr-en-us-2650) |
[msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md](https://github.com/MicrosoftDocs/msteams-docs/blob/(Policy)(Doc-Enhancement)(1462062)/msteams-platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/frequently-failed-cases?branch=pr-en-us-2650) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C27%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202101271211417807-2650%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=RpW0e8S0ohZMP5Cuq9EDUh%2B%2FgtBzMpQHjKb6jJI9yxc%3D&st=2021-01-27T12%3A07%3A15Z&se=2021-02-27T12%3A12%3A15Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-28 01:55 UTC, SonalNigam28 approved these changes
Looks good . please go ahead

2021-01-28 11:55 UTC, KirtiPereira approved these changes
Approved

2021-01-28 11:56 UTC, surbhigupta12 approved these changes
Approving the PR.

2021-01-28 11:56 UTC, merged