[Samples][Tableandlinkupdate]
MicrosoftDocs/msteams-docs pull request #2654
Opened 2021-01-21 12:09 UTC by KirtiPereira

Updated the following files:

- TOC.yml
- conversation-basics.md

Removed the Bots and Messaging extension samples from the TOC.

@Wajeed-msft - please update the following before we approve the PR:

- [ ] Verify if the inline code has been updated.
- [ ] Does this file require a code snippet?

2021-01-21 12:10 UTC, opbld31 commented
Docs Build status updates of commit _[d2afa7d](https://github.com/MicrosoftDocs/msteams-docs/commits/d2afa7dc1e45812d10b33589482a6664393f1375)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/KirtiPereira-patch-1/msteams-platform/bots/how-to/conversations/conversation-basics.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-basics?branch=pr-en-us-2654) | [Details](#user-content-17ca7678-40aff950)
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/KirtiPereira-patch-1/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-basics?branch=pr-en-us-2654) |
[msteams-platform/tutorials/code-samples.md](https://github.com/MicrosoftDocs/msteams-docs/blob/KirtiPereira-patch-1/msteams-platform/tutorials/code-samples.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tutorials/code-samples?branch=pr-en-us-2654) |

<a id="17ca7678-40aff950"></a>
### [msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/KirtiPereira-patch-1/msteams-platform/bots/how-to/conversations/conversation-basics.md)
 - **Line 332, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /azure/bot-service/dotnet/bot-builder-dotnet-add-media-attachments?view=azure-bot-service-3.0`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C21%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202101211209257129-2654%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=1Dw7PUns1UiQfiKjHdG4uD7jM%2Fie2mmtsDQhDwg2XSg%3D&st=2021-01-21T12%3A04%3A59Z&se=2021-02-21T12%3A09%3A59Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-21 12:19 UTC, opbld32 commented
Docs Build status updates of commit _[41dd9b1](https://github.com/MicrosoftDocs/msteams-docs/commits/41dd9b12b8681b1f27979c0f59af0b71e9a1c953)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/KirtiPereira-patch-1/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-basics?branch=pr-en-us-2654) |
[msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/KirtiPereira-patch-1/msteams-platform/bots/how-to/conversations/conversation-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-basics?branch=pr-en-us-2654) |
[msteams-platform/tutorials/code-samples.md](https://github.com/MicrosoftDocs/msteams-docs/blob/KirtiPereira-patch-1/msteams-platform/tutorials/code-samples.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tutorials/code-samples?branch=pr-en-us-2654) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C21%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202101211218267984-2654%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2BfUOB6rk%2B1qp5L6zqS4FqUSd8BnY9jD%2Fg%2FTgQpHiA4M%3D&st=2021-01-21T12%3A14%3A00Z&se=2021-02-21T12%3A19%3A00Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-21 12:58 UTC, surbhigupta12 requested changes
Minor comments.

2021-01-21 12:58 UTC, surbhigupta12 commented on msteams-platform/tutorials/code-samples.md
>  Here you will find a list of tutorials and code samples that demonstrate how you can extend the Teams developer platform capabilities by creating custom apps.
Line 8, please change to:

Here you will find a list of tutorials that demonstrate how you can extend the Teams developer platform capabilities by creating custom apps.

2021-01-21 12:58 UTC, surbhigupta12 commented on msteams-platform/TOC.yml
>    - name: Overview
Line 25, Please change "overview" to  "Tutorials"

2021-01-21 13:07 UTC, opbld31 commented
Docs Build status updates of commit _[545cd92](https://github.com/MicrosoftDocs/msteams-docs/commits/545cd928f7ce0f6095a9bfcc81abce61a1fed387)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/KirtiPereira-patch-1/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-basics?branch=pr-en-us-2654) |
[msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/KirtiPereira-patch-1/msteams-platform/bots/how-to/conversations/conversation-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-basics?branch=pr-en-us-2654) |
[msteams-platform/tutorials/code-samples.md](https://github.com/MicrosoftDocs/msteams-docs/blob/KirtiPereira-patch-1/msteams-platform/tutorials/code-samples.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tutorials/code-samples?branch=pr-en-us-2654) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C21%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202101211307061430-2654%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Om0yAHYSkPyFsWq8raEGxQ2ShjPgGy8Ayt5lWEtdrcI%3D&st=2021-01-21T13%3A02%3A42Z&se=2021-02-21T13%3A07%3A42Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-02 10:55 UTC, KirtiPereira commented
@Wajeed-msft - gentle reminder to approve the PR. Thank you.

2021-02-02 16:40 UTC, Wajeed-msft approved these changes

2021-02-02 16:44 UTC, surbhigupta12 approved these changes
Approving the PR.

2021-02-02 16:44 UTC, merged