[App][Addinfo][1489120]
MicrosoftDocs/msteams-docs pull request #2682
Opened 2021-01-27 12:11 UTC by Rajeshwari-v

Updated the document. Please review.

2021-01-27 12:12 UTC, opbld31 commented
Docs Build status updates of commit _[5599ddc](https://github.com/MicrosoftDocs/msteams-docs/commits/5599ddc4e629f55f5e1ed80371b807218b255532)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/build-your-first-app/build-and-run.md](https://github.com/MicrosoftDocs/msteams-docs/blob/App-Addinfo-1489120/msteams-platform/build-your-first-app/build-and-run.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/build-your-first-app/build-and-run?branch=pr-en-us-2682) | [Details](#user-content-d4d5a980-50c196a3)
[]() | :warning:Warning | | [Details](#user-content-50c196a3)
[msteams-platform/messaging-extensions/how-to/create-messaging-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/App-Addinfo-1489120/msteams-platform/messaging-extensions/how-to/create-messaging-extension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/create-messaging-extension?branch=pr-en-us-2682) |

<a id="d4d5a980-50c196a3"></a>
### [msteams-platform/build-your-first-app/build-and-run.md](https://github.com/MicrosoftDocs/msteams-docs/blob/App-Addinfo-1489120/msteams-platform/build-your-first-app/build-and-run.md)
 - **Line 59, Column 24**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'prepare-your-o365-tenant'.`````

<a id="50c196a3"></a>
###
 - **Line 0, Column 0**: **[Warning-[redirected-file-not-removed](https://review.docs.microsoft.com/help/contribute/validation-ref/redirected-file-not-removed?branch=main)]** `````Redirected file 'messaging-extensions/how-to/create-messaging-extension.md [redirection]' is still in the repo. After adding a file to the redirection JSON file, you must delete the original file from the repo.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C27%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202101271211473914-2682%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=hrrGSMpZs5E8Nui5hVtBHMvnqLLmWGvK8Q0qmkL3L%2F4%3D&st=2021-01-27T12%3A07%3A19Z&se=2021-02-27T12%3A12%3A19Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-27 12:50 UTC, opbld32 commented
Docs Build status updates of commit _[a224366](https://github.com/MicrosoftDocs/msteams-docs/commits/a224366236e73aa335c2c43c0de20616407a14bf)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :warning:Warning | | [Details](#user-content-b8f4d78c)
[msteams-platform/build-your-first-app/build-and-run.md](https://github.com/MicrosoftDocs/msteams-docs/blob/App-Addinfo-1489120/msteams-platform/build-your-first-app/build-and-run.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/build-your-first-app/build-and-run?branch=pr-en-us-2682) |
[msteams-platform/messaging-extensions/how-to/create-messaging-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/App-Addinfo-1489120/msteams-platform/messaging-extensions/how-to/create-messaging-extension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/create-messaging-extension?branch=pr-en-us-2682) |

<a id="b8f4d78c"></a>
###
 - **Line 0, Column 0**: **[Warning-[redirected-file-not-removed](https://review.docs.microsoft.com/help/contribute/validation-ref/redirected-file-not-removed?branch=main)]** `````Redirected file 'messaging-extensions/how-to/create-messaging-extension.md [redirection]' is still in the repo. After adding a file to the redirection JSON file, you must delete the original file from the repo.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C27%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202101271250119784-2682%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=58M%2FLBRa74n09K2Cw2jBqDkJ4aGEQlTVFPwb8NQb6%2B8%3D&st=2021-01-27T12%3A45%3A43Z&se=2021-02-27T12%3A50%3A43Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-29 05:26 UTC, opbld31 commented
Docs Build status updates of commit _[0eb5f34](https://github.com/MicrosoftDocs/msteams-docs/commits/0eb5f349356eeef1cdc2165c8381270c2024e646)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/build-your-first-app/build-and-run.md](https://github.com/MicrosoftDocs/msteams-docs/blob/App-Addinfo-1489120/msteams-platform/build-your-first-app/build-and-run.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/build-your-first-app/build-and-run?branch=pr-en-us-2682) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C29%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202101290525314417-2682%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=1VuwzMGGyY4uI3DpFoMxoDaftKi%2F7ezf2kNuDn%2BfG44%3D&st=2021-01-29T05%3A21%3A07Z&se=2021-03-01T05%3A26%3A07Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-29 05:55 UTC, opbld30 commented
Docs Build status updates of commit _[929f4bc](https://github.com/MicrosoftDocs/msteams-docs/commits/929f4bcfdb0e96d4975ef42cda6220e93591ea9a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/build-your-first-app/build-and-run.md](https://github.com/MicrosoftDocs/msteams-docs/blob/App-Addinfo-1489120/msteams-platform/build-your-first-app/build-and-run.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/build-your-first-app/build-and-run?branch=pr-en-us-2682) | [Details](#user-content-d4d5a980-4daf5b6a)

<a id="d4d5a980-4daf5b6a"></a>
### [msteams-platform/build-your-first-app/build-and-run.md](https://github.com/MicrosoftDocs/msteams-docs/blob/App-Addinfo-1489120/msteams-platform/build-your-first-app/build-and-run.md)
 - **Line 58, Column 23**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'build-and-test/prepare-your-o365-tenant.md'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C29%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202101290554496961-2682%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=nhZnfs9C%2FT9oZpXrJMXbXzfikHFH7CAYRpXyNS44vXI%3D&st=2021-01-29T05%3A50%3A24Z&se=2021-03-01T05%3A55%3A24Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-29 06:05 UTC, opbld32 commented
Docs Build status updates of commit _[1817455](https://github.com/MicrosoftDocs/msteams-docs/commits/1817455d31db5f00b807846f407352b5a20c54a8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/build-your-first-app/build-and-run.md](https://github.com/MicrosoftDocs/msteams-docs/blob/App-Addinfo-1489120/msteams-platform/build-your-first-app/build-and-run.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/build-your-first-app/build-and-run?branch=pr-en-us-2682) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C29%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202101290605083282-2682%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Zb%2BjAgzlFTnmjPQB1zIJeWXMysYef%2BnE1NUIRHDuWog%3D&st=2021-01-29T06%3A00%3A43Z&se=2021-03-01T06%3A05%3A43Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-29 12:04 UTC, KirtiPereira requested changes
Please verify and update the comment.

2021-01-29 12:04 UTC, KirtiPereira commented on msteams-platform/build-your-first-app/build-and-run.md
> +Your app is ready to test in Teams. To do this, you must have an account that allows app sideloading. If you are not sure you have that account, learn about getting a [Teams development account](../b
"that account" is which account?

2021-01-29 14:38 UTC, opbld31 commented
Docs Build status updates of commit _[7c5ed6a](https://github.com/MicrosoftDocs/msteams-docs/commits/7c5ed6aead3e8777d1cd0ec3726e067a0a3e7c16)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/build-your-first-app/build-and-run.md](https://github.com/MicrosoftDocs/msteams-docs/blob/App-Addinfo-1489120/msteams-platform/build-your-first-app/build-and-run.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/build-your-first-app/build-and-run?branch=pr-en-us-2682) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C29%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202101291437474463-2682%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=0p58llMhKxwiRVYfYedgEx4vAzGpfyFVBOohGAyAweY%3D&st=2021-01-29T14%3A33%3A37Z&se=2021-03-01T14%3A38%3A37Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-02 04:47 UTC, Trinetra-MSFT reviewed
Next steps does not look good
![image](https://user-images.githubusercontent.com/50989436/106553652-cbb65000-653f-11eb-9170-b231cbbf25cc.png)

Why do we have that div

2021-02-02 07:31 UTC, opbld32 commented
Docs Build status updates of commit _[f40b81a](https://github.com/MicrosoftDocs/msteams-docs/commits/f40b81acf6a89ef2816953aa78d05b91725a3edf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/build-your-first-app/build-and-run.md](https://github.com/MicrosoftDocs/msteams-docs/blob/App-Addinfo-1489120/msteams-platform/build-your-first-app/build-and-run.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/build-your-first-app/build-and-run?branch=pr-en-us-2682) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C2%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202102020730433933-2682%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=amkc0UrJYgvl6Ad0aTekL59SB%2BjO6GCQdM3M2e98ihE%3D&st=2021-02-02T07%3A26%3A19Z&se=2021-03-05T07%3A31%3A19Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-02 07:36 UTC, Rajeshwari-v commented
> Next steps does not look good
> ![image](https://user-images.githubusercontent.com/50989436/106553652-cbb65000-653f-11eb-9170-b231cbbf25cc.png)
> 
> Why do we have that div

@Trinetra-MSFT, Incorporated the suggested changes. Please review and approve.

2021-02-02 09:59 UTC, opbld31 commented
Docs Build status updates of commit _[efa61f8](https://github.com/MicrosoftDocs/msteams-docs/commits/efa61f859c29a9a4ff8cf859307727d4cb081412)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/build-your-first-app/build-and-run.md](https://github.com/MicrosoftDocs/msteams-docs/blob/App-Addinfo-1489120/msteams-platform/build-your-first-app/build-and-run.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/build-your-first-app/build-and-run?branch=pr-en-us-2682) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C2%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202102020958392353-2682%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=rc5SroupF3P3ukJtdVTbzFOyE6re1NL46GS9sluSnoI%3D&st=2021-02-02T09%3A54%3A09Z&se=2021-03-05T09%3A59%3A09Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-03 09:55 UTC, Trinetra-MSFT approved these changes

2021-02-03 10:02 UTC, KirtiPereira submitted a review, later dismissed
Approve

2021-02-03 10:08 UTC, surbhigupta12 commented on msteams-platform/build-your-first-app/build-and-run.md
> +> Follow the steps to [Turn on app sideloading](../concepts/build-and-test/prepare-your-o365-tenant.md#enable-custom-teams-apps-and-turn-on-custom-app-uploading), if the side loading is not enabled.
Please follow style guide here.

2021-02-03 10:20 UTC, opbld33 commented
Docs Build status updates of commit _[df6f4ed](https://github.com/MicrosoftDocs/msteams-docs/commits/df6f4ede5328a251f4316877a62bb8f385567de4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/build-your-first-app/build-and-run.md](https://github.com/MicrosoftDocs/msteams-docs/blob/App-Addinfo-1489120/msteams-platform/build-your-first-app/build-and-run.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/build-your-first-app/build-and-run?branch=pr-en-us-2682) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C3%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202102031020098684-2682%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=cdkVdXdawWuksHAWtBlBB2sOLiyrP%2BGdP1lFL9D7uB0%3D&st=2021-02-03T10%3A15%3A40Z&se=2021-03-06T10%3A20%3A40Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-03 10:42 UTC, opbld32 commented
Docs Build status updates of commit _[5c2cd8e](https://github.com/MicrosoftDocs/msteams-docs/commits/5c2cd8e73fe48788131b5c97cdc22d68f0580bd0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/build-your-first-app/build-and-run.md](https://github.com/MicrosoftDocs/msteams-docs/blob/App-Addinfo-1489120/msteams-platform/build-your-first-app/build-and-run.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/build-your-first-app/build-and-run?branch=pr-en-us-2682) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C3%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202102031042058633-2682%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ViLugEPoLRM4UhBq1IpKrg7Ia49hNq%2FdGLoMNGTds4g%3D&st=2021-02-03T10%3A37%3A37Z&se=2021-03-06T10%3A42%3A37Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-03 12:50 UTC, surbhigupta12 approved these changes
Approving the PR

2021-02-03 12:50 UTC, KirtiPereira approved these changes
Approve.

2021-02-03 12:50 UTC, merged