[Bots][Addedinlineimagesection][1466405]
MicrosoftDocs/msteams-docs pull request #2702
Opened 2021-01-29 11:56 UTC by v-rodriguezd

Added Fetching inline images from message section with code and changed basic example C# code and added image and hyperlink. Please review.

2021-01-29 11:57 UTC, opbld31 commented
Docs Build status updates of commit _[0589087](https://github.com/MicrosoftDocs/msteams-docs/commits/05890875ab97186de13e43a9efe165c9f834783a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/bots/inline-image.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1466405-Inlineimage/msteams-platform/assets/images/bots/inline-image.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/bots-filesv4?branch=pr-en-us-2702) |
[msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1466405-Inlineimage/msteams-platform/bots/how-to/bots-filesv4.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/bots-filesv4?branch=pr-en-us-2702) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C29%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202101291156331218-2702%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=1dWYUCNSMi47Y4buAuArY315JCSKvEr7guFye%2BpxPKg%3D&st=2021-01-29T11%3A52%3A44Z&se=2021-03-01T11%3A57%3A44Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-01 07:19 UTC, KirtiPereira requested changes
@v-rodriguezd - please verify and commit suggestion.

2021-02-01 07:19 UTC, KirtiPereira commented on msteams-platform/bots/how-to/bots-filesv4.md
> +An invoke activity is sent to the bot if and when the user accepts the file. It contains the OneDrive for Business placeholder URL that the bot can then issue a `PUT` into to transfer the file conten
```suggestion
An invoke activity is sent to the bot if and when the user accepts the file. It contains the OneDrive for Business placeholder URL that the bot can then issue a `PUT` to transfer the file contents. For information on uploading to the OneDrive URL, see [upload bytes to the upload session](/onedrive/developer/rest-api/api/driveitem_createuploadsession#upload-bytes-to-the-upload-session).
```

2021-02-01 08:31 UTC, opbld30 commented
Docs Build status updates of commit _[2bd3fe9](https://github.com/MicrosoftDocs/msteams-docs/commits/2bd3fe9b4c4cff4dbc3fe9fd8f850d59b3e16edd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/bots/inline-image.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1466405-Inlineimage/msteams-platform/assets/images/bots/inline-image.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/bots-filesv4?branch=pr-en-us-2702) |
[msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1466405-Inlineimage/msteams-platform/bots/how-to/bots-filesv4.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/bots-filesv4?branch=pr-en-us-2702) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C1%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202102010831073647-2702%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=p8VF6pcvfbKQKLhlQRxqvPd6xSxbXisI70RhsBGo4cc%3D&st=2021-02-01T08%3A26%3A51Z&se=2021-03-04T08%3A31%3A51Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-01 09:56 UTC, opbld32 commented
Docs Build status updates of commit _[91129ef](https://github.com/MicrosoftDocs/msteams-docs/commits/91129ef3569f074625e15a020160127239b4f458)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1466405-Inlineimage/msteams-platform/bots/how-to/bots-filesv4.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/bots-filesv4?branch=pr-en-us-2702) | [Details](#user-content-55d25fa3-fa30050b)
[msteams-platform/resources/bot-v3/bots-text-formats.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1466405-Inlineimage/msteams-platform/resources/bot-v3/bots-text-formats.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bots-text-formats?branch=pr-en-us-2702) | [Details](#user-content-1219ada2-fa30050b)
[msteams-platform/assets/images/bots/inline-image.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1466405-Inlineimage/msteams-platform/assets/images/bots/inline-image.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/bots-filesv4?branch=pr-en-us-2702) |

<a id="55d25fa3-fa30050b"></a>
### [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1466405-Inlineimage/msteams-platform/bots/how-to/bots-filesv4.md)
 - **Line 308, Column 40**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#code-sample' in 'bots/how-to/conversations/conversation-basics.md'.`````

<a id="1219ada2-fa30050b"></a>
### [msteams-platform/resources/bot-v3/bots-text-formats.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1466405-Inlineimage/msteams-platform/resources/bot-v3/bots-text-formats.md)
 - **Line 82, Column 26**: **[Warning-[insecure-link](https://review.docs.microsoft.com/help/contribute/validation-ref/insecure-link?branch=main)]** `````Link 'http://aka.ms/Fo983c' is insecure. Links to Microsoft sites must use 'https' instead of 'http'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C1%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202102010955558445-2702%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=aspyhU%2BOjd5SjARyu%2FoHBNQfFlUmkUBZbfnlb3Pr0PQ%3D&st=2021-02-01T09%3A51%3A27Z&se=2021-03-04T09%3A56%3A27Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-01 14:02 UTC, opbld32 commented
Docs Build status updates of commit _[9862113](https://github.com/MicrosoftDocs/msteams-docs/commits/98621131f33f1bc09b54290cf3da7acb67ee9fbc)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/resources/bot-v3/bots-text-formats.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1466405-Inlineimage/msteams-platform/resources/bot-v3/bots-text-formats.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bots-text-formats?branch=pr-en-us-2702) | [Details](#user-content-1219ada2-b2889b31)
[msteams-platform/assets/images/bots/inline-image.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1466405-Inlineimage/msteams-platform/assets/images/bots/inline-image.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/bots-filesv4?branch=pr-en-us-2702) |
[msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1466405-Inlineimage/msteams-platform/bots/how-to/bots-filesv4.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/bots-filesv4?branch=pr-en-us-2702) |

<a id="1219ada2-b2889b31"></a>
### [msteams-platform/resources/bot-v3/bots-text-formats.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1466405-Inlineimage/msteams-platform/resources/bot-v3/bots-text-formats.md)
 - **Line 82, Column 26**: **[Warning-[insecure-link](https://review.docs.microsoft.com/help/contribute/validation-ref/insecure-link?branch=main)]** `````Link 'http://aka.ms/Fo983c' is insecure. Links to Microsoft sites must use 'https' instead of 'http'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C1%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202102011402034314-2702%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=lRUugCCHcMENQPOiUG2pFEMggp3nwvH%2Fce%2BBmVkxbBo%3D&st=2021-02-01T13%3A57%3A39Z&se=2021-03-04T14%3A02%3A39Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-02 06:26 UTC, opbld30 commented
Docs Build status updates of commit _[7ab76d6](https://github.com/MicrosoftDocs/msteams-docs/commits/7ab76d670bced08b759160ab75344dad21980297)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/bots/inline-image.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1466405-Inlineimage/msteams-platform/assets/images/bots/inline-image.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/bots-filesv4?branch=pr-en-us-2702) |
[msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1466405-Inlineimage/msteams-platform/bots/how-to/bots-filesv4.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/bots-filesv4?branch=pr-en-us-2702) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C2%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202102020626130140-2702%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=eHKoiwidJN3aTEdTTNJkIbKwdmPxgv804Jy0oHy8YMU%3D&st=2021-02-02T06%3A21%3A49Z&se=2021-03-05T06%3A26%3A49Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-02 09:53 UTC, opbld31 commented
Docs Build status updates of commit _[8162d4b](https://github.com/MicrosoftDocs/msteams-docs/commits/8162d4b7ef1598f0dfc9af1b1a53466b95305c3b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/bots/inline-image.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1466405-Inlineimage/msteams-platform/assets/images/bots/inline-image.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/bots-filesv4?branch=pr-en-us-2702) |
[msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1466405-Inlineimage/msteams-platform/bots/how-to/bots-filesv4.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/bots-filesv4?branch=pr-en-us-2702) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C2%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202102020952480902-2702%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=nvO1twXpUPZ6ta5dOkA6n%2BkGLKrmzVNVoIYnXl0t3K8%3D&st=2021-02-02T09%3A48%3A22Z&se=2021-03-05T09%3A53%3A22Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-02 13:20 UTC, KirtiPereira commented
@Wajeed-msft - kindly review / approve the PR. Thank you.

2021-02-03 05:51 UTC, Wajeed-msft approved these changes

2021-02-03 06:49 UTC, KirtiPereira approved these changes
Approve

2021-02-03 06:49 UTC, surbhigupta12 approved these changes
Approving the PR.

2021-02-03 06:49 UTC, merged