Update cards-format.md
MicrosoftDocs/msteams-docs pull request #2722
Opened 2021-02-02 17:55 UTC by ojasvichoudhary

add support for full width adaptive cards

2021-02-02 17:55 UTC, opbld33 commented
Docs Build status updates of commit _[066f442](https://github.com/MicrosoftDocs/msteams-docs/commits/066f4427cfd4a40b8f1be3bf00bec4598976ec5e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/task-modules-and-cards/cards/cards-format.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ojasvichoudhary-patch-1/msteams-platform/task-modules-and-cards/cards/cards-format.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?branch=pr-en-us-2722) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C2%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202102021755233323-2722%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=vx3phkJpQaSk2xYdOuhvKdk%2BbeKBNtSW6%2FNx0JoJons%3D&st=2021-02-02T17%3A50%3A54Z&se=2021-03-05T17%3A55%3A54Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-03 06:40 UTC, KirtiPereira requested changes
@ojasvichoudhary - please verify and commit the suggestions.
Thank you.

2021-02-03 06:40 UTC, KirtiPereira commented on msteams-platform/task-modules-and-cards/cards/cards-format.md
> +* The `width` object inside of an `msteams` property in the card content should be set to `Full`
```suggestion
To make a full width Adaptive card the `width` object in `msteams` property in the card content must be set to `Full`.
In addition, your app must include the following elements:
```

2021-02-08 11:56 UTC, KirtiPereira commented
@ojasvichoudhary - please incorporate the suggested changes, so we can merge the PR.
Thank you.

2021-02-12 12:14 UTC, surbhigupta12 commented
@ojasvichoudhary  - please incorporate the suggested changes, so we can merge the PR.
Thank you.

2021-02-17 11:47 UTC, opbld31 commented
Docs Build status updates of commit _[3aa82af](https://github.com/MicrosoftDocs/msteams-docs/commits/3aa82afe92253acd212d6bf9b4e0a4a134cc4330)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/Cards/full-width-adaptive-card.png](https://github.com/MicrosoftDocs/msteams-docs/blob/ojasvichoudhary-patch-1/msteams-platform/assets/images/Cards/full-width-adaptive-card.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/cards/full-width-adaptive-card.png?branch=pr-en-us-2722) |
[msteams-platform/assets/images/Cards/small-width-adaptive-card.png](https://github.com/MicrosoftDocs/msteams-docs/blob/ojasvichoudhary-patch-1/msteams-platform/assets/images/Cards/small-width-adaptive-card.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/cards/small-width-adaptive-card.png?branch=pr-en-us-2722) |
[msteams-platform/task-modules-and-cards/cards/cards-format.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ojasvichoudhary-patch-1/msteams-platform/task-modules-and-cards/cards/cards-format.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?branch=pr-en-us-2722) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C17%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202102171146345371-2722%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=f83ZUq11PzpK7IpM3WwgSkm3b0ko9Y%2Fo9oEgdkmtmXo%3D&st=2021-02-17T11%3A42%3A25Z&se=2021-03-20T11%3A47%3A25Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-17 12:12 UTC, opbld31 commented
Docs Build status updates of commit _[a5ab2c2](https://github.com/MicrosoftDocs/msteams-docs/commits/a5ab2c273bfdf76db48644862bfae3c659e6b579)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/Cards/full-width-adaptive-card.png](https://github.com/MicrosoftDocs/msteams-docs/blob/ojasvichoudhary-patch-1/msteams-platform/assets/images/Cards/full-width-adaptive-card.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?branch=pr-en-us-2722) |
[msteams-platform/assets/images/Cards/small-width-adaptive-card.png](https://github.com/MicrosoftDocs/msteams-docs/blob/ojasvichoudhary-patch-1/msteams-platform/assets/images/Cards/small-width-adaptive-card.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?branch=pr-en-us-2722) |
[msteams-platform/task-modules-and-cards/cards/cards-format.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ojasvichoudhary-patch-1/msteams-platform/task-modules-and-cards/cards/cards-format.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?branch=pr-en-us-2722) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C17%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202102171212128092-2722%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=e17vfO3TCxAoqhdpZp4rGQBFSMrQJ4mHgPTCYm2ipSA%3D&st=2021-02-17T12%3A07%3A50Z&se=2021-03-20T12%3A12%3A50Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-17 12:21 UTC, opbld30 commented
Docs Build status updates of commit _[c824215](https://github.com/MicrosoftDocs/msteams-docs/commits/c8242152b94254edef3baefe42568c49bcab6993)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/Cards/full-width-adaptive-card.png](https://github.com/MicrosoftDocs/msteams-docs/blob/ojasvichoudhary-patch-1/msteams-platform/assets/images/Cards/full-width-adaptive-card.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?branch=pr-en-us-2722) |
[msteams-platform/assets/images/Cards/small-width-adaptive-card.png](https://github.com/MicrosoftDocs/msteams-docs/blob/ojasvichoudhary-patch-1/msteams-platform/assets/images/Cards/small-width-adaptive-card.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?branch=pr-en-us-2722) |
[msteams-platform/task-modules-and-cards/cards/cards-format.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ojasvichoudhary-patch-1/msteams-platform/task-modules-and-cards/cards/cards-format.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?branch=pr-en-us-2722) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C17%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202102171221103018-2722%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=zOijXiFM8snVqXizjP2FOcXWAaSGR%2Bqn45KFsIjfx6w%3D&st=2021-02-17T12%3A16%3A42Z&se=2021-03-20T12%3A21%3A42Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-17 12:25 UTC, opbld32 commented
Docs Build status updates of commit _[9b70d5d](https://github.com/MicrosoftDocs/msteams-docs/commits/9b70d5dd397466fe0c641b5c50cd97a394170159)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/Cards/full-width-adaptive-card.png](https://github.com/MicrosoftDocs/msteams-docs/blob/ojasvichoudhary-patch-1/msteams-platform/assets/images/Cards/full-width-adaptive-card.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?branch=pr-en-us-2722) |
[msteams-platform/assets/images/Cards/small-width-adaptive-card.png](https://github.com/MicrosoftDocs/msteams-docs/blob/ojasvichoudhary-patch-1/msteams-platform/assets/images/Cards/small-width-adaptive-card.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?branch=pr-en-us-2722) |
[msteams-platform/task-modules-and-cards/cards/cards-format.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ojasvichoudhary-patch-1/msteams-platform/task-modules-and-cards/cards/cards-format.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?branch=pr-en-us-2722) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C17%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202102171225276879-2722%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=z%2BmSDPZ9A6ishAV1sgbLfSvJwsK%2B8kggFQVI7VS1MNA%3D&st=2021-02-17T12%3A20%3A57Z&se=2021-03-20T12%3A25%3A57Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-17 12:33 UTC, opbld32 commented
Docs Build status updates of commit _[e30828b](https://github.com/MicrosoftDocs/msteams-docs/commits/e30828b96ef0a80ae768bd6e78de5124c173145b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/Cards/full-width-adaptive-card.png](https://github.com/MicrosoftDocs/msteams-docs/blob/ojasvichoudhary-patch-1/msteams-platform/assets/images/Cards/full-width-adaptive-card.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?branch=pr-en-us-2722) |
[msteams-platform/assets/images/Cards/small-width-adaptive-card.png](https://github.com/MicrosoftDocs/msteams-docs/blob/ojasvichoudhary-patch-1/msteams-platform/assets/images/Cards/small-width-adaptive-card.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?branch=pr-en-us-2722) |
[msteams-platform/task-modules-and-cards/cards/cards-format.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ojasvichoudhary-patch-1/msteams-platform/task-modules-and-cards/cards/cards-format.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?branch=pr-en-us-2722) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C17%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202102171233091456-2722%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=3z2TcZ3ftr2hIY03RvKrX55gvU48IboQwuAY5Mcehxw%3D&st=2021-02-17T12%3A28%3A41Z&se=2021-03-20T12%3A33%3A41Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-17 12:42 UTC, opbld32 commented
Docs Build status updates of commit _[d576ddf](https://github.com/MicrosoftDocs/msteams-docs/commits/d576ddfa5429f3b9e3ac8d5a7750a0e674393012)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/Cards/full-width-adaptive-card.png](https://github.com/MicrosoftDocs/msteams-docs/blob/ojasvichoudhary-patch-1/msteams-platform/assets/images/Cards/full-width-adaptive-card.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?branch=pr-en-us-2722) |
[msteams-platform/assets/images/Cards/small-width-adaptive-card.png](https://github.com/MicrosoftDocs/msteams-docs/blob/ojasvichoudhary-patch-1/msteams-platform/assets/images/Cards/small-width-adaptive-card.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?branch=pr-en-us-2722) |
[msteams-platform/task-modules-and-cards/cards/cards-format.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ojasvichoudhary-patch-1/msteams-platform/task-modules-and-cards/cards/cards-format.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?branch=pr-en-us-2722) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C17%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202102171241476178-2722%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=dToGXArsSKepHSsKmSOaT0PEftBx5OaEtOiT9NGQzNw%3D&st=2021-02-17T12%3A37%3A34Z&se=2021-03-20T12%3A42%3A34Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-17 12:43 UTC, opbld32 commented
Docs Build status updates of commit _[7efc1a2](https://github.com/MicrosoftDocs/msteams-docs/commits/7efc1a28b72214e9cdd17c76be61481b6291d7e1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/Cards/full-width-adaptive-card.png](https://github.com/MicrosoftDocs/msteams-docs/blob/ojasvichoudhary-patch-1/msteams-platform/assets/images/Cards/full-width-adaptive-card.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?branch=pr-en-us-2722) |
[msteams-platform/assets/images/Cards/small-width-adaptive-card.png](https://github.com/MicrosoftDocs/msteams-docs/blob/ojasvichoudhary-patch-1/msteams-platform/assets/images/Cards/small-width-adaptive-card.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?branch=pr-en-us-2722) |
[msteams-platform/task-modules-and-cards/cards/cards-format.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ojasvichoudhary-patch-1/msteams-platform/task-modules-and-cards/cards/cards-format.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?branch=pr-en-us-2722) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C17%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202102171242576622-2722%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=bJrEhbQIqlBR3oXxWvFj%2FozYdvVi3rGsXDMIi%2Bj%2FyvU%3D&st=2021-02-17T12%3A38%3A30Z&se=2021-03-20T12%3A43%3A30Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-17 12:52 UTC, opbld31 commented
Docs Build status updates of commit _[229ba0e](https://github.com/MicrosoftDocs/msteams-docs/commits/229ba0e51a686466f846952e511952d28120ba09)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/Cards/full-width-adaptive-card.png](https://github.com/MicrosoftDocs/msteams-docs/blob/ojasvichoudhary-patch-1/msteams-platform/assets/images/Cards/full-width-adaptive-card.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?branch=pr-en-us-2722) |
[msteams-platform/assets/images/Cards/small-width-adaptive-card.png](https://github.com/MicrosoftDocs/msteams-docs/blob/ojasvichoudhary-patch-1/msteams-platform/assets/images/Cards/small-width-adaptive-card.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?branch=pr-en-us-2722) |
[msteams-platform/task-modules-and-cards/cards/cards-format.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ojasvichoudhary-patch-1/msteams-platform/task-modules-and-cards/cards/cards-format.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?branch=pr-en-us-2722) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C17%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202102171251132746-2722%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=gNLxO3T%2FwP6gijduIgKfEkHgkckYcnWmYVeqYD%2F7XGo%3D&st=2021-02-17T12%3A47%3A02Z&se=2021-03-20T12%3A52%3A02Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-17 12:55 UTC, opbld32 commented
Docs Build status updates of commit _[9c37586](https://github.com/MicrosoftDocs/msteams-docs/commits/9c37586b24f2fd91ada22e46b486f34338f1c900)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/Cards/full-width-adaptive-card.png](https://github.com/MicrosoftDocs/msteams-docs/blob/ojasvichoudhary-patch-1/msteams-platform/assets/images/Cards/full-width-adaptive-card.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?branch=pr-en-us-2722) |
[msteams-platform/assets/images/Cards/small-width-adaptive-card.png](https://github.com/MicrosoftDocs/msteams-docs/blob/ojasvichoudhary-patch-1/msteams-platform/assets/images/Cards/small-width-adaptive-card.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?branch=pr-en-us-2722) |
[msteams-platform/task-modules-and-cards/cards/cards-format.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ojasvichoudhary-patch-1/msteams-platform/task-modules-and-cards/cards/cards-format.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?branch=pr-en-us-2722) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C17%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202102171254534785-2722%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=bO8EgnNEMOOKbFrpKef3ulC%2BNGlg%2F1XO4jFdpQ28NTQ%3D&st=2021-02-17T12%3A50%3A26Z&se=2021-03-20T12%3A55%3A26Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-17 13:01 UTC, opbld32 commented
Docs Build status updates of commit _[8856532](https://github.com/MicrosoftDocs/msteams-docs/commits/8856532c6705f7fdb7a7907a5417791fbe8e69e0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/Cards/full-width-adaptive-card.png](https://github.com/MicrosoftDocs/msteams-docs/blob/ojasvichoudhary-patch-1/msteams-platform/assets/images/Cards/full-width-adaptive-card.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?branch=pr-en-us-2722) |
[msteams-platform/assets/images/Cards/small-width-adaptive-card.png](https://github.com/MicrosoftDocs/msteams-docs/blob/ojasvichoudhary-patch-1/msteams-platform/assets/images/Cards/small-width-adaptive-card.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?branch=pr-en-us-2722) |
[msteams-platform/task-modules-and-cards/cards/cards-format.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ojasvichoudhary-patch-1/msteams-platform/task-modules-and-cards/cards/cards-format.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?branch=pr-en-us-2722) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C17%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202102171300297358-2722%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=iX1cl8Mlb%2FjirRRmStw7lxUP6Kdmm%2FPgiqGjF9Ww5u0%3D&st=2021-02-17T12%3A56%3A09Z&se=2021-03-20T13%3A01%3A09Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-17 13:04 UTC, opbld32 commented
Docs Build status updates of commit _[3340372](https://github.com/MicrosoftDocs/msteams-docs/commits/3340372120fbacb914b9bf05feda19d1f345b478)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/Cards/full-width-adaptive-card.png](https://github.com/MicrosoftDocs/msteams-docs/blob/ojasvichoudhary-patch-1/msteams-platform/assets/images/Cards/full-width-adaptive-card.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?branch=pr-en-us-2722) |
[msteams-platform/assets/images/Cards/small-width-adaptive-card.png](https://github.com/MicrosoftDocs/msteams-docs/blob/ojasvichoudhary-patch-1/msteams-platform/assets/images/Cards/small-width-adaptive-card.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?branch=pr-en-us-2722) |
[msteams-platform/task-modules-and-cards/cards/cards-format.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ojasvichoudhary-patch-1/msteams-platform/task-modules-and-cards/cards/cards-format.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?branch=pr-en-us-2722) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C17%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202102171303504845-2722%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ppJrz76sV1LPLriQgOGQSqHV%2FwAhCJ9LaCcLaijF%2BmM%3D&st=2021-02-17T12%3A59%3A37Z&se=2021-03-20T13%3A04%3A37Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-17 13:08 UTC, KirtiPereira commented
@ojasvichoudhary - have uploaded the screenshots as discussed. Please verify the placement is appropriate and also commit the suggestions / comments already provided and confirm if the PR can be merged.

2021-02-17 13:40 UTC, opbld31 commented
Docs Build status updates of commit _[3829e63](https://github.com/MicrosoftDocs/msteams-docs/commits/3829e637e931ef038c2c935f33c7a25caec9b521)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/Cards/full-width-adaptive-card.png](https://github.com/MicrosoftDocs/msteams-docs/blob/ojasvichoudhary-patch-1/msteams-platform/assets/images/Cards/full-width-adaptive-card.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?branch=pr-en-us-2722) |
[msteams-platform/assets/images/Cards/small-width-adaptive-card.png](https://github.com/MicrosoftDocs/msteams-docs/blob/ojasvichoudhary-patch-1/msteams-platform/assets/images/Cards/small-width-adaptive-card.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?branch=pr-en-us-2722) |
[msteams-platform/task-modules-and-cards/cards/cards-format.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ojasvichoudhary-patch-1/msteams-platform/task-modules-and-cards/cards/cards-format.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?branch=pr-en-us-2722) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C17%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202102171340069790-2722%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2FckuDybyUr%2FrCoLszhEYrzY2vE025N1y%2FAysGFzN5qw%3D&st=2021-02-17T13%3A35%3A38Z&se=2021-03-20T13%3A40%3A38Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-17 13:44 UTC, opbld31 commented
Docs Build status updates of commit _[386fbfa](https://github.com/MicrosoftDocs/msteams-docs/commits/386fbfa5082b8dd129c22236ae43af1a3236bcab)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/Cards/full-width-adaptive-card.png](https://github.com/MicrosoftDocs/msteams-docs/blob/ojasvichoudhary-patch-1/msteams-platform/assets/images/Cards/full-width-adaptive-card.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?branch=pr-en-us-2722) |
[msteams-platform/assets/images/Cards/small-width-adaptive-card.png](https://github.com/MicrosoftDocs/msteams-docs/blob/ojasvichoudhary-patch-1/msteams-platform/assets/images/Cards/small-width-adaptive-card.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?branch=pr-en-us-2722) |
[msteams-platform/task-modules-and-cards/cards/cards-format.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ojasvichoudhary-patch-1/msteams-platform/task-modules-and-cards/cards/cards-format.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?branch=pr-en-us-2722) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C17%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202102171343543378-2722%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ppAnrHNlCyzanILqJLoBwawzx1QuJ9r0ACB%2F3ynD9Wc%3D&st=2021-02-17T13%3A39%3A44Z&se=2021-03-20T13%3A44%3A44Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-23 07:09 UTC, ojasvichoudhary commented
@KirtiPereira changes look good, can you please push this PR out, I'll create a separate one for other cards changes.

2021-02-23 07:10 UTC, ojasvichoudhary reviewed
changes look good

2021-03-04 07:03 UTC, KirtiPereira approved these changes
Approved

2021-03-04 07:04 UTC, surbhigupta12 approved these changes

2021-03-04 07:04 UTC, merged