[Bots][AddedclientInfoentity][1492175]
MicrosoftDocs/msteams-docs pull request #2734
Opened 2021-02-03 12:07 UTC by v-rodriguezd

Added get clientInfo in your bot context section with json and c# code. Reviewed document for grammar and formatting. Please review.

2021-02-03 12:08 UTC, opbld30 commented
Docs Build status updates of commit _[7762b10](https://github.com/MicrosoftDocs/msteams-docs/commits/7762b1005ed81fe81c55ff85debe34c762a20af8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/resources/bot-v3/bot-conversations/bots-conv-proactive.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1492175-Clientinfoentity/msteams-platform/resources/bot-v3/bot-conversations/bots-conv-proactive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bot-conversations/bots-conv-proactive?branch=pr-en-us-2734) | [Details](#user-content-10cd35ed-28c1513c)
[msteams-platform/resources/bot-v3/bot-conversations/bots-conv-channel.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1492175-Clientinfoentity/msteams-platform/resources/bot-v3/bot-conversations/bots-conv-channel.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bot-conversations/bots-conv-channel?branch=pr-en-us-2734) | [Details](#user-content-0aa0f724-28c1513c)
[msteams-platform/resources/bot-v3/bots-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1492175-Clientinfoentity/msteams-platform/resources/bot-v3/bots-context.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bots-context?branch=pr-en-us-2734) | [Details](#user-content-5b981841-28c1513c)
[msteams-platform/includes/v3-to-v4-pointer-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1492175-Clientinfoentity/msteams-platform/includes/v3-to-v4-pointer-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bots-context?branch=pr-en-us-2734) |

<a id="10cd35ed-28c1513c"></a>
### [msteams-platform/resources/bot-v3/bot-conversations/bots-conv-proactive.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1492175-Clientinfoentity/msteams-platform/resources/bot-v3/bot-conversations/bots-conv-proactive.md)
 - **Line 52, Column 6**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#fetching-the-team-roster' in 'resources/bot-v3/bots-context.md', did you mean '#fetch-the-team-roster'?`````

<a id="0aa0f724-28c1513c"></a>
### [msteams-platform/resources/bot-v3/bot-conversations/bots-conv-channel.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1492175-Clientinfoentity/msteams-platform/resources/bot-v3/bot-conversations/bots-conv-channel.md)
 - **Line 51, Column 120**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#fetching-the-team-roster' in 'resources/bot-v3/bots-context.md', did you mean '#fetch-the-team-roster'?`````

<a id="5b981841-28c1513c"></a>
### [msteams-platform/resources/bot-v3/bots-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1492175-Clientinfoentity/msteams-platform/resources/bot-v3/bots-context.md)
 - **Line 209, Column 1**: **[Suggestion-[code-block-unclosed](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-indented?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C3%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202102031207309981-2734%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=XK76%2BVfQ5CQ7kiNt5hlOjNFrHQz4X5z3DWrVPrBueZ4%3D&st=2021-02-03T12%3A03%3A22Z&se=2021-03-06T12%3A08%3A22Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-04 05:39 UTC, KirtiPereira requested changes
@v-rodriguezd - please verify and incorporate the suggestion.

2021-02-04 05:39 UTC, KirtiPereira commented on msteams-platform/resources/bot-v3/bots-context.md
> +Your bot can query for the list of team members and their basic profiles, which includes Teams user IDs and Azure Active Directory (AAD) information such as name and objectId. You can use this inform
```suggestion
Your bot can query for the list of team members and their basic profiles, which includes Teams user IDs and Azure Active Directory (AAD) information such as name and objectId. You can use this information to correlate user identities. For example, to check if a user logged into a tab through AAD credentials is a member of the team.
```

2021-02-04 05:39 UTC, KirtiPereira commented on msteams-platform/resources/bot-v3/bots-context.md
> +Your bot can query for the list of team members and their basic profiles, which includes Teams user IDs and Azure Active Directory (AAD) information such as name and objectId. You can use this inform
Should **objectId** be object ID? Please verify and update.

2021-02-04 05:39 UTC, KirtiPereira commented on msteams-platform/resources/bot-v3/bots-context.md
> +You can directly issue a GET request on [`/conversations/{teamId}/members/`](/bot-framework/rest-api/bot-framework-rest-connector-api-reference#get-conversation-members), using the `serviceUrl` value
```suggestion
Directly issue a GET request on [`/conversations/{teamId}/members/`](/bot-framework/rest-api/bot-framework-rest-connector-api-reference#get-conversation-members), using the `serviceUrl` value as the endpoint.
```

2021-02-04 05:39 UTC, KirtiPereira commented on msteams-platform/resources/bot-v3/bots-context.md
> +>* The value of `serviceUrl` tends to be stable but can change. When a new message arrives, your bot must verify its stored value of `serviceUrl`.
```suggestion
>* The value of `serviceUrl` tends to be stable but can change. When a new message arrives, your bot must verify its stored `serviceUrl` value.
```

2021-02-04 05:39 UTC, KirtiPereira commented on msteams-platform/resources/bot-v3/bots-context.md
> +You can directly issue a GET request on `/teams/{teamId}/conversations/`, using the `serviceUrl` value as the endpoint.
```suggestion
Directly issue a GET request on `/teams/{teamId}/conversations/`, using the `serviceUrl` value as the endpoint.
```

2021-02-04 05:40 UTC, KirtiPereira commented
Also, please work on the Warnings.

2021-02-04 07:14 UTC, opbld30 commented
Docs Build status updates of commit _[c79f3f0](https://github.com/MicrosoftDocs/msteams-docs/commits/c79f3f0b06a9bdd6c656ba0a06d74ad6d4d4bb41)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/includes/v3-to-v4-pointer-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1492175-Clientinfoentity/msteams-platform/includes/v3-to-v4-pointer-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bot-conversations/bots-conv-channel?branch=pr-en-us-2734) |
[msteams-platform/resources/bot-v3/bot-conversations/bots-conv-channel.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1492175-Clientinfoentity/msteams-platform/resources/bot-v3/bot-conversations/bots-conv-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bot-conversations/bots-conv-channel?branch=pr-en-us-2734) |
[msteams-platform/resources/bot-v3/bot-conversations/bots-conv-proactive.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1492175-Clientinfoentity/msteams-platform/resources/bot-v3/bot-conversations/bots-conv-proactive.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bot-conversations/bots-conv-proactive?branch=pr-en-us-2734) |
[msteams-platform/resources/bot-v3/bots-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1492175-Clientinfoentity/msteams-platform/resources/bot-v3/bots-context.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bots-context?branch=pr-en-us-2734) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C4%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202102040713567611-2734%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=921JbWxIXqVpJkzfHaighBt6i9fni3ViGnYSnffxZkA%3D&st=2021-02-04T07%3A09%3A30Z&se=2021-03-07T07%3A14%3A30Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-04 08:54 UTC, opbld30 commented
Docs Build status updates of commit _[3b7431f](https://github.com/MicrosoftDocs/msteams-docs/commits/3b7431f7d00b57bc1dc701c0cd0aa28cea20973f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/includes/v3-to-v4-pointer-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1492175-Clientinfoentity/msteams-platform/includes/v3-to-v4-pointer-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bot-conversations/bots-conv-channel?branch=pr-en-us-2734) |
[msteams-platform/resources/bot-v3/bot-conversations/bots-conv-channel.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1492175-Clientinfoentity/msteams-platform/resources/bot-v3/bot-conversations/bots-conv-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bot-conversations/bots-conv-channel?branch=pr-en-us-2734) |
[msteams-platform/resources/bot-v3/bot-conversations/bots-conv-proactive.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1492175-Clientinfoentity/msteams-platform/resources/bot-v3/bot-conversations/bots-conv-proactive.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bot-conversations/bots-conv-proactive?branch=pr-en-us-2734) |
[msteams-platform/resources/bot-v3/bots-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1492175-Clientinfoentity/msteams-platform/resources/bot-v3/bots-context.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bots-context?branch=pr-en-us-2734) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C4%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202102040853262801-2734%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ArtyM%2FvqqDg7xu%2FLXlsamlRvuxaB5AFoWmwZb6FGy2s%3D&st=2021-02-04T08%3A49%3A01Z&se=2021-03-07T08%3A54%3A01Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-04 12:58 UTC, KirtiPereira approved these changes
Approved

2021-02-10 08:49 UTC, Trinetra-MSFT approved these changes

2021-02-10 09:08 UTC, surbhigupta12 approved these changes
Approving the PR

2021-02-10 12:07 UTC, merged