Changed Emergency Button app to Get Support
MicrosoftDocs/msteams-docs pull request #2736
Opened 2021-02-03 13:03 UTC by adityachallapally

And added gif

2021-02-03 13:04 UTC, opbld33 commented
Docs Build status updates of commit _[6340953](https://github.com/MicrosoftDocs/msteams-docs/commits/63409536fd805ccd82f1b11d1ec8b007196f91c0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/samples/app-templates.md](https://github.com/MicrosoftDocs/msteams-docs/blob/get-support-app/msteams-platform/samples/app-templates.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/samples/app-templates?branch=pr-en-us-2736) | [Details](#user-content-528f02ad-6c7feb19)

<a id="528f02ad-6c7feb19"></a>
### [msteams-platform/samples/app-templates.md](https://github.com/MicrosoftDocs/msteams-docs/blob/get-support-app/msteams-platform/samples/app-templates.md)
 - **Line 579, Column 1**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../assets/images/get-support.gif'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C3%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202102031303467979-2736%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=xtncj%2ByVoGBSc44m6aeISHkjcRMJwRjXpW3WZEOv91s%3D&st=2021-02-03T12%3A59%3A21Z&se=2021-03-06T13%3A04%3A21Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-03 13:53 UTC, KirtiPereira requested changes
@adityachallapally - please move **Get Support App** after **FAQ Plus** as it needs to be in alphabetical order. It is currently appearing after **Staff Check-ins**.
Thank you.

2021-02-05 16:54 UTC, opbld32 commented
Docs Build status updates of commit _[91dc604](https://github.com/MicrosoftDocs/msteams-docs/commits/91dc60415a79bfa8ce347300e280cee01fc78ead)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/samples/app-templates.md](https://github.com/MicrosoftDocs/msteams-docs/blob/get-support-app/msteams-platform/samples/app-templates.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/samples/app-templates?branch=pr-en-us-2736) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C5%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202102051653558779-2736%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ldqSKG6PBmADNw5U2eXXxKFPXS1inmsJlDWCk8V%2FJgk%3D&st=2021-02-05T16%3A49%3A30Z&se=2021-03-08T16%3A54%3A30Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-08 11:59 UTC, KirtiPereira approved these changes
Approved

2021-02-08 11:59 UTC, surbhigupta12 approved these changes
Approving the PR.

2021-02-08 11:59 UTC, merged