[Bots][Universalbotactionmodelnewdocument][1149654]
MicrosoftDocs/msteams-docs pull request #2769
Opened 2021-02-11 06:24 UTC by v-rodriguezd

Created draft version of Universal bot action model document. Please review.

2021-02-11 06:25 UTC, opbld32 commented
Docs Build status updates of commit _[8b29654](https://github.com/MicrosoftDocs/msteams-docs/commits/8b2965418f1d23b5ba4be62f9165c49e7b0f1614)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/TOC.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model?branch=pr-en-us-2769) | [Details](#user-content-0d1dee3d-483e9dad)
[msteams-platform/bots/Universal-bot-action-model.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/bots/Universal-bot-action-model.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model?branch=pr-en-us-2769) | [Details](#user-content-efa987d9-483e9dad)
[msteams-platform/assets/images/bots/contextual-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/new-universal-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/new-universal-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/sequentialworkflow.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/sequentialworkflow.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/universal-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/universal-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model?branch=pr-en-us-2769) |

<a id="0d1dee3d-483e9dad"></a>
### [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/TOC.yml)
 - **Line 240, Column 11**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/Universal-bot-action-model.md'.`````

<a id="efa987d9-483e9dad"></a>
### [msteams-platform/bots/Universal-bot-action-model.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/bots/Universal-bot-action-model.md)
 - **Line 28, Column 27**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/outlook/actionable-messages/send-via-email' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C11%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202102110624277352-2769%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=6WfEzrCBWKMEzdIAqflkIJ0P3%2FkKFk1oyba48VxgzGM%3D&st=2021-02-11T06%3A20%3A13Z&se=2021-03-14T06%3A25%3A13Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-11 08:41 UTC, opbld33 commented
Docs Build status updates of commit _[64a30c1](https://github.com/MicrosoftDocs/msteams-docs/commits/64a30c1d0ccc288ac7934da5aa40e4994b291afe)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/bots/Universal-bot-action-model/Develop-universal-bot-action-model.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/bots/Universal-bot-action-model/Develop-universal-bot-action-model.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/develop-universal-bot-action-model?branch=pr-en-us-2769) | [Details](#user-content-80d145ec-f73aad18)
[msteams-platform/bots/Universal-bot-action-model/Overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/bots/Universal-bot-action-model/Overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) | [Details](#user-content-48316b08-f73aad18)
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/develop-universal-bot-action-model?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/contextual-views.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/inconsistent-action-model-lifecycle.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/inconsistent-action-model.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/new-universal-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/new-universal-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/new-universal-action-model.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/sequentialworkflow.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/sequentialworkflow.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/sequentialworkflow.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/universal-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/universal-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/universal-action-model-lifecycle.png?branch=pr-en-us-2769) |

<a id="80d145ec-f73aad18"></a>
### [msteams-platform/bots/Universal-bot-action-model/Develop-universal-bot-action-model.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/bots/Universal-bot-action-model/Develop-universal-bot-action-model.md)
 - **Line 17, Column 27**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/outlook/actionable-messages/send-via-email' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````

<a id="48316b08-f73aad18"></a>
### [msteams-platform/bots/Universal-bot-action-model/Overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/bots/Universal-bot-action-model/Overview.md)
 - **Line 15, Column 1**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../assets/images/bots/inconsistent-action-model-lifecycle.png'.`````
 - **Line 17, Column 1**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../assets/images/bots/universal-action-model-lifecycle.png'.`````
 - **Line 42, Column 1**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../assets/images/bots/inconsistent-action-model.png'.`````
 - **Line 46, Column 1**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../assets/images/bots/new-universal-action-model.png'.`````
 - **Line 52, Column 1**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../assets/images/bots/contextual-views.png'.`````
 - **Line 58, Column 1**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../assets/images/bots/sequentialworkflow.png'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C11%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202102110840263298-2769%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=CA4FrM2aCPbm43azzcC%2BlYt4KmCczx1VXLIfL%2Bu3SWM%3D&st=2021-02-11T08%3A36%3A02Z&se=2021-03-14T08%3A41%3A02Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/ [...]

2021-02-11 08:49 UTC, opbld31 commented
Docs Build status updates of commit _[7af7d24](https://github.com/MicrosoftDocs/msteams-docs/commits/7af7d243e8ea1ddaffba859e8c79c25fa62af70d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/bots/Universal-bot-action-model/Develop-universal-bot-action-model.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/bots/Universal-bot-action-model/Develop-universal-bot-action-model.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/develop-universal-bot-action-model?branch=pr-en-us-2769) | [Details](#user-content-80d145ec-7b92406d)
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/develop-universal-bot-action-model?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/new-universal-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/new-universal-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/sequentialworkflow.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/sequentialworkflow.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/universal-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/universal-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/bots/Universal-bot-action-model/Overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/bots/Universal-bot-action-model/Overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |

<a id="80d145ec-7b92406d"></a>
### [msteams-platform/bots/Universal-bot-action-model/Develop-universal-bot-action-model.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/bots/Universal-bot-action-model/Develop-universal-bot-action-model.md)
 - **Line 17, Column 27**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/outlook/actionable-messages/send-via-email' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C11%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202102110848482614-2769%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=n83mzzjFz8rn0UsdOYj9nFzWfJ2bGf7iFTnyad5QpwM%3D&st=2021-02-11T08%3A44%3A23Z&se=2021-03-14T08%3A49%3A23Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-11 11:08 UTC, opbld31 commented
Docs Build status updates of commit _[8a8d533](https://github.com/MicrosoftDocs/msteams-docs/commits/8a8d533d6ef86de99f5796dfe0696495a9e0b679)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/bots/Universal-bot-action-model/Develop-universal-bot-action-model.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/bots/Universal-bot-action-model/Develop-universal-bot-action-model.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/develop-universal-bot-action-model?branch=pr-en-us-2769) | [Details](#user-content-80d145ec-9287312b)
[msteams-platform/bots/Universal-bot-action-model/Overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/bots/Universal-bot-action-model/Overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) | [Details](#user-content-48316b08-9287312b)
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/develop-universal-bot-action-model?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/new-universal-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/new-universal-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/sequentialworkflow.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/sequentialworkflow.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/universal-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/universal-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |

<a id="80d145ec-9287312b"></a>
### [msteams-platform/bots/Universal-bot-action-model/Develop-universal-bot-action-model.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/bots/Universal-bot-action-model/Develop-universal-bot-action-model.md)
 - **Line 17, Column 27**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/outlook/actionable-messages/send-via-email' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````

<a id="48316b08-9287312b"></a>
### [msteams-platform/bots/Universal-bot-action-model/Overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/bots/Universal-bot-action-model/Overview.md)
 - **Line 52, Column 1**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '~/assets/images/bots/contextual-views.png'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C11%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202102111107307817-2769%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=A5hxZxKUfZ%2FYgE1LJGEV8sryOYJ8qGCxbqOtNIxY3TM%3D&st=2021-02-11T11%3A03%3A05Z&se=2021-03-14T11%3A08%3A05Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-11 11:09 UTC, opbld31 commented
Docs Build status updates of commit _[81d438d](https://github.com/MicrosoftDocs/msteams-docs/commits/81d438ddc0e139e81bc436910e5865f270913477)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/bots/Universal-bot-action-model/Develop-universal-bot-action-model.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/bots/Universal-bot-action-model/Develop-universal-bot-action-model.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/develop-universal-bot-action-model?branch=pr-en-us-2769) | [Details](#user-content-80d145ec-9f25aa36)
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/develop-universal-bot-action-model?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/contextual-views2.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/new-universal-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/new-universal-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/sequentialworkflow.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/sequentialworkflow.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/universal-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/universal-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/bots/Universal-bot-action-model/Overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/bots/Universal-bot-action-model/Overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |

<a id="80d145ec-9f25aa36"></a>
### [msteams-platform/bots/Universal-bot-action-model/Develop-universal-bot-action-model.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/bots/Universal-bot-action-model/Develop-universal-bot-action-model.md)
 - **Line 17, Column 27**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/outlook/actionable-messages/send-via-email' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C11%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202102111108247109-2769%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=T7muYg3LzNtEButjkL%2BTquqvVPFmQpuhZre3yNIde6w%3D&st=2021-02-11T11%3A03%3A59Z&se=2021-03-14T11%3A08%3A59Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-11 13:42 UTC, opbld32 commented
Docs Build status updates of commit _[5661d0e](https://github.com/MicrosoftDocs/msteams-docs/commits/5661d0e3d9ee475123bf229e02b70a2ba871fa76)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/develop-universal-bot-action-model?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/new-universal-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/new-universal-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/sequentialworkflow.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/sequentialworkflow.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/universal-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/universal-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/bots/Universal-bot-action-model/Develop-universal-bot-action-model.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/bots/Universal-bot-action-model/Develop-universal-bot-action-model.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/develop-universal-bot-action-model?branch=pr-en-us-2769) |
[msteams-platform/bots/Universal-bot-action-model/Overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/bots/Universal-bot-action-model/Overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C11%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202102111342061084-2769%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=YnDA4YMOxeGB7J2G8UgyjXFZc9JXjmqBb%2F6ySTJxRUg%3D&st=2021-02-11T13%3A37%3A37Z&se=2021-03-14T13%3A42%3A37Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-12 07:55 UTC, opbld32 commented
Docs Build status updates of commit _[b18433c](https://github.com/MicrosoftDocs/msteams-docs/commits/b18433ca66af1bf68032a045b9d47ddcc11ed18f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/develop-universal-bot-action-model?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/new-universal-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/new-universal-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/sequentialworkflow.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/sequentialworkflow.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/universal-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/universal-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/bots/Universal-bot-action-model/Develop-universal-bot-action-model.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/bots/Universal-bot-action-model/Develop-universal-bot-action-model.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/develop-universal-bot-action-model?branch=pr-en-us-2769) |
[msteams-platform/bots/Universal-bot-action-model/Overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/bots/Universal-bot-action-model/Overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C12%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202102120755003291-2769%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=fbrLuDO8hvirbBS6PRKiA5wPA4O743zUj04cLdlphXs%3D&st=2021-02-12T07%3A50%3A44Z&se=2021-03-15T07%3A55%3A44Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-15 12:07 UTC, opbld31 commented
Docs Build status updates of commit _[9da0f76](https://github.com/MicrosoftDocs/msteams-docs/commits/9da0f76c0bb6f96aa28aacfe15213d5fa0cd1d40)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/develop-universal-bot-action-model?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/new-universal-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/new-universal-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/sequentialworkflow.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/sequentialworkflow.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/universal-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/universal-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/bots/Universal-bot-action-model/Develop-universal-bot-action-model.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/bots/Universal-bot-action-model/Develop-universal-bot-action-model.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/develop-universal-bot-action-model?branch=pr-en-us-2769) |
[msteams-platform/bots/Universal-bot-action-model/Overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/bots/Universal-bot-action-model/Overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C15%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202102151207087152-2769%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=jeHEz4Km5C2lwXyoJaMxhsJEC01GZ9F8SvNtdPOvFkc%3D&st=2021-02-15T12%3A02%3A40Z&se=2021-03-18T12%3A07%3A40Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-15 12:16 UTC, opbld31 commented
Docs Build status updates of commit _[9c8f2c5](https://github.com/MicrosoftDocs/msteams-docs/commits/9c8f2c5fd052286bcc3aead0666e398d4e50bd61)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/bots/Universal-bot-action-model/Overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/bots/Universal-bot-action-model/Overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) | [Details](#user-content-48316b08-623b1495)
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/develop-universal-bot-action-model?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/sequentialworkflow.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/sequentialworkflow.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/universal-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/universal-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/bots/Universal-bot-action-model/Develop-universal-bot-action-model.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/bots/Universal-bot-action-model/Develop-universal-bot-action-model.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/develop-universal-bot-action-model?branch=pr-en-us-2769) |

<a id="48316b08-623b1495"></a>
### [msteams-platform/bots/Universal-bot-action-model/Overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/bots/Universal-bot-action-model/Overview.md)
 - **Line 40, Column 1**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '~/assets/images/bots/new-universal-action-model.png'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C15%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202102151215538825-2769%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=p%2Bo3hiXLkd5CT5q9vLR4Hay%2FO%2F0E9Dg5CohRa1pNlP0%3D&st=2021-02-15T12%3A11%3A23Z&se=2021-03-18T12%3A16%3A23Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-15 12:17 UTC, opbld33 commented
Docs Build status updates of commit _[2fe1121](https://github.com/MicrosoftDocs/msteams-docs/commits/2fe112191f5ba6400219b47b0e8b0ccd661ac0f8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/develop-universal-bot-action-model?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/new-universal-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/new-universal-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/sequentialworkflow.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/sequentialworkflow.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/universal-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/universal-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/bots/Universal-bot-action-model/Develop-universal-bot-action-model.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/bots/Universal-bot-action-model/Develop-universal-bot-action-model.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/develop-universal-bot-action-model?branch=pr-en-us-2769) |
[msteams-platform/bots/Universal-bot-action-model/Overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/bots/Universal-bot-action-model/Overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C15%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202102151216272766-2769%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=gVR3j07nWUmvtY%2BU7Mg47rSk7vtsItOa3gWsNtwkQrs%3D&st=2021-02-15T12%3A12%3A10Z&se=2021-03-18T12%3A17%3A10Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-16 06:24 UTC, opbld33 commented
Docs Build status updates of commit _[b95e11c](https://github.com/MicrosoftDocs/msteams-docs/commits/b95e11cfeeafbd900165abe9b0ad12549b32b153)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/task-modules-and-cards/cards/cards-actions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/task-modules-and-cards/cards/cards-actions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions?branch=pr-en-us-2769) | [Details](#user-content-d4017612-1ffe8506)
[msteams-platform/task-modules-and-cards/what-are-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/task-modules-and-cards/what-are-cards.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/what-are-cards?branch=pr-en-us-2769) | [Details](#user-content-dcb4fc34-1ffe8506)
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/develop-universal-bot-action-model?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/new-universal-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/new-universal-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/sequentialworkflow.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/sequentialworkflow.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/universal-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/universal-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/bots/Universal-bot-action-model/Develop-universal-bot-action-model.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/bots/Universal-bot-action-model/Develop-universal-bot-action-model.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/develop-universal-bot-action-model?branch=pr-en-us-2769) |
[msteams-platform/bots/Universal-bot-action-model/Overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/bots/Universal-bot-action-model/Overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |

<a id="d4017612-1ffe8506"></a>
### [msteams-platform/task-modules-and-cards/cards/cards-actions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/task-modules-and-cards/cards/cards-actions.md)
 - **Line 223, Column 3**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#action.execute-command' in 'bots/Universal-bot-action-model/Develop-universal-bot-action-model.md', did you mean '#actionexecute-command'?`````

<a id="dcb4fc34-1ffe8506"></a>
### [msteams-platform/task-modules-and-cards/what-are-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/task-modules-and-cards/what-are-cards.md)
 - **Line 33, Column 285**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#action.execute-command' in 'bots/Universal-bot-action-model/Develop-universal-bot-action-model.md', did you mean '#actionexecute-command'?`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C16%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202102160623550792-2769%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=NMJz1EllWX2KEJZks1yG%2BIIc1CX90Y%2FyGLG23XzZLws%3D&st=2021-02-16T06%3A19%3A32Z&se=2021-03-19T06%3A24%3A32Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">D [...]

2021-02-16 06:27 UTC, opbld33 commented
Docs Build status updates of commit _[f36c280](https://github.com/MicrosoftDocs/msteams-docs/commits/f36c28057d1908e31f47f46c54e0ee39f93ba739)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/develop-universal-bot-action-model?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/new-universal-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/new-universal-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/sequentialworkflow.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/sequentialworkflow.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/universal-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/universal-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/bots/Universal-bot-action-model/Develop-universal-bot-action-model.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/bots/Universal-bot-action-model/Develop-universal-bot-action-model.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/develop-universal-bot-action-model?branch=pr-en-us-2769) |
[msteams-platform/bots/Universal-bot-action-model/Overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/bots/Universal-bot-action-model/Overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/task-modules-and-cards/cards/cards-actions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/task-modules-and-cards/cards/cards-actions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions?branch=pr-en-us-2769) |
[msteams-platform/task-modules-and-cards/what-are-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/task-modules-and-cards/what-are-cards.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/what-are-cards?branch=pr-en-us-2769) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C16%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202102160626227436-2769%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=iPGuGhJ%2By56WXuXGYjCaelNEQpHebt%2FGoPSXb3hF8rk%3D&st=2021-02-16T06%3A22%3A08Z&se=2021-03-19T06%3A27%3A08Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-16 06:38 UTC, opbld31 commented
Docs Build status updates of commit _[0162ced](https://github.com/MicrosoftDocs/msteams-docs/commits/0162ceda613e59d05a8dab1a703cdea9e83e1464)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/develop-universal-bot-action-model?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/new-universal-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/new-universal-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/sequentialworkflow.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/sequentialworkflow.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/universal-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/universal-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/bots/Universal-bot-action-model/Develop-universal-bot-action-model.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/bots/Universal-bot-action-model/Develop-universal-bot-action-model.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/develop-universal-bot-action-model?branch=pr-en-us-2769) |
[msteams-platform/bots/Universal-bot-action-model/Overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/bots/Universal-bot-action-model/Overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/task-modules-and-cards/cards/cards-actions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/task-modules-and-cards/cards/cards-actions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions?branch=pr-en-us-2769) |
[msteams-platform/task-modules-and-cards/what-are-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/task-modules-and-cards/what-are-cards.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/what-are-cards?branch=pr-en-us-2769) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C16%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202102160637376870-2769%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=jpf5CPW3f2o83I8eaVP7uZxTkLokSYVod6S3J%2FaL93s%3D&st=2021-02-16T06%3A33%3A16Z&se=2021-03-19T06%3A38%3A16Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-17 07:00 UTC, opbld33 commented
Docs Build status updates of commit _[8c00645](https://github.com/MicrosoftDocs/msteams-docs/commits/8c006456c5d5d540a6e4a4a8d79947f6832aadcd)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/TOC.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) | [Details](#user-content-0d1dee3d-464ac325)
[msteams-platform/bots/Universal-bot-action-model/Overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/bots/Universal-bot-action-model/Overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) | [Details](#user-content-48316b08-464ac325)
[msteams-platform/assets/images/bots/contextual-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/new-universal-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/new-universal-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/sequentialworkflow.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/sequentialworkflow.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/universal-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/universal-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/bots/Universal-bot-action-model/Work-with-universal-bot-action-model.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/bots/Universal-bot-action-model/Work-with-universal-bot-action-model.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/work-with-universal-bot-action-model?branch=pr-en-us-2769) |
[msteams-platform/task-modules-and-cards/cards/cards-actions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/task-modules-and-cards/cards/cards-actions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions?branch=pr-en-us-2769) |
[msteams-platform/task-modules-and-cards/what-are-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/task-modules-and-cards/what-are-cards.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/what-are-cards?branch=pr-en-us-2769) |

<a id="0d1dee3d-464ac325"></a>
### [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/TOC.yml)
 - **Line 244, Column 13**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'bots/Universal-bot-action-model/Develop-universal-bot-action-model.md'.`````

<a id="48316b08-464ac325"></a>
### [msteams-platform/bots/Universal-bot-action-model/Overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/bots/Universal-bot-action-model/Overview.md)
 - **Line 67, Column 27**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#refresh-feature' in 'bots/Universal-bot-action-model/Overview.md'.`````
 - **Line 95, Column 3**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'Develop-universal-bot-action-model.md'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C17%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202102170659174348-2769%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=QphLrts1AS5RskibRHDwJKHjdaKcwkGA%2Bn%2F9kgr4pHY%3D&st=2021-02-17T06%3A55%3A04Z&se=2021-03-20T07%3A00%3A04Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4- [...]

2021-02-17 12:08 UTC, opbld31 commented
Docs Build status updates of commit _[41e0549](https://github.com/MicrosoftDocs/msteams-docs/commits/41e05497f23433f37137de8e0cddef6171b39328)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/new-universal-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/new-universal-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/sequentialworkflow.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/sequentialworkflow.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/universal-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/universal-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/bots/Universal-bot-action-model/Overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/bots/Universal-bot-action-model/Overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/bots/Universal-bot-action-model/Work-with-universal-bot-action-model.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/bots/Universal-bot-action-model/Work-with-universal-bot-action-model.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/work-with-universal-bot-action-model?branch=pr-en-us-2769) |
[msteams-platform/task-modules-and-cards/cards/cards-actions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/task-modules-and-cards/cards/cards-actions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions?branch=pr-en-us-2769) |
[msteams-platform/task-modules-and-cards/what-are-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/task-modules-and-cards/what-are-cards.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/what-are-cards?branch=pr-en-us-2769) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C17%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202102171208012667-2769%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=sYfMPgk4fxpz2WD8DHNJx9M2grZ5YkKYLH8TfbjmvHs%3D&st=2021-02-17T12%3A03%3A39Z&se=2021-03-20T12%3A08%3A39Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-18 05:53 UTC, opbld33 commented
Docs Build status updates of commit _[57f89a2](https://github.com/MicrosoftDocs/msteams-docs/commits/57f89a2056a1b11043524661525ed45ac0f6f2e7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/new-universal-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/new-universal-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/sequentialworkflow.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/sequentialworkflow.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/universal-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/universal-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/bots/Universal-bot-action-model/Overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/bots/Universal-bot-action-model/Overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/bots/Universal-bot-action-model/Work-with-universal-bot-action-model.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/bots/Universal-bot-action-model/Work-with-universal-bot-action-model.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/work-with-universal-bot-action-model?branch=pr-en-us-2769) |
[msteams-platform/task-modules-and-cards/cards/cards-actions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/task-modules-and-cards/cards/cards-actions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions?branch=pr-en-us-2769) |
[msteams-platform/task-modules-and-cards/what-are-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/task-modules-and-cards/what-are-cards.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/what-are-cards?branch=pr-en-us-2769) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C18%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202102180552223205-2769%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=WDet83VEeuJY26k%2Bhua77LAdYR3k0hgjU4MHI7GOc%2BU%3D&st=2021-02-18T05%3A47%3A59Z&se=2021-03-21T05%3A52%3A59Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-18 10:34 UTC, opbld30 commented
Docs Build status updates of commit _[06791be](https://github.com/MicrosoftDocs/msteams-docs/commits/06791beb416b37750cf69c5e81e6106caac7d1ec)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/bots/Universal-bot-action-model/Work-with-universal-bot-action-model.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/bots/Universal-bot-action-model/Work-with-universal-bot-action-model.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/work-with-universal-bot-action-model?branch=pr-en-us-2769) | [Details](#user-content-920b24aa-20f5b07f)
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/new-universal-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/new-universal-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/sequentialworkflow.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/sequentialworkflow.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/universal-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/universal-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/bots/Universal-bot-action-model/Overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/bots/Universal-bot-action-model/Overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/task-modules-and-cards/cards/cards-actions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/task-modules-and-cards/cards/cards-actions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions?branch=pr-en-us-2769) |
[msteams-platform/task-modules-and-cards/what-are-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/task-modules-and-cards/what-are-cards.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/what-are-cards?branch=pr-en-us-2769) |

<a id="920b24aa-20f5b07f"></a>
### [msteams-platform/bots/Universal-bot-action-model/Work-with-universal-bot-action-model.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/bots/Universal-bot-action-model/Work-with-universal-bot-action-model.md)
 - **Line 296, Column 3**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'azure/bot-service/bot-builder-basics'.`````
 - **Line 296, Column 3**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: azure/bot-service/bot-builder-basics?view=azure-bot-service-4.0. Otherwise, remove the view parameter.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C18%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202102181034000115-2769%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Zm9M9ZNyJzZb%2BNSGiN8XkTiY3JyC%2Bp%2FEQnbxN5%2BjjTw%3D&st=2021-02-18T10%3A29%3A29Z&se=2021-03-21T10%3A34%3A29Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-18 10:37 UTC, opbld32 commented
Docs Build status updates of commit _[5813f0a](https://github.com/MicrosoftDocs/msteams-docs/commits/5813f0a0266ee519ad07727bc939f4a22fe88508)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/new-universal-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/new-universal-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/sequentialworkflow.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/sequentialworkflow.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/universal-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/universal-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/bots/Universal-bot-action-model/Overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/bots/Universal-bot-action-model/Overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/bots/Universal-bot-action-model/Work-with-universal-bot-action-model.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/bots/Universal-bot-action-model/Work-with-universal-bot-action-model.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/work-with-universal-bot-action-model?branch=pr-en-us-2769) |
[msteams-platform/task-modules-and-cards/cards/cards-actions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/task-modules-and-cards/cards/cards-actions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions?branch=pr-en-us-2769) |
[msteams-platform/task-modules-and-cards/what-are-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/task-modules-and-cards/what-are-cards.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/what-are-cards?branch=pr-en-us-2769) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C18%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202102181036548475-2769%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=28r8BzLdJCW3g2k3w7LXwCyDON5VqnOsObREnHE5jaU%3D&st=2021-02-18T10%3A32%3A30Z&se=2021-03-21T10%3A37%3A30Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-18 10:52 UTC, opbld33 commented
Docs Build status updates of commit _[635955d](https://github.com/MicrosoftDocs/msteams-docs/commits/635955d0bc573a4596828c3edaa15b029e7648ba)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/new-universal-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/new-universal-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/sequentialworkflow.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/sequentialworkflow.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/universal-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/universal-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/bots/Universal-bot-action-model/Overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/bots/Universal-bot-action-model/Overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/bots/Universal-bot-action-model/Work-with-universal-bot-action-model.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/bots/Universal-bot-action-model/Work-with-universal-bot-action-model.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/work-with-universal-bot-action-model?branch=pr-en-us-2769) |
[msteams-platform/task-modules-and-cards/cards/cards-actions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/task-modules-and-cards/cards/cards-actions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions?branch=pr-en-us-2769) |
[msteams-platform/task-modules-and-cards/what-are-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/task-modules-and-cards/what-are-cards.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/what-are-cards?branch=pr-en-us-2769) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C18%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202102181051491616-2769%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=yydsvu86Y%2BzkSFNOewGxekLYae8FlJrCTyCamiVTz4M%3D&st=2021-02-18T10%3A47%3A22Z&se=2021-03-21T10%3A52%3A22Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-18 15:19 UTC, opbld33 commented
Docs Build status updates of commit _[2ca7848](https://github.com/MicrosoftDocs/msteams-docs/commits/2ca7848041d15e298eef5e4fe4e3834f3f08aa31)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/bots/Universal-bot-action-model/Overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/bots/Universal-bot-action-model/Overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) | [Details](#user-content-48316b08-40042c2e)
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/new-universal-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/new-universal-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/sequentialworkflow.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/sequentialworkflow.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/universal-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/universal-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/bots/Universal-bot-action-model/Work-with-universal-bot-action-model.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/bots/Universal-bot-action-model/Work-with-universal-bot-action-model.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/work-with-universal-bot-action-model?branch=pr-en-us-2769) |
[msteams-platform/task-modules-and-cards/cards/cards-actions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/task-modules-and-cards/cards/cards-actions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions?branch=pr-en-us-2769) |
[msteams-platform/task-modules-and-cards/what-are-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/task-modules-and-cards/what-are-cards.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/what-are-cards?branch=pr-en-us-2769) |

<a id="48316b08-40042c2e"></a>
### [msteams-platform/bots/Universal-bot-action-model/Overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/bots/Universal-bot-action-model/Overview.md)
 - **Line 36, Column 3**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#contextual-views' in 'bots/Universal-bot-action-model/Overview.md'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C18%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202102181519093695-2769%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Qsd2Pz26467u6zsgcKksSZd9knx2qpPNLRnJLNU5Ja0%3D&st=2021-02-18T15%3A14%3A46Z&se=2021-03-21T15%3A19%3A46Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-18 15:35 UTC, opbld31 commented
Docs Build status updates of commit _[76bc4f7](https://github.com/MicrosoftDocs/msteams-docs/commits/76bc4f7c916007e6548e44089a6c91d1aee3bf96)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/bots/Universal-bot-action-model/Overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/bots/Universal-bot-action-model/Overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) | [Details](#user-content-48316b08-87a038ab)
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/new-universal-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/new-universal-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/sequentialworkflow.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/sequentialworkflow.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/universal-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/universal-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/bots/Universal-bot-action-model/Work-with-universal-bot-action-model.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/bots/Universal-bot-action-model/Work-with-universal-bot-action-model.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/work-with-universal-bot-action-model?branch=pr-en-us-2769) |
[msteams-platform/task-modules-and-cards/cards/cards-actions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/task-modules-and-cards/cards/cards-actions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions?branch=pr-en-us-2769) |
[msteams-platform/task-modules-and-cards/what-are-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/task-modules-and-cards/what-are-cards.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/what-are-cards?branch=pr-en-us-2769) |

<a id="48316b08-87a038ab"></a>
### [msteams-platform/bots/Universal-bot-action-model/Overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/bots/Universal-bot-action-model/Overview.md)
 - **Line 36, Column 3**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#contextual-views-or-role-based-views' in 'bots/Universal-bot-action-model/Overview.md'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C18%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202102181534332246-2769%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=aORoJFG%2FhBSXGzEOJAEZl9R2QUcrqR4ZJPVL2brhurU%3D&st=2021-02-18T15%3A30%3A07Z&se=2021-03-21T15%3A35%3A07Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-18 15:36 UTC, opbld32 commented
Docs Build status updates of commit _[aca0056](https://github.com/MicrosoftDocs/msteams-docs/commits/aca00562fd8338dbcf3fb94a3010aebfb5f15900)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/new-universal-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/new-universal-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/sequentialworkflow.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/sequentialworkflow.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/universal-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/universal-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/bots/Universal-bot-action-model/Overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/bots/Universal-bot-action-model/Overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/bots/Universal-bot-action-model/Work-with-universal-bot-action-model.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/bots/Universal-bot-action-model/Work-with-universal-bot-action-model.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/work-with-universal-bot-action-model?branch=pr-en-us-2769) |
[msteams-platform/task-modules-and-cards/cards/cards-actions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/task-modules-and-cards/cards/cards-actions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions?branch=pr-en-us-2769) |
[msteams-platform/task-modules-and-cards/what-are-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/task-modules-and-cards/what-are-cards.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/what-are-cards?branch=pr-en-us-2769) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C18%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202102181536232107-2769%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Fn6ToU%2Btu%2B%2FCT2396Gqkg5smrj7nZMs5kfyvmg4z4FA%3D&st=2021-02-18T15%3A31%3A55Z&se=2021-03-21T15%3A36%3A55Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-18 15:39 UTC, opbld33 commented
Docs Build status updates of commit _[e90274d](https://github.com/MicrosoftDocs/msteams-docs/commits/e90274de2d56e2d556361fb0a1a576f364d5188a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/new-universal-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/new-universal-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/sequentialworkflow.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/sequentialworkflow.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/universal-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/universal-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/bots/Universal-bot-action-model/Overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/bots/Universal-bot-action-model/Overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/bots/Universal-bot-action-model/Work-with-universal-bot-action-model.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/bots/Universal-bot-action-model/Work-with-universal-bot-action-model.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/work-with-universal-bot-action-model?branch=pr-en-us-2769) |
[msteams-platform/task-modules-and-cards/cards/cards-actions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/task-modules-and-cards/cards/cards-actions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions?branch=pr-en-us-2769) |
[msteams-platform/task-modules-and-cards/what-are-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/task-modules-and-cards/what-are-cards.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/what-are-cards?branch=pr-en-us-2769) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C18%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202102181538520646-2769%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=2BzAclh30A0EaWz3iCBBp2bDBKBItbVWWZN0yg%2B%2BylU%3D&st=2021-02-18T15%3A34%3A25Z&se=2021-03-21T15%3A39%3A25Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-24 13:35 UTC, sowrabh-msft requested changes

2021-02-24 13:35 UTC, sowrabh-msft commented on msteams-platform/bots/Universal-bot-action-model/Work-with-universal-bot-action-model.md
> +If you set the card version to less than 1.4 and use either or both, `refresh` property and the `Action.Execute` command the following happens:
Let us use `action` instead of `command` everywhere

2021-02-25 05:59 UTC, v-rodriguezd commented on msteams-platform/bots/Universal-bot-action-model/Overview.md
> +With sequential workflow, any user part of a chat or channel can take action on their specific adaptive card. This workflow allows the user to take action or respond to cards without modifying the ca
Could you please elaborate on this comment. Should I rephrase the statements.

2021-03-03 12:36 UTC, opbld32 commented
Docs Build status updates of commit _[652b7e2](https://github.com/MicrosoftDocs/msteams-docs/commits/652b7e2ffd6d2728784b4eea52345c512f716bdc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/new-universal-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/new-universal-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/sequentialworkflow.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/sequentialworkflow.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/universal-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/universal-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/bots/Universal-bot-action-model/Overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/bots/Universal-bot-action-model/Overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/bots/Universal-bot-action-model/Work-with-universal-bot-action-model.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/bots/Universal-bot-action-model/Work-with-universal-bot-action-model.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/work-with-universal-bot-action-model?branch=pr-en-us-2769) |
[msteams-platform/task-modules-and-cards/cards/cards-actions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/task-modules-and-cards/cards/cards-actions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions?branch=pr-en-us-2769) |
[msteams-platform/task-modules-and-cards/what-are-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/task-modules-and-cards/what-are-cards.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/what-are-cards?branch=pr-en-us-2769) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C3%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202103031235366919-2769%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=gsbV3xFoIro4ZxX5l2X0uw9wpaEu9W0kVsBCcXVyQmg%3D&st=2021-03-03T12%3A31%3A12Z&se=2021-04-03T12%3A36%3A12Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-04 12:02 UTC, opbld31 commented
Docs Build status updates of commit _[f9610ba](https://github.com/MicrosoftDocs/msteams-docs/commits/f9610bab21fe53ea1608f87847a4387845f58a51)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/new-universal-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/new-universal-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/sequentialworkflow.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/sequentialworkflow.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/universal-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/universal-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/bots/Universal-bot-action-model/Overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/bots/Universal-bot-action-model/Overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/bots/Universal-bot-action-model/Work-with-universal-bot-action-model.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/bots/Universal-bot-action-model/Work-with-universal-bot-action-model.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/work-with-universal-bot-action-model?branch=pr-en-us-2769) |
[msteams-platform/task-modules-and-cards/cards/cards-actions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/task-modules-and-cards/cards/cards-actions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions?branch=pr-en-us-2769) |
[msteams-platform/task-modules-and-cards/what-are-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/task-modules-and-cards/what-are-cards.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/what-are-cards?branch=pr-en-us-2769) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C4%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202103041201373854-2769%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=7F1e7UGHOxDWTSnPJahO1DZ4JtUnTS76bdU%2B8QxsxMY%3D&st=2021-03-04T11%3A57%3A21Z&se=2021-04-04T12%3A02%3A21Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-07 05:20 UTC, opbld33 commented
Docs Build status updates of commit _[4413554](https://github.com/MicrosoftDocs/msteams-docs/commits/441355481532110d0fe7577fcc6d0324c6a97034)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/TOC.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) | [Details](#user-content-0d1dee3d-3ac690be)
[msteams-platform/assets/images/bots/contextual-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/new-universal-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/new-universal-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/sequentialworkflow.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/sequentialworkflow.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/universal-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/universal-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/bots/Universal-bot-action-model/Overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/bots/Universal-bot-action-model/Overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/bots/Universal-bot-action-model/Work-with-universal-bot-action-model.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/bots/Universal-bot-action-model/Work-with-universal-bot-action-model.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/work-with-universal-bot-action-model?branch=pr-en-us-2769) |
[msteams-platform/task-modules-and-cards/cards/cards-actions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/task-modules-and-cards/cards/cards-actions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions?branch=pr-en-us-2769) |
[msteams-platform/task-modules-and-cards/what-are-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/task-modules-and-cards/what-are-cards.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/what-are-cards?branch=pr-en-us-2769) |

<a id="0d1dee3d-3ac690be"></a>
### [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/TOC.yml)
 - **Line 34, Column 11**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'tutorials/UpgradeTeamsUsingYeoman.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C7%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202103070519373387-2769%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=RMNVMmqrSALKgWsbyZgf4cb1Jdu3FjaqfjvoxgJgtMs%3D&st=2021-03-07T05%3A15%3A23Z&se=2021-04-07T05%3A20%3A23Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-08 07:01 UTC, opbld32 commented
Docs Build status updates of commit _[102a05b](https://github.com/MicrosoftDocs/msteams-docs/commits/102a05b38f8341f36c9af376b58c1e95da95157b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/TOC.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) | [Details](#user-content-0d1dee3d-9390ea7b)
[msteams-platform/bots/Universal-bot-action-model/Overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/bots/Universal-bot-action-model/Overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) | [Details](#user-content-48316b08-9390ea7b)
[msteams-platform/assets/images/bots/Cateringbotstates.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Cateringbotstates.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Newuniversalactionmodel.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Newuniversalactionmodel.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Rolebasedviews.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Rolebasedviews.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/TeamsandOutlook.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/TeamsandOutlook.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/contextual-views.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/contextual-views2.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/new-universal-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/new-universal-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/new-universal-action-model.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/sequentialworkflow.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/sequentialworkflow.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/sequentialworkflow.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/sequentialworkflowsupport.gif](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/sequentialworkflowsupport.gif) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/sequentialworkflowsupport.gif?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/universal-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/universal-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/bots/Universal-bot-action-model/Work-with-universal-bot-action-model.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/bots/Universal-bot-action-model/Work-with-universal-bot-action-model.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/work-with-universal-bot-action-model?branch=pr-en-us-2769) |
[msteams-platform/task-modules-and-cards/cards/cards-actions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/task-modules-and-cards/cards/cards-actions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions?branch=pr-en-us-2769) |
[msteams-platform/task-modules-and-cards/what-are-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/task-modules-and-cards/what-are-cards.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/what-are-cards?branch=pr-en-us-2769) |

<a id="0d1dee3d-9390ea7b"></a>
### [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/TOC.yml)
 - **Line 34, Column 11**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'tutorials/UpgradeTeamsUsingYeoman.md'.`````

<a id="48316b08-9390ea7b"></a>
### [msteams-platform/bots/Universal-bot-action-model/Overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/bots/Universal-bot-action-model/Overview.md)
 - **Line 51, Column 1**: **[Warning-duplicate-alt-text]** `````Alt text 'Sequential workflow' is duplicated. Within an article, alt text must be unique.`````
 - **Line 53, Column 1**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '~/assets/images/bots/sequentialworkflowsupport.png'.`````
 - **Line 53, Column 1**: **[Warning-duplicate-alt-text]** `````Alt text 'Sequential workflow' is duplicated. Within an article, alt text must be unique.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C8%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5C [...]

2021-03-08 07:13 UTC, opbld31 commented
Docs Build status updates of commit _[a11b6f6](https://github.com/MicrosoftDocs/msteams-docs/commits/a11b6f629fa3522266d0a7883f3f7832ab9ce821)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/TOC.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) | [Details](#user-content-0d1dee3d-6c2138e5)
[msteams-platform/assets/images/bots/Cateringbotstates.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Cateringbotstates.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Newuniversalactionmodel.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Newuniversalactionmodel.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Rolebasedviews.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Rolebasedviews.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/TeamsandOutlook.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/TeamsandOutlook.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/contextual-views.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/contextual-views2.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/new-universal-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/new-universal-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/new-universal-action-model.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/sequentialworkflow.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/sequentialworkflow.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/sequentialworkflow.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/sequentialworkflowsupport.gif](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/sequentialworkflowsupport.gif) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/universal-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/universal-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/bots/Universal-bot-action-model/Overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/bots/Universal-bot-action-model/Overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/bots/Universal-bot-action-model/Work-with-universal-bot-action-model.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/bots/Universal-bot-action-model/Work-with-universal-bot-action-model.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/work-with-universal-bot-action-model?branch=pr-en-us-2769) |
[msteams-platform/task-modules-and-cards/cards/cards-actions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/task-modules-and-cards/cards/cards-actions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions?branch=pr-en-us-2769) |
[msteams-platform/task-modules-and-cards/what-are-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/task-modules-and-cards/what-are-cards.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/what-are-cards?branch=pr-en-us-2769) |

<a id="0d1dee3d-6c2138e5"></a>
### [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/TOC.yml)
 - **Line 34, Column 11**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'tutorials/UpgradeTeamsUsingYeoman.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C8%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202103080712463795-2769%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=aXJdu3zbK9IDXKf8uKDcDQ38O5zCsf8dopltA2KE9hQ%3D&st=2021-03-08T07%3A08%3A22Z&se=2021-04-08T07%3A13%3A22Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or war [...]

2021-03-08 07:20 UTC, opbld33 commented
Docs Build status updates of commit _[092e11e](https://github.com/MicrosoftDocs/msteams-docs/commits/092e11e91d3072e6d1e58bafd3fde095fc523e8a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/TOC.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) | [Details](#user-content-0d1dee3d-d31d1470)
[msteams-platform/assets/images/bots/Cateringbotstates.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Cateringbotstates.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Newuniversalactionmodel.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Newuniversalactionmodel.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Rolebasedviews.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Rolebasedviews.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/TeamsandOutlook.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/TeamsandOutlook.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/contextual-views.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/contextual-views2.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/new-universal-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/new-universal-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/new-universal-action-model.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/sequentialworkflow.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/sequentialworkflow.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/sequentialworkflow.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/sequentialworkflowsupport.gif](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/sequentialworkflowsupport.gif) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/universal-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/universal-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/bots/Universal-bot-action-model/Overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/bots/Universal-bot-action-model/Overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/bots/Universal-bot-action-model/Work-with-universal-bot-action-model.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/bots/Universal-bot-action-model/Work-with-universal-bot-action-model.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/work-with-universal-bot-action-model?branch=pr-en-us-2769) |
[msteams-platform/task-modules-and-cards/cards/cards-actions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/task-modules-and-cards/cards/cards-actions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions?branch=pr-en-us-2769) |
[msteams-platform/task-modules-and-cards/what-are-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/task-modules-and-cards/what-are-cards.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/what-are-cards?branch=pr-en-us-2769) |

<a id="0d1dee3d-d31d1470"></a>
### [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/TOC.yml)
 - **Line 34, Column 11**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'tutorials/UpgradeTeamsUsingYeoman.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C8%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202103080719522489-2769%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=L%2BPPbiTTzV2HgVMRLLZRffZOuDV4z8X2yW6lHHD6Dzk%3D&st=2021-03-08T07%3A15%3A28Z&se=2021-04-08T07%3A20%3A28Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or w [...]

2021-03-08 07:26 UTC, opbld33 commented
Docs Build status updates of commit _[0ed1ebb](https://github.com/MicrosoftDocs/msteams-docs/commits/0ed1ebbfe6c3392569ad74cb977e207d6179bbdc)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/TOC.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) | [Details](#user-content-0d1dee3d-b472dcb3)
[msteams-platform/assets/images/bots/Cateringbotstates.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Cateringbotstates.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Newuniversalactionmodel.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Newuniversalactionmodel.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Rolebasedviews.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Rolebasedviews.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/TeamsandOutlook.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/TeamsandOutlook.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/contextual-views.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/contextual-views2.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/new-universal-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/new-universal-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/new-universal-action-model.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/sequentialworkflow.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/sequentialworkflow.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/sequentialworkflow.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/sequentialworkflowsupport.gif](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/sequentialworkflowsupport.gif) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/universal-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/universal-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/bots/Universal-bot-action-model/Overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/bots/Universal-bot-action-model/Overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/bots/Universal-bot-action-model/Work-with-universal-bot-action-model.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/bots/Universal-bot-action-model/Work-with-universal-bot-action-model.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/work-with-universal-bot-action-model?branch=pr-en-us-2769) |
[msteams-platform/task-modules-and-cards/cards/cards-actions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/task-modules-and-cards/cards/cards-actions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions?branch=pr-en-us-2769) |
[msteams-platform/task-modules-and-cards/what-are-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/task-modules-and-cards/what-are-cards.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/what-are-cards?branch=pr-en-us-2769) |

<a id="0d1dee3d-b472dcb3"></a>
### [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/TOC.yml)
 - **Line 34, Column 11**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'tutorials/UpgradeTeamsUsingYeoman.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C8%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202103080725467138-2769%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=dIefN8dwZ26eYFAHYtLdLECTKXTpFkINjWGPmpRuvnw%3D&st=2021-03-08T07%3A21%3A22Z&se=2021-04-08T07%3A26%3A22Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or war [...]

2021-03-08 07:39 UTC, opbld32 commented
Docs Build status updates of commit _[bbc5e9b](https://github.com/MicrosoftDocs/msteams-docs/commits/bbc5e9bd476a877a5820caa5552b2859b625f6d2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/TOC.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) | [Details](#user-content-0d1dee3d-2a7dba53)
[msteams-platform/assets/images/bots/Cateringbotstates.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Cateringbotstates.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Newuniversalactionmodel.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Newuniversalactionmodel.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Rolebasedviews.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Rolebasedviews.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/TeamsandOutlook.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/TeamsandOutlook.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/contextual-views.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/contextual-views2.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/new-universal-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/new-universal-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/new-universal-action-model.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/sequentialworkflow.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/sequentialworkflow.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/sequentialworkflow.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/sequentialworkflowsupport.gif](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/sequentialworkflowsupport.gif) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/universal-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/universal-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/bots/Universal-bot-action-model/Overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/bots/Universal-bot-action-model/Overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/bots/Universal-bot-action-model/Work-with-universal-bot-action-model.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/bots/Universal-bot-action-model/Work-with-universal-bot-action-model.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/work-with-universal-bot-action-model?branch=pr-en-us-2769) |
[msteams-platform/task-modules-and-cards/cards/cards-actions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/task-modules-and-cards/cards/cards-actions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions?branch=pr-en-us-2769) |
[msteams-platform/task-modules-and-cards/what-are-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/task-modules-and-cards/what-are-cards.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/what-are-cards?branch=pr-en-us-2769) |

<a id="0d1dee3d-2a7dba53"></a>
### [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/TOC.yml)
 - **Line 34, Column 11**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'tutorials/UpgradeTeamsUsingYeoman.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C8%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202103080738373434-2769%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=x3VkE67%2FbgD5tEJhK1BSMQ1Y3YDwekg8W%2FZO30Dx%2Fqk%3D&st=2021-03-08T07%3A34%3A18Z&se=2021-04-08T07%3A39%3A18Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors  [...]

2021-03-08 07:41 UTC, opbld32 commented
Docs Build status updates of commit _[f0df95d](https://github.com/MicrosoftDocs/msteams-docs/commits/f0df95d7bffb247ede41813f2f456b95d64afb3f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/TOC.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) | [Details](#user-content-0d1dee3d-895257aa)
[msteams-platform/assets/images/bots/Cateringbotstates.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Cateringbotstates.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Newuniversalactionmodel.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Newuniversalactionmodel.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Rolebasedviews.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Rolebasedviews.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/TeamsandOutlook.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/TeamsandOutlook.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/contextual-views.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/contextual-views2.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/new-universal-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/new-universal-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/new-universal-action-model.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/sequentialworkflow.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/sequentialworkflow.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/sequentialworkflow.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/sequentialworkflowsupport.gif](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/sequentialworkflowsupport.gif) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/universal-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/universal-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/bots/Universal-bot-action-model/Overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/bots/Universal-bot-action-model/Overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/bots/Universal-bot-action-model/Work-with-universal-bot-action-model.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/bots/Universal-bot-action-model/Work-with-universal-bot-action-model.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/work-with-universal-bot-action-model?branch=pr-en-us-2769) |
[msteams-platform/task-modules-and-cards/cards/cards-actions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/task-modules-and-cards/cards/cards-actions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions?branch=pr-en-us-2769) |
[msteams-platform/task-modules-and-cards/what-are-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/task-modules-and-cards/what-are-cards.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/what-are-cards?branch=pr-en-us-2769) |

<a id="0d1dee3d-895257aa"></a>
### [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/TOC.yml)
 - **Line 34, Column 11**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'tutorials/UpgradeTeamsUsingYeoman.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C8%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202103080741141970-2769%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=odc5lQp5HLyA6JVIKE6dBmKrJmymMnygC2jjBtPoa1o%3D&st=2021-03-08T07%3A36%3A52Z&se=2021-04-08T07%3A41%3A52Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or war [...]

2021-03-08 07:44 UTC, opbld30 commented
Docs Build status updates of commit _[1f9d5b0](https://github.com/MicrosoftDocs/msteams-docs/commits/1f9d5b03641336521a09272a19637b284f1bab70)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/TOC.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) | [Details](#user-content-0d1dee3d-a17679eb)
[msteams-platform/assets/images/bots/Cateringbotstates.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Cateringbotstates.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Newuniversalactionmodel.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Newuniversalactionmodel.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Rolebasedviews.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Rolebasedviews.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/TeamsandOutlook.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/TeamsandOutlook.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/contextual-views.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/contextual-views2.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/new-universal-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/new-universal-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/new-universal-action-model.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/sequentialworkflow.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/sequentialworkflow.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/sequentialworkflow.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/sequentialworkflowsupport.gif](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/sequentialworkflowsupport.gif) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/universal-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/universal-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/bots/Universal-bot-action-model/Overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/bots/Universal-bot-action-model/Overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/bots/Universal-bot-action-model/Work-with-universal-bot-action-model.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/bots/Universal-bot-action-model/Work-with-universal-bot-action-model.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/work-with-universal-bot-action-model?branch=pr-en-us-2769) |
[msteams-platform/task-modules-and-cards/cards/cards-actions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/task-modules-and-cards/cards/cards-actions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions?branch=pr-en-us-2769) |
[msteams-platform/task-modules-and-cards/what-are-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/task-modules-and-cards/what-are-cards.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/what-are-cards?branch=pr-en-us-2769) |

<a id="0d1dee3d-a17679eb"></a>
### [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/TOC.yml)
 - **Line 34, Column 11**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'tutorials/UpgradeTeamsUsingYeoman.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C8%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202103080744111273-2769%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Opp%2FEMrCeTDnfL7c%2BlETPUQNwFQueLrI4GD6yVTCJZQ%3D&st=2021-03-08T07%3A39%3A52Z&se=2021-04-08T07%3A44%3A52Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or [...]

2021-03-08 07:46 UTC, opbld31 commented
Docs Build status updates of commit _[268e184](https://github.com/MicrosoftDocs/msteams-docs/commits/268e1844520b503b609011c92aaf938a60914253)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/TOC.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) | [Details](#user-content-0d1dee3d-9ba2a4ba)
[msteams-platform/assets/images/bots/Cateringbotstates.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Cateringbotstates.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Newuniversalactionmodel.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Newuniversalactionmodel.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Rolebasedviews.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Rolebasedviews.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/TeamsandOutlook.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/TeamsandOutlook.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/contextual-views.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/contextual-views2.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/new-universal-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/new-universal-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/new-universal-action-model.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/sequentialworkflow.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/sequentialworkflow.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/sequentialworkflow.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/sequentialworkflowsupport.gif](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/sequentialworkflowsupport.gif) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/universal-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/universal-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/bots/Universal-bot-action-model/Overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/bots/Universal-bot-action-model/Overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/bots/Universal-bot-action-model/Work-with-universal-bot-action-model.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/bots/Universal-bot-action-model/Work-with-universal-bot-action-model.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/work-with-universal-bot-action-model?branch=pr-en-us-2769) |
[msteams-platform/task-modules-and-cards/cards/cards-actions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/task-modules-and-cards/cards/cards-actions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions?branch=pr-en-us-2769) |
[msteams-platform/task-modules-and-cards/what-are-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/task-modules-and-cards/what-are-cards.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/what-are-cards?branch=pr-en-us-2769) |

<a id="0d1dee3d-9ba2a4ba"></a>
### [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/TOC.yml)
 - **Line 34, Column 11**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'tutorials/UpgradeTeamsUsingYeoman.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C8%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202103080746077961-2769%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=9KiA1Zx2pbnY99cPC0mUf8EhM2Kr5%2BHRtW%2FX3YnVQHA%3D&st=2021-03-08T07%3A41%3A48Z&se=2021-04-08T07%3A46%3A48Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or [...]

2021-03-08 07:49 UTC, opbld30 commented
Docs Build status updates of commit _[105ab9e](https://github.com/MicrosoftDocs/msteams-docs/commits/105ab9e7131d65b6847e03925c6e68309c95d8a7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/TOC.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) | [Details](#user-content-0d1dee3d-1a8991d8)
[msteams-platform/assets/images/bots/Cateringbotstates.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Cateringbotstates.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Newuniversalactionmodel.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Newuniversalactionmodel.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Rolebasedviews.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Rolebasedviews.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/TeamsandOutlook.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/TeamsandOutlook.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/contextual-views.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/contextual-views2.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/new-universal-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/new-universal-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/new-universal-action-model.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/sequentialworkflow.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/sequentialworkflow.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/sequentialworkflow.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/sequentialworkflowsupport.gif](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/sequentialworkflowsupport.gif) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/universal-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/universal-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/bots/Universal-bot-action-model/Overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/bots/Universal-bot-action-model/Overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/overview?branch=pr-en-us-2769) |
[msteams-platform/bots/Universal-bot-action-model/Work-with-universal-bot-action-model.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/bots/Universal-bot-action-model/Work-with-universal-bot-action-model.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/universal-bot-action-model/work-with-universal-bot-action-model?branch=pr-en-us-2769) |
[msteams-platform/task-modules-and-cards/cards/cards-actions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/task-modules-and-cards/cards/cards-actions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions?branch=pr-en-us-2769) |
[msteams-platform/task-modules-and-cards/what-are-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/task-modules-and-cards/what-are-cards.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/what-are-cards?branch=pr-en-us-2769) |

<a id="0d1dee3d-1a8991d8"></a>
### [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/TOC.yml)
 - **Line 34, Column 11**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'tutorials/UpgradeTeamsUsingYeoman.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C8%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202103080748304064-2769%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=4MOsHZ6rb56HAqcgMFfimJs%2F6vIlEZj%2ByeaBvC4Rukg%3D&st=2021-03-08T07%3A44%3A15Z&se=2021-04-08T07%3A49%3A15Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or [...]

2021-03-16 04:34 UTC, ojasvichoudhary commented on msteams-platform/bots/Universal-bot-action-model/Overview.md
> +# Universal bot action model
Universal Actions for adaptive cards

2021-03-16 07:06 UTC, opbld33 commented
Docs Build status updates of commit _[b365aaa](https://github.com/MicrosoftDocs/msteams-docs/commits/b365aaa15101b40877eab30cb8b48d39e5d36e46)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/TOC.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions?branch=pr-en-us-2769) | [Details](#user-content-f679b5d0ee59eb212f56a224ff613c91-d18b177e)
[msteams-platform/assets/images/bots/Cateringbotstates.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Cateringbotstates.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Newuniversalactionmodel.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Newuniversalactionmodel.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Rolebasedviews.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Rolebasedviews.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/TeamsandOutlook.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/TeamsandOutlook.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/contextual-views.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/contextual-views2.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/inconsistent-action-model-lifecycle.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/new-universal-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/new-universal-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/new-universal-action-model.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/sequentialworkflow.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/sequentialworkflow.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/sequentialworkflow.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/sequentialworkflowsupport.gif](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/sequentialworkflowsupport.gif) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/universal-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/universal-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/universal-action-model-lifecycle.png?branch=pr-en-us-2769) |
[msteams-platform/task-modules-and-cards/cards/Universal-actions-for-adaptive-cards/Overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/task-modules-and-cards/cards/Universal-actions-for-adaptive-cards/Overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/task-modules-and-cards/cards/Universal-actions-for-adaptive-cards/Work-with-universal-actions-for-adaptive-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/task-modules-and-cards/cards/Universal-actions-for-adaptive-cards/Work-with-universal-actions-for-adaptive-cards.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/work-with-universal-actions-for-adaptive-cards?branch=pr-en-us-2769) |
[msteams-platform/task-modules-and-cards/cards/cards-actions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/task-modules-and-cards/cards/cards-actions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions?branch=pr-en-us-2769) |
[msteams-platform/task-modules-and-cards/what-are-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/task-modules-and-cards/what-are-cards.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/what-are-cards?branch=pr-en-us-2769) |

<a id="f679b5d0ee59eb212f56a224ff613c91-d18b177e"></a>
### [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/TOC.yml)
 - **Line 300, Column 15**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'bots/Universal-actions-for-adaptive-cards/overview.md'.`````
 - **Line 302, Column 15**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'bots/Universal-actions-for-adaptive-cards/Work-with-universal-actions-for-adaptive-cards.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C16%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest [...]

2021-03-16 07:09 UTC, opbld33 commented
Docs Build status updates of commit _[9d0cb7e](https://github.com/MicrosoftDocs/msteams-docs/commits/9d0cb7ee2232132332ab7b3851d9303254c54e2a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Cateringbotstates.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Cateringbotstates.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Newuniversalactionmodel.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Newuniversalactionmodel.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Rolebasedviews.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Rolebasedviews.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/TeamsandOutlook.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/TeamsandOutlook.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/contextual-views.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/contextual-views2.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/inconsistent-action-model-lifecycle.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/new-universal-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/new-universal-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/new-universal-action-model.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/sequentialworkflow.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/sequentialworkflow.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/sequentialworkflow.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/sequentialworkflowsupport.gif](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/sequentialworkflowsupport.gif) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/universal-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/universal-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/universal-action-model-lifecycle.png?branch=pr-en-us-2769) |
[msteams-platform/task-modules-and-cards/cards/Universal-actions-for-adaptive-cards/Overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/task-modules-and-cards/cards/Universal-actions-for-adaptive-cards/Overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/task-modules-and-cards/cards/Universal-actions-for-adaptive-cards/Work-with-universal-actions-for-adaptive-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/task-modules-and-cards/cards/Universal-actions-for-adaptive-cards/Work-with-universal-actions-for-adaptive-cards.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/work-with-universal-actions-for-adaptive-cards?branch=pr-en-us-2769) |
[msteams-platform/task-modules-and-cards/cards/cards-actions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/task-modules-and-cards/cards/cards-actions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions?branch=pr-en-us-2769) |
[msteams-platform/task-modules-and-cards/what-are-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/task-modules-and-cards/what-are-cards.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/what-are-cards?branch=pr-en-us-2769) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C16%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202103160708493028-2769%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=JsuO9vjow7dR2FBcU7ciOVkXwOT65D1EbSzQvE3CfgA%3D&st=2021-03-16T07%3A04%3A26Z&se=2021-04-16T07%3A09%3A26Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.sk [...]

2021-03-29 20:29 UTC, ojasvichoudhary submitted a review, later dismissed

2021-04-27 14:35 UTC, opbld31 commented
Docs Build status updates of commit _[e2cc8c6](https://github.com/MicrosoftDocs/msteams-docs/commits/e2cc8c60a8d88723f60433236c039b17f642c56f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions?branch=pr-en-us-2769) |
[msteams-platform/assets/images/.DS_Store](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/.DS_Store) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/adaptive-cards/current-teams-outlook-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/current-teams-outlook-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-catering-bot.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-catering-bot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-incident-management.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-incident-management.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-teams-outlook.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-teams-outlook.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up-to-date-views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up-to-date-views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-3.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-3.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up-to-date-views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Cateringbotstates.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Cateringbotstates.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/cateringbotstates.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Newuniversalactionmodel.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Newuniversalactionmodel.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/newuniversalactionmodel.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Rolebasedviews.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Rolebasedviews.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/rolebasedviews.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/TeamsandOutlook.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/TeamsandOutlook.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/teamsandoutlook.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/contextual-views.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/contextual-views2.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/inconsistent-action-model-lifecycle.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/inconsistent-action-model.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/new-universal-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/new-universal-action-model.png) | :white_check_mark:Succeeded | [Vie [...]

2021-04-28 05:59 UTC, opbld30 commented
Docs Build status updates of commit _[66ac900](https://github.com/MicrosoftDocs/msteams-docs/commits/66ac900b30e3bc10899b4ddc9b1490c93c75a9aa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions?branch=pr-en-us-2769) |
[msteams-platform/assets/images/.DS_Store](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/.DS_Store) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/adaptive-cards/current-teams-outlook-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/current-teams-outlook-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-catering-bot.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-catering-bot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-incident-management.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-incident-management.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-teams-outlook.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-teams-outlook.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up-to-date-views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up-to-date-views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-3.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-3.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up-to-date-views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Cateringbotstates.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Cateringbotstates.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/cateringbotstates.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Newuniversalactionmodel.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Newuniversalactionmodel.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/newuniversalactionmodel.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Rolebasedviews.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Rolebasedviews.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/rolebasedviews.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/TeamsandOutlook.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/TeamsandOutlook.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/teamsandoutlook.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/contextual-views.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/contextual-views2.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/inconsistent-action-model-lifecycle.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/inconsistent-action-model.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/new-universal-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/new-universal-action-model.png) | :white_check_mark:Succeeded | [Vie [...]

2021-04-28 06:05 UTC, opbld30 commented
Docs Build status updates of commit _[510c825](https://github.com/MicrosoftDocs/msteams-docs/commits/510c8252c9db66bcf04a5a97a2fe45ac0ee96bbd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions?branch=pr-en-us-2769) |
[msteams-platform/assets/images/.DS_Store](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/.DS_Store) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/adaptive-cards/current-teams-outlook-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/current-teams-outlook-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-catering-bot.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-catering-bot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-incident-management.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-incident-management.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-teams-outlook.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-teams-outlook.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up-to-date-views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up-to-date-views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-3.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-3.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up-to-date-views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Cateringbotstates.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Cateringbotstates.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/cateringbotstates.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Newuniversalactionmodel.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Newuniversalactionmodel.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/newuniversalactionmodel.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Rolebasedviews.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Rolebasedviews.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/rolebasedviews.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/TeamsandOutlook.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/TeamsandOutlook.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/teamsandoutlook.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/contextual-views.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/contextual-views2.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/inconsistent-action-model-lifecycle.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/inconsistent-action-model.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/new-universal-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/new-universal-action-model.png) | :white_check_mark:Succeeded | [Vie [...]

2021-04-28 06:12 UTC, opbld32 commented
Docs Build status updates of commit _[ae6e57b](https://github.com/MicrosoftDocs/msteams-docs/commits/ae6e57bff3f7d49108a00289ba594edb61ea36c3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions?branch=pr-en-us-2769) |
[msteams-platform/assets/images/.DS_Store](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/.DS_Store) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/adaptive-cards/current-teams-outlook-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/current-teams-outlook-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-catering-bot.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-catering-bot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-incident-management.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-incident-management.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-teams-outlook.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-teams-outlook.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up-to-date-views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up-to-date-views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-3.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-3.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up-to-date-views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Cateringbotstates.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Cateringbotstates.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/cateringbotstates.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Newuniversalactionmodel.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Newuniversalactionmodel.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/newuniversalactionmodel.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Rolebasedviews.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Rolebasedviews.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/rolebasedviews.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/TeamsandOutlook.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/TeamsandOutlook.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/teamsandoutlook.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/contextual-views.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/contextual-views2.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/inconsistent-action-model-lifecycle.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/inconsistent-action-model.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/new-universal-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/new-universal-action-model.png) | :white_check_mark:Succeeded | [Vie [...]

2021-04-28 08:31 UTC, opbld33 commented
Docs Build status updates of commit _[fd886ad](https://github.com/MicrosoftDocs/msteams-docs/commits/fd886ade2460f9fb44efb1fc0b81b8f8643d675a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions?branch=pr-en-us-2769) |
[msteams-platform/assets/images/.DS_Store](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/.DS_Store) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/adaptive-cards/current-teams-outlook-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/current-teams-outlook-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-catering-bot.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-catering-bot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-incident-management.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-incident-management.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-teams-outlook.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-teams-outlook.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up-to-date-views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up-to-date-views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-3.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-3.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up-to-date-views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Cateringbotstates.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Cateringbotstates.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/cateringbotstates.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Newuniversalactionmodel.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Newuniversalactionmodel.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/newuniversalactionmodel.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Rolebasedviews.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Rolebasedviews.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/rolebasedviews.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/TeamsandOutlook.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/TeamsandOutlook.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/teamsandoutlook.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/contextual-views.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/contextual-views2.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/inconsistent-action-model-lifecycle.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/inconsistent-action-model.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/new-universal-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/new-universal-action-model.png) | :white_check_mark:Succeeded | [Vie [...]

2021-04-28 17:19 UTC, opbld30 commented
Docs Build status updates of commit _[3c4dbfb](https://github.com/MicrosoftDocs/msteams-docs/commits/3c4dbfbec3edddb6e57ad2abfb98c11d0c220327)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/task-modules-and-cards/cards/Universal-actions-for-adaptive-cards/Overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/task-modules-and-cards/cards/Universal-actions-for-adaptive-cards/Overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) | [Details](#user-content-5a9ad89638b6928a74cc6a9b81d90583-0be185f1)
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions?branch=pr-en-us-2769) |
[msteams-platform/assets/images/.DS_Store](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/.DS_Store) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/adaptive-cards/current-teams-outlook-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/current-teams-outlook-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-catering-bot.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-catering-bot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-incident-management.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-incident-management.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-teams-outlook.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-teams-outlook.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up-to-date-views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up-to-date-views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-3.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-3.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up-to-date-views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Cateringbotstates.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Cateringbotstates.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/cateringbotstates.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Newuniversalactionmodel.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Newuniversalactionmodel.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/newuniversalactionmodel.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Rolebasedviews.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Rolebasedviews.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/rolebasedviews.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/TeamsandOutlook.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/TeamsandOutlook.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/teamsandoutlook.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/contextual-views.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/contextual-views2.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/inconsistent-action-model-lifecycle.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/b [...]

2021-04-28 17:21 UTC, opbld33 commented
Docs Build status updates of commit _[2f9f631](https://github.com/MicrosoftDocs/msteams-docs/commits/2f9f63154bc8efec171f8bc9a1467022c5304856)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/task-modules-and-cards/cards/Universal-actions-for-adaptive-cards/Overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/task-modules-and-cards/cards/Universal-actions-for-adaptive-cards/Overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) | [Details](#user-content-5a9ad89638b6928a74cc6a9b81d90583-11bcbe02)
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions?branch=pr-en-us-2769) |
[msteams-platform/assets/images/.DS_Store](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/.DS_Store) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/adaptive-cards/current-teams-outlook-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/current-teams-outlook-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-catering-bot.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-catering-bot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-incident-management.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-incident-management.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-teams-outlook.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-teams-outlook.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up-to-date-views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up-to-date-views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-3.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-3.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up-to-date-views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Cateringbotstates.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Cateringbotstates.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/cateringbotstates.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Newuniversalactionmodel.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Newuniversalactionmodel.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/newuniversalactionmodel.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Rolebasedviews.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Rolebasedviews.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/rolebasedviews.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/TeamsandOutlook.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/TeamsandOutlook.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/teamsandoutlook.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/contextual-views.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/contextual-views2.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/inconsistent-action-model-lifecycle.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/b [...]

2021-04-28 17:33 UTC, opbld31 commented
Docs Build status updates of commit _[034cc76](https://github.com/MicrosoftDocs/msteams-docs/commits/034cc763e09941c23e5640712710fe480af3de4e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/task-modules-and-cards/cards/Universal-actions-for-adaptive-cards/Overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/task-modules-and-cards/cards/Universal-actions-for-adaptive-cards/Overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) | [Details](#user-content-5a9ad89638b6928a74cc6a9b81d90583-57624689)
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions?branch=pr-en-us-2769) |
[msteams-platform/assets/images/.DS_Store](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/.DS_Store) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/adaptive-cards/current-teams-outlook-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/current-teams-outlook-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-catering-bot.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-catering-bot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-incident-management.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-incident-management.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-teams-outlook.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-teams-outlook.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up-to-date-views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up-to-date-views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-3.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-3.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up-to-date-views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Cateringbotstates.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Cateringbotstates.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/cateringbotstates.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Newuniversalactionmodel.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Newuniversalactionmodel.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/newuniversalactionmodel.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Rolebasedviews.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Rolebasedviews.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/rolebasedviews.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/TeamsandOutlook.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/TeamsandOutlook.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/teamsandoutlook.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/contextual-views.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/contextual-views2.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/inconsistent-action-model-lifecycle.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/b [...]

2021-04-28 19:11 UTC, opbld32 commented
Docs Build status updates of commit _[63bc2fe](https://github.com/MicrosoftDocs/msteams-docs/commits/63bc2fefaa1ba409994fed632508d7add9e8491b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/task-modules-and-cards/cards/Universal-actions-for-adaptive-cards/Overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/task-modules-and-cards/cards/Universal-actions-for-adaptive-cards/Overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) | [Details](#user-content-5a9ad89638b6928a74cc6a9b81d90583-5e1e6e03)
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions?branch=pr-en-us-2769) |
[msteams-platform/assets/images/.DS_Store](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/.DS_Store) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/adaptive-cards/current-teams-outlook-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/current-teams-outlook-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-catering-bot.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-catering-bot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-incident-management.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-incident-management.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-teams-outlook.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-teams-outlook.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up-to-date-views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up-to-date-views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-3.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-3.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up-to-date-views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Cateringbotstates.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Cateringbotstates.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/cateringbotstates.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Newuniversalactionmodel.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Newuniversalactionmodel.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/newuniversalactionmodel.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Rolebasedviews.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Rolebasedviews.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/rolebasedviews.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/TeamsandOutlook.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/TeamsandOutlook.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/teamsandoutlook.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/contextual-views.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/contextual-views2.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/inconsistent-action-model-lifecycle.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/b [...]

2021-04-28 19:23 UTC, opbld30 commented
Docs Build status updates of commit _[03d6c37](https://github.com/MicrosoftDocs/msteams-docs/commits/03d6c37e14b367b4c7065a41599dc1760d9815f8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/task-modules-and-cards/cards/Universal-actions-for-adaptive-cards/Overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/task-modules-and-cards/cards/Universal-actions-for-adaptive-cards/Overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) | [Details](#user-content-5a9ad89638b6928a74cc6a9b81d90583-49afa31a)
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions?branch=pr-en-us-2769) |
[msteams-platform/assets/images/.DS_Store](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/.DS_Store) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/adaptive-cards/current-teams-outlook-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/current-teams-outlook-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-catering-bot.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-catering-bot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-incident-management.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-incident-management.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-teams-outlook.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-teams-outlook.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up-to-date-views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up-to-date-views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-3.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-3.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up-to-date-views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Cateringbotstates.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Cateringbotstates.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/cateringbotstates.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Newuniversalactionmodel.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Newuniversalactionmodel.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/newuniversalactionmodel.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Rolebasedviews.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Rolebasedviews.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/rolebasedviews.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/TeamsandOutlook.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/TeamsandOutlook.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/teamsandoutlook.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/contextual-views.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/contextual-views2.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/inconsistent-action-model-lifecycle.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/b [...]

2021-04-28 19:34 UTC, opbld33 commented
Docs Build status updates of commit _[d1742fb](https://github.com/MicrosoftDocs/msteams-docs/commits/d1742fb965a3ace13e9c465044f2defc28f59f60)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/TOC.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions?branch=pr-en-us-2769) | [Details](#user-content-f679b5d0ee59eb212f56a224ff613c91-e9c712d6)
[msteams-platform/task-modules-and-cards/cards/Universal-actions-for-adaptive-cards/Overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/task-modules-and-cards/cards/Universal-actions-for-adaptive-cards/Overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) | [Details](#user-content-5a9ad89638b6928a74cc6a9b81d90583-e9c712d6)
[msteams-platform/task-modules-and-cards/cards/Universal-actions-for-adaptive-cards/Up-To-Date-Views.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/task-modules-and-cards/cards/Universal-actions-for-adaptive-cards/Up-To-Date-Views.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up-to-date-views?branch=pr-en-us-2769) | [Details](#user-content-0bee81f13674ef9d929fad6d66d95c2b-e9c712d6)
[msteams-platform/assets/images/.DS_Store](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/.DS_Store) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/adaptive-cards/current-teams-outlook-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/current-teams-outlook-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-catering-bot.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-catering-bot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-incident-management.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-incident-management.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-teams-outlook.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-teams-outlook.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up-to-date-views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up-to-date-views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-3.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-3.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up-to-date-views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Cateringbotstates.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Cateringbotstates.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/cateringbotstates.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Newuniversalactionmodel.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Newuniversalactionmodel.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/newuniversalactionmodel.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Rolebasedviews.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Rolebasedviews.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/rolebasedviews.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/TeamsandOutlook.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/TeamsandOutlook.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/teamsandoutlook.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/contextual-views.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams [...]

2021-04-28 20:14 UTC, opbld30 commented
Docs Build status updates of commit _[ef863c2](https://github.com/MicrosoftDocs/msteams-docs/commits/ef863c29bb3a2ea1d62130727efe504706af874e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/TOC.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions?branch=pr-en-us-2769) | [Details](#user-content-f679b5d0ee59eb212f56a224ff613c91-4009a42e)
[msteams-platform/task-modules-and-cards/cards/Universal-actions-for-adaptive-cards/Overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/task-modules-and-cards/cards/Universal-actions-for-adaptive-cards/Overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) | [Details](#user-content-5a9ad89638b6928a74cc6a9b81d90583-4009a42e)
[msteams-platform/task-modules-and-cards/cards/Universal-actions-for-adaptive-cards/Up To Date Views.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/task-modules-and-cards/cards/Universal-actions-for-adaptive-cards/Up%20To%20Date%20Views.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up%20to%20date%20views?branch=pr-en-us-2769) | [Details](#user-content-a3d2332470967c8a23923be8a1360149-4009a42e)
[msteams-platform/task-modules-and-cards/cards/Universal-actions-for-adaptive-cards/User Specific Views.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/task-modules-and-cards/cards/Universal-actions-for-adaptive-cards/User%20Specific%20Views.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/user%20specific%20views?branch=pr-en-us-2769) | [Details](#user-content-7ad7e95ffe3d0a94b7150a2a97b77c34-4009a42e)
[msteams-platform/assets/images/.DS_Store](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/.DS_Store) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/adaptive-cards/current-teams-outlook-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/current-teams-outlook-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-catering-bot.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-catering-bot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-incident-management.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-incident-management.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-teams-outlook.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-teams-outlook.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up%20to%20date%20views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up%20to%20date%20views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-3.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-3.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up%20to%20date%20views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Cateringbotstates.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Cateringbotstates.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/cateringbotstates.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Newuniversalactionmodel.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Newuniversalactionmodel.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/newuniversalactionmodel.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Rolebasedviews.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Rolebasedviews.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/rolebasedviews.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/TeamsandOutlook.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/TeamsandOutlook.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/teamsandoutlook.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-v [...]

2021-04-28 20:16 UTC, shiladityasaha submitted a review, later dismissed
I have made some minor changes across pages. Please check and merge those. Approving the PR.

2021-04-29 03:06 UTC, sowrabh-msft commented on msteams-platform/task-modules-and-cards/cards/Universal-actions-for-adaptive-cards/Overview.md
> +For more information, see [sample for User Specific Views](User-Specific-Views.md).
This link seems to be broken. Please check

2021-04-29 03:07 UTC, sowrabh-msft commented on msteams-platform/task-modules-and-cards/cards/Universal-actions-for-adaptive-cards/Overview.md
> +For more information, see [sample for User Specific Views](User-Specific-Views.md).
In fact all user-specific-view.md links are broken

2021-04-29 03:32 UTC, opbld32 commented
Docs Build status updates of commit _[5bcb180](https://github.com/MicrosoftDocs/msteams-docs/commits/5bcb1809c113b6f6430446bfa871cdabad7ade2b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/TOC.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions?branch=pr-en-us-2769) | [Details](#user-content-f679b5d0ee59eb212f56a224ff613c91-37a8dd26)
[msteams-platform/task-modules-and-cards/cards/Universal-actions-for-adaptive-cards/Overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/task-modules-and-cards/cards/Universal-actions-for-adaptive-cards/Overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) | [Details](#user-content-5a9ad89638b6928a74cc6a9b81d90583-37a8dd26)
[msteams-platform/task-modules-and-cards/cards/Universal-actions-for-adaptive-cards/Up To Date Views.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/task-modules-and-cards/cards/Universal-actions-for-adaptive-cards/Up%20To%20Date%20Views.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up%20to%20date%20views?branch=pr-en-us-2769) | [Details](#user-content-a3d2332470967c8a23923be8a1360149-37a8dd26)
[msteams-platform/task-modules-and-cards/cards/Universal-actions-for-adaptive-cards/User Specific Views.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/task-modules-and-cards/cards/Universal-actions-for-adaptive-cards/User%20Specific%20Views.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/user%20specific%20views?branch=pr-en-us-2769) | [Details](#user-content-7ad7e95ffe3d0a94b7150a2a97b77c34-37a8dd26)
[msteams-platform/assets/images/.DS_Store](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/.DS_Store) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/adaptive-cards/current-teams-outlook-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/current-teams-outlook-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-catering-bot.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-catering-bot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-incident-management.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-incident-management.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-teams-outlook.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-teams-outlook.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up%20to%20date%20views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up%20to%20date%20views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-3.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-3.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up%20to%20date%20views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Cateringbotstates.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Cateringbotstates.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/cateringbotstates.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Newuniversalactionmodel.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Newuniversalactionmodel.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/newuniversalactionmodel.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Rolebasedviews.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Rolebasedviews.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/rolebasedviews.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/TeamsandOutlook.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/TeamsandOutlook.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/teamsandoutlook.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-v [...]

2021-04-29 04:55 UTC, opbld30 commented
Docs Build status updates of commit _[2dec76f](https://github.com/MicrosoftDocs/msteams-docs/commits/2dec76f0e4a8fe5fdee99b41775032776ea3a3c7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/TOC.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions?branch=pr-en-us-2769) | [Details](#user-content-f679b5d0ee59eb212f56a224ff613c91-891a1fb2)
[msteams-platform/task-modules-and-cards/cards/Universal-actions-for-adaptive-cards/Overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/task-modules-and-cards/cards/Universal-actions-for-adaptive-cards/Overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) | [Details](#user-content-5a9ad89638b6928a74cc6a9b81d90583-891a1fb2)
[msteams-platform/task-modules-and-cards/cards/Universal-actions-for-adaptive-cards/Up To Date Views.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/task-modules-and-cards/cards/Universal-actions-for-adaptive-cards/Up%20To%20Date%20Views.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up%20to%20date%20views?branch=pr-en-us-2769) | [Details](#user-content-a3d2332470967c8a23923be8a1360149-891a1fb2)
[msteams-platform/task-modules-and-cards/cards/Universal-actions-for-adaptive-cards/User Specific Views.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/task-modules-and-cards/cards/Universal-actions-for-adaptive-cards/User%20Specific%20Views.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/user%20specific%20views?branch=pr-en-us-2769) | [Details](#user-content-7ad7e95ffe3d0a94b7150a2a97b77c34-891a1fb2)
[msteams-platform/assets/images/.DS_Store](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/.DS_Store) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/adaptive-cards/current-teams-outlook-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/current-teams-outlook-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-catering-bot.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-catering-bot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-incident-management.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-incident-management.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-teams-outlook.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-teams-outlook.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up%20to%20date%20views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up%20to%20date%20views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-3.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-3.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up%20to%20date%20views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Cateringbotstates.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Cateringbotstates.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/cateringbotstates.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Newuniversalactionmodel.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Newuniversalactionmodel.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/newuniversalactionmodel.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Rolebasedviews.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Rolebasedviews.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/rolebasedviews.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/TeamsandOutlook.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/TeamsandOutlook.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/teamsandoutlook.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-v [...]

2021-04-29 05:00 UTC, opbld32 commented
Docs Build status updates of commit _[e5b3f8d](https://github.com/MicrosoftDocs/msteams-docs/commits/e5b3f8dd1da8925f46e6295a8c36d26169144ef6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/task-modules-and-cards/cards/Universal-actions-for-adaptive-cards/Overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/task-modules-and-cards/cards/Universal-actions-for-adaptive-cards/Overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) | [Details](#user-content-5a9ad89638b6928a74cc6a9b81d90583-36faae98)
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions?branch=pr-en-us-2769) |
[msteams-platform/assets/images/.DS_Store](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/.DS_Store) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/adaptive-cards/current-teams-outlook-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/current-teams-outlook-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-catering-bot.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-catering-bot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-incident-management.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-incident-management.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-teams-outlook.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-teams-outlook.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up-to-date-views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up-to-date-views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-3.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-3.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up-to-date-views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Cateringbotstates.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Cateringbotstates.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/cateringbotstates.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Newuniversalactionmodel.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Newuniversalactionmodel.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/newuniversalactionmodel.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Rolebasedviews.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Rolebasedviews.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/rolebasedviews.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/TeamsandOutlook.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/TeamsandOutlook.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/teamsandoutlook.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/contextual-views.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/contextual-views2.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/inconsistent-action-model-lifecycle.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/b [...]

2021-04-29 05:08 UTC, opbld30 commented
Docs Build status updates of commit _[69eaeb2](https://github.com/MicrosoftDocs/msteams-docs/commits/69eaeb264e1a42f72c1effcd6a7e626d85b105c7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/task-modules-and-cards/cards/Universal-actions-for-adaptive-cards/Overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/task-modules-and-cards/cards/Universal-actions-for-adaptive-cards/Overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) | [Details](#user-content-5a9ad89638b6928a74cc6a9b81d90583-1155c5fc)
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions?branch=pr-en-us-2769) |
[msteams-platform/assets/images/.DS_Store](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/.DS_Store) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/adaptive-cards/current-teams-outlook-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/current-teams-outlook-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-catering-bot.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-catering-bot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-incident-management.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-incident-management.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-teams-outlook.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-teams-outlook.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up-to-date-views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up-to-date-views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-3.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-3.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up-to-date-views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Cateringbotstates.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Cateringbotstates.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/cateringbotstates.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Newuniversalactionmodel.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Newuniversalactionmodel.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/newuniversalactionmodel.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Rolebasedviews.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Rolebasedviews.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/rolebasedviews.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/TeamsandOutlook.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/TeamsandOutlook.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/teamsandoutlook.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/contextual-views.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/contextual-views2.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/inconsistent-action-model-lifecycle.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/b [...]

2021-04-29 05:19 UTC, opbld30 commented
Docs Build status updates of commit _[5188104](https://github.com/MicrosoftDocs/msteams-docs/commits/518810472f2c7bee43f6783f47673a093deef5be)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/TOC.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions?branch=pr-en-us-2769) | [Details](#user-content-f679b5d0ee59eb212f56a224ff613c91-db460a78)
[msteams-platform/assets/images/.DS_Store](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/.DS_Store) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/adaptive-cards/current-teams-outlook-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/current-teams-outlook-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-catering-bot.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-catering-bot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-incident-management.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-incident-management.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-teams-outlook.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-teams-outlook.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up-to-date-views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up-to-date-views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-3.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-3.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up-to-date-views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Cateringbotstates.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Cateringbotstates.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/cateringbotstates.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Newuniversalactionmodel.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Newuniversalactionmodel.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/newuniversalactionmodel.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Rolebasedviews.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Rolebasedviews.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/rolebasedviews.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/TeamsandOutlook.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/TeamsandOutlook.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/teamsandoutlook.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/contextual-views.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/contextual-views2.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/inconsistent-action-model-lifecycle.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/inconsistent-action-model.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/new-universal-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/new-universal-actio [...]

2021-04-29 05:24 UTC, opbld30 commented
Docs Build status updates of commit _[3ad4e7f](https://github.com/MicrosoftDocs/msteams-docs/commits/3ad4e7fae51b8a7bd3525c8825ab669c087c56cd)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/TOC.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions?branch=pr-en-us-2769) | [Details](#user-content-f679b5d0ee59eb212f56a224ff613c91-54fee22f)
[msteams-platform/assets/images/.DS_Store](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/.DS_Store) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/adaptive-cards/current-teams-outlook-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/current-teams-outlook-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-catering-bot.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-catering-bot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-incident-management.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-incident-management.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-teams-outlook.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-teams-outlook.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up-to-date-views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up-to-date-views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-3.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-3.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up-to-date-views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Cateringbotstates.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Cateringbotstates.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/cateringbotstates.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Newuniversalactionmodel.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Newuniversalactionmodel.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/newuniversalactionmodel.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Rolebasedviews.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Rolebasedviews.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/rolebasedviews.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/TeamsandOutlook.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/TeamsandOutlook.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/teamsandoutlook.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/contextual-views.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/contextual-views2.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/inconsistent-action-model-lifecycle.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/inconsistent-action-model.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/new-universal-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/new-universal-actio [...]

2021-04-29 05:26 UTC, opbld33 commented
Docs Build status updates of commit _[06abc3e](https://github.com/MicrosoftDocs/msteams-docs/commits/06abc3e49b5a61b97964bfaec26f3b9df4f8e238)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions?branch=pr-en-us-2769) |
[msteams-platform/assets/images/.DS_Store](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/.DS_Store) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/adaptive-cards/current-teams-outlook-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/current-teams-outlook-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-catering-bot.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-catering-bot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-incident-management.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-incident-management.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-teams-outlook.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-teams-outlook.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up-to-date-views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up-to-date-views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-3.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-3.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up-to-date-views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Cateringbotstates.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Cateringbotstates.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/cateringbotstates.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Newuniversalactionmodel.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Newuniversalactionmodel.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/newuniversalactionmodel.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Rolebasedviews.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Rolebasedviews.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/rolebasedviews.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/TeamsandOutlook.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/TeamsandOutlook.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/teamsandoutlook.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/contextual-views.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/contextual-views2.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/inconsistent-action-model-lifecycle.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/inconsistent-action-model.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/new-universal-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/new-universal-action-model.png) | :white_check_mark:Succeeded | [Vie [...]

2021-04-29 05:40 UTC, opbld31 commented
Docs Build status updates of commit _[1eb90ae](https://github.com/MicrosoftDocs/msteams-docs/commits/1eb90ae26bd9e87b954a04031bd1fbf05535a9fe)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions?branch=pr-en-us-2769) |
[msteams-platform/assets/images/.DS_Store](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/.DS_Store) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/adaptive-cards/current-teams-outlook-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/current-teams-outlook-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-catering-bot.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-catering-bot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-incident-management.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-incident-management.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-teams-outlook.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-teams-outlook.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up-to-date-views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up-to-date-views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-3.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-3.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up-to-date-views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Cateringbotstates.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Cateringbotstates.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/cateringbotstates.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Newuniversalactionmodel.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Newuniversalactionmodel.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/newuniversalactionmodel.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Rolebasedviews.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Rolebasedviews.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/rolebasedviews.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/TeamsandOutlook.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/TeamsandOutlook.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/teamsandoutlook.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/contextual-views.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/contextual-views2.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/inconsistent-action-model-lifecycle.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/inconsistent-action-model.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/new-universal-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/new-universal-action-model.png) | :white_check_mark:Succeeded | [Vie [...]

2021-04-29 05:48 UTC, opbld32 commented
Docs Build status updates of commit _[583748e](https://github.com/MicrosoftDocs/msteams-docs/commits/583748ef95ff8db2fc7c3c114fdcdb85dc7725a8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions?branch=pr-en-us-2769) |
[msteams-platform/assets/images/.DS_Store](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/.DS_Store) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/adaptive-cards/current-teams-outlook-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/current-teams-outlook-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-catering-bot.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-catering-bot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-incident-management.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-incident-management.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-teams-outlook.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-teams-outlook.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up-to-date-views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up-to-date-views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-3.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-3.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up-to-date-views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Cateringbotstates.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Cateringbotstates.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/cateringbotstates.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Newuniversalactionmodel.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Newuniversalactionmodel.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/newuniversalactionmodel.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Rolebasedviews.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Rolebasedviews.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/rolebasedviews.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/TeamsandOutlook.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/TeamsandOutlook.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/teamsandoutlook.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/contextual-views.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/contextual-views2.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/inconsistent-action-model-lifecycle.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/inconsistent-action-model.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/new-universal-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/new-universal-action-model.png) | :white_check_mark:Succeeded | [Vie [...]

2021-04-29 06:26 UTC, opbld33 commented
Docs Build status updates of commit _[c5f254f](https://github.com/MicrosoftDocs/msteams-docs/commits/c5f254f69815c6d79950a1de7eb8764d8b953f42)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions?branch=pr-en-us-2769) |
[msteams-platform/assets/images/.DS_Store](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/.DS_Store) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/adaptive-cards/current-teams-outlook-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/current-teams-outlook-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-catering-bot.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-catering-bot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-incident-management.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-incident-management.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-teams-outlook.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-teams-outlook.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up-to-date-views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up-to-date-views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-3.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-3.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up-to-date-views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Cateringbotstates.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Cateringbotstates.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/cateringbotstates.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Newuniversalactionmodel.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Newuniversalactionmodel.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/newuniversalactionmodel.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Rolebasedviews.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Rolebasedviews.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/rolebasedviews.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/TeamsandOutlook.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/TeamsandOutlook.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/teamsandoutlook.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/contextual-views.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/contextual-views2.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/inconsistent-action-model-lifecycle.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/inconsistent-action-model.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/new-universal-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/new-universal-action-model.png) | :white_check_mark:Succeeded | [Vie [...]

2021-04-29 07:17 UTC, opbld33 commented
Docs Build status updates of commit _[d764d05](https://github.com/MicrosoftDocs/msteams-docs/commits/d764d05b8680bfe3468a3491bd37bd54bdb1eff9)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-a532c1e6)

<a id="a532c1e6"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C29%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202104290717140652-2769%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=yjs4dMukzhoF48qtZ9Om95Mw4hPKIw8uDYQ3%2FARvabw%3D&st=2021-04-29T07%3A12%3A29Z&se=2021-05-30T07%3A17%3A29Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-29 07:21 UTC, opbld32 commented
Docs Build status updates of commit _[228ac0c](https://github.com/MicrosoftDocs/msteams-docs/commits/228ac0c87e3fcf38871a2553eca380429d264ce3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions?branch=pr-en-us-2769) |
[msteams-platform/assets/images/.DS_Store](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/.DS_Store) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/adaptive-cards/current-teams-outlook-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/current-teams-outlook-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-catering-bot.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-catering-bot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-incident-management.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-incident-management.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-teams-outlook.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-teams-outlook.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up-to-date-views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up-to-date-views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-3.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-3.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up-to-date-views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Cateringbotstates.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Cateringbotstates.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/cateringbotstates.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Newuniversalactionmodel.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Newuniversalactionmodel.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/newuniversalactionmodel.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Rolebasedviews.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Rolebasedviews.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/rolebasedviews.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/TeamsandOutlook.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/TeamsandOutlook.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/teamsandoutlook.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/contextual-views.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/contextual-views2.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/inconsistent-action-model-lifecycle.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/inconsistent-action-model.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/new-universal-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/new-universal-action-model.png) | :white_check_mark:Succeeded | [Vie [...]

2021-04-29 07:35 UTC, opbld33 commented
Docs Build status updates of commit _[9b0d56e](https://github.com/MicrosoftDocs/msteams-docs/commits/9b0d56e82b5af306081de6457aad89bf75fd3ca0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions?branch=pr-en-us-2769) |
[msteams-platform/assets/images/.DS_Store](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/.DS_Store) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/adaptive-cards/current-teams-outlook-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/current-teams-outlook-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-catering-bot.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-catering-bot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-incident-management.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-incident-management.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-teams-outlook.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-teams-outlook.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up-to-date-views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up-to-date-views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-3.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-3.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up-to-date-views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Cateringbotstates.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Cateringbotstates.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/cateringbotstates.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Newuniversalactionmodel.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Newuniversalactionmodel.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/newuniversalactionmodel.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Rolebasedviews.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Rolebasedviews.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/rolebasedviews.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/TeamsandOutlook.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/TeamsandOutlook.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/teamsandoutlook.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/contextual-views.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/contextual-views2.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/inconsistent-action-model-lifecycle.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/inconsistent-action-model.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/new-universal-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/new-universal-action-model.png) | :white_check_mark:Succeeded | [Vie [...]

2021-04-29 08:45 UTC, opbld31 commented
Docs Build status updates of commit _[f0c7f4f](https://github.com/MicrosoftDocs/msteams-docs/commits/f0c7f4f1aad07e27e08211d77348279c3fc8ccb6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions?branch=pr-en-us-2769) |
[msteams-platform/assets/images/.DS_Store](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/.DS_Store) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/adaptive-cards/current-teams-outlook-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/current-teams-outlook-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-catering-bot.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-catering-bot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-incident-management.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-incident-management.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-teams-outlook.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-teams-outlook.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up-to-date-views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up-to-date-views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-3.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-3.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up-to-date-views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Cateringbotstates.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Cateringbotstates.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/cateringbotstates.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Newuniversalactionmodel.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Newuniversalactionmodel.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/newuniversalactionmodel.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Rolebasedviews.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Rolebasedviews.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/rolebasedviews.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/TeamsandOutlook.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/TeamsandOutlook.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/teamsandoutlook.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/contextual-views.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/contextual-views2.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/inconsistent-action-model-lifecycle.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/inconsistent-action-model.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/new-universal-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/new-universal-action-model.png) | :white_check_mark:Succeeded | [Vie [...]

2021-04-29 09:52 UTC, opbld32 commented
Docs Build status updates of commit _[2106b85](https://github.com/MicrosoftDocs/msteams-docs/commits/2106b8591aa3f756826faf7c8a4e95f9c52b4209)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions?branch=pr-en-us-2769) |
[msteams-platform/assets/images/.DS_Store](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/.DS_Store) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/adaptive-cards/current-teams-outlook-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/current-teams-outlook-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-catering-bot.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-catering-bot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-incident-management.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-incident-management.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-teams-outlook.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-teams-outlook.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up-to-date-views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up-to-date-views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-3.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-3.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up-to-date-views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Cateringbotstates.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Cateringbotstates.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/cateringbotstates.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Newuniversalactionmodel.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Newuniversalactionmodel.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/newuniversalactionmodel.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Rolebasedviews.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Rolebasedviews.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/rolebasedviews.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/TeamsandOutlook.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/TeamsandOutlook.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/teamsandoutlook.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/contextual-views.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/contextual-views2.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/inconsistent-action-model-lifecycle.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/inconsistent-action-model.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/new-universal-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/new-universal-action-model.png) | :white_check_mark:Succeeded | [Vie [...]

2021-04-29 09:56 UTC, opbld30 commented
Docs Build status updates of commit _[db75601](https://github.com/MicrosoftDocs/msteams-docs/commits/db75601e9d810ae52ce2e0ab7c0ebbeb4b85ba17)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions?branch=pr-en-us-2769) |
[msteams-platform/assets/images/.DS_Store](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/.DS_Store) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/adaptive-cards/current-teams-outlook-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/current-teams-outlook-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-catering-bot.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-catering-bot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-incident-management.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-incident-management.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-teams-outlook.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-teams-outlook.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up-to-date-views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up-to-date-views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-3.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-3.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up-to-date-views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Cateringbotstates.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Cateringbotstates.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/cateringbotstates.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Newuniversalactionmodel.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Newuniversalactionmodel.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/newuniversalactionmodel.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Rolebasedviews.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Rolebasedviews.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/rolebasedviews.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/TeamsandOutlook.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/TeamsandOutlook.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/teamsandoutlook.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/contextual-views.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/contextual-views2.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/inconsistent-action-model-lifecycle.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/inconsistent-action-model.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/new-universal-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/new-universal-action-model.png) | :white_check_mark:Succeeded | [Vie [...]

2021-04-29 10:00 UTC, opbld31 commented
Docs Build status updates of commit _[de390c3](https://github.com/MicrosoftDocs/msteams-docs/commits/de390c324aeff8d9c10c89fa03709cadf972fcdd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions?branch=pr-en-us-2769) |
[msteams-platform/assets/images/.DS_Store](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/.DS_Store) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/adaptive-cards/current-teams-outlook-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/current-teams-outlook-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-catering-bot.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-catering-bot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-incident-management.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-incident-management.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-teams-outlook.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-teams-outlook.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up-to-date-views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up-to-date-views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-3.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-3.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up-to-date-views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Cateringbotstates.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Cateringbotstates.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/cateringbotstates.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Newuniversalactionmodel.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Newuniversalactionmodel.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/newuniversalactionmodel.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Rolebasedviews.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Rolebasedviews.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/rolebasedviews.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/TeamsandOutlook.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/TeamsandOutlook.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/teamsandoutlook.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/contextual-views.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/contextual-views2.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/inconsistent-action-model-lifecycle.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/inconsistent-action-model.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/new-universal-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/new-universal-action-model.png) | :white_check_mark:Succeeded | [Vie [...]

2021-04-29 11:08 UTC, opbld32 commented
Docs Build status updates of commit _[6ce4900](https://github.com/MicrosoftDocs/msteams-docs/commits/6ce49008b3000ebc0d2650c9d2456e565763c498)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions?branch=pr-en-us-2769) |
[msteams-platform/assets/images/.DS_Store](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/.DS_Store) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/adaptive-cards/current-teams-outlook-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/current-teams-outlook-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-catering-bot.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-catering-bot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-incident-management.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-incident-management.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-teams-outlook.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-teams-outlook.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up-to-date-views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up-to-date-views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-3.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-3.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up-to-date-views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Cateringbotstates.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Cateringbotstates.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/cateringbotstates.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Newuniversalactionmodel.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Newuniversalactionmodel.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/newuniversalactionmodel.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Rolebasedviews.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Rolebasedviews.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/rolebasedviews.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/TeamsandOutlook.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/TeamsandOutlook.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/teamsandoutlook.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/contextual-views.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/contextual-views2.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/inconsistent-action-model-lifecycle.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/inconsistent-action-model.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/new-universal-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/new-universal-action-model.png) | :white_check_mark:Succeeded | [Vie [...]

2021-04-29 12:31 UTC, opbld32 commented
Docs Build status updates of commit _[0022646](https://github.com/MicrosoftDocs/msteams-docs/commits/002264671dd755c892ad37afb5c71d832b72b4b6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions?branch=pr-en-us-2769) |
[msteams-platform/assets/images/.DS_Store](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/.DS_Store) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/adaptive-cards/current-teams-outlook-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/current-teams-outlook-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-catering-bot.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-catering-bot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-incident-management.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-incident-management.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-teams-outlook.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-teams-outlook.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up-to-date-views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up-to-date-views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-3.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-3.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up-to-date-views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Cateringbotstates.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Cateringbotstates.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/cateringbotstates.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Newuniversalactionmodel.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Newuniversalactionmodel.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/newuniversalactionmodel.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Rolebasedviews.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Rolebasedviews.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/rolebasedviews.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/TeamsandOutlook.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/TeamsandOutlook.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/teamsandoutlook.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/contextual-views.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/contextual-views2.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/inconsistent-action-model-lifecycle.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/inconsistent-action-model.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/new-universal-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/new-universal-action-model.png) | :white_check_mark:Succeeded | [Vie [...]

2021-04-29 13:47 UTC, opbld33 commented
Docs Build status updates of commit _[adc915e](https://github.com/MicrosoftDocs/msteams-docs/commits/adc915e5a99dcc87d13ba499a408109f2ce7251e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions?branch=pr-en-us-2769) |
[msteams-platform/assets/images/.DS_Store](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/.DS_Store) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/adaptive-cards/current-teams-outlook-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/current-teams-outlook-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-catering-bot.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-catering-bot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-incident-management.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-incident-management.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-teams-outlook.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-teams-outlook.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up-to-date-views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up-to-date-views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-3.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views-3.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/up-to-date-views?branch=pr-en-us-2769) |
[msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/adaptive-cards/universal-bots-up-to-date-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Cateringbotstates.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Cateringbotstates.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/cateringbotstates.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Newuniversalactionmodel.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Newuniversalactionmodel.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/newuniversalactionmodel.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/Rolebasedviews.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/Rolebasedviews.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/rolebasedviews.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/TeamsandOutlook.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/TeamsandOutlook.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/teamsandoutlook.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/contextual-views.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/contextual-views2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/contextual-views2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/contextual-views2.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model-lifecycle.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/inconsistent-action-model-lifecycle.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/inconsistent-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/inconsistent-action-model.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/bots/inconsistent-action-model.png?branch=pr-en-us-2769) |
[msteams-platform/assets/images/bots/new-universal-action-model.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Universalbotactionmodel/msteams-platform/assets/images/bots/new-universal-action-model.png) | :white_check_mark:Succeeded | [Vie [...]

2021-04-29 13:49 UTC, KirtiPereira approved these changes
Approved

2021-04-29 16:08 UTC, sowrabh-msft approved these changes

2021-04-29 16:12 UTC, surbhigupta12 approved these changes
Approved the PR

2021-04-29 16:12 UTC, merged