Update cards-format.md
MicrosoftDocs/msteams-docs pull request #2913
Opened 2021-03-16 04:30 UTC by ojasvichoudhary

2021-03-16 04:31 UTC, opbld32 commented
Docs Build status updates of commit _[b11d30c](https://github.com/MicrosoftDocs/msteams-docs/commits/b11d30c3ebf0b4861317b0bb5d9ff6af9a6bfb19)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/task-modules-and-cards/cards/cards-format.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ojasvichoudhary-adaptiveCards/msteams-platform/task-modules-and-cards/cards/cards-format.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?branch=pr-en-us-2913) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C16%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202103160430387037-2913%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=4Bh4gdJj5WS11tWFoEi%2FG2p7RJQwG4NeCekA5GdJ%2FVY%3D&st=2021-03-16T04%3A26%3A14Z&se=2021-04-16T04%3A31%3A14Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-16 05:42 UTC, opbld31 commented
Docs Build status updates of commit _[88041e4](https://github.com/MicrosoftDocs/msteams-docs/commits/88041e47308d72de0cd54b54159af54ff350f980)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/task-modules-and-cards/cards/cards-format.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ojasvichoudhary-adaptiveCards/msteams-platform/task-modules-and-cards/cards/cards-format.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?branch=pr-en-us-2913) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C16%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202103160542079829-2913%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Z9mucqvnHXHwiZ0uDlNgxjl63kbXfmZBWgK6CcsWdYo%3D&st=2021-03-16T05%3A37%3A44Z&se=2021-04-16T05%3A42%3A44Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-29 08:22 UTC, KirtiPereira requested changes
Hi @ojasvichoudhary - kindly validate and incorporate the suggestions. Also, please confirm if we are good to approve and merge the PR after your changes.
Thank you.

2021-03-29 08:22 UTC, KirtiPereira commented on msteams-platform/task-modules-and-cards/cards/cards-format.md
> +Use the information masking property to mask specific information, such as password or sensitive information from users within the adaptive card [Input Text](https://adaptivecards.io/explorer/Input.T
```suggestion
Use the information masking property to mask specific information, such as password or sensitive information from users within the Adaptive card [`Input.Text`](https://adaptivecards.io/explorer/Input.Text.html) input element. 

> [!NOTE]
> The feature only supports client side information masking, the masked input text is sent as clear text to the https endpoint address that was specified during [bot configuration](../../build-your-first-app/build-bot#4-configure-your-bot). 
```

2021-03-29 08:22 UTC, KirtiPereira commented on msteams-platform/task-modules-and-cards/cards/cards-format.md
> +Within the [Input Choiceset](https://adaptivecards.io/explorer/Input.ChoiceSet.html) schema element, asking users to filter through and select through a sizable number of choices can signnificantly s
```suggestion
### Typeahead support

Within the [`Input.Choiceset`](https://adaptivecards.io/explorer/Input.ChoiceSet.html) schema element, asking users to filter through and select through a sizable number of choices can significantly slow down task completion. Typeahead support within Adaptive cards can simplify input selection by narrowing or filtering the set of input choices as a user is typing the input. 
```

2021-03-29 08:22 UTC, KirtiPereira commented on msteams-platform/task-modules-and-cards/cards/cards-format.md
> +To enable typeahead within the Input choiceset set `style` to `filtered` and ensure `isMultiSelect` is set to `false`.
```suggestion
#### Enable typeahead in Adaptive cards

To enable typeahead within the `Input.Choiceset` set `style` to `filtered` and ensure `isMultiSelect` is set to `false`. 
```

2021-03-29 20:26 UTC, opbld32 commented
Docs Build status updates of commit _[69ae97b](https://github.com/MicrosoftDocs/msteams-docs/commits/69ae97b2deb3ea1ab50c3e5a106ea894f59ff69b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/task-modules-and-cards/cards/cards-format.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ojasvichoudhary-adaptiveCards/msteams-platform/task-modules-and-cards/cards/cards-format.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?branch=pr-en-us-2913) | [Details](#user-content-3f9a89611d5b09ba4ab60e4ebd6b87ec-2adda5c0)

<a id="3f9a89611d5b09ba4ab60e4ebd6b87ec-2adda5c0"></a>
### [msteams-platform/task-modules-and-cards/cards/cards-format.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ojasvichoudhary-adaptiveCards/msteams-platform/task-modules-and-cards/cards/cards-format.md)
 - **Line 160, Column 162**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../../build-your-first-app/build-bot'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C29%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202103292025299513-2913%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=KsesV1yVkY1rIH7xIOwoJWr3ZR7FVkMuCTPjB%2Bh6MSo%3D&st=2021-03-29T20%3A21%3A01Z&se=2021-04-29T20%3A26%3A01Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-29 20:26 UTC, opbld31 commented
Docs Build status updates of commit _[e46c07e](https://github.com/MicrosoftDocs/msteams-docs/commits/e46c07ede4ab65431003542c2ca317fbf70f1674)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/task-modules-and-cards/cards/cards-format.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ojasvichoudhary-adaptiveCards/msteams-platform/task-modules-and-cards/cards/cards-format.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?branch=pr-en-us-2913) | [Details](#user-content-3f9a89611d5b09ba4ab60e4ebd6b87ec-189f0616)

<a id="3f9a89611d5b09ba4ab60e4ebd6b87ec-189f0616"></a>
### [msteams-platform/task-modules-and-cards/cards/cards-format.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ojasvichoudhary-adaptiveCards/msteams-platform/task-modules-and-cards/cards/cards-format.md)
 - **Line 160, Column 162**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../../build-your-first-app/build-bot'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C29%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202103292025453337-2913%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=u36u6p8iQJMQ%2FJKT1prMXA2N4thyLI8kXf23ahkmytg%3D&st=2021-03-29T20%3A21%3A40Z&se=2021-04-29T20%3A26%3A40Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-29 20:27 UTC, opbld31 commented
Docs Build status updates of commit _[917f3a7](https://github.com/MicrosoftDocs/msteams-docs/commits/917f3a772f9c4e30ab5aa99e275f1d1c967d8e76)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-7935eb60)
[msteams-platform/task-modules-and-cards/cards/cards-format.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ojasvichoudhary-adaptiveCards/msteams-platform/task-modules-and-cards/cards/cards-format.md) | :warning:Warning | | [Details](#user-content-3f9a89611d5b09ba4ab60e4ebd6b87ec-7935eb60)

<a id="7935eb60"></a>
###
 - **[Error-RuningBuildFailed]** `````Some unexpected errors happened when running build, please open a ticket in https://SiteHelp and include the error report for our team to troubleshoot`````

<a id="3f9a89611d5b09ba4ab60e4ebd6b87ec-7935eb60"></a>
### [msteams-platform/task-modules-and-cards/cards/cards-format.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ojasvichoudhary-adaptiveCards/msteams-platform/task-modules-and-cards/cards/cards-format.md)
 - **Line 160, Column 162**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../../build-your-first-app/build-bot'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C29%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202103292026219171-2913%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=4VUxYLxTZhw1dSFFah8YS%2B4bFNDO5Sg6A06Cf9e2tGk%3D&st=2021-03-29T20%3A22%3A31Z&se=2021-04-29T20%3A27%3A31Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-30 05:45 UTC, opbld32 commented
Docs Build status updates of commit _[b90bdfc](https://github.com/MicrosoftDocs/msteams-docs/commits/b90bdfc16ee1f99726a7340e38b7109f9d9cb659)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/task-modules-and-cards/cards/cards-format.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ojasvichoudhary-adaptiveCards/msteams-platform/task-modules-and-cards/cards/cards-format.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?branch=pr-en-us-2913) | [Details](#user-content-3f9a89611d5b09ba4ab60e4ebd6b87ec-c331ffa3)

<a id="3f9a89611d5b09ba4ab60e4ebd6b87ec-c331ffa3"></a>
### [msteams-platform/task-modules-and-cards/cards/cards-format.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ojasvichoudhary-adaptiveCards/msteams-platform/task-modules-and-cards/cards/cards-format.md)
 - **Line 160, Column 162**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../../build-your-first-app/build-bot'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C30%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202103300544031770-2913%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=DZo7c1pUKjMgrJ4Jolg9YYW1da7%2FNHhZrH8Smij%2F9KU%3D&st=2021-03-30T05%3A40%3A01Z&se=2021-04-30T05%3A45%3A01Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-30 06:00 UTC, opbld30 commented
Docs Build status updates of commit _[2335e54](https://github.com/MicrosoftDocs/msteams-docs/commits/2335e54441e3b4f7339f76c37663baaac0c9b434)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/task-modules-and-cards/cards/cards-format.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ojasvichoudhary-adaptiveCards/msteams-platform/task-modules-and-cards/cards/cards-format.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?branch=pr-en-us-2913) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C30%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202103300559347388-2913%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=qMF0mDQh9yHW7My3CcpH%2Bq%2BRqGZcNIVvian9N8dEFR4%3D&st=2021-03-30T05%3A55%3A08Z&se=2021-04-30T06%3A00%3A08Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-30 08:34 UTC, KirtiPereira approved these changes
Approved

2021-03-30 08:34 UTC, surbhigupta12 approved these changes
Approved the PR.

2021-03-30 08:34 UTC, merged