[Authentication][Signoutflowadded][1570772]
MicrosoftDocs/msteams-docs pull request #2918
Opened 2021-03-16 10:28 UTC by v-rodriguezd

Added section for sign out flow with code for issue 424. Please review.

2021-03-16 10:29 UTC, opbld31 commented
Docs Build status updates of commit _[e45669e](https://github.com/MicrosoftDocs/msteams-docs/commits/e45669e150c47813c46bf2c22627e9b5246a7443)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/tabs/how-to/authentication/auth-silent-aad.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1570772-signoutflow/msteams-platform/tabs/how-to/authentication/auth-silent-aad.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-silent-aad?branch=pr-en-us-2918) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C16%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202103161028545691-2918%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Ds9pYDtOULP%2FTW53r92CBZumhoZ5gZxfrOgW0HZGJ0I%3D&st=2021-03-16T10%3A24%3A23Z&se=2021-04-16T10%3A29%3A23Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-19 07:22 UTC, KirtiPereira requested changes
@v-rodriguezd - please validate and incorporate the suggestions.

2021-03-19 07:22 UTC, KirtiPereira commented on msteams-platform/tabs/how-to/authentication/auth-silent-aad.md
> +If ADAL has an unexpired token cached for the user, use the token. Alternately, attempt to get a token silently by calling `acquireToken(resource, callback)`. ADAL.js calls your callback function wit
```suggestion
If ADAL has a token cached for the user that has not expired, use that token. Alternately, get a token silently by calling `acquireToken(resource, callback)`. ADAL.js calls the callback function with the requested token, or gives an error if authentication fails.
```

2021-03-19 07:40 UTC, opbld32 commented
Docs Build status updates of commit _[3da79ff](https://github.com/MicrosoftDocs/msteams-docs/commits/3da79ff1817766293e3afda1985876fc64569bb1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/tabs/how-to/authentication/auth-silent-aad.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1570772-signoutflow/msteams-platform/tabs/how-to/authentication/auth-silent-aad.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-silent-aad?branch=pr-en-us-2918) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C19%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202103190739548603-2918%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=IZM4Hkqro2prBAgp0wcIIBhGzp4%2BZJKJ%2BtQYvtVGeCs%3D&st=2021-03-19T07%3A35%3A35Z&se=2021-04-19T07%3A40%3A35Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-22 04:45 UTC, Trinetra-MSFT requested changes

2021-03-22 04:45 UTC, Trinetra-MSFT commented on msteams-platform/tabs/how-to/authentication/auth-silent-aad.md
> +Use the following code to handle sign out flow in AAD Auth:
Please give some insight on sign out flow, "While we do logout for teams tab or Bot, we clear the current session"

2021-03-22 04:45 UTC, Trinetra-MSFT commented on msteams-platform/tabs/how-to/authentication/auth-silent-aad.md
> +function logoutV1() {
Please rename this Method name to "logout" remove V1

2021-03-22 04:45 UTC, Trinetra-MSFT commented on msteams-platform/tabs/how-to/authentication/auth-silent-aad.md
> +window.location.href = "@Url.Action("ChooseAuth", "Home")";
Please replace chooseAuth with `<<Action Name>>` and Home to `<<Controller Name>>`

2021-03-22 05:52 UTC, opbld33 commented
Docs Build status updates of commit _[91e2c5f](https://github.com/MicrosoftDocs/msteams-docs/commits/91e2c5fc856c65e02fed1854d09096b4f07cfdf4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/tabs/how-to/authentication/auth-silent-aad.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1570772-signoutflow/msteams-platform/tabs/how-to/authentication/auth-silent-aad.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-silent-aad?branch=pr-en-us-2918) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C22%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202103220551580411-2918%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=2w2dgjl%2FhptR7STbwFYSHtLHgpqtmMokKSJw2nFWiF8%3D&st=2021-03-22T05%3A47%3A38Z&se=2021-04-22T05%3A52%3A38Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-26 05:16 UTC, Trinetra-MSFT approved these changes

2021-03-26 06:27 UTC, KirtiPereira approved these changes
Approved

2021-03-26 11:03 UTC, surbhigupta12 approved these changes
Approving the PR

2021-03-26 11:03 UTC, merged