Messaging extension anuj
MicrosoftDocs/msteams-docs pull request #2919
Opened 2021-03-16 10:32 UTC by anbah34

2021-03-16 10:33 UTC, opbld32 commented
Docs Build status updates of commit _[0de805b](https://github.com/MicrosoftDocs/msteams-docs/commits/0de805b9a7e56359fcc10edb519c556f9e8b855c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/messaging-extensions/design/messaging-extension-design.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Messagin_Extension_Anuj/msteams-platform/messaging-extensions/design/messaging-extension-design.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/design/messaging-extension-design?branch=pr-en-us-2919) | [Details](#user-content-d5f2092c4275ea066ff6b685c0075f33-d30ef628)

<a id="d5f2092c4275ea066ff6b685c0075f33-d30ef628"></a>
### [msteams-platform/messaging-extensions/design/messaging-extension-design.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Messagin_Extension_Anuj/msteams-platform/messaging-extensions/design/messaging-extension-design.md)
 - **Line 96, Column 1**: **[Warning-duplicate-alt-text]** `````Alt text 'Example shows a user searching for content to insert from the compose box.' is duplicated. Within an article, alt text must be unique.`````
 - **Line 110, Column 1**: **[Warning-duplicate-alt-text]** `````Alt text 'Example shows a user searching for content to insert from the compose box.' is duplicated. Within an article, alt text must be unique.`````
 - **Line 162, Column 1**: **[Warning-duplicate-alt-text]** `````Alt text 'Example showing a messaging extension best practice.' is duplicated. Within an article, alt text must be unique.`````
 - **Line 170, Column 1**: **[Warning-duplicate-alt-text]** `````Alt text 'Example showing a messaging extension best practice.' is duplicated. Within an article, alt text must be unique.`````
 - **Line 187, Column 1**: **[Warning-duplicate-alt-text]** `````Alt text 'Example showing a messaging extension best practice.' is duplicated. Within an article, alt text must be unique.`````
 - **Line 195, Column 1**: **[Warning-duplicate-alt-text]** `````Alt text 'Example showing a messaging extension best practice.' is duplicated. Within an article, alt text must be unique.`````
 - **Line 208, Column 1**: **[Warning-duplicate-alt-text]** `````Alt text 'Example showing a messaging extension best practice.' is duplicated. Within an article, alt text must be unique.`````
 - **Line 216, Column 1**: **[Warning-duplicate-alt-text]** `````Alt text 'Example showing a messaging extension best practice.' is duplicated. Within an article, alt text must be unique.`````
 - **Line 229, Column 1**: **[Warning-duplicate-alt-text]** `````Alt text 'Example showing a messaging extension best practice.' is duplicated. Within an article, alt text must be unique.`````
 - **Line 237, Column 1**: **[Warning-duplicate-alt-text]** `````Alt text 'Example showing a messaging extension best practice.' is duplicated. Within an article, alt text must be unique.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C16%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202103161032583243-2919%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=iPLiev80hIRFKVLrAoSoK%2Feqhqbydpog7f%2Fp4Uqiors%3D&st=2021-03-16T10%3A28%3A54Z&se=2021-04-16T10%3A33%3A54Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-19 06:35 UTC, KirtiPereira requested changes
@anbah34 - Please incorporate the comment and resolve the build warnings.

2021-03-19 06:35 UTC, KirtiPereira commented on msteams-platform/messaging-extensions/design/messaging-extension-design.md
> +Hi anuj here
Please remove this.

2021-03-23 06:09 UTC, opbld31 commented
Docs Build status updates of commit _[39941f5](https://github.com/MicrosoftDocs/msteams-docs/commits/39941f5c7201063f168c4001f419e8a666eec254)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/messaging-extensions/design/messaging-extension-design.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Messagin_Extension_Anuj/msteams-platform/messaging-extensions/design/messaging-extension-design.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/design/messaging-extension-design?branch=pr-en-us-2919) | [Details](#user-content-d5f2092c4275ea066ff6b685c0075f33-08a722d2)

<a id="d5f2092c4275ea066ff6b685c0075f33-08a722d2"></a>
### [msteams-platform/messaging-extensions/design/messaging-extension-design.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Messagin_Extension_Anuj/msteams-platform/messaging-extensions/design/messaging-extension-design.md)
 - **Line 95, Column 1**: **[Warning-[duplicate-alt-text](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-alt-text?branch=main)]** `````Alt text 'Example shows a user searching for content to insert from the compose box.' is duplicated. Within an article, alt text must be unique.`````
 - **Line 109, Column 1**: **[Warning-[duplicate-alt-text](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-alt-text?branch=main)]** `````Alt text 'Example shows a user searching for content to insert from the compose box.' is duplicated. Within an article, alt text must be unique.`````
 - **Line 161, Column 1**: **[Warning-[duplicate-alt-text](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-alt-text?branch=main)]** `````Alt text 'Example showing a messaging extension best practice.' is duplicated. Within an article, alt text must be unique.`````
 - **Line 169, Column 1**: **[Warning-[duplicate-alt-text](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-alt-text?branch=main)]** `````Alt text 'Example showing a messaging extension best practice.' is duplicated. Within an article, alt text must be unique.`````
 - **Line 186, Column 1**: **[Warning-[duplicate-alt-text](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-alt-text?branch=main)]** `````Alt text 'Example showing a messaging extension best practice.' is duplicated. Within an article, alt text must be unique.`````
 - **Line 194, Column 1**: **[Warning-[duplicate-alt-text](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-alt-text?branch=main)]** `````Alt text 'Example showing a messaging extension best practice.' is duplicated. Within an article, alt text must be unique.`````
 - **Line 207, Column 1**: **[Warning-[duplicate-alt-text](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-alt-text?branch=main)]** `````Alt text 'Example showing a messaging extension best practice.' is duplicated. Within an article, alt text must be unique.`````
 - **Line 215, Column 1**: **[Warning-[duplicate-alt-text](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-alt-text?branch=main)]** `````Alt text 'Example showing a messaging extension best practice.' is duplicated. Within an article, alt text must be unique.`````
 - **Line 228, Column 1**: **[Warning-[duplicate-alt-text](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-alt-text?branch=main)]** `````Alt text 'Example showing a messaging extension best practice.' is duplicated. Within an article, alt text must be unique.`````
 - **Line 236, Column 1**: **[Warning-[duplicate-alt-text](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-alt-text?branch=main)]** `````Alt text 'Example showing a messaging extension best practice.' is duplicated. Within an article, alt text must be unique.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C23%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202103230609146921-2919%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=XQ64AQcRrKJII5hI6s6bRtXha2Onp0vz2InocOa9dMk%3D&st=2021-03-23T06%3A04%3A49Z&se=2021-04-23T06%3A09%3A49Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-23 06:17 UTC, surbhigupta12 approved these changes
Approving the PR

2021-03-23 06:17 UTC, KirtiPereira approved these changes
approved

2021-03-23 06:17 UTC, merged