[Meetings][Updatedin-meetingdialog][1609291]
MicrosoftDocs/msteams-docs pull request #2941
Opened 2021-03-19 11:51 UTC by v-rodriguezd

Added information about in-meeting dialog and task module for issue 2870. Grammar and language changes. Please review.

2021-03-19 11:51 UTC, opbld33 commented
Docs Build status updates of commit _[9097408](https://github.com/MicrosoftDocs/msteams-docs/commits/90974085831b2c41c79b977e7e55d9c2b3df98b9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1609291-inmeetingdialog/msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-2941) | [Details](#user-content-351f2ba35302ce86d26f9fa3fc15a178-4aa5dab3)

<a id="351f2ba35302ce86d26f9fa3fc15a178-4aa5dab3"></a>
### [msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1609291-inmeetingdialog/msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md)
 - **Line 17, Column 120**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'enable-and-configure-your-app-for-teams-meetings.md'.`````
 - **Line 281, Column 57**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '~/assets/images/apps-in-meetings/plusbutton.png'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C19%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202103191151073544-2941%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=DIucj0fnaXntCrosMzHxdDJLylp0j6uHXDprrQqUnsY%3D&st=2021-03-19T11%3A46%3A44Z&se=2021-04-19T11%3A51%3A44Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-19 12:10 UTC, opbld33 commented
Docs Build status updates of commit _[c489122](https://github.com/MicrosoftDocs/msteams-docs/commits/c489122a25cefc60fe1ee84799b9a18ae128ee64)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1609291-inmeetingdialog/msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-2941) |
[msteams-platform/assets/images/apps-in-meetings/plusbutton.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1609291-inmeetingdialog/msteams-platform/assets/images/apps-in-meetings/plusbutton.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-2941) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C19%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202103191209332495-2941%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=cB%2F4sNdsNhsdMzPVoY3HkxPhYyk6buCvwNC9Wuj2mTM%3D&st=2021-03-19T12%3A05%3A11Z&se=2021-04-19T12%3A10%3A11Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-22 04:37 UTC, Trinetra-MSFT requested changes

2021-03-22 04:37 UTC, Trinetra-MSFT commented on msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md
> +In-meeting dialog must not use task module. Task module is not invoked in meeting chat rather external resource URL is used to display content bubble pop-up in meeting. Then you can use `submitTask`
Can you rephrase this sentence properly?

2021-03-22 04:40 UTC, Trinetra-MSFT requested changes

2021-03-22 04:40 UTC, Trinetra-MSFT commented on msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md
>  protected override async Task OnMessageActivityAsync(ITurnContext<IMessageActivity> turnContext, CancellationToken cancellationToken)
Document doesn't talk about from where we will get the meeting id and participants id

2021-03-22 05:42 UTC, opbld32 commented
Docs Build status updates of commit _[e2e8e31](https://github.com/MicrosoftDocs/msteams-docs/commits/e2e8e3152dbe120fc5c357114e8ff24056ad6346)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1609291-inmeetingdialog/msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-2941) |
[msteams-platform/assets/images/apps-in-meetings/plusbutton.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1609291-inmeetingdialog/msteams-platform/assets/images/apps-in-meetings/plusbutton.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-2941) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C22%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202103220542120435-2941%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=kT%2FRIskw5PwFXnVHfTghixjJ4s%2FlsCi1esQTXAzqdW4%3D&st=2021-03-22T05%3A37%3A58Z&se=2021-04-22T05%3A42%3A58Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-25 05:55 UTC, Trinetra-MSFT approved these changes
Looks Good

2021-03-25 10:37 UTC, surbhigupta12 approved these changes
Approving the PR

2021-03-25 10:38 UTC, merged