[Bots][Statuscodes][1644144]
MicrosoftDocs/msteams-docs pull request #2974
Opened 2021-03-25 06:36 UTC by v-rodriguezd

Added status code responses section as per issue 1697 and grammar and language changes done. Please review.

2021-03-25 06:37 UTC, opbld31 commented
Docs Build status updates of commit _[dbe9688](https://github.com/MicrosoftDocs/msteams-docs/commits/dbe96885405d26ce560d611d7fab3f7ad17dfb9d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1644144-statuscodes/msteams-platform/bots/how-to/conversations/conversation-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-basics?branch=pr-en-us-2974) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C25%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202103250636393499-2974%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=MoWfrQ%2BKhjLJmJOoCleUUljzUYqEP12XAxhssUyYx%2F0%3D&st=2021-03-25T06%3A32%3A14Z&se=2021-04-25T06%3A37%3A14Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-25 06:39 UTC, opbld33 commented
Docs Build status updates of commit _[9ce1d98](https://github.com/MicrosoftDocs/msteams-docs/commits/9ce1d980b3a7f6142fc3595f3cca444cf3bdfce9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1644144-statuscodes/msteams-platform/bots/how-to/conversations/conversation-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-basics?branch=pr-en-us-2974) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C25%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202103250639085228-2974%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=BA7XBlYafiAJyuVEWhJJg4IO1itW45p%2BSmAQMx8ma9M%3D&st=2021-03-25T06%3A34%3A43Z&se=2021-04-25T06%3A39%3A43Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-25 06:48 UTC, opbld31 commented
Docs Build status updates of commit _[23a7de7](https://github.com/MicrosoftDocs/msteams-docs/commits/23a7de7dec307b1fa6cb9b14465ba3a26136340b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/sample403response.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1644144-statuscodes/msteams-platform/assets/images/sample403response.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-basics?branch=pr-en-us-2974) |
[msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1644144-statuscodes/msteams-platform/bots/how-to/conversations/conversation-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-basics?branch=pr-en-us-2974) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C25%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202103250647330168-2974%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=D6C9bw33CADOcZfp87Ww4OIqXkFe%2BsHcDz8H1Y%2BdF8I%3D&st=2021-03-25T06%3A43%3A10Z&se=2021-04-25T06%3A48%3A10Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-26 10:32 UTC, Wajeed-msft requested changes

2021-03-26 10:32 UTC, Wajeed-msft commented on msteams-platform/bots/how-to/conversations/conversation-basics.md
> +
Could you please help to make following changes?
1. Swap the position of description and error code columns.
2. Add code and message on two separate lines and update the formatting
**Code**: `ConversationBlockedByUser` 
**Message**: User blocked the conversation with the bot.

2021-03-26 10:43 UTC, opbld30 commented
Docs Build status updates of commit _[1c7847e](https://github.com/MicrosoftDocs/msteams-docs/commits/1c7847e8f36f7b9d0e7e38894eb73fbd496c2741)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/sample403response.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1644144-statuscodes/msteams-platform/assets/images/sample403response.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-basics?branch=pr-en-us-2974) |
[msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1644144-statuscodes/msteams-platform/bots/how-to/conversations/conversation-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-basics?branch=pr-en-us-2974) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C26%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202103261042353609-2974%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=cEBzYrY5CDK54jYT54lXnJ5KLyIGT6YQYVktLKQxQP8%3D&st=2021-03-26T10%3A38%3A10Z&se=2021-04-26T10%3A43%3A10Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-26 10:57 UTC, opbld32 commented
Docs Build status updates of commit _[0e56d5f](https://github.com/MicrosoftDocs/msteams-docs/commits/0e56d5fe770afb4db6782bfbb5202ae7d3d9f367)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/sample403response.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1644144-statuscodes/msteams-platform/assets/images/sample403response.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-basics?branch=pr-en-us-2974) |
[msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1644144-statuscodes/msteams-platform/bots/how-to/conversations/conversation-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-basics?branch=pr-en-us-2974) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C26%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202103261056338721-2974%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=HfXYIGqCocsUvKdErwxxbGTDvFs2Sy1wXfXP05IusYc%3D&st=2021-03-26T10%3A52%3A08Z&se=2021-04-26T10%3A57%3A08Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-26 11:01 UTC, opbld31 commented
Docs Build status updates of commit _[1464c41](https://github.com/MicrosoftDocs/msteams-docs/commits/1464c4198ccfcf91509e3bf072a19c01b36a9bc1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/sample403response.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1644144-statuscodes/msteams-platform/assets/images/sample403response.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-basics?branch=pr-en-us-2974) |
[msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1644144-statuscodes/msteams-platform/bots/how-to/conversations/conversation-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-basics?branch=pr-en-us-2974) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C26%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202103261100397093-2974%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=sdVBdMzK4cPN0puaPN%2Bi2l10gS8vZf8QllF2dhDn64E%3D&st=2021-03-26T10%3A56%3A20Z&se=2021-04-26T11%3A01%3A20Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-05 14:02 UTC, opbld33 commented
Docs Build status updates of commit _[592cc0c](https://github.com/MicrosoftDocs/msteams-docs/commits/592cc0cb4a9dfcf2427acc1f048d477a5354b41f)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-7bf6119b)

<a id="7bf6119b"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C5%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202104051402114108-2974%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=NldSnmKw1faU6eP0bYi%2Bj16n3e2qpbqga%2Bx53FyU%2Bck%3D&st=2021-04-05T13%3A57%3A38Z&se=2021-05-06T14%3A02%3A38Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-12 05:34 UTC, Wajeed-msft approved these changes

2021-04-12 06:05 UTC, opbld33 commented
Docs Build status updates of commit _[3e0317a](https://github.com/MicrosoftDocs/msteams-docs/commits/3e0317a722c082a2fd9821d731aedf00aadb239b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1644144-statuscodes/msteams-platform/bots/how-to/conversations/conversation-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-basics?branch=pr-en-us-2974) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C12%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202104120604341885-2974%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=7NyJUhoPMGfXt93OJuM0ZwtUQoOpplcNIAA0%2Bd9NzaY%3D&st=2021-04-12T06%3A00%3A08Z&se=2021-05-13T06%3A05%3A08Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-12 06:08 UTC, KirtiPereira approved these changes
Approved

2021-04-12 06:11 UTC, surbhigupta12 approved these changes
Approved the PR.

2021-04-12 06:11 UTC, merged