Update app-templates.md
MicrosoftDocs/msteams-docs pull request #3014
Opened 2021-03-30 11:55 UTC by YogeshIITK

Adding following app template descriptions :
1- Training App Template
2- Quiz App Template

2021-03-30 11:55 UTC, opbld32 commented
Docs Build status updates of commit _[b59d2d9](https://github.com/MicrosoftDocs/msteams-docs/commits/b59d2d98d9a74e72af4ed03835058d3f1852151b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/samples/app-templates.md](https://github.com/MicrosoftDocs/msteams-docs/blob/YogeshIITK-patch-1/msteams-platform/samples/app-templates.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/samples/app-templates?branch=pr-en-us-3014) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C30%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202103301155201484-3014%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=I%2BLwIJXA7%2BOAHcVzgPXO7Y%2FShLciGYjCarDGlR8KRuA%3D&st=2021-03-30T11%3A50%3A54Z&se=2021-04-30T11%3A55%3A54Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-30 12:32 UTC, opbld33 commented
Docs Build status updates of commit _[6350c05](https://github.com/MicrosoftDocs/msteams-docs/commits/6350c0567447634df3ec196e77882d3b45f34757)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/samples/app-templates.md](https://github.com/MicrosoftDocs/msteams-docs/blob/YogeshIITK-patch-1/msteams-platform/samples/app-templates.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/samples/app-templates?branch=pr-en-us-3014) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C30%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202103301232102054-3014%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=h%2FwYhGdPO9a%2FeUHGPX58fBEtoR0KzAMR8IqoYaV%2F56M%3D&st=2021-03-30T12%3A27%3A48Z&se=2021-04-30T12%3A32%3A48Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-31 05:24 UTC, v-pmuthyala requested changes
minor changes

2021-03-31 05:24 UTC, v-pmuthyala commented on msteams-platform/samples/app-templates.md
> +extension ](../messaging-extensions/what-are-messaging-extensions.md) app that enables customers to publish a training within a chat or a channel for offline knowledge sharing and upskilling. The app
customers to publish training

2021-03-31 05:24 UTC, v-pmuthyala commented on msteams-platform/samples/app-templates.md
> +Quiz is a custom [Teams messaging extension ](../messaging-extensions/what-are-messaging-extensions.md) app that enables you to create a quiz within a chat or a channel for knowledge check and instan
knowledge check within the team, and for fun quizzes within the team.

2021-03-31 12:17 UTC, surbhigupta12 approved these changes
Approve the PR.

2021-03-31 12:18 UTC, KirtiPereira approved these changes
Approved.

2021-03-31 12:39 UTC, v-pmuthyala approved these changes
changes reviewed.

2021-03-31 12:43 UTC, merged