Update app-templates.md
MicrosoftDocs/msteams-docs pull request #3042
Opened 2021-04-02 19:20 UTC by jhwang-ms

Adding two additional adoption tools to this page, submitting on behalf of Josh Leporati.

2021-04-02 19:20 UTC, opbld33 commented
Docs Build status updates of commit _[a676b18](https://github.com/jhwang-ms/msteams-docs/commits/a676b18bd7112b6025e093c95e91c955a6eb368c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/samples/app-templates.md](https://github.com/jhwang-ms/msteams-docs/blob/patch-2/msteams-platform/samples/app-templates.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/samples/app-templates?branch=pr-en-us-3042) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C2%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202104021920026694-3042%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=tPaMewGaUuxjzU2Cfc%2Bmb67TNI5wRDyP8D3R0opzQi0%3D&st=2021-04-02T19%3A15%3A58Z&se=2021-05-03T19%3A20%3A58Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-05 22:50 UTC, jhwang-ms commented
@Mahesh2516 and @KirtiPereira - kindly request a status update on this review request so that I can provide a status update for my manager. Thank you.

2021-04-06 07:03 UTC, Mahesh2516 requested changes

2021-04-06 07:03 UTC, Mahesh2516 commented on msteams-platform/samples/app-templates.md
> +The Champion Management Platform (CMP) app template helps you manage, scale, and inspire your teamwork champions to achieve more. This app template is built on the SharePoint Framework and loaded int
The sentence can be written as:

Groups can leverage this tool and manage program membership, provide a leaderboard and event types for logging, and tools to overlay digital badges to program participants.

2021-04-06 07:14 UTC, opbld33 commented
Docs Build status updates of commit _[97d47ff](https://github.com/jhwang-ms/msteams-docs/commits/97d47ffd25a699b8c379ea00774af096315ae041)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/samples/app-templates.md](https://github.com/jhwang-ms/msteams-docs/blob/patch-2/msteams-platform/samples/app-templates.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/samples/app-templates?branch=pr-en-us-3042) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C6%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202104060714104082-3042%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=3qeoV%2B6CzFppGMQsp7vXk9x%2BIxZpqe9N4EmW3iLcn64%3D&st=2021-04-06T07%3A09%3A47Z&se=2021-05-07T07%3A14%3A47Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-06 07:20 UTC, opbld33 commented
Docs Build status updates of commit _[6717993](https://github.com/jhwang-ms/msteams-docs/commits/671799380fec8bb602706db4b8ea27aa0cccc332)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/samples/app-templates.md](https://github.com/jhwang-ms/msteams-docs/blob/patch-2/msteams-platform/samples/app-templates.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/samples/app-templates?branch=pr-en-us-3042) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C6%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202104060719440799-3042%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=kBTOWgbm64T6T9y9tBWoKTmYLZZwY%2BUXRjLhXBC6bB4%3D&st=2021-04-06T07%3A15%3A25Z&se=2021-05-07T07%3A20%3A25Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-06 07:24 UTC, KirtiPereira approved these changes
@jhwang-ms - we have approved the PR and it will be pushed to live.
Approved

2021-04-06 07:25 UTC, surbhigupta12 submitted a review, later dismissed
Approved the PR

2021-04-06 07:31 UTC, Mahesh2516 submitted a review, later dismissed

2021-04-06 07:37 UTC, opbld31 commented
Docs Build status updates of commit _[447c772](https://github.com/jhwang-ms/msteams-docs/commits/447c772ea658a6f4dd7b4072ce3cd279f7c815ad)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/samples/app-templates.md](https://github.com/jhwang-ms/msteams-docs/blob/patch-2/msteams-platform/samples/app-templates.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/samples/app-templates?branch=pr-en-us-3042) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C6%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202104060736441910-3042%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=6Izn7VaVzr8mOl0BSZksae9S9j6eBsoSL8ffRXZzQqg%3D&st=2021-04-06T07%3A32%3A23Z&se=2021-05-07T07%3A37%3A23Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-06 07:38 UTC, surbhigupta12 approved these changes
Approved

2021-04-06 07:38 UTC, KirtiPereira approved these changes
Approved

2021-04-06 07:41 UTC, Mahesh2516 approved these changes
Approved

2021-04-06 09:48 UTC, opbld32 commented
Docs Build status updates of commit _[39fec59](https://github.com/jhwang-ms/msteams-docs/commits/39fec5904b874a52daf91d13ff9a013b401a7a6f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/samples/app-templates.md](https://github.com/jhwang-ms/msteams-docs/blob/patch-2/msteams-platform/samples/app-templates.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/samples/app-templates?branch=pr-en-us-3042) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C6%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202104060947319534-3042%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=PLRJJSQlbutOz3QApF1PZVLe6K7PbTlcQDor4aWwF78%3D&st=2021-04-06T09%3A43%3A09Z&se=2021-05-07T09%3A48%3A09Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-06 12:22 UTC, closed without merging

2021-04-06 16:27 UTC, jhwang-ms commented
@KirtiPereira many thanks for pushing this live, but I see that the wording layout was changed. My manager, Karuana Gatimu, owns these two adoption tools and wants them to read the way we had submitted them originally: "Adoption tool - Change Management Platform" and "Adoption tool - Microsoft 365 learning pathways app (Get Started)". Can we revert please?