[Meetings][Usertypedetails][1677986]
MicrosoftDocs/msteams-docs pull request #3065
Opened 2021-04-07 09:37 UTC by v-rodriguezd

Updated user types details and added table for features as per issue 2995. Please review.

2021-04-07 09:37 UTC, opbld33 commented
Docs Build status updates of commit _[b50da62](https://github.com/MicrosoftDocs/msteams-docs/commits/b50da62d65d749ec62f705142d2eb3e08e772603)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1677986-Usertypedetails/msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/teams-apps-in-meetings?branch=pr-en-us-3065) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C7%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202104070937190485-3065%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=HNXIb05ctK%2FlB9vag%2F5lrZwcoJ99JYSw7ljLxfmGsNQ%3D&st=2021-04-07T09%3A32%3A53Z&se=2021-05-08T09%3A37%3A53Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-08 04:59 UTC, opbld32 commented
Docs Build status updates of commit _[3515705](https://github.com/MicrosoftDocs/msteams-docs/commits/35157052bc1802bf0db3f90630b5a9369c8523e9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1677986-Usertypedetails/msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/teams-apps-in-meetings?branch=pr-en-us-3065) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C8%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202104080459071876-3065%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=J7%2Fdl629tA6qItYDe56%2BfO1D7AHxPuKz0obvtKQfTIc%3D&st=2021-04-08T04%3A54%3A44Z&se=2021-05-09T04%3A59%3A44Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-12 22:40 UTC, rarang commented on msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md
> +| Federated | Not available | Not available | Not available | Not available | Not available | Not available. This is planned to be supported in the future. |
Remove this line "This is planned to be supported in the future" under Federated

2021-04-14 05:57 UTC, opbld32 commented
Docs Build status updates of commit _[561a2cf](https://github.com/MicrosoftDocs/msteams-docs/commits/561a2cf5c9268ee19482e42e01b0bf438c24b2b7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1677986-Usertypedetails/msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/teams-apps-in-meetings?branch=pr-en-us-3065) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C14%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202104140556593921-3065%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=sMqGWiKT8AxfJ7LQHKgnCUWjzW6WYTvJ5HH9Vs8IAgg%3D&st=2021-04-14T05%3A52%3A36Z&se=2021-05-15T05%3A57%3A36Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-14 05:58 UTC, opbld32 commented
Docs Build status updates of commit _[65243fe](https://github.com/MicrosoftDocs/msteams-docs/commits/65243feac8f805b2f74f864294e58177e34c5761)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1677986-Usertypedetails/msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/teams-apps-in-meetings?branch=pr-en-us-3065) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C14%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202104140557566860-3065%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2F8PLcRSRqso6dMaIWyfJo4DV3Rd8oeAl7bqEJ2aJI1Q%3D&st=2021-04-14T05%3A53%3A32Z&se=2021-05-15T05%3A58%3A32Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-15 03:19 UTC, rarang commented on msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md
>  | Anonymous user | Not available | Not available | Not available | Interactions in the meeting chat are allowed. | Interactions in the meeting chat from an adaptive card are allowed. | Not available
Note: Anonymous users inherit the global default user-level app permission policy. Refer to the "Manage Apps" section to learn more.

2021-04-15 03:20 UTC, rarang commented on msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md
>  | Anonymous user | Not available | Not available | Not available | Interactions in the meeting chat are allowed. | Interactions in the meeting chat from an adaptive card are allowed. | Not available
Add this on top of the table

2021-04-15 04:09 UTC, opbld32 commented
Docs Build status updates of commit _[451b833](https://github.com/MicrosoftDocs/msteams-docs/commits/451b833e22ed9df80afce8acb0e16b989eb094aa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1677986-Usertypedetails/msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/teams-apps-in-meetings?branch=pr-en-us-3065) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C15%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202104150409139282-3065%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=y79P%2B9TCGeo8aO8JwhkbKBuAGadnzJBRjLGLinx1bJA%3D&st=2021-04-15T04%3A04%3A53Z&se=2021-05-16T04%3A09%3A53Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-15 15:51 UTC, rarang approved these changes

2021-04-16 04:27 UTC, opbld31 commented
Docs Build status updates of commit _[fe38582](https://github.com/MicrosoftDocs/msteams-docs/commits/fe3858272e8bfc1207f0712e012ae7a05589e6a5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1677986-Usertypedetails/msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/teams-apps-in-meetings?branch=pr-en-us-3065) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C16%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202104160426482923-3065%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=fywGmlyZVonJPm8%2F5tCdZmLg2GmijU0MuF%2BMRwxnBRQ%3D&st=2021-04-16T04%3A22%3A23Z&se=2021-05-17T04%3A27%3A23Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-16 06:07 UTC, KirtiPereira requested changes
@v-rodriguezd - please validate and incorporate the changes.

2021-04-16 06:07 UTC, KirtiPereira commented on msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md
> +✔ An app is visible in a Teams meeting in the side panel or the in-meeting dialog box. Use the in-meeting dialog box to showcase actionable content for meeting participants. For more information , se
remove extra space '...information , see...'

2021-04-16 06:07 UTC, KirtiPereira commented on msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md
> +* **Anonymous**: Anonymous users do not have an AAD identity and are not federated with a tenant. The anonymous participant is like an external user, but their identity is not projected in the meetin
...an attendee.

2021-04-16 06:07 UTC, KirtiPereira commented on msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md
> +| Anonymous user | Not available | Not available | Not available | Interactions in the meeting chat are allowed. | Interactions in the meeting chat from an adaptive card are allowed. | Not available
Adaptive Card

2021-04-16 06:07 UTC, KirtiPereira commented on msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md
> +| Guest that is part of the tenant AAD | Interaction is allowed. Creating, updating, and deleting are not allowed. | Not available | Not available | Interactions in the meeting chat are allowed | Int
missing periods (.)

2021-04-16 07:16 UTC, opbld32 commented
Docs Build status updates of commit _[d0dc7c7](https://github.com/MicrosoftDocs/msteams-docs/commits/d0dc7c757e17e34b3eafab3189fe4ba4e6ae362f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1677986-Usertypedetails/msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/teams-apps-in-meetings?branch=pr-en-us-3065) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C16%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202104160716066658-3065%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=OzFz%2BgTsdVD6tFfkSModwJmzRZunNmLiY8%2FQDXY2m2s%3D&st=2021-04-16T07%3A11%3A43Z&se=2021-05-17T07%3A16%3A43Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-16 07:19 UTC, opbld30 commented
Docs Build status updates of commit _[9a8bf75](https://github.com/MicrosoftDocs/msteams-docs/commits/9a8bf75e234b56d94774ce4c8cafeb3bc258ddde)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1677986-Usertypedetails/msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/teams-apps-in-meetings?branch=pr-en-us-3065) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C16%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202104160719201483-3065%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=piQcrRZqBn8bdenJLJgz3q8kKfJHiZnovwESKJWInuo%3D&st=2021-04-16T07%3A14%3A54Z&se=2021-05-17T07%3A19%3A54Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-16 07:24 UTC, opbld33 commented
Docs Build status updates of commit _[9457957](https://github.com/MicrosoftDocs/msteams-docs/commits/94579578ac680885a599b455f4b3b2909e649069)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1677986-Usertypedetails/msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/teams-apps-in-meetings?branch=pr-en-us-3065) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C16%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202104160724044503-3065%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=dP3zalsIzMLJK37yKlR1VKxlQ6bHjfrzXAGrsNdipE8%3D&st=2021-04-16T07%3A19%3A42Z&se=2021-05-17T07%3A24%3A42Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-16 07:46 UTC, surbhigupta12 approved these changes
Approved.

2021-04-16 07:46 UTC, KirtiPereira approved these changes
Approved

2021-04-16 07:46 UTC, merged