[Build apps for Teams meetings][Doc revamp][1700925]
MicrosoftDocs/msteams-docs pull request #3119
Opened 2021-04-15 08:20 UTC by v-pmuthyala

Added note to side panel

2021-04-15 08:21 UTC, opbld30 commented
Docs Build status updates of commit _[c17e8b2](https://github.com/MicrosoftDocs/msteams-docs/commits/c17e8b25c9ed39638a791021472eea5b26481613)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Build-apps-for-Teams-meetings]Doc-enhancement]1700925]/msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3119) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C15%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202104150820331150-3119%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ovLAf%2F6E3VcLQceVXZetUNXYqxwRNJgpfz%2FTafCakhU%3D&st=2021-04-15T08%3A16%3A07Z&se=2021-05-16T08%3A21%3A07Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-15 09:57 UTC, opbld30 commented
Docs Build status updates of commit _[1f2f6b2](https://github.com/MicrosoftDocs/msteams-docs/commits/1f2f6b25340224cac3ccc74954804de9ea6ac681)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Build-apps-for-Teams-meetings]Doc-enhancement]1700925]/msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3119) | [Details](#user-content-351f2ba35302ce86d26f9fa3fc15a178-0faa16f3)

<a id="351f2ba35302ce86d26f9fa3fc15a178-0faa16f3"></a>
### [msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Build-apps-for-Teams-meetings]Doc-enhancement]1700925]/msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md)
 - **Line 320, Column 112**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /javascript/api/overview/msteams-client?view=msteams-client-js-latest. Otherwise, remove the view parameter.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C15%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202104150957083591-3119%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2BiLHj3x5WWcSW3%2BrAmC5qvwzcb0TxEh8RFHtaA6ioWA%3D&st=2021-04-15T09%3A52%3A40Z&se=2021-05-16T09%3A57%3A40Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-15 10:07 UTC, opbld32 commented
Docs Build status updates of commit _[0147882](https://github.com/MicrosoftDocs/msteams-docs/commits/014788239cee5cd0cecb6413f8f92f79d8808d71)_: 

### :white_check_mark: Validation status: partially passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-d45132b1)
[msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Build-apps-for-Teams-meetings]Doc-enhancement]1700925]/msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3119) |

<a id="d45132b1"></a>
###
 - **[Error-RuningBuildFailed]** `````Some unexpected errors happened when running build, please open a ticket in https://aka.ms/SiteHelp and include the error report for our team to troubleshoot`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C15%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202104151006164783-3119%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=u9vtCfI8uXi%2BIcGErH89GY%2FkCaBwXMjYDAaMQzrSKhw%3D&st=2021-04-15T10%3A02%3A04Z&se=2021-05-16T10%3A07%3A04Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-15 10:09 UTC, SubbaReddi approved these changes
Looks fine to me. Thanks

2021-04-15 10:32 UTC, opbld30 commented
Docs Build status updates of commit _[99efd5e](https://github.com/MicrosoftDocs/msteams-docs/commits/99efd5e81cbd5e3716ef2cd115e880c14a332d9f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Build-apps-for-Teams-meetings]Doc-enhancement]1700925]/msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3119) | [Details](#user-content-351f2ba35302ce86d26f9fa3fc15a178-ffd07740)

<a id="351f2ba35302ce86d26f9fa3fc15a178-ffd07740"></a>
### [msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Build-apps-for-Teams-meetings]Doc-enhancement]1700925]/msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md)
 - **Line 320, Column 112**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/javascript/api/overview/msteams-client?view=msteams-client-js-latest. Otherwise, remove the view parameter.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C15%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202104151031231979-3119%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Av8NNNjrMLl6fG86p%2FBvWfLlUujym6wDNUBnogug%2Fh0%3D&st=2021-04-15T10%3A27%3A03Z&se=2021-05-16T10%3A32%3A03Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-15 10:34 UTC, opbld33 commented
Docs Build status updates of commit _[d4eff6b](https://github.com/MicrosoftDocs/msteams-docs/commits/d4eff6b559d325d7638152fa20dd5914487962c6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Build-apps-for-Teams-meetings]Doc-enhancement]1700925]/msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3119) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C15%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202104151033475581-3119%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=o4p1LAbJU35J%2FCw4LUaEHLS7L0fR75oykL%2BsBhlFCpQ%3D&st=2021-04-15T10%3A29%3A23Z&se=2021-05-16T10%3A34%3A23Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-15 12:19 UTC, KirtiPereira requested changes

2021-04-15 12:19 UTC, KirtiPereira commented on msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md
> +> * The side panel is not supported in the older version of SDK. Make sure you use the latest version 1.9.0 of [Teams SDK](https://docs.microsoft.com/javascript/api/overview/msteams-client?view=mstea
Please rephrase the note to remove repetitive information and remove the *.

2021-04-16 05:18 UTC, opbld30 commented
Docs Build status updates of commit _[f427778](https://github.com/MicrosoftDocs/msteams-docs/commits/f427778bec604b2d2c62aec6a34a49fc84b2b76d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Build-apps-for-Teams-meetings]Doc-enhancement]1700925]/msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3119) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C16%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202104160517355257-3119%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ConUsg%2Fd3C%2FEUmvmX%2BNLy7tnvKdbNl5%2FK3go69ZtDz8%3D&st=2021-04-16T05%3A13%3A18Z&se=2021-05-17T05%3A18%3A18Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-16 07:03 UTC, opbld33 commented
Docs Build status updates of commit _[8c7e839](https://github.com/MicrosoftDocs/msteams-docs/commits/8c7e839ccbc44dc0fddefd08b25115ee46540880)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Build-apps-for-Teams-meetings]Doc-enhancement]1700925]/msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3119) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C16%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202104160703139691-3119%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ppuiWMBTtny9IPtkItm9uL68y607dBVQFmhw44Euny4%3D&st=2021-04-16T06%3A58%3A47Z&se=2021-05-17T07%3A03%3A47Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-16 07:39 UTC, surbhigupta12 approved these changes
Approved

2021-04-16 07:39 UTC, KirtiPereira approved these changes
Approved

2021-04-16 07:40 UTC, merged