Rev2 of the BUILD docs for Teams Toolkit
MicrosoftDocs/msteams-docs pull request #3426
Opened 2021-05-24 21:09 UTC by adrianhall

Re-build of the BUILD docs PR for Teams Toolkit

2021-05-24 21:10 UTC, opbld30 commented
Docs Build status updates of commit _[24ee20b](https://github.com/adrianhall/msteams-docs/commits/24ee20b97e5af9e2b69c92b27a6a746f43a282a8)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/get-started/first-app-bot.md](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/get-started/first-app-bot.md) | :x:Error | | [Details](#user-content-74c13a82cc6b1db413a8914d4d646b46-eccf856b)
[msteams-platform/get-started/first-app-react.md](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/get-started/first-app-react.md) | :x:Error | | [Details](#user-content-2e339651f32c3da97004fd697e64db30-eccf856b)
[msteams-platform/get-started/first-message-extension.md](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/get-started/first-message-extension.md) | :x:Error | | [Details](#user-content-3e168388da0a82701b78c341568efad0-eccf856b)
[msteams-platform/get-started/prerequisites.md](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/get-started/prerequisites.md) | :bulb:Suggestion | | [Details](#user-content-e0bde9a5a118edc11d9d2fe6651c792b-eccf856b)

<a id="74c13a82cc6b1db413a8914d4d646b46-eccf856b"></a>
### [msteams-platform/get-started/first-app-bot.md](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/get-started/first-app-bot.md)
 - **Line 142, Column 1**: **[Error-include-not-found]** `````Invalid include link: '~/includes/get-started/azure-provisioning-instructions.md'.`````

<a id="2e339651f32c3da97004fd697e64db30-eccf856b"></a>
### [msteams-platform/get-started/first-app-react.md](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/get-started/first-app-react.md)
 - **Line 122, Column 1**: **[Error-include-not-found]** `````Invalid include link: '~/includes/get-started/browser-private-launch.md'.`````
 - **Line 171, Column 1**: **[Error-include-not-found]** `````Invalid include link: '~/includes/get-started/azure-provisioning-instructions.md'.`````

<a id="3e168388da0a82701b78c341568efad0-eccf856b"></a>
### [msteams-platform/get-started/first-message-extension.md](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/get-started/first-message-extension.md)
 - **Line 149, Column 1**: **[Error-include-not-found]** `````Invalid include link: '~/includes/get-started/azure-provisioning-instructions.md'.`````

<a id="e0bde9a5a118edc11d9d2fe6651c792b-eccf856b"></a>
### [msteams-platform/get-started/prerequisites.md](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/get-started/prerequisites.md)
 - **Line 4, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Learn how to get started with Microsoft Teams app development and set up your environment.' is duplicated in 'build-your-first-app/build-first-app-overview.md(4,14)', 'get-started/prerequisites.md(4,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C24%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202105242110020944-3426%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=lJzZYx%2BBzSROBkvdZA8R3yfXqbdlFoEYmdzENGTidGM%3D&st=2021-05-24T21%3A05%3A30Z&se=2021-06-24T21%3A10%3A30Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-24 21:13 UTC, opbld32 commented
Docs Build status updates of commit _[b58f3a2](https://github.com/adrianhall/msteams-docs/commits/b58f3a289259b3d833bceb9d3836bdafb8e17738)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/get-started/prerequisites.md](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/get-started/prerequisites.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/prerequisites?branch=pr-en-us-3426) | [Details](#user-content-e0bde9a5a118edc11d9d2fe6651c792b-f3985980)
[msteams-platform/TOC.yml](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/account-commands.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/account-commands.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/prerequisites?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/app-project-files-spfx.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/app-project-files-spfx.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-spfx?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/blazor-completed-app.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/blazor-completed-app.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/blazor-file-layout.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/blazor-file-layout.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish1.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish2.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish3.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish3.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish4.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish4.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish5.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish5.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish6.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish6.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish7.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish7.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish8.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish8.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/bot-file-layout.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/bot-file-layout.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-bot?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/build-sharepoint-package.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/build-sharepoint-package.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-spfx?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/create-bot-registration.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/create-bot-registration.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-bot?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/create-new-project-intro.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/create-new-project-intro.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-bot?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/create-project-capabilities-bot.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/create-project-capabilities-bot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-bot?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/create-project-capabilities.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/create-project-capabilities.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-react?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/create-project-cloud-resources.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/create-p [...]

2021-05-24 21:30 UTC, opbld30 commented
Docs Build status updates of commit _[83a501a](https://github.com/adrianhall/msteams-docs/commits/83a501a0d70222ec1ac35b73b9b71a68e1a26cbf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/get-started/prerequisites.md](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/get-started/prerequisites.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/prerequisites?branch=pr-en-us-3426) | [Details](#user-content-e0bde9a5a118edc11d9d2fe6651c792b-cfeaacdd)
[msteams-platform/TOC.yml](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/account-commands.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/account-commands.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/prerequisites?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/app-project-files-spfx.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/app-project-files-spfx.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-spfx?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/blazor-completed-app.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/blazor-completed-app.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/blazor-file-layout.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/blazor-file-layout.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish1.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish2.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish3.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish3.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish4.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish4.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish5.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish5.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish6.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish6.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish7.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish7.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish8.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish8.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/bot-file-layout.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/bot-file-layout.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-bot?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/build-sharepoint-package.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/build-sharepoint-package.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-spfx?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/create-bot-registration.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/create-bot-registration.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-bot?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/create-new-project-intro.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/create-new-project-intro.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-bot?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/create-project-capabilities-bot.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/create-project-capabilities-bot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-bot?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/create-project-capabilities.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/create-project-capabilities.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-react?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/create-project-cloud-resources.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/create-p [...]

2021-05-24 21:43 UTC, heath-hamilton requested changes
Just a few comments, @adrianhall. Otherwise, good to go!

2021-05-24 21:43 UTC, heath-hamilton commented on msteams-platform/get-started/prerequisites.md
> +## Enable side-loading
```suggestion
## Enable sideloading
```

2021-05-24 21:43 UTC, heath-hamilton commented on msteams-platform/get-started/prerequisites.md
> +1. Select **Join Now*- and follow the onscreen instructions.
```suggestion
1. Select **Join Now** and follow the onscreen instructions.
```
Fixed bold issue.

2021-05-24 21:43 UTC, heath-hamilton commented on msteams-platform/get-started/first-app-bot.md
> +title: Get started - Build a conversational bot for Microsoft Teams
```suggestion
title: Get started - Build your first conversational bot
```

2021-05-24 21:43 UTC, heath-hamilton commented on msteams-platform/get-started/first-app-bot.md
> +# Build a conversational bot for Microsoft Teams
```suggestion
# Build your first conversational bot for Microsoft Teams
```
For consistency with the other GS topics.

2021-05-24 21:43 UTC, heath-hamilton commented on msteams-platform/get-started/first-message-extension.md
> +title: Get started - Build your first Teams Message Extension
```suggestion
title: Get started - Build your first messaging extension
```

2021-05-24 21:43 UTC, heath-hamilton commented on msteams-platform/get-started/first-message-extension.md
> +# Build and run your first message extension for Microsoft Teams
```suggestion
# Build and run your first messaging extension for Microsoft Teams
```
Should be "messaging" instead of "message".

2021-05-24 21:43 UTC, heath-hamilton commented on msteams-platform/get-started/first-message-extension.md
> +There are two types of Teams **message extensions**:
```suggestion
There are two types of Teams **messaging extensions**:
```

2021-05-24 21:43 UTC, heath-hamilton commented on msteams-platform/get-started/first-app-bot.md
> +A message extension uses the [Bot Framework](https://docs.botframework.com) to allow the user to interact with your service via a conversation.  After scaffolding, your project will look like this:
```suggestion
A messaging extension uses the [Bot Framework](https://docs.botframework.com) to allow the user to interact with your service via a conversation.  After scaffolding, your project will look like this:
```

2021-05-24 21:43 UTC, heath-hamilton commented on msteams-platform/get-started/first-message-extension.md
> +   > Message extensions rely on bots to provide a dialog between the user and your code.
```suggestion
   > Messaging extensions rely on bots to provide a dialog between the user and your code.
```

2021-05-24 21:43 UTC, heath-hamilton commented on msteams-platform/get-started/first-message-extension.md
> +A message extension uses the [Bot Framework](https://docs.botframework.com) to allow the user to interact with your service via a conversation.  After scaffolding, your project will look like this:
```suggestion
A messaging extension uses the [Bot Framework](https://docs.botframework.com) to allow the user to interact with your service via a conversation.  After scaffolding, your project will look like this:
```

2021-05-24 21:43 UTC, heath-hamilton commented on msteams-platform/get-started/first-message-extension.md
> +The bot code is stored in the `bot` directory.  The `bots/messageExtensionBot.js` is the main entry point for the message extension.
```suggestion
The bot code is stored in the `bot` directory.  The `bots/messageExtensionBot.js` is the main entry point for the messaging extension.
```

2021-05-24 21:43 UTC, heath-hamilton commented on msteams-platform/get-started/first-message-extension.md
> +- [ngrok](https://ngrok.io) is installed and used to provide a tunnel between Teams and your message extension.
```suggestion
- [ngrok](https://ngrok.io) is installed and used to provide a tunnel between Teams and your messaging extension.
```

2021-05-24 21:43 UTC, heath-hamilton commented on msteams-platform/get-started/first-message-extension.md
> +description: Create a message extension for Microsoft Teams using the Teams Toolkit
```suggestion
description: Create a messaging extension for Microsoft Teams using the Teams Toolkit.
```

2021-05-24 21:43 UTC, heath-hamilton commented on msteams-platform/get-started/first-message-extension.md
> +:::image type="content" source="../assets/images/teams-toolkit-v2/msgextn-completed-app.png" alt-text="Your Search-based message extension in action":::
```suggestion
:::image type="content" source="../assets/images/teams-toolkit-v2/msgextn-completed-app.png" alt-text="Your Search-based messaging extension in action":::
```

2021-05-24 21:52 UTC, opbld32 commented
Docs Build status updates of commit _[9044605](https://github.com/adrianhall/msteams-docs/commits/9044605af47a3db29e45d2f3ded5dcf41a2b3aef)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/get-started/first-app-blazor.md](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/get-started/first-app-blazor.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) | [Details](#user-content-76e9166813889db92cb5bab14d776970-d22b0164)
[msteams-platform/get-started/first-app-bot.md](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/get-started/first-app-bot.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-bot?branch=pr-en-us-3426) | [Details](#user-content-74c13a82cc6b1db413a8914d4d646b46-d22b0164)
[msteams-platform/get-started/first-app-react.md](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/get-started/first-app-react.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-react?branch=pr-en-us-3426) | [Details](#user-content-2e339651f32c3da97004fd697e64db30-d22b0164)
[msteams-platform/get-started/first-message-extension.md](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/get-started/first-message-extension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-message-extension?branch=pr-en-us-3426) | [Details](#user-content-3e168388da0a82701b78c341568efad0-d22b0164)
[msteams-platform/get-started/prerequisites.md](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/get-started/prerequisites.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/prerequisites?branch=pr-en-us-3426) | [Details](#user-content-e0bde9a5a118edc11d9d2fe6651c792b-d22b0164)
[msteams-platform/TOC.yml](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/account-commands.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/account-commands.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/prerequisites?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/app-project-files-spfx.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/app-project-files-spfx.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-spfx?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/blazor-completed-app.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/blazor-completed-app.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/blazor-file-layout.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/blazor-file-layout.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish1.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish2.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish3.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish3.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish4.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish4.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish5.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish5.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish6.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish6.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish7.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish7.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish8.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish8.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/bot-file-layout.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/bot-file-layout.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-bot?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/build-sharepoint-package.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/build-sharepoint-package.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-spfx?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/create-bot-registration.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/create-bot-registrati [...]

2021-05-24 21:54 UTC, heath-hamilton approved these changes
Approved. Ready for publication, @surbhigupta12.

2021-05-25 07:01 UTC, opbld30 commented
Docs Build status updates of commit _[2301668](https://github.com/adrianhall/msteams-docs/commits/23016682e24db9c0bd23dabdb05a1275f5f8da96)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/get-started/first-app-bot.md](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/get-started/first-app-bot.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-bot?branch=pr-en-us-3426) | [Details](#user-content-74c13a82cc6b1db413a8914d4d646b46-22525ad2)
[msteams-platform/get-started/first-app-react.md](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/get-started/first-app-react.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-react?branch=pr-en-us-3426) | [Details](#user-content-2e339651f32c3da97004fd697e64db30-22525ad2)
[msteams-platform/get-started/first-message-extension.md](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/get-started/first-message-extension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-message-extension?branch=pr-en-us-3426) | [Details](#user-content-3e168388da0a82701b78c341568efad0-22525ad2)
[msteams-platform/get-started/prerequisites.md](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/get-started/prerequisites.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/prerequisites?branch=pr-en-us-3426) | [Details](#user-content-e0bde9a5a118edc11d9d2fe6651c792b-22525ad2)
[msteams-platform/TOC.yml](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/account-commands.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/account-commands.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/prerequisites?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/app-project-files-spfx.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/app-project-files-spfx.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-spfx?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/blazor-completed-app.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/blazor-completed-app.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/blazor-file-layout.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/blazor-file-layout.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish1.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish2.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish3.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish3.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish4.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish4.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish5.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish5.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish6.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish6.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish7.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish7.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish8.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish8.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/bot-file-layout.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/bot-file-layout.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-bot?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/build-sharepoint-package.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/build-sharepoint-package.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-spfx?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/create-bot-registration.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/create-bot-registration.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-bot?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/create-new-project-intro.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/create-new-project-intro. [...]

2021-05-25 07:03 UTC, opbld32 commented
Docs Build status updates of commit _[6e4c8b7](https://github.com/adrianhall/msteams-docs/commits/6e4c8b77e6f1142dec60fde045949a70e8919f7e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/get-started/first-app-react.md](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/get-started/first-app-react.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-react?branch=pr-en-us-3426) | [Details](#user-content-2e339651f32c3da97004fd697e64db30-10eff082)
[msteams-platform/get-started/first-message-extension.md](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/get-started/first-message-extension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-message-extension?branch=pr-en-us-3426) | [Details](#user-content-3e168388da0a82701b78c341568efad0-10eff082)
[msteams-platform/get-started/prerequisites.md](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/get-started/prerequisites.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/prerequisites?branch=pr-en-us-3426) | [Details](#user-content-e0bde9a5a118edc11d9d2fe6651c792b-10eff082)
[msteams-platform/TOC.yml](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/account-commands.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/account-commands.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/prerequisites?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/app-project-files-spfx.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/app-project-files-spfx.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-spfx?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/blazor-completed-app.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/blazor-completed-app.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/blazor-file-layout.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/blazor-file-layout.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish1.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish2.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish3.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish3.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish4.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish4.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish5.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish5.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish6.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish6.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish7.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish7.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish8.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish8.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/bot-file-layout.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/bot-file-layout.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-bot?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/build-sharepoint-package.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/build-sharepoint-package.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-spfx?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/create-bot-registration.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/create-bot-registration.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-bot?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/create-new-project-intro.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/create-new-project-intro.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-bot?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/create-project-capabilities-bot.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/create-proje [...]

2021-05-25 07:05 UTC, opbld32 commented
Docs Build status updates of commit _[319b497](https://github.com/adrianhall/msteams-docs/commits/319b497f24871c4b4e7c0e9ee647d1944f9fa718)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/get-started/first-message-extension.md](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/get-started/first-message-extension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-message-extension?branch=pr-en-us-3426) | [Details](#user-content-3e168388da0a82701b78c341568efad0-51ee0074)
[msteams-platform/get-started/prerequisites.md](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/get-started/prerequisites.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/prerequisites?branch=pr-en-us-3426) | [Details](#user-content-e0bde9a5a118edc11d9d2fe6651c792b-51ee0074)
[msteams-platform/TOC.yml](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/account-commands.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/account-commands.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/prerequisites?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/app-project-files-spfx.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/app-project-files-spfx.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-spfx?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/blazor-completed-app.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/blazor-completed-app.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/blazor-file-layout.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/blazor-file-layout.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish1.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish2.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish3.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish3.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish4.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish4.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish5.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish5.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish6.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish6.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish7.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish7.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish8.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish8.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/bot-file-layout.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/bot-file-layout.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-bot?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/build-sharepoint-package.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/build-sharepoint-package.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-spfx?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/create-bot-registration.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/create-bot-registration.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-bot?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/create-new-project-intro.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/create-new-project-intro.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-bot?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/create-project-capabilities-bot.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/create-project-capabilities-bot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-bot?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/create-project-capabilities.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/cr [...]

2021-05-25 07:08 UTC, opbld33 commented
Docs Build status updates of commit _[6caf0ff](https://github.com/adrianhall/msteams-docs/commits/6caf0ff3e59e27b2806d7f93b63387488bc00e62)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/get-started/prerequisites.md](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/get-started/prerequisites.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/prerequisites?branch=pr-en-us-3426) | [Details](#user-content-e0bde9a5a118edc11d9d2fe6651c792b-a4b3048f)
[msteams-platform/TOC.yml](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/account-commands.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/account-commands.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/prerequisites?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/app-project-files-spfx.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/app-project-files-spfx.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-spfx?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/blazor-completed-app.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/blazor-completed-app.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/blazor-file-layout.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/blazor-file-layout.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish1.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish2.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish3.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish3.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish4.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish4.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish5.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish5.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish6.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish6.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish7.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish7.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish8.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish8.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/bot-file-layout.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/bot-file-layout.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-bot?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/build-sharepoint-package.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/build-sharepoint-package.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-spfx?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/create-bot-registration.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/create-bot-registration.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-bot?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/create-new-project-intro.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/create-new-project-intro.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-bot?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/create-project-capabilities-bot.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/create-project-capabilities-bot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-bot?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/create-project-capabilities.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/create-project-capabilities.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-react?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/create-project-cloud-resources.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/create-p [...]

2021-05-25 07:10 UTC, opbld30 commented
Docs Build status updates of commit _[a0e613c](https://github.com/adrianhall/msteams-docs/commits/a0e613ce179ec7a28990a4d8fa13f0a95a23d892)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/account-commands.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/account-commands.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/prerequisites?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/app-project-files-spfx.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/app-project-files-spfx.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-spfx?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/blazor-completed-app.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/blazor-completed-app.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/blazor-file-layout.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/blazor-file-layout.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish1.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish2.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish3.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish3.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish4.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish4.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish5.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish5.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish6.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish6.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish7.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish7.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish8.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/blazor-vs2019-publish8.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/bot-file-layout.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/bot-file-layout.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-bot?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/build-sharepoint-package.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/build-sharepoint-package.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-spfx?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/create-bot-registration.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/create-bot-registration.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-bot?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/create-new-project-intro.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/create-new-project-intro.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-bot?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/create-project-capabilities-bot.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/create-project-capabilities-bot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-bot?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/create-project-capabilities.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/create-project-capabilities.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-react?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/create-project-cloud-resources.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit-v2/create-project-cloud-resources.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-react?branch=pr-en-us-3426) |
[msteams-platform/assets/images/teams-toolkit-v2/create-project-hosting.png](https://github.com/adrianhall/msteams-docs/blob/adhal-teamsfx-build-rev2/msteams-platform/assets/images/teams-toolkit [...]

2021-05-25 07:10 UTC, surbhigupta12 approved these changes
Approved

2021-05-25 07:21 UTC, merged