[Docbug][move-section][1809608]
MicrosoftDocs/msteams-docs pull request #3514
Opened 2021-05-28 06:06 UTC by Mahesh2516

moved a topic as a section in another

2021-05-28 06:07 UTC, opbld32 commented
Docs Build status updates of commit _[9fa57d4](https://github.com/MicrosoftDocs/msteams-docs/commits/9fa57d4b9234aca61a5342c6e10681fcb8d47ffa)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md](https://github.com/MicrosoftDocs/msteams-docs/blob/docbug-move-section-1809608/msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/search-commands/respond-to-search?branch=pr-en-us-3514) | [Details](#user-content-d88ceab071c788c3d5fd0cd66fb710f8-1547ccdc)
[msteams-platform/messaging-extensions/how-to/action-commands/respond-to-task-module-submit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/docbug-move-section-1809608/msteams-platform/messaging-extensions/how-to/action-commands/respond-to-task-module-submit.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/action-commands/respond-to-task-module-submit?branch=pr-en-us-3514) | [Details](#user-content-7628845123c01ee0841c24838cff279a-1547ccdc)
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/docbug-move-section-1809608/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-message-extension?branch=pr-en-us-3514) |
[msteams-platform/get-started/first-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/docbug-move-section-1809608/msteams-platform/get-started/first-message-extension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-message-extension?branch=pr-en-us-3514) |
[msteams-platform/messaging-extensions/how-to/add-configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/docbug-move-section-1809608/msteams-platform/messaging-extensions/how-to/add-configuration-page.md) | :white_check_mark:Succeeded | |

<a id="d88ceab071c788c3d5fd0cd66fb710f8-1547ccdc"></a>
### [msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md](https://github.com/MicrosoftDocs/msteams-docs/blob/docbug-move-section-1809608/msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md)
 - **Line 344, Column 1**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '~/messaging-extensions/how-to/add-configuration-page.md'.`````

<a id="7628845123c01ee0841c24838cff279a-1547ccdc"></a>
### [msteams-platform/messaging-extensions/how-to/action-commands/respond-to-task-module-submit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/docbug-move-section-1809608/msteams-platform/messaging-extensions/how-to/action-commands/respond-to-task-module-submit.md)
 - **Line 24, Column 3**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '~/messaging-extensions/how-to/add-configuration-page.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C28%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202105280606282777-3514%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=a9GWe76X28Sw4b8Ro1kaVvwbAj2wwWzBnV2orfeSt90%3D&st=2021-05-28T06%3A02%3A00Z&se=2021-06-28T06%3A07%3A00Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-28 06:17 UTC, opbld32 commented
Docs Build status updates of commit _[054a14a](https://github.com/MicrosoftDocs/msteams-docs/commits/054a14af591c3b352ba2bf4728ca41e7e03b0ca2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/messaging-extensions/how-to/action-commands/respond-to-task-module-submit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/docbug-move-section-1809608/msteams-platform/messaging-extensions/how-to/action-commands/respond-to-task-module-submit.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/action-commands/respond-to-task-module-submit?branch=pr-en-us-3514) | [Details](#user-content-7628845123c01ee0841c24838cff279a-f81e8ce5)
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/docbug-move-section-1809608/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-message-extension?branch=pr-en-us-3514) |
[msteams-platform/get-started/first-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/docbug-move-section-1809608/msteams-platform/get-started/first-message-extension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-message-extension?branch=pr-en-us-3514) |
[msteams-platform/messaging-extensions/how-to/add-configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/docbug-move-section-1809608/msteams-platform/messaging-extensions/how-to/add-configuration-page.md) | :white_check_mark:Succeeded | |
[msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md](https://github.com/MicrosoftDocs/msteams-docs/blob/docbug-move-section-1809608/msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/search-commands/respond-to-search?branch=pr-en-us-3514) |

<a id="7628845123c01ee0841c24838cff279a-f81e8ce5"></a>
### [msteams-platform/messaging-extensions/how-to/action-commands/respond-to-task-module-submit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/docbug-move-section-1809608/msteams-platform/messaging-extensions/how-to/action-commands/respond-to-task-module-submit.md)
 - **Line 24, Column 3**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '~/messaging-extensions/how-to/add-configuration-page.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C28%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202105280616314798-3514%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2Fj9J0d3wZG69o%2F9Hc2gcRFOYFnQWvv8W2TirnbdHSgk%3D&st=2021-05-28T06%3A12%3A10Z&se=2021-06-28T06%3A17%3A10Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-28 06:20 UTC, opbld32 commented
Docs Build status updates of commit _[fd57f47](https://github.com/MicrosoftDocs/msteams-docs/commits/fd57f47e4d33fd1a41e212922de897e2db0591b6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/docbug-move-section-1809608/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-message-extension?branch=pr-en-us-3514) |
[msteams-platform/get-started/first-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/docbug-move-section-1809608/msteams-platform/get-started/first-message-extension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-message-extension?branch=pr-en-us-3514) |
[msteams-platform/messaging-extensions/how-to/action-commands/respond-to-task-module-submit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/docbug-move-section-1809608/msteams-platform/messaging-extensions/how-to/action-commands/respond-to-task-module-submit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/action-commands/respond-to-task-module-submit?branch=pr-en-us-3514) |
[msteams-platform/messaging-extensions/how-to/add-configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/docbug-move-section-1809608/msteams-platform/messaging-extensions/how-to/add-configuration-page.md) | :white_check_mark:Succeeded | |
[msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md](https://github.com/MicrosoftDocs/msteams-docs/blob/docbug-move-section-1809608/msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/search-commands/respond-to-search?branch=pr-en-us-3514) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C28%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202105280619428505-3514%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2FIMs1sVW9tys15he5ngUnRPgJ2UC9NRdRspo8y48y6Q%3D&st=2021-05-28T06%3A15%3A30Z&se=2021-06-28T06%3A20%3A30Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-31 10:44 UTC, Wajeed-msft requested changes

2021-05-31 10:44 UTC, Wajeed-msft commented on msteams-platform/get-started/first-message-extension.md
> +## Add a configuration page to your messaging extension on GitHub
GitHub part in title is bit confusing. Could you please check if this can be changed?

2021-05-31 10:44 UTC, Wajeed-msft commented on msteams-platform/get-started/first-message-extension.md
> +The Teams Search Auth Config for sample projects on GitHub, demonstrate how to create messaging extensions that include a configuration page and Bot Service authentication. The samples also demonstra
Attached sample do not have authentication implemented, so we can remove **and Bot Service authentication** part or link mentioned here : https://github.com/microsoft/BotBuilder-Samples#teams-samples on Point 52.

2021-05-31 10:44 UTC, Wajeed-msft commented on msteams-platform/get-started/first-message-extension.md
> +> [View more Bot Framework Samples on GitHub](https://github.com/microsoft/BotBuilder-Samples)
Could you please link to this section? https://github.com/OfficeDev/microsoft-teams-samples#messaging-extensions-samples-using-the-v4-sdk

2021-05-31 10:54 UTC, opbld32 commented
Docs Build status updates of commit _[e21013d](https://github.com/MicrosoftDocs/msteams-docs/commits/e21013d3e09658ad20d604bfcbdf4f28d5f2e14b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/docbug-move-section-1809608/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-message-extension?branch=pr-en-us-3514) |
[msteams-platform/get-started/first-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/docbug-move-section-1809608/msteams-platform/get-started/first-message-extension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-message-extension?branch=pr-en-us-3514) |
[msteams-platform/messaging-extensions/how-to/action-commands/respond-to-task-module-submit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/docbug-move-section-1809608/msteams-platform/messaging-extensions/how-to/action-commands/respond-to-task-module-submit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/action-commands/respond-to-task-module-submit?branch=pr-en-us-3514) |
[msteams-platform/messaging-extensions/how-to/add-configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/docbug-move-section-1809608/msteams-platform/messaging-extensions/how-to/add-configuration-page.md) | :white_check_mark:Succeeded | |
[msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md](https://github.com/MicrosoftDocs/msteams-docs/blob/docbug-move-section-1809608/msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/search-commands/respond-to-search?branch=pr-en-us-3514) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C31%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202105311053195417-3514%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=5Ct2ylig9AtHEekW10WNtzoM3auGikcHgDvBQqQyiLM%3D&st=2021-05-31T10%3A49%3A22Z&se=2021-07-01T10%3A54%3A22Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-31 11:00 UTC, Wajeed-msft approved these changes

2021-05-31 11:07 UTC, surbhigupta12 approved these changes
Approved

2021-05-31 11:07 UTC, merged