[Docrevamp][Buildtabs][1684145]
MicrosoftDocs/msteams-docs pull request #3530
Opened 2021-06-01 12:13 UTC by v-rodriguezd

Revamp of build tabs module.

2021-06-01 12:13 UTC, opbld31 commented
Docs Build status updates of commit _[fac576b](https://github.com/MicrosoftDocs/msteams-docs/commits/fac576b7e3250f9c8453bb99b436503ebfac9f34)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-f2f0d333)

<a id="f2f0d333"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C1%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202106011213040855-3530%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=XvvaWBP2qc%2B1n5K5DrXQuUlALu2ri%2B8OOjD95hflV6M%3D&st=2021-06-01T12%3A08%3A21Z&se=2021-07-02T12%3A13%3A21Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-01 12:17 UTC, opbld32 commented
Docs Build status updates of commit _[9eca11e](https://github.com/MicrosoftDocs/msteams-docs/commits/9eca11e356ad60ebbb17eec80f7ed1f27f666375)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/what-are-tabs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?branch=pr-en-us-3530) | [Details](#user-content-b15c6f8d479be682a8d146c5929a3aa0-38786e4d)
[msteams-platform/includes/tabs/node-js-yeoman-prereq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/node-js-yeoman-prereq.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) | [Details](#user-content-00d939954906805eadaa6d1ce53951b4-38786e4d)
[msteams-platform/includes/tabs/dotnet-core-prereq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-core-prereq.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) | [Details](#user-content-63f45c29c641d729bf9ae42f8ada9acb-38786e4d)
[msteams-platform/includes/tabs/dotnet-ngrok-intro.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-ngrok-intro.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) | [Details](#user-content-25fed10b8237eb395acc430cda80c425-38786e4d)
[msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) | [Details](#user-content-dafc8b859211aaf2987134bb9f7a6b14-38786e4d)
[msteams-platform/includes/tabs/dotnet-update-personal-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-update-personal-app.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) | [Details](#user-content-d1cd15c457560dee67a45bbb7043bd26-38786e4d)
[msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) | [Details](#user-content-94b0e3db0e1631404cabf87725aa0bdc-38786e4d)
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tabs/tabs.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tabs/tabs.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-channel-group-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-personal-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/content-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/content-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/tab-requirements.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/tab-requirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/tab-requirements?branch=pr-en-us-3530) |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core-mvc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core-mvc.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-node-yeoman.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-node-yeoman.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core-mvc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core-mvc.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-personal-tab-node-yeoman.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-personal-tab-node-yeoman.md) | :white_check_mark:Succeeded | |

<a id="b15c6f8d479be682a8d146c5929a3aa0-38786e4d"></a>
### [msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/what-are-tabs.md)
 - **Line 14, Column 1**: **[Warning-[alt-text-bad-value](https://review.docs.microsoft.com/help/contribute/validation-ref/alt-text-bad-value?branch=main)]** `````Alt text 'Tabs' is the same as the image file name. This redundancy adds no value for users of screen readers. For accessibility, add more descriptive alt text.`````

<a id="00d939954906805eadaa6d1ce53951b4-38786e4d"></a>
### [msteams-platform/includes/tabs/node-js-yeoman-prereq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/node-js-yeoman-prereq.md)
 - **Line 1, Column 1**: **[Warning-[duplicate-h2s](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/duplicate-h2s?branch=master)]** `````Duplicate heading: 'H2 'Prerequisites'(tabs/how-to/create-channel-group-tab.md(21,1) -> includes/tabs/node-js-yeoman-prereq.md)'. Each second level heading (H2) in an article must be unique.`````
 - **Line 1, Column 1**: **[Warning-[duplicate-h2s](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/duplicate-h2s?branch=master)]** `````Duplicate heading: 'H2 'Prerequisites' [...]

2021-06-01 12:37 UTC, opbld31 commented
Docs Build status updates of commit _[bd36925](https://github.com/MicrosoftDocs/msteams-docs/commits/bd3692587625959a905f1298afbdf1dedb3db9d1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/includes/tabs/dotnet-core-prereq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-core-prereq.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) | [Details](#user-content-63f45c29c641d729bf9ae42f8ada9acb-e2f46822)
[msteams-platform/includes/tabs/dotnet-ngrok-intro.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-ngrok-intro.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) | [Details](#user-content-25fed10b8237eb395acc430cda80c425-e2f46822)
[msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) | [Details](#user-content-94b0e3db0e1631404cabf87725aa0bdc-e2f46822)
[msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) | [Details](#user-content-dafc8b859211aaf2987134bb9f7a6b14-e2f46822)
[msteams-platform/includes/tabs/dotnet-update-personal-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-update-personal-app.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) | [Details](#user-content-d1cd15c457560dee67a45bbb7043bd26-e2f46822)
[msteams-platform/includes/tabs/node-js-yeoman-prereq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/node-js-yeoman-prereq.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) | [Details](#user-content-00d939954906805eadaa6d1ce53951b4-e2f46822)
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tabs/tabs.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tabs/tabs.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-channel-group-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-personal-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/content-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/content-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/tab-requirements.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/tab-requirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/tab-requirements?branch=pr-en-us-3530) |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core-mvc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core-mvc.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-node-yeoman.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-node-yeoman.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core-mvc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core-mvc.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-personal-tab-node-yeoman.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-personal-tab-node-yeoman.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/what-are-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?branch=pr-en-us-3530) |

<a id="63f45c29c641d729bf9ae42f8ada9acb-e2f46822"></a>
### [msteams-platform/includes/tabs/dotnet-core-prereq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-core-prereq.md)
 - **Line 1, Column 1**: **[Warning-[duplicate-h2s](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/duplicate-h2s?branch=master)]** `````Duplicate heading: 'H2 'Prerequisites for Teams apps'(tabs/how-to/create-personal-tab.md(141,1) -> includes/tabs/dotnet-core-prereq.md)'. Each second level heading (H2) in an article must be unique.`````
 - **Line 1, Column 1**: **[Warning-[duplicate-h2s](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/duplicate-h2s?branch=master)]** `````Duplicate heading: 'H2 'Prerequisites for Teams apps'(tabs/how-to/create-personal-tab.md(247,1) -> includes/tabs/dotnet-core-prereq.md)'. Each second level heading (H2) in an article must be unique.`````
 - **Line 1, Column 1**: **[Warning-[duplicate-h2s](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/duplicate-h2s?branch=master)]** `````Duplicate heading: 'H2 'Prerequisites for Teams apps'(tabs/how-to/create-channel-group-tab.md(97,1) -> includes/tabs/dotnet-core-prereq.md)'. Each second level heading (H2) in an article must be unique.`````
 - **Line 1, Column 1**: **[Warning-[duplicate-h2s](https://revie [...]

2021-06-01 13:11 UTC, opbld31 commented
Docs Build status updates of commit _[0678f9e](https://github.com/MicrosoftDocs/msteams-docs/commits/0678f9e7fc1498213ff70f6411f8ab6546065fcb)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/includes/tabs/dotnet-ngrok-intro.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-ngrok-intro.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) | [Details](#user-content-25fed10b8237eb395acc430cda80c425-cb280f4a)
[msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) | [Details](#user-content-94b0e3db0e1631404cabf87725aa0bdc-cb280f4a)
[msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) | [Details](#user-content-dafc8b859211aaf2987134bb9f7a6b14-cb280f4a)
[msteams-platform/includes/tabs/dotnet-update-personal-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-update-personal-app.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) | [Details](#user-content-d1cd15c457560dee67a45bbb7043bd26-cb280f4a)
[msteams-platform/includes/tabs/dotnet-core-prereq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-core-prereq.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) | [Details](#user-content-63f45c29c641d729bf9ae42f8ada9acb-cb280f4a)
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tabs/tabs.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tabs/tabs.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/node-js-yeoman-prereq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/node-js-yeoman-prereq.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-channel-group-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-personal-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/content-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/content-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/tab-requirements.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/tab-requirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/tab-requirements?branch=pr-en-us-3530) |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core-mvc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core-mvc.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-node-yeoman.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-node-yeoman.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core-mvc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core-mvc.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-personal-tab-node-yeoman.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-personal-tab-node-yeoman.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/what-are-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?branch=pr-en-us-3530) |

<a id="25fed10b8237eb395acc430cda80c425-cb280f4a"></a>
### [msteams-platform/includes/tabs/dotnet-ngrok-intro.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-ngrok-intro.md)
 - **Line 1, Column 1**: **[Warning-[duplicate-h2s](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/duplicate-h2s?branch=master)]** `````Duplicate heading: 'H2 'Establish a secure tunnel to your tab for Teams'(tabs/how-to/create-personal-tab.md(220,1) -> includes/tabs/dotnet-ngrok-intro.md)'. Each second level heading (H2) in an article must be unique.`````
 - **Line 1, Column 1**: **[Warning-[duplicate-h2s](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/duplicate-h2s?branch=master)]** `````Duplicate heading: 'H2 'Establish a secure tunnel to your tab for Teams'(tabs/how-to/create-personal-tab.md(339,1) -> includes/tabs/dotnet-ngrok-intro.md)'. Each second level heading (H2) in an article must be unique.`````
 - **Line 1, Column 1**: **[Warning-[duplicate-h2s](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/duplicate-h2s?branch=master)]** `````Duplicate heading: 'H2 'Establish a secure tunnel to your tab for Teams'(tabs/how-to/create-channel-group-tab.md(177,1) -> includes/tabs/dotnet-ngrok-intro.md)'. Each second level heading (H2) in an article must be unique.`````
 - **Line 1, Column 1**: **[Warning-[duplicate-h2s](https://rev [...]

2021-06-02 05:24 UTC, opbld31 commented
Docs Build status updates of commit _[7330346](https://github.com/MicrosoftDocs/msteams-docs/commits/733034653522be3c81c04e7ebab4a7bda0c64eb4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/includes/tabs/node-js-yeoman-prereq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/node-js-yeoman-prereq.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) | [Details](#user-content-00d939954906805eadaa6d1ce53951b4-923a65a9)
[msteams-platform/includes/tabs/dotnet-core-prereq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-core-prereq.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) | [Details](#user-content-63f45c29c641d729bf9ae42f8ada9acb-923a65a9)
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tabs/tabs.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tabs/tabs.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-channel-group-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-personal-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/content-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/content-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/tab-requirements.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/tab-requirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/tab-requirements?branch=pr-en-us-3530) |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core-mvc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core-mvc.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-node-yeoman.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-node-yeoman.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core-mvc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core-mvc.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-personal-tab-node-yeoman.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-personal-tab-node-yeoman.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/what-are-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?branch=pr-en-us-3530) |

<a id="00d939954906805eadaa6d1ce53951b4-923a65a9"></a>
### [msteams-platform/includes/tabs/node-js-yeoman-prereq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/node-js-yeoman-prereq.md)
 - **Line 1, Column 1**: **[Warning-[duplicate-h2s](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/duplicate-h2s?branch=master)]** `````Duplicate heading: 'H2 'Prerequisites'(tabs/how-to/create-personal-tab.md(21,1) -> includes/tabs/node-js-yeoman-prereq.md)'. Each second level heading (H2) in an article must be unique.`````
 - **Line 1, Column 1**: **[Warning-[duplicate-h2s](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/duplicate-h2s?branch=master)]** `````Duplicate heading: 'H2 'Prerequisites'(tabs/how-to/create-channel-group-tab.md(21,1) -> includes/tabs/node-js-yeoman-prereq.md)'. Each second level heading (H2) in an article must be unique.`````

<a id="63f45c29c641d729bf9ae42f8ada9acb-923a65a9"></a>
### [msteams-platform/includes/tabs/dotnet-core-prereq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-core-prereq.md)
 - **Line 1, Column 1**: **[Warning-[duplicate-h2s](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/duplicate-h2s?branch=master)]** `````Duplicate heading: 'H2 'Prerequisites'(tabs/how-to/create-personal-tab.md(357,1) -> includes/tabs/dotnet-core-prereq.md)'. Each second level heading (H2) in an article must be unique.`````
 - **Line 1, Column 1**: **[Warning-[duplicate-h2s](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/duplicate-h2s?branch=master)]** `````Duplicate heading: 'H2 'Prerequisites'(tabs/how-to/create-channel-group-tab.md(345,1) -> includes/tabs/dotnet-core-prereq.md)'. Each second level heading (H2) in an article must be unique.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C2%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202106020522493186-3530%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=4VmYqEsVaPOrSTCVfwX0jZD1kNvemq9GPjmvFC9cTxw%3D&st=2021-06-02T05%3A19%3A04Z&se=2021-07-03T05%3A24%3A04Z&sp=r).

If you see build warnings/errors with permission issues, it might b [...]

2021-06-02 05:30 UTC, opbld33 commented
Docs Build status updates of commit _[51918b1](https://github.com/MicrosoftDocs/msteams-docs/commits/51918b1e8013c5ca5af6d3d950056baff21bcf81)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-channel-group-tab.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) | [Details](#user-content-15c143b9bb75f20a5acd815ed765d740-073f1ca9)
[msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-personal-tab.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) | [Details](#user-content-ba3b05282a3fc888b3c1d57fa2074e3b-073f1ca9)
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tabs/tabs.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tabs/tabs.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/content-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/content-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/tab-requirements.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/tab-requirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/tab-requirements?branch=pr-en-us-3530) |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core-mvc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core-mvc.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-node-yeoman.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-node-yeoman.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core-mvc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core-mvc.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-personal-tab-node-yeoman.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-personal-tab-node-yeoman.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/what-are-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?branch=pr-en-us-3530) |

<a id="15c143b9bb75f20a5acd815ed765d740-073f1ca9"></a>
### [msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-channel-group-tab.md)
 - **Line 97, Column 1**: **[Warning-[duplicate-h2s](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/duplicate-h2s?branch=master)]** `````Duplicate heading: 'H2 'Prerequisites for Teams apps''. Each second level heading (H2) in an article must be unique.`````
 - **Line 345, Column 1**: **[Warning-[duplicate-h2s](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/duplicate-h2s?branch=master)]** `````Duplicate heading: 'H2 'Prerequisites for Teams apps''. Each second level heading (H2) in an article must be unique.`````

<a id="ba3b05282a3fc888b3c1d57fa2074e3b-073f1ca9"></a>
### [msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-personal-tab.md)
 - **Line 21, Column 1**: **[Warning-[duplicate-h2s](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/duplicate-h2s?branch=master)]** `````Duplicate heading: 'H2 'Prerequisites for Teams apps''. Each second level heading (H2) in an article must be unique.`````
 - **Line 225, Column 1**: **[Warning-[duplicate-h2s](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/duplicate-h2s?branch=master)]** `````Duplicate heading: 'H2 'Prerequisites for Teams apps''. Each second level heading (H2) in an article must be unique.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C2%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202106020529434274-3530%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=DdriwabJZZJln16AlY32Vo9Lnv2%2BYs6nu3hb3UyyYCI%3D&st=2021-06-02T05%3A25%3A24Z&se=2021-07-03T05%3A30%3A24Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-bra [...]

2021-06-02 05:32 UTC, opbld32 commented
Docs Build status updates of commit _[97ddffb](https://github.com/MicrosoftDocs/msteams-docs/commits/97ddffbadd8a4b373018d9ec99560845ec7482d1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-channel-group-tab.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) | [Details](#user-content-15c143b9bb75f20a5acd815ed765d740-bdd47fb2)
[msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-personal-tab.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) | [Details](#user-content-ba3b05282a3fc888b3c1d57fa2074e3b-bdd47fb2)
[msteams-platform/includes/tabs/node-js-yeoman-prereq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/node-js-yeoman-prereq.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) | [Details](#user-content-00d939954906805eadaa6d1ce53951b4-bdd47fb2)
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tabs/tabs.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tabs/tabs.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/content-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/content-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/tab-requirements.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/tab-requirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/tab-requirements?branch=pr-en-us-3530) |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core-mvc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core-mvc.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-node-yeoman.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-node-yeoman.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core-mvc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core-mvc.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-personal-tab-node-yeoman.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-personal-tab-node-yeoman.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/what-are-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?branch=pr-en-us-3530) |

<a id="15c143b9bb75f20a5acd815ed765d740-bdd47fb2"></a>
### [msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-channel-group-tab.md)
 - **Line 345, Column 1**: **[Warning-[duplicate-h2s](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/duplicate-h2s?branch=master)]** `````Duplicate heading: 'H2 'Prerequisites''. Each second level heading (H2) in an article must be unique.`````

<a id="ba3b05282a3fc888b3c1d57fa2074e3b-bdd47fb2"></a>
### [msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-personal-tab.md)
 - **Line 225, Column 1**: **[Warning-[duplicate-h2s](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/duplicate-h2s?branch=master)]** `````Duplicate heading: 'H2 'Prerequisites''. Each second level heading (H2) in an article must be unique.`````
 - **Line 441, Column 1**: **[Warning-[duplicate-h2s](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/duplicate-h2s?branch=master)]** `````Duplicate heading: 'H2 'Prerequisites''. Each second level heading (H2) in an article must be unique.`````

<a id="00d939954906805eadaa6d1ce53951b4-bdd47fb2"></a>
### [msteams-platform/includes/tabs/node-js-yeoman-prereq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/node-js-yeoman-prereq.md)
 - **Line 1, Column 1**: **[Warning-[duplicate-h2s](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/duplicate-h2s?branch=master)]** `````Duplicate heading: 'H2 'Prerequisites'(tabs/how-to/create-channel-group-tab.md(21,1) -> includes/tabs/node-js-yeoman-prereq.md)'. Each second level heading (H2) in an article must be unique.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C2%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202106020532173866-3530%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=5Ufmo0pMMBaIbKyt4dl%2FsUhiRrRtwlnxYWrRBzDQa9o%3D&st=2021-06-02T05%3A27%3A56Z&se=2021-07-03T05%3A32%3A56Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as rela [...]

2021-06-02 05:37 UTC, opbld30 commented
Docs Build status updates of commit _[1ce15b9](https://github.com/MicrosoftDocs/msteams-docs/commits/1ce15b9b4d21420ac322ab5cda46e51a6c539543)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tabs/tabs.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tabs/tabs.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/node-js-yeoman-prereq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/node-js-yeoman-prereq.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-channel-group-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-personal-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/content-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/content-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/tab-requirements.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/tab-requirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/tab-requirements?branch=pr-en-us-3530) |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core-mvc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core-mvc.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-node-yeoman.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-node-yeoman.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core-mvc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core-mvc.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-personal-tab-node-yeoman.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-personal-tab-node-yeoman.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/what-are-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?branch=pr-en-us-3530) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C2%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202106020536443005-3530%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=0E6hXE0IGLH3fx%2F%2F1qhAi2l3uZi3YuweUhUkNK3HrCY%3D&st=2021-06-02T05%3A32%3A23Z&se=2021-07-03T05%3A37%3A23Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-02 05:38 UTC, opbld31 commented
Docs Build status updates of commit _[6c17a68](https://github.com/MicrosoftDocs/msteams-docs/commits/6c17a68a707f338dc729fbb9020e14ea98cdffb3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tabs/tabs.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tabs/tabs.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/node-js-yeoman-prereq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/node-js-yeoman-prereq.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-channel-group-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-personal-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/content-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/content-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/tab-requirements.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/tab-requirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/tab-requirements?branch=pr-en-us-3530) |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core-mvc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core-mvc.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-node-yeoman.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-node-yeoman.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core-mvc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core-mvc.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-personal-tab-node-yeoman.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-personal-tab-node-yeoman.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/what-are-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?branch=pr-en-us-3530) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C2%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202106020537011920-3530%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=YS0BWFaJ0KqDP3AYvD9%2F5w4r1CDBGAF%2BaTHz%2BsZRAwg%3D&st=2021-06-02T05%3A33%3A09Z&se=2021-07-03T05%3A38%3A09Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-02 09:53 UTC, opbld31 commented
Docs Build status updates of commit _[665cd4e](https://github.com/MicrosoftDocs/msteams-docs/commits/665cd4efc61970e559a57e171893026ead46957e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3530) | [Details](#user-content-351f2ba35302ce86d26f9fa3fc15a178-96e33396)
[msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/whats-new.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/whats-new?branch=pr-en-us-3530) | [Details](#user-content-2282d08dedb2572c86ab0482a1f6dc50-96e33396)
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/design/tabs-mobile?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tabs/tabs.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tabs/tabs.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/node-js-yeoman-prereq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/node-js-yeoman-prereq.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/design/tabs-mobile.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/design/tabs-mobile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/design/tabs-mobile?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/access-teams-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/access-teams-context.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/access-teams-context?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/build-adaptive-card-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/build-adaptive-card-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/build-adaptive-card-tabs?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-channel-group-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-personal-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/configuration-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/content-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/content-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/removal-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/removal-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/removal-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/tab-requirements.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/tab-requirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/tab-requirements?branch=pr-en-us-3530) |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core-mvc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core-mvc.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-node-yeoman.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-node-yeoman.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core-mvc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core-mvc.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-personal-tab-node-yeoman.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-personal-tab-node-yeoman.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/what-are-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?branch=pr-en-us-3530) |

<a id="351f2ba35302ce86d26f9fa3fc15a178-96e33396"></a>
### [msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/apps-in-te [...]

2021-06-02 09:59 UTC, opbld30 commented
Docs Build status updates of commit _[20af997](https://github.com/MicrosoftDocs/msteams-docs/commits/20af997d1c7c84ce3e09c8993de1a84bc5cf97a7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3530) |
[msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tabs/tabs.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tabs/tabs.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/node-js-yeoman-prereq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/node-js-yeoman-prereq.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/design/tabs-mobile.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/design/tabs-mobile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/design/tabs-mobile?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/access-teams-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/access-teams-context.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/access-teams-context?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/build-adaptive-card-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/build-adaptive-card-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/build-adaptive-card-tabs?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-channel-group-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-personal-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/configuration-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/content-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/content-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/removal-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/removal-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/removal-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/tab-requirements.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/tab-requirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/tab-requirements?branch=pr-en-us-3530) |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core-mvc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core-mvc.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-node-yeoman.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-node-yeoman.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core-mvc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core-mvc.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-personal-tab-node-yeoman.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-personal-tab-node-yeoman.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/what-are-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?branch=pr-en-us-3530) |
[msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/whats-new.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/whats-new?branch=pr-en-us-3530) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C2%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202106020958252536-3530%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=PZHVZSXiSTq00kzQCkj%2BUMVrooI2Y7Z4kZgwAOS4qUQ%3D&st=2021-06 [...]

2021-06-02 11:41 UTC, opbld32 commented
Docs Build status updates of commit _[899f09f](https://github.com/MicrosoftDocs/msteams-docs/commits/899f09ff1102fe652f05c686a15b515bc7816975)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-a237847b)

<a id="a237847b"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C2%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202106021141031073-3530%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=UEjJkeBjT4gjc2VWYanXFcfn%2BY%2B3or2KFTwW1zB%2FoSs%3D&st=2021-06-02T11%3A36%3A21Z&se=2021-07-03T11%3A41%3A21Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-02 11:59 UTC, opbld30 commented
Docs Build status updates of commit _[dc4c091](https://github.com/MicrosoftDocs/msteams-docs/commits/dc4c0916429975566ea25ca4eb9cc78ed1e7058b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3530) |
[msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tabs/tabs.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tabs/tabs.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/node-js-yeoman-prereq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/node-js-yeoman-prereq.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/design/tabs-mobile.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/design/tabs-mobile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/design/tabs-mobile?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/access-teams-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/access-teams-context.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/access-teams-context?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/build-adaptive-card-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/build-adaptive-card-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/build-adaptive-card-tabs?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-channel-group-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-personal-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/configuration-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/content-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/content-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/removal-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/removal-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/removal-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/tab-requirements.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/tab-requirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/tab-requirements?branch=pr-en-us-3530) |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core-mvc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core-mvc.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-node-yeoman.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-node-yeoman.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core-mvc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core-mvc.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-personal-tab-node-yeoman.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-personal-tab-node-yeoman.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/what-are-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?branch=pr-en-us-3530) |
[msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/whats-new.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/whats-new?branch=pr-en-us-3530) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C2%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202106021158299273-3530%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=l4rkdlJ3ir90i9PmKHNPxWONJZXjOGx%2BsW%2Fn3eXMrsw%3D&st=2021- [...]

2021-06-02 12:20 UTC, opbld30 commented
Docs Build status updates of commit _[d069039](https://github.com/MicrosoftDocs/msteams-docs/commits/d069039afd08a945c5f838157b01cc5dfd340b6a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3530) |
[msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tabs/tabs.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tabs/tabs.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/node-js-yeoman-prereq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/node-js-yeoman-prereq.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/design/tabs-mobile.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/design/tabs-mobile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/design/tabs-mobile?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/access-teams-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/access-teams-context.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/access-teams-context?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/build-adaptive-card-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/build-adaptive-card-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/build-adaptive-card-tabs?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-channel-group-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-personal-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/configuration-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/content-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/content-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/removal-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/removal-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/removal-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/tab-requirements.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/tab-requirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/tab-requirements?branch=pr-en-us-3530) |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core-mvc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core-mvc.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-node-yeoman.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-node-yeoman.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core-mvc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core-mvc.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-personal-tab-node-yeoman.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-personal-tab-node-yeoman.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/what-are-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?branch=pr-en-us-3530) |
[msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/whats-new.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/whats-new?branch=pr-en-us-3530) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C2%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202106021219208697-3530%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=3SwfvRBeNqWlxjHmpvJxOP%2BLY19WqLYQymHDZpvB5CU%3D&st=2021-06 [...]

2021-06-03 03:27 UTC, opbld32 commented
Docs Build status updates of commit _[63101f6](https://github.com/MicrosoftDocs/msteams-docs/commits/63101f6a23b16fbd315372d4980f871937c19007)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3530) |
[msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tabs/tabs.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tabs/tabs.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/node-js-yeoman-prereq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/node-js-yeoman-prereq.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/design/tabs-mobile.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/design/tabs-mobile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/design/tabs-mobile?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/access-teams-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/access-teams-context.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/access-teams-context?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/build-adaptive-card-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/build-adaptive-card-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/build-adaptive-card-tabs?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-channel-group-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-personal-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/configuration-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/content-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/content-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/removal-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/removal-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/removal-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/tab-requirements.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/tab-requirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/tab-requirements?branch=pr-en-us-3530) |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core-mvc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core-mvc.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-node-yeoman.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-node-yeoman.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core-mvc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core-mvc.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-personal-tab-node-yeoman.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-personal-tab-node-yeoman.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/what-are-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?branch=pr-en-us-3530) |
[msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/whats-new.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/whats-new?branch=pr-en-us-3530) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C3%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202106030326320970-3530%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=FkI2oiAuWlpxKIpA1g4nzR%2FDjJcnAAUgsFRRiWhJeY8%3D&st=2021-06 [...]

2021-06-03 05:50 UTC, opbld33 commented
Docs Build status updates of commit _[7b9b651](https://github.com/MicrosoftDocs/msteams-docs/commits/7b9b651f1d1f610decf5470c256fd01daa67ec44)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/meeting-app-extensibility?branch=pr-en-us-3530) | [Details](#user-content-9cecf106fbdf1b3914298efe0241f5ff-550419d4)
[msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/teams-apps-in-meetings?branch=pr-en-us-3530) | [Details](#user-content-72d418f93d252ea69be5c97e3537f14c-550419d4)
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3530) |
[msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tabs/tabs.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tabs/tabs.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/node-js-yeoman-prereq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/node-js-yeoman-prereq.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/design/tabs-mobile.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/design/tabs-mobile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/design/tabs-mobile?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/access-teams-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/access-teams-context.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/access-teams-context?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/build-adaptive-card-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/build-adaptive-card-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/build-adaptive-card-tabs?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/conversational-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/conversational-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/conversational-tabs?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-channel-group-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-personal-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/configuration-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/content-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/content-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/removal-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/removal-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/removal-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/tab-requirements.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/tab-requirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/tab-requirements?branch=pr-en-us-3530) |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core-mvc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core-mvc.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-node-yeoman.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-node-yeoman.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core-mvc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core-mvc.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/q [...]

2021-06-03 08:49 UTC, opbld31 commented
Docs Build status updates of commit _[3a52a96](https://github.com/MicrosoftDocs/msteams-docs/commits/3a52a961c93174b9ef8ff803e3ed5932755e9f1d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/what-are-tabs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?branch=pr-en-us-3530) | [Details](#user-content-b15c6f8d479be682a8d146c5929a3aa0-729bf795)
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3530) |
[msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tabs/tabs.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tabs/tabs.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/node-js-yeoman-prereq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/node-js-yeoman-prereq.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/design/tabs-mobile.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/design/tabs-mobile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/design/tabs-mobile?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/access-teams-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/access-teams-context.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/access-teams-context?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/build-adaptive-card-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/build-adaptive-card-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/build-adaptive-card-tabs?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/conversational-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/conversational-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/conversational-tabs?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-channel-group-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-personal-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/configuration-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/content-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/content-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/removal-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/removal-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/removal-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/tab-requirements.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/tab-requirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/tab-requirements?branch=pr-en-us-3530) |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core-mvc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core-mvc.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-node-yeoman.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-node-yeoman.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core-mvc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core-mvc.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-personal-tab-node-yeoman.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-personal-tab-node-yeoman.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/tabs-link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/tabs-link-unfurling.md) | :white_check_mark:Succeeded  [...]

2021-06-03 10:08 UTC, opbld31 commented
Docs Build status updates of commit _[9935646](https://github.com/MicrosoftDocs/msteams-docs/commits/99356461625aa524d8bbc36faf03254e8ce8718a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/what-are-tabs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?branch=pr-en-us-3530) | [Details](#user-content-b15c6f8d479be682a8d146c5929a3aa0-9dca5e9c)
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3530) |
[msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tabs/tabs.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tabs/tabs.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/node-js-yeoman-prereq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/node-js-yeoman-prereq.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/design/tabs-mobile.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/design/tabs-mobile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/design/tabs-mobile?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/access-teams-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/access-teams-context.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/access-teams-context?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/build-adaptive-card-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/build-adaptive-card-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/build-adaptive-card-tabs?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/conversational-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/conversational-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/conversational-tabs?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-channel-group-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-personal-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/configuration-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/content-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/content-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/removal-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/removal-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/removal-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/tab-requirements.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/tab-requirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/tab-requirements?branch=pr-en-us-3530) |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core-mvc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core-mvc.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-node-yeoman.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-node-yeoman.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core-mvc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core-mvc.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-personal-tab-node-yeoman.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-personal-tab-node-yeoman.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/tabs-link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/tabs-link-unfurling.md) | :white_check_mark:Succeeded  [...]

2021-06-03 12:30 UTC, opbld33 commented
Docs Build status updates of commit _[a9dfdf2](https://github.com/MicrosoftDocs/msteams-docs/commits/a9dfdf2b6f06c48dd4198d8b3bf24bd1df38695a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/what-are-tabs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?branch=pr-en-us-3530) | [Details](#user-content-b15c6f8d479be682a8d146c5929a3aa0-ccd19835)
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3530) |
[msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tabs/tabs.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tabs/tabs.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/node-js-yeoman-prereq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/node-js-yeoman-prereq.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/design/tabs-mobile.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/design/tabs-mobile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/design/tabs-mobile?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/access-teams-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/access-teams-context.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/access-teams-context?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/build-adaptive-card-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/build-adaptive-card-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/build-adaptive-card-tabs?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/conversational-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/conversational-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/conversational-tabs?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-channel-group-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-personal-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/configuration-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/content-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/content-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/removal-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/removal-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/removal-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/tab-requirements.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/tab-requirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/tab-requirements?branch=pr-en-us-3530) |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core-mvc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core-mvc.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-node-yeoman.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-node-yeoman.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core-mvc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core-mvc.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-personal-tab-node-yeoman.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-personal-tab-node-yeoman.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/tabs-link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/tabs-link-unfurling.md) | :white_check_mark:Succeeded  [...]

2021-06-04 12:59 UTC, opbld33 commented
Docs Build status updates of commit _[1b68dbf](https://github.com/MicrosoftDocs/msteams-docs/commits/1b68dbfd67f006d859dfdafe654f0ed8c9d8cd4e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/what-are-tabs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?branch=pr-en-us-3530) | [Details](#user-content-b15c6f8d479be682a8d146c5929a3aa0-fdda92e0)
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3530) |
[msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tabs/tabs.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tabs/tabs.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/node-js-yeoman-prereq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/node-js-yeoman-prereq.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/design/tabs-mobile.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/design/tabs-mobile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/design/tabs-mobile?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/access-teams-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/access-teams-context.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/access-teams-context?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/build-adaptive-card-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/build-adaptive-card-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/build-adaptive-card-tabs?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/conversational-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/conversational-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/conversational-tabs?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-channel-group-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-personal-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/configuration-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/content-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/content-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/removal-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/removal-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/removal-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/tab-requirements.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/tab-requirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/tab-requirements?branch=pr-en-us-3530) |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core-mvc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core-mvc.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-node-yeoman.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-node-yeoman.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core-mvc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core-mvc.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-personal-tab-node-yeoman.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-personal-tab-node-yeoman.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/tabs-link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/tabs-link-unfurling.md) | :white_check_mark:Succeeded  [...]

2021-06-07 05:31 UTC, opbld33 commented
Docs Build status updates of commit _[728765a](https://github.com/MicrosoftDocs/msteams-docs/commits/728765aeed31886ea1fae62809999886ffd7bf8e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/what-are-tabs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?branch=pr-en-us-3530) | [Details](#user-content-b15c6f8d479be682a8d146c5929a3aa0-f2f25e81)
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3530) |
[msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tabs/tabs.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tabs/tabs.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/node-js-yeoman-gulp-tasks.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/node-js-yeoman-gulp-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/node-js-yeoman-prereq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/node-js-yeoman-prereq.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/design/tabs-mobile.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/design/tabs-mobile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/design/tabs-mobile?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/access-teams-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/access-teams-context.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/access-teams-context?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/build-adaptive-card-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/build-adaptive-card-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/build-adaptive-card-tabs?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/conversational-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/conversational-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/conversational-tabs?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-channel-group-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-personal-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/configuration-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/content-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/content-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/removal-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/removal-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/removal-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/tab-requirements.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/tab-requirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/tab-requirements?branch=pr-en-us-3530) |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core-mvc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core-mvc.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-node-yeoman.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-node-yeoman.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core-mvc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core-mvc.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-personal-tab-node-yeoman.md](https://github. [...]

2021-06-07 06:06 UTC, opbld32 commented
Docs Build status updates of commit _[b99cdd6](https://github.com/MicrosoftDocs/msteams-docs/commits/b99cdd6a153d8b59c50441c1db1d81ac6d76673f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/what-are-tabs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?branch=pr-en-us-3530) | [Details](#user-content-b15c6f8d479be682a8d146c5929a3aa0-785949eb)
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3530) |
[msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tabs/tabs.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tabs/tabs.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/node-js-yeoman-gulp-tasks.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/node-js-yeoman-gulp-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/node-js-yeoman-prereq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/node-js-yeoman-prereq.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/design/tabs-mobile.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/design/tabs-mobile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/design/tabs-mobile?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/access-teams-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/access-teams-context.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/access-teams-context?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/build-adaptive-card-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/build-adaptive-card-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/build-adaptive-card-tabs?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/conversational-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/conversational-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/conversational-tabs?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-channel-group-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-personal-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/configuration-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/content-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/content-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/removal-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/removal-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/removal-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/tab-requirements.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/tab-requirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/tab-requirements?branch=pr-en-us-3530) |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core-mvc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core-mvc.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-node-yeoman.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-node-yeoman.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core-mvc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core-mvc.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-personal-tab-node-yeoman.md](https://github. [...]

2021-06-08 07:37 UTC, opbld30 commented
Docs Build status updates of commit _[7a49a21](https://github.com/MicrosoftDocs/msteams-docs/commits/7a49a21ba8f58c09aba83c5624911d5fa74c293b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/what-are-tabs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?branch=pr-en-us-3530) | [Details](#user-content-b15c6f8d479be682a8d146c5929a3aa0-d861dad4)
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3530) |
[msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tabs/tabs.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tabs/tabs.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-ngrok-intro.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-ngrok-intro.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-update-personal-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-update-personal-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/node-js-yeoman-gulp-tasks.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/node-js-yeoman-gulp-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/node-js-yeoman-prereq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/node-js-yeoman-prereq.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/design/tabs-mobile.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/design/tabs-mobile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/design/tabs-mobile?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/access-teams-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/access-teams-context.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/access-teams-context?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/build-adaptive-card-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/build-adaptive-card-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/build-adaptive-card-tabs?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/conversational-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/conversational-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/conversational-tabs?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-channel-group-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-personal-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/configuration-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/content-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/content-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/removal-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/removal-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/removal-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/tab-requirements.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/tab-requirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/tab-requirements?branch=pr-en-us-3530) |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core-mvc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core-mvc.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-node-yeoman.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrev [...]

2021-06-08 12:44 UTC, opbld33 commented
Docs Build status updates of commit _[9dd3045](https://github.com/MicrosoftDocs/msteams-docs/commits/9dd304590d65c2d99ba4de53145bd5f17dddce0b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3530) |
[msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tabs/tabs.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tabs/tabs.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-ngrok-intro.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-ngrok-intro.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-update-personal-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-update-personal-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/node-js-yeoman-gulp-tasks.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/node-js-yeoman-gulp-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/node-js-yeoman-prereq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/node-js-yeoman-prereq.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/design/tabs-mobile.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/design/tabs-mobile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/design/tabs-mobile?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/access-teams-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/access-teams-context.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/access-teams-context?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/build-adaptive-card-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/build-adaptive-card-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/build-adaptive-card-tabs?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/conversational-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/conversational-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/conversational-tabs?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-channel-group-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-personal-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/configuration-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/content-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/content-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/removal-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/removal-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/removal-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/tab-requirements.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/tab-requirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/tab-requirements?branch=pr-en-us-3530) |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core-mvc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core-mvc.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-node-yeoman.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-node-yeoman.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core-mvc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core-mvc.md) | :white_check [...]

2021-06-09 04:04 UTC, opbld31 commented
Docs Build status updates of commit _[481d788](https://github.com/MicrosoftDocs/msteams-docs/commits/481d788f1dd7df9d4d5c76a7651f1c77f664ba2d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3530) |
[msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tabs/tabs.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tabs/tabs.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-ngrok-intro.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-ngrok-intro.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-update-personal-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-update-personal-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/node-js-yeoman-gulp-tasks.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/node-js-yeoman-gulp-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/node-js-yeoman-prereq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/node-js-yeoman-prereq.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/design/tabs-mobile.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/design/tabs-mobile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/design/tabs-mobile?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/access-teams-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/access-teams-context.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/access-teams-context?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/build-adaptive-card-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/build-adaptive-card-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/build-adaptive-card-tabs?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/conversational-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/conversational-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/conversational-tabs?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-channel-group-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-personal-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/configuration-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/content-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/content-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/removal-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/removal-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/removal-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/tab-requirements.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/tab-requirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/tab-requirements?branch=pr-en-us-3530) |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core-mvc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core-mvc.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-node-yeoman.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-node-yeoman.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core-mvc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core-mvc.md) | :white_check [...]

2021-06-10 05:17 UTC, opbld31 commented
Docs Build status updates of commit _[ed13c10](https://github.com/MicrosoftDocs/msteams-docs/commits/ed13c106461a167fb67b7118697b6e5fd016667b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3530) |
[msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tabs/tabs.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tabs/tabs.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-ngrok-intro.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-ngrok-intro.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-update-personal-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-update-personal-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/node-js-yeoman-gulp-tasks.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/node-js-yeoman-gulp-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/node-js-yeoman-prereq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/node-js-yeoman-prereq.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/design/tabs-mobile.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/design/tabs-mobile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/design/tabs-mobile?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/access-teams-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/access-teams-context.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/access-teams-context?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/build-adaptive-card-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/build-adaptive-card-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/build-adaptive-card-tabs?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/conversational-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/conversational-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/conversational-tabs?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-channel-group-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-personal-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/configuration-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/content-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/content-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/removal-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/removal-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/removal-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/tab-requirements.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/tab-requirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/tab-requirements?branch=pr-en-us-3530) |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core-mvc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core-mvc.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-node-yeoman.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-node-yeoman.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core-mvc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core-mvc.md) | :white_check [...]

2021-06-10 05:41 UTC, opbld33 commented
Docs Build status updates of commit _[7ab335d](https://github.com/MicrosoftDocs/msteams-docs/commits/7ab335db00212177575a16644ba07eeb99e698bd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3530) |
[msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tabs/tabs.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tabs/tabs.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-ngrok-intro.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-ngrok-intro.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-update-personal-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-update-personal-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/node-js-yeoman-gulp-tasks.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/node-js-yeoman-gulp-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/node-js-yeoman-prereq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/node-js-yeoman-prereq.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/design/tabs-mobile.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/design/tabs-mobile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/design/tabs-mobile?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/access-teams-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/access-teams-context.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/access-teams-context?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/build-adaptive-card-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/build-adaptive-card-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/build-adaptive-card-tabs?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/conversational-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/conversational-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/conversational-tabs?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-channel-group-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-personal-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/configuration-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/content-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/content-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/removal-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/removal-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/removal-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/tab-requirements.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/tab-requirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/tab-requirements?branch=pr-en-us-3530) |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core-mvc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core-mvc.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-node-yeoman.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-node-yeoman.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core-mvc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core-mvc.md) | :white_check [...]

2021-06-10 07:37 UTC, opbld32 commented
Docs Build status updates of commit _[8d2858a](https://github.com/MicrosoftDocs/msteams-docs/commits/8d2858a7ea99cc5607062403f574f131839fa8f5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3530) |
[msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tabs/tabs.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tabs/tabs.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-ngrok-intro.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-ngrok-intro.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-update-personal-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-update-personal-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/node-js-yeoman-gulp-tasks.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/node-js-yeoman-gulp-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/node-js-yeoman-prereq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/node-js-yeoman-prereq.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/design/tabs-mobile.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/design/tabs-mobile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/design/tabs-mobile?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/access-teams-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/access-teams-context.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/access-teams-context?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/build-adaptive-card-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/build-adaptive-card-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/build-adaptive-card-tabs?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/conversational-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/conversational-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/conversational-tabs?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-channel-group-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-personal-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/configuration-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/content-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/content-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/removal-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/removal-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/removal-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/tab-requirements.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/tab-requirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/tab-requirements?branch=pr-en-us-3530) |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core-mvc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core-mvc.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-node-yeoman.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-node-yeoman.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core-mvc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core-mvc.md) | :white_check [...]

2021-06-10 09:04 UTC, opbld33 commented
Docs Build status updates of commit _[1695d30](https://github.com/MicrosoftDocs/msteams-docs/commits/1695d30e4797b3bcbb0c568f217fd4c53cb076f6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3530) |
[msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tabs/tabs.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tabs/tabs.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-ngrok-intro.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-ngrok-intro.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-update-personal-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-update-personal-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/node-js-yeoman-gulp-tasks.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/node-js-yeoman-gulp-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/node-js-yeoman-prereq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/node-js-yeoman-prereq.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/design/tabs-mobile.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/design/tabs-mobile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/design/tabs-mobile?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/access-teams-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/access-teams-context.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/access-teams-context?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/build-adaptive-card-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/build-adaptive-card-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/build-adaptive-card-tabs?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/conversational-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/conversational-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/conversational-tabs?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-channel-group-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-personal-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/configuration-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/content-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/content-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/removal-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/removal-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/removal-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/tab-requirements.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/tab-requirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/tab-requirements?branch=pr-en-us-3530) |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core-mvc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core-mvc.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-node-yeoman.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-node-yeoman.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core-mvc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core-mvc.md) | :white_check [...]

2021-06-15 09:53 UTC, opbld33 commented
Docs Build status updates of commit _[234f59a](https://github.com/MicrosoftDocs/msteams-docs/commits/234f59a1ebf913301aaf98c038b32cc63ecf164b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3530) |
[msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tabs/tabs.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tabs/tabs.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-ngrok-intro.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-ngrok-intro.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-update-personal-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-update-personal-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/node-js-yeoman-gulp-tasks.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/node-js-yeoman-gulp-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/node-js-yeoman-prereq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/node-js-yeoman-prereq.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/design/tabs-mobile.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/design/tabs-mobile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/design/tabs-mobile?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/access-teams-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/access-teams-context.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/access-teams-context?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/build-adaptive-card-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/build-adaptive-card-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/build-adaptive-card-tabs?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/conversational-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/conversational-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/conversational-tabs?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-channel-group-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-personal-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/configuration-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/content-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/content-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/removal-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/removal-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/removal-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/tab-requirements.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/tab-requirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/tab-requirements?branch=pr-en-us-3530) |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core-mvc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core-mvc.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-node-yeoman.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-node-yeoman.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core-mvc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core-mvc.md) | :white_check [...]

2021-06-15 10:47 UTC, opbld33 commented
Docs Build status updates of commit _[bbf089c](https://github.com/MicrosoftDocs/msteams-docs/commits/bbf089cc4491d18dfd6ac68cff7c0b95bc130dfc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3530) |
[msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tabs/tabs.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tabs/tabs.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-ngrok-intro.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-ngrok-intro.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-update-personal-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-update-personal-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/node-js-yeoman-gulp-tasks.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/node-js-yeoman-gulp-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/node-js-yeoman-prereq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/node-js-yeoman-prereq.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/design/tabs-mobile.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/design/tabs-mobile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/design/tabs-mobile?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/access-teams-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/access-teams-context.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/access-teams-context?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/build-adaptive-card-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/build-adaptive-card-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/build-adaptive-card-tabs?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/conversational-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/conversational-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/conversational-tabs?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-channel-group-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-personal-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/configuration-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/content-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/content-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/removal-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/removal-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/removal-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/tab-requirements.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/tab-requirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/tab-requirements?branch=pr-en-us-3530) |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core-mvc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core-mvc.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-node-yeoman.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-node-yeoman.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core-mvc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-personal-tab-dotnet-core-mvc.md) | :white_check [...]

2021-06-16 07:43 UTC, opbld32 commented
Docs Build status updates of commit _[78edb99](https://github.com/MicrosoftDocs/msteams-docs/commits/78edb990c9f330601953c9208259a299dce51176)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/tabs/design/tabs-mobile.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/design/tabs-mobile.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/design/tabs-mobile?branch=pr-en-us-3530) | [Details](#user-content-846d465acfae1cdec4e326b48378d59b-98b98430)
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3530) |
[msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tabs/tabs.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tabs/tabs.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-ngrok-intro.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-ngrok-intro.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-update-personal-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-update-personal-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/node-js-yeoman-gulp-tasks.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/node-js-yeoman-gulp-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/node-js-yeoman-prereq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/node-js-yeoman-prereq.md) | :white_check_mark:Succeeded | |
[msteams-platform/resources/removing-tab-margins.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/resources/removing-tab-margins.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/removing-tab-margins?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/access-teams-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/access-teams-context.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/access-teams-context?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/build-adaptive-card-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/build-adaptive-card-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/build-adaptive-card-tabs?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/conversational-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/conversational-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/conversational-tabs?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-channel-group-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-personal-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/configuration-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/content-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/content-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/removal-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/removal-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/removal-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/tab-requirements.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/tab-requirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/tab-requirements?branch=pr-en-us-3530) |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core-mvc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core-mvc.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-node-yeoman.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-node-yeoman.md) | :white_check_ [...]

2021-06-18 04:41 UTC, opbld32 commented
Docs Build status updates of commit _[071eb7d](https://github.com/MicrosoftDocs/msteams-docs/commits/071eb7dd4744546130ecefab8b5b00b43f2c0b01)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/tabs/design/tabs-mobile.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/design/tabs-mobile.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/design/tabs-mobile?branch=pr-en-us-3530) | [Details](#user-content-846d465acfae1cdec4e326b48378d59b-fe275a5b)
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3530) |
[msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tabs/tabs.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tabs/tabs.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-ngrok-intro.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-ngrok-intro.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-update-personal-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-update-personal-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/node-js-yeoman-gulp-tasks.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/node-js-yeoman-gulp-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/node-js-yeoman-prereq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/node-js-yeoman-prereq.md) | :white_check_mark:Succeeded | |
[msteams-platform/resources/removing-tab-margins.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/resources/removing-tab-margins.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/removing-tab-margins?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/access-teams-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/access-teams-context.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/access-teams-context?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/build-adaptive-card-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/build-adaptive-card-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/build-adaptive-card-tabs?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/conversational-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/conversational-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/conversational-tabs?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-channel-group-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-personal-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/configuration-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/content-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/content-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/removal-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/removal-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/removal-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/tab-requirements.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/tab-requirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/tab-requirements?branch=pr-en-us-3530) |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core-mvc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core-mvc.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-node-yeoman.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-node-yeoman.md) | :white_check_ [...]

2021-06-18 04:45 UTC, opbld30 commented
Docs Build status updates of commit _[5377379](https://github.com/MicrosoftDocs/msteams-docs/commits/5377379cb6374e4b86701b60458db91dc7ae9614)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3530) |
[msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tabs/tabs.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tabs/tabs.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-ngrok-intro.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-ngrok-intro.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-update-personal-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-update-personal-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/node-js-yeoman-gulp-tasks.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/node-js-yeoman-gulp-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/node-js-yeoman-prereq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/node-js-yeoman-prereq.md) | :white_check_mark:Succeeded | |
[msteams-platform/resources/removing-tab-margins.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/resources/removing-tab-margins.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/removing-tab-margins?branch=pr-en-us-3530) |
[msteams-platform/tabs/design/tabs-mobile.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/design/tabs-mobile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/design/tabs-mobile?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/access-teams-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/access-teams-context.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/access-teams-context?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/build-adaptive-card-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/build-adaptive-card-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/build-adaptive-card-tabs?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/conversational-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/conversational-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/conversational-tabs?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-channel-group-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-personal-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/configuration-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/content-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/content-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/removal-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/removal-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/removal-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/tab-requirements.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/tab-requirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/tab-requirements?branch=pr-en-us-3530) |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core-mvc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core-mvc.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-node-yeoman.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-node-yeoman.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickst [...]

2021-06-21 12:48 UTC, opbld30 commented
Docs Build status updates of commit _[3a683a4](https://github.com/MicrosoftDocs/msteams-docs/commits/3a683a45feef7205f95a8cb1eb246c269a94289b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/whats-new.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/whats-new?branch=pr-en-us-3530) | [Details](#user-content-2282d08dedb2572c86ab0482a1f6dc50-284d3770)
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3530) |
[msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tabs/tabs.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tabs/tabs.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-ngrok-intro.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-ngrok-intro.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-update-personal-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-update-personal-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/node-js-yeoman-gulp-tasks.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/node-js-yeoman-gulp-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/node-js-yeoman-prereq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/node-js-yeoman-prereq.md) | :white_check_mark:Succeeded | |
[msteams-platform/resources/removing-tab-margins.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/resources/removing-tab-margins.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/removing-tab-margins?branch=pr-en-us-3530) |
[msteams-platform/tabs/design/tabs-mobile.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/design/tabs-mobile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/design/tabs-mobile?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/access-teams-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/access-teams-context.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/access-teams-context?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/build-adaptive-card-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/build-adaptive-card-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/build-adaptive-card-tabs?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/conversational-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/conversational-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/conversational-tabs?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-channel-group-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-personal-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/configuration-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/content-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/content-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/removal-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/removal-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/removal-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/tab-requirements.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/tab-requirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/tab-requirements?branch=pr-en-us-3530) |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core-mvc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core-mvc.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core.md)  [...]

2021-06-21 12:59 UTC, opbld30 commented
Docs Build status updates of commit _[57282a2](https://github.com/MicrosoftDocs/msteams-docs/commits/57282a2a5bdc661ddf6a4462682773ba37b4f4b7)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-c631bce7)

<a id="c631bce7"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C21%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202106211259419127-3530%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=KF%2BXHXHZZMuGk9%2BNBIIXD5AuQCJNsQypDR4q6aMZ22A%3D&st=2021-06-21T12%3A54%3A53Z&se=2021-07-22T12%3A59%3A53Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-21 13:02 UTC, opbld31 commented
Docs Build status updates of commit _[d431f00](https://github.com/MicrosoftDocs/msteams-docs/commits/d431f00ede3aa997bd76cca6b5a2c826e0a8cd68)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3530) |
[msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tabs/tabs.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tabs/tabs.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-ngrok-intro.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-ngrok-intro.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-update-personal-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-update-personal-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/node-js-yeoman-gulp-tasks.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/node-js-yeoman-gulp-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/node-js-yeoman-prereq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/node-js-yeoman-prereq.md) | :white_check_mark:Succeeded | |
[msteams-platform/resources/removing-tab-margins.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/resources/removing-tab-margins.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/removing-tab-margins?branch=pr-en-us-3530) |
[msteams-platform/tabs/design/tabs-mobile.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/design/tabs-mobile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/design/tabs-mobile?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/access-teams-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/access-teams-context.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/access-teams-context?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/build-adaptive-card-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/build-adaptive-card-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/build-adaptive-card-tabs?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/conversational-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/conversational-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/conversational-tabs?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-channel-group-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-personal-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/configuration-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/content-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/content-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/removal-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/removal-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/removal-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/tab-requirements.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/tab-requirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/tab-requirements?branch=pr-en-us-3530) |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core-mvc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core-mvc.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-node-yeoman.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-node-yeoman.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickst [...]

2021-06-23 04:22 UTC, opbld33 commented
Docs Build status updates of commit _[45bc30a](https://github.com/MicrosoftDocs/msteams-docs/commits/45bc30a71367ddb17935a55fdc48b3ea7375a440)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3530) |
[msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tabs/tabs.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tabs/tabs.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-ngrok-intro.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-ngrok-intro.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-update-personal-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-update-personal-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/node-js-yeoman-gulp-tasks.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/node-js-yeoman-gulp-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/node-js-yeoman-prereq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/node-js-yeoman-prereq.md) | :white_check_mark:Succeeded | |
[msteams-platform/resources/removing-tab-margins.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/resources/removing-tab-margins.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/removing-tab-margins?branch=pr-en-us-3530) |
[msteams-platform/tabs/design/tabs-mobile.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/design/tabs-mobile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/design/tabs-mobile?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/access-teams-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/access-teams-context.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/access-teams-context?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/build-adaptive-card-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/build-adaptive-card-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/build-adaptive-card-tabs?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/conversational-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/conversational-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/conversational-tabs?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-channel-group-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-personal-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/configuration-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/content-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/content-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/removal-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/removal-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/removal-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/tab-requirements.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/tab-requirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/tab-requirements?branch=pr-en-us-3530) |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core-mvc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core-mvc.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-node-yeoman.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-node-yeoman.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickst [...]

2021-06-23 21:51 UTC, lokimeyburg commented on msteams-platform/includes/tabs/dotnet-ngrok-intro.md
> +To test your tab, use [ngrok](https://ngrok.com/docs). Your server's web endpoints are available while ngrok is running on your computer. If you close ngrok, the URLs are different the next time you
Do we want to mention that ngrok urls only change in the free version of ngrok?

2021-06-23 21:51 UTC, lokimeyburg commented on msteams-platform/tabs/how-to/build-adaptive-card-tabs.md
> +When developing a tab using the traditional method, you must consider these issues, such as HTML and Cascading Style Sheets (CSS) considerations, slow load times, iFrame constraints, and server maint
1. This sentence reads unintuitively. Consider something like:
```
When developing a tab using the traditional method, you may run into these issues: ...."
```
2. No one writes out CSS as "Cascading Style Sheets". Can we just say "CSS"?
3. "You can render Adaptive Card**s** to a tab"
4. "While the front-end is rendered with Adaptive Card**s**"

2021-06-23 21:51 UTC, lokimeyburg commented on msteams-platform/tabs/how-to/build-adaptive-card-tabs.md
> +Use Adaptive Cards to build tabs with ease. You can build your tabs with ready-made user interface (UI) Lego-blocks that look and feel native on desktop, web, and mobile. Building tabs with Adaptive
Is this not restating what was said in the previous paragraph?

2021-06-23 21:51 UTC, lokimeyburg commented on msteams-platform/tabs/how-to/build-adaptive-card-tabs.md
> +The following code provide examples of `task/submit` request and response:
provide**s**

2021-06-23 21:51 UTC, lokimeyburg commented on msteams-platform/tabs/how-to/conversational-tabs.md
> +Tt is important that your tab includes [deeplinks to your sub-entity](~/concepts/build-and-test/deep-links.md). For example, user selecting the tab chiclet deeplink from the channel conversation. The
It is

2021-06-23 21:51 UTC, lokimeyburg commented on msteams-platform/tabs/how-to/conversational-tabs.md
> +To support conversational sub-entities from your personal or static tab, you do not have to change anything in your implementation. Starting or continuing conversations from channel tabs that are alr
Consider active tense:
``We only support starting or continuing conversations from channel tabs...``

2021-06-23 21:51 UTC, lokimeyburg commented on msteams-platform/tabs/how-to/create-tab-pages/content-page.md
> +If you indicate `showLoadingIndicator : true`  in your app manifest, then all tab configuration, content, and removal pages and all iframe-based task modules must follow the mandatory protocol.
"must follow the mandatory protocol" doesn't sound natural. Consider saying "must follow the protocol/steps below", or something like that.

2021-06-23 21:51 UTC, lokimeyburg commented on msteams-platform/tabs/how-to/create-tab-pages/removal-page.md
> +After the remove handler is executed, `removeEvent.notifySuccess()` or `removeEvent.notifyFailure()` notify Teams of the content removal outcome.
notify Teams? consider saying "...notifies Teams" instead.

2021-06-23 21:51 UTC, lokimeyburg commented on msteams-platform/tabs/what-are-tabs.md
> +You can build tabs with Adaptive Cards and centralize all Teams app capabilities by eliminating the need for a different backend for your bots and tabs. Stage View is a new UI component that allows y
Consider adding links to the documentation of the features you're discussing in this paragraph.

2021-06-24 05:58 UTC, opbld31 commented
Docs Build status updates of commit _[865cf5b](https://github.com/MicrosoftDocs/msteams-docs/commits/865cf5b4174417f1e4b30fd7a913b6cea5091f26)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3530) |
[msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tabs/tabs.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tabs/tabs.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-ngrok-intro.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-ngrok-intro.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-update-personal-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-update-personal-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/node-js-yeoman-gulp-tasks.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/node-js-yeoman-gulp-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/node-js-yeoman-prereq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/node-js-yeoman-prereq.md) | :white_check_mark:Succeeded | |
[msteams-platform/resources/removing-tab-margins.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/resources/removing-tab-margins.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/removing-tab-margins?branch=pr-en-us-3530) |
[msteams-platform/tabs/design/tabs-mobile.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/design/tabs-mobile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/design/tabs-mobile?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/access-teams-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/access-teams-context.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/access-teams-context?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/build-adaptive-card-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/build-adaptive-card-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/build-adaptive-card-tabs?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/conversational-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/conversational-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/conversational-tabs?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-channel-group-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-personal-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/configuration-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/content-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/content-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/removal-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/removal-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/removal-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/tab-requirements.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/tab-requirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/tab-requirements?branch=pr-en-us-3530) |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core-mvc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core-mvc.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-core.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-node-yeoman.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/quickstarts/create-channel-group-tab-node-yeoman.md) | :white_check_mark:Succeeded | |
[msteams-platform/tabs/quickst [...]

2021-06-24 10:27 UTC, opbld30 commented
Docs Build status updates of commit _[5d04a1b](https://github.com/MicrosoftDocs/msteams-docs/commits/5d04a1bd99ce5e36f96df0677e4c3a5097f3e57d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-personal-tab.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) | [Details](#user-content-ba3b05282a3fc888b3c1d57fa2074e3b-a27e07f1)
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3530) |
[msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/addingpersonaltab.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/addingpersonaltab.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/tab-images/addingpersonaltab.png?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/teamsTabScreenshot.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/teamsTabScreenshot.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/tab-images/teamstabscreenshot.png?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tabs/tabs.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tabs/tabs.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-ngrok-intro.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-ngrok-intro.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-update-personal-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-update-personal-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/node-js-yeoman-gulp-tasks.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/node-js-yeoman-gulp-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/node-js-yeoman-prereq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/node-js-yeoman-prereq.md) | :white_check_mark:Succeeded | |
[msteams-platform/resources/removing-tab-margins.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/resources/removing-tab-margins.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/removing-tab-margins?branch=pr-en-us-3530) |
[msteams-platform/tabs/design/tabs-mobile.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/design/tabs-mobile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/design/tabs-mobile?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/access-teams-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/access-teams-context.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/access-teams-context?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/build-adaptive-card-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/build-adaptive-card-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/build-adaptive-card-tabs?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/conversational-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/conversational-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/conversational-tabs?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-channel-group-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/configuration-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/content-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/content-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/removal-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/removal-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/removal-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/tab-requirements.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/tab-requirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/tab-requirements?branch=pr-en-us-3530) |
[mstea [...]

2021-06-24 10:36 UTC, opbld30 commented
Docs Build status updates of commit _[7b31328](https://github.com/MicrosoftDocs/msteams-docs/commits/7b3132819295f760b97fc2220366b8de096055a6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3530) |
[msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/addingpersonaltab.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/addingpersonaltab.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/teamsTabScreenshot.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/teamsTabScreenshot.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/tab-images/teamstabscreenshot.png?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tabs/tabs.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tabs/tabs.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-ngrok-intro.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-ngrok-intro.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-update-personal-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-update-personal-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/node-js-yeoman-gulp-tasks.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/node-js-yeoman-gulp-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/node-js-yeoman-prereq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/node-js-yeoman-prereq.md) | :white_check_mark:Succeeded | |
[msteams-platform/resources/removing-tab-margins.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/resources/removing-tab-margins.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/removing-tab-margins?branch=pr-en-us-3530) |
[msteams-platform/tabs/design/tabs-mobile.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/design/tabs-mobile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/design/tabs-mobile?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/access-teams-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/access-teams-context.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/access-teams-context?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/build-adaptive-card-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/build-adaptive-card-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/build-adaptive-card-tabs?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/conversational-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/conversational-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/conversational-tabs?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-channel-group-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-personal-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/configuration-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/content-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/content-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/create-tab-pages/removal-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/create-tab-pages/removal-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/removal-page?branch=pr-en-us-3530) |
[msteams-platform/tabs/how-to/tab-requirements.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/how-to/tab-requirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/tab-requirements?branch=pr-en-us-3530) |
[msteams-platform/tabs/quickstarts/create-channel-group-tab-dotnet-cor [...]

2021-06-24 12:40 UTC, opbld33 commented
Docs Build status updates of commit _[2523bb1](https://github.com/MicrosoftDocs/msteams-docs/commits/2523bb180cfc480122cd512f645a79ec4ea1d42f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3530) |
[msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/addingpersonaltab.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/addingpersonaltab.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/appurls.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/appurls.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/channeltabadded.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/channeltabadded.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/channeltabaspnetmvcuploaded.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/channeltabaspnetmvcuploaded.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/channeltabaspnetuploaded.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/channeltabaspnetuploaded.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/channeltabuploaded.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/channeltabuploaded.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/personaltabaspnetmvcuploaded.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/personaltabaspnetmvcuploaded.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/personaltabaspnetuploaded.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/personaltabaspnetuploaded.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/personaltabdetails.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/personaltabdetails.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/personaltabuploaded.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/personaltabuploaded.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/teamsTabScreenshot.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/teamsTabScreenshot.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/tab-images/teamstabscreenshot.png?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tabs/tabs.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tabs/tabs.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-ngrok-intro.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-ngrok-intro.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-update-personal-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-update-personal-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/node-js-yeoman-gulp-tasks.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/node-js-yeoman-gulp-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/node-js-yeoman-prereq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/node-js-yeoman-prereq.md) | :white_check_mark:Succeeded | |
[msteams-platform/resources/removing-tab-margins.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/resources/removing-tab-margins.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/removing-tab-margins?branch=pr-en-us-3530) |
[msteams-platform/tabs/design/tabs-mobile.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/tabs/design/tabs-mobile.md) | :white_check_mark:Succeeded | [View](https://review.docs.mi [...]

2021-06-24 15:03 UTC, lokimeyburg approved these changes

2021-06-24 16:21 UTC, opbld32 commented
Docs Build status updates of commit _[33e4469](https://github.com/MicrosoftDocs/msteams-docs/commits/33e4469318a36ee89b031190c4e79dfae72ef01b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3530) |
[msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/addingpersonaltab.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/addingpersonaltab.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/appurls.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/appurls.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/channeltabadded.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/channeltabadded.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/channeltabaspnetmvcuploaded.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/channeltabaspnetmvcuploaded.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/channeltabaspnetuploaded.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/channeltabaspnetuploaded.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/channeltabuploaded.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/channeltabuploaded.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/personaltabaspnetmvcuploaded.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/personaltabaspnetmvcuploaded.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/personaltabaspnetuploaded.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/personaltabaspnetuploaded.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/personaltabdetails.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/personaltabdetails.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/personaltabuploaded.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/personaltabuploaded.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/teamsTabScreenshot.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/teamsTabScreenshot.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/tab-images/teamstabscreenshot.png?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tabs/tabs.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tabs/tabs.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?branch=pr-en-us-3530) |
[msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/concepts/build-and-test/apps-localization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/apps-localization?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-ngrok-intro.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-ngrok-intro.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-update-personal-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-update-personal-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/node-js-yeoman-gulp-tasks.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/node-js-yeoman-gulp-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/node-js-yeoman-prereq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/node-js-yeoman-prereq.md) | :white_check_mark:Succeeded | |
[msteams-platform/resources/removing-tab-margins.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/resources/removing-tab-margins.md) | :white_check [...]

2021-06-25 04:54 UTC, Nikitha-MSFT approved these changes
Reviewed and approved

2021-06-25 04:58 UTC, opbld32 commented
Docs Build status updates of commit _[ae3488a](https://github.com/MicrosoftDocs/msteams-docs/commits/ae3488abc5ad4d89b2af9af677672c2081e83b4b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3530) |
[msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/addingpersonaltab.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/addingpersonaltab.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/appurls.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/appurls.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/channeltabadded.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/channeltabadded.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/channeltabaspnetmvcuploaded.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/channeltabaspnetmvcuploaded.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/channeltabaspnetuploaded.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/channeltabaspnetuploaded.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/channeltabuploaded.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/channeltabuploaded.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/personaltabaspnetmvcuploaded.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/personaltabaspnetmvcuploaded.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/personaltabaspnetuploaded.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/personaltabaspnetuploaded.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/personaltabdetails.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/personaltabdetails.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/personaltabuploaded.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/personaltabuploaded.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/teamsTabScreenshot.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/teamsTabScreenshot.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/tab-images/teamstabscreenshot.png?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tabs/tabs.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tabs/tabs.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?branch=pr-en-us-3530) |
[msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/concepts/build-and-test/apps-localization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/apps-localization?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-ngrok-intro.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-ngrok-intro.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-update-personal-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-update-personal-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/node-js-yeoman-gulp-tasks.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/node-js-yeoman-gulp-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/node-js-yeoman-prereq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/node-js-yeoman-prereq.md) | :white_check_mark:Succeeded | |
[msteams-platform/resources/removing-tab-margins.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/resources/removing-tab-margins.md) | :white_check [...]

2021-06-25 05:11 UTC, opbld32 commented
Docs Build status updates of commit _[8a78112](https://github.com/MicrosoftDocs/msteams-docs/commits/8a78112f3f18add2500e73fe034dc83b98bc475d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3530) |
[msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/addingpersonaltab.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/addingpersonaltab.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/appurls.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/appurls.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/channeltabadded.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/channeltabadded.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/channeltabaspnetmvcuploaded.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/channeltabaspnetmvcuploaded.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/channeltabaspnetuploaded.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/channeltabaspnetuploaded.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/channeltabuploaded.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/channeltabuploaded.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/personaltabaspnetmvcuploaded.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/personaltabaspnetmvcuploaded.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/personaltabaspnetuploaded.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/personaltabaspnetuploaded.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/personaltabdetails.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/personaltabdetails.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/personaltabuploaded.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/personaltabuploaded.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/teamsTabScreenshot.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/teamsTabScreenshot.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/tab-images/teamstabscreenshot.png?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tabs/tabs.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tabs/tabs.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?branch=pr-en-us-3530) |
[msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/concepts/build-and-test/apps-localization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/apps-localization?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-ngrok-intro.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-ngrok-intro.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-update-personal-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-update-personal-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/node-js-yeoman-gulp-tasks.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/node-js-yeoman-gulp-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/node-js-yeoman-prereq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/node-js-yeoman-prereq.md) | :white_check_mark:Succeeded | |
[msteams-platform/resources/removing-tab-margins.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/resources/removing-tab-margins.md) | :white_check [...]

2021-06-25 06:23 UTC, opbld30 commented
Docs Build status updates of commit _[6138d4c](https://github.com/MicrosoftDocs/msteams-docs/commits/6138d4c2d3aa677970f4da3958f69e6bd162d972)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3530) |
[msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/addingpersonaltab.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/addingpersonaltab.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/appurls.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/appurls.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/channeltabadded.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/channeltabadded.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/channeltabaspnetmvcuploaded.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/channeltabaspnetmvcuploaded.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/channeltabaspnetuploaded.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/channeltabaspnetuploaded.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/channeltabuploaded.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/channeltabuploaded.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/personaltabaspnetmvcuploaded.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/personaltabaspnetmvcuploaded.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/personaltabaspnetuploaded.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/personaltabaspnetuploaded.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/personaltabdetails.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/personaltabdetails.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/personaltabuploaded.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/personaltabuploaded.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/teamsTabScreenshot.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/teamsTabScreenshot.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/tab-images/teamstabscreenshot.png?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tabs/tabs.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tabs/tabs.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?branch=pr-en-us-3530) |
[msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/concepts/build-and-test/apps-localization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/apps-localization?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-ngrok-intro.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-ngrok-intro.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-update-personal-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-update-personal-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/node-js-yeoman-gulp-tasks.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/node-js-yeoman-gulp-tasks.md) | :white_check_mark:Succeeded | |
[msteams-platform/includes/tabs/node-js-yeoman-prereq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/node-js-yeoman-prereq.md) | :white_check_mark:Succeeded | |
[msteams-platform/resources/removing-tab-margins.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/resources/removing-tab-margins.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/removing-tab-margins?branch=pr- [...]

2021-06-25 06:29 UTC, opbld30 commented
Docs Build status updates of commit _[842f5ee](https://github.com/MicrosoftDocs/msteams-docs/commits/842f5ee156da6fe1611d8079d7848514e0845f80)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3530) |
[msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/addingpersonaltab.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/addingpersonaltab.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/appurls.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/appurls.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/channeltabadded.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/channeltabadded.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/channeltabaspnetmvcuploaded.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/channeltabaspnetmvcuploaded.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/channeltabaspnetuploaded.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/channeltabaspnetuploaded.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/channeltabuploaded.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/channeltabuploaded.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/personaltabaspnetmvcuploaded.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/personaltabaspnetmvcuploaded.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/personaltabaspnetuploaded.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/personaltabaspnetuploaded.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/personaltabdetails.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/personaltabdetails.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/personaltabuploaded.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/personaltabuploaded.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/teamsTabScreenshot.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/teamsTabScreenshot.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/tab-images/teamstabscreenshot.png?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tabs/tabs.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tabs/tabs.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?branch=pr-en-us-3530) |
[msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/concepts/build-and-test/apps-localization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/apps-localization?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-ngrok-intro.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-ngrok-intro.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-update-personal-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-update-personal-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/node-js-yeoman-gulp-tasks.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/node-js-yeoman-gulp-tasks.md) | :white_check_mark:Succeeded | |
[msteams-platform/includes/tabs/node-js-yeoman-prereq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/node-js-yeoman-prereq.md) | :white_check_mark:Succeeded | |
[msteams-platform/resources/removing-tab-margins.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/resources/removing-tab-margins.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/removing-tab-margins?branch=pr- [...]

2021-06-25 08:14 UTC, opbld32 commented
Docs Build status updates of commit _[7538be5](https://github.com/MicrosoftDocs/msteams-docs/commits/7538be5c8803ec206a251afcd5dcdf4e82e678fa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3530) |
[msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/addingpersonaltab.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/addingpersonaltab.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/appurls.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/appurls.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/channeltabadded.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/channeltabadded.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/channeltabaspnetmvcuploaded.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/channeltabaspnetmvcuploaded.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/channeltabaspnetuploaded.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/channeltabaspnetuploaded.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/channeltabuploaded.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/channeltabuploaded.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/personaltabaspnetmvcuploaded.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/personaltabaspnetmvcuploaded.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/personaltabaspnetuploaded.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/personaltabaspnetuploaded.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/personaltabdetails.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/personaltabdetails.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/personaltabuploaded.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/personaltabuploaded.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/teamsTabScreenshot.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/teamsTabScreenshot.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/tab-images/teamstabscreenshot.png?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tabs/tabs.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tabs/tabs.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?branch=pr-en-us-3530) |
[msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/concepts/build-and-test/apps-localization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/apps-localization?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-ngrok-intro.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-ngrok-intro.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-update-personal-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-update-personal-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/node-js-yeoman-gulp-tasks.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/node-js-yeoman-gulp-tasks.md) | :white_check_mark:Succeeded | |
[msteams-platform/includes/tabs/node-js-yeoman-prereq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/node-js-yeoman-prereq.md) | :white_check_mark:Succeeded | |
[msteams-platform/resources/removing-tab-margins.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/resources/removing-tab-margins.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/removing-tab-margins?branch=pr- [...]

2021-06-25 09:18 UTC, opbld33 commented
Docs Build status updates of commit _[771264c](https://github.com/MicrosoftDocs/msteams-docs/commits/771264c3fec4ac8286e30ff6c052a9a2a4c95126)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3530) |
[msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/addingpersonaltab.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/addingpersonaltab.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/appurls.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/appurls.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/channeltabadded.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/channeltabadded.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/channeltabaspnetmvcuploaded.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/channeltabaspnetmvcuploaded.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/channeltabaspnetuploaded.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/channeltabaspnetuploaded.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/channeltabuploaded.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/channeltabuploaded.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/personaltabaspnetmvcuploaded.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/personaltabaspnetmvcuploaded.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/personaltabaspnetuploaded.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/personaltabaspnetuploaded.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/personaltabdetails.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/personaltabdetails.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/personaltabuploaded.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/personaltabuploaded.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/teamsTabScreenshot.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/teamsTabScreenshot.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/tab-images/teamstabscreenshot.png?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tabs/tabs.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tabs/tabs.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?branch=pr-en-us-3530) |
[msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/concepts/build-and-test/apps-localization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/apps-localization?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-ngrok-intro.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-ngrok-intro.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-update-personal-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-update-personal-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/node-js-yeoman-gulp-tasks.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/node-js-yeoman-gulp-tasks.md) | :white_check_mark:Succeeded | |
[msteams-platform/includes/tabs/node-js-yeoman-prereq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/node-js-yeoman-prereq.md) | :white_check_mark:Succeeded | |
[msteams-platform/resources/removing-tab-margins.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/resources/removing-tab-margins.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/removing-tab-margins?branch=pr- [...]

2021-06-25 09:22 UTC, opbld30 commented
Docs Build status updates of commit _[cff1d77](https://github.com/MicrosoftDocs/msteams-docs/commits/cff1d77ea5c4f4189d3d3a39ac810c0148f83aa7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3530) |
[msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/addingpersonaltab.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/addingpersonaltab.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/appurls.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/appurls.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/channeltabadded.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/channeltabadded.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/channeltabaspnetmvcuploaded.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/channeltabaspnetmvcuploaded.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/channeltabaspnetuploaded.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/channeltabaspnetuploaded.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/channeltabuploaded.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/channeltabuploaded.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/personaltabaspnetmvcuploaded.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/personaltabaspnetmvcuploaded.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/personaltabaspnetuploaded.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/personaltabaspnetuploaded.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/personaltabdetails.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/personaltabdetails.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/personaltabuploaded.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/personaltabuploaded.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/teamsTabScreenshot.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/teamsTabScreenshot.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/tab-images/teamstabscreenshot.png?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tabs/tabs.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tabs/tabs.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?branch=pr-en-us-3530) |
[msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/concepts/build-and-test/apps-localization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/apps-localization?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-ngrok-intro.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-ngrok-intro.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-update-personal-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-update-personal-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/node-js-yeoman-gulp-tasks.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/node-js-yeoman-gulp-tasks.md) | :white_check_mark:Succeeded | |
[msteams-platform/includes/tabs/node-js-yeoman-prereq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/node-js-yeoman-prereq.md) | :white_check_mark:Succeeded | |
[msteams-platform/resources/removing-tab-margins.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/resources/removing-tab-margins.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/removing-tab-margins?branch=pr- [...]

2021-06-25 17:46 UTC, opbld32 commented
Docs Build status updates of commit _[c0590a4](https://github.com/MicrosoftDocs/msteams-docs/commits/c0590a4a1aad9454fc44c24da4b1f81829f265b8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3530) |
[msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/addingpersonaltab.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/addingpersonaltab.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/appurls.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/appurls.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/channeltabadded.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/channeltabadded.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/channeltabaspnetmvcuploaded.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/channeltabaspnetmvcuploaded.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/channeltabaspnetuploaded.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/channeltabaspnetuploaded.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/channeltabuploaded.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/channeltabuploaded.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/personaltabaspnetmvcuploaded.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/personaltabaspnetmvcuploaded.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/personaltabaspnetuploaded.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/personaltabaspnetuploaded.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/personaltabdetails.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/personaltabdetails.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/personaltabuploaded.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/personaltabuploaded.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/teamsTabScreenshot.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/teamsTabScreenshot.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/tab-images/teamstabscreenshot.png?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tabs/tabs.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tabs/tabs.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?branch=pr-en-us-3530) |
[msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/concepts/build-and-test/apps-localization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/apps-localization?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-ngrok-intro.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-ngrok-intro.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-update-personal-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-update-personal-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/node-js-yeoman-gulp-tasks.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/node-js-yeoman-gulp-tasks.md) | :white_check_mark:Succeeded | |
[msteams-platform/includes/tabs/node-js-yeoman-prereq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/node-js-yeoman-prereq.md) | :white_check_mark:Succeeded | |
[msteams-platform/resources/removing-tab-margins.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/resources/removing-tab-margins.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/removing-tab-margins?branch=pr- [...]

2021-06-25 18:37 UTC, Wajeed-msft requested changes

2021-06-25 18:37 UTC, Wajeed-msft commented on msteams-platform/tabs/how-to/create-personal-tab.md
> +## Reorder static personal tabs
I feel reordering can be moved after "Create a custom personal tab".

2021-06-25 18:37 UTC, Wajeed-msft commented on msteams-platform/tabs/what-are-tabs.md
> +![Channel or group and personal tabs](../assets/images/tabs/tabs.png)
Can we add two images, one for personal tab and another for channel tab?

2021-06-25 18:37 UTC, Wajeed-msft commented on msteams-platform/tabs/what-are-tabs.md
> +
Can we move this sentence after the video? currently it feels like videos are about prerequesites.

2021-06-25 18:37 UTC, Wajeed-msft commented on msteams-platform/tabs/how-to/tab-requirements.md
> +* [Teams tabs](~/tabs/what-are-tabs.md)
I feel there are too many see also links. Do we have any fixed guidelines on number of links?

2021-06-25 18:39 UTC, Wajeed-msft approved these changes

2021-06-25 18:44 UTC, v-abirade approved these changes
Approval

2021-06-25 18:45 UTC, opbld30 commented
Docs Build status updates of commit _[e7d5663](https://github.com/MicrosoftDocs/msteams-docs/commits/e7d566321f67fb0c37e5f6b4d42baad4ebad5098)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3530) |
[msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/addingpersonaltab.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/addingpersonaltab.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/appurls.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/appurls.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/channeltabadded.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/channeltabadded.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/channeltabaspnetmvcuploaded.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/channeltabaspnetmvcuploaded.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/channeltabaspnetuploaded.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/channeltabaspnetuploaded.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/channeltabuploaded.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/channeltabuploaded.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/personaltabaspnetmvcuploaded.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/personaltabaspnetmvcuploaded.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/personaltabaspnetuploaded.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/personaltabaspnetuploaded.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/personaltabdetails.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/personaltabdetails.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/personaltabuploaded.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/personaltabuploaded.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tab-images/teamsTabScreenshot.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tab-images/teamsTabScreenshot.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/tab-images/teamstabscreenshot.png?branch=pr-en-us-3530) |
[msteams-platform/assets/images/tabs/tabs.png](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/assets/images/tabs/tabs.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?branch=pr-en-us-3530) |
[msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/concepts/build-and-test/apps-localization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/apps-localization?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-ngrok-intro.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-ngrok-intro.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-personal-use-appstudio.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/dotnet-update-personal-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/dotnet-update-personal-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3530) |
[msteams-platform/includes/tabs/node-js-yeoman-gulp-tasks.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/node-js-yeoman-gulp-tasks.md) | :white_check_mark:Succeeded | |
[msteams-platform/includes/tabs/node-js-yeoman-prereq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/includes/tabs/node-js-yeoman-prereq.md) | :white_check_mark:Succeeded | |
[msteams-platform/resources/removing-tab-margins.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1684145-Buildtabsrevamp/msteams-platform/resources/removing-tab-margins.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/removing-tab-margins?branch=pr- [...]

2021-06-25 18:47 UTC, surbhigupta12 approved these changes
Approved

2021-06-25 18:47 UTC, merged