Updates VS Toolkit overview
MicrosoftDocs/msteams-docs pull request #3549
Opened 2021-06-03 17:26 UTC by therealjohn

Updated to reflect the new extension.

2021-06-03 17:27 UTC, opbld32 commented
Docs Build status updates of commit _[6d447de](https://github.com/therealjohn/msteams-docs/commits/6d447de2759682865e7951fcf96d3cb27460ed19)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/toolkit/visual-studio-overview.md](https://github.com/therealjohn/msteams-docs/blob/master/msteams-platform/toolkit/visual-studio-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/visual-studio-overview?branch=pr-en-us-3549) | [Details](#user-content-8c8ee9b14a30e3551e8cbef87b812c49-70dee8c0)

<a id="8c8ee9b14a30e3551e8cbef87b812c49-70dee8c0"></a>
### [msteams-platform/toolkit/visual-studio-overview.md](https://github.com/therealjohn/msteams-docs/blob/master/msteams-platform/toolkit/visual-studio-overview.md)
 - **Line 30, Column 3**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#package-your-app' in 'toolkit/visual-studio-overview.md', did you mean '#validate-your-app'?`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C3%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202106031726300538-3549%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=4ulhqpLlLID%2FsxBGIPD2vpZIsUnpC%2Ft0stwHP5h16QQ%3D&st=2021-06-03T17%3A22%3A12Z&se=2021-07-04T17%3A27%3A12Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-03 18:33 UTC, opbld30 commented
Docs Build status updates of commit _[5daf2aa](https://github.com/therealjohn/msteams-docs/commits/5daf2aa48ac517ff4a00692aa7837cab9ea9f682)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/toolkit/visual-studio-overview.md](https://github.com/therealjohn/msteams-docs/blob/master/msteams-platform/toolkit/visual-studio-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/visual-studio-overview?branch=pr-en-us-3549) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C3%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202106031833016523-3549%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Z0xH2OUyT9KEKBAOtvgf9mRPS%2B%2BXrfZJ9DzONLD2oRE%3D&st=2021-06-03T18%3A28%3A44Z&se=2021-07-04T18%3A33%3A44Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-04 12:29 UTC, v-rodriguezd requested changes
Reviewed the modified content. Please verify.

2021-06-04 12:29 UTC, v-rodriguezd commented on msteams-platform/toolkit/visual-studio-overview.md
> +5. Select the **Next** button to choose a name for the app.
5. Select **Next** to enter a name for the app.

Question: Please clarify the resulting screen post selecting Next. Are you selecting or entering the app name? Please change the process step as per the action.

2021-06-09 08:05 UTC, v-rodriguezd commented
@therealjohn please incorporate the review changes. Let me know in case of any issues.

2021-06-09 14:29 UTC, therealjohn commented on msteams-platform/toolkit/visual-studio-overview.md
>  ## Using the toolkit
Not sure what change you are suggesting. Can you clarify?

2021-06-11 08:27 UTC, v-rodriguezd commented
@therealjohn Please incorporate the review suggestions. Thank you.

2021-06-14 04:51 UTC, v-rodriguezd commented on msteams-platform/toolkit/visual-studio-overview.md
>  ## Using the toolkit
@therealjohn please change the title "Using the toolkit" on line 26 to "Use the Toolkit".

2021-06-14 04:53 UTC, v-rodriguezd commented
Hi @therealjohn please incorporate the review comments and let me know in case of any issues. Awaiting your changes.

2021-06-14 14:35 UTC, opbld30 commented
Docs Build status updates of commit _[d8190ee](https://github.com/therealjohn/msteams-docs/commits/d8190ee7bf5ad76a6f8e71abe7bdbb0cfc03e5e0)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-5443f568)

<a id="5443f568"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C14%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202106141435322898-3549%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2Fir3FCarTmzRqxODmMVZv9tntHUPtp3N44Pwif1lpxA%3D&st=2021-06-14T14%3A30%3A50Z&se=2021-07-15T14%3A35%3A50Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-14 14:39 UTC, therealjohn commented
@v-rodriguezd Done! Please review. Thanks!

2021-06-14 14:40 UTC, opbld31 commented
Docs Build status updates of commit _[1cd8b5a](https://github.com/therealjohn/msteams-docs/commits/1cd8b5abb296134b1cd5177e66741aab5ab6dfef)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/toolkit/visual-studio-overview.md](https://github.com/therealjohn/msteams-docs/blob/master/msteams-platform/toolkit/visual-studio-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/visual-studio-overview?branch=pr-en-us-3549) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C14%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202106141439073185-3549%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=6YCHkKn8JxlYkWwqFqBjz4a0zLrEzdvRQA30BOpQLvE%3D&st=2021-06-14T14%3A35%3A24Z&se=2021-07-15T14%3A40%3A24Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-15 12:04 UTC, v-rodriguezd commented on msteams-platform/toolkit/visual-studio-overview.md
> +  2. A server that responds to requests for content that will be displayed in Teams, e.g., HTML tab content or a bot adaptive card .
@therealjohn please replace 'e.g.,' with 'for example'. Also please remove extra space before the period in 'bot adaptive card.' Please remove 'that will be'.

2021-06-15 12:06 UTC, v-rodriguezd commented on msteams-platform/toolkit/visual-studio-overview.md
> +You will be prompted to sign-in to your Microsoft Account that has a M365 tenant.
@therealjohn this change is not reflected please replace "You will be prompted to sign-in to your Microsoft Account that has a M365 tenant." with "When prompted, sign in to your Microsoft account that has an M365 tenant."

2021-06-15 12:08 UTC, v-rodriguezd commented
Please incorporate the suggestions. There are some changes which are not reflecting.

2021-06-15 13:37 UTC, opbld31 commented
Docs Build status updates of commit _[207e7f8](https://github.com/therealjohn/msteams-docs/commits/207e7f875f23665bf4379b80a4cf5b59eb20ba2e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/toolkit/visual-studio-overview.md](https://github.com/therealjohn/msteams-docs/blob/master/msteams-platform/toolkit/visual-studio-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/visual-studio-overview?branch=pr-en-us-3549) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C15%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202106151336422375-3549%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=9L1vfGpyaDd5grmTpiPrl2RpMOvOrJgnMJR7CuUNuT4%3D&st=2021-06-15T13%3A32%3A24Z&se=2021-07-16T13%3A37%3A24Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-16 05:35 UTC, v-rodriguezd commented on msteams-platform/toolkit/visual-studio-overview.md
> +5. Select the **Next** button to choose a name for the app.
Please rephrase step 5 to "Select Next to enter a name for the app."

2021-06-16 05:38 UTC, v-rodriguezd commented on msteams-platform/toolkit/visual-studio-overview.md
> +You will be prompted to sign-in to your Microsoft Account that has a M365 tenant.
Change not reflected.

2021-06-16 05:39 UTC, v-rodriguezd commented
There are two comments pending, please incorporate these:
Change "You will be prompted to sign-in to your Microsoft Account that has a M365 tenant." to "When prompted, sign in to your Microsoft account that has an M365 tenant."
Please rephrase step 5 under Set up a new Teams project to "Select Next to enter a name for the app."

2021-06-16 05:40 UTC, v-rodriguezd commented
@therealjohn There are two comments pending, please incorporate these:
Change "You will be prompted to sign-in to your Microsoft Account that has a M365 tenant." to "When prompted, sign in to your Microsoft account that has an M365 tenant."
Please rephrase step 5 under Set up a new Teams project to "Select Next to enter a name for the app."

2021-06-17 04:20 UTC, v-rodriguezd commented
@therealjohn Please incorporate these suggestions:
Rephrase "You will be prompted to sign-in to your Microsoft Account that has a M365 tenant." to "When prompted, sign in to your Microsoft account that has an M365 tenant."
Please rephrase step 5 under Set up a new Teams project to "Select Next to enter a name for the app."

2021-06-18 10:17 UTC, v-rodriguezd commented
@therealjohn Please incorporate these pending suggestions:
Rephrase "You will be prompted to sign-in to your Microsoft Account that has a M365 tenant." to "When prompted, sign in to your Microsoft account that has an M365 tenant."
Please rephrase step 5 under Set up a new Teams project to "Select Next to enter a name for the app."

2021-06-21 09:09 UTC, v-rodriguezd commented
@therealjohn please incorporate the two pending suggestions as soon as possible. Awaiting your changes.

2021-06-21 14:51 UTC, opbld31 commented
Docs Build status updates of commit _[491fb69](https://github.com/therealjohn/msteams-docs/commits/491fb69fcf6eb5ea8b9bae997ae0af9f52ff6401)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/toolkit/visual-studio-overview.md](https://github.com/therealjohn/msteams-docs/blob/master/msteams-platform/toolkit/visual-studio-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/visual-studio-overview?branch=pr-en-us-3549) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C21%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202106211451009465-3549%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=hHV8CX1EkLElG1JHBVjaKHNZLbExcpYdeGQr8TuSuAA%3D&st=2021-06-21T14%3A46%3A31Z&se=2021-07-22T14%3A51%3A31Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-21 14:52 UTC, opbld32 commented
Docs Build status updates of commit _[0862114](https://github.com/therealjohn/msteams-docs/commits/0862114f480f161e3aad1ac2d6e12c528a93ccd0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/toolkit/visual-studio-overview.md](https://github.com/therealjohn/msteams-docs/blob/master/msteams-platform/toolkit/visual-studio-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/visual-studio-overview?branch=pr-en-us-3549) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C21%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202106211451418204-3549%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=FzbsKSjwnva7TzCWMdPBEjCcEgI7eHZc68OLncl8Mhs%3D&st=2021-06-21T14%3A47%3A09Z&se=2021-07-22T14%3A52%3A09Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-21 16:38 UTC, v-rodriguezd commented
Hi @therealjohn Please rephrase step 5 under Set up a new Teams project to "Select Next to enter a name for the app."

2021-06-21 16:50 UTC, v-rodriguezd commented on msteams-platform/toolkit/visual-studio-overview.md
> +5. Select the **Next** button to choose a name for the app.
Please incorporate this suggestion rephrase step 5 to "Select Next to enter a name for the app."

2021-06-21 17:19 UTC, opbld32 commented
Docs Build status updates of commit _[e091f73](https://github.com/therealjohn/msteams-docs/commits/e091f739cb6d307279ada153f37dad48ab9ff89b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/toolkit/visual-studio-overview.md](https://github.com/therealjohn/msteams-docs/blob/master/msteams-platform/toolkit/visual-studio-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/visual-studio-overview?branch=pr-en-us-3549) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C21%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202106211718576180-3549%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=tYfmSyzGQBtTpaMR1WWdTvyXR%2BSR5MOHXlWd6LZAiII%3D&st=2021-06-21T17%3A14%3A28Z&se=2021-07-22T17%3A19%3A28Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-22 06:26 UTC, v-rodriguezd approved these changes
Approved

2021-06-23 14:55 UTC, merged