[Feature[GCC][1811749]
MicrosoftDocs/msteams-docs pull request #3675
Opened 2021-06-18 08:41 UTC by v-rodriguezd

Added important note for GCC in for third party apps, bot, sideloading apps, custom tabs, and custom connectors. Could not find Lob apps, custom bot, and Custom InputExtensions. Please review.

2021-06-18 08:41 UTC, opbld31 commented
Docs Build status updates of commit _[e3ce52a](https://github.com/MicrosoftDocs/msteams-docs/commits/e3ce52ab17990fdbf62bb4228cd731de17330024)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/apps-publish-overview?branch=pr-en-us-3675) | [Details](#user-content-33a73a9b206d2febb043073fd80f622f-d6cca792)
[msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/meeting-app-extensibility?branch=pr-en-us-3675) |
[msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/bots/design/bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/design/bots?branch=pr-en-us-3675) |
[msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/bots/what-are-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/what-are-bots?branch=pr-en-us-3675) |
[msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/concepts/deploy-and-publish/apps-upload.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/apps-upload?branch=pr-en-us-3675) |
[msteams-platform/concepts/design/enable-app-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/concepts/design/enable-app-customization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/design/enable-app-customization?branch=pr-en-us-3675) |
[msteams-platform/get-started/first-app-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/get-started/first-app-bot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-bot?branch=pr-en-us-3675) |
[msteams-platform/resources/bot-v3/bots-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/resources/bot-v3/bots-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bots-overview?branch=pr-en-us-3675) |
[msteams-platform/samples/integrating-web-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/samples/integrating-web-apps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/samples/integrating-web-apps?branch=pr-en-us-3675) |
[msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/tabs/what-are-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?branch=pr-en-us-3675) |
[msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-creating?branch=pr-en-us-3675) |

<a id="33a73a9b206d2febb043073fd80f622f-d6cca792"></a>
### [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md)
 - **Line 29, Column 27**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/MicrosoftTeams/manage-apps?toc=%2Fmicrosoftteams%2Fplatform%2Ftoc.json&bc=%2FMicrosoftTeams%2Fbreadcrumb%2Ftoc.json' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C18%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202106180841041622-3675%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=6zDTb9AjWrXIUJM39pGlduKMDQDSJmomUKXQPaBrAGo%3D&st=2021-06-18T08%3A36%3A44Z&se=2021-07-19T08%3A41%3A44Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-18 08:44 UTC, opbld32 commented
Docs Build status updates of commit _[0f2655c](https://github.com/MicrosoftDocs/msteams-docs/commits/0f2655ca067550b86e63d2db5e92f26860cd1e77)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/meeting-app-extensibility?branch=pr-en-us-3675) |
[msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/bots/design/bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/design/bots?branch=pr-en-us-3675) |
[msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/bots/what-are-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/what-are-bots?branch=pr-en-us-3675) |
[msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/apps-publish-overview?branch=pr-en-us-3675) |
[msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/concepts/deploy-and-publish/apps-upload.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/apps-upload?branch=pr-en-us-3675) |
[msteams-platform/concepts/design/enable-app-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/concepts/design/enable-app-customization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/design/enable-app-customization?branch=pr-en-us-3675) |
[msteams-platform/get-started/first-app-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/get-started/first-app-bot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-bot?branch=pr-en-us-3675) |
[msteams-platform/resources/bot-v3/bots-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/resources/bot-v3/bots-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bots-overview?branch=pr-en-us-3675) |
[msteams-platform/samples/integrating-web-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/samples/integrating-web-apps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/samples/integrating-web-apps?branch=pr-en-us-3675) |
[msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/tabs/what-are-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?branch=pr-en-us-3675) |
[msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-creating?branch=pr-en-us-3675) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C18%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202106180843583242-3675%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=nNHUCDcfoNm5HZVL0ldSdr%2FL84PmmxelXNoqoIUXNmY%3D&st=2021-06-18T08%3A39%3A41Z&se=2021-07-19T08%3A44%3A41Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-23 06:51 UTC, opbld33 commented
Docs Build status updates of commit _[6bb4f8a](https://github.com/MicrosoftDocs/msteams-docs/commits/6bb4f8ae1513661ccb051a1e18c9053c81e4ab47)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/meeting-app-extensibility?branch=pr-en-us-3675) |
[msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/bots/design/bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/design/bots?branch=pr-en-us-3675) |
[msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/bots/what-are-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/what-are-bots?branch=pr-en-us-3675) |
[msteams-platform/concepts/capabilities-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/concepts/capabilities-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/capabilities-overview?branch=pr-en-us-3675) |
[msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/apps-publish-overview?branch=pr-en-us-3675) |
[msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/concepts/deploy-and-publish/apps-upload.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/apps-upload?branch=pr-en-us-3675) |
[msteams-platform/concepts/design/enable-app-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/concepts/design/enable-app-customization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/design/enable-app-customization?branch=pr-en-us-3675) |
[msteams-platform/get-started/first-app-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/get-started/first-app-bot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-bot?branch=pr-en-us-3675) |
[msteams-platform/resources/bot-v3/bots-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/resources/bot-v3/bots-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bots-overview?branch=pr-en-us-3675) |
[msteams-platform/samples/integrating-web-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/samples/integrating-web-apps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/samples/integrating-web-apps?branch=pr-en-us-3675) |
[msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/tabs/what-are-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?branch=pr-en-us-3675) |
[msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-creating?branch=pr-en-us-3675) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C23%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202106230650394340-3675%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=w0wD9rgzJyqGUj1ag8qTiNExtGvMztOVs0LlNiD1Ecs%3D&st=2021-06-23T06%3A46%3A23Z&se=2021-07-24T06%3A51%3A23Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-23 07:53 UTC, opbld31 commented
Docs Build status updates of commit _[a7bca5d](https://github.com/MicrosoftDocs/msteams-docs/commits/a7bca5df39b2fac3313904896868691233f2f81f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/meeting-app-extensibility?branch=pr-en-us-3675) |
[msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/bots/design/bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/design/bots?branch=pr-en-us-3675) |
[msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/bots/what-are-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/what-are-bots?branch=pr-en-us-3675) |
[msteams-platform/concepts/capabilities-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/concepts/capabilities-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/capabilities-overview?branch=pr-en-us-3675) |
[msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/apps-publish-overview?branch=pr-en-us-3675) |
[msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/concepts/deploy-and-publish/apps-upload.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/apps-upload?branch=pr-en-us-3675) |
[msteams-platform/concepts/design/enable-app-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/concepts/design/enable-app-customization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/design/enable-app-customization?branch=pr-en-us-3675) |
[msteams-platform/get-started/first-app-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/get-started/first-app-bot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-bot?branch=pr-en-us-3675) |
[msteams-platform/resources/bot-v3/bots-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/resources/bot-v3/bots-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bots-overview?branch=pr-en-us-3675) |
[msteams-platform/samples/integrating-web-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/samples/integrating-web-apps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/samples/integrating-web-apps?branch=pr-en-us-3675) |
[msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/tabs/what-are-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?branch=pr-en-us-3675) |
[msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-creating?branch=pr-en-us-3675) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C23%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202106230752007039-3675%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=d7CgmDZb%2Fm%2FpKq4OiNZXxKlMWJllWo0Covs5LsSCWo0%3D&st=2021-06-23T07%3A48%3A23Z&se=2021-07-24T07%3A53%3A23Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-23 07:57 UTC, v-abirade submitted a review, later dismissed
Approved

2021-07-16 09:31 UTC, opbld33 commented
Docs Build status updates of commit _[0ea19bd](https://github.com/MicrosoftDocs/msteams-docs/commits/0ea19bdbdc966c44feacda19dec4b32b6f38cfcb)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-e1f5cd96)

<a id="e1f5cd96"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C16%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202107160930560220-3675%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-16T08%3A01%3A15Z&ske=2021-07-23T08%3A06%3A15Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-16T09%3A26%3A13Z&se=2021-08-16T09%3A31%3A13Z&sr=b&sp=r&sig=DVkq710tKMnIq0B1EObwSrQeZWmc%2FYk2l9TmAqgY8Gg%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-16 09:31 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We do not currently enforce a minimum score for content merged to the default branch. This will change in the future.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0ea19bdbdc966c44feacda19dec4b32b6f38cfcb/msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md) | 90 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/467e92c2-b7df-49c7-9082-fbf49dfb4c7d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0ea19bdbdc966c44feacda19dec4b32b6f38cfcb/msteams-platform/bots/design/bots.md) | 91 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3ed594e1-e03f-4970-b7c7-0260588fbaa0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0ea19bdbdc966c44feacda19dec4b32b6f38cfcb/msteams-platform/bots/what-are-bots.md) | 84 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fceb6676-7d82-49c6-934f-287cd6346235) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/capabilities-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0ea19bdbdc966c44feacda19dec4b32b6f38cfcb/msteams-platform/concepts/capabilities-overview.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9910fd2d-436c-4bea-ae39-4d08c211041d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0ea19bdbdc966c44feacda19dec4b32b6f38cfcb/msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5903f2c8-42a8-4bae-bcaa-d1ec8c4fe96f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0ea19bdbdc966c44feacda19dec4b32b6f38cfcb/msteams-platform/concepts/deploy-and-publish/apps-upload.md) | 84 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d0751290-d1c6-419e-b258-3bc675993610) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/enable-app-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0ea19bdbdc966c44feacda19dec4b32b6f38cfcb/msteams-platform/concepts/design/enable-app-customization.md) | 88 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/78af2bc6-b97b-4e80-a50c-1960976a25c2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/first-app-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0ea19bdbdc966c44feacda19dec4b32b6f38cfcb/msteams-platform/get-started/first-app-bot.md) | 88 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/90d23238-93bc-41b8-8d9e-550bd0094742) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bots-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0ea19bdbdc966c44feacda19dec4b32b6f38cfcb/msteams-platform/resources/bot-v3/bots-overview.md) | 89 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/09f52a24-aa47-4e4a-b97f-3318af578690) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/integrating-web-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0ea19bdbdc966c44feacda19dec4b32b6f38cfcb/msteams-platform/samples/integrating-web-apps.md) | 85 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/61b234df-1ab6-48df-93d8-c727c2aa7169) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0ea19bdbdc966c44feacda19dec4b32b6f38cfcb/msteams-platform/tabs/what-are-tabs.md) | 88 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4ed6304e-58cd-483d-8dab-9aadd3ccc155) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0ea19bdbdc966c44feacda19dec4b32b6f38cfcb/msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md) | 82 | 47 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3d8189f3-9db6-4c1a-9f2b-b0cb3da08f65) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2021-07-16 09:46 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We do not currently enforce a minimum score for content merged to the default branch. This will change in the future.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2f8e9367b725dbf42fd253d9e7b22f52081c2249/msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md) | 90 | 30 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2d3718c9-bd49-488a-b4e0-b26fded30529) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2f8e9367b725dbf42fd253d9e7b22f52081c2249/msteams-platform/bots/design/bots.md) | 91 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c6ade8a4-68df-43ef-969f-77c934f9f499) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2f8e9367b725dbf42fd253d9e7b22f52081c2249/msteams-platform/bots/what-are-bots.md) | 84 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/57a04efb-ab85-49b1-938a-0c377e7c84d4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/capabilities-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2f8e9367b725dbf42fd253d9e7b22f52081c2249/msteams-platform/concepts/capabilities-overview.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5a8a4e26-d173-4ec9-b067-39d1daf3e0ee) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2f8e9367b725dbf42fd253d9e7b22f52081c2249/msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/55f28eaa-944b-4b94-9923-2617f56de9d8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2f8e9367b725dbf42fd253d9e7b22f52081c2249/msteams-platform/concepts/deploy-and-publish/apps-upload.md) | 84 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/538448ce-4b6c-4990-9692-911bdcf469e1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/enable-app-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2f8e9367b725dbf42fd253d9e7b22f52081c2249/msteams-platform/concepts/design/enable-app-customization.md) | 88 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/20b43333-1245-406b-929a-40b8c619d777) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/first-app-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2f8e9367b725dbf42fd253d9e7b22f52081c2249/msteams-platform/get-started/first-app-bot.md) | 88 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c4952b16-42b4-48ed-b4e4-79576ddfb73e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bots-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2f8e9367b725dbf42fd253d9e7b22f52081c2249/msteams-platform/resources/bot-v3/bots-overview.md) | 89 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1346b341-093d-47da-9709-0f9645def793) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/integrating-web-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2f8e9367b725dbf42fd253d9e7b22f52081c2249/msteams-platform/samples/integrating-web-apps.md) | 85 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/56ffdaf5-afb0-4a5d-898d-163a88141ced) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2f8e9367b725dbf42fd253d9e7b22f52081c2249/msteams-platform/tabs/what-are-tabs.md) | 88 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cee805da-2810-41c0-9e2b-2f7100db52d6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2f8e9367b725dbf42fd253d9e7b22f52081c2249/msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md) | 90 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d5dbc0cf-c544-4846-9f8b-43f5d3dd300e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2021-07-16 09:47 UTC, opbld31 commented
Docs Build status updates of commit _[2f8e936](https://github.com/MicrosoftDocs/msteams-docs/commits/2f8e9367b725dbf42fd253d9e7b22f52081c2249)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/meeting-app-extensibility?branch=pr-en-us-3675) |
[msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/bots/design/bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/design/bots?branch=pr-en-us-3675) |
[msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/bots/what-are-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/what-are-bots?branch=pr-en-us-3675) |
[msteams-platform/concepts/capabilities-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/concepts/capabilities-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/capabilities-overview?branch=pr-en-us-3675) |
[msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/apps-publish-overview?branch=pr-en-us-3675) |
[msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/concepts/deploy-and-publish/apps-upload.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/apps-upload?branch=pr-en-us-3675) |
[msteams-platform/concepts/design/enable-app-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/concepts/design/enable-app-customization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/design/enable-app-customization?branch=pr-en-us-3675) |
[msteams-platform/get-started/first-app-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/get-started/first-app-bot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-bot?branch=pr-en-us-3675) |
[msteams-platform/resources/bot-v3/bots-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/resources/bot-v3/bots-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bots-overview?branch=pr-en-us-3675) |
[msteams-platform/samples/integrating-web-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/samples/integrating-web-apps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/samples/integrating-web-apps?branch=pr-en-us-3675) |
[msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/tabs/what-are-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?branch=pr-en-us-3675) |
[msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-creating?branch=pr-en-us-3675) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C16%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202107160945411245-3675%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-16T08%3A05%3A12Z&ske=2021-07-23T08%3A10%3A12Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-16T09%3A42%3A20Z&se=2021-08-16T09%3A47%3A20Z&sr=b&sp=r&sig=UR%2FSTO9U%2BMmoKGeOVkjUOAg5w3Jn3wh4TU0rvIk0GnA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-19 10:34 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We do not currently enforce a minimum score for content merged to the default branch. This will change in the future.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9700f2ca4d1f6eed56abfeb2778d42567cd7ecbf/msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md) | 90 | 30 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bc955cb2-0f32-4e23-bc46-ec56b2004557) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9700f2ca4d1f6eed56abfeb2778d42567cd7ecbf/msteams-platform/bots/design/bots.md) | 91 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/93020499-3491-41f5-8028-e5c93819f3cf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9700f2ca4d1f6eed56abfeb2778d42567cd7ecbf/msteams-platform/bots/what-are-bots.md) | 84 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/02fc35fe-4530-4707-8e5b-6184b7739530) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/capabilities-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9700f2ca4d1f6eed56abfeb2778d42567cd7ecbf/msteams-platform/concepts/capabilities-overview.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/49b95dd6-348d-4c7b-97eb-86d342e92afb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9700f2ca4d1f6eed56abfeb2778d42567cd7ecbf/msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f1ff9612-12dc-45ab-b772-1173567abef4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9700f2ca4d1f6eed56abfeb2778d42567cd7ecbf/msteams-platform/concepts/deploy-and-publish/apps-upload.md) | 84 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9120d8cd-923a-4850-a6ec-06895ef8bfc1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/enable-app-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9700f2ca4d1f6eed56abfeb2778d42567cd7ecbf/msteams-platform/concepts/design/enable-app-customization.md) | 88 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c33890df-db0a-4f47-8c23-957a8af0e7dc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/first-app-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9700f2ca4d1f6eed56abfeb2778d42567cd7ecbf/msteams-platform/get-started/first-app-bot.md) | 88 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/302e50f5-f639-40a1-860c-a953be1a4600) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bots-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9700f2ca4d1f6eed56abfeb2778d42567cd7ecbf/msteams-platform/resources/bot-v3/bots-overview.md) | 89 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/90dcbf64-4c77-4d78-995c-a487070f281c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/integrating-web-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9700f2ca4d1f6eed56abfeb2778d42567cd7ecbf/msteams-platform/samples/integrating-web-apps.md) | 85 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/df27f4ab-e80f-4607-99b7-a9238e302258) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9700f2ca4d1f6eed56abfeb2778d42567cd7ecbf/msteams-platform/tabs/what-are-tabs.md) | 88 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4777f386-7c00-4e97-ac81-01c2655fabcf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9700f2ca4d1f6eed56abfeb2778d42567cd7ecbf/msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md) | 90 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f474ada6-1018-4c03-a720-d432961accb9) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2021-07-19 10:35 UTC, opbld30 commented
Docs Build status updates of commit _[9700f2c](https://github.com/MicrosoftDocs/msteams-docs/commits/9700f2ca4d1f6eed56abfeb2778d42567cd7ecbf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/meeting-app-extensibility?branch=pr-en-us-3675) |
[msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/bots/design/bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/design/bots?branch=pr-en-us-3675) |
[msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/bots/what-are-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/what-are-bots?branch=pr-en-us-3675) |
[msteams-platform/concepts/capabilities-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/concepts/capabilities-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/capabilities-overview?branch=pr-en-us-3675) |
[msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/apps-publish-overview?branch=pr-en-us-3675) |
[msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/concepts/deploy-and-publish/apps-upload.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/apps-upload?branch=pr-en-us-3675) |
[msteams-platform/concepts/design/enable-app-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/concepts/design/enable-app-customization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/design/enable-app-customization?branch=pr-en-us-3675) |
[msteams-platform/get-started/first-app-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/get-started/first-app-bot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-bot?branch=pr-en-us-3675) |
[msteams-platform/resources/bot-v3/bots-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/resources/bot-v3/bots-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bots-overview?branch=pr-en-us-3675) |
[msteams-platform/samples/integrating-web-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/samples/integrating-web-apps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/samples/integrating-web-apps?branch=pr-en-us-3675) |
[msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/tabs/what-are-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?branch=pr-en-us-3675) |
[msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-creating?branch=pr-en-us-3675) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C19%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202107191033338688-3675%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-19T03%3A13%3A37Z&ske=2021-07-26T03%3A18%3A37Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-19T10%3A30%3A20Z&se=2021-08-19T10%3A35%3A20Z&sr=b&sp=r&sig=qZaLyrKomXpNzuZKeh9kgiawhlQRe3EB3W3F%2BTJJT8o%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-19 10:46 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We do not currently enforce a minimum score for content merged to the default branch. This will change in the future.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md](https://github.com/MicrosoftDocs/msteams-docs/blob/06ca6a600925239ac3ebf5d4a5e53be4389035b0/msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md) | 90 | 30 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/df96b79d-a22f-4c4c-a5a1-704483e37fbb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/06ca6a600925239ac3ebf5d4a5e53be4389035b0/msteams-platform/bots/design/bots.md) | 91 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c9b5e1be-3db9-482a-ac8a-7aa6f7d7004b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/06ca6a600925239ac3ebf5d4a5e53be4389035b0/msteams-platform/bots/what-are-bots.md) | 84 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5b098109-5c52-4b2b-ac2d-d1e1997d32a4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/capabilities-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/06ca6a600925239ac3ebf5d4a5e53be4389035b0/msteams-platform/concepts/capabilities-overview.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d8867a4c-f428-4c65-8182-68dd724eac56) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/06ca6a600925239ac3ebf5d4a5e53be4389035b0/msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b9675f8f-a915-42b3-abca-a60b2cdba3d2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/06ca6a600925239ac3ebf5d4a5e53be4389035b0/msteams-platform/concepts/deploy-and-publish/apps-upload.md) | 84 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/00b36180-ca54-4ba0-98a0-8636e43f4910) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/enable-app-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/06ca6a600925239ac3ebf5d4a5e53be4389035b0/msteams-platform/concepts/design/enable-app-customization.md) | 88 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cd10bc63-5a61-42b2-96fa-6086d326aecd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/first-app-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/06ca6a600925239ac3ebf5d4a5e53be4389035b0/msteams-platform/get-started/first-app-bot.md) | 88 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1af509e9-610f-4e41-afa7-6afef324a860) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bots-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/06ca6a600925239ac3ebf5d4a5e53be4389035b0/msteams-platform/resources/bot-v3/bots-overview.md) | 89 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d88f1fd1-9d94-453b-bb18-8618f6e26d4a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/integrating-web-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/06ca6a600925239ac3ebf5d4a5e53be4389035b0/msteams-platform/samples/integrating-web-apps.md) | 85 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/78560569-0e05-49e6-8234-0ec0da70f394) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/06ca6a600925239ac3ebf5d4a5e53be4389035b0/msteams-platform/tabs/what-are-tabs.md) | 88 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/723b8b69-2856-4ba6-b4e3-e8fe472d6fb7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/MicrosoftDocs/msteams-docs/blob/06ca6a600925239ac3ebf5d4a5e53be4389035b0/msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md) | 90 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0e23d614-ab91-49fd-b324-654a27cf3eea) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2021-07-19 10:48 UTC, opbld31 commented
Docs Build status updates of commit _[06ca6a6](https://github.com/MicrosoftDocs/msteams-docs/commits/06ca6a600925239ac3ebf5d4a5e53be4389035b0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/meeting-app-extensibility?branch=pr-en-us-3675) |
[msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/bots/design/bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/design/bots?branch=pr-en-us-3675) |
[msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/bots/what-are-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/what-are-bots?branch=pr-en-us-3675) |
[msteams-platform/concepts/capabilities-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/concepts/capabilities-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/capabilities-overview?branch=pr-en-us-3675) |
[msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/apps-publish-overview?branch=pr-en-us-3675) |
[msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/concepts/deploy-and-publish/apps-upload.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/apps-upload?branch=pr-en-us-3675) |
[msteams-platform/concepts/design/enable-app-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/concepts/design/enable-app-customization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/design/enable-app-customization?branch=pr-en-us-3675) |
[msteams-platform/get-started/first-app-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/get-started/first-app-bot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-bot?branch=pr-en-us-3675) |
[msteams-platform/resources/bot-v3/bots-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/resources/bot-v3/bots-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bots-overview?branch=pr-en-us-3675) |
[msteams-platform/samples/integrating-web-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/samples/integrating-web-apps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/samples/integrating-web-apps?branch=pr-en-us-3675) |
[msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/tabs/what-are-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?branch=pr-en-us-3675) |
[msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-creating?branch=pr-en-us-3675) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C19%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202107191045498778-3675%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-19T02%3A39%3A33Z&ske=2021-07-26T02%3A44%3A33Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-19T10%3A43%3A04Z&se=2021-08-19T10%3A48%3A04Z&sr=b&sp=r&sig=GDTolH%2B5rOZiX%2Fus3nMTy%2BxSseU9ylFPyuEDX0pjmdQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-19 11:03 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We do not currently enforce a minimum score for content merged to the default branch. This will change in the future.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md](https://github.com/MicrosoftDocs/msteams-docs/blob/86a04ab3faf6edcad8fa1d53db6b94ca0474c74f/msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md) | 90 | 30 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/23b92f2a-891d-4517-9531-46fefe4ec597) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/86a04ab3faf6edcad8fa1d53db6b94ca0474c74f/msteams-platform/bots/design/bots.md) | 91 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/99406bfc-535a-434d-a787-a3b6dc0a6eb1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/86a04ab3faf6edcad8fa1d53db6b94ca0474c74f/msteams-platform/bots/what-are-bots.md) | 84 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b98b0526-d5f2-44b3-8f25-31a4879d5315) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/capabilities-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/86a04ab3faf6edcad8fa1d53db6b94ca0474c74f/msteams-platform/concepts/capabilities-overview.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/50218029-da90-4b1d-a14f-23a5f7af8b64) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/86a04ab3faf6edcad8fa1d53db6b94ca0474c74f/msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d76a11ba-f852-4ff6-aed1-308d47994cae) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/86a04ab3faf6edcad8fa1d53db6b94ca0474c74f/msteams-platform/concepts/deploy-and-publish/apps-upload.md) | 84 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d6d1aaa1-d01b-4559-a02e-f0a0ecb9bf23) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/enable-app-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/86a04ab3faf6edcad8fa1d53db6b94ca0474c74f/msteams-platform/concepts/design/enable-app-customization.md) | 88 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6287167c-19b4-4c19-817b-6789279ae115) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/first-app-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/86a04ab3faf6edcad8fa1d53db6b94ca0474c74f/msteams-platform/get-started/first-app-bot.md) | 88 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c4c81765-5da2-4518-9c41-a315e727b29f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bots-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/86a04ab3faf6edcad8fa1d53db6b94ca0474c74f/msteams-platform/resources/bot-v3/bots-overview.md) | 89 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4c436774-0152-4a15-ba69-b284991871df) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/integrating-web-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/86a04ab3faf6edcad8fa1d53db6b94ca0474c74f/msteams-platform/samples/integrating-web-apps.md) | 85 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/70fbe143-bfe8-4aed-8b6d-ba0e3983d1c0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/86a04ab3faf6edcad8fa1d53db6b94ca0474c74f/msteams-platform/tabs/what-are-tabs.md) | 88 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6bc942b5-ace3-4033-89c2-9d39cce8c4d5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/MicrosoftDocs/msteams-docs/blob/86a04ab3faf6edcad8fa1d53db6b94ca0474c74f/msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md) | 90 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7fe4789b-508e-4777-bbd4-8f66f99f7536) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2021-07-19 11:05 UTC, opbld32 commented
Docs Build status updates of commit _[86a04ab](https://github.com/MicrosoftDocs/msteams-docs/commits/86a04ab3faf6edcad8fa1d53db6b94ca0474c74f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/meeting-app-extensibility?branch=pr-en-us-3675) |
[msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/bots/design/bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/design/bots?branch=pr-en-us-3675) |
[msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/bots/what-are-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/what-are-bots?branch=pr-en-us-3675) |
[msteams-platform/concepts/capabilities-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/concepts/capabilities-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/capabilities-overview?branch=pr-en-us-3675) |
[msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/apps-publish-overview?branch=pr-en-us-3675) |
[msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/concepts/deploy-and-publish/apps-upload.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/apps-upload?branch=pr-en-us-3675) |
[msteams-platform/concepts/design/enable-app-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/concepts/design/enable-app-customization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/design/enable-app-customization?branch=pr-en-us-3675) |
[msteams-platform/get-started/first-app-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/get-started/first-app-bot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-bot?branch=pr-en-us-3675) |
[msteams-platform/resources/bot-v3/bots-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/resources/bot-v3/bots-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bots-overview?branch=pr-en-us-3675) |
[msteams-platform/samples/integrating-web-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/samples/integrating-web-apps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/samples/integrating-web-apps?branch=pr-en-us-3675) |
[msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/tabs/what-are-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?branch=pr-en-us-3675) |
[msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-creating?branch=pr-en-us-3675) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C19%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202107191103190550-3675%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-19T03%3A25%3A36Z&ske=2021-07-26T03%3A30%3A36Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-19T11%3A00%3A47Z&se=2021-08-19T11%3A05%3A47Z&sr=b&sp=r&sig=dIo3XBfTvltSdUK0nZQ3Y3TFSAkUK4TwT8vO%2Fb2fiq8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-28 05:37 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We do not currently enforce a minimum score for content merged to the default branch. This will change in the future.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c3756371be57800396cc2cb0dd0a9a62172c10f7/msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md) | 90 | 30 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/14e6f40a-e04d-4f1f-8d6e-9e87ba4c5a7e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c3756371be57800396cc2cb0dd0a9a62172c10f7/msteams-platform/bots/design/bots.md) | 91 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8810b7db-32d4-4765-b8a8-22133a35e0b5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c3756371be57800396cc2cb0dd0a9a62172c10f7/msteams-platform/bots/what-are-bots.md) | 84 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aa49cf8b-7466-43c5-8994-a2e908cf4109) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/capabilities-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c3756371be57800396cc2cb0dd0a9a62172c10f7/msteams-platform/concepts/capabilities-overview.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a9f97fdc-2099-4825-b771-c3fbbaba4ca5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c3756371be57800396cc2cb0dd0a9a62172c10f7/msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4be72b3b-f8ed-4dbf-afd0-57a3d84a3334) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c3756371be57800396cc2cb0dd0a9a62172c10f7/msteams-platform/concepts/deploy-and-publish/apps-upload.md) | 84 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ef31bb5f-e003-4291-a927-788b3edd4730) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/enable-app-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c3756371be57800396cc2cb0dd0a9a62172c10f7/msteams-platform/concepts/design/enable-app-customization.md) | 88 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/92a279f6-ed28-421a-b7a1-8c59e5e8b7f8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/first-app-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c3756371be57800396cc2cb0dd0a9a62172c10f7/msteams-platform/get-started/first-app-bot.md) | 88 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1f8a8f49-0135-4c63-bb48-c9b9f1be0fa8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bots-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c3756371be57800396cc2cb0dd0a9a62172c10f7/msteams-platform/resources/bot-v3/bots-overview.md) | 89 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7a8510ea-8d48-4d61-8188-338a250bc7ae) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/integrating-web-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c3756371be57800396cc2cb0dd0a9a62172c10f7/msteams-platform/samples/integrating-web-apps.md) | 85 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0d3ff522-0713-4be8-a64d-0451e437606c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c3756371be57800396cc2cb0dd0a9a62172c10f7/msteams-platform/tabs/what-are-tabs.md) | 88 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cc90e68b-bec9-45fa-9f24-761d408c0d08) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c3756371be57800396cc2cb0dd0a9a62172c10f7/msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md) | 90 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2c454085-b11a-404e-97c2-e78e8fb112fd) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2021-07-28 05:38 UTC, opbld30 commented
Docs Build status updates of commit _[c375637](https://github.com/MicrosoftDocs/msteams-docs/commits/c3756371be57800396cc2cb0dd0a9a62172c10f7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/meeting-app-extensibility?branch=pr-en-us-3675) |
[msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/bots/design/bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/design/bots?branch=pr-en-us-3675) |
[msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/bots/what-are-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/what-are-bots?branch=pr-en-us-3675) |
[msteams-platform/concepts/capabilities-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/concepts/capabilities-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/capabilities-overview?branch=pr-en-us-3675) |
[msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/apps-publish-overview?branch=pr-en-us-3675) |
[msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/concepts/deploy-and-publish/apps-upload.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/apps-upload?branch=pr-en-us-3675) |
[msteams-platform/concepts/design/enable-app-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/concepts/design/enable-app-customization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/design/enable-app-customization?branch=pr-en-us-3675) |
[msteams-platform/get-started/first-app-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/get-started/first-app-bot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-bot?branch=pr-en-us-3675) |
[msteams-platform/resources/bot-v3/bots-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/resources/bot-v3/bots-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bots-overview?branch=pr-en-us-3675) |
[msteams-platform/samples/integrating-web-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/samples/integrating-web-apps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/samples/integrating-web-apps?branch=pr-en-us-3675) |
[msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/tabs/what-are-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?branch=pr-en-us-3675) |
[msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-creating?branch=pr-en-us-3675) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C28%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202107280537099446-3675%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-28T04%3A14%3A23Z&ske=2021-08-04T04%3A19%3A23Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-28T05%3A33%3A21Z&se=2021-08-28T05%3A38%3A21Z&sr=b&sp=r&sig=okSM4t6z40hrUPF1fulkxfTLRmdGGK4eRnKLO8S7SJ4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-29 09:35 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We do not currently enforce a minimum score for content merged to the default branch. This will change in the future.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md](https://github.com/MicrosoftDocs/msteams-docs/blob/90d2c5e0102c125c1f6c84fd3d0e2b0823eff596/msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md) | 90 | 30 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6374e0ae-8b09-468c-90a9-96520e124fb8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/90d2c5e0102c125c1f6c84fd3d0e2b0823eff596/msteams-platform/bots/design/bots.md) | 91 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c2fdeb3a-c237-4247-9c94-94e13e2ac909) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/90d2c5e0102c125c1f6c84fd3d0e2b0823eff596/msteams-platform/bots/what-are-bots.md) | 84 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6db0ff95-d24f-4eb7-96bb-fb68fa4dfaf2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/capabilities-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/90d2c5e0102c125c1f6c84fd3d0e2b0823eff596/msteams-platform/concepts/capabilities-overview.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1c139aa3-cb1d-4e68-bbe7-5741b7b01d1a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/90d2c5e0102c125c1f6c84fd3d0e2b0823eff596/msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0266cc90-ec48-45a4-bd42-1960c972c02f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/90d2c5e0102c125c1f6c84fd3d0e2b0823eff596/msteams-platform/concepts/deploy-and-publish/apps-upload.md) | 84 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e5e4698a-fc61-4dfd-9372-ecbddd9201b5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/enable-app-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/90d2c5e0102c125c1f6c84fd3d0e2b0823eff596/msteams-platform/concepts/design/enable-app-customization.md) | 88 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/56b6341e-f01e-4d4b-836e-0ab75be0f119) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/first-app-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/90d2c5e0102c125c1f6c84fd3d0e2b0823eff596/msteams-platform/get-started/first-app-bot.md) | 88 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a4fbe092-890d-4a8d-8a8d-6eae452592e1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bots-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/90d2c5e0102c125c1f6c84fd3d0e2b0823eff596/msteams-platform/resources/bot-v3/bots-overview.md) | 89 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/706e4643-10d1-42da-8264-a52edaa2ebf3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/integrating-web-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/90d2c5e0102c125c1f6c84fd3d0e2b0823eff596/msteams-platform/samples/integrating-web-apps.md) | 85 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/79fdc966-0af9-48fe-9ccc-2655b7fb069c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/90d2c5e0102c125c1f6c84fd3d0e2b0823eff596/msteams-platform/tabs/what-are-tabs.md) | 88 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/13ced28d-d3e4-4084-8bce-dd26dfced252) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/MicrosoftDocs/msteams-docs/blob/90d2c5e0102c125c1f6c84fd3d0e2b0823eff596/msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md) | 90 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/69cdfacb-a61a-4300-98e5-4ad987aab3d2) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2021-07-29 09:35 UTC, opbld30 commented
Docs Build status updates of commit _[90d2c5e](https://github.com/MicrosoftDocs/msteams-docs/commits/90d2c5e0102c125c1f6c84fd3d0e2b0823eff596)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/meeting-app-extensibility?branch=pr-en-us-3675) |
[msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/bots/design/bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/design/bots?branch=pr-en-us-3675) |
[msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/bots/what-are-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/what-are-bots?branch=pr-en-us-3675) |
[msteams-platform/concepts/capabilities-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/concepts/capabilities-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/capabilities-overview?branch=pr-en-us-3675) |
[msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/apps-publish-overview?branch=pr-en-us-3675) |
[msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/concepts/deploy-and-publish/apps-upload.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/apps-upload?branch=pr-en-us-3675) |
[msteams-platform/concepts/design/enable-app-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/concepts/design/enable-app-customization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/design/enable-app-customization?branch=pr-en-us-3675) |
[msteams-platform/get-started/first-app-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/get-started/first-app-bot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-bot?branch=pr-en-us-3675) |
[msteams-platform/resources/bot-v3/bots-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/resources/bot-v3/bots-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bots-overview?branch=pr-en-us-3675) |
[msteams-platform/samples/integrating-web-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/samples/integrating-web-apps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/samples/integrating-web-apps?branch=pr-en-us-3675) |
[msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/tabs/what-are-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?branch=pr-en-us-3675) |
[msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-creating?branch=pr-en-us-3675) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C29%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202107290934340840-3675%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-28T03%3A38%3A39Z&ske=2021-08-04T03%3A43%3A39Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-29T09%3A30%3A55Z&se=2021-08-29T09%3A35%3A55Z&sr=b&sp=r&sig=VAZflQN2RDb62H9sGPLcTchIm%2FQsjA9kBslwQw6%2Fqm4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-29 11:05 UTC, v-abirade requested changes
@surbhigupta12 , please confirm if we can use 'LOB' in our document?

2021-08-04 04:05 UTC, ushaganesan submitted a review, later dismissed

2021-08-04 04:09 UTC, ushaganesan reviewed
GCC High is shown as GCC-High and DOD is not expanded anywhere in our service descriptions here https://docs.microsoft.com/en-us/office365/servicedescriptions/teams-service-description#feature-availability   Can we follow the same in this document?

2021-08-04 09:02 UTC, opbld31 commented
Docs Build status updates of commit _[37d524b](https://github.com/MicrosoftDocs/msteams-docs/commits/37d524bbd875006e155884dde27f758de9b56d66)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/meeting-app-extensibility?branch=pr-en-us-3675) |
[msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/bots/design/bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/design/bots?branch=pr-en-us-3675) |
[msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/bots/what-are-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/what-are-bots?branch=pr-en-us-3675) |
[msteams-platform/concepts/capabilities-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/concepts/capabilities-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/capabilities-overview?branch=pr-en-us-3675) |
[msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/apps-publish-overview?branch=pr-en-us-3675) |
[msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/concepts/deploy-and-publish/apps-upload.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/apps-upload?branch=pr-en-us-3675) |
[msteams-platform/concepts/design/enable-app-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/concepts/design/enable-app-customization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/design/enable-app-customization?branch=pr-en-us-3675) |
[msteams-platform/get-started/first-app-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/get-started/first-app-bot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-bot?branch=pr-en-us-3675) |
[msteams-platform/resources/bot-v3/bots-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/resources/bot-v3/bots-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bots-overview?branch=pr-en-us-3675) |
[msteams-platform/samples/integrating-web-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/samples/integrating-web-apps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/samples/integrating-web-apps?branch=pr-en-us-3675) |
[msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/tabs/what-are-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?branch=pr-en-us-3675) |
[msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-creating?branch=pr-en-us-3675) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C4%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202108040901340660-3675%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=dADxyX%2FW2NJFnAQNCD1rqzQehq%2FF98vySFSyu3nrB6w%3D&st=2021-08-04T08%3A57%3A00Z&se=2021-09-04T09%3A02%3A00Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-04 09:02 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We do not currently enforce a minimum score for content merged to the default branch. This will change in the future.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md](https://github.com/MicrosoftDocs/msteams-docs/blob/37d524bbd875006e155884dde27f758de9b56d66/msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md) | 90 | 30 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/59f429f8-f9b0-404f-a143-63819958f63c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/37d524bbd875006e155884dde27f758de9b56d66/msteams-platform/bots/design/bots.md) | 91 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/30595927-d206-4903-800c-022b15f1a2a1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/37d524bbd875006e155884dde27f758de9b56d66/msteams-platform/bots/what-are-bots.md) | 84 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1436386e-64a5-4eb4-ae63-04da46b2942a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/capabilities-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/37d524bbd875006e155884dde27f758de9b56d66/msteams-platform/concepts/capabilities-overview.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/90310921-60cc-41a6-9672-a46bda08cb74) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/37d524bbd875006e155884dde27f758de9b56d66/msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9cf56eee-6f92-4677-817c-6847b80fe9c6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/37d524bbd875006e155884dde27f758de9b56d66/msteams-platform/concepts/deploy-and-publish/apps-upload.md) | 84 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cd0f1cdb-cd52-4a40-81f7-4c21cf6c47c9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/enable-app-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/37d524bbd875006e155884dde27f758de9b56d66/msteams-platform/concepts/design/enable-app-customization.md) | 88 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4b12652b-8c60-4164-8a04-52ecde6e3457) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/first-app-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/37d524bbd875006e155884dde27f758de9b56d66/msteams-platform/get-started/first-app-bot.md) | 88 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/72539c3b-9f40-42e1-8489-21e7dad78d3b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bots-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/37d524bbd875006e155884dde27f758de9b56d66/msteams-platform/resources/bot-v3/bots-overview.md) | 89 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b590c565-2756-4621-808c-56afca41b7da) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/integrating-web-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/37d524bbd875006e155884dde27f758de9b56d66/msteams-platform/samples/integrating-web-apps.md) | 85 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/724c0a56-b932-4c4d-bf51-7d5e2feec8bd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/37d524bbd875006e155884dde27f758de9b56d66/msteams-platform/tabs/what-are-tabs.md) | 88 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ee856d62-acba-491c-8c6e-d8f4e907408f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/MicrosoftDocs/msteams-docs/blob/37d524bbd875006e155884dde27f758de9b56d66/msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md) | 90 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9363518a-c5dc-4f49-8dc0-62b21e5e32fc) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2021-08-04 12:22 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We do not currently enforce a minimum score for content merged to the default branch. This will change in the future.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cfc1b31cc68db5d1c9c229f3b91fdd52649e1d6f/msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md) | 90 | 30 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9ce3c807-153a-4ad5-8224-1b758472a8e6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cfc1b31cc68db5d1c9c229f3b91fdd52649e1d6f/msteams-platform/bots/design/bots.md) | 91 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/160d4afb-7e7e-4474-9045-ac6abbab24b2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cfc1b31cc68db5d1c9c229f3b91fdd52649e1d6f/msteams-platform/bots/what-are-bots.md) | 84 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e9bb2ddd-3501-483d-a78d-60b17cb0cb4b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/capabilities-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cfc1b31cc68db5d1c9c229f3b91fdd52649e1d6f/msteams-platform/concepts/capabilities-overview.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a5a4dfe8-c6c0-49b6-8321-26981e5e2f92) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cfc1b31cc68db5d1c9c229f3b91fdd52649e1d6f/msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bfd6307c-bf62-4219-91fb-85d34eb0f6df) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cfc1b31cc68db5d1c9c229f3b91fdd52649e1d6f/msteams-platform/concepts/deploy-and-publish/apps-upload.md) | 84 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/baa3adde-306d-47a5-8f8e-a9faac7ec2c7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/enable-app-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cfc1b31cc68db5d1c9c229f3b91fdd52649e1d6f/msteams-platform/concepts/design/enable-app-customization.md) | 88 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/39f75e3f-0901-4090-8777-8a178bd8c749) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/first-app-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cfc1b31cc68db5d1c9c229f3b91fdd52649e1d6f/msteams-platform/get-started/first-app-bot.md) | 88 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ed613a80-bc88-4221-b2d7-fdb2b8300f02) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bots-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cfc1b31cc68db5d1c9c229f3b91fdd52649e1d6f/msteams-platform/resources/bot-v3/bots-overview.md) | 89 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/98569f28-1db9-47eb-a23e-aa6d89aede12) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/integrating-web-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cfc1b31cc68db5d1c9c229f3b91fdd52649e1d6f/msteams-platform/samples/integrating-web-apps.md) | 85 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6d1386cc-c56a-4898-b6db-9e66e3bdf488) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cfc1b31cc68db5d1c9c229f3b91fdd52649e1d6f/msteams-platform/tabs/what-are-tabs.md) | 88 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9deb8e25-919a-4d84-b67f-45552c19741c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cfc1b31cc68db5d1c9c229f3b91fdd52649e1d6f/msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md) | 90 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/50bb68d1-4397-41c7-9cf7-a0a52a6ff38f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2021-08-04 12:22 UTC, opbld32 commented
Docs Build status updates of commit _[cfc1b31](https://github.com/MicrosoftDocs/msteams-docs/commits/cfc1b31cc68db5d1c9c229f3b91fdd52649e1d6f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/meeting-app-extensibility?branch=pr-en-us-3675) |
[msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/bots/design/bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/design/bots?branch=pr-en-us-3675) |
[msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/bots/what-are-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/what-are-bots?branch=pr-en-us-3675) |
[msteams-platform/concepts/capabilities-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/concepts/capabilities-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/capabilities-overview?branch=pr-en-us-3675) |
[msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/apps-publish-overview?branch=pr-en-us-3675) |
[msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/concepts/deploy-and-publish/apps-upload.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/apps-upload?branch=pr-en-us-3675) |
[msteams-platform/concepts/design/enable-app-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/concepts/design/enable-app-customization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/design/enable-app-customization?branch=pr-en-us-3675) |
[msteams-platform/get-started/first-app-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/get-started/first-app-bot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-bot?branch=pr-en-us-3675) |
[msteams-platform/resources/bot-v3/bots-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/resources/bot-v3/bots-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bots-overview?branch=pr-en-us-3675) |
[msteams-platform/samples/integrating-web-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/samples/integrating-web-apps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/samples/integrating-web-apps?branch=pr-en-us-3675) |
[msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/tabs/what-are-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?branch=pr-en-us-3675) |
[msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-creating?branch=pr-en-us-3675) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C4%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202108041221327250-3675%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=9C86utRl0FJ64dE%2BGDMz9Vw7wo0w0J3TFyJoZZG1ByM%3D&st=2021-08-04T12%3A17%3A37Z&se=2021-09-04T12%3A22%3A37Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-04 12:51 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We do not currently enforce a minimum score for content merged to the default branch. This will change in the future.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md](https://github.com/MicrosoftDocs/msteams-docs/blob/71eeaea94e38e36da66b19b828e8f8b187f66c25/msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md) | 90 | 30 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/44ce7e43-eec1-4db5-983e-ea80e78727e3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/71eeaea94e38e36da66b19b828e8f8b187f66c25/msteams-platform/bots/design/bots.md) | 91 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9939aaec-d128-42d4-ba53-de654b6ed330) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/71eeaea94e38e36da66b19b828e8f8b187f66c25/msteams-platform/bots/what-are-bots.md) | 84 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4e3077ab-7d54-4947-998e-86e7debf9384) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/capabilities-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/71eeaea94e38e36da66b19b828e8f8b187f66c25/msteams-platform/concepts/capabilities-overview.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d1d37896-41d2-4a43-a4d5-ff9a5621bdd5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/71eeaea94e38e36da66b19b828e8f8b187f66c25/msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/02f89bad-6390-4753-bd3b-86421d35383b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/71eeaea94e38e36da66b19b828e8f8b187f66c25/msteams-platform/concepts/deploy-and-publish/apps-upload.md) | 84 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f333936b-caad-4d4c-9396-989e522679f9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/enable-app-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/71eeaea94e38e36da66b19b828e8f8b187f66c25/msteams-platform/concepts/design/enable-app-customization.md) | 88 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8bec3c32-a14d-40ae-b269-6a4825d725a0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/first-app-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/71eeaea94e38e36da66b19b828e8f8b187f66c25/msteams-platform/get-started/first-app-bot.md) | 88 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ea0d98b5-014b-42a8-b3d1-fb82dabe1d04) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bots-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/71eeaea94e38e36da66b19b828e8f8b187f66c25/msteams-platform/resources/bot-v3/bots-overview.md) | 89 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f88c235b-6a74-4e3a-aaad-ccf1f694589f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/integrating-web-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/71eeaea94e38e36da66b19b828e8f8b187f66c25/msteams-platform/samples/integrating-web-apps.md) | 85 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/118d2782-cdcc-4e32-9196-ff714cf3710d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/71eeaea94e38e36da66b19b828e8f8b187f66c25/msteams-platform/tabs/what-are-tabs.md) | 88 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/90657105-919a-46dd-8d97-eb2688c9aedb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/MicrosoftDocs/msteams-docs/blob/71eeaea94e38e36da66b19b828e8f8b187f66c25/msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md) | 90 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/87db0029-8e1e-4998-8413-1b7655eb6dfe) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2021-08-04 12:52 UTC, opbld33 commented
Docs Build status updates of commit _[71eeaea](https://github.com/MicrosoftDocs/msteams-docs/commits/71eeaea94e38e36da66b19b828e8f8b187f66c25)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/meeting-app-extensibility?branch=pr-en-us-3675) |
[msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/bots/design/bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/design/bots?branch=pr-en-us-3675) |
[msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/bots/what-are-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/what-are-bots?branch=pr-en-us-3675) |
[msteams-platform/concepts/capabilities-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/concepts/capabilities-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/capabilities-overview?branch=pr-en-us-3675) |
[msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/apps-publish-overview?branch=pr-en-us-3675) |
[msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/concepts/deploy-and-publish/apps-upload.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/apps-upload?branch=pr-en-us-3675) |
[msteams-platform/concepts/design/enable-app-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/concepts/design/enable-app-customization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/design/enable-app-customization?branch=pr-en-us-3675) |
[msteams-platform/get-started/first-app-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/get-started/first-app-bot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-bot?branch=pr-en-us-3675) |
[msteams-platform/resources/bot-v3/bots-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/resources/bot-v3/bots-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bots-overview?branch=pr-en-us-3675) |
[msteams-platform/samples/integrating-web-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/samples/integrating-web-apps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/samples/integrating-web-apps?branch=pr-en-us-3675) |
[msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/tabs/what-are-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?branch=pr-en-us-3675) |
[msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1811749-GCC/msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-creating?branch=pr-en-us-3675) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C4%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202108041251029532-3675%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=8oGwk8jheqOkKZedhVlSysbtfNlTVG%2Bw2fATn4xk294%3D&st=2021-08-04T12%3A47%3A11Z&se=2021-09-04T12%3A52%3A11Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-04 12:56 UTC, v-abirade approved these changes
Approve

2021-08-04 13:26 UTC, merged