[Docenhancement][Sideloadingnote]
MicrosoftDocs/msteams-docs pull request #3797
Opened 2021-07-08 06:16 UTC by v-rodriguezd

Added note for sideloading app.

2021-07-08 06:17 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We do not currently enforce a minimum score for content merged to the default branch. This will change in the future.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/get-started/get-started-use-app-studio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/80859b5e7f040c43fa2435eb286a787a08e1aba5/msteams-platform/includes/get-started/get-started-use-app-studio.md) | 91 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/21f6cdd9-a6b8-4f23-b7ac-8fcde5241bad) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2021-07-08 06:17 UTC, opbld31 commented
Docs Build status updates of commit _[80859b5](https://github.com/MicrosoftDocs/msteams-docs/commits/80859b5e7f040c43fa2435eb286a787a08e1aba5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/includes/get-started/get-started-use-app-studio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/sideloading-note/msteams-platform/includes/get-started/get-started-use-app-studio.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/get-started-dotnet-app-studio?branch=pr-en-us-3797) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C8%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202107080616553032-3797%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-06T06%3A24%3A56Z&ske=2021-07-13T06%3A29%3A56Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-08T06%3A12%3A35Z&se=2021-08-08T06%3A17%3A35Z&sr=b&sp=r&sig=32VikQhDzwXvb9tf79daPCo5YX0zwD%2BYBeVwEaz9CSE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-08 08:01 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We do not currently enforce a minimum score for content merged to the default branch. This will change in the future.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/get-started/get-started-use-app-studio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d3cb47a19670aed8b050ff4ac9af28b0cdbd057d/msteams-platform/includes/get-started/get-started-use-app-studio.md) | 91 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d0e6d5cc-a8a7-443e-8f7d-811db09d1c19) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2021-07-08 08:01 UTC, opbld30 commented
Docs Build status updates of commit _[d3cb47a](https://github.com/MicrosoftDocs/msteams-docs/commits/d3cb47a19670aed8b050ff4ac9af28b0cdbd057d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/includes/get-started/get-started-use-app-studio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/sideloading-note/msteams-platform/includes/get-started/get-started-use-app-studio.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/get-started-dotnet-app-studio?branch=pr-en-us-3797) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C8%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202107080800392320-3797%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-06T08%3A08%3A15Z&ske=2021-07-13T08%3A13%3A15Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-08T07%3A56%3A19Z&se=2021-08-08T08%3A01%3A19Z&sr=b&sp=r&sig=E2D6o%2BI5u3QXRF%2FyKS%2FmZ7J5QUofye3h2XXE1ImJVWQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-09 09:44 UTC, v-abirade submitted a review, later dismissed
Approve

2021-07-09 13:47 UTC, Wajeed-msft requested changes

2021-07-09 13:47 UTC, Wajeed-msft commented on msteams-platform/includes/get-started/get-started-use-app-studio.md
> +    > If you are unable to sideload the app, verify whether you have [prepared your development environment](#prepare-your-development-environment).
```suggestion
    > If you are unable to sideload the app, verify whether you have [enabled custom app uploading](#prepare-your-development-environment).
```

2021-07-09 13:49 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We do not currently enforce a minimum score for content merged to the default branch. This will change in the future.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/get-started/get-started-use-app-studio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/caea5ddb7313f48d72a3ba78a62e3395df6818e5/msteams-platform/includes/get-started/get-started-use-app-studio.md) | 91 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aa6b24dd-da47-4628-aaee-8a93206456c6) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2021-07-09 13:49 UTC, opbld30 commented
Docs Build status updates of commit _[caea5dd](https://github.com/MicrosoftDocs/msteams-docs/commits/caea5ddb7313f48d72a3ba78a62e3395df6818e5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/includes/get-started/get-started-use-app-studio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/sideloading-note/msteams-platform/includes/get-started/get-started-use-app-studio.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/get-started-dotnet-app-studio?branch=pr-en-us-3797) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C9%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202107091349021879-3797%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-06T07%3A01%3A02Z&ske=2021-07-13T07%3A06%3A02Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-09T13%3A44%3A42Z&se=2021-08-09T13%3A49%3A42Z&sr=b&sp=r&sig=Rc4dVuNw5q2C8TDD%2Bx7Y9MFKZPVypkGCrUnd0S2K5u4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-09 13:49 UTC, Wajeed-msft approved these changes

2021-07-09 13:50 UTC, merged