Adding external apps and Azure Communication Services
MicrosoftDocs/msteams-docs pull request #3858
Opened 2021-07-21 18:43 UTC by tophpalmer

2021-07-21 18:44 UTC, opbld31 commented
Docs Build status updates of commit _[d06babf](https://github.com/tophpalmer/msteams-docs/commits/d06babf2d9b90fd4c9538487e772503ad79c618a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/overview.md](https://github.com/tophpalmer/msteams-docs/blob/patch-1/msteams-platform/overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/overview?branch=pr-en-us-3858) | [Details](#user-content-3d1527dbf8dc8d1a982d21bb96023425-2b549c06)

<a id="3d1527dbf8dc8d1a982d21bb96023425-2b549c06"></a>
### [msteams-platform/overview.md](https://github.com/tophpalmer/msteams-docs/blob/patch-1/msteams-platform/overview.md)
 - **Line 207, Column 207**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/azure/communication-services/overview' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 211, Column 47**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/azure/communication-services/concepts/teams-interop' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 211, Column 377**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/skype-sdk/appsdk/skypeappsdk' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C21%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202107211843201232-3858%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-19T02%3A39%3A52Z&ske=2021-07-26T02%3A44%3A52Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-21T18%3A39%3A05Z&se=2021-08-21T18%3A44%3A05Z&sr=b&sp=r&sig=TNepotR53YiUqbmfSahIgbfBXG0qOiFmO%2B4CrdMKe70%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-21 18:44 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We do not currently enforce a minimum score for content merged to the default branch. This will change in the future.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d06babf2d9b90fd4c9538487e772503ad79c618a/msteams-platform/overview.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8cae064c-1226-4c49-9eff-ec6235973f7d) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2021-07-22 08:25 UTC, v-abirade reviewed
Please implement the change.

2021-07-22 08:25 UTC, v-abirade commented on msteams-platform/overview.md
> +Azure Communication Services are cloud-based services with REST APIs and client library SDKs to help you integrate communication into your own custom applications. A [UI library](https://azure.github
You can embed generic or Teams-styled components for calling and chatting with the help of [UI library](https://azure.github.io/communication-ui-library/).

2021-07-22 08:29 UTC, v-abirade requested changes
Please update the changes as suggested.

2021-07-22 08:29 UTC, v-abirade commented on msteams-platform/overview.md
> +This page focuses on embedding your own experiences into Microsoft Teams. If you'd like to reverse this model and integrate Teams or other communication capabilities into your own app experience, che
see [Azure Communication Services](https://docs.microsoft.com/azure/communication-services/overview).

2021-07-29 07:05 UTC, v-abirade commented
Hi @tophpalmer,

Please incorporate the changes as suggested.

2021-08-02 14:07 UTC, v-abirade requested changes
@tophpalmer,

Please make the changes.

2021-08-03 23:13 UTC, opbld32 commented
Docs Build status updates of commit _[a6144b8](https://github.com/tophpalmer/msteams-docs/commits/a6144b844419f3149de406da103205774f89524f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/overview.md](https://github.com/tophpalmer/msteams-docs/blob/patch-1/msteams-platform/overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/overview?branch=pr-en-us-3858) | [Details](#user-content-3d1527dbf8dc8d1a982d21bb96023425-6a6039af)

<a id="3d1527dbf8dc8d1a982d21bb96023425-6a6039af"></a>
### [msteams-platform/overview.md](https://github.com/tophpalmer/msteams-docs/blob/patch-1/msteams-platform/overview.md)
 - **Line 207, Column 201**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/azure/communication-services/overview' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 211, Column 47**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/azure/communication-services/concepts/teams-interop' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 211, Column 377**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/skype-sdk/appsdk/skypeappsdk' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C3%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202108032312533314-3858%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=BX6vOHogIYSZZn5mXWRZ8HBB8RTJLI9%2FGTPZKJdGVjk%3D&st=2021-08-03T23%3A08%3A21Z&se=2021-09-03T23%3A13%3A21Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-03 23:13 UTC, tophpalmer commented
@v-abirade thank you for the feedback, changes are committed!

2021-08-03 23:13 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We do not currently enforce a minimum score for content merged to the default branch. This will change in the future.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a6144b844419f3149de406da103205774f89524f/msteams-platform/overview.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d2fdd51c-dbf9-4a11-a93f-be81fe8cf8d3) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2021-08-04 04:37 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We do not currently enforce a minimum score for content merged to the default branch. This will change in the future.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dd05186303b7eb838cb26d4a000d4135bfe73dab/msteams-platform/overview.md) | 91 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9386ae68-d07e-47c3-9983-3efb974cd544) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2021-08-04 04:38 UTC, opbld32 commented
Docs Build status updates of commit _[dd05186](https://github.com/tophpalmer/msteams-docs/commits/dd05186303b7eb838cb26d4a000d4135bfe73dab)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/overview.md](https://github.com/tophpalmer/msteams-docs/blob/patch-1/msteams-platform/overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/overview?branch=pr-en-us-3858) | [Details](#user-content-3d1527dbf8dc8d1a982d21bb96023425-71170101)

<a id="3d1527dbf8dc8d1a982d21bb96023425-71170101"></a>
### [msteams-platform/overview.md](https://github.com/tophpalmer/msteams-docs/blob/patch-1/msteams-platform/overview.md)
 - **Line 207, Column 235**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/azure/communication-services/overview' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 209, Column 47**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/azure/communication-services/concepts/teams-interop' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 211, Column 154**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/skype-sdk/appsdk/skypeappsdk' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C4%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202108040436567591-3858%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=gkcDhaCHdZtS%2FwVWLVC7dIcYls6J3IZJBvvqb1edJTU%3D&st=2021-08-04T04%3A32%3A59Z&se=2021-09-04T04%3A37%3A59Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-04 04:41 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We do not currently enforce a minimum score for content merged to the default branch. This will change in the future.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1597567f20a6099f205ba4dd105409632969ade2/msteams-platform/overview.md) | 91 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/63425617-1f3b-48bb-90a8-0970733ac71c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2021-08-04 04:42 UTC, opbld33 commented
Docs Build status updates of commit _[1597567](https://github.com/tophpalmer/msteams-docs/commits/1597567f20a6099f205ba4dd105409632969ade2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/overview.md](https://github.com/tophpalmer/msteams-docs/blob/patch-1/msteams-platform/overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/overview?branch=pr-en-us-3858) | [Details](#user-content-3d1527dbf8dc8d1a982d21bb96023425-096f7bb0)

<a id="3d1527dbf8dc8d1a982d21bb96023425-096f7bb0"></a>
### [msteams-platform/overview.md](https://github.com/tophpalmer/msteams-docs/blob/patch-1/msteams-platform/overview.md)
 - **Line 207, Column 235**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/azure/communication-services/overview' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 209, Column 83**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/azure/communication-services/concepts/teams-interop' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 211, Column 154**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/skype-sdk/appsdk/skypeappsdk' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C4%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202108040440369452-3858%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=pskjtE72eCaOguMpp1AjoOL6L27JC8jhvVT1p753B0c%3D&st=2021-08-04T04%3A37%3A31Z&se=2021-09-04T04%3A42%3A31Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-04 12:30 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We do not currently enforce a minimum score for content merged to the default branch. This will change in the future.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f912e7ad1332edae832498da5b37a633d5c44579/msteams-platform/overview.md) | 91 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/be7558d6-61dc-4f6c-ba70-672b904646f2) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2021-08-04 12:31 UTC, opbld32 commented
Docs Build status updates of commit _[f912e7a](https://github.com/tophpalmer/msteams-docs/commits/f912e7ad1332edae832498da5b37a633d5c44579)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/overview.md](https://github.com/tophpalmer/msteams-docs/blob/patch-1/msteams-platform/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/overview?branch=pr-en-us-3858) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C4%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202108041230040190-3858%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=qXBQnGTESrF26Yq3McUiqdJxhgmtCAkpJoCk5yazZOk%3D&st=2021-08-04T12%3A26%3A15Z&se=2021-09-04T12%3A31%3A15Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-04 12:32 UTC, v-abirade approved these changes
Approve

2021-08-04 13:08 UTC, merged