Add Teams Toolkit Support guide
MicrosoftDocs/msteams-docs pull request #3859
Opened 2021-07-21 22:48 UTC by zyxiaoyuer

I added a row to the table for Teams Toolkit support

2021-07-21 22:49 UTC, opbld32 commented
Docs Build status updates of commit _[35b3a09](https://github.com/zyxiaoyuer/msteams-docs/commits/35b3a09a74264623c598702f499bddeaf4162928)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/feedback.md](https://github.com/zyxiaoyuer/msteams-docs/blob/patch-2/msteams-platform/feedback.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/feedback?branch=pr-en-us-3859) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C21%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202107212248245151-3859%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-19T03%3A25%3A36Z&ske=2021-07-26T03%3A30%3A36Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-21T22%3A44%3A08Z&se=2021-08-21T22%3A49%3A08Z&sr=b&sp=r&sig=L1foO6ygpaA3aShazcNX8agPze0f2gxXRiXJDn0ydOY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-21 22:49 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We do not currently enforce a minimum score for content merged to the default branch. This will change in the future.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/35b3a09a74264623c598702f499bddeaf4162928/msteams-platform/feedback.md) | 80 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/263067cc-2d11-42c1-8416-aa58b039952a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2021-07-26 16:20 UTC, v-abirade requested changes

2021-07-26 16:20 UTC, v-abirade commented on msteams-platform/feedback.md
> +|          **Teams Toolkit or TeamsFx SDK and CLI issues**           |     <ul><li> [Github Issues](https://github.com/OfficeDev/TeamsFx/issues) Create new issue on the [TeamsFx (Microsoft Teams Fram
Please rephrase:
We love Github Issues and our extensive support is assured for customers who ask questions there.

2021-07-28 12:51 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We do not currently enforce a minimum score for content merged to the default branch. This will change in the future.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/df13ea94369206a6356895175105d40b486d9606/msteams-platform/feedback.md) | 80 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f8ebbd58-b741-4018-9fe5-7790f12a2766) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2021-07-28 12:52 UTC, opbld31 commented
Docs Build status updates of commit _[df13ea9](https://github.com/zyxiaoyuer/msteams-docs/commits/df13ea94369206a6356895175105d40b486d9606)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/feedback.md](https://github.com/zyxiaoyuer/msteams-docs/blob/patch-2/msteams-platform/feedback.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/feedback?branch=pr-en-us-3859) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C28%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202107281250415882-3859%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-28T04%3A12%3A54Z&ske=2021-08-04T04%3A17%3A54Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-28T12%3A47%3A03Z&se=2021-08-28T12%3A52%3A03Z&sr=b&sp=r&sig=id%2FrQ2IftZCS8t5S2aHydx1TGtypJvBAUX%2F5l1XzqPM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-28 12:52 UTC, zyxiaoyuer commented on msteams-platform/feedback.md
> +|          **Teams Toolkit or TeamsFx SDK and CLI issues**           |     <ul><li> [Github Issues](https://github.com/OfficeDev/TeamsFx/issues) Create new issue on the [TeamsFx (Microsoft Teams Fram
done rephrasing, please check.

2021-07-29 06:56 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We do not currently enforce a minimum score for content merged to the default branch. This will change in the future.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ed965eb1da1caafcb8b14514bff82b6a2c8e6c51/msteams-platform/feedback.md) | 79 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d616f646-d141-461d-9ff9-a105fd541011) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2021-07-29 06:57 UTC, opbld31 commented
Docs Build status updates of commit _[ed965eb](https://github.com/zyxiaoyuer/msteams-docs/commits/ed965eb1da1caafcb8b14514bff82b6a2c8e6c51)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/feedback.md](https://github.com/zyxiaoyuer/msteams-docs/blob/patch-2/msteams-platform/feedback.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/feedback?branch=pr-en-us-3859) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C29%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202107290656206495-3859%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-28T18%3A46%3A04Z&ske=2021-08-04T18%3A51%3A04Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-29T06%3A52%3A34Z&se=2021-08-29T06%3A57%3A34Z&sr=b&sp=r&sig=v8PyxpRTQHT1BgsLpZYIjWdta0R1W1xNRJ3kA7j5aGE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-29 07:02 UTC, v-abirade approved these changes
Approved

2021-08-02 12:10 UTC, merged