[Docbug][ESlintsupport][3879]
MicrosoftDocs/msteams-docs pull request #3895
Opened 2021-07-30 05:15 UTC by v-rodriguezd

Added ESLint support question to Manifest file. Please review.

2021-07-30 05:15 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We do not currently enforce a minimum score for content merged to the default branch. This will change in the future.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0d90eb25f1b4a1aad93ede3d4677ff8a43cd019c/msteams-platform/tabs/how-to/create-personal-tab.md) | 98 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b3ba3c9f-cb7b-4e61-892a-f10c19084088) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2021-07-30 05:15 UTC, opbld31 commented
Docs Build status updates of commit _[0d90eb2](https://github.com/MicrosoftDocs/msteams-docs/commits/0d90eb25f1b4a1aad93ede3d4677ff8a43cd019c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ESLintsupport-3879/msteams-platform/tabs/how-to/create-personal-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3895) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C30%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202107300515106752-3895%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-28T03%3A34%3A07Z&ske=2021-08-04T03%3A39%3A07Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-30T05%3A10%3A50Z&se=2021-08-30T05%3A15%3A50Z&sr=b&sp=r&sig=%2BgodIIpEsTuDQvG8L7PdgMDDMfjJtXUz%2F1CStaI11P0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-03 05:10 UTC, v-abirade requested changes
@v-rodriguezd,

Please make the changes.

2021-08-03 05:10 UTC, v-abirade commented on msteams-platform/tabs/how-to/create-personal-tab.md
> +    This field isn't required and must be only used if you're already part of the [Microsoft Partner Network](https://partner.microsoft.com).
must be used only if you're already part of the...

2021-08-03 09:26 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We do not currently enforce a minimum score for content merged to the default branch. This will change in the future.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b02c983e1b1f89de3304fab007105c20095570c2/msteams-platform/tabs/how-to/create-personal-tab.md) | 98 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f1fc94d5-3b3f-4860-89ac-934e9444d3d4) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2021-08-03 09:27 UTC, opbld33 commented
Docs Build status updates of commit _[b02c983](https://github.com/MicrosoftDocs/msteams-docs/commits/b02c983e1b1f89de3304fab007105c20095570c2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ESLintsupport-3879/msteams-platform/tabs/how-to/create-personal-tab.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3895) | [Details](#user-content-ba3b05282a3fc888b3c1d57fa2074e3b-ce43c229)

<a id="ba3b05282a3fc888b3c1d57fa2074e3b-ce43c229"></a>
### [msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ESLintsupport-3879/msteams-platform/tabs/how-to/create-personal-tab.md)
 - **Line 243, Column 87**: **[Suggestion-[disallowed-html-tag](https://review.docs.microsoft.com/help/contribute/validation-ref/disallowed-html-tag?branch=main)]** `````HTML tag 'yourDefaultAppNameTab' isn't allowed. Disallowed HTML poses a security risk and must be replaced with approved Docs Markdown syntax.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C3%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202108030926115428-3895%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=qR22df6naJUUFV6XNAmSovBL4ryz8V%2F5xCGuW1sei9U%3D&st=2021-08-03T09%3A22%3A33Z&se=2021-09-03T09%3A27%3A33Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-03 09:34 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We do not currently enforce a minimum score for content merged to the default branch. This will change in the future.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/79ee2b818389594f8ebc4020dae3841f3d961f66/msteams-platform/tabs/how-to/create-personal-tab.md) | 98 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0bb4cc66-35eb-461f-a99d-933997f5875a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2021-08-03 09:35 UTC, opbld31 commented
Docs Build status updates of commit _[79ee2b8](https://github.com/MicrosoftDocs/msteams-docs/commits/79ee2b818389594f8ebc4020dae3841f3d961f66)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ESLintsupport-3879/msteams-platform/tabs/how-to/create-personal-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-3895) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C3%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202108030933386347-3895%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=a2xw%2FwJ7n9hfOY18sbWGDJL1Pt%2BVAAMghdW1f8AdDiI%3D&st=2021-08-03T09%3A30%3A05Z&se=2021-09-03T09%3A35%3A05Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-03 11:15 UTC, v-abirade approved these changes
Approve

2021-08-03 11:19 UTC, merged