[Docenhancement][BotSDKmethods][3846]
MicrosoftDocs/msteams-docs pull request #3898
Opened 2021-08-02 08:51 UTC by v-rodriguezd

Added table for Bot framework SDK methods. Please review.

2021-08-02 08:52 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We do not currently enforce a minimum score for content merged to the default branch. This will change in the future.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/706490bb91f24baade368b42c5dee43fafdbff90/msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md) | 96 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2571fdd2-57bf-44c8-b82f-523fd0b948c1) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2021-08-02 08:53 UTC, opbld32 commented
Docs Build status updates of commit _[706490b](https://github.com/MicrosoftDocs/msteams-docs/commits/706490bb91f24baade368b42c5dee43fafdbff90)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BotSDKmethods/msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3898) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C2%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202108020851581843-3898%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=eaoJD3B3JuUMOm1M4mOW2lYrrEnHtYJY%2FgDyzNGWM4s%3D&st=2021-08-02T08%3A48%3A24Z&se=2021-09-02T08%3A53%3A24Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-02 12:17 UTC, v-abirade approved these changes
Approved.

2021-08-02 12:19 UTC, surbhigupta12 commented
@v-rodriguezd, please resolve conflicts.

2021-08-02 12:31 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We do not currently enforce a minimum score for content merged to the default branch. This will change in the future.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0f16c8f122b23d2efd36aad7818cf85c52f0c925/msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md) | 96 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b6f7b759-70c6-4467-bb60-2ff190c81de7) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2021-08-02 12:32 UTC, opbld32 commented
Docs Build status updates of commit _[0f16c8f](https://github.com/MicrosoftDocs/msteams-docs/commits/0f16c8f122b23d2efd36aad7818cf85c52f0c925)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BotSDKmethods/msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3898) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C2%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202108021231158692-3898%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=fT%2BXd%2BfsOfYB9vr9jku8AGsjFe1krmixc8Nw42AC8%2FA%3D&st=2021-08-02T12%3A27%3A32Z&se=2021-09-02T12%3A32%3A32Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-02 12:33 UTC, v-rodriguezd commented
> @v-rodriguezd, please resolve conflicts.

Done. Thanks.

2021-08-02 14:05 UTC, v-abirade requested changes
@v-rodriguezd, 
Please make the changes.

2021-08-02 14:05 UTC, v-abirade commented on msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md
> +The Meeting Details API enables your app to get static meeting metadata. The metadata provide data points that don't change dynamically.
The metadata provides data points that don't change dynamically.

2021-08-03 06:05 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We do not currently enforce a minimum score for content merged to the default branch. This will change in the future.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e66a89a02b0d5716ec52d51c500170b88b264a1e/msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md) | 96 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9d7d70a0-c0ff-4777-ab18-4f14fdc501c6) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2021-08-03 06:07 UTC, opbld32 commented
Docs Build status updates of commit _[e66a89a](https://github.com/MicrosoftDocs/msteams-docs/commits/e66a89a02b0d5716ec52d51c500170b88b264a1e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BotSDKmethods/msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3898) | [Details](#user-content-351f2ba35302ce86d26f9fa3fc15a178-07862b96)

<a id="351f2ba35302ce86d26f9fa3fc15a178-07862b96"></a>
### [msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BotSDKmethods/msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md)
 - **Line 63, Column 130**: **[Suggestion-[disallowed-html-tag](https://review.docs.microsoft.com/help/contribute/validation-ref/disallowed-html-tag?branch=main)]** `````HTML tag 'title' isn't allowed. Disallowed HTML poses a security risk and must be replaced with approved Docs Markdown syntax.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C3%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202108030604586993-3898%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=qddKfmcZqa%2Bc3FkVk%2BWGx4lvcxLKMYoqlO1qiZoIJSQ%3D&st=2021-08-03T06%3A02%3A04Z&se=2021-09-03T06%3A07%3A04Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-03 06:12 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We do not currently enforce a minimum score for content merged to the default branch. This will change in the future.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c83b33e50158d290f0adc009b0ff56c384ebba4d/msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md) | 97 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f9a72c72-60ca-48dd-83b1-2f3a03b346fd) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2021-08-03 06:13 UTC, opbld30 commented
Docs Build status updates of commit _[c83b33e](https://github.com/MicrosoftDocs/msteams-docs/commits/c83b33e50158d290f0adc009b0ff56c384ebba4d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BotSDKmethods/msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?branch=pr-en-us-3898) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C3%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202108030612291343-3898%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=ErlcZbIK4EqGzGJ2Ki4mwVj%2BWBNDQ31P%2BUPcxqKvyHc%3D&st=2021-08-03T06%3A08%3A43Z&se=2021-09-03T06%3A13%3A43Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-03 08:22 UTC, v-abirade approved these changes
Approved

2021-08-03 11:20 UTC, merged