Update design-teams-app-overview.md
MicrosoftDocs/msteams-docs pull request #3969
Opened 2021-08-17 05:45 UTC by pallabiwrites

The decsription of the "Collaborative" feature was not well-defined. It merely stated the information provided under the "Teams app design principles" heading. I have fixed that.

2021-08-17 05:46 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We do not currently enforce a minimum score for content merged to the default branch. This will change in the future.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/design/design-teams-app-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/81f19ab0850e0e646e7a79acb889aefee53d35e9/msteams-platform/concepts/design/design-teams-app-overview.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8cbf6d74-bd57-4b67-a3df-4ae73d58d2b3) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2021-08-17 05:47 UTC, opbld33 commented
Docs Build status updates of commit _[81f19ab](https://github.com/pallabiwrites/msteams-docs/commits/81f19ab0850e0e646e7a79acb889aefee53d35e9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/design/design-teams-app-overview.md](https://github.com/pallabiwrites/msteams-docs/blob/patch-6/msteams-platform/concepts/design/design-teams-app-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/design/design-teams-app-overview?branch=pr-en-us-3969) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C17%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202108170545531846-3969%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=pc%2B8b8kofm0qF2sipdALz7mFtx7jyD7nsA4kc0jXJmI%3D&st=2021-08-17T05%3A42%3A19Z&se=2021-09-17T05%3A47%3A19Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-17 06:03 UTC, v-abirade requested changes
Request change

2021-08-17 06:20 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We do not currently enforce a minimum score for content merged to the default branch. This will change in the future.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/design/design-teams-app-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cc41b12c8d750be7484ab43ce65c4b4c1e031d7d/msteams-platform/concepts/design/design-teams-app-overview.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/31a6a3eb-40c3-4845-a594-9340d5790492) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2021-08-17 06:20 UTC, pallabiwrites commented on msteams-platform/concepts/design/design-teams-app-overview.md
> +The app is designed to promote collaboration through coordinated and shared activities among the users.
Fixed.

2021-08-17 06:20 UTC, opbld31 commented
Docs Build status updates of commit _[cc41b12](https://github.com/pallabiwrites/msteams-docs/commits/cc41b12c8d750be7484ab43ce65c4b4c1e031d7d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/design/design-teams-app-overview.md](https://github.com/pallabiwrites/msteams-docs/blob/patch-6/msteams-platform/concepts/design/design-teams-app-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/design/design-teams-app-overview?branch=pr-en-us-3969) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C17%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202108170619549958-3969%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=WGWy6rJH32IbN4vxNOrHb5GKheJ4Xq7JGnz9iRULH2U%3D&st=2021-08-17T06%3A15%3A35Z&se=2021-09-17T06%3A20%3A35Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-17 06:23 UTC, v-abirade approved these changes
Approved

2021-09-13 14:26 UTC, surbhigupta12 approved these changes
Approved

2021-09-13 14:26 UTC, merged