[Doc enhancement][Add info][Issue3923]
MicrosoftDocs/msteams-docs pull request #3971
Opened 2021-08-17 06:16 UTC by Rajeshwari-v

Please review.

2021-08-17 06:16 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We do not currently enforce a minimum score for content merged to the default branch. This will change in the future.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d9b0294b5015f552c3ee094d06a81fbfaa46e662/msteams-platform/concepts/build-and-test/deep-links.md) | 83 | 54 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cc1ca2bb-19ec-49d1-b7e1-001f138b0ab2) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2021-08-17 06:17 UTC, opbld32 commented
Docs Build status updates of commit _[d9b0294](https://github.com/MicrosoftDocs/msteams-docs/commits/d9b0294b5015f552c3ee094d06a81fbfaa46e662)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-enhancement-add-details-3923/msteams-platform/concepts/build-and-test/deep-links.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links?branch=pr-en-us-3971) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C17%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202108170616195098-3971%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=YRdbouaWkHUR4uf4D6AfeyQD4QkbQ5l3Ov8StJK3bdo%3D&st=2021-08-17T06%3A12%3A36Z&se=2021-09-17T06%3A17%3A36Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-17 06:25 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We do not currently enforce a minimum score for content merged to the default branch. This will change in the future.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f6b5a5ee3e1b51e5c8f82b72c7737f8d953ea2bd/msteams-platform/concepts/build-and-test/deep-links.md) | 83 | 54 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/50a296a2-ea83-4fe7-9bf3-e0fbb97be25d) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2021-08-17 06:25 UTC, opbld32 commented
Docs Build status updates of commit _[f6b5a5e](https://github.com/MicrosoftDocs/msteams-docs/commits/f6b5a5ee3e1b51e5c8f82b72c7737f8d953ea2bd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-enhancement-add-details-3923/msteams-platform/concepts/build-and-test/deep-links.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links?branch=pr-en-us-3971) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C17%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202108170624371884-3971%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=4jtUFK1sVCjRjjHFZheQxBzqO%2Fl6MipUCMPYxoOXCIU%3D&st=2021-08-17T06%3A20%3A47Z&se=2021-09-17T06%3A25%3A47Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-17 08:43 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We do not currently enforce a minimum score for content merged to the default branch. This will change in the future.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cc6797e38e29b09c0fffe4238037c857a3932eab/msteams-platform/concepts/build-and-test/deep-links.md) | 83 | 54 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6eeb2b80-8c02-4a87-9829-378495be2e23) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2021-08-17 08:44 UTC, opbld30 commented
Docs Build status updates of commit _[cc6797e](https://github.com/MicrosoftDocs/msteams-docs/commits/cc6797e38e29b09c0fffe4238037c857a3932eab)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-enhancement-add-details-3923/msteams-platform/concepts/build-and-test/deep-links.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links?branch=pr-en-us-3971) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C17%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202108170842525999-3971%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=e%2Fdt7I6npeoYVYDDhiWrZwGzN0TzuAVsr29y74kvDQI%3D&st=2021-08-17T08%3A39%3A08Z&se=2021-09-17T08%3A44%3A08Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-17 10:17 UTC, v-abirade requested changes
As discussed.

2021-08-17 10:17 UTC, v-abirade commented on msteams-platform/concepts/build-and-test/deep-links.md
> +Following is the example format of deeplink to files:
The following example...

2021-08-17 10:42 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We do not currently enforce a minimum score for content merged to the default branch. This will change in the future.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/687b69dd0a544a48106364d1ce92a29d1cc67745/msteams-platform/concepts/build-and-test/deep-links.md) | 83 | 55 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fadc5d77-a7ab-435a-8421-8db629db20cd) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2021-08-17 10:43 UTC, opbld33 commented
Docs Build status updates of commit _[687b69d](https://github.com/MicrosoftDocs/msteams-docs/commits/687b69dd0a544a48106364d1ce92a29d1cc67745)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-enhancement-add-details-3923/msteams-platform/concepts/build-and-test/deep-links.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links?branch=pr-en-us-3971) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C17%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202108171042259805-3971%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=WPovhAylLP%2FgChjF9PjvPuoeChZPYwzvpN8ZCc%2Fphis%3D&st=2021-08-17T10%3A38%3A26Z&se=2021-09-17T10%3A43%3A26Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-18 10:19 UTC, v-abirade requested changes
@Rajeshwari-v,

Please update the sentence.

2021-08-18 10:19 UTC, v-abirade commented on msteams-platform/concepts/build-and-test/deep-links.md
> +The following is the example format of deeplink to files:
The following example format shows the deeplink to files:

2021-08-18 10:46 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We do not currently enforce a minimum score for content merged to the default branch. This will change in the future.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1bf378d77c6ca10dd80129621d0a5e72dbd49dcd/msteams-platform/concepts/build-and-test/deep-links.md) | 83 | 54 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f3fd8db3-5b8c-47c9-83e8-15a150c3329e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2021-08-18 10:46 UTC, opbld33 commented
Docs Build status updates of commit _[1bf378d](https://github.com/MicrosoftDocs/msteams-docs/commits/1bf378d77c6ca10dd80129621d0a5e72dbd49dcd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-enhancement-add-details-3923/msteams-platform/concepts/build-and-test/deep-links.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links?branch=pr-en-us-3971) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C18%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202108181045384149-3971%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=DML8MrL9BbzoJ%2B4yddzxspzBuG18iW8YaEx2pyVk0Rs%3D&st=2021-08-18T10%3A41%3A20Z&se=2021-09-18T10%3A46%3A20Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-19 05:11 UTC, v-abirade approved these changes
Approved

2021-08-31 16:01 UTC, Wajeed-msft approved these changes

2021-09-01 13:37 UTC, merged