Update teams-store-validation-guidelines.md
MicrosoftDocs/msteams-docs pull request #4138
Opened 2021-09-13 05:47 UTC by ramendhe

2021-09-13 05:48 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We do not currently enforce a minimum score for content merged to the default branch. This will change in the future.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/teams-store-validation-guidelines.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1a0409ccf9559491864b260f71d8834b4f363278/msteams-platform/concepts/deploy-and-publish/appsource/prepare/teams-store-validation-guidelines.md) | 87 | 75 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5e1cedca-e2b5-45ed-b88e-333fa028e9df) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2021-09-13 05:48 UTC, opbld33 commented
Docs Build status updates of commit _[1a0409c](https://github.com/MicrosoftDocs/msteams-docs/commits/1a0409ccf9559491864b260f71d8834b4f363278)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/deploy-and-publish/appsource/prepare/teams-store-validation-guidelines.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ramendhe-patch-4/msteams-platform/concepts/deploy-and-publish/appsource/prepare/teams-store-validation-guidelines.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/teams-store-validation-guidelines?branch=pr-en-us-4138) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C13%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202109130547404084-4138%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=xKWtJurvOiqy10uqOU2iMB8y%2FSgiGa8lJH1mUjBNmkQ%3D&st=2021-09-13T05%3A43%3A30Z&se=2021-10-14T05%3A48%3A30Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-13 05:48 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We do not currently enforce a minimum score for content merged to the default branch. This will change in the future.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/teams-store-validation-guidelines.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1a0409ccf9559491864b260f71d8834b4f363278/msteams-platform/concepts/deploy-and-publish/appsource/prepare/teams-store-validation-guidelines.md) | 87 | 75 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1f302e26-eb1c-4091-af67-11c6d93180a7) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2021-09-13 05:49 UTC, opbld31 commented
Docs Build status updates of commit _[1a0409c](https://github.com/MicrosoftDocs/msteams-docs/commits/1a0409ccf9559491864b260f71d8834b4f363278)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/deploy-and-publish/appsource/prepare/teams-store-validation-guidelines.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ramendhe-patch-4/msteams-platform/concepts/deploy-and-publish/appsource/prepare/teams-store-validation-guidelines.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/teams-store-validation-guidelines?branch=pr-en-us-4138) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C13%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202109130548110406-4138%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=4lE41oJx75OpMGBRLTHrNQA982%2BYuhDKH1aXV7kVy6s%3D&st=2021-09-13T05%3A44%3A11Z&se=2021-10-14T05%3A49%3A11Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-13 14:06 UTC, v-abirade requested changes
Please rephrase.

2021-09-13 14:06 UTC, v-abirade commented on msteams-platform/concepts/deploy-and-publish/appsource/prepare/teams-store-validation-guidelines.md
> +* Include a 'Settings' tabs if your app has functionality that requires a changes in the settings.
Please rephrase:
```suggestion
* If your app functionality requires changes in the settings, include a **Settings** tab.
```

2021-09-16 08:09 UTC, opbld33 commented
Docs Build status updates of commit _[fa142d3](https://github.com/MicrosoftDocs/msteams-docs/commits/fa142d303abd2dd45b9cd9abe01a440d27acde9f)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-153aa330)

<a id="153aa330"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C16%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202109160809063834-4138%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-17T08%3A09%3A24Z&sr=b&sp=r&sig=klWlBKojcjeI0WyqxbqTSRJJqn9iQ7vsT5lYOxfNDuQ%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-16 08:10 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We do not currently enforce a minimum score for content merged to the default branch. This will change in the future.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/teams-store-validation-guidelines.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fa142d303abd2dd45b9cd9abe01a440d27acde9f/msteams-platform/concepts/deploy-and-publish/appsource/prepare/teams-store-validation-guidelines.md) | 87 | 74 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f5f912d0-5981-4aa9-a4d5-0afb7455e39c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2021-09-21 16:19 UTC, v-abirade approved these changes
Approved

2021-09-21 16:21 UTC, opbld30 commented
Docs Build status updates of commit _[f5d8179](https://github.com/MicrosoftDocs/msteams-docs/commits/f5d81790fc5a9aa5c4f08af115f6cecf7aada510)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/deploy-and-publish/appsource/prepare/teams-store-validation-guidelines.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ramendhe-patch-4/msteams-platform/concepts/deploy-and-publish/appsource/prepare/teams-store-validation-guidelines.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/teams-store-validation-guidelines?branch=pr-en-us-4138) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C21%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202109211620249997-4138%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-22T16%3A21%3A07Z&sr=b&sp=r&sig=A2zBotTVBDtkgtQwjAPQY5BB8C2j73C7vEUUNgQYbrU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-21 16:21 UTC, merged

2021-09-21 16:21 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We do not currently enforce a minimum score for content merged to the default branch. This will change in the future.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/teams-store-validation-guidelines.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f5d81790fc5a9aa5c4f08af115f6cecf7aada510/msteams-platform/concepts/deploy-and-publish/appsource/prepare/teams-store-validation-guidelines.md) | 87 | 75 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/52e804bb-2694-4bcb-9e4b-d05c7f7f669c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).