[Docenhancement][RSC for bots moved to GA]
MicrosoftDocs/msteams-docs pull request #4478
Opened 2021-10-28 10:30 UTC by v-sreenivasv

Removed note on dev preview. 
Updated What's new.
Updated information as received.

2021-11-11 19:24 UTC, opbld31 commented
Docs Build status updates of commit _[c02faa7](https://github.com/v-sreenivasv/msteams-docs/commits/c02faa70ffaf13f0dce40eabde62d33c2cccccd1)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-df17f991)

<a id="df17f991"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C11%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202111111923408310-4478%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-12T19%3A23%3A59Z&sr=b&sp=r&sig=l4ZojbBf3DmeXN2D4MJV6gZuZ2p1qvlf0gRa4RO%2BWtE%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-11 19:24 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c02faa70ffaf13f0dce40eabde62d33c2cccccd1/msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md) | 93 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/62a8daa8-e79e-4548-82d2-fc9ecd2d6f39) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c02faa70ffaf13f0dce40eabde62d33c2cccccd1/msteams-platform/whats-new.md) | 88 | 33 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b459c6ad-5928-44a8-9089-502fa16a7152) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2021-11-11 19:26 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/223436b5df81121081e31aece93ce6081e6a0242/msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md) | 93 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3e902fd9-1569-4792-b077-08ca61c8ce49) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/223436b5df81121081e31aece93ce6081e6a0242/msteams-platform/whats-new.md) | 87 | 33 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7fcca839-427e-4744-b2af-cc912d51f19e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2021-11-11 19:27 UTC, opbld30 commented
Docs Build status updates of commit _[223436b](https://github.com/v-sreenivasv/msteams-docs/commits/223436b5df81121081e31aece93ce6081e6a0242)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/v-sreenivasv/msteams-docs/blob/docenhancement-bots-phase/msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/channel-messages-with-rsc?branch=pr-en-us-4478) |
[msteams-platform/whats-new.md](https://github.com/v-sreenivasv/msteams-docs/blob/docenhancement-bots-phase/msteams-platform/whats-new.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/whats-new?branch=pr-en-us-4478) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C11%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202111111926231829-4478%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-12T19%3A27%3A27Z&sr=b&sp=r&sig=NI%2BQYGHhhPIJVaEOy4JqF7cwEVO5%2BWlAV%2Bbtc3ZN8M8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-11 21:18 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/60f66aba62c659718b64c1fab1f50cfbf7194aa0/msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md) | 93 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f3f9c797-e06b-4478-8c42-db5f535ac7c0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/60f66aba62c659718b64c1fab1f50cfbf7194aa0/msteams-platform/whats-new.md) | 87 | 33 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7a268c81-2471-418f-a4d8-0b244b1bbd42) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2021-11-11 21:19 UTC, opbld30 commented
Docs Build status updates of commit _[60f66ab](https://github.com/v-sreenivasv/msteams-docs/commits/60f66aba62c659718b64c1fab1f50cfbf7194aa0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/v-sreenivasv/msteams-docs/blob/docenhancement-bots-phase/msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/channel-messages-with-rsc?branch=pr-en-us-4478) |
[msteams-platform/whats-new.md](https://github.com/v-sreenivasv/msteams-docs/blob/docenhancement-bots-phase/msteams-platform/whats-new.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/whats-new?branch=pr-en-us-4478) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C11%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202111112118154494-4478%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-12T21%3A19%3A08Z&sr=b&sp=r&sig=wig8tFgfqU2f4lbLW4VcbcQVMWU3Vx4ZOWjWar7EQkA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-12 18:44 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/567e41801e6f00ba8795413e96806f8db00a119a/msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md) | 93 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7f2a6434-d9c9-4391-b6bf-4303fa4b1b0f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/567e41801e6f00ba8795413e96806f8db00a119a/msteams-platform/whats-new.md) | 87 | 33 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ee9a67ef-0135-474a-acc5-7464965af9cb) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2021-11-12 18:44 UTC, opbld31 commented
Docs Build status updates of commit _[567e418](https://github.com/v-sreenivasv/msteams-docs/commits/567e41801e6f00ba8795413e96806f8db00a119a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/v-sreenivasv/msteams-docs/blob/docenhancement-bots-phase/msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/channel-messages-with-rsc?branch=pr-en-us-4478) |
[msteams-platform/whats-new.md](https://github.com/v-sreenivasv/msteams-docs/blob/docenhancement-bots-phase/msteams-platform/whats-new.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/whats-new?branch=pr-en-us-4478) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C12%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202111121843469364-4478%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-13T18%3A44%3A34Z&sr=b&sp=r&sig=yPIjjHM3%2BwW7zkVpHjyV6Dt08x06EBa9jc1P375ILiQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-12 18:47 UTC, v-abirade submitted a review, later dismissed
Approved

2021-11-12 18:48 UTC, surbhigupta12 submitted a review, later dismissed
Approved

2021-11-12 18:50 UTC, vule-msft requested changes

2021-11-12 18:50 UTC, vule-msft commented on msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md
>  Currently, bots can only receive user channel messages when they are @mentioned. Using RSC, you can now request team owners to consent for a bot to receive user messages across standard channels in a
Let's delete this first sentence as it no longer holds now that this feature is being released

`Currently, bots can only receive user channel messages when they are @mentioned.`

2021-11-12 18:51 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e757690776ef988d3f9748f6827f0adeb705c053/msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f9bf5150-110a-42ed-9d1b-df758693836d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e757690776ef988d3f9748f6827f0adeb705c053/msteams-platform/whats-new.md) | 87 | 33 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5fb71cbf-a5e5-4357-8a94-92f09cc26e05) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2021-11-12 18:52 UTC, opbld33 commented
Docs Build status updates of commit _[e757690](https://github.com/v-sreenivasv/msteams-docs/commits/e757690776ef988d3f9748f6827f0adeb705c053)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/v-sreenivasv/msteams-docs/blob/docenhancement-bots-phase/msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/channel-messages-with-rsc?branch=pr-en-us-4478) |
[msteams-platform/whats-new.md](https://github.com/v-sreenivasv/msteams-docs/blob/docenhancement-bots-phase/msteams-platform/whats-new.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/whats-new?branch=pr-en-us-4478) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C12%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202111121851206663-4478%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-13T18%3A52%3A24Z&sr=b&sp=r&sig=nbZV%2Fcpv8zRRDlyRB1JVWQFsWS1Pd%2BZGEEl1RpNrPKQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-12 18:52 UTC, vule-msft approved these changes

2021-11-12 18:53 UTC, merged