[Doc Improvement][Update link-unfurling]
MicrosoftDocs/msteams-docs pull request #4531
Opened 2021-11-09 05:34 UTC by v-ypalikila

Added changes.

2021-11-09 05:34 UTC, opbld30 commented
Docs Build status updates of commit _[492e1bd](https://github.com/v-ypalikila/msteams-docs/commits/492e1bdf431ff12409b0230dfb9dafdd718f6cc3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/v-ypalikila/msteams-docs/blob/doc-enhancement-github-issue-link-unfurling/msteams-platform/messaging-extensions/how-to/link-unfurling.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-4531) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C9%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202111090534057695-4531%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-10T05%3A34%3A55Z&sr=b&sp=r&sig=7ltXVlO5Rr4xX%2BKNbJtDYcGdq374rJw3j9Xn%2FimGsLU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-09 05:35 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/492e1bdf431ff12409b0230dfb9dafdd718f6cc3/msteams-platform/messaging-extensions/how-to/link-unfurling.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ce59211a-2585-4372-ae5a-e7f8fe1b0eaf) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2021-11-10 06:04 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a90bbd564e08c028c6ccc3f3d63bca08393551ae/msteams-platform/messaging-extensions/how-to/link-unfurling.md) | 92 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6249649d-9ec5-4a1f-91c9-a0be6096ea64) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a90bbd564e08c028c6ccc3f3d63bca08393551ae/msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e00b8956-e091-480e-90b1-7575bccb8f28) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2021-11-10 06:05 UTC, opbld30 commented
Docs Build status updates of commit _[a90bbd5](https://github.com/v-ypalikila/msteams-docs/commits/a90bbd564e08c028c6ccc3f3d63bca08393551ae)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/v-ypalikila/msteams-docs/blob/doc-enhancement-github-issue-link-unfurling/msteams-platform/messaging-extensions/how-to/link-unfurling.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-4531) | [Details](#user-content-5d6d73cdb6df317e67b4e47d8fcb779e-d150e289)
[msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md](https://github.com/v-ypalikila/msteams-docs/blob/doc-enhancement-github-issue-link-unfurling/msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/search-commands/respond-to-search?branch=pr-en-us-4531) |

<a id="5d6d73cdb6df317e67b4e47d8fcb779e-d150e289"></a>
### [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/v-ypalikila/msteams-docs/blob/doc-enhancement-github-issue-link-unfurling/msteams-platform/messaging-extensions/how-to/link-unfurling.md)
 - **Line 25, Column 1**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../assets/images/messaging-extension/link-unfurl.gif'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C10%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202111100604178212-4531%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-11T06%3A05%3A05Z&sr=b&sp=r&sig=A6Qysyk82nGTwlV6aByKWTFVzX%2B9dV2PHUi7zKVY9Ew%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-10 06:22 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/95491d8b042b25a7064b54990efc195a644ca701/msteams-platform/messaging-extensions/how-to/link-unfurling.md) | 92 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7888b607-ee11-409d-a4ba-8ad68e269a6e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md](https://github.com/MicrosoftDocs/msteams-docs/blob/95491d8b042b25a7064b54990efc195a644ca701/msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5709defc-df96-4202-a2fc-0c0c45e41f57) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2021-11-10 06:22 UTC, opbld32 commented
Docs Build status updates of commit _[95491d8](https://github.com/v-ypalikila/msteams-docs/commits/95491d8b042b25a7064b54990efc195a644ca701)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/v-ypalikila/msteams-docs/blob/doc-enhancement-github-issue-link-unfurling/msteams-platform/messaging-extensions/how-to/link-unfurling.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-4531) |
[msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md](https://github.com/v-ypalikila/msteams-docs/blob/doc-enhancement-github-issue-link-unfurling/msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/search-commands/respond-to-search?branch=pr-en-us-4531) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C10%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202111100622121620-4531%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-11T06%3A22%3A58Z&sr=b&sp=r&sig=QAM3wHz9kAzHfGDs8Pufs2Fqesj44niD0apXDNtJVzo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-10 16:20 UTC, opbld32 commented
Docs Build status updates of commit _[5fcd2b0](https://github.com/v-ypalikila/msteams-docs/commits/5fcd2b0127548917725627a40ff1125df836ce1c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/v-ypalikila/msteams-docs/blob/doc-enhancement-github-issue-link-unfurling/msteams-platform/messaging-extensions/how-to/link-unfurling.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-4531) |
[msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md](https://github.com/v-ypalikila/msteams-docs/blob/doc-enhancement-github-issue-link-unfurling/msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/search-commands/respond-to-search?branch=pr-en-us-4531) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C10%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202111101620215937-4531%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-11T16%3A20%3A51Z&sr=b&sp=r&sig=7CJ6Bjij1ls%2FKkVrrsYwZd%2BCY8qSA3BtoyNsaf1vqPo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-10 16:21 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5fcd2b0127548917725627a40ff1125df836ce1c/msteams-platform/messaging-extensions/how-to/link-unfurling.md) | 92 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/80356ffd-63c3-4fb4-9ac5-434cd0c52e31) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5fcd2b0127548917725627a40ff1125df836ce1c/msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md) | 94 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4d2539fa-04f2-469e-af71-b8d0edd140a6) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2021-11-11 10:01 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/678eed7ef8dcd5cf211b2d7bd51d01beb85b3fda/msteams-platform/messaging-extensions/how-to/link-unfurling.md) | 92 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5e007845-ed11-4791-8c16-2b796f409c03) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md](https://github.com/MicrosoftDocs/msteams-docs/blob/678eed7ef8dcd5cf211b2d7bd51d01beb85b3fda/msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md) | 93 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/56027939-0854-41c4-90de-8d2c09bc2456) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2021-11-11 10:02 UTC, opbld32 commented
Docs Build status updates of commit _[678eed7](https://github.com/v-ypalikila/msteams-docs/commits/678eed7ef8dcd5cf211b2d7bd51d01beb85b3fda)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/v-ypalikila/msteams-docs/blob/doc-enhancement-github-issue-link-unfurling/msteams-platform/messaging-extensions/how-to/link-unfurling.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-4531) | [Details](#user-content-5d6d73cdb6df317e67b4e47d8fcb779e-fe157fe1)
[msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md](https://github.com/v-ypalikila/msteams-docs/blob/doc-enhancement-github-issue-link-unfurling/msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/search-commands/respond-to-search?branch=pr-en-us-4531) | [Details](#user-content-d88ceab071c788c3d5fd0cd66fb710f8-fe157fe1)

<a id="5d6d73cdb6df317e67b4e47d8fcb779e-fe157fe1"></a>
### [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/v-ypalikila/msteams-docs/blob/doc-enhancement-github-issue-link-unfurling/msteams-platform/messaging-extensions/how-to/link-unfurling.md)
 - **Line 25, Column 1**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../assets/images/messaging-extension/link-unfurl.gif'.`````

<a id="d88ceab071c788c3d5fd0cd66fb710f8-fe157fe1"></a>
### [msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md](https://github.com/v-ypalikila/msteams-docs/blob/doc-enhancement-github-issue-link-unfurling/msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md)
 - **Line 114, Column 1**: **[Warning: invalid-note-section]** `````Text in the first line of Note/Section/Video is not valid. Will be rendered to <blockquote>`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C11%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202111111001211976-4531%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-12T10%3A02%3A24Z&sr=b&sp=r&sig=sKoXkc5Yd1mZEYnE86McSTJHo4FzVqUGceE0xrHGBD0%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-11 10:09 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1f10e7c4e5927c7c63f5f84b5bb236844801eda5/msteams-platform/messaging-extensions/how-to/link-unfurling.md) | 92 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/191be653-a447-439f-b0ed-589ea8c33afc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1f10e7c4e5927c7c63f5f84b5bb236844801eda5/msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md) | 93 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b50b937a-51aa-49b8-82aa-83d14b6cefd2) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2021-11-11 10:09 UTC, opbld32 commented
Docs Build status updates of commit _[1f10e7c](https://github.com/v-ypalikila/msteams-docs/commits/1f10e7c4e5927c7c63f5f84b5bb236844801eda5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/v-ypalikila/msteams-docs/blob/doc-enhancement-github-issue-link-unfurling/msteams-platform/messaging-extensions/how-to/link-unfurling.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-4531) |
[msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md](https://github.com/v-ypalikila/msteams-docs/blob/doc-enhancement-github-issue-link-unfurling/msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/search-commands/respond-to-search?branch=pr-en-us-4531) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C11%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202111111009040164-4531%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-12T10%3A09%3A54Z&sr=b&sp=r&sig=3LtVr4pRdSVRm9Fai32ufsPpuLkBPr%2BqPPVarnOGoKw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-11 10:18 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8aaa59df8155e71b14f50e2bf583a3ed30196630/msteams-platform/messaging-extensions/how-to/link-unfurling.md) | 92 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2b217458-1176-4ef9-a9c8-cbb3bea15da4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8aaa59df8155e71b14f50e2bf583a3ed30196630/msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md) | 93 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/460e0f56-e852-4c84-adb5-8ba657ef3400) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2021-11-11 10:18 UTC, opbld33 commented
Docs Build status updates of commit _[8aaa59d](https://github.com/v-ypalikila/msteams-docs/commits/8aaa59df8155e71b14f50e2bf583a3ed30196630)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/v-ypalikila/msteams-docs/blob/doc-enhancement-github-issue-link-unfurling/msteams-platform/messaging-extensions/how-to/link-unfurling.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-4531) |
[msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md](https://github.com/v-ypalikila/msteams-docs/blob/doc-enhancement-github-issue-link-unfurling/msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/search-commands/respond-to-search?branch=pr-en-us-4531) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C11%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202111111018006802-4531%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-12T10%3A18%3A47Z&sr=b&sp=r&sig=x93GUNSQU3aTwgC3LdmCF%2B0JzifbIrZx%2BGCgt99z9CU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-11 11:04 UTC, v-habibaumme approved these changes
Approved

2021-11-11 20:39 UTC, surbhigupta12 requested changes
Please incorporate the comments.

2021-11-11 20:39 UTC, surbhigupta12 commented on msteams-platform/messaging-extensions/how-to/link-unfurling.md
> + The following image displays link unfurling feature when a link is pasted in messaging extension:
Why has this text been updated? The original information is right. Please revert. It doesn't seem to be part of the issue.

2021-11-11 20:39 UTC, surbhigupta12 commented on msteams-platform/messaging-extensions/how-to/link-unfurling.md
> -* [Adaptive Card](~/task-modules-and-cards/cards/cards-reference.md#adaptive-card)
Please revert. Why has this section been deleted. Only line 76 had to be removed.

2021-11-11 20:39 UTC, surbhigupta12 commented on msteams-platform/messaging-extensions/how-to/link-unfurling.md
> + Use the received URL to search your service and create a card response. If you respond with more than one card, only the first card response is used.
Revert to original

2021-11-11 20:39 UTC, surbhigupta12 commented on msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md
> +After the user submits the search command, your web service receives a `composeExtension/query` invoke message that contains a `value` object with the search parameters, which is triggered with the f
Modified sentence is too long. Please revert to original.

2021-11-11 20:39 UTC, surbhigupta12 commented on msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md
> +When the user performs a query, Microsoft Teams issues a synchronous HTTP request to your service. At that point, your code has `5` seconds to provide an HTTP response to the request. During this tim
Do is not the right usage. Please revert to original.

2021-11-11 20:39 UTC, surbhigupta12 commented on msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md
> +> If the link unfurling doesn't work, check the code for preview property mentioned in the earlier section.
Please rephrase and make use of style guide.

2021-11-11 20:39 UTC, surbhigupta12 commented on msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md
> +If you set `initialRun` to `true` in the manifest, Microsoft Teams issues a **default** query when the user first opens the messaging extension. Your service can respond to the query with a set of pr
Please do not introduce errors. Revert "the" to "this".

2021-11-22 05:22 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8715e054a5bd3c908110ab1932b7ef501d5a0fec/msteams-platform/messaging-extensions/how-to/link-unfurling.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5d7f377d-8b60-43fe-9997-7f3a250eb0be) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8715e054a5bd3c908110ab1932b7ef501d5a0fec/msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1319e79b-af7b-4121-af41-16e3e14baac7) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2021-11-22 05:22 UTC, opbld32 commented
Docs Build status updates of commit _[8715e05](https://github.com/v-ypalikila/msteams-docs/commits/8715e054a5bd3c908110ab1932b7ef501d5a0fec)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/v-ypalikila/msteams-docs/blob/doc-enhancement-github-issue-link-unfurling/msteams-platform/messaging-extensions/how-to/link-unfurling.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-4531) |
[msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md](https://github.com/v-ypalikila/msteams-docs/blob/doc-enhancement-github-issue-link-unfurling/msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/search-commands/respond-to-search?branch=pr-en-us-4531) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C22%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202111220521537549-4531%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-23T05%3A22%3A30Z&sr=b&sp=r&sig=LY9mVl8XB2ygVC9BCgXJAhL3EkHlZ5hrRGYSwo%2BDQ1c%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-22 10:09 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c6295d8630c9f426c50d67850d697d06287caf38/msteams-platform/messaging-extensions/how-to/link-unfurling.md) | 91 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6ffc23bc-98c2-433a-89cf-4203dff0a479) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c6295d8630c9f426c50d67850d697d06287caf38/msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1f5831cb-8341-41ca-b802-e134cc0a7e52) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2021-11-22 10:09 UTC, opbld30 commented
Docs Build status updates of commit _[c6295d8](https://github.com/v-ypalikila/msteams-docs/commits/c6295d8630c9f426c50d67850d697d06287caf38)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md](https://github.com/v-ypalikila/msteams-docs/blob/doc-enhancement-github-issue-link-unfurling/msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/search-commands/respond-to-search?branch=pr-en-us-4531) | [Details](#user-content-d88ceab071c788c3d5fd0cd66fb710f8-ee4719cb)
[msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/v-ypalikila/msteams-docs/blob/doc-enhancement-github-issue-link-unfurling/msteams-platform/messaging-extensions/how-to/link-unfurling.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-4531) |

<a id="d88ceab071c788c3d5fd0cd66fb710f8-ee4719cb"></a>
### [msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md](https://github.com/v-ypalikila/msteams-docs/blob/doc-enhancement-github-issue-link-unfurling/msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md)
 - **Line 114, Column 1**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../assets/images/messaging-extension/link-unfurl.gif'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C22%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202111221008556088-4531%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-23T10%3A09%3A34Z&sr=b&sp=r&sig=Od79%2FqiUCfBthTKrJqy83AInFy8w1n9BooIU1Qw8IAE%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-22 10:17 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/af0760cba56c17922f222de47d94bbff054a57fa/msteams-platform/messaging-extensions/how-to/link-unfurling.md) | 91 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7debd0aa-09d6-4567-be6c-f8bfe0548348) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md](https://github.com/MicrosoftDocs/msteams-docs/blob/af0760cba56c17922f222de47d94bbff054a57fa/msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/17b81476-669c-42fd-90cf-e051170fb03d) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2021-11-22 10:17 UTC, opbld31 commented
Docs Build status updates of commit _[af0760c](https://github.com/v-ypalikila/msteams-docs/commits/af0760cba56c17922f222de47d94bbff054a57fa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/v-ypalikila/msteams-docs/blob/doc-enhancement-github-issue-link-unfurling/msteams-platform/messaging-extensions/how-to/link-unfurling.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-4531) |
[msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md](https://github.com/v-ypalikila/msteams-docs/blob/doc-enhancement-github-issue-link-unfurling/msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/search-commands/respond-to-search?branch=pr-en-us-4531) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C22%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202111221016343119-4531%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-23T10%3A17%3A30Z&sr=b&sp=r&sig=pRvDDnkzdgNXxapxBgagHov9v%2FEnFD31%2FEd7ufEy%2FMU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-22 10:53 UTC, v-habibaumme commented on msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md
> +For more information about the Office 365 Connector card, see [Using Office 365 Connector cards](~/task-modules-and-cards/cards/cards-reference.md#office-365-connector-card).
Please revert to additional

2021-11-22 10:53 UTC, v-habibaumme commented on msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md
> -The result list is displayed in the Microsoft Teams UI with a preview of each item. The preview is generated in one of the two ways:
Is there a result list. Please confirm and then make the change

2021-11-22 11:39 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b2bba431fe89ffa96715b65b8be97e8ee23c1b14/msteams-platform/messaging-extensions/how-to/link-unfurling.md) | 91 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fd5d024d-605c-4565-ba6e-5f096d44d612) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b2bba431fe89ffa96715b65b8be97e8ee23c1b14/msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md) | 89 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d5d6a807-b5e5-4004-9be5-1d4810a60996) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2021-11-24 08:20 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4589d6acdb225c0badf3ab98ebd649885e127320/msteams-platform/messaging-extensions/how-to/link-unfurling.md) | 93 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5b034f1f-6066-47a0-b34e-8e45ead9685c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4589d6acdb225c0badf3ab98ebd649885e127320/msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md) | 88 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/68b28fd8-ce89-4404-aa50-7a8adc69e1d2) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2021-11-24 08:21 UTC, opbld30 commented
Docs Build status updates of commit _[4589d6a](https://github.com/v-ypalikila/msteams-docs/commits/4589d6acdb225c0badf3ab98ebd649885e127320)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/v-ypalikila/msteams-docs/blob/doc-enhancement-github-issue-link-unfurling/msteams-platform/messaging-extensions/how-to/link-unfurling.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-4531) |
[msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md](https://github.com/v-ypalikila/msteams-docs/blob/doc-enhancement-github-issue-link-unfurling/msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/search-commands/respond-to-search?branch=pr-en-us-4531) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C24%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202111240820147796-4531%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-25T08%3A21%3A06Z&sr=b&sp=r&sig=PE%2FUfYkmyVsocAoelznytcWthEfJcx673VDR4lDDXQ8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-25 10:36 UTC, Wajeed-msft approved these changes

2021-11-25 10:37 UTC, surbhigupta12 approved these changes
Approved

2021-11-25 10:37 UTC, merged

2021-12-01 10:46 UTC, juna-gupta reviewed
https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/search-commands/respond-to-search?tabs=dotnet#response-card-types-and-previews

Card types and Preview card information seems to be moved to a different page now (seems incorrect). Search action command page includes Url unfurling example.