[Doc Improvement][M365]
MicrosoftDocs/msteams-docs pull request #4617
Opened 2021-11-17 09:46 UTC by v-dreddipogu

2021-11-17 09:47 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/m365-apps/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f2ba551e0d1e1cbc0bd21c5724edc86b65d595d0/msteams-platform/m365-apps/overview.md) | 94 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4684a597-3a19-441e-b6c7-877547fe38a6) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2021-11-17 09:48 UTC, opbld31 commented
Docs Build status updates of commit _[f2ba551](https://github.com/v-dreddipogu/msteams-docs/commits/f2ba551e0d1e1cbc0bd21c5724edc86b65d595d0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/m365-apps/overview.md](https://github.com/v-dreddipogu/msteams-docs/blob/doc-improvement-m365/msteams-platform/m365-apps/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/m365-apps/overview?branch=pr-en-us-4617) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C17%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202111170946586915-4617%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-18T09%3A48%3A25Z&sr=b&sp=r&sig=ebbyBTAvwoonudhnrS%2FZWyNTg7laH0hTcCmXhJdOIWc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-17 09:50 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/m365-apps/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3d36e06d8b5e9d7ffaddd8128316a6330fd6cd1e/msteams-platform/m365-apps/overview.md) | 94 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/59db7b4a-a156-4883-a5c0-14277e26a932) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2021-11-17 09:51 UTC, opbld30 commented
Docs Build status updates of commit _[3d36e06](https://github.com/v-dreddipogu/msteams-docs/commits/3d36e06d8b5e9d7ffaddd8128316a6330fd6cd1e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/m365-apps/overview.md](https://github.com/v-dreddipogu/msteams-docs/blob/doc-improvement-m365/msteams-platform/m365-apps/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/m365-apps/overview?branch=pr-en-us-4617) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C17%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202111170950350137-4617%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-18T09%3A51%3A27Z&sr=b&sp=r&sig=%2FQB9LTxYHazy5LuPSu0du2jAvXkF6GIQ21t6f9G9dP4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-18 06:17 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/m365-apps/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ea9d79c4a29a1abf9a9b57bf95baa177a3d6d160/msteams-platform/m365-apps/overview.md) | 94 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4c06ce07-2062-479d-a03f-5ff3725bb463) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2021-11-18 06:18 UTC, opbld31 commented
Docs Build status updates of commit _[ea9d79c](https://github.com/v-dreddipogu/msteams-docs/commits/ea9d79c4a29a1abf9a9b57bf95baa177a3d6d160)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/m365-apps/images/messaging-extensions-outlook-teams.png](https://github.com/v-dreddipogu/msteams-docs/blob/doc-improvement-m365/msteams-platform/m365-apps/images/messaging-extensions-outlook-teams.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/m365-apps/overview?branch=pr-en-us-4617) |
[msteams-platform/m365-apps/overview.md](https://github.com/v-dreddipogu/msteams-docs/blob/doc-improvement-m365/msteams-platform/m365-apps/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/m365-apps/overview?branch=pr-en-us-4617) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C18%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202111180617107440-4617%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-19T06%3A18%3A05Z&sr=b&sp=r&sig=92rajoqiMxu4wBgba5JzGq%2FK9cjXC01twfv3VDyz1d0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-18 06:22 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/m365-apps/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3b8cf08d4e566947fd336010a7f7aaf798c5b40e/msteams-platform/m365-apps/overview.md) | 93 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/983ccaa0-0766-433b-a0ba-53e787b9dd35) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2021-11-18 06:23 UTC, opbld30 commented
Docs Build status updates of commit _[3b8cf08](https://github.com/v-dreddipogu/msteams-docs/commits/3b8cf08d4e566947fd336010a7f7aaf798c5b40e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/m365-apps/images/messaging-extensions-outlook-teams.png](https://github.com/v-dreddipogu/msteams-docs/blob/doc-improvement-m365/msteams-platform/m365-apps/images/messaging-extensions-outlook-teams.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/m365-apps/overview?branch=pr-en-us-4617) |
[msteams-platform/m365-apps/overview.md](https://github.com/v-dreddipogu/msteams-docs/blob/doc-improvement-m365/msteams-platform/m365-apps/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/m365-apps/overview?branch=pr-en-us-4617) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C18%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202111180622093761-4617%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-19T06%3A23%3A04Z&sr=b&sp=r&sig=3DjJ7KoYFiyHRyc3TZv5QKN%2FwWy%2BejSP27vtv6Gk3oo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-23 20:24 UTC, surbhigupta12 requested changes
Please rework. The meaning is changed and context is lost in most of the places.

2021-11-23 20:24 UTC, surbhigupta12 commented on msteams-platform/m365-apps/overview.md
> +> Teams developers can try the new functionalities and [provide feedback](/microsoftteams/platform/feedback) using existing applications in early Developer preview for expansion of the Teams develope
Incorrect. Changed the meaning. Please rephrase.

2021-11-23 20:24 UTC, surbhigupta12 commented on msteams-platform/m365-apps/overview.md
> +:::image type="content" source="images/messaging-extensions-outlook-teams.png" alt-text="Messaging extensions in outlook and Teams":::
Please revert/rephrase. The main context is lost.

2021-11-24 09:17 UTC, v-dreddipogu commented
Invalid PR. Hence closing it

2021-11-24 09:17 UTC, closed without merging