[Doc-enhancement][Update-channeldata-in-personal-conversation][]
MicrosoftDocs/msteams-docs pull request #4785
Opened 2021-12-03 08:03 UTC by v-npaladugu

2021-12-03 08:04 UTC, opbld32 commented
Docs Build status updates of commit _[5215957](https://github.com/MicrosoftDocs/msteams-docs/commits/521595763aca139ca51514bec32eb659ac696c12)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/resources/bot-v3/bot-conversations/bots-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-channelData/msteams-platform/resources/bot-v3/bot-conversations/bots-conversations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bot-conversations/bots-conversations?branch=pr-en-us-4785) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C3%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202112030803253107-4785%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-03T08%3A04%3A02Z&sr=b&sp=r&sig=vwg7ZqYXZR2iIs7J3nRhqK1EE03Ob%2B0tA3962MCAEW4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-03 08:16 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/bot-v3/bot-conversations/bots-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/521595763aca139ca51514bec32eb659ac696c12/msteams-platform/resources/bot-v3/bot-conversations/bots-conversations.md) | 83 | 46 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/41488d98-c2fc-488b-a924-0a247a62094c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2021-12-03 12:32 UTC, v-chetsh requested changes
Reviewed and provided my comment.

2021-12-03 12:32 UTC, v-chetsh commented on msteams-platform/resources/bot-v3/bot-conversations/bots-conversations.md
> +The `channelData` object include only `tenant.id` in messages for personal conversations since these take place outside of any channel.
Looks like this change is not correct.
Please wait, we will confirm once and let you know.

2021-12-14 11:20 UTC, ashishguptaiitb commented
Hi @v-habibaumme , please help me understand what is the next action required to complete this update?

2021-12-16 04:52 UTC, v-chetsh commented
@v-npaladugu - Could you please remove the below line from documentation:
Doc section for ref : https://docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bot-conversations/bots-conversations#teams-channel-data

UI
![image](https://user-images.githubusercontent.com/59052547/146310375-34980b4e-7523-4e34-9d4a-ebde34ce2d82.png)

2021-12-16 04:54 UTC, v-chetsh commented on msteams-platform/resources/bot-v3/bot-conversations/bots-conversations.md
> -The `channelData` object is not included in messages in personal conversations since these take place outside of any channel.
@v-npaladugu - Could you please remove the below line from documentation:
Doc section for ref : https://docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bot-conversations/bots-conversations#teams-channel-data

UI
![image](https://user-images.githubusercontent.com/59052547/146310375-34980b4e-7523-4e34-9d4a-ebde34ce2d82.png)

2021-12-16 06:19 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/bot-v3/bot-conversations/bots-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a9a4d731b319293ceb6b214df55d0f5c7a334917/msteams-platform/resources/bot-v3/bot-conversations/bots-conversations.md) | 83 | 45 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/389830ca-bba6-41b2-8d6f-d55997fe3104) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2021-12-16 06:20 UTC, opbld32 commented
Docs Build status updates of commit _[a9a4d73](https://github.com/MicrosoftDocs/msteams-docs/commits/a9a4d731b319293ceb6b214df55d0f5c7a334917)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/resources/bot-v3/bot-conversations/bots-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-channelData/msteams-platform/resources/bot-v3/bot-conversations/bots-conversations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bot-conversations/bots-conversations?branch=pr-en-us-4785) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C16%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202112160619197232-4785%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-16T06%3A20%3A33Z&sr=b&sp=r&sig=33LbIxwoEjWbO5WzSYrRDiUEakmHmd%2Ff%2Felceys7fwM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-16 06:58 UTC, Wajeed-msft approved these changes

2021-12-16 07:08 UTC, v-habibaumme approved these changes
Approved

2021-12-16 07:17 UTC, ashishguptaiitb approved these changes

2021-12-20 05:42 UTC, v-chetsh approved these changes
Changes looks fine, approving it.

2021-12-20 06:00 UTC, merged