[doc-feature][glossary]
MicrosoftDocs/msteams-docs pull request #5024
Opened 2022-01-17 10:40 UTC by v-shalinirobinson

Glossary for MS Teams Developer Documentation

2022-01-17 10:41 UTC, opbld33 commented
Docs Build status updates of commit _[ef2771a](https://github.com/MicrosoftDocs/msteams-docs/commits/ef2771a57f9ba7640fe113d504beb6e52093b971)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/get-started/glossary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C17%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202201171040586214-5024%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-17T10%3A41%3A46Z&sr=b&sp=r&sig=lgIcNtaogc1%2Fw0OrI%2FyKzfYTqnntYq58TWW%2FeWg%2FVaM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-17 10:45 UTC, opbld33 commented
Docs Build status updates of commit _[cadbe7d](https://github.com/MicrosoftDocs/msteams-docs/commits/cadbe7dc107463fe6810852acb4501204b72dc2f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |
[msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/get-started/glossary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C17%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202201171044480680-5024%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-17T10%3A45%3A35Z&sr=b&sp=r&sig=telxF6HJob2rebljy6SIXMvrZvfUxkpzUKr2d9kI3ZI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-17 11:28 UTC, opbld32 commented
Docs Build status updates of commit _[3bbbfa0](https://github.com/MicrosoftDocs/msteams-docs/commits/3bbbfa063065ed55fb2722d460966b4696907a7f)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-d420711a)

<a id="d420711a"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C17%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202201171128226896-5024%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-17T11%3A28%3A36Z&sr=b&sp=r&sig=VVEX6SL3UWVrzvvIxf4qiOpLf9QXRvyiGGiCI3HLd%2Bk%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-17 11:37 UTC, opbld33 commented
Docs Build status updates of commit _[8dbf9bd](https://github.com/MicrosoftDocs/msteams-docs/commits/8dbf9bd8a5b83b3dc11d51697d265b06001f3dfb)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/TOC.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/api-references?branch=pr-en-us-5024) | [Details](#user-content-f679b5d0ee59eb212f56a224ff613c91-de670ae8)

<a id="f679b5d0ee59eb212f56a224ff613c91-de670ae8"></a>
### [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/TOC.yml)
 - **Line 24, Column 11**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'get-started/glossary.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C17%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202201171136126647-5024%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-17T11%3A36%3A59Z&sr=b&sp=r&sig=JlQb0J0fR5etLIXC3CVr41tuiAiwOMHbyURNSo6m8Fk%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-17 11:38 UTC, opbld33 commented
Docs Build status updates of commit _[30001be](https://github.com/MicrosoftDocs/msteams-docs/commits/30001bee997134ad507893800a6bce89adfc348a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |
[msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/get-started/glossary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C17%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202201171138023604-5024%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-17T11%3A38%3A44Z&sr=b&sp=r&sig=7Nmur%2BKuJ1NKUVe2BX4S1bskhGwF%2FG059hm6Dg9JgoY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-17 11:53 UTC, opbld30 commented
Docs Build status updates of commit _[f7ecf69](https://github.com/MicrosoftDocs/msteams-docs/commits/f7ecf690770dfbd2b330b093c5a739bca057f28a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/get-started/glossary.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) | [Details](#user-content-ebc1a69710ba4f0d66997f8d89c0b432-36bec225)
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |

<a id="ebc1a69710ba4f0d66997f8d89c0b432-36bec225"></a>
### [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/get-started/glossary.md)
 - **Line 73, Column 225**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/javascript/api/overview/msteams-client?view=msteams-client-js-latest&preserve-view=true' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 73, Column 225**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/javascript/api/overview/msteams-client?view=msteams-client-js-latest&preserve-view=true' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C17%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202201171152506854-5024%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-17T11%3A53%3A34Z&sr=b&sp=r&sig=STUfHwvHhjym2zOUxMxA6dsVyiw%2Bk6%2BuwGFBRIfdVjo%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-17 11:58 UTC, opbld31 commented
Docs Build status updates of commit _[4bd54fa](https://github.com/MicrosoftDocs/msteams-docs/commits/4bd54fa0ec54ca1a79cce1dfdd88a974fb99bcdb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |
[msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/get-started/glossary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C17%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202201171157551802-5024%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-17T11%3A58%3A40Z&sr=b&sp=r&sig=RX3KTnk9nQm3Zr3xO5cMuD44vTnjtWVDbc6kZxQPcnU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-18 03:46 UTC, opbld33 commented
Docs Build status updates of commit _[40bd400](https://github.com/MicrosoftDocs/msteams-docs/commits/40bd400a3e9acfe02339f23e4228881e0f4a5b5a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |
[msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/get-started/glossary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C18%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202201180345077546-5024%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-18T03%3A46%3A39Z&sr=b&sp=r&sig=3jLrHAl5upESPeh%2B6ZY7U3MU3Sz5vDxwbVZeGB5UTMA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-18 04:57 UTC, opbld33 commented
Docs Build status updates of commit _[a373e6d](https://github.com/MicrosoftDocs/msteams-docs/commits/a373e6dd37a0ae3b25aae84f5c49584f711efeec)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |
[msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/get-started/glossary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C18%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202201180455562851-5024%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-18T04%3A57%3A46Z&sr=b&sp=r&sig=wP6732AfiC0zhhW3xaWg98HmpB8pUZRrpfkZxyMFaLU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-18 06:21 UTC, opbld33 commented
Docs Build status updates of commit _[e06f004](https://github.com/MicrosoftDocs/msteams-docs/commits/e06f00487a1709751d0e7aa76b48aae6591f87ee)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |
[msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/get-started/glossary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C18%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202201180620071527-5024%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-18T06%3A21%3A07Z&sr=b&sp=r&sig=dzqLTYTRM3bqzE7NDqLw2nqtNd1r%2BDoeRtt7rQBIgjg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-18 10:47 UTC, opbld33 commented
Docs Build status updates of commit _[e400bf0](https://github.com/MicrosoftDocs/msteams-docs/commits/e400bf0c73f72cffa01685417f9cc285c6670a11)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |
[msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/get-started/glossary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C18%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202201181046334329-5024%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-18T10%3A47%3A14Z&sr=b&sp=r&sig=LN3dMhoz3nAa8Q0kvaVeMqINuOQTVngchbhCP38xGik%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-18 12:29 UTC, opbld33 commented
Docs Build status updates of commit _[fc8e12b](https://github.com/MicrosoftDocs/msteams-docs/commits/fc8e12b0e8bdb046fd76a4b8ef9bdf9ada78cd31)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |
[msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/get-started/glossary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C18%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202201181228320526-5024%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-18T12%3A29%3A15Z&sr=b&sp=r&sig=tepwNjJ4f%2F9ArkNKGNpKiep35bLMgD7foHgcGRupwmQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-18 12:35 UTC, opbld31 commented
Docs Build status updates of commit _[148a78a](https://github.com/MicrosoftDocs/msteams-docs/commits/148a78a120b8314c832f17759119015419688844)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |
[msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/get-started/glossary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C18%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202201181234418041-5024%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-18T12%3A35%3A24Z&sr=b&sp=r&sig=v71WSox2Aus0tYNohjAXo570dB864Qu%2FWSGDTdVtha4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-19 04:44 UTC, opbld30 commented
Docs Build status updates of commit _[71b4129](https://github.com/MicrosoftDocs/msteams-docs/commits/71b4129d5a826e62ba76edc893db158d089c0dc2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |
[msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/get-started/glossary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C19%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202201190443377265-5024%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-19T04%3A44%3A21Z&sr=b&sp=r&sig=JNVwh%2BEZc9L%2FZyOdpXDQdqGbwtlx6cL7hwKNLbEQhZ4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-19 07:09 UTC, opbld31 commented
Docs Build status updates of commit _[8a5996e](https://github.com/MicrosoftDocs/msteams-docs/commits/8a5996e9cf5f2a6603c9ce6af17a8e672179aa57)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |
[msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/get-started/glossary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C19%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202201190707571167-5024%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-19T07%3A09%3A07Z&sr=b&sp=r&sig=dpE1ERWrcwycqwKiUolmLrYsx5vjjpnHQUFy9wIZTmI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-19 08:29 UTC, opbld32 commented
Docs Build status updates of commit _[dc393eb](https://github.com/MicrosoftDocs/msteams-docs/commits/dc393ebf1efcd8bfd0f2163819284f916f0b136d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |
[msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/get-started/glossary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C19%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202201190828457337-5024%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-19T08%3A29%3A41Z&sr=b&sp=r&sig=Gegh9V091pTAcRCZhQaw%2BVUJc6xVrapTbVENG0iBqkc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-19 12:39 UTC, opbld33 commented
Docs Build status updates of commit _[cc7755c](https://github.com/MicrosoftDocs/msteams-docs/commits/cc7755cb6c3d7231aad2344841442bcfda53b8c5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |
[msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/get-started/glossary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C19%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202201191238245822-5024%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-19T12%3A39%3A24Z&sr=b&sp=r&sig=pJjFOvhaWQtAjwWCshSIcqZEdkFRs5rY5%2B79hyJU4Xo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-19 12:45 UTC, opbld32 commented
Docs Build status updates of commit _[3cbb05d](https://github.com/MicrosoftDocs/msteams-docs/commits/3cbb05df824a085cb99653d3c77cd111195fe82a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |
[msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/get-started/glossary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C19%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202201191244441018-5024%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-19T12%3A45%3A41Z&sr=b&sp=r&sig=z8QJuJoTFgnWArqANz5RXuPMgms6dPYCI7GjR%2FyI2eQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-20 04:13 UTC, opbld32 commented
Docs Build status updates of commit _[6cb7886](https://github.com/MicrosoftDocs/msteams-docs/commits/6cb78866731f06e378aaa9c55448476a744228c9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/get-started/glossary.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) | [Details](#user-content-ebc1a69710ba4f0d66997f8d89c0b432-a59dd510)
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |

<a id="ebc1a69710ba4f0d66997f8d89c0b432-a59dd510"></a>
### [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/get-started/glossary.md)
 - **Line 23, Column 9**: **[Warning: table-syntax-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C20%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202201200412348653-5024%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-20T04%3A13%3A41Z&sr=b&sp=r&sig=Ttzkisb2PiZ%2FaNxjeJ2QpjNnIrgxvwT%2FDOhZFexULZY%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-20 04:22 UTC, opbld32 commented
Docs Build status updates of commit _[1f19aa4](https://github.com/MicrosoftDocs/msteams-docs/commits/1f19aa4872f03e243d4f6cadca7d3bd5f474db3a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |
[msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/get-started/glossary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C20%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202201200421090354-5024%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-20T04%3A22%3A17Z&sr=b&sp=r&sig=JDnL%2F%2Fo4SXk%2B0L%2BmxZCUEhhyJdDczZ4pkKTthqicDqg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-20 05:32 UTC, opbld32 commented
Docs Build status updates of commit _[186ceef](https://github.com/MicrosoftDocs/msteams-docs/commits/186ceef0276127938b2f4b4455c2f0f115958d93)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |
[msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/get-started/glossary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C20%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202201200531121086-5024%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-20T05%3A32%3A50Z&sr=b&sp=r&sig=0kHBTf1vbcQyN8AR063Tx8J4JRpf6FPT5qomjiTudTg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-20 12:10 UTC, opbld33 commented
Docs Build status updates of commit _[da475fc](https://github.com/MicrosoftDocs/msteams-docs/commits/da475fc17e1c9070860b8786dfd4fc78376109c1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |
[msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/get-started/glossary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C20%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202201201209118736-5024%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-20T12%3A10%3A11Z&sr=b&sp=r&sig=DltAzjVuCOVCEfjBopQZqLPs0LcQ4zWmUW20hIWiiA4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-21 03:50 UTC, opbld33 commented
Docs Build status updates of commit _[25f258b](https://github.com/MicrosoftDocs/msteams-docs/commits/25f258b1945a36486c02acb8e299bf680768746a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |
[msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/get-started/glossary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C21%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202201210349164257-5024%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-21T03%3A50%3A31Z&sr=b&sp=r&sig=YPTUZbIj4Kr%2B2jOF4EscIhUbEcw70G1OJNWAYBF0Hfc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-21 05:00 UTC, opbld32 commented
Docs Build status updates of commit _[af8bfaa](https://github.com/MicrosoftDocs/msteams-docs/commits/af8bfaa0323cda26ab42db16d523e7eff6042dcd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |
[msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/get-started/glossary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C21%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202201210459559317-5024%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-21T05%3A00%3A47Z&sr=b&sp=r&sig=i7%2BMbXTQjQ6PLc1LdPdbJkZHmgpR3mQf%2BPKW%2BeQChq8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-21 05:46 UTC, opbld32 commented
Docs Build status updates of commit _[4c32f2b](https://github.com/MicrosoftDocs/msteams-docs/commits/4c32f2b6255ed8cb935dcd9e86182642d2079894)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/get-started/glossary.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) | [Details](#user-content-ebc1a69710ba4f0d66997f8d89c0b432-022a086d)
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |

<a id="ebc1a69710ba4f0d66997f8d89c0b432-022a086d"></a>
### [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/get-started/glossary.md)
 - **Line 26, Column 11**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/schema/manifest-schema'.`````
 - **Line 27, Column 11**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../concepts/build-and-test/apps-package'.`````
 - **Line 28, Column 11**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../concepts/device-capabilities/browser-device-permissions'.`````
 - **Line 29, Column 11**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../concepts/design/app-structure'.`````
 - **Line 30, Column 11**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../concepts/build-and-test/app-studio-overview'.`````
 - **Line 31, Column 11**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../toolkit/provision'.`````
 - **Line 32, Column 11**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../tabs/how-to/authentication/auth-tab-aad'.`````
 - **Line 33, Column 11**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../concepts/authentication/authentication'.`````
 - **Line 34, Column 11**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../concepts/authentication/authentication'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C21%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202201210545107150-5024%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-21T05%3A46%3A08Z&sr=b&sp=r&sig=Ty2vsMYt1vcajB9PEWYtv%2FruaIC2%2Bl85s9pHierY3qM%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-21 05:51 UTC, opbld30 commented
Docs Build status updates of commit _[e1902fb](https://github.com/MicrosoftDocs/msteams-docs/commits/e1902fbbd6c9ae866a468882710e45ae58349d2d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/get-started/glossary.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) | [Details](#user-content-ebc1a69710ba4f0d66997f8d89c0b432-71d7543f)
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |

<a id="ebc1a69710ba4f0d66997f8d89c0b432-71d7543f"></a>
### [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/get-started/glossary.md)
 - **Line 28, Column 11**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../concepts/device-capabilities/browser-device-permissions'.`````
 - **Line 34, Column 11**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../concepts/authentication/authentication'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C21%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202201210550048446-5024%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-21T05%3A51%3A05Z&sr=b&sp=r&sig=9XNKE8GMpD0Yv2VV%2BTXntAeHs6Ls8SbKPWtkL9K3Nbk%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-21 05:55 UTC, opbld30 commented
Docs Build status updates of commit _[742e0ad](https://github.com/MicrosoftDocs/msteams-docs/commits/742e0adb77ad6c686cf48786f2e97fb01a5090d6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |
[msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/get-started/glossary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C21%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202201210554230654-5024%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-21T05%3A55%3A29Z&sr=b&sp=r&sig=6cjBZKHlAWhBmmOacFpZCmvE8wAuUSwhyf05ScnuRf8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-21 06:11 UTC, opbld30 commented
Docs Build status updates of commit _[993bb16](https://github.com/MicrosoftDocs/msteams-docs/commits/993bb166f27b430f3bd3d178ce3deefbfebf99af)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |
[msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/get-started/glossary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C21%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202201210610584297-5024%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-21T06%3A11%3A57Z&sr=b&sp=r&sig=awzGxrYBv32zmIzT5fIi0n9MsyCRFfq3EmwSlNhAihA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-21 06:14 UTC, opbld33 commented
Docs Build status updates of commit _[6cd5961](https://github.com/MicrosoftDocs/msteams-docs/commits/6cd5961bdb855abf6ae5fe0e781a8f53b92feed6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |
[msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/get-started/glossary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C21%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202201210613322292-5024%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-21T06%3A14%3A31Z&sr=b&sp=r&sig=Q9VLtLdMpiQngruy6LHEsZgXbiHQc7rGdC8XM0MuvD8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-21 08:03 UTC, opbld30 commented
Docs Build status updates of commit _[96360a9](https://github.com/MicrosoftDocs/msteams-docs/commits/96360a92439ceeb623d34c2ee94895d0bcc604bf)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/get-started/glossary.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) | [Details](#user-content-ebc1a69710ba4f0d66997f8d89c0b432-790bd34d)
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |

<a id="ebc1a69710ba4f0d66997f8d89c0b432-790bd34d"></a>
### [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/get-started/glossary.md)
 - **Line 67, Column 11**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../platform/webhooks-and-connectors/what-are-webhooks-and-connectors.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C21%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202201210802183624-5024%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-21T08%3A03%3A21Z&sr=b&sp=r&sig=AeWu1FojrOpuG513U3b4ySKdLp6%2BTpvXZRZeMGMPTk4%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-21 11:50 UTC, opbld30 commented
Docs Build status updates of commit _[3bb3f03](https://github.com/MicrosoftDocs/msteams-docs/commits/3bb3f0340ea208ac99ae11fd4c6185c058998f61)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/get-started/glossary.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) | [Details](#user-content-ebc1a69710ba4f0d66997f8d89c0b432-2f78e3b6)
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |

<a id="ebc1a69710ba4f0d66997f8d89c0b432-2f78e3b6"></a>
### [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/get-started/glossary.md)
 - **Line 67, Column 11**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../platform/webhooks-and-connectors/what-are-webhooks-and-connectors.md'.`````
 - **Line 81, Column 11**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../concepts/build-and-test/teams-developer-portal'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C21%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202201211149373695-5024%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-21T11%3A50%3A51Z&sr=b&sp=r&sig=B3BqUj56vmxYAWJzRec92iS8px%2F8j5UVoNKAatmDbBY%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-21 11:56 UTC, opbld32 commented
Docs Build status updates of commit _[90fd477](https://github.com/MicrosoftDocs/msteams-docs/commits/90fd477f795cfc3f2b156b72699f95126a536c9f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |
[msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/get-started/glossary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C21%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202201211155106302-5024%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-21T11%3A56%3A03Z&sr=b&sp=r&sig=FOiu5%2B6TQTlGNe6GEl3JfUvQPDF4YqJTO0jTLZp66Uo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-24 03:28 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/972958edd0b27afc77a7bceb6fca802e52495fe2/msteams-platform/TOC.yml) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b142dca0-7a00-4e9c-ab43-2ee7394120e5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/972958edd0b27afc77a7bceb6fca802e52495fe2/msteams-platform/get-started/glossary.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4b9ca040-46fc-4a75-b96c-7d558488a51e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-01-24 03:28 UTC, opbld31 commented
Docs Build status updates of commit _[972958e](https://github.com/MicrosoftDocs/msteams-docs/commits/972958edd0b27afc77a7bceb6fca802e52495fe2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |
[msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/get-started/glossary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C24%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202201240327383778-5024%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-24T03%3A28%3A44Z&sr=b&sp=r&sig=n3K7rY4E5pmx%2B4imidtojkd59rAp4zyieeWbDFbVfjU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-24 03:40 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/21739a23afada44e8c1f5ac6533688c7d9e82873/msteams-platform/TOC.yml) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f0adf21e-0dcb-47a0-a12b-5cb93b9661aa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/21739a23afada44e8c1f5ac6533688c7d9e82873/msteams-platform/get-started/glossary.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9aec3711-5a35-4fbb-8c2a-c6b115fe5ab3) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-01-24 03:41 UTC, opbld33 commented
Docs Build status updates of commit _[21739a2](https://github.com/MicrosoftDocs/msteams-docs/commits/21739a23afada44e8c1f5ac6533688c7d9e82873)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |
[msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/get-started/glossary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C24%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202201240339439185-5024%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-24T03%3A41%3A51Z&sr=b&sp=r&sig=28uw%2Fclp44lYicBCi1QZ1T1pu7MTHNO%2FapuUtEcET%2F8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-24 04:36 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/3cc30a9918f3e4d2eea499b1c38de7450435eb90/msteams-platform/TOC.yml) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2f8aa6aa-75fc-459c-ba97-3be1a436d269) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3cc30a9918f3e4d2eea499b1c38de7450435eb90/msteams-platform/get-started/glossary.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a720c564-3889-49b7-b477-c1be657bf5a0) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-01-24 04:38 UTC, opbld30 commented
Docs Build status updates of commit _[3cc30a9](https://github.com/MicrosoftDocs/msteams-docs/commits/3cc30a9918f3e4d2eea499b1c38de7450435eb90)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |
[msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/get-started/glossary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C24%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202201240436243410-5024%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-24T04%3A38%3A45Z&sr=b&sp=r&sig=CNyHyW8yOid1ezJoiYwKLxm5YNx%2BsZqOnYUiAa5FlGo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-24 05:02 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/675b498086409fb00ba4e13427e91eb1aaa3a489/msteams-platform/TOC.yml) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/79cb4bba-da2f-431b-b6bb-db8043f4c9bc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/675b498086409fb00ba4e13427e91eb1aaa3a489/msteams-platform/get-started/glossary.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4d34e9a6-e520-4328-a74f-eb46ce4f1f9c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-01-24 05:03 UTC, opbld32 commented
Docs Build status updates of commit _[675b498](https://github.com/MicrosoftDocs/msteams-docs/commits/675b498086409fb00ba4e13427e91eb1aaa3a489)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |
[msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/get-started/glossary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C24%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202201240501400800-5024%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-24T05%3A03%3A19Z&sr=b&sp=r&sig=Tv3jFlcnqXh9W%2FLk8V9H8gcP0Jk1EpiHDnqGccDPHKs%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-24 05:41 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c144d290d97466415b1b9e190742dd4768ecec9e/msteams-platform/TOC.yml) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7586a407-0b87-4587-9700-a51c28eb7b28) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c144d290d97466415b1b9e190742dd4768ecec9e/msteams-platform/get-started/glossary.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2025efbd-7b51-4414-8b35-49bde7f45ec9) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-01-24 05:41 UTC, opbld31 commented
Docs Build status updates of commit _[c144d29](https://github.com/MicrosoftDocs/msteams-docs/commits/c144d290d97466415b1b9e190742dd4768ecec9e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |
[msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/get-started/glossary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C24%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202201240540339769-5024%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-24T05%3A41%3A27Z&sr=b&sp=r&sig=nBdVkUhcVus8eVDPuG4dsBfi%2FrOc1ws%2FVZUCKaHFJtI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-24 06:13 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/15da3fe31f455f366257b18ceb6db27b1e33c393/msteams-platform/TOC.yml) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e845bc81-a638-4063-884e-d15daed66354) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/15da3fe31f455f366257b18ceb6db27b1e33c393/msteams-platform/get-started/glossary.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fb4b27d5-4297-4ec3-8965-b954f3d750a3) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-01-24 06:15 UTC, opbld30 commented
Docs Build status updates of commit _[15da3fe](https://github.com/MicrosoftDocs/msteams-docs/commits/15da3fe31f455f366257b18ceb6db27b1e33c393)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |
[msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/get-started/glossary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C24%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202201240613194951-5024%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-24T06%3A15%3A20Z&sr=b&sp=r&sig=r9vpNDGJ6vl%2B7MW3ZjTem2c4%2FffAzoVQLFvsCPNKUvE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-24 06:30 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/aa0659af578f9d3492cce9550fc51b91801747f0/msteams-platform/TOC.yml) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bc959d42-7b80-4679-a4f9-9d2057246299) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/aa0659af578f9d3492cce9550fc51b91801747f0/msteams-platform/get-started/glossary.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/80a31466-90ee-406a-a2a0-a0dcaa544307) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-01-24 06:32 UTC, opbld31 commented
Docs Build status updates of commit _[aa0659a](https://github.com/MicrosoftDocs/msteams-docs/commits/aa0659af578f9d3492cce9550fc51b91801747f0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |
[msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/get-started/glossary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C24%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202201240629478545-5024%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-24T06%3A32%3A08Z&sr=b&sp=r&sig=D8w%2Fr6FXXuAFqVE5rekwzGuFqZqtApBHZenj84UNN4A%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-24 06:36 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/d293047a09311d52e49feb1fdf2a10e97c59c7a2/msteams-platform/TOC.yml) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6566fbb8-2c49-4937-bfad-f673d4631de3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d293047a09311d52e49feb1fdf2a10e97c59c7a2/msteams-platform/get-started/glossary.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/087ed1b5-f832-471a-b100-b199df4fe048) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-01-24 06:37 UTC, opbld30 commented
Docs Build status updates of commit _[d293047](https://github.com/MicrosoftDocs/msteams-docs/commits/d293047a09311d52e49feb1fdf2a10e97c59c7a2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |
[msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/get-started/glossary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C24%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202201240636242161-5024%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-24T06%3A37%3A57Z&sr=b&sp=r&sig=FOchLqXXzT57dQfIqdXevdadoCoqGn0cUlkCoeBY28A%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-01 02:47 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/770534d6d1fc6b0c72dafa656e92b53965762e20/msteams-platform/TOC.yml) | 96 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/92d322b9-687f-46f7-8f2e-0338a132ac5b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/770534d6d1fc6b0c72dafa656e92b53965762e20/msteams-platform/get-started/glossary.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d7dd1c62-e9fb-4885-a663-3a6d4765de71) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-02-01 02:47 UTC, opbld31 commented
Docs Build status updates of commit _[770534d](https://github.com/MicrosoftDocs/msteams-docs/commits/770534d6d1fc6b0c72dafa656e92b53965762e20)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |
[msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/get-started/glossary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C1%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202202010246573100-5024%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-04T02%3A47%3A57Z&sr=b&sp=r&sig=8kBdxgFqsHsQv0ftc5apHlDGsmOxjvE97l4pErKz%2BEg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-01 02:58 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/99997d9c4e72212f0a13316c8bfedc03f701b72e/msteams-platform/TOC.yml) | 96 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9cfbfbf9-042d-4771-81f6-a28ab11b1270) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/99997d9c4e72212f0a13316c8bfedc03f701b72e/msteams-platform/get-started/glossary.md) | 88 | 45 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/72fe4110-fecb-4692-b0e7-498a09190f8e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-02-01 02:59 UTC, opbld30 commented
Docs Build status updates of commit _[99997d9](https://github.com/MicrosoftDocs/msteams-docs/commits/99997d9c4e72212f0a13316c8bfedc03f701b72e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |
[msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/get-started/glossary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C1%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202202010258090596-5024%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-04T02%3A59%3A15Z&sr=b&sp=r&sig=PUANIceyFAccoiX1wCmHRlFwY893NHQhXkZUT5%2F%2BgpM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-02 11:35 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a28cdebaf5a653d219b532ec0f193c22147b7093/msteams-platform/TOC.yml) | 98 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/419834e3-ef85-4dc4-ade3-8f3031690760) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a28cdebaf5a653d219b532ec0f193c22147b7093/msteams-platform/get-started/glossary.md) | 94 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/12ff5819-801c-4ce7-b6de-5d02001a52b1) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-02-02 11:36 UTC, opbld33 commented
Docs Build status updates of commit _[a28cdeb](https://github.com/MicrosoftDocs/msteams-docs/commits/a28cdebaf5a653d219b532ec0f193c22147b7093)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/get-started/glossary.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) | [Details](#user-content-ebc1a69710ba4f0d66997f8d89c0b432-d569ef1a)
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |

<a id="ebc1a69710ba4f0d66997f8d89c0b432-d569ef1a"></a>
### [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/get-started/glossary.md)
 - **Line 41, Column 204**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#a' in 'get-started/glossary.md', did you mean '#b'?`````
 - **Line 81, Column 267**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#a' in 'get-started/glossary.md', did you mean '#b'?`````
 - **Line 119, Column 209**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#a' in 'get-started/glossary.md', did you mean '#b'?`````
 - **Line 151, Column 257**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#a' in 'get-started/glossary.md', did you mean '#b'?`````
 - **Line 212, Column 275**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#a' in 'get-started/glossary.md', did you mean '#b'?`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C2%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202202021135214490-5024%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-05T11%3A36%3A15Z&sr=b&sp=r&sig=a5WOnBUJRq8Hby6ckihBZua4TgM8%2FyrgO7w7U2U7IgE%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-02 11:59 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ec9b7daed6dcbe1af4c0fb95ad109b0e10e66dc8/msteams-platform/TOC.yml) | 98 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9500e1d1-0cd2-48e8-9304-3115a63b0cc8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ec9b7daed6dcbe1af4c0fb95ad109b0e10e66dc8/msteams-platform/get-started/glossary.md) | 94 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9c2fade5-7c76-4f10-b2b5-1220235c3023) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-02-02 11:59 UTC, opbld32 commented
Docs Build status updates of commit _[ec9b7da](https://github.com/MicrosoftDocs/msteams-docs/commits/ec9b7daed6dcbe1af4c0fb95ad109b0e10e66dc8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |
[msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/get-started/glossary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C2%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202202021158289867-5024%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-05T11%3A59%3A26Z&sr=b&sp=r&sig=g%2FjSbnpWLnFg4If0zaFKK9Y9vU%2FaEs3tiUAj019agL0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-03 04:40 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/6ae7257d1208ec2a6dfa5aea48e627f20c479c21/msteams-platform/TOC.yml) | 100 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/710e2b00-a4fb-49d6-a384-e5b1e328a5ae) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6ae7257d1208ec2a6dfa5aea48e627f20c479c21/msteams-platform/get-started/glossary.md) | 92 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d8f1d713-ae63-46c8-9338-e6ee7bd5f3c2) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-02-03 04:41 UTC, opbld31 commented
Docs Build status updates of commit _[6ae7257](https://github.com/MicrosoftDocs/msteams-docs/commits/6ae7257d1208ec2a6dfa5aea48e627f20c479c21)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |
[msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/get-started/glossary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C3%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202202030440120284-5024%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-06T04%3A41%3A57Z&sr=b&sp=r&sig=UQFPp%2Fcsw3LYjE8iGLbYkOWeE6DRzqQ125YoAJd6kUo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-03 05:19 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/94ee4adf977bc99bf7b9a7e0018f500d93f423b2/msteams-platform/TOC.yml) | 100 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/abf374c2-155d-401f-869c-9cbc5af768e3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/94ee4adf977bc99bf7b9a7e0018f500d93f423b2/msteams-platform/get-started/glossary.md) | 92 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a3dfb7c5-6d4b-4265-b57c-41ca28e79226) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-02-03 05:20 UTC, opbld32 commented
Docs Build status updates of commit _[94ee4ad](https://github.com/MicrosoftDocs/msteams-docs/commits/94ee4adf977bc99bf7b9a7e0018f500d93f423b2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/get-started/glossary.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) | [Details](#user-content-ebc1a69710ba4f0d66997f8d89c0b432-d4cfe762)
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |

<a id="ebc1a69710ba4f0d66997f8d89c0b432-d4cfe762"></a>
### [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/get-started/glossary.md)
 - **Line 44, Column 205**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#a' in 'get-started/glossary.md', did you mean '#b'?`````
 - **Line 84, Column 267**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#a' in 'get-started/glossary.md', did you mean '#b'?`````
 - **Line 122, Column 209**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#a' in 'get-started/glossary.md', did you mean '#b'?`````
 - **Line 154, Column 257**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#a' in 'get-started/glossary.md', did you mean '#b'?`````
 - **Line 215, Column 275**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#a' in 'get-started/glossary.md', did you mean '#b'?`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C3%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202202030519066994-5024%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-06T05%3A20%3A29Z&sr=b&sp=r&sig=x9tqr1OfsYz2ymCZBkTsGJA3aG65eJq%2B3X762PJHnjQ%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-03 05:27 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ce39aa83a8a92f7dbf164f7d5c1442ab629a0f13/msteams-platform/TOC.yml) | 100 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f0e72ffa-500a-404f-81d6-5efec565d73d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ce39aa83a8a92f7dbf164f7d5c1442ab629a0f13/msteams-platform/get-started/glossary.md) | 92 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7ffd685f-1b0f-4c71-95fa-319c93df44b9) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-02-03 05:28 UTC, opbld32 commented
Docs Build status updates of commit _[ce39aa8](https://github.com/MicrosoftDocs/msteams-docs/commits/ce39aa83a8a92f7dbf164f7d5c1442ab629a0f13)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/get-started/glossary.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) | [Details](#user-content-ebc1a69710ba4f0d66997f8d89c0b432-a9c1d8aa)
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |

<a id="ebc1a69710ba4f0d66997f8d89c0b432-a9c1d8aa"></a>
### [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/get-started/glossary.md)
 - **Line 42, Column 206**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#a' in 'get-started/glossary.md', did you mean '#-'?`````
 - **Line 82, Column 267**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#a' in 'get-started/glossary.md', did you mean '#-'?`````
 - **Line 120, Column 209**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#a' in 'get-started/glossary.md', did you mean '#-'?`````
 - **Line 152, Column 257**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#a' in 'get-started/glossary.md', did you mean '#-'?`````
 - **Line 213, Column 275**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#a' in 'get-started/glossary.md', did you mean '#-'?`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C3%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202202030527208647-5024%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-06T05%3A28%3A13Z&sr=b&sp=r&sig=66exblJwvBoPPDcoVVJWqBQgjvMf6H%2FQinm18VcAc0c%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-03 06:18 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/35d7cf99cb81e42f1ce1c958ffcaed53212f3c7f/msteams-platform/TOC.yml) | 100 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e7155aab-5242-4206-ac99-c791ea0240bf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/35d7cf99cb81e42f1ce1c958ffcaed53212f3c7f/msteams-platform/get-started/glossary.md) | 92 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/22c0d5be-d808-49a2-be14-5008427cc40b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-02-03 06:19 UTC, opbld33 commented
Docs Build status updates of commit _[35d7cf9](https://github.com/MicrosoftDocs/msteams-docs/commits/35d7cf99cb81e42f1ce1c958ffcaed53212f3c7f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |
[msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/get-started/glossary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C3%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202202030618054001-5024%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-06T06%3A19%3A04Z&sr=b&sp=r&sig=XSOKfgyJD%2BY26a4Vsh8UMqxJGLyDrCJzgb0CO6djYLI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-08 02:59 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c5167109e58e815ec4cd60b19bb2f99874ca18ff/msteams-platform/TOC.yml) | 100 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/449beace-16dc-4330-a87e-caf62cc26759) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c5167109e58e815ec4cd60b19bb2f99874ca18ff/msteams-platform/get-started/glossary.md) | 92 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2461d115-f8bf-4a8a-8057-14b67fd8b3b7) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-02-08 02:59 UTC, opbld33 commented
Docs Build status updates of commit _[c516710](https://github.com/MicrosoftDocs/msteams-docs/commits/c5167109e58e815ec4cd60b19bb2f99874ca18ff)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |
[msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/get-started/glossary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C8%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202202080258372680-5024%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-11T02%3A59%3A29Z&sr=b&sp=r&sig=FqrlZ5RpJK%2BNUFAWTdlC4TRpqGypIGt0%2Fb0A%2FP8xZic%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-08 03:46 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c1997b3fa5aca8217c8a24340b49e3c077ab9a5b/msteams-platform/TOC.yml) | 100 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c13e559b-350c-429e-bdd7-df75e7be35e3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c1997b3fa5aca8217c8a24340b49e3c077ab9a5b/msteams-platform/get-started/glossary.md) | 92 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6b01163e-ba52-4961-9230-78f89c73f9cf) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-02-08 03:47 UTC, opbld31 commented
Docs Build status updates of commit _[c1997b3](https://github.com/MicrosoftDocs/msteams-docs/commits/c1997b3fa5aca8217c8a24340b49e3c077ab9a5b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |
[msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/get-started/glossary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C8%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202202080345375125-5024%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-11T03%3A47%3A11Z&sr=b&sp=r&sig=mziWYRG2Bo5UYChhABkWj6QsotC4Uf3k1b4FNb12j90%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-08 06:56 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/9cd3b6287e004de78b6d3294e407619880f30655/msteams-platform/TOC.yml) | 100 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c19f7dd9-8b5e-4ab7-9f8d-09c782c53fdb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9cd3b6287e004de78b6d3294e407619880f30655/msteams-platform/get-started/glossary.md) | 91 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a47734a2-589e-4d9d-a6ad-439258579b1c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-02-08 06:56 UTC, opbld32 commented
Docs Build status updates of commit _[9cd3b62](https://github.com/MicrosoftDocs/msteams-docs/commits/9cd3b6287e004de78b6d3294e407619880f30655)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/get-started/glossary.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) | [Details](#user-content-ebc1a69710ba4f0d66997f8d89c0b432-4e7404a5)
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |

<a id="ebc1a69710ba4f0d66997f8d89c0b432-4e7404a5"></a>
### [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/get-started/glossary.md)
 - **Line 55, Column 2**: **[Suggestion: column-header-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/column-header-missing?branch=main)]** `````Column headers are required for tables. Add appropriate header text, or remove any extra table cells that cause an extra column.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C8%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202202080655271066-5024%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-11T06%3A56%3A20Z&sr=b&sp=r&sig=EQuDqdihwWU7LQ9aUdvE8tHugJQ%2BWLEP42BwwHK4kZQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-08 07:03 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/59111b378fcde9df22b82776081c6a53f2bc9689/msteams-platform/TOC.yml) | 100 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bba3c13c-14fd-4db6-8b91-b3271120d053) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/59111b378fcde9df22b82776081c6a53f2bc9689/msteams-platform/get-started/glossary.md) | 91 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9337ff9e-66e9-409a-9d54-02b9c2238c62) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-02-08 07:04 UTC, opbld32 commented
Docs Build status updates of commit _[59111b3](https://github.com/MicrosoftDocs/msteams-docs/commits/59111b378fcde9df22b82776081c6a53f2bc9689)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |
[msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/get-started/glossary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C8%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202202080702258652-5024%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-11T07%3A04%3A02Z&sr=b&sp=r&sig=ZMFM1FXTOSPFFtccIGp8aom%2BzG7P5%2Fi4lQdQiXi6H7E%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-10 13:12 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/b40997feb0521de489179b19b95c9c6015248cfc/msteams-platform/TOC.yml) | 100 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/29c154e7-7b65-4ad4-839a-608b3c56db1c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b40997feb0521de489179b19b95c9c6015248cfc/msteams-platform/get-started/glossary.md) | 91 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9a6dc4f7-c3b6-4c7b-acfe-b7ef3983e592) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-02-10 13:20 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/24fecc31d02a8c4c59a937d2eb3335e0be3ccafd/msteams-platform/TOC.yml) | 100 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a21a24b3-d020-4064-a303-14279c8e08e7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/24fecc31d02a8c4c59a937d2eb3335e0be3ccafd/msteams-platform/get-started/glossary.md) | 91 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/489ca51b-26dd-42e6-875a-68818239e24f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-02-10 13:20 UTC, opbld32 commented
Docs Build status updates of commit _[24fecc3](https://github.com/MicrosoftDocs/msteams-docs/commits/24fecc31d02a8c4c59a937d2eb3335e0be3ccafd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |
[msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/get-started/glossary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C10%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202202101319397306-5024%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-13T13%3A20%3A46Z&sr=b&sp=r&sig=IPwMOPDQViHyaimhdbAMGnLbrZjH8X8QJZ4NkqAkPqg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-14 05:07 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/f98e65999e722086918dbf732be303790af29bdb/msteams-platform/TOC.yml) | 100 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e3603fdd-f5ac-4169-8d89-c2ac381770d0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f98e65999e722086918dbf732be303790af29bdb/msteams-platform/get-started/glossary.md) | 91 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5c2a1630-5053-4a3b-bc99-d652f3c99880) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-02-14 05:09 UTC, opbld32 commented
Docs Build status updates of commit _[f98e659](https://github.com/MicrosoftDocs/msteams-docs/commits/f98e65999e722086918dbf732be303790af29bdb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |
[msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/get-started/glossary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C14%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202202140507174061-5024%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-17T05%3A09%3A02Z&sr=b&sp=r&sig=sqmDEBT2OrL4EHdD3CQoY8UyyckToMwBgEmqOD%2Fyjd0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-14 06:44 UTC, opbld32 commented
Docs Build status updates of commit _[3de2ec9](https://github.com/MicrosoftDocs/msteams-docs/commits/3de2ec9e3877144177f5535c0a00281852e836cc)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/get-started/glossary.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) | [Details](#user-content-ebc1a69710ba4f0d66997f8d89c0b432-66fabb88)
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |

<a id="ebc1a69710ba4f0d66997f8d89c0b432-66fabb88"></a>
### [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/get-started/glossary.md)
 - **Line 137, Column 1**: **[Warning: sensitive-language-wl - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/sensitive-language?branch=main)]** `````Term 'whitelisting' is sensitive and should not be used in content or code. Usage: '| [Mobile whitelisting](../tabs/design/tabs-mobile.md) | A process to approve trusted websites for communication with a mo'`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C14%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202202140643066142-5024%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-17T06%3A44%3A01Z&sr=b&sp=r&sig=NEOnWOOcdAVueo82eE3nE5tbEe9qA0GRuugSXIZidMw%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-14 06:44 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/3de2ec9e3877144177f5535c0a00281852e836cc/msteams-platform/TOC.yml) | 100 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4b0d7dc6-0c64-414c-af3a-9940e73f9e52) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3de2ec9e3877144177f5535c0a00281852e836cc/msteams-platform/get-started/glossary.md) | 91 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/03cfa573-138c-4270-99b5-19b64be17b42) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-02-14 07:24 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1888ae592c0f7c462873e55756e2d193a1c5fd93/msteams-platform/TOC.yml) | 100 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/730917e7-4691-4bad-b6aa-1fe6ba91dff5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1888ae592c0f7c462873e55756e2d193a1c5fd93/msteams-platform/get-started/glossary.md) | 91 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/92579496-d56b-4b16-8c74-632db1bc4d58) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-02-14 07:25 UTC, opbld32 commented
Docs Build status updates of commit _[1888ae5](https://github.com/MicrosoftDocs/msteams-docs/commits/1888ae592c0f7c462873e55756e2d193a1c5fd93)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/get-started/glossary.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) | [Details](#user-content-ebc1a69710ba4f0d66997f8d89c0b432-87891804)
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |

<a id="ebc1a69710ba4f0d66997f8d89c0b432-87891804"></a>
### [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/get-started/glossary.md)
 - **Line 137, Column 1**: **[Warning: sensitive-language-wl - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/sensitive-language?branch=main)]** `````Term 'whitelisting' is sensitive and should not be used in content or code. Usage: '| [Mobile whitelisting](../tabs/design/tabs-mobile.md) | A process to approve trusted websites for communication with a mo'`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C14%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202202140724018603-5024%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-17T07%3A25%3A01Z&sr=b&sp=r&sig=U5xN6rDE5hz%2F6NAp3T40bEmiD1p9juQ8KMVoLyVgSR8%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-14 08:25 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/684f063b4941a0b6e36c64efcdcfa8ebe549f2ab/msteams-platform/TOC.yml) | 100 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8e26644d-dbaf-4003-b0a1-1951deb538c8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/684f063b4941a0b6e36c64efcdcfa8ebe549f2ab/msteams-platform/get-started/glossary.md) | 89 | 41 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b4f9d2d2-d87f-43e7-bce6-dca550c3985b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-02-14 08:26 UTC, opbld31 commented
Docs Build status updates of commit _[684f063](https://github.com/MicrosoftDocs/msteams-docs/commits/684f063b4941a0b6e36c64efcdcfa8ebe549f2ab)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/get-started/glossary.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) | [Details](#user-content-ebc1a69710ba4f0d66997f8d89c0b432-4411751d)
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |

<a id="ebc1a69710ba4f0d66997f8d89c0b432-4411751d"></a>
### [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/get-started/glossary.md)
 - **Line 145, Column 1**: **[Warning: sensitive-language-wl - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/sensitive-language?branch=main)]** `````Term 'whitelisting' is sensitive and should not be used in content or code. Usage: '| [Mobile whitelisting](../tabs/design/tabs-mobile.md) | A process to approve trusted websites for communication with a mo'`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C14%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202202140824255029-5024%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-17T08%3A26%3A13Z&sr=b&sp=r&sig=E1AbFmyzb9eUNuJTLc2j4SWWV4%2BM3rByF3cZTbdVNMA%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-14 08:29 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/eb79b3ff47e8b720fea22c273a261e435734e7cf/msteams-platform/TOC.yml) | 100 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3ce684a6-7338-43a8-9f63-bb6e2115e613) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/eb79b3ff47e8b720fea22c273a261e435734e7cf/msteams-platform/get-started/glossary.md) | 89 | 40 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/77a59d35-3c07-44f0-93c9-1c4c69b99abe) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-02-14 08:29 UTC, opbld32 commented
Docs Build status updates of commit _[eb79b3f](https://github.com/MicrosoftDocs/msteams-docs/commits/eb79b3ff47e8b720fea22c273a261e435734e7cf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |
[msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/get-started/glossary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C14%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202202140828204201-5024%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-17T08%3A29%3A01Z&sr=b&sp=r&sig=XEORQ7x3oenCtbPDwiq64oT%2Fn7QGRltpoFgSbWpHp6A%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-16 14:56 UTC, surbhigupta12 requested changes

2022-02-16 14:56 UTC, surbhigupta12 commented on msteams-platform/get-started/glossary.md
> +| [Adaptive Card](../task-modules-and-cards/what-are-cards.md) | An actionable content snippet added to a conversation by a bot or messaging extension. Use text, graphics, and buttons with these card
Global comment: Adaptive Cards

2022-02-16 14:56 UTC, surbhigupta12 commented on msteams-platform/get-started/glossary.md
> +| [App package](../concepts/build-and-test/apps-package.md) | A Teams app package is a zip file that contains the App manifest file and app icons - color icon and outline icon. |
Avoid using -

See MSTP once

2022-02-16 14:56 UTC, surbhigupta12 commented on msteams-platform/get-started/glossary.md
> +| [Capability](../toolkit/add-capability.md) | The feature of a Teams app are called as Capability. An app may have one or more core capabilities, such as tab, bot, messaging extensions. <br>**See al
A feature of a Teams app is called capability. 

Please verify once

2022-02-16 14:56 UTC, surbhigupta12 commented on msteams-platform/get-started/glossary.md
> +| [Local environment](../toolkit/teamsfx-multi-env.md#create-a-new-environment) | A default development environment created by Teams Toolkit  <br>**See also**: [Environment](#e); [Dev environment](#d
Period missing

2022-02-16 14:56 UTC, surbhigupta12 commented on msteams-platform/get-started/glossary.md
> +| [Store validation guidelines](../concepts/deploy-and-publish/appsource/prepare/teams-store-validation-guidelines.md) | A set of Teams-specific guidelines for validating an app before it can be subm
Global

Teams Store
or
Teams store

2022-02-17 03:51 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/0160847ea4c5d116d52bb6fce996777e2000ad19/msteams-platform/TOC.yml) | 100 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0004566a-d351-41b9-8e11-c2f0be2e650b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0160847ea4c5d116d52bb6fce996777e2000ad19/msteams-platform/get-started/glossary.md) | 89 | 40 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/de5e99f6-c17d-475a-9307-ce1ce554682a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-02-17 03:51 UTC, opbld32 commented
Docs Build status updates of commit _[0160847](https://github.com/MicrosoftDocs/msteams-docs/commits/0160847ea4c5d116d52bb6fce996777e2000ad19)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |
[msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/get-started/glossary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C17%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202202170351017945-5024%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-20T03%3A51%3A54Z&sr=b&sp=r&sig=a2EPXhV8OGc133tKHdYwqPaM9m8N1qAEWZIKtXRO1dI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-17 04:17 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/638e0db2f95a1c80013a992ead2b640b01279b30/msteams-platform/TOC.yml) | 100 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/13cbddf8-37cf-4a3a-a28e-707d84689890) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/638e0db2f95a1c80013a992ead2b640b01279b30/msteams-platform/get-started/glossary.md) | 90 | 39 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/db5e2f21-e174-4f89-a26c-3fa56cf0ef17) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-02-17 04:19 UTC, opbld31 commented
Docs Build status updates of commit _[638e0db](https://github.com/MicrosoftDocs/msteams-docs/commits/638e0db2f95a1c80013a992ead2b640b01279b30)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |
[msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/get-started/glossary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C17%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202202170417138060-5024%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-20T04%3A19%3A09Z&sr=b&sp=r&sig=jFQtd8YA6cF4NTA%2FicET1HH1ZXCSK4BrKAvQSKnzcG0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-17 04:39 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/66b78e111009199c0ec72a6b1d942b43c53b78cc/msteams-platform/TOC.yml) | 100 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/887fa4b7-d9fc-42af-9234-8bae92b761ea) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/66b78e111009199c0ec72a6b1d942b43c53b78cc/msteams-platform/get-started/glossary.md) | 90 | 39 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cfc149be-e285-4241-aefe-8924dfdd0fc4) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-02-17 04:41 UTC, opbld32 commented
Docs Build status updates of commit _[66b78e1](https://github.com/MicrosoftDocs/msteams-docs/commits/66b78e111009199c0ec72a6b1d942b43c53b78cc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |
[msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/get-started/glossary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C17%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202202170439028096-5024%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-20T04%3A41%3A00Z&sr=b&sp=r&sig=bLvtroXoztKgFx6TsWtHPOvLfHAA87kFP3CUGVgwl7w%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-17 05:31 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/609a3c61a8749815dafd56aa9e2896c69355f974/msteams-platform/TOC.yml) | 100 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/78a49e96-49ae-4bae-bfff-0cd03221a407) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/609a3c61a8749815dafd56aa9e2896c69355f974/msteams-platform/get-started/glossary.md) | 90 | 39 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f580caf3-e7e4-4d7e-90d1-85a425c4cca5) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-02-17 05:31 UTC, opbld33 commented
Docs Build status updates of commit _[609a3c6](https://github.com/MicrosoftDocs/msteams-docs/commits/609a3c61a8749815dafd56aa9e2896c69355f974)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |
[msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/get-started/glossary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C17%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202202170530587002-5024%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-20T05%3A31%3A56Z&sr=b&sp=r&sig=CHjrEoD5lFqHQ6TsufmZDrjPqKt5Oj3E8f%2BTTMAgBaE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-17 10:44 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/f9d3bff7f417c89f70f149436a50642bfd2ca06d/msteams-platform/TOC.yml) | 100 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/77968b65-6843-4e4e-98ff-4b145ec7b5f7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f9d3bff7f417c89f70f149436a50642bfd2ca06d/msteams-platform/get-started/glossary.md) | 90 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c3a1cbe7-1a67-4d79-b5d1-9ea22f5853d3) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-02-17 10:44 UTC, opbld30 commented
Docs Build status updates of commit _[f9d3bff](https://github.com/MicrosoftDocs/msteams-docs/commits/f9d3bff7f417c89f70f149436a50642bfd2ca06d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |
[msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/get-started/glossary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C17%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202202171043549451-5024%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-20T10%3A44%3A52Z&sr=b&sp=r&sig=VTK410lWaisKbx5FatXtV27zHNh0wMoEhS0IT%2FLWgBM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-17 11:53 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/35be0d2168a4935838b2269bd2147fd48837a5c8/msteams-platform/TOC.yml) | 100 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2969e998-595e-4f00-9132-2050f7dd05df) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/35be0d2168a4935838b2269bd2147fd48837a5c8/msteams-platform/get-started/glossary.md) | 91 | 33 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e6e7c538-0042-4808-8fab-12e985414fc0) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-02-17 11:53 UTC, opbld31 commented
Docs Build status updates of commit _[35be0d2](https://github.com/MicrosoftDocs/msteams-docs/commits/35be0d2168a4935838b2269bd2147fd48837a5c8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |
[msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/get-started/glossary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C17%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202202171152489121-5024%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-20T11%3A53%3A48Z&sr=b&sp=r&sig=KBB8hRxz0SmLi%2F12o7vw4tDNKHAQW912M31G0QEOx44%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-17 11:59 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c405074416c944c936b8b582237c1ea61d965f4b/msteams-platform/TOC.yml) | 100 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c175830e-6aa8-4be7-bbbc-fc9ee064e183) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c405074416c944c936b8b582237c1ea61d965f4b/msteams-platform/get-started/glossary.md) | 95 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9974713f-03ec-457b-918b-6a4bcc5156a6) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-02-17 11:59 UTC, opbld33 commented
Docs Build status updates of commit _[c405074](https://github.com/MicrosoftDocs/msteams-docs/commits/c405074416c944c936b8b582237c1ea61d965f4b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |
[msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/get-started/glossary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C17%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202202171158325489-5024%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-20T11%3A59%3A34Z&sr=b&sp=r&sig=VeLddkC1X1edLDaNL%2FHY13u5hHrf%2B5qJk6pvKjVsfDo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-18 12:18 UTC, opbld33 commented
Docs Build status updates of commit _[552c4bf](https://github.com/MicrosoftDocs/msteams-docs/commits/552c4bfad68f50b9dec56200c5a4aac0b9241ac3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |
[msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/glossary/msteams-platform/get-started/glossary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/get-started/glossary?branch=pr-en-us-5024) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C18%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202202181217288666-5024%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-21T12%3A18%3A32Z&sr=b&sp=r&sig=oLIvBQ3m0P%2FhShkifz5WIfonDxeJy0fqPlsdRhI1DCQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-18 12:19 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/552c4bfad68f50b9dec56200c5a4aac0b9241ac3/msteams-platform/TOC.yml) | 100 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/37ff2407-6321-4c34-b38e-9c2cac751393) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/552c4bfad68f50b9dec56200c5a4aac0b9241ac3/msteams-platform/get-started/glossary.md) | 95 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f08ec50e-623a-440e-84fc-aa743bd1b4e8) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-02-18 12:20 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/828a34eea7fb345b3a88f8346709c2965c4131a2/msteams-platform/TOC.yml) | 100 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fca55627-84b7-4bb3-9377-b7ad531696b8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/828a34eea7fb345b3a88f8346709c2965c4131a2/msteams-platform/get-started/glossary.md) | 95 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d74662a1-cfdc-4ecd-abcb-1d82f70a28cc) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-02-18 12:43 UTC, surbhigupta12 approved these changes
Approved

2022-02-18 12:43 UTC, merged