[Doc-update][Meeting-details-APIs-CART-API]
MicrosoftDocs/msteams-docs pull request #5076
Opened 2022-01-21 07:49 UTC by v-ypalikila

Added CART API

2022-01-21 07:50 UTC, opbld30 commented
Docs Build status updates of commit _[58b6d14](https://github.com/MicrosoftDocs/msteams-docs/commits/58b6d14ed14357b5ec02446bee34d86e9d81e2ac)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/API-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-update-meeting-apps-api-CART-api/msteams-platform/apps-in-teams-meetings/API-references.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/api-references?branch=pr-en-us-5076) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C21%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202201210749161186-5076%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-21T07%3A50%3A13Z&sr=b&sp=r&sig=zedXTWSnTdolUpCYRYHTBFg8zCTvxs%2FtLC3xHmX2KYE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-21 08:08 UTC, opbld33 commented
Docs Build status updates of commit _[43ef29e](https://github.com/MicrosoftDocs/msteams-docs/commits/43ef29edbdf275be14afef126e03fb1a6ac80b3c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/API-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-update-meeting-apps-api-CART-api/msteams-platform/apps-in-teams-meetings/API-references.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/api-references?branch=pr-en-us-5076) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C21%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202201210807476725-5076%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-21T08%3A08%3A52Z&sr=b&sp=r&sig=DibR4bnX11Wt%2F%2FrrQg7G0nZgmOFhIjvWM%2BWwfAYME5E%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-21 09:52 UTC, opbld32 commented
Docs Build status updates of commit _[747cd31](https://github.com/MicrosoftDocs/msteams-docs/commits/747cd3186b085a3e795d63a6b3696665ef7dc2d8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/API-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-update-meeting-apps-api-CART-api/msteams-platform/apps-in-teams-meetings/API-references.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/api-references?branch=pr-en-us-5076) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C21%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202201210951231078-5076%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-21T09%3A52%3A24Z&sr=b&sp=r&sig=d5banNMmIwvt5j%2FuSaAC7qElqpC8FWS5aj08Eaaz7HY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-21 10:14 UTC, opbld30 commented
Docs Build status updates of commit _[1ffc450](https://github.com/MicrosoftDocs/msteams-docs/commits/1ffc4502f70a524441e5516b39f43327d37b5672)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/API-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-update-meeting-apps-api-CART-api/msteams-platform/apps-in-teams-meetings/API-references.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/api-references?branch=pr-en-us-5076) |
[msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-update-meeting-apps-api-CART-api/msteams-platform/whats-new.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/whats-new?branch=pr-en-us-5076) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C21%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202201211013456079-5076%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-21T10%3A14%3A45Z&sr=b&sp=r&sig=M%2BmcjjbX8782zKf6jvsoEtXdvA1%2BJ8l7xy2iuHMjzNg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-21 10:27 UTC, opbld30 commented
Docs Build status updates of commit _[2a41cfe](https://github.com/MicrosoftDocs/msteams-docs/commits/2a41cfe4a0ccb4ce16a7801562d6343bd4d8e604)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/API-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-update-meeting-apps-api-CART-api/msteams-platform/apps-in-teams-meetings/API-references.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/api-references?branch=pr-en-us-5076) |
[msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-update-meeting-apps-api-CART-api/msteams-platform/whats-new.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/whats-new?branch=pr-en-us-5076) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C21%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202201211026151672-5076%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-21T10%3A27%3A19Z&sr=b&sp=r&sig=ohZFqWrvpliWzzSZBDKfrvbW%2BamM8zEvU8OMPuLXMLs%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-21 10:32 UTC, opbld32 commented
Docs Build status updates of commit _[73f18e7](https://github.com/MicrosoftDocs/msteams-docs/commits/73f18e7664d7d17100e6b8de58d22a7121465623)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/API-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-update-meeting-apps-api-CART-api/msteams-platform/apps-in-teams-meetings/API-references.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/api-references?branch=pr-en-us-5076) |
[msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-update-meeting-apps-api-CART-api/msteams-platform/whats-new.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/whats-new?branch=pr-en-us-5076) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C21%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202201211031039663-5076%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-21T10%3A32%3A10Z&sr=b&sp=r&sig=Zb4%2FSc9jGqKaQg1noJKso1eAYkiZIFSlN0cZsagebiY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-23 18:30 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/API-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a407a0add4319ea904cc62d8ee86390f08881340/msteams-platform/apps-in-teams-meetings/API-references.md) | 98 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f6357510-de37-4af9-8a58-298f9b4199dc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a407a0add4319ea904cc62d8ee86390f08881340/msteams-platform/whats-new.md) | 89 | 40 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/71a44770-12c9-4c3c-8c81-750dfa0eb954) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-01-23 18:30 UTC, opbld30 commented
Docs Build status updates of commit _[a407a0a](https://github.com/MicrosoftDocs/msteams-docs/commits/a407a0add4319ea904cc62d8ee86390f08881340)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/API-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-update-meeting-apps-api-CART-api/msteams-platform/apps-in-teams-meetings/API-references.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/api-references?branch=pr-en-us-5076) |
[msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-update-meeting-apps-api-CART-api/msteams-platform/whats-new.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/whats-new?branch=pr-en-us-5076) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C23%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202201231829580848-5076%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-23T18%3A30%3A57Z&sr=b&sp=r&sig=b5XzznLLaXrdTbdYMOMXBuRyMb1IeRdoy4CV4MyQooU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-24 17:12 UTC, lawrencecushman approved these changes
Approved pending suggestions

2022-01-24 17:12 UTC, lawrencecushman commented on msteams-platform/apps-in-teams-meetings/API-references.md
> +### Base URL
I'd change Base URL to CART URL here and in the paragraph, since Base URL refers to the common part of the URL

2022-01-24 17:12 UTC, lawrencecushman commented on msteams-platform/apps-in-teams-meetings/API-references.md
> +The communication access real-time translation (CART) API enables your app to expose a POST endpoint for Microsoft Teams CART captions.
This paragraph is a bit misleading. Applications can send captions to the CART API to send the captions directly to an ongoing Teams meeting. Let's change this to

```
The CART API exposes a POST endpoint for Microsoft Teams CART captions – human-typed closed captions. Text content sent to this endpoint will be displayed to end users in a Microsoft Teams meeting when they have captions enabled. 
```

2022-01-24 17:35 UTC, pandher1 requested changes
Please update the first paragraph as per Lawrence's comment

2022-01-24 20:28 UTC, csano commented on msteams-platform/apps-in-teams-meetings/API-references.md
> +You can get the Base URL for the POST endpoint from the **Meeting options** page in a Microsoft Teams meeting. For more information, see [CART captions in a Microsoft Teams meeting](https://support.m
Anywhere we have Base URL, should be changed to CART URL.

2022-01-25 04:46 UTC, opbld31 commented
Docs Build status updates of commit _[df382f6](https://github.com/MicrosoftDocs/msteams-docs/commits/df382f68af20c19f1f21476680bfcf0c1a9888e0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/API-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-update-meeting-apps-api-CART-api/msteams-platform/apps-in-teams-meetings/API-references.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/api-references?branch=pr-en-us-5076) |
[msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-update-meeting-apps-api-CART-api/msteams-platform/whats-new.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/whats-new?branch=pr-en-us-5076) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C25%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202201250445558281-5076%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-25T04%3A46%3A59Z&sr=b&sp=r&sig=beK9NP5WyHRKdUSoCJWBhun1c0Tr2oqlD41D1iHhP38%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-25 05:00 UTC, opbld32 commented
Docs Build status updates of commit _[6eb2d6b](https://github.com/MicrosoftDocs/msteams-docs/commits/6eb2d6bfcf9b006f3a94d32dba4b7a8999ffa7a2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/API-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-update-meeting-apps-api-CART-api/msteams-platform/apps-in-teams-meetings/API-references.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/api-references?branch=pr-en-us-5076) |
[msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-update-meeting-apps-api-CART-api/msteams-platform/whats-new.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/whats-new?branch=pr-en-us-5076) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C25%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202201250459381905-5076%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-25T05%3A00%3A31Z&sr=b&sp=r&sig=eNqD8PqKJdk7CBd9LgptNpDjkEXnwTdh9eZOSan1JvM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-25 07:14 UTC, opbld30 commented
Docs Build status updates of commit _[d77b856](https://github.com/MicrosoftDocs/msteams-docs/commits/d77b856aa14d9e9e2198b87d9356f63565708fd2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/API-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-update-meeting-apps-api-CART-api/msteams-platform/apps-in-teams-meetings/API-references.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/api-references?branch=pr-en-us-5076) |
[msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-update-meeting-apps-api-CART-api/msteams-platform/whats-new.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/whats-new?branch=pr-en-us-5076) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C25%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202201250713321362-5076%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-25T07%3A14%3A07Z&sr=b&sp=r&sig=c0%2FNyjgDT7nv9X8VtGsoZSqDLfvUTTLIv3jPc5Xpnqk%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-25 07:14 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/API-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d77b856aa14d9e9e2198b87d9356f63565708fd2/msteams-platform/apps-in-teams-meetings/API-references.md) | 98 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5df55ace-af28-4003-98d2-b017c8b5f8df) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d77b856aa14d9e9e2198b87d9356f63565708fd2/msteams-platform/whats-new.md) | 89 | 40 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7d7d82c9-2d2e-436c-9adb-f2dfb4c4c267) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-01-25 18:54 UTC, merged