[Doc improvement][Update app manifest schema]
MicrosoftDocs/msteams-docs pull request #5130
Opened 2022-02-01 12:48 UTC by v-abirade

2022-02-01 12:49 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b974af6782f91a0eeabd581f29043c104ccda8bf/msteams-platform/resources/schema/manifest-schema.md) | 93 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9a1b8290-3c4a-4658-b3b6-740ff8d86cde) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-02-01 12:57 UTC, opbld33 commented
Docs Build status updates of commit _[5ab7b51](https://github.com/MicrosoftDocs/msteams-docs/commits/5ab7b51e2e5d52673112c49afebdd8669fe5910d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-app-manifest-schema/msteams-platform/resources/schema/manifest-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema?branch=pr-en-us-5130) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C1%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202202011256452052-5130%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-04T12%3A57%3A21Z&sr=b&sp=r&sig=uN1e7s44KT6DgQYkr1zEhwAYr5VoCxf3lgiMhp9oiEE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-01 12:57 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5ab7b51e2e5d52673112c49afebdd8669fe5910d/msteams-platform/resources/schema/manifest-schema.md) | 93 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fecd0b46-2928-4207-9da6-f262dcd2394a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-02-01 13:11 UTC, opbld33 commented
Docs Build status updates of commit _[c507795](https://github.com/MicrosoftDocs/msteams-docs/commits/c507795d60371ce0863813ff8c21bdaef8bc27a0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-app-manifest-schema/msteams-platform/resources/schema/manifest-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema?branch=pr-en-us-5130) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C1%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202202011311153203-5130%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-04T13%3A11%3A52Z&sr=b&sp=r&sig=b%2FaBLcTqC7lw9e7HfzCppgX7C%2BUKl3ptC1FJ1t78XlY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-01 13:12 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c507795d60371ce0863813ff8c21bdaef8bc27a0/msteams-platform/resources/schema/manifest-schema.md) | 93 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5aa7a8ee-08b2-4bad-8ef1-335a52c75782) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-02-01 13:14 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/92964dc917238975b27a4f8fa29b5754998d5b4b/msteams-platform/resources/schema/manifest-schema.md) | 93 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/654c7468-7d50-4d8e-b409-1ecb272515f5) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-02-01 13:15 UTC, opbld30 commented
Docs Build status updates of commit _[92964dc](https://github.com/MicrosoftDocs/msteams-docs/commits/92964dc917238975b27a4f8fa29b5754998d5b4b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-app-manifest-schema/msteams-platform/resources/schema/manifest-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema?branch=pr-en-us-5130) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C1%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202202011314040523-5130%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-04T13%3A15%3A01Z&sr=b&sp=r&sig=LVN%2FZ2qw7yeIjvvMBHefb%2BSiTnTegAa9jbdwx8UnX0Q%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-01 14:57 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/016f8656d2b30e7b6e0b489815424a5aef4484d1/msteams-platform/resources/schema/manifest-schema.md) | 92 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/544e97dd-851b-4767-8c5f-8852c39e7bbc) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-02-01 14:57 UTC, opbld32 commented
Docs Build status updates of commit _[016f865](https://github.com/MicrosoftDocs/msteams-docs/commits/016f8656d2b30e7b6e0b489815424a5aef4484d1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-app-manifest-schema/msteams-platform/resources/schema/manifest-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema?branch=pr-en-us-5130) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C1%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202202011456543794-5130%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-04T14%3A57%3A56Z&sr=b&sp=r&sig=%2FaAXXkva8VnVfRev65zmFWBQyx0QO6OrkNYgNd6K5u0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-01 15:57 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5833c12cdf209c948e23dbb16fa90aba1c23660e/msteams-platform/resources/schema/manifest-schema.md) | 92 | 33 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1a802986-1716-40d3-a2be-e7d67808dba4) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-02-02 04:28 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2c71882e80dee31b36209d7046f5517d084063ce/msteams-platform/resources/schema/manifest-schema.md) | 93 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/961bfa58-1afa-4d67-9b7e-d9310e8d0265) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-02-02 04:29 UTC, opbld31 commented
Docs Build status updates of commit _[2c71882](https://github.com/MicrosoftDocs/msteams-docs/commits/2c71882e80dee31b36209d7046f5517d084063ce)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-app-manifest-schema/msteams-platform/resources/schema/manifest-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema?branch=pr-en-us-5130) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C2%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202202020428268726-5130%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-05T04%3A29%3A23Z&sr=b&sp=r&sig=%2BNdDVGxt9qYUpV4S6izi01fCFKNTMA2QH%2BZ%2B2dOPxBo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-02 05:22 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/387a05c741642c7879a2f9603cf92b3e3b5e27b8/msteams-platform/resources/schema/manifest-schema.md) | 93 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f9c8a28c-522a-44cb-845a-9fbeb555e69d) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-02-02 05:22 UTC, opbld30 commented
Docs Build status updates of commit _[387a05c](https://github.com/MicrosoftDocs/msteams-docs/commits/387a05c741642c7879a2f9603cf92b3e3b5e27b8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-app-manifest-schema/msteams-platform/resources/schema/manifest-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema?branch=pr-en-us-5130) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C2%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202202020521373537-5130%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-05T05%3A22%3A36Z&sr=b&sp=r&sig=tDW8Ef9t6x2aoq9C4l5n%2FaWawozwKrb7OYeCzeNshgc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-02 05:33 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/01a1b6fb121844a544ea51e09d9c7417cf97ca04/msteams-platform/resources/schema/manifest-schema.md) | 93 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/136c65bb-8677-4f7a-a6aa-cc54cfcee932) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-02-02 05:33 UTC, opbld32 commented
Docs Build status updates of commit _[01a1b6f](https://github.com/MicrosoftDocs/msteams-docs/commits/01a1b6fb121844a544ea51e09d9c7417cf97ca04)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-app-manifest-schema/msteams-platform/resources/schema/manifest-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema?branch=pr-en-us-5130) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C2%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202202020533047043-5130%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-05T05%3A33%3A58Z&sr=b&sp=r&sig=YmmjuM6gXzjx%2Fi%2B5GuGuCTYz0HyOaoBBa5qFBQ0TRWU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-02 07:19 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7db2d5cc9b692acdefd96352fd1313adffbabfdd/msteams-platform/resources/schema/manifest-schema.md) | 93 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/19a196e0-e18e-4682-9c36-b567e45e14d7) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-02-02 07:19 UTC, opbld30 commented
Docs Build status updates of commit _[7db2d5c](https://github.com/MicrosoftDocs/msteams-docs/commits/7db2d5cc9b692acdefd96352fd1313adffbabfdd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-app-manifest-schema/msteams-platform/resources/schema/manifest-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema?branch=pr-en-us-5130) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C2%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202202020718498913-5130%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-05T07%3A19%3A45Z&sr=b&sp=r&sig=BW%2B8nc2c4%2BIMB7WYdIbaPg46GCcAbVP%2FJEIYPzDTkfw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-02 08:04 UTC, opbld31 commented
Docs Build status updates of commit _[0b7a01b](https://github.com/MicrosoftDocs/msteams-docs/commits/0b7a01b2436d0beaf1f044bc38b35290acbc2ff9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-app-manifest-schema/msteams-platform/resources/schema/manifest-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema?branch=pr-en-us-5130) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C2%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202202020804095809-5130%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-05T08%3A04%3A48Z&sr=b&sp=r&sig=BIzE5WRTtz5htt5QOZtXa7erfzV6wfQxC%2FQzNrVfcOg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-02 08:04 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0b7a01b2436d0beaf1f044bc38b35290acbc2ff9/msteams-platform/resources/schema/manifest-schema.md) | 93 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f39b02ce-917c-47f1-b147-167743aaff40) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-02-02 08:31 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f0446e2ee26c4a0b5c8bb9a319ba32359fdb9b22/msteams-platform/resources/schema/manifest-schema.md) | 93 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/79477acf-d387-493b-aba1-ffc1c3a0a25f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-02-02 08:31 UTC, opbld31 commented
Docs Build status updates of commit _[f0446e2](https://github.com/MicrosoftDocs/msteams-docs/commits/f0446e2ee26c4a0b5c8bb9a319ba32359fdb9b22)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-app-manifest-schema/msteams-platform/resources/schema/manifest-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema?branch=pr-en-us-5130) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C2%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202202020830433640-5130%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-05T08%3A31%3A42Z&sr=b&sp=r&sig=mui0Ov0WOmacA%2Fm%2BRvCX85%2BlzVN%2FvpMD5iOORaHuhos%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-02 08:37 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4b43886d60deda551c7c38835a68d19bf4cd82a7/msteams-platform/resources/schema/manifest-schema.md) | 93 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/05d656ac-1200-4090-88e5-466d9720f1ca) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-02-02 08:38 UTC, opbld31 commented
Docs Build status updates of commit _[4b43886](https://github.com/MicrosoftDocs/msteams-docs/commits/4b43886d60deda551c7c38835a68d19bf4cd82a7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-app-manifest-schema/msteams-platform/resources/schema/manifest-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema?branch=pr-en-us-5130) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C2%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202202020837158588-5130%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-05T08%3A38%3A14Z&sr=b&sp=r&sig=K8j4qA%2BbcIMhXh20EKzM0h89mIBdJLab6TnknTG0i%2B0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-02 08:46 UTC, opbld31 commented
Docs Build status updates of commit _[3887097](https://github.com/MicrosoftDocs/msteams-docs/commits/38870974a0bed7d39cc9fe3a5ffafd00c3d9edf1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/resources/schema/manifest-schema-dev-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-app-manifest-schema/msteams-platform/resources/schema/manifest-schema-dev-preview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema-dev-preview?branch=pr-en-us-5130) |
[msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-app-manifest-schema/msteams-platform/resources/schema/manifest-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema?branch=pr-en-us-5130) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C2%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202202020845119924-5130%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-05T08%3A46%3A09Z&sr=b&sp=r&sig=j8D5x2ztiEEAHO8D%2FaQ1yEHdOZ%2F8IveFsEYYEK7UV5k%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-02 08:46 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/schema/manifest-schema-dev-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/38870974a0bed7d39cc9fe3a5ffafd00c3d9edf1/msteams-platform/resources/schema/manifest-schema-dev-preview.md) | 85 | 46 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/be344b82-8f3c-4a54-a35f-422802c71535) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/38870974a0bed7d39cc9fe3a5ffafd00c3d9edf1/msteams-platform/resources/schema/manifest-schema.md) | 93 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6fc68d4a-3134-4545-abdf-6d775a309726) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-02-02 09:02 UTC, opbld30 commented
Docs Build status updates of commit _[b1c5318](https://github.com/MicrosoftDocs/msteams-docs/commits/b1c5318ba75196f02b01a8c1270c04e89fcac3bd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/resources/schema/manifest-schema-dev-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-app-manifest-schema/msteams-platform/resources/schema/manifest-schema-dev-preview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema-dev-preview?branch=pr-en-us-5130) |
[msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-app-manifest-schema/msteams-platform/resources/schema/manifest-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema?branch=pr-en-us-5130) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C2%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202202020901371790-5130%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-05T09%3A02%3A34Z&sr=b&sp=r&sig=897U2uqoezzO3q6O9eE4ifgnRTY7ZufC3ctA9Gndit0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-02 09:02 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/schema/manifest-schema-dev-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c75fa361746676fd9387f289d30766a212a2c12d/msteams-platform/resources/schema/manifest-schema-dev-preview.md) | 85 | 46 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4ff0694c-1eaf-473b-9922-ba53195593d5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c75fa361746676fd9387f289d30766a212a2c12d/msteams-platform/resources/schema/manifest-schema.md) | 93 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c7754421-f313-4a37-9ee2-11e3939b04cf) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-02-02 09:03 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/schema/manifest-schema-dev-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c75fa361746676fd9387f289d30766a212a2c12d/msteams-platform/resources/schema/manifest-schema-dev-preview.md) | 85 | 46 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/63b9daeb-9ee1-473d-8ff6-7590e13ac12d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c75fa361746676fd9387f289d30766a212a2c12d/msteams-platform/resources/schema/manifest-schema.md) | 93 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aa91219b-5b25-4385-a44c-d185c6d7365b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-02-02 09:03 UTC, opbld31 commented
Docs Build status updates of commit _[c75fa36](https://github.com/MicrosoftDocs/msteams-docs/commits/c75fa361746676fd9387f289d30766a212a2c12d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/resources/schema/manifest-schema-dev-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-app-manifest-schema/msteams-platform/resources/schema/manifest-schema-dev-preview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema-dev-preview?branch=pr-en-us-5130) |
[msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-app-manifest-schema/msteams-platform/resources/schema/manifest-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema?branch=pr-en-us-5130) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C2%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202202020902093919-5130%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-05T09%3A03%3A44Z&sr=b&sp=r&sig=soo44MyJlgUv6ZCga8z94DxfyYMqvKXWLrBUuytxysM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-02 09:28 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/schema/manifest-schema-dev-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3e54eb59cdf7f42bb5425896ec4a6fe6ac575103/msteams-platform/resources/schema/manifest-schema-dev-preview.md) | 85 | 45 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/69da5294-c12c-426c-a2e5-9f1edc4d4861) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3e54eb59cdf7f42bb5425896ec4a6fe6ac575103/msteams-platform/resources/schema/manifest-schema.md) | 94 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bd2ef713-b4cd-43aa-b123-36346fc44ed1) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-02-02 09:28 UTC, opbld31 commented
Docs Build status updates of commit _[3e54eb5](https://github.com/MicrosoftDocs/msteams-docs/commits/3e54eb59cdf7f42bb5425896ec4a6fe6ac575103)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/resources/schema/manifest-schema-dev-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-app-manifest-schema/msteams-platform/resources/schema/manifest-schema-dev-preview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema-dev-preview?branch=pr-en-us-5130) |
[msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-app-manifest-schema/msteams-platform/resources/schema/manifest-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema?branch=pr-en-us-5130) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C2%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202202020927288053-5130%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-05T09%3A28%3A29Z&sr=b&sp=r&sig=ae%2ByUAcHXHwkWxmZeQZCSFFIQCpCNgAT7t6Xq0BxqbY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-02 09:43 UTC, opbld33 commented
Docs Build status updates of commit _[7553f86](https://github.com/MicrosoftDocs/msteams-docs/commits/7553f86d256c77e5db412d5d67ee1ff37402041a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-app-manifest-schema/msteams-platform/resources/schema/manifest-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema?branch=pr-en-us-5130) | [Details](#user-content-e6bfdece3996fe1b9cb1478f31495a5b-be417472)
[msteams-platform/resources/schema/manifest-schema-dev-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-app-manifest-schema/msteams-platform/resources/schema/manifest-schema-dev-preview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema-dev-preview?branch=pr-en-us-5130) |

<a id="e6bfdece3996fe1b9cb1478f31495a5b-be417472"></a>
### [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-app-manifest-schema/msteams-platform/resources/schema/manifest-schema.md)
 - **Line 804, Column 213**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#authorizationpermissionsdelegated' in 'resources/schema/manifest-schema.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C2%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202202020942587275-5130%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-05T09%3A43%3A55Z&sr=b&sp=r&sig=witDDn8ZQLKdNg7fkRDoxSXnOlhdpTx6K%2BjcXvMP7Zw%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-02 09:44 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/schema/manifest-schema-dev-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7553f86d256c77e5db412d5d67ee1ff37402041a/msteams-platform/resources/schema/manifest-schema-dev-preview.md) | 85 | 45 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/596a88f3-2c5e-47a0-a08f-83203dd70e7b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7553f86d256c77e5db412d5d67ee1ff37402041a/msteams-platform/resources/schema/manifest-schema.md) | 93 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/38a746be-7312-459e-8835-5b9a026d07ca) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-02-02 09:48 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/schema/manifest-schema-dev-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9ab04c0b4aff7dba9e26374a76226b31df357609/msteams-platform/resources/schema/manifest-schema-dev-preview.md) | 85 | 45 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/98893880-476c-4a34-a67f-821a342bf1a7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9ab04c0b4aff7dba9e26374a76226b31df357609/msteams-platform/resources/schema/manifest-schema.md) | 93 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7c5eb50c-73a9-4a46-b7ef-139c6d9dbc79) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-02-02 09:48 UTC, opbld31 commented
Docs Build status updates of commit _[9ab04c0](https://github.com/MicrosoftDocs/msteams-docs/commits/9ab04c0b4aff7dba9e26374a76226b31df357609)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-app-manifest-schema/msteams-platform/resources/schema/manifest-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema?branch=pr-en-us-5130) | [Details](#user-content-e6bfdece3996fe1b9cb1478f31495a5b-6047b327)
[msteams-platform/resources/schema/manifest-schema-dev-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-app-manifest-schema/msteams-platform/resources/schema/manifest-schema-dev-preview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema-dev-preview?branch=pr-en-us-5130) |

<a id="e6bfdece3996fe1b9cb1478f31495a5b-6047b327"></a>
### [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-app-manifest-schema/msteams-platform/resources/schema/manifest-schema.md)
 - **Line 804, Column 213**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#authorizationpermissionsdelegated' in 'resources/schema/manifest-schema.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C2%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202202020947330816-5130%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-05T09%3A48%3A26Z&sr=b&sp=r&sig=fdfykKgu5Dpf%2BQVhr4XwlpgYhmvpc16%2BhAWf5fc5lYY%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-02 09:55 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/schema/manifest-schema-dev-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8821ebeec2d344eb75b8ae4a5deaa2c5d186d841/msteams-platform/resources/schema/manifest-schema-dev-preview.md) | 85 | 45 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/040cc40e-42f5-43e3-81c4-6cc3effc19d2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8821ebeec2d344eb75b8ae4a5deaa2c5d186d841/msteams-platform/resources/schema/manifest-schema.md) | 93 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6ccab1d3-61d1-4f41-9f69-62b5d393b407) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-02-02 09:55 UTC, opbld30 commented
Docs Build status updates of commit _[8821ebe](https://github.com/MicrosoftDocs/msteams-docs/commits/8821ebeec2d344eb75b8ae4a5deaa2c5d186d841)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-app-manifest-schema/msteams-platform/resources/schema/manifest-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema?branch=pr-en-us-5130) | [Details](#user-content-e6bfdece3996fe1b9cb1478f31495a5b-609cf504)
[msteams-platform/resources/schema/manifest-schema-dev-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-app-manifest-schema/msteams-platform/resources/schema/manifest-schema-dev-preview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema-dev-preview?branch=pr-en-us-5130) |

<a id="e6bfdece3996fe1b9cb1478f31495a5b-609cf504"></a>
### [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-app-manifest-schema/msteams-platform/resources/schema/manifest-schema.md)
 - **Line 824, Column 193**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#authorizationpermissionsdelegated' in 'resources/schema/manifest-schema.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C2%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202202020954203342-5130%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-05T09%3A55%3A17Z&sr=b&sp=r&sig=QsqL4aN%2BlnXKa76jDCChhqiYynWo8Bq%2BwVHfVTwCkeI%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-02 10:04 UTC, Wajeed-msft requested changes

2022-02-02 10:19 UTC, v-abirade commented on msteams-platform/resources/schema/manifest-schema.md
> +|`name`|string|128 characters|✔|The name of the resource-specific permission. <br> For more details please refer [Application permission](../../graph-api/rsc/resource-specific-consent.md) and [Delega
Done

2022-02-02 10:22 UTC, v-abirade commented on msteams-platform/resources/schema/manifest-schema.md
> +Specify meeting extension definition.
Done

2022-02-02 10:33 UTC, v-abirade commented on msteams-platform/resources/schema/manifest-schema.md
> +    * `OutgoingVideoStream.Write.User`: Modify the users' outgoing video.
Done

2022-02-02 10:35 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/schema/manifest-schema-dev-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/60fa64aea87704982a9c307a576a01671eaf8082/msteams-platform/resources/schema/manifest-schema-dev-preview.md) | 88 | 38 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/db723160-6757-4927-ad61-698eb784d86b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/60fa64aea87704982a9c307a576a01671eaf8082/msteams-platform/resources/schema/manifest-schema.md) | 95 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bb5c438c-e266-4157-b351-c11eca5bc3a8) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-02-02 10:35 UTC, opbld31 commented
Docs Build status updates of commit _[60fa64a](https://github.com/MicrosoftDocs/msteams-docs/commits/60fa64aea87704982a9c307a576a01671eaf8082)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/resources/schema/manifest-schema-dev-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-app-manifest-schema/msteams-platform/resources/schema/manifest-schema-dev-preview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema-dev-preview?branch=pr-en-us-5130) |
[msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-app-manifest-schema/msteams-platform/resources/schema/manifest-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema?branch=pr-en-us-5130) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C2%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202202021034499971-5130%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-05T10%3A35%3A55Z&sr=b&sp=r&sig=zRM8lh7xlNkaI8WabcAj%2B%2BP1XQAiM5kiiX%2BVyaFslDg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-02 10:51 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/schema/manifest-schema-dev-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/488216f966432e2c5809f9f431a2f05595193c7f/msteams-platform/resources/schema/manifest-schema-dev-preview.md) | 88 | 38 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/af6c8cb4-ad03-434b-8548-384827c46df8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/488216f966432e2c5809f9f431a2f05595193c7f/msteams-platform/resources/schema/manifest-schema.md) | 95 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/26868b5b-fcf3-419c-b85b-58fc6e248ad1) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-02-02 10:52 UTC, opbld33 commented
Docs Build status updates of commit _[488216f](https://github.com/MicrosoftDocs/msteams-docs/commits/488216f966432e2c5809f9f431a2f05595193c7f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/resources/schema/manifest-schema-dev-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-app-manifest-schema/msteams-platform/resources/schema/manifest-schema-dev-preview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema-dev-preview?branch=pr-en-us-5130) |
[msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-app-manifest-schema/msteams-platform/resources/schema/manifest-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema?branch=pr-en-us-5130) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C2%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202202021051050361-5130%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-05T10%3A52%3A06Z&sr=b&sp=r&sig=u6yuVata%2Bh426410qkugsK2YL%2FFvgzoYPjW2M9AGbgo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-02 10:58 UTC, opbld31 commented
Docs Build status updates of commit _[be56777](https://github.com/MicrosoftDocs/msteams-docs/commits/be56777cf2b6c75171f89f7467f5475b47dd9563)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/resources/schema/manifest-schema-dev-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-app-manifest-schema/msteams-platform/resources/schema/manifest-schema-dev-preview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema-dev-preview?branch=pr-en-us-5130) |
[msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-app-manifest-schema/msteams-platform/resources/schema/manifest-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema?branch=pr-en-us-5130) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C2%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202202021057379874-5130%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-05T10%3A58%3A37Z&sr=b&sp=r&sig=Unw1kofycP0QpmkYebedUZNdj3m%2BcTB7fnZSXfSU%2BmY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-02 10:58 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/schema/manifest-schema-dev-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/be56777cf2b6c75171f89f7467f5475b47dd9563/msteams-platform/resources/schema/manifest-schema-dev-preview.md) | 88 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c39de6ed-a7d1-42bd-8da1-08f00433d32b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/be56777cf2b6c75171f89f7467f5475b47dd9563/msteams-platform/resources/schema/manifest-schema.md) | 95 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/de3095b6-5130-4c3b-b17c-fb3123bed5d4) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-02-02 11:02 UTC, opbld33 commented
Docs Build status updates of commit _[50de241](https://github.com/MicrosoftDocs/msteams-docs/commits/50de2417310de3a3c0947b6c9a70d6869b480646)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/resources/schema/manifest-schema-dev-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-app-manifest-schema/msteams-platform/resources/schema/manifest-schema-dev-preview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema-dev-preview?branch=pr-en-us-5130) |
[msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-app-manifest-schema/msteams-platform/resources/schema/manifest-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema?branch=pr-en-us-5130) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C2%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202202021101465685-5130%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-05T11%3A02%3A23Z&sr=b&sp=r&sig=DkDsO7SaRiG5xLOY6NWKivCxgetNoYgxPIzbAPK6sZA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-02 11:02 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/schema/manifest-schema-dev-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/50de2417310de3a3c0947b6c9a70d6869b480646/msteams-platform/resources/schema/manifest-schema-dev-preview.md) | 88 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e775a5e0-f6f8-4402-8c65-935a542770e4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/50de2417310de3a3c0947b6c9a70d6869b480646/msteams-platform/resources/schema/manifest-schema.md) | 95 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8b795432-00f6-4c76-a72a-e48206ef1814) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-02-02 11:03 UTC, opbld31 commented
Docs Build status updates of commit _[5ecd099](https://github.com/MicrosoftDocs/msteams-docs/commits/5ecd0993bc41783515be330d127708895cd248bc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/resources/schema/manifest-schema-dev-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-app-manifest-schema/msteams-platform/resources/schema/manifest-schema-dev-preview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema-dev-preview?branch=pr-en-us-5130) |
[msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-app-manifest-schema/msteams-platform/resources/schema/manifest-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema?branch=pr-en-us-5130) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C2%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202202021103085631-5130%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-05T11%3A03%3A44Z&sr=b&sp=r&sig=Lji2MrkjX0G2R0vqLbfUuJhP5vxmbgo7K20udXHng0Q%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-02 11:03 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/schema/manifest-schema-dev-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5ecd0993bc41783515be330d127708895cd248bc/msteams-platform/resources/schema/manifest-schema-dev-preview.md) | 88 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aa309ac0-249f-43a6-988d-0baf43064564) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5ecd0993bc41783515be330d127708895cd248bc/msteams-platform/resources/schema/manifest-schema.md) | 95 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e15196ac-e0d2-4d70-9d53-ab75671a2a31) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-02-02 11:07 UTC, opbld31 commented
Docs Build status updates of commit _[2d02f7e](https://github.com/MicrosoftDocs/msteams-docs/commits/2d02f7ef01503b5527a05db57bf223a2462d179a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/resources/schema/manifest-schema-dev-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-app-manifest-schema/msteams-platform/resources/schema/manifest-schema-dev-preview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema-dev-preview?branch=pr-en-us-5130) |
[msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-app-manifest-schema/msteams-platform/resources/schema/manifest-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema?branch=pr-en-us-5130) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C2%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202202021106475799-5130%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-05T11%3A07%3A22Z&sr=b&sp=r&sig=oWFAV9%2F%2BEv0B%2FXM0qOkrBzc8gXMrC0%2BIGx%2B27MB2dFM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-02 11:07 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/schema/manifest-schema-dev-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2d02f7ef01503b5527a05db57bf223a2462d179a/msteams-platform/resources/schema/manifest-schema-dev-preview.md) | 88 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2103470f-b029-45ab-9a4b-c84ffb777b71) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2d02f7ef01503b5527a05db57bf223a2462d179a/msteams-platform/resources/schema/manifest-schema.md) | 95 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5b021e8b-5fca-44a4-9352-9dc40d7b9153) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-02-02 11:23 UTC, Wajeed-msft approved these changes

2022-02-03 12:14 UTC, opbld33 commented
Docs Build status updates of commit _[61c3a0b](https://github.com/MicrosoftDocs/msteams-docs/commits/61c3a0b853cdd86f8a9393da3dca4e073c3afd20)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/resources/schema/manifest-schema-dev-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-app-manifest-schema/msteams-platform/resources/schema/manifest-schema-dev-preview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema-dev-preview?branch=pr-en-us-5130) |
[msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-app-manifest-schema/msteams-platform/resources/schema/manifest-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema?branch=pr-en-us-5130) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C3%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202202031213138474-5130%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-06T12%3A14%3A19Z&sr=b&sp=r&sig=3ZIbREHAuChWG7yxvPQ4g8WRSlZ7X1DXcr3oo%2BKZy10%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-03 12:22 UTC, AkJo commented on msteams-platform/resources/schema/manifest-schema.md
> +    |`OutgoingVideoStream.Write.User`|Modify the users' outgoing video.|
Please remove this permission.

2022-02-03 12:22 UTC, AkJo commented on msteams-platform/resources/schema/manifest-schema.md
> +    |`CameraStream.Read.User`|Read the users' camera stream.|
Please remove this permission.

2022-02-03 12:23 UTC, AkJo commented on msteams-platform/resources/schema/manifest-schema.md
> +
Please add a line.

Delegated permissions allow the app to access data on behalf of the signed-in user.

2022-02-03 12:24 UTC, AkJo commented on msteams-platform/resources/schema/manifest-schema.md
> +    |**Delegated permission**|**Action**|
Name

2022-02-03 12:25 UTC, AkJo commented on msteams-platform/resources/schema/manifest-schema.md
> +    |**Delegated permission**|**Action**|
Description

2022-02-03 12:25 UTC, AkJo commented on msteams-platform/resources/schema/manifest-schema.md
> +    |**Delegated permission**|**Action**|
Name

2022-02-03 12:25 UTC, AkJo commented on msteams-platform/resources/schema/manifest-schema.md
> +    |**Delegated permission**|**Action**|
Description

2022-02-03 12:27 UTC, AkJo commented on msteams-platform/resources/schema/manifest-schema.md
> +    |**Delegated permission**|**Action**|
For the permission descriptions, please lift and shift from the following table:

<html>
<body>
<!--StartFragment--><div ccp_infra_version='3' ccp_infra_timestamp='1643891171411' ccp_infra_user_hash='3504234856' ccp_infra_copy_id='566c28cc-e345-45df-8f7d-8d9219216403' data-ccp-timestamp='1643891171411'><html>

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<style>
table
	{mso-displayed-decimal-separator:"\.";
	mso-displayed-thousand-separator:"\,";}
tr
	{mso-height-source:auto;}
col
	{mso-width-source:auto;}
td
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Calibri, sans-serif;
	mso-font-charset:0;
	text-align:general;
	vertical-align:bottom;
	border:none;
	white-space:nowrap;
	mso-rotate:0;}
.xl39
	{white-space:normal;}
.xl40
	{color:black;
	white-space:normal;}
.xl142
	{background:yellow;
	mso-pattern:black none;
	white-space:normal;}
</style>
</head>

<body link="#0563C1" vlink="#954F72">



OnlineMeetingParticipant.ToggleIncomingAudio.Chat | Toggle incoming audio for participants in meetings associated with this chat | Allows the app to toggle incoming audio for participants in meetings associated with this chat, on behalf of the signed-in user.
-- | -- | --
CameraStream.Read.User | Read the user's camera stream | Allows the app to read the user's camera stream, on behalf of the signed-in user.
OutgoingVideoStream.Write.User | Modify the user's outgoing video | Allows the app to modify the user's outgoing video, on behalf of the signed-in user.
InAppPurchase.Allow.User | Show and complete in-app purchases | Allow the app to show the user marketplace offers and complete the user's purchases within the app, on behalf of the signed-in user.
MeetingStage.Write.Chat | Show content on the meeting stage of meetings associated with this chat | Allows the app to show content on the meeting stage in meetings associated with this chat, on behalf of the signed-in user.
OnlineMeetingParticipant.Read.Chat | Read participant information, including name, role, id, joined and left times, of meetings associated with this chat | Allows the app to read participant information, including name, role, id, joined and left times, of meeting associated with this chat, on behalf of the signed-in user.
ChannelMeetingParticipant.Read.Group | Read participant information, including name, role, id, joined and left times, of channel meetings associated with this team | Allows the app to read participant information, including name, role, id, joined and left times, of channel meetings associated with this team, on behalf of the signed-in user.
ChannelMeetingStage.Write.Group | Show content on the meeting stage of channel meetings associated with this team | Allows the app to show content on the meeting stage in channel meetings associated with this team, on behalf of the signed-in user.
InAppPurchase.Allow.Group | Show and complete in-app purchases for users in this team | Allow the app to show marketplace offers to users in this team and complete their purchases within the app, on behalf of the signed-in user.
InAppPurchase.Allow.Chat | Show and complete in-app purchases for users in this chat and any associated meeting | Allow the app to show marketplace offers to the users in this chat, and any associated meeting, and complete their purchases within the app, on behalf of the signed-in user.



</body>

</html>
</div><!--EndFragment-->
</body>
</html>

2022-02-03 12:29 UTC, AkJo reviewed
Called out corrections.

2022-02-03 16:35 UTC, opbld30 commented
Docs Build status updates of commit _[289712a](https://github.com/MicrosoftDocs/msteams-docs/commits/289712a6a525569245b5c208523fb40abd94b1c4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/resources/schema/manifest-schema-dev-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-app-manifest-schema/msteams-platform/resources/schema/manifest-schema-dev-preview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema-dev-preview?branch=pr-en-us-5130) |
[msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-app-manifest-schema/msteams-platform/resources/schema/manifest-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema?branch=pr-en-us-5130) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C3%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202202031634437203-5130%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-06T16%3A35%3A44Z&sr=b&sp=r&sig=79KqS8p2vjYXrsYdPyeaAouDZCSVSeQ2F9y1go8VBOg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-03 16:37 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/schema/manifest-schema-dev-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/289712a6a525569245b5c208523fb40abd94b1c4/msteams-platform/resources/schema/manifest-schema-dev-preview.md) | 84 | 51 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/88935e46-d6f2-4dd7-947e-cce4c4f45f8e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/289712a6a525569245b5c208523fb40abd94b1c4/msteams-platform/resources/schema/manifest-schema.md) | 94 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d14f1fc9-7c4f-4c45-a09f-b93baca503bf) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-02-03 17:19 UTC, opbld30 commented
Docs Build status updates of commit _[2ef733b](https://github.com/MicrosoftDocs/msteams-docs/commits/2ef733b3db2de133ffb6e79ce446c303adf5e308)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/resources/schema/manifest-schema-dev-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-app-manifest-schema/msteams-platform/resources/schema/manifest-schema-dev-preview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema-dev-preview?branch=pr-en-us-5130) |
[msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-app-manifest-schema/msteams-platform/resources/schema/manifest-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema?branch=pr-en-us-5130) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C3%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202202031718356799-5130%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-06T17%3A19%3A35Z&sr=b&sp=r&sig=lQo36ULvMRCRPOzxoDUWbvuk1h9I4cv1lObw4dCylGg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-03 17:21 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/schema/manifest-schema-dev-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0cfaa6700e7af61508469675af6d90066c60c95b/msteams-platform/resources/schema/manifest-schema-dev-preview.md) | 84 | 51 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f52d5de1-fd74-462b-bea3-3a1c766c58ac) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0cfaa6700e7af61508469675af6d90066c60c95b/msteams-platform/resources/schema/manifest-schema.md) | 92 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3317ca09-eece-4ec4-9d22-19f09bf7cd41) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-02-03 17:22 UTC, opbld32 commented
Docs Build status updates of commit _[0cfaa67](https://github.com/MicrosoftDocs/msteams-docs/commits/0cfaa6700e7af61508469675af6d90066c60c95b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/resources/schema/manifest-schema-dev-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-app-manifest-schema/msteams-platform/resources/schema/manifest-schema-dev-preview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema-dev-preview?branch=pr-en-us-5130) |
[msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-app-manifest-schema/msteams-platform/resources/schema/manifest-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema?branch=pr-en-us-5130) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C3%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202202031720536561-5130%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-06T17%3A21%3A59Z&sr=b&sp=r&sig=oEnqY06GmfR5ZOdEGJ7e%2FD%2FDtu8nj6sWLtfpQv015vI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-03 17:24 UTC, merged