Update feedback.md
MicrosoftDocs/msteams-docs pull request #5151
Opened 2022-02-03 11:24 UTC by Wajeed-msft

2022-02-03 11:25 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5e968d1eb961fb32afe36228facf2ecadadad56d/msteams-platform/feedback.md) | 89 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c5067c6e-ea20-4fb2-8227-07888250451a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-02-03 11:25 UTC, opbld30 commented
Docs Build status updates of commit _[5e968d1](https://github.com/MicrosoftDocs/msteams-docs/commits/5e968d1eb961fb32afe36228facf2ecadadad56d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Wajeed-msft-support-page/msteams-platform/feedback.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/feedback?branch=pr-en-us-5151) | [Details](#user-content-3c08073bd5fb191858653873dd0c7a47-e387ab31)

<a id="3c08073bd5fb191858653873dd0c7a47-e387ab31"></a>
### [msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Wajeed-msft-support-page/msteams-platform/feedback.md)
 - **Line 0, Column 0**: **[Warning: h1-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/h1-missing?branch=main)]** `````H1 is required. Use a single hash (#) followed by a space to create your top-level heading.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C3%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202202031124374721-5151%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-06T11%3A25%3A28Z&sr=b&sp=r&sig=eVzTLi9vN7mXDmuPmiv1TtLOyjVuwCCZL6NF7LzexTM%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-03 17:54 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b9739f7a6a7799ff7fb7997ff1707f707263e4c2/msteams-platform/feedback.md) | 89 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5f166228-0331-4288-ab85-80394984f618) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-02-03 17:54 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b9739f7a6a7799ff7fb7997ff1707f707263e4c2/msteams-platform/feedback.md) | 89 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6d90ce49-ec33-46a0-8810-287e6a840383) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-02-03 17:54 UTC, opbld32 commented
Docs Build status updates of commit _[b9739f7](https://github.com/MicrosoftDocs/msteams-docs/commits/b9739f7a6a7799ff7fb7997ff1707f707263e4c2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Wajeed-msft-support-page/msteams-platform/feedback.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/feedback?branch=pr-en-us-5151) | [Details](#user-content-3c08073bd5fb191858653873dd0c7a47-f0f4691b)

<a id="3c08073bd5fb191858653873dd0c7a47-f0f4691b"></a>
### [msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Wajeed-msft-support-page/msteams-platform/feedback.md)
 - **Line 0, Column 0**: **[Warning: h1-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/h1-missing?branch=main)]** `````H1 is required. Use a single hash (#) followed by a space to create your top-level heading.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C3%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202202031753508165-5151%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-06T17%3A54%3A57Z&sr=b&sp=r&sig=g7h3PiEBXHV1b2%2F3hnkO8IoFQH3BFrYn5BQHXvA8AOQ%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-03 17:56 UTC, opbld31 commented
Docs Build status updates of commit _[b9739f7](https://github.com/MicrosoftDocs/msteams-docs/commits/b9739f7a6a7799ff7fb7997ff1707f707263e4c2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Wajeed-msft-support-page/msteams-platform/feedback.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/feedback?branch=pr-en-us-5151) | [Details](#user-content-3c08073bd5fb191858653873dd0c7a47-e38a8580)

<a id="3c08073bd5fb191858653873dd0c7a47-e38a8580"></a>
### [msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Wajeed-msft-support-page/msteams-platform/feedback.md)
 - **Line 0, Column 0**: **[Warning: h1-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/h1-missing?branch=main)]** `````H1 is required. Use a single hash (#) followed by a space to create your top-level heading.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C3%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202202031754010377-5151%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-06T17%3A56%3A03Z&sr=b&sp=r&sig=PNsz2UrC6u%2FPfCUi9IlPUED2zDXS0V4Xl5vaM6BX%2BA0%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-03 18:26 UTC, opbld31 commented
Docs Build status updates of commit _[2709355](https://github.com/MicrosoftDocs/msteams-docs/commits/2709355e8c978e24721edcdcbbb060ce0c3012bf)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Wajeed-msft-support-page/msteams-platform/feedback.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/feedback?branch=pr-en-us-5151) | [Details](#user-content-3c08073bd5fb191858653873dd0c7a47-b26f7d41)
[msteams-platform/assets/icons/community-doc-updates.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Wajeed-msft-support-page/msteams-platform/assets/icons/community-doc-updates.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/feedback?branch=pr-en-us-5151) |
[msteams-platform/assets/icons/community-feature-ask.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Wajeed-msft-support-page/msteams-platform/assets/icons/community-feature-ask.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/feedback?branch=pr-en-us-5151) |
[msteams-platform/assets/icons/community-forums.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Wajeed-msft-support-page/msteams-platform/assets/icons/community-forums.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/feedback?branch=pr-en-us-5151) |
[msteams-platform/assets/icons/community-help.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Wajeed-msft-support-page/msteams-platform/assets/icons/community-help.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/feedback?branch=pr-en-us-5151) |
[msteams-platform/assets/icons/community-issues.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Wajeed-msft-support-page/msteams-platform/assets/icons/community-issues.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/feedback?branch=pr-en-us-5151) |
[msteams-platform/assets/icons/developer-support.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Wajeed-msft-support-page/msteams-platform/assets/icons/developer-support.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/feedback?branch=pr-en-us-5151) |

<a id="3c08073bd5fb191858653873dd0c7a47-b26f7d41"></a>
### [msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Wajeed-msft-support-page/msteams-platform/feedback.md)
 - **Line 0, Column 0**: **[Warning: h1-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/h1-missing?branch=main)]** `````H1 is required. Use a single hash (#) followed by a space to create your top-level heading.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C3%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202202031825048620-5151%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-06T18%3A26%3A17Z&sr=b&sp=r&sig=JlZ4IB1jMfVYBJB3SzT6NxjS%2B8OYDn86wZ%2FQvVApKxs%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-03 18:27 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2709355e8c978e24721edcdcbbb060ce0c3012bf/msteams-platform/feedback.md) | 89 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b3c75611-7f44-4967-b671-93f56e86280f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-02-03 18:41 UTC, opbld31 commented
Docs Build status updates of commit _[c65c2f3](https://github.com/MicrosoftDocs/msteams-docs/commits/c65c2f3a91f4153488c71e619376eeacbf1d00ad)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/icons/azure.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Wajeed-msft-support-page/msteams-platform/assets/icons/azure.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/feedback?branch=pr-en-us-5151) |
[msteams-platform/assets/icons/community-doc-updates.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Wajeed-msft-support-page/msteams-platform/assets/icons/community-doc-updates.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/feedback?branch=pr-en-us-5151) |
[msteams-platform/assets/icons/community-feature-ask.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Wajeed-msft-support-page/msteams-platform/assets/icons/community-feature-ask.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/feedback?branch=pr-en-us-5151) |
[msteams-platform/assets/icons/community-forums.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Wajeed-msft-support-page/msteams-platform/assets/icons/community-forums.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/feedback?branch=pr-en-us-5151) |
[msteams-platform/assets/icons/community-help.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Wajeed-msft-support-page/msteams-platform/assets/icons/community-help.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/feedback?branch=pr-en-us-5151) |
[msteams-platform/assets/icons/community-issues.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Wajeed-msft-support-page/msteams-platform/assets/icons/community-issues.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/feedback?branch=pr-en-us-5151) |
[msteams-platform/assets/icons/developer-support.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Wajeed-msft-support-page/msteams-platform/assets/icons/developer-support.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/feedback?branch=pr-en-us-5151) |
[msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Wajeed-msft-support-page/msteams-platform/feedback.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/feedback?branch=pr-en-us-5151) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C3%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202202031839396125-5151%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-06T18%3A41%3A04Z&sr=b&sp=r&sig=cBIbd3gNyNYBruz4EWfQeR98%2F%2B%2BBLCEzn5odnX3dtgw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-03 18:42 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c65c2f3a91f4153488c71e619376eeacbf1d00ad/msteams-platform/feedback.md) | 89 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b01a84f5-5b44-4a1e-9e68-edc96cb01129) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-02-04 05:34 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0d5ef99a4fcad63da778f262765476bdc1436255/msteams-platform/feedback.md) | 89 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b244487a-2eae-4d25-9b14-40881b94e670) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-02-04 05:35 UTC, opbld33 commented
Docs Build status updates of commit _[0d5ef99](https://github.com/MicrosoftDocs/msteams-docs/commits/0d5ef99a4fcad63da778f262765476bdc1436255)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/icons/azure.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Wajeed-msft-support-page/msteams-platform/assets/icons/azure.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/feedback?branch=pr-en-us-5151) |
[msteams-platform/assets/icons/community-doc-updates.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Wajeed-msft-support-page/msteams-platform/assets/icons/community-doc-updates.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/feedback?branch=pr-en-us-5151) |
[msteams-platform/assets/icons/community-feature-ask.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Wajeed-msft-support-page/msteams-platform/assets/icons/community-feature-ask.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/feedback?branch=pr-en-us-5151) |
[msteams-platform/assets/icons/community-forums.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Wajeed-msft-support-page/msteams-platform/assets/icons/community-forums.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/feedback?branch=pr-en-us-5151) |
[msteams-platform/assets/icons/community-help.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Wajeed-msft-support-page/msteams-platform/assets/icons/community-help.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/feedback?branch=pr-en-us-5151) |
[msteams-platform/assets/icons/community-issues.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Wajeed-msft-support-page/msteams-platform/assets/icons/community-issues.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/feedback?branch=pr-en-us-5151) |
[msteams-platform/assets/icons/developer-support.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Wajeed-msft-support-page/msteams-platform/assets/icons/developer-support.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/feedback?branch=pr-en-us-5151) |
[msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Wajeed-msft-support-page/msteams-platform/feedback.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/feedback?branch=pr-en-us-5151) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C4%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202202040534108232-5151%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-07T05%3A35%3A06Z&sr=b&sp=r&sig=F2zp8tHAO1QxM3%2FP50A%2BiCThldKkou39nTw9kN%2Bj%2F8c%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-04 05:37 UTC, opbld32 commented
Docs Build status updates of commit _[b6ec0dc](https://github.com/MicrosoftDocs/msteams-docs/commits/b6ec0dcf3dc39ce7f6d2b55a60b79ca65ca3dac2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Wajeed-msft-support-page/msteams-platform/feedback.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/feedback?branch=pr-en-us-5151) | [Details](#user-content-3c08073bd5fb191858653873dd0c7a47-d0cd7c71)
[msteams-platform/assets/icons/azure.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Wajeed-msft-support-page/msteams-platform/assets/icons/azure.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/feedback?branch=pr-en-us-5151) |

<a id="3c08073bd5fb191858653873dd0c7a47-d0cd7c71"></a>
### [msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Wajeed-msft-support-page/msteams-platform/feedback.md)
 - **Line 11, Column 4**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'assets/icons/developer-support.png'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C4%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202202040536239899-5151%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-07T05%3A36%3A59Z&sr=b&sp=r&sig=TP3TiEoM6q4qelNf%2B%2FwuDTec82ilOdOOudFhTco4etM%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-04 05:37 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b6ec0dcf3dc39ce7f6d2b55a60b79ca65ca3dac2/msteams-platform/feedback.md) | 89 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4ccf154e-1fcd-43f4-a62b-895b2e62f499) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-02-04 05:52 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f8cd78216227f99a945d834645b88915874aa460/msteams-platform/feedback.md) | 89 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d699ac56-0f3b-4dc0-ab32-f08089effc89) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-02-04 05:53 UTC, opbld33 commented
Docs Build status updates of commit _[f8cd782](https://github.com/MicrosoftDocs/msteams-docs/commits/f8cd78216227f99a945d834645b88915874aa460)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Wajeed-msft-support-page/msteams-platform/feedback.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/feedback?branch=pr-en-us-5151) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C4%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202202040552190320-5151%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-07T05%3A53%3A18Z&sr=b&sp=r&sig=jSGKr6mNBYDzfGFBr23ay12qCYAsGcrtbpDeKuwxHho%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-04 10:25 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d5405dd2f96db7ae3f8a1f9292f9dd7b27829631/msteams-platform/feedback.md) | 89 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aa54e13f-1392-4685-aa17-9c63ac555224) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-02-04 10:26 UTC, opbld31 commented
Docs Build status updates of commit _[d5405dd](https://github.com/MicrosoftDocs/msteams-docs/commits/d5405dd2f96db7ae3f8a1f9292f9dd7b27829631)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Wajeed-msft-support-page/msteams-platform/feedback.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/feedback?branch=pr-en-us-5151) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C4%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202202041025299325-5151%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-07T10%3A26%3A27Z&sr=b&sp=r&sig=Qm7AtdMxwP0q%2FoSlfDlHAWPSua8lcoKWkyUUsy8OWic%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-04 10:42 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fa8b8a0e1f9c6e82dd88063ffd52b516cd1e9ca3/msteams-platform/feedback.md) | 89 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/da335f67-3d3a-4a61-8b16-20f3c3612f52) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-02-04 10:42 UTC, opbld33 commented
Docs Build status updates of commit _[fa8b8a0](https://github.com/MicrosoftDocs/msteams-docs/commits/fa8b8a0e1f9c6e82dd88063ffd52b516cd1e9ca3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Wajeed-msft-support-page/msteams-platform/feedback.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/feedback?branch=pr-en-us-5151) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C4%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202202041042079530-5151%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-07T10%3A42%3A44Z&sr=b&sp=r&sig=Bf%2B1sfHqRXXt3k2WEGXhzJSbmt0mTjtA%2Bo8w2VfkFWI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-04 10:46 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/506b45271b26c0029fb3097d1ca4493e4877a022/msteams-platform/feedback.md) | 89 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f36f9e4e-4e66-4d01-8b6c-006949d27c9a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-02-04 10:46 UTC, opbld32 commented
Docs Build status updates of commit _[506b452](https://github.com/MicrosoftDocs/msteams-docs/commits/506b45271b26c0029fb3097d1ca4493e4877a022)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Wajeed-msft-support-page/msteams-platform/feedback.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/feedback?branch=pr-en-us-5151) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C4%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202202041045596001-5151%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-07T10%3A46%3A56Z&sr=b&sp=r&sig=1IejJmcSpjnV1%2Bp6gSxjC3EccxmydtArDRrxIz3dP%2B4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-04 17:58 UTC, Wajeed-msft commented
@surbhigupta12, @ashishguptaiitb - could you please help to review this?

2022-02-09 06:41 UTC, surbhigupta12 requested changes
Reviewed, please verify

2022-02-09 06:41 UTC, surbhigupta12 commented on msteams-platform/feedback.md
> +Please use **Azure Admin Center** or **Microsoft 365 Admin Center** for any **business-critical issues** which need SLA based support.
```suggestion
Use **Azure Admin Center** or **Microsoft 365 Admin Center** for any **business-critical issues** that need SLA-based support.
``

2022-02-09 06:41 UTC, surbhigupta12 commented on msteams-platform/feedback.md
> +| **General questions about Microsoft Teams** | Submit your questions on :::image type="icon" source="assets/icons/microsoft-icon.png" border="false"::: [Microsoft Teams Community](https://answers.mi
```suggestion
| **Microsoft Teams product issues and failures** | If you have a Premier support contract for :::image type="icon" source="assets/icons/microsoft-icon.png" border="false"::: Microsoft 365, visit the Microsoft 365 Admin Center and use the Support menu to [open a service request ](https://admin.microsoft.com/). |
| **Azure help and support** | If you have a paid Azure subscription, visit the Azure Admin Center to [open a ticket](https://ms.portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade/newsupportreq). |
| **General questions about Microsoft Teams** | If you have general questions on Microsoft Teams, submit your questions on :::image type="icon" source="assets/icons/microsoft-icon.png" border="false"::: [Microsoft Teams Community](https://answers.microsoft.com/en-us/msteams/forum).|
```

2022-02-09 06:41 UTC, surbhigupta12 commented on msteams-platform/feedback.md
> +Microsoft Teams community of developers use Stack Overflow and Microsoft Q&A to connect with other developers to ideate, get clarifications, and submit queries. In addition, developers can also use o
```suggestion
Microsoft Teams community of developers use Stack Overflow and Microsoft Q&A to connect with other developers to ideate, get clarifications, and submit queries. In addition, developers can also use other contacts or sites, depending on the type of community help required to raise issues, limitations, and general questions.
```

2022-02-09 06:41 UTC, surbhigupta12 commented on msteams-platform/feedback.md
> +Post your questions and help other community members by sharing and responding to questions related to  Microsoft Teams App Development.
```suggestion
Post your questions and help other community members by sharing and responding to Microsoft Teams App Development questions.
```

2022-02-09 06:41 UTC, surbhigupta12 commented on msteams-platform/feedback.md
> +|**Community help** | <ul> <li>:::image type="icon" source="assets/icons/stack-overflow-icon.png" border="false"::: [Stack Overflow](https://stackoverflow.com/questions/tagged/microsoft-teams): Use t
```suggestion
|**Community help** | <ul> <li>:::image type="icon" source="assets/icons/stack-overflow-icon.png" border="false"::: [Stack Overflow](https://stackoverflow.com/questions/tagged/microsoft-teams): Use the `microsoft-teams` tag to post questions. Follow the Stack Overflow guidelines, such as providing a descriptive title, a concise problem statement, and details to reproduce the issue. Feature requests or broad questions are off-topic. If you are a new user, see [Stack Overflow Help Center](https://stackoverflow.com/help).</li>  <li>:::image type="icon" source="assets/icons/microsoft-icon.png" border="false"::: [Microsoft Q&A](/answers/topics/office-teams-app-dev.html): We love Stack Overflow and provide extensive support to questions posted on Stack Overflow. Use the `office-teams-app-dev` tag to post questions. Stack Overflow has criteria about appropriate questions and [Microsoft Q&A](/answers/topics/office-teams-app-dev.html) has an open policy regarding this. </li><ul> |
```

2022-02-09 06:41 UTC, surbhigupta12 commented on msteams-platform/feedback.md
> +| **General questions** | Send general questions about the Microsoft Teams developer platform to [Microsoft Teams Community Help](mailto:microsoftteamsdev@microsoft.com). We encourage posting questio
```suggestion
| **General questions** | Send general questions about the Microsoft Teams developer platform to [Microsoft Teams Community Help](mailto:microsoftteamsdev@microsoft.com). We encourage posting questions on the channels mentioned here and using email only if no other mode of communication is applicable. |
```

2022-02-09 06:44 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ec153912e2e93235a96f770aa0df275b265d3304/msteams-platform/feedback.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/644a4384-ae5c-4094-bc03-07072228d098) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-02-09 06:44 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ec153912e2e93235a96f770aa0df275b265d3304/msteams-platform/feedback.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5cdd83f4-581a-4fe9-aac3-b81e328b6ecb) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-02-09 06:45 UTC, opbld30 commented
Docs Build status updates of commit _[e1426f1](https://github.com/MicrosoftDocs/msteams-docs/commits/e1426f1a72232185830c1570057d9ef6ccaf37b0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Wajeed-msft-support-page/msteams-platform/feedback.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/feedback?branch=pr-en-us-5151) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C9%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202202090644118304-5151%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-12T06%3A45%3A09Z&sr=b&sp=r&sig=Qi7lZ1MeakQejGjrgWQHFC1O78%2F%2BmyYrcsmePV1mPio%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-09 06:45 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9cb76069b664c4cb98ab60315d9738d17a81fbe3/msteams-platform/feedback.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f567e7a9-b357-45c4-97ea-f4e6251ce6ed) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-02-09 06:45 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2172e296472fe24953c38c5721a10a9c181d1d5c/msteams-platform/feedback.md) | 93 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7c406575-e7f4-420b-86bc-c25e2fccf548) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-02-09 06:45 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2172e296472fe24953c38c5721a10a9c181d1d5c/msteams-platform/feedback.md) | 93 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fa3979d1-1799-4b64-a608-accb7ab36b56) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-02-09 06:45 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2172e296472fe24953c38c5721a10a9c181d1d5c/msteams-platform/feedback.md) | 93 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/85fe2e97-a1c5-457f-969b-11c201ad86ad) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-02-09 06:46 UTC, opbld32 commented
Docs Build status updates of commit _[9cb7606](https://github.com/MicrosoftDocs/msteams-docs/commits/9cb76069b664c4cb98ab60315d9738d17a81fbe3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Wajeed-msft-support-page/msteams-platform/feedback.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/feedback?branch=pr-en-us-5151) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C9%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202202090644547845-5151%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-12T06%3A46%3A13Z&sr=b&sp=r&sig=4NmmJhwgi9y%2Bz%2Fr9lu%2F0QrhgAT8PhgnFi0GcEZmsfLo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-09 06:47 UTC, opbld33 commented
Docs Build status updates of commit _[2172e29](https://github.com/MicrosoftDocs/msteams-docs/commits/2172e296472fe24953c38c5721a10a9c181d1d5c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Wajeed-msft-support-page/msteams-platform/feedback.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/feedback?branch=pr-en-us-5151) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C9%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202202090645336327-5151%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-12T06%3A47%3A15Z&sr=b&sp=r&sig=gAn%2BzRoQswc9EnvgrJT3lxbRoFzcmgVC9PBdfbTGz0M%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-09 06:47 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2de2e1eb29a7fc85ff169ee584f9203f07faf6a4/msteams-platform/feedback.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/95710405-f25d-4cb4-8ade-168d4250b5b1) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-02-09 06:48 UTC, opbld31 commented
Docs Build status updates of commit _[2de2e1e](https://github.com/MicrosoftDocs/msteams-docs/commits/2de2e1eb29a7fc85ff169ee584f9203f07faf6a4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Wajeed-msft-support-page/msteams-platform/feedback.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/feedback?branch=pr-en-us-5151) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C9%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202202090646518900-5151%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-12T06%3A48%3A23Z&sr=b&sp=r&sig=29U9Lu1b8KnhHn4RBTWcZo0LskLD403WUuHHEwsptGo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-09 06:49 UTC, opbld33 commented
Docs Build status updates of commit _[fed114b](https://github.com/MicrosoftDocs/msteams-docs/commits/fed114b012b04dba544af54212ff273ccb3c58e0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Wajeed-msft-support-page/msteams-platform/feedback.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/feedback?branch=pr-en-us-5151) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C9%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202202090648024368-5151%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-12T06%3A49%3A20Z&sr=b&sp=r&sig=Zeam6460uY5D9EXXLL9KB8rlkvDrcpcE%2FMmBXhwShgs%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-09 06:49 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fed114b012b04dba544af54212ff273ccb3c58e0/msteams-platform/feedback.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/623d0412-1547-4eff-97ee-66b293f159d7) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-02-09 07:14 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2aec4ee6160e2679008647575ee82410ddfb6051/msteams-platform/feedback.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/736d50cc-cfe7-4323-a115-72d6c20d0be4) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-02-09 07:15 UTC, opbld31 commented
Docs Build status updates of commit _[2aec4ee](https://github.com/MicrosoftDocs/msteams-docs/commits/2aec4ee6160e2679008647575ee82410ddfb6051)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Wajeed-msft-support-page/msteams-platform/feedback.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/feedback?branch=pr-en-us-5151) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C9%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202202090714312786-5151%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-12T07%3A15%3A29Z&sr=b&sp=r&sig=FHj53gNMYIoU3F91VgAfSrOcTQ1%2BJnYiXsU9XhM3zeQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-09 07:19 UTC, surbhigupta12 approved these changes
Approved

2022-02-09 07:19 UTC, merged