[Doc Improvement][Content-bubble-to-in-meeting-dialog]
MicrosoftDocs/msteams-docs pull request #5672
Opened 2022-04-05 11:03 UTC by v-npaladugu

2022-04-05 11:03 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a8f58bc4e1ca93bcf93a907d40fb9436479dbe0e/msteams-platform%2Fapps-in-teams-meetings%2Fmeeting-app-extensibility.md) |   |   | [link]( ) | [:warning:](# "Could not check with Acrolinx&#10;Please close and reopen pull request") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-05 11:04 UTC, opbld33 commented
Docs Build status updates of commit _[a8f58bc](https://github.com/MicrosoftDocs/msteams-docs/commits/a8f58bc4e1ca93bcf93a907d40fb9436479dbe0e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-update-content-bubble-to-in-meeting/msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/meeting-app-extensibility?branch=pr-en-us-5672) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C5%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204051103167798-5672%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-06T11%3A04%3A12Z&sr=b&sp=r&sig=IZhQC4iBpUhbO9f0uXabD3S398FT3BJV1KfvOlJY0mg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-05 11:21 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f1f7b756e4da8f52396d131a5ffec2226d4d7f36/msteams-platform%2Fapps-in-teams-meetings%2Fenable-and-configure-your-app-for-teams-meetings.md) | 97 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cc1dd92b-4113-43c6-be05-581d11b4ae60) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f1f7b756e4da8f52396d131a5ffec2226d4d7f36/msteams-platform%2Fapps-in-teams-meetings%2Fmeeting-app-extensibility.md) | 97 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cb99625d-cb99-4351-bd03-312e79c3a515) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-05 11:21 UTC, opbld33 commented
Docs Build status updates of commit _[f1f7b75](https://github.com/MicrosoftDocs/msteams-docs/commits/f1f7b756e4da8f52396d131a5ffec2226d4d7f36)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-update-content-bubble-to-in-meeting/msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings?branch=pr-en-us-5672) |
[msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-update-content-bubble-to-in-meeting/msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/meeting-app-extensibility?branch=pr-en-us-5672) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C5%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204051120490043-5672%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-06T11%3A21%3A24Z&sr=b&sp=r&sig=9MebqoFqgBnJpH6LfhpEM8A%2BUpcclrs1DS1uKxZdCsM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-06 07:26 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6f5a6a466980c0d73b61b16b470436cc2d0d039c/msteams-platform%2Fapps-in-teams-meetings%2Fenable-and-configure-your-app-for-teams-meetings.md) | 97 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f1167d2c-976d-4948-9be7-d0cccd5569df) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6f5a6a466980c0d73b61b16b470436cc2d0d039c/msteams-platform%2Fapps-in-teams-meetings%2Fmeeting-app-extensibility.md) | 97 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b52118d4-b8db-46b7-89bd-e4484c3497e1) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-06 07:29 UTC, opbld33 commented
Docs Build status updates of commit _[a3867d2](https://github.com/MicrosoftDocs/msteams-docs/commits/a3867d2abda5f20361ba728b8aedcea0606ccd44)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-update-content-bubble-to-in-meeting/msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings?branch=pr-en-us-5672) |
[msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-update-content-bubble-to-in-meeting/msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/meeting-app-extensibility?branch=pr-en-us-5672) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C6%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204060728330620-5672%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-07T07%3A29%3A28Z&sr=b&sp=r&sig=E46VCNRfQMxsrzOHflTSAEFo2rcg%2FORBknmXtaokCmQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-06 07:31 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a3867d2abda5f20361ba728b8aedcea0606ccd44/msteams-platform%2Fapps-in-teams-meetings%2Fenable-and-configure-your-app-for-teams-meetings.md) | 97 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f927768d-9e4f-4e46-97f3-1c362aca902b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a3867d2abda5f20361ba728b8aedcea0606ccd44/msteams-platform%2Fapps-in-teams-meetings%2Fmeeting-app-extensibility.md) | 97 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/20a8b490-05a4-455b-98c6-dd17e6ee122d) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-06 07:50 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8636fd04a22189d15d3f67e0349ee6f2f5b85865/msteams-platform%2Fapps-in-teams-meetings%2Fenable-and-configure-your-app-for-teams-meetings.md) | 97 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8b278bc1-7ee1-4a16-9c9d-d6acf3bad105) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8636fd04a22189d15d3f67e0349ee6f2f5b85865/msteams-platform%2Fapps-in-teams-meetings%2Fmeeting-app-extensibility.md) | 97 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4d72f2ad-9bfa-4782-b387-c339cf06d304) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-06 07:50 UTC, opbld32 commented
Docs Build status updates of commit _[8636fd0](https://github.com/MicrosoftDocs/msteams-docs/commits/8636fd04a22189d15d3f67e0349ee6f2f5b85865)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-update-content-bubble-to-in-meeting/msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings?branch=pr-en-us-5672) |
[msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-update-content-bubble-to-in-meeting/msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/meeting-app-extensibility?branch=pr-en-us-5672) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C6%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204060750048147-5672%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-07T07%3A50%3A43Z&sr=b&sp=r&sig=zzNOiHhxoU3YVgKZiAREYYH1pq09ApSi6q05U9Qbbdo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-08 11:58 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/636fc215a75f343ebcdc7a183d96d4b2b8516f71/msteams-platform%2Fapps-in-teams-meetings%2Fenable-and-configure-your-app-for-teams-meetings.md) | 97 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c923b72b-d58c-4e15-bf8e-49ba2b2bd903) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md](https://github.com/MicrosoftDocs/msteams-docs/blob/636fc215a75f343ebcdc7a183d96d4b2b8516f71/msteams-platform%2Fapps-in-teams-meetings%2Fmeeting-app-extensibility.md) | 97 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5483dd46-d2eb-47cb-a303-be1853cd82b5) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-08 11:58 UTC, opbld30 commented
Docs Build status updates of commit _[636fc21](https://github.com/MicrosoftDocs/msteams-docs/commits/636fc215a75f343ebcdc7a183d96d4b2b8516f71)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-update-content-bubble-to-in-meeting/msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings?branch=pr-en-us-5672) |
[msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-update-content-bubble-to-in-meeting/msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/meeting-app-extensibility?branch=pr-en-us-5672) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C8%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204081157310180-5672%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-09T11%3A58%3A04Z&sr=b&sp=r&sig=LvSyE4W0goFdt9iYm5hYJPYp4SsnNlvwvKqWVamKEt4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-08 12:12 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/637e27fe40ef2208db3b65e933fe32d9975a9da5/msteams-platform%2Fapps-in-teams-meetings%2Fenable-and-configure-your-app-for-teams-meetings.md) | 97 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/df1f5432-40f4-466a-9204-7189adda5b12) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md](https://github.com/MicrosoftDocs/msteams-docs/blob/637e27fe40ef2208db3b65e933fe32d9975a9da5/msteams-platform%2Fapps-in-teams-meetings%2Fmeeting-app-extensibility.md) | 97 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2d375959-43bd-42e1-a739-e9a023f60a87) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-08 12:13 UTC, opbld33 commented
Docs Build status updates of commit _[637e27f](https://github.com/MicrosoftDocs/msteams-docs/commits/637e27fe40ef2208db3b65e933fe32d9975a9da5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-update-content-bubble-to-in-meeting/msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings?branch=pr-en-us-5672) |
[msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-update-content-bubble-to-in-meeting/msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/meeting-app-extensibility?branch=pr-en-us-5672) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C8%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204081211330214-5672%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-09T12%3A13%3A22Z&sr=b&sp=r&sig=2tjhRwrTtY4TxhU02XZtF6I61cYX5Yh2O08TIzjbZxw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-12 05:41 UTC, arocc requested changes
Hi @v-npaladugu, thank you for the updates! I added a couple of comments for additional things we found when testing.

2022-04-12 05:41 UTC, arocc commented on msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md
> +| Federated users, for more information, see [non-standard users](/microsoftteams/non-standard-users). | Interaction is allowed. Create, update, and delete aren't allowed. | Interaction is allowed. A
Additional updates after testing with team:

```suggestion
| Federated users, for more information, see [non-standard users](/microsoftteams/non-standard-users). | Interaction is allowed. Create, update, and delete aren't allowed. | Interaction is allowed. Acquire, update, and delete aren't allowed. | Not available | Interactions in the meeting chat are allowed. | Interactions in the meeting chat from Adaptive Card are allowed. | Interactions in the meeting chat are allowed. | Can view and interact with app on the meeting stage |
```

2022-04-12 05:41 UTC, arocc commented on msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md
> +| Anonymous user | Not available | Not available | Not available | Interactions in the meeting chat are allowed. | Interactions in the meeting chat from Adaptive Card are allowed. | Not available | C
Additional update after testing with team. There are plans to go back to this, but currently it is not supported for anonymous users.

```suggestion
| Anonymous user | Not available | Not available | Not available | Interactions in the meeting chat are allowed. | Interactions in the meeting chat from Adaptive Card are allowed. | Not available | Not available |
```

2022-04-12 08:15 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8cef262374d0c91e18351ea1b6c1ac99c6c640db/msteams-platform%2Fapps-in-teams-meetings%2Fenable-and-configure-your-app-for-teams-meetings.md) | 97 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bcfe4a4a-caa5-4a57-934c-d2976daca08a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8cef262374d0c91e18351ea1b6c1ac99c6c640db/msteams-platform%2Fapps-in-teams-meetings%2Fmeeting-app-extensibility.md) | 97 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cefc6d8b-15cd-442a-88b3-371b346f82c7) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-12 13:21 UTC, arocc commented on msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md
> +| Federated users, for more information, see [non-standard users](/microsoftteams/non-standard-users). | Interaction is allowed. Create, update, and delete aren't allowed. | Interaction is allowed. A
```suggestion
| Federated users, for more information, see [non-standard users](/microsoftteams/non-standard-users). | Interaction is allowed. Create, update, and delete aren't allowed. | Interaction is allowed. Acquire, update, and delete aren't allowed. | Not available | Interactions in the meeting chat are allowed. | Interactions in the meeting chat from Adaptive Card are allowed. | Interactions in the meeting chat are allowed. | Can [start](https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/api-references?tabs=dotnet#share-app-content-to-stage-api) (through SDK API), view, and interact with app on the meeting stage. |
```

2022-04-12 13:22 UTC, arocc requested changes
Tested one more for clarification, thank you for the updates!!

2022-04-13 03:45 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e4b484ecacca0dc9f3b419991ea38faa5588d255/msteams-platform%2Fapps-in-teams-meetings%2Fenable-and-configure-your-app-for-teams-meetings.md) | 97 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b6bc26e0-ce40-4690-868d-c35b8a512bd5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e4b484ecacca0dc9f3b419991ea38faa5588d255/msteams-platform%2Fapps-in-teams-meetings%2Fmeeting-app-extensibility.md) | 97 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/06c20e04-114e-4735-911f-6937ea97ad7c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-13 03:45 UTC, opbld33 commented
Docs Build status updates of commit _[e4b484e](https://github.com/MicrosoftDocs/msteams-docs/commits/e4b484ecacca0dc9f3b419991ea38faa5588d255)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-update-content-bubble-to-in-meeting/msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings?branch=pr-en-us-5672) |
[msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-update-content-bubble-to-in-meeting/msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/meeting-app-extensibility?branch=pr-en-us-5672) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C13%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204130344555579-5672%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-14T03%3A45%3A41Z&sr=b&sp=r&sig=%2FFq3ImX3HFfsFhrdQMgDoRF9ObMu2UQxddPF8%2FGTc5M%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-13 03:50 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6785e36e1df5fa421873551d9ec4f4181f7720e3/msteams-platform%2Fapps-in-teams-meetings%2Fenable-and-configure-your-app-for-teams-meetings.md) | 97 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6eed2f5a-d39e-4ad8-864e-0a3d0a198d0c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6785e36e1df5fa421873551d9ec4f4181f7720e3/msteams-platform%2Fapps-in-teams-meetings%2Fmeeting-app-extensibility.md) | 97 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/911cb1e8-0e14-4e70-90d6-98c083cd7436) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-13 03:51 UTC, opbld32 commented
Docs Build status updates of commit _[6785e36](https://github.com/MicrosoftDocs/msteams-docs/commits/6785e36e1df5fa421873551d9ec4f4181f7720e3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-update-content-bubble-to-in-meeting/msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/meeting-app-extensibility?branch=pr-en-us-5672) | [Details](#user-content-9cecf106fbdf1b3914298efe0241f5ff-0b22cb74)
[msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-update-content-bubble-to-in-meeting/msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings?branch=pr-en-us-5672) |

<a id="9cecf106fbdf1b3914298efe0241f5ff-0b22cb74"></a>
### [msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-update-content-bubble-to-in-meeting/msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md)
 - **Line 210, Column 428**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../apps-in-teams-meetings/api-references'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C13%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204130350278553-5672%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-14T03%3A51%3A27Z&sr=b&sp=r&sig=7O5jKH6wlIfHwTzI8K2NCdifjQpkmPNlWgq4vPx2TlI%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-13 03:54 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2a974987a91bcc2699b82bbb23e5fb216fed9f96/msteams-platform%2Fapps-in-teams-meetings%2Fenable-and-configure-your-app-for-teams-meetings.md) | 97 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/89e5750b-81a6-4239-b2ea-76fcd579a1a3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2a974987a91bcc2699b82bbb23e5fb216fed9f96/msteams-platform%2Fapps-in-teams-meetings%2Fmeeting-app-extensibility.md) | 97 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/eaf162e1-01be-43c8-931b-d53113dba9d1) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-13 03:54 UTC, opbld30 commented
Docs Build status updates of commit _[2a97498](https://github.com/MicrosoftDocs/msteams-docs/commits/2a974987a91bcc2699b82bbb23e5fb216fed9f96)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-update-content-bubble-to-in-meeting/msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings?branch=pr-en-us-5672) |
[msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-update-content-bubble-to-in-meeting/msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/meeting-app-extensibility?branch=pr-en-us-5672) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C13%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204130353347270-5672%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-14T03%3A54%3A27Z&sr=b&sp=r&sig=zQ78%2FMNED0ElEXA9WqCXAkp9B8o%2FusoYLfQUKmGjy4w%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-13 03:56 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e2a61e6cfe74035c89370e48e15c6764e345223e/msteams-platform%2Fapps-in-teams-meetings%2Fenable-and-configure-your-app-for-teams-meetings.md) | 97 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c275cb5a-8760-4527-9f41-b6cfb78c32cb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e2a61e6cfe74035c89370e48e15c6764e345223e/msteams-platform%2Fapps-in-teams-meetings%2Fmeeting-app-extensibility.md) | 97 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ea845f4f-0ce8-48ef-abb3-4e5e8b08c4c0) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-13 03:56 UTC, opbld32 commented
Docs Build status updates of commit _[e2a61e6](https://github.com/MicrosoftDocs/msteams-docs/commits/e2a61e6cfe74035c89370e48e15c6764e345223e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-update-content-bubble-to-in-meeting/msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings?branch=pr-en-us-5672) |
[msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-update-content-bubble-to-in-meeting/msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/meeting-app-extensibility?branch=pr-en-us-5672) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C13%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204130355351605-5672%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-14T03%3A56%3A40Z&sr=b&sp=r&sig=T3UEPxGrUApSUsGPw96%2FJG3jJT85FuHzGeW%2BNymp3Rw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-13 04:00 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/855ec88d4a6224ac52bfc45f740d62394d111e00/msteams-platform%2Fapps-in-teams-meetings%2Fenable-and-configure-your-app-for-teams-meetings.md) | 97 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/11ef25fc-bce6-478a-8c2c-3c8d839ac8bc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md](https://github.com/MicrosoftDocs/msteams-docs/blob/855ec88d4a6224ac52bfc45f740d62394d111e00/msteams-platform%2Fapps-in-teams-meetings%2Fmeeting-app-extensibility.md) | 97 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fff1a309-eac9-47e7-a856-1cb930319df8) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-13 04:01 UTC, opbld33 commented
Docs Build status updates of commit _[855ec88](https://github.com/MicrosoftDocs/msteams-docs/commits/855ec88d4a6224ac52bfc45f740d62394d111e00)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-update-content-bubble-to-in-meeting/msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings?branch=pr-en-us-5672) |
[msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-update-content-bubble-to-in-meeting/msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/meeting-app-extensibility?branch=pr-en-us-5672) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C13%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204130400073186-5672%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-14T04%3A01%3A08Z&sr=b&sp=r&sig=IKaZ0rFjjg06TxXPwziOx1MvTvdZPUqzKskkR0dcEFM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-13 04:04 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2df30ebcc1fabdbaa1e46a99b2dfa204339ede82/msteams-platform%2Fapps-in-teams-meetings%2Fenable-and-configure-your-app-for-teams-meetings.md) | 97 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b40cfbf0-54c3-4ec4-81f2-149bebd41c53) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2df30ebcc1fabdbaa1e46a99b2dfa204339ede82/msteams-platform%2Fapps-in-teams-meetings%2Fmeeting-app-extensibility.md) | 97 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/efd7063d-05fa-407d-90a2-31a02a7f6880) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-13 04:05 UTC, opbld33 commented
Docs Build status updates of commit _[2df30eb](https://github.com/MicrosoftDocs/msteams-docs/commits/2df30ebcc1fabdbaa1e46a99b2dfa204339ede82)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-update-content-bubble-to-in-meeting/msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings?branch=pr-en-us-5672) |
[msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-update-content-bubble-to-in-meeting/msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/meeting-app-extensibility?branch=pr-en-us-5672) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C13%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204130404291359-5672%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-14T04%3A05%3A12Z&sr=b&sp=r&sig=am2gmL3Ii9W66ASN3uNtjWniJSz0IL8uKrKCcwzgHOA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-13 05:13 UTC, arocc commented on msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md
> +| Federated users, for more information, see [non-standard users](/microsoftteams/non-standard-users). | Interaction is allowed. Create, update, and delete aren't allowed. | Interaction is allowed. A
Apologies @v-npaladugu for another comment 😅  -- just hoping to give a bit more clarity here for readers, on what this link is going to. 

```suggestion
| Federated users, for more information, see [non-standard users](/microsoftteams/non-standard-users). | Interaction is allowed. Create, update, and delete aren't allowed. | Interaction is allowed. Acquire, update, and delete aren't allowed. | Not available | Interactions in the meeting chat are allowed. | Interactions in the meeting chat from Adaptive Card are allowed. | Interactions in the meeting chat are allowed. | Can start programmatically, see [share app content to stage through Teams client SDK API](~/apps-in-teams-meetings/API-references.md?tabs=dotnet#share-app-content-to-stage-api). Can view and interact with app on the meeting stage |
```

2022-04-13 05:17 UTC, arocc approved these changes

2022-04-13 06:03 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/76c9fb6af3e1e8fb9cefea317ed3558b5345f372/msteams-platform%2Fapps-in-teams-meetings%2Fenable-and-configure-your-app-for-teams-meetings.md) | 97 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/87f74331-571e-4491-bf9d-bf7b53714b68) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md](https://github.com/MicrosoftDocs/msteams-docs/blob/76c9fb6af3e1e8fb9cefea317ed3558b5345f372/msteams-platform%2Fapps-in-teams-meetings%2Fmeeting-app-extensibility.md) | 97 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3053a7ca-abab-41d5-b573-6d1b09c30ddd) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-13 06:03 UTC, opbld32 commented
Docs Build status updates of commit _[76c9fb6](https://github.com/MicrosoftDocs/msteams-docs/commits/76c9fb6af3e1e8fb9cefea317ed3558b5345f372)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-update-content-bubble-to-in-meeting/msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings?branch=pr-en-us-5672) |
[msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-update-content-bubble-to-in-meeting/msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/meeting-app-extensibility?branch=pr-en-us-5672) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C13%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204130603047696-5672%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-14T06%3A03%3A48Z&sr=b&sp=r&sig=2Fv3rUHUeky55J%2FagoZ08pI%2FFBpo1CipW1567SHL7LM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-13 07:02 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2ef9479808ea6b0d39d3f66c53200c94ecc37f7e/msteams-platform%2Fapps-in-teams-meetings%2Fenable-and-configure-your-app-for-teams-meetings.md) | 97 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bfeadecb-0621-4f74-a5fd-e7e5f4f27752) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2ef9479808ea6b0d39d3f66c53200c94ecc37f7e/msteams-platform%2Fapps-in-teams-meetings%2Fmeeting-app-extensibility.md) | 97 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5f5d82d3-eb86-4d68-840b-d448cd178a9a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-13 07:02 UTC, opbld32 commented
Docs Build status updates of commit _[2ef9479](https://github.com/MicrosoftDocs/msteams-docs/commits/2ef9479808ea6b0d39d3f66c53200c94ecc37f7e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-update-content-bubble-to-in-meeting/msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings?branch=pr-en-us-5672) |
[msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-update-content-bubble-to-in-meeting/msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/meeting-app-extensibility?branch=pr-en-us-5672) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C13%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204130702089561-5672%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-14T07%3A02%3A53Z&sr=b&sp=r&sig=p7dAAKy91gqdeQg5QUMcVrLUrGgQpHWQd2At7De1Pm0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-13 08:42 UTC, surbhigupta12 approved these changes
Approved

2022-04-13 08:42 UTC, merged