[Doc Feature][Update location API][1844452]
MicrosoftDocs/msteams-docs pull request #5704
Opened 2022-04-11 14:30 UTC by v-bdeepa

2022-04-11 14:33 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ad6a7b753add7cfee144d28628b97efb0470293a/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) | 86 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5151f4ef-8ad6-479b-9c40-19f9cacd66a6) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-11 14:34 UTC, opbld32 commented
Docs Build status updates of commit _[ad6a7b7](https://github.com/MicrosoftDocs/msteams-docs/commits/ad6a7b753add7cfee144d28628b97efb0470293a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/tabs/location-picker-desktop.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-desktop.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/concepts/device-capabilities/location-capability.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C11%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204111433065640-5704%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-12T14%3A34%3A08Z&sr=b&sp=r&sig=5hsehxassU4%2FBef0Vyw97z6W4bPXEVKE%2BgQ8d%2BjTJ0o%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-11 14:40 UTC, opbld31 commented
Docs Build status updates of commit _[55fd8bc](https://github.com/MicrosoftDocs/msteams-docs/commits/55fd8bce2ed7fae5985d0cf8a5751eca2b6b3e8a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/tabs/location-picker-desktop.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-desktop.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/concepts/device-capabilities/location-capability.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C11%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204111439147020-5704%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-12T14%3A39%3A59Z&sr=b&sp=r&sig=eDLO2lS8AYtfZVN9JZIvKFuR%2BfAwmsTR6ZkWMrXb8w8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-11 14:44 UTC, opbld31 commented
Docs Build status updates of commit _[22fe90e](https://github.com/MicrosoftDocs/msteams-docs/commits/22fe90e66ac0a0070943374c7161598a884c2a68)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/tabs/location-picker-desktop.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-desktop.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/concepts/device-capabilities/location-capability.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C11%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204111443332402-5704%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-12T14%3A44%3A25Z&sr=b&sp=r&sig=5Ua8ruczYme%2FRxHwDBvRS47j4Wcn1GXFld8lelA8YcM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-11 14:44 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/22fe90e66ac0a0070943374c7161598a884c2a68/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) | 87 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/483cc96f-3faa-4720-bbf5-658c8b953602) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-12 03:45 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/58f4f60da514ae2ee3dbc7b7a02b15324634dad2/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) | 88 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0ef402c2-148c-4df3-8f74-d982ebf9f114) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-12 03:45 UTC, opbld31 commented
Docs Build status updates of commit _[58f4f60](https://github.com/MicrosoftDocs/msteams-docs/commits/58f4f60da514ae2ee3dbc7b7a02b15324634dad2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/tabs/location-picker-desktop.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-desktop.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/concepts/device-capabilities/location-capability.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C12%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204120344563278-5704%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-13T03%3A45%3A40Z&sr=b&sp=r&sig=%2Blf1FDRYeweqOb5896xL0nOFcl17hO4InUsUqsPjWjo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-12 03:48 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/41e90193283580073515fe693f681bffeca4b410/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) | 87 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/10f0383e-297f-4cc9-8d6b-ff5b51d713e3) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-12 03:48 UTC, opbld30 commented
Docs Build status updates of commit _[41e9019](https://github.com/MicrosoftDocs/msteams-docs/commits/41e90193283580073515fe693f681bffeca4b410)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/tabs/location-picker-desktop.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-desktop.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/concepts/device-capabilities/location-capability.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C12%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204120348012417-5704%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-13T03%3A48%3A41Z&sr=b&sp=r&sig=U30Ymwb91j6fSdNz98mI1dkzcSm34Bb2L9GdahRk3Ns%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-12 10:54 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fa5f3fe2078116f1bd54d8e3f3f46e573bb050d4/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) | 89 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bd2af523-2c33-4250-92be-5b17a89fc077) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-12 10:54 UTC, opbld30 commented
Docs Build status updates of commit _[fa5f3fe](https://github.com/MicrosoftDocs/msteams-docs/commits/fa5f3fe2078116f1bd54d8e3f3f46e573bb050d4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/tabs/location-picker-desktop.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-desktop.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/concepts/device-capabilities/location-capability.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C12%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204121053295162-5704%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-13T10%3A54%3A14Z&sr=b&sp=r&sig=VwYnXV63OLBkupnyWvThmK8cKh6LDV%2B731Wt%2FBsNzkE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-12 10:55 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a49c764c0d3ac78ec69111d2d2f6bd6254182acf/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) |   |   | [link]( ) | [:warning:](# "Could not check with Acrolinx&#10;Please close and reopen pull request") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-12 10:56 UTC, opbld32 commented
Docs Build status updates of commit _[a49c764](https://github.com/MicrosoftDocs/msteams-docs/commits/a49c764c0d3ac78ec69111d2d2f6bd6254182acf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/tabs/location-picker-desktop.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-desktop.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/concepts/device-capabilities/location-capability.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C12%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204121055271682-5704%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-13T10%3A56%3A04Z&sr=b&sp=r&sig=0e5BbdSAdzHIEF32N7g%2Fpti0Bu3ANh5IgH0Fowt7r5M%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-12 10:58 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/205c3953a35a6fca7d5b165ddf20feb550b1540e/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) |   |   | [link]( ) | [:warning:](# "Could not check with Acrolinx&#10;Please close and reopen pull request") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-12 10:59 UTC, opbld31 commented
Docs Build status updates of commit _[205c395](https://github.com/MicrosoftDocs/msteams-docs/commits/205c3953a35a6fca7d5b165ddf20feb550b1540e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/tabs/location-picker-desktop.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-desktop.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/concepts/device-capabilities/location-capability.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C12%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204121058285507-5704%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-13T10%3A59%3A06Z&sr=b&sp=r&sig=UYGjHJmpuIB7fxXgD5lE9uHetL%2BVkEXzXapGRj9zAGM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-12 11:05 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1635c2096586bccd2721363bce9b78353ecec0a1/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) | 89 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2e2339b1-bb9d-4465-9861-e681bc6e9386) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-13 03:45 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0de2eb5858967a7a528736487f14037f8553b9a4/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) | 89 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b3c809cf-7072-4253-ae61-1bfb67cdf631) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-13 03:45 UTC, opbld32 commented
Docs Build status updates of commit _[0de2eb5](https://github.com/MicrosoftDocs/msteams-docs/commits/0de2eb5858967a7a528736487f14037f8553b9a4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/tabs/location-picker-desktop.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-desktop.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/concepts/device-capabilities/location-capability.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C13%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204130344397808-5704%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-14T03%3A45%3A20Z&sr=b&sp=r&sig=QYck5cOaKUzngPEnofwp%2Bn1LNm5RKchSs05m8CMKtVQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-13 04:30 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/106c18f19bd7dd5c857216908f95a203f1225147/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) | 89 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5becccc7-7a4b-41cb-9be5-b273c6ef76b3) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-13 04:30 UTC, opbld30 commented
Docs Build status updates of commit _[106c18f](https://github.com/MicrosoftDocs/msteams-docs/commits/106c18f19bd7dd5c857216908f95a203f1225147)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/tabs/location-picker-desktop.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-desktop.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/concepts/device-capabilities/location-capability.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C13%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204130430061225-5704%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-14T04%3A30%3A50Z&sr=b&sp=r&sig=wEYnlw1yvLEBMQUWQDDjjxhQlgd2AJ%2Bld8gt%2FNgXr2o%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-13 08:02 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f38ad08bc452f76bf72e935e5c2d7056d4dfd314/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) | 88 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/83ef242d-9a3f-46d5-b040-2817959ab410) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-13 08:03 UTC, opbld33 commented
Docs Build status updates of commit _[f38ad08](https://github.com/MicrosoftDocs/msteams-docs/commits/f38ad08bc452f76bf72e935e5c2d7056d4dfd314)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/tabs/location-picker-desktop.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-desktop.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/concepts/device-capabilities/location-capability.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C13%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204130802187597-5704%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-14T08%3A03%3A01Z&sr=b&sp=r&sig=Ivkpwwuzj%2Fk7xvP%2BrtxiXeMnnS9dahVWC85kB6yH1gY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-13 08:08 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a28fa75fe81cf8dcdfdd20b553c3d5452400673b/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) | 88 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7b47bf84-aa4b-4cc6-bba7-f2e00f091d4e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-13 08:08 UTC, opbld33 commented
Docs Build status updates of commit _[a28fa75](https://github.com/MicrosoftDocs/msteams-docs/commits/a28fa75fe81cf8dcdfdd20b553c3d5452400673b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/tabs/location-picker-desktop.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-desktop.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/concepts/device-capabilities/location-capability.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C13%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204130807373052-5704%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-14T08%3A08%3A34Z&sr=b&sp=r&sig=3U8UMUAktNrc2Ido3BEuhTEsMqPMZx0JaQ6%2Be6UL%2FRo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-13 08:38 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c2d676ff1fb7452f6b8b7ab742b2600d4da1c994/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) | 88 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/888a0ed1-8d1b-4c9b-8315-e8429c45edfa) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-13 08:38 UTC, opbld32 commented
Docs Build status updates of commit _[c2d676f](https://github.com/MicrosoftDocs/msteams-docs/commits/c2d676ff1fb7452f6b8b7ab742b2600d4da1c994)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/tabs/location-picker-desktop.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-desktop.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/concepts/device-capabilities/location-capability.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C13%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204130837353693-5704%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-14T08%3A38%3A19Z&sr=b&sp=r&sig=jHYGswy8L7AgwJR5v6Ued0s3z7ku%2FJ8ap%2FMqr7DaieY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-18 04:46 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/07b1f290b5fca6b9667288d390ca825ef7a60f2e/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) | 88 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aabb99b1-0398-4218-a3fe-72c4bb4971df) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-18 04:48 UTC, opbld30 commented
Docs Build status updates of commit _[07b1f29](https://github.com/MicrosoftDocs/msteams-docs/commits/07b1f290b5fca6b9667288d390ca825ef7a60f2e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/tabs/location-picker-desktop.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-desktop.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/concepts/device-capabilities/location-capability.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C18%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204180445540249-5704%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-19T04%3A48%3A20Z&sr=b&sp=r&sig=ExMLQgkIZ3cI7%2BtAOZLhNJ%2FxsgtMgJkbI3jEsTLJ6K0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-19 03:23 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/77cd9c2cc907a957e67d856f4844b4c5a37d714b/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) | 88 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dd44a471-778b-4727-af94-afa94ac68f0b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-19 03:23 UTC, opbld33 commented
Docs Build status updates of commit _[77cd9c2](https://github.com/MicrosoftDocs/msteams-docs/commits/77cd9c2cc907a957e67d856f4844b4c5a37d714b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/tabs/location-picker-desktop.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-desktop.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/concepts/device-capabilities/location-capability.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C19%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204190323081886-5704%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-20T03%3A23%3A39Z&sr=b&sp=r&sig=LMSLkXTfdM9m7O0I2Wr8UCaGSPAa2od8N%2Bgg%2BR5fc8M%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-21 12:05 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/74a72583dea1e2a0cea7714de47ca120f6e25a1a/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) | 88 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a8e738f9-e630-42f3-b03e-395d4b8649a6) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-21 12:06 UTC, opbld30 commented
Docs Build status updates of commit _[74a7258](https://github.com/MicrosoftDocs/msteams-docs/commits/74a72583dea1e2a0cea7714de47ca120f6e25a1a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/tabs/location-picker-desktop.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-desktop.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/location-capability.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C21%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204211205192122-5704%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-22T12%3A06%3A01Z&sr=b&sp=r&sig=0wNx%2FyF0XNi4s5wupv2ezQnrzrgjUly%2F%2FOdaUqKgXKI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-25 03:54 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d82442d8aacfff3bd58a965a27d2c4e44f012ff6/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) | 88 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9b7de514-fcc2-4d07-871b-c61a40b64b9a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-25 03:55 UTC, opbld30 commented
Docs Build status updates of commit _[d82442d](https://github.com/MicrosoftDocs/msteams-docs/commits/d82442d8aacfff3bd58a965a27d2c4e44f012ff6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/tabs/location-picker-desktop.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-desktop.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/location-capability.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C25%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204250354219289-5704%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-26T03%3A55%3A26Z&sr=b&sp=r&sig=04SxpgbrBqQtgFGTENaQf5jLDioJYhfID8EuS%2Ft%2Fzag%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-25 05:29 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/00ae08fd050baee223a2aef460e459848c1ab667/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) | 89 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8d7bf576-d657-4f03-9e0c-89295ff52d3e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-25 05:31 UTC, opbld33 commented
Docs Build status updates of commit _[00ae08f](https://github.com/MicrosoftDocs/msteams-docs/commits/00ae08fd050baee223a2aef460e459848c1ab667)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/location-capability.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) | [Details](#user-content-0a4769b3701b815d94d2e807526f75ed-7bfe39ac)
[msteams-platform/assets/images/tabs/location-picker-desktop.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-desktop.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |

<a id="0a4769b3701b815d94d2e807526f75ed-7bfe39ac"></a>
### [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/location-capability.md)
 - **Line 13, Column 74**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/javascript/api/overview/msteams-client?view=msteams-client-js-latest&preserve-view=true' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 13, Column 74**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/javascript/api/overview/msteams-client?view=msteams-client-js-latest&preserve-view=true' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C25%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204250529143478-5704%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-26T05%3A31%3A01Z&sr=b&sp=r&sig=y1UNy13s40hX%2BcYDiW3Q2b39BSTSI99paKh0hapyfUE%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-25 07:12 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7197266b09355687ff2af16cc143f6fdb1d74935/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) | 89 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/527d6ee3-7ec4-42fc-8d9b-a3b40c333117) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-25 07:13 UTC, opbld33 commented
Docs Build status updates of commit _[7197266](https://github.com/MicrosoftDocs/msteams-docs/commits/7197266b09355687ff2af16cc143f6fdb1d74935)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/tabs/location-picker-desktop.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-desktop.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/location-capability.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C25%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204250712067548-5704%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-26T07%3A13%3A26Z&sr=b&sp=r&sig=WsDIQkGU4wNrPIWtC98dxAEjP4ZnOQNPrQhQa4qA5sI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-25 10:33 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c88df7d91797540f989df062bbd05a4a041eb833/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) | 89 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bd6b3f16-0825-4e4e-b972-24453ac0c0db) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c88df7d91797540f989df062bbd05a4a041eb833/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fnative-device-permissions.md) | 88 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b8e144a8-1095-4a74-9dca-8bf66cf048b4) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-25 10:33 UTC, opbld30 commented
Docs Build status updates of commit _[c88df7d](https://github.com/MicrosoftDocs/msteams-docs/commits/c88df7d91797540f989df062bbd05a4a041eb833)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/tabs/location-picker-desktop.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-desktop.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/location-capability.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/native-device-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C25%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204251033112026-5704%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-26T10%3A33%3A50Z&sr=b&sp=r&sig=Cu1cN26T9nl6SmpVMhMx6mi7UDhcIttvNrZn5qASqBM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-25 10:42 UTC, v-abirade requested changes

2022-04-25 10:42 UTC, v-abirade commented on msteams-platform/concepts/device-capabilities/location-capability.md
> +To integrate location capabilities, you must do the following:
Add this in Update manifest section.

2022-04-25 10:42 UTC, v-abirade commented on msteams-platform/concepts/device-capabilities/location-capability.md
> +The following image depicts mobile app experience of location capabilities:
Add steps for navigation.

2022-04-25 10:42 UTC, v-abirade commented on msteams-platform/concepts/device-capabilities/location-capability.md
> +# [Desktop or web](#tab/desktop)
Change heading to Desktop, remove or Web.

2022-04-25 10:57 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4beddb611a462d591ced10f9a9c32be766071f03/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) | 89 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ab98db94-c040-4353-856f-57783811d31c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4beddb611a462d591ced10f9a9c32be766071f03/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fnative-device-permissions.md) | 88 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6821040b-7b85-4a66-8f11-7cefcc94f54e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-25 11:00 UTC, opbld31 commented
Docs Build status updates of commit _[4beddb6](https://github.com/MicrosoftDocs/msteams-docs/commits/4beddb611a462d591ced10f9a9c32be766071f03)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-1c404f6e)

<a id="1c404f6e"></a>
###
 - **[Error: RuningBuildFailed]** `````Some unexpected errors happened when running build, please open a ticket in https://aka.ms/SiteHelp and include the error report for our team to troubleshoot`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C25%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204251057203995-5704%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-26T11%3A00%3A30Z&sr=b&sp=r&sig=JrLrQ4T2SVViroPB2GvUTf4Ezd2RCmkBqMoPn4l4sGo%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-25 13:19 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9f47bb09ecc345f93d9f2500fac72185993720f9/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) | 81 | 28 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/67c806f9-9f71-478d-beb3-2d5bda73286e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9f47bb09ecc345f93d9f2500fac72185993720f9/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fnative-device-permissions.md) | 89 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ea5e5b73-88f1-41a3-b647-015ea52252ca) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-25 13:19 UTC, opbld32 commented
Docs Build status updates of commit _[9f47bb0](https://github.com/MicrosoftDocs/msteams-docs/commits/9f47bb09ecc345f93d9f2500fac72185993720f9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/tabs/MobileLocationPermission.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/MobileLocationPermission.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/MobilePermissions.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/MobilePermissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/device-permissions.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/device-permissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-desktop.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-desktop.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/location-capability.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/native-device-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C25%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204251318449565-5704%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-26T13%3A19%3A31Z&sr=b&sp=r&sig=VfSbOJ95qT9lp%2FICxvuJORYSHOvWN5RBXsZ5TuVDS18%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-25 13:24 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/410384ca44d5a0c19b7b34cf09ed68f5046327cc/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) | 81 | 28 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/21e6791d-5e76-4aee-87ef-364724216da2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/410384ca44d5a0c19b7b34cf09ed68f5046327cc/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fnative-device-permissions.md) | 89 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aa045bd0-dc2a-4829-945b-4cd604e2566f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-26 05:51 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dae231c86e346c6e9be42fa4d3b337d232c370a3/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) | 83 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/186eceb0-6381-4e14-9d0e-fea390599d97) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dae231c86e346c6e9be42fa4d3b337d232c370a3/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fnative-device-permissions.md) | 89 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/01869829-e685-40f3-9f81-de0d07e41817) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-26 05:52 UTC, opbld31 commented
Docs Build status updates of commit _[dae231c](https://github.com/MicrosoftDocs/msteams-docs/commits/dae231c86e346c6e9be42fa4d3b337d232c370a3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/tabs/MobileLocationPermission.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/MobileLocationPermission.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/MobilePermissions.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/MobilePermissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/device-permissions.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/device-permissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-desktop.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-desktop.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/location-capability.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/native-device-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C26%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204260551131691-5704%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-27T05%3A52%3A11Z&sr=b&sp=r&sig=%2FkZm6%2BWQilM3HX0oC%2FNvqyol23LL6aFAuheDqO0RHeE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-26 06:50 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/40245709b048171c1a74d05ce3ff942647ecd22e/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) | 83 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2551cf0c-5fc4-4f79-9908-aade1198cdb2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/40245709b048171c1a74d05ce3ff942647ecd22e/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fnative-device-permissions.md) | 89 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4284e2f9-292c-4dcd-a477-8c54b395f35a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/40245709b048171c1a74d05ce3ff942647ecd22e/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f30a1a43-a2a9-48c4-a148-ccc33f0e48a4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/40245709b048171c1a74d05ce3ff942647ecd22e/msteams-platform%2Fwhats-new.md) | 93 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a9aec78b-c065-4a03-a141-81fd6788bbf9) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-26 06:50 UTC, opbld32 commented
Docs Build status updates of commit _[4024570](https://github.com/MicrosoftDocs/msteams-docs/commits/40245709b048171c1a74d05ce3ff942647ecd22e)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/mstdd-landing.yml) | :x:Error | | [Details](#user-content-cb2a1ff90e05ba4253e780c1fb182487-dfc2058c)

<a id="cb2a1ff90e05ba4253e780c1fb182487-dfc2058c"></a>
### [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/mstdd-landing.yml)
 - **Line 27, Column 7**: **[Error: array-length-invalid]** `````Array 'landingContent.linkLists.links' length should be <= 10.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C26%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204260649348369-5704%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-27T06%3A50%3A19Z&sr=b&sp=r&sig=XyuVfUwW36YCBENyJ0YWlRLtJ80Y16kEaCk6OJZSF9o%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-26 06:52 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7f158e6bb12ffbc7ead0cc0363928b005e14c33a/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) | 83 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a013290c-6947-4b37-8f26-84cbcc794279) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7f158e6bb12ffbc7ead0cc0363928b005e14c33a/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fnative-device-permissions.md) | 89 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/49828342-a132-41c7-ba47-af958758da1e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/7f158e6bb12ffbc7ead0cc0363928b005e14c33a/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/32c95410-3466-4189-8a8b-3af9f2bfa2d4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7f158e6bb12ffbc7ead0cc0363928b005e14c33a/msteams-platform%2Fwhats-new.md) | 93 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5626322c-cc25-4b96-9e2f-b0232665f480) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-26 06:52 UTC, opbld31 commented
Docs Build status updates of commit _[7f158e6](https://github.com/MicrosoftDocs/msteams-docs/commits/7f158e6bb12ffbc7ead0cc0363928b005e14c33a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/tabs/MobileLocationPermission.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/MobileLocationPermission.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/MobilePermissions.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/MobilePermissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/device-permissions.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/device-permissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-desktop.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-desktop.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/location-capability.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/native-device-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/mstdd-landing.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/mstdd-landing?branch=pr-en-us-5704) |
[msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/whats-new.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/whats-new?branch=pr-en-us-5704) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C26%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204260651580010-5704%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-27T06%3A52%3A44Z&sr=b&sp=r&sig=82u9YOS1bgfvuHRfB%2FbLAvvbin%2Ba535XxbSJarE0DG8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-27 05:14 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c2066c2453085bf41c0d398f809250ff578f0871/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) | 83 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/96e66bd7-aa10-42a1-98da-1ee17957b829) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c2066c2453085bf41c0d398f809250ff578f0871/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fnative-device-permissions.md) | 89 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/163be60a-d8f4-4c8b-bb44-8e68ba3a0722) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c2066c2453085bf41c0d398f809250ff578f0871/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6664f6ea-085b-4d83-ae13-2832a146c8c3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c2066c2453085bf41c0d398f809250ff578f0871/msteams-platform%2Fwhats-new.md) | 93 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d004be7e-07de-459f-bb6d-3fa2defe524c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-27 05:15 UTC, opbld32 commented
Docs Build status updates of commit _[c2066c2](https://github.com/MicrosoftDocs/msteams-docs/commits/c2066c2453085bf41c0d398f809250ff578f0871)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/tabs/MobileLocationPermission.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/MobileLocationPermission.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/MobilePermissions.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/MobilePermissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/device-permissions.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/device-permissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-desktop.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-desktop.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/location-capability.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/native-device-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/mstdd-landing.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/mstdd-landing?branch=pr-en-us-5704) |
[msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/whats-new.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/whats-new?branch=pr-en-us-5704) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C27%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204270514034106-5704%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-28T05%3A15%3A10Z&sr=b&sp=r&sig=wo6ukHjUtXoQ%2FKpRszL4eg8ggjTNcgEG62RfWAR9zlQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-27 05:43 UTC, opbld31 commented
Docs Build status updates of commit _[de02dfe](https://github.com/MicrosoftDocs/msteams-docs/commits/de02dfef6d28a773b248cde0e6b7ef671058a167)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/tabs/MobileLocationPermission.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/MobileLocationPermission.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/MobilePermissions.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/MobilePermissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/device-permissions.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/device-permissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-desktop.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-desktop.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/location-capability.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/native-device-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/mstdd-landing.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/mstdd-landing?branch=pr-en-us-5704) |
[msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/whats-new.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/whats-new?branch=pr-en-us-5704) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C27%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204270542459225-5704%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-28T05%3A43%3A42Z&sr=b&sp=r&sig=CeTGorwUOSYl9Jwc4AGMh9Fdk9S9aafZYmFayEH0x3Y%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-27 05:45 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/de02dfef6d28a773b248cde0e6b7ef671058a167/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) | 83 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5977f283-f69b-43d1-8a51-6880fc182d7f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/de02dfef6d28a773b248cde0e6b7ef671058a167/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fnative-device-permissions.md) | 89 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7797ae2b-0086-421c-a3ea-23f97258671c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/de02dfef6d28a773b248cde0e6b7ef671058a167/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9c26e120-e42d-46c1-a5f0-81ebb23accb9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/de02dfef6d28a773b248cde0e6b7ef671058a167/msteams-platform%2Fwhats-new.md) | 93 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/75f1dab1-48d2-4c5e-9193-ef7ff11bbab7) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-27 05:48 UTC, opbld33 commented
Docs Build status updates of commit _[fa1a307](https://github.com/MicrosoftDocs/msteams-docs/commits/fa1a307859eab737ff3aac1194e336c6e478658f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/tabs/MobileLocationPermission.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/MobileLocationPermission.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/MobilePermissions.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/MobilePermissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/device-permissions.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/device-permissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-desktop.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-desktop.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/location-capability.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/native-device-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/mstdd-landing.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/mstdd-landing?branch=pr-en-us-5704) |
[msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/whats-new.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/whats-new?branch=pr-en-us-5704) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C27%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204270547322303-5704%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-28T05%3A48%3A14Z&sr=b&sp=r&sig=k8PnLNxlwklSohCPsPs6Mc6eA1R4v98Sf0xdMvXZiBU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-27 05:50 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fa1a307859eab737ff3aac1194e336c6e478658f/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) | 83 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6e10ab14-f0a2-49b4-b887-f860a36d62a9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fa1a307859eab737ff3aac1194e336c6e478658f/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fnative-device-permissions.md) | 89 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/15e8e97a-b68e-4d11-9166-e84d121ad0b2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/fa1a307859eab737ff3aac1194e336c6e478658f/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e1b56983-6fcc-4204-b2f5-5eff9f66410e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fa1a307859eab737ff3aac1194e336c6e478658f/msteams-platform%2Fwhats-new.md) | 93 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fa5040c0-98bf-4702-9457-a097d9b18355) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-27 10:19 UTC, opbld33 commented
Docs Build status updates of commit _[1436dab](https://github.com/MicrosoftDocs/msteams-docs/commits/1436dabd1203af112c38355fde246e1306453265)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/location-capability.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) | [Details](#user-content-0a4769b3701b815d94d2e807526f75ed-2de67d46)
[msteams-platform/assets/images/tabs/MobileLocationPermission.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/MobileLocationPermission.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/MobilePermissions.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/MobilePermissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/device-permissions.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/device-permissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-desktop.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-desktop.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/native-device-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/mstdd-landing.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/mstdd-landing?branch=pr-en-us-5704) |
[msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/whats-new.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/whats-new?branch=pr-en-us-5704) |

<a id="0a4769b3701b815d94d2e807526f75ed-2de67d46"></a>
### [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/location-capability.md)
 - **Line 55, Column 77**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#location-api' in 'concepts/device-capabilities/location-capability.md', did you mean '#location-apis'?`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C27%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204271019007280-5704%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-28T10%3A19%3A40Z&sr=b&sp=r&sig=RhtGXT9dF8benJq62AcaFhEIIVp9DSMdO4redO7XdFk%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-27 10:21 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1436dabd1203af112c38355fde246e1306453265/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) | 83 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/49bdfc20-1212-4b1c-911c-28dc94307536) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1436dabd1203af112c38355fde246e1306453265/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fnative-device-permissions.md) | 89 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3257b279-f30d-4950-b7b7-9a19c04e1649) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1436dabd1203af112c38355fde246e1306453265/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6b535297-3b2b-40a2-96f5-908ce310df1b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1436dabd1203af112c38355fde246e1306453265/msteams-platform%2Fwhats-new.md) | 93 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a205b11f-a02c-4447-bcb1-f2a3b703e417) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-27 10:27 UTC, opbld32 commented
Docs Build status updates of commit _[7b849e1](https://github.com/MicrosoftDocs/msteams-docs/commits/7b849e1ba69381746900c869d9c92403c30be7f4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/tabs/MobileLocationPermission.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/MobileLocationPermission.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/MobilePermissions.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/MobilePermissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/device-permissions.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/device-permissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-desktop.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-desktop.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/location-capability.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/native-device-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/mstdd-landing.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/mstdd-landing?branch=pr-en-us-5704) |
[msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/whats-new.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/whats-new?branch=pr-en-us-5704) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C27%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204271025483103-5704%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-28T10%3A27%3A05Z&sr=b&sp=r&sig=BGwiLwodNQCt6b02WeXKMtZ5mXubDvU77psYSJFFai8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-27 10:28 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7b849e1ba69381746900c869d9c92403c30be7f4/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) | 83 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/16da226b-f2c6-45e5-88f5-1f0fd3c0c8c0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7b849e1ba69381746900c869d9c92403c30be7f4/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fnative-device-permissions.md) | 89 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8247ee34-6d7e-4096-9ab5-23df4716ba30) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/7b849e1ba69381746900c869d9c92403c30be7f4/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/13f6e96c-5f3c-4339-9992-c2ecb0b6de35) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7b849e1ba69381746900c869d9c92403c30be7f4/msteams-platform%2Fwhats-new.md) | 93 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/df90226c-60c7-44ed-987a-256ac99ba340) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-28 04:51 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c752d4e2f0354ecc4adc4d398d6763744e1a2aec/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) | 83 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4ff29c1b-6e8f-4ee1-b665-55bb7bad95df) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c752d4e2f0354ecc4adc4d398d6763744e1a2aec/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fnative-device-permissions.md) | 89 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8afb7fde-e407-4786-8080-1ccdbc850ad5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c752d4e2f0354ecc4adc4d398d6763744e1a2aec/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/85dfa767-a882-441e-a7c0-abdc02609f31) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c752d4e2f0354ecc4adc4d398d6763744e1a2aec/msteams-platform%2Fwhats-new.md) | 93 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/874343ea-18ec-491d-b47e-b03b9a653d11) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-28 04:52 UTC, opbld32 commented
Docs Build status updates of commit _[c752d4e](https://github.com/MicrosoftDocs/msteams-docs/commits/c752d4e2f0354ecc4adc4d398d6763744e1a2aec)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/tabs/MobileLocationPermission.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/MobileLocationPermission.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/MobilePermissions.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/MobilePermissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/device-permissions.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/device-permissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-desktop.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-desktop.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/location-capability.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/native-device-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/mstdd-landing.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/mstdd-landing?branch=pr-en-us-5704) |
[msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/whats-new.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/whats-new?branch=pr-en-us-5704) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C28%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204280451045963-5704%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-29T04%3A52%3A38Z&sr=b&sp=r&sig=iplV9lABqKvplYsM7o5n8VKG58pz92SM3U1Au9iA3LM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-28 06:27 UTC, opbld30 commented
Docs Build status updates of commit _[47a35d2](https://github.com/MicrosoftDocs/msteams-docs/commits/47a35d2ef87172f040d431ea5e06d32230acbf35)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/tabs/MobileLocationPermission.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/MobileLocationPermission.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/MobilePermissions.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/MobilePermissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/device-permissions.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/device-permissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-desktop.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-desktop.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/location-capability.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/native-device-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/mstdd-landing.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/mstdd-landing?branch=pr-en-us-5704) |
[msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/whats-new.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/whats-new?branch=pr-en-us-5704) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C28%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204280626442568-5704%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-29T06%3A27%3A38Z&sr=b&sp=r&sig=Be9X0aJoSQ3QkjnGchOqUVfhBHGKEfEk26nZiL%2BcjXI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-28 06:27 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/47a35d2ef87172f040d431ea5e06d32230acbf35/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) | 83 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7ad91126-9f0f-40c7-b2c5-3d1d30021f99) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/47a35d2ef87172f040d431ea5e06d32230acbf35/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fnative-device-permissions.md) | 89 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/78ff5082-408e-40b0-a20e-b0311a319b1e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/47a35d2ef87172f040d431ea5e06d32230acbf35/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/945bf334-3007-465b-914b-77b693b198cf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/47a35d2ef87172f040d431ea5e06d32230acbf35/msteams-platform%2Fwhats-new.md) | 93 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/be9facf3-d03b-4794-9b45-9e20cd3e0d33) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-28 06:28 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4e72a0a05e1afd96015d451190ae9e2e9809f158/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) | 83 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5ff8c0df-cd4a-4df8-b027-1bf6ede3e712) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4e72a0a05e1afd96015d451190ae9e2e9809f158/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fnative-device-permissions.md) | 89 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7b1e7490-c776-4713-8e5b-9524c6c86c2a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/4e72a0a05e1afd96015d451190ae9e2e9809f158/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b4774f1c-a4c0-4dc5-abf6-e15c8d99c5e9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4e72a0a05e1afd96015d451190ae9e2e9809f158/msteams-platform%2Fwhats-new.md) | 93 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c244f0f5-67bb-43a7-845d-fd7cd3ad5152) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-28 06:29 UTC, opbld31 commented
Docs Build status updates of commit _[4e72a0a](https://github.com/MicrosoftDocs/msteams-docs/commits/4e72a0a05e1afd96015d451190ae9e2e9809f158)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/tabs/MobileLocationPermission.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/MobileLocationPermission.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/MobilePermissions.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/MobilePermissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/device-permissions.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/device-permissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-desktop.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-desktop.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/location-capability.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/native-device-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/mstdd-landing.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/mstdd-landing?branch=pr-en-us-5704) |
[msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/whats-new.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/whats-new?branch=pr-en-us-5704) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C28%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204280627565999-5704%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-29T06%3A29%3A02Z&sr=b&sp=r&sig=L3H%2BBKlbVAsCcx4MvZT%2FGWbhX6VrbSywVtxaJ2j81Bw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-28 07:30 UTC, opbld31 commented
Docs Build status updates of commit _[a420624](https://github.com/MicrosoftDocs/msteams-docs/commits/a420624fe90609a564bafd972b3e346f912d7ff4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/tabs/MobileLocationPermission.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/MobileLocationPermission.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/MobilePermissions.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/MobilePermissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/device-permissions.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/device-permissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-desktop.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-desktop.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/location-capability.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/native-device-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/mstdd-landing.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/mstdd-landing?branch=pr-en-us-5704) |
[msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/whats-new.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/whats-new?branch=pr-en-us-5704) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C28%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204280729505295-5704%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-29T07%3A30%3A58Z&sr=b&sp=r&sig=9uk8ZtPyaNMdjjeftsLvvwzFZ6qe%2FhD8AkI8gVmbKOE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-28 07:50 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0ced734d9eebc84cafda64a1597240f27675ea22/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) | 88 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6837b4ad-83d3-41e7-ae58-84d6f953be23) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0ced734d9eebc84cafda64a1597240f27675ea22/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fnative-device-permissions.md) | 89 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7234ec84-fc7c-499b-8668-b48ecaf5f6d4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/0ced734d9eebc84cafda64a1597240f27675ea22/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/58d32152-c8c8-44d6-ba0b-4dd3d008de80) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0ced734d9eebc84cafda64a1597240f27675ea22/msteams-platform%2Fwhats-new.md) | 93 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5345c513-0aec-46f7-9415-55644c48e661) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-28 07:50 UTC, opbld33 commented
Docs Build status updates of commit _[0ced734](https://github.com/MicrosoftDocs/msteams-docs/commits/0ced734d9eebc84cafda64a1597240f27675ea22)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/tabs/MobileLocationPermission.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/MobileLocationPermission.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/MobilePermissions.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/MobilePermissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/device-permissions.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/device-permissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-desktop.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-desktop.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/location-capability.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/native-device-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/mstdd-landing.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/mstdd-landing?branch=pr-en-us-5704) |
[msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/whats-new.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/whats-new?branch=pr-en-us-5704) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C28%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204280749229070-5704%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-29T07%3A50%3A22Z&sr=b&sp=r&sig=a0KeGaAfzp5UQmXu5EOpQmluzSiJRrXKZaquXBXJSRQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-28 09:46 UTC, opbld33 commented
Docs Build status updates of commit _[e119379](https://github.com/MicrosoftDocs/msteams-docs/commits/e1193797f5df9ca9e6f7a8638fef5761c8ee5c36)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/tabs/MobileLocationPermission.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/MobileLocationPermission.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/MobilePermissions.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/MobilePermissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/device-permissions.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/device-permissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-desktop.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-desktop.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/location-capability.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/native-device-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/mstdd-landing.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/mstdd-landing?branch=pr-en-us-5704) |
[msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/whats-new.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/whats-new?branch=pr-en-us-5704) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C28%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204280945409060-5704%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-29T09%3A46%3A33Z&sr=b&sp=r&sig=MkwxuEMG1w1lkPeJLn4r%2FK20TEOIC6AMdBKenqydN9w%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-28 09:46 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e1193797f5df9ca9e6f7a8638fef5761c8ee5c36/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) | 88 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5d4dd65a-d79c-4178-bc2a-1657e2ffe8ed) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e1193797f5df9ca9e6f7a8638fef5761c8ee5c36/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fnative-device-permissions.md) | 89 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f03ce6f7-363e-4368-93c4-dddf19ae5346) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e1193797f5df9ca9e6f7a8638fef5761c8ee5c36/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/db1a2edd-e9ed-4911-b8cd-a04e368ebd64) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e1193797f5df9ca9e6f7a8638fef5761c8ee5c36/msteams-platform%2Fwhats-new.md) | 93 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9426a305-2f32-423c-94cd-b26c3fa11fc2) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-28 09:48 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8841cc36a4a55f073d8390f325a3e0d5c4129ec7/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) | 88 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/128351a8-9b78-43ee-a5b8-3ad65179f300) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8841cc36a4a55f073d8390f325a3e0d5c4129ec7/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fnative-device-permissions.md) | 89 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/90768a14-5565-437b-ac25-23150d82486e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/8841cc36a4a55f073d8390f325a3e0d5c4129ec7/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/835f171d-41bd-403a-a299-a01168ef2bae) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8841cc36a4a55f073d8390f325a3e0d5c4129ec7/msteams-platform%2Fwhats-new.md) | 93 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0f2f348d-57f9-4138-ac59-31058ee66010) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-28 09:49 UTC, opbld31 commented
Docs Build status updates of commit _[8841cc3](https://github.com/MicrosoftDocs/msteams-docs/commits/8841cc36a4a55f073d8390f325a3e0d5c4129ec7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/tabs/MobileLocationPermission.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/MobileLocationPermission.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/MobilePermissions.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/MobilePermissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/device-permissions.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/device-permissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-desktop.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-desktop.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/location-capability.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/native-device-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/mstdd-landing.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/mstdd-landing?branch=pr-en-us-5704) |
[msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/whats-new.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/whats-new?branch=pr-en-us-5704) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C28%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204280948037831-5704%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-29T09%3A49%3A17Z&sr=b&sp=r&sig=2ok6Nng4Zfw8aPoUX8ZN9JUG61CXGQsaRLJFFY4FPt8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-02 09:02 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ff2f70c45f144a2ec26cb146125df78a124b3a24/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) | 86 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/663e3e6b-f92d-4c34-8840-f80f8305d364) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ff2f70c45f144a2ec26cb146125df78a124b3a24/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fnative-device-permissions.md) | 88 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/836c5ef5-586e-40de-94a3-bb5f63d4d02f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ff2f70c45f144a2ec26cb146125df78a124b3a24/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1f04d2fc-b541-4ee1-8afa-de4b01e0f31b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ff2f70c45f144a2ec26cb146125df78a124b3a24/msteams-platform%2Fwhats-new.md) | 92 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/15ffb9b2-1c79-46a7-b017-1ca8b1233add) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-02 09:02 UTC, opbld30 commented
Docs Build status updates of commit _[ff2f70c](https://github.com/MicrosoftDocs/msteams-docs/commits/ff2f70c45f144a2ec26cb146125df78a124b3a24)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/mstdd-landing.yml) | :x:Error | | [Details](#user-content-cb2a1ff90e05ba4253e780c1fb182487-9233cd08)

<a id="cb2a1ff90e05ba4253e780c1fb182487-9233cd08"></a>
### [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/mstdd-landing.yml)
 - **Line 27, Column 7**: **[Error: array-length-invalid]** `````Array 'landingContent.linkLists.links' length should be <= 10.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C2%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202205020901356239-5704%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-02T09%3A02%3A18Z&sr=b&sp=r&sig=xQhFT7DNeXtT%2FbXfnfAT30ywNCCXexAg6IshqmkKTxU%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-04 13:10 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1c9ce5aaf67d7c913724c4dec46b135b960dac34/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) | 86 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f3e9cffa-b410-4d64-bced-44ce57eca307) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1c9ce5aaf67d7c913724c4dec46b135b960dac34/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fnative-device-permissions.md) | 88 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/82489fcd-0fba-46de-b8a7-572eecd1af58) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1c9ce5aaf67d7c913724c4dec46b135b960dac34/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/eb8aeae5-fd17-413c-a35b-dc407ee302c5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1c9ce5aaf67d7c913724c4dec46b135b960dac34/msteams-platform%2Fwhats-new.md) | 92 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/22875c82-77eb-4add-80e1-7c1f3fb5531e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-04 13:12 UTC, opbld31 commented
Docs Build status updates of commit _[1c9ce5a](https://github.com/MicrosoftDocs/msteams-docs/commits/1c9ce5aaf67d7c913724c4dec46b135b960dac34)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/mstdd-landing.yml) | :x:Error | | [Details](#user-content-cb2a1ff90e05ba4253e780c1fb182487-a445cf37)

<a id="cb2a1ff90e05ba4253e780c1fb182487-a445cf37"></a>
### [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/mstdd-landing.yml)
 - **Line 27, Column 7**: **[Error: array-length-invalid]** `````Array 'landingContent.linkLists.links' length should be <= 10.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C4%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202205041310154163-5704%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-04T13%3A12%3A11Z&sr=b&sp=r&sig=hebGSjd%2FNHBwU5f8MQYVB8cCkyLLrFFYFViQm%2FHAh%2BA%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-06 05:37 UTC, opbld32 commented
Docs Build status updates of commit _[2ca333a](https://github.com/MicrosoftDocs/msteams-docs/commits/2ca333af87eb5f02c5afe4eb93a578d59e8bb73a)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/mstdd-landing.yml) | :x:Error | | [Details](#user-content-cb2a1ff90e05ba4253e780c1fb182487-9c042f9c)

<a id="cb2a1ff90e05ba4253e780c1fb182487-9c042f9c"></a>
### [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/mstdd-landing.yml)
 - **Line 27, Column 7**: **[Error: array-length-invalid]** `````Array 'landingContent.linkLists.links' length should be <= 10.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C6%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202205060537149022-5704%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-06T05%3A37%3A45Z&sr=b&sp=r&sig=8YkXQllhWQLki6zx%2FwlzifaMdZAOmkNcL1PKrxVLP84%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-06 05:37 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2ca333af87eb5f02c5afe4eb93a578d59e8bb73a/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) | 86 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/791933b8-873e-4f28-81b7-dffb64acf940) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2ca333af87eb5f02c5afe4eb93a578d59e8bb73a/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fnative-device-permissions.md) | 88 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/71f937df-26e2-4b3c-ab2c-655320cd4bde) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/2ca333af87eb5f02c5afe4eb93a578d59e8bb73a/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/80b4120d-5020-40c0-b06c-1d3f5a403f5b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2ca333af87eb5f02c5afe4eb93a578d59e8bb73a/msteams-platform%2Fwhats-new.md) | 92 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bc87e825-89c0-4942-85e3-9b0689739663) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-06 05:41 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/12b74e4db7b59f820158e0a3c457c39fba49874a/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) | 86 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/be377c9d-ce1e-4966-9e89-df8d9045c66f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/12b74e4db7b59f820158e0a3c457c39fba49874a/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fnative-device-permissions.md) | 88 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/904d349b-21a3-4f0b-8c1a-ec7e15473741) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/12b74e4db7b59f820158e0a3c457c39fba49874a/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fa1b3751-ae4a-45ca-ac9e-26d32676c36b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/12b74e4db7b59f820158e0a3c457c39fba49874a/msteams-platform%2Fwhats-new.md) | 92 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/70707e9d-b894-491b-82c4-24887916753b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-06 05:41 UTC, opbld32 commented
Docs Build status updates of commit _[12b74e4](https://github.com/MicrosoftDocs/msteams-docs/commits/12b74e4db7b59f820158e0a3c457c39fba49874a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/tabs/MobileLocationPermission.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/MobileLocationPermission.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/MobilePermissions.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/MobilePermissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/device-permissions.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/device-permissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-desktop.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-desktop.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/location-capability.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/native-device-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/mstdd-landing.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/mstdd-landing?branch=pr-en-us-5704) |
[msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/whats-new.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/whats-new?branch=pr-en-us-5704) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C6%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202205060540264696-5704%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-06T05%3A41%3A25Z&sr=b&sp=r&sig=o2yv0ChVlSD4OMiikja%2FVtzfiAAlZAePekA79tXsgmE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-09 12:48 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4e37ac9c995c97a57adfd589a610299f00c5a48b/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) | 86 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dc45b3ac-2903-4ca9-9985-d4e5f2090064) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4e37ac9c995c97a57adfd589a610299f00c5a48b/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fnative-device-permissions.md) | 88 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f77a9240-8140-4240-821d-e5d09f002673) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/4e37ac9c995c97a57adfd589a610299f00c5a48b/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/444af36e-5473-4e8e-8dad-bb87b9921772) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4e37ac9c995c97a57adfd589a610299f00c5a48b/msteams-platform%2Fwhats-new.md) | 92 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fc092f97-44fa-4c32-bab4-67fc9e390a08) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-09 12:48 UTC, opbld32 commented
Docs Build status updates of commit _[4e37ac9](https://github.com/MicrosoftDocs/msteams-docs/commits/4e37ac9c995c97a57adfd589a610299f00c5a48b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/tabs/MobileLocationPermission.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/MobileLocationPermission.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/MobilePermissions.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/MobilePermissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/device-permissions.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/device-permissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-desktop.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-desktop.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/location-capability.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/native-device-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/mstdd-landing.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/mstdd-landing?branch=pr-en-us-5704) |
[msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/whats-new.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/whats-new?branch=pr-en-us-5704) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C9%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202205091247251035-5704%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-09T12%3A48%3A05Z&sr=b&sp=r&sig=qTrAChmuzPoeYkAGyaCwxvIfJHE2zqzPKIWwF%2FGILt4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-10 04:53 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/10458f50593a0713d738dc48bfdc25c747b7ad46/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) | 86 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4fb5157f-3327-449b-affb-f778e2c4631d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/10458f50593a0713d738dc48bfdc25c747b7ad46/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fnative-device-permissions.md) | 88 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/75c3510d-a02f-461a-8892-dc64aaf50152) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/10458f50593a0713d738dc48bfdc25c747b7ad46/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b0b5fd1d-1c44-4588-9ffb-b2828fbaa156) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/10458f50593a0713d738dc48bfdc25c747b7ad46/msteams-platform%2Fwhats-new.md) | 92 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/856948c1-d8ab-44e6-8f6f-2deaf4282f32) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-10 04:53 UTC, opbld32 commented
Docs Build status updates of commit _[10458f5](https://github.com/MicrosoftDocs/msteams-docs/commits/10458f50593a0713d738dc48bfdc25c747b7ad46)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/tabs/MobileLocationPermission.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/MobileLocationPermission.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/MobilePermissions.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/MobilePermissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/device-permissions.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/device-permissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-desktop.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-desktop.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/location-capability.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/native-device-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/mstdd-landing.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/mstdd-landing?branch=pr-en-us-5704) |
[msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/whats-new.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/whats-new?branch=pr-en-us-5704) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C10%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202205100452223561-5704%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-10T04%3A53%3A26Z&sr=b&sp=r&sig=FE3CClcirqcoosiDe%2FmNGoSR02ylo2EDDTFKAnPBmHA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-10 06:03 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c3bb00ddd6849f5462036f78827df1e7a4dc0351/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) | 88 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/eadd43db-9199-4b10-b389-27446afa7deb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c3bb00ddd6849f5462036f78827df1e7a4dc0351/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fnative-device-permissions.md) | 88 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cdd11fd3-4b41-426c-b4a4-ca5b0cb10cf6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c3bb00ddd6849f5462036f78827df1e7a4dc0351/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cfca0977-730b-4305-a30d-ae62c0b9a371) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c3bb00ddd6849f5462036f78827df1e7a4dc0351/msteams-platform%2Fwhats-new.md) | 92 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1623b2fb-43ca-4ad6-a13a-42ff640b082d) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-10 06:04 UTC, opbld32 commented
Docs Build status updates of commit _[c3bb00d](https://github.com/MicrosoftDocs/msteams-docs/commits/c3bb00ddd6849f5462036f78827df1e7a4dc0351)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/tabs/MobileLocationPermission.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/MobileLocationPermission.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/MobilePermissions.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/MobilePermissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/device-permissions.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/device-permissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-desktop.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-desktop.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/location-capability.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/native-device-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/mstdd-landing.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/mstdd-landing?branch=pr-en-us-5704) |
[msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/whats-new.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/whats-new?branch=pr-en-us-5704) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C10%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202205100603071892-5704%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-10T06%3A04%3A09Z&sr=b&sp=r&sig=0KxrPyiG1SOUNfn4%2BGh2%2FPGKa%2FkaMplljzFfxC041vM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-10 06:06 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/502f9c87c43fcf2347161ccc5fb54dd50e709225/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) | 88 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ca316d8c-20b9-4da9-9187-5a27adb6b282) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/502f9c87c43fcf2347161ccc5fb54dd50e709225/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fnative-device-permissions.md) | 88 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3065f1dd-052d-41a7-a23e-d39e8557998d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/502f9c87c43fcf2347161ccc5fb54dd50e709225/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cf8a0edd-6452-4fd0-b4e0-4044eda8f550) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/502f9c87c43fcf2347161ccc5fb54dd50e709225/msteams-platform%2Fwhats-new.md) | 92 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ecf45d18-ff31-41e3-af78-1345e45f7299) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-10 06:06 UTC, opbld32 commented
Docs Build status updates of commit _[502f9c8](https://github.com/MicrosoftDocs/msteams-docs/commits/502f9c87c43fcf2347161ccc5fb54dd50e709225)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/tabs/MobileLocationPermission.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/MobileLocationPermission.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/MobilePermissions.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/MobilePermissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/device-permissions.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/device-permissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-desktop.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-desktop.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/location-capability.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/native-device-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/mstdd-landing.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/mstdd-landing?branch=pr-en-us-5704) |
[msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/whats-new.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/whats-new?branch=pr-en-us-5704) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C10%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202205100605429505-5704%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-10T06%3A06%3A27Z&sr=b&sp=r&sig=FXsCWTalzI9IGEn8AHkNAdf8lNU9M115GxA%2BkgkJzc4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-10 06:30 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5a036a0892d66ae08e0678360289f5ae743b5f3d/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) | 87 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3a4fb056-ce37-441d-b3e3-e074fcd88312) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5a036a0892d66ae08e0678360289f5ae743b5f3d/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fnative-device-permissions.md) | 88 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/58cce96d-40d9-43c3-8a7c-833cb97bc101) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/5a036a0892d66ae08e0678360289f5ae743b5f3d/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/073dd1b3-8d44-4534-81bf-7d968b2b8ef7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5a036a0892d66ae08e0678360289f5ae743b5f3d/msteams-platform%2Fwhats-new.md) | 92 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/25aa3a62-df8f-40cd-b0d2-c3a76aebb0dd) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-10 06:31 UTC, opbld30 commented
Docs Build status updates of commit _[5a036a0](https://github.com/MicrosoftDocs/msteams-docs/commits/5a036a0892d66ae08e0678360289f5ae743b5f3d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/tabs/MobileLocationPermission.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/MobileLocationPermission.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/MobilePermissions.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/MobilePermissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/device-permissions.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/device-permissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-desktop.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-desktop.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/location-capability.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/native-device-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/mstdd-landing.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/mstdd-landing?branch=pr-en-us-5704) |
[msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/whats-new.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/whats-new?branch=pr-en-us-5704) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C10%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202205100630162227-5704%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-10T06%3A31%3A31Z&sr=b&sp=r&sig=G%2Bgb5654UZMmsDHrNFa9qxFocqMbAIxXIEtKdbZX%2BZA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-10 06:35 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8fc4b23c03ea7b14982e207c1d1e6cccdffa0f04/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) | 87 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/48a9a9f8-25f1-43f4-a965-4e63abc619cd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8fc4b23c03ea7b14982e207c1d1e6cccdffa0f04/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fnative-device-permissions.md) | 88 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/100d8103-f5d5-4981-8ccd-b4794e188d87) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/8fc4b23c03ea7b14982e207c1d1e6cccdffa0f04/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/33230b04-afa4-4424-b308-fd8307fb5e76) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8fc4b23c03ea7b14982e207c1d1e6cccdffa0f04/msteams-platform%2Fwhats-new.md) | 92 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5e252d39-1151-46d4-b1e6-8609219d7358) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-10 06:35 UTC, opbld31 commented
Docs Build status updates of commit _[8fc4b23](https://github.com/MicrosoftDocs/msteams-docs/commits/8fc4b23c03ea7b14982e207c1d1e6cccdffa0f04)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/tabs/MobileLocationPermission.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/MobileLocationPermission.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/MobilePermissions.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/MobilePermissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/device-permissions.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/device-permissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-desktop.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-desktop.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/location-capability.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/native-device-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/mstdd-landing.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/mstdd-landing?branch=pr-en-us-5704) |
[msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/whats-new.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/whats-new?branch=pr-en-us-5704) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C10%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202205100634238882-5704%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-10T06%3A35%3A14Z&sr=b&sp=r&sig=%2BvA7V5z9TT6H1dZE1q9%2F6Lux7STY0SKnTKxQB8ugo2c%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-10 06:50 UTC, opbld32 commented
Docs Build status updates of commit _[10cc877](https://github.com/MicrosoftDocs/msteams-docs/commits/10cc877f05f6641920b0e5023d0c885b5625dff5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/tabs/MobileLocationPermission.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/MobileLocationPermission.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/MobilePermissions.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/MobilePermissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/device-permissions.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/device-permissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-desktop.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-desktop.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/location-capability.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/native-device-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/mstdd-landing.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/mstdd-landing?branch=pr-en-us-5704) |
[msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/whats-new.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/whats-new?branch=pr-en-us-5704) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C10%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202205100650102558-5704%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-10T06%3A50%3A49Z&sr=b&sp=r&sig=tOQKhk2tKu03VdRdtCREY9xHmk5TuDbzc%2BDMXs1JzUI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-10 06:50 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/10cc877f05f6641920b0e5023d0c885b5625dff5/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) | 88 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d97b87be-33e3-4b9f-a672-2c6f03e58a13) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/10cc877f05f6641920b0e5023d0c885b5625dff5/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fnative-device-permissions.md) | 88 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c4b16cae-d2ed-4011-9887-d71d8f22ac38) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/10cc877f05f6641920b0e5023d0c885b5625dff5/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/18311dde-727c-444c-be09-d5381fd36915) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/10cc877f05f6641920b0e5023d0c885b5625dff5/msteams-platform%2Fwhats-new.md) | 92 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f253732e-4e5e-4957-b7a5-0841f66f50cd) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-10 07:00 UTC, opbld31 commented
Docs Build status updates of commit _[a9975a8](https://github.com/MicrosoftDocs/msteams-docs/commits/a9975a8c9ff15df1a6e31c1b3600708eeb7eddc1)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-10 07:01 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a9975a8c9ff15df1a6e31c1b3600708eeb7eddc1/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) | 88 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/28c81588-de5d-43fe-908e-b27cc95bf045) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a9975a8c9ff15df1a6e31c1b3600708eeb7eddc1/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fnative-device-permissions.md) | 88 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b9da4f6e-d5c7-4e71-9793-00da143a776f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a9975a8c9ff15df1a6e31c1b3600708eeb7eddc1/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/121da67d-e069-44e6-bb82-d56da41a0d9d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a9975a8c9ff15df1a6e31c1b3600708eeb7eddc1/msteams-platform%2Fwhats-new.md) | 92 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a3d95ec9-29a9-41cc-9a57-51bd37e2adac) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-10 07:12 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/06fad51906a5906ae6784d7030419e637bb082f5/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) | 88 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/71b2a8ec-3bc6-491b-b1fe-01f7aed9c274) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/06fad51906a5906ae6784d7030419e637bb082f5/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fnative-device-permissions.md) | 88 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d094591c-4679-4bc6-92dc-4346a31d9c38) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/06fad51906a5906ae6784d7030419e637bb082f5/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9c2d73ad-5145-4021-9525-c2d66459b425) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/06fad51906a5906ae6784d7030419e637bb082f5/msteams-platform%2Fwhats-new.md) | 92 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2688179f-8962-4f5a-a0d0-055fc41d7fd8) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-10 07:13 UTC, opbld30 commented
Docs Build status updates of commit _[06fad51](https://github.com/MicrosoftDocs/msteams-docs/commits/06fad51906a5906ae6784d7030419e637bb082f5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/tabs/MobileLocationPermission.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/MobileLocationPermission.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/MobilePermissions.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/MobilePermissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/device-permissions.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/device-permissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-desktop.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-desktop.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/location-capability.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/native-device-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/mstdd-landing.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/mstdd-landing?branch=pr-en-us-5704) |
[msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/whats-new.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/whats-new?branch=pr-en-us-5704) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202205100712060570-5704/BuildReport?accessString=cd6868262adbcd7d9ca4c1c89e4bf315f0d64d06980073dd226a48235fdd1db5).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-23 12:05 UTC, shuchauh requested changes
Kindly address the feedback before merging changes. Thanks! :)

2022-05-23 12:05 UTC, shuchauh commented on msteams-platform/concepts/device-capabilities/native-device-permissions.md
> -> * Support for `location` is enabled through [**getLocation API**](/javascript/api/@microsoft/teams-js/microsoftteams.location?view=msteams-client-js-latest#getLocation_LocationProps___error__SdkErr
Why did we remove the HTML5 part? It's still not supported.

2022-05-23 12:05 UTC, shuchauh commented on msteams-platform/concepts/device-capabilities/native-device-permissions.md
> -* To capture the image on mobile, Teams mobile asks for permission when you call `captureImage()`:
captureImage is only supported on mobile. Let's revert.

2022-05-23 12:05 UTC, shuchauh commented on msteams-platform/concepts/device-capabilities/native-device-permissions.md
> +* To use the camera or access photo gallery, Teams app asks permission when you call `selectMedia()`:
This is only supported on mobile. Let's revert.

2022-05-23 12:05 UTC, shuchauh commented on msteams-platform/concepts/device-capabilities/native-device-permissions.md
> +* To prompt the user to share location on the map interface, Teams app asks permission when you call `getLocation()`:
This is only supported on mobile. Let's revert.

2022-05-26 04:45 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5ccbf872c158e1808508dbd6e20f33de7d9c817c/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) | 88 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/076a8e16-e699-48e8-b653-5340350f4187) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5ccbf872c158e1808508dbd6e20f33de7d9c817c/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fnative-device-permissions.md) | 88 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/40ce3d10-5397-4e22-9f8f-bcabd384edf7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/5ccbf872c158e1808508dbd6e20f33de7d9c817c/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0a63a3b9-7695-45c4-9b18-5d72d013b778) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5ccbf872c158e1808508dbd6e20f33de7d9c817c/msteams-platform%2Fwhats-new.md) | 91 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a9a7d17c-bd5b-4871-bdb6-ef5f56269635) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-26 04:46 UTC, opbld32 commented
Docs Build status updates of commit _[5ccbf87](https://github.com/MicrosoftDocs/msteams-docs/commits/5ccbf872c158e1808508dbd6e20f33de7d9c817c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/tabs/MobileLocationPermission.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/MobileLocationPermission.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/MobilePermissions.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/MobilePermissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/device-permissions.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/device-permissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-desktop.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-desktop.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/location-capability.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/native-device-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/mstdd-landing.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/mstdd-landing?branch=pr-en-us-5704) |
[msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/whats-new.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/whats-new?branch=pr-en-us-5704) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202205260444594443-5704/BuildReport?accessString=4898ae76934b149a2e218c58fd46ba27a7d0ff1d8a3ccc7072abd22509832fb4).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-26 05:32 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a30e805e0ab4eb795655057355fba57fe384fd58/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) | 88 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6ae8c043-5466-4fca-91e5-d049b9ee98cf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a30e805e0ab4eb795655057355fba57fe384fd58/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fnative-device-permissions.md) | 89 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a3add6d6-3511-427d-997c-3271f99f50c7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a30e805e0ab4eb795655057355fba57fe384fd58/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6797fa08-e93e-4a09-bdbd-e472ab8ccb8f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a30e805e0ab4eb795655057355fba57fe384fd58/msteams-platform%2Fwhats-new.md) | 91 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/64342d6a-f5bd-4cc3-8f39-807c4ef411b5) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-26 05:32 UTC, opbld33 commented
Docs Build status updates of commit _[a30e805](https://github.com/MicrosoftDocs/msteams-docs/commits/a30e805e0ab4eb795655057355fba57fe384fd58)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/tabs/MobileLocationPermission.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/MobileLocationPermission.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/MobilePermissions.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/MobilePermissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/device-permissions.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/device-permissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-desktop.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-desktop.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/location-capability.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/native-device-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/mstdd-landing.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/mstdd-landing?branch=pr-en-us-5704) |
[msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/whats-new.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/whats-new?branch=pr-en-us-5704) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202205260531121325-5704/BuildReport?accessString=ee8e1d5865b1c4546e309a4258b320da637f33a22c9f7a37af1fa99daeb66e6f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-26 05:40 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/406de2c6124d4e4426d0cd45f3020b14b3cb2816/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) | 89 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8bfc77c9-6e4f-4853-a529-dca948107414) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/406de2c6124d4e4426d0cd45f3020b14b3cb2816/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fnative-device-permissions.md) | 89 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0b5524f9-6e89-4c7f-9285-f7eac309e6cf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/406de2c6124d4e4426d0cd45f3020b14b3cb2816/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b559c49e-bc1b-4b7d-8df7-848230d06d45) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/406de2c6124d4e4426d0cd45f3020b14b3cb2816/msteams-platform%2Fwhats-new.md) | 91 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2ced4d96-8620-4cac-9616-a4d24785de0c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-26 05:40 UTC, opbld30 commented
Docs Build status updates of commit _[406de2c](https://github.com/MicrosoftDocs/msteams-docs/commits/406de2c6124d4e4426d0cd45f3020b14b3cb2816)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/tabs/MobileLocationPermission.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/MobileLocationPermission.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/MobilePermissions.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/MobilePermissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/device-permissions.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/device-permissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-desktop.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-desktop.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/location-capability.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/native-device-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/mstdd-landing.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/mstdd-landing?branch=pr-en-us-5704) |
[msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/whats-new.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/whats-new?branch=pr-en-us-5704) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202205260539394652-5704/BuildReport?accessString=12e9cee28f3049722bc524c97bef9c9bc23a11eb72be91eae0e2a7886854900f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-30 06:02 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/de6ae2eedddb6b56b5f052704bd2a7573d6980f3/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) | 89 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8698ad43-79e9-42f7-90a0-0ecb4f10d52b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/de6ae2eedddb6b56b5f052704bd2a7573d6980f3/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fnative-device-permissions.md) | 94 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1aff8677-ed67-4695-9043-7ac6e8a80dd2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/de6ae2eedddb6b56b5f052704bd2a7573d6980f3/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/28e9f3e3-f36e-4ad3-a594-bf0effb2f9ca) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/de6ae2eedddb6b56b5f052704bd2a7573d6980f3/msteams-platform%2Fwhats-new.md) | 91 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4f07a182-5c8c-4f68-9e59-77fa329a98ad) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-30 06:05 UTC, opbld31 commented
Docs Build status updates of commit _[de6ae2e](https://github.com/MicrosoftDocs/msteams-docs/commits/de6ae2eedddb6b56b5f052704bd2a7573d6980f3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/tabs/MobileLocationPermission.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/MobileLocationPermission.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/MobilePermissions.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/MobilePermissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/device-permissions.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/device-permissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-desktop.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-desktop.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/location-capability.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/native-device-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/mstdd-landing.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/mstdd-landing?branch=pr-en-us-5704) |
[msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/whats-new.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/whats-new?branch=pr-en-us-5704) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202205300602029433-5704/BuildReport?accessString=51dc1ec3ee77ba8e507dd48550b0bf67c9a52190356b60de96c744f185b04f93).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-30 07:36 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b6146128d198ed98d93eac1d46072eb8c0f47708/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) | 89 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9a2cfde8-d00f-413f-84ac-0131b7b62ad7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b6146128d198ed98d93eac1d46072eb8c0f47708/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fnative-device-permissions.md) | 94 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1faedded-bddb-4425-9245-ab4cf64b1263) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/b6146128d198ed98d93eac1d46072eb8c0f47708/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b61cb754-510c-47f1-8883-aed2c4fc50a8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b6146128d198ed98d93eac1d46072eb8c0f47708/msteams-platform%2Fwhats-new.md) | 91 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/526c7403-8cea-4aab-94e9-f6e7470e22fb) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-30 07:38 UTC, opbld32 commented
Docs Build status updates of commit _[b614612](https://github.com/MicrosoftDocs/msteams-docs/commits/b6146128d198ed98d93eac1d46072eb8c0f47708)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/tabs/MobileLocationPermission.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/MobileLocationPermission.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/MobilePermissions.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/MobilePermissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/device-permissions.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/device-permissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-desktop.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-desktop.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/location-capability.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/native-device-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/mstdd-landing.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/mstdd-landing?branch=pr-en-us-5704) |
[msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/whats-new.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/whats-new?branch=pr-en-us-5704) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202205300735231097-5704/BuildReport?accessString=c17fa79e07d0028eef98e3775793735dc5b5cb28fb749016707eef3cabff772f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-01 04:37 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bef2bad1fb467a372ffb3c6f10b891b312f542c0/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) | 89 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/519ded09-987c-40fd-b0c2-1f1e85e09f6b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bef2bad1fb467a372ffb3c6f10b891b312f542c0/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fnative-device-permissions.md) | 94 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/11485688-af86-4433-8605-0a727690b06d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/bef2bad1fb467a372ffb3c6f10b891b312f542c0/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/31173513-6fc3-40a6-892f-925154f25d3b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bef2bad1fb467a372ffb3c6f10b891b312f542c0/msteams-platform%2Fwhats-new.md) | 91 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/82c93e97-1fcc-4ff1-9b70-8f68be0f5fbe) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-06-01 04:38 UTC, opbld30 commented
Docs Build status updates of commit _[bef2bad](https://github.com/MicrosoftDocs/msteams-docs/commits/bef2bad1fb467a372ffb3c6f10b891b312f542c0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/tabs/MobileLocationPermission.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/MobileLocationPermission.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/MobilePermissions.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/MobilePermissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/device-permissions.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/device-permissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-desktop.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-desktop.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/location-capability.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/native-device-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/mstdd-landing.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/mstdd-landing?branch=pr-en-us-5704) |
[msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/whats-new.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/whats-new?branch=pr-en-us-5704) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202206010437022757-5704/BuildReport?accessString=2f40c2a414f69ef52bc2eedbea0bdef11df407bac4dcb71fba2858c2f0002b69).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-07 10:57 UTC, opbld32 commented
Docs Build status updates of commit _[42075a5](https://github.com/MicrosoftDocs/msteams-docs/commits/42075a5022eca6ccb6d36c104fd81e205579fc1e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/tabs/MobileLocationPermission.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/MobileLocationPermission.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/MobilePermissions.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/MobilePermissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/device-permissions.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/device-permissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-desktop.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-desktop.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/location-capability.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/native-device-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/mstdd-landing.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/mstdd-landing?branch=pr-en-us-5704) |
[msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/whats-new.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/whats-new?branch=pr-en-us-5704) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202206071056509531-5704/BuildReport?accessString=5390490c20cd4db5258f962f34c576fab698a3db7e9a208acff3299149248044).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-07 10:57 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/42075a5022eca6ccb6d36c104fd81e205579fc1e/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) | 89 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5d990c93-020f-4272-8bd4-b381fefdf6dd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/42075a5022eca6ccb6d36c104fd81e205579fc1e/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fnative-device-permissions.md) | 94 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/af849eee-750a-44f9-aa0b-bbce26ac4ec4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/42075a5022eca6ccb6d36c104fd81e205579fc1e/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/09741cf7-46e3-4824-b44b-4f093e7715e0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/42075a5022eca6ccb6d36c104fd81e205579fc1e/msteams-platform%2Fwhats-new.md) | 91 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8e348f49-ae65-452f-b24e-dc5167aa3501) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-06-08 03:56 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c460ab09c1d680f8cfd5ab09136634e07ad8f4e9/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) | 89 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a4cf600e-8a49-4a09-add0-7688c6ec37c0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c460ab09c1d680f8cfd5ab09136634e07ad8f4e9/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fnative-device-permissions.md) | 94 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/292fed83-31a0-4b56-9c8f-70cc82c417d6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c460ab09c1d680f8cfd5ab09136634e07ad8f4e9/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/122496f0-3b5e-4708-8bce-b5ceb0f2d8c9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c460ab09c1d680f8cfd5ab09136634e07ad8f4e9/msteams-platform%2Fwhats-new.md) | 91 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/85160dbb-cb87-448a-ae02-a4032b8c6edb) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-06-08 03:57 UTC, opbld33 commented
Docs Build status updates of commit _[c460ab0](https://github.com/MicrosoftDocs/msteams-docs/commits/c460ab09c1d680f8cfd5ab09136634e07ad8f4e9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/tabs/MobileLocationPermission.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/MobileLocationPermission.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/MobilePermissions.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/MobilePermissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/device-permissions.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/device-permissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-desktop.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-desktop.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/location-capability.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/native-device-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/mstdd-landing.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/mstdd-landing?branch=pr-en-us-5704) |
[msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/whats-new.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/whats-new?branch=pr-en-us-5704) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202206080356104745-5704/BuildReport?accessString=07338da13d32255176f4a67f184383f97dc3d93d36af907d7770b93d752805c9).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-08 04:15 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6e4eaf85836859a4b8b09e8cfa8cb3930fbcf8f7/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/48e3e05c-9d13-4238-94c6-b16264407c3a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6e4eaf85836859a4b8b09e8cfa8cb3930fbcf8f7/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fnative-device-permissions.md) | 94 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b3ceb209-55de-476b-8905-11ba315f7966) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/6e4eaf85836859a4b8b09e8cfa8cb3930fbcf8f7/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/71d56981-975c-4fcf-a6ac-866887870579) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6e4eaf85836859a4b8b09e8cfa8cb3930fbcf8f7/msteams-platform%2Fwhats-new.md) | 91 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9b858f81-1dc4-42c3-8478-7890e5e13a21) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-06-08 04:16 UTC, opbld30 commented
Docs Build status updates of commit _[6e4eaf8](https://github.com/MicrosoftDocs/msteams-docs/commits/6e4eaf85836859a4b8b09e8cfa8cb3930fbcf8f7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/tabs/MobileLocationPermission.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/MobileLocationPermission.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/MobilePermissions.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/MobilePermissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/device-permissions.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/device-permissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-desktop.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-desktop.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/location-capability.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/native-device-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/mstdd-landing.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/mstdd-landing?branch=pr-en-us-5704) |
[msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/whats-new.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/whats-new?branch=pr-en-us-5704) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202206080415007629-5704/BuildReport?accessString=9ecef319efbaeec1d94e24f2da51ceed389cde986e7f34411654bbdcde19b27d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-08 04:45 UTC, opbld32 commented
Docs Build status updates of commit _[4f10966](https://github.com/MicrosoftDocs/msteams-docs/commits/4f109662c85db5e91f0c1011d0a73c480cc8e81d)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-b210ef03)

<a id="b210ef03"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202206080444435182-5704/BuildReport?accessString=3296def968830129bcd66eb3d0d22df647fc6a5c0bc7bd6b26f038d59acbec87).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-08 04:45 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4f109662c85db5e91f0c1011d0a73c480cc8e81d/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bddaead8-7b42-41c8-b8e7-c8c85071e960) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4f109662c85db5e91f0c1011d0a73c480cc8e81d/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fnative-device-permissions.md) | 94 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c168daf4-8ab3-4c5b-979c-19cb46f06021) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/4f109662c85db5e91f0c1011d0a73c480cc8e81d/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4a530407-5c72-4b00-b9fa-24984da2b0eb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4f109662c85db5e91f0c1011d0a73c480cc8e81d/msteams-platform%2Fwhats-new.md) | 91 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6c377216-bdd8-46f1-906d-cfe896f112c3) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-06-08 07:58 UTC, opbld32 commented
Docs Build status updates of commit _[53bcb60](https://github.com/MicrosoftDocs/msteams-docs/commits/53bcb6002c8cf6b6fa2bcd0a2f60c87ecd278992)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/location-capability.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) | [Details](#user-content-0a4769b3701b815d94d2e807526f75ed-27f2d69a)
[msteams-platform/assets/images/tabs/MobileLocationPermission.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/MobileLocationPermission.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/MobilePermissions.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/MobilePermissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/device-permissions.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/device-permissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-desktop.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-desktop.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/native-device-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/mstdd-landing.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/mstdd-landing?branch=pr-en-us-5704) |
[msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/whats-new.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/whats-new?branch=pr-en-us-5704) |

<a id="0a4769b3701b815d94d2e807526f75ed-27f2d69a"></a>
### [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/location-capability.md)
 - **Line 73, Column 1**: **[Warning: invalid-note-section]** `````Text in the first line of Note/Section/Video is not valid. Will be rendered to <blockquote>`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202206080757161000-5704/BuildReport?accessString=71d41d825d730e1c8e82e1a5beec7dcca3a54fb0503545c839da69170c651866).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-08 07:58 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/53bcb6002c8cf6b6fa2bcd0a2f60c87ecd278992/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d3690f87-1351-4c5a-9637-d7a26b31db70) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/53bcb6002c8cf6b6fa2bcd0a2f60c87ecd278992/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fnative-device-permissions.md) | 94 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cbeba932-fa2a-4bfd-a1a2-e5e90892b613) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/53bcb6002c8cf6b6fa2bcd0a2f60c87ecd278992/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b1895497-1425-44e9-8d48-68d3f51e9f6b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/53bcb6002c8cf6b6fa2bcd0a2f60c87ecd278992/msteams-platform%2Fwhats-new.md) | 91 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e0fbd59b-c46e-48c6-a214-c4c061b28021) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-06-08 08:04 UTC, opbld32 commented
Docs Build status updates of commit _[bd07be4](https://github.com/MicrosoftDocs/msteams-docs/commits/bd07be437438c57a5d7966659eda2b177a793e2e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/tabs/MobileLocationPermission.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/MobileLocationPermission.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/MobilePermissions.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/MobilePermissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/device-permissions.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/device-permissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-desktop.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-desktop.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/location-capability.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/native-device-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/mstdd-landing.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/mstdd-landing?branch=pr-en-us-5704) |
[msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/whats-new.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/whats-new?branch=pr-en-us-5704) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202206080802365211-5704/BuildReport?accessString=b9a6db5dd9b597349f427282a95b80648d227e9c76ea216eba3f4f40fa64cca6).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-08 08:05 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bd07be437438c57a5d7966659eda2b177a793e2e/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/be22c049-89f9-455b-ae8c-1f22eb7c3d57) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bd07be437438c57a5d7966659eda2b177a793e2e/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fnative-device-permissions.md) | 94 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/200ca2e8-644b-49d7-9757-bdac34264bc2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/bd07be437438c57a5d7966659eda2b177a793e2e/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/811bc015-8882-473e-aa61-fc74fbca027a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bd07be437438c57a5d7966659eda2b177a793e2e/msteams-platform%2Fwhats-new.md) | 91 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/268056dd-c962-4559-a7b6-ccf9df4bf334) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-06-08 08:07 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/333a56b58fe463e66414cd06d71c16cea8232f13/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/31d5c68d-687f-494b-a3eb-397ed9945dce) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/333a56b58fe463e66414cd06d71c16cea8232f13/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fnative-device-permissions.md) | 94 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1e51ead0-0288-4290-b1f3-39d59b791fac) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/333a56b58fe463e66414cd06d71c16cea8232f13/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/921307e9-e5a7-4f2e-95f2-420f72a6e739) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/333a56b58fe463e66414cd06d71c16cea8232f13/msteams-platform%2Fwhats-new.md) | 91 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e23a409f-7490-4990-a242-bf0bf05e0233) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-06-08 08:07 UTC, opbld33 commented
Docs Build status updates of commit _[333a56b](https://github.com/MicrosoftDocs/msteams-docs/commits/333a56b58fe463e66414cd06d71c16cea8232f13)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/tabs/MobileLocationPermission.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/MobileLocationPermission.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/MobilePermissions.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/MobilePermissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/device-permissions.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/device-permissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-desktop.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-desktop.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/location-capability.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/native-device-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/mstdd-landing.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/mstdd-landing?branch=pr-en-us-5704) |
[msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/whats-new.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/whats-new?branch=pr-en-us-5704) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202206080806394599-5704/BuildReport?accessString=15c54af9580caee5244c7c82223d14c64e2d2f0857485bb5a0f82fb133ae202d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-08 12:35 UTC, shuchauh commented on msteams-platform/concepts/device-capabilities/location-capability.md
> +
Let's remove this note. Not required here as it's implicitly applicable to all APIs.

2022-06-08 12:38 UTC, shuchauh commented on msteams-platform/concepts/device-capabilities/location-capability.md
> +> [!NOTE]
Can we change it to "Important"?

2022-06-09 08:37 UTC, opbld31 commented
Docs Build status updates of commit _[8ff617d](https://github.com/MicrosoftDocs/msteams-docs/commits/8ff617d3b7e07511aa3451d5106820dead7143e7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/tabs/MobileLocationPermission.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/MobileLocationPermission.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/MobilePermissions.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/MobilePermissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/device-permissions.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/device-permissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-desktop.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-desktop.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/location-capability.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/native-device-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/mstdd-landing.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/mstdd-landing?branch=pr-en-us-5704) |
[msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/whats-new.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/whats-new?branch=pr-en-us-5704) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202206090836566687-5704/BuildReport?accessString=dbb75d3020e3770e94000608c5db84fb9a15a82f70ea389e7a47df94d25bfe10).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-09 08:37 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8ff617d3b7e07511aa3451d5106820dead7143e7/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/333eb5f3-8a1f-4913-a86e-50d250a9a8f5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8ff617d3b7e07511aa3451d5106820dead7143e7/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fnative-device-permissions.md) | 94 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b5b890a7-0225-42a8-8303-1e15e0453570) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/8ff617d3b7e07511aa3451d5106820dead7143e7/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2f245025-13bb-45f8-af32-7bb374c38fd3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8ff617d3b7e07511aa3451d5106820dead7143e7/msteams-platform%2Fwhats-new.md) | 89 | 42 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/40474624-3aa1-4ce2-8f48-fa6d05339648) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-06-09 08:46 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bc43a375a3a74b4d01d05b289b89cb58344d7079/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) | 89 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a8de8042-51b9-4dcf-a0f5-37e73bfb7038) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bc43a375a3a74b4d01d05b289b89cb58344d7079/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fnative-device-permissions.md) | 94 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1bcc3183-2465-499f-95e3-073c66c08cc3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/bc43a375a3a74b4d01d05b289b89cb58344d7079/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5ebe0e6d-4239-495a-802e-7dddc499f7ff) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bc43a375a3a74b4d01d05b289b89cb58344d7079/msteams-platform%2Fwhats-new.md) | 89 | 42 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fac3c729-f9bc-446f-a21a-9235c4412db1) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-06-09 08:46 UTC, opbld33 commented
Docs Build status updates of commit _[bc43a37](https://github.com/MicrosoftDocs/msteams-docs/commits/bc43a375a3a74b4d01d05b289b89cb58344d7079)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/tabs/MobileLocationPermission.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/MobileLocationPermission.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/MobilePermissions.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/MobilePermissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/device-permissions.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/device-permissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-desktop.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-desktop.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/location-capability.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/device-capabilities/native-device-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/mstdd-landing.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/mstdd-landing?branch=pr-en-us-5704) |
[msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/whats-new.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/whats-new?branch=pr-en-us-5704) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202206090845252124-5704/BuildReport?accessString=188f5d3038f42b3fd2ff760fbf4079f586bade82d8f4503e2d0b59dba3f85685).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-22 11:57 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/726b9b13054de8050be679a344353bb15bfc1866/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) | 90 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/09bc911e-8709-4953-a934-f843f7710014) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/726b9b13054de8050be679a344353bb15bfc1866/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fnative-device-permissions.md) | 91 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fe458204-83b3-45d1-874e-bd9946f2fad8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/726b9b13054de8050be679a344353bb15bfc1866/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dcdccf50-6094-4d6f-ad6e-fd1b8a1e218b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/726b9b13054de8050be679a344353bb15bfc1866/msteams-platform%2Fwhats-new.md) | 91 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9625a397-3599-4124-b864-f2ecc32b4bfc) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-09-22 11:58 UTC, opbld32 commented
Docs Build status updates of commit _[726b9b1](https://github.com/MicrosoftDocs/msteams-docs/commits/726b9b13054de8050be679a344353bb15bfc1866)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/concepts/device-capabilities/location-capability.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) | [Details](#user-content-0a4769b3701b815d94d2e807526f75ed-a008333c)
[msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/concepts/device-capabilities/native-device-permissions.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) | [Details](#user-content-dfdd0e708ea7bf1bd86a5755bdf35897-a008333c)
[msteams-platform/assets/images/tabs/device-permissions.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/device-permissions.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-desktop.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-desktop.PNG) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/location-picker-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/location-picker-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/MobileLocationPermission.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/MobileLocationPermission.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/assets/images/tabs/MobilePermissions.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/assets/images/tabs/MobilePermissions.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?branch=pr-en-us-5704) |
[msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/mstdd-landing.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/mstdd-landing?branch=pr-en-us-5704) |
[msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/whats-new.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/whats-new?branch=pr-en-us-5704) |

<a id="0a4769b3701b815d94d2e807526f75ed-a008333c"></a>
### [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/concepts/device-capabilities/location-capability.md)
 - **Line 84, Column 1**: **[Warning: duplicate-h2s - [See documentation](https://review.learn.microsoft.com/en-us/help/contribute/validation-ref/duplicate-h2s?branch=master)]** `````Duplicate heading: 'H2 'Error handling''. Each second level heading (H2) in an article must be unique.`````
 - **Line 162, Column 1**: **[Warning: duplicate-h2s - [See documentation](https://review.learn.microsoft.com/en-us/help/contribute/validation-ref/duplicate-h2s?branch=master)]** `````Duplicate heading: 'H2 'Error handling''. Each second level heading (H2) in an article must be unique.`````

<a id="dfdd0e708ea7bf1bd86a5755bdf35897-a008333c"></a>
### [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-location-api/msteams-platform/concepts/device-capabilities/native-device-permissions.md)
 - **Line 14, Column 91**: **[Warning: file-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'mobile-camera-image-permissions.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202209221157465430-5704/BuildReport?accessString=ae5f9449b2ecdfd03eff23e41dc30673e47835a48177666a4985415407670a4d).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-11-23 06:05 UTC, v-amprasad commented
Copied the content to PR#: 7500.

2022-11-23 11:16 UTC, shuchauh commented on msteams-platform/concepts/device-capabilities/native-device-permissions.md
> +> * To integrate media capabilities within your Teams web client, desktop, and mobile see [Integrate media capabilities](mobile-camera-image-permissions.md).
Repetitive to the 2nd bullet point. Kindly remove one.

2022-11-23 11:21 UTC, v-abirade commented on msteams-platform/concepts/device-capabilities/location-capability.md
>  You can use [Microsoft Teams JavaScript client SDK](/javascript/api/overview/msteams-client?view=msteams-client-js-latest&preserve-view=true), which provides the tools necessary for your app to acces
@v-amprasad, please work on the changes, suggested by Shubham.

2022-11-23 11:25 UTC, shuchauh commented on msteams-platform/concepts/device-capabilities/location-capability.md
> +> `showMap` conditions for True and False:<br> - True: Show location on map <br> - False: Do not show location on map <br>-(false,false): This configuration is only supported on mobile <br> -If `allo
```suggestion
> <br> -If `allowChooseLocation` is set to true, then `showMap` is ignored.<br> -`showMap`= false is not supported on Teams web or desktop.
```

2022-11-23 11:26 UTC, shuchauh commented on msteams-platform/concepts/device-capabilities/location-capability.md
> +> Further, you must provide a hypertext link to Bing Maps TOU, which is located here, either at the bottom of each page in your Application where the services can be accessed or viewed or within the
Kindly hyperlink the URLs

2022-11-23 11:27 UTC, shuchauh requested changes
Dropped in comments requesting changes. Thanks!

2022-11-23 11:29 UTC, v-abirade commented on msteams-platform/concepts/device-capabilities/location-capability.md
> +The following image depicts web app experience of getLocation API:
> Dropped in comments requesting changes. Thanks!

Thanks @shuchauh, Aman will work on the comments and share the link with you.

2022-11-23 11:42 UTC, v-amprasad commented on msteams-platform/concepts/device-capabilities/location-capability.md
>  You can use [Microsoft Teams JavaScript client SDK](/javascript/api/overview/msteams-client?view=msteams-client-js-latest&preserve-view=true), which provides the tools necessary for your app to acces
The repetitive line has been removed to adjust to the flow and move to the advantages.

2022-11-23 11:47 UTC, v-amprasad commented on msteams-platform/concepts/device-capabilities/location-capability.md
> +The following image depicts web app experience of getLocation API:
Can you confirm if this is the correct image? 
![image](https://user-images.githubusercontent.com/108111416/203539302-39a61109-2f06-451e-b499-79f72c44bd24.png)

2022-11-23 11:58 UTC, v-amprasad commented on msteams-platform/concepts/device-capabilities/location-capability.md
> +> Further, you must provide a hypertext link to Bing Maps TOU, which is located here, either at the bottom of each page in your Application where the services can be accessed or viewed or within the
Updated as hyperlinks

2022-11-23 12:19 UTC, shuchauh commented on msteams-platform/concepts/device-capabilities/location-capability.md
> +The following image depicts web app experience of getLocation API:
No, I was referring to the web image. The mobile one is fine.

2022-11-23 13:32 UTC, v-abirade commented
Closing the PR as the content have been added to PR #7500

2022-11-23 13:32 UTC, closed without merging