[Doc Feature][Enable-deeplink-meeting-sidepanel][2266740]
MicrosoftDocs/msteams-docs pull request #5715
Opened 2022-04-12 11:24 UTC by v-npaladugu

2022-04-12 11:24 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c4d943723fed605a6266ddb3503d6823e738f570/msteams-platform%2Fapps-in-teams-meetings%2Fenable-and-configure-your-app-for-teams-meetings.md) | 94 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3d4271dc-d7be-4f16-8974-eee6724d9199) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-13 10:23 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6d25b8e9826339ebb3da4f8532bb47da46f8ed4c/msteams-platform%2Fapps-in-teams-meetings%2Fenable-and-configure-your-app-for-teams-meetings.md) | 95 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/52bf61c2-4b0d-4253-be3a-a84ef37ea235) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-13 10:23 UTC, opbld30 commented
Docs Build status updates of commit _[6d25b8e](https://github.com/MicrosoftDocs/msteams-docs/commits/6d25b8e9826339ebb3da4f8532bb47da46f8ed4c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-feature-deeplink-meeting-sidepanel/msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings?branch=pr-en-us-5715) | [Details](#user-content-10577a9a92399b7aac17adcc0eed17ef-c37ba332)

<a id="10577a9a92399b7aac17adcc0eed17ef-c37ba332"></a>
### [msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-feature-deeplink-meeting-sidepanel/msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md)
 - **Line 125, Column 53**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '~/concepts/build-and-test/deep-links'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C13%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204131022412048-5715%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-14T10%3A23%3A28Z&sr=b&sp=r&sig=n%2FAnv6Sid0qBX%2F33h2BlczjDizWLOjZBvAA4fuXCSe4%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-13 10:25 UTC, opbld30 commented
Docs Build status updates of commit _[6d95109](https://github.com/MicrosoftDocs/msteams-docs/commits/6d95109f44a0c32846b7af39f6f7972a129f107f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-feature-deeplink-meeting-sidepanel/msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings?branch=pr-en-us-5715) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C13%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204131024476371-5715%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-14T10%3A25%3A38Z&sr=b&sp=r&sig=TNpfZvc3b7nCXU8NGNZ2GlNJsezRoSIlht3EyZsPLwE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-13 10:26 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6d95109f44a0c32846b7af39f6f7972a129f107f/msteams-platform%2Fapps-in-teams-meetings%2Fenable-and-configure-your-app-for-teams-meetings.md) | 95 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e4a0534f-138c-43ab-81bc-6b7e662edc66) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-13 11:18 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/52b6134da32dad6d8e3f91d5493392c0a0432f94/msteams-platform%2Fapps-in-teams-meetings%2Fenable-and-configure-your-app-for-teams-meetings.md) | 95 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e9091269-61ed-42ef-ba0c-6772fff424c5) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-13 11:18 UTC, opbld31 commented
Docs Build status updates of commit _[52b6134](https://github.com/MicrosoftDocs/msteams-docs/commits/52b6134da32dad6d8e3f91d5493392c0a0432f94)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-feature-deeplink-meeting-sidepanel/msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings?branch=pr-en-us-5715) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C13%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204131117528458-5715%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-14T11%3A18%3A53Z&sr=b&sp=r&sig=xTm%2BiyBAeM%2BrXUDnrm7fzRi189aHWsLeK3XmJVb5ItA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-20 10:55 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bb87ae3734f5ed3af4ece7f9aa01db6df9389f4e/msteams-platform%2Fapps-in-teams-meetings%2Fenable-and-configure-your-app-for-teams-meetings.md) | 95 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0bdcebaa-f983-437c-8269-fcbfe691d697) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-20 10:56 UTC, opbld31 commented
Docs Build status updates of commit _[bb87ae3](https://github.com/MicrosoftDocs/msteams-docs/commits/bb87ae3734f5ed3af4ece7f9aa01db6df9389f4e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings?branch=pr-en-us-5715) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C20%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204201055222865-5715%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-21T10%3A56%3A13Z&sr=b&sp=r&sig=YGtTrGYqFnBemvdSFiP9OSyrCMrP6HRQKadj%2BPVSF%2F4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-20 11:42 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e3e1ba784d5b13815d9e5576d4fc0eba8e3aafb2/msteams-platform%2Fapps-in-teams-meetings%2Fenable-and-configure-your-app-for-teams-meetings.md) | 96 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/202cefba-55ab-434c-91b9-32d3e6e77d9e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e3e1ba784d5b13815d9e5576d4fc0eba8e3aafb2/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-links.md) | 82 | 52 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/22401e13-4770-4aae-8915-2d8936fa191b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-20 11:42 UTC, opbld32 commented
Docs Build status updates of commit _[e3e1ba7](https://github.com/MicrosoftDocs/msteams-docs/commits/e3e1ba784d5b13815d9e5576d4fc0eba8e3aafb2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings?branch=pr-en-us-5715) |
[msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/build-and-test/deep-links.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links?branch=pr-en-us-5715) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C20%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204201142223884-5715%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-21T11%3A42%3A53Z&sr=b&sp=r&sig=c53Kpb9cc0CvDh2FJZoT2s%2FjQ8vh9H8wVqexwQABK%2BA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-25 07:14 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/72c0ea0d8e99fab06639fa69ebf351e7122feab9/msteams-platform%2Fapps-in-teams-meetings%2Fenable-and-configure-your-app-for-teams-meetings.md) | 96 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c07195b7-b269-426d-afb3-86b6037a335b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/72c0ea0d8e99fab06639fa69ebf351e7122feab9/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-links.md) | 82 | 52 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/75689656-7114-4612-9845-11b0da499f96) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-25 07:15 UTC, opbld31 commented
Docs Build status updates of commit _[72c0ea0](https://github.com/MicrosoftDocs/msteams-docs/commits/72c0ea0d8e99fab06639fa69ebf351e7122feab9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings?branch=pr-en-us-5715) |
[msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/build-and-test/deep-links.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links?branch=pr-en-us-5715) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C25%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204250713592877-5715%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-26T07%3A15%3A07Z&sr=b&sp=r&sig=WixUgUkTtErpchT4EagDsGPpT0ds%2Fjvdom2x4N8t27s%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-25 07:33 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/aa107f200e5632d602f01e7971b3e4d50a808a18/msteams-platform%2Fapps-in-teams-meetings%2Fenable-and-configure-your-app-for-teams-meetings.md) | 96 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/75c386e3-5975-4259-8813-adda3daf0102) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/aa107f200e5632d602f01e7971b3e4d50a808a18/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-links.md) | 82 | 52 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2a965ecc-d319-4ebf-b6e4-0b8aac344627) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-25 07:34 UTC, opbld32 commented
Docs Build status updates of commit _[aa107f2](https://github.com/MicrosoftDocs/msteams-docs/commits/aa107f200e5632d602f01e7971b3e4d50a808a18)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings?branch=pr-en-us-5715) |
[msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/build-and-test/deep-links.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links?branch=pr-en-us-5715) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C25%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204250732455861-5715%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-26T07%3A34%3A07Z&sr=b&sp=r&sig=gfyKN8oTtdsR86%2FZNJtlC8cGqHzn0M%2BIHLgEWg7bCnc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-01 05:00 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a8e62c19836250d125201c4ee881621bcb5a6ffa/msteams-platform%2Fapps-in-teams-meetings%2Fenable-and-configure-your-app-for-teams-meetings.md) | 96 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2a855183-142c-4580-9df1-234c8c3da474) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a8e62c19836250d125201c4ee881621bcb5a6ffa/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-links.md) | 79 | 46 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0af8afe9-74ee-4569-b830-fce36b710ddc) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-09-01 05:00 UTC, opbld30 commented
Docs Build status updates of commit _[a8e62c1](https://github.com/MicrosoftDocs/msteams-docs/commits/a8e62c19836250d125201c4ee881621bcb5a6ffa)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-2dea91ed)

<a id="2dea91ed"></a>
###
 - **[Error: CannotMergeCommit]** `````Cannot merge commit a8e62c19836250d125201c4ee881621bcb5a6ffa in branch Doc-feature-deeplink-meeting-sidepanel of repository https://github.com/MicrosoftDocs/msteams-docs into branch main (commit ca847c2865378eb12028c214caf6b0d9132f566d). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202209010500060933-5715/BuildReport?accessString=aededfbbac2efc86cad5af46635a5f2c797d31c2ab971b8cd2b3dd53d2009e8d).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-22 11:41 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9e1333f4f7639bc58914ddb5d8ae41556a783697/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-links.md) | 91 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d2106565-328f-40c8-997f-aa148412f1d3) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-09-22 11:42 UTC, opbld30 commented
Docs Build status updates of commit _[9e1333f](https://github.com/MicrosoftDocs/msteams-docs/commits/9e1333f4f7639bc58914ddb5d8ae41556a783697)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-feature-deeplink-meeting-sidepanel/msteams-platform/concepts/build-and-test/deep-links.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links?branch=pr-en-us-5715) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202209221141156157-5715/BuildReport?accessString=e1dffb49ad737c0d72bba52600f51f204c7431dacd26fc5049fc4df2beb07996).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2023-04-05 15:30 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/21cdd073f49d099d1720174600ff416212f63668/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 91 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4bc5d6d1-3429-426b-a909-37244944cd3c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-04-12 02:49 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9bb18e886a7e31aa339a42820b250c72a67800e5/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 91 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6273d69c-3586-4f3f-8e08-68622de149ce) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-04-12 03:12 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a2d22372406d9f961d7aff593dd5d61826cac014/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 91 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/edd10ecb-3d91-4cf7-90ff-50a6a31fa0d7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-workflow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a2d22372406d9f961d7aff593dd5d61826cac014/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-workflow.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/eee4e577-7e06-4ac7-a216-e8dfe639ec5d) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-04-12 03:55 UTC, juna-gupta requested changes

2023-04-12 03:55 UTC, juna-gupta commented on msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md
> +When app users in selects the deeplink is selected to meeting sidepanel is selected in the meeting stage, it opens the sidepanel in the meeting stage. If the deeplink to meeting sidepanel is selected
please review this description. "When app users in selects the deeplink is selected to meeting sidepanel is selected" - doesn't make sense.

2023-04-29 06:33 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bce292b7f0c800acf40615122d0aaf27a0f7548f/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 91 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/702bd0df-a456-4248-ad41-35f56f239c85) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-workflow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bce292b7f0c800acf40615122d0aaf27a0f7548f/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-workflow.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/30b834bd-b950-40da-bf37-95e9e4ea1011) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-05-02 04:12 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9e4b483577b18f51dfbee3004beed2ffe853148d/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 91 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f15cbb7d-31b1-4132-8d93-9ef12e9ec830) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-workflow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9e4b483577b18f51dfbee3004beed2ffe853148d/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-workflow.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a4227904-a40e-43ce-8eeb-dda7f1ff6064) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-05-02 07:42 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0c5b754bdc5e78019b024ff9e6ed7c771f2a3378/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 91 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/37a166d5-5612-4f03-be89-2dddc0d945ea) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-application.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0c5b754bdc5e78019b024ff9e6ed7c771f2a3378/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-application.md) | 95 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8ad39c90-8f8a-4c75-ab44-60e4673eb182) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-workflow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0c5b754bdc5e78019b024ff9e6ed7c771f2a3378/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-workflow.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/001b5140-a3cd-4f3d-a580-9dd06eb4aa14) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/0c5b754bdc5e78019b024ff9e6ed7c771f2a3378/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/886f3d2f-9275-478d-8578-4ac6e5304843) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-05-02 07:51 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7eeb0031a351fa46398ba48b45c517bf11329010/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 91 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ce93a9da-be93-4fd0-b93d-ddf1deb88e14) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-application.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7eeb0031a351fa46398ba48b45c517bf11329010/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-application.md) | 95 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c36827aa-b7e9-4843-9789-d173b616fdee) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-workflow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7eeb0031a351fa46398ba48b45c517bf11329010/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-workflow.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/78f5cd82-68fa-42e7-ad28-ea651691ab74) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/7eeb0031a351fa46398ba48b45c517bf11329010/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f4e8d553-699e-4a27-a17b-8788c7639156) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-05-02 08:27 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/486a16703313bca3cfc4e112486b94e35ac8796e/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 91 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0807d2f3-f8a2-4db1-9a0c-a345bf0ac9dc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-application.md](https://github.com/MicrosoftDocs/msteams-docs/blob/486a16703313bca3cfc4e112486b94e35ac8796e/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-application.md) | 95 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/481bd197-7857-4797-935b-32f97ff77aaf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-workflow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/486a16703313bca3cfc4e112486b94e35ac8796e/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-workflow.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/421c0172-6201-4390-a253-b9097b59881c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/486a16703313bca3cfc4e112486b94e35ac8796e/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/512020a2-8e3c-4d44-8061-21c2dfde2a9b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-05-02 08:50 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8b3b1f347c81def994ab024c454dd2430e0dc07e/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 93 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/eab81be2-0d29-4e97-ad8e-859927d4e25e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-application.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8b3b1f347c81def994ab024c454dd2430e0dc07e/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-application.md) | 95 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b9b7ce4a-74f5-4aef-97f7-dec35ca2117c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-workflow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8b3b1f347c81def994ab024c454dd2430e0dc07e/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-workflow.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1630ef37-aa16-43c0-bf6e-d8e00fbdc253) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/8b3b1f347c81def994ab024c454dd2430e0dc07e/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f49fc2bd-010e-4a29-8913-e62e284e15aa) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-05-02 08:55 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/782fe50076c9dbc891f1fae62e08ba058489f805/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 93 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ae8c9ba9-2c0d-4761-b7d2-323aec8e3601) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-application.md](https://github.com/MicrosoftDocs/msteams-docs/blob/782fe50076c9dbc891f1fae62e08ba058489f805/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-application.md) | 95 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/99947393-ff3f-424d-b46c-9a16b4041c0d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-workflow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/782fe50076c9dbc891f1fae62e08ba058489f805/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-workflow.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/22309448-cb3f-4fb0-a716-919eb1cf5530) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/782fe50076c9dbc891f1fae62e08ba058489f805/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/80f0a993-3e7e-44e7-bf8d-8b0210846f89) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-05-02 10:15 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7321e301840ac6c6bf1eced9d97ffcd930491ef8/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 95 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0f4c0ad4-9038-494c-8b62-6f666c26dedc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-application.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7321e301840ac6c6bf1eced9d97ffcd930491ef8/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-application.md) | 95 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3c8ba5a3-881e-4053-86fe-40701f5e336d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-workflow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7321e301840ac6c6bf1eced9d97ffcd930491ef8/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-workflow.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/26d4de1b-8039-4bc5-ab40-9a42e8cf784f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/7321e301840ac6c6bf1eced9d97ffcd930491ef8/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7b40af4e-7927-4f3a-8f36-0f6f5ce8c27c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-05-05 03:45 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4c020482db2a2249c5198016a30d083a62a6f08e/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 93 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8937e417-5fb9-4a32-b627-bd98f4526ab4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-application.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4c020482db2a2249c5198016a30d083a62a6f08e/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-application.md) | 93 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3349a13b-84a9-4d05-99c2-494d0bfe8d0e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-workflow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4c020482db2a2249c5198016a30d083a62a6f08e/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-workflow.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c9b5c72b-91a5-45f6-b696-c34b530537a6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/4c020482db2a2249c5198016a30d083a62a6f08e/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/35c696b5-5a97-44eb-b81f-b8d9589f2046) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-05-05 04:50 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/039f351d116697cd267ac40db151ca3a7edde050/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 93 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fbff8268-f3d1-4c1d-9c85-086cb0748092) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-application.md](https://github.com/MicrosoftDocs/msteams-docs/blob/039f351d116697cd267ac40db151ca3a7edde050/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-application.md) | 93 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/36c04d0b-0bbe-40ce-8a24-34d52484d6d0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-workflow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/039f351d116697cd267ac40db151ca3a7edde050/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-workflow.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5cb04d1a-7dfc-4897-b739-0c6d4c759b2b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/039f351d116697cd267ac40db151ca3a7edde050/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1971402f-5a12-4c20-a6d3-9a6f10bfa092) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-05-05 09:22 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3b30cce76c42983b19523b225083fa1187283535/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 93 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/57c8e6aa-8012-43ec-8b6f-c34d517a8d7d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-application.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3b30cce76c42983b19523b225083fa1187283535/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-application.md) | 93 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a8740f92-c72f-452a-820c-8747bb89b20c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-workflow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3b30cce76c42983b19523b225083fa1187283535/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-workflow.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/62b8174e-7c10-4a13-8351-2ea5e89f477b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/3b30cce76c42983b19523b225083fa1187283535/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5fc5895e-4b32-4a94-b078-202fa6332c76) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-05-05 12:21 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/adcb3e1975cb981bb8488a24358cfd9b8ab94183/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 92 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b4a8c997-9726-46a2-81a8-87ea0c2880a5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-application.md](https://github.com/MicrosoftDocs/msteams-docs/blob/adcb3e1975cb981bb8488a24358cfd9b8ab94183/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-application.md) | 93 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fe5d52b9-ebda-4a26-83c1-2d54700fed96) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-workflow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/adcb3e1975cb981bb8488a24358cfd9b8ab94183/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-workflow.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3969f1ab-53f5-4fb5-8811-6c49c7bccfed) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/adcb3e1975cb981bb8488a24358cfd9b8ab94183/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2176fa43-1801-43c6-97e4-91dea90f9693) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/adcb3e1975cb981bb8488a24358cfd9b8ab94183/msteams-platform%2Fwhats-new.md) | 93 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/953c0d1f-1dfe-442c-b9f9-978b5b4ada92) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-05-05 12:30 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b10a7f67bcdf0323d1943cd0c032609a3a562ba3/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 92 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b9c61fa2-a800-4378-a1ff-b4aaf43730fc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-application.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b10a7f67bcdf0323d1943cd0c032609a3a562ba3/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-application.md) | 93 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/408c7fe9-f1f5-4561-a6b4-02d2e85dee3e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-workflow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b10a7f67bcdf0323d1943cd0c032609a3a562ba3/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-workflow.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/003a1bd0-ac2d-4dfe-9d19-c374e3a28681) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/b10a7f67bcdf0323d1943cd0c032609a3a562ba3/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/457b95dd-6adb-4f2f-ab53-fb25a7928d10) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b10a7f67bcdf0323d1943cd0c032609a3a562ba3/msteams-platform%2Fwhats-new.md) | 93 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fd38f7da-910d-49b4-b174-a1aa702ec8a5) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-05-05 16:54 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/08c9d3c11e4cb2366c7f53b8d0a8bac7d1feef8c/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 92 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d3ce10b6-e7d2-45c5-aa63-0fc72888916c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-application.md](https://github.com/MicrosoftDocs/msteams-docs/blob/08c9d3c11e4cb2366c7f53b8d0a8bac7d1feef8c/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-application.md) | 93 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/62d0176b-3d30-4c1e-b645-7629fee25f39) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-workflow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/08c9d3c11e4cb2366c7f53b8d0a8bac7d1feef8c/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-workflow.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3555eb38-1352-48bb-8c99-f08d2aa68706) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/08c9d3c11e4cb2366c7f53b8d0a8bac7d1feef8c/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4d5fb1ac-306e-4b8d-a647-7b62384f48c5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/08c9d3c11e4cb2366c7f53b8d0a8bac7d1feef8c/msteams-platform%2Fwhats-new.md) | 93 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d188cf85-7290-4ca3-ac3d-f1fa89bf70ce) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-05-09 22:06 UTC, melu613 commented on msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md
> +# [Pre or post-meeting tab](#tab/pre-or-post-meeting-tab)
Please add some additional info on this. 

While it is true in a private meeting/group call/1:1 chat we can still navigate to the tab in chat pre/post meeting, we do not support this behavior in channel meetings.

2023-05-18 06:21 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2e10f456e6b4951b81331e02ad8d60ad0d81d135/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 93 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2949b49d-255d-4198-bb07-227e3c6bde04) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-application.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2e10f456e6b4951b81331e02ad8d60ad0d81d135/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-application.md) | 92 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/288223b3-5940-4b22-a74c-abbc8b1afbd9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-workflow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2e10f456e6b4951b81331e02ad8d60ad0d81d135/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-workflow.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6ad17c7d-becf-46a3-851b-8faea732acf5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/2e10f456e6b4951b81331e02ad8d60ad0d81d135/msteams-platform%2Fmstdd-landing.yml) | 89 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/eb4d2d9f-263f-4505-8234-c9106452d113) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2e10f456e6b4951b81331e02ad8d60ad0d81d135/msteams-platform%2Fwhats-new.md) | 93 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d2c2a521-1298-4c59-90e2-a28cc111fa0a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-05-18 10:17 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/255027d98734e93410a5620fda39a9bb8c40a427/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 92 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3523c65a-bfd3-4647-ad6e-d6fce67023da) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-application.md](https://github.com/MicrosoftDocs/msteams-docs/blob/255027d98734e93410a5620fda39a9bb8c40a427/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-application.md) | 92 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/36373bac-6ea6-47e8-8d86-a51918b69cb9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-workflow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/255027d98734e93410a5620fda39a9bb8c40a427/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-workflow.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8dfdde3b-74e1-4827-b988-f181d1842ae1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/255027d98734e93410a5620fda39a9bb8c40a427/msteams-platform%2Fmstdd-landing.yml) | 89 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fce43ae4-dc35-4000-a835-fbd12646ee18) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/255027d98734e93410a5620fda39a9bb8c40a427/msteams-platform%2Fwhats-new.md) | 93 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0eb819d3-e43d-4af0-8fdf-9dbdeb20932a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-05-18 10:46 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6c56776afa75ecfcc99f0f515f9d1d4149a810cd/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 93 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c8410296-0ed3-446b-9e8a-424e1b6de4dd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-application.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6c56776afa75ecfcc99f0f515f9d1d4149a810cd/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-application.md) | 92 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/48c42ce2-1af2-4d39-98f1-b5e7174928e9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-workflow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6c56776afa75ecfcc99f0f515f9d1d4149a810cd/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-workflow.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/eac6fb10-85a5-4a77-ab3d-ba7342cd0249) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/6c56776afa75ecfcc99f0f515f9d1d4149a810cd/msteams-platform%2Fmstdd-landing.yml) | 89 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/da32cfbe-78c9-4a0a-8168-40d785c6adeb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6c56776afa75ecfcc99f0f515f9d1d4149a810cd/msteams-platform%2Fwhats-new.md) | 93 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e3fae2d5-854f-4a18-817e-4711d6414a5c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-05-22 05:05 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/412701eb199a12722c355ebe789051595bb57259/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 93 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/40166ee3-57e3-41b2-a208-289129adc1ea) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-application.md](https://github.com/MicrosoftDocs/msteams-docs/blob/412701eb199a12722c355ebe789051595bb57259/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-application.md) | 92 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5130740c-5cfd-4dd8-af73-ad43fbebb798) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-workflow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/412701eb199a12722c355ebe789051595bb57259/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-workflow.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f78a1016-680b-45fd-aaa4-e90f2ee0e46b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/412701eb199a12722c355ebe789051595bb57259/msteams-platform%2Fmstdd-landing.yml) | 89 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2b170776-f2e7-4ad9-b930-10f26f059daa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/412701eb199a12722c355ebe789051595bb57259/msteams-platform%2Fwhats-new.md) | 93 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d39d5303-d236-4b94-8582-aaf8bff19092) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-05-22 05:37 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8c3156a925196d218504f276f5e9ecb4217d962e/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 93 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c32db0f0-d6d5-4d53-9337-115e0ca277dc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-application.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8c3156a925196d218504f276f5e9ecb4217d962e/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-application.md) | 92 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/25777ed6-5124-4cce-8b3a-84172f8d39b3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-workflow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8c3156a925196d218504f276f5e9ecb4217d962e/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-workflow.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/eb12e724-985d-4e33-8c32-7401ddbecce9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/8c3156a925196d218504f276f5e9ecb4217d962e/msteams-platform%2Fmstdd-landing.yml) | 89 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1a2c7a36-228f-4e55-b346-d22d172970c9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8c3156a925196d218504f276f5e9ecb4217d962e/msteams-platform%2Fwhats-new.md) | 93 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/33339582-bc49-421b-8960-5be5519270f8) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-05-22 05:41 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d8baaea7c84e7b4043144255a2cc1f667cd3f690/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 93 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f6c44837-d794-4a53-92b7-5b9225e2f4dd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-application.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d8baaea7c84e7b4043144255a2cc1f667cd3f690/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-application.md) | 92 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e0c02be4-bb7c-4ab2-b19e-a31b0dec0a70) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-workflow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d8baaea7c84e7b4043144255a2cc1f667cd3f690/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-workflow.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/46779475-244b-4c82-86d7-5d47542b47ae) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/d8baaea7c84e7b4043144255a2cc1f667cd3f690/msteams-platform%2Fmstdd-landing.yml) | 89 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fbbfab0e-7d18-4248-a892-95b918c49ebc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d8baaea7c84e7b4043144255a2cc1f667cd3f690/msteams-platform%2Fwhats-new.md) | 93 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6f6860f3-b921-4cbb-a5e1-89984a7aa7f7) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-05-22 05:44 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e247193c5c061482a08eb7c8de2a014acf0ab9c7/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 93 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3e2fdbe1-a6f2-4050-a9d5-7caa5a707467) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-application.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e247193c5c061482a08eb7c8de2a014acf0ab9c7/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-application.md) | 92 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3633e9da-9773-4b6b-8e47-4f7de55b81da) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-workflow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e247193c5c061482a08eb7c8de2a014acf0ab9c7/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-workflow.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/91ef9f87-ed21-460d-ba69-9a6c0ac8d0d8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e247193c5c061482a08eb7c8de2a014acf0ab9c7/msteams-platform%2Fmstdd-landing.yml) | 89 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8966dde8-0c16-45f6-99b1-fc54da853f1c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e247193c5c061482a08eb7c8de2a014acf0ab9c7/msteams-platform%2Fwhats-new.md) | 93 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e04a7d01-6225-4d75-b26e-b2ca551fcae9) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-05-22 05:51 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/513807b98588a1ca28035dc094ce9bb81a0b591e/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 93 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2e5fb87d-3225-4dc0-88ec-98c866e11f41) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-application.md](https://github.com/MicrosoftDocs/msteams-docs/blob/513807b98588a1ca28035dc094ce9bb81a0b591e/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-application.md) | 92 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7b70f2b2-c6af-47c5-b7c4-3e44c96cf8c4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-workflow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/513807b98588a1ca28035dc094ce9bb81a0b591e/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-workflow.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6dd47510-2f47-45e7-9e2c-1fd201dd5c02) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/513807b98588a1ca28035dc094ce9bb81a0b591e/msteams-platform%2Fmstdd-landing.yml) | 89 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/48b84a5d-ac88-4728-a7e1-eb0c0f62306c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/513807b98588a1ca28035dc094ce9bb81a0b591e/msteams-platform%2Fwhats-new.md) | 93 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7cc8124f-31d8-4c25-b4d7-9205eacfa689) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-05-22 05:54 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5057948e7908ea891d5b8b1c64f3fbac6f339224/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 93 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/feacfe80-90dc-4df7-998b-7c85c74debfa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-application.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5057948e7908ea891d5b8b1c64f3fbac6f339224/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-application.md) | 92 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5c434279-8a37-46c3-8431-7ec3f45a451f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-workflow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5057948e7908ea891d5b8b1c64f3fbac6f339224/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-workflow.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ff083816-cddb-4be0-8d4c-72d9fbc55f33) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/5057948e7908ea891d5b8b1c64f3fbac6f339224/msteams-platform%2Fmstdd-landing.yml) | 89 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/57f17415-9a2c-445e-96ed-992feecb164c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5057948e7908ea891d5b8b1c64f3fbac6f339224/msteams-platform%2Fwhats-new.md) | 93 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e6e5b4ef-ac44-4260-8499-a7d3a9f55371) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-05-22 06:01 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2f4684bc8d8254ef44e8ba4a8a4a34603fcfeb8f/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 93 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7bccc2d4-526a-4d0a-be1e-5b4ee087ed67) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-application.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2f4684bc8d8254ef44e8ba4a8a4a34603fcfeb8f/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-application.md) | 92 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/36d50301-8421-400b-a96a-e2c68e4cd501) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-workflow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2f4684bc8d8254ef44e8ba4a8a4a34603fcfeb8f/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-workflow.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/560ad407-75d1-489c-ba4a-a6b7a312a41e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/2f4684bc8d8254ef44e8ba4a8a4a34603fcfeb8f/msteams-platform%2Fmstdd-landing.yml) | 89 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4e4e8f53-8728-44b5-8e13-c0617630dc2f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2f4684bc8d8254ef44e8ba4a8a4a34603fcfeb8f/msteams-platform%2Fwhats-new.md) | 93 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d0f4077a-84e9-4953-8274-96f14aa955ca) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-05-22 06:04 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/039dff88a9c6598ca78cb928be15b6e736d66aeb/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 93 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3b5d710a-b746-4370-833f-5975e55f51f0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-application.md](https://github.com/MicrosoftDocs/msteams-docs/blob/039dff88a9c6598ca78cb928be15b6e736d66aeb/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-application.md) | 92 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6671922e-3db9-4a6c-9652-bf7f4b487575) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-workflow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/039dff88a9c6598ca78cb928be15b6e736d66aeb/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-workflow.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8b7e4cf3-a43c-4019-8711-994af5fc8bb2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/039dff88a9c6598ca78cb928be15b6e736d66aeb/msteams-platform%2Fmstdd-landing.yml) | 89 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1b0723e7-4bba-4730-b27f-c76fce57065f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/039dff88a9c6598ca78cb928be15b6e736d66aeb/msteams-platform%2Fwhats-new.md) | 93 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c33669fa-013a-4e2d-a289-a65e2e2ac874) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-05-22 06:11 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a45c595ba8b66ff9c13d3ea07a8b72bb1d2cd750/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 92 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4d1dc56a-6478-451d-bb9f-53cd6a013d6b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-application.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a45c595ba8b66ff9c13d3ea07a8b72bb1d2cd750/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-application.md) | 92 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/38268cc4-41da-4498-bffd-1ce99d18eb86) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-workflow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a45c595ba8b66ff9c13d3ea07a8b72bb1d2cd750/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-workflow.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6945cc27-3722-427b-bd34-938cb5946e26) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a45c595ba8b66ff9c13d3ea07a8b72bb1d2cd750/msteams-platform%2Fmstdd-landing.yml) | 89 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ce689703-f88b-4474-9d2d-2457ebcd826d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a45c595ba8b66ff9c13d3ea07a8b72bb1d2cd750/msteams-platform%2Fwhats-new.md) | 93 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/88761815-fa54-4b2c-b80c-5fc3c04c0446) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-05-22 06:34 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/95d57d7be3d3ae69a06c59c4b2d79da84197266c/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 92 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/31beebe4-5a31-456d-b008-c4a699cbbf53) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-application.md](https://github.com/MicrosoftDocs/msteams-docs/blob/95d57d7be3d3ae69a06c59c4b2d79da84197266c/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-application.md) | 92 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ff3906f3-1c15-4ba3-a01e-c2c0d3aa357c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-workflow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/95d57d7be3d3ae69a06c59c4b2d79da84197266c/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-workflow.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/91e7acf8-baa1-4f85-abea-dc73ee18fb7d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/95d57d7be3d3ae69a06c59c4b2d79da84197266c/msteams-platform%2Fmstdd-landing.yml) | 89 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6255f4c0-3e61-456d-b62f-8eb02a29cd67) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/95d57d7be3d3ae69a06c59c4b2d79da84197266c/msteams-platform%2Fwhats-new.md) | 93 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3a46026d-1ce8-4f33-9ae2-62aada5ec62c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-05-22 06:52 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/91560dc41d82866e0b398ac31231c4527099f961/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 92 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8d4225bf-40a3-4a40-b63d-41a4461d139d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-application.md](https://github.com/MicrosoftDocs/msteams-docs/blob/91560dc41d82866e0b398ac31231c4527099f961/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-application.md) | 92 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8ed670fc-fd81-4097-8252-ca965c67da3f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-workflow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/91560dc41d82866e0b398ac31231c4527099f961/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-workflow.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/65e8b211-fa29-4950-aa0b-e3eb5832d006) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/91560dc41d82866e0b398ac31231c4527099f961/msteams-platform%2Fmstdd-landing.yml) | 89 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4a6b4fb2-18f3-4f31-8e05-072475a09210) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/91560dc41d82866e0b398ac31231c4527099f961/msteams-platform%2Fwhats-new.md) | 93 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/671f19f1-dfd9-4569-89f6-b7ea6d8a8017) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-05-22 07:13 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/32299f7074adde3f8d560d5f43e89956f46f10cb/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 92 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2e43d219-d805-4e9e-a574-750a41054e70) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-application.md](https://github.com/MicrosoftDocs/msteams-docs/blob/32299f7074adde3f8d560d5f43e89956f46f10cb/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-application.md) | 92 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5e09d9be-9146-4193-96aa-2c72802eb539) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-workflow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/32299f7074adde3f8d560d5f43e89956f46f10cb/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-workflow.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6a1173a4-d00b-43eb-9ecc-bf051b875acb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/32299f7074adde3f8d560d5f43e89956f46f10cb/msteams-platform%2Fmstdd-landing.yml) | 89 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/de072e81-d814-4590-94b0-359ae0e6ee41) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/32299f7074adde3f8d560d5f43e89956f46f10cb/msteams-platform%2Fwhats-new.md) | 93 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/460e7076-a247-498d-981c-78a97864eb72) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-05-22 11:40 UTC, Wajeed-msft submitted a review, later dismissed

2023-05-23 09:40 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/baf60c066c9b41c8b4a9f0580d5e8bcf20e14462/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 92 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a9d463ae-027f-4a2f-99f4-87f5f3bf3c61) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-application.md](https://github.com/MicrosoftDocs/msteams-docs/blob/baf60c066c9b41c8b4a9f0580d5e8bcf20e14462/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-application.md) | 92 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/84ff0978-6a56-4797-ae0f-14398d49fc04) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-workflow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/baf60c066c9b41c8b4a9f0580d5e8bcf20e14462/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-workflow.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5653db7c-ee38-4f8e-97cb-87c4bb11dad1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/baf60c066c9b41c8b4a9f0580d5e8bcf20e14462/msteams-platform%2Fmstdd-landing.yml) | 89 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a1413bb8-dc7e-4646-b91e-47b99b82c731) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/baf60c066c9b41c8b4a9f0580d5e8bcf20e14462/msteams-platform%2Fwhats-new.md) | 93 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/18d66561-90ed-4e07-b913-c480d9756cbd) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-05-23 10:25 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e0b72b9a948f4e35b6e3dd92987d0e9cf74b5c10/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 92 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/11a2bb90-3473-4796-bc67-567deca7df4a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-application.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e0b72b9a948f4e35b6e3dd92987d0e9cf74b5c10/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-application.md) | 92 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ac289a1c-61d9-4858-8460-a225e43e6d81) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-workflow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e0b72b9a948f4e35b6e3dd92987d0e9cf74b5c10/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-workflow.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ebdbd40e-0993-440b-82f9-ecff42cf47b8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e0b72b9a948f4e35b6e3dd92987d0e9cf74b5c10/msteams-platform%2Fmstdd-landing.yml) | 89 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b0b53338-9354-498e-9f23-dc95c1286169) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e0b72b9a948f4e35b6e3dd92987d0e9cf74b5c10/msteams-platform%2Fwhats-new.md) | 93 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e609b354-a73a-431e-90ab-34bc40e646c7) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-05-23 10:48 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bc8fccec26c3705fe7ca20ccdf567d08da748500/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 92 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/39853d5b-3965-44b0-8eff-3a9b5d8befe4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-application.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bc8fccec26c3705fe7ca20ccdf567d08da748500/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-application.md) | 92 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2956f0ad-03d9-448e-86fb-27d04434dd4e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-workflow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bc8fccec26c3705fe7ca20ccdf567d08da748500/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-workflow.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/260ed617-2b51-4283-911f-ba2c6d1b44ff) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/bc8fccec26c3705fe7ca20ccdf567d08da748500/msteams-platform%2Fmstdd-landing.yml) | 89 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/70e255f0-1740-4daa-ad36-2aeab9ecd915) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bc8fccec26c3705fe7ca20ccdf567d08da748500/msteams-platform%2Fwhats-new.md) | 93 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0a6c2579-d4d1-4b1c-8de7-c2980afbc2f8) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-05-24 05:07 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/95a730639285347d0841b2f7c92d10fc57d848f3/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 92 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4afeb991-29e1-47d2-a38c-b2b38ae5c874) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-application.md](https://github.com/MicrosoftDocs/msteams-docs/blob/95a730639285347d0841b2f7c92d10fc57d848f3/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-application.md) | 92 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3566d98b-c6ad-4af0-b37f-4f3beea02538) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-workflow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/95a730639285347d0841b2f7c92d10fc57d848f3/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-workflow.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/85da9ad6-80ed-42e6-8b3a-1f5f3158ccfd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/95a730639285347d0841b2f7c92d10fc57d848f3/msteams-platform%2Fmstdd-landing.yml) | 89 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ff9819a1-db3d-4e4a-bcdf-d5ec2580dd0b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/95a730639285347d0841b2f7c92d10fc57d848f3/msteams-platform%2Fwhats-new.md) | 93 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4cb93d1e-a2c3-4bec-af48-dd895fc50a54) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-05-24 06:49 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c9fe8df4a54d5885e9d91c5635397606dec08ff2/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 92 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9ea3b118-048e-46a6-b84c-865072f0074a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-application.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c9fe8df4a54d5885e9d91c5635397606dec08ff2/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-application.md) | 92 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/523a7c2e-c959-4061-b011-18548a125b6c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-workflow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c9fe8df4a54d5885e9d91c5635397606dec08ff2/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-workflow.md) | 87 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e3397a8e-26ae-447c-90a8-6d8c8a62dd66) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c9fe8df4a54d5885e9d91c5635397606dec08ff2/msteams-platform%2Fmstdd-landing.yml) | 89 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/15208e94-eca1-4b11-9c22-cd820e5f71a8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c9fe8df4a54d5885e9d91c5635397606dec08ff2/msteams-platform%2Fwhats-new.md) | 93 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ababf95c-ea06-46ca-b6d7-4261f172b90f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-05-24 06:52 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/57e4b9bcfec88bfb7d03c85afe4825f34669af05/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 92 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/03168cae-2556-4cf3-9bc2-ac50bc660540) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-application.md](https://github.com/MicrosoftDocs/msteams-docs/blob/57e4b9bcfec88bfb7d03c85afe4825f34669af05/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-application.md) | 92 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/10299eea-1e23-4d73-8d21-f1735259d6b0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-workflow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/57e4b9bcfec88bfb7d03c85afe4825f34669af05/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-workflow.md) | 87 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9fb35cca-4d56-4b32-a3b4-82e979ebff6e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/57e4b9bcfec88bfb7d03c85afe4825f34669af05/msteams-platform%2Fmstdd-landing.yml) | 89 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2e2881e6-2413-4c05-b99e-926f8bba1a57) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/57e4b9bcfec88bfb7d03c85afe4825f34669af05/msteams-platform%2Fwhats-new.md) | 93 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7371051e-785a-4374-9396-5701dfeb1f40) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-05-24 08:20 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c349dc4075bee280a0a480ebb4f76ffcbd3fa5e3/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 92 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c86f3665-2cf3-4123-845a-5a6ef86e512c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-application.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c349dc4075bee280a0a480ebb4f76ffcbd3fa5e3/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-application.md) | 92 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c83e9195-2a9c-41cc-9eea-e27a1995c6e3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-workflow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c349dc4075bee280a0a480ebb4f76ffcbd3fa5e3/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-workflow.md) | 89 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dbd6e078-e6eb-4348-96a4-58e900f4cb2e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c349dc4075bee280a0a480ebb4f76ffcbd3fa5e3/msteams-platform%2Fmstdd-landing.yml) | 89 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/94c5fcc1-4100-4db2-8abf-8f38c451dc2f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c349dc4075bee280a0a480ebb4f76ffcbd3fa5e3/msteams-platform%2Fwhats-new.md) | 93 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3686bd80-3b60-48a1-8bb8-0bc8141d1851) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-05-25 06:43 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/19ad6eb50b07d2427763c81f2d15eb3e89cc070a/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 92 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a5fa1045-f4c5-49d4-b7d1-6009afc120e4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-application.md](https://github.com/MicrosoftDocs/msteams-docs/blob/19ad6eb50b07d2427763c81f2d15eb3e89cc070a/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-application.md) | 92 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/34284b3d-16a1-44b2-904a-d09438f37576) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-workflow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/19ad6eb50b07d2427763c81f2d15eb3e89cc070a/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-workflow.md) | 89 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/192b531e-11c1-4682-81fb-65b2ab9ccac4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/19ad6eb50b07d2427763c81f2d15eb3e89cc070a/msteams-platform%2Fmstdd-landing.yml) | 89 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0839527b-6b04-4a0a-9fdb-1e24aeac0f08) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/19ad6eb50b07d2427763c81f2d15eb3e89cc070a/msteams-platform%2Fwhats-new.md) | 93 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/41f7c364-a433-4c22-a0ab-ce4e0a32fadb) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-05-25 07:02 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2058b0eadd74d3f06aecd81e24321c487ce640d7/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 92 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bfdba4c6-535f-4746-a484-0fa735b36e19) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-application.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2058b0eadd74d3f06aecd81e24321c487ce640d7/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-application.md) | 92 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4f6394d2-cc93-4648-b4fa-476326dc1b3f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-workflow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2058b0eadd74d3f06aecd81e24321c487ce640d7/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-workflow.md) | 89 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/26eed73d-c3c5-4b73-b78d-06b64ea8db6d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/2058b0eadd74d3f06aecd81e24321c487ce640d7/msteams-platform%2Fmstdd-landing.yml) | 89 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/20afa677-3865-482d-8adf-5e8281d7939d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2058b0eadd74d3f06aecd81e24321c487ce640d7/msteams-platform%2Fwhats-new.md) | 93 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e9c9e3f3-f3f7-41fb-8c9e-dbf0b5a5c9ff) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-05-25 10:26 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7c29ddfb8e6b90cfd5cef18ab30c3c220b8043a7/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 92 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/24b6792f-07fe-494e-8bd4-aff7c0492be6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-application.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7c29ddfb8e6b90cfd5cef18ab30c3c220b8043a7/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-application.md) | 92 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8bc18abb-1a4b-4359-a308-2d2d00fe2743) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-workflow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7c29ddfb8e6b90cfd5cef18ab30c3c220b8043a7/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-workflow.md) | 89 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/eceb8812-5bef-46e1-aeb4-76015c87d673) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/7c29ddfb8e6b90cfd5cef18ab30c3c220b8043a7/msteams-platform%2Fmstdd-landing.yml) | 89 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f5a6312f-644b-4105-af45-0df7c6b19a98) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7c29ddfb8e6b90cfd5cef18ab30c3c220b8043a7/msteams-platform%2Fwhats-new.md) | 93 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8f9a64e8-ba48-4d0d-b72c-9eebba706d18) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-05-25 10:28 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/654b9444486ef3540c0da29c3655e101b45bbdff/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 92 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6b026a5e-3999-474e-ac70-e25f59fdfd89) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-application.md](https://github.com/MicrosoftDocs/msteams-docs/blob/654b9444486ef3540c0da29c3655e101b45bbdff/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-application.md) | 92 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7c6a7ad6-c33d-4088-b311-ac45036bfab3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-workflow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/654b9444486ef3540c0da29c3655e101b45bbdff/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-workflow.md) | 89 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/87999cc1-830e-4460-8b43-aaa6ad20dce9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/654b9444486ef3540c0da29c3655e101b45bbdff/msteams-platform%2Fmstdd-landing.yml) | 89 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b9caebbb-805c-4e22-ba1a-9e58157d38b2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/654b9444486ef3540c0da29c3655e101b45bbdff/msteams-platform%2Fwhats-new.md) | 93 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8365bc97-229b-4949-aa53-ccf48142a0e5) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-05-25 16:29 UTC, vikramjit-singh-chug approved these changes

2023-05-25 16:59 UTC, merged