[Doc Issue][Build your first app with SPFx]
MicrosoftDocs/msteams-docs pull request #5734
Opened 2022-04-13 09:34 UTC by vsoniv

2022-04-13 09:35 UTC, opbld30 commented
Docs Build status updates of commit _[edc6476](https://github.com/MicrosoftDocs/msteams-docs/commits/edc647608b8e19abb976fe494974502d7594c1db)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/teams-toolkit-v2/spfx-another-helloworld.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-another-helloworld.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-helloworld.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-helloworld.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-react-page.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-react-page.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfxTab-spfx.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfxTab-spfx.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/sbs-gs-spfx.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/sbs-gs-spfx.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C13%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204130934305250-5734%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-14T09%3A35%3A07Z&sr=b&sp=r&sig=wIeLKsFVVS6aKfB3ZSJNY1Uxx4sScsjMrUcicy4lC%2Bs%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-13 09:35 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-spfx.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/da6f60f9a3363c9e6d77d66284fb4e475eb293fe/msteams-platform%2Fsbs-gs-spfx.yml) | 95 | 28 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/db471b80-abad-4dc2-816a-dbb8ebeff93d) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-13 09:35 UTC, opbld32 commented
Docs Build status updates of commit _[da6f60f](https://github.com/MicrosoftDocs/msteams-docs/commits/da6f60f9a3363c9e6d77d66284fb4e475eb293fe)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/teams-toolkit-v2/spfx-another-helloworld.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-another-helloworld.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-helloworld.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-helloworld.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-react-page.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-react-page.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfxTab-spfx.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfxTab-spfx.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/sbs-gs-spfx.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/sbs-gs-spfx.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C13%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204130935099265-5734%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-14T09%3A35%3A56Z&sr=b&sp=r&sig=B3HBza%2B3E00hBu8%2BsWFpwAee1nLZ8966xt2L4NaJTes%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-13 09:40 UTC, opbld33 commented
Docs Build status updates of commit _[6814cde](https://github.com/MicrosoftDocs/msteams-docs/commits/6814cde4cd9cd0e6be29e63fad91f5be3b294c61)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/teams-toolkit-v2/spfx-another-helloworld.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-another-helloworld.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-helloworld.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-helloworld.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-react-page.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-react-page.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfxTab-spfx.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfxTab-spfx.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/sbs-gs-spfx.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/sbs-gs-spfx.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C13%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204130939045260-5734%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-14T09%3A40%3A05Z&sr=b&sp=r&sig=br164n3bA%2Br4%2B%2Fjn36E1Ns6OArqtKfI7g4lw%2FzIU%2FJs%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-13 09:42 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-spfx.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/6814cde4cd9cd0e6be29e63fad91f5be3b294c61/msteams-platform%2Fsbs-gs-spfx.yml) | 95 | 28 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4e6c6fbd-879a-47b2-a84b-287767fb4538) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-13 12:42 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-spfx.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/de64c06a545a8d58d695bffe69240abe3b28c770/msteams-platform%2Fsbs-gs-spfx.yml) | 95 | 28 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5d478c0b-6a5f-4a7b-8b83-694406c6b6fe) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-13 12:42 UTC, opbld30 commented
Docs Build status updates of commit _[de64c06](https://github.com/MicrosoftDocs/msteams-docs/commits/de64c06a545a8d58d695bffe69240abe3b28c770)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/teams-toolkit-v2/sbs-share-point.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/sbs-share-point.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-Teams-toolkit.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-Teams-toolkit.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-another-helloworld.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-another-helloworld.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-debug.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-debug.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-helloworld.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-helloworld.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-react-page.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-react-page.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfxTab-spfx.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfxTab-spfx.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/sbs-gs-spfx.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/sbs-gs-spfx.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C13%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204131241502382-5734%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-14T12%3A42%3A31Z&sr=b&sp=r&sig=TpVgTH%2F7VXuRVyMA%2Fx8wJtXiY9nSxNZyfGQsgYGDdGg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-13 12:49 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-spfx.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/8d95632a99824d2269980194f0dd976a77f5a64f/msteams-platform%2Fsbs-gs-spfx.yml) | 95 | 28 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7c2d85d3-4f46-4fea-a2b8-f5198c676acd) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-13 12:50 UTC, opbld31 commented
Docs Build status updates of commit _[8d95632](https://github.com/MicrosoftDocs/msteams-docs/commits/8d95632a99824d2269980194f0dd976a77f5a64f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/teams-toolkit-v2/sbs-share-point.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/sbs-share-point.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-Teams-toolkit.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-Teams-toolkit.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-another-helloworld.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-another-helloworld.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-debug.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-debug.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-helloworld.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-helloworld.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-react-page.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-react-page.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfxTab-spfx.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfxTab-spfx.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/sbs-gs-spfx.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/sbs-gs-spfx.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C13%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204131249176132-5734%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-14T12%3A50%3A12Z&sr=b&sp=r&sig=9zDiDLs7HMgeR%2ByMJ%2BFu%2FvTExbdfmg19o6g%2Fm4iiMsk%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-13 12:54 UTC, opbld31 commented
Docs Build status updates of commit _[8f02c9e](https://github.com/MicrosoftDocs/msteams-docs/commits/8f02c9e2fa93c072f737e48e8efd2c3fa8d68be6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/teams-toolkit-v2/sbs-share-point.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/sbs-share-point.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-Teams-toolkit.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-Teams-toolkit.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-another-helloworld.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-another-helloworld.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-debug.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-debug.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-helloworld.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-helloworld.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-react-page.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-react-page.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfxTab-spfx.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfxTab-spfx.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/sbs-gs-spfx.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/sbs-gs-spfx.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C13%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204131253259960-5734%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-14T12%3A54%3A08Z&sr=b&sp=r&sig=PZtOcuTpfj1X9cE0jzu5eOv%2BEtiotlXdCCVIy2aCvjk%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-13 12:55 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-spfx.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/8f02c9e2fa93c072f737e48e8efd2c3fa8d68be6/msteams-platform%2Fsbs-gs-spfx.yml) | 95 | 28 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b5a5df43-43ef-4e37-a697-395a39389fdc) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-13 13:02 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-spfx.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/348eded15469444a82bc877b905dea8f6db65e0f/msteams-platform%2Fsbs-gs-spfx.yml) | 95 | 28 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e9b6bdfa-c9c7-48f8-a2b7-0456483b06ee) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-13 13:06 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-spfx.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/0538dd3e7d5e2666c62509ca3f1c88f5f4ed3650/msteams-platform%2Fsbs-gs-spfx.yml) | 95 | 28 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c1165d84-354c-4683-947f-c237a955b016) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-13 13:06 UTC, opbld31 commented
Docs Build status updates of commit _[0538dd3](https://github.com/MicrosoftDocs/msteams-docs/commits/0538dd3e7d5e2666c62509ca3f1c88f5f4ed3650)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/teams-toolkit-v2/sbs-share-point.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/sbs-share-point.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-Teams-toolkit.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-Teams-toolkit.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-another-helloworld.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-another-helloworld.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-debug.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-debug.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-helloworld.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-helloworld.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-new-toolkit.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-new-toolkit.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-new-toolkit.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-react-page.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-react-page.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit-new.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-tooklit-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-tooklit-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfxTab-spfx.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfxTab-spfx.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/sbs-gs-spfx.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/sbs-gs-spfx.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C13%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204131306011606-5734%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-14T13%3A06%3A45Z&sr=b&sp=r&sig=EoTwhQG49aaiXD0KpjV1iu%2BY9Hio0%2By4%2BtXdc%2BWnNgw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-13 14:13 UTC, opbld31 commented
Docs Build status updates of commit _[24584a2](https://github.com/MicrosoftDocs/msteams-docs/commits/24584a2dec671e0d4ab696a025a288dd7a17a00e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/teams-toolkit-v2/sbs-share-point.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/sbs-share-point.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-Teams-toolkit.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-Teams-toolkit.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-another-helloworld.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-another-helloworld.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-custom-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-custom-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-debug.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-debug.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-helloworld.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-helloworld.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-new-toolkit.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-new-toolkit.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-new-toolkit.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-react-page.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-react-page.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit-new.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-tooklit-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-tooklit-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfxTab-spfx.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfxTab-spfx.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/sbs-gs-spfx.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/sbs-gs-spfx.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C13%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204131412290598-5734%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-14T14%3A13%3A02Z&sr=b&sp=r&sig=ujhmDPLVbFVJXVfyNiaAhADFTj%2BfxgaQIgtLRkpk2t8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-13 14:13 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-spfx.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/24584a2dec671e0d4ab696a025a288dd7a17a00e/msteams-platform%2Fsbs-gs-spfx.yml) | 95 | 28 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c54ef1f4-8ad2-4488-8a9f-c836edef0d94) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-13 14:27 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-spfx.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/0bc96ced1ff5e0ba06ed9ee7a785506340d271e1/msteams-platform%2Fsbs-gs-spfx.yml) | 95 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0aa6b3e3-df65-4a33-9fb2-057ca8d0b0a2) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-13 14:27 UTC, opbld30 commented
Docs Build status updates of commit _[0bc96ce](https://github.com/MicrosoftDocs/msteams-docs/commits/0bc96ced1ff5e0ba06ed9ee7a785506340d271e1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/teams-toolkit-v2/sbs-share-point.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/sbs-share-point.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-Teams-toolkit.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-Teams-toolkit.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-another-helloworld.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-another-helloworld.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-custom-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-custom-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-debug.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-debug.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-helloworld.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-helloworld.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-new-toolkit.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-new-toolkit.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-new-toolkit.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-react-page.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-react-page.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit-new.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-tooklit-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-tooklit-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfxTab-spfx.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfxTab-spfx.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/sbs-gs-spfx.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/sbs-gs-spfx.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C13%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204131426570078-5734%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-14T14%3A27%3A52Z&sr=b&sp=r&sig=1EGM%2BJR%2B2O1E5ttrqyiYG0O6QhdN12s7kn1P%2Fqr%2FNdA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-18 08:12 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-spfx.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/7d26a8c0d216fa54928f7a2fa9313e02198e98f3/msteams-platform%2Fsbs-gs-spfx.yml) | 95 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0f779517-dd43-42d3-9b39-311e335dab77) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-18 08:12 UTC, opbld30 commented
Docs Build status updates of commit _[7d26a8c](https://github.com/MicrosoftDocs/msteams-docs/commits/7d26a8c0d216fa54928f7a2fa9313e02198e98f3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/teams-toolkit-v2/sbs-share-point.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/sbs-share-point.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-Teams-toolkit.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-Teams-toolkit.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-another-helloworld.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-another-helloworld.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-custom-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-custom-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-debug.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-debug.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-helloworld.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-helloworld.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-new-toolkit.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-new-toolkit.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-new-toolkit.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-react-page.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-react-page.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit-new.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-tooklit-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-tooklit-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfxTab-spfx.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfxTab-spfx.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/sbs-gs-spfx.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/sbs-gs-spfx.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C18%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204180812115857-5734%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-19T08%3A12%3A42Z&sr=b&sp=r&sig=rKC%2B%2F%2BKH0U2uovqAWHVku76oubpfkfyWAbElmIWStnc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-18 08:26 UTC, xu-hong reviewed
Thanks for the work! Made one comment. Also there's a recap section that needs update, which includes a new GIF that I will send separately.

2022-04-18 08:26 UTC, xu-hong commented on msteams-platform/sbs-gs-spfx.yml
> +        :::image type="content" source="~/assets/images/teams-toolkit-v2/spfxTab-spfx.png" alt-text="bot home" border="true":::
a heads up that there's a small string change on this screenshot, which I will provide the new screenshot tomorrow

2022-04-18 11:03 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-spfx.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/b8df826ee48bf8f2b307d4ec42b33dfe8191b961/msteams-platform%2Fsbs-gs-spfx.yml) | 95 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fe23adb4-3080-412d-ad73-61c614fde102) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-18 11:03 UTC, opbld30 commented
Docs Build status updates of commit _[b8df826](https://github.com/MicrosoftDocs/msteams-docs/commits/b8df826ee48bf8f2b307d4ec42b33dfe8191b961)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/teams-toolkit-v2/sbs-share-point.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/sbs-share-point.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-Teams-toolkit.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-Teams-toolkit.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-another-helloworld.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-another-helloworld.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-custom-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-custom-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-debug.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-debug.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-helloworld.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-helloworld.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-microsoft-365.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-microsoft-365.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-new-toolkit.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-new-toolkit.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-new-toolkit.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-react-page.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-react-page.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit-new.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-tooklit-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-tooklit-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfxTab-spfx.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfxTab-spfx.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/sbs-gs-spfx.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/sbs-gs-spfx.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C18%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204181102569068-5734%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-19T11%3A03%3A37Z&sr=b&sp=r&sig=JIIqRdtMXe5CNwwK0pw2cQaydSNHWovmWR3DCnOcHrs%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-18 11:16 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-spfx.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/2c02563fcce0056c61d4b563a08d0c5b8c0ffd8e/msteams-platform%2Fsbs-gs-spfx.yml) | 95 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a0ed3648-a281-45f9-9cc5-d0539643d310) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-18 11:16 UTC, opbld30 commented
Docs Build status updates of commit _[2c02563](https://github.com/MicrosoftDocs/msteams-docs/commits/2c02563fcce0056c61d4b563a08d0c5b8c0ffd8e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/teams-toolkit-v2/sbs-share-point.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/sbs-share-point.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-Teams-toolkit.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-Teams-toolkit.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-another-helloworld.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-another-helloworld.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-custom-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-custom-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-debug.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-debug.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-helloworld.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-helloworld.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-microsoft-365.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-microsoft-365.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-new-toolkit.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-new-toolkit.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-new-toolkit.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-react-page.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-react-page.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit-new.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-tooklit-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-tooklit-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfxTab-spfx.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfxTab-spfx.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/sbs-gs-spfx.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/sbs-gs-spfx.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C18%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204181115565244-5734%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-19T11%3A16%3A34Z&sr=b&sp=r&sig=IF7GZaP%2FRReM58Q3waAcDgiWqdIxMojOjhTJ95U7qUE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-18 11:23 UTC, opbld31 commented
Docs Build status updates of commit _[aedc900](https://github.com/MicrosoftDocs/msteams-docs/commits/aedc9005c85fa63365110dc47aa8620c6d7a59df)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/teams-toolkit-v2/sbs-share-point.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/sbs-share-point.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-Teams-toolkit.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-Teams-toolkit.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-another-helloworld.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-another-helloworld.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-custom-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-custom-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-debug.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-debug.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-helloworld.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-helloworld.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-microsoft-365.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-microsoft-365.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-new-toolkit.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-new-toolkit.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-new-toolkit.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-react-page.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-react-page.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit-new.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-tooklit-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-tooklit-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfxTab-spfx.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfxTab-spfx.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/ssl-prompt.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/ssl-prompt.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/sbs-gs-spfx.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/sbs-gs-spfx.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C18%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204181122588369-5734%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-19T11%3A23%3A30Z&sr=b&sp=r&sig=O6Ib1OXmx2qTuWPXycDFzjXFULkCLwYUvmdPALuFhFc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-18 11:24 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-spfx.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/aedc9005c85fa63365110dc47aa8620c6d7a59df/msteams-platform%2Fsbs-gs-spfx.yml) | 95 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f3edff26-ed9f-4b1b-80d7-8fcee86acf77) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-18 13:32 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-spfx.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/330a54fafe42882cc0593029b81e1370e8e7af12/msteams-platform%2Fsbs-gs-spfx.yml) | 95 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8a009365-ba27-40e3-912c-a91c949a944b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-18 13:33 UTC, opbld30 commented
Docs Build status updates of commit _[330a54f](https://github.com/MicrosoftDocs/msteams-docs/commits/330a54fafe42882cc0593029b81e1370e8e7af12)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/teams-toolkit-v2/sbs-share-point.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/sbs-share-point.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-Teams-toolkit.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-Teams-toolkit.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-another-helloworld.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-another-helloworld.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-custom-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-custom-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-debug.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-debug.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-helloworld.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-helloworld.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-microsoft-365.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-microsoft-365.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-new-toolkit.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-new-toolkit.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-new-toolkit.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-react-page.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-react-page.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit-new.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-tooklit-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-tooklit-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfxTab-spfx.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfxTab-spfx.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/ssl-prompt.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/ssl-prompt.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/sbs-gs-spfx.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/sbs-gs-spfx.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C18%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204181332318690-5734%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-19T13%3A33%3A04Z&sr=b&sp=r&sig=Nbku20acH7YGEE38ohUXyKkU3xszNsB%2Fnz%2Fyr%2Bnwi9E%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-18 15:33 UTC, opbld30 commented
Docs Build status updates of commit _[b053d73](https://github.com/MicrosoftDocs/msteams-docs/commits/b053d73553723793a3d632ee1e439316bc0f7ae1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/teams-toolkit-v2/install-toolkit-vscode.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/install-toolkit-vscode.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/install-toolkit-vscode.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/sbs-share-point.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/sbs-share-point.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-Teams-toolkit.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-Teams-toolkit.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-another-helloworld.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-another-helloworld.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-custom-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-custom-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-debug.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-debug.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-helloworld.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-helloworld.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-microsoft-365.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-microsoft-365.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-new-toolkit.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-new-toolkit.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-new-toolkit.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-react-page.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-react-page.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit-new.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-tooklit-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-tooklit-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfxTab-spfx.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfxTab-spfx.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/ssl-prompt.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/ssl-prompt.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/sbs-gs-spfx.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/sbs-gs-spfx.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C18%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204181532354254-5734%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-19T15%3A33%3A38Z&sr=b&sp=r&sig=frn9377YEvv%2Bq5H2h%2F7mG75Nk48lCq5h98n%2Bge34EMs%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-18 15:34 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-spfx.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/b053d73553723793a3d632ee1e439316bc0f7ae1/msteams-platform%2Fsbs-gs-spfx.yml) | 95 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bad250c8-a3a0-4835-820f-644b67725221) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-18 15:35 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-spfx.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/b053d73553723793a3d632ee1e439316bc0f7ae1/msteams-platform%2Fsbs-gs-spfx.yml) | 95 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9e2cc8bb-9662-4c0d-aa1a-2bb3b1438810) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-18 15:38 UTC, opbld32 commented
Docs Build status updates of commit _[9f29499](https://github.com/MicrosoftDocs/msteams-docs/commits/9f29499cace8bf12ed4be92b53096af0f043e82c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/teams-toolkit-v2/install-toolkit-vscode.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/install-toolkit-vscode.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/sbs-share-point.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/sbs-share-point.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-Teams-toolkit.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-Teams-toolkit.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-another-helloworld.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-another-helloworld.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-custom-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-custom-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-debug.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-debug.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-helloworld.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-helloworld.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-microsoft-365.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-microsoft-365.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-new-toolkit.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-new-toolkit.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-new-toolkit.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-preview.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-react-page.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-react-page.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit-new.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-tooklit-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-tooklit-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfxTab-spfx.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfxTab-spfx.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/ssl-prompt.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/ssl-prompt.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/sbs-gs-spfx.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/sbs-gs-spfx.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C18%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204181537240245-5734%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-19T15%3A38%3A02Z&sr=b&sp=r&sig=JAtC%2Bnee3A4JxaBH0hYgKxpVwpcqSXy%2BCOevgbuqP0E%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-18 15:39 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-spfx.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/9f29499cace8bf12ed4be92b53096af0f043e82c/msteams-platform%2Fsbs-gs-spfx.yml) | 95 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8517d2be-3385-4ea9-bb3a-03077ad2bd8a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-18 15:40 UTC, opbld30 commented
Docs Build status updates of commit _[6d5789a](https://github.com/MicrosoftDocs/msteams-docs/commits/6d5789a419affc9b6e2efc34593a467f0e4a64ba)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/sbs-gs-spfx.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/sbs-gs-spfx.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) | [Details](#user-content-ba8b60b3814caf1cb1b4ded75b049c70-9f87309f)
[msteams-platform/assets/images/teams-toolkit-v2/sbs-share-point.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/sbs-share-point.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-Teams-toolkit.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-Teams-toolkit.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-another-helloworld.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-another-helloworld.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-custom-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-custom-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-debug.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-debug.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-helloworld.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-helloworld.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-install-toolkit-vscode.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-install-toolkit-vscode.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-install-toolkit-vscode.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-microsoft-365.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-microsoft-365.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-new-toolkit.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-new-toolkit.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-new-toolkit.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-preview.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-react-page.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-react-page.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit-new.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-tooklit-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-tooklit-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfxTab-spfx.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfxTab-spfx.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/ssl-prompt.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/ssl-prompt.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |

<a id="ba8b60b3814caf1cb1b4ded75b049c70-9f87309f"></a>
### [msteams-platform/sbs-gs-spfx.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/sbs-gs-spfx.yml)
 - **Line 61, Column 5**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '~/assets/images/teams-toolkit-v2/install-toolkit-vscode.png'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C18%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204181540265376-5734%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-19T15%3A40%3A58Z&sr=b&sp=r&sig=Io1B%2B%2Bm84wF4HhkVc3CnDmlqQSmM9SagPIkMGF8cttU%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, [...]

2022-04-18 15:42 UTC, opbld33 commented
Docs Build status updates of commit _[ac11f6d](https://github.com/MicrosoftDocs/msteams-docs/commits/ac11f6d33904de393b48691d679bb2ff7ca9e5f2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/teams-toolkit-v2/sbs-share-point.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/sbs-share-point.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-Teams-toolkit.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-Teams-toolkit.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-another-helloworld.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-another-helloworld.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-custom-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-custom-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-debug.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-debug.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-helloworld.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-helloworld.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-install-toolkit-vscode.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-install-toolkit-vscode.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-microsoft-365.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-microsoft-365.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-new-toolkit.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-new-toolkit.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-new-toolkit.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-preview.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-react-page.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-react-page.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit-new.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-tooklit-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-tooklit-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfxTab-spfx.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfxTab-spfx.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/ssl-prompt.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/ssl-prompt.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/sbs-gs-spfx.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/sbs-gs-spfx.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C18%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204181542065218-5734%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-19T15%3A42%3A47Z&sr=b&sp=r&sig=ja%2BU6WnNIgUz4CVn8eEoCfwajDrtTRzA%2F0epQdqS1fc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-18 15:42 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-spfx.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ac11f6d33904de393b48691d679bb2ff7ca9e5f2/msteams-platform%2Fsbs-gs-spfx.yml) | 95 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9e736ffd-5839-4e8a-aeb9-9ea124e948c1) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-18 15:44 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-spfx.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ac11f6d33904de393b48691d679bb2ff7ca9e5f2/msteams-platform%2Fsbs-gs-spfx.yml) | 95 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7f8cdb21-faae-4e42-92e5-294a114b0078) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-19 04:46 UTC, v-abirade submitted a review, later dismissed
Approved

2022-04-19 05:57 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-spfx.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/3cd17d60715c85eec5b023e0ffd6723a76e8d64f/msteams-platform%2Fsbs-gs-spfx.yml) | 95 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6d92878e-b3e3-4b60-b5e3-e2aa16d9542a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-19 05:58 UTC, opbld30 commented
Docs Build status updates of commit _[3cd17d6](https://github.com/MicrosoftDocs/msteams-docs/commits/3cd17d60715c85eec5b023e0ffd6723a76e8d64f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/teams-toolkit-v2/sbs-share-point.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/sbs-share-point.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-Teams-toolkit.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-Teams-toolkit.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-another-helloworld.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-another-helloworld.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-custom-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-custom-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-debug.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-debug.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-helloworld.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-helloworld.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-install-toolkit-vscode.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-install-toolkit-vscode.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-microsoft-365.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-microsoft-365.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-new-toolkit.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-new-toolkit.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-new-toolkit.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-preview.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-react-page.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-react-page.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit-new.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-tooklit-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-tooklit-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfxTab-spfx.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfxTab-spfx.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/ssl-prompt.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/ssl-prompt.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/videos/spfx-tab-source.gif](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/videos/spfx-tab-source.gif) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/sbs-gs-spfx.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/sbs-gs-spfx.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C19%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204190556419542-5734%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-20T05%3A58%3A51Z&sr=b&sp=r&sig=oOIdJvdexAbPq4OMSEQ6AG1l%2Be8Bfyd6e4ec0NHYmjY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-19 07:11 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-spfx.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/cad7f8b8f7912b6baadbef3dcbf7a878bbb097f3/msteams-platform%2Fsbs-gs-spfx.yml) | 95 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/98697e86-a522-4b84-a512-a488050d7a30) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-19 07:14 UTC, opbld32 commented
Docs Build status updates of commit _[cad7f8b](https://github.com/MicrosoftDocs/msteams-docs/commits/cad7f8b8f7912b6baadbef3dcbf7a878bbb097f3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/teams-toolkit-v2/sbs-share-point.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/sbs-share-point.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-Teams-toolkit.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-Teams-toolkit.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-another-helloworld.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-another-helloworld.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-custom-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-custom-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-debug.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-debug.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-helloworld.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-helloworld.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-install-toolkit-vscode.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-install-toolkit-vscode.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-microsoft-365.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-microsoft-365.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-new-toolkit.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-new-toolkit.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-new-toolkit.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-preview.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-react-page.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-react-page.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit-new.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-tooklit-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-tooklit-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfxTab-spfx.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfxTab-spfx.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/ssl-prompt.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/ssl-prompt.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/videos/spfx-tab-source.gif](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/videos/spfx-tab-source.gif) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/sbs-gs-spfx.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/sbs-gs-spfx.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C19%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204190711085588-5734%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-20T07%3A14%3A37Z&sr=b&sp=r&sig=2STofK2FviiKbF5zVpM3XQ7q3gdKmFqPXIkvEw2nhis%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-19 07:19 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-spfx.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/5ebf5278ca110a23bcfd41a4dfdba5a8302a7604/msteams-platform%2Fsbs-gs-spfx.yml) | 95 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e4522805-0e64-4610-ac7d-b3a7233b2763) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-19 07:19 UTC, opbld30 commented
Docs Build status updates of commit _[5ebf527](https://github.com/MicrosoftDocs/msteams-docs/commits/5ebf5278ca110a23bcfd41a4dfdba5a8302a7604)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/teams-toolkit-v2/sbs-share-point.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/sbs-share-point.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-Teams-toolkit.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-Teams-toolkit.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-another-helloworld.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-another-helloworld.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-custom-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-custom-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-debug.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-debug.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-helloworld.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-helloworld.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-install-toolkit-vscode.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-install-toolkit-vscode.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-microsoft-365.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-microsoft-365.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-new-toolkit.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-new-toolkit.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-new-toolkit.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-preview.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-react-page.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-react-page.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit-new.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-tooklit-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-tooklit-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfxTab-spfx.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfxTab-spfx.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/ssl-prompt.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/ssl-prompt.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/videos/spfx-tab-source.gif](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/videos/spfx-tab-source.gif) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/sbs-gs-spfx.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/sbs-gs-spfx.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C19%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204190719010537-5734%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-20T07%3A19%3A42Z&sr=b&sp=r&sig=714sojXJaewfvygxZ%2BjCCsn%2BuBcNX9mQPugYtEYvPHg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-19 07:25 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-spfx.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ef529f794ca7f87946ac7aea9495e6aa44e73d02/msteams-platform%2Fsbs-gs-spfx.yml) | 95 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7be31702-3a2f-425a-b659-b033c6cf3b41) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-19 07:26 UTC, opbld30 commented
Docs Build status updates of commit _[ef529f7](https://github.com/MicrosoftDocs/msteams-docs/commits/ef529f794ca7f87946ac7aea9495e6aa44e73d02)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/teams-toolkit-v2/sbs-share-point.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/sbs-share-point.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-Teams-toolkit.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-Teams-toolkit.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-another-helloworld.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-another-helloworld.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-custom-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-custom-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-debug.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-debug.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-helloworld.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-helloworld.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-install-toolkit-vscode.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-install-toolkit-vscode.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-microsoft-365.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-microsoft-365.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-new-toolkit.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-new-toolkit.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-new-toolkit.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-preview.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-react-page.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-react-page.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit-new.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-tooklit-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-tooklit-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfxTab-spfx.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfxTab-spfx.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/ssl-prompt.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/ssl-prompt.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/videos/spfx-tab-source.gif](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/videos/spfx-tab-source.gif) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/sbs-gs-spfx.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/sbs-gs-spfx.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C19%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204190725284219-5734%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-20T07%3A26%3A07Z&sr=b&sp=r&sig=rNuUJnb3o%2F57vaYOs8mvKdeXMzv2gQURBTvmqssDKlw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-19 07:34 UTC, opbld30 commented
Docs Build status updates of commit _[b29d0dc](https://github.com/MicrosoftDocs/msteams-docs/commits/b29d0dca9fd1767f63a566d559d2c199fd9469af)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/teams-toolkit-v2/sbs-share-point.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/sbs-share-point.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-Teams-toolkit.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-Teams-toolkit.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-another-helloworld.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-another-helloworld.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-custom-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-custom-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-debug.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-debug.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-helloworld.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-helloworld.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-install-toolkit-vscode.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-install-toolkit-vscode.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-microsoft-365.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-microsoft-365.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-new-toolkit.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-new-toolkit.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-new-toolkit.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-preview.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-react-page.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-react-page.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit-new.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-tooklit-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-tooklit-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfxTab-spfx.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfxTab-spfx.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/ssl-prompt.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/ssl-prompt.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/videos/spfx-tab-source.gif](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/videos/spfx-tab-source.gif) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/sbs-gs-spfx.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/sbs-gs-spfx.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C19%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204190733558597-5734%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-20T07%3A34%3A34Z&sr=b&sp=r&sig=glSMKTWPyAKSfFLp2AMvn86sfe6b80n55gdldcXezQg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-19 07:38 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-spfx.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/88a6629c731477e8784d3042fb7238dbfab276e8/msteams-platform%2Fsbs-gs-spfx.yml) | 95 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/67f82e74-f111-469f-80a3-a296058b5163) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-19 07:39 UTC, opbld31 commented
Docs Build status updates of commit _[88a6629](https://github.com/MicrosoftDocs/msteams-docs/commits/88a6629c731477e8784d3042fb7238dbfab276e8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/teams-toolkit-v2/sbs-share-point.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/sbs-share-point.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-Teams-toolkit.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-Teams-toolkit.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-another-helloworld.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-another-helloworld.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-custom-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-custom-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-debug.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-debug.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-helloworld.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-helloworld.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-install-toolkit-vscode.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-install-toolkit-vscode.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-microsoft-365.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-microsoft-365.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-new-toolkit.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-new-toolkit.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-new-toolkit.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-preview.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-react-page.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-react-page.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit-new.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-tooklit-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-tooklit-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfxTab-spfx.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfxTab-spfx.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/ssl-prompt.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/ssl-prompt.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/videos/spfx-tab-source.gif](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/videos/spfx-tab-source.gif) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/sbs-gs-spfx.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/sbs-gs-spfx.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C19%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204190738222243-5734%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-20T07%3A39%3A03Z&sr=b&sp=r&sig=y96bkJ3RmiZBl9QveaJrEDIW7zwnwswoSlfOI1NCgvk%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-19 10:06 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-spfx.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/36c56cea0b10755b19275c6f5a5eacbd65598599/msteams-platform%2Fsbs-gs-spfx.yml) | 95 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a398fcca-9bf1-43c1-86d4-cb66c77dabf3) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-19 10:06 UTC, opbld31 commented
Docs Build status updates of commit _[36c56ce](https://github.com/MicrosoftDocs/msteams-docs/commits/36c56cea0b10755b19275c6f5a5eacbd65598599)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/teams-toolkit-v2/first-tab/location-change-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/first-tab/location-change-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/sbs-share-point.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/sbs-share-point.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-Teams-toolkit.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-Teams-toolkit.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-another-helloworld.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-another-helloworld.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-custom-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-custom-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-debug.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-debug.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-helloworld.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-helloworld.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-install-toolkit-vscode.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-install-toolkit-vscode.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-microsoft-365.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-microsoft-365.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-new-toolkit.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-new-toolkit.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-new-toolkit.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-preview.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-react-page.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-react-page.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit-new.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-tooklit-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-tooklit-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfxTab-spfx.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfxTab-spfx.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/ssl-prompt.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/ssl-prompt.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/videos/spfx-tab-source.gif](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/videos/spfx-tab-source.gif) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/sbs-gs-spfx.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/sbs-gs-spfx.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C19%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204191005444742-5734%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-20T10%3A06%3A24Z&sr=b&sp=r&sig=yyutyKsHQOlHLwA1m7SfxZxyR1T7OaVPBb%2FeOtzaYBs%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-19 10:12 UTC, opbld32 commented
Docs Build status updates of commit _[5a33c9a](https://github.com/MicrosoftDocs/msteams-docs/commits/5a33c9add8748ddd28707fce1a32d76cb88bdd78)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/teams-toolkit-v2/first-tab/location-change-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/first-tab/location-change-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/sbs-share-point.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/sbs-share-point.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-Teams-toolkit.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-Teams-toolkit.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-another-helloworld.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-another-helloworld.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-custom-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-custom-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-debug.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-debug.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-helloworld.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-helloworld.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-install-toolkit-vscode.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-install-toolkit-vscode.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-microsoft-365.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-microsoft-365.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-new-toolkit.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-new-toolkit.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-new-toolkit.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-preview.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-react-page.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-react-page.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit-new.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-tooklit-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-tooklit-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfxTab-spfx.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfxTab-spfx.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/ssl-prompt.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/ssl-prompt.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/videos/spfx-tab-source.gif](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/videos/spfx-tab-source.gif) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/sbs-gs-spfx.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/sbs-gs-spfx.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C19%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204191011271339-5734%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-20T10%3A12%3A06Z&sr=b&sp=r&sig=DuCJ32J7Xq2D264HwXpVi0KMQenzFBN3dks4FLT801E%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-19 10:42 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-spfx.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/727064150c4d346b3848119fb3342512385ea547/msteams-platform%2Fsbs-gs-spfx.yml) |   |   | [link]( ) | [:warning:](# "Could not check with Acrolinx&#10;Please close and reopen pull request") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-19 10:42 UTC, opbld32 commented
Docs Build status updates of commit _[7270641](https://github.com/MicrosoftDocs/msteams-docs/commits/727064150c4d346b3848119fb3342512385ea547)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/sbs-gs-spfx.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/sbs-gs-spfx.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) | [Details](#user-content-ba8b60b3814caf1cb1b4ded75b049c70-7c283844)
[msteams-platform/assets/images/teams-toolkit-v2/first-tab/location-change-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/first-tab/location-change-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/sbs-share-point.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/sbs-share-point.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-Teams-toolkit.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-Teams-toolkit.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-another-helloworld.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-another-helloworld.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-custom-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-custom-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-debug.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-debug.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-helloworld.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-helloworld.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-install-toolkit-vscode.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-install-toolkit-vscode.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-microsoft-365.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-microsoft-365.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-new-toolkit.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-new-toolkit.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-new-toolkit.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-preview.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-react-page.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-react-page.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit-new.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-tooklit-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-tooklit-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfxTab-spfx.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfxTab-spfx.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfxtab-spfx.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/ssl-prompt.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/ssl-prompt.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/videos/spfx-tab-source.gif](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/videos/spfx-tab-source.gif) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |

<a id="ba8b60b3814caf1cb1b4ded75b049c70-7c283844"></a>
### [msteams-platform/sbs-gs-spfx.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/sbs-gs-spfx.yml)
 - **Line 167, Column 5**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '~/assets/images/teams-toolkit-v2/prerequisites/spfx-tab-new.png'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C19%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204191041441653-5734%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-20T10%3A42%3A39Z&sr=b&sp=r&sig=dKcxRVwphUwEY4dkxnljNJhardTkYzCplcDhUP5cNIM%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build repor [...]

2022-04-19 10:48 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-spfx.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/49a2edae7243f4e4e8c5b86eac76b2210ff362b2/msteams-platform%2Fsbs-gs-spfx.yml) | 95 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/642f72a1-2247-46f6-b787-94e99ac427a9) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-19 10:48 UTC, opbld31 commented
Docs Build status updates of commit _[49a2eda](https://github.com/MicrosoftDocs/msteams-docs/commits/49a2edae7243f4e4e8c5b86eac76b2210ff362b2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/teams-toolkit-v2/first-tab/location-change-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/first-tab/location-change-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/prerequisites/spfx-tab-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/prerequisites/spfx-tab-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/sbs-share-point.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/sbs-share-point.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-Teams-toolkit.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-Teams-toolkit.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-another-helloworld.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-another-helloworld.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-custom-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-custom-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-debug.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-debug.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-helloworld.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-helloworld.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-install-toolkit-vscode.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-install-toolkit-vscode.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-microsoft-365.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-microsoft-365.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-new-toolkit.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-new-toolkit.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-new-toolkit.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-preview.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-react-page.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-react-page.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit-new.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-tooklit-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-tooklit-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfxTab-spfx.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfxTab-spfx.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfxtab-spfx.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/ssl-prompt.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/ssl-prompt.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/videos/spfx-tab-source.gif](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/videos/spfx-tab-source.gif) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/sbs-gs-spfx.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/sbs-gs-spfx.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C19%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204191047299123-5734%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-20T10%3A48%3A10Z&sr=b&sp=r&sig=i35MsSm3v%2Bun%2FDEcxBorVgB%2FQL125g1H%2FyHEFc4iD3w%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a398 [...]

2022-04-19 11:01 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-spfx.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/62eadc685eef6f1d26f2a9989f7f81a0f2e18a14/msteams-platform%2Fsbs-gs-spfx.yml) | 95 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6bb834e8-43c4-4b57-ac27-cd600cb66e5f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-19 11:01 UTC, opbld30 commented
Docs Build status updates of commit _[62eadc6](https://github.com/MicrosoftDocs/msteams-docs/commits/62eadc685eef6f1d26f2a9989f7f81a0f2e18a14)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/teams-toolkit-v2/first-tab/location-change-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/first-tab/location-change-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/first-tab/select-capabilities-tab.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/first-tab/select-capabilities-tab.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-javascript?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/prerequisites/select-capabilities-tab-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/prerequisites/select-capabilities-tab-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/prerequisites/select-capabilities-tab-new.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/prerequisites/spfx-tab-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/prerequisites/spfx-tab-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/prerequisites/spfx-tab-new.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/sbs-share-point.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/sbs-share-point.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-Teams-toolkit.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-Teams-toolkit.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-another-helloworld.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-another-helloworld.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-custom-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-custom-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-debug.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-debug.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-helloworld.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-helloworld.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-install-toolkit-vscode.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-install-toolkit-vscode.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-microsoft-365.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-microsoft-365.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-new-toolkit.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-new-toolkit.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-new-toolkit.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-preview.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-react-page.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-react-page.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit-new.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-tooklit-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-tooklit-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfxTab-spfx.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfxTab-spfx.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/ssl-prompt.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/ssl-prompt.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/videos/spfx-tab-source.gif](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/videos/spfx-tab-source.gif) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/sbs-gs-spfx.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/sbs-gs-spfx.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |

For more d [...]

2022-04-20 01:59 UTC, xu-hong commented on msteams-platform/sbs-gs-spfx.yml
>      1. Deselect **Tab**, select **Tab(SPFx)**, and select **OK**.
add a space before `(`, so select `**Tab (SPFx)**`

2022-04-20 01:59 UTC, xu-hong commented on msteams-platform/sbs-gs-spfx.yml
> +        Teams Toolkit invokes Yeoman CLI to scaffold your Teams app, and install the required dependencies in the process.</br>
Delete "Your Teams app is created within a few seconds."

2022-04-20 02:01 UTC, xu-hong requested changes
thanks, made 2 comments

2022-04-20 02:11 UTC, xu-hong commented on msteams-platform/sbs-gs-spfx.yml
> +        :::image type="content" source="~/assets/images/teams-toolkit-v2/spfxTab-spfx.png" alt-text="tab spfx new" border="true":::
Found another one: looks like this is still pointing to the previous png file, not the latest one that I sent to you?

2022-04-20 09:05 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-spfx.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/b707ef4bbc0f94652e848d807542e61c78e761ff/msteams-platform%2Fsbs-gs-spfx.yml) | 95 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/05f91590-bccd-4dec-bd6b-be6369421e6c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-20 09:05 UTC, opbld30 commented
Docs Build status updates of commit _[b707ef4](https://github.com/MicrosoftDocs/msteams-docs/commits/b707ef4bbc0f94652e848d807542e61c78e761ff)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/teams-toolkit-v2/first-tab/location-change-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/first-tab/location-change-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/first-tab/select-capabilities-tab.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/first-tab/select-capabilities-tab.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-javascript?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/prerequisites/select-capabilities-tab-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/prerequisites/select-capabilities-tab-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/prerequisites/select-capabilities-tab-new.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/prerequisites/spfx-tab-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/prerequisites/spfx-tab-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/prerequisites/spfx-tab-new.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/sbs-share-point.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/sbs-share-point.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-Teams-toolkit.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-Teams-toolkit.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-another-helloworld.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-another-helloworld.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-custom-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-custom-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-debug.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-debug.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-helloworld.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-helloworld.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-install-toolkit-vscode.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-install-toolkit-vscode.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-microsoft-365.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-microsoft-365.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-new-toolkit.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-new-toolkit.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-new-toolkit.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-preview.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-react-page.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-react-page.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit-new.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-tooklit-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-tooklit-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfxTab-spfx.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfxTab-spfx.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/ssl-prompt.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/ssl-prompt.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/videos/spfx-tab-source.gif](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/videos/spfx-tab-source.gif) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/sbs-gs-spfx.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/sbs-gs-spfx.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |

For more d [...]

2022-04-20 09:13 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-spfx.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1a90c140a6a299ff3cf126b4c349e7dc59ad64be/msteams-platform%2Fsbs-gs-spfx.yml) | 95 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/644d0b0a-26d0-4a1f-a9c6-bd483d1a37a0) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-20 09:13 UTC, opbld32 commented
Docs Build status updates of commit _[1a90c14](https://github.com/MicrosoftDocs/msteams-docs/commits/1a90c140a6a299ff3cf126b4c349e7dc59ad64be)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/teams-toolkit-v2/first-tab/location-change-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/first-tab/location-change-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/first-tab/select-capabilities-tab.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/first-tab/select-capabilities-tab.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-javascript?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/prerequisites/new-spfx-tab.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/prerequisites/new-spfx-tab.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/prerequisites/select-capabilities-tab-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/prerequisites/select-capabilities-tab-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/prerequisites/select-capabilities-tab-new.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/prerequisites/spfx-tab-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/prerequisites/spfx-tab-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/prerequisites/spfx-tab-new.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/sbs-share-point.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/sbs-share-point.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-Teams-toolkit.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-Teams-toolkit.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-another-helloworld.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-another-helloworld.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-custom-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-custom-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-debug.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-debug.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-helloworld.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-helloworld.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-install-toolkit-vscode.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-install-toolkit-vscode.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-microsoft-365.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-microsoft-365.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-new-toolkit.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-new-toolkit.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-new-toolkit.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-preview.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-react-page.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-react-page.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfx-teams-toolkit-new.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-tooklit-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfx-tooklit-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/spfxTab-spfx.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/spfxTab-spfx.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/spfxtab-spfx.png?branch=pr-en-us-5734) |
[msteams-platform/assets/images/teams-toolkit-v2/ssl-prompt.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/images/teams-toolkit-v2/ssl-prompt.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5734) |
[msteams-platform/assets/videos/spfx-tab-source.gif](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-spfx/msteams-platform/assets/videos/spfx-tab-source.gif) | :white_check_mark:Su [...]

2022-04-20 09:21 UTC, xu-hong approved these changes
LGTM, thanks!!

2022-04-20 09:31 UTC, surbhigupta12 approved these changes

2022-04-20 09:31 UTC, merged