[Doc Feature][Enable Link unfurling for compose box extension on Mobile][2270588]
MicrosoftDocs/msteams-docs pull request #5767
Opened 2022-04-21 11:05 UTC by vsoniv

2022-04-21 11:06 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6ce8ce7832b444065828667273e6d55ac2c1213e/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 94 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4e7f7025-a5f1-4c1d-b727-4be8ae99975e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-21 11:06 UTC, opbld30 commented
Docs Build status updates of commit _[6ce8ce7](https://github.com/MicrosoftDocs/msteams-docs/commits/6ce8ce7832b444065828667273e6d55ac2c1213e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/messaging-extensions/how-to/link-unfurling.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C21%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204211105514839-5767%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-22T11%3A06%3A43Z&sr=b&sp=r&sig=zFBAUVYnYwY0Xy%2BalJKvY8Ii5Sn57xE42waYPct088s%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-22 10:18 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5f54c9384df9fea844ad91459b54d47f99533fe0/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 94 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/235fa2db-b5ae-455c-b6c2-e79cd88e17a7) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-22 10:18 UTC, opbld30 commented
Docs Build status updates of commit _[5f54c93](https://github.com/MicrosoftDocs/msteams-docs/commits/5f54c9384df9fea844ad91459b54d47f99533fe0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/messaging-extensions/how-to/link-unfurling.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C22%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204221017468459-5767%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-23T10%3A18%3A37Z&sr=b&sp=r&sig=y%2BhJ48KAlubE%2Bkbjr5bRTmCPbnsR8GTHhBJuPf71nqw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-22 10:45 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5c506a847eb7af553197a33298283929d8ac73f6/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/61fcb57a-c9aa-4883-a8c0-608ba22662a3) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-22 10:45 UTC, opbld31 commented
Docs Build status updates of commit _[5c506a8](https://github.com/MicrosoftDocs/msteams-docs/commits/5c506a847eb7af553197a33298283929d8ac73f6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/messaging-extensions/how-to/link-unfurling.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) | [Details](#user-content-5d6d73cdb6df317e67b4e47d8fcb779e-10f82552)
[msteams-platform/assets/images/compose-extensions/Capture 3.1.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%203.1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%203.1.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 3.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%203.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%203.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 4.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%204.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%204.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 5.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%205.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%205.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 7.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%207.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%207.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 8.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%208.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%208.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_1.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_2.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |

<a id="5d6d73cdb6df317e67b4e47d8fcb779e-10f82552"></a>
### [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/messaging-extensions/how-to/link-unfurling.md)
 - **Line 25, Column 1**: **[Warning: duplicate-alt-text - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-alt-text?branch=main)]** `````Alt text 'Example of link unfurling' is duplicated. Within an article, alt text must be unique.`````
 - **Line 31, Column 1**: **[Warning: duplicate-alt-text - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-alt-text?branch=main)]** `````Alt text 'Example of link unfurling' is duplicated. Within an article, alt text must be unique.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C22%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204221044439995-5767%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-23T10%3A45%3A28Z&sr=b&sp=r&sig=Z3uuBdRGso0qUuiiG4NjPNawvNC4sh8CPTtYwPAqcoQ%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-22 10:52 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b1a7e8316ca1eb25959dca0fec1e28a852cfdb43/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/802a346e-c233-4b0f-b903-82b9cf8ceb43) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-22 10:52 UTC, opbld33 commented
Docs Build status updates of commit _[b1a7e83](https://github.com/MicrosoftDocs/msteams-docs/commits/b1a7e8316ca1eb25959dca0fec1e28a852cfdb43)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/messaging-extensions/how-to/link-unfurling.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) | [Details](#user-content-5d6d73cdb6df317e67b4e47d8fcb779e-acfa0b55)
[msteams-platform/assets/images/compose-extensions/Capture 3.1.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%203.1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%203.1.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 3.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%203.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%203.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 4.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%204.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%204.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 5.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%205.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%205.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 7.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%207.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%207.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 8.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%208.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%208.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_1.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_2.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |

<a id="5d6d73cdb6df317e67b4e47d8fcb779e-acfa0b55"></a>
### [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/messaging-extensions/how-to/link-unfurling.md)
 - **Line 25, Column 1**: **[Warning: duplicate-alt-text - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-alt-text?branch=main)]** `````Alt text 'Example of link unfurling' is duplicated. Within an article, alt text must be unique.`````
 - **Line 31, Column 1**: **[Warning: duplicate-alt-text - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-alt-text?branch=main)]** `````Alt text 'Example of link unfurling' is duplicated. Within an article, alt text must be unique.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C22%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204221052033904-5767%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-23T10%3A52%3A51Z&sr=b&sp=r&sig=kJeO06gjAp3pP2XbAmQx84%2Ff1CEBkQrFLX%2BIfuG1DOs%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-22 10:55 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/74742849bf56f7882d739bf1a3b178894cc47d00/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/593a3f9f-d7b8-444c-b6f1-90b7e17938c1) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-22 10:55 UTC, opbld30 commented
Docs Build status updates of commit _[7474284](https://github.com/MicrosoftDocs/msteams-docs/commits/74742849bf56f7882d739bf1a3b178894cc47d00)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/compose-extensions/Capture 3.1.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%203.1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%203.1.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 3.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%203.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%203.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 4.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%204.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%204.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 5.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%205.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%205.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 7.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%207.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%207.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 8.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%208.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%208.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_1.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_2.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/messaging-extensions/how-to/link-unfurling.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C22%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204221054523250-5767%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-23T10%3A55%3A31Z&sr=b&sp=r&sig=pm5xRwTWFvW%2BuuQT3De3UWkyvFbExmfwBJQrmeFNDGI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-22 10:57 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9b6a5fd3f22e3444b7ee9f9a42d68bc2c5bc7c38/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/399fb858-b7db-4a51-9410-7368c1d07672) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-22 10:58 UTC, opbld32 commented
Docs Build status updates of commit _[9b6a5fd](https://github.com/MicrosoftDocs/msteams-docs/commits/9b6a5fd3f22e3444b7ee9f9a42d68bc2c5bc7c38)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/compose-extensions/Capture 3.1.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%203.1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%203.1.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 3.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%203.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%203.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 4.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%204.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%204.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 5.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%205.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%205.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 7.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%207.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%207.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 8.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%208.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%208.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_1.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_2.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/messaging-extensions/how-to/link-unfurling.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C22%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204221057165053-5767%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-23T10%3A58%3A58Z&sr=b&sp=r&sig=UAUdgMtkoYKPh79xqOwiEDTQjBxquddIzMnQQ%2BYEqqY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-22 11:05 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d329a4f14109ac79bd6d46ef8a7e408f40f3849c/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9485f6be-b8b5-4b1c-a806-1d143346d66f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-22 11:05 UTC, opbld32 commented
Docs Build status updates of commit _[d329a4f](https://github.com/MicrosoftDocs/msteams-docs/commits/d329a4f14109ac79bd6d46ef8a7e408f40f3849c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/compose-extensions/Capture 4.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%204.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%204.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 5.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%205.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%205.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 7.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%207.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%207.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 8.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%208.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%208.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_1.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_2.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_3.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_3.png?branch=pr-en-us-5767) |
[msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/messaging-extensions/how-to/link-unfurling.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C22%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204221105033221-5767%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-23T11%3A05%3A41Z&sr=b&sp=r&sig=%2FpU2e4MHdv0dJruYGln5uy%2Bo0mpM8Bs7PJAUABXv6yQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-22 11:25 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/62d1225af943c1bde71082fd8ebac48716bdfbe6/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 88 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0f188fd1-700e-4dd7-a729-da2eeb964e52) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-22 11:26 UTC, opbld33 commented
Docs Build status updates of commit _[62d1225](https://github.com/MicrosoftDocs/msteams-docs/commits/62d1225af943c1bde71082fd8ebac48716bdfbe6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/compose-extensions/Capture 4.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%204.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%204.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 5.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%205.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%205.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 7.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%207.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%207.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 8.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%208.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%208.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_1.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_2.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_3.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_3.png?branch=pr-en-us-5767) |
[msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/messaging-extensions/how-to/link-unfurling.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C22%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204221125284252-5767%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-23T11%3A26%3A14Z&sr=b&sp=r&sig=YzcVDMq3Ytq1IgUPRcOwXdltOEWTbeO%2FjMXWhiY2Wr0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-29 06:09 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/685f6ce7a57961c9b33f9e40340fe10d9794fd24/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 89 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/594ccc32-a885-4f59-8c3b-980ddaa7db23) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-29 06:09 UTC, opbld33 commented
Docs Build status updates of commit _[685f6ce](https://github.com/MicrosoftDocs/msteams-docs/commits/685f6ce7a57961c9b33f9e40340fe10d9794fd24)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/compose-extensions/Capture 4.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%204.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%204.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 5.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%205.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%205.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 7.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%207.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%207.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 8.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%208.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%208.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_1.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_2.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_3.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_3.png?branch=pr-en-us-5767) |
[msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/messaging-extensions/how-to/link-unfurling.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C29%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204290608497597-5767%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-30T06%3A09%3A27Z&sr=b&sp=r&sig=w1HM1nCHrU6TUoJ9qG2bRAW263Opp22py30HtNp9YQI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-29 06:26 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8fa3b84e3f5059fd5170415467c9ce73dbd3cffd/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 86 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3028b53e-8dfc-477a-90b4-34bbf5e8ecab) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-29 06:27 UTC, opbld32 commented
Docs Build status updates of commit _[8fa3b84](https://github.com/MicrosoftDocs/msteams-docs/commits/8fa3b84e3f5059fd5170415467c9ce73dbd3cffd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/compose-extensions/Capture 4.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%204.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%204.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 5.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%205.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%205.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 7.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%207.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%207.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 8.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%208.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%208.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_1.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_1.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_2.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_3.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_3.png?branch=pr-en-us-5767) |
[msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/messaging-extensions/how-to/link-unfurling.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C29%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204290626307588-5767%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-30T06%3A27%3A08Z&sr=b&sp=r&sig=JdpHxB5g5oelhWnn5aV8agbOE48bL1F%2FFPS8%2FIb1DQc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-29 06:55 UTC, opbld32 commented
Docs Build status updates of commit _[55bc7d4](https://github.com/MicrosoftDocs/msteams-docs/commits/55bc7d456a6447bf01a08b59279a005b7001db96)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-e62841a9)

<a id="e62841a9"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C29%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204290654411215-5767%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-30T06%3A55%3A00Z&sr=b&sp=r&sig=fL7k%2FZfvkAuos3udcT2PHMr83f%2F%2FmVYJGBtpHPectYk%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-29 06:55 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/55bc7d456a6447bf01a08b59279a005b7001db96/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 86 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6081e64c-7c60-4604-9123-e3766e700c1f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-29 06:59 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/db4010598770c26061fccbf30653547144e4e33e/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 86 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4917c4f8-becd-4abd-81cb-7c87caedb405) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-29 08:32 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/afe5f833bbc2d24fb45c1177cdcebbc30a3ab1f4/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 86 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9bd24ba0-87ab-409b-ad71-dce12e12a4e8) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-29 08:33 UTC, opbld32 commented
Docs Build status updates of commit _[afe5f83](https://github.com/MicrosoftDocs/msteams-docs/commits/afe5f833bbc2d24fb45c1177cdcebbc30a3ab1f4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/messaging-extensions/how-to/link-unfurling.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) | [Details](#user-content-5d6d73cdb6df317e67b4e47d8fcb779e-2c2c7650)
[msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling - Shortcut.lnk](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling%20-%20Shortcut.lnk) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/feature-mobile-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 4.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%204.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%204.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 5.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%205.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%205.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 7.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%207.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%207.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 8.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%208.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%208.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_1.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_1.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_2.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_2.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_3.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_3.png?branch=pr-en-us-5767) |

<a id="5d6d73cdb6df317e67b4e47d8fcb779e-2c2c7650"></a>
### [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/messaging-extensions/how-to/link-unfurling.md)
 - **Line 31, Column 1**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '~/assets/images/Teams-link-unfurling/feature-mobile-new..png'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C29%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204290832191295-5767%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-30T08%3A33%3A00Z&sr=b&sp=r&sig=TAL8xxhPjmkkxhxCB6sTTWjA7kte7rKDGKkx2dNpo0I%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-29 08:39 UTC, opbld31 commented
Docs Build status updates of commit _[522d02d](https://github.com/MicrosoftDocs/msteams-docs/commits/522d02dab8cc6f5aa8ea2c490cb7489d01dc5052)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling - Shortcut.lnk](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling%20-%20Shortcut.lnk) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 4.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%204.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%204.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 5.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%205.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%205.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 7.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%207.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%207.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 8.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%208.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%208.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_1.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_1.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_2.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_2.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_3.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_3.png?branch=pr-en-us-5767) |
[msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/messaging-extensions/how-to/link-unfurling.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C29%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204290838275889-5767%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-30T08%3A39%3A04Z&sr=b&sp=r&sig=PSPCz3XG5mNquVhQ8wiZLufCbbMA%2BhVzA0r9z0T%2BQd8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-29 10:57 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5680cc5f580966c0f22ed0571c0027baa70b4187/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 85 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6e5e8b39-67b6-4486-8f8b-62ef57f85eb0) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-04-29 10:57 UTC, opbld31 commented
Docs Build status updates of commit _[5680cc5](https://github.com/MicrosoftDocs/msteams-docs/commits/5680cc5f580966c0f22ed0571c0027baa70b4187)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/messaging-extensions/how-to/link-unfurling.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) | [Details](#user-content-5d6d73cdb6df317e67b4e47d8fcb779e-9a2f0b0f)
[msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling - Shortcut.lnk](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling%20-%20Shortcut.lnk) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/card-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/card-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/congi-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/congi-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/install-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/install-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 4.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%204.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%204.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 5.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%205.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%205.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 7.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%207.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%207.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 8.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%208.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%208.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_1.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_1.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_2.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_2.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_3.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_3.png?branch=pr-en-us-5767) |

<a id="5d6d73cdb6df317e67b4e47d8fcb779e-9a2f0b0f"></a>
### [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/messaging-extensions/how-to/link-unfurling.md)
 - **Line 67, Column 1**: **[Warning: alt-text-bad-value - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/alt-text-bad-value?branch=main)]** `````Alt text 'Url-preview' is the same as the image file name. This redundancy adds no value for users of screen readers. For accessibility, add more descriptive alt text.`````
 - **Line 76, Column 1**: **[Warning: alt-text-bad-value - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/alt-text-bad-value?branch=main)]** `````Alt text 'install-preview' is the same as the image file name. This redundancy adds no value for users of screen readers. For accessibility, add more descriptive alt text.`````
 - **Line 85, Column 1**: **[Warning: alt-text-bad-value - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/alt-text-bad-value?branch=main)]** `````Alt text 'congi-preview' is the same as the image file name. This redundancy adds no value for users of screen readers. For accessibility, add more descriptive alt text.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C29%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204291056449669-5767%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-30T10%3A57%3A21Z&sr=b&sp=r&sig=%2BeHjhCNtgSq9I%2BhnDYlMkyeSnpSzOIJhVx8jKHiOn0g%3D).

If you see build warnings/errors with permission issues, it might  [...]

2022-04-29 14:07 UTC, opbld31 commented
Docs Build status updates of commit _[76dbf18](https://github.com/MicrosoftDocs/msteams-docs/commits/76dbf185e4032665ffadc038753f269af4d42a49)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/messaging-extensions/how-to/link-unfurling.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) | [Details](#user-content-5d6d73cdb6df317e67b4e47d8fcb779e-2fe55c5d)
[msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling - Shortcut.lnk](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling%20-%20Shortcut.lnk) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/card-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/card-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/congi-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/congi-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/install-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/install-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 4.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%204.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%204.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 5.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%205.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%205.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 7.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%207.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%207.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 8.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%208.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%208.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_1.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_1.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_2.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_2.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_3.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_3.png?branch=pr-en-us-5767) |

<a id="5d6d73cdb6df317e67b4e47d8fcb779e-2fe55c5d"></a>
### [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/messaging-extensions/how-to/link-unfurling.md)
 - **Line 67, Column 1**: **[Warning: alt-text-bad-value - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/alt-text-bad-value?branch=main)]** `````Alt text 'Url-preview' is the same as the image file name. This redundancy adds no value for users of screen readers. For accessibility, add more descriptive alt text.`````
 - **Line 76, Column 1**: **[Warning: alt-text-bad-value - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/alt-text-bad-value?branch=main)]** `````Alt text 'install-preview' is the same as the image file name. This redundancy adds no value for users of screen readers. For accessibility, add more descriptive alt text.`````
 - **Line 85, Column 1**: **[Warning: alt-text-bad-value - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/alt-text-bad-value?branch=main)]** `````Alt text 'congi-preview' is the same as the image file name. This redundancy adds no value for users of screen readers. For accessibility, add more descriptive alt text.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C29%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204291406443319-5767%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-30T14%3A07%3A25Z&sr=b&sp=r&sig=OYg8Yf%2BQdHwx2Bt6qc208Bws6umrfTi9bfwLwHVJwng%3D).

If you see build warnings/errors with permission issues, it might be [...]

2022-05-02 05:25 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c053bc08aa4099c317e99feef7e1b1fd60d28547/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 85 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b9d94b3a-7225-49c7-a920-4b56d64026c7) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-02 05:26 UTC, opbld31 commented
Docs Build status updates of commit _[c053bc0](https://github.com/MicrosoftDocs/msteams-docs/commits/c053bc08aa4099c317e99feef7e1b1fd60d28547)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling - Shortcut.lnk](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling%20-%20Shortcut.lnk) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/card-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/card-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/congi-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/congi-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/install-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/install-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 4.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%204.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%204.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 5.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%205.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%205.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 7.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%207.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%207.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 8.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%208.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%208.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_1.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_1.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_2.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_2.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_3.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_3.png?branch=pr-en-us-5767) |
[msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/messaging-extensions/how-to/link-unfurling.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C2%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202205020525271229-5767%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-02T05%3A26%3A17Z&sr=b&sp=r&sig=WyO7z8S8hmhvxLfLx2ryJrHZcS9IJWgqgmiO4hf9SOA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-02 06:32 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/94262be92bc777548684ba3fbe68a10f9aed6af3/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 86 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5ffa4a52-3775-4df6-af8a-96ad8dffaf2a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-02 06:32 UTC, opbld30 commented
Docs Build status updates of commit _[94262be](https://github.com/MicrosoftDocs/msteams-docs/commits/94262be92bc777548684ba3fbe68a10f9aed6af3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/messaging-extensions/how-to/link-unfurling.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) | [Details](#user-content-5d6d73cdb6df317e67b4e47d8fcb779e-5b18bd42)
[msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling - Shortcut.lnk](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling%20-%20Shortcut.lnk) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/card-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/card-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/congi-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/congi-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/congi-preview.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/install-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/install-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/install-preview.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 4.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%204.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%204.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 5.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%205.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%205.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 7.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%207.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%207.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 8.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%208.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%208.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_1.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_1.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_2.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_2.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_3.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_3.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/share-to-teams/auth-preview-updated.JPG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/share-to-teams/auth-preview-updated.JPG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/share-to-teams/auth-preview-updated.jpg?branch=pr-en-us-5767) |
[msteams-platform/assets/images/share-to-teams/install-preview-updated-new.JPG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/share-to-teams/install-preview-updated-new.JPG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/share-to-teams/install-preview-updated-new.jpg?branch=pr-en-us-5767) |

<a id="5d6d73cdb6df317e67b4e47d8fcb779e-5b18bd42"></a>
### [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/messaging-extensions/how-to/link-unfurling.md)
 - **Line 72, Column 1**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '~/assets/images/share-to-teams/install-preview-updated-new.png'.`````
 - **Line 81, Column 1**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '~/assets/images/share-to-teams/auth-preview-updated.png'.`````

For more details, please refer to the [build report](https://opbuilduserst [...]

2022-05-02 06:49 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1a537ab2a0860f5cec75cd7efccfd6832dd55161/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 86 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aefc1db9-0418-4fc1-812c-6e85ebaf141d) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-02 06:50 UTC, opbld31 commented
Docs Build status updates of commit _[1a537ab](https://github.com/MicrosoftDocs/msteams-docs/commits/1a537ab2a0860f5cec75cd7efccfd6832dd55161)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/messaging-extensions/how-to/link-unfurling.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) | [Details](#user-content-5d6d73cdb6df317e67b4e47d8fcb779e-ca035b9c)
[msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling - Shortcut.lnk](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling%20-%20Shortcut.lnk) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/card-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/card-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/congi-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/congi-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/install-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/install-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 4.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%204.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%204.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 5.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%205.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%205.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 7.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%207.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%207.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 8.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%208.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%208.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_1.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_1.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_2.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_2.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_3.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_3.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/share-to-teams/auth-preview-updated.JPG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/share-to-teams/auth-preview-updated.JPG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/share-to-teams/auth-preview-updated.jpg?branch=pr-en-us-5767) |
[msteams-platform/assets/images/share-to-teams/install-preview-updated-new.JPG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/share-to-teams/install-preview-updated-new.JPG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/share-to-teams/install-preview-updated-new.jpg?branch=pr-en-us-5767) |

<a id="5d6d73cdb6df317e67b4e47d8fcb779e-ca035b9c"></a>
### [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/messaging-extensions/how-to/link-unfurling.md)
 - **Line 72, Column 1**: **[Warning: duplicate-alt-text - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-alt-text?branch=main)]** `````Alt text 'install preview updated' is duplicated. Within an article, alt text must be unique.`````
 - **Line 81, Column 1**: **[Warning: duplicate-alt-text - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-alt-text?branch=main)]** `````Alt text 'install preview updated' is duplicated. Within an article, alt text must be unique.`````

For more details, please refer to the [build report](ht [...]

2022-05-02 06:58 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bad004dad02142614bd666560a4209dc35a99d89/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 86 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3cda5564-87e7-4454-8b2d-f696c4f565ef) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-02 06:58 UTC, opbld31 commented
Docs Build status updates of commit _[bad004d](https://github.com/MicrosoftDocs/msteams-docs/commits/bad004dad02142614bd666560a4209dc35a99d89)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/messaging-extensions/how-to/link-unfurling.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) | [Details](#user-content-5d6d73cdb6df317e67b4e47d8fcb779e-dae5d5e3)
[msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling - Shortcut.lnk](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling%20-%20Shortcut.lnk) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/auth-preview-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/card-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/card-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/congi-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/congi-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/install-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/install-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 4.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%204.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%204.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 5.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%205.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%205.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 7.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%207.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%207.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 8.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%208.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%208.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_1.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_1.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_2.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_2.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_3.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_3.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/share-to-teams/auth-preview-updated.JPG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/share-to-teams/auth-preview-updated.JPG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/share-to-teams/auth-preview-updated.jpg?branch=pr-en-us-5767) |
[msteams-platform/assets/images/share-to-teams/install-preview-updated-new.JPG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/share-to-teams/install-preview-updated-new.JPG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/share-to-teams/install-preview-updated-new.jpg?branch=pr-en-us-5767) |

<a id="5d6d73cdb6df317e67b4e47d8fcb779e-dae5d5e3"></a>
### [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/messaging-extensions/how-to/link-unfurling.md)
 - **Line 72, Column 1**: **[Warning: duplicate-alt-text - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-alt-text?branch=main)]** ```` [...]

2022-05-02 07:01 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ea3f7be248cdaa01a6780976089ce79ed606405d/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 86 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fca5436e-17d2-4c9b-ac6d-fac6783cce93) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-02 07:01 UTC, opbld30 commented
Docs Build status updates of commit _[ea3f7be](https://github.com/MicrosoftDocs/msteams-docs/commits/ea3f7be248cdaa01a6780976089ce79ed606405d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/messaging-extensions/how-to/link-unfurling.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) | [Details](#user-content-5d6d73cdb6df317e67b4e47d8fcb779e-95f7e0e0)
[msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling - Shortcut.lnk](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling%20-%20Shortcut.lnk) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/auth-preview-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/card-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/card-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/congi-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/congi-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/install-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/install-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 4.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%204.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%204.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 5.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%205.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%205.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 7.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%207.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%207.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 8.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%208.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%208.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_1.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_1.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_2.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_2.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_3.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_3.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/share-to-teams/auth-preview-updated.JPG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/share-to-teams/auth-preview-updated.JPG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/share-to-teams/auth-preview-updated.jpg?branch=pr-en-us-5767) |
[msteams-platform/assets/images/share-to-teams/install-preview-updated-new.JPG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/share-to-teams/install-preview-updated-new.JPG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/share-to-teams/install-preview-updated-new.jpg?branch=pr-en-us-5767) |

<a id="5d6d73cdb6df317e67b4e47d8fcb779e-95f7e0e0"></a>
### [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/messaging-extensions/how-to/link-unfurling.md)
 - **Line 72, Column 1**: **[Warning: duplicate-alt-text - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-alt-text?branch=main)]** ```` [...]

2022-05-02 07:03 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ee13b5c1c1e658be5e978d9387f09622170180ec/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 86 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/19b87740-0c2c-4a14-a226-80d1db42d2f4) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-02 07:03 UTC, opbld33 commented
Docs Build status updates of commit _[ee13b5c](https://github.com/MicrosoftDocs/msteams-docs/commits/ee13b5c1c1e658be5e978d9387f09622170180ec)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/messaging-extensions/how-to/link-unfurling.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) | [Details](#user-content-5d6d73cdb6df317e67b4e47d8fcb779e-cc3a554d)
[msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling - Shortcut.lnk](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling%20-%20Shortcut.lnk) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/auth-preview-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/card-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/card-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/congi-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/congi-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/install-preview-updated-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/install-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/install-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 4.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%204.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%204.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 5.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%205.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%205.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 7.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%207.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%207.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 8.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%208.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%208.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_1.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_1.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_2.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_2.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_3.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_3.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/share-to-teams/auth-preview-updated.JPG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/share-to-teams/auth-preview-updated.JPG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/share-to-teams/auth-preview-updated.jpg?branch=pr-en-us-5767) |
[msteams-platform/assets/images/share-to-teams/install-preview-updated-new.JPG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/share-to-teams/install-preview-updated-new.JPG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/share-to-teams/install-preview-updated- [...]

2022-05-02 07:05 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/74fa36744a0aaec8419a2358ba0ecdc5038150b4/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 86 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9dca4625-2175-4ca6-9b55-4a2776b88a6c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-02 07:06 UTC, opbld32 commented
Docs Build status updates of commit _[74fa367](https://github.com/MicrosoftDocs/msteams-docs/commits/74fa36744a0aaec8419a2358ba0ecdc5038150b4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling - Shortcut.lnk](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling%20-%20Shortcut.lnk) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/card-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/card-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 4.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%204.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%204.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 5.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%205.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%205.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 7.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%207.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%207.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 8.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%208.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%208.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_1.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_1.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_2.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_2.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_3.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_3.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/share-to-teams/auth-preview-updated.JPG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/share-to-teams/auth-preview-updated.JPG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/share-to-teams/auth-preview-updated.jpg?branch=pr-en-us-5767) |
[msteams-platform/assets/images/share-to-teams/install-preview-updated-new.JPG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/share-to-teams/install-preview-updated-new.JPG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/share-to-teams/install-preview-updated-new.jpg?branch=pr-en-us-5767) |
[msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/messaging-extensions/how-to/link-unfurling.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C2%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202205020705160266-5767%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-02T07%3A06%3A15Z&sr=b&sp=r&sig=bsgA2%2B5rMx5TolBSxjaKZ0cMWugrzD13dHCQeFPr28s%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986 [...]

2022-05-02 08:09 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ae21bc2e87c041bb76914ec9d94dd050e12f9dd1/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 85 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9c889640-51c9-46dc-808f-e760a3cacbb4) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-02 08:10 UTC, opbld30 commented
Docs Build status updates of commit _[ae21bc2](https://github.com/MicrosoftDocs/msteams-docs/commits/ae21bc2e87c041bb76914ec9d94dd050e12f9dd1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling - Shortcut.lnk](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling%20-%20Shortcut.lnk) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/card-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/card-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 4.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%204.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%204.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 5.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%205.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%205.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 7.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%207.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%207.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 8.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%208.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%208.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_1.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_1.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_2.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_2.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_3.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_3.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/share-to-teams/auth-preview-updated.JPG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/share-to-teams/auth-preview-updated.JPG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/share-to-teams/auth-preview-updated.jpg?branch=pr-en-us-5767) |
[msteams-platform/assets/images/share-to-teams/install-preview-updated-new.JPG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/share-to-teams/install-preview-updated-new.JPG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/share-to-teams/install-preview-updated-new.jpg?branch=pr-en-us-5767) |
[msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/messaging-extensions/how-to/link-unfurling.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C2%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202205020809205330-5767%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-02T08%3A10%3A08Z&sr=b&sp=r&sig=46UiiK0a6dbMvdxrPxdu73XrbHoS1bhJDBFRkRQEmjo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fe [...]

2022-05-02 08:17 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4487768e5032a04670907fe1ee6dcfcdcebf5dc0/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 85 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ad7e0b47-1fd4-4df3-8756-bee8b2ee154b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-02 08:17 UTC, opbld33 commented
Docs Build status updates of commit _[4487768](https://github.com/MicrosoftDocs/msteams-docs/commits/4487768e5032a04670907fe1ee6dcfcdcebf5dc0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling - Shortcut.lnk](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling%20-%20Shortcut.lnk) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/card-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/card-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 4.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%204.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%204.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 5.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%205.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%205.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 7.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%207.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%207.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 8.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%208.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%208.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_1.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_1.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_2.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_2.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_3.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_3.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/share-to-teams/auth-preview-updated.JPG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/share-to-teams/auth-preview-updated.JPG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/share-to-teams/auth-preview-updated.jpg?branch=pr-en-us-5767) |
[msteams-platform/assets/images/share-to-teams/install-preview-updated-new.JPG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/share-to-teams/install-preview-updated-new.JPG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/share-to-teams/install-preview-updated-new.jpg?branch=pr-en-us-5767) |
[msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/messaging-extensions/how-to/link-unfurling.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C2%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202205020816346795-5767%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-02T08%3A17%3A16Z&sr=b&sp=r&sig=jYGnnJyB5s%2BmoZfILQo5yye%2B46GgKthjjp7MesTKyHQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a39 [...]

2022-05-02 12:21 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f087d4e4e08dd069a15aa29d934e04819119647a/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 81 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2858451f-e05d-4ad7-96cd-927fc71c0063) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-linkunfurling.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/f087d4e4e08dd069a15aa29d934e04819119647a/msteams-platform%2Fsbs-botbuilder-linkunfurling.yml) | 80 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f8ca5030-6e7d-404f-9d3c-64e6207c84c3) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-02 12:21 UTC, opbld32 commented
Docs Build status updates of commit _[f087d4e](https://github.com/MicrosoftDocs/msteams-docs/commits/f087d4e4e08dd069a15aa29d934e04819119647a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling - Shortcut.lnk](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling%20-%20Shortcut.lnk) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/url-preview.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/auth-preview-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/card-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/card-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/card-preview.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/feature-mobile-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/install-preview-updated-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 4.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%204.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%204.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 5.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%205.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%205.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 7.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%207.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%207.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 8.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%208.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%208.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_1.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_1.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_2.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_2.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_3.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_3.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/share-to-teams/auth-preview-updated.JPG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/share-to-teams/auth-preview-updated.JPG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/share-to-teams/auth-preview-updated.jpg?branch=pr-en-us-5767) |
[msteams-platform/assets/images/share-to-teams/install-preview-updated-new.JPG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/share-to-teams/install-preview-updated-new.JPG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/share-to-teams/install-preview-updated-new.jpg?branch=pr-en-us-5767) |
[msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/messaging-extensions/how-to/link-unfurling.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/sbs-botbuilder-linkunfurling.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/sbs-botbuilder-linkunfurling.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-botbuilder-linkunfurling?branch=pr-en-us-5767) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C2%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202205021220584504-5767%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-02T12%3A21%3A45Z&sr=b&sp=r&sig=hDKsF4FhcM52XhebnP8EBI%2BOWo%2FD9bcrd4zba8r9S0Q%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links writ [...]

2022-05-02 12:27 UTC, opbld31 commented
Docs Build status updates of commit _[2886fc0](https://github.com/MicrosoftDocs/msteams-docs/commits/2886fc0dfe8a155b69c2f0072c313ed6ad6be19d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling - Shortcut.lnk](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling%20-%20Shortcut.lnk) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/url-preview.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/auth-preview-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/card-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/card-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/card-preview.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/feature-mobile-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/install-preview-updated-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 4.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%204.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%204.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 5.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%205.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%205.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 7.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%207.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%207.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 8.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%208.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%208.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_1.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_1.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_2.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_2.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_3.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_3.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/share-to-teams/auth-preview-updated.JPG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/share-to-teams/auth-preview-updated.JPG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/share-to-teams/auth-preview-updated.jpg?branch=pr-en-us-5767) |
[msteams-platform/assets/images/share-to-teams/install-preview-updated-new.JPG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/share-to-teams/install-preview-updated-new.JPG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/share-to-teams/install-preview-updated-new.jpg?branch=pr-en-us-5767) |
[msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/messaging-extensions/how-to/link-unfurling.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/sbs-botbuilder-linkunfurling.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/sbs-botbuilder-linkunfurling.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-botbuilder-linkunfurling?branch=pr-en-us-5767) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C2%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202205021226246297-5767%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-02T12%3A27%3A08Z&sr=b&sp=r&sig=bizOmkfm91hbLfq1lEANYunUwlYREjkHXxPi5ms9OOY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written  [...]

2022-05-02 12:27 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2886fc0dfe8a155b69c2f0072c313ed6ad6be19d/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 81 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8a02c202-d41a-47a1-a23d-3575191bdc14) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-linkunfurling.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/2886fc0dfe8a155b69c2f0072c313ed6ad6be19d/msteams-platform%2Fsbs-botbuilder-linkunfurling.yml) | 80 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/87d737d7-8f9d-4cf3-8a62-2e6ab3927f79) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-05 06:15 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c59df9f74771d8dfdab757b9108fa963fead7ee3/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 81 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/eec231a9-4489-4fd3-9312-108c7c4a1dbf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-linkunfurling.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c59df9f74771d8dfdab757b9108fa963fead7ee3/msteams-platform%2Fsbs-botbuilder-linkunfurling.yml) | 80 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b7311b6e-abd6-4a55-bb21-29140912297e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-05 06:15 UTC, opbld30 commented
Docs Build status updates of commit _[c59df9f](https://github.com/MicrosoftDocs/msteams-docs/commits/c59df9f74771d8dfdab757b9108fa963fead7ee3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling - Shortcut.lnk](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling%20-%20Shortcut.lnk) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/url-preview.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/auth-preview-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/card-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/card-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/card-preview.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/feature-mobile-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/install-preview-updated-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 4.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%204.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%204.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 5.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%205.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%205.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 7.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%207.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%207.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 8.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%208.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%208.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_1.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_1.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_2.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_2.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_3.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_3.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/share-to-teams/auth-preview-updated.JPG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/share-to-teams/auth-preview-updated.JPG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/share-to-teams/auth-preview-updated.jpg?branch=pr-en-us-5767) |
[msteams-platform/assets/images/share-to-teams/install-preview-updated-new.JPG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/share-to-teams/install-preview-updated-new.JPG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/share-to-teams/install-preview-updated-new.jpg?branch=pr-en-us-5767) |
[msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/messaging-extensions/how-to/link-unfurling.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/sbs-botbuilder-linkunfurling.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/sbs-botbuilder-linkunfurling.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-botbuilder-linkunfurling?branch=pr-en-us-5767) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C5%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202205050614464901-5767%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-05T06%3A15%3A30Z&sr=b&sp=r&sig=esKwLzRuxOhrMmt0kC4pHa77tyGGrhmu3BXKjpSoBa8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written  [...]

2022-05-05 06:45 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a6bac44642e980751b643ed1d45b99c51b875e3d/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 82 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8824a827-3186-439d-9262-0eb96115b18b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-linkunfurling.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a6bac44642e980751b643ed1d45b99c51b875e3d/msteams-platform%2Fsbs-botbuilder-linkunfurling.yml) | 80 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/27f7c835-887f-4bdd-b6b0-d173f57bb234) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-05 06:46 UTC, opbld30 commented
Docs Build status updates of commit _[a6bac44](https://github.com/MicrosoftDocs/msteams-docs/commits/a6bac44642e980751b643ed1d45b99c51b875e3d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/messaging-extensions/how-to/link-unfurling.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) | [Details](#user-content-5d6d73cdb6df317e67b4e47d8fcb779e-d015901e)
[msteams-platform/assets/images/Teams-link-unfurling/Output-desktop-new.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Output-desktop-new.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/Output-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Output-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling - Shortcut.lnk](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling%20-%20Shortcut.lnk) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/url-preview.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/auth-preview-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/card-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/card-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/card-preview.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/feature-mobile-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/install-preview-updated-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 4.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%204.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%204.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 5.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%205.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%205.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 7.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%207.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%207.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 8.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%208.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%208.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_1.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_1.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_2.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_2.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_3.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_3.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/share-to-teams/auth-preview-updated.JPG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/share-to-teams/auth-preview-updated.JPG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/share-to-teams/auth-preview-updated.jpg?branch=pr-en-us-5767) |
[msteams-platform/assets/images/share-to-teams/install-preview-updated-new.JPG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/share-to-teams/install-preview-updated-new.JPG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/s [...]

2022-05-05 06:48 UTC, opbld31 commented
Docs Build status updates of commit _[fcd6462](https://github.com/MicrosoftDocs/msteams-docs/commits/fcd646297e7cc4193c3b2946d744cd88b42c3825)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/messaging-extensions/how-to/link-unfurling.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) | [Details](#user-content-5d6d73cdb6df317e67b4e47d8fcb779e-582e7337)
[msteams-platform/assets/images/Teams-link-unfurling/Output-desktop-new.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Output-desktop-new.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/Output-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Output-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling - Shortcut.lnk](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling%20-%20Shortcut.lnk) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/url-preview.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/auth-preview-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/card-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/card-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/card-preview.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/feature-mobile-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/install-preview-updated-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 4.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%204.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%204.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 5.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%205.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%205.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 7.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%207.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%207.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 8.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%208.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%208.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_1.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_1.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_2.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_2.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_3.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_3.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/share-to-teams/auth-preview-updated.JPG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/share-to-teams/auth-preview-updated.JPG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/share-to-teams/auth-preview-updated.jpg?branch=pr-en-us-5767) |
[msteams-platform/assets/images/share-to-teams/install-preview-updated-new.JPG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/share-to-teams/install-preview-updated-new.JPG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/s [...]

2022-05-05 06:48 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fcd646297e7cc4193c3b2946d744cd88b42c3825/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 82 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9c66388d-f6a0-4e3b-aa1a-1f3601db3920) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-linkunfurling.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/fcd646297e7cc4193c3b2946d744cd88b42c3825/msteams-platform%2Fsbs-botbuilder-linkunfurling.yml) | 80 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b48eb931-4d1a-43b9-9741-04ba6eca018b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-05 07:01 UTC, opbld32 commented
Docs Build status updates of commit _[13ed18f](https://github.com/MicrosoftDocs/msteams-docs/commits/13ed18f1dec8459f4a88b40e38bd924328cecbcb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/Teams-link-unfurling/Output-desktop-new.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Output-desktop-new.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/Output-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Output-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling - Shortcut.lnk](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling%20-%20Shortcut.lnk) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/url-preview.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/auth-preview-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/card-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/card-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/card-preview.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/feature-mobile-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/install-preview-updated-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 4.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%204.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%204.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 5.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%205.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%205.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 7.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%207.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%207.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 8.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%208.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%208.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_1.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_1.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_2.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_2.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_3.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_3.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/share-to-teams/auth-preview-updated.JPG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/share-to-teams/auth-preview-updated.JPG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/share-to-teams/auth-preview-updated.jpg?branch=pr-en-us-5767) |
[msteams-platform/assets/images/share-to-teams/install-preview-updated-new.JPG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/share-to-teams/install-preview-updated-new.JPG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/share-to-teams/install-preview-updated-new.jpg?branch=pr-en-us-5767) |
[msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/messaging-extensions/how-to/link-unfurling.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?bra [...]

2022-05-05 07:02 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/13ed18f1dec8459f4a88b40e38bd924328cecbcb/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 83 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/127dc56d-8237-4f7f-beef-98d50ddd1342) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-linkunfurling.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/13ed18f1dec8459f4a88b40e38bd924328cecbcb/msteams-platform%2Fsbs-botbuilder-linkunfurling.yml) | 80 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/031bb3b2-6cfb-4572-84ea-9efc92deb012) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-05 07:07 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/10b57a122368cba67beea76582adf9b197b78948/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 83 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cde974d4-f250-45c0-b42e-8ecc32fffb69) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-linkunfurling.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/10b57a122368cba67beea76582adf9b197b78948/msteams-platform%2Fsbs-botbuilder-linkunfurling.yml) | 80 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e388acc0-604a-40fc-9cf5-ca171e2043b1) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-05 07:07 UTC, opbld33 commented
Docs Build status updates of commit _[10b57a1](https://github.com/MicrosoftDocs/msteams-docs/commits/10b57a122368cba67beea76582adf9b197b78948)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/Teams-link-unfurling/Output-desktop-new.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Output-desktop-new.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/Output-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Output-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling - Shortcut.lnk](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling%20-%20Shortcut.lnk) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/url-preview.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/auth-preview-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/card-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/card-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/card-preview.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/feature-mobile-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/install-preview-updated-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/unfurl-desktop.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/unfurl-desktop.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/unfurl-desktop.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 4.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%204.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%204.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 5.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%205.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%205.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 7.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%207.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%207.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 8.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%208.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%208.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_1.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_1.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_2.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_2.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_3.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_3.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/share-to-teams/auth-preview-updated.JPG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/share-to-teams/auth-preview-updated.JPG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/share-to-teams/auth-preview-updated.jpg?branch=pr-en-us-5767) |
[msteams-platform/assets/images/share-to-teams/install-preview-updated-new.JPG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/share-to-teams/install-preview-updated-new.JPG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platfor [...]

2022-05-05 07:11 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/57f80ac429ea4399ee77e6b088891a1b9fdd6c49/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 83 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4974f15d-734b-4ff5-b4a8-086898f494aa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-linkunfurling.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/57f80ac429ea4399ee77e6b088891a1b9fdd6c49/msteams-platform%2Fsbs-botbuilder-linkunfurling.yml) | 80 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/46b93781-c4b2-41a6-b82c-9ed5c30c252e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-05 07:11 UTC, opbld31 commented
Docs Build status updates of commit _[57f80ac](https://github.com/MicrosoftDocs/msteams-docs/commits/57f80ac429ea4399ee77e6b088891a1b9fdd6c49)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/Teams-link-unfurling/Output-desktop-new.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Output-desktop-new.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/output-desktop-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/Output-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Output-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling - Shortcut.lnk](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling%20-%20Shortcut.lnk) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/url-preview.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/auth-preview-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/card-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/card-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/card-preview.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/feature-mobile-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/install-preview-updated-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/unfurl-desktop.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/unfurl-desktop.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 4.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%204.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%204.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 5.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%205.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%205.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 7.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%207.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%207.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 8.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%208.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%208.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_1.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_1.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_2.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_2.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_3.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_3.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/share-to-teams/auth-preview-updated.JPG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/share-to-teams/auth-preview-updated.JPG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/share-to-teams/auth-preview-updated.jpg?branch=pr-en-us-5767) |
[msteams-platform/assets/images/share-to-teams/install-preview-updated-new.JPG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/share-to-teams/install-preview-updated-new.JPG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/pla [...]

2022-05-05 07:25 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/83c2332e1428ffccd3a7728071cf07d5f44d43e2/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 83 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/64fa6a04-fc84-448b-8074-a918da11b4ff) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-linkunfurling.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/83c2332e1428ffccd3a7728071cf07d5f44d43e2/msteams-platform%2Fsbs-botbuilder-linkunfurling.yml) | 80 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c4205bdf-8fbb-4839-9b1f-c48f6ff07b85) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-05 07:25 UTC, opbld31 commented
Docs Build status updates of commit _[83c2332](https://github.com/MicrosoftDocs/msteams-docs/commits/83c2332e1428ffccd3a7728071cf07d5f44d43e2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/Teams-link-unfurling/Output-desktop-new.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Output-desktop-new.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/output-desktop-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/Output-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Output-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling - Shortcut.lnk](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling%20-%20Shortcut.lnk) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/url-preview.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/auth-preview-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/card-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/card-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/card-preview.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/feature-mobile-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/install-preview-updated-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/unfurl-desktop12.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/unfurl-desktop12.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 4.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%204.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%204.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 5.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%205.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%205.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 7.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%207.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%207.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 8.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%208.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%208.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_1.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_1.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_2.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_2.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_3.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_3.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/share-to-teams/auth-preview-updated.JPG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/share-to-teams/auth-preview-updated.JPG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/share-to-teams/auth-preview-updated.jpg?branch=pr-en-us-5767) |
[msteams-platform/assets/images/share-to-teams/install-preview-updated-new.JPG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/share-to-teams/install-preview-updated-new.JPG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams [...]

2022-05-05 07:30 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/715e66235185678a986eef92a2529108d5e4ee54/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 83 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5ab61f16-cd38-4050-990a-8e9c636f014c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-linkunfurling.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/715e66235185678a986eef92a2529108d5e4ee54/msteams-platform%2Fsbs-botbuilder-linkunfurling.yml) | 80 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/92f24749-0b07-40d4-bc28-54ed2968011c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-05 07:31 UTC, opbld31 commented
Docs Build status updates of commit _[715e662](https://github.com/MicrosoftDocs/msteams-docs/commits/715e66235185678a986eef92a2529108d5e4ee54)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/messaging-extensions/how-to/link-unfurling.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) | [Details](#user-content-5d6d73cdb6df317e67b4e47d8fcb779e-81f01b55)
[msteams-platform/assets/images/Teams-link-unfurling/Output-desktop-new.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Output-desktop-new.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/output-desktop-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/Output-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Output-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling - Shortcut.lnk](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling%20-%20Shortcut.lnk) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/url-preview.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/auth-preview-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/card-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/card-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/card-preview.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/feature-mobile-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/install-preview-updated-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/unfurl-desktop-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/unfurl-desktop-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/unfurl-desktop-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 4.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%204.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%204.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 5.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%205.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%205.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 7.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%207.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%207.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 8.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%208.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%208.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_1.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_1.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_2.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_2.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_3.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_3.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/share-to-teams/auth-preview-updated.JPG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/share-to-teams/auth-preview-updated.JPG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams [...]

2022-05-05 07:33 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/443a3c668ded508372a0db087c027e6c426a30e2/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 82 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f20fe433-2c0b-45e5-99b3-b2e1e4273417) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-linkunfurling.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/443a3c668ded508372a0db087c027e6c426a30e2/msteams-platform%2Fsbs-botbuilder-linkunfurling.yml) | 80 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1155e06b-8cad-4da8-9c15-32a47f1a688f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-05 07:33 UTC, opbld30 commented
Docs Build status updates of commit _[443a3c6](https://github.com/MicrosoftDocs/msteams-docs/commits/443a3c668ded508372a0db087c027e6c426a30e2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/messaging-extensions/how-to/link-unfurling.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) | [Details](#user-content-5d6d73cdb6df317e67b4e47d8fcb779e-2c5a5ce9)
[msteams-platform/assets/images/Teams-link-unfurling/Output-desktop-new.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Output-desktop-new.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/output-desktop-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/Output-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Output-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling - Shortcut.lnk](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling%20-%20Shortcut.lnk) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/url-preview.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/auth-preview-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/card-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/card-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/card-preview.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/feature-mobile-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/install-preview-updated-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/unfurl-desktop-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/unfurl-desktop-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 4.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%204.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%204.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 5.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%205.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%205.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 7.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%207.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%207.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 8.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%208.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%208.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_1.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_1.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_2.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_2.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_3.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_3.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/share-to-teams/auth-preview-updated.JPG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/share-to-teams/auth-preview-updated.JPG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/im [...]

2022-05-05 07:36 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e677fcb13f43e9ba71e9bf569a1510df208c99e0/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 83 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/257fa444-7b71-42cf-b770-1efb4f0a2188) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-linkunfurling.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e677fcb13f43e9ba71e9bf569a1510df208c99e0/msteams-platform%2Fsbs-botbuilder-linkunfurling.yml) | 80 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e1c298d0-bab4-4079-aec8-3973a5096c12) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-05 07:37 UTC, opbld30 commented
Docs Build status updates of commit _[e677fcb](https://github.com/MicrosoftDocs/msteams-docs/commits/e677fcb13f43e9ba71e9bf569a1510df208c99e0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/Teams-link-unfurling/Output-desktop-new.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Output-desktop-new.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/output-desktop-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/Output-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Output-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling - Shortcut.lnk](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling%20-%20Shortcut.lnk) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/url-preview.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/auth-preview-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/card-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/card-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/card-preview.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/feature-mobile-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/install-preview-updated-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/unfurl-desktop-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/unfurl-desktop-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 4.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%204.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%204.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 5.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%205.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%205.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 7.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%207.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%207.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 8.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%208.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%208.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_1.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_1.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_2.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_2.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_3.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_3.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/share-to-teams/auth-preview-updated.JPG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/share-to-teams/auth-preview-updated.JPG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/share-to-teams/auth-preview-updated.jpg?branch=pr-en-us-5767) |
[msteams-platform/assets/images/share-to-teams/install-preview-updated-new.JPG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/share-to-teams/install-preview-updated-new.JPG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/mi [...]

2022-05-05 07:55 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/36d41674ed21d5046630a2258b3c95a5e6d62fca/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 85 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ca2c8e1b-cc84-4523-9fb2-89b67b03441a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-linkunfurling.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/36d41674ed21d5046630a2258b3c95a5e6d62fca/msteams-platform%2Fsbs-botbuilder-linkunfurling.yml) | 80 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/26de8770-2346-42ab-8733-3eaaffc630db) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-05 07:55 UTC, opbld30 commented
Docs Build status updates of commit _[36d4167](https://github.com/MicrosoftDocs/msteams-docs/commits/36d41674ed21d5046630a2258b3c95a5e6d62fca)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/Teams-link-unfurling/Output-desktop-new.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Output-desktop-new.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/output-desktop-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/Output-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Output-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling - Shortcut.lnk](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling%20-%20Shortcut.lnk) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/url-preview.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/auth-preview-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/card-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/card-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/card-preview.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/feature-mobile-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/install-preview-updated-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/unfurl-desktop-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/unfurl-desktop-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 4.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%204.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%204.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 5.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%205.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%205.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 7.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%207.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%207.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 8.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%208.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%208.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_1.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_1.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_2.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_2.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_3.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_3.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/share-to-teams/auth-preview-updated.JPG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/share-to-teams/auth-preview-updated.JPG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/share-to-teams/auth-preview-updated.jpg?branch=pr-en-us-5767) |
[msteams-platform/assets/images/share-to-teams/install-preview-updated-new.JPG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/share-to-teams/install-preview-updated-new.JPG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/mi [...]

2022-05-05 07:58 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8faf67462af3ddb9d9ec5d320b90d8d8b308b392/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 85 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/999ae466-8be3-4ce7-b446-426f677d2eab) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-linkunfurling.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/8faf67462af3ddb9d9ec5d320b90d8d8b308b392/msteams-platform%2Fsbs-botbuilder-linkunfurling.yml) | 80 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/30c73fa4-4286-4dde-b344-59878e99bbe1) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-05 07:59 UTC, opbld30 commented
Docs Build status updates of commit _[8faf674](https://github.com/MicrosoftDocs/msteams-docs/commits/8faf67462af3ddb9d9ec5d320b90d8d8b308b392)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/Teams-link-unfurling/Output-desktop-new.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Output-desktop-new.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/output-desktop-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/Output-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Output-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling - Shortcut.lnk](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling%20-%20Shortcut.lnk) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/url-preview.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/auth-preview-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/card-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/card-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/card-preview.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/feature-mobile-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/install-preview-updated-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/unfurl-desktop-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/unfurl-desktop-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 4.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%204.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%204.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 5.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%205.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%205.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 7.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%207.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%207.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 8.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%208.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%208.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_1.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_1.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_2.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_2.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_3.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_3.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/share-to-teams/auth-preview-updated.JPG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/share-to-teams/auth-preview-updated.JPG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/share-to-teams/auth-preview-updated.jpg?branch=pr-en-us-5767) |
[msteams-platform/assets/images/share-to-teams/install-preview-updated-new.JPG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/share-to-teams/install-preview-updated-new.JPG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/mi [...]

2022-05-05 08:47 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2fec88165ac22636c83690f7d02e18f3efd97972/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 86 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f54e8829-65c7-4e46-ada3-2d4b377fb858) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-linkunfurling.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/2fec88165ac22636c83690f7d02e18f3efd97972/msteams-platform%2Fsbs-botbuilder-linkunfurling.yml) | 80 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/74a8d926-3469-416d-a522-5e61404b45e2) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-05 08:47 UTC, opbld33 commented
Docs Build status updates of commit _[2fec881](https://github.com/MicrosoftDocs/msteams-docs/commits/2fec88165ac22636c83690f7d02e18f3efd97972)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/messaging-extensions/how-to/link-unfurling.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) | [Details](#user-content-5d6d73cdb6df317e67b4e47d8fcb779e-41a1250e)
[msteams-platform/assets/images/Teams-link-unfurling/Output-desktop-new.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Output-desktop-new.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/output-desktop-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/Output-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Output-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling - Shortcut.lnk](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling%20-%20Shortcut.lnk) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/url-preview.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/auth-preview-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/card-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/card-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/card-preview.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/feature-mobile-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/install-preview-updated-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/result-output-new1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/result-output-new1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/result-output-new1.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/unfurl-desktop-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/unfurl-desktop-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 4.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%204.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%204.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 5.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%205.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%205.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 7.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%207.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%207.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 8.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%208.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%208.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_1.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_1.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_2.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_2.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_3.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams [...]

2022-05-05 08:58 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b7cbee8cb0bd5e6b701bb9a04a64bd0ae1de275a/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 84 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0ea41e78-eed4-4e92-ab04-a3d2c3afc573) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-linkunfurling.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/b7cbee8cb0bd5e6b701bb9a04a64bd0ae1de275a/msteams-platform%2Fsbs-botbuilder-linkunfurling.yml) | 80 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/65839d1b-e170-43c6-82ce-576023c3cc2a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-05 08:58 UTC, opbld32 commented
Docs Build status updates of commit _[b7cbee8](https://github.com/MicrosoftDocs/msteams-docs/commits/b7cbee8cb0bd5e6b701bb9a04a64bd0ae1de275a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/messaging-extensions/how-to/link-unfurling.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) | [Details](#user-content-5d6d73cdb6df317e67b4e47d8fcb779e-3a2210b8)
[msteams-platform/assets/images/Teams-link-unfurling/Output-desktop-new.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Output-desktop-new.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/output-desktop-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/Output-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Output-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling - Shortcut.lnk](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling%20-%20Shortcut.lnk) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/url-preview.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/auth-preview-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/card-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/card-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/card-preview.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/feature-mobile-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/install-preview-updated-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/result-output-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/result-output-new1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/result-output-new1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/result-output-new1.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/unfurl-desktop-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/unfurl-desktop-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/unfurl-desktop-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 4.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%204.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%204.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 5.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%205.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%205.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 7.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%207.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%207.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 8.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%208.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%208.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_1.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_1.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_2.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_2.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_3.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.m [...]

2022-05-05 09:23 UTC, opbld32 commented
Docs Build status updates of commit _[b23af52](https://github.com/MicrosoftDocs/msteams-docs/commits/b23af524b9e1c20d6dcde527ba869eb346b71788)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/Teams-link-unfurling/Output-desktop-new.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Output-desktop-new.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/output-desktop-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/Output-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Output-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling - Shortcut.lnk](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling%20-%20Shortcut.lnk) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/url-preview.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/auth-preview-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/card-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/card-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/card-preview.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/feature-mobile-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/install-preview-updated-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/result-output-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/result-output-new1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/result-output-new1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/result-output-new1.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/unfurl-desktop-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/unfurl-desktop-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/unfurl-desktop-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 4.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%204.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%204.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 5.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%205.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%205.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 7.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%207.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%207.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 8.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%208.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%208.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_1.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_1.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_2.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_2.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_3.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_3.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/share-to-teams/auth-preview-updated.JPG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/share-to-teams/auth-preview-updated.JPG) | :white_check_mark:Succeeded | [View](https://rev [...]

2022-05-05 09:42 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ad8a27f03021b8a8fcf83ada318001434471b144/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 84 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9e0e9be2-81cd-4b08-902e-d0e520120d38) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-linkunfurling.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ad8a27f03021b8a8fcf83ada318001434471b144/msteams-platform%2Fsbs-botbuilder-linkunfurling.yml) | 80 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/617629d7-9501-4f2a-8c2a-3f45acf51686) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-05 09:43 UTC, opbld33 commented
Docs Build status updates of commit _[ad8a27f](https://github.com/MicrosoftDocs/msteams-docs/commits/ad8a27f03021b8a8fcf83ada318001434471b144)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/Teams-link-unfurling/Output-desktop-new.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Output-desktop-new.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/output-desktop-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/Output-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Output-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling - Shortcut.lnk](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling%20-%20Shortcut.lnk) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/url-preview.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/auth-preview-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/card-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/card-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/card-preview.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/feature-mobile-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/install-preview-updated-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/result-output-new1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/result-output-new1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/result-output-new1.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/unfurl-desktop-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/unfurl-desktop-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/unfurl-desktop-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 4.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%204.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%204.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 5.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%205.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%205.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 7.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%207.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%207.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 8.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%208.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%208.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_1.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_1.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_2.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_2.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_3.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_3.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/share-to-teams/auth-preview-updated.JPG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/share-to-teams/auth-preview-updated.JPG) | :white_check_mark:Succeeded | [View](https://review.docs.micro [...]

2022-05-05 09:46 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/568a3ca67e49af12eec5c2060c97fbabb94a0c2c/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 84 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/20f911c9-513e-4463-b4fe-3bcc6a2e3845) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-linkunfurling.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/568a3ca67e49af12eec5c2060c97fbabb94a0c2c/msteams-platform%2Fsbs-botbuilder-linkunfurling.yml) | 80 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f514fa6e-1650-4cd2-a432-1a0f088cc4bd) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-05 09:46 UTC, opbld32 commented
Docs Build status updates of commit _[568a3ca](https://github.com/MicrosoftDocs/msteams-docs/commits/568a3ca67e49af12eec5c2060c97fbabb94a0c2c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/Teams-link-unfurling/Output-desktop-new.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Output-desktop-new.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/output-desktop-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/Output-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Output-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling - Shortcut.lnk](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling%20-%20Shortcut.lnk) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/url-preview.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/auth-preview-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/card-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/card-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/card-preview.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/feature-mobile-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/install-preview-updated-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/result-output-new1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/result-output-new1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/result-output-new1.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/unfurl-desktop-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/unfurl-desktop-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/unfurl-desktop-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 4.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%204.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%204.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 5.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%205.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%205.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 7.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%207.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%207.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 8.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%208.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%208.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_1.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_1.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_2.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_2.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_3.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_3.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/share-to-teams/auth-preview-updated.JPG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/share-to-teams/auth-preview-updated.JPG) | :white_check_mark:Succeeded | [View](https://review.docs.micro [...]

2022-05-05 11:26 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d7a01aadf127bd77a4f232278121c3904ed2377b/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 84 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/30c26a13-4ec9-4e93-aad4-ddce486cc3c5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-linkunfurling.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/d7a01aadf127bd77a4f232278121c3904ed2377b/msteams-platform%2Fsbs-botbuilder-linkunfurling.yml) | 80 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d0ea15de-dfc8-48d6-97d3-200e2bdb4df8) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-05 11:26 UTC, opbld30 commented
Docs Build status updates of commit _[d7a01aa](https://github.com/MicrosoftDocs/msteams-docs/commits/d7a01aadf127bd77a4f232278121c3904ed2377b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/Teams-link-unfurling/Output-desktop-new.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Output-desktop-new.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/output-desktop-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/Output-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Output-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling - Shortcut.lnk](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling%20-%20Shortcut.lnk) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/url-preview.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/auth-preview-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/card-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/card-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/card-preview.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/feature-mobile-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/install-preview-updated-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/result-output-new1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/result-output-new1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/result-output-new1.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/search-new-desktop-updated.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/search-new-desktop-updated.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/search-new-desktop-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/search-new-desktop.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/search-new-desktop.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/search-new-desktop.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/unfurl-desktop-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/unfurl-desktop-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/unfurl-desktop-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 4.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%204.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%204.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 5.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%205.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%205.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 7.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%207.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%207.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 8.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%208.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%208.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_1.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_1.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_2.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/cap [...]

2022-05-05 11:29 UTC, opbld32 commented
Docs Build status updates of commit _[e0da4f4](https://github.com/MicrosoftDocs/msteams-docs/commits/e0da4f4884b572f13d07f5facb16dda9d58e6745)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/Teams-link-unfurling/Output-desktop-new.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Output-desktop-new.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/output-desktop-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/Output-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Output-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling - Shortcut.lnk](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling%20-%20Shortcut.lnk) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/url-preview.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/auth-preview-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/card-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/card-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/card-preview.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/feature-mobile-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/install-preview-updated-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/result-output-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/result-output-new1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/result-output-new1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/result-output-new1.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/search-new-desktop-updated.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/search-new-desktop-updated.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/unfurl-desktop-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/unfurl-desktop-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/unfurl-desktop-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 4.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%204.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%204.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 5.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%205.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%205.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 7.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%207.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%207.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 8.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%208.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%208.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_1.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_1.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_2.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture_2.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_3.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/capture_3.PNG) | :white_check_mark:Succeeded  [...]

2022-05-05 11:30 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e0da4f4884b572f13d07f5facb16dda9d58e6745/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 84 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8cd06370-f8b0-492d-a1d7-54abb4025b3d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-linkunfurling.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e0da4f4884b572f13d07f5facb16dda9d58e6745/msteams-platform%2Fsbs-botbuilder-linkunfurling.yml) | 80 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/94846060-85b4-4f7b-a15c-2b4edf129f32) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-05 12:05 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bd002aae628aa1e69aecad4d62e800659420d87b/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 86 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/514ace3b-9536-4eee-9b06-f3766f122460) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-linkunfurling.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/bd002aae628aa1e69aecad4d62e800659420d87b/msteams-platform%2Fsbs-botbuilder-linkunfurling.yml) | 80 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6fe583dd-99b0-4037-8c3f-afe72d5502ef) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-05 12:05 UTC, opbld33 commented
Docs Build status updates of commit _[bd002aa](https://github.com/MicrosoftDocs/msteams-docs/commits/bd002aae628aa1e69aecad4d62e800659420d87b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/messaging-extensions/how-to/link-unfurling.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) | [Details](#user-content-5d6d73cdb6df317e67b4e47d8fcb779e-e7777cd6)
[msteams-platform/assets/images/Teams-link-unfurling/Output-desktop-new.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Output-desktop-new.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/output-desktop-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/Output-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Output-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling - Shortcut.lnk](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling%20-%20Shortcut.lnk) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/url-preview.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/auth-preview-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/card-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/card-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/card-preview.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/desktop-link.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/desktop-link.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/desktop-link.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/feature-mobile-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/install-preview-updated-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/mobile-link.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/mobile-link.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/mobile-link.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/result-output-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/result-output-new1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/result-output-new1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/result-output-new1.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/search-new-desktop-updated.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/search-new-desktop-updated.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/unfurl-desktop-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/unfurl-desktop-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/unfurl-desktop-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 4.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%204.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%204.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 5.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%205.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%205.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 7.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%207.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%207.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 8.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%208.PNG) | [...]

2022-05-05 12:49 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3fdde29a5a30f4a48e521587f3f516d13d21f8e6/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 85 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e0a93b28-1ad8-4f20-a782-9b0e6ba5a6cc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-linkunfurling.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/3fdde29a5a30f4a48e521587f3f516d13d21f8e6/msteams-platform%2Fsbs-botbuilder-linkunfurling.yml) | 80 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b8bb2670-d7e8-4749-b4b9-e9403a0bbb74) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-05 12:49 UTC, opbld33 commented
Docs Build status updates of commit _[3fdde29](https://github.com/MicrosoftDocs/msteams-docs/commits/3fdde29a5a30f4a48e521587f3f516d13d21f8e6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/messaging-extensions/how-to/link-unfurling.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) | [Details](#user-content-5d6d73cdb6df317e67b4e47d8fcb779e-4b0bbce7)
[msteams-platform/assets/images/Teams-link-unfurling/Output-desktop-new.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Output-desktop-new.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/output-desktop-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/Output-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Output-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/output-mobile.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling - Shortcut.lnk](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling%20-%20Shortcut.lnk) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/url-preview.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/auth-preview-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/card-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/card-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/card-preview.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/desktop-link.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/desktop-link.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/feature-mobile-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/install-preview-updated-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/mobile-link.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/mobile-link.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/result-output-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/result-output-new1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/result-output-new1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/result-output-new1.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/search-new-desktop-updated.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/search-new-desktop-updated.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/search-new-desktop-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/unfurl-desktop-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/unfurl-desktop-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/unfurl-desktop-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 4.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%204.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%204.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 5.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%205.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%205.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 7.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%207.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%207.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 8.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Ca [...]

2022-05-05 13:01 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cd7309648176473b18a9b3efd3ba6b0e24bb1e95/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 85 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f4be5e71-5cf9-48b4-98b8-a7e8e2f41df9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-linkunfurling.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/cd7309648176473b18a9b3efd3ba6b0e24bb1e95/msteams-platform%2Fsbs-botbuilder-linkunfurling.yml) | 80 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/521986df-0c06-44c3-933a-c09abccba8a9) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-05 13:02 UTC, opbld32 commented
Docs Build status updates of commit _[cd73096](https://github.com/MicrosoftDocs/msteams-docs/commits/cd7309648176473b18a9b3efd3ba6b0e24bb1e95)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/messaging-extensions/how-to/link-unfurling.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) | [Details](#user-content-5d6d73cdb6df317e67b4e47d8fcb779e-ec86ec14)
[msteams-platform/assets/images/Teams-link-unfurling/Output-desktop-new.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Output-desktop-new.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/output-desktop-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/Output-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Output-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/output-mobile.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling - Shortcut.lnk](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling%20-%20Shortcut.lnk) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/url-preview.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/auth-preview-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/card-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/card-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/card-preview.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/desktop-link-unfurl.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/desktop-link-unfurl.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/feature-mobile-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/install-preview-updated-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/mobile-link-unfurl.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/mobile-link-unfurl.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/result-output-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/result-output-new1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/result-output-new1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/result-output-new1.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/search-new-desktop-updated.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/search-new-desktop-updated.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/search-new-desktop-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/unfurl-desktop-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/unfurl-desktop-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/unfurl-desktop-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 4.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%204.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%204.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 5.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%205.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%205.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 7.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%207.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%207.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 8.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/ [...]

2022-05-05 13:07 UTC, opbld32 commented
Docs Build status updates of commit _[e593b6b](https://github.com/MicrosoftDocs/msteams-docs/commits/e593b6bb09245d2ebe4f86fdd477bf88b689cfc9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/Teams-link-unfurling/Output-desktop-new.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Output-desktop-new.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/output-desktop-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/Output-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Output-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/output-mobile.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling - Shortcut.lnk](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling%20-%20Shortcut.lnk) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/url-preview.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/auth-preview-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/card-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/card-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/card-preview.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/desktop-link-unfurl.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/desktop-link-unfurl.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/feature-mobile-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/install-preview-updated-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/mobile-link-unfurl.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/mobile-link-unfurl.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/result-output-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/result-output-new1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/result-output-new1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/result-output-new1.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/search-new-desktop-updated.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/search-new-desktop-updated.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/search-new-desktop-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/unfurl-desktop-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/unfurl-desktop-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/unfurl-desktop-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 4.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%204.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%204.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 5.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%205.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%205.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 7.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%207.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%207.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 8.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%208.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%208.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/capture_1.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/ [...]

2022-05-05 13:24 UTC, opbld33 commented
Docs Build status updates of commit _[40716f6](https://github.com/MicrosoftDocs/msteams-docs/commits/40716f6cfc3208b4e3f3bcf8a1ef4bdff6b51511)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/Teams-link-unfurling/Output-desktop-new.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Output-desktop-new.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/output-desktop-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/Output-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Output-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/output-mobile.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling - Shortcut.lnk](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling%20-%20Shortcut.lnk) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/url-preview.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/auth-preview-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/card-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/card-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/card-preview.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/desktop-link-unfurl.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/desktop-link-unfurl.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/desktop-newūnfurl.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/desktop-new%C5%ABnfurl.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/desktop-new%C5%ABnfurl.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/desktop.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/desktop.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/desktop.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/feature-mobile-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/install-preview-updated-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/mobile-link-unfurl.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/mobile-link-unfurl.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/result-output-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/result-output-new1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/result-output-new1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/result-output-new1.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/search-new-desktop-updated.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/search-new-desktop-updated.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/search-new-desktop-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/unfurl-desktop-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/unfurl-desktop-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/unfurl-desktop-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 4.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%204.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%204.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 5.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%205.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%205.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 7.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on [...]

2022-05-05 13:25 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b7af1ed698d531be8ea91f9cd85a1bf810f72646/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 84 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e9b42ce8-1435-427e-9e22-82833a1bbaf6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-linkunfurling.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/b7af1ed698d531be8ea91f9cd85a1bf810f72646/msteams-platform%2Fsbs-botbuilder-linkunfurling.yml) | 80 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8e07ef88-6674-4575-b249-4dbce50ae865) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-05 13:26 UTC, opbld31 commented
Docs Build status updates of commit _[b7af1ed](https://github.com/MicrosoftDocs/msteams-docs/commits/b7af1ed698d531be8ea91f9cd85a1bf810f72646)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/Teams-link-unfurling/Output-desktop-new.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Output-desktop-new.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/output-desktop-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/Output-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Output-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/output-mobile.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling - Shortcut.lnk](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling%20-%20Shortcut.lnk) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/url-preview.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/auth-preview-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/card-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/card-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/card-preview.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/desktop-link-unfurl.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/desktop-link-unfurl.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/desktop-link-unfurl.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/desktop-newūnfurl.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/desktop-new%C5%ABnfurl.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/desktop.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/desktop.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/desktop.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/feature-mobile-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/install-preview-updated-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/mobile-link-unfurl.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/mobile-link-unfurl.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/result-output-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/result-output-new1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/result-output-new1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/result-output-new1.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/search-new-desktop-updated.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/search-new-desktop-updated.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/search-new-desktop-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/unfurl-desktop-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/unfurl-desktop-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/unfurl-desktop-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 4.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%204.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%204.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 5.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%205.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%205.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 7.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mo [...]

2022-05-05 13:28 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b7af1ed698d531be8ea91f9cd85a1bf810f72646/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 84 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/28cc526c-267e-4807-b5bb-91e83c6715b4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-linkunfurling.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/b7af1ed698d531be8ea91f9cd85a1bf810f72646/msteams-platform%2Fsbs-botbuilder-linkunfurling.yml) | 80 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3cfe91bb-c1bd-4292-8ee0-5046659514b3) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-05 13:31 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0a15b6a9c316492cdeca900593bd80a226cf7b2c/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 84 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fba1c5cb-8e84-4f9e-bb3f-52d9b476d12f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-linkunfurling.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/0a15b6a9c316492cdeca900593bd80a226cf7b2c/msteams-platform%2Fsbs-botbuilder-linkunfurling.yml) | 80 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e44c24e9-ab18-442b-8548-3aa5e17663d2) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-05 13:31 UTC, opbld30 commented
Docs Build status updates of commit _[0a15b6a](https://github.com/MicrosoftDocs/msteams-docs/commits/0a15b6a9c316492cdeca900593bd80a226cf7b2c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/Teams-link-unfurling/Output-desktop-new.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Output-desktop-new.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/output-desktop-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/Output-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Output-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/output-mobile.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling - Shortcut.lnk](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling%20-%20Shortcut.lnk) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/url-preview.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/auth-preview-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/card-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/card-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/card-preview.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/desktop-link-unfurl.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/desktop-link-unfurl.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/desktop-link-unfurl.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/desktop-newūnfurl.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/desktop-new%C5%ABnfurl.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/desktop.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/desktop.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/desktop.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/feature-mobile-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/install-preview-updated-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/mobile-link-unfurl.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/mobile-link-unfurl.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/result-output-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/result-output-new1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/result-output-new1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/result-output-new1.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/search-new-desktop-updated.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/search-new-desktop-updated.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/search-new-desktop-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/unfurl-desktop-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/unfurl-desktop-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/unfurl-desktop-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 4.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%204.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%204.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 5.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%205.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%205.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 7.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mo [...]

2022-05-06 05:26 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bba9c212e13241dda5389d3bfddfad2e79150859/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 85 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e8330f84-5641-47df-ac88-aa20c621425a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-linkunfurling.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/bba9c212e13241dda5389d3bfddfad2e79150859/msteams-platform%2Fsbs-botbuilder-linkunfurling.yml) | 80 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/12399b80-00ea-4c39-b41c-bf0300df32eb) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-06 05:26 UTC, opbld30 commented
Docs Build status updates of commit _[bba9c21](https://github.com/MicrosoftDocs/msteams-docs/commits/bba9c212e13241dda5389d3bfddfad2e79150859)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/Teams-link-unfurling/Output-desktop-new.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Output-desktop-new.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/output-desktop-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/Output-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Output-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/output-mobile.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling - Shortcut.lnk](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling%20-%20Shortcut.lnk) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/url-preview.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/auth-preview-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/card-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/card-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/card-preview.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/desktop-link-unfurl.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/desktop-link-unfurl.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/desktop-link-unfurl.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/desktop-newūnfurl.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/desktop-new%C5%ABnfurl.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/desktop-new%C5%ABnfurl.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/desktop.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/desktop.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/desktop.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/feature-mobile-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/install-preview-updated-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/mobile-link-unfurl.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/mobile-link-unfurl.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/result-output-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/result-output-new1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/result-output-new1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/result-output-new1.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/search-new-desktop-updated.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/search-new-desktop-updated.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/search-new-desktop-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/unfurl-desktop-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/unfurl-desktop-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/unfurl-desktop-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 4.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%204.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%204.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 5.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%205.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%205.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 7.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-l [...]

2022-05-06 07:00 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f26676f15dde62e9243537cd5d451c429520c256/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 85 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5bfcf782-586d-4870-b491-30ea146cd697) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-linkunfurling.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/f26676f15dde62e9243537cd5d451c429520c256/msteams-platform%2Fsbs-botbuilder-linkunfurling.yml) | 80 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b32804e0-74a4-41f5-871d-f45550e2b2b8) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-06 07:01 UTC, opbld33 commented
Docs Build status updates of commit _[f26676f](https://github.com/MicrosoftDocs/msteams-docs/commits/f26676f15dde62e9243537cd5d451c429520c256)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/Teams-link-unfurling/Output-desktop-new.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Output-desktop-new.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/output-desktop-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/Output-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Output-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/output-mobile.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling - Shortcut.lnk](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling%20-%20Shortcut.lnk) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/url-preview.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/auth-preview-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/card-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/card-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/card-preview.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/desktop-link-unfurl.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/desktop-link-unfurl.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/desktop-link-unfurl.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/desktop-newūnfurl.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/desktop-new%C5%ABnfurl.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/desktop-new%C5%ABnfurl.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/desktop.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/desktop.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/desktop.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/feature-mobile-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/install-preview-updated-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/mobile-link-unfurl.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/mobile-link-unfurl.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/result-output-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/result-output-new1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/result-output-new1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/result-output-new1.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/search-new-desktop-updated.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/search-new-desktop-updated.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/search-new-desktop-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/unfurl-desktop-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/unfurl-desktop-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/unfurl-desktop-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 4.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%204.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%204.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 5.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%205.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%205.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 7.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-l [...]

2022-05-06 07:16 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cf7e5bbbc3e171f087ad31eea9ce96180c7bc192/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 85 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/69e5e859-5c24-46cb-aec3-f2e9e59f6e7d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-linkunfurling.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/cf7e5bbbc3e171f087ad31eea9ce96180c7bc192/msteams-platform%2Fsbs-botbuilder-linkunfurling.yml) | 80 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0d6a5eb0-3feb-4193-a747-69f755a13dd5) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-06 07:16 UTC, opbld31 commented
Docs Build status updates of commit _[cf7e5bb](https://github.com/MicrosoftDocs/msteams-docs/commits/cf7e5bbbc3e171f087ad31eea9ce96180c7bc192)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/Teams-link-unfurling/Output-desktop-new.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Output-desktop-new.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/output-desktop-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/Output-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Output-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/output-mobile.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling - Shortcut.lnk](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling%20-%20Shortcut.lnk) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/url-preview.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/auth-preview-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/card-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/card-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/card-preview.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/desktop-link-unfurl.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/desktop-link-unfurl.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/desktop-newūnfurl.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/desktop-new%C5%ABnfurl.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/desktop-new%C5%ABnfurl.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/desktop.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/desktop.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/desktop.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/feature-mobile-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/install-preview-updated-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/mobile-link-unfurl.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/mobile-link-unfurl.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/result-output-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/result-output-new1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/result-output-new1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/result-output-new1.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/search-new-desktop-updated.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/search-new-desktop-updated.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/search-new-desktop-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/unfurl-desktop-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/unfurl-desktop-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/unfurl-desktop-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 4.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%204.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%204.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 5.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%205.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%205.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 7.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on [...]

2022-05-06 08:07 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9224960a81864a129a32a1e3c8170375ec56daa2/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 85 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6a6ce0c9-4040-4775-a0cf-5ff8c50d1749) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-linkunfurling.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/9224960a81864a129a32a1e3c8170375ec56daa2/msteams-platform%2Fsbs-botbuilder-linkunfurling.yml) | 80 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/32f95b7c-ae17-4ddc-8ee5-b8308419c935) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-06 08:08 UTC, opbld31 commented
Docs Build status updates of commit _[9224960](https://github.com/MicrosoftDocs/msteams-docs/commits/9224960a81864a129a32a1e3c8170375ec56daa2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/Teams-link-unfurling/Output-desktop-new.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Output-desktop-new.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/output-desktop-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/Output-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Output-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/output-mobile.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling - Shortcut.lnk](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling%20-%20Shortcut.lnk) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/url-preview.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/auth-preview-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/card-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/card-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/card-preview.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/desktop-link-unfurl.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/desktop-link-unfurl.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/desktop-newūnfurl.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/desktop-new%C5%ABnfurl.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/desktop-new%C5%ABnfurl.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/desktop.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/desktop.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/desktop.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/feature-mobile-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/install-preview-updated-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/mobile-link-unfurl.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/mobile-link-unfurl.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/result-output-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/result-output-new1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/result-output-new1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/result-output-new1.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/search-new-desktop-updated.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/search-new-desktop-updated.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/search-new-desktop-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/unfurl-desktop-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/unfurl-desktop-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/unfurl-desktop-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 4.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%204.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%204.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 5.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%205.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%205.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 7.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on [...]

2022-05-06 08:15 UTC, opbld30 commented
Docs Build status updates of commit _[de2dfd4](https://github.com/MicrosoftDocs/msteams-docs/commits/de2dfd465a625e53ddd71c550a7b5656eef75e36)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/Teams-link-unfurling/Output-desktop-new.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Output-desktop-new.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/output-desktop-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/Output-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Output-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/output-mobile.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling - Shortcut.lnk](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling%20-%20Shortcut.lnk) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/url-preview.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/auth-preview-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/card-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/card-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/card-preview.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/desktop-link-unfurl.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/desktop-link-unfurl.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/desktop-newūnfurl.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/desktop-new%C5%ABnfurl.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/desktop-new%C5%ABnfurl.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/desktop.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/desktop.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/desktop.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/feature-mobile-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/install-preview-updated-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/mobile-link-unfurl.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/mobile-link-unfurl.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/result-output-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/result-output-new1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/result-output-new1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/result-output-new1.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/search-new-desktop-updated.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/search-new-desktop-updated.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/search-new-desktop-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/unfurl-desktop-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/unfurl-desktop-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/unfurl-desktop-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 4.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%204.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%204.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 5.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%205.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%205.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 7.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on [...]

2022-05-06 08:21 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f976cc86fb87f9313e4b710cf85d7d66d42b4631/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 82 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/486a1af0-c818-473f-ad6b-e5baf1346dde) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-linkunfurling.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/f976cc86fb87f9313e4b710cf85d7d66d42b4631/msteams-platform%2Fsbs-botbuilder-linkunfurling.yml) | 80 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5b08403d-996e-4823-a757-e6aa4fe16b3b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-06 08:21 UTC, opbld31 commented
Docs Build status updates of commit _[f976cc8](https://github.com/MicrosoftDocs/msteams-docs/commits/f976cc86fb87f9313e4b710cf85d7d66d42b4631)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/Teams-link-unfurling/Output-desktop-new.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Output-desktop-new.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/output-desktop-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/Output-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Output-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/output-mobile.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling - Shortcut.lnk](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling%20-%20Shortcut.lnk) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/url-preview.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/auth-preview-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/card-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/card-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/card-preview.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/desktop-link-unfurl.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/desktop-link-unfurl.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/desktop-newūnfurl.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/desktop-new%C5%ABnfurl.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/desktop-new%C5%ABnfurl.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/desktop.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/desktop.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/desktop.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/feature-mobile-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/install-preview-updated-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/mobile-link-unfurl.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/mobile-link-unfurl.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/result-output-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/result-output-new1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/result-output-new1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/result-output-new1.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/search-new-desktop-updated.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/search-new-desktop-updated.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/search-new-desktop-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/unfurl-desktop-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/unfurl-desktop-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/unfurl-desktop-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 4.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%204.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%204.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 5.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%205.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%205.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 7.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on [...]

2022-05-06 08:23 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/369d7aba2d588fd7beca6d52332f2a93abce0fa7/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 82 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f4ca3c7c-b944-4580-98c9-fde040cb1c75) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-linkunfurling.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/369d7aba2d588fd7beca6d52332f2a93abce0fa7/msteams-platform%2Fsbs-botbuilder-linkunfurling.yml) | 80 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/751ee6e7-e3d9-41c1-870f-aded9bb8567e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-06 08:25 UTC, opbld33 commented
Docs Build status updates of commit _[369d7ab](https://github.com/MicrosoftDocs/msteams-docs/commits/369d7aba2d588fd7beca6d52332f2a93abce0fa7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/Teams-link-unfurling/Output-desktop-new.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Output-desktop-new.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/output-desktop-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/Output-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Output-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/output-mobile.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling - Shortcut.lnk](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling%20-%20Shortcut.lnk) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/url-preview.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/auth-preview-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/card-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/card-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/card-preview.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/desktop-link-unfurl.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/desktop-link-unfurl.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/desktop-newūnfurl.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/desktop-new%C5%ABnfurl.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/desktop-new%C5%ABnfurl.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/desktop.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/desktop.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/desktop.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/feature-mobile-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/install-preview-updated-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/mobile-link-unfurl.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/mobile-link-unfurl.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/result-output-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/result-output-new1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/result-output-new1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/result-output-new1.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/search-new-desktop-updated.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/search-new-desktop-updated.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/search-new-desktop-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/unfurl-desktop-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/unfurl-desktop-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/unfurl-desktop-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 4.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%204.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%204.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 5.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%205.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%205.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 7.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on [...]

2022-05-06 08:28 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/12f41209ebae2386f822ae0108f9bbcd150f8b52/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 84 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/88dd897f-30a9-4756-a8c2-64a5fb94c925) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-linkunfurling.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/12f41209ebae2386f822ae0108f9bbcd150f8b52/msteams-platform%2Fsbs-botbuilder-linkunfurling.yml) | 80 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/226859e6-ee7d-430e-b483-d932e46bf12c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-06 08:30 UTC, opbld30 commented
Docs Build status updates of commit _[12f4120](https://github.com/MicrosoftDocs/msteams-docs/commits/12f41209ebae2386f822ae0108f9bbcd150f8b52)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/Teams-link-unfurling/Output-desktop-new.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Output-desktop-new.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/output-desktop-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/Output-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Output-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/output-mobile.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling - Shortcut.lnk](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling%20-%20Shortcut.lnk) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/url-preview.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/auth-preview-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/card-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/card-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/card-preview.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/desktop-link-unfurl.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/desktop-link-unfurl.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/desktop-newūnfurl.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/desktop-new%C5%ABnfurl.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/desktop-new%C5%ABnfurl.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/desktop.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/desktop.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/desktop.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/feature-mobile-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/install-preview-updated-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/mobile-link-unfurl.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/mobile-link-unfurl.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/result-output-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/result-output-new1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/result-output-new1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/result-output-new1.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/search-new-desktop-updated.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/search-new-desktop-updated.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/search-new-desktop-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/unfurl-desktop-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/unfurl-desktop-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/unfurl-desktop-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 4.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%204.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%204.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 5.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%205.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%205.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 7.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on [...]

2022-05-06 09:03 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/af955442f22f269e9aa46975419109f02ac58793/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 84 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e9efe665-24ab-4daa-8b75-60c10e4b3c87) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-linkunfurling.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/af955442f22f269e9aa46975419109f02ac58793/msteams-platform%2Fsbs-botbuilder-linkunfurling.yml) | 80 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1b1ee0b6-5a5d-423e-9723-40c28b795dd8) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-06 09:25 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7cfb6f61d5e4f199c3fe5babf3ea9d32472ebb87/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 84 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0d452d58-d121-4d6b-8e81-0479ce44e0e7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-linkunfurling.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/7cfb6f61d5e4f199c3fe5babf3ea9d32472ebb87/msteams-platform%2Fsbs-botbuilder-linkunfurling.yml) | 80 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bd0f4af1-1697-43b4-8d09-7a778b7f0069) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-06 09:25 UTC, opbld32 commented
Docs Build status updates of commit _[7cfb6f6](https://github.com/MicrosoftDocs/msteams-docs/commits/7cfb6f61d5e4f199c3fe5babf3ea9d32472ebb87)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/Teams-link-unfurling/Output-desktop-new.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Output-desktop-new.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/output-desktop-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/Output-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Output-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/output-mobile.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling - Shortcut.lnk](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling%20-%20Shortcut.lnk) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/url-preview.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/auth-preview-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/card-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/card-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/card-preview.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/desktop-link-unfurl.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/desktop-link-unfurl.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/desktop-newūnfurl.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/desktop-new%C5%ABnfurl.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/desktop-new%C5%ABnfurl.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/desktop.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/desktop.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/desktop.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/feature-mobile-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/install-preview-updated-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/mobile-link-unfurl.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/mobile-link-unfurl.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/result-output-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/result-output-new1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/result-output-new1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/result-output-new1.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/search-new-desktop-updated.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/search-new-desktop-updated.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/search-new-desktop-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/unfurl-desktop-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/unfurl-desktop-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/unfurl-desktop-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 4.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%204.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%204.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 5.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%205.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%205.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 7.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on [...]

2022-05-06 09:27 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b02d83df0760161363a6442fee865d2e216def35/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 84 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a61c509b-b82e-4b8e-800b-9c40ec196c78) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-linkunfurling.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/b02d83df0760161363a6442fee865d2e216def35/msteams-platform%2Fsbs-botbuilder-linkunfurling.yml) | 80 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d1a0ff67-1b9e-4496-830b-d45fda338d37) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-06 09:27 UTC, opbld30 commented
Docs Build status updates of commit _[b02d83d](https://github.com/MicrosoftDocs/msteams-docs/commits/b02d83df0760161363a6442fee865d2e216def35)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/Teams-link-unfurling/Output-desktop-new.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Output-desktop-new.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/output-desktop-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/Output-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Output-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/output-mobile.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling - Shortcut.lnk](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling%20-%20Shortcut.lnk) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/url-preview.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/auth-preview-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/card-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/card-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/card-preview.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/desktop-link-unfurl.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/desktop-link-unfurl.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/desktop-newūnfurl.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/desktop-new%C5%ABnfurl.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/desktop-new%C5%ABnfurl.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/desktop.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/desktop.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/desktop.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/feature-mobile-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/install-preview-updated-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/mobile-link-unfurl.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/mobile-link-unfurl.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/result-output-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/result-output-new1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/result-output-new1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/result-output-new1.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/search-new-desktop-updated.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/search-new-desktop-updated.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/search-new-desktop-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/unfurl-desktop-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/unfurl-desktop-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/unfurl-desktop-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 4.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%204.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%204.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 5.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%205.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%205.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 7.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on [...]

2022-05-06 09:49 UTC, opbld31 commented
Docs Build status updates of commit _[bfc6946](https://github.com/MicrosoftDocs/msteams-docs/commits/bfc6946f6bf60e70d7472d3f6660a95256b3049d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/Teams-link-unfurling/Output-desktop-new.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Output-desktop-new.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/output-desktop-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/Output-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Output-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/output-mobile.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling - Shortcut.lnk](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling%20-%20Shortcut.lnk) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/url-preview.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/auth-preview-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/card-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/card-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/card-preview.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/desktop-link-unfurl.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/desktop-link-unfurl.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/desktop-newūnfurl.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/desktop-new%C5%ABnfurl.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/desktop-new%C5%ABnfurl.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/desktop.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/desktop.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/desktop.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/feature-mobile-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/install-preview-updated-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/mobile-link-unfurl.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/mobile-link-unfurl.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/result-output-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/result-output-new1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/result-output-new1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/result-output-new1.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/search-new-desktop-updated.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/search-new-desktop-updated.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/search-new-desktop-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/unfurl-desktop-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/unfurl-desktop-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/unfurl-desktop-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 4.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%204.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%204.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 5.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%205.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%205.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 7.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on [...]

2022-05-06 09:49 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bfc6946f6bf60e70d7472d3f6660a95256b3049d/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 84 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/89f77f90-f4e3-446b-9e81-eb0a6ae18ded) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-linkunfurling.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/bfc6946f6bf60e70d7472d3f6660a95256b3049d/msteams-platform%2Fsbs-botbuilder-linkunfurling.yml) | 80 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/311f2f25-55ac-41bf-b7de-c87117aaa29b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-09 09:59 UTC, v-abirade requested changes
@vsoniv, please make changes as per the comments.

2022-05-09 09:59 UTC, v-abirade commented on msteams-platform/messaging-extensions/how-to/link-unfurling.md
> +In link unfurling, your app can register to receive an invoke activity when URLs with a particular domain are pasted into the compose message area. The invoke contains the full URL and you can respon
Please rephrase.

2022-05-09 09:59 UTC, v-abirade commented on msteams-platform/messaging-extensions/how-to/link-unfurling.md
> +* Link unfurling provides preview of the URL
Use parallel structure.

2022-05-09 09:59 UTC, v-abirade commented on msteams-platform/messaging-extensions/how-to/link-unfurling.md
> +  Link unfurling on mobile using the following steps:
Please complete the sentence.

2022-05-09 09:59 UTC, v-abirade commented on msteams-platform/messaging-extensions/how-to/link-unfurling.md
> +   1. User has pasted an URL in the compose message area in mobile
Write the steps correctly. Please follow correct step- by step instruction convention.

2022-05-09 09:59 UTC, v-abirade commented on msteams-platform/messaging-extensions/how-to/link-unfurling.md
> +   1. User has pasted an URL in the compose message area in desktop
Write the steps correctly. Please follow correct step- by step instruction convention.

2022-05-09 09:59 UTC, v-abirade commented on msteams-platform/sbs-botbuilder-linkunfurling.yml
> +    **Key features of link unfurling**
.Add image for mobile in introduction and output

2022-05-10 09:35 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/67750e9061f4340ee96ae20e642bdf10859e0ee7/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 84 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9b2ec9e7-2ef8-4f54-91b1-20fa21404caa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-linkunfurling.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/67750e9061f4340ee96ae20e642bdf10859e0ee7/msteams-platform%2Fsbs-botbuilder-linkunfurling.yml) | 80 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fe8a6570-d94d-407c-a8de-b8b03b0e007d) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-10 09:36 UTC, opbld31 commented
Docs Build status updates of commit _[67750e9](https://github.com/MicrosoftDocs/msteams-docs/commits/67750e9061f4340ee96ae20e642bdf10859e0ee7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/Teams-link-unfurling/Output-desktop-new.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Output-desktop-new.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/output-desktop-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/Output-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Output-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/output-mobile.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling - Shortcut.lnk](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling%20-%20Shortcut.lnk) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/url-preview.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/auth-preview-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/card-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/card-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/card-preview.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/desktop-link-unfurl.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/desktop-link-unfurl.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/desktop-newūnfurl.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/desktop-new%C5%ABnfurl.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/desktop-new%C5%ABnfurl.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/desktop.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/desktop.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/desktop.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/feature-mobile-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/install-preview-updated-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/mobile-link-unfurl.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/mobile-link-unfurl.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/result-output-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/result-output-new1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/result-output-new1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/result-output-new1.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/search-new-desktop-updated.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/search-new-desktop-updated.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/search-new-desktop-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/unfurl-desktop-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/unfurl-desktop-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/unfurl-desktop-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 4.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%204.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%204.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 5.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%205.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%205.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 7.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on [...]

2022-05-10 09:55 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b1b0fffd2df1c2ccd8134d5cb1d40ba3084216a6/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 84 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/babd4bb0-be0f-48f4-840d-478dc6d1e717) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-linkunfurling.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/b1b0fffd2df1c2ccd8134d5cb1d40ba3084216a6/msteams-platform%2Fsbs-botbuilder-linkunfurling.yml) | 80 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/36dc85e1-3d03-421e-a11c-a3780d4d04fc) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-10 09:56 UTC, opbld30 commented
Docs Build status updates of commit _[b1b0fff](https://github.com/MicrosoftDocs/msteams-docs/commits/b1b0fffd2df1c2ccd8134d5cb1d40ba3084216a6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/Teams-link-unfurling/Output-desktop-new.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Output-desktop-new.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/output-desktop-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/Output-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Output-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/output-mobile.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling - Shortcut.lnk](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling%20-%20Shortcut.lnk) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/url-preview.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/auth-preview-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/card-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/card-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/card-preview.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/desktop-link-unfurl.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/desktop-link-unfurl.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/desktop-newūnfurl.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/desktop-new%C5%ABnfurl.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/desktop-new%C5%ABnfurl.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/desktop.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/desktop.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/desktop.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/feature-mobile-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/install-preview-updated-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/mobile-link-unfurl.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/mobile-link-unfurl.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/result-output-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/result-output-new1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/result-output-new1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/result-output-new1.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/search-new-desktop-updated.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/search-new-desktop-updated.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/search-new-desktop-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/unfurl-desktop-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/unfurl-desktop-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/unfurl-desktop-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 4.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%204.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%204.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 5.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%205.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%205.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 7.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on [...]

2022-05-10 10:05 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e824e6d6f7741c5d55b2925f29000fceb363265b/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 84 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/559bb97e-1a83-4c67-b464-ab6a7e50f183) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-linkunfurling.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e824e6d6f7741c5d55b2925f29000fceb363265b/msteams-platform%2Fsbs-botbuilder-linkunfurling.yml) | 80 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8ba20d08-f102-41e2-8985-29d598831c9e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-06-01 10:10 UTC, opbld30 commented
Docs Build status updates of commit _[3b40739](https://github.com/MicrosoftDocs/msteams-docs/commits/3b407396ab5adcefdf6a9654d29462b1caa8db58)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/Teams-link-unfurling/Output-desktop-new.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Output-desktop-new.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/output-desktop-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/Output-mobile.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Output-mobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/output-mobile.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling - Shortcut.lnk](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Teams-link-unfurling%20-%20Shortcut.lnk) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/Url-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/url-preview.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/auth-preview-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/auth-preview-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/card-preview.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/card-preview.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/card-preview.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/desktop-link-unfurl.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/desktop-link-unfurl.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/desktop-newūnfurl.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/desktop-new%C5%ABnfurl.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/desktop-new%C5%ABnfurl.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/desktop.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/desktop.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/desktop.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/feature-mobile-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/feature-mobile-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/install-preview-updated-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/install-preview-updated-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/mobile-link-unfurl.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/mobile-link-unfurl.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/result-output-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/result-output-new.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/result-output-new1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/result-output-new1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/result-output-new1.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/search-new-desktop-updated.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/search-new-desktop-updated.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/search-new-desktop-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/Teams-link-unfurling/unfurl-desktop-updated.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/Teams-link-unfurling/unfurl-desktop-updated.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-link-unfurling/unfurl-desktop-updated.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 4.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%204.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%204.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 5.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on-mobile/msteams-platform/assets/images/compose-extensions/Capture%205.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/compose-extensions/capture%205.png?branch=pr-en-us-5767) |
[msteams-platform/assets/images/compose-extensions/Capture 7.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-feature-enable-link-unfurling-on [...]

2022-09-28 11:35 UTC, surbhigupta12 commented
Closing this PR as it is part of #7041

2022-09-28 11:35 UTC, closed without merging