[Doc-Improvement][Teams-Toolkit]
MicrosoftDocs/msteams-docs pull request #5837
Opened 2022-05-02 11:27 UTC by v-rramanna

2022-05-02 11:28 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/TeamsFx-manifest-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/696aa4eef37e5d59c20c1f72313f31968c4799e7/msteams-platform%2Ftoolkit%2FTeamsFx-manifest-customization.md) | 88 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0e60880a-6f4f-44e4-8e0e-094296efc585) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/696aa4eef37e5d59c20c1f72313f31968c4799e7/msteams-platform%2Ftoolkit%2FTeamsFx-manifest-preview.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5e916fc8-373a-4556-bb0d-0d621efb8c02) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-02 11:28 UTC, opbld31 commented
Docs Build status updates of commit _[696aa4e](https://github.com/MicrosoftDocs/msteams-docs/commits/696aa4eef37e5d59c20c1f72313f31968c4799e7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/toolkit/TeamsFx-manifest-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-manifest-customization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-customization?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-manifest-preview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C2%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202205021127545308-5837%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-02T11%3A28%3A49Z&sr=b&sp=r&sig=KBbNfMomDNJXCMqSjUqLyUxKlYjqsZh1tewrE5PHD6Q%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-03 02:56 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/TeamsFx-manifest-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/360c4a1cf7cc6b2f38da0ff24f7e311159230336/msteams-platform%2Ftoolkit%2FTeamsFx-manifest-customization.md) | 88 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fb3398a0-d9f9-43df-8778-f23420f21d87) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/360c4a1cf7cc6b2f38da0ff24f7e311159230336/msteams-platform%2Ftoolkit%2FTeamsFx-manifest-preview.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5071c252-8a6f-4c4f-a2b7-f157217a2db4) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-03 02:56 UTC, opbld32 commented
Docs Build status updates of commit _[360c4a1](https://github.com/MicrosoftDocs/msteams-docs/commits/360c4a1cf7cc6b2f38da0ff24f7e311159230336)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/teams-toolkit-v2/create-project.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/create-project.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-manifest-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-manifest-customization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-customization?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-manifest-preview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C3%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202205030255590840-5837%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-03T02%3A56%3A44Z&sr=b&sp=r&sig=4NzfFobP3Jrf9GQDN69Naa1CsijRbDyJHPb123%2Bye%2Bs%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-03 03:01 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/TeamsFx-manifest-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5686c8e764529526fd13b85be630934394ddc748/msteams-platform%2Ftoolkit%2FTeamsFx-manifest-customization.md) | 88 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/782755b0-5504-429a-9cd0-21d113f15737) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5686c8e764529526fd13b85be630934394ddc748/msteams-platform%2Ftoolkit%2FTeamsFx-manifest-preview.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/97b33943-11b4-4be0-8440-c0140d544d87) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-03 03:01 UTC, opbld33 commented
Docs Build status updates of commit _[5686c8e](https://github.com/MicrosoftDocs/msteams-docs/commits/5686c8e764529526fd13b85be630934394ddc748)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/teams-toolkit-v2/create-project.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/create-project.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-manifest-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-manifest-customization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-customization?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-manifest-preview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C3%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202205030301133909-5837%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-03T03%3A01%3A56Z&sr=b&sp=r&sig=%2Bzc35FxyebZAXDjUIUg6Bq7PWUI0pkTBHpmS7uQ8DfQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-03 03:04 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/TeamsFx-manifest-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fd41b3a19b6163d16c6bc74413719a4b4be676d7/msteams-platform%2Ftoolkit%2FTeamsFx-manifest-customization.md) | 88 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0d4127e6-88fa-4852-a183-86c7695c7251) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-03 03:04 UTC, opbld30 commented
Docs Build status updates of commit _[fd41b3a](https://github.com/MicrosoftDocs/msteams-docs/commits/fd41b3a19b6163d16c6bc74413719a4b4be676d7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/teams-toolkit-v2/create-project.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/create-project.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-manifest-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-manifest-customization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-customization?branch=pr-en-us-5837) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C3%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202205030303407890-5837%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-03T03%3A04%3A25Z&sr=b&sp=r&sig=xwLUpUqC7poeeCznChdJGIl3DCMzvEDMtOfQ04FFpr0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-03 10:13 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/TeamsFx-manifest-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/52a76d8432bb6d0a58e11c18fd4700affbac59b0/msteams-platform%2Ftoolkit%2FTeamsFx-manifest-customization.md) | 88 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d6ff79fc-450d-442b-9ca7-04fa72ea776e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-03 10:14 UTC, opbld30 commented
Docs Build status updates of commit _[52a76d8](https://github.com/MicrosoftDocs/msteams-docs/commits/52a76d8432bb6d0a58e11c18fd4700affbac59b0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/teams-toolkit-v2/create-project.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/create-project.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-manifest-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-manifest-customization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-customization?branch=pr-en-us-5837) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C3%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202205031013343904-5837%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-03T10%3A14%3A32Z&sr=b&sp=r&sig=CA6oM6FvU%2FNPQJATEN7pQoW%2F6d5zXAwI7X5229o9Itw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-03 16:35 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/TeamsFx-manifest-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6057f012b65833791edb0f18810c98c7ea646b8d/msteams-platform%2Ftoolkit%2FTeamsFx-manifest-customization.md) | 88 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4b103811-1433-4b68-98ca-e60130106994) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6057f012b65833791edb0f18810c98c7ea646b8d/msteams-platform%2Ftoolkit%2FTeamsFx-manifest-preview.md) | 89 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f00f4e39-4877-46cc-9837-04952e4ad1bc) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-03 16:35 UTC, opbld30 commented
Docs Build status updates of commit _[6057f01](https://github.com/MicrosoftDocs/msteams-docs/commits/6057f012b65833791edb0f18810c98c7ea646b8d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/toolkit/TeamsFx-manifest-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-manifest-customization.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-customization?branch=pr-en-us-5837) | [Details](#user-content-4b79caac002a5471906c80c4179f299c-40497546)
[msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-manifest-preview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) | [Details](#user-content-2c7cdd9ef78ab71d670c5049f92895b0-40497546)
[msteams-platform/assets/images/teams-toolkit-v2/create-project.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/create-project.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5837) |

<a id="4b79caac002a5471906c80c4179f299c-40497546"></a>
### [msteams-platform/toolkit/TeamsFx-manifest-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-manifest-customization.md)
 - **Line 0, Column 0**: **[Warning: h1-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/h1-missing?branch=main)]** `````H1 is required. Use a single hash (#) followed by a space to create your top-level heading.`````

<a id="2c7cdd9ef78ab71d670c5049f92895b0-40497546"></a>
### [msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-manifest-preview.md)
 - **Line 65, Column 1**: **[Warning: multiple-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** `````Multiple H1s(H1 'Customize app manifest') are not allowed. You can only have one top-level heading.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C3%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202205031634393202-5837%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-03T16%3A35%3A23Z&sr=b&sp=r&sig=qjQ%2BgUFXu2er3blPjo3fJtw0tmlHhSXupX9zcgZb5NA%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-03 17:18 UTC, opbld33 commented
Docs Build status updates of commit _[d734434](https://github.com/MicrosoftDocs/msteams-docs/commits/d734434ee3884185107f33cf3edc043ca4798a72)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/toolkit/TeamsFx-manifest-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-manifest-customization.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-customization?branch=pr-en-us-5837) | [Details](#user-content-4b79caac002a5471906c80c4179f299c-0737af68)
[msteams-platform/assets/images/teams-toolkit-v2/create-project.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/create-project.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-manifest-preview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |

<a id="4b79caac002a5471906c80c4179f299c-0737af68"></a>
### [msteams-platform/toolkit/TeamsFx-manifest-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-manifest-customization.md)
 - **Line 0, Column 0**: **[Warning: h1-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/h1-missing?branch=main)]** `````H1 is required. Use a single hash (#) followed by a space to create your top-level heading.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C3%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202205031717108194-5837%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-03T17%3A18%3A06Z&sr=b&sp=r&sig=%2B%2FVtxy9GG1tvH5JYdHDXtOrfYcfUZtbHMS4wMTfTtAg%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-03 17:18 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/TeamsFx-manifest-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d734434ee3884185107f33cf3edc043ca4798a72/msteams-platform%2Ftoolkit%2FTeamsFx-manifest-customization.md) | 88 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ceea7198-b20e-467a-9be1-2294c3d96f4e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d734434ee3884185107f33cf3edc043ca4798a72/msteams-platform%2Ftoolkit%2FTeamsFx-manifest-preview.md) | 89 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/99ae68fb-77c7-433c-b619-c7398d53ee58) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-03 17:30 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/TeamsFx-manifest-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5a7a6df702218c7b5c45fd816b4f3b739046b9fe/msteams-platform%2Ftoolkit%2FTeamsFx-manifest-customization.md) | 88 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f942a538-24b1-478e-bb29-61cdd4786d29) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5a7a6df702218c7b5c45fd816b4f3b739046b9fe/msteams-platform%2Ftoolkit%2FTeamsFx-manifest-preview.md) | 89 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/19e3eedd-873c-4ea8-b14e-4d6b418c5de4) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-03 17:30 UTC, opbld32 commented
Docs Build status updates of commit _[5a7a6df](https://github.com/MicrosoftDocs/msteams-docs/commits/5a7a6df702218c7b5c45fd816b4f3b739046b9fe)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/teams-toolkit-v2/create-project.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/create-project.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-manifest-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-manifest-customization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-customization?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-manifest-preview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C3%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202205031729549724-5837%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-03T17%3A30%3A55Z&sr=b&sp=r&sig=B%2BWVJqgZ4G2bb31RktHot4c7byn1K5JO%2B3V8xrsaNVI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-04 09:34 UTC, opbld31 commented
Docs Build status updates of commit _[ca0e323](https://github.com/MicrosoftDocs/msteams-docs/commits/ca0e3233a8f135f0041f9cf7e670d2c1dec14a3d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-manifest-preview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) | [Details](#user-content-2c7cdd9ef78ab71d670c5049f92895b0-d2d71a1e)
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/TOC.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) | [Details](#user-content-f679b5d0ee59eb212f56a224ff613c91-d2d71a1e)
[msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-multi-env.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-multi-env?branch=pr-en-us-5837) | [Details](#user-content-12216123ba329c9ca6700f9d931f42c2-d2d71a1e)
[msteams-platform/assets/images/teams-toolkit-v2/create-project.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/create-project.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-manifest-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/toolkit/TeamsFx-manifest-customization.md) | :white_check_mark:Succeeded | |

<a id="2c7cdd9ef78ab71d670c5049f92895b0-d2d71a1e"></a>
### [msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-manifest-preview.md)
 - **Line 124, Column 1**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'TeamsFx-manifest-customization.md'.`````

<a id="f679b5d0ee59eb212f56a224ff613c91-d2d71a1e"></a>
### [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/TOC.yml)
 - **Line 112, Column 13**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'toolkit/TeamsFx-manifest-customization.md'.`````

<a id="12216123ba329c9ca6700f9d931f42c2-d2d71a1e"></a>
### [msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-multi-env.md)
 - **Line 80, Column 145**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'TeamsFx-manifest-customization.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C4%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202205040933435220-5837%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-04T09%3A34%3A28Z&sr=b&sp=r&sig=GahZ3sJgb4XzVJvnwDUP5uuT%2BSdMEDWSdtyh6VhEQbg%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-09 08:05 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b50bd65f8f8ae8a56a356bd5471e54d3a5e91860/msteams-platform%2Ftoolkit%2FTeamsFx-manifest-preview.md) | 89 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5493dae1-e7e9-43e6-9d3b-0cccb8b001fe) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-09 08:05 UTC, opbld33 commented
Docs Build status updates of commit _[b50bd65](https://github.com/MicrosoftDocs/msteams-docs/commits/b50bd65f8f8ae8a56a356bd5471e54d3a5e91860)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-manifest-preview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) | [Details](#user-content-2c7cdd9ef78ab71d670c5049f92895b0-561e99f9)
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/TOC.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) | [Details](#user-content-f679b5d0ee59eb212f56a224ff613c91-561e99f9)
[msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-multi-env.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-multi-env?branch=pr-en-us-5837) | [Details](#user-content-12216123ba329c9ca6700f9d931f42c2-561e99f9)
[msteams-platform/assets/images/teams-toolkit-v2/create-project.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/create-project.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-manifest-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/toolkit/TeamsFx-manifest-customization.md) | :white_check_mark:Succeeded | |

<a id="2c7cdd9ef78ab71d670c5049f92895b0-561e99f9"></a>
### [msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-manifest-preview.md)
 - **Line 124, Column 1**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'TeamsFx-manifest-customization.md'.`````

<a id="f679b5d0ee59eb212f56a224ff613c91-561e99f9"></a>
### [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/TOC.yml)
 - **Line 112, Column 13**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'toolkit/TeamsFx-manifest-customization.md'.`````

<a id="12216123ba329c9ca6700f9d931f42c2-561e99f9"></a>
### [msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-multi-env.md)
 - **Line 80, Column 145**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'TeamsFx-manifest-customization.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C9%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202205090804481890-5837%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-09T08%3A05%3A33Z&sr=b&sp=r&sig=5sRyhS%2Flu9BkJtqWkp54y9nvYvGgHkUtGGPKYHw6E5I%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-09 08:51 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4a17190f6e82f2372aee8e8fd998874a50968574/msteams-platform%2Ftoolkit%2FTeamsFx-manifest-preview.md) | 86 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bd9e1aff-0837-4467-bac3-8f1632ffced4) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-09 08:52 UTC, opbld30 commented
Docs Build status updates of commit _[4a17190](https://github.com/MicrosoftDocs/msteams-docs/commits/4a17190f6e82f2372aee8e8fd998874a50968574)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-manifest-preview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) | [Details](#user-content-2c7cdd9ef78ab71d670c5049f92895b0-e841f52b)
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/TOC.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) | [Details](#user-content-f679b5d0ee59eb212f56a224ff613c91-e841f52b)
[msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-multi-env.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-multi-env?branch=pr-en-us-5837) | [Details](#user-content-12216123ba329c9ca6700f9d931f42c2-e841f52b)
[msteams-platform/assets/images/teams-toolkit-v2/create-project.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/create-project.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-manifest-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/toolkit/TeamsFx-manifest-customization.md) | :white_check_mark:Succeeded | |

<a id="2c7cdd9ef78ab71d670c5049f92895b0-e841f52b"></a>
### [msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-manifest-preview.md)
 - **Line 71, Column 5**: **[Warning: alt-text-bad-value - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/alt-text-bad-value?branch=main)]** `````Alt text 'deploy-manifest' is the same as the image file name. This redundancy adds no value for users of screen readers. For accessibility, add more descriptive alt text.`````
 - **Line 71, Column 5**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../images/deploy-manifest.png'.`````
 - **Line 76, Column 5**: **[Warning: alt-text-bad-value - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/alt-text-bad-value?branch=main)]** `````Alt text 'deploy-command' is the same as the image file name. This redundancy adds no value for users of screen readers. For accessibility, add more descriptive alt text.`````
 - **Line 76, Column 5**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../images/deploy-command.png'.`````
 - **Line 82, Column 5**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../images/updatetoteamsplatform.png'.`````
 - **Line 91, Column 1**: **[Warning: invalid-note-section]** `````Text in the first line of Note/Section/Video is not valid. Will be rendered to <blockquote>`````
 - **Line 93, Column 1**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../images/manifest_outdated_dialog.png'.`````
 - **Line 99, Column 1**: **[Warning: invalid-note-section]** `````Text in the first line of Note/Section/Video is not valid. Will be rendered to <blockquote>`````
 - **Line 136, Column 5**: **[Warning: alt-text-bad-value - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/alt-text-bad-value?branch=main)]** `````Alt text 'validate' is the same as the image file name. This redundancy adds no value for users of screen readers. For accessibility, add more descriptive alt text.`````
 - **Line 136, Column 5**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../images/validate.png'.`````
 - **Line 150, Column 1**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../images/codelens.png'.`````
 - **Line 156, Column 1**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../images/select-env-with-local.png'.`````
 - **Line 160, Column 1**: **[Warning: alt-text-bad-value - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/alt-text-bad-value?branch=main)]** `````Alt text 'hover' is the same as the image file name. This redundancy adds no value for users of screen readers. For accessibility, add more descriptive alt text.`````
 - **Line 160, Column 1**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../images/hover.png'.`````

<a id="f679b5d0ee59eb212f56a224ff613c91-e841f52b"></a>
### [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/TOC.yml)
 - **Line 112, Column 13**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'toolkit/TeamsFx-manifest-customization.md'.`````

<a id="12216123ba329c9ca6700f9d931f42c2-e841f52b"></a>
### [msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-multi-env.md)
 - **Line 80, Column 145**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'TeamsFx-manifest-customization.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C9%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202205090851189957-5837%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-09T08%3A52%3A03Z&sr=b&sp=r&sig=8998X2Y7kxd1zMJr17XLKG%2FkPdXABNqZ2D0FgbYoa70%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the [...]

2022-05-09 10:55 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/8ef4329bf43cb9acf955a86bfc14a42daea6b1d8/msteams-platform%2FTOC.yml) | 98 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2404110b-6c7c-48ca-aeb4-7c5e459c940f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8ef4329bf43cb9acf955a86bfc14a42daea6b1d8/msteams-platform%2Ftoolkit%2FTeamsFx-manifest-preview.md) | 86 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1a135955-6916-4c23-85c0-03e6b0f7c113) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8ef4329bf43cb9acf955a86bfc14a42daea6b1d8/msteams-platform%2Ftoolkit%2FTeamsFx-multi-env.md) | 90 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3dea433b-e18c-4d63-9a1b-b3ad95bc3ff8) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-09 10:55 UTC, opbld30 commented
Docs Build status updates of commit _[8ef4329](https://github.com/MicrosoftDocs/msteams-docs/commits/8ef4329bf43cb9acf955a86bfc14a42daea6b1d8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-manifest-preview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) | [Details](#user-content-2c7cdd9ef78ab71d670c5049f92895b0-93c594ac)
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/create-project.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/create-project.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-manifest-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/toolkit/TeamsFx-manifest-customization.md) | :white_check_mark:Succeeded | |
[msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-multi-env.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-multi-env?branch=pr-en-us-5837) |

<a id="2c7cdd9ef78ab71d670c5049f92895b0-93c594ac"></a>
### [msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-manifest-preview.md)
 - **Line 71, Column 5**: **[Warning: alt-text-bad-value - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/alt-text-bad-value?branch=main)]** `````Alt text 'deploy-manifest' is the same as the image file name. This redundancy adds no value for users of screen readers. For accessibility, add more descriptive alt text.`````
 - **Line 71, Column 5**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../images/deploy-manifest.png'.`````
 - **Line 76, Column 5**: **[Warning: alt-text-bad-value - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/alt-text-bad-value?branch=main)]** `````Alt text 'deploy-command' is the same as the image file name. This redundancy adds no value for users of screen readers. For accessibility, add more descriptive alt text.`````
 - **Line 76, Column 5**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../images/deploy-command.png'.`````
 - **Line 82, Column 5**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../images/updatetoteamsplatform.png'.`````
 - **Line 91, Column 1**: **[Warning: invalid-note-section]** `````Text in the first line of Note/Section/Video is not valid. Will be rendered to <blockquote>`````
 - **Line 93, Column 1**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../images/manifest_outdated_dialog.png'.`````
 - **Line 99, Column 1**: **[Warning: invalid-note-section]** `````Text in the first line of Note/Section/Video is not valid. Will be rendered to <blockquote>`````
 - **Line 136, Column 5**: **[Warning: alt-text-bad-value - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/alt-text-bad-value?branch=main)]** `````Alt text 'validate' is the same as the image file name. This redundancy adds no value for users of screen readers. For accessibility, add more descriptive alt text.`````
 - **Line 136, Column 5**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../images/validate.png'.`````
 - **Line 150, Column 1**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../images/codelens.png'.`````
 - **Line 156, Column 1**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../images/select-env-with-local.png'.`````
 - **Line 160, Column 1**: **[Warning: alt-text-bad-value - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/alt-text-bad-value?branch=main)]** `````Alt text 'hover' is the same as the image file name. This redundancy adds no value for users of screen readers. For accessibility, add more descriptive alt text.`````
 - **Line 160, Column 1**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../images/hover.png'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C9%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202205091054491656-5837%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-09T10%3A55%3A53Z&sr=b&sp=r&sig=2uocU6EfQJIkQPo0e7PjulN9vH2h%2B2ZX0vSLal%2BeLP0%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-09 12:15 UTC, opbld31 commented
Docs Build status updates of commit _[1702cc5](https://github.com/MicrosoftDocs/msteams-docs/commits/1702cc5b17a5b2721e152384e5bcb5b02c863e17)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-manifest-preview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) | [Details](#user-content-2c7cdd9ef78ab71d670c5049f92895b0-f85a1414)
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/create-project.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/create-project.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-manifest-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/toolkit/TeamsFx-manifest-customization.md) | :white_check_mark:Succeeded | |
[msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-multi-env.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-multi-env?branch=pr-en-us-5837) |

<a id="2c7cdd9ef78ab71d670c5049f92895b0-f85a1414"></a>
### [msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-manifest-preview.md)
 - **Line 71, Column 5**: **[Warning: alt-text-bad-value - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/alt-text-bad-value?branch=main)]** `````Alt text 'deploy-manifest' is the same as the image file name. This redundancy adds no value for users of screen readers. For accessibility, add more descriptive alt text.`````
 - **Line 71, Column 5**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../images/deploy-manifest.png'.`````
 - **Line 76, Column 5**: **[Warning: alt-text-bad-value - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/alt-text-bad-value?branch=main)]** `````Alt text 'deploy-command' is the same as the image file name. This redundancy adds no value for users of screen readers. For accessibility, add more descriptive alt text.`````
 - **Line 76, Column 5**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../images/deploy-command.png'.`````
 - **Line 82, Column 5**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../images/updatetoteamsplatform.png'.`````
 - **Line 91, Column 1**: **[Warning: invalid-note-section]** `````Text in the first line of Note/Section/Video is not valid. Will be rendered to <blockquote>`````
 - **Line 93, Column 1**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../images/manifest_outdated_dialog.png'.`````
 - **Line 99, Column 1**: **[Warning: invalid-note-section]** `````Text in the first line of Note/Section/Video is not valid. Will be rendered to <blockquote>`````
 - **Line 136, Column 5**: **[Warning: alt-text-bad-value - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/alt-text-bad-value?branch=main)]** `````Alt text 'validate' is the same as the image file name. This redundancy adds no value for users of screen readers. For accessibility, add more descriptive alt text.`````
 - **Line 136, Column 5**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../images/validate.png'.`````
 - **Line 150, Column 1**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../images/codelens.png'.`````
 - **Line 156, Column 1**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../images/select-env-with-local.png'.`````
 - **Line 160, Column 1**: **[Warning: alt-text-bad-value - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/alt-text-bad-value?branch=main)]** `````Alt text 'hover' is the same as the image file name. This redundancy adds no value for users of screen readers. For accessibility, add more descriptive alt text.`````
 - **Line 160, Column 1**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../images/hover.png'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C9%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202205091214450704-5837%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-09T12%3A15%3A24Z&sr=b&sp=r&sig=d4Ya6uKGxwTedyStgvde%2F31Ox1wCb2U7gSFsUfNvhd4%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-10 07:44 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/2ab12d103c067d4f680e34f6bfd7f081b104f539/msteams-platform%2FTOC.yml) | 98 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1ac7a161-32fb-4620-94a1-873c0ea6594e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2ab12d103c067d4f680e34f6bfd7f081b104f539/msteams-platform%2Ftoolkit%2FTeamsFx-manifest-preview.md) | 86 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/81ada992-047a-44b1-84a2-29d125c526a3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2ab12d103c067d4f680e34f6bfd7f081b104f539/msteams-platform%2Ftoolkit%2FTeamsFx-multi-env.md) | 90 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c0d37f55-004b-4b70-bf30-fee04e500f50) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-10 07:45 UTC, opbld33 commented
Docs Build status updates of commit _[2ab12d1](https://github.com/MicrosoftDocs/msteams-docs/commits/2ab12d103c067d4f680e34f6bfd7f081b104f539)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-manifest-preview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) | [Details](#user-content-2c7cdd9ef78ab71d670c5049f92895b0-ff7edd2f)
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/create-project.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/create-project.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-multi-env.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-multi-env?branch=pr-en-us-5837) |

<a id="2c7cdd9ef78ab71d670c5049f92895b0-ff7edd2f"></a>
### [msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-manifest-preview.md)
 - **Line 71, Column 5**: **[Warning: alt-text-bad-value - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/alt-text-bad-value?branch=main)]** `````Alt text 'deploy-manifest' is the same as the image file name. This redundancy adds no value for users of screen readers. For accessibility, add more descriptive alt text.`````
 - **Line 71, Column 5**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../images/deploy-manifest.png'.`````
 - **Line 76, Column 5**: **[Warning: alt-text-bad-value - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/alt-text-bad-value?branch=main)]** `````Alt text 'deploy-command' is the same as the image file name. This redundancy adds no value for users of screen readers. For accessibility, add more descriptive alt text.`````
 - **Line 76, Column 5**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../images/deploy-command.png'.`````
 - **Line 82, Column 5**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../images/updatetoteamsplatform.png'.`````
 - **Line 91, Column 1**: **[Warning: invalid-note-section]** `````Text in the first line of Note/Section/Video is not valid. Will be rendered to <blockquote>`````
 - **Line 93, Column 1**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../images/manifest_outdated_dialog.png'.`````
 - **Line 99, Column 1**: **[Warning: invalid-note-section]** `````Text in the first line of Note/Section/Video is not valid. Will be rendered to <blockquote>`````
 - **Line 136, Column 5**: **[Warning: alt-text-bad-value - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/alt-text-bad-value?branch=main)]** `````Alt text 'validate' is the same as the image file name. This redundancy adds no value for users of screen readers. For accessibility, add more descriptive alt text.`````
 - **Line 136, Column 5**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../images/validate.png'.`````
 - **Line 150, Column 1**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../images/codelens.png'.`````
 - **Line 156, Column 1**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../images/select-env-with-local.png'.`````
 - **Line 160, Column 1**: **[Warning: alt-text-bad-value - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/alt-text-bad-value?branch=main)]** `````Alt text 'hover' is the same as the image file name. This redundancy adds no value for users of screen readers. For accessibility, add more descriptive alt text.`````
 - **Line 160, Column 1**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../images/hover.png'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202205100744103725-5837/BuildReport?accessString=d6168396ebe7a5d309dbfe548b9ae0485c06f3e5f0589a878fb61d230bffab21).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-10 09:14 UTC, opbld30 commented
Docs Build status updates of commit _[c614601](https://github.com/MicrosoftDocs/msteams-docs/commits/c614601cb20c2ba72030d5bccc3bf34eab7ce32d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-manifest-preview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) | [Details](#user-content-2c7cdd9ef78ab71d670c5049f92895b0-cf168a05)
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/create-project.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/create-project.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/codelens.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/codelens.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/codelens.png?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/hover.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/hover.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/hover.png?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/select-environment.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/select-environment.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/select-environment.png?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/validate-manifest.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/validate-manifest.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/validate-manifest.png?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-multi-env.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-multi-env?branch=pr-en-us-5837) |

<a id="2c7cdd9ef78ab71d670c5049f92895b0-cf168a05"></a>
### [msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-manifest-preview.md)
 - **Line 0, Column 0**: **[Warning: h1-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/h1-missing?branch=main)]** `````H1 is required. Use a single hash (#) followed by a space to create your top-level heading.`````
 - **Line 46, Column 5**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../assets/images/teams-toolkit-v2/teams toolkit fundamentals/validate-manifest'.`````
 - **Line 144, Column 1**: **[Warning: code-block-unclosed - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202205100913191241-5837/BuildReport?accessString=1f9fbd54a677ea2667cd659287f572bea5d1ade4f506fdf3734541c2ac5fe1c6).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-10 09:15 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c614601cb20c2ba72030d5bccc3bf34eab7ce32d/msteams-platform%2FTOC.yml) | 98 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3306f443-78cf-4386-b628-a19b098780e6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c614601cb20c2ba72030d5bccc3bf34eab7ce32d/msteams-platform%2Ftoolkit%2FTeamsFx-manifest-preview.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/025747ee-58e9-4931-9fca-a0acd9e40d77) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c614601cb20c2ba72030d5bccc3bf34eab7ce32d/msteams-platform%2Ftoolkit%2FTeamsFx-multi-env.md) | 90 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0afbe639-c3d8-42b0-8e72-cb3732baffc5) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-10 09:24 UTC, opbld30 commented
Docs Build status updates of commit _[8d7bd9c](https://github.com/MicrosoftDocs/msteams-docs/commits/8d7bd9c9c82aafdc8ae2849650c5a8a5192af35c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-manifest-preview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) | [Details](#user-content-2c7cdd9ef78ab71d670c5049f92895b0-6dc99218)
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/create-project.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/create-project.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/codelens.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/codelens.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/codelens.png?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/hover.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/hover.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/hover.png?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/select-environment.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/select-environment.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/select-environment.png?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/validate-manifest.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/validate-manifest.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/validate-manifest.png?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-multi-env.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-multi-env?branch=pr-en-us-5837) |

<a id="2c7cdd9ef78ab71d670c5049f92895b0-6dc99218"></a>
### [msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-manifest-preview.md)
 - **Line 0, Column 0**: **[Warning: h1-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/h1-missing?branch=main)]** `````H1 is required. Use a single hash (#) followed by a space to create your top-level heading.`````
 - **Line 46, Column 1**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../assets/images/teams-toolkit-v2/teams toolkit fundamentals/validate-manifest'.`````
 - **Line 144, Column 1**: **[Warning: code-block-unclosed - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202205100923484056-5837/BuildReport?accessString=04fbc7efd1dc8312493474edfa872ea8d54a89c9bff464d8be9a5dd728bc6e1a).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-10 09:54 UTC, opbld33 commented
Docs Build status updates of commit _[2ce31b3](https://github.com/MicrosoftDocs/msteams-docs/commits/2ce31b375eb770e0c1f78c5d91d49a6ca99c872c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-manifest-preview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) | [Details](#user-content-2c7cdd9ef78ab71d670c5049f92895b0-ca1c6dd0)
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/create-project.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/create-project.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/codelens.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/codelens.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/hover.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/hover.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/select-environment.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/select-environment.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/validate-manifest1.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/validate-manifest1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/validate-manifest1.png?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-multi-env.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-multi-env?branch=pr-en-us-5837) |

<a id="2c7cdd9ef78ab71d670c5049f92895b0-ca1c6dd0"></a>
### [msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-manifest-preview.md)
 - **Line 0, Column 0**: **[Warning: h1-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/h1-missing?branch=main)]** `````H1 is required. Use a single hash (#) followed by a space to create your top-level heading.`````
 - **Line 46, Column 1**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../assets/images/teams-toolkit-v2/teams toolkit fundamentals/validate-manifest1'.`````
 - **Line 50, Column 1**: **[Warning: code-block-indented - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-indented?branch=main)]** `````Indented code blocks aren't allowed. Use a Markdown code block surrounded by triple backticks (```).`````
 - **Line 61, Column 1**: **[Warning: alt-text-bad-value - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/alt-text-bad-value?branch=main)]** `````Alt text 'Codelens' is the same as the image file name. This redundancy adds no value for users of screen readers. For accessibility, add more descriptive alt text.`````
 - **Line 61, Column 1**: **[Warning: duplicate-alt-text - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-alt-text?branch=main)]** `````Alt text 'Codelens' is duplicated. Within an article, alt text must be unique.`````
 - **Line 67, Column 1**: **[Warning: duplicate-alt-text - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-alt-text?branch=main)]** `````Alt text 'Codelens' is duplicated. Within an article, alt text must be unique.`````
 - **Line 71, Column 1**: **[Warning: alt-text-bad-value - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/alt-text-bad-value?branch=main)]** `````Alt text 'Hover' is the same as the image file name. This redundancy adds no value for users of screen readers. For accessibility, add more descriptive alt text.`````
 - **Line 144, Column 1**: **[Warning: code-block-indented - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-indented?branch=main)]** `````Indented code blocks aren't allowed. Use a Markdown code block surrounded by triple backticks (```).`````
 - **Line 158, Column 1**: **[Warning: invalid-note-section]** `````Text in the first line of Note/Section/Video is not valid. Will be rendered to <blockquote>`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202205100954008609-5837/BuildReport?accessString=d93bb64d81b737a1ec426b149148f8c63336c0defbce71e24982da9e9d06f025).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-10 09:55 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/2ce31b375eb770e0c1f78c5d91d49a6ca99c872c/msteams-platform%2FTOC.yml) | 98 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0afafd90-bd3b-4b41-9d37-781559c37442) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2ce31b375eb770e0c1f78c5d91d49a6ca99c872c/msteams-platform%2Ftoolkit%2FTeamsFx-manifest-preview.md) | 86 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/02ffbff9-294f-4a85-9954-03e03349f273) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2ce31b375eb770e0c1f78c5d91d49a6ca99c872c/msteams-platform%2Ftoolkit%2FTeamsFx-multi-env.md) | 90 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/51e4cef2-03f9-468e-9926-21965dbc5b95) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-10 10:07 UTC, opbld33 commented
Docs Build status updates of commit _[5675b90](https://github.com/MicrosoftDocs/msteams-docs/commits/5675b907b3c25985cc53b73ff8e04369beeb26c5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-manifest-preview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) | [Details](#user-content-2c7cdd9ef78ab71d670c5049f92895b0-f2440e6e)
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/create-project.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/create-project.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/codelens.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/codelens.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/hover.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/hover.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/select-environment.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/select-environment.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/validate-manifest.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/validate-manifest.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/validate-manifest.png?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-multi-env.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-multi-env?branch=pr-en-us-5837) |

<a id="2c7cdd9ef78ab71d670c5049f92895b0-f2440e6e"></a>
### [msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-manifest-preview.md)
 - **Line 46, Column 1**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '~/assets/images/teams-toolkit-v2/teams toolkit fundamentals/validate-manifest'.`````
 - **Line 144, Column 4**: **[Warning: code-block-unclosed - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202205101006188615-5837/BuildReport?accessString=d790bb2cdb6fa7339d98a305284fdccf34d116d388c073c779983426b4418db0).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-10 10:07 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/5675b907b3c25985cc53b73ff8e04369beeb26c5/msteams-platform%2FTOC.yml) | 98 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f5adaf46-0439-4dac-9b01-a7c9b9c68bf1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5675b907b3c25985cc53b73ff8e04369beeb26c5/msteams-platform%2Ftoolkit%2FTeamsFx-manifest-preview.md) | 85 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/feb07630-b86b-42c0-ace6-0c3651d0b7ce) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5675b907b3c25985cc53b73ff8e04369beeb26c5/msteams-platform%2Ftoolkit%2FTeamsFx-multi-env.md) | 90 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/280efd5d-e483-41ea-99d7-f1bbe90d05ca) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-10 10:11 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/88ef28b53c74e9e71c6e5212ea5adb68083e19c5/msteams-platform%2FTOC.yml) | 98 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e6e005ec-f373-42ff-a83e-e001c982b317) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/88ef28b53c74e9e71c6e5212ea5adb68083e19c5/msteams-platform%2Ftoolkit%2FTeamsFx-manifest-preview.md) | 85 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/263866ae-f621-4da0-9e35-386cb5596a1c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/88ef28b53c74e9e71c6e5212ea5adb68083e19c5/msteams-platform%2Ftoolkit%2FTeamsFx-multi-env.md) | 90 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aa8f6834-902b-4b48-846a-469f7d688cd7) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-10 10:11 UTC, opbld33 commented
Docs Build status updates of commit _[88ef28b](https://github.com/MicrosoftDocs/msteams-docs/commits/88ef28b53c74e9e71c6e5212ea5adb68083e19c5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-manifest-preview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) | [Details](#user-content-2c7cdd9ef78ab71d670c5049f92895b0-d493492e)
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/create-project.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/create-project.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/codelens.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/codelens.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/hover.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/hover.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/select-environment.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/select-environment.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/validate.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/validate.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/validate.png?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-multi-env.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-multi-env?branch=pr-en-us-5837) |

<a id="2c7cdd9ef78ab71d670c5049f92895b0-d493492e"></a>
### [msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-manifest-preview.md)
 - **Line 46, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '~/assets/images/teams-toolkit-v2/teams toolkit fundamentals/validate'.`````
 - **Line 144, Column 1**: **[Warning: code-block-unclosed - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202205101010403379-5837/BuildReport?accessString=918a7c1525b5a0c8201e0a89b0bd3900135ada25502e1acf78182a298442fd31).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-10 10:18 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/9098ff8451bd9eec3df4b784b55e978b6de8f68d/msteams-platform%2FTOC.yml) | 98 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/95531c0c-b86b-4543-9bff-52af6353a365) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9098ff8451bd9eec3df4b784b55e978b6de8f68d/msteams-platform%2Ftoolkit%2FTeamsFx-manifest-preview.md) | 86 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f4bbf133-7b2a-436f-af0b-29ee12d49682) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9098ff8451bd9eec3df4b784b55e978b6de8f68d/msteams-platform%2Ftoolkit%2FTeamsFx-multi-env.md) | 90 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e6ac5d2d-99cf-4b07-bc30-d5b578cc1b41) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-10 10:18 UTC, opbld31 commented
Docs Build status updates of commit _[9098ff8](https://github.com/MicrosoftDocs/msteams-docs/commits/9098ff8451bd9eec3df4b784b55e978b6de8f68d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/create-project.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/create-project.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/codelens.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/codelens.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/hover.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/hover.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/select-environment.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/select-environment.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/validate.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/validate.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-manifest-preview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-multi-env.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-multi-env?branch=pr-en-us-5837) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202205101017248726-5837/BuildReport?accessString=d5e79e5cc87cd6520b900fb81b2adddbd5fd04ab07c3b132fa29882af6597579).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-11 06:39 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a0e7dc3d57923bc8781ead15521bec32b562dc69/msteams-platform%2FTOC.yml) | 98 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5f04fa7c-3085-4842-b235-03fcd014ba2a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a0e7dc3d57923bc8781ead15521bec32b562dc69/msteams-platform%2Ftoolkit%2FTeamsFx-manifest-preview.md) | 86 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6a6879c4-60bd-4b2f-9de6-7a3f5fe2697f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a0e7dc3d57923bc8781ead15521bec32b562dc69/msteams-platform%2Ftoolkit%2FTeamsFx-multi-env.md) | 90 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8c3676c5-1192-48d4-aebb-c5e81615eee1) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-11 06:40 UTC, opbld31 commented
Docs Build status updates of commit _[a0e7dc3](https://github.com/MicrosoftDocs/msteams-docs/commits/a0e7dc3d57923bc8781ead15521bec32b562dc69)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/create-project.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/create-project.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/codelens.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/codelens.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/hover.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/hover.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/select-environment.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/select-environment.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/validate.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/validate.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-manifest-preview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-multi-env.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-multi-env?branch=pr-en-us-5837) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202205110639174131-5837/BuildReport?accessString=fa148a052ec6e1c85496643883bc767053d89009c358315487f92c40148efa14).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-11 07:13 UTC, opbld31 commented
Docs Build status updates of commit _[61a16ab](https://github.com/MicrosoftDocs/msteams-docs/commits/61a16ab96cc0db3d15ee0bc5b9a74b573fc30f6c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/create-project.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/create-project.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/codelens.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/codelens.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/hover.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/hover.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/select-environment.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/select-environment.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/validate.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/validate.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-manifest-preview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-multi-env.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-multi-env?branch=pr-en-us-5837) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202205110712151710-5837/BuildReport?accessString=42fc0fab69fba8cb38adae9d8a22bed832eeb5854ca7e8f0c1bbf0bcc387efca).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-11 07:13 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/61a16ab96cc0db3d15ee0bc5b9a74b573fc30f6c/msteams-platform%2FTOC.yml) | 98 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/73ea1ecb-5ede-4e95-b452-8d42f253ce6b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/61a16ab96cc0db3d15ee0bc5b9a74b573fc30f6c/msteams-platform%2Ftoolkit%2FTeamsFx-manifest-preview.md) | 86 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ca20420c-2c24-4774-9361-07647366bf81) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/61a16ab96cc0db3d15ee0bc5b9a74b573fc30f6c/msteams-platform%2Ftoolkit%2FTeamsFx-multi-env.md) | 90 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/07a11bed-5a5d-4ab6-aeeb-a8ced4c2f42a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-11 07:33 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/030de538eb476568bfb20c9304ba88e8d672aed8/msteams-platform%2FTOC.yml) | 98 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0b8eb418-b8be-4a0a-9977-1ad38fffb819) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/030de538eb476568bfb20c9304ba88e8d672aed8/msteams-platform%2Ftoolkit%2FTeamsFx-manifest-preview.md) | 87 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/05a2b532-189d-479e-a29a-78a44f963b06) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/030de538eb476568bfb20c9304ba88e8d672aed8/msteams-platform%2Ftoolkit%2FTeamsFx-multi-env.md) | 90 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fa7eb0e2-b485-4b3f-acd2-c357d1709eb0) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-11 07:33 UTC, opbld33 commented
Docs Build status updates of commit _[030de53](https://github.com/MicrosoftDocs/msteams-docs/commits/030de538eb476568bfb20c9304ba88e8d672aed8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/create-project.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/create-project.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/codelens.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/codelens.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/hover.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/hover.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/select-environment.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/select-environment.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/select-environment.png?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/validate.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/validate.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-manifest-preview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-multi-env.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-multi-env?branch=pr-en-us-5837) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202205110733095261-5837/BuildReport?accessString=5b9692a1880ff1cc64bc4caafc0b3356f1abdb2aaa61944be3bc92792eb6b08d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-11 08:08 UTC, opbld30 commented
Docs Build status updates of commit _[f152ce6](https://github.com/MicrosoftDocs/msteams-docs/commits/f152ce6dafde56014731973845ae00fd99540b6b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/create-project.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/create-project.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/codelens.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/codelens.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/hover.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/hover.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/select-environment.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/select-environment.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/validate.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/validate.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-manifest-preview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-multi-env.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-multi-env?branch=pr-en-us-5837) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202205110807586658-5837/BuildReport?accessString=6ac3f8c757aad8f3b9419b0a48e2b62e3b95ef6ca9bc6f49a6737df65ace0c56).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-11 08:09 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/f152ce6dafde56014731973845ae00fd99540b6b/msteams-platform%2FTOC.yml) | 98 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1fc5f0cb-1833-473b-84f6-7d218e5ee17c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f152ce6dafde56014731973845ae00fd99540b6b/msteams-platform%2Ftoolkit%2FTeamsFx-manifest-preview.md) | 87 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0204304e-6ec5-4a27-8a85-0c81623972d4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f152ce6dafde56014731973845ae00fd99540b6b/msteams-platform%2Ftoolkit%2FTeamsFx-multi-env.md) | 90 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/37a8f99d-fbf6-4f0b-9271-b5c2cda52739) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-13 06:04 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/dd8dcbd58d6c72dea04d5001e11c25f77d94b001/msteams-platform%2FTOC.yml) | 98 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bbbf968f-4d67-4d6f-bbe9-66d5259ff2f5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dd8dcbd58d6c72dea04d5001e11c25f77d94b001/msteams-platform%2Ftoolkit%2FTeamsFx-manifest-preview.md) | 86 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/23b60852-03ee-4c9e-979e-22c14419effc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dd8dcbd58d6c72dea04d5001e11c25f77d94b001/msteams-platform%2Ftoolkit%2FTeamsFx-multi-env.md) | 90 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d6b5a924-5278-427f-9f9d-b59170692532) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-13 06:05 UTC, opbld33 commented
Docs Build status updates of commit _[dd8dcbd](https://github.com/MicrosoftDocs/msteams-docs/commits/dd8dcbd58d6c72dea04d5001e11c25f77d94b001)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/create-project.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/create-project.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/codelens.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/codelens.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/hover.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/hover.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/select-environment.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/select-environment.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/validate.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/validate.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-manifest-preview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-multi-env.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-multi-env?branch=pr-en-us-5837) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202205130604053690-5837/BuildReport?accessString=ceae7df32736b78dd3d90b984c1ee6ab68053f09c883dc309e23d50976492e08).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-13 07:15 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ba9e94480ba266784cd9d64dd82a296ee90f559b/msteams-platform%2FTOC.yml) | 98 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/304a43de-1b40-4e30-88b5-5f0dc818717f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ba9e94480ba266784cd9d64dd82a296ee90f559b/msteams-platform%2Ftoolkit%2FTeamsFx-manifest-preview.md) | 86 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/128ed3ae-b1a6-4c50-83f3-bd6f51e22a3d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ba9e94480ba266784cd9d64dd82a296ee90f559b/msteams-platform%2Ftoolkit%2FTeamsFx-multi-env.md) | 90 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bcec56d9-87a2-4f3f-8e51-9da73f3fda82) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-13 07:16 UTC, opbld31 commented
Docs Build status updates of commit _[ba9e944](https://github.com/MicrosoftDocs/msteams-docs/commits/ba9e94480ba266784cd9d64dd82a296ee90f559b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/create-project.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/create-project.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/codelens.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/codelens.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/deploy-command.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/deploy-command.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/deploy-manifest.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/deploy-manifest.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/hover.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/hover.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/manifest preview-1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/manifest%20preview-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/preview-23.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/preview-23.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/select-environment.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/select-environment.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/update-to-teams.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/update-to-teams.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/validate.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/validate.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-manifest-preview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-multi-env.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-multi-env?branch=pr-en-us-5837) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202205130715204645-5837/BuildReport?accessString=d4a272fe6ee2ffae9d34096a9274676efcfae941bea5f0e18cf1b1cb21533f45).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-13 07:21 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/17819865efadc28ac8c572901b216295e8ec3044/msteams-platform%2FTOC.yml) | 98 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/59ff354c-73cf-4143-8a5b-1bf457fd3f31) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/17819865efadc28ac8c572901b216295e8ec3044/msteams-platform%2Ftoolkit%2FTeamsFx-manifest-preview.md) | 86 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f62fe9d4-3149-460c-baf7-66e64991ae8c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/17819865efadc28ac8c572901b216295e8ec3044/msteams-platform%2Ftoolkit%2FTeamsFx-multi-env.md) | 90 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d2c78720-8731-46a7-bf6b-207fdaa64929) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-13 07:21 UTC, opbld32 commented
Docs Build status updates of commit _[1781986](https://github.com/MicrosoftDocs/msteams-docs/commits/17819865efadc28ac8c572901b216295e8ec3044)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/create-project.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/create-project.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/codelens.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/codelens.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/deploy-command.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/deploy-command.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/deploy-manifest.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/deploy-manifest.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/hover.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/hover.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/manifest preview-1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/manifest%20preview-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/preview-23.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/preview-23.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/select-environment.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/select-environment.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/update-to-teams.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/update-to-teams.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/validate.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/validate.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-manifest-preview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-multi-env.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-multi-env?branch=pr-en-us-5837) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202205130720579403-5837/BuildReport?accessString=af1125fe181491a320f2466084fcdf7b01890e22eb4e9cef7271aa1dc371b477).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-13 07:32 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/34155e585661e4f30319cc06ebcc1f0c4c72ef7e/msteams-platform%2FTOC.yml) | 98 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a6ae8583-0cd4-44d7-9a56-8dd1e6c3f331) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/34155e585661e4f30319cc06ebcc1f0c4c72ef7e/msteams-platform%2Ftoolkit%2FTeamsFx-manifest-preview.md) | 86 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/537e690b-9741-4eef-b1df-81a6f658739d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/34155e585661e4f30319cc06ebcc1f0c4c72ef7e/msteams-platform%2Ftoolkit%2FTeamsFx-multi-env.md) | 90 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/97e042aa-abe9-480f-beb5-6c8547cd14d8) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-13 07:32 UTC, opbld33 commented
Docs Build status updates of commit _[34155e5](https://github.com/MicrosoftDocs/msteams-docs/commits/34155e585661e4f30319cc06ebcc1f0c4c72ef7e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/create-project.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/create-project.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/codelens.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/codelens.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/deploy-command.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/deploy-command.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/deploy-manifest.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/deploy-manifest.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/hover.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/hover.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/manifest preview-1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/manifest%20preview-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/preview-23.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/preview-23.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/select-environment.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/select-environment.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/update-to-teams.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/update-to-teams.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/validate.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/validate.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-manifest-preview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-multi-env.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-multi-env?branch=pr-en-us-5837) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202205130731442217-5837/BuildReport?accessString=2bb997e0348cdb226a3aa43800e53a10733fce2fa578037ae0d29d3c3c2ba99c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-13 07:37 UTC, opbld31 commented
Docs Build status updates of commit _[bdef3b1](https://github.com/MicrosoftDocs/msteams-docs/commits/bdef3b153c5a488a5f403a3853c2b014a1b0bb3a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/create-project.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/create-project.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/codelens.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/codelens.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/deploy-command.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/deploy-command.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/deploy-manifest.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/deploy-manifest.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/hover.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/hover.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/manifest preview-1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/manifest%20preview-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/preview-23.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/preview-23.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/select-environment.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/select-environment.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/update-to-teams.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/update-to-teams.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/validate.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/validate.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-manifest-preview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-multi-env.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-multi-env?branch=pr-en-us-5837) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202205130736253299-5837/BuildReport?accessString=51851457a01dc8e376d928a28905dbebd5f92b4c0e73084d31a6d3b0bafa0b85).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-13 07:37 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/bdef3b153c5a488a5f403a3853c2b014a1b0bb3a/msteams-platform%2FTOC.yml) | 98 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4b694749-5a7e-422f-8d18-d75ce822587d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bdef3b153c5a488a5f403a3853c2b014a1b0bb3a/msteams-platform%2Ftoolkit%2FTeamsFx-manifest-preview.md) | 86 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/00f48d05-621b-47db-a84f-0a7f83114b86) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bdef3b153c5a488a5f403a3853c2b014a1b0bb3a/msteams-platform%2Ftoolkit%2FTeamsFx-multi-env.md) | 90 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/44bcfa3c-246b-49da-ab81-447b60800f9a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-13 08:04 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/8ef568c954777747366244a24c8838d72e95eed0/msteams-platform%2FTOC.yml) | 98 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/19e11c2c-be78-4532-9874-77e9b35e7d80) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8ef568c954777747366244a24c8838d72e95eed0/msteams-platform%2Ftoolkit%2FTeamsFx-manifest-preview.md) | 90 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1b5be11b-cbc2-4031-b01d-769d908565a4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8ef568c954777747366244a24c8838d72e95eed0/msteams-platform%2Ftoolkit%2FTeamsFx-multi-env.md) | 90 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d8aa39d1-89e9-4a37-939d-036117fb98d3) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-13 08:05 UTC, opbld30 commented
Docs Build status updates of commit _[8ef568c](https://github.com/MicrosoftDocs/msteams-docs/commits/8ef568c954777747366244a24c8838d72e95eed0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/create-project.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/create-project.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/codelens.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/codelens.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/deploy-command.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/deploy-command.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/deploy-manifest.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/deploy-manifest.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/hover.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/hover.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/manifest preview-1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/manifest%20preview-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/preview-23.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/preview-23.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/select-environment.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/select-environment.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/update-to-teams.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/update-to-teams.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/validate.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/validate.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-manifest-preview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-multi-env.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-multi-env?branch=pr-en-us-5837) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202205130804225149-5837/BuildReport?accessString=7b3981d52a3de0e378f0a80172b593ad03088a74e2828cc1c64e2293b2dda115).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-13 08:17 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/df449b3138c8b1bcfad71a3b2f5b6aae0bfc3e91/msteams-platform%2FTOC.yml) | 98 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0fe67b08-ecf5-4b27-9017-064d16dcfd1c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/df449b3138c8b1bcfad71a3b2f5b6aae0bfc3e91/msteams-platform%2Ftoolkit%2FTeamsFx-manifest-preview.md) | 90 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b69de89b-7456-4f68-8519-ed091fc60910) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/df449b3138c8b1bcfad71a3b2f5b6aae0bfc3e91/msteams-platform%2Ftoolkit%2FTeamsFx-multi-env.md) | 90 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8b613b37-3629-442d-a3c6-cb4af6c54f88) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-13 08:17 UTC, opbld32 commented
Docs Build status updates of commit _[df449b3](https://github.com/MicrosoftDocs/msteams-docs/commits/df449b3138c8b1bcfad71a3b2f5b6aae0bfc3e91)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/create-project.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/create-project.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/codelens.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/codelens.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/deploy-command.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/deploy-command.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/deploy-manifest.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/deploy-manifest.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/hover.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/hover.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/manifest preview-1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/manifest%20preview-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/preview-23.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/preview-23.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/select-environment.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/select-environment.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/update-to-teams.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/update-to-teams.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/validate.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/validate.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-manifest-preview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-multi-env.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-multi-env?branch=pr-en-us-5837) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202205130816481002-5837/BuildReport?accessString=b7a28abdce29854c75ceea2361999ee6538d51ea15b108fd9355a1e626f230d2).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-13 09:16 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/baa55edce1855c7367cf660b7c9eb8fef177b880/msteams-platform%2FTOC.yml) | 98 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1ced6b5b-dec9-4ddb-bd25-33c2d4786231) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/baa55edce1855c7367cf660b7c9eb8fef177b880/msteams-platform%2Ftoolkit%2FTeamsFx-manifest-preview.md) | 90 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/601b737c-26fa-4060-aeaf-88a2bf608203) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/baa55edce1855c7367cf660b7c9eb8fef177b880/msteams-platform%2Ftoolkit%2FTeamsFx-multi-env.md) | 90 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/102a0c03-597c-4f2b-b296-442e27c30389) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-13 09:17 UTC, opbld32 commented
Docs Build status updates of commit _[baa55ed](https://github.com/MicrosoftDocs/msteams-docs/commits/baa55edce1855c7367cf660b7c9eb8fef177b880)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/create-project.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/create-project.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/codelens.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/codelens.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/deploy-command.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/deploy-command.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/deploy-manifest.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/deploy-manifest.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/hover.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/hover.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/manifest preview-1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/manifest%20preview-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/preview-23.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/preview-23.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/select-environment.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/select-environment.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/update-to-teams.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/update-to-teams.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/validate.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/validate.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-manifest-preview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-multi-env.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-multi-env?branch=pr-en-us-5837) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202205130916148794-5837/BuildReport?accessString=2209317f4056a5a0d45dc42a1ac0beb3cb2497f57d2a43e90636268839704d53).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-13 09:54 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/094ffc6c77e7648c54e9ceb596cecb29e88f1adc/msteams-platform%2FTOC.yml) | 98 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9acdad24-477f-4364-9f31-74467e1a7f9d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/094ffc6c77e7648c54e9ceb596cecb29e88f1adc/msteams-platform%2Ftoolkit%2FTeamsFx-manifest-preview.md) | 89 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dd803375-39c6-4adf-bd59-09cb30ae8788) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/094ffc6c77e7648c54e9ceb596cecb29e88f1adc/msteams-platform%2Ftoolkit%2FTeamsFx-multi-env.md) | 90 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/da24145a-293c-42e3-a178-dcc362cbc21f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-13 09:55 UTC, opbld33 commented
Docs Build status updates of commit _[094ffc6](https://github.com/MicrosoftDocs/msteams-docs/commits/094ffc6c77e7648c54e9ceb596cecb29e88f1adc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/create-project.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/create-project.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/codelens.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/codelens.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/deploy-command.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/deploy-command.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/deploy-manifest.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/deploy-manifest.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/hover.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/hover.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/manifest preview-1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/manifest%20preview-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/preview-23.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/preview-23.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/select-environment.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/select-environment.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/update-to-teams.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/update-to-teams.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/validate.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/validate.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-manifest-preview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-multi-env.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-multi-env?branch=pr-en-us-5837) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202205130954118056-5837/BuildReport?accessString=e904f69aa141190d1bd47e375ec8296b9eb19f50c28d25a9dc3a0f358b164f79).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-13 10:38 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c751dcdaf02a69a39eb6d5348bef4a68de3254b7/msteams-platform%2FTOC.yml) | 98 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a23159f6-c8c6-4e3a-9116-40056c7e1390) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c751dcdaf02a69a39eb6d5348bef4a68de3254b7/msteams-platform%2Ftoolkit%2FTeamsFx-manifest-preview.md) | 89 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a30232b6-3b24-4b75-951b-7d72c37f576e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c751dcdaf02a69a39eb6d5348bef4a68de3254b7/msteams-platform%2Ftoolkit%2FTeamsFx-multi-env.md) | 90 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f1ab7b42-9c88-4067-94d4-9b00dd1c3999) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-13 10:38 UTC, opbld30 commented
Docs Build status updates of commit _[c751dcd](https://github.com/MicrosoftDocs/msteams-docs/commits/c751dcdaf02a69a39eb6d5348bef4a68de3254b7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/create-project.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/create-project.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/codelens.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/codelens.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/deploy-command.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/deploy-command.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/deploy-manifest.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/deploy-manifest.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/hover.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/hover.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/manifest preview-1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/manifest%20preview-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/preview-23.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/preview-23.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/select-environment.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/select-environment.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/update-to-teams.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/update-to-teams.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/validate.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/validate.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-manifest-preview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-multi-env.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-multi-env?branch=pr-en-us-5837) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202205131037342301-5837/BuildReport?accessString=7a90a04481fda89043ce72466b732590b481aa39e916c6d2c17f36f0d70b0b24).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-13 10:44 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/f5a7f9ffdc5d7d8b164f72056ef3122c633310c8/msteams-platform%2FTOC.yml) | 98 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3c5948b5-71c7-4ede-bc77-28390f330842) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f5a7f9ffdc5d7d8b164f72056ef3122c633310c8/msteams-platform%2Ftoolkit%2FTeamsFx-manifest-preview.md) | 89 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2a55766c-ae95-4134-90c5-ac4a3711c0c6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f5a7f9ffdc5d7d8b164f72056ef3122c633310c8/msteams-platform%2Ftoolkit%2FTeamsFx-multi-env.md) | 90 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7f01b037-0cc2-4e3c-acb4-df5ff3d92f55) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-13 10:44 UTC, opbld31 commented
Docs Build status updates of commit _[f5a7f9f](https://github.com/MicrosoftDocs/msteams-docs/commits/f5a7f9ffdc5d7d8b164f72056ef3122c633310c8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/create-project.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/create-project.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/codelens.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/codelens.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/deploy-command.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/deploy-command.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/deploy-manifest.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/deploy-manifest.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/hover.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/hover.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/manifest preview-1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/manifest%20preview-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/preview-23.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/preview-23.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/select-environment.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/select-environment.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/update-to-teams.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/update-to-teams.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/validate.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/validate.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-manifest-preview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-multi-env.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-multi-env?branch=pr-en-us-5837) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202205131043454230-5837/BuildReport?accessString=295789842d4b376c4657ce96416a46ca2ecec8f7957eabd5a05b9a2526a828f3).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-13 10:50 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/5955e350d11c308324ae8231cd4fac97eb5a63ff/msteams-platform%2FTOC.yml) | 98 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0986c9bb-99ee-4cf7-a353-f1351c77edf6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5955e350d11c308324ae8231cd4fac97eb5a63ff/msteams-platform%2Ftoolkit%2FTeamsFx-manifest-preview.md) | 89 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0a0f7af1-2e14-446b-84cb-2f1428ca94dd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5955e350d11c308324ae8231cd4fac97eb5a63ff/msteams-platform%2Ftoolkit%2FTeamsFx-multi-env.md) | 90 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/01c66210-f61a-42df-8dc7-86f47efe1750) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-13 10:50 UTC, opbld31 commented
Docs Build status updates of commit _[5955e35](https://github.com/MicrosoftDocs/msteams-docs/commits/5955e350d11c308324ae8231cd4fac97eb5a63ff)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/create-project.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/create-project.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/codelens.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/codelens.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/deploy-command.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/deploy-command.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/deploy-manifest.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/deploy-manifest.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/hover.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/hover.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/manifest preview -3.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/manifest%20preview%20-3.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/manifest preview-1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/manifest%20preview-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/preview-23.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/preview-23.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/select-environment.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/select-environment.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/update-to-teams.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/update-to-teams.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/validate.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/validate.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-manifest-preview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-multi-env.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-multi-env?branch=pr-en-us-5837) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202205131049429988-5837/BuildReport?accessString=691d90e81eac2160d6fa7f99af2140d6d95e9ca2a9de4677cf52e6d5a6b793e5).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-13 10:55 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/f7f6fd44842a533753d232aab23f32458472be59/msteams-platform%2FTOC.yml) | 98 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dcaf25ab-434c-46e3-b70d-9583122d89cf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f7f6fd44842a533753d232aab23f32458472be59/msteams-platform%2Ftoolkit%2FTeamsFx-manifest-preview.md) | 89 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2bfd87a0-032c-4001-8f3d-242a368f3598) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f7f6fd44842a533753d232aab23f32458472be59/msteams-platform%2Ftoolkit%2FTeamsFx-multi-env.md) | 90 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7461518c-2df7-463b-b405-9cf1f777dc25) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-13 10:55 UTC, opbld31 commented
Docs Build status updates of commit _[f7f6fd4](https://github.com/MicrosoftDocs/msteams-docs/commits/f7f6fd44842a533753d232aab23f32458472be59)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/create-project.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/create-project.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/codelens.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/codelens.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/deploy-command.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/deploy-command.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/deploy-manifest.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/deploy-manifest.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/hover.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/hover.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/manifest preview -3.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/manifest%20preview%20-3.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/manifest preview-1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/manifest%20preview-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/preview-23.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/preview-23.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/select-environment.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/select-environment.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/update-to-teams.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/update-to-teams.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/validate.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/validate.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-manifest-preview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-multi-env.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-multi-env?branch=pr-en-us-5837) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202205131054585166-5837/BuildReport?accessString=212802b9381e7a729493ac11dfdfd94d5aa1efe5b9bdeb0508558a8c16b5d4dc).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-13 11:17 UTC, opbld32 commented
Docs Build status updates of commit _[63f74b9](https://github.com/MicrosoftDocs/msteams-docs/commits/63f74b94e2b6ff5bf688d44e581bbecb4d91ddca)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/create-project.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/create-project.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/codelens.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/codelens.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/deploy-command.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/deploy-command.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/deploy-manifest.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/deploy-manifest.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/hover.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/hover.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/manifest preview -3.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/manifest%20preview%20-3.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/manifest preview-1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/manifest%20preview-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/pre.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/pre.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/preview-23.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/preview-23.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/select-environment.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/select-environment.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/update-to-teams.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/update-to-teams.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/validate.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/validate.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-manifest-preview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-multi-env.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-multi-env?branch=pr-en-us-5837) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202205131116337737-5837/BuildReport?accessString=b6fb923821f3f69d85d386d7dd26f7020ce20ce472e1abf4b383092438be7d78).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-13 11:17 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/63f74b94e2b6ff5bf688d44e581bbecb4d91ddca/msteams-platform%2FTOC.yml) | 98 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f6392158-be43-4bd1-aad0-8c7560d9fce8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/63f74b94e2b6ff5bf688d44e581bbecb4d91ddca/msteams-platform%2Ftoolkit%2FTeamsFx-manifest-preview.md) | 89 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/872ed2f2-435d-42d5-8319-f47ecd77fe50) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/63f74b94e2b6ff5bf688d44e581bbecb4d91ddca/msteams-platform%2Ftoolkit%2FTeamsFx-multi-env.md) | 90 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ff589179-3eac-4263-9a39-4b340934628c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-13 11:22 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/bdbaadefa016afc2be429ee193ed1930f0c94370/msteams-platform%2FTOC.yml) | 98 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a8bac703-c17b-4e9a-9919-45026bb2c2a3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bdbaadefa016afc2be429ee193ed1930f0c94370/msteams-platform%2Ftoolkit%2FTeamsFx-manifest-preview.md) | 89 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b1ea07c0-21d8-4f7e-87c1-506e7ff84f1b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bdbaadefa016afc2be429ee193ed1930f0c94370/msteams-platform%2Ftoolkit%2FTeamsFx-multi-env.md) | 90 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/483fa9ad-d4a5-4ad5-8016-1fc2bbdacf72) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-13 11:23 UTC, opbld31 commented
Docs Build status updates of commit _[bdbaade](https://github.com/MicrosoftDocs/msteams-docs/commits/bdbaadefa016afc2be429ee193ed1930f0c94370)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/create-project.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/create-project.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/codelens.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/codelens.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/deploy-command.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/deploy-command.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/deploy-manifest.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/deploy-manifest.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/hover.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/hover.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/manifest preview -3.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/manifest%20preview%20-3.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/manifest preview-1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/manifest%20preview-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/pre.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/pre.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/preview-23.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/preview-23.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/select-environment.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/select-environment.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/update-to-teams.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/update-to-teams.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/validate.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/validate.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-manifest-preview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-multi-env.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-multi-env?branch=pr-en-us-5837) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202205131122254921-5837/BuildReport?accessString=b77b6df0e5520396161eab140eb7e5310f9d8f1312b08605268c22f4a192fa19).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-13 11:34 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/b78ba8d979f09255aea6b54a25b14c483386fffd/msteams-platform%2FTOC.yml) | 98 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/509a65f8-25bb-4637-9f65-e0095d24c59f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b78ba8d979f09255aea6b54a25b14c483386fffd/msteams-platform%2Ftoolkit%2FTeamsFx-manifest-preview.md) | 89 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5de6f0bf-ea83-497b-acda-1e42883b359a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b78ba8d979f09255aea6b54a25b14c483386fffd/msteams-platform%2Ftoolkit%2FTeamsFx-multi-env.md) | 90 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5eec6258-faba-4052-8e06-46a17667065b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-13 11:34 UTC, opbld30 commented
Docs Build status updates of commit _[b78ba8d](https://github.com/MicrosoftDocs/msteams-docs/commits/b78ba8d979f09255aea6b54a25b14c483386fffd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/create-project.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/create-project.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/codelens.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/codelens.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/deploy-command.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/deploy-command.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/deploy-manifest.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/deploy-manifest.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/hover.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/hover.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/manifest preview -3.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/manifest%20preview%20-3.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/manifest preview-1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/manifest%20preview-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/pre.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/pre.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/preview-23.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/preview-23.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/select-environment.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/select-environment.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/update-to-teams.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/update-to-teams.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/validate.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/validate.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-manifest-preview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-multi-env.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-multi-env?branch=pr-en-us-5837) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202205131133572600-5837/BuildReport?accessString=73cbeabff677dd5d3865ecc4adb184041fd7045e55c20fd683cc95efb4481dee).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-13 11:37 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/af422f3f1ec0e9ca12d98df320dcf9c8eb52153e/msteams-platform%2FTOC.yml) | 98 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a016d98c-6f92-49ac-8ae5-d32f0f59e161) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/af422f3f1ec0e9ca12d98df320dcf9c8eb52153e/msteams-platform%2Ftoolkit%2FTeamsFx-manifest-preview.md) | 89 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/34c68b9b-11a9-4c30-bac7-eeee2a490692) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/af422f3f1ec0e9ca12d98df320dcf9c8eb52153e/msteams-platform%2Ftoolkit%2FTeamsFx-multi-env.md) | 90 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8e8918cd-035c-4133-bfdf-a6bfb2b5b12e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-13 11:38 UTC, opbld30 commented
Docs Build status updates of commit _[af422f3](https://github.com/MicrosoftDocs/msteams-docs/commits/af422f3f1ec0e9ca12d98df320dcf9c8eb52153e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-manifest-preview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) | [Details](#user-content-2c7cdd9ef78ab71d670c5049f92895b0-eb1ead71)
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/create-project.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/create-project.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/codelens.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/codelens.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/deploy-command.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/deploy-command.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/deploy-manifest.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/deploy-manifest.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/hover.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/hover.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/manifest preview -3.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/manifest%20preview%20-3.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/manifest preview-1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/manifest%20preview-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/pre.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/pre.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/preview-23.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/preview-23.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/select-environment.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/select-environment.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/update-to-teams.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/update-to-teams.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/validate.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/validate.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-multi-env.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-multi-env?branch=pr-en-us-5837) |

<a id="2c7cdd9ef78ab71d670c5049f92895b0-eb1ead71"></a>
### [msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-manifest-preview.md)
 - **Line 43, Column 1**: **[Warning: code-block-indented - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-indented?branch=main)]** `````Indented code blocks aren't allowed. Use a Markdown code block surrounded by triple backticks (```).`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202205131137115339-5837/BuildReport?accessString=15fb9dac4c5dded516dee4c3d9656a7aa8a3b64a4da6fe514970392f64ee4a5c).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updat [...]

2022-05-13 11:41 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/62d53d5e44c800a2c0f95316f9503742c128d418/msteams-platform%2FTOC.yml) | 98 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/761cad14-5ffd-46fc-8358-a8edd20edf6a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/62d53d5e44c800a2c0f95316f9503742c128d418/msteams-platform%2Ftoolkit%2FTeamsFx-manifest-preview.md) | 89 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7e63792d-029f-41a1-9070-a92009c1e366) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/62d53d5e44c800a2c0f95316f9503742c128d418/msteams-platform%2Ftoolkit%2FTeamsFx-multi-env.md) | 90 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a3a6b4af-6a08-4132-9462-c2be8e58a4c4) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-13 11:41 UTC, opbld32 commented
Docs Build status updates of commit _[62d53d5](https://github.com/MicrosoftDocs/msteams-docs/commits/62d53d5e44c800a2c0f95316f9503742c128d418)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/create-project.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/create-project.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/codelens.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/codelens.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/deploy-command.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/deploy-command.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/deploy-manifest.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/deploy-manifest.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/hover.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/hover.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/manifest preview -3.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/manifest%20preview%20-3.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/manifest preview-1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/manifest%20preview-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/pre.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/pre.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/preview-23.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/preview-23.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/select-environment.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/select-environment.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/update-to-teams.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/update-to-teams.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/validate.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/validate.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-manifest-preview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-multi-env.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-multi-env?branch=pr-en-us-5837) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202205131141019309-5837/BuildReport?accessString=74f3f11e1db6b154aca6834941dc057ae7c42d2bf4bdf1cded37f56bbcfd66b3).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-13 11:46 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/b7a5c350966ae49d81fce83a6c19bb98053ece04/msteams-platform%2FTOC.yml) | 98 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/91a5e945-020a-48bc-aa06-05a162ecd185) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b7a5c350966ae49d81fce83a6c19bb98053ece04/msteams-platform%2Ftoolkit%2FTeamsFx-manifest-preview.md) | 89 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c80f41d5-976f-46a8-a5a4-881d82c0810c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b7a5c350966ae49d81fce83a6c19bb98053ece04/msteams-platform%2Ftoolkit%2FTeamsFx-multi-env.md) | 90 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d2f999f3-494d-4871-86fb-0ef81c567475) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-13 11:46 UTC, opbld30 commented
Docs Build status updates of commit _[b7a5c35](https://github.com/MicrosoftDocs/msteams-docs/commits/b7a5c350966ae49d81fce83a6c19bb98053ece04)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/create-project.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/create-project.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/codelens.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/codelens.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/deploy-command.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/deploy-command.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/deploy-manifest.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/deploy-manifest.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/hover.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/hover.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/manifest preview -3.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/manifest%20preview%20-3.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/manifest preview-1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/manifest%20preview-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/pre.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/pre.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/preview-23.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/preview-23.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/select-environment.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/select-environment.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/update-to-teams.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/update-to-teams.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/validate.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/validate.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-manifest-preview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-multi-env.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-multi-env?branch=pr-en-us-5837) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202205131145462579-5837/BuildReport?accessString=e37a706adaceed95d46d1c65e1148bee0f9f9c0cf8cd1383580d4cbc239f4bf3).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-13 11:50 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c1586f3459ae8f62294782fce278ebdf061aabd2/msteams-platform%2FTOC.yml) | 98 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0657b836-9525-495c-9e28-61711f424440) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c1586f3459ae8f62294782fce278ebdf061aabd2/msteams-platform%2Ftoolkit%2FTeamsFx-manifest-preview.md) | 89 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bd365f24-7855-4d35-97cc-8be0f5fc86a4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c1586f3459ae8f62294782fce278ebdf061aabd2/msteams-platform%2Ftoolkit%2FTeamsFx-multi-env.md) | 90 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/13e85af1-0e20-4c73-a514-0a08a5b3409e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-13 11:50 UTC, opbld30 commented
Docs Build status updates of commit _[c1586f3](https://github.com/MicrosoftDocs/msteams-docs/commits/c1586f3459ae8f62294782fce278ebdf061aabd2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/create-project.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/create-project.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/codelens.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/codelens.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/deploy-command.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/deploy-command.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/deploy-manifest.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/deploy-manifest.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/hover.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/hover.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/manifest preview -3.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/manifest%20preview%20-3.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/manifest preview-1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/manifest%20preview-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/pre.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/pre.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/preview-23.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/preview-23.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/select-environment.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/select-environment.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/update-to-teams.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/update-to-teams.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/validate.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/validate.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-manifest-preview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-multi-env.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-multi-env?branch=pr-en-us-5837) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202205131149465935-5837/BuildReport?accessString=ec3b105ba2584de1e1e837be994b16aa0b8589d1358c8da9303eaf8172e52100).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-17 06:45 UTC, opbld33 commented
Docs Build status updates of commit _[ad3151a](https://github.com/MicrosoftDocs/msteams-docs/commits/ad3151af6f81d1230e96acf6bffdd413e4d37c8d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/create-project.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/create-project.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/codelens.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/codelens.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/deploy-command.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/deploy-command.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/deploy-manifest.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/deploy-manifest.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/hover.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/hover.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/manifest preview -3.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/manifest%20preview%20-3.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/manifest preview-1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/manifest%20preview-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/pre.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/pre.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/preview-23.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/preview-23.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/select-environment.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/select-environment.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/update-to-teams.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/update-to-teams.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/validate.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/validate.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-manifest-preview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-multi-env.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-multi-env?branch=pr-en-us-5837) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202205170644155240-5837/BuildReport?accessString=8397011e57d72124b5c0b17416b67a3987fd949c2a4107207052fef762f65113).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-17 06:46 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ad3151af6f81d1230e96acf6bffdd413e4d37c8d/msteams-platform%2FTOC.yml) | 98 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/744afa4f-b19a-452a-82e4-dff0238171cf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ad3151af6f81d1230e96acf6bffdd413e4d37c8d/msteams-platform%2Ftoolkit%2FTeamsFx-manifest-preview.md) | 89 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6acf0c46-ae43-4104-aec0-bea599a1d169) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ad3151af6f81d1230e96acf6bffdd413e4d37c8d/msteams-platform%2Ftoolkit%2FTeamsFx-multi-env.md) | 90 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b83dcdd3-613a-4ce1-a06d-e2a84559492d) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-17 07:11 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/dbad6945f1fec6e9ca878e1ffef7e7c47709def2/msteams-platform%2FTOC.yml) | 98 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9d752d66-c8db-4a52-9e33-e9b856c2bd27) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dbad6945f1fec6e9ca878e1ffef7e7c47709def2/msteams-platform%2Ftoolkit%2FTeamsFx-manifest-preview.md) | 89 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ec43e59e-d992-4761-936f-2c46a1563409) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dbad6945f1fec6e9ca878e1ffef7e7c47709def2/msteams-platform%2Ftoolkit%2FTeamsFx-multi-env.md) | 90 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a18df9e4-a9dc-47e7-9ee5-56f3f935a300) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-17 07:12 UTC, opbld30 commented
Docs Build status updates of commit _[dbad694](https://github.com/MicrosoftDocs/msteams-docs/commits/dbad6945f1fec6e9ca878e1ffef7e7c47709def2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/create-project.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/create-project.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/codelens.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/codelens.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/deploy-command.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/deploy-command.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/deploy-manifest.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/deploy-manifest.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/hover.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/hover.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/manifest preview -3.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/manifest%20preview%20-3.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/manifest preview-1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/manifest%20preview-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/pre.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/pre.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/preview-23.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/preview-23.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/select-environment.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/select-environment.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/update-to-teams.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/update-to-teams.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/validate.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/validate.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-manifest-preview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-multi-env.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-multi-env?branch=pr-en-us-5837) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202205170711167201-5837/BuildReport?accessString=8f404482ea74c0c11d389fdebb740964320a55faf5ee2acdf3ab44cae7f54bc3).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-17 11:31 UTC, zhenjiao-ms requested changes

2022-05-17 11:31 UTC, zhenjiao-ms commented on msteams-platform/toolkit/TeamsFx-manifest-preview.md
> +* Install the [Teams Toolkit version 3.8.1](https://github.com/OfficeDev/TeamsFx/releases/tag/vscode-extension-3.8.1-beta.adb483893.0).
Should be 4.0.0

2022-05-18 05:44 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/12c3b2372e1b176baf2fba602c595523cf4cb5f1/msteams-platform%2FTOC.yml) | 98 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e220ea60-642d-46e8-819a-9ff6a986465d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/12c3b2372e1b176baf2fba602c595523cf4cb5f1/msteams-platform%2Ftoolkit%2FTeamsFx-manifest-preview.md) | 89 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0ab32c99-c031-484f-8a14-3592a806be8e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/12c3b2372e1b176baf2fba602c595523cf4cb5f1/msteams-platform%2Ftoolkit%2FTeamsFx-multi-env.md) | 90 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/879c0ec1-12d7-4ac7-a4a9-c814621027ed) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-18 05:44 UTC, opbld33 commented
Docs Build status updates of commit _[12c3b23](https://github.com/MicrosoftDocs/msteams-docs/commits/12c3b2372e1b176baf2fba602c595523cf4cb5f1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/create-project.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/create-project.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/codelens.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/codelens.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/deploy-command.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/deploy-command.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/deploy-manifest.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/deploy-manifest.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/hover.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/hover.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/manifest preview -3.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/manifest%20preview%20-3.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/manifest preview-1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/manifest%20preview-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/pre.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/pre.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/preview-23.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/preview-23.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/select-environment.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/select-environment.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/update-to-teams.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/update-to-teams.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/validate.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/validate.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-manifest-preview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-preview?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-multi-env.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-multi-env?branch=pr-en-us-5837) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202205180543455171-5837/BuildReport?accessString=366ee89890d509f252dc0b0df68f835e6774bc205caf5b7cfb49b349b3687900).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-19 11:34 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/660bffb8bf9e8ea2fdfd156dc69ef16fb29ca871/msteams-platform%2FTOC.yml) | 98 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/041637ca-6adf-4dbc-8532-60bae1202294) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/Preview and customize Teams app manifest.md](https://github.com/MicrosoftDocs/msteams-docs/blob/660bffb8bf9e8ea2fdfd156dc69ef16fb29ca871/msteams-platform%2Ftoolkit%2FPreview%20and%20customize%20Teams%20app%20manifest.md) | 89 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8e72ffc6-4d4a-472d-88dc-9020342c00d1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/660bffb8bf9e8ea2fdfd156dc69ef16fb29ca871/msteams-platform%2Ftoolkit%2FTeamsFx-multi-env.md) | 90 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2514cab7-d6f7-42a6-abdb-949fa86a20b2) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-19 11:34 UTC, opbld33 commented
Docs Build status updates of commit _[660bffb](https://github.com/MicrosoftDocs/msteams-docs/commits/660bffb8bf9e8ea2fdfd156dc69ef16fb29ca871)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-multi-env.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-multi-env?branch=pr-en-us-5837) | [Details](#user-content-12216123ba329c9ca6700f9d931f42c2-e18878d0)
[msteams-platform/toolkit/TeamsFx-manifest-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-manifest-customization.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-customization?branch=pr-en-us-5837) | [Details](#user-content-4b79caac002a5471906c80c4179f299c-e18878d0)
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/preview%20and%20customize%20teams%20app%20manifest?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/create-project.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/create-project.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/codelens.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/codelens.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/preview%20and%20customize%20teams%20app%20manifest?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/deploy-command.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/deploy-command.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/preview%20and%20customize%20teams%20app%20manifest?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/deploy-manifest.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/deploy-manifest.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/preview%20and%20customize%20teams%20app%20manifest?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/hover.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/hover.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/preview%20and%20customize%20teams%20app%20manifest?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/manifest preview -3.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/manifest%20preview%20-3.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/preview%20and%20customize%20teams%20app%20manifest?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/manifest preview-1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/manifest%20preview-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/preview%20and%20customize%20teams%20app%20manifest?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/pre.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/pre.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/preview%20and%20customize%20teams%20app%20manifest?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/preview-23.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/preview-23.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/preview%20and%20customize%20teams%20app%20manifest?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/select-environment.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/select-environment.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/preview%20and%20customize%20teams%20app%20manifest?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/update-to-teams.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/update-to-teams.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/preview%20and%20customize%20teams%20app%20manifest?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/validate.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/validate.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/preview%20and%20customize%20teams%20app%20manifest?branch=pr-en-us-5837) |
[msteams-platform/toolkit/Preview and customize Teams app manifest.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/Preview and customize Teams app manifest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/preview%20and%20customize%20teams%20app%20manifest?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/toolkit/TeamsFx-manifest-preview.md) | :white_check_mark:Succeeded | |

<a id="12216123ba329c9ca6700f9d931f42c2-e18878d0"></a>
### [msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-multi-env.md)
 - **Line 80, Column 145**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'TeamsFx-manifest-preview.md'.`````

<a id="4b79caac002a5471906c80c4179f299c-e18878d0"></a>
### [msteams-platform/toolkit/TeamsFx-manifest-custo [...]

2022-05-19 11:39 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e593893753c6bdd527236e0c2bafe0efe626ce48/msteams-platform%2FTOC.yml) | 98 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/068cf839-505f-4268-b856-dac8f1a27d91) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/Preview and customize Teams app manifest.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e593893753c6bdd527236e0c2bafe0efe626ce48/msteams-platform%2Ftoolkit%2FPreview%20and%20customize%20Teams%20app%20manifest.md) | 89 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/06f0521c-ba27-4fce-9d46-250e24384104) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-manifest-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e593893753c6bdd527236e0c2bafe0efe626ce48/msteams-platform%2Ftoolkit%2FTeamsFx-manifest-customization.md) | 88 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5179bd2a-3602-4bdb-b601-ace64e1422c2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e593893753c6bdd527236e0c2bafe0efe626ce48/msteams-platform%2Ftoolkit%2FTeamsFx-multi-env.md) | 90 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a1bcfeea-ce99-4504-ac5c-0a420f296864) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-19 11:39 UTC, opbld33 commented
Docs Build status updates of commit _[e593893](https://github.com/MicrosoftDocs/msteams-docs/commits/e593893753c6bdd527236e0c2bafe0efe626ce48)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/preview%20and%20customize%20teams%20app%20manifest?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/create-project.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/create-project.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/codelens.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/codelens.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/preview%20and%20customize%20teams%20app%20manifest?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/deploy-command.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/deploy-command.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/preview%20and%20customize%20teams%20app%20manifest?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/deploy-manifest.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/deploy-manifest.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/preview%20and%20customize%20teams%20app%20manifest?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/hover.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/hover.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/preview%20and%20customize%20teams%20app%20manifest?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/manifest preview -3.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/manifest%20preview%20-3.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/preview%20and%20customize%20teams%20app%20manifest?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/manifest preview-1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/manifest%20preview-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/preview%20and%20customize%20teams%20app%20manifest?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/pre.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/pre.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/preview%20and%20customize%20teams%20app%20manifest?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/preview-23.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/preview-23.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/preview%20and%20customize%20teams%20app%20manifest?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/select-environment.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/select-environment.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/preview%20and%20customize%20teams%20app%20manifest?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/update-to-teams.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/update-to-teams.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/preview%20and%20customize%20teams%20app%20manifest?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/validate.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/validate.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/preview%20and%20customize%20teams%20app%20manifest?branch=pr-en-us-5837) |
[msteams-platform/toolkit/Preview and customize Teams app manifest.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/Preview and customize Teams app manifest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/preview%20and%20customize%20teams%20app%20manifest?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-manifest-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-manifest-customization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-customization?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/toolkit/TeamsFx-manifest-preview.md) | :white_check_mark:Succeeded | |
[msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-multi-env.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-multi-env?branch=pr-en-us-5837) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202205191138348892-5837/BuildReport?accessString=07ec727cf4b5ee5185c9a3c692b0b4cd3744b9362dc646cdcbd05cfcafc2cf46).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/h [...]

2022-05-19 11:43 UTC, opbld33 commented
Docs Build status updates of commit _[bc5d521](https://github.com/MicrosoftDocs/msteams-docs/commits/bc5d521b6b926bc8da30931d5b5444e0b34d9383)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/preview%20and%20customize%20teams%20app%20manifest?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/create-project.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/create-project.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/codelens.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/codelens.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/preview%20and%20customize%20teams%20app%20manifest?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/deploy-command.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/deploy-command.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/preview%20and%20customize%20teams%20app%20manifest?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/deploy-manifest.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/deploy-manifest.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/preview%20and%20customize%20teams%20app%20manifest?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/hover.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/hover.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/preview%20and%20customize%20teams%20app%20manifest?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/manifest preview -3.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/manifest%20preview%20-3.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/preview%20and%20customize%20teams%20app%20manifest?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/manifest preview-1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/manifest%20preview-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/preview%20and%20customize%20teams%20app%20manifest?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/pre.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/pre.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/preview%20and%20customize%20teams%20app%20manifest?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/preview-23.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/preview-23.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/preview%20and%20customize%20teams%20app%20manifest?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/select-environment.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/select-environment.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/preview%20and%20customize%20teams%20app%20manifest?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/update-to-teams.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/update-to-teams.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/preview%20and%20customize%20teams%20app%20manifest?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/validate.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/validate.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/preview%20and%20customize%20teams%20app%20manifest?branch=pr-en-us-5837) |
[msteams-platform/toolkit/Preview and customize Teams app manifest.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/Preview and customize Teams app manifest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/preview%20and%20customize%20teams%20app%20manifest?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-manifest-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-manifest-customization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-customization?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/toolkit/TeamsFx-manifest-preview.md) | :white_check_mark:Succeeded | |
[msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-multi-env.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-multi-env?branch=pr-en-us-5837) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202205191142400295-5837/BuildReport?accessString=5ae4ae994dbd917027f7161dd4947a03da29d37eae3505e8405fc6d5911bab2d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/h [...]

2022-05-19 11:43 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/bc5d521b6b926bc8da30931d5b5444e0b34d9383/msteams-platform%2FTOC.yml) | 98 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fef2f39c-c31d-4c8b-a71e-b1543adefcd4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/Preview and customize Teams app manifest.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bc5d521b6b926bc8da30931d5b5444e0b34d9383/msteams-platform%2Ftoolkit%2FPreview%20and%20customize%20Teams%20app%20manifest.md) | 89 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e46221f6-4258-423c-ab4d-6780f0041121) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-manifest-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bc5d521b6b926bc8da30931d5b5444e0b34d9383/msteams-platform%2Ftoolkit%2FTeamsFx-manifest-customization.md) | 88 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/746e6fe2-5065-4213-9cbc-e1be71efa6b3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bc5d521b6b926bc8da30931d5b5444e0b34d9383/msteams-platform%2Ftoolkit%2FTeamsFx-multi-env.md) | 90 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f5d7cc91-fe63-4fd1-acb5-7b6f24568c2a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-19 11:45 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/6083d75627b0f93988a9fb809e7f53600b124911/msteams-platform%2FTOC.yml) | 98 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2377957e-381f-47a5-80e8-9b09edb417a6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-Preview and customize Teams app manifest.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6083d75627b0f93988a9fb809e7f53600b124911/msteams-platform%2Ftoolkit%2FTeamsFx-Preview%20and%20customize%20Teams%20app%20manifest.md) | 89 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7b00ec35-69cf-4414-ac80-ffdc39b91ae8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-manifest-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6083d75627b0f93988a9fb809e7f53600b124911/msteams-platform%2Ftoolkit%2FTeamsFx-manifest-customization.md) | 88 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/84379bb0-8042-4099-8ae6-864e428f7ef3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6083d75627b0f93988a9fb809e7f53600b124911/msteams-platform%2Ftoolkit%2FTeamsFx-multi-env.md) | 90 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d8327862-5b87-4811-b7e5-11ba64d7676e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-19 11:46 UTC, opbld33 commented
Docs Build status updates of commit _[6083d75](https://github.com/MicrosoftDocs/msteams-docs/commits/6083d75627b0f93988a9fb809e7f53600b124911)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/TOC.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-customization?branch=pr-en-us-5837) | [Details](#user-content-f679b5d0ee59eb212f56a224ff613c91-9df50ed7)
[msteams-platform/toolkit/TeamsFx-manifest-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-manifest-customization.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-customization?branch=pr-en-us-5837) | [Details](#user-content-4b79caac002a5471906c80c4179f299c-9df50ed7)
[msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-multi-env.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-multi-env?branch=pr-en-us-5837) | [Details](#user-content-12216123ba329c9ca6700f9d931f42c2-9df50ed7)
[msteams-platform/assets/images/teams-toolkit-v2/create-project.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/create-project.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/codelens.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/codelens.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-preview%20and%20customize%20teams%20app%20manifest?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/deploy-command.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/deploy-command.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-preview%20and%20customize%20teams%20app%20manifest?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/deploy-manifest.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/deploy-manifest.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-preview%20and%20customize%20teams%20app%20manifest?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/hover.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/hover.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-preview%20and%20customize%20teams%20app%20manifest?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/manifest preview -3.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/manifest%20preview%20-3.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-preview%20and%20customize%20teams%20app%20manifest?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/manifest preview-1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/manifest%20preview-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-multi-env?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/pre.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/pre.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-preview%20and%20customize%20teams%20app%20manifest?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/preview-23.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/preview-23.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-preview%20and%20customize%20teams%20app%20manifest?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/select-environment.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/select-environment.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-preview%20and%20customize%20teams%20app%20manifest?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/update-to-teams.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/update-to-teams.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-preview%20and%20customize%20teams%20app%20manifest?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/validate.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/validate.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-preview%20and%20customize%20teams%20app%20manifest?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-Preview and customize Teams app manifest.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-Preview and customize Teams app manifest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-preview%20and%20customize%20teams%20app%20manifest?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/toolkit/TeamsFx-manifest-preview.md) | :white_check_mark:Succeeded | |

<a id="f679b5d0ee59eb212f56a224ff613c91-9df50ed7"></a>
### [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/TOC.yml)
 - **Line 112, Column 13**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'toolkit/Preview and customize Teams app manifest.md'.`````

<a id="4b79caac002 [...]

2022-05-19 11:58 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/bec2174c5fe3c6511c4823becb21ba4f66630b54/msteams-platform%2FTOC.yml) | 98 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/22dbbb31-9f22-431b-86d8-9d4bedad2c66) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-Preview and customize Teams app manifest.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bec2174c5fe3c6511c4823becb21ba4f66630b54/msteams-platform%2Ftoolkit%2FTeamsFx-Preview%20and%20customize%20Teams%20app%20manifest.md) | 89 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/53f1c99c-87e9-4495-b505-8580f9a3a5fd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-manifest-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bec2174c5fe3c6511c4823becb21ba4f66630b54/msteams-platform%2Ftoolkit%2FTeamsFx-manifest-customization.md) | 88 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/70b38c12-1e8b-47e7-87a7-3675879bf852) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bec2174c5fe3c6511c4823becb21ba4f66630b54/msteams-platform%2Ftoolkit%2FTeamsFx-multi-env.md) | 90 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f703880c-b4d0-41b6-a878-9e0c67dd9813) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-19 11:58 UTC, opbld31 commented
Docs Build status updates of commit _[bec2174](https://github.com/MicrosoftDocs/msteams-docs/commits/bec2174c5fe3c6511c4823becb21ba4f66630b54)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-customization?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/create-project.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/create-project.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/codelens.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/codelens.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-preview%20and%20customize%20teams%20app%20manifest?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/deploy-command.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/deploy-command.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-preview%20and%20customize%20teams%20app%20manifest?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/deploy-manifest.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/deploy-manifest.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-preview%20and%20customize%20teams%20app%20manifest?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/hover.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/hover.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-preview%20and%20customize%20teams%20app%20manifest?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/manifest preview -3.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/manifest%20preview%20-3.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-preview%20and%20customize%20teams%20app%20manifest?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/manifest preview-1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/manifest%20preview-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-multi-env?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/pre.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/pre.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-preview%20and%20customize%20teams%20app%20manifest?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/preview-23.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/preview-23.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-preview%20and%20customize%20teams%20app%20manifest?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/select-environment.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/select-environment.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-preview%20and%20customize%20teams%20app%20manifest?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/update-to-teams.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/update-to-teams.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-preview%20and%20customize%20teams%20app%20manifest?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/validate.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/validate.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-preview%20and%20customize%20teams%20app%20manifest?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-Preview and customize Teams app manifest.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-Preview and customize Teams app manifest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-preview%20and%20customize%20teams%20app%20manifest?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-manifest-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-manifest-customization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-customization?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/toolkit/TeamsFx-manifest-preview.md) | :white_check_mark:Succeeded | |
[msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-multi-env.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-multi-env?branch=pr-en-us-5837) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202205191157568929-5837/BuildReport?accessString=9fead47231adeebfc6cde9bbfa9f626ff2494d1a11fa9203c486423cfe5992db).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com [...]

2022-05-20 05:19 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/542e01cfdae9d378ddab869d6a5a922aeeb3b370/msteams-platform%2FTOC.yml) | 98 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5c7cb504-9fc7-43bf-9a56-09da31d33e29) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-Preview and customize Teams app manifest.md](https://github.com/MicrosoftDocs/msteams-docs/blob/542e01cfdae9d378ddab869d6a5a922aeeb3b370/msteams-platform%2Ftoolkit%2FTeamsFx-Preview%20and%20customize%20Teams%20app%20manifest.md) | 89 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/de63b42f-6aee-4286-baba-76048a27adc0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-manifest-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/542e01cfdae9d378ddab869d6a5a922aeeb3b370/msteams-platform%2Ftoolkit%2FTeamsFx-manifest-customization.md) | 88 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b1b58c09-aab0-4e38-b008-989fb4a284c4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/542e01cfdae9d378ddab869d6a5a922aeeb3b370/msteams-platform%2Ftoolkit%2FTeamsFx-multi-env.md) | 90 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/38bd7ba9-bbe6-4288-a05f-6920fa835b3c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-20 05:20 UTC, opbld32 commented
Docs Build status updates of commit _[542e01c](https://github.com/MicrosoftDocs/msteams-docs/commits/542e01cfdae9d378ddab869d6a5a922aeeb3b370)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-customization?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/create-project.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/create-project.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/codelens.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/codelens.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-preview%20and%20customize%20teams%20app%20manifest?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/deploy-command.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/deploy-command.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-preview%20and%20customize%20teams%20app%20manifest?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/deploy-manifest.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/deploy-manifest.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-preview%20and%20customize%20teams%20app%20manifest?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/hover.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/hover.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-preview%20and%20customize%20teams%20app%20manifest?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/manifest preview -3.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/manifest%20preview%20-3.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-preview%20and%20customize%20teams%20app%20manifest?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/manifest preview-1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/manifest%20preview-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-multi-env?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/pre.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/pre.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-preview%20and%20customize%20teams%20app%20manifest?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/preview-23.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/preview-23.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-preview%20and%20customize%20teams%20app%20manifest?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/select-environment.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/select-environment.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-preview%20and%20customize%20teams%20app%20manifest?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/update-to-teams.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/update-to-teams.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-preview%20and%20customize%20teams%20app%20manifest?branch=pr-en-us-5837) |
[msteams-platform/assets/images/teams-toolkit-v2/teams toolkit fundamentals/validate.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/assets/images/teams-toolkit-v2/teams%20toolkit%20fundamentals/validate.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-preview%20and%20customize%20teams%20app%20manifest?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-Preview and customize Teams app manifest.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-Preview and customize Teams app manifest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-preview%20and%20customize%20teams%20app%20manifest?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-manifest-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-manifest-customization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-manifest-customization?branch=pr-en-us-5837) |
[msteams-platform/toolkit/TeamsFx-manifest-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Teams-Toolkit-revamp]/msteams-platform/toolkit/TeamsFx-manifest-preview.md) | :white_check_mark:Succeeded | |
[msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/TeamsFx-multi-env.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-multi-env?branch=pr-en-us-5837) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202205200518291814-5837/BuildReport?accessString=edd293ca378fbc5908f5f9504602dc639c876d550febf679e925a6c75cc542a0).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com [...]

2022-05-20 05:59 UTC, v-bdeepa commented
Closing PR as outdated.

2022-05-20 05:59 UTC, closed without merging