[Doc-Improvement][Update-Teams-Toolkit]
MicrosoftDocs/msteams-docs pull request #5843
Opened 2022-05-03 03:07 UTC by v-rramanna

2022-05-03 03:07 UTC, opbld31 commented
Docs Build status updates of commit _[0d68b6b](https://github.com/MicrosoftDocs/msteams-docs/commits/0d68b6b67937eb15270e24a7375b56756c695a5e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/toolkit/create-new-project.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/create-new-project.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) |
[msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/debug-local.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-local?branch=pr-en-us-5843) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C3%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202205030307083212-5843%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-03T03%3A07%3A57Z&sr=b&sp=r&sig=4Xkn6fgl6a1uRfr22HwEkeCHjfy%2F%2BlWyNN9SGfjkJ18%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-03 03:08 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/create-new-project.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0d68b6b67937eb15270e24a7375b56756c695a5e/msteams-platform%2Ftoolkit%2Fcreate-new-project.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/83a61d28-b312-4712-a062-24c2169b6b28) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0d68b6b67937eb15270e24a7375b56756c695a5e/msteams-platform%2Ftoolkit%2Fdebug-local.md) | 94 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/04e75a80-3490-4a08-b55e-b9fa3995b812) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-03 03:10 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/create-new-project.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9b23e0bfb4bea10cdbb34ac7b2e43742df23dda3/msteams-platform%2Ftoolkit%2Fcreate-new-project.md) | 92 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/491cde30-0ae0-4bdf-a64f-5d512eaaaa88) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9b23e0bfb4bea10cdbb34ac7b2e43742df23dda3/msteams-platform%2Ftoolkit%2Fdebug-local.md) | 94 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/85fbc0e8-706e-48d4-8ca7-c9506dcd1ad2) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-03 03:10 UTC, opbld30 commented
Docs Build status updates of commit _[9b23e0b](https://github.com/MicrosoftDocs/msteams-docs/commits/9b23e0bfb4bea10cdbb34ac7b2e43742df23dda3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/toolkit/create-new-project.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/create-new-project.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) | [Details](#user-content-08cb23e5dcaaafcdd2df153d3af57961-54b93867)
[msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/debug-local.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-local?branch=pr-en-us-5843) |

<a id="08cb23e5dcaaafcdd2df153d3af57961-54b93867"></a>
### [msteams-platform/toolkit/create-new-project.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/create-new-project.md)
 - **Line 28, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../assets/images/teams-toolkit-v2/extension.png'.`````
 - **Line 31, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../assets/images/teams-toolkit-v2/extension1.png'.`````
 - **Line 42, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../assets/images/teams-toolkit-v2/create123.png'.`````
 - **Line 44, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../assets/images/teams-toolkit-v2/create1234.png'.`````
 - **Line 56, Column 4**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../assets/images/teams-toolkit-v2/sample1.png'.`````
 - **Line 59, Column 4**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../assets/images/teams-toolkit-v2/sample2.png'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C3%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202205030309497334-5843%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-03T03%3A10%3A37Z&sr=b&sp=r&sig=cYq18DBySnV6B3sDeSPN5%2FUWpbIWY3AvLWISh2oYM%2Fk%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-03 03:11 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/create-new-project.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3ab8a5cf34b1bb50fa245f6c83c5b46bd5ceab48/msteams-platform%2Ftoolkit%2Fcreate-new-project.md) | 92 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fd0a5b0f-4e56-49c4-a360-d5649be697c9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3ab8a5cf34b1bb50fa245f6c83c5b46bd5ceab48/msteams-platform%2Ftoolkit%2Fdebug-local.md) | 92 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e1c40284-edd5-4064-9362-12139da13525) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-03 03:11 UTC, opbld31 commented
Docs Build status updates of commit _[3ab8a5c](https://github.com/MicrosoftDocs/msteams-docs/commits/3ab8a5cf34b1bb50fa245f6c83c5b46bd5ceab48)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/toolkit/create-new-project.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/create-new-project.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) | [Details](#user-content-08cb23e5dcaaafcdd2df153d3af57961-8b59abea)
[msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/debug-local.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-local?branch=pr-en-us-5843) | [Details](#user-content-6b15a1a1be07df380eb32b0e8a86ee1b-8b59abea)

<a id="08cb23e5dcaaafcdd2df153d3af57961-8b59abea"></a>
### [msteams-platform/toolkit/create-new-project.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/create-new-project.md)
 - **Line 28, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../assets/images/teams-toolkit-v2/extension.png'.`````
 - **Line 31, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../assets/images/teams-toolkit-v2/extension1.png'.`````
 - **Line 42, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../assets/images/teams-toolkit-v2/create123.png'.`````
 - **Line 44, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../assets/images/teams-toolkit-v2/create1234.png'.`````
 - **Line 56, Column 4**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../assets/images/teams-toolkit-v2/sample1.png'.`````
 - **Line 59, Column 4**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../assets/images/teams-toolkit-v2/sample2.png'.`````

<a id="6b15a1a1be07df380eb32b0e8a86ee1b-8b59abea"></a>
### [msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/debug-local.md)
 - **Line 181, Column 4**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../assets/images/teams-toolkit-v2/debug/app1.png'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C3%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202205030311057030-5843%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-03T03%3A11%3A52Z&sr=b&sp=r&sig=sEFtSJPB9%2B5XAOTVpBi6fF4S1lDk4X18q7MG1HdwM2E%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-03 17:10 UTC, opbld30 commented
Docs Build status updates of commit _[2f9f5b1](https://github.com/MicrosoftDocs/msteams-docs/commits/2f9f5b174396771f57b339ad2928aa3546904508)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/debug-local.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-local?branch=pr-en-us-5843) | [Details](#user-content-6b15a1a1be07df380eb32b0e8a86ee1b-d8c3dd0c)
[msteams-platform/assets/images/teams-toolkit-v2/create123.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/create123.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) |
[msteams-platform/assets/images/teams-toolkit-v2/create1234.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/create1234.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) |
[msteams-platform/assets/images/teams-toolkit-v2/extension.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/extension.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) |
[msteams-platform/assets/images/teams-toolkit-v2/extension1.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/extension1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) |
[msteams-platform/assets/images/teams-toolkit-v2/sample1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/sample1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) |
[msteams-platform/assets/images/teams-toolkit-v2/samples2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/samples2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) |
[msteams-platform/toolkit/create-new-project.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/create-new-project.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) |

<a id="6b15a1a1be07df380eb32b0e8a86ee1b-d8c3dd0c"></a>
### [msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/debug-local.md)
 - **Line 181, Column 4**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../assets/images/teams-toolkit-v2/debug/app1.png'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C3%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202205031709528367-5843%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-03T17%3A10%3A44Z&sr=b&sp=r&sig=xbFVVBtG%2FdBJvSHLgtQTFAt698rmLJSZsAmKiDgyVDg%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-03 17:11 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/create-new-project.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2f9f5b174396771f57b339ad2928aa3546904508/msteams-platform%2Ftoolkit%2Fcreate-new-project.md) | 92 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c21a6789-997f-4f9b-99e3-c637e364d94a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2f9f5b174396771f57b339ad2928aa3546904508/msteams-platform%2Ftoolkit%2Fdebug-local.md) | 92 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1ccc1893-cf7f-4b24-a78c-4b27f01217d5) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-03 17:13 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/create-new-project.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ba3367d88946976d5dd4f0d866fbfcfde26d3e81/msteams-platform%2Ftoolkit%2Fcreate-new-project.md) | 92 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ed13a263-0552-4a9f-afe4-7c19bcd48e79) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ba3367d88946976d5dd4f0d866fbfcfde26d3e81/msteams-platform%2Ftoolkit%2Fdebug-local.md) | 92 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3a7a96d5-d4ea-4527-98c1-a847569906df) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-03 17:14 UTC, opbld33 commented
Docs Build status updates of commit _[ba3367d](https://github.com/MicrosoftDocs/msteams-docs/commits/ba3367d88946976d5dd4f0d866fbfcfde26d3e81)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/teams-toolkit-v2/create123.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/create123.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) |
[msteams-platform/assets/images/teams-toolkit-v2/create1234.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/create1234.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/app1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/debug/app1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-local?branch=pr-en-us-5843) |
[msteams-platform/assets/images/teams-toolkit-v2/extension.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/extension.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) |
[msteams-platform/assets/images/teams-toolkit-v2/extension1.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/extension1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) |
[msteams-platform/assets/images/teams-toolkit-v2/sample1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/sample1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) |
[msteams-platform/assets/images/teams-toolkit-v2/samples2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/samples2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) |
[msteams-platform/toolkit/create-new-project.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/create-new-project.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) |
[msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/debug-local.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-local?branch=pr-en-us-5843) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C3%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202205031713139974-5843%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-03T17%3A13%3A59Z&sr=b&sp=r&sig=jHR6fxJ4rOQ1fivhBJrNXZ0drt01UjxAveGqk3jhq7I%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-04 07:31 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/create-new-project.md](https://github.com/MicrosoftDocs/msteams-docs/blob/90a0b118e4c0e6b90b75deb5759044043863b2b2/msteams-platform%2Ftoolkit%2Fcreate-new-project.md) | 92 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0ce0da96-2cbe-4d95-bb85-769adebf0d4c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/90a0b118e4c0e6b90b75deb5759044043863b2b2/msteams-platform%2Ftoolkit%2Fdebug-local.md) | 92 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c25cf46d-f9e3-4a5a-ab9d-ca2479301208) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-04 07:31 UTC, opbld32 commented
Docs Build status updates of commit _[90a0b11](https://github.com/MicrosoftDocs/msteams-docs/commits/90a0b118e4c0e6b90b75deb5759044043863b2b2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/teams-toolkit-v2/create123.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/create123.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) |
[msteams-platform/assets/images/teams-toolkit-v2/create1234.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/create1234.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/app1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/debug/app1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-local?branch=pr-en-us-5843) |
[msteams-platform/assets/images/teams-toolkit-v2/extension.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/extension.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) |
[msteams-platform/assets/images/teams-toolkit-v2/extension1.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/extension1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) |
[msteams-platform/assets/images/teams-toolkit-v2/sample1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/sample1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) |
[msteams-platform/assets/images/teams-toolkit-v2/samples2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/samples2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) |
[msteams-platform/toolkit/create-new-project.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/create-new-project.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) |
[msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/debug-local.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-local?branch=pr-en-us-5843) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C4%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202205040730572519-5843%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-04T07%3A31%3A44Z&sr=b&sp=r&sig=BnR%2BT4JFjpUH3VKT5pnwfd3T9idS8PYE%2FcktkjYE6gY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-04 07:43 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/create-new-project.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a441308716f929fb50c1eb4231a8b1e0b8c440e2/msteams-platform%2Ftoolkit%2Fcreate-new-project.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/30022fce-9343-48fc-947b-675d5e92c2aa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a441308716f929fb50c1eb4231a8b1e0b8c440e2/msteams-platform%2Ftoolkit%2Fdebug-local.md) | 92 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/51f2a78d-7624-492c-aab6-70763a0dbd59) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-04 07:44 UTC, opbld33 commented
Docs Build status updates of commit _[a441308](https://github.com/MicrosoftDocs/msteams-docs/commits/a441308716f929fb50c1eb4231a8b1e0b8c440e2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/toolkit/create-new-project.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/create-new-project.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) | [Details](#user-content-08cb23e5dcaaafcdd2df153d3af57961-f21f0579)
[msteams-platform/assets/images/teams-toolkit-v2/create123.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/create123.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) |
[msteams-platform/assets/images/teams-toolkit-v2/create1234.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/create1234.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/app1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/debug/app1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-local?branch=pr-en-us-5843) |
[msteams-platform/assets/images/teams-toolkit-v2/extension.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/extension.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) |
[msteams-platform/assets/images/teams-toolkit-v2/extension1.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/extension1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) |
[msteams-platform/assets/images/teams-toolkit-v2/sample1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/sample1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) |
[msteams-platform/assets/images/teams-toolkit-v2/samples2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/samples2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) |
[msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/debug-local.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-local?branch=pr-en-us-5843) |

<a id="08cb23e5dcaaafcdd2df153d3af57961-f21f0579"></a>
### [msteams-platform/toolkit/create-new-project.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/create-new-project.md)
 - **Line 35, Column 1**: **[Warning: code-block-indented - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-indented?branch=main)]** `````Indented code blocks aren't allowed. Use a Markdown code block surrounded by triple backticks (```).`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C4%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202205040743208900-5843%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-04T07%3A44%3A06Z&sr=b&sp=r&sig=iCaqwr4qk%2FQzShlO3eMJ6kOD0awjXM3QKNnBkhchHo0%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-04 08:15 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/create-new-project.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7aaf234ce94ec72a2d5848a890b88be7c14b3a91/msteams-platform%2Ftoolkit%2Fcreate-new-project.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/068e583c-cff4-48b7-9f87-d4316e3cec30) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7aaf234ce94ec72a2d5848a890b88be7c14b3a91/msteams-platform%2Ftoolkit%2Fdebug-local.md) | 92 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bcacba15-e8ce-4db8-9265-db17cd64ffa9) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-04 08:16 UTC, opbld31 commented
Docs Build status updates of commit _[7aaf234](https://github.com/MicrosoftDocs/msteams-docs/commits/7aaf234ce94ec72a2d5848a890b88be7c14b3a91)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/teams-toolkit-v2/create123.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/create123.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) |
[msteams-platform/assets/images/teams-toolkit-v2/create1234.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/create1234.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/app1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/debug/app1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-local?branch=pr-en-us-5843) |
[msteams-platform/assets/images/teams-toolkit-v2/extension.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/extension.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) |
[msteams-platform/assets/images/teams-toolkit-v2/extension1.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/extension1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) |
[msteams-platform/assets/images/teams-toolkit-v2/sample1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/sample1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) |
[msteams-platform/assets/images/teams-toolkit-v2/samples2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/samples2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) |
[msteams-platform/toolkit/create-new-project.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/create-new-project.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) |
[msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/debug-local.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-local?branch=pr-en-us-5843) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C4%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202205040815276692-5843%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-04T08%3A16%3A10Z&sr=b&sp=r&sig=7dXXlt3L1BNho%2FYCyOr8hIECpqJKdcTA7swPXr%2B4AIk%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-04 08:20 UTC, opbld31 commented
Docs Build status updates of commit _[95589d3](https://github.com/MicrosoftDocs/msteams-docs/commits/95589d3296615e68aa557b1206ae9cd11887c886)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/teams-toolkit-v2/create123.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/create123.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) |
[msteams-platform/assets/images/teams-toolkit-v2/create1234.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/create1234.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/app1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/debug/app1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-local?branch=pr-en-us-5843) |
[msteams-platform/assets/images/teams-toolkit-v2/extension.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/extension.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) |
[msteams-platform/assets/images/teams-toolkit-v2/extension1.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/extension1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) |
[msteams-platform/assets/images/teams-toolkit-v2/sample1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/sample1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) |
[msteams-platform/assets/images/teams-toolkit-v2/samples2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/samples2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) |
[msteams-platform/toolkit/create-new-project.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/create-new-project.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) |
[msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/debug-local.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-local?branch=pr-en-us-5843) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C4%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202205040819226480-5843%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-04T08%3A20%3A07Z&sr=b&sp=r&sig=8eLYEethjfjNzeYty4CHcRgQYu1YGTOjbL8rMm6nhWM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-04 08:20 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/create-new-project.md](https://github.com/MicrosoftDocs/msteams-docs/blob/95589d3296615e68aa557b1206ae9cd11887c886/msteams-platform%2Ftoolkit%2Fcreate-new-project.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2d441c70-960a-401e-93de-9c8f59b83539) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/95589d3296615e68aa557b1206ae9cd11887c886/msteams-platform%2Ftoolkit%2Fdebug-local.md) | 93 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e2bcdafb-40fb-437e-98f6-ec191a54ecf9) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-04 12:36 UTC, opbld31 commented
Docs Build status updates of commit _[7cd7f45](https://github.com/MicrosoftDocs/msteams-docs/commits/7cd7f45ae4e5b3204090a988faa99005a822402c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/teams-toolkit-v2/create123.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/create123.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) |
[msteams-platform/assets/images/teams-toolkit-v2/create1234.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/create1234.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/app1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/debug/app1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-local?branch=pr-en-us-5843) |
[msteams-platform/assets/images/teams-toolkit-v2/extension.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/extension.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) |
[msteams-platform/assets/images/teams-toolkit-v2/extension1.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/extension1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) |
[msteams-platform/assets/images/teams-toolkit-v2/sample1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/sample1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) |
[msteams-platform/assets/images/teams-toolkit-v2/samples2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/samples2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) |
[msteams-platform/toolkit/create-new-project.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/create-new-project.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) |
[msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/debug-local.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-local?branch=pr-en-us-5843) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C4%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202205041236123278-5843%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-04T12%3A36%3A56Z&sr=b&sp=r&sig=wspvf9LTO8Aix4fVzph1dR4fEsBh7ihEPipyzP7IrKc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-04 12:38 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/create-new-project.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cee3e6e2847642c0ef2f906b25b4b53e0f5509a1/msteams-platform%2Ftoolkit%2Fcreate-new-project.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0c23d5cb-e2f0-4ba3-bdc6-e1d31c2a535a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cee3e6e2847642c0ef2f906b25b4b53e0f5509a1/msteams-platform%2Ftoolkit%2Fdebug-local.md) | 93 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2ea173a2-97e6-4e1b-a5f5-c579bcbbdad4) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-04 12:38 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/create-new-project.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cee3e6e2847642c0ef2f906b25b4b53e0f5509a1/msteams-platform%2Ftoolkit%2Fcreate-new-project.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e13d16a5-b325-411a-b9a3-9a04a79ca991) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cee3e6e2847642c0ef2f906b25b4b53e0f5509a1/msteams-platform%2Ftoolkit%2Fdebug-local.md) | 93 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/eca21fe1-4a04-4ec6-a4b6-bbd6d5dd0137) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-04 12:38 UTC, opbld30 commented
Docs Build status updates of commit _[cee3e6e](https://github.com/MicrosoftDocs/msteams-docs/commits/cee3e6e2847642c0ef2f906b25b4b53e0f5509a1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/teams-toolkit-v2/create123.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/create123.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) |
[msteams-platform/assets/images/teams-toolkit-v2/create1234.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/create1234.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/app1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/debug/app1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-local?branch=pr-en-us-5843) |
[msteams-platform/assets/images/teams-toolkit-v2/extension.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/extension.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) |
[msteams-platform/assets/images/teams-toolkit-v2/extension1.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/extension1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) |
[msteams-platform/assets/images/teams-toolkit-v2/sample1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/sample1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) |
[msteams-platform/assets/images/teams-toolkit-v2/samples2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/samples2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) |
[msteams-platform/toolkit/create-new-project.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/create-new-project.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) |
[msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/debug-local.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-local?branch=pr-en-us-5843) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C4%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202205041237558883-5843%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-04T12%3A38%3A42Z&sr=b&sp=r&sig=0TNJyfvCpV8gbypfkwPnTML1SfOx5%2FLF%2FkWrvJogkys%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-04 14:21 UTC, opbld32 commented
Docs Build status updates of commit _[ef368df](https://github.com/MicrosoftDocs/msteams-docs/commits/ef368df7f3070bb78c0e23391c9c270d8939ef85)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/toolkit/create-new-project.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/create-new-project.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) | [Details](#user-content-08cb23e5dcaaafcdd2df153d3af57961-f264c918)
[msteams-platform/assets/images/teams-toolkit-v2/Program.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/Program.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) |
[msteams-platform/assets/images/teams-toolkit-v2/app.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/app.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) |
[msteams-platform/assets/images/teams-toolkit-v2/capability.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/capability.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) |
[msteams-platform/assets/images/teams-toolkit-v2/create123.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/create123.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) |
[msteams-platform/assets/images/teams-toolkit-v2/create1234.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/create1234.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/app1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/debug/app1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-local?branch=pr-en-us-5843) |
[msteams-platform/assets/images/teams-toolkit-v2/extension.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/extension.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/extension.png?branch=pr-en-us-5843) |
[msteams-platform/assets/images/teams-toolkit-v2/extension1.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/extension1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/extension1.png?branch=pr-en-us-5843) |
[msteams-platform/assets/images/teams-toolkit-v2/sample1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/sample1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) |
[msteams-platform/assets/images/teams-toolkit-v2/samples2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/samples2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) |
[msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/debug-local.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-local?branch=pr-en-us-5843) |

<a id="08cb23e5dcaaafcdd2df153d3af57961-f264c918"></a>
### [msteams-platform/toolkit/create-new-project.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/create-new-project.md)
 - **Line 30, Column 4**: **[Warning: duplicate-alt-text - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-alt-text?branch=main)]** `````Alt text 'create-option' is duplicated. Within an article, alt text must be unique.`````
 - **Line 33, Column 4**: **[Warning: duplicate-alt-text - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-alt-text?branch=main)]** `````Alt text 'create-option' is duplicated. Within an article, alt text must be unique.`````
 - **Line 37, Column 4**: **[Warning: duplicate-alt-text - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-alt-text?branch=main)]** `````Alt text 'create-option' is duplicated. Within an article, alt text must be unique.`````
 - **Line 41, Column 4**: **[Warning: duplicate-alt-text - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-alt-text?branch=main)]** `````Alt text 'create-option' is duplicated. Within an article, alt text must be unique.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C4%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202205041420249651-5843%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-04T14%3A21%3A10Z&sr=b&sp=r&sig=qnEGFJ5YlNWOcwH7fAg3YUNpnfUs9AciZngaM7WDT4Q%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-04 14:25 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/create-new-project.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ef368df7f3070bb78c0e23391c9c270d8939ef85/msteams-platform%2Ftoolkit%2Fcreate-new-project.md) | 97 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9e04e2f9-50a6-4aeb-9ca5-78adaad620be) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ef368df7f3070bb78c0e23391c9c270d8939ef85/msteams-platform%2Ftoolkit%2Fdebug-local.md) | 93 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/62e45e65-8a5f-4479-81a7-2756b04978bb) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-04 14:42 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/create-new-project.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9aec6245771aeff8e9091acfb41913ee32c82fb3/msteams-platform%2Ftoolkit%2Fcreate-new-project.md) | 97 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/acad2074-fd75-4582-b8ba-8af3b6b728de) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9aec6245771aeff8e9091acfb41913ee32c82fb3/msteams-platform%2Ftoolkit%2Fdebug-local.md) | 93 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b243baec-836d-45d6-bf09-bde9efb5811b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-04 14:52 UTC, opbld31 commented
Docs Build status updates of commit _[d82b7f3](https://github.com/MicrosoftDocs/msteams-docs/commits/d82b7f3a3134a66dfc00d4f88dda534740b5df94)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/toolkit/create-new-project.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/create-new-project.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) | [Details](#user-content-08cb23e5dcaaafcdd2df153d3af57961-41020f51)
[msteams-platform/assets/images/teams-toolkit-v2/Program.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/Program.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) |
[msteams-platform/assets/images/teams-toolkit-v2/app.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/app.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) |
[msteams-platform/assets/images/teams-toolkit-v2/capability.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/capability.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) |
[msteams-platform/assets/images/teams-toolkit-v2/create123.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/create123.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) |
[msteams-platform/assets/images/teams-toolkit-v2/create1234.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/create1234.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/app1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/debug/app1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-local?branch=pr-en-us-5843) |
[msteams-platform/assets/images/teams-toolkit-v2/extension.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/extension.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/extension.png?branch=pr-en-us-5843) |
[msteams-platform/assets/images/teams-toolkit-v2/extension1.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/extension1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/extension1.png?branch=pr-en-us-5843) |
[msteams-platform/assets/images/teams-toolkit-v2/sample1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/sample1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) |
[msteams-platform/assets/images/teams-toolkit-v2/samples2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/samples2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) |
[msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/debug-local.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-local?branch=pr-en-us-5843) |

<a id="08cb23e5dcaaafcdd2df153d3af57961-41020f51"></a>
### [msteams-platform/toolkit/create-new-project.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/create-new-project.md)
 - **Line 24, Column 3**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#create-a-new-teams-app-using-view-samples' in 'toolkit/create-new-project.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C4%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202205041451218857-5843%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-04T14%3A52%3A06Z&sr=b&sp=r&sig=t6j5Xu7onRVgihueNi0MhaumUFDy0ejFx6czspwiSfU%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-04 16:12 UTC, v-abirade requested changes
@v-rramanna, please work on the comments.

2022-05-04 16:12 UTC, v-abirade commented on msteams-platform/toolkit/create-new-project.md
> +Explore samples to quickly get started with concepts and code examples. Follow the instructions for each sample, or select **View on GitHub** to open the sample in the `TeamsFx Samples` repository an
You can remove the world quickly. Please update information on the graphics and documents available to guide developers to create app.

2022-05-04 16:12 UTC, v-abirade commented on msteams-platform/toolkit/create-new-project.md
> +2. Select **DEVELOPMENT** section in Treeview and then Select **View samples**.
Please confirm, if this step is correct:
2. Select **DEVELOPMENT** section in Treeview and then Select **View samples**.
Can we select DEVELOPMENT? or do we need to select **View Samples** listed under **DEVELOPMENT** section.

2022-05-04 16:37 UTC, v-abirade requested changes
Please make changes

2022-05-04 16:37 UTC, v-abirade commented on msteams-platform/toolkit/debug-local.md
> + Debug is the process of resolving the conflicts to ensure the program runs successfully. Visual Studio Code allows you to debug tab, bot, message extension, and Azure Functions. Teams Toolkit helps
Please retain: Teams Toolkit helps you to debug and preview your Teams app locally. Debug is the process of checking, detecting, and correcting issues or bugs.

2022-05-04 16:37 UTC, v-abirade commented on msteams-platform/toolkit/debug-local.md
>  ## Prerequisite
Do we need to update prerequisite in all the files?

2022-05-04 16:37 UTC, v-abirade commented on msteams-platform/toolkit/debug-local.md
> +The following list shows the primary debug features used in Teams Toolkit.
There is no need to add the sentence as the heading provides the required information.

2022-05-04 16:37 UTC, v-abirade commented on msteams-platform/toolkit/debug-local.md
> +You can select debut option under **DEVELOPMENT** activity bar, Teams Toolkit utilizes multi-target debugging feature to debug tab, bot, message extension, and Azure Functions at the same time.
Check for Typos.

2022-05-04 16:37 UTC, v-abirade commented on msteams-platform/toolkit/debug-local.md
> +Follow the steps to debug your app once you create a new app:
Please correct the sentence.

2022-05-04 16:37 UTC, v-abirade commented on msteams-platform/toolkit/debug-local.md
> +The debug configuration names and types for project with Tab app and Bot app:
Please rephrase to the previous sentence:
The following table lists the debug configuration names and types for project with tab app and bot app:

2022-05-04 16:37 UTC, v-abirade commented on msteams-platform/toolkit/debug-local.md
> +The debug configuration names and types for project with Bot app:
Please retain.

2022-05-04 16:37 UTC, v-abirade commented on msteams-platform/toolkit/debug-local.md
> +The configuration **Attach to Frontend** or **Launch Bot** launches a new browser instance and opens a web page to load the Teams client. After the Teams client is loaded, Teams sideloads the Teams a
When Teams client loads in the web browser, select **Add** or select the required dropdown list option.

2022-05-04 17:34 UTC, opbld32 commented
Docs Build status updates of commit _[94185f3](https://github.com/MicrosoftDocs/msteams-docs/commits/94185f36db84c4c1dc2e44db5ae11035e9f2cc35)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/toolkit/create-new-project.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/create-new-project.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) | [Details](#user-content-08cb23e5dcaaafcdd2df153d3af57961-190af6a2)
[msteams-platform/assets/images/teams-toolkit-v2/Program.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/Program.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) |
[msteams-platform/assets/images/teams-toolkit-v2/app.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/app.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/app.png?branch=pr-en-us-5843) |
[msteams-platform/assets/images/teams-toolkit-v2/capability.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/capability.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) |
[msteams-platform/assets/images/teams-toolkit-v2/create123.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/create123.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) |
[msteams-platform/assets/images/teams-toolkit-v2/create1234.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/create1234.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/app1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/debug/app1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-local?branch=pr-en-us-5843) |
[msteams-platform/assets/images/teams-toolkit-v2/extension.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/extension.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/extension.png?branch=pr-en-us-5843) |
[msteams-platform/assets/images/teams-toolkit-v2/extension1.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/extension1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/extension1.png?branch=pr-en-us-5843) |
[msteams-platform/assets/images/teams-toolkit-v2/sample1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/sample1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) |
[msteams-platform/assets/images/teams-toolkit-v2/samples2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/samples2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) |
[msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/debug-local.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-local?branch=pr-en-us-5843) |

<a id="08cb23e5dcaaafcdd2df153d3af57961-190af6a2"></a>
### [msteams-platform/toolkit/create-new-project.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/create-new-project.md)
 - **Line 31, Column 3**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#create-a-new-teams-app-using-view-samples' in 'toolkit/create-new-project.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C4%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202205041731241179-5843%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-04T17%3A34%3A05Z&sr=b&sp=r&sig=B0FuJcJit0Gh3%2FcCxutlTUQiHpN6KbOteq0rkkcp0hA%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-05 01:00 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/create-new-project.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8a0785f117e9465b1d6feca6e30fd97bfadb679c/msteams-platform%2Ftoolkit%2Fcreate-new-project.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/630e0166-3448-47c4-a01e-7ba341e87e48) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8a0785f117e9465b1d6feca6e30fd97bfadb679c/msteams-platform%2Ftoolkit%2Fdebug-local.md) | 93 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/37ac2ec9-e375-483c-860d-446c4ec9b780) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-05-05 01:01 UTC, opbld32 commented
Docs Build status updates of commit _[8a0785f](https://github.com/MicrosoftDocs/msteams-docs/commits/8a0785f117e9465b1d6feca6e30fd97bfadb679c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/toolkit/create-new-project.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/create-new-project.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) | [Details](#user-content-08cb23e5dcaaafcdd2df153d3af57961-881f49e3)
[msteams-platform/assets/images/teams-toolkit-v2/Program.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/Program.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) |
[msteams-platform/assets/images/teams-toolkit-v2/app.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/app.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/app.png?branch=pr-en-us-5843) |
[msteams-platform/assets/images/teams-toolkit-v2/capability.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/capability.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) |
[msteams-platform/assets/images/teams-toolkit-v2/create123.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/create123.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) |
[msteams-platform/assets/images/teams-toolkit-v2/create1234.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/create1234.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/app1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/debug/app1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-local?branch=pr-en-us-5843) |
[msteams-platform/assets/images/teams-toolkit-v2/extension.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/extension.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/extension.png?branch=pr-en-us-5843) |
[msteams-platform/assets/images/teams-toolkit-v2/extension1.PNG](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/extension1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/assets/images/teams-toolkit-v2/extension1.png?branch=pr-en-us-5843) |
[msteams-platform/assets/images/teams-toolkit-v2/sample1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/sample1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) |
[msteams-platform/assets/images/teams-toolkit-v2/samples2.png](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-Improvement]-Update-Teams-Toolkit]/msteams-platform/assets/images/teams-toolkit-v2/samples2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?branch=pr-en-us-5843) |
[msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/debug-local.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-local?branch=pr-en-us-5843) |

<a id="08cb23e5dcaaafcdd2df153d3af57961-881f49e3"></a>
### [msteams-platform/toolkit/create-new-project.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/create-new-project.md)
 - **Line 30, Column 3**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#create-a-new-teams-app-using-view-samples' in 'toolkit/create-new-project.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C5%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202205050100185291-5843%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-05T01%3A01%3A56Z&sr=b&sp=r&sig=qIyCVHyWnaGhypkIla9Oh4ux%2B7SY6S1MejpCoCwZgjU%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-28 09:59 UTC, surbhigupta12 commented
Closing this PR as it is obsolete.

2022-05-28 09:59 UTC, closed without merging