[Doc-Improvement][Conversation events]
MicrosoftDocs/msteams-docs pull request #6378
Opened 2022-07-05 05:17 UTC by v-habibaumme

Removing dev preview details from the article

2022-07-05 05:18 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c20e754a6a5cbb196e9484f969219247db349370/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsubscribe-to-conversation-events.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/075f7972-4c7b-40d2-b3ea-1baba85cf170) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c20e754a6a5cbb196e9484f969219247db349370/msteams-platform%2Fwhats-new.md) | 91 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8083196a-38e3-4169-be11-585dba7bb72c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-07-05 05:18 UTC, opbld30 commented
Docs Build status updates of commit _[c20e754](https://github.com/MicrosoftDocs/msteams-docs/commits/c20e754a6a5cbb196e9484f969219247db349370)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-dev-pre-convestaion-events/msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/subscribe-to-conversation-events?branch=pr-en-us-6378) |
[msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-dev-pre-convestaion-events/msteams-platform/whats-new.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/whats-new?branch=pr-en-us-6378) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202207050517260922-6378/BuildReport?accessString=61809510d0aee073debb09277e40069b0753667412396fe7b7b756ddb0445ecf).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-06 08:21 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bee568957c4db18c554f0afed2c3ab600331f636/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsubscribe-to-conversation-events.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9a72e6ef-0c26-42e3-b596-5f9b380295fa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bee568957c4db18c554f0afed2c3ab600331f636/msteams-platform%2Fwhats-new.md) | 91 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a6a58a39-c3ae-4793-b027-7296db743554) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-07-06 08:21 UTC, opbld32 commented
Docs Build status updates of commit _[bee5689](https://github.com/MicrosoftDocs/msteams-docs/commits/bee568957c4db18c554f0afed2c3ab600331f636)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-dev-pre-convestaion-events/msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/subscribe-to-conversation-events?branch=pr-en-us-6378) |
[msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-dev-pre-convestaion-events/msteams-platform/whats-new.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/whats-new?branch=pr-en-us-6378) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202207060820543761-6378/BuildReport?accessString=34f5ff4eefa18257de6ba271690b56c26496d0cc69f42f1698ac4872fc240ad6).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-06 10:20 UTC, opbld30 commented
Docs Build status updates of commit _[f02e40d](https://github.com/MicrosoftDocs/msteams-docs/commits/f02e40d59652bb85477e41065bd4b4cc8bbb4070)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-dev-pre-convestaion-events/msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/subscribe-to-conversation-events?branch=pr-en-us-6378) |
[msteams-platform/concepts/deploy-and-publish/appsource/resolve-submission-issues.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-dev-pre-convestaion-events/msteams-platform/concepts/deploy-and-publish/appsource/resolve-submission-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/resolve-submission-issues?branch=pr-en-us-6378) |
[msteams-platform/resources/messaging-extension-v3/create-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-dev-pre-convestaion-events/msteams-platform/resources/messaging-extension-v3/create-extensions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/messaging-extension-v3/create-extensions?branch=pr-en-us-6378) |
[msteams-platform/resources/moodle-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-dev-pre-convestaion-events/msteams-platform/resources/moodle-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/moodle-overview?branch=pr-en-us-6378) |
[msteams-platform/samples/virtual-assistant.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-dev-pre-convestaion-events/msteams-platform/samples/virtual-assistant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/samples/virtual-assistant?branch=pr-en-us-6378) |
[msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-dev-pre-convestaion-events/msteams-platform/whats-new.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/whats-new?branch=pr-en-us-6378) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202207061019284754-6378/BuildReport?accessString=e673a4358f2d4c291698311ce89bf987ad4e73e5c2d9ce2e6953400d015722c6).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-06 10:21 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/de5b6a404c0fff97afb770870934a82654a4babd/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsubscribe-to-conversation-events.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c9c77824-f277-48ed-81c6-affe42aa314f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/resolve-submission-issues.md](https://github.com/MicrosoftDocs/msteams-docs/blob/de5b6a404c0fff97afb770870934a82654a4babd/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fresolve-submission-issues.md) | 91 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ed56f9df-2a22-4d55-9608-81fc25ab3ccd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/messaging-extension-v3/create-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/de5b6a404c0fff97afb770870934a82654a4babd/msteams-platform%2Fresources%2Fmessaging-extension-v3%2Fcreate-extensions.md) | 89 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4c87d17f-2d8b-4cf8-9d0c-eab3644afe49) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/moodle-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/de5b6a404c0fff97afb770870934a82654a4babd/msteams-platform%2Fresources%2Fmoodle-overview.md) | 98 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/be702881-5881-4d3e-989c-a1838364f31b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/virtual-assistant.md](https://github.com/MicrosoftDocs/msteams-docs/blob/de5b6a404c0fff97afb770870934a82654a4babd/msteams-platform%2Fsamples%2Fvirtual-assistant.md) | 84 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4bc1e995-184d-4432-85c2-08d823a43f0e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/de5b6a404c0fff97afb770870934a82654a4babd/msteams-platform%2Fwhats-new.md) | 91 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b255f46d-015c-4fdb-a1d2-c10b06f017ec) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-07-06 10:22 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/de5b6a404c0fff97afb770870934a82654a4babd/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsubscribe-to-conversation-events.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e376ed90-016f-410c-af20-573eac1eba72) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/resolve-submission-issues.md](https://github.com/MicrosoftDocs/msteams-docs/blob/de5b6a404c0fff97afb770870934a82654a4babd/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fresolve-submission-issues.md) | 91 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3dee2dc2-08c3-4ed3-98bb-c9b5523538c3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/messaging-extension-v3/create-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/de5b6a404c0fff97afb770870934a82654a4babd/msteams-platform%2Fresources%2Fmessaging-extension-v3%2Fcreate-extensions.md) | 89 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4d338217-2bb6-4563-8e9e-53ac4c545b47) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/moodle-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/de5b6a404c0fff97afb770870934a82654a4babd/msteams-platform%2Fresources%2Fmoodle-overview.md) | 98 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2d7042b0-1087-49cd-8202-da2970b42d1c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/virtual-assistant.md](https://github.com/MicrosoftDocs/msteams-docs/blob/de5b6a404c0fff97afb770870934a82654a4babd/msteams-platform%2Fsamples%2Fvirtual-assistant.md) | 84 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7add3663-a201-462e-9216-39fc56b6e55b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/de5b6a404c0fff97afb770870934a82654a4babd/msteams-platform%2Fwhats-new.md) | 91 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/33326589-752b-4bcd-b117-66f5ac94a723) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-07-06 15:52 UTC, vule-msft requested changes

2022-07-07 03:34 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/52601299f0953676f6b5f4b2992fe5de7e30614e/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsubscribe-to-conversation-events.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/118102d5-40dd-4670-93cb-9a0246dc520c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/resolve-submission-issues.md](https://github.com/MicrosoftDocs/msteams-docs/blob/52601299f0953676f6b5f4b2992fe5de7e30614e/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fresolve-submission-issues.md) | 91 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a841850e-3c8a-4508-b495-cbb6bcacec31) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/messaging-extension-v3/create-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/52601299f0953676f6b5f4b2992fe5de7e30614e/msteams-platform%2Fresources%2Fmessaging-extension-v3%2Fcreate-extensions.md) | 89 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/41bf7994-142d-4923-bb4f-f14833c9b047) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/moodle-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/52601299f0953676f6b5f4b2992fe5de7e30614e/msteams-platform%2Fresources%2Fmoodle-overview.md) | 98 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8266ec0b-cef1-4d41-936a-7e3aa3e408d9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/virtual-assistant.md](https://github.com/MicrosoftDocs/msteams-docs/blob/52601299f0953676f6b5f4b2992fe5de7e30614e/msteams-platform%2Fsamples%2Fvirtual-assistant.md) | 84 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/98e6ba63-ea31-425f-8aae-d47ad5fe4f6a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/52601299f0953676f6b5f4b2992fe5de7e30614e/msteams-platform%2Fwhats-new.md) | 91 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/55c0c4f7-19c8-4a2c-ae22-5abcd8f8bdc1) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-07-07 03:35 UTC, opbld33 commented
Docs Build status updates of commit _[5260129](https://github.com/MicrosoftDocs/msteams-docs/commits/52601299f0953676f6b5f4b2992fe5de7e30614e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-dev-pre-convestaion-events/msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/subscribe-to-conversation-events?branch=pr-en-us-6378) |
[msteams-platform/concepts/deploy-and-publish/appsource/resolve-submission-issues.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-dev-pre-convestaion-events/msteams-platform/concepts/deploy-and-publish/appsource/resolve-submission-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/resolve-submission-issues?branch=pr-en-us-6378) |
[msteams-platform/resources/messaging-extension-v3/create-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-dev-pre-convestaion-events/msteams-platform/resources/messaging-extension-v3/create-extensions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/messaging-extension-v3/create-extensions?branch=pr-en-us-6378) |
[msteams-platform/resources/moodle-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-dev-pre-convestaion-events/msteams-platform/resources/moodle-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/moodle-overview?branch=pr-en-us-6378) |
[msteams-platform/samples/virtual-assistant.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-dev-pre-convestaion-events/msteams-platform/samples/virtual-assistant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/samples/virtual-assistant?branch=pr-en-us-6378) |
[msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-dev-pre-convestaion-events/msteams-platform/whats-new.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/whats-new?branch=pr-en-us-6378) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202207070334034567-6378/BuildReport?accessString=a4d096f68a4d01ddb2ee458ab07f860d35880b7cd4b9fa207aea8a05a22d9199).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-07 03:36 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dc3cb23afe91bfc987fb2ed174ae6d1fd84332c7/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsubscribe-to-conversation-events.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/92655e73-e8fd-491e-ac1c-4e99725f9590) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/resolve-submission-issues.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dc3cb23afe91bfc987fb2ed174ae6d1fd84332c7/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fresolve-submission-issues.md) | 91 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/eb7b3c15-8ecf-4fbe-96c1-dc91f0c32bd6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/messaging-extension-v3/create-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dc3cb23afe91bfc987fb2ed174ae6d1fd84332c7/msteams-platform%2Fresources%2Fmessaging-extension-v3%2Fcreate-extensions.md) | 89 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/731d5caa-91c4-43e8-b6cc-5325cc7dbf62) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/moodle-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dc3cb23afe91bfc987fb2ed174ae6d1fd84332c7/msteams-platform%2Fresources%2Fmoodle-overview.md) | 98 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7df1bfd4-ff68-41bd-8c25-3a0a092ee898) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/virtual-assistant.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dc3cb23afe91bfc987fb2ed174ae6d1fd84332c7/msteams-platform%2Fsamples%2Fvirtual-assistant.md) | 84 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/52e1071c-82dd-4991-b342-2456bb755624) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dc3cb23afe91bfc987fb2ed174ae6d1fd84332c7/msteams-platform%2Fwhats-new.md) | 91 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3fdf456e-d78f-4d47-89fd-22dbc1aac462) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-07-07 03:36 UTC, opbld31 commented
Docs Build status updates of commit _[dc3cb23](https://github.com/MicrosoftDocs/msteams-docs/commits/dc3cb23afe91bfc987fb2ed174ae6d1fd84332c7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-dev-pre-convestaion-events/msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/subscribe-to-conversation-events?branch=pr-en-us-6378) |
[msteams-platform/concepts/deploy-and-publish/appsource/resolve-submission-issues.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-dev-pre-convestaion-events/msteams-platform/concepts/deploy-and-publish/appsource/resolve-submission-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/resolve-submission-issues?branch=pr-en-us-6378) |
[msteams-platform/resources/messaging-extension-v3/create-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-dev-pre-convestaion-events/msteams-platform/resources/messaging-extension-v3/create-extensions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/messaging-extension-v3/create-extensions?branch=pr-en-us-6378) |
[msteams-platform/resources/moodle-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-dev-pre-convestaion-events/msteams-platform/resources/moodle-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/moodle-overview?branch=pr-en-us-6378) |
[msteams-platform/samples/virtual-assistant.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-dev-pre-convestaion-events/msteams-platform/samples/virtual-assistant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/samples/virtual-assistant?branch=pr-en-us-6378) |
[msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-dev-pre-convestaion-events/msteams-platform/whats-new.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/whats-new?branch=pr-en-us-6378) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202207070335326358-6378/BuildReport?accessString=a284992042670f7ab15ccfbdce9bd1524a597125c3d08559273b419663fa124c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-07 03:40 UTC, v-habibaumme commented on msteams-platform/whats-new.md
> +| 07/05/2022| Update conversation and installation events in your Teams bot |  Build bots > Bot conversations > Conversation events in your Teams bot > [Conversation events in your Teams bot](bots/ho
Changed as per the request.

2022-07-07 03:41 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ff76244d51e1eea59759adcfc657b63324992f9a/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsubscribe-to-conversation-events.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/93ada53f-4b79-46f5-9187-929ca901f293) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/resolve-submission-issues.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ff76244d51e1eea59759adcfc657b63324992f9a/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fresolve-submission-issues.md) | 91 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/98ae8112-0205-4e37-8c41-318b3bd85dfa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/messaging-extension-v3/create-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ff76244d51e1eea59759adcfc657b63324992f9a/msteams-platform%2Fresources%2Fmessaging-extension-v3%2Fcreate-extensions.md) | 89 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/914bdcd0-30c0-46e8-af33-3214f6aa369f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/moodle-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ff76244d51e1eea59759adcfc657b63324992f9a/msteams-platform%2Fresources%2Fmoodle-overview.md) | 98 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4f26aa25-0533-4f2a-a72e-6dfb0fb0e715) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/virtual-assistant.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ff76244d51e1eea59759adcfc657b63324992f9a/msteams-platform%2Fsamples%2Fvirtual-assistant.md) | 84 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/356f6072-3806-48be-8af2-e54136a62285) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ff76244d51e1eea59759adcfc657b63324992f9a/msteams-platform%2Fwhats-new.md) | 91 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2412cd4d-8231-4d47-9b15-748c98729785) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-07-07 03:42 UTC, opbld30 commented
Docs Build status updates of commit _[ff76244](https://github.com/MicrosoftDocs/msteams-docs/commits/ff76244d51e1eea59759adcfc657b63324992f9a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-dev-pre-convestaion-events/msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/subscribe-to-conversation-events?branch=pr-en-us-6378) |
[msteams-platform/concepts/deploy-and-publish/appsource/resolve-submission-issues.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-dev-pre-convestaion-events/msteams-platform/concepts/deploy-and-publish/appsource/resolve-submission-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/resolve-submission-issues?branch=pr-en-us-6378) |
[msteams-platform/resources/messaging-extension-v3/create-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-dev-pre-convestaion-events/msteams-platform/resources/messaging-extension-v3/create-extensions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/messaging-extension-v3/create-extensions?branch=pr-en-us-6378) |
[msteams-platform/resources/moodle-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-dev-pre-convestaion-events/msteams-platform/resources/moodle-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/moodle-overview?branch=pr-en-us-6378) |
[msteams-platform/samples/virtual-assistant.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-dev-pre-convestaion-events/msteams-platform/samples/virtual-assistant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/samples/virtual-assistant?branch=pr-en-us-6378) |
[msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-dev-pre-convestaion-events/msteams-platform/whats-new.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/whats-new?branch=pr-en-us-6378) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202207070340439882-6378/BuildReport?accessString=7779ac08252d6119d84b587a6843f07b662876a334a3f9d747514d10e72f1d3c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-07 17:49 UTC, vule-msft requested changes

2022-07-08 03:35 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/290b730bf92e9ad3a431bf5d90acd63da971d15b/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsubscribe-to-conversation-events.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4b637e3e-7ada-4e80-8639-2ab638d8ad86) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/resolve-submission-issues.md](https://github.com/MicrosoftDocs/msteams-docs/blob/290b730bf92e9ad3a431bf5d90acd63da971d15b/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fresolve-submission-issues.md) | 91 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d47034d1-b33c-4453-a503-361c5c466d3e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/messaging-extension-v3/create-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/290b730bf92e9ad3a431bf5d90acd63da971d15b/msteams-platform%2Fresources%2Fmessaging-extension-v3%2Fcreate-extensions.md) | 89 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2b5cad0a-07c6-4c15-9006-695d6a361f23) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/moodle-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/290b730bf92e9ad3a431bf5d90acd63da971d15b/msteams-platform%2Fresources%2Fmoodle-overview.md) | 98 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/16174e4f-6c1f-4052-8c77-7455041e6b1e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/virtual-assistant.md](https://github.com/MicrosoftDocs/msteams-docs/blob/290b730bf92e9ad3a431bf5d90acd63da971d15b/msteams-platform%2Fsamples%2Fvirtual-assistant.md) | 84 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1917e2ef-8552-469a-abde-6cbee718ef80) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/290b730bf92e9ad3a431bf5d90acd63da971d15b/msteams-platform%2Fwhats-new.md) | 91 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e2c3941d-7db1-4cb4-adc7-d32874f849c9) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-07-08 03:35 UTC, opbld33 commented
Docs Build status updates of commit _[290b730](https://github.com/MicrosoftDocs/msteams-docs/commits/290b730bf92e9ad3a431bf5d90acd63da971d15b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-dev-pre-convestaion-events/msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/subscribe-to-conversation-events?branch=pr-en-us-6378) |
[msteams-platform/concepts/deploy-and-publish/appsource/resolve-submission-issues.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-dev-pre-convestaion-events/msteams-platform/concepts/deploy-and-publish/appsource/resolve-submission-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/resolve-submission-issues?branch=pr-en-us-6378) |
[msteams-platform/resources/messaging-extension-v3/create-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-dev-pre-convestaion-events/msteams-platform/resources/messaging-extension-v3/create-extensions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/messaging-extension-v3/create-extensions?branch=pr-en-us-6378) |
[msteams-platform/resources/moodle-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-dev-pre-convestaion-events/msteams-platform/resources/moodle-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/moodle-overview?branch=pr-en-us-6378) |
[msteams-platform/samples/virtual-assistant.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-dev-pre-convestaion-events/msteams-platform/samples/virtual-assistant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/samples/virtual-assistant?branch=pr-en-us-6378) |
[msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-dev-pre-convestaion-events/msteams-platform/whats-new.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/whats-new?branch=pr-en-us-6378) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202207080333296774-6378/BuildReport?accessString=b0710498a6243238bdbb9256d86a4175c8bde45f6601f972293b9a4bc8de659f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-08 03:36 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/56cdc5b4e973448653aab22ef352266fd5acdfe2/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsubscribe-to-conversation-events.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9676bf49-2a8d-41c7-b296-2b0c00ecf7da) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/messaging-extension-v3/create-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/56cdc5b4e973448653aab22ef352266fd5acdfe2/msteams-platform%2Fresources%2Fmessaging-extension-v3%2Fcreate-extensions.md) | 89 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/07ca84af-23f4-4d19-bc82-0c2e54cf1b24) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/moodle-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/56cdc5b4e973448653aab22ef352266fd5acdfe2/msteams-platform%2Fresources%2Fmoodle-overview.md) | 98 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4466b944-c1ab-4851-9ad0-74b7989f39be) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/virtual-assistant.md](https://github.com/MicrosoftDocs/msteams-docs/blob/56cdc5b4e973448653aab22ef352266fd5acdfe2/msteams-platform%2Fsamples%2Fvirtual-assistant.md) | 84 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0a924566-e6ef-4444-b45b-84af21f25035) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/56cdc5b4e973448653aab22ef352266fd5acdfe2/msteams-platform%2Fwhats-new.md) | 91 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d63e9110-a8b1-4e09-92c5-dd6c135d9d69) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-07-08 03:36 UTC, opbld31 commented
Docs Build status updates of commit _[56cdc5b](https://github.com/MicrosoftDocs/msteams-docs/commits/56cdc5b4e973448653aab22ef352266fd5acdfe2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-dev-pre-convestaion-events/msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/subscribe-to-conversation-events?branch=pr-en-us-6378) |
[msteams-platform/resources/messaging-extension-v3/create-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-dev-pre-convestaion-events/msteams-platform/resources/messaging-extension-v3/create-extensions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/messaging-extension-v3/create-extensions?branch=pr-en-us-6378) |
[msteams-platform/resources/moodle-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-dev-pre-convestaion-events/msteams-platform/resources/moodle-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/moodle-overview?branch=pr-en-us-6378) |
[msteams-platform/samples/virtual-assistant.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-dev-pre-convestaion-events/msteams-platform/samples/virtual-assistant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/samples/virtual-assistant?branch=pr-en-us-6378) |
[msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-dev-pre-convestaion-events/msteams-platform/whats-new.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/whats-new?branch=pr-en-us-6378) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202207080335492945-6378/BuildReport?accessString=7599f235a24e98d1c09c586c2af9a95d71bc30c71a56f81f181c90dcf77e588e).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-08 03:41 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/da948bbeb7e637140ce038998868cd49a41e63fc/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsubscribe-to-conversation-events.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b37a6d2b-6a97-4b7e-9c8b-11d99c7530e9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/messaging-extension-v3/create-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/da948bbeb7e637140ce038998868cd49a41e63fc/msteams-platform%2Fresources%2Fmessaging-extension-v3%2Fcreate-extensions.md) | 89 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a4d5c38d-5ed6-46f2-b489-cee97d8ed048) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/moodle-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/da948bbeb7e637140ce038998868cd49a41e63fc/msteams-platform%2Fresources%2Fmoodle-overview.md) | 98 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/72553500-9f10-45c7-9aa5-86cbc640d0f8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/virtual-assistant.md](https://github.com/MicrosoftDocs/msteams-docs/blob/da948bbeb7e637140ce038998868cd49a41e63fc/msteams-platform%2Fsamples%2Fvirtual-assistant.md) | 84 | 33 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8804b321-101e-4968-823e-1d6b430b0856) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/da948bbeb7e637140ce038998868cd49a41e63fc/msteams-platform%2Fwhats-new.md) | 91 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cd287958-44d0-41ea-9563-fe52893d3133) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-07-08 03:41 UTC, opbld32 commented
Docs Build status updates of commit _[da948bb](https://github.com/MicrosoftDocs/msteams-docs/commits/da948bbeb7e637140ce038998868cd49a41e63fc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-dev-pre-convestaion-events/msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/subscribe-to-conversation-events?branch=pr-en-us-6378) |
[msteams-platform/resources/messaging-extension-v3/create-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-dev-pre-convestaion-events/msteams-platform/resources/messaging-extension-v3/create-extensions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/messaging-extension-v3/create-extensions?branch=pr-en-us-6378) |
[msteams-platform/resources/moodle-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-dev-pre-convestaion-events/msteams-platform/resources/moodle-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/moodle-overview?branch=pr-en-us-6378) |
[msteams-platform/samples/virtual-assistant.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-dev-pre-convestaion-events/msteams-platform/samples/virtual-assistant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/samples/virtual-assistant?branch=pr-en-us-6378) |
[msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-dev-pre-convestaion-events/msteams-platform/whats-new.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/whats-new?branch=pr-en-us-6378) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202207080340079150-6378/BuildReport?accessString=b9c2b2c18feccca60ac1722196c40d980c5e82617dbf0de976ef524b4387ade0).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-08 03:49 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/84837ae2f559e8f4a3fa8cc22fa9ca0ee284a8dd/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsubscribe-to-conversation-events.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/71bd66f3-7a47-41b8-b014-b5ce50e5d733) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/messaging-extension-v3/create-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/84837ae2f559e8f4a3fa8cc22fa9ca0ee284a8dd/msteams-platform%2Fresources%2Fmessaging-extension-v3%2Fcreate-extensions.md) | 89 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/73d64668-9256-44dd-abe1-7eb272230f04) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/moodle-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/84837ae2f559e8f4a3fa8cc22fa9ca0ee284a8dd/msteams-platform%2Fresources%2Fmoodle-overview.md) | 95 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dff4f4c2-f8f4-4fe1-9aa6-dcd47fa79f2f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/virtual-assistant.md](https://github.com/MicrosoftDocs/msteams-docs/blob/84837ae2f559e8f4a3fa8cc22fa9ca0ee284a8dd/msteams-platform%2Fsamples%2Fvirtual-assistant.md) | 84 | 33 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/165fdcfe-ebff-4932-a772-253f11776af9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/84837ae2f559e8f4a3fa8cc22fa9ca0ee284a8dd/msteams-platform%2Fwhats-new.md) | 91 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e63491e7-c7e6-4e24-bf4c-52797a792ea0) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-07-08 03:50 UTC, opbld31 commented
Docs Build status updates of commit _[84837ae](https://github.com/MicrosoftDocs/msteams-docs/commits/84837ae2f559e8f4a3fa8cc22fa9ca0ee284a8dd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-dev-pre-convestaion-events/msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/subscribe-to-conversation-events?branch=pr-en-us-6378) |
[msteams-platform/resources/messaging-extension-v3/create-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-dev-pre-convestaion-events/msteams-platform/resources/messaging-extension-v3/create-extensions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/messaging-extension-v3/create-extensions?branch=pr-en-us-6378) |
[msteams-platform/resources/moodle-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-dev-pre-convestaion-events/msteams-platform/resources/moodle-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/resources/moodle-overview?branch=pr-en-us-6378) |
[msteams-platform/samples/virtual-assistant.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-dev-pre-convestaion-events/msteams-platform/samples/virtual-assistant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/samples/virtual-assistant?branch=pr-en-us-6378) |
[msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-dev-pre-convestaion-events/msteams-platform/whats-new.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/whats-new?branch=pr-en-us-6378) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202207080349000833-6378/BuildReport?accessString=ecebba1334bd2dd504f24d930d8cad6a5aa67861ef45e932b07eb555bbd7d5ee).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-08 04:06 UTC, surbhigupta12 commented on msteams-platform/resources/moodle-overview.md
> +* **Personalize meeting panels**: Create unique collaborative learning experiences using Teams Graph API endpoints. For other more plans or projects, users can interview all new recruits and categori
@v-habibaumme 

No sure why this file is even part of this PR.

Please remove it.

2022-07-18 11:37 UTC, closed without merging