[Doc Improvement][Build Bots][Req. ID]
MicrosoftDocs/msteams-docs pull request #6415
Opened 2022-07-08 11:31 UTC by v-pooyadav

2022-07-08 11:31 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c326c85599e761e2c2107e14f1466b5852c0d9b1/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 93 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8bf0bc6d-6994-4417-9655-5ac7b11cc951) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-07-08 11:32 UTC, opbld32 commented
Docs Build status updates of commit _[c326c85](https://github.com/MicrosoftDocs/msteams-docs/commits/c326c85599e761e2c2107e14f1466b5852c0d9b1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/what-are-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/what-are-bots?branch=pr-en-us-6415) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202207081131207224-6415/BuildReport?accessString=07b6941003007ed2a9baa1fcc32f30a6a020e9ef7d1510986ac405759ba642d6).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-11 07:51 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/260915f69bfc1dc26c426c8944253d8949872fb6/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 93 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ded9b796-4889-4383-b5fc-7b991eadddd7) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-07-11 07:52 UTC, opbld30 commented
Docs Build status updates of commit _[260915f](https://github.com/MicrosoftDocs/msteams-docs/commits/260915f69bfc1dc26c426c8944253d8949872fb6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/what-are-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/what-are-bots?branch=pr-en-us-6415) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202207110751277599-6415/BuildReport?accessString=69d9200d2d1baa74b68fa82b90ad169dcee7b741ebc294ea02e1bca70f94c2f4).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-11 10:01 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c5c7fe2dac224f5d35bb764fcf62f39af74da8f1/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d7d17f24-55c5-44c4-8ad9-90def69ac675) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-07-11 10:02 UTC, opbld31 commented
Docs Build status updates of commit _[c5c7fe2](https://github.com/MicrosoftDocs/msteams-docs/commits/c5c7fe2dac224f5d35bb764fcf62f39af74da8f1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/what-are-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/what-are-bots?branch=pr-en-us-6415) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202207111000599561-6415/BuildReport?accessString=d6533fc10864aebdeb906a4c15f96e7623be2eacb08078db7f8c17d7fbfc9bbe).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-11 10:43 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ed03ab48f7eba329526a96038f5a50381af1619c/msteams-platform%2Fbots%2Fbot-features.md) | 90 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/674c1500-684c-44fe-91a9-f11f38c833f5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ed03ab48f7eba329526a96038f5a50381af1619c/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/96f40af3-0dc1-4863-b88d-e604c8ddff13) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-07-11 10:44 UTC, opbld32 commented
Docs Build status updates of commit _[ed03ab4](https://github.com/MicrosoftDocs/msteams-docs/commits/ed03ab48f7eba329526a96038f5a50381af1619c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-features.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-features?branch=pr-en-us-6415) |
[msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/what-are-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/what-are-bots?branch=pr-en-us-6415) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202207111043084834-6415/BuildReport?accessString=ceb372ce84b5cdfd7e20f8e7fe84e20d723e6478db3acd64559311b27c6e7e87).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-13 05:18 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6a1f6d99b9220d0b6ff119486e5290e6f60e8cee/msteams-platform%2Fbots%2Fbot-features.md) | 90 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d529f38d-77ba-4bef-b686-faa657177877) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6a1f6d99b9220d0b6ff119486e5290e6f60e8cee/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/82a22a9e-e259-4341-ac61-e0088c6b8fbf) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-07-13 05:18 UTC, opbld30 commented
Docs Build status updates of commit _[6a1f6d9](https://github.com/MicrosoftDocs/msteams-docs/commits/6a1f6d99b9220d0b6ff119486e5290e6f60e8cee)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-features.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-features?branch=pr-en-us-6415) |
[msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/what-are-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/what-are-bots?branch=pr-en-us-6415) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202207130517459296-6415/BuildReport?accessString=0ffff381d7c35fcbe39778ad94261f66d74a5fcf622053b678514ea11ce4cbb7).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-13 06:51 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f2cb98a1cbda63525e727d0f19239b0519396c10/msteams-platform%2Fbots%2Fbot-features.md) | 88 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a75f6159-9d81-40b4-8825-6bb702421821) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f2cb98a1cbda63525e727d0f19239b0519396c10/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2f20d740-6968-4bbd-adad-5ad6b23a2742) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-07-13 06:52 UTC, opbld31 commented
Docs Build status updates of commit _[f2cb98a](https://github.com/MicrosoftDocs/msteams-docs/commits/f2cb98a1cbda63525e727d0f19239b0519396c10)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-features.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-features?branch=pr-en-us-6415) |
[msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/what-are-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/what-are-bots?branch=pr-en-us-6415) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202207130651179754-6415/BuildReport?accessString=ad1600f545bab139676aa7a32204132d1a4fa0914cd37d6d837270d23b6d7472).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-14 06:44 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ceefb9016ce11e2f5fcdda7ab93c0e07e1f012fe/msteams-platform%2Fbots%2Fbot-features.md) | 88 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7554c27b-6e32-42b0-9583-d33937315ad1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ceefb9016ce11e2f5fcdda7ab93c0e07e1f012fe/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0996765f-d2c6-42da-ac78-38cfc6c56139) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-07-14 06:45 UTC, opbld31 commented
Docs Build status updates of commit _[ceefb90](https://github.com/MicrosoftDocs/msteams-docs/commits/ceefb9016ce11e2f5fcdda7ab93c0e07e1f012fe)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-features.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-features?branch=pr-en-us-6415) |
[msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/what-are-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/what-are-bots?branch=pr-en-us-6415) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202207140644172005-6415/BuildReport?accessString=73fca540cc0a8e8d6d65590098220a5f76bebbcc5b58a43571114f772a70dee3).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-14 07:21 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bd7397e8339c1cdbdbc33cb737d0b98dfcf34380/msteams-platform%2Fbots%2Fbot-basics.md) | 88 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a297ccb0-48a5-47db-af38-ac6f7005b7da) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bd7397e8339c1cdbdbc33cb737d0b98dfcf34380/msteams-platform%2Fbots%2Fbot-features.md) | 88 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e7cdd64c-28ad-4502-9952-5297487afa78) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bd7397e8339c1cdbdbc33cb737d0b98dfcf34380/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4cb93c85-0c8e-49f0-8671-d82bba57fa31) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-07-14 07:21 UTC, opbld31 commented
Docs Build status updates of commit _[bd7397e](https://github.com/MicrosoftDocs/msteams-docs/commits/bd7397e8339c1cdbdbc33cb737d0b98dfcf34380)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-basics?branch=pr-en-us-6415) |
[msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-features.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-features?branch=pr-en-us-6415) |
[msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/what-are-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/what-are-bots?branch=pr-en-us-6415) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202207140720321378-6415/BuildReport?accessString=5568eb6cbeab9a545240d561b2ca303ac66e109bdf89f2543035de65cc41fcac).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-14 07:22 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/69f3cf84b1665c7a00684d9e22a31853f1f99a38/msteams-platform%2Fbots%2Fbot-basics.md) | 88 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c41f9508-2d3b-40a4-aa49-5b76e27c5550) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/69f3cf84b1665c7a00684d9e22a31853f1f99a38/msteams-platform%2Fbots%2Fbot-features.md) | 88 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/afe95677-2c20-4225-8a1c-42ebc2917641) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/69f3cf84b1665c7a00684d9e22a31853f1f99a38/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/667f2364-1f49-49ef-9cf9-630e3c6e703f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-07-14 07:23 UTC, opbld30 commented
Docs Build status updates of commit _[69f3cf8](https://github.com/MicrosoftDocs/msteams-docs/commits/69f3cf84b1665c7a00684d9e22a31853f1f99a38)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-basics?branch=pr-en-us-6415) |
[msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-features.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-features?branch=pr-en-us-6415) |
[msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/what-are-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/what-are-bots?branch=pr-en-us-6415) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202207140722078052-6415/BuildReport?accessString=833b7a0bcffc91ea6ea3dbf16571c8fd104d80113b9899984a1aa9a5164e0d04).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-14 08:31 UTC, opbld30 commented
Docs Build status updates of commit _[3086e6f](https://github.com/MicrosoftDocs/msteams-docs/commits/3086e6fc55805091da3aadc42b7c4202bdda12ad)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-basics?branch=pr-en-us-6415) |
[msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-features.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-features?branch=pr-en-us-6415) |
[msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/what-are-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/what-are-bots?branch=pr-en-us-6415) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202207140829338892-6415/BuildReport?accessString=986c76810e85b88bd33328f502a405a7b457546981471b7c0a8c509650ae8ab1).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-15 09:47 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2eebc75fac4700f95aa6d3b6bf3e81413c149fd4/msteams-platform%2Fbots%2Fbot-basics.md) | 88 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7d7bc334-2021-46be-b474-3b65cac37c84) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2eebc75fac4700f95aa6d3b6bf3e81413c149fd4/msteams-platform%2Fbots%2Fbot-features.md) | 88 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c41afb4f-a19a-4981-9442-ea7016a399c1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2eebc75fac4700f95aa6d3b6bf3e81413c149fd4/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9bd79f68-e903-4cfc-9158-0c78f0de7b43) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-07-18 04:08 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/df53c138993ed4b8cca5e550ad369ad451d32ede/msteams-platform%2Fbots%2Fbot-basics.md) | 88 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6c138df9-3a96-4499-bcf8-da836c85f12b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/df53c138993ed4b8cca5e550ad369ad451d32ede/msteams-platform%2Fbots%2Fbot-features.md) | 88 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/50c7b448-1690-4a3b-a9f3-1688c694f9e6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/df53c138993ed4b8cca5e550ad369ad451d32ede/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-basics.md) | 87 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0a39e6ab-6532-4469-bb4c-e625e648e22c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/df53c138993ed4b8cca5e550ad369ad451d32ede/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b8063713-528e-48e2-9d43-459dc9e0f118) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-07-18 04:08 UTC, opbld32 commented
Docs Build status updates of commit _[ea7d5d7](https://github.com/MicrosoftDocs/msteams-docs/commits/ea7d5d79d2e9100b4419511bad0d9a98a2ebde2b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-basics?branch=pr-en-us-6415) |
[msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-features.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-features?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/conversation-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-basics?branch=pr-en-us-6415) |
[msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/what-are-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/what-are-bots?branch=pr-en-us-6415) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202207180407480990-6415/BuildReport?accessString=38685f7ebe89b1893c28417d74c0d11ba5824993a713fa3b009d4d87ddcb20d8).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-18 04:08 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/df53c138993ed4b8cca5e550ad369ad451d32ede/msteams-platform%2Fbots%2Fbot-basics.md) | 88 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bd32f1f4-d018-430d-a24b-81abf429e7c0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/df53c138993ed4b8cca5e550ad369ad451d32ede/msteams-platform%2Fbots%2Fbot-features.md) | 88 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b038cb59-3849-4cdf-a239-d93c51720ed9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/df53c138993ed4b8cca5e550ad369ad451d32ede/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-basics.md) | 87 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3c54cf23-990f-486d-acf1-ce857e348cd8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/df53c138993ed4b8cca5e550ad369ad451d32ede/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0f708873-54cb-4b00-a634-47c3c35b7b85) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-07-18 04:09 UTC, opbld33 commented
Docs Build status updates of commit _[df53c13](https://github.com/MicrosoftDocs/msteams-docs/commits/df53c138993ed4b8cca5e550ad369ad451d32ede)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-basics?branch=pr-en-us-6415) |
[msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-features.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-features?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/conversation-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-basics?branch=pr-en-us-6415) |
[msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/what-are-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/what-are-bots?branch=pr-en-us-6415) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202207180408067403-6415/BuildReport?accessString=dee9fdd8ace352be344d659cac3fd0a11ef4a729a2942d944904f7975ea5f485).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-18 04:25 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/407593ba437d63bf6a1cb37fd1877b6fd1205e2b/msteams-platform%2Fbots%2Fbot-basics.md) | 88 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f86e2343-4bf9-42a9-b53b-79d2b474d71b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/407593ba437d63bf6a1cb37fd1877b6fd1205e2b/msteams-platform%2Fbots%2Fbot-features.md) | 88 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/67c77ec1-57ee-4c65-8559-9521a52a9f2d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/407593ba437d63bf6a1cb37fd1877b6fd1205e2b/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-basics.md) | 87 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cfda0100-d4dc-4abf-96e1-1ceb850bd55d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/407593ba437d63bf6a1cb37fd1877b6fd1205e2b/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-messages.md) | 97 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8f2dd623-481e-487b-9461-358d3387a247) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/407593ba437d63bf6a1cb37fd1877b6fd1205e2b/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/470850c7-3026-4714-9f46-725c53eec588) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-07-18 04:26 UTC, opbld31 commented
Docs Build status updates of commit _[407593b](https://github.com/MicrosoftDocs/msteams-docs/commits/407593ba437d63bf6a1cb37fd1877b6fd1205e2b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-basics?branch=pr-en-us-6415) |
[msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-features.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-features?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/conversation-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-basics?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/conversation-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-messages?branch=pr-en-us-6415) |
[msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/what-are-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/what-are-bots?branch=pr-en-us-6415) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202207180425113264-6415/BuildReport?accessString=c335b638a06aa8fd75fa6669fee73652a356340371e71bc339366251b8b485e4).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-18 08:47 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8af7a9f5f332271faada2d012d7c0452ee2e9d3b/msteams-platform%2Fbots%2Fbot-basics.md) | 88 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/998d9fb2-50bb-48d8-b157-76e460cac322) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8af7a9f5f332271faada2d012d7c0452ee2e9d3b/msteams-platform%2Fbots%2Fbot-features.md) | 88 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ca01d935-c8dd-4726-9729-9e93c540dad7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8af7a9f5f332271faada2d012d7c0452ee2e9d3b/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-basics.md) | 87 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/baf3da3e-61ba-4df3-bd03-df4e3e8bcb17) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8af7a9f5f332271faada2d012d7c0452ee2e9d3b/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-messages.md) | 97 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5413e71f-ab54-49f4-875e-6a49148c9267) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8af7a9f5f332271faada2d012d7c0452ee2e9d3b/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b7609b7d-5120-4708-b81b-ad6900fccacc) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-07-18 08:47 UTC, opbld30 commented
Docs Build status updates of commit _[8af7a9f](https://github.com/MicrosoftDocs/msteams-docs/commits/8af7a9f5f332271faada2d012d7c0452ee2e9d3b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-basics?branch=pr-en-us-6415) |
[msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-features.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-features?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/conversation-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-basics?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/conversation-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-messages?branch=pr-en-us-6415) |
[msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/what-are-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/what-are-bots?branch=pr-en-us-6415) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202207180846368500-6415/BuildReport?accessString=80386f370668981494a547c6bcea73df453d8c0fa91b637de587bed23a32fb53).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-18 08:51 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8b6afc1a60c7d372c91097e352167ea35cd1f57e/msteams-platform%2Fbots%2Fbot-basics.md) | 88 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/137bef6e-699f-4b22-afaa-e95e95904889) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8b6afc1a60c7d372c91097e352167ea35cd1f57e/msteams-platform%2Fbots%2Fbot-features.md) | 88 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/61914c78-41b5-4be7-a0b6-3cf5de534fed) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8b6afc1a60c7d372c91097e352167ea35cd1f57e/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-basics.md) | 87 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/04c9d6c5-d2e7-4a28-a5d6-67378d15e77a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8b6afc1a60c7d372c91097e352167ea35cd1f57e/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-messages.md) | 97 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9d69bc5b-5f7b-4556-9eec-4821ce3bcee4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8b6afc1a60c7d372c91097e352167ea35cd1f57e/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2019a846-9b0b-4092-a68d-e4b18973e960) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-07-18 08:51 UTC, opbld31 commented
Docs Build status updates of commit _[8b6afc1](https://github.com/MicrosoftDocs/msteams-docs/commits/8b6afc1a60c7d372c91097e352167ea35cd1f57e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-basics?branch=pr-en-us-6415) |
[msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-features.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-features?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/conversation-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-basics?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/conversation-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-messages?branch=pr-en-us-6415) |
[msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/what-are-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/what-are-bots?branch=pr-en-us-6415) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202207180851026356-6415/BuildReport?accessString=bed52b329479527795b9b416a98c87361b3b4992cd7cc1c7b6fdeeb9f4ab931f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-18 09:01 UTC, opbld31 commented
Docs Build status updates of commit _[03648a6](https://github.com/MicrosoftDocs/msteams-docs/commits/03648a6ec57154c20425877dfc4ab8c44498704d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-basics?branch=pr-en-us-6415) |
[msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-features.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-features?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/conversation-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-basics?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/conversation-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-messages?branch=pr-en-us-6415) |
[msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/what-are-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/what-are-bots?branch=pr-en-us-6415) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202207180900355570-6415/BuildReport?accessString=d30b2f981330401774e03119e457f210b0377f67c77e82dc6891a63fd3492be9).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-18 09:01 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/03648a6ec57154c20425877dfc4ab8c44498704d/msteams-platform%2Fbots%2Fbot-basics.md) | 88 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/953ab9d2-ca28-41bf-942b-2324e71f73dd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/03648a6ec57154c20425877dfc4ab8c44498704d/msteams-platform%2Fbots%2Fbot-features.md) | 88 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d6642098-dc09-48ae-b890-bda01a29bdfb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/03648a6ec57154c20425877dfc4ab8c44498704d/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-basics.md) | 84 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7f9b1e65-4447-402c-8abc-47abf1537c29) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/03648a6ec57154c20425877dfc4ab8c44498704d/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-messages.md) | 97 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1b35dcd9-0f34-4fa8-9aed-913cbf8e6b22) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/03648a6ec57154c20425877dfc4ab8c44498704d/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6d8d49a8-9349-4d94-82d0-da8f0cce2c25) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-07-19 10:41 UTC, opbld32 commented
Docs Build status updates of commit _[904e950](https://github.com/MicrosoftDocs/msteams-docs/commits/904e9505d0dd69d3f131dd160a7764cc93cbf8fe)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-basics?branch=pr-en-us-6415) |
[msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-features.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-features?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/conversation-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-basics?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/conversation-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-messages?branch=pr-en-us-6415) |
[msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/what-are-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/what-are-bots?branch=pr-en-us-6415) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202207191040221141-6415/BuildReport?accessString=156714dfd4feee11e00c7bcfa598b6b21df864d355a2ea95ceb769d3b03e3741).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-19 10:41 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/904e9505d0dd69d3f131dd160a7764cc93cbf8fe/msteams-platform%2Fbots%2Fbot-basics.md) | 88 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/902e2f77-82ad-4e24-8980-4faaf8088320) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/904e9505d0dd69d3f131dd160a7764cc93cbf8fe/msteams-platform%2Fbots%2Fbot-features.md) | 88 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1f2010a7-bbd1-46d1-a122-ec387041ccbc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/904e9505d0dd69d3f131dd160a7764cc93cbf8fe/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-basics.md) | 84 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0e4be029-7942-4f7a-85df-b70942575526) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/904e9505d0dd69d3f131dd160a7764cc93cbf8fe/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-messages.md) | 97 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6b1154ff-4797-4d1f-9445-1792c218447b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/904e9505d0dd69d3f131dd160a7764cc93cbf8fe/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6b492424-4743-4f98-be60-55ad4a53df49) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-07-19 10:41 UTC, opbld33 commented
Docs Build status updates of commit _[b1f72ed](https://github.com/MicrosoftDocs/msteams-docs/commits/b1f72ed47454132ff50ba246b5cd26fd225c4847)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-basics?branch=pr-en-us-6415) |
[msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-features.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-features?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/conversation-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-basics?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/conversation-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-messages?branch=pr-en-us-6415) |
[msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/what-are-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/what-are-bots?branch=pr-en-us-6415) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202207191040466893-6415/BuildReport?accessString=413b803b1595495f546ef0ccae18256568aeb405db067f933f18103537dc0b19).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-19 10:41 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b1f72ed47454132ff50ba246b5cd26fd225c4847/msteams-platform%2Fbots%2Fbot-basics.md) | 88 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7a378390-77af-4715-b876-2cb9a921cd3f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b1f72ed47454132ff50ba246b5cd26fd225c4847/msteams-platform%2Fbots%2Fbot-features.md) | 88 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/870cc625-c8be-41ec-ba5d-f260e7817a30) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b1f72ed47454132ff50ba246b5cd26fd225c4847/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-basics.md) | 84 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0d9755b1-63d1-47a4-b605-2e3b2c447dd6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b1f72ed47454132ff50ba246b5cd26fd225c4847/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-messages.md) | 97 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/271d527b-a08e-4b1d-a527-025584f78d79) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b1f72ed47454132ff50ba246b5cd26fd225c4847/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a7d4cb93-2bd8-4936-9759-0f55b86d9174) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-07-20 05:31 UTC, opbld30 commented
Docs Build status updates of commit _[d6f057c](https://github.com/MicrosoftDocs/msteams-docs/commits/d6f057c7705bb369411338cfc90379109faa0b95)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-basics?branch=pr-en-us-6415) |
[msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-features.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-features?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/conversation-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-basics?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/conversation-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-messages?branch=pr-en-us-6415) |
[msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/what-are-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/what-are-bots?branch=pr-en-us-6415) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202207200531172956-6415/BuildReport?accessString=0c54232877f8fc5076ddd0b60facc86b2d9d8573b8b2ec9e284d75ec09e9e33d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-20 05:32 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d6f057c7705bb369411338cfc90379109faa0b95/msteams-platform%2Fbots%2Fbot-basics.md) | 88 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0da1836b-6f26-42c1-abf7-ca874c09eb46) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d6f057c7705bb369411338cfc90379109faa0b95/msteams-platform%2Fbots%2Fbot-features.md) | 88 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3b84c508-e1d7-4bd1-b02c-6139867c96fd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d6f057c7705bb369411338cfc90379109faa0b95/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-basics.md) | 84 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/80739204-3971-4994-8050-39b1c21037db) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d6f057c7705bb369411338cfc90379109faa0b95/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-messages.md) | 97 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a1d1739a-60d4-4aec-ab2d-29743b07e942) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d6f057c7705bb369411338cfc90379109faa0b95/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7eadc386-0354-4a05-9a2e-2fdfeacec870) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-07-20 08:13 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9bedefa6d68919efc257b2b9526db246a724dd8a/msteams-platform%2Fbots%2Fbot-basics.md) | 88 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b02893a6-5045-4bf2-b3db-d9fdab0ac43f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9bedefa6d68919efc257b2b9526db246a724dd8a/msteams-platform%2Fbots%2Fbot-features.md) | 88 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/52bd14b0-64fa-4b38-8f40-19abed653c68) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9bedefa6d68919efc257b2b9526db246a724dd8a/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aa564aa2-c9ed-4f1e-b904-399131135f1c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9bedefa6d68919efc257b2b9526db246a724dd8a/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-basics.md) | 84 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/05da5c34-a5e9-4bf0-bc93-b73a0fa9a7a4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9bedefa6d68919efc257b2b9526db246a724dd8a/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-messages.md) | 97 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7ba0ecbf-510c-4b54-8e9b-09fdd8342d45) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9bedefa6d68919efc257b2b9526db246a724dd8a/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6b206fdc-36fa-46c4-8548-f241a15b8026) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-07-20 08:17 UTC, opbld32 commented
Docs Build status updates of commit _[9bedefa](https://github.com/MicrosoftDocs/msteams-docs/commits/9bedefa6d68919efc257b2b9526db246a724dd8a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-basics?branch=pr-en-us-6415) |
[msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-features.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-features?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/channel-messages-with-rsc?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/conversation-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-basics?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/conversation-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-messages?branch=pr-en-us-6415) |
[msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/what-are-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/what-are-bots?branch=pr-en-us-6415) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202207200815324663-6415/BuildReport?accessString=64eb698370da237ce4c89c960711fce3ccebda6cf38c1ee1f001c8cc15a6989a).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-21 02:42 UTC, opbld31 commented
Docs Build status updates of commit _[7bd2c3e](https://github.com/MicrosoftDocs/msteams-docs/commits/7bd2c3e8e423987fe7900ab573ec9a83804afb02)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-aed819f2)

<a id="aed819f2"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202207210241587405-6415/BuildReport?accessString=3052b9f645a6a4b87cd146e18468d1986c5fe95b4ebd307b2cadef808ebb01a0).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-21 02:42 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7bd2c3e8e423987fe7900ab573ec9a83804afb02/msteams-platform%2Fbots%2Fbot-basics.md) | 88 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8b07b3dd-bba7-4416-86fa-7131efe6c3be) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7bd2c3e8e423987fe7900ab573ec9a83804afb02/msteams-platform%2Fbots%2Fbot-features.md) | 88 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/39a587e9-142c-4f60-9c9b-ad6bf700b2a8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7bd2c3e8e423987fe7900ab573ec9a83804afb02/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ecb6694a-6a96-451d-a299-e3d354f64da6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7bd2c3e8e423987fe7900ab573ec9a83804afb02/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-basics.md) | 84 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d2fa861e-cdbb-4848-9a71-f32ef430ceb2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7bd2c3e8e423987fe7900ab573ec9a83804afb02/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-messages.md) | 97 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4d97a344-ae49-46ac-9460-49744b47ff16) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/create-a-bot-commands-menu.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7bd2c3e8e423987fe7900ab573ec9a83804afb02/msteams-platform%2Fbots%2Fhow-to%2Fcreate-a-bot-commands-menu.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ef004c47-b842-43bc-b0cc-dbd94f823a2e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7bd2c3e8e423987fe7900ab573ec9a83804afb02/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/46be5850-fbe7-4284-8dde-b0e2411d5bd9) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-07-21 04:45 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5d00e6586e9599e1147f6dc39bdbe470cdb537d9/msteams-platform%2Fbots%2Fbot-basics.md) | 88 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a2d0efac-bbe6-49d9-a15b-c74d7e160471) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5d00e6586e9599e1147f6dc39bdbe470cdb537d9/msteams-platform%2Fbots%2Fbot-features.md) | 88 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a4d53b2e-5e5d-45fe-a339-03de7f8a1dcf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5d00e6586e9599e1147f6dc39bdbe470cdb537d9/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/87daa32a-325f-4aab-8f4a-19f8d29de609) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5d00e6586e9599e1147f6dc39bdbe470cdb537d9/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-basics.md) | 84 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1fe44edb-bda2-440b-962d-24c125862c34) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5d00e6586e9599e1147f6dc39bdbe470cdb537d9/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-messages.md) | 97 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bfaeab0c-a87e-48f6-afae-57d631003f92) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/create-a-bot-commands-menu.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5d00e6586e9599e1147f6dc39bdbe470cdb537d9/msteams-platform%2Fbots%2Fhow-to%2Fcreate-a-bot-commands-menu.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/204c37ac-1ac8-4741-80d0-4b7cb28b1a77) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5d00e6586e9599e1147f6dc39bdbe470cdb537d9/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 92 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ea039346-2654-4796-8007-13e105578869) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-07-21 04:45 UTC, opbld33 commented
Docs Build status updates of commit _[5d00e65](https://github.com/MicrosoftDocs/msteams-docs/commits/5d00e6586e9599e1147f6dc39bdbe470cdb537d9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-basics?branch=pr-en-us-6415) |
[msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-features.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-features?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/channel-messages-with-rsc?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/conversation-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-basics?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/conversation-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-messages?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/create-a-bot-commands-menu.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/create-a-bot-commands-menu.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/create-a-bot-commands-menu?branch=pr-en-us-6415) |
[msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/what-are-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/what-are-bots?branch=pr-en-us-6415) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202207210444501393-6415/BuildReport?accessString=5c707d18109dd9eb5bff9dcf397492a38185ba14329e7c48435e373cc83bb241).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-21 06:05 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f3a6134324ef753d9b5a14f43f5ef31fe6df2ed5/msteams-platform%2Fbots%2Fbot-basics.md) | 88 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/60e48558-e861-4367-8eb0-7e082d6136e1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f3a6134324ef753d9b5a14f43f5ef31fe6df2ed5/msteams-platform%2Fbots%2Fbot-features.md) | 88 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f8d94580-4309-4263-83a8-0e2acd488f55) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f3a6134324ef753d9b5a14f43f5ef31fe6df2ed5/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b65d4f24-04fe-43d2-bbf1-657708919d48) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f3a6134324ef753d9b5a14f43f5ef31fe6df2ed5/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-basics.md) | 84 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fba699e5-0203-4f32-b4f8-1d5bb8d63b94) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f3a6134324ef753d9b5a14f43f5ef31fe6df2ed5/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-messages.md) | 97 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/011afe5c-2dde-443c-8c33-5a55a49291e5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/create-a-bot-commands-menu.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f3a6134324ef753d9b5a14f43f5ef31fe6df2ed5/msteams-platform%2Fbots%2Fhow-to%2Fcreate-a-bot-commands-menu.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3bda6381-1e55-4a7c-8ace-46527b308f2e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f3a6134324ef753d9b5a14f43f5ef31fe6df2ed5/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 92 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/675b3931-3089-4334-a75f-50c0b89a651a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-07-21 06:06 UTC, opbld33 commented
Docs Build status updates of commit _[f3a6134](https://github.com/MicrosoftDocs/msteams-docs/commits/f3a6134324ef753d9b5a14f43f5ef31fe6df2ed5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-basics?branch=pr-en-us-6415) |
[msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-features.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-features?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/channel-messages-with-rsc?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/conversation-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-basics?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/conversation-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-messages?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/create-a-bot-commands-menu.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/create-a-bot-commands-menu.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/create-a-bot-commands-menu?branch=pr-en-us-6415) |
[msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/what-are-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/what-are-bots?branch=pr-en-us-6415) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202207210605014244-6415/BuildReport?accessString=15d62bf8796f682573714904eea27c1738e46c0ba2778a890f35c1f814f09811).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-21 06:18 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0f55948726862508a29ac208fbc44c66176bc18b/msteams-platform%2Fbots%2Fbot-basics.md) | 88 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a6b868b4-6e8a-4c6f-acc9-80a74854d08f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0f55948726862508a29ac208fbc44c66176bc18b/msteams-platform%2Fbots%2Fbot-features.md) | 88 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/13d50692-7084-4f61-a2bc-022a76188768) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0f55948726862508a29ac208fbc44c66176bc18b/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/87b14fa8-7aaf-4d4f-a1b2-10462837a2b7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0f55948726862508a29ac208fbc44c66176bc18b/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/62804c4b-44f8-48b0-b559-7097103d1fab) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0f55948726862508a29ac208fbc44c66176bc18b/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-basics.md) | 84 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/88a276a7-3182-4aff-8643-e6cd354fc8fd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0f55948726862508a29ac208fbc44c66176bc18b/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-messages.md) | 97 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/292a62a6-ca13-47f3-bdd3-e5aa7986f348) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/create-a-bot-commands-menu.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0f55948726862508a29ac208fbc44c66176bc18b/msteams-platform%2Fbots%2Fhow-to%2Fcreate-a-bot-commands-menu.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/61da6d05-7b7e-48c6-a907-f3da765660aa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0f55948726862508a29ac208fbc44c66176bc18b/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 92 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/83bb982e-6068-42f2-b38b-e669879bfa06) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-07-21 06:19 UTC, opbld33 commented
Docs Build status updates of commit _[0f55948](https://github.com/MicrosoftDocs/msteams-docs/commits/0f55948726862508a29ac208fbc44c66176bc18b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-basics?branch=pr-en-us-6415) |
[msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-features.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-features?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/channel-and-group-conversations?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/channel-messages-with-rsc?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/conversation-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-basics?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/conversation-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-messages?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/create-a-bot-commands-menu.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/create-a-bot-commands-menu.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/create-a-bot-commands-menu?branch=pr-en-us-6415) |
[msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/what-are-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/what-are-bots?branch=pr-en-us-6415) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202207210617432935-6415/BuildReport?accessString=584213f23e3ad20b5392411a508fe576e8f83ac7a3f44f235b2736850c5e2e3a).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-21 07:13 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/af83546e1580ec86a342e95d467b5f773559b2c9/msteams-platform%2Fbots%2Fbot-basics.md) | 88 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/72215fa7-fbae-4ecd-8c53-9ab24292f22d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/af83546e1580ec86a342e95d467b5f773559b2c9/msteams-platform%2Fbots%2Fbot-features.md) | 88 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c5bd8a34-70b6-4dec-8ff2-f4d2aae2ccaf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/af83546e1580ec86a342e95d467b5f773559b2c9/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/33e5e131-0e04-4201-9563-376de121bb77) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/af83546e1580ec86a342e95d467b5f773559b2c9/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/44e6b022-d6cb-4c97-9921-07fe9620b526) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/af83546e1580ec86a342e95d467b5f773559b2c9/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-basics.md) | 84 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6b6f2a75-f38a-4254-bfbb-7a203a13ee5d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/af83546e1580ec86a342e95d467b5f773559b2c9/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-messages.md) | 97 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/116f7ec1-fdda-4aeb-872c-05a72992e68c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/af83546e1580ec86a342e95d467b5f773559b2c9/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsubscribe-to-conversation-events.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cd9a6b53-132f-489a-b79c-a7f8fec96a64) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/create-a-bot-commands-menu.md](https://github.com/MicrosoftDocs/msteams-docs/blob/af83546e1580ec86a342e95d467b5f773559b2c9/msteams-platform%2Fbots%2Fhow-to%2Fcreate-a-bot-commands-menu.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b170a112-c780-4251-9bdd-230d406fab86) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/af83546e1580ec86a342e95d467b5f773559b2c9/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 92 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b0f3c4e2-98cf-4e0b-b894-147a44941ba5) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-07-21 07:14 UTC, opbld32 commented
Docs Build status updates of commit _[af83546](https://github.com/MicrosoftDocs/msteams-docs/commits/af83546e1580ec86a342e95d467b5f773559b2c9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-basics?branch=pr-en-us-6415) |
[msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-features.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-features?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/channel-and-group-conversations?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/channel-messages-with-rsc?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/conversation-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-basics?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/conversation-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-messages?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/subscribe-to-conversation-events?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/create-a-bot-commands-menu.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/create-a-bot-commands-menu.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/create-a-bot-commands-menu?branch=pr-en-us-6415) |
[msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/what-are-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/what-are-bots?branch=pr-en-us-6415) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202207210713043867-6415/BuildReport?accessString=4d5b3b1a54f67ff093dd32c47a0bf5a5aa02732c3acad9da4ef69aeb8d75cd63).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-21 07:40 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/39213b9ee3a2b7f7f92f8d5a5c7a6f61979cc06a/msteams-platform%2Fbots%2Fbot-basics.md) | 88 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9a16ed6c-c5c9-4ba5-95ad-6c2d0ca8992b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/39213b9ee3a2b7f7f92f8d5a5c7a6f61979cc06a/msteams-platform%2Fbots%2Fbot-features.md) | 88 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/464b2abb-5654-48c8-93fc-a540b3553ab1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/39213b9ee3a2b7f7f92f8d5a5c7a6f61979cc06a/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f8d54d2a-d5fe-4e9b-8e91-2618c1ff444b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/39213b9ee3a2b7f7f92f8d5a5c7a6f61979cc06a/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c891980e-55cd-462a-83d4-77f99d298759) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/39213b9ee3a2b7f7f92f8d5a5c7a6f61979cc06a/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-basics.md) | 84 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3c8e7e7f-dd7e-4c6e-a81e-519a352af105) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/39213b9ee3a2b7f7f92f8d5a5c7a6f61979cc06a/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-messages.md) | 97 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fa83926e-9a6c-419f-b5d1-ba39ecb7fae5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/39213b9ee3a2b7f7f92f8d5a5c7a6f61979cc06a/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsubscribe-to-conversation-events.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cfcfd57b-4182-4c17-b8bc-9ff05e9e0cfd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/create-a-bot-commands-menu.md](https://github.com/MicrosoftDocs/msteams-docs/blob/39213b9ee3a2b7f7f92f8d5a5c7a6f61979cc06a/msteams-platform%2Fbots%2Fhow-to%2Fcreate-a-bot-commands-menu.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aaabe062-4901-463d-aba4-513296646bab) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/39213b9ee3a2b7f7f92f8d5a5c7a6f61979cc06a/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 92 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b70dfe81-f36c-44d8-b25d-25ef97985de6) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-07-21 07:40 UTC, opbld33 commented
Docs Build status updates of commit _[39213b9](https://github.com/MicrosoftDocs/msteams-docs/commits/39213b9ee3a2b7f7f92f8d5a5c7a6f61979cc06a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-basics?branch=pr-en-us-6415) |
[msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-features.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-features?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/channel-and-group-conversations?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/channel-messages-with-rsc?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/conversation-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-basics?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/conversation-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-messages?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/subscribe-to-conversation-events?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/create-a-bot-commands-menu.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/create-a-bot-commands-menu.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/create-a-bot-commands-menu?branch=pr-en-us-6415) |
[msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/what-are-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/what-are-bots?branch=pr-en-us-6415) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202207210739387801-6415/BuildReport?accessString=02134084d0598b570fcbe741195cf14af6d2d0cb529c9d556431903f1dda7f8c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-21 09:16 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/597c22a1b5740a15ee00b56e70c0d4bdddb46970/msteams-platform%2Fbots%2Fbot-basics.md) | 88 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f50f4f87-1365-4857-a08a-f67c802f5147) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/597c22a1b5740a15ee00b56e70c0d4bdddb46970/msteams-platform%2Fbots%2Fbot-features.md) | 88 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/714557df-dd1b-4e5b-bb26-9c75227c4ac6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/597c22a1b5740a15ee00b56e70c0d4bdddb46970/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e3f6e254-c708-4527-aa58-14177aaeccd9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/597c22a1b5740a15ee00b56e70c0d4bdddb46970/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/67f5739f-af4c-436e-9e82-ef1d8f69068d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/597c22a1b5740a15ee00b56e70c0d4bdddb46970/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-basics.md) | 84 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e0b2a6aa-fe88-4b72-b8b7-d3ff27b21388) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/597c22a1b5740a15ee00b56e70c0d4bdddb46970/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-messages.md) | 96 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4cc9045d-55c0-47ec-a669-46848427cdbb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/597c22a1b5740a15ee00b56e70c0d4bdddb46970/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsubscribe-to-conversation-events.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b925e745-0ea0-4042-a854-11d53e50f260) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/create-a-bot-commands-menu.md](https://github.com/MicrosoftDocs/msteams-docs/blob/597c22a1b5740a15ee00b56e70c0d4bdddb46970/msteams-platform%2Fbots%2Fhow-to%2Fcreate-a-bot-commands-menu.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c3ba79a4-3d9e-424f-82db-2cae7bf96835) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/597c22a1b5740a15ee00b56e70c0d4bdddb46970/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 92 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/49ae2f42-5f5a-400f-8a67-1602c679ce32) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-07-21 09:16 UTC, opbld32 commented
Docs Build status updates of commit _[d0f9d1f](https://github.com/MicrosoftDocs/msteams-docs/commits/d0f9d1f3142bfb5b989a323143ff4f255dfb6676)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-basics?branch=pr-en-us-6415) |
[msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-features.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-features?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/channel-and-group-conversations?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/channel-messages-with-rsc?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/conversation-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-basics?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/conversation-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-messages?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/subscribe-to-conversation-events?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/create-a-bot-commands-menu.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/create-a-bot-commands-menu.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/create-a-bot-commands-menu?branch=pr-en-us-6415) |
[msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/what-are-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/what-are-bots?branch=pr-en-us-6415) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202207210915282855-6415/BuildReport?accessString=6d56f3abc9cc754cf5ffc1164a55e96d950f39c74fbf892a831f40337316b6ba).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-21 09:16 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/597c22a1b5740a15ee00b56e70c0d4bdddb46970/msteams-platform%2Fbots%2Fbot-basics.md) | 88 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7ea0fa39-9b41-485c-858e-2bf76e0a2646) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/597c22a1b5740a15ee00b56e70c0d4bdddb46970/msteams-platform%2Fbots%2Fbot-features.md) | 88 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cdcef466-af53-44b3-810e-03fe6d1ba63a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/597c22a1b5740a15ee00b56e70c0d4bdddb46970/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8c04698a-3c51-4e48-aaac-7caf354d2c0e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/597c22a1b5740a15ee00b56e70c0d4bdddb46970/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e246e939-2861-48e4-9eab-fb1e309bd952) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/597c22a1b5740a15ee00b56e70c0d4bdddb46970/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-basics.md) | 84 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/008c9525-10f6-46bd-a5d6-fa716d490eb2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/597c22a1b5740a15ee00b56e70c0d4bdddb46970/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-messages.md) | 96 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d4027b70-31a2-4c93-9831-61be15551e4d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/597c22a1b5740a15ee00b56e70c0d4bdddb46970/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsubscribe-to-conversation-events.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f6fc34b0-09ce-41bf-ac2a-e637fab0b3ac) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/create-a-bot-commands-menu.md](https://github.com/MicrosoftDocs/msteams-docs/blob/597c22a1b5740a15ee00b56e70c0d4bdddb46970/msteams-platform%2Fbots%2Fhow-to%2Fcreate-a-bot-commands-menu.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2b1fbf7c-99a2-4200-8462-acb1d3ac042a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/597c22a1b5740a15ee00b56e70c0d4bdddb46970/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 92 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/86b78334-1add-48c4-b667-caf35e8c0215) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-07-21 09:17 UTC, opbld30 commented
Docs Build status updates of commit _[597c22a](https://github.com/MicrosoftDocs/msteams-docs/commits/597c22a1b5740a15ee00b56e70c0d4bdddb46970)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-basics?branch=pr-en-us-6415) |
[msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-features.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-features?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/channel-and-group-conversations?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/channel-messages-with-rsc?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/conversation-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-basics?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/conversation-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-messages?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/subscribe-to-conversation-events?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/create-a-bot-commands-menu.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/create-a-bot-commands-menu.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/create-a-bot-commands-menu?branch=pr-en-us-6415) |
[msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/what-are-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/what-are-bots?branch=pr-en-us-6415) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202207210915461342-6415/BuildReport?accessString=15beb0b7f2c48406d5178d2deba6045ffb46682d79247347f6f96aaa2bdba7b4).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-21 10:10 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/53e2bae592a7052591f5b240568723015c8b28a2/msteams-platform%2Fbots%2Fbot-basics.md) | 88 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d0c114a1-e789-46e8-908a-1a649a9cf233) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/53e2bae592a7052591f5b240568723015c8b28a2/msteams-platform%2Fbots%2Fbot-features.md) | 88 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cd296270-0c31-49a3-b3a7-a3c1860f6938) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/53e2bae592a7052591f5b240568723015c8b28a2/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/07df7bb9-14c1-47be-a348-82962a230365) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/53e2bae592a7052591f5b240568723015c8b28a2/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e2b826ed-65c0-4cab-b1ac-797ea5ce534f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/53e2bae592a7052591f5b240568723015c8b28a2/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-basics.md) | 84 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/81b78f13-d167-4b9e-ba8f-9d1a81a8d8b3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/53e2bae592a7052591f5b240568723015c8b28a2/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-messages.md) | 96 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c9edfda8-7dfa-4176-96f9-2a812786c4a9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/53e2bae592a7052591f5b240568723015c8b28a2/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsubscribe-to-conversation-events.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/703d5e72-6a85-4796-9f9c-6b2eccd4d5de) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/create-a-bot-commands-menu.md](https://github.com/MicrosoftDocs/msteams-docs/blob/53e2bae592a7052591f5b240568723015c8b28a2/msteams-platform%2Fbots%2Fhow-to%2Fcreate-a-bot-commands-menu.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e4fee587-badf-4c92-af2b-d3ab91b23685) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/53e2bae592a7052591f5b240568723015c8b28a2/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 92 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ad5779b6-c44f-4c70-93f6-7ce23efee607) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-07-21 10:10 UTC, opbld33 commented
Docs Build status updates of commit _[53e2bae](https://github.com/MicrosoftDocs/msteams-docs/commits/53e2bae592a7052591f5b240568723015c8b28a2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-basics?branch=pr-en-us-6415) |
[msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-features.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-features?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/channel-and-group-conversations?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/channel-messages-with-rsc?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/conversation-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-basics?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/conversation-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-messages?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/subscribe-to-conversation-events?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/create-a-bot-commands-menu.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/create-a-bot-commands-menu.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/create-a-bot-commands-menu?branch=pr-en-us-6415) |
[msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/what-are-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/what-are-bots?branch=pr-en-us-6415) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202207211008421055-6415/BuildReport?accessString=dbc02f0b9419318796c7defcbea7de0e483170c6f41de4756b8af574e0399d62).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-21 11:51 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a9482a9d3832672a634cdb62c4a8f27c632bd4f3/msteams-platform%2Fbots%2Fbot-basics.md) | 88 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6f162cae-61c6-44c1-84e9-1ce3eb9662a4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a9482a9d3832672a634cdb62c4a8f27c632bd4f3/msteams-platform%2Fbots%2Fbot-features.md) | 88 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bfd0f9e7-fdf4-4eee-98d6-d9cff96fd3b9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a9482a9d3832672a634cdb62c4a8f27c632bd4f3/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0d0c2f10-fa55-4bd9-a69f-657f7c6fa7a5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a9482a9d3832672a634cdb62c4a8f27c632bd4f3/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b4250946-6579-46e2-af2e-15526cfc4440) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a9482a9d3832672a634cdb62c4a8f27c632bd4f3/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-basics.md) | 84 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0a890b3b-d8f3-4a21-b3cb-50ccad8e7a3e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a9482a9d3832672a634cdb62c4a8f27c632bd4f3/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-messages.md) | 96 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b9860a1f-de60-4a32-9e2f-41b991d8f1c0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a9482a9d3832672a634cdb62c4a8f27c632bd4f3/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsubscribe-to-conversation-events.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6574f2cf-5710-41a2-86bc-c46af2816a2d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/create-a-bot-commands-menu.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a9482a9d3832672a634cdb62c4a8f27c632bd4f3/msteams-platform%2Fbots%2Fhow-to%2Fcreate-a-bot-commands-menu.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9233f3e8-1e68-47da-8664-326578e45484) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a9482a9d3832672a634cdb62c4a8f27c632bd4f3/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 92 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f226d8c2-b73c-43e0-96c3-95dbb10a7df1) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-07-21 11:52 UTC, opbld32 commented
Docs Build status updates of commit _[ba08740](https://github.com/MicrosoftDocs/msteams-docs/commits/ba08740b8b2dd6b233edf0a4cba4db06321e8b30)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-basics?branch=pr-en-us-6415) |
[msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-features.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-features?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/channel-and-group-conversations?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/channel-messages-with-rsc?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/conversation-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-basics?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/conversation-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-messages?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/subscribe-to-conversation-events?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/create-a-bot-commands-menu.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/create-a-bot-commands-menu.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/create-a-bot-commands-menu?branch=pr-en-us-6415) |
[msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/what-are-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/what-are-bots?branch=pr-en-us-6415) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202207211151080490-6415/BuildReport?accessString=e80c61cac292bed54952cc9311b060311165c5d9dd9b5877c0cd694ea33668d8).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-21 11:52 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a9482a9d3832672a634cdb62c4a8f27c632bd4f3/msteams-platform%2Fbots%2Fbot-basics.md) | 88 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0a2cc9e1-2b3f-4068-91bc-24a82d177fe4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a9482a9d3832672a634cdb62c4a8f27c632bd4f3/msteams-platform%2Fbots%2Fbot-features.md) | 88 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2d57567d-6ed4-4217-ada3-4993eb1c12c3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a9482a9d3832672a634cdb62c4a8f27c632bd4f3/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/97d7ae47-3bc2-4af9-97fc-b1a32d65b012) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a9482a9d3832672a634cdb62c4a8f27c632bd4f3/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ad046e31-50be-46eb-9078-dfd5e8371a2d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a9482a9d3832672a634cdb62c4a8f27c632bd4f3/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-basics.md) | 84 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0707019d-d2c9-428f-9214-af93cf913818) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a9482a9d3832672a634cdb62c4a8f27c632bd4f3/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-messages.md) | 96 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/54c4a4af-1be8-45d9-ae43-9bf2466fd4ca) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a9482a9d3832672a634cdb62c4a8f27c632bd4f3/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsubscribe-to-conversation-events.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b365e884-999d-4483-a1f4-d43f8a97d6ce) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/create-a-bot-commands-menu.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a9482a9d3832672a634cdb62c4a8f27c632bd4f3/msteams-platform%2Fbots%2Fhow-to%2Fcreate-a-bot-commands-menu.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a5e923d0-c088-42c8-8da9-ea727dabe593) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a9482a9d3832672a634cdb62c4a8f27c632bd4f3/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 92 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/57d29972-5623-4b35-b7d6-96191c4ff651) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-07-21 11:52 UTC, opbld32 commented
Docs Build status updates of commit _[a9482a9](https://github.com/MicrosoftDocs/msteams-docs/commits/a9482a9d3832672a634cdb62c4a8f27c632bd4f3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-basics?branch=pr-en-us-6415) |
[msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-features.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-features?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/channel-and-group-conversations?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/channel-messages-with-rsc?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/conversation-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-basics?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/conversation-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-messages?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/subscribe-to-conversation-events?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/create-a-bot-commands-menu.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/create-a-bot-commands-menu.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/create-a-bot-commands-menu?branch=pr-en-us-6415) |
[msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/what-are-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/what-are-bots?branch=pr-en-us-6415) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202207211151250490-6415/BuildReport?accessString=67de9eea5c83abd222880985e481111f3e64ba6637545034ec459c4944b69816).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-21 12:15 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/734634397d7ac2a235a4e4102a3d55c3d7195f28/msteams-platform%2Fbots%2Fbot-basics.md) | 88 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c4b0ac64-3163-4a19-8a51-25d602c18cfd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/734634397d7ac2a235a4e4102a3d55c3d7195f28/msteams-platform%2Fbots%2Fbot-features.md) | 88 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4d2821c9-c2ed-4b6f-9aea-569d00151958) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/734634397d7ac2a235a4e4102a3d55c3d7195f28/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c29d9615-094a-45cd-9f4c-796c295315b5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/734634397d7ac2a235a4e4102a3d55c3d7195f28/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1bf5ac4b-d97b-4c36-b091-a40c4af004b1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/734634397d7ac2a235a4e4102a3d55c3d7195f28/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-basics.md) | 84 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0bea93f6-f173-46e3-8fd2-d0056178d073) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/734634397d7ac2a235a4e4102a3d55c3d7195f28/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-messages.md) | 96 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1ab4ced1-a8e6-40ea-8e33-14a6448ae010) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/734634397d7ac2a235a4e4102a3d55c3d7195f28/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsubscribe-to-conversation-events.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e4ddb743-8320-4b8a-bd6c-3c102d92c3d5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/create-a-bot-commands-menu.md](https://github.com/MicrosoftDocs/msteams-docs/blob/734634397d7ac2a235a4e4102a3d55c3d7195f28/msteams-platform%2Fbots%2Fhow-to%2Fcreate-a-bot-commands-menu.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/013a02af-4267-4358-ad7a-c9504d29b9fd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/734634397d7ac2a235a4e4102a3d55c3d7195f28/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 92 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3a8edbd0-88c3-4e01-895c-1f83811f9e20) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-07-21 12:15 UTC, opbld31 commented
Docs Build status updates of commit _[7346343](https://github.com/MicrosoftDocs/msteams-docs/commits/734634397d7ac2a235a4e4102a3d55c3d7195f28)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-basics?branch=pr-en-us-6415) |
[msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-features.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-features?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/channel-and-group-conversations?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/channel-messages-with-rsc?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/conversation-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-basics?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/conversation-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-messages?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/subscribe-to-conversation-events?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/create-a-bot-commands-menu.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/create-a-bot-commands-menu.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/create-a-bot-commands-menu?branch=pr-en-us-6415) |
[msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/what-are-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/what-are-bots?branch=pr-en-us-6415) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202207211214313478-6415/BuildReport?accessString=9006b54f5a06bc31c51cb723c892b4bf6dd439a98c698422f9fb9a2577a09c87).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-22 04:22 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/44ea0b6b8c061b260e13dc78f2dc818773f2c48c/msteams-platform%2Fbots%2Fbot-basics.md) | 88 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a33d2145-b123-41e9-845f-65aa6329bdbb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/44ea0b6b8c061b260e13dc78f2dc818773f2c48c/msteams-platform%2Fbots%2Fbot-features.md) | 88 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3752184c-ab97-4399-9ae8-fe449b9fd162) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/44ea0b6b8c061b260e13dc78f2dc818773f2c48c/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/570b0296-418b-4e98-901c-ea1ae2e11a00) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/44ea0b6b8c061b260e13dc78f2dc818773f2c48c/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b3ee3c18-060d-4899-bbaa-8bb75960966a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/44ea0b6b8c061b260e13dc78f2dc818773f2c48c/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-basics.md) | 84 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/91a1a518-c657-44fa-bb6f-5ffa1e213832) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/44ea0b6b8c061b260e13dc78f2dc818773f2c48c/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-messages.md) | 96 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5d745e1c-1a5b-4de9-b9af-53e0c72c55e5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/44ea0b6b8c061b260e13dc78f2dc818773f2c48c/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsubscribe-to-conversation-events.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b2b16ed9-ba12-4df7-996b-3fe5cbe66d18) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/create-a-bot-commands-menu.md](https://github.com/MicrosoftDocs/msteams-docs/blob/44ea0b6b8c061b260e13dc78f2dc818773f2c48c/msteams-platform%2Fbots%2Fhow-to%2Fcreate-a-bot-commands-menu.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/942901e9-7ac8-4953-b43e-25a8f3e06bad) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/44ea0b6b8c061b260e13dc78f2dc818773f2c48c/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 92 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ae1675da-df16-4221-b0da-c892cd8234e0) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-07-22 04:22 UTC, opbld32 commented
Docs Build status updates of commit _[44ea0b6](https://github.com/MicrosoftDocs/msteams-docs/commits/44ea0b6b8c061b260e13dc78f2dc818773f2c48c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-basics?branch=pr-en-us-6415) |
[msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-features.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-features?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/channel-and-group-conversations?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/channel-messages-with-rsc?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/conversation-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-basics?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/conversation-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-messages?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/subscribe-to-conversation-events?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/create-a-bot-commands-menu.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/create-a-bot-commands-menu.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/create-a-bot-commands-menu?branch=pr-en-us-6415) |
[msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/what-are-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/what-are-bots?branch=pr-en-us-6415) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202207220421362902-6415/BuildReport?accessString=0d3251918007b1c767320a22d25b103dfea37f6297ae4feaa5047b4b8e6b0fba).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-22 09:52 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3b0619513c81fc20002a27c04657aa21a8f1bc5e/msteams-platform%2Fbots%2Fbot-basics.md) | 88 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/204b6937-0fd0-4034-a220-3ba78f48e060) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3b0619513c81fc20002a27c04657aa21a8f1bc5e/msteams-platform%2Fbots%2Fbot-features.md) | 88 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/63c3a861-ea0f-4a97-97f7-d8f7d9d123e5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3b0619513c81fc20002a27c04657aa21a8f1bc5e/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c090b67a-0bc3-4585-b9c4-88a6c07c1155) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3b0619513c81fc20002a27c04657aa21a8f1bc5e/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4edfcb9e-be1e-4bc5-86da-b68c41d78a0f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3b0619513c81fc20002a27c04657aa21a8f1bc5e/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-basics.md) | 84 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c59ad19f-47a3-470f-80dd-b9ca20fbed15) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3b0619513c81fc20002a27c04657aa21a8f1bc5e/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-messages.md) | 96 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/88d165dc-ac85-49fe-851a-3aacea7df175) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3b0619513c81fc20002a27c04657aa21a8f1bc5e/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsubscribe-to-conversation-events.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/da089dd0-18ef-48f3-9a02-0a0a3752c6ef) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/create-a-bot-commands-menu.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3b0619513c81fc20002a27c04657aa21a8f1bc5e/msteams-platform%2Fbots%2Fhow-to%2Fcreate-a-bot-commands-menu.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/616924c2-9a3c-42ab-a80b-a80a487105fa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3b0619513c81fc20002a27c04657aa21a8f1bc5e/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 92 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7a121c1d-cde7-4785-8429-467b613a9511) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-07-22 09:52 UTC, opbld31 commented
Docs Build status updates of commit _[3b06195](https://github.com/MicrosoftDocs/msteams-docs/commits/3b0619513c81fc20002a27c04657aa21a8f1bc5e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-basics?branch=pr-en-us-6415) |
[msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-features.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-features?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/channel-and-group-conversations?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/channel-messages-with-rsc?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/conversation-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-basics?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/conversation-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-messages?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/subscribe-to-conversation-events?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/create-a-bot-commands-menu.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/create-a-bot-commands-menu.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/create-a-bot-commands-menu?branch=pr-en-us-6415) |
[msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/what-are-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/what-are-bots?branch=pr-en-us-6415) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202207220951271863-6415/BuildReport?accessString=dee27a589838f779a14873c856345d8e43e770c8989fc3d29c36f1448fbfc146).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-22 09:57 UTC, opbld30 commented
Docs Build status updates of commit _[5ebd3c6](https://github.com/MicrosoftDocs/msteams-docs/commits/5ebd3c633c69b4fdaaf90090b098e7958c4d2651)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-basics?branch=pr-en-us-6415) |
[msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-features.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-features?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/channel-and-group-conversations?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/channel-messages-with-rsc?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/conversation-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-basics?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/conversation-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-messages?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/subscribe-to-conversation-events?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/create-a-bot-commands-menu.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/create-a-bot-commands-menu.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/create-a-bot-commands-menu?branch=pr-en-us-6415) |
[msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/what-are-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/what-are-bots?branch=pr-en-us-6415) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202207220956566138-6415/BuildReport?accessString=b0a8f9c8a1c3be5c28df61cd02a3fd457d8ccee290c9fac160381b38befeae7d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-22 09:59 UTC, opbld30 commented
Docs Build status updates of commit _[b118809](https://github.com/MicrosoftDocs/msteams-docs/commits/b118809580d2b098c59c4135e6241885c0ec4186)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-basics?branch=pr-en-us-6415) |
[msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-features.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-features?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/channel-and-group-conversations?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/channel-messages-with-rsc?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/conversation-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-basics?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/conversation-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-messages?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/subscribe-to-conversation-events?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/create-a-bot-commands-menu.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/create-a-bot-commands-menu.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/create-a-bot-commands-menu?branch=pr-en-us-6415) |
[msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/what-are-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/what-are-bots?branch=pr-en-us-6415) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202207220957160374-6415/BuildReport?accessString=f1a5c09bdbff623db7cb2c8094c98ea79290b6a683b1aa300847ac85e7451ca6).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-22 09:59 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b118809580d2b098c59c4135e6241885c0ec4186/msteams-platform%2Fbots%2Fbot-basics.md) | 88 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6722a825-6d7f-4d6d-b4bb-1aaf8b35de7b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b118809580d2b098c59c4135e6241885c0ec4186/msteams-platform%2Fbots%2Fbot-features.md) | 88 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7675b672-8330-43bb-98f0-970df94aff5f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b118809580d2b098c59c4135e6241885c0ec4186/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c028beb9-a184-4a35-beed-0f609867201c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b118809580d2b098c59c4135e6241885c0ec4186/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/59a2fc85-4561-484b-880f-b7482614aa61) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b118809580d2b098c59c4135e6241885c0ec4186/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-basics.md) | 84 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8b9698e1-055c-4de2-afb8-d93230ef2555) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b118809580d2b098c59c4135e6241885c0ec4186/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-messages.md) | 96 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f15a2a70-950b-4365-9e0b-f72e816de004) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b118809580d2b098c59c4135e6241885c0ec4186/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsubscribe-to-conversation-events.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cedb6be9-ceab-4e08-9db7-6ab55ae96d32) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/create-a-bot-commands-menu.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b118809580d2b098c59c4135e6241885c0ec4186/msteams-platform%2Fbots%2Fhow-to%2Fcreate-a-bot-commands-menu.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5d73f205-a89b-4987-922f-780ab7669bdf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b118809580d2b098c59c4135e6241885c0ec4186/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 92 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/405e804c-983b-4d26-94d7-b0636465e30f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-07-22 09:59 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b118809580d2b098c59c4135e6241885c0ec4186/msteams-platform%2Fbots%2Fbot-basics.md) | 88 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/112970a6-2211-4467-8a3a-25e7b2c90e4c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b118809580d2b098c59c4135e6241885c0ec4186/msteams-platform%2Fbots%2Fbot-features.md) | 88 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8ef173ce-16a8-418c-b7f0-488a1e1fab33) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b118809580d2b098c59c4135e6241885c0ec4186/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8ff53090-7545-47d1-99ec-efad8b2fb3bb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b118809580d2b098c59c4135e6241885c0ec4186/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/50be7933-426e-4da7-96b5-95eb5aa4965f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b118809580d2b098c59c4135e6241885c0ec4186/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-basics.md) | 84 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6b900368-e1c2-4569-b92a-113e326a678a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b118809580d2b098c59c4135e6241885c0ec4186/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-messages.md) | 96 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0394dd7f-39e0-4bed-bce8-916567402159) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b118809580d2b098c59c4135e6241885c0ec4186/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsubscribe-to-conversation-events.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/246550e4-3974-4d4c-83ae-f9f233076b42) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/create-a-bot-commands-menu.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b118809580d2b098c59c4135e6241885c0ec4186/msteams-platform%2Fbots%2Fhow-to%2Fcreate-a-bot-commands-menu.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d880b7c7-6370-4eb1-a00c-3219463caf0e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b118809580d2b098c59c4135e6241885c0ec4186/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 92 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1a1fc421-9278-441a-af10-485de44440d4) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-07-22 11:36 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0f9791cf9eb900cd4290908f3d1cbfed13983fcc/msteams-platform%2Fbots%2Fbot-basics.md) | 88 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2d5bcf7a-27c5-4360-ba4b-41e761662dda) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0f9791cf9eb900cd4290908f3d1cbfed13983fcc/msteams-platform%2Fbots%2Fbot-features.md) | 88 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7021bc58-565d-4673-8c0b-fa8cad7cbea4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0f9791cf9eb900cd4290908f3d1cbfed13983fcc/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bc46333d-5b21-4388-a84c-a5803fe0349d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0f9791cf9eb900cd4290908f3d1cbfed13983fcc/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8785e638-ac39-4007-8a9c-16d30d204944) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0f9791cf9eb900cd4290908f3d1cbfed13983fcc/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-basics.md) | 84 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d25b6f2e-753c-4c9b-b2f6-86447a92e879) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0f9791cf9eb900cd4290908f3d1cbfed13983fcc/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-messages.md) | 96 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9cdf12bd-27c9-4037-89bb-adb4b1034e6f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0f9791cf9eb900cd4290908f3d1cbfed13983fcc/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsubscribe-to-conversation-events.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f3b5eee8-803b-4bec-b86f-9653bd83314a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/create-a-bot-commands-menu.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0f9791cf9eb900cd4290908f3d1cbfed13983fcc/msteams-platform%2Fbots%2Fhow-to%2Fcreate-a-bot-commands-menu.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bd0cf818-0d88-499e-a654-54a0b0cbfc2b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0f9791cf9eb900cd4290908f3d1cbfed13983fcc/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 92 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3cfc723f-2bb4-4889-8873-28325bdba345) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-07-22 11:36 UTC, opbld32 commented
Docs Build status updates of commit _[0f9791c](https://github.com/MicrosoftDocs/msteams-docs/commits/0f9791cf9eb900cd4290908f3d1cbfed13983fcc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-basics?branch=pr-en-us-6415) |
[msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-features.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-features?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/channel-and-group-conversations?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/channel-messages-with-rsc?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/conversation-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-basics?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/conversation-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-messages?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/subscribe-to-conversation-events?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/create-a-bot-commands-menu.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/create-a-bot-commands-menu.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/create-a-bot-commands-menu?branch=pr-en-us-6415) |
[msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/what-are-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/what-are-bots?branch=pr-en-us-6415) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202207221135374237-6415/BuildReport?accessString=0f981fc3ef11662aed252cee1cff87f0b79f3241f886fdb4863bd8b46aa033db).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-26 04:29 UTC, opbld30 commented
Docs Build status updates of commit _[2325f47](https://github.com/MicrosoftDocs/msteams-docs/commits/2325f47a65f82d3523059070d155f9dc4e1a4796)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-basics?branch=pr-en-us-6415) |
[msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-features.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-features?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/channel-and-group-conversations?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/channel-messages-with-rsc?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/conversation-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-basics?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/conversation-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-messages?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/subscribe-to-conversation-events?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/create-a-bot-commands-menu.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/create-a-bot-commands-menu.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/create-a-bot-commands-menu?branch=pr-en-us-6415) |
[msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/what-are-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/what-are-bots?branch=pr-en-us-6415) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202207260428315142-6415/BuildReport?accessString=9812ee266c4633c184f8822c4d9d0775498d3c7d5b71329b66fac025620cf1a9).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-26 04:29 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2325f47a65f82d3523059070d155f9dc4e1a4796/msteams-platform%2Fbots%2Fbot-basics.md) | 88 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/52ed3887-f5f1-4554-bd5e-075b8ae89a5a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2325f47a65f82d3523059070d155f9dc4e1a4796/msteams-platform%2Fbots%2Fbot-features.md) | 88 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c0db40f6-f9ec-46b0-a110-d3271fb020a8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2325f47a65f82d3523059070d155f9dc4e1a4796/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3968903e-faed-45ef-83c7-fdf402c3f93b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2325f47a65f82d3523059070d155f9dc4e1a4796/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bbd32580-54a7-4574-a1cd-30dbb5c6972e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2325f47a65f82d3523059070d155f9dc4e1a4796/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-basics.md) | 84 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c8f8f1f2-bdc8-40f9-8380-bb10bcbabb5c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2325f47a65f82d3523059070d155f9dc4e1a4796/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-messages.md) | 96 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5e613abc-250e-4ea3-8201-508ccbc4beb4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2325f47a65f82d3523059070d155f9dc4e1a4796/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsubscribe-to-conversation-events.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/73d240b1-bd7b-41d2-937a-2c2a7c0b576a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/create-a-bot-commands-menu.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2325f47a65f82d3523059070d155f9dc4e1a4796/msteams-platform%2Fbots%2Fhow-to%2Fcreate-a-bot-commands-menu.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c60acb6f-fcc0-4b66-b705-9b07f61934da) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2325f47a65f82d3523059070d155f9dc4e1a4796/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 92 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f9c3e878-d91a-4e1b-b926-2559d61a2b22) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-07-26 11:10 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/14076316b8b63ad5029f0500271416445f9ba3c8/msteams-platform%2Fbots%2Fbot-basics.md) | 88 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0557c08d-adc4-4c59-8ea8-d9ed98b25a74) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/14076316b8b63ad5029f0500271416445f9ba3c8/msteams-platform%2Fbots%2Fbot-features.md) | 88 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7ec36eba-afaa-43e3-a037-bbcfa195aadf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/14076316b8b63ad5029f0500271416445f9ba3c8/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0dd766ad-10fc-4641-b707-c37832b5e09a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/14076316b8b63ad5029f0500271416445f9ba3c8/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/11338874-c51f-4ffe-a83c-195c35001eb2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/14076316b8b63ad5029f0500271416445f9ba3c8/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-basics.md) | 84 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8a133efb-52b0-4e9f-8111-bd44c38581a2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/14076316b8b63ad5029f0500271416445f9ba3c8/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-messages.md) | 94 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/829ffc16-031a-48b6-8c5e-69e7b620b279) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/14076316b8b63ad5029f0500271416445f9ba3c8/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsubscribe-to-conversation-events.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/18ec1492-36dc-456e-8520-e0a6bf7553a8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/create-a-bot-commands-menu.md](https://github.com/MicrosoftDocs/msteams-docs/blob/14076316b8b63ad5029f0500271416445f9ba3c8/msteams-platform%2Fbots%2Fhow-to%2Fcreate-a-bot-commands-menu.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e7a20fbe-b84e-48e6-82f8-34cfa340a4a3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/14076316b8b63ad5029f0500271416445f9ba3c8/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 92 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e7b582d7-e328-492e-9be5-a8d90f6ebf5a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-07-26 11:10 UTC, opbld32 commented
Docs Build status updates of commit _[1407631](https://github.com/MicrosoftDocs/msteams-docs/commits/14076316b8b63ad5029f0500271416445f9ba3c8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-basics?branch=pr-en-us-6415) |
[msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-features.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-features?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/channel-and-group-conversations?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/channel-messages-with-rsc?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/conversation-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-basics?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/conversation-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-messages?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/subscribe-to-conversation-events?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/create-a-bot-commands-menu.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/create-a-bot-commands-menu.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/create-a-bot-commands-menu?branch=pr-en-us-6415) |
[msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/what-are-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/what-are-bots?branch=pr-en-us-6415) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202207261109382768-6415/BuildReport?accessString=57e3c54e88a008a225be8085a33656ee584d381b363524573e89828828742458).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-26 11:39 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1c176cecd02879c7609dc41d03328771f0f32ca0/msteams-platform%2Fbots%2Fbot-basics.md) | 88 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/08725bf2-d7d8-46a1-8392-d1f5303a0c7b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1c176cecd02879c7609dc41d03328771f0f32ca0/msteams-platform%2Fbots%2Fbot-features.md) | 88 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c0d89ee2-6fb0-45e8-a57a-d063f9b60e17) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1c176cecd02879c7609dc41d03328771f0f32ca0/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c07bdd59-c82e-472c-adc5-87137ebc3612) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1c176cecd02879c7609dc41d03328771f0f32ca0/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bc21b9b2-3799-41ec-8db1-124579acaf1c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1c176cecd02879c7609dc41d03328771f0f32ca0/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-basics.md) | 84 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/41a962b4-61a7-45a5-bdb0-f514c128fb9b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1c176cecd02879c7609dc41d03328771f0f32ca0/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-messages.md) | 94 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/367ce977-3951-4f60-b576-a00265f94454) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1c176cecd02879c7609dc41d03328771f0f32ca0/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 90 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ac08d96c-13b3-4cc8-b4c9-69ff0e5fdfaa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1c176cecd02879c7609dc41d03328771f0f32ca0/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsubscribe-to-conversation-events.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f2ad2d28-81b9-4e74-835b-db41ef247381) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/create-a-bot-commands-menu.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1c176cecd02879c7609dc41d03328771f0f32ca0/msteams-platform%2Fbots%2Fhow-to%2Fcreate-a-bot-commands-menu.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/28054804-64d0-420e-80a1-376b955c093a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1c176cecd02879c7609dc41d03328771f0f32ca0/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 92 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7c413f0a-8776-4104-b4b5-9f2269c15c35) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-07-26 11:39 UTC, opbld30 commented
Docs Build status updates of commit _[1c176ce](https://github.com/MicrosoftDocs/msteams-docs/commits/1c176cecd02879c7609dc41d03328771f0f32ca0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-basics?branch=pr-en-us-6415) |
[msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-features.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-features?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/channel-and-group-conversations?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/channel-messages-with-rsc?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/conversation-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-basics?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/conversation-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-messages?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/send-proactive-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/send-proactive-messages?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/subscribe-to-conversation-events?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/create-a-bot-commands-menu.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/create-a-bot-commands-menu.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/create-a-bot-commands-menu?branch=pr-en-us-6415) |
[msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/what-are-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/what-are-bots?branch=pr-en-us-6415) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202207261138385926-6415/BuildReport?accessString=5738ff003fc5cb18d4d32db5496019f3739bc7964299c7c146de21de0e05b6a6).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-27 03:17 UTC, opbld30 commented
Docs Build status updates of commit _[15cd0b3](https://github.com/MicrosoftDocs/msteams-docs/commits/15cd0b399aff6352a66574a28b3e68271a97a897)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-basics?branch=pr-en-us-6415) |
[msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-features.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-features?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/channel-and-group-conversations?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/channel-messages-with-rsc?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/conversation-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-basics?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/conversation-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-messages?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/send-proactive-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/send-proactive-messages?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/subscribe-to-conversation-events?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/create-a-bot-commands-menu.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/create-a-bot-commands-menu.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/create-a-bot-commands-menu?branch=pr-en-us-6415) |
[msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/what-are-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/what-are-bots?branch=pr-en-us-6415) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202207270315566160-6415/BuildReport?accessString=6024dcb2f92f21c8260ce5455c05955f56524324808f4b79e311ec54fca22455).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-27 03:23 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/15cd0b399aff6352a66574a28b3e68271a97a897/msteams-platform%2Fbots%2Fbot-basics.md) | 88 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2574cf9f-0b7b-4e85-89ba-79a21a1a0e6f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/15cd0b399aff6352a66574a28b3e68271a97a897/msteams-platform%2Fbots%2Fbot-features.md) | 88 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9a1ebc07-3dda-4f7e-b138-48eba5f63743) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/15cd0b399aff6352a66574a28b3e68271a97a897/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5a373f3c-3a5d-432e-9480-ad8e96ecc860) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/15cd0b399aff6352a66574a28b3e68271a97a897/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c892d618-7224-45a1-8d38-c9d7b6eb221b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/15cd0b399aff6352a66574a28b3e68271a97a897/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-basics.md) | 84 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/be0eaa4f-eb58-49b4-82f7-76c143137543) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/15cd0b399aff6352a66574a28b3e68271a97a897/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-messages.md) | 94 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a8ba55ad-131d-42f8-9f57-3a17cf0b8c3a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/15cd0b399aff6352a66574a28b3e68271a97a897/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 90 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7d4ceff1-997c-4f0a-839a-317fc34eb7df) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/15cd0b399aff6352a66574a28b3e68271a97a897/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsubscribe-to-conversation-events.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ff8885c9-a428-458d-ad85-fffb4079b0cb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/create-a-bot-commands-menu.md](https://github.com/MicrosoftDocs/msteams-docs/blob/15cd0b399aff6352a66574a28b3e68271a97a897/msteams-platform%2Fbots%2Fhow-to%2Fcreate-a-bot-commands-menu.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9b707460-8211-4d0b-9adb-d0e17b94196c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/15cd0b399aff6352a66574a28b3e68271a97a897/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 92 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fd3961e3-3e0e-4a86-8368-bed64aa4cf0f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-07-27 08:12 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4cd50ab3b80fb1e840323e4540c8a60842143005/msteams-platform%2Fbots%2Fbot-basics.md) | 88 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1f649f00-ab3f-4b9f-b616-d480da49a606) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4cd50ab3b80fb1e840323e4540c8a60842143005/msteams-platform%2Fbots%2Fbot-features.md) | 88 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/41ab680c-85fd-426f-88a3-54713a1cbbe9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4cd50ab3b80fb1e840323e4540c8a60842143005/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/66c75098-0dd2-4df0-89fa-3b1dd59b0bc6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4cd50ab3b80fb1e840323e4540c8a60842143005/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cf2934d9-f853-434b-873c-e8cabbc04929) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4cd50ab3b80fb1e840323e4540c8a60842143005/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-basics.md) | 84 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/56a91eb9-9219-46db-83e7-ca6d45bec417) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4cd50ab3b80fb1e840323e4540c8a60842143005/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-messages.md) | 94 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f0bba5bf-7514-4428-a9c8-846983666e3d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4cd50ab3b80fb1e840323e4540c8a60842143005/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 90 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ff919678-5f4f-447f-871e-738145e7f0f0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4cd50ab3b80fb1e840323e4540c8a60842143005/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsubscribe-to-conversation-events.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6fef8805-9149-4339-8d81-36352d920394) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/create-a-bot-commands-menu.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4cd50ab3b80fb1e840323e4540c8a60842143005/msteams-platform%2Fbots%2Fhow-to%2Fcreate-a-bot-commands-menu.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2ff3e4f5-dcd5-4853-8deb-f5ec7e385b51) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4cd50ab3b80fb1e840323e4540c8a60842143005/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 92 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/47d91171-d6bd-4b08-8e13-a7ca934eae1b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-07-27 08:15 UTC, opbld30 commented
Docs Build status updates of commit _[4cd50ab](https://github.com/MicrosoftDocs/msteams-docs/commits/4cd50ab3b80fb1e840323e4540c8a60842143005)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-basics?branch=pr-en-us-6415) |
[msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-features.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-features?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/channel-and-group-conversations?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/channel-messages-with-rsc?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/conversation-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-basics?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/conversation-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-messages?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/send-proactive-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/send-proactive-messages?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/subscribe-to-conversation-events?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/create-a-bot-commands-menu.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/create-a-bot-commands-menu.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/create-a-bot-commands-menu?branch=pr-en-us-6415) |
[msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/what-are-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/what-are-bots?branch=pr-en-us-6415) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202207270814246382-6415/BuildReport?accessString=e1faebe569dc99cf2536b9d7e88fd515c7ed029a4381f7a59994f89fad386a96).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-27 08:59 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/49ba4c5dc2877474e2982bbd2a9b7acb37d16d2d/msteams-platform%2Fbots%2Fbot-basics.md) | 93 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/83f49b1f-4700-4c39-a02a-54ecf7d2f3e2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/49ba4c5dc2877474e2982bbd2a9b7acb37d16d2d/msteams-platform%2Fbots%2Fbot-features.md) | 88 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/96c366d1-bd71-476f-a770-23e18b71776c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/49ba4c5dc2877474e2982bbd2a9b7acb37d16d2d/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b28d68df-ffa8-425a-9471-540214054a4c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/49ba4c5dc2877474e2982bbd2a9b7acb37d16d2d/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1536af47-4b3f-4e5e-8928-853d5bc770f9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/49ba4c5dc2877474e2982bbd2a9b7acb37d16d2d/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-basics.md) | 84 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7e1c0999-b163-446e-9f62-b81f9a966201) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/49ba4c5dc2877474e2982bbd2a9b7acb37d16d2d/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-messages.md) | 94 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/516027fd-4596-4724-85c6-9c2b36cacb10) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/49ba4c5dc2877474e2982bbd2a9b7acb37d16d2d/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 90 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/17cb4e90-3f2d-41b9-b46b-ca157909f2ef) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/49ba4c5dc2877474e2982bbd2a9b7acb37d16d2d/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsubscribe-to-conversation-events.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ae06e810-8694-4586-95bc-78fb60e9b924) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/create-a-bot-commands-menu.md](https://github.com/MicrosoftDocs/msteams-docs/blob/49ba4c5dc2877474e2982bbd2a9b7acb37d16d2d/msteams-platform%2Fbots%2Fhow-to%2Fcreate-a-bot-commands-menu.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/54645c08-62af-45ca-9099-e0667cf5f482) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/49ba4c5dc2877474e2982bbd2a9b7acb37d16d2d/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 92 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e4c0e1b0-b3d3-4a99-9cb9-adf683d5da81) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-07-27 09:00 UTC, opbld30 commented
Docs Build status updates of commit _[49ba4c5](https://github.com/MicrosoftDocs/msteams-docs/commits/49ba4c5dc2877474e2982bbd2a9b7acb37d16d2d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-basics?branch=pr-en-us-6415) |
[msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-features.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-features?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/channel-and-group-conversations?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/channel-messages-with-rsc?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/conversation-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-basics?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/conversation-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-messages?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/send-proactive-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/send-proactive-messages?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/subscribe-to-conversation-events?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/create-a-bot-commands-menu.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/create-a-bot-commands-menu.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/create-a-bot-commands-menu?branch=pr-en-us-6415) |
[msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/what-are-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/what-are-bots?branch=pr-en-us-6415) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202207270859029830-6415/BuildReport?accessString=ff641ab70a5175506dd19e95ab3f092aaac923042af2565e49df0102b40675b5).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-27 09:00 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e046988a65e3abaec01b9b9ae42d5701713154cf/msteams-platform%2Fbots%2Fbot-basics.md) | 93 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c3d7783e-53a2-4a5f-b4e8-947730486cca) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e046988a65e3abaec01b9b9ae42d5701713154cf/msteams-platform%2Fbots%2Fbot-features.md) | 88 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/723db1b4-c706-4330-9e75-181d00c5e1c4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e046988a65e3abaec01b9b9ae42d5701713154cf/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fd5af927-c0e8-482c-a189-1dfeb3960f43) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e046988a65e3abaec01b9b9ae42d5701713154cf/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e98910b3-969e-446b-9597-8a9cf6f23305) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e046988a65e3abaec01b9b9ae42d5701713154cf/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-basics.md) | 84 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3e656a11-9100-4d6d-aebd-9303ca56380f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e046988a65e3abaec01b9b9ae42d5701713154cf/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-messages.md) | 94 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/078d7e90-5ad4-4593-acaf-1921334b45b9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e046988a65e3abaec01b9b9ae42d5701713154cf/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 90 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/935bcbc0-9aba-4c43-a325-43f2f57b4b39) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e046988a65e3abaec01b9b9ae42d5701713154cf/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsubscribe-to-conversation-events.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/484fc5d0-e327-4769-86d2-e5213d78d673) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/create-a-bot-commands-menu.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e046988a65e3abaec01b9b9ae42d5701713154cf/msteams-platform%2Fbots%2Fhow-to%2Fcreate-a-bot-commands-menu.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b1938a70-541d-48b3-868f-3711e5cc7917) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e046988a65e3abaec01b9b9ae42d5701713154cf/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 92 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/905753cd-8622-4049-9617-25cbac96b21a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-07-27 09:01 UTC, opbld33 commented
Docs Build status updates of commit _[e046988](https://github.com/MicrosoftDocs/msteams-docs/commits/e046988a65e3abaec01b9b9ae42d5701713154cf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-basics?branch=pr-en-us-6415) |
[msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-features.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-features?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/channel-and-group-conversations?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/channel-messages-with-rsc?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/conversation-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-basics?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/conversation-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-messages?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/send-proactive-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/send-proactive-messages?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/subscribe-to-conversation-events?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/create-a-bot-commands-menu.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/create-a-bot-commands-menu.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/create-a-bot-commands-menu?branch=pr-en-us-6415) |
[msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/what-are-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/what-are-bots?branch=pr-en-us-6415) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202207270900143832-6415/BuildReport?accessString=56e12c83162891c8fa0ff2c63467e5553c880b69d089b2255df4d472e135ccc1).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-02 11:08 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/459c16928e68ff82cae86cb7c6e1b0ea42779c4a/msteams-platform%2Fbots%2Fbot-basics.md) | 93 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7f215569-b888-4bf6-aac0-e62e69fd2ff1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/459c16928e68ff82cae86cb7c6e1b0ea42779c4a/msteams-platform%2Fbots%2Fbot-features.md) | 88 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/17791b65-f44a-40f4-9f00-3dbd73726e1d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/459c16928e68ff82cae86cb7c6e1b0ea42779c4a/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/05198c7b-3f30-4569-9b63-7809bbbf41ec) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/459c16928e68ff82cae86cb7c6e1b0ea42779c4a/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b3974e1e-1791-4e2c-b2dd-a4960ca82fac) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/459c16928e68ff82cae86cb7c6e1b0ea42779c4a/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-basics.md) | 84 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e3ae2887-86be-4323-b83a-f403e3067794) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/459c16928e68ff82cae86cb7c6e1b0ea42779c4a/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-messages.md) | 94 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/feaaf3c0-2109-417f-9486-9d7c0a47285f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/459c16928e68ff82cae86cb7c6e1b0ea42779c4a/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 90 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d0d721e2-77d7-4c65-9bb2-f73c238a06ed) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/459c16928e68ff82cae86cb7c6e1b0ea42779c4a/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsubscribe-to-conversation-events.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d8e72cda-a6e7-4ee4-802e-16bd57412dc9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/create-a-bot-commands-menu.md](https://github.com/MicrosoftDocs/msteams-docs/blob/459c16928e68ff82cae86cb7c6e1b0ea42779c4a/msteams-platform%2Fbots%2Fhow-to%2Fcreate-a-bot-commands-menu.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/471a5707-298a-4ccc-a95c-3dba9a8b88ee) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/459c16928e68ff82cae86cb7c6e1b0ea42779c4a/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 92 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/91f5b748-b769-4f03-9ba5-315937a95c2a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-08-02 11:08 UTC, opbld30 commented
Docs Build status updates of commit _[459c169](https://github.com/MicrosoftDocs/msteams-docs/commits/459c16928e68ff82cae86cb7c6e1b0ea42779c4a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-basics?branch=pr-en-us-6415) |
[msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-features.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-features?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/channel-and-group-conversations?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/channel-messages-with-rsc?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/conversation-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-basics?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/conversation-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-messages?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/send-proactive-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/send-proactive-messages?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/subscribe-to-conversation-events?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/create-a-bot-commands-menu.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/create-a-bot-commands-menu.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/create-a-bot-commands-menu?branch=pr-en-us-6415) |
[msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/what-are-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/what-are-bots?branch=pr-en-us-6415) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202208021107505783-6415/BuildReport?accessString=330cc39ad5c51fbbce71d8a3a3d49de015277acc677b48701c44b6c2e3cebb6f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-02 11:15 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3c8295f5ffbfb5d9341e6133cf92897d58caecf2/msteams-platform%2Fbots%2Fbot-basics.md) | 93 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5731d3cf-3917-412e-a6a6-47417255af09) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3c8295f5ffbfb5d9341e6133cf92897d58caecf2/msteams-platform%2Fbots%2Fbot-features.md) | 88 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/42e0b981-21a7-46ce-a2b4-ccd0ccf97d19) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3c8295f5ffbfb5d9341e6133cf92897d58caecf2/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/324b5a98-5eb2-4169-adf4-6079b4997483) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3c8295f5ffbfb5d9341e6133cf92897d58caecf2/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/957a4387-259b-44b0-b87f-86f5fdc5f4f1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3c8295f5ffbfb5d9341e6133cf92897d58caecf2/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-basics.md) | 87 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b2e76ac0-aa43-4ab8-8ea3-b1528dca9b2e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3c8295f5ffbfb5d9341e6133cf92897d58caecf2/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-messages.md) | 94 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/043ecda2-904e-477d-8053-a2a003512c15) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3c8295f5ffbfb5d9341e6133cf92897d58caecf2/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 90 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/db0c7249-91bb-4b80-b03c-1950cacaf55f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3c8295f5ffbfb5d9341e6133cf92897d58caecf2/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsubscribe-to-conversation-events.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/992d7f1a-b1b4-4ad9-8e78-3a59180eefc2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/create-a-bot-commands-menu.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3c8295f5ffbfb5d9341e6133cf92897d58caecf2/msteams-platform%2Fbots%2Fhow-to%2Fcreate-a-bot-commands-menu.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/969e1134-e256-459e-994a-224ef94ee143) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3c8295f5ffbfb5d9341e6133cf92897d58caecf2/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 92 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/febd20c5-1be0-419d-bbe2-dda0c029107c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-08-02 11:16 UTC, opbld31 commented
Docs Build status updates of commit _[3c8295f](https://github.com/MicrosoftDocs/msteams-docs/commits/3c8295f5ffbfb5d9341e6133cf92897d58caecf2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-basics?branch=pr-en-us-6415) |
[msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-features.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-features?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/channel-and-group-conversations?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/channel-messages-with-rsc?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/conversation-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-basics?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/conversation-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-messages?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/send-proactive-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/send-proactive-messages?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/subscribe-to-conversation-events?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/create-a-bot-commands-menu.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/create-a-bot-commands-menu.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/create-a-bot-commands-menu?branch=pr-en-us-6415) |
[msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/what-are-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/what-are-bots?branch=pr-en-us-6415) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202208021115209043-6415/BuildReport?accessString=445caafdd31e76a13293ce33ea2b72e0da30273f92d523714ca782cf6ef76377).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-03 10:07 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7c312f143aa18a775a5359c6d9c6ad0735a27e80/msteams-platform%2Fbots%2Fbot-basics.md) | 93 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9155257e-6dd4-4ea9-98b7-57fd20315bd8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7c312f143aa18a775a5359c6d9c6ad0735a27e80/msteams-platform%2Fbots%2Fbot-features.md) | 88 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/addc8ffa-354c-4b5a-b301-47acceda30f1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7c312f143aa18a775a5359c6d9c6ad0735a27e80/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2c20dcc0-c63d-4cd0-8068-2c9e6efcc727) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7c312f143aa18a775a5359c6d9c6ad0735a27e80/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/320e2d3e-f955-4666-8097-aee2e3a2129a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7c312f143aa18a775a5359c6d9c6ad0735a27e80/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-basics.md) | 87 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/24c8c2d8-e11d-4f2c-8c93-9d5eb5ba9a40) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7c312f143aa18a775a5359c6d9c6ad0735a27e80/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-messages.md) | 94 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0501d6a1-2f4b-4787-b853-0257d40c940c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7c312f143aa18a775a5359c6d9c6ad0735a27e80/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 90 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ced9a422-a5fc-43b6-afbb-a2cfb88738e4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7c312f143aa18a775a5359c6d9c6ad0735a27e80/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsubscribe-to-conversation-events.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f4b6c843-20c8-4ffb-9dc2-7ad209146621) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/create-a-bot-commands-menu.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7c312f143aa18a775a5359c6d9c6ad0735a27e80/msteams-platform%2Fbots%2Fhow-to%2Fcreate-a-bot-commands-menu.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d1423ad5-83ba-4164-b0a7-3fa4febc2cad) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7c312f143aa18a775a5359c6d9c6ad0735a27e80/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 92 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1b5f324b-567c-4aa2-bc01-649329bd3d52) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-08-03 10:07 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7c312f143aa18a775a5359c6d9c6ad0735a27e80/msteams-platform%2Fbots%2Fbot-basics.md) | 93 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8a1c288d-4ba2-451c-a008-55b2f82f2a3b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7c312f143aa18a775a5359c6d9c6ad0735a27e80/msteams-platform%2Fbots%2Fbot-features.md) | 88 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/29e8b59d-bf76-4d74-86a0-f86b2977a94c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7c312f143aa18a775a5359c6d9c6ad0735a27e80/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3ecf25b2-9d99-4c67-b22d-81c9214a845b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7c312f143aa18a775a5359c6d9c6ad0735a27e80/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/20d01b27-09a6-4271-a695-b4192651d83a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7c312f143aa18a775a5359c6d9c6ad0735a27e80/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-basics.md) | 87 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/da7f6ad8-1182-4f68-b84b-d0ef9c5d9ea8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7c312f143aa18a775a5359c6d9c6ad0735a27e80/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-messages.md) | 94 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5345879c-9dee-44d5-8b7e-59b83e09d0ce) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7c312f143aa18a775a5359c6d9c6ad0735a27e80/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 90 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6007f64a-5426-4a4b-be25-0168f9de012a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7c312f143aa18a775a5359c6d9c6ad0735a27e80/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsubscribe-to-conversation-events.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2d668290-13f5-48a8-a28f-34878e13b0b5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/create-a-bot-commands-menu.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7c312f143aa18a775a5359c6d9c6ad0735a27e80/msteams-platform%2Fbots%2Fhow-to%2Fcreate-a-bot-commands-menu.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/13b09f8c-3621-4e53-987d-d14cccf45f4a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7c312f143aa18a775a5359c6d9c6ad0735a27e80/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 92 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9715e4eb-c31b-461b-871d-2db4816c81e0) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-08-03 10:07 UTC, opbld30 commented
Docs Build status updates of commit _[b058c33](https://github.com/MicrosoftDocs/msteams-docs/commits/b058c338eaae608235df5c231b99d0d743c65526)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-basics?branch=pr-en-us-6415) |
[msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-features.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-features?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/channel-and-group-conversations?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/channel-messages-with-rsc?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/conversation-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-basics?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/conversation-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-messages?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/send-proactive-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/send-proactive-messages?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/subscribe-to-conversation-events?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/create-a-bot-commands-menu.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/create-a-bot-commands-menu.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/create-a-bot-commands-menu?branch=pr-en-us-6415) |
[msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/what-are-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/what-are-bots?branch=pr-en-us-6415) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202208031006317976-6415/BuildReport?accessString=31325af2d79433f432801f98ba950eae3ba8e7e3bd07280df6f02ea3f8494624).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-03 10:08 UTC, opbld31 commented
Docs Build status updates of commit _[7c312f1](https://github.com/MicrosoftDocs/msteams-docs/commits/7c312f143aa18a775a5359c6d9c6ad0735a27e80)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-basics?branch=pr-en-us-6415) |
[msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-features.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-features?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/channel-and-group-conversations?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/channel-messages-with-rsc?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/conversation-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-basics?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/conversation-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-messages?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/send-proactive-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/send-proactive-messages?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/subscribe-to-conversation-events?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/create-a-bot-commands-menu.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/create-a-bot-commands-menu.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/create-a-bot-commands-menu?branch=pr-en-us-6415) |
[msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/what-are-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/what-are-bots?branch=pr-en-us-6415) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202208031006535692-6415/BuildReport?accessString=f24fc1c4eec03a158dbfe38c289604904d68c736fd6412b23067361994e5e473).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-29 09:45 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/17d9fd2f944e296d3e526d0ed5572ee21a29a674/msteams-platform%2Fbots%2Fbot-basics.md) | 93 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6551dc56-0fd8-4e6f-b3d5-b04b628328a8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/17d9fd2f944e296d3e526d0ed5572ee21a29a674/msteams-platform%2Fbots%2Fbot-features.md) | 86 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5df56a62-5fdd-4096-b258-50c973d8d2f6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/17d9fd2f944e296d3e526d0ed5572ee21a29a674/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ed31d161-fae6-40d5-adfe-cfe253d9470e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/17d9fd2f944e296d3e526d0ed5572ee21a29a674/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 92 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5d043464-c9db-4a4b-8d44-f12e4a6d5fd4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/17d9fd2f944e296d3e526d0ed5572ee21a29a674/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-basics.md) | 87 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/75b7f2e5-1d31-4a83-8c0c-cddd775f70c9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/17d9fd2f944e296d3e526d0ed5572ee21a29a674/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-messages.md) | 93 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dfd65eaf-8742-4528-a246-38a9f2c58dd0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/17d9fd2f944e296d3e526d0ed5572ee21a29a674/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 94 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/85370704-91fb-4519-9c52-fde5ff8c48ac) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/17d9fd2f944e296d3e526d0ed5572ee21a29a674/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsubscribe-to-conversation-events.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c5459895-65ed-4adb-92e6-495a841791a4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/create-a-bot-commands-menu.md](https://github.com/MicrosoftDocs/msteams-docs/blob/17d9fd2f944e296d3e526d0ed5572ee21a29a674/msteams-platform%2Fbots%2Fhow-to%2Fcreate-a-bot-commands-menu.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9a4242fa-f754-486b-b680-35fb6323e24b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/17d9fd2f944e296d3e526d0ed5572ee21a29a674/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 89 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1aaca28d-0688-4b4c-920f-71ad6331dae0) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-08-29 09:45 UTC, opbld33 commented
Docs Build status updates of commit _[17d9fd2](https://github.com/MicrosoftDocs/msteams-docs/commits/17d9fd2f944e296d3e526d0ed5572ee21a29a674)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-basics?branch=pr-en-us-6415) |
[msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-features.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-features?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/channel-and-group-conversations?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/channel-messages-with-rsc?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/conversation-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-basics?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/conversation-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-messages?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/send-proactive-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/send-proactive-messages?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/subscribe-to-conversation-events?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/create-a-bot-commands-menu.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/create-a-bot-commands-menu.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/create-a-bot-commands-menu?branch=pr-en-us-6415) |
[msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/what-are-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/what-are-bots?branch=pr-en-us-6415) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202208290944531320-6415/BuildReport?accessString=2ca6688ca011d7fe3095ddd54ef72340fc4349b63c916e815724d68ce8e7e0af).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-02 10:57 UTC, opbld30 commented
Docs Build status updates of commit _[14f7b3f](https://github.com/MicrosoftDocs/msteams-docs/commits/14f7b3f31a4214cde10e3398332658ad42100e6d)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-188e336f)

<a id="188e336f"></a>
###
 - **[Error: CannotMergeCommit]** `````Cannot merge commit 14f7b3f31a4214cde10e3398332658ad42100e6d in branch BuildBotsReview of repository https://github.com/MicrosoftDocs/msteams-docs into branch main (commit 7e3709c98717b1aad67de6561a3b9ed5e01e1a5a). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202209021056428820-6415/BuildReport?accessString=8f4baf837ae7ecc3c00f0877e17adaaa0ef4e3f1c42dbbc54e550373e347c29a).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-02 10:57 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/14f7b3f31a4214cde10e3398332658ad42100e6d/msteams-platform%2Fbots%2Fbot-basics.md) | 93 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/784acd56-04de-493a-be62-5a782af37743) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/14f7b3f31a4214cde10e3398332658ad42100e6d/msteams-platform%2Fbots%2Fbot-features.md) | 86 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ecb1077b-2236-47b2-bf17-395eeb003c20) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/14f7b3f31a4214cde10e3398332658ad42100e6d/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/38da159c-3394-4f31-ac8c-e3ffbe0ce60e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/14f7b3f31a4214cde10e3398332658ad42100e6d/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 92 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b35b2950-a247-4ca3-9647-0320fd8e8a55) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/14f7b3f31a4214cde10e3398332658ad42100e6d/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-basics.md) | 87 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/76a7e011-5e7e-4ca1-853d-d17b2c1e6a5f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/14f7b3f31a4214cde10e3398332658ad42100e6d/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-messages.md) | 93 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8219c5b2-0a95-4e39-adeb-abdbf15d58cc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/14f7b3f31a4214cde10e3398332658ad42100e6d/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 94 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f51c28ed-c665-4610-b714-db4fa977c208) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/14f7b3f31a4214cde10e3398332658ad42100e6d/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsubscribe-to-conversation-events.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/389bbc11-ef50-49d5-91d9-4181c14bdb4f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/create-a-bot-commands-menu.md](https://github.com/MicrosoftDocs/msteams-docs/blob/14f7b3f31a4214cde10e3398332658ad42100e6d/msteams-platform%2Fbots%2Fhow-to%2Fcreate-a-bot-commands-menu.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e397c20b-b067-48f8-bd23-45e138cc80aa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/14f7b3f31a4214cde10e3398332658ad42100e6d/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 89 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9d91d0b0-011c-4c28-b5e0-db0bf60902f1) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-09-02 12:17 UTC, v-prepatel requested changes
Under Note, Line 1:
It's recommended that you'd create your first bot app or notification bot app using the new generation development tool for Teams.
Correction: It's recommended that you create your first bot app or notification bot app using the new generation development tool for Teams.

First Paragraph after Note, Line 2:
It's an app that runs simple and repetitive tasks by users such as customer service or support staff. 
Correction: It's an app that runs simple and repetitive tasks for users, such as customer service or support staff. 

First Paragraph after Note, Line 3:
Everyday use of bots include, bots that provide information about the weather, make dinner reservations, or provide travel information.
Correction: Everyday uses of bots include bots that provide information about the weather, make dinner reservations, or provide travel information.

After Last Image, Paragraph 2, Line 3:
A bot behaves differently in a channel or group chat conversation and in a one-to-one conversation.
Correction: A bot behaves differently in a channel or group chat conversation than in a one-to-one conversation.

After Last Image, Paragraph 3, Line 1:
Your bot requires contextual information, such as user profile details to access relevant content and enhance the bot experience.
Correction: Your bot requires contextual information, such as user profile details, to access relevant content and enhance the bot experience.

2022-09-02 12:24 UTC, v-prepatel commented
[msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/14f7b3f31a4214cde10e3398332658ad42100e6d/msteams-platform%2Fbots%2Fbot-features.md)

Under Bots with webhooks and connectors, Last Line:
For more information, see what are webhooks and connectors.
Correction: For more information, see what webhooks and connectors are.

Under In a channel, Line 1:
Channels contain threaded conversations between multiple people even up to two thousand.
Correction: Channels contain threaded conversations between multiple people, even up to two thousand.

Under In a channel, Point 3:
Single request or response cycle resolves interactions and the results are useful for multiple members of the conversation.
Correction: Single request or response cycle resolves interactions, and the results are useful for multiple members of the conversation.

Under In a group chat, Paragraph 2:
In the cases where bots work better in a channel also work better in a group chat.
Correction: In the cases where bots work better in a channel, they also work better in a group chat.

Under Have multi-turn experiences in chat:
BOT: I’ve found 200 results, please include a first and last name.
Correction: BOT: I’ve found 200 resu

2022-09-02 12:31 UTC, v-prepatel commented
[msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/14f7b3f31a4214cde10e3398332658ad42100e6d/msteams-platform%2Fbots%2Fbot-basics.md)

Paragraph 2, Line 2:
Activities are handled in two ways using Teams activity handlers and bot logic.
Correction: Activities are handled in two ways, using Teams activity handlers and bot logic.

Under Teams activity handlers, Paragraph 2, Line 2:
All activities are routed through one base handler called the turn handler.
Correction: All activities are routed through one base handler, called the turn handler.

Under Bot logic, Line 1:
The bot logic processes incoming activities from one or more of your bot channels and in response generates outgoing activities.
Correction: The bot logic processes incoming activities from one or more of your bot channels and, in response, generates outgoing activities.

Table under Core Bot Framework handlers, Row 4, Column 3:
This method calls a handler if members other than the bot joined or left the conversation, on a ConversationUpdate activity.
Correction: This method calls a handler if members other than the bot join or leave the conversation on a ConversationUpdate activity.

Table under Core Bot Framework handlers, Row 7, Column 3:
This method calls a handler specific to the event type, on an Event activity.
Correction: This method calls a handler specific to the event type on an Event activity.

Last Line:
Now that you've familiarized yourself with bot activity handlers, let us see how bots behave differently depending on the conversation and the messages it receives or sends.
Correction: Now that you've familiarized yourself with bot activity handlers, let us see how bots behave differently depending on the conversation and the messages they receive or send.

2022-09-02 12:32 UTC, v-prepatel commented
[msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/14f7b3f31a4214cde10e3398332658ad42100e6d/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-basics.md)

Above Note, Point 2, Line 2:
All messages sent by the user routes to your bot.
Correction: All messages sent by the user are routed to your bot.

After Note, Second Paragraph, Line 2:
When a user sends a message, Teams posts the message to your bot and the bot handles the message.
Correction: When a user sends a message, Teams posts the message to your bot, and the bot handles the message.

After Note, Second Paragraph, Line 4:
Bots in a group or channel only receive messages when they are mentioned @botname.
Correction: Bots in a group or channel only receive messages when they are mentioned with @botname.

Last Paragraph, Line 3:
You can format your bot messages to include rich cards that include interactive elements, such as buttons, text, images, audio, video, and so on.
Correction: You can format your bot messages to include rich cards that include interactive elements such as buttons, text, images, audio, video, and so on.

2022-09-02 12:33 UTC, v-prepatel commented
[msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/14f7b3f31a4214cde10e3398332658ad42100e6d/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-messages.md)

Line 3:
Teams sends a JSON object to your bot's messaging endpoint and Teams allows only one endpoint for messaging. Your bot examines the message to determine its type and responds accordingly.
Correction: Teams sends a JSON object to your bot's messaging endpoint, and Teams allows only one endpoint for messaging. Your bot examines the message to determine its type and responds accordingly.

After First 3 Pointers, Line 1:
Your bot receives messages from Teams using the Text property and it sends single or multiple message responses to the users.
Correction: Your bot receives messages from Teams using the Text property, and it sends single or multiple message responses to the users.

Under Send suggested actions, Line 2:
Suggested actions enhance user experience by enabling the user to answer a question or make a choice with selection of a button, rather than typing a response with a keyboard.
Correction: Suggested actions enhance the user experience by enabling the user to answer a question or make a choice with the selection of a button rather than by typing a response with a keyboard.

Under Send suggested actions, Line 3:
The buttons remain visible and accessible to the user in the rich cards even after user makes a selection whereas for suggested actions, buttons aren't available.
Correction: The buttons remain visible and accessible to the user in the rich cards even after the user makes a selection, whereas for suggested actions, the buttons aren't available.

Under Notifications to your message, Second-last Line:
Whether or not a notification is raised depends on the individual user's Teams settings and you can't override these settings.
Correction: Whether or not a notification is raised depends on the individual user's Teams settings, and you can't override these settings.

Under Picture messages, Line 4:
Animated GIF isn't supported.
Correction: Animated GIFs aren't supported.

Under Status code responses:
Following are the status codes and their error code and message values:
Correction: Following are the status codes and their error codes and message values:

Table under Status code responses, Row 6, Column 2:
Message: Precondition failed, please try again.
Correction: Message: Precondition failed. Please try again.

Table under Status code responses, Row 8, Column 3:
The size on the incoming request was too large.
Correction: The size of the incoming request was too large.

2022-09-02 12:35 UTC, v-prepatel commented
[msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/14f7b3f31a4214cde10e3398332658ad42100e6d/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md)

Line 2:
Using RSC, you can now request team owners to consent for a bot to receive user messages across standard channels in a team without being @mentioned.
Correction: Using RSC, you can now request team owners’ consent for a bot to receive user messages across standard channels in a team without being @mentioned.

Under Note, Point 2, Line 1:
ots must use the ChannelMessage.Read.Group RSC permission appropriately to build and enhance engaging experience for users in the team or they will not pass the store approval.
Correction: ots must use the ChannelMessage.Read.Group RSC permission appropriately to build and enhance an engaging experience for users in the team or they will not pass the store approval.

Under Update app manifest, Point 2:
resource: Any string. This field has no operation in RSC, but must be added and have a value to avoid error response.
Correction: resource: Any string. This field has no operation in RSC but must be added and have a value to avoid an error response.

Under Sideload in a team, Line 1:
To sideload in a team to test, whether all channel messages in a team with RSC are received without being @mentioned:
Correction: To sideload in a team to test whether all channel messages in a team with RSC are received without being @mentioned:

Under Sideload in a team, Point 8:
Select Add from the app details pop-up, to add the bot to your selected team.
Correction: Select Add from the app details pop-up to add the bot to your selected team.

2022-09-02 12:36 UTC, v-prepatel commented
[msteams-platform/bots/how-to/create-a-bot-commands-menu.md](https://github.com/MicrosoftDocs/msteams-docs/blob/14f7b3f31a4214cde10e3398332658ad42100e6d/msteams-platform%2Fbots%2Fhow-to%2Fcreate-a-bot-commands-menu.md)

Under Note, Line 1:
It's recommended that you'd create a command bot by following the step-by-step guide to Build command bot with JavaScript using the new generation development tool for Teams.
Correction: It's recommended that you create a command bot by following the step-by-step guide to Build command bot with JavaScript using the new generation development tool for Teams.

Under Create a command menu for your bot using Developer Portal, Point 1, Line 2:
In the Apps page, search for Developer Portal, and then select Open.
Correction: On the Apps page, search for Developer Portal, and then select Open.

Under Create a command menu for your bot using Developer Portal, Point 5:
Enter the Command that appears as the command menu for your bot.
Correction: Enter the Command that appears in the command menu for your bot.

Under Handle menu commands in your bot code, Line 1:
Bots in a group or channel respond only when they are mentioned @botname in a message.
Correction: Bots in a group or channel respond only when they are mentioned as @botname in a message.

Under Handle menu commands in your bot code, Under Note, Line 4:
The user must then send that text as they do for any other message.
Correction: The user must then send that text as they would for any other message.

Line above Command menu best practices:
To enable smooth functioning of your bot code, there are few best practices that you must follow.
Correction: To enable smooth functioning of your bot code, there are a few best practices that you must follow.

2022-09-02 12:37 UTC, v-prepatel commented
[msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/14f7b3f31a4214cde10e3398332658ad42100e6d/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md)

After Important, Paragraph 2, Line 1:
Bots in a group or channel only receive messages when they're mentioned @botname.
Correction: Bots in a group or channel only receive messages when they're mentioned with @botname.

Under Note, Line 2:
Using resource-specific consent (RSC), bots can receive all channel messages in teams that it is installed in without being @mentioned.
Correction: Using resource-specific consent (RSC), bots can receive all channel messages in teams that they are installed in without being @mentioned.

Under Design guidelines, Line 1:
Unlike personal chats, in group chats and channels, your bot must provide a quick introduction.
Correction: Unlike in personal chats, in group chats and channels, your bot must provide a quick introduction.

Under Create new conversation threads, Line 2:
At times it's difficult to differentiate between two conversations.
Correction: At times, it's difficult to differentiate between two conversations.

Under Work with mentions, Line 2:
Your bot can also retrieve other users mentioned in a message and add mentions to any messages it sends.
Correction: Your bot can also retrieve other users mentioned in a message and add mentions to any message it sends.

Under Step-by-step guide:
Follow the step-by-step guide, to create a Teams conversational bot.
Correction: Follow the step-by-step guide to create a Teams conversational bot.

2022-09-02 12:37 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/25b493e93cf7a5b8150c8fc5820993bdebe4fb7a/msteams-platform%2Fbots%2Fbot-basics.md) | 93 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4a61e819-7c53-4daa-88c4-73585890d9af) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/25b493e93cf7a5b8150c8fc5820993bdebe4fb7a/msteams-platform%2Fbots%2Fbot-features.md) | 86 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/89b71f7b-5439-4a5a-82b1-213be4071685) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/25b493e93cf7a5b8150c8fc5820993bdebe4fb7a/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/285e7cf4-7b6f-4acf-b9e4-3a43cbca13c4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/25b493e93cf7a5b8150c8fc5820993bdebe4fb7a/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 92 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8d4bd7f0-4541-493b-8554-4b64fc66bc68) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/25b493e93cf7a5b8150c8fc5820993bdebe4fb7a/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-basics.md) | 87 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0494ca6b-f9f3-48a0-9355-92514265d226) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/25b493e93cf7a5b8150c8fc5820993bdebe4fb7a/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-messages.md) | 93 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a29fa8be-dff8-434d-8ae6-e4202c51fef9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/25b493e93cf7a5b8150c8fc5820993bdebe4fb7a/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 94 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/334b7de2-8bb6-4a8e-b9d5-51e29aa51061) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/25b493e93cf7a5b8150c8fc5820993bdebe4fb7a/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsubscribe-to-conversation-events.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/83b0a882-7f5b-4e68-8ce2-e63bc2c76aa5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/create-a-bot-commands-menu.md](https://github.com/MicrosoftDocs/msteams-docs/blob/25b493e93cf7a5b8150c8fc5820993bdebe4fb7a/msteams-platform%2Fbots%2Fhow-to%2Fcreate-a-bot-commands-menu.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/80b1569e-76d0-4788-9792-254528931b4a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/25b493e93cf7a5b8150c8fc5820993bdebe4fb7a/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 89 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/03316428-9286-4456-8f64-159e65acee86) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-09-02 12:38 UTC, opbld31 commented
Docs Build status updates of commit _[25b493e](https://github.com/MicrosoftDocs/msteams-docs/commits/25b493e93cf7a5b8150c8fc5820993bdebe4fb7a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-basics?branch=pr-en-us-6415) |
[msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/bot-features.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-features?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/channel-and-group-conversations?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/channel-messages-with-rsc?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/conversation-basics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-basics?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/conversation-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-messages?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/send-proactive-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/send-proactive-messages?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/subscribe-to-conversation-events?branch=pr-en-us-6415) |
[msteams-platform/bots/how-to/create-a-bot-commands-menu.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/how-to/create-a-bot-commands-menu.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/create-a-bot-commands-menu?branch=pr-en-us-6415) |
[msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/BuildBotsReview/msteams-platform/bots/what-are-bots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/what-are-bots?branch=pr-en-us-6415) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202209021237197211-6415/BuildReport?accessString=fe609f2687edbc9489e4bc47112e6d52c4946b6eba676fe040b8b37b8f6ae624).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-02 12:49 UTC, v-prepatel requested changes
Paragraph 2, Line 2:
Activities are handled in two ways using Teams activity handlers and bot logic.
Correction: Activities are handled in two ways, using Teams activity handlers and bot logic.

Under Teams activity handlers, Paragraph 2, Line 2:
All activities are routed through one base handler called the turn handler.
Correction: All activities are routed through one base handler, called the turn handler.

Under Bot logic, Line 1:
The bot logic processes incoming activities from one or more of your bot channels and in response generates outgoing activities.
Correction: The bot logic processes incoming activities from one or more of your bot channels and, in response, generates outgoing activities.

Table under Core Bot Framework handlers, Row 4, Column 3:
This method calls a handler if members other than the bot joined or left the conversation, on a ConversationUpdate activity.
Correction: This method calls a handler if members other than the bot join or leave the conversation on a ConversationUpdate activity.

Table under Core Bot Framework handlers, Row 7, Column 3:
This method calls a handler specific to the event type, on an Event activity.
Correction: This method calls a handler specific to the event type on an Event activity.

Last Line:
Now that you've familiarized yourself with bot activity handlers, let us see how bots behave differently depending on the conversation and the messages it receives or sends.
Correction: Now that you've familiarized yourself with bot activity handlers, let us see how bots behave differently depending on the conversation and the messages they receive or send.

2022-09-02 12:52 UTC, v-prepatel requested changes
Under Bots with webhooks and connectors, Last Line:
For more information, see what are webhooks and connectors.
Correction: For more information, see what webhooks and connectors are.

Under In a channel, Line 1:
Channels contain threaded conversations between multiple people even up to two thousand.
Correction: Channels contain threaded conversations between multiple people, even up to two thousand.

Under In a channel, Point 3:
Single request or response cycle resolves interactions and the results are useful for multiple members of the conversation.
Correction: Single request or response cycle resolves interactions, and the results are useful for multiple members of the conversation.

Under In a group chat, Paragraph 2:
In the cases where bots work better in a channel also work better in a group chat.
Correction: In the cases where bots work better in a channel, they also work better in a group chat.

Under Have multi-turn experiences in chat:
BOT: I’ve found 200 results, please include a first and last name.
Correction: BOT: I’ve found 200 results. Please include your first and last name.

2022-09-02 12:53 UTC, v-prepatel requested changes
Under Note, Line 1:
It's recommended that you'd create your first bot app or notification bot app using the new generation development tool for Teams.
Correction: It's recommended that you create your first bot app or notification bot app using the new generation development tool for Teams.

First Paragraph after Note, Line 2:
It's an app that runs simple and repetitive tasks by users such as customer service or support staff. 
Correction: It's an app that runs simple and repetitive tasks for users, such as customer service or support staff. 

First Paragraph after Note, Line 3:
Everyday use of bots include, bots that provide information about the weather, make dinner reservations, or provide travel information.
Correction: Everyday uses of bots include bots that provide information about the weather, make dinner reservations, or provide travel information.

After Last Image, Paragraph 2, Line 3:
A bot behaves differently in a channel or group chat conversation and in a one-to-one conversation.
Correction: A bot behaves differently in a channel or group chat conversation than in a one-to-one conversation.

After Last Image, Paragraph 3, Line 1:
Your bot requires contextual information, such as user profile details to access relevant content and enhance the bot experience.
Correction: Your bot requires contextual information, such as user profile details, to access relevant content and enhance the bot experience.

2022-09-02 12:54 UTC, v-prepatel requested changes
Above Note, Point 2, Line 2:
All messages sent by the user routes to your bot.
Correction: All messages sent by the user are routed to your bot.

After Note, Second Paragraph, Line 2:
When a user sends a message, Teams posts the message to your bot and the bot handles the message.
Correction: When a user sends a message, Teams posts the message to your bot, and the bot handles the message.

After Note, Second Paragraph, Line 4:
Bots in a group or channel only receive messages when they are mentioned @botname.
Correction: Bots in a group or channel only receive messages when they are mentioned with @botname.

Last Paragraph, Line 3:
You can format your bot messages to include rich cards that include interactive elements, such as buttons, text, images, audio, video, and so on.
Correction: You can format your bot messages to include rich cards that include interactive elements such as buttons, text, images, audio, video, and so on.

2022-09-02 12:55 UTC, v-prepatel requested changes
Line 3:
Teams sends a JSON object to your bot's messaging endpoint and Teams allows only one endpoint for messaging. Your bot examines the message to determine its type and responds accordingly.
Correction: Teams sends a JSON object to your bot's messaging endpoint, and Teams allows only one endpoint for messaging. Your bot examines the message to determine its type and responds accordingly.

After First 3 Pointers, Line 1:
Your bot receives messages from Teams using the Text property and it sends single or multiple message responses to the users.
Correction: Your bot receives messages from Teams using the Text property, and it sends single or multiple message responses to the users.

Under Send suggested actions, Line 2:
Suggested actions enhance user experience by enabling the user to answer a question or make a choice with selection of a button, rather than typing a response with a keyboard.
Correction: Suggested actions enhance the user experience by enabling the user to answer a question or make a choice with the selection of a button rather than by typing a response with a keyboard.

Under Send suggested actions, Line 3:
The buttons remain visible and accessible to the user in the rich cards even after user makes a selection whereas for suggested actions, buttons aren't available.
Correction: The buttons remain visible and accessible to the user in the rich cards even after the user makes a selection, whereas for suggested actions, the buttons aren't available.

Under Notifications to your message, Second-last Line:
Whether or not a notification is raised depends on the individual user's Teams settings and you can't override these settings.
Correction: Whether or not a notification is raised depends on the individual user's Teams settings, and you can't override these settings.

Under Picture messages, Line 4:
Animated GIF isn't supported.
Correction: Animated GIFs aren't supported.

Under Status code responses:
Following are the status codes and their error code and message values:
Correction: Following are the status codes and their error codes and message values:

Table under Status code responses, Row 6, Column 2:
Message: Precondition failed, please try again.
Correction: Message: Precondition failed. Please try again.

Table under Status code responses, Row 8, Column 3:
The size on the incoming request was too large.
Correction: The size of the incoming request was too large.

2022-09-02 12:56 UTC, v-prepatel requested changes
Line 2:
Using RSC, you can now request team owners to consent for a bot to receive user messages across standard channels in a team without being @mentioned.
Correction: Using RSC, you can now request team owners’ consent for a bot to receive user messages across standard channels in a team without being @mentioned.

Under Note, Point 2, Line 1:
ots must use the ChannelMessage.Read.Group RSC permission appropriately to build and enhance engaging experience for users in the team or they will not pass the store approval.
Correction: ots must use the ChannelMessage.Read.Group RSC permission appropriately to build and enhance an engaging experience for users in the team or they will not pass the store approval.

Under Update app manifest, Point 2:
resource: Any string. This field has no operation in RSC, but must be added and have a value to avoid error response.
Correction: resource: Any string. This field has no operation in RSC but must be added and have a value to avoid an error response.

Under Sideload in a team, Line 1:
To sideload in a team to test, whether all channel messages in a team with RSC are received without being @mentioned:
Correction: To sideload in a team to test whether all channel messages in a team with RSC are received without being @mentioned:

Under Sideload in a team, Point 8:
Select Add from the app details pop-up, to add the bot to your selected team.
Correction: Select Add from the app details pop-up to add the bot to your selected team.

2022-09-02 12:57 UTC, v-prepatel requested changes
Under Note, Line 1:
It's recommended that you'd create a command bot by following the step-by-step guide to Build command bot with JavaScript using the new generation development tool for Teams.
Correction: It's recommended that you create a command bot by following the step-by-step guide to Build command bot with JavaScript using the new generation development tool for Teams.

Under Create a command menu for your bot using Developer Portal, Point 1, Line 2:
In the Apps page, search for Developer Portal, and then select Open.
Correction: On the Apps page, search for Developer Portal, and then select Open.

Under Create a command menu for your bot using Developer Portal, Point 5:
Enter the Command that appears as the command menu for your bot.
Correction: Enter the Command that appears in the command menu for your bot.

Under Handle menu commands in your bot code, Line 1:
Bots in a group or channel respond only when they are mentioned @botname in a message.
Correction: Bots in a group or channel respond only when they are mentioned as @botname in a message.

Under Handle menu commands in your bot code, Under Note, Line 4:
The user must then send that text as they do for any other message.
Correction: The user must then send that text as they would for any other message.

Line above Command menu best practices:
To enable smooth functioning of your bot code, there are few best practices that you must follow.
Correction: To enable smooth functioning of your bot code, there are a few best practices that you must follow.

2022-09-02 12:59 UTC, v-prepatel requested changes
After Important, Paragraph 2, Line 1:
Bots in a group or channel only receive messages when they're mentioned @botname.
Correction: Bots in a group or channel only receive messages when they're mentioned with @botname.

Under Note, Line 2:
Using resource-specific consent (RSC), bots can receive all channel messages in teams that it is installed in without being @mentioned.
Correction: Using resource-specific consent (RSC), bots can receive all channel messages in teams that they are installed in without being @mentioned.

Under Design guidelines, Line 1:
Unlike personal chats, in group chats and channels, your bot must provide a quick introduction.
Correction: Unlike in personal chats, in group chats and channels, your bot must provide a quick introduction.

Under Create new conversation threads, Line 2:
At times it's difficult to differentiate between two conversations.
Correction: At times, it's difficult to differentiate between two conversations.

Under Work with mentions, Line 2:
Your bot can also retrieve other users mentioned in a message and add mentions to any messages it sends.
Correction: Your bot can also retrieve other users mentioned in a message and add mentions to any message it sends.

Under Step-by-step guide:
Follow the step-by-step guide, to create a Teams conversational bot.
Correction: Follow the step-by-step guide to create a Teams conversational bot.

2022-09-02 13:01 UTC, v-prepatel requested changes
Under Conversation update events:
You can use conversation update events to provide better notifications and effective bot actions.
Correction: You can use conversation update events to provide better notifications and more effective bot actions.

Under Conversation update events, Under Important, Point 1:
You can add new events any time and your bot begins to receive them.
Correction: You can add new events at any time and your bot will begin to receive them.

Under Channel restored:
The channelRestored event is sent to your bot, whenever a channel that was previously deleted is restored in a team where your bot is already installed.
Correction: The channelRestored event is sent to your bot whenever a channel that was previously deleted is restored in a team where your bot is already installed.

Under Tip:
Use the InstallationUpdate event to determine when when your bot is added or removed from a conversation.
Correction: Use the InstallationUpdate event to determine when your bot is added or removed from a conversation.

Under Installation update event, Line 1:
The bot receives an installationUpdate event when you install a bot to a conversation thread.
Correction: The bot receives an installationUpdate event when you install a bot into a conversation thread.

Under Installation update event, Last Line:
On installing a bot, the action field in the event is set to add, and when the bot is uninstalled the action field is set to remove.
Correction: On installing a bot, the action field in the event is set to add, and when the bot is uninstalled, the action field is set to remove.

Under Install update event, Line 2:
This event helps you to meet your privacy and data retention requirements.
Correction: This event helps you meet your privacy and data retention requirements.

Under Uninstall behaviour for personal app with bot, Line 2:
When a user sends a message to your app, they receive a 403 response code.
Correction: When a user sends a message to your app, they will receive a 403 response code.

Under Uninstall behaviour for personal app with bot, Line 4:
The post uninstall behaviour for bots in the personal scope with the Teams and groupChat scopes are now aligned.
Correction: The post uninstall behaviour for bots in the personal scope with Teams and groupChat scopes is now aligned.

Under Event handling for install and uninstall events, Point 1: 
You build your bot without the Microsoft Bot Framework SDK, and as a result the bot gives an exception on receiving an unexpected event.
Correction: You build your bot without the Microsoft Bot Framework SDK, and as a result, the bot gives an exception on receiving an unexpected event.

Under Event handling for install and uninstall events, After Point 2, Line 1: 
It's important to know that new events can be added anytime in the future and your bot begins to receive them.
Correction: It's important to know that new events can be added anytime in the future and that your bot will begin to receive them.

2022-09-02 13:02 UTC, v-prepatel requested changes
Under Important 2, Line 2:
For proactive messages the bots should use the following end points for government cloud environments:
Correction: For proactive messages, the bots should use the following end points for government cloud environments:

After Important 2, Paragraph 2, Line 1:
You can proactively install your app using Microsoft Graph in a team, if necessary, or use a custom app policy to install an app in your teams and for organization's users.
Correction: You can proactively install your app using Microsoft Graph in a team, if necessary, or use a custom app policy to install an app in your teams and for your organization's users.

After Important 2, Paragraph 2, Last Line:
For a user to receive proactive messages, install the app for the user or make the user a part of a team in which the app is installed.
Correction: For a user to receive proactive messages, either install the app for the user or make the user a part of a team in which the app is installed.

Before Create the conversation, Second-last Line:
However, install the bot in the team before you can send a proactive message to a channel.
Correction: However, you must install the bot in the team before you can send a proactive message to a channel.

Before Create the conversation, Last Line:
Create the conversation, after you have the user or channel information.
Correction: Create the conversation after you have the user or channel information.

Under Send the message, Line 2:
If you're using the SDK, you must use the continueConversation method, and the conversationId and tenantId to make a direct API call.
Correction: If you're using the SDK, you must use the continueConversation method and the conversationId and tenantId to make a direct API call.

Under Best practices for proactive messaging, Line 1:
Sending proactive messages to the users is an effective way to communicate with your users.
Correction: Sending proactive messages to your users is an effective way to communicate with them.

Under Welcome messages, Line 1:
When proactive messaging is used to send a welcome message to a user, there's no context for why the user receives the message.
Correction: When proactive messaging is used to send a welcome message to a user, there's no context for why the user received the message.

Under Welcome messages, Line 5:
Poor welcome messages can lead the users to block your app.
Correction: Poor welcome messages can lead users to block your app.

Under Notification messages, Point 2:
What was the result? It must be clear, what item is updated to get the notification.
Correction: What was the result? It must be clear what item is updated to get the notification.

Before Scheduled messages, Last Line:
To send messages to a large group of users, for example to your organization, proactively install your app using Graph.
Correction: To send messages to a large group of users, for example, to your organization, proactively install your app using Graph.

Under Scheduled messages, Point 2:
What can user do next? Users can take the required action based on the message content.
Correction: What can users do next? Users can take the required action based on the message content.

2022-09-06 16:24 UTC, v-abirade commented
Closing the PR as obselete.

2022-09-06 16:24 UTC, closed without merging