[Doc Improvement][Updating resolve the filename too long error notes for SBS guides]
MicrosoftDocs/msteams-docs pull request #6496
Opened 2022-07-20 06:14 UTC by v-tanmayirs

2022-07-20 06:15 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-meeting-content-bubble.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/2580ab7467e6452c4c44f8b021b84ee18e53adf7/msteams-platform%2Fsbs-meeting-content-bubble.yml) | 83 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ed2dbf28-df5a-4776-b3ca-6b33a1d5da1c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-token-generator.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/2580ab7467e6452c4c44f8b021b84ee18e53adf7/msteams-platform%2Fsbs-meeting-token-generator.yml) | 88 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a5c2e57e-5ae7-40e0-ae64-a83bbec00c28) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetings-sidepanel.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/2580ab7467e6452c4c44f8b021b84ee18e53adf7/msteams-platform%2Fsbs-meetings-sidepanel.yml) | 85 | 30 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d3dc275f-e9b6-4a66-a157-73e052c9bdfb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetings-stage-view.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/2580ab7467e6452c4c44f8b021b84ee18e53adf7/msteams-platform%2Fsbs-meetings-stage-view.yml) | 87 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aeaf2b84-8013-4a0d-9361-ba2fc62b4ee9) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-07-20 06:16 UTC, opbld32 commented
Docs Build status updates of commit _[2580ab7](https://github.com/MicrosoftDocs/msteams-docs/commits/2580ab7467e6452c4c44f8b021b84ee18e53adf7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/sbs-meeting-content-bubble.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/updating-notes-for-SBS-resolve-the-filename/msteams-platform/sbs-meeting-content-bubble.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-meeting-content-bubble?branch=pr-en-us-6496) |
[msteams-platform/sbs-meetings-sidepanel.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/updating-notes-for-SBS-resolve-the-filename/msteams-platform/sbs-meetings-sidepanel.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-meetings-sidepanel?branch=pr-en-us-6496) |
[msteams-platform/sbs-meetings-stage-view.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/updating-notes-for-SBS-resolve-the-filename/msteams-platform/sbs-meetings-stage-view.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-meetings-stage-view?branch=pr-en-us-6496) |
[msteams-platform/sbs-meeting-token-generator.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/updating-notes-for-SBS-resolve-the-filename/msteams-platform/sbs-meeting-token-generator.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-meeting-token-generator?branch=pr-en-us-6496) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202207200614367168-6496/BuildReport?accessString=68ab5f94c5c2191d76248f5e1dab89da5aec9a79bee1f2c0250005eb2081e5f0).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-20 06:41 UTC, opbld31 commented
Docs Build status updates of commit _[a8b2333](https://github.com/MicrosoftDocs/msteams-docs/commits/a8b23331761b527282b6528380f3ccafd1f1633f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/sbs-gs-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/updating-notes-for-SBS-resolve-the-filename/msteams-platform/sbs-gs-bot.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-bot?branch=pr-en-us-6496) |
[msteams-platform/sbs-gs-javascript.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/updating-notes-for-SBS-resolve-the-filename/msteams-platform/sbs-gs-javascript.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-javascript?branch=pr-en-us-6496) |
[msteams-platform/sbs-gs-msgext.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/updating-notes-for-SBS-resolve-the-filename/msteams-platform/sbs-gs-msgext.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-msgext?branch=pr-en-us-6496) |
[msteams-platform/sbs-meeting-content-bubble.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/updating-notes-for-SBS-resolve-the-filename/msteams-platform/sbs-meeting-content-bubble.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-meeting-content-bubble?branch=pr-en-us-6496) |
[msteams-platform/sbs-meetings-sidepanel.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/updating-notes-for-SBS-resolve-the-filename/msteams-platform/sbs-meetings-sidepanel.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-meetings-sidepanel?branch=pr-en-us-6496) |
[msteams-platform/sbs-meetings-stage-view.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/updating-notes-for-SBS-resolve-the-filename/msteams-platform/sbs-meetings-stage-view.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-meetings-stage-view?branch=pr-en-us-6496) |
[msteams-platform/sbs-meeting-token-generator.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/updating-notes-for-SBS-resolve-the-filename/msteams-platform/sbs-meeting-token-generator.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-meeting-token-generator?branch=pr-en-us-6496) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202207200640549830-6496/BuildReport?accessString=f6bb127fe31478b44b6eac7e0554d9a61428027899174279d112193250672c9b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-20 06:41 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a8b23331761b527282b6528380f3ccafd1f1633f/msteams-platform%2Fsbs-gs-bot.yml) | 91 | 42 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fd3f45de-b4e6-4854-9d2f-de664a45dd62) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-javascript.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a8b23331761b527282b6528380f3ccafd1f1633f/msteams-platform%2Fsbs-gs-javascript.yml) | 91 | 40 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4ffaaf11-f964-4f08-9146-937fdc7aa684) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-msgext.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a8b23331761b527282b6528380f3ccafd1f1633f/msteams-platform%2Fsbs-gs-msgext.yml) | 91 | 45 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/85307d2b-e4a4-48ee-8447-604710e1f8d5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-content-bubble.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a8b23331761b527282b6528380f3ccafd1f1633f/msteams-platform%2Fsbs-meeting-content-bubble.yml) | 83 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/79e80de5-5962-4f6f-9387-71e7a2a0cf05) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-token-generator.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a8b23331761b527282b6528380f3ccafd1f1633f/msteams-platform%2Fsbs-meeting-token-generator.yml) | 88 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ec27f3d0-7fec-41a3-93da-2e9da4573920) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetings-sidepanel.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a8b23331761b527282b6528380f3ccafd1f1633f/msteams-platform%2Fsbs-meetings-sidepanel.yml) | 85 | 30 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/51b3ad5d-bf98-4c77-ab11-d3d074ccc562) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetings-stage-view.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a8b23331761b527282b6528380f3ccafd1f1633f/msteams-platform%2Fsbs-meetings-stage-view.yml) | 87 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b7d5cbf7-4574-484e-b9fa-94e60a0045a4) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-07-20 07:16 UTC, opbld30 commented
Docs Build status updates of commit _[c393f27](https://github.com/MicrosoftDocs/msteams-docs/commits/c393f276f2cc0d4ac7f4f2a0a48ab619bbf89720)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/sbs-gs-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/updating-notes-for-SBS-resolve-the-filename/msteams-platform/sbs-gs-bot.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-bot?branch=pr-en-us-6496) |
[msteams-platform/sbs-gs-javascript.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/updating-notes-for-SBS-resolve-the-filename/msteams-platform/sbs-gs-javascript.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-javascript?branch=pr-en-us-6496) |
[msteams-platform/sbs-gs-msgext.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/updating-notes-for-SBS-resolve-the-filename/msteams-platform/sbs-gs-msgext.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-msgext?branch=pr-en-us-6496) |
[msteams-platform/sbs-meeting-content-bubble.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/updating-notes-for-SBS-resolve-the-filename/msteams-platform/sbs-meeting-content-bubble.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-meeting-content-bubble?branch=pr-en-us-6496) |
[msteams-platform/sbs-meetings-sidepanel.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/updating-notes-for-SBS-resolve-the-filename/msteams-platform/sbs-meetings-sidepanel.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-meetings-sidepanel?branch=pr-en-us-6496) |
[msteams-platform/sbs-meetings-stage-view.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/updating-notes-for-SBS-resolve-the-filename/msteams-platform/sbs-meetings-stage-view.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-meetings-stage-view?branch=pr-en-us-6496) |
[msteams-platform/sbs-meeting-token-generator.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/updating-notes-for-SBS-resolve-the-filename/msteams-platform/sbs-meeting-token-generator.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-meeting-token-generator?branch=pr-en-us-6496) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202207200716191667-6496/BuildReport?accessString=bda907f1776363bed5bdf3b02d2292cb28da53280d97dde6233b236c68874133).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-20 07:17 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c393f276f2cc0d4ac7f4f2a0a48ab619bbf89720/msteams-platform%2Fsbs-gs-bot.yml) | 91 | 41 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6919e616-a240-4766-8380-17af8a73f377) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-javascript.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c393f276f2cc0d4ac7f4f2a0a48ab619bbf89720/msteams-platform%2Fsbs-gs-javascript.yml) | 91 | 40 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2dde5eb9-7bfd-4b1f-9cf1-1b29cf1d3ca3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-msgext.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c393f276f2cc0d4ac7f4f2a0a48ab619bbf89720/msteams-platform%2Fsbs-gs-msgext.yml) | 91 | 45 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/88744094-da82-497d-860f-88c464c3a075) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-content-bubble.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c393f276f2cc0d4ac7f4f2a0a48ab619bbf89720/msteams-platform%2Fsbs-meeting-content-bubble.yml) | 86 | 28 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7a3774b8-4f64-45b9-b73d-221f3c3c830f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-token-generator.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c393f276f2cc0d4ac7f4f2a0a48ab619bbf89720/msteams-platform%2Fsbs-meeting-token-generator.yml) | 89 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/06e521c8-d919-4ab8-b26b-85962cff371f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetings-sidepanel.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c393f276f2cc0d4ac7f4f2a0a48ab619bbf89720/msteams-platform%2Fsbs-meetings-sidepanel.yml) | 85 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e30dfee3-a4a8-455c-8a58-92e5b07d390f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetings-stage-view.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c393f276f2cc0d4ac7f4f2a0a48ab619bbf89720/msteams-platform%2Fsbs-meetings-stage-view.yml) | 87 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/61ad8863-2fc2-4d6b-aea5-693d1c30d3ac) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-07-27 15:50 UTC, v-abirade commented
The doc draft is based on PR #6403.

2022-07-28 06:31 UTC, v-abirade submitted a review, later dismissed
Approved

2022-07-28 15:33 UTC, mobajemu-msft requested changes
"source="~/assets/images/teams-toolkit-v2/spfx-custom-new.png" is not updated with the latest version of the image in the branch. how would you like me to provide the updated image file?

2022-08-02 18:02 UTC, mobajemu-msft commented
#sign-off @v-abirade ready to merge

2022-08-03 04:56 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/155ca71110294130ba6b344ca7cebd69c8417fee/msteams-platform%2Fsbs-gs-bot.yml) | 91 | 41 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e3f8026c-1fe1-4f25-8d9d-77f0693b00a7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-javascript.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/155ca71110294130ba6b344ca7cebd69c8417fee/msteams-platform%2Fsbs-gs-javascript.yml) | 91 | 40 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4bafb50e-0e44-4fdd-aeee-1fb982e5aa19) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-msgext.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/155ca71110294130ba6b344ca7cebd69c8417fee/msteams-platform%2Fsbs-gs-msgext.yml) | 91 | 45 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/316a9f19-8fcc-4d9a-b9b9-411342fbfb7d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-content-bubble.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/155ca71110294130ba6b344ca7cebd69c8417fee/msteams-platform%2Fsbs-meeting-content-bubble.yml) | 86 | 28 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a5a2e277-a522-41fa-b913-5e8688304043) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-token-generator.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/155ca71110294130ba6b344ca7cebd69c8417fee/msteams-platform%2Fsbs-meeting-token-generator.yml) | 89 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f45c8efc-3cb2-497c-a28a-deac36a7fcdc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetings-sidepanel.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/155ca71110294130ba6b344ca7cebd69c8417fee/msteams-platform%2Fsbs-meetings-sidepanel.yml) | 85 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/58b09709-6e42-4cbc-ab79-adeca89018b0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetings-stage-view.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/155ca71110294130ba6b344ca7cebd69c8417fee/msteams-platform%2Fsbs-meetings-stage-view.yml) | 87 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7e3931d4-c62a-4b42-97f5-6270f8fd49ee) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-08-03 04:56 UTC, opbld30 commented
Docs Build status updates of commit _[155ca71](https://github.com/MicrosoftDocs/msteams-docs/commits/155ca71110294130ba6b344ca7cebd69c8417fee)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/sbs-gs-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/updating-notes-for-SBS-resolve-the-filename/msteams-platform/sbs-gs-bot.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-bot?branch=pr-en-us-6496) |
[msteams-platform/sbs-gs-javascript.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/updating-notes-for-SBS-resolve-the-filename/msteams-platform/sbs-gs-javascript.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-javascript?branch=pr-en-us-6496) |
[msteams-platform/sbs-gs-msgext.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/updating-notes-for-SBS-resolve-the-filename/msteams-platform/sbs-gs-msgext.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-msgext?branch=pr-en-us-6496) |
[msteams-platform/sbs-meeting-content-bubble.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/updating-notes-for-SBS-resolve-the-filename/msteams-platform/sbs-meeting-content-bubble.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-meeting-content-bubble?branch=pr-en-us-6496) |
[msteams-platform/sbs-meetings-sidepanel.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/updating-notes-for-SBS-resolve-the-filename/msteams-platform/sbs-meetings-sidepanel.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-meetings-sidepanel?branch=pr-en-us-6496) |
[msteams-platform/sbs-meetings-stage-view.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/updating-notes-for-SBS-resolve-the-filename/msteams-platform/sbs-meetings-stage-view.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-meetings-stage-view?branch=pr-en-us-6496) |
[msteams-platform/sbs-meeting-token-generator.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/updating-notes-for-SBS-resolve-the-filename/msteams-platform/sbs-meeting-token-generator.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-meeting-token-generator?branch=pr-en-us-6496) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202208030455277444-6496/BuildReport?accessString=d44971281d881dfcef4c5c6bf439ce01ab4efd779fc5c772d3c794a36e2a15c5).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-03 05:04 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/495a8d5a9134bfa77798ae3b9ce7387208dfb128/msteams-platform%2Fsbs-gs-bot.yml) | 91 | 41 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/18af3d21-7b88-4460-9b44-6490c4f94c3f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-javascript.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/495a8d5a9134bfa77798ae3b9ce7387208dfb128/msteams-platform%2Fsbs-gs-javascript.yml) | 91 | 40 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cfe3aede-fa63-4a12-b26e-1e4f722e1bf4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-msgext.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/495a8d5a9134bfa77798ae3b9ce7387208dfb128/msteams-platform%2Fsbs-gs-msgext.yml) | 91 | 45 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b84267cf-eaef-4e50-8096-2fa19d29da32) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-content-bubble.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/495a8d5a9134bfa77798ae3b9ce7387208dfb128/msteams-platform%2Fsbs-meeting-content-bubble.yml) | 86 | 28 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0bc962e8-4490-4d9e-b726-8784c6aa7129) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-token-generator.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/495a8d5a9134bfa77798ae3b9ce7387208dfb128/msteams-platform%2Fsbs-meeting-token-generator.yml) | 89 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e5aea4a1-919b-4323-a64c-c820ca877205) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetings-sidepanel.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/495a8d5a9134bfa77798ae3b9ce7387208dfb128/msteams-platform%2Fsbs-meetings-sidepanel.yml) | 85 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/471b0b1f-104d-4a64-8592-5abc642d6dad) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetings-stage-view.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/495a8d5a9134bfa77798ae3b9ce7387208dfb128/msteams-platform%2Fsbs-meetings-stage-view.yml) | 87 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/55940d78-8361-4587-b063-dbcf5084bdb5) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-08-03 05:06 UTC, opbld30 commented
Docs Build status updates of commit _[495a8d5](https://github.com/MicrosoftDocs/msteams-docs/commits/495a8d5a9134bfa77798ae3b9ce7387208dfb128)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/teams-toolkit-v2/spfx-custom-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/updating-notes-for-SBS-resolve-the-filename/msteams-platform/assets/images/teams-toolkit-v2/spfx-custom-new.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-bot?branch=pr-en-us-6496) |
[msteams-platform/sbs-gs-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/updating-notes-for-SBS-resolve-the-filename/msteams-platform/sbs-gs-bot.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-bot?branch=pr-en-us-6496) |
[msteams-platform/sbs-gs-javascript.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/updating-notes-for-SBS-resolve-the-filename/msteams-platform/sbs-gs-javascript.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-javascript?branch=pr-en-us-6496) |
[msteams-platform/sbs-gs-msgext.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/updating-notes-for-SBS-resolve-the-filename/msteams-platform/sbs-gs-msgext.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-msgext?branch=pr-en-us-6496) |
[msteams-platform/sbs-meeting-content-bubble.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/updating-notes-for-SBS-resolve-the-filename/msteams-platform/sbs-meeting-content-bubble.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-meeting-content-bubble?branch=pr-en-us-6496) |
[msteams-platform/sbs-meetings-sidepanel.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/updating-notes-for-SBS-resolve-the-filename/msteams-platform/sbs-meetings-sidepanel.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-meetings-sidepanel?branch=pr-en-us-6496) |
[msteams-platform/sbs-meetings-stage-view.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/updating-notes-for-SBS-resolve-the-filename/msteams-platform/sbs-meetings-stage-view.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-meetings-stage-view?branch=pr-en-us-6496) |
[msteams-platform/sbs-meeting-token-generator.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/updating-notes-for-SBS-resolve-the-filename/msteams-platform/sbs-meeting-token-generator.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-meeting-token-generator?branch=pr-en-us-6496) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202208030506016890-6496/BuildReport?accessString=22bee49df72a3d426699d8abd9a92249332daea082c7b1bd8699ccfcc53e0c64).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-03 05:20 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/0429e1443d69ca420c3e433406860cc53d6bc069/msteams-platform%2Fsbs-gs-bot.yml) | 91 | 41 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2dddc978-56a4-474b-952e-59500f1c1003) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-javascript.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/0429e1443d69ca420c3e433406860cc53d6bc069/msteams-platform%2Fsbs-gs-javascript.yml) | 91 | 40 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d8acc58b-8475-486e-9aa2-963e34df1105) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-msgext.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/0429e1443d69ca420c3e433406860cc53d6bc069/msteams-platform%2Fsbs-gs-msgext.yml) | 91 | 45 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8acb765c-7403-4704-a577-63042d3376d9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-content-bubble.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/0429e1443d69ca420c3e433406860cc53d6bc069/msteams-platform%2Fsbs-meeting-content-bubble.yml) | 86 | 28 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/661a2450-7dc4-41b5-8fe4-df23d7590498) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-token-generator.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/0429e1443d69ca420c3e433406860cc53d6bc069/msteams-platform%2Fsbs-meeting-token-generator.yml) | 89 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4f5a0e8a-12aa-4973-a200-313cdf51210c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetings-sidepanel.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/0429e1443d69ca420c3e433406860cc53d6bc069/msteams-platform%2Fsbs-meetings-sidepanel.yml) | 85 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3221a8d2-cf8a-435a-8812-55e95e09ba9e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetings-stage-view.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/0429e1443d69ca420c3e433406860cc53d6bc069/msteams-platform%2Fsbs-meetings-stage-view.yml) | 87 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/448358d2-c918-45e5-8888-6925b44ae915) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-08-03 05:21 UTC, opbld32 commented
Docs Build status updates of commit _[0429e14](https://github.com/MicrosoftDocs/msteams-docs/commits/0429e1443d69ca420c3e433406860cc53d6bc069)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/sbs-gs-spfx.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/updating-notes-for-SBS-resolve-the-filename/msteams-platform/sbs-gs-spfx.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-6496) | [Details](#user-content-ba8b60b3814caf1cb1b4ded75b049c70-830d2137)
[msteams-platform/assets/images/teams-toolkit-v2/spfx-custom-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/updating-notes-for-SBS-resolve-the-filename/msteams-platform/assets/images/teams-toolkit-v2/spfx-custom-new.png) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-custom-new1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/updating-notes-for-SBS-resolve-the-filename/msteams-platform/assets/images/teams-toolkit-v2/spfx-custom-new1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-bot?branch=pr-en-us-6496) |
[msteams-platform/sbs-gs-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/updating-notes-for-SBS-resolve-the-filename/msteams-platform/sbs-gs-bot.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-bot?branch=pr-en-us-6496) |
[msteams-platform/sbs-gs-javascript.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/updating-notes-for-SBS-resolve-the-filename/msteams-platform/sbs-gs-javascript.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-javascript?branch=pr-en-us-6496) |
[msteams-platform/sbs-gs-msgext.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/updating-notes-for-SBS-resolve-the-filename/msteams-platform/sbs-gs-msgext.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-msgext?branch=pr-en-us-6496) |
[msteams-platform/sbs-meeting-content-bubble.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/updating-notes-for-SBS-resolve-the-filename/msteams-platform/sbs-meeting-content-bubble.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-meeting-content-bubble?branch=pr-en-us-6496) |
[msteams-platform/sbs-meetings-sidepanel.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/updating-notes-for-SBS-resolve-the-filename/msteams-platform/sbs-meetings-sidepanel.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-meetings-sidepanel?branch=pr-en-us-6496) |
[msteams-platform/sbs-meetings-stage-view.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/updating-notes-for-SBS-resolve-the-filename/msteams-platform/sbs-meetings-stage-view.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-meetings-stage-view?branch=pr-en-us-6496) |
[msteams-platform/sbs-meeting-token-generator.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/updating-notes-for-SBS-resolve-the-filename/msteams-platform/sbs-meeting-token-generator.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-meeting-token-generator?branch=pr-en-us-6496) |

<a id="ba8b60b3814caf1cb1b4ded75b049c70-830d2137"></a>
### [msteams-platform/sbs-gs-spfx.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/updating-notes-for-SBS-resolve-the-filename/msteams-platform/sbs-gs-spfx.yml)
 - **Line 113, Column 5**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '~/assets/images/teams-toolkit-v2/spfx-custom-new.png'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202208030520380968-6496/BuildReport?accessString=0b848e198510c7d5c467997813e48039cae5e708187f4957f3a5d867d6c7897f).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-03 05:24 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e9048086c9d753bb6c345cb06c7e3e6262dc775f/msteams-platform%2Fsbs-gs-bot.yml) | 91 | 41 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b61e47bf-317e-41ed-ba6a-68e242fcd907) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-javascript.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e9048086c9d753bb6c345cb06c7e3e6262dc775f/msteams-platform%2Fsbs-gs-javascript.yml) | 91 | 40 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b783e28d-e967-42d5-b030-02c20df73a9a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-msgext.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e9048086c9d753bb6c345cb06c7e3e6262dc775f/msteams-platform%2Fsbs-gs-msgext.yml) | 91 | 45 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8bf86356-8a03-433b-8e43-3e5e2cd6e979) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-spfx.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e9048086c9d753bb6c345cb06c7e3e6262dc775f/msteams-platform%2Fsbs-gs-spfx.yml) | 94 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/87c6b012-d7da-4c1a-ad54-61a4e782378c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-content-bubble.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e9048086c9d753bb6c345cb06c7e3e6262dc775f/msteams-platform%2Fsbs-meeting-content-bubble.yml) | 86 | 28 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f41bbd66-f98f-4925-81f5-47a0685907c9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-token-generator.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e9048086c9d753bb6c345cb06c7e3e6262dc775f/msteams-platform%2Fsbs-meeting-token-generator.yml) | 89 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/af40be33-c53f-4733-a98d-eceef7111f9c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetings-sidepanel.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e9048086c9d753bb6c345cb06c7e3e6262dc775f/msteams-platform%2Fsbs-meetings-sidepanel.yml) | 85 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/369d2439-31e7-40c3-8d09-0b44206c5f78) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetings-stage-view.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e9048086c9d753bb6c345cb06c7e3e6262dc775f/msteams-platform%2Fsbs-meetings-stage-view.yml) | 87 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dda18419-18c7-4273-8606-4fd0a9b43707) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-08-03 05:25 UTC, opbld30 commented
Docs Build status updates of commit _[e904808](https://github.com/MicrosoftDocs/msteams-docs/commits/e9048086c9d753bb6c345cb06c7e3e6262dc775f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/teams-toolkit-v2/spfx-custom-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/updating-notes-for-SBS-resolve-the-filename/msteams-platform/assets/images/teams-toolkit-v2/spfx-custom-new.png) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-custom-new1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/updating-notes-for-SBS-resolve-the-filename/msteams-platform/assets/images/teams-toolkit-v2/spfx-custom-new1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-bot?branch=pr-en-us-6496) |
[msteams-platform/sbs-gs-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/updating-notes-for-SBS-resolve-the-filename/msteams-platform/sbs-gs-bot.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-bot?branch=pr-en-us-6496) |
[msteams-platform/sbs-gs-javascript.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/updating-notes-for-SBS-resolve-the-filename/msteams-platform/sbs-gs-javascript.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-javascript?branch=pr-en-us-6496) |
[msteams-platform/sbs-gs-msgext.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/updating-notes-for-SBS-resolve-the-filename/msteams-platform/sbs-gs-msgext.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-msgext?branch=pr-en-us-6496) |
[msteams-platform/sbs-gs-spfx.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/updating-notes-for-SBS-resolve-the-filename/msteams-platform/sbs-gs-spfx.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-6496) |
[msteams-platform/sbs-meeting-content-bubble.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/updating-notes-for-SBS-resolve-the-filename/msteams-platform/sbs-meeting-content-bubble.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-meeting-content-bubble?branch=pr-en-us-6496) |
[msteams-platform/sbs-meetings-sidepanel.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/updating-notes-for-SBS-resolve-the-filename/msteams-platform/sbs-meetings-sidepanel.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-meetings-sidepanel?branch=pr-en-us-6496) |
[msteams-platform/sbs-meetings-stage-view.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/updating-notes-for-SBS-resolve-the-filename/msteams-platform/sbs-meetings-stage-view.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-meetings-stage-view?branch=pr-en-us-6496) |
[msteams-platform/sbs-meeting-token-generator.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/updating-notes-for-SBS-resolve-the-filename/msteams-platform/sbs-meeting-token-generator.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-meeting-token-generator?branch=pr-en-us-6496) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202208030524168830-6496/BuildReport?accessString=99f5fbb4b5d01d288ff9b9957b6e29d80d9ffe6fa7b0dcdf791934637715ba22).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-03 05:33 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/4aa030c0e50c79ca619ca8a6716e0e1f121f7415/msteams-platform%2Fsbs-gs-bot.yml) | 91 | 41 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/09a9fb45-f786-473e-9403-4d3d0209c063) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-javascript.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/4aa030c0e50c79ca619ca8a6716e0e1f121f7415/msteams-platform%2Fsbs-gs-javascript.yml) | 91 | 40 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/13f19331-b249-4178-9d5b-cbd14fbe2b1a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-msgext.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/4aa030c0e50c79ca619ca8a6716e0e1f121f7415/msteams-platform%2Fsbs-gs-msgext.yml) | 91 | 45 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7299fc79-fae8-4979-a933-907e800257e2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-spfx.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/4aa030c0e50c79ca619ca8a6716e0e1f121f7415/msteams-platform%2Fsbs-gs-spfx.yml) | 94 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fa0c450a-2501-49b2-87d5-de2a4c04f7fe) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-content-bubble.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/4aa030c0e50c79ca619ca8a6716e0e1f121f7415/msteams-platform%2Fsbs-meeting-content-bubble.yml) | 86 | 28 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bc3d0401-3f26-41d6-b39c-0a53c7d25e49) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-token-generator.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/4aa030c0e50c79ca619ca8a6716e0e1f121f7415/msteams-platform%2Fsbs-meeting-token-generator.yml) | 89 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/77d728f8-bde4-4327-aa05-1ff6e0f37fbf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetings-sidepanel.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/4aa030c0e50c79ca619ca8a6716e0e1f121f7415/msteams-platform%2Fsbs-meetings-sidepanel.yml) | 85 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/820827a4-6b10-4718-a5f0-66daf19e8c10) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetings-stage-view.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/4aa030c0e50c79ca619ca8a6716e0e1f121f7415/msteams-platform%2Fsbs-meetings-stage-view.yml) | 87 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4948ac2d-c674-4ce1-a5da-8ddaa026e1ac) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-08-03 05:33 UTC, opbld33 commented
Docs Build status updates of commit _[4aa030c](https://github.com/MicrosoftDocs/msteams-docs/commits/4aa030c0e50c79ca619ca8a6716e0e1f121f7415)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/teams-toolkit-v2/spfx-custom-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/updating-notes-for-SBS-resolve-the-filename/msteams-platform/assets/images/teams-toolkit-v2/spfx-custom-new.png) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-custom-new1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/updating-notes-for-SBS-resolve-the-filename/msteams-platform/assets/images/teams-toolkit-v2/spfx-custom-new1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-bot?branch=pr-en-us-6496) |
[msteams-platform/sbs-gs-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/updating-notes-for-SBS-resolve-the-filename/msteams-platform/sbs-gs-bot.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-bot?branch=pr-en-us-6496) |
[msteams-platform/sbs-gs-javascript.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/updating-notes-for-SBS-resolve-the-filename/msteams-platform/sbs-gs-javascript.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-javascript?branch=pr-en-us-6496) |
[msteams-platform/sbs-gs-msgext.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/updating-notes-for-SBS-resolve-the-filename/msteams-platform/sbs-gs-msgext.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-msgext?branch=pr-en-us-6496) |
[msteams-platform/sbs-gs-spfx.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/updating-notes-for-SBS-resolve-the-filename/msteams-platform/sbs-gs-spfx.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-6496) |
[msteams-platform/sbs-meeting-content-bubble.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/updating-notes-for-SBS-resolve-the-filename/msteams-platform/sbs-meeting-content-bubble.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-meeting-content-bubble?branch=pr-en-us-6496) |
[msteams-platform/sbs-meetings-sidepanel.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/updating-notes-for-SBS-resolve-the-filename/msteams-platform/sbs-meetings-sidepanel.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-meetings-sidepanel?branch=pr-en-us-6496) |
[msteams-platform/sbs-meetings-stage-view.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/updating-notes-for-SBS-resolve-the-filename/msteams-platform/sbs-meetings-stage-view.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-meetings-stage-view?branch=pr-en-us-6496) |
[msteams-platform/sbs-meeting-token-generator.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/updating-notes-for-SBS-resolve-the-filename/msteams-platform/sbs-meeting-token-generator.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-meeting-token-generator?branch=pr-en-us-6496) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202208030532450715-6496/BuildReport?accessString=f8633ad54cf1a9b42827db70e2de585e622823d720aceb133339e6911c15c51e).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-03 06:55 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/2e25a52eefd19fc9a4da91f3868dd7031ce81a03/msteams-platform%2Fsbs-gs-bot.yml) | 91 | 41 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d4f85781-1631-4949-bd1e-71d0e01ef7fe) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-javascript.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/2e25a52eefd19fc9a4da91f3868dd7031ce81a03/msteams-platform%2Fsbs-gs-javascript.yml) | 91 | 40 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5c55adad-2fc5-448f-bec9-656628a5ae55) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-msgext.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/2e25a52eefd19fc9a4da91f3868dd7031ce81a03/msteams-platform%2Fsbs-gs-msgext.yml) | 91 | 45 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b3ebd886-fab9-4dc1-b11c-fd52ed80d282) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-spfx.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/2e25a52eefd19fc9a4da91f3868dd7031ce81a03/msteams-platform%2Fsbs-gs-spfx.yml) | 94 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ad825f7c-0a68-461d-a31a-4ddd1ce8a80b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-content-bubble.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/2e25a52eefd19fc9a4da91f3868dd7031ce81a03/msteams-platform%2Fsbs-meeting-content-bubble.yml) | 86 | 28 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c2a5df93-e689-4e30-bb9d-7e71bf382fa3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-token-generator.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/2e25a52eefd19fc9a4da91f3868dd7031ce81a03/msteams-platform%2Fsbs-meeting-token-generator.yml) | 89 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/530858a8-2baa-439e-b331-2068cbd0c356) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetings-sidepanel.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/2e25a52eefd19fc9a4da91f3868dd7031ce81a03/msteams-platform%2Fsbs-meetings-sidepanel.yml) | 85 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2f82eea6-b571-4764-95c3-d74c121e3a92) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetings-stage-view.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/2e25a52eefd19fc9a4da91f3868dd7031ce81a03/msteams-platform%2Fsbs-meetings-stage-view.yml) | 87 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f968099b-f66a-4126-83c9-6c4ef615cd4d) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-08-03 06:55 UTC, opbld32 commented
Docs Build status updates of commit _[2e25a52](https://github.com/MicrosoftDocs/msteams-docs/commits/2e25a52eefd19fc9a4da91f3868dd7031ce81a03)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/teams-toolkit-v2/spfx-custom-new.png](https://github.com/MicrosoftDocs/msteams-docs/blob/updating-notes-for-SBS-resolve-the-filename/msteams-platform/assets/images/teams-toolkit-v2/spfx-custom-new.png) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/teams-toolkit-v2/spfx-custom-new1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/updating-notes-for-SBS-resolve-the-filename/msteams-platform/assets/images/teams-toolkit-v2/spfx-custom-new1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-bot?branch=pr-en-us-6496) |
[msteams-platform/sbs-gs-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/updating-notes-for-SBS-resolve-the-filename/msteams-platform/sbs-gs-bot.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-bot?branch=pr-en-us-6496) |
[msteams-platform/sbs-gs-javascript.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/updating-notes-for-SBS-resolve-the-filename/msteams-platform/sbs-gs-javascript.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-javascript?branch=pr-en-us-6496) |
[msteams-platform/sbs-gs-msgext.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/updating-notes-for-SBS-resolve-the-filename/msteams-platform/sbs-gs-msgext.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-msgext?branch=pr-en-us-6496) |
[msteams-platform/sbs-gs-spfx.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/updating-notes-for-SBS-resolve-the-filename/msteams-platform/sbs-gs-spfx.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?branch=pr-en-us-6496) |
[msteams-platform/sbs-meeting-content-bubble.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/updating-notes-for-SBS-resolve-the-filename/msteams-platform/sbs-meeting-content-bubble.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-meeting-content-bubble?branch=pr-en-us-6496) |
[msteams-platform/sbs-meetings-sidepanel.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/updating-notes-for-SBS-resolve-the-filename/msteams-platform/sbs-meetings-sidepanel.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-meetings-sidepanel?branch=pr-en-us-6496) |
[msteams-platform/sbs-meetings-stage-view.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/updating-notes-for-SBS-resolve-the-filename/msteams-platform/sbs-meetings-stage-view.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-meetings-stage-view?branch=pr-en-us-6496) |
[msteams-platform/sbs-meeting-token-generator.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/updating-notes-for-SBS-resolve-the-filename/msteams-platform/sbs-meeting-token-generator.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/sbs-meeting-token-generator?branch=pr-en-us-6496) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202208030654378788-6496/BuildReport?accessString=bd673913c388c89275be5c90c536bb487b60cec11ad4c9b3d406b4c80295e851).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-05 17:21 UTC, mobajemu-msft approved these changes

2022-08-13 11:57 UTC, v-abirade approved these changes
Approved.

2022-08-15 07:37 UTC, surbhigupta12 approved these changes

2022-08-15 07:37 UTC, merged