[Doc Improvement] Correct CDN import example
MicrosoftDocs/msteams-docs pull request #6872
Opened 2022-09-06 23:57 UTC by erikadoyle

Per https://github.com/OfficeDev/microsoft-teams-library-js/issues/1322

2022-09-06 23:57 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ff09c5b50d0f752087e24abb866fd29f85fa5431/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fcontent-page.md) | 91 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6e4b5295-fc8b-4870-a72c-60a0f42690e5) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-09-06 23:58 UTC, opbld31 commented
Docs Build status updates of commit _[ff09c5b](https://github.com/erikadoyle/msteams-docs/commits/ff09c5b50d0f752087e24abb866fd29f85fa5431)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/tabs/how-to/create-tab-pages/content-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/content-page?branch=pr-en-us-6872) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202209062357263892-6872/BuildReport?accessString=a648c552bc779e03d9f5d82d173c410f9625e7c732791c82d228609c20212db3).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-07 18:36 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/aea54fa323ce4da6555474f2ab45466bf4c6bda2/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-tutorial.md) | 94 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7ce3d47c-e403-40f0-beb8-2d6cd27ee703) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/aea54fa323ce4da6555474f2ab45466bf4c6bda2/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 94 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f97fab0c-2af4-48f9-adc2-3cbc6984dc8f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/aea54fa323ce4da6555474f2ab45466bf4c6bda2/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-channel-group-tab.md) | 96 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b199465a-004e-4a5f-b5b5-bd7054a0213b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/aea54fa323ce4da6555474f2ab45466bf4c6bda2/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-personal-tab.md) | 93 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/671c2f82-b3c4-4ded-8b1d-f0e268970080) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/aea54fa323ce4da6555474f2ab45466bf4c6bda2/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fconfiguration-page.md) | 93 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/04d61309-53c0-4727-88b5-e0023d26ed3b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/aea54fa323ce4da6555474f2ab45466bf4c6bda2/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fcontent-page.md) | 91 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d4a6fdf8-0cc1-4fa9-9316-9ba07666f1f3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/removal-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/aea54fa323ce4da6555474f2ab45466bf4c6bda2/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fremoval-page.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c4e43b8b-8cb1-47a2-81c1-f99244936af5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/MicrosoftDocs/msteams-docs/blob/aea54fa323ce4da6555474f2ab45466bf4c6bda2/msteams-platform%2Fwebhooks-and-connectors%2Fhow-to%2Fconnectors-creating.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/47e29d15-2b96-4257-b2ad-1d1be2434276) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-09-07 18:38 UTC, opbld31 commented
Docs Build status updates of commit _[aea54fa](https://github.com/erikadoyle/msteams-docs/commits/aea54fa323ce4da6555474f2ab45466bf4c6bda2)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-cc5de8b5)

<a id="cc5de8b5"></a>
###
 - **[Error: RuningBuildFailed]** `````Some unexpected errors happened when running build, please open a ticket in https://aka.ms/SiteHelp and include the error report for our team to troubleshoot`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202209071836036980-6872/BuildReport?accessString=95682c836840473c8407356f2891ca575949964c2eb611bc559423807fa80e2f).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-07 18:44 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/aea54fa323ce4da6555474f2ab45466bf4c6bda2/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-tutorial.md) | 94 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/632a015a-7e3a-477c-b65a-82fa6811c914) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/aea54fa323ce4da6555474f2ab45466bf4c6bda2/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 94 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/58cbc008-b84b-447f-a5fa-a54ff76c229e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/aea54fa323ce4da6555474f2ab45466bf4c6bda2/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-channel-group-tab.md) | 96 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cc4950d0-5f2c-4d4c-8453-41e9110bca19) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/aea54fa323ce4da6555474f2ab45466bf4c6bda2/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-personal-tab.md) | 93 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/830ae39d-bc1f-47a6-9505-8fc229ee9c4c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/aea54fa323ce4da6555474f2ab45466bf4c6bda2/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fconfiguration-page.md) | 93 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e748fa4a-565d-4c24-9438-c77a0de29a4b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/aea54fa323ce4da6555474f2ab45466bf4c6bda2/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fcontent-page.md) | 91 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a179fdf8-f371-4726-b6ed-55160d507fd9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/removal-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/aea54fa323ce4da6555474f2ab45466bf4c6bda2/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fremoval-page.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e0035cb0-89cb-4d39-b5c9-da666a4ed7ee) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/MicrosoftDocs/msteams-docs/blob/aea54fa323ce4da6555474f2ab45466bf4c6bda2/msteams-platform%2Fwebhooks-and-connectors%2Fhow-to%2Fconnectors-creating.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fd3f6579-c4a6-476e-a46e-e5cdfbc3952c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-09-07 18:46 UTC, opbld32 commented
Docs Build status updates of commit _[aea54fa](https://github.com/erikadoyle/msteams-docs/commits/aea54fa323ce4da6555474f2ab45466bf4c6bda2)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-477ec3b7)

<a id="477ec3b7"></a>
###
 - **[Error: RuningBuildFailed]** `````Some unexpected errors happened when running build, please open a ticket in https://aka.ms/SiteHelp and include the error report for our team to troubleshoot`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202209071843285867-6872/BuildReport?accessString=6a4b1b1e321ab0a0080df0debc26b6c9209edb3ff9c556ca7d71c00debd49876).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-07 18:50 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/aea54fa323ce4da6555474f2ab45466bf4c6bda2/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-tutorial.md) | 94 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b502d367-6511-480f-9884-2b071e540fba) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/aea54fa323ce4da6555474f2ab45466bf4c6bda2/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 94 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7ab2ec44-a74c-4365-94d2-5023c0cd3e75) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/aea54fa323ce4da6555474f2ab45466bf4c6bda2/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-channel-group-tab.md) | 96 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c5982006-aafe-4089-9843-e47b7dc9a661) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/aea54fa323ce4da6555474f2ab45466bf4c6bda2/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-personal-tab.md) | 93 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2653e754-0847-4156-a303-0e30dc147b27) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/aea54fa323ce4da6555474f2ab45466bf4c6bda2/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fconfiguration-page.md) | 93 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9311828c-2f99-418a-b581-f17864d6a678) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/aea54fa323ce4da6555474f2ab45466bf4c6bda2/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fcontent-page.md) | 91 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4e866902-4764-46d7-aa15-4f3d10dcd4bb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/removal-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/aea54fa323ce4da6555474f2ab45466bf4c6bda2/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fremoval-page.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/42383c9e-128f-400d-84d5-9fd1c93bd151) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/MicrosoftDocs/msteams-docs/blob/aea54fa323ce4da6555474f2ab45466bf4c6bda2/msteams-platform%2Fwebhooks-and-connectors%2Fhow-to%2Fconnectors-creating.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f8a5369a-0130-46f1-826a-e847a3f59416) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-09-07 18:56 UTC, opbld31 commented
Docs Build status updates of commit _[aea54fa](https://github.com/erikadoyle/msteams-docs/commits/aea54fa323ce4da6555474f2ab45466bf4c6bda2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/teams-live-share-tutorial.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/apps-in-teams-meetings/teams-live-share-tutorial.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/teams-live-share-tutorial?branch=pr-en-us-6872) |
[msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow?branch=pr-en-us-6872) |
[msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/tabs/how-to/create-channel-group-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-6872) |
[msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/tabs/how-to/create-personal-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-6872) |
[msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/configuration-page?branch=pr-en-us-6872) |
[msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/tabs/how-to/create-tab-pages/content-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/content-page?branch=pr-en-us-6872) |
[msteams-platform/tabs/how-to/create-tab-pages/removal-page.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/tabs/how-to/create-tab-pages/removal-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/removal-page?branch=pr-en-us-6872) |
[msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-creating?branch=pr-en-us-6872) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202209071850064203-6872/BuildReport?accessString=25149ac499f9bc229b7e4d5447af699c30a87fda61673f0a3ba5e94bc53ca785).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-07 21:08 UTC, erikadoyle commented
#assign-reviewer:@nwojod-MSFT

2022-09-07 21:19 UTC, nwojod-MSFT approved these changes
Looks good.

2022-09-07 21:21 UTC, nwojod-MSFT approved these changes

2022-09-07 21:22 UTC, nwojod-MSFT reviewed
Changes look good.

2022-09-09 13:34 UTC, v-abirade requested changes

2022-09-09 13:34 UTC, v-abirade commented on msteams-platform/apps-in-teams-meetings/teams-live-share-tutorial.md
> +Teams meeting apps require multiple views (content, configuration, and stage). We'll create a `start()` function to help identify the view to render and to perform any initialization that's required.
Teams meeting apps require multiple views, such as content, configuration, and stage. You can create a `start()` function to help identify the view. This helps to render and perform any initialization that's required. The app supports running both locally in a web browser and from within a Teams Meeting. The `start()` function looks for an `inTeams=true` query parameter to determine if it's running in Teams. 

> [!NOTE]
> When running in Teams your application needs to call `app.initialize()` prior to calling any other teams-js methods.

2022-09-09 13:34 UTC, v-abirade commented on msteams-platform/tabs/how-to/create-personal-tab.md
> +1. In Visual Studio Solution Explorer open **PersonalTab.cshtml** from **Pages** folder and add `microsoftTeams.app.initialize()` in the `<script>` tags and save.
In Visual Studio Solution Explorer open **PersonalTab.cshtml** from **Pages** folder and add `microsoftTeams.app.initialize()` in the `<script>` tags and select **Save**.

This is a global comment. Please make changes wherever required.

2022-09-09 19:12 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/aea22f501fd506a4a16fb1e8c190748d424dfcb3/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-tutorial.md) | 94 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1e99b3b9-627a-4442-8798-c002f09b057c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/aea22f501fd506a4a16fb1e8c190748d424dfcb3/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 94 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7701c977-40ab-447a-a896-9fc58787b081) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/aea22f501fd506a4a16fb1e8c190748d424dfcb3/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-channel-group-tab.md) | 96 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f64f5b70-2f12-420e-bbfc-4827a5b85216) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/aea22f501fd506a4a16fb1e8c190748d424dfcb3/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-personal-tab.md) | 93 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0da68fab-1bc3-41bc-a450-ecdc0019aa8a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/aea22f501fd506a4a16fb1e8c190748d424dfcb3/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fconfiguration-page.md) | 93 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7ac88a6d-3777-42bd-97c9-c1277b1cc159) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/aea22f501fd506a4a16fb1e8c190748d424dfcb3/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fcontent-page.md) | 91 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/63b2e2e9-eceb-4823-b1cd-2aa517daefc0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/removal-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/aea22f501fd506a4a16fb1e8c190748d424dfcb3/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fremoval-page.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f78c6fdd-9cdd-4392-8fc0-4eda246cbd52) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/MicrosoftDocs/msteams-docs/blob/aea22f501fd506a4a16fb1e8c190748d424dfcb3/msteams-platform%2Fwebhooks-and-connectors%2Fhow-to%2Fconnectors-creating.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/51e9e355-90b9-4abf-990d-e23b81805147) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-09-09 19:13 UTC, erikadoyle commented
Thanks @v-abirade. Would you mind taking another look and/or helping to merge?

2022-09-09 19:13 UTC, opbld32 commented
Docs Build status updates of commit _[aea22f5](https://github.com/erikadoyle/msteams-docs/commits/aea22f501fd506a4a16fb1e8c190748d424dfcb3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/teams-live-share-tutorial.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/apps-in-teams-meetings/teams-live-share-tutorial.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/teams-live-share-tutorial?branch=pr-en-us-6872) |
[msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow?branch=pr-en-us-6872) |
[msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/tabs/how-to/create-channel-group-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-6872) |
[msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/tabs/how-to/create-personal-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-6872) |
[msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/configuration-page?branch=pr-en-us-6872) |
[msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/tabs/how-to/create-tab-pages/content-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/content-page?branch=pr-en-us-6872) |
[msteams-platform/tabs/how-to/create-tab-pages/removal-page.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/tabs/how-to/create-tab-pages/removal-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/removal-page?branch=pr-en-us-6872) |
[msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-creating?branch=pr-en-us-6872) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202209091912071564-6872/BuildReport?accessString=52ed208e2d8942721421e3e4c2e1efffe032006ecbc3cdfdd19b9dc81d5bd643).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-15 17:41 UTC, erikadoyle commented
Hi @v-abirade, would you mind reviewing again?

2022-09-19 05:29 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bf3ff2e9c1adf8efb0b548255a6d93d685337227/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-tutorial.md) | 94 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b9b26494-22bf-4fd3-b61b-42fb53fe2fe5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bf3ff2e9c1adf8efb0b548255a6d93d685337227/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 94 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/46933dd7-e41f-4433-9b98-9e0e774c46f0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bf3ff2e9c1adf8efb0b548255a6d93d685337227/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-channel-group-tab.md) | 96 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/09de557a-9e1c-4539-88cb-297ef93e47ee) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bf3ff2e9c1adf8efb0b548255a6d93d685337227/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-personal-tab.md) | 93 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/279c2fe9-54e4-4359-a741-b935cbe1680e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bf3ff2e9c1adf8efb0b548255a6d93d685337227/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fconfiguration-page.md) | 93 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f530c7ad-d223-42f4-95dc-d9a719435031) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bf3ff2e9c1adf8efb0b548255a6d93d685337227/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fcontent-page.md) | 91 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/64e1b787-f78c-45ef-84d6-5414dc284820) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/removal-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bf3ff2e9c1adf8efb0b548255a6d93d685337227/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fremoval-page.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/595c6d91-106c-4a79-b9c3-37443da6724e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bf3ff2e9c1adf8efb0b548255a6d93d685337227/msteams-platform%2Fwebhooks-and-connectors%2Fhow-to%2Fconnectors-creating.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0a26d60f-18a4-46b5-826e-829fe919ff3a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-09-19 05:29 UTC, opbld30 commented
Docs Build status updates of commit _[bf3ff2e](https://github.com/erikadoyle/msteams-docs/commits/bf3ff2e9c1adf8efb0b548255a6d93d685337227)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/teams-live-share-tutorial.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/apps-in-teams-meetings/teams-live-share-tutorial.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/teams-live-share-tutorial?branch=pr-en-us-6872) |
[msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow?branch=pr-en-us-6872) |
[msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/tabs/how-to/create-channel-group-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-6872) |
[msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/tabs/how-to/create-personal-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-6872) |
[msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/configuration-page?branch=pr-en-us-6872) |
[msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/tabs/how-to/create-tab-pages/content-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/content-page?branch=pr-en-us-6872) |
[msteams-platform/tabs/how-to/create-tab-pages/removal-page.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/tabs/how-to/create-tab-pages/removal-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/removal-page?branch=pr-en-us-6872) |
[msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-creating?branch=pr-en-us-6872) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202209190529008633-6872/BuildReport?accessString=4fc353f18fb4c94bd2019754f6580ca4a856bcd00e4fe93867e27eb70870340e).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-19 05:44 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4361ef7a040214a55666d554e054bca3ac29de02/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-tutorial.md) | 94 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/af0bfbd7-506e-4603-9d2e-3e6bf277b96b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4361ef7a040214a55666d554e054bca3ac29de02/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 94 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aee29556-617f-4d3e-a2f2-7463010520c7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4361ef7a040214a55666d554e054bca3ac29de02/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-channel-group-tab.md) | 96 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5236973f-885c-4192-a887-3461cf905119) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4361ef7a040214a55666d554e054bca3ac29de02/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-personal-tab.md) | 94 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7f4df6e1-4681-4d6b-88f1-8c073b8297c7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4361ef7a040214a55666d554e054bca3ac29de02/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fconfiguration-page.md) | 93 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f9a8859c-3bcf-40f0-a3e2-027b36c6a1c1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4361ef7a040214a55666d554e054bca3ac29de02/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fcontent-page.md) | 91 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/941e0d71-c7a0-47e8-ac66-727cd9bbeed8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/removal-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4361ef7a040214a55666d554e054bca3ac29de02/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fremoval-page.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fc570ef8-d99e-4671-97e0-668fc70696ec) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4361ef7a040214a55666d554e054bca3ac29de02/msteams-platform%2Fwebhooks-and-connectors%2Fhow-to%2Fconnectors-creating.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9dd70991-1e13-4497-8772-0b0f9cd3351a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-09-19 05:48 UTC, opbld30 commented
Docs Build status updates of commit _[4361ef7](https://github.com/erikadoyle/msteams-docs/commits/4361ef7a040214a55666d554e054bca3ac29de02)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/teams-live-share-tutorial.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/apps-in-teams-meetings/teams-live-share-tutorial.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/teams-live-share-tutorial?branch=pr-en-us-6872) |
[msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow?branch=pr-en-us-6872) |
[msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/tabs/how-to/create-channel-group-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-6872) |
[msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/tabs/how-to/create-personal-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-6872) |
[msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/configuration-page?branch=pr-en-us-6872) |
[msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/tabs/how-to/create-tab-pages/content-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/content-page?branch=pr-en-us-6872) |
[msteams-platform/tabs/how-to/create-tab-pages/removal-page.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/tabs/how-to/create-tab-pages/removal-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/removal-page?branch=pr-en-us-6872) |
[msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-creating?branch=pr-en-us-6872) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202209190544426117-6872/BuildReport?accessString=61f669e549871b43f0a29db483c0a0e27f01807ef0494da3c8da08a18c95f099).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-23 03:01 UTC, v-abirade requested changes

2022-09-23 03:01 UTC, v-abirade commented on msteams-platform/apps-in-teams-meetings/teams-live-share-tutorial.md
> +Teams meeting apps require multiple views, such as content, configuration, and stage. We'll create a `start()` function to help identify the view. This helps to render and perform any initialization
```Suggestion
Teams meeting apps require multiple views, such as content, configuration, and stage. You can create a `start()` function to help identify the view. This helps to render and perform any initialization that's required. The app supports running both locally in a web browser and from within a Teams Meeting. The `start()` function looks for an `inTeams=true` query parameter to determine if it's running in Teams.

2022-09-25 20:05 UTC, v-abirade requested changes
Please make changes.

2022-09-27 17:48 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dfea0ed5f2105f2d398e8984adc4c5f801e37696/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-tutorial.md) | 94 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/25019aae-4f39-4b04-a03b-2b0605c9ff2e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dfea0ed5f2105f2d398e8984adc4c5f801e37696/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 94 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/913c96d4-7eb9-4c18-96eb-e70a5291c298) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dfea0ed5f2105f2d398e8984adc4c5f801e37696/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-channel-group-tab.md) | 96 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ba40d2e4-6369-4d28-bc0a-5592dd99d3bf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dfea0ed5f2105f2d398e8984adc4c5f801e37696/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-personal-tab.md) | 95 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1e5fafff-917e-4aeb-acc1-cb7a9a96656e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dfea0ed5f2105f2d398e8984adc4c5f801e37696/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fconfiguration-page.md) | 93 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3a474ad1-d461-4b75-aeff-8fb8ed5624b9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dfea0ed5f2105f2d398e8984adc4c5f801e37696/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fcontent-page.md) | 91 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/829444d8-191c-4bc4-9169-78df658f4abf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/removal-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dfea0ed5f2105f2d398e8984adc4c5f801e37696/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fremoval-page.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1a011b05-48c4-42b4-90a1-37ede30d4b80) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dfea0ed5f2105f2d398e8984adc4c5f801e37696/msteams-platform%2Fwebhooks-and-connectors%2Fhow-to%2Fconnectors-creating.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a4f4b473-d211-4561-9ecd-8fcfa57ad308) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-09-27 17:49 UTC, opbld30 commented
Docs Build status updates of commit _[dfea0ed](https://github.com/erikadoyle/msteams-docs/commits/dfea0ed5f2105f2d398e8984adc4c5f801e37696)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/teams-live-share-tutorial.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/apps-in-teams-meetings/teams-live-share-tutorial.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/teams-live-share-tutorial?branch=pr-en-us-6872) |
[msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow?branch=pr-en-us-6872) |
[msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/tabs/how-to/create-channel-group-tab.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-6872) |
[msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/tabs/how-to/create-personal-tab.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-6872) |
[msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/configuration-page?branch=pr-en-us-6872) |
[msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/tabs/how-to/create-tab-pages/content-page.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/content-page?branch=pr-en-us-6872) |
[msteams-platform/tabs/how-to/create-tab-pages/removal-page.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/tabs/how-to/create-tab-pages/removal-page.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/removal-page?branch=pr-en-us-6872) |
[msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-creating?branch=pr-en-us-6872) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202209271747515569-6872/BuildReport?accessString=8820984ccaffd9aa7fa0f93dbda6c414a4a3d0cd72c5ef3834ebc06e3eac5d3f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-27 17:50 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/097bdba98d7b134e81131e19f6bbda345f4bf31d/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-tutorial.md) | 94 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ac16c7a1-c38c-4a5c-a357-60fc79b68683) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/097bdba98d7b134e81131e19f6bbda345f4bf31d/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 94 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0d13b531-55f2-4737-931c-4c803d7cb57a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/097bdba98d7b134e81131e19f6bbda345f4bf31d/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-channel-group-tab.md) | 96 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/927c3edd-4459-445b-94f7-bf111dd2dfa7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/097bdba98d7b134e81131e19f6bbda345f4bf31d/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-personal-tab.md) | 95 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6f3ab814-b649-40f9-a8f7-14aadac9478c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/097bdba98d7b134e81131e19f6bbda345f4bf31d/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fconfiguration-page.md) | 93 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dbc3c574-b5e3-43c5-a65a-4e3a6926be79) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/097bdba98d7b134e81131e19f6bbda345f4bf31d/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fcontent-page.md) | 91 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/643f0bf6-b155-47c3-a14c-b6c963b072f5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/removal-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/097bdba98d7b134e81131e19f6bbda345f4bf31d/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fremoval-page.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/551b033a-0e6d-49e4-b3c1-dfd3be7c4c0e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/MicrosoftDocs/msteams-docs/blob/097bdba98d7b134e81131e19f6bbda345f4bf31d/msteams-platform%2Fwebhooks-and-connectors%2Fhow-to%2Fconnectors-creating.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/af1dd771-0cea-41be-81f3-36a510097884) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-09-27 17:51 UTC, opbld33 commented
Docs Build status updates of commit _[097bdba](https://github.com/erikadoyle/msteams-docs/commits/097bdba98d7b134e81131e19f6bbda345f4bf31d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/teams-live-share-tutorial.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/apps-in-teams-meetings/teams-live-share-tutorial.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/teams-live-share-tutorial?branch=pr-en-us-6872) |
[msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow?branch=pr-en-us-6872) |
[msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/tabs/how-to/create-channel-group-tab.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-6872) |
[msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/tabs/how-to/create-personal-tab.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-6872) |
[msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/configuration-page?branch=pr-en-us-6872) |
[msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/tabs/how-to/create-tab-pages/content-page.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/content-page?branch=pr-en-us-6872) |
[msteams-platform/tabs/how-to/create-tab-pages/removal-page.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/tabs/how-to/create-tab-pages/removal-page.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/removal-page?branch=pr-en-us-6872) |
[msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-creating?branch=pr-en-us-6872) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202209271750120836-6872/BuildReport?accessString=4a4c93bf3b2f62824ac1e34d27af8154c8ddc647df4329b0fa525beb355328af).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-10-03 20:13 UTC, erikadoyle commented
@v-abirade would you mind taking another look? Thanks!

2022-10-06 05:02 UTC, v-abirade commented
> @v-abirade would you mind taking another look? Thanks!

Sure, I shall share the same today.

2022-10-10 10:19 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6367c9731f6e650a9bccc7797f6280c7d42fa796/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-tutorial.md) | 94 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e8eb6f05-2f22-4b03-a0b8-56b980500ef1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6367c9731f6e650a9bccc7797f6280c7d42fa796/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 94 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/11f76d69-297d-4c15-851c-58fa87467b8f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6367c9731f6e650a9bccc7797f6280c7d42fa796/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-channel-group-tab.md) | 96 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aa28235d-26b2-4f3d-89f6-7fcbccc7d4f3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6367c9731f6e650a9bccc7797f6280c7d42fa796/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-personal-tab.md) | 94 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8382ddf6-7f4f-4c81-adb0-8d56e0f53167) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6367c9731f6e650a9bccc7797f6280c7d42fa796/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fconfiguration-page.md) | 93 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/01e8d17f-3ea5-4f59-bb76-a2fe4698167a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6367c9731f6e650a9bccc7797f6280c7d42fa796/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fcontent-page.md) | 91 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b5ab15b7-3cb4-4cf4-a63c-556f2173f630) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/removal-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6367c9731f6e650a9bccc7797f6280c7d42fa796/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fremoval-page.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/432a4996-bb28-432d-909b-9ec66ac1e287) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6367c9731f6e650a9bccc7797f6280c7d42fa796/msteams-platform%2Fwebhooks-and-connectors%2Fhow-to%2Fconnectors-creating.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a769bc37-bb9f-4f61-b3dc-53c022619cad) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-10-10 10:20 UTC, opbld30 commented
Learn Build status updates of commit _[6367c97](https://github.com/erikadoyle/msteams-docs/commits/6367c9731f6e650a9bccc7797f6280c7d42fa796)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/teams-live-share-tutorial.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/apps-in-teams-meetings/teams-live-share-tutorial.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/teams-live-share-tutorial?branch=pr-en-us-6872) |
[msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow?branch=pr-en-us-6872) |
[msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/tabs/how-to/create-channel-group-tab.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-6872) |
[msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/tabs/how-to/create-personal-tab.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-6872) |
[msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/configuration-page?branch=pr-en-us-6872) |
[msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/tabs/how-to/create-tab-pages/content-page.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/content-page?branch=pr-en-us-6872) |
[msteams-platform/tabs/how-to/create-tab-pages/removal-page.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/tabs/how-to/create-tab-pages/removal-page.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/removal-page?branch=pr-en-us-6872) |
[msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-creating?branch=pr-en-us-6872) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202210101019235096-6872/BuildReport?accessString=cc9df45c0bdcb1e4cb67b489fb4b4e9a938d4e6646c4c0c9b88285fdeeced27e).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-10 11:59 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0a8ed563a29559255f47e24be37ada22fb4fcc9c/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-tutorial.md) | 94 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2b4c0f0a-58c7-4686-8458-63eefef8423d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0a8ed563a29559255f47e24be37ada22fb4fcc9c/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 94 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fc19a8ce-ef7f-4a79-af26-62ca825687f0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0a8ed563a29559255f47e24be37ada22fb4fcc9c/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-channel-group-tab.md) | 99 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/976d01aa-474e-4eb4-9823-102ac76cd702) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0a8ed563a29559255f47e24be37ada22fb4fcc9c/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-personal-tab.md) | 98 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c287be53-e281-410d-9f2a-c399d46293d2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0a8ed563a29559255f47e24be37ada22fb4fcc9c/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fconfiguration-page.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/18d57325-5b13-4f8b-9552-7ff4514769e6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0a8ed563a29559255f47e24be37ada22fb4fcc9c/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fcontent-page.md) | 93 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7d45ea10-1536-4414-8bc7-60295e5389bb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/removal-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0a8ed563a29559255f47e24be37ada22fb4fcc9c/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fremoval-page.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8d02cde2-ac11-4f0e-97d0-d352800cefac) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0a8ed563a29559255f47e24be37ada22fb4fcc9c/msteams-platform%2Fwebhooks-and-connectors%2Fhow-to%2Fconnectors-creating.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b6fc8809-b36c-4356-9ac0-05c7df79eca7) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-10-10 12:00 UTC, opbld33 commented
Learn Build status updates of commit _[0a8ed56](https://github.com/erikadoyle/msteams-docs/commits/0a8ed563a29559255f47e24be37ada22fb4fcc9c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/teams-live-share-tutorial.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/apps-in-teams-meetings/teams-live-share-tutorial.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/teams-live-share-tutorial?branch=pr-en-us-6872) |
[msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow?branch=pr-en-us-6872) |
[msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/tabs/how-to/create-channel-group-tab.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-6872) |
[msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/tabs/how-to/create-personal-tab.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-6872) |
[msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/configuration-page?branch=pr-en-us-6872) |
[msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/tabs/how-to/create-tab-pages/content-page.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/content-page?branch=pr-en-us-6872) |
[msteams-platform/tabs/how-to/create-tab-pages/removal-page.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/tabs/how-to/create-tab-pages/removal-page.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/removal-page?branch=pr-en-us-6872) |
[msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-creating?branch=pr-en-us-6872) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202210101159270299-6872/BuildReport?accessString=af913c876cef9f976d846a1fd8da1becc9d3cb9b90cf50a40bc9f86817651e62).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-10 13:20 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2e5465d0b70ccf9a7a8be2c50b71af5ceb1454a6/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-tutorial.md) | 94 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3d4e65e1-77ed-48d5-8d41-39451a591c98) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2e5465d0b70ccf9a7a8be2c50b71af5ceb1454a6/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 94 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fe227078-50d4-4a8d-969b-8aaf5d4c18ab) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2e5465d0b70ccf9a7a8be2c50b71af5ceb1454a6/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-channel-group-tab.md) | 99 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a0713973-b9fb-4848-836b-ad6d5bb541a4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2e5465d0b70ccf9a7a8be2c50b71af5ceb1454a6/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-personal-tab.md) | 98 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/183d3457-d6b3-459f-81fe-395655549af8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2e5465d0b70ccf9a7a8be2c50b71af5ceb1454a6/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fconfiguration-page.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fcef2c24-16a3-4297-8f52-67fd45eda65e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2e5465d0b70ccf9a7a8be2c50b71af5ceb1454a6/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fcontent-page.md) | 93 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/94164b38-d191-4531-b179-43be05d441fc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/removal-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2e5465d0b70ccf9a7a8be2c50b71af5ceb1454a6/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fremoval-page.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a1f2cec9-6ba0-47fa-9974-997b52e4249d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2e5465d0b70ccf9a7a8be2c50b71af5ceb1454a6/msteams-platform%2Fwebhooks-and-connectors%2Fhow-to%2Fconnectors-creating.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9346f34c-6004-4196-8f60-03a7a55389a4) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-10-10 13:20 UTC, opbld32 commented
Learn Build status updates of commit _[2e5465d](https://github.com/erikadoyle/msteams-docs/commits/2e5465d0b70ccf9a7a8be2c50b71af5ceb1454a6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/teams-live-share-tutorial.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/apps-in-teams-meetings/teams-live-share-tutorial.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/teams-live-share-tutorial?branch=pr-en-us-6872) |
[msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow?branch=pr-en-us-6872) |
[msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/tabs/how-to/create-channel-group-tab.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-6872) |
[msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/tabs/how-to/create-personal-tab.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-6872) |
[msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/configuration-page?branch=pr-en-us-6872) |
[msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/tabs/how-to/create-tab-pages/content-page.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/content-page?branch=pr-en-us-6872) |
[msteams-platform/tabs/how-to/create-tab-pages/removal-page.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/tabs/how-to/create-tab-pages/removal-page.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/removal-page?branch=pr-en-us-6872) |
[msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-creating?branch=pr-en-us-6872) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202210101319520357-6872/BuildReport?accessString=b539d6f7d8ad6e4329b56348152f777735eb076239e7ad33f8f7a9a85ace64b6).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-12 06:05 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b160db323cf27670dc633cbb843dc072c3986ce4/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-tutorial.md) | 94 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e1b6e1fb-8d31-4506-b7fa-7bebb94f3a20) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b160db323cf27670dc633cbb843dc072c3986ce4/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 94 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9733313e-c58f-4dcd-a2b4-ad9c7bf8bb84) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b160db323cf27670dc633cbb843dc072c3986ce4/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-channel-group-tab.md) | 99 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d42047ee-1cac-495a-8299-f7425d72deb1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b160db323cf27670dc633cbb843dc072c3986ce4/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-personal-tab.md) | 98 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4784dca0-e41d-40ad-adb0-1ec9733cc863) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b160db323cf27670dc633cbb843dc072c3986ce4/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fconfiguration-page.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fa5e572e-c30c-4e01-bd97-bc8038a9ccf9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b160db323cf27670dc633cbb843dc072c3986ce4/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fcontent-page.md) | 93 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b8984d12-6477-40e3-ab67-df5a86ce544a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/removal-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b160db323cf27670dc633cbb843dc072c3986ce4/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fremoval-page.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6e714453-bc99-4545-8aed-2252ae2cb23f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b160db323cf27670dc633cbb843dc072c3986ce4/msteams-platform%2Fwebhooks-and-connectors%2Fhow-to%2Fconnectors-creating.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e4c4fe56-d703-42ea-9665-e116a4a28df0) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-10-12 06:06 UTC, opbld31 commented
Learn Build status updates of commit _[b160db3](https://github.com/erikadoyle/msteams-docs/commits/b160db323cf27670dc633cbb843dc072c3986ce4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/teams-live-share-tutorial.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/apps-in-teams-meetings/teams-live-share-tutorial.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/teams-live-share-tutorial?branch=pr-en-us-6872) |
[msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow?branch=pr-en-us-6872) |
[msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/tabs/how-to/create-channel-group-tab.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-6872) |
[msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/tabs/how-to/create-personal-tab.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-6872) |
[msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/configuration-page?branch=pr-en-us-6872) |
[msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/tabs/how-to/create-tab-pages/content-page.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/content-page?branch=pr-en-us-6872) |
[msteams-platform/tabs/how-to/create-tab-pages/removal-page.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/tabs/how-to/create-tab-pages/removal-page.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/removal-page?branch=pr-en-us-6872) |
[msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-creating?branch=pr-en-us-6872) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202210120605208458-6872/BuildReport?accessString=23368af6171356c8c5f71481c0ef2b44e01467132197dd4b6197846d5ccd3dd1).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-12 06:32 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9a522677d1f93d915931572ea27f4ed9ad1caaca/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-tutorial.md) | 94 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/72208273-0d58-46bd-8644-4c7dfc844135) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9a522677d1f93d915931572ea27f4ed9ad1caaca/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 94 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/74be92cf-e8ef-42b8-8429-a680196e0e45) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9a522677d1f93d915931572ea27f4ed9ad1caaca/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-channel-group-tab.md) | 99 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/68902a1f-5903-473d-8f58-e32b882179e6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9a522677d1f93d915931572ea27f4ed9ad1caaca/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-personal-tab.md) | 98 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c6f2f66c-32df-4ef4-b16b-2873fb073636) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9a522677d1f93d915931572ea27f4ed9ad1caaca/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fconfiguration-page.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/09b84eac-1828-4bf1-9347-2b469aecf789) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9a522677d1f93d915931572ea27f4ed9ad1caaca/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fcontent-page.md) | 93 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d61e3358-a64b-42d8-96e5-4f25bcf0986d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/removal-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9a522677d1f93d915931572ea27f4ed9ad1caaca/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fremoval-page.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/029331f8-6c39-4ddf-b456-1526c97cc432) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9a522677d1f93d915931572ea27f4ed9ad1caaca/msteams-platform%2Fwebhooks-and-connectors%2Fhow-to%2Fconnectors-creating.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dcaca58a-d100-47ab-b9af-29538869fea5) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-10-12 06:33 UTC, opbld33 commented
Learn Build status updates of commit _[9a52267](https://github.com/erikadoyle/msteams-docs/commits/9a522677d1f93d915931572ea27f4ed9ad1caaca)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-d18fd91c)

<a id="d18fd91c"></a>
###
 - **[Error: CannotMergeCommit]** `````Cannot merge commit 9a522677d1f93d915931572ea27f4ed9ad1caaca in branch cdn-import-fix of repository https://github.com/erikadoyle/msteams-docs into branch main (commit 6c0a9522d3dd57ebe7a5525dbca7a1cd285c21b2). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202210120632363752-6872/BuildReport?accessString=6e84bed6b13d463c45374c680645e9c79adbadfa4a6490e52783831ee02e0b55).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-12 06:34 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0fe3eaeeaa975766ca10c17dfb75ec4c1c6902dd/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-tutorial.md) | 93 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0fc714b1-746c-4425-9aa9-f5d85ea8cf63) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0fe3eaeeaa975766ca10c17dfb75ec4c1c6902dd/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 94 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b81499a3-20dc-4685-a489-d112d67e2150) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0fe3eaeeaa975766ca10c17dfb75ec4c1c6902dd/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-channel-group-tab.md) | 99 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/770a9f82-2629-4728-8078-3f16cb80b195) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0fe3eaeeaa975766ca10c17dfb75ec4c1c6902dd/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-personal-tab.md) | 98 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bd3144cc-cdc1-40cd-81d6-ab14062d1c44) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0fe3eaeeaa975766ca10c17dfb75ec4c1c6902dd/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fconfiguration-page.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7c58c708-eff0-4639-b74a-73ad42d853d9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0fe3eaeeaa975766ca10c17dfb75ec4c1c6902dd/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fcontent-page.md) | 93 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ad20e296-b23a-4b4a-9d4e-fedd38583084) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/removal-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0fe3eaeeaa975766ca10c17dfb75ec4c1c6902dd/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fremoval-page.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/833bb4ef-20b2-49e3-9a91-bad926b5f2bb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0fe3eaeeaa975766ca10c17dfb75ec4c1c6902dd/msteams-platform%2Fwebhooks-and-connectors%2Fhow-to%2Fconnectors-creating.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8ed2c95d-6555-4592-9113-fb28d37d7424) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-10-12 06:35 UTC, opbld31 commented
Learn Build status updates of commit _[0fe3eae](https://github.com/erikadoyle/msteams-docs/commits/0fe3eaeeaa975766ca10c17dfb75ec4c1c6902dd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/teams-live-share-tutorial.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/apps-in-teams-meetings/teams-live-share-tutorial.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/teams-live-share-tutorial?branch=pr-en-us-6872) |
[msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow?branch=pr-en-us-6872) |
[msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/tabs/how-to/create-channel-group-tab.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-6872) |
[msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/tabs/how-to/create-personal-tab.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-6872) |
[msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/configuration-page?branch=pr-en-us-6872) |
[msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/tabs/how-to/create-tab-pages/content-page.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/content-page?branch=pr-en-us-6872) |
[msteams-platform/tabs/how-to/create-tab-pages/removal-page.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/tabs/how-to/create-tab-pages/removal-page.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/removal-page?branch=pr-en-us-6872) |
[msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-creating?branch=pr-en-us-6872) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202210120634041717-6872/BuildReport?accessString=069be84b55faba4aa0a3ccb1eef661d0adbc670c7f147f36e1acdcaee50ca9db).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-12 06:36 UTC, v-abirade submitted a review, later dismissed
Approve

2022-10-12 06:56 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b0ecaa5222737141e6bd252c0b409a8eca207bf7/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-tutorial.md) | 93 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/81f89598-4edf-4967-8e89-b16bf10cc9a8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b0ecaa5222737141e6bd252c0b409a8eca207bf7/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 94 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3561eef7-e9dc-42f6-82b6-b3d02dadc37f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b0ecaa5222737141e6bd252c0b409a8eca207bf7/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-channel-group-tab.md) | 99 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1e51fde8-b9ea-4a27-b29f-07a7f20dde30) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b0ecaa5222737141e6bd252c0b409a8eca207bf7/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-personal-tab.md) | 97 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/579663a2-d800-4b19-881d-f28a55cb4d11) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b0ecaa5222737141e6bd252c0b409a8eca207bf7/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fconfiguration-page.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a280e16b-6a2c-4402-8103-98d7b4c5f885) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b0ecaa5222737141e6bd252c0b409a8eca207bf7/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fcontent-page.md) | 93 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/466d8588-7774-4d99-ae1f-17d9892de5bf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/removal-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b0ecaa5222737141e6bd252c0b409a8eca207bf7/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fremoval-page.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4b1f7db6-f7ec-4de2-b1a2-7ea088cfe37a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b0ecaa5222737141e6bd252c0b409a8eca207bf7/msteams-platform%2Fwebhooks-and-connectors%2Fhow-to%2Fconnectors-creating.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ff3b916c-888d-4899-8205-0090f329b78a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-10-12 06:56 UTC, opbld31 commented
Learn Build status updates of commit _[b0ecaa5](https://github.com/erikadoyle/msteams-docs/commits/b0ecaa5222737141e6bd252c0b409a8eca207bf7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/teams-live-share-tutorial.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/apps-in-teams-meetings/teams-live-share-tutorial.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/teams-live-share-tutorial?branch=pr-en-us-6872) |
[msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow?branch=pr-en-us-6872) |
[msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/tabs/how-to/create-channel-group-tab.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-6872) |
[msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/tabs/how-to/create-personal-tab.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-6872) |
[msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/configuration-page?branch=pr-en-us-6872) |
[msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/tabs/how-to/create-tab-pages/content-page.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/content-page?branch=pr-en-us-6872) |
[msteams-platform/tabs/how-to/create-tab-pages/removal-page.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/tabs/how-to/create-tab-pages/removal-page.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/removal-page?branch=pr-en-us-6872) |
[msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-creating?branch=pr-en-us-6872) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202210120655521484-6872/BuildReport?accessString=75bc0b913f1a2493cae4c385e3b1fb8cf73c2708d6325679c9072b758c1bf9a9).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-12 07:07 UTC, opbld30 commented
Learn Build status updates of commit _[e87b472](https://github.com/erikadoyle/msteams-docs/commits/e87b47212ceb001465a0992c33efa043495a329c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/teams-live-share-tutorial.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/apps-in-teams-meetings/teams-live-share-tutorial.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/teams-live-share-tutorial?branch=pr-en-us-6872) |
[msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow?branch=pr-en-us-6872) |
[msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/tabs/how-to/create-channel-group-tab.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-6872) |
[msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/tabs/how-to/create-personal-tab.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-6872) |
[msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/configuration-page?branch=pr-en-us-6872) |
[msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/tabs/how-to/create-tab-pages/content-page.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/content-page?branch=pr-en-us-6872) |
[msteams-platform/tabs/how-to/create-tab-pages/removal-page.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/tabs/how-to/create-tab-pages/removal-page.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/removal-page?branch=pr-en-us-6872) |
[msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-creating?branch=pr-en-us-6872) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202210120706246861-6872/BuildReport?accessString=a5a6ea8159a571b02697c8b2a804c533e9d5ce95eeddff5ccd68b0eed737f050).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-12 08:11 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1e06743c7fbcd1ebc2f14c4dbc318fca9543c206/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-tutorial.md) | 92 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/01566e98-7369-48e3-b9c7-80e973bc6afe) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1e06743c7fbcd1ebc2f14c4dbc318fca9543c206/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 94 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e25aa10a-5b03-41e1-bf8a-182bfdf06f21) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1e06743c7fbcd1ebc2f14c4dbc318fca9543c206/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-channel-group-tab.md) | 99 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f6b263dc-09fc-47cd-9104-fe0de63f9f5c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1e06743c7fbcd1ebc2f14c4dbc318fca9543c206/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-personal-tab.md) | 97 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4987504f-c20c-4dd9-9c50-00b8094928ef) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1e06743c7fbcd1ebc2f14c4dbc318fca9543c206/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fconfiguration-page.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f364aede-a8d5-4839-a3ed-1c30dc325c88) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1e06743c7fbcd1ebc2f14c4dbc318fca9543c206/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fcontent-page.md) | 93 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d3688a2f-4f2a-4592-b865-b229dea1bb27) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/removal-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1e06743c7fbcd1ebc2f14c4dbc318fca9543c206/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fremoval-page.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/687b3b7d-f6af-4551-92a4-c891fa97d4a7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1e06743c7fbcd1ebc2f14c4dbc318fca9543c206/msteams-platform%2Fwebhooks-and-connectors%2Fhow-to%2Fconnectors-creating.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e90231af-ff90-447e-9b40-d166361e4163) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-10-12 08:12 UTC, opbld33 commented
Learn Build status updates of commit _[1e06743](https://github.com/erikadoyle/msteams-docs/commits/1e06743c7fbcd1ebc2f14c4dbc318fca9543c206)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/teams-live-share-tutorial.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/apps-in-teams-meetings/teams-live-share-tutorial.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/teams-live-share-tutorial?branch=pr-en-us-6872) |
[msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow?branch=pr-en-us-6872) |
[msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/tabs/how-to/create-channel-group-tab.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?branch=pr-en-us-6872) |
[msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/tabs/how-to/create-personal-tab.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab?branch=pr-en-us-6872) |
[msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/configuration-page?branch=pr-en-us-6872) |
[msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/tabs/how-to/create-tab-pages/content-page.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/content-page?branch=pr-en-us-6872) |
[msteams-platform/tabs/how-to/create-tab-pages/removal-page.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/tabs/how-to/create-tab-pages/removal-page.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/removal-page?branch=pr-en-us-6872) |
[msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/erikadoyle/msteams-docs/blob/cdn-import-fix/msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-creating?branch=pr-en-us-6872) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202210120811149612-6872/BuildReport?accessString=2c938dd58fa66bdd0003199e5745c09fb3045dfe3f6fc4278487630d7b523c8e).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-12 08:42 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5b730c85faa59e936995ac2a71744b3c03a80588/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-tutorial.md) | 92 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b8312572-d741-42f5-a746-af173b3ab717) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5b730c85faa59e936995ac2a71744b3c03a80588/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 94 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3cae2af9-baa1-4266-8169-04b03e8bb80d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5b730c85faa59e936995ac2a71744b3c03a80588/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-channel-group-tab.md) | 99 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/41c2faaa-bf35-48d2-a592-dde9e1c6fd4c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5b730c85faa59e936995ac2a71744b3c03a80588/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-personal-tab.md) | 97 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ff5db18f-a577-4431-aa17-2f19ed15a8ea) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5b730c85faa59e936995ac2a71744b3c03a80588/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fconfiguration-page.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7c407034-9d5a-46f5-b358-0895c4a8f88d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5b730c85faa59e936995ac2a71744b3c03a80588/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fcontent-page.md) | 93 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3ef82ad4-71e1-4f2d-a73a-056431ad89b7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/removal-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5b730c85faa59e936995ac2a71744b3c03a80588/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fremoval-page.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/32c11fd3-f09c-4a9e-a2d0-deb13b35baa4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5b730c85faa59e936995ac2a71744b3c03a80588/msteams-platform%2Fwebhooks-and-connectors%2Fhow-to%2Fconnectors-creating.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/342c94b4-d07e-4c87-8623-3c8d404a9a8b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-10-12 08:44 UTC, v-abirade approved these changes
Approved

2022-10-12 14:04 UTC, merged