[Doc Improvement][Add details for Get app content stage sharing capabilities API][2487612]
MicrosoftDocs/msteams-docs pull request #7001
Opened 2022-09-20 11:54 UTC by v-npaladugu

2022-09-20 11:54 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/API-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/51db519caee5ca6ad781655346bde4a2d9fb9a7d/msteams-platform%2Fapps-in-teams-meetings%2FAPI-references.md) | 92 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8596d39f-250d-486d-9011-a0dbb7a0ff64) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-09-20 11:55 UTC, opbld31 commented
Docs Build status updates of commit _[51db519](https://github.com/MicrosoftDocs/msteams-docs/commits/51db519caee5ca6ad781655346bde4a2d9fb9a7d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/API-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-improvement-content-stage-sharing-capabilities/msteams-platform/apps-in-teams-meetings/API-references.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/api-references?branch=pr-en-us-7001) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202209201154130120-7001/BuildReport?accessString=73de7532853e9f2b42634a9dc0abd2d3ae0bf3e1a28de72f58daba58d2d65e3c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-22 06:39 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/API-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/90d15e1681cc93c2b2e8fdef59bd0db37012b00b/msteams-platform%2Fapps-in-teams-meetings%2FAPI-references.md) | 92 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e7513431-5875-475a-b71d-4747bb7da620) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-09-22 06:40 UTC, opbld31 commented
Docs Build status updates of commit _[90d15e1](https://github.com/MicrosoftDocs/msteams-docs/commits/90d15e1681cc93c2b2e8fdef59bd0db37012b00b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/API-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-improvement-content-stage-sharing-capabilities/msteams-platform/apps-in-teams-meetings/API-references.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/api-references?branch=pr-en-us-7001) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202209220639103656-7001/BuildReport?accessString=2fde2cfb26567d15b607664d26c4eba831f26d49ec184ea92f9ec1a99ce50ec1).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-22 12:53 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/API-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/eceb2219e6e9458336427639c74e37393f37a60a/msteams-platform%2Fapps-in-teams-meetings%2FAPI-references.md) | 91 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/681e624c-a113-49bc-91dc-5a2304e78287) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-09-23 05:02 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/API-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/acf3b19894817d1775891f71442bab00198544eb/msteams-platform%2Fapps-in-teams-meetings%2FAPI-references.md) | 91 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/909a9b9e-27e4-4314-8d35-2654c335bcec) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-09-23 05:03 UTC, opbld33 commented
Docs Build status updates of commit _[acf3b19](https://github.com/MicrosoftDocs/msteams-docs/commits/acf3b19894817d1775891f71442bab00198544eb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/API-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-improvement-content-stage-sharing-capabilities/msteams-platform/apps-in-teams-meetings/API-references.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/api-references?branch=pr-en-us-7001) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202209230501517815-7001/BuildReport?accessString=d108e623edc2087c6f9be55eb07791c888b642937e23cae9a80a704faa27efa6).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-23 06:36 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/API-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fdff88e0fd49e225d9727a200073fa34957fabf5/msteams-platform%2Fapps-in-teams-meetings%2FAPI-references.md) | 91 | 33 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b127d9e9-fe4e-4d89-852e-58ddb32f53e8) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-09-23 06:38 UTC, opbld30 commented
Docs Build status updates of commit _[fdff88e](https://github.com/MicrosoftDocs/msteams-docs/commits/fdff88e0fd49e225d9727a200073fa34957fabf5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/API-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-improvement-content-stage-sharing-capabilities/msteams-platform/apps-in-teams-meetings/API-references.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/api-references?branch=pr-en-us-7001) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202209230637174215-7001/BuildReport?accessString=b6b08aeb4d4cec625a1585a874d2123d60075d63147d2be4eb7ad18c00734bda).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-23 13:07 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/API-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/294d1c92fe3e674455c3c936ec0a01f99d2817b5/msteams-platform%2Fapps-in-teams-meetings%2FAPI-references.md) | 91 | 33 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/56fb0bd5-5a29-494a-b588-3971a3b7b81c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-09-23 13:09 UTC, opbld32 commented
Docs Build status updates of commit _[294d1c9](https://github.com/MicrosoftDocs/msteams-docs/commits/294d1c92fe3e674455c3c936ec0a01f99d2817b5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/API-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-improvement-content-stage-sharing-capabilities/msteams-platform/apps-in-teams-meetings/API-references.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/api-references?branch=pr-en-us-7001) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202209231307317806-7001/BuildReport?accessString=366a06d06842b63b3d2198c6aa6b54c726c3aa26ac0773f7095a15313a2fb1d1).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-23 13:48 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/API-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/91fdc60b4db478d93454584f9c78592cb502e593/msteams-platform%2Fapps-in-teams-meetings%2FAPI-references.md) | 91 | 33 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bc1fff5b-c2b5-49cb-a1b8-2e2cf51aac3b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-09-23 13:49 UTC, opbld33 commented
Docs Build status updates of commit _[91fdc60](https://github.com/MicrosoftDocs/msteams-docs/commits/91fdc60b4db478d93454584f9c78592cb502e593)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/API-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-improvement-content-stage-sharing-capabilities/msteams-platform/apps-in-teams-meetings/API-references.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/api-references?branch=pr-en-us-7001) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202209231348071476-7001/BuildReport?accessString=cac7dbcf315eabe28566fd4d9ee52d16555b3182d69263fff1b84a8d0d91aae4).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-23 13:51 UTC, opbld30 commented
Docs Build status updates of commit _[fda16b2](https://github.com/MicrosoftDocs/msteams-docs/commits/fda16b2207e9df303fd250c8f6f1b145dc0af025)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/API-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-improvement-content-stage-sharing-capabilities/msteams-platform/apps-in-teams-meetings/API-references.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/api-references?branch=pr-en-us-7001) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202209231350423023-7001/BuildReport?accessString=11e604e6e94a73afed90ea8ebdfd62e9b05b3465a0d65a97acbd7146dd6775dc).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-26 03:31 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/API-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4f5d7a2bffda693d9a20a010eee00ad8f8082f9a/msteams-platform%2Fapps-in-teams-meetings%2FAPI-references.md) | 91 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5fc99b2b-268b-4306-a767-f63e66a3ad21) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-09-26 03:32 UTC, opbld31 commented
Docs Build status updates of commit _[4f5d7a2](https://github.com/MicrosoftDocs/msteams-docs/commits/4f5d7a2bffda693d9a20a010eee00ad8f8082f9a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/API-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-improvement-content-stage-sharing-capabilities/msteams-platform/apps-in-teams-meetings/API-references.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/api-references?branch=pr-en-us-7001) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202209260331259768-7001/BuildReport?accessString=47dac9f4341086ac833e9e288179736fdc15e60a3224a54bae965428e5676b46).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-26 05:40 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/API-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/54dfe300ddd1bdaaa2664f6ce58eddd09a527a6b/msteams-platform%2Fapps-in-teams-meetings%2FAPI-references.md) | 91 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7c878922-5194-4680-ba0c-fb2141860d0f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-09-26 05:41 UTC, opbld33 commented
Docs Build status updates of commit _[54dfe30](https://github.com/MicrosoftDocs/msteams-docs/commits/54dfe300ddd1bdaaa2664f6ce58eddd09a527a6b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/API-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-improvement-content-stage-sharing-capabilities/msteams-platform/apps-in-teams-meetings/API-references.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/api-references?branch=pr-en-us-7001) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202209260540037180-7001/BuildReport?accessString=712f390bf56fa77fb161afb5c0357efb2fba619712bb57aa67808e802adb91af).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-26 15:03 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/API-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a218603eb3258f495aac1aa572e64f38316b4913/msteams-platform%2Fapps-in-teams-meetings%2FAPI-references.md) | 91 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e6bc5ed2-7f0e-4f0f-a3ef-e1c4b44b8fd6) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-09-26 15:04 UTC, opbld32 commented
Docs Build status updates of commit _[a218603](https://github.com/MicrosoftDocs/msteams-docs/commits/a218603eb3258f495aac1aa572e64f38316b4913)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/API-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-improvement-content-stage-sharing-capabilities/msteams-platform/apps-in-teams-meetings/API-references.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/api-references?branch=pr-en-us-7001) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202209261503276927-7001/BuildReport?accessString=ca51a5f7a809ae73d790a5c1d691890b78b132518ba3c15dcc7169b5396657ca).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-27 09:51 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/API-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cc4ed3fcc3c25feed5b153d7d7950f111f5a209e/msteams-platform%2Fapps-in-teams-meetings%2FAPI-references.md) | 91 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/13a90f5f-1f6f-4c7c-97f7-dc9689864e58) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-09-27 09:52 UTC, opbld32 commented
Docs Build status updates of commit _[cc4ed3f](https://github.com/MicrosoftDocs/msteams-docs/commits/cc4ed3fcc3c25feed5b153d7d7950f111f5a209e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/API-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-improvement-content-stage-sharing-capabilities/msteams-platform/apps-in-teams-meetings/API-references.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/api-references?branch=pr-en-us-7001) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202209270951188022-7001/BuildReport?accessString=93bbf9ede90b6e7589061147f7f2e4cb21ec84862836425ae1f7bfe4f0801163).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-27 15:47 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/API-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/01fd9b922aa9b1db7bc9d553486ba77238106ded/msteams-platform%2Fapps-in-teams-meetings%2FAPI-references.md) | 91 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e4b35ef2-c3cc-4651-b936-b5f62d3afb63) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-09-27 15:48 UTC, opbld30 commented
Docs Build status updates of commit _[01fd9b9](https://github.com/MicrosoftDocs/msteams-docs/commits/01fd9b922aa9b1db7bc9d553486ba77238106ded)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/API-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-improvement-content-stage-sharing-capabilities/msteams-platform/apps-in-teams-meetings/API-references.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/api-references?branch=pr-en-us-7001) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202209271547200314-7001/BuildReport?accessString=66048fef2136947607420a214526b498d1d118a84c145523a87b8bed6d346af6).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-28 04:28 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/API-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/194714c69c2461341d6af6593cb32f9ef951f806/msteams-platform%2Fapps-in-teams-meetings%2FAPI-references.md) | 91 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/952caf4a-f70b-4286-8295-f87afa0647c9) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-09-28 04:29 UTC, opbld30 commented
Docs Build status updates of commit _[194714c](https://github.com/MicrosoftDocs/msteams-docs/commits/194714c69c2461341d6af6593cb32f9ef951f806)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/API-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-improvement-content-stage-sharing-capabilities/msteams-platform/apps-in-teams-meetings/API-references.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/api-references?branch=pr-en-us-7001) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202209280427569660-7001/BuildReport?accessString=1a2914855f0256ee2196226fc6b2f51f54e2de32f381d2d84bc1e0e5b0c8b5de).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-28 04:38 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/API-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/871ff5db281b3e619db1346c29cdfeed216b1e3f/msteams-platform%2Fapps-in-teams-meetings%2FAPI-references.md) | 91 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aa8859ab-15a3-426b-92b6-2c09e328ce11) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-09-28 04:42 UTC, opbld30 commented
Docs Build status updates of commit _[871ff5d](https://github.com/MicrosoftDocs/msteams-docs/commits/871ff5db281b3e619db1346c29cdfeed216b1e3f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/API-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-improvement-content-stage-sharing-capabilities/msteams-platform/apps-in-teams-meetings/API-references.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/api-references?branch=pr-en-us-7001) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202209280438185993-7001/BuildReport?accessString=e4c6184bf95a718401350f872ccb062c723153643cbc894b6e2af205e68cfb14).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-28 05:41 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/API-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2f67c05b8083d444b80d794cf8721c1661bda665/msteams-platform%2Fapps-in-teams-meetings%2FAPI-references.md) | 91 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fe39afc9-897f-4b45-88ff-dcf50679f4ff) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-09-28 05:42 UTC, opbld32 commented
Docs Build status updates of commit _[2f67c05](https://github.com/MicrosoftDocs/msteams-docs/commits/2f67c05b8083d444b80d794cf8721c1661bda665)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/API-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-improvement-content-stage-sharing-capabilities/msteams-platform/apps-in-teams-meetings/API-references.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/api-references?branch=pr-en-us-7001) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202209280541254530-7001/BuildReport?accessString=660feb5f6422209ed217ffcf9c1c6ba60be2ce9443f0c4b8e398425f9f690c61).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-28 07:51 UTC, juna-gupta requested changes
Please address the comments.

2022-09-28 07:51 UTC, juna-gupta commented on msteams-platform/apps-in-teams-meetings/API-references.md
> +The `getAppContentStageSharingCapabilities` API enables you to fetch the app's capabilities for sharing to meeting stage. The `getAppContentStageSharingCapabilities` API  enables the app to render th
The share to stage button will not appear if a meeting participant doesn't have permission to share app content to the meeting stage.

Applications should call this API to enable/disable custom share to stage buttons for a meeting participant in the meeting side panel.

2022-09-28 07:51 UTC, juna-gupta commented on msteams-platform/apps-in-teams-meetings/API-references.md
Update the comment in the JS example:

"Indicates if the meeting participant has permission to share content to the meeting stage."

2022-10-14 08:37 UTC, opbld30 commented
Learn Build status updates of commit _[9466973](https://github.com/MicrosoftDocs/msteams-docs/commits/9466973f5a93523125ec7ce1b9542dd931bee5e9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/API-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-improvement-content-stage-sharing-capabilities/msteams-platform/apps-in-teams-meetings/API-references.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/api-references?branch=pr-en-us-7001) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202210140833554663-7001/BuildReport?accessString=1c2fc84575bb7e9999d6ff5a0059a1780dd750e330990dd0f5e0ebdc16663555).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-14 10:45 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/API-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/61be35309260c48b220712cafdb78954340057e1/msteams-platform%2Fapps-in-teams-meetings%2FAPI-references.md) | 91 | 33 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/36e5a55b-c4b9-4f35-ac82-bd734629b169) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-10-14 10:46 UTC, opbld32 commented
Learn Build status updates of commit _[61be353](https://github.com/MicrosoftDocs/msteams-docs/commits/61be35309260c48b220712cafdb78954340057e1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/API-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-improvement-content-stage-sharing-capabilities/msteams-platform/apps-in-teams-meetings/API-references.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/api-references?branch=pr-en-us-7001) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202210141045285493-7001/BuildReport?accessString=5e880c3e7c8ac16098d9e116e41bdbd4ccc8fbb4758d5363a69081911174b177).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-07 09:19 UTC, opbld31 commented
Learn Build status updates of commit _[2f1997b](https://github.com/MicrosoftDocs/msteams-docs/commits/2f1997bc07f42a0a39b2c36512bc88da72e34308)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202211070916508327-7001/BuildReport?accessString=be307e67acad20ba060763ec8de4a297c45658fd0c2d65d68224d92f495ea0d7).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-07 10:14 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-teams-meeting-stage.md](https://github.com/MicrosoftDocs/msteams-docs/blob/720d72323e35a41ec1489701c8518fc28aaa921a/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-teams-meeting-stage.md) | 90 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d0cb33be-8390-417d-ad7b-c024651463b3) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-11-07 10:14 UTC, opbld33 commented
Learn Build status updates of commit _[720d723](https://github.com/MicrosoftDocs/msteams-docs/commits/720d72323e35a41ec1489701c8518fc28aaa921a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/build-apps-for-teams-meeting-stage.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-improvement-content-stage-sharing-capabilities/msteams-platform/apps-in-teams-meetings/build-apps-for-teams-meeting-stage.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/build-apps-for-teams-meeting-stage?branch=pr-en-us-7001) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202211071014032384-7001/BuildReport?accessString=b599c27338ed5c4e6149496fe1c3cf14d4adde6dccb12faafebf8a4c2b42c7a6).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-15 14:31 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-teams-meeting-stage.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4fa4aff90c5f33e8d65557a527fbdda85e7b3112/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-teams-meeting-stage.md) | 90 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4e430988-2cd0-4826-9c7b-458c13cac8c8) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-11-15 14:32 UTC, opbld33 commented
Learn Build status updates of commit _[4fa4aff](https://github.com/MicrosoftDocs/msteams-docs/commits/4fa4aff90c5f33e8d65557a527fbdda85e7b3112)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/build-apps-for-teams-meeting-stage.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-improvement-content-stage-sharing-capabilities/msteams-platform/apps-in-teams-meetings/build-apps-for-teams-meeting-stage.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/build-apps-for-teams-meeting-stage?branch=pr-en-us-7001) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202211151431156549-7001/BuildReport?accessString=498520fb2c7b19e8c0f5e3f6187188dc67fccdb3a0e9a994dbb220a9bc18b9fa).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-21 08:06 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-teams-meeting-stage.md](https://github.com/MicrosoftDocs/msteams-docs/blob/47ba92652656acd96b39c968000792820de9691b/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-teams-meeting-stage.md) | 90 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9598af6e-fdde-4f72-b279-9df0090eb441) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-11-21 08:08 UTC, opbld31 commented
Learn Build status updates of commit _[47ba926](https://github.com/MicrosoftDocs/msteams-docs/commits/47ba92652656acd96b39c968000792820de9691b)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-862b2c87)

<a id="862b2c87"></a>
###
 - **Line 0, Column 0**: **[Error: restore-dependent-repository-failed]** `````Failed to restore dependent repository `https://github.com/Microsoft/templates.docs.msft#main`. This could be caused by an incorrect repository URL, please verify the URL on the Docs Portal (https://ops.microsoft.com). If it is not the case, please open a ticket in https://aka.ms/SiteHelp and include URL of the build report.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202211210806227466-7001/BuildReport?accessString=9ea0f5ceacfe4a389275fcb3d3d9b33c66baf66ae30a18d010a02e90101a8415).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-21 16:48 UTC, opbld30 commented
Learn Build status updates of commit _[9e55979](https://github.com/MicrosoftDocs/msteams-docs/commits/9e559791d151ae86941bcc7c5eb9cb096cca49c8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/build-apps-for-teams-meeting-stage.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-improvement-content-stage-sharing-capabilities/msteams-platform/apps-in-teams-meetings/build-apps-for-teams-meeting-stage.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/build-apps-for-teams-meeting-stage?branch=pr-en-us-7001) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202211211647206584-7001/BuildReport?accessString=894092a630b281fd3b2e100399205fc196fc1b5c1f3dff532363e1a99e2bc0b6).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-21 18:26 UTC, juna-gupta submitted a review, later dismissed
Minor fix in the comments

2022-11-21 18:26 UTC, juna-gupta commented on msteams-platform/apps-in-teams-meetings/build-apps-for-teams-meeting-stage.md
> +The `getAppContentStageSharingCapabilities` API enables you to fetch the app's capabilities for sharing the app content to meeting stage. Apps need to call the `getAppContentStageSharingCapabilities`
share to stage button should be disabled/hidden if a meeting participant doesn't have permission to share the app content to the meeting stage.

2022-11-25 04:38 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-teams-meeting-stage.md](https://github.com/MicrosoftDocs/msteams-docs/blob/51d22441bc39295ff8e5147d6d95b26bf6f93613/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-teams-meeting-stage.md) | 90 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/94ceb19d-3502-4ad3-bb53-e3d0d7facf5e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-11-25 04:39 UTC, opbld30 commented
Learn Build status updates of commit _[51d2244](https://github.com/MicrosoftDocs/msteams-docs/commits/51d22441bc39295ff8e5147d6d95b26bf6f93613)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/build-apps-for-teams-meeting-stage.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-improvement-content-stage-sharing-capabilities/msteams-platform/apps-in-teams-meetings/build-apps-for-teams-meeting-stage.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/build-apps-for-teams-meeting-stage?branch=pr-en-us-7001) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202211250438366440-7001/BuildReport?accessString=b7eac9526f2b35ebae6b5304a9e9dce2556239050c67086f32f0377e0b445b8f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-29 11:04 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-teams-meeting-stage.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b0d694c64d8738b446f185309a72beaef2a34ff6/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-teams-meeting-stage.md) | 90 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/de5cc8c2-f01b-4d48-b7f1-97108a7e23ad) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-11-29 11:05 UTC, opbld33 commented
Learn Build status updates of commit _[b0d694c](https://github.com/MicrosoftDocs/msteams-docs/commits/b0d694c64d8738b446f185309a72beaef2a34ff6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/build-apps-for-teams-meeting-stage.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-improvement-content-stage-sharing-capabilities/msteams-platform/apps-in-teams-meetings/build-apps-for-teams-meeting-stage.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/build-apps-for-teams-meeting-stage?branch=pr-en-us-7001) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202211291103554240-7001/BuildReport?accessString=324b0c2ed771df0ca4b43ca55b4a510c228c0ab5a6b84c3f7f81514dc6d74b01).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-29 11:24 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-teams-meeting-stage.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b0719d3b5b88b589f4ccc7c79cc1436ec1a1cb2e/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-teams-meeting-stage.md) | 91 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4dbeb056-60ea-48f1-b709-bda38b183971) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-11-29 11:24 UTC, opbld33 commented
Learn Build status updates of commit _[b0719d3](https://github.com/MicrosoftDocs/msteams-docs/commits/b0719d3b5b88b589f4ccc7c79cc1436ec1a1cb2e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/build-apps-for-teams-meeting-stage.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-improvement-content-stage-sharing-capabilities/msteams-platform/apps-in-teams-meetings/build-apps-for-teams-meeting-stage.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/build-apps-for-teams-meeting-stage?branch=pr-en-us-7001) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202211291123582076-7001/BuildReport?accessString=dd307334ea83a1cbed8cccfaed259f1d3f1c1cd1ff0bd13693b96f974b530d05).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-29 11:57 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-teams-meeting-stage.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2137934a0483ef6a11690acc22348cd6549a6ff9/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-teams-meeting-stage.md) | 91 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bd4826e7-8ce1-46cc-ae28-eaf3ce56fa36) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-11-29 11:58 UTC, opbld33 commented
Learn Build status updates of commit _[2137934](https://github.com/MicrosoftDocs/msteams-docs/commits/2137934a0483ef6a11690acc22348cd6549a6ff9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/apps-in-teams-meetings/build-apps-for-teams-meeting-stage.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Doc-improvement-content-stage-sharing-capabilities/msteams-platform/apps-in-teams-meetings/build-apps-for-teams-meeting-stage.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/build-apps-for-teams-meeting-stage?branch=pr-en-us-7001) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202211291157349852-7001/BuildReport?accessString=3568a1f2e7806c30a2a7bf4a960dcfa49aa3abe908fc0ca4ae79a2552b106a2e).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-29 11:58 UTC, surbhigupta12 approved these changes

2022-11-29 11:59 UTC, merged