[Do Not Merge][Doc Improvement][Mobile Android Preview]
MicrosoftDocs/msteams-docs pull request #7009
Opened 2022-09-21 01:12 UTC by mobajemu-msft

2022-09-21 01:12 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/m365-apps/extend-m365-teams-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e608b0c17b919c230113188147b38d178acbb337/msteams-platform%2Fm365-apps%2Fextend-m365-teams-personal-tab.md) | 96 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8dc70190-e0d0-4b49-a556-6917c12ee465) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e608b0c17b919c230113188147b38d178acbb337/msteams-platform%2Fm365-apps%2Foverview.md) | 91 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a890b21b-3d16-4522-9fe6-a78f40bae8ae) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e608b0c17b919c230113188147b38d178acbb337/msteams-platform%2Fm365-apps%2Fprerequisites.md) | 85 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/48ca927f-9d31-49a3-a6fe-5260139940e5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e608b0c17b919c230113188147b38d178acbb337/msteams-platform%2Fm365-apps%2Fpublish.md) | 89 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fdb182e4-a341-4ce3-8377-9869293cb1b3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/using-teams-client-sdk.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e608b0c17b919c230113188147b38d178acbb337/msteams-platform%2Ftabs%2Fhow-to%2Fusing-teams-client-sdk.md) | 92 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5c14b0c3-9494-4300-b1c3-7e494b9b24f5) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-09-21 01:13 UTC, opbld32 commented
Docs Build status updates of commit _[e608b0c](https://github.com/JoshuaPartlow/msteams-docs/commits/e608b0c17b919c230113188147b38d178acbb337)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/m365-apps/extend-m365-teams-personal-tab.md](https://github.com/JoshuaPartlow/msteams-docs/blob/mobajemu-mobile-android-preview-3/msteams-platform/m365-apps/extend-m365-teams-personal-tab.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/extend-m365-teams-personal-tab?branch=pr-en-us-7009) |
[msteams-platform/m365-apps/images/office-android-debug.png](https://github.com/JoshuaPartlow/msteams-docs/blob/mobajemu-mobile-android-preview-3/msteams-platform/m365-apps/images/office-android-debug.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/extend-m365-teams-personal-tab?branch=pr-en-us-7009) |
[msteams-platform/m365-apps/images/office-android-enable-remote-debugging.png](https://github.com/JoshuaPartlow/msteams-docs/blob/mobajemu-mobile-android-preview-3/msteams-platform/m365-apps/images/office-android-enable-remote-debugging.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/extend-m365-teams-personal-tab?branch=pr-en-us-7009) |
[msteams-platform/m365-apps/images/office-android-install.png](https://github.com/JoshuaPartlow/msteams-docs/blob/mobajemu-mobile-android-preview-3/msteams-platform/m365-apps/images/office-android-install.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/prerequisites?branch=pr-en-us-7009) |
[msteams-platform/m365-apps/images/office-android-join-beta.png](https://github.com/JoshuaPartlow/msteams-docs/blob/mobajemu-mobile-android-preview-3/msteams-platform/m365-apps/images/office-android-join-beta.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/prerequisites?branch=pr-en-us-7009) |
[msteams-platform/m365-apps/images/office-mobile-apps.png](https://github.com/JoshuaPartlow/msteams-docs/blob/mobajemu-mobile-android-preview-3/msteams-platform/m365-apps/images/office-mobile-apps.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/extend-m365-teams-personal-tab?branch=pr-en-us-7009) |
[msteams-platform/m365-apps/images/office-mobile-personal-tab.png](https://github.com/JoshuaPartlow/msteams-docs/blob/mobajemu-mobile-android-preview-3/msteams-platform/m365-apps/images/office-mobile-personal-tab.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/overview?branch=pr-en-us-7009) |
[msteams-platform/m365-apps/overview.md](https://github.com/JoshuaPartlow/msteams-docs/blob/mobajemu-mobile-android-preview-3/msteams-platform/m365-apps/overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/overview?branch=pr-en-us-7009) |
[msteams-platform/m365-apps/prerequisites.md](https://github.com/JoshuaPartlow/msteams-docs/blob/mobajemu-mobile-android-preview-3/msteams-platform/m365-apps/prerequisites.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/prerequisites?branch=pr-en-us-7009) |
[msteams-platform/m365-apps/publish.md](https://github.com/JoshuaPartlow/msteams-docs/blob/mobajemu-mobile-android-preview-3/msteams-platform/m365-apps/publish.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/publish?branch=pr-en-us-7009) |
[msteams-platform/tabs/how-to/using-teams-client-sdk.md](https://github.com/JoshuaPartlow/msteams-docs/blob/mobajemu-mobile-android-preview-3/msteams-platform/tabs/how-to/using-teams-client-sdk.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/using-teams-client-sdk?branch=pr-en-us-7009) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202209210112200811-7009/BuildReport?accessString=1c34b3acc1281d83aa79d0b5424d57c0f558908f6e3a0e8f2cb5970ebbde8627).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-21 01:22 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/m365-apps/extend-m365-teams-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/63ad628356686853c38961e184f2cf984befa2ef/msteams-platform%2Fm365-apps%2Fextend-m365-teams-personal-tab.md) | 96 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fe63e7f2-c34b-4576-9e44-3c67a623dbeb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/63ad628356686853c38961e184f2cf984befa2ef/msteams-platform%2Fm365-apps%2Foverview.md) | 91 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9b8a07f8-028f-4252-afa4-fb2488332ec0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/63ad628356686853c38961e184f2cf984befa2ef/msteams-platform%2Fm365-apps%2Fprerequisites.md) | 85 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b60e92fd-887b-455b-9a58-92fa4527b8f0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/63ad628356686853c38961e184f2cf984befa2ef/msteams-platform%2Fm365-apps%2Fpublish.md) | 89 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2aa98620-b3cd-4e66-87e2-cd1dd3b0df56) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/using-teams-client-sdk.md](https://github.com/MicrosoftDocs/msteams-docs/blob/63ad628356686853c38961e184f2cf984befa2ef/msteams-platform%2Ftabs%2Fhow-to%2Fusing-teams-client-sdk.md) | 92 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/84736eb2-4400-4426-bb88-0807f4290cf1) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-09-21 01:23 UTC, opbld31 commented
Docs Build status updates of commit _[63ad628](https://github.com/JoshuaPartlow/msteams-docs/commits/63ad628356686853c38961e184f2cf984befa2ef)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/m365-apps/extend-m365-teams-personal-tab.md](https://github.com/JoshuaPartlow/msteams-docs/blob/mobajemu-mobile-android-preview-3/msteams-platform/m365-apps/extend-m365-teams-personal-tab.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/extend-m365-teams-personal-tab?branch=pr-en-us-7009) |
[msteams-platform/m365-apps/images/office-android-debug.png](https://github.com/JoshuaPartlow/msteams-docs/blob/mobajemu-mobile-android-preview-3/msteams-platform/m365-apps/images/office-android-debug.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/extend-m365-teams-personal-tab?branch=pr-en-us-7009) |
[msteams-platform/m365-apps/images/office-android-enable-remote-debugging.png](https://github.com/JoshuaPartlow/msteams-docs/blob/mobajemu-mobile-android-preview-3/msteams-platform/m365-apps/images/office-android-enable-remote-debugging.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/extend-m365-teams-personal-tab?branch=pr-en-us-7009) |
[msteams-platform/m365-apps/images/office-android-install.png](https://github.com/JoshuaPartlow/msteams-docs/blob/mobajemu-mobile-android-preview-3/msteams-platform/m365-apps/images/office-android-install.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/prerequisites?branch=pr-en-us-7009) |
[msteams-platform/m365-apps/images/office-android-join-beta.png](https://github.com/JoshuaPartlow/msteams-docs/blob/mobajemu-mobile-android-preview-3/msteams-platform/m365-apps/images/office-android-join-beta.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/prerequisites?branch=pr-en-us-7009) |
[msteams-platform/m365-apps/images/office-mobile-apps.png](https://github.com/JoshuaPartlow/msteams-docs/blob/mobajemu-mobile-android-preview-3/msteams-platform/m365-apps/images/office-mobile-apps.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/extend-m365-teams-personal-tab?branch=pr-en-us-7009) |
[msteams-platform/m365-apps/images/office-mobile-personal-tab.png](https://github.com/JoshuaPartlow/msteams-docs/blob/mobajemu-mobile-android-preview-3/msteams-platform/m365-apps/images/office-mobile-personal-tab.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/overview?branch=pr-en-us-7009) |
[msteams-platform/m365-apps/overview.md](https://github.com/JoshuaPartlow/msteams-docs/blob/mobajemu-mobile-android-preview-3/msteams-platform/m365-apps/overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/overview?branch=pr-en-us-7009) |
[msteams-platform/m365-apps/prerequisites.md](https://github.com/JoshuaPartlow/msteams-docs/blob/mobajemu-mobile-android-preview-3/msteams-platform/m365-apps/prerequisites.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/prerequisites?branch=pr-en-us-7009) |
[msteams-platform/m365-apps/publish.md](https://github.com/JoshuaPartlow/msteams-docs/blob/mobajemu-mobile-android-preview-3/msteams-platform/m365-apps/publish.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/publish?branch=pr-en-us-7009) |
[msteams-platform/tabs/how-to/using-teams-client-sdk.md](https://github.com/JoshuaPartlow/msteams-docs/blob/mobajemu-mobile-android-preview-3/msteams-platform/tabs/how-to/using-teams-client-sdk.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/using-teams-client-sdk?branch=pr-en-us-7009) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202209210122164370-7009/BuildReport?accessString=e0db3ed4b8b14e1de2da8f2cc5234ec70197d9febce4b2ba0d3a13a1edb6c22f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-21 16:28 UTC, erikadoyle reviewed
Tweak to the note on Client IDs

2022-09-21 16:28 UTC, erikadoyle commented on msteams-platform/m365-apps/extend-m365-teams-personal-tab.md
> +    > Please note that some Microsoft apps share client IDs as this simplifies SSO and also enables a feature to more easily show up across different Microsoft apps
Let's remove the explanatory part (implementation details):

    > [!NOTE]
    > Some Client IDs are shared across Microsoft 365 client applications.

2022-09-21 17:39 UTC, erikadoyle commented on msteams-platform/m365-apps/extend-m365-teams-personal-tab.md
>  ## Sideload your app in Teams
[Line 165] After it's sideloaded to Teams, your personal tab is available in Outlook and Office. Be sure to sign in with the same credentials you used to sign in to Teams to sideload your app.

. . . could we add this:

After it's sideloaded to Teams, your personal tab is available in Outlook and Office. Be sure to sign in with the same credentials you used to sideload your app in Teams. When running the Office app for Android, you'll need to restart to use your personal tab app from the Office app.

2022-09-21 17:41 UTC, erikadoyle reviewed
More suggestions from Sheena

2022-09-21 19:55 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/m365-apps/extend-m365-teams-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/16dcb03ef89ef560cbc1e94c9a132efe0dcf8499/msteams-platform%2Fm365-apps%2Fextend-m365-teams-personal-tab.md) | 96 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/30f37bdd-dc16-4aa9-94e3-6392f2136fb0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/16dcb03ef89ef560cbc1e94c9a132efe0dcf8499/msteams-platform%2Fm365-apps%2Foverview.md) | 91 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/942506b7-8c68-4c97-af28-4e34987e18c8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/16dcb03ef89ef560cbc1e94c9a132efe0dcf8499/msteams-platform%2Fm365-apps%2Fprerequisites.md) | 85 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/084bcbc9-8cd4-4e5b-8204-6d9a337a1a4a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/16dcb03ef89ef560cbc1e94c9a132efe0dcf8499/msteams-platform%2Fm365-apps%2Fpublish.md) | 89 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4b75ef5b-9f7d-4fc2-b066-4703b6ec4a86) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/using-teams-client-sdk.md](https://github.com/MicrosoftDocs/msteams-docs/blob/16dcb03ef89ef560cbc1e94c9a132efe0dcf8499/msteams-platform%2Ftabs%2Fhow-to%2Fusing-teams-client-sdk.md) | 92 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e4f55380-4cfc-409a-bc7f-4ce3806a4f70) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-09-21 19:56 UTC, opbld32 commented
Docs Build status updates of commit _[16dcb03](https://github.com/JoshuaPartlow/msteams-docs/commits/16dcb03ef89ef560cbc1e94c9a132efe0dcf8499)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/m365-apps/extend-m365-teams-personal-tab.md](https://github.com/JoshuaPartlow/msteams-docs/blob/mobajemu-mobile-android-preview-3/msteams-platform/m365-apps/extend-m365-teams-personal-tab.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/extend-m365-teams-personal-tab?branch=pr-en-us-7009) |
[msteams-platform/m365-apps/images/office-android-debug.png](https://github.com/JoshuaPartlow/msteams-docs/blob/mobajemu-mobile-android-preview-3/msteams-platform/m365-apps/images/office-android-debug.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/extend-m365-teams-personal-tab?branch=pr-en-us-7009) |
[msteams-platform/m365-apps/images/office-android-enable-remote-debugging.png](https://github.com/JoshuaPartlow/msteams-docs/blob/mobajemu-mobile-android-preview-3/msteams-platform/m365-apps/images/office-android-enable-remote-debugging.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/extend-m365-teams-personal-tab?branch=pr-en-us-7009) |
[msteams-platform/m365-apps/images/office-android-install.png](https://github.com/JoshuaPartlow/msteams-docs/blob/mobajemu-mobile-android-preview-3/msteams-platform/m365-apps/images/office-android-install.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/prerequisites?branch=pr-en-us-7009) |
[msteams-platform/m365-apps/images/office-android-join-beta.png](https://github.com/JoshuaPartlow/msteams-docs/blob/mobajemu-mobile-android-preview-3/msteams-platform/m365-apps/images/office-android-join-beta.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/prerequisites?branch=pr-en-us-7009) |
[msteams-platform/m365-apps/images/office-mobile-apps.png](https://github.com/JoshuaPartlow/msteams-docs/blob/mobajemu-mobile-android-preview-3/msteams-platform/m365-apps/images/office-mobile-apps.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/extend-m365-teams-personal-tab?branch=pr-en-us-7009) |
[msteams-platform/m365-apps/images/office-mobile-personal-tab.png](https://github.com/JoshuaPartlow/msteams-docs/blob/mobajemu-mobile-android-preview-3/msteams-platform/m365-apps/images/office-mobile-personal-tab.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/overview?branch=pr-en-us-7009) |
[msteams-platform/m365-apps/overview.md](https://github.com/JoshuaPartlow/msteams-docs/blob/mobajemu-mobile-android-preview-3/msteams-platform/m365-apps/overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/overview?branch=pr-en-us-7009) |
[msteams-platform/m365-apps/prerequisites.md](https://github.com/JoshuaPartlow/msteams-docs/blob/mobajemu-mobile-android-preview-3/msteams-platform/m365-apps/prerequisites.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/prerequisites?branch=pr-en-us-7009) |
[msteams-platform/m365-apps/publish.md](https://github.com/JoshuaPartlow/msteams-docs/blob/mobajemu-mobile-android-preview-3/msteams-platform/m365-apps/publish.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/publish?branch=pr-en-us-7009) |
[msteams-platform/tabs/how-to/using-teams-client-sdk.md](https://github.com/JoshuaPartlow/msteams-docs/blob/mobajemu-mobile-android-preview-3/msteams-platform/tabs/how-to/using-teams-client-sdk.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/using-teams-client-sdk?branch=pr-en-us-7009) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202209211955154144-7009/BuildReport?accessString=9271ac0c29e6117090f2f200a3b9f38e8037d78fa96205c5ff2242d7c5457e42).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-22 02:48 UTC, erikadoyle commented
Hi @surbhigupta12, could someone from your team please review? Thank you!

2022-09-22 03:06 UTC, erikadoyle commented on msteams-platform/m365-apps/publish.md
> +Microsoft 365-enabled Teams apps are supported for production use in Microsoft Teams. You can distribute these apps to preview audiences who use the *Targeted Release* versions of outlook.com and off
Whoops, this needs updated from:

You can distribute these apps to preview audiences who use the *Targeted Release* versions of outlook.com and office.com, and the *Beta Channel* build of Outlook for Windows desktop, and Office Current Channel (Preview) build of Office app for Android.

To:

You can distribute these apps to preview audiences who use the *Targeted Release* versions of outlook.com and office.com, the *Beta Channel* build of Outlook for Windows desktop, and beta program builds of Office app for Android.

and

2022-09-22 03:06 UTC, erikadoyle reviewed
Added note to update the name of beta Office app for Android. After that, all looks good to me--will sign off.

2022-09-22 13:40 UTC, v-ksar requested changes
Please make the changes as suggested.

2022-09-22 13:40 UTC, v-ksar commented on msteams-platform/m365-apps/extend-m365-teams-personal-tab.md
> +After it's sideloaded to Teams, your personal tab is available in Outlook and Office. Be sure to sign in with the same credentials you used to sideload your app in Teams. When running the Office app
Please change to: 
After it's sideloaded to Teams, your personal tab is available in Outlook and Office. You must sign in with the same credentials that you used to sideload your app in Teams. When running the Office app for Android, you need to restart to use your personal tab app from the Office app.

2022-09-22 13:40 UTC, v-ksar commented on msteams-platform/m365-apps/extend-m365-teams-personal-tab.md
> +> Before installing this app, verify you have followed [the steps To install the latest Office app beta build](prerequisites.md#mobile) and are part of the beta program.
Please change to:
Before installing this app, perform [the steps to install the latest Office app beta build](https://review.learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/prerequisites#mobile) and be a part of the beta program.

2022-09-22 13:40 UTC, v-ksar commented on msteams-platform/m365-apps/extend-m365-teams-personal-tab.md
> +Here's how to remotely debug your app running in Office app for Android.
Please change to:
To remotely debug your app running in Office app for Android.

2022-09-22 13:40 UTC, v-ksar commented on msteams-platform/m365-apps/extend-m365-teams-personal-tab.md
> +1. Exit Settings, then exit your profile screen, **Me**.
Please change to:
Exit settings > Exit your profile screen.

2022-09-22 13:40 UTC, v-ksar commented on msteams-platform/m365-apps/extend-m365-teams-personal-tab.md
> +1. Ensure your mobile phone is connected to your dev machine. From your dev machine, open your browser to its DevTools inspection page. For example, go to `edge://inspect/#devices` in Microsoft Edge
Please change to:
Ensure your Android device is connected to your dev machine.

2022-09-22 13:40 UTC, v-ksar commented on msteams-platform/m365-apps/extend-m365-teams-personal-tab.md
> +1. Debug your tab app within the Android WebView the same way you would [remotely debug](/microsoft-edge/devtools-guide-chromium/remote-debugging) a regular website on an Android device.
Please change to:
Debug your tab app within the Android WebView. In the same way you [remotely debug](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/remote-debugging) a regular website on an Android device.

2022-09-22 13:40 UTC, v-ksar commented on msteams-platform/m365-apps/prerequisites.md
> +1. Select the **Install** button.
Please change to:
Select **Install**.

2022-09-22 13:40 UTC, v-ksar commented on msteams-platform/m365-apps/prerequisites.md
> +1. Once installed, from the same screen under Join the beta select **Join**.
Please change to:
Once installed, select **Join** under **Join the beta section**.

2022-09-22 13:40 UTC, v-ksar commented on msteams-platform/m365-apps/publish.md
> +Microsoft 365-enabled Teams apps are supported for production use in Microsoft Teams. You can distribute these apps to preview audiences who use the *Targeted Release* versions of outlook.com and off
Please change to:
You can distribute these apps to audience who use the Targeted Release (dev preview) versions of Outlook.com and Office.com, the Beta Channel build of Outlook for Windows desktop, and Office Current Channel (dev preview) build of Office app for Android.

2022-09-22 16:58 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/m365-apps/extend-m365-teams-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/505580eef6b9678d0c7989daa85e1d7eb69f2459/msteams-platform%2Fm365-apps%2Fextend-m365-teams-personal-tab.md) | 95 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/44345a2a-037e-46cb-9b11-dddea712089c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/505580eef6b9678d0c7989daa85e1d7eb69f2459/msteams-platform%2Fm365-apps%2Foverview.md) | 91 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c13a1c43-d5b7-4910-97fd-bfe7f0c973ec) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/505580eef6b9678d0c7989daa85e1d7eb69f2459/msteams-platform%2Fm365-apps%2Fprerequisites.md) | 86 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2a7c5be3-0a8b-4f4a-b531-23f38c9bc814) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/505580eef6b9678d0c7989daa85e1d7eb69f2459/msteams-platform%2Fm365-apps%2Fpublish.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cc54a019-8032-4160-8547-07512e19ead2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/using-teams-client-sdk.md](https://github.com/MicrosoftDocs/msteams-docs/blob/505580eef6b9678d0c7989daa85e1d7eb69f2459/msteams-platform%2Ftabs%2Fhow-to%2Fusing-teams-client-sdk.md) | 92 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b03399be-46d3-40ca-a11e-8416afddfed5) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-09-22 16:59 UTC, opbld31 commented
Docs Build status updates of commit _[505580e](https://github.com/JoshuaPartlow/msteams-docs/commits/505580eef6b9678d0c7989daa85e1d7eb69f2459)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/m365-apps/extend-m365-teams-personal-tab.md](https://github.com/JoshuaPartlow/msteams-docs/blob/mobajemu-mobile-android-preview-3/msteams-platform/m365-apps/extend-m365-teams-personal-tab.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/extend-m365-teams-personal-tab?branch=pr-en-us-7009) |
[msteams-platform/m365-apps/images/office-android-debug.png](https://github.com/JoshuaPartlow/msteams-docs/blob/mobajemu-mobile-android-preview-3/msteams-platform/m365-apps/images/office-android-debug.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/extend-m365-teams-personal-tab?branch=pr-en-us-7009) |
[msteams-platform/m365-apps/images/office-android-enable-remote-debugging.png](https://github.com/JoshuaPartlow/msteams-docs/blob/mobajemu-mobile-android-preview-3/msteams-platform/m365-apps/images/office-android-enable-remote-debugging.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/extend-m365-teams-personal-tab?branch=pr-en-us-7009) |
[msteams-platform/m365-apps/images/office-android-install.png](https://github.com/JoshuaPartlow/msteams-docs/blob/mobajemu-mobile-android-preview-3/msteams-platform/m365-apps/images/office-android-install.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/prerequisites?branch=pr-en-us-7009) |
[msteams-platform/m365-apps/images/office-android-join-beta.png](https://github.com/JoshuaPartlow/msteams-docs/blob/mobajemu-mobile-android-preview-3/msteams-platform/m365-apps/images/office-android-join-beta.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/prerequisites?branch=pr-en-us-7009) |
[msteams-platform/m365-apps/images/office-mobile-apps.png](https://github.com/JoshuaPartlow/msteams-docs/blob/mobajemu-mobile-android-preview-3/msteams-platform/m365-apps/images/office-mobile-apps.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/extend-m365-teams-personal-tab?branch=pr-en-us-7009) |
[msteams-platform/m365-apps/images/office-mobile-personal-tab.png](https://github.com/JoshuaPartlow/msteams-docs/blob/mobajemu-mobile-android-preview-3/msteams-platform/m365-apps/images/office-mobile-personal-tab.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/overview?branch=pr-en-us-7009) |
[msteams-platform/m365-apps/overview.md](https://github.com/JoshuaPartlow/msteams-docs/blob/mobajemu-mobile-android-preview-3/msteams-platform/m365-apps/overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/overview?branch=pr-en-us-7009) |
[msteams-platform/m365-apps/prerequisites.md](https://github.com/JoshuaPartlow/msteams-docs/blob/mobajemu-mobile-android-preview-3/msteams-platform/m365-apps/prerequisites.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/prerequisites?branch=pr-en-us-7009) |
[msteams-platform/m365-apps/publish.md](https://github.com/JoshuaPartlow/msteams-docs/blob/mobajemu-mobile-android-preview-3/msteams-platform/m365-apps/publish.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/publish?branch=pr-en-us-7009) |
[msteams-platform/tabs/how-to/using-teams-client-sdk.md](https://github.com/JoshuaPartlow/msteams-docs/blob/mobajemu-mobile-android-preview-3/msteams-platform/tabs/how-to/using-teams-client-sdk.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/using-teams-client-sdk?branch=pr-en-us-7009) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202209221658451572-7009/BuildReport?accessString=c9240f0a4483170db14c470f4fbf41f53e6de4b43b238952c632c7085466ba66).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-22 17:00 UTC, mobajemu-msft reviewed
changes made

2022-09-23 04:39 UTC, v-ksar commented
Approved.

2022-09-23 04:57 UTC, v-ksar approved these changes
Approved.

2022-09-23 04:57 UTC, v-abirade approved these changes
Approved

2022-09-25 19:10 UTC, v-abirade requested changes
Please make changes.

2022-09-25 19:10 UTC, v-abirade commented on msteams-platform/m365-apps/prerequisites.md
> +2. Once installed, select **Join** under **Join the beta section**.
2. Select **Join** under **Join the beta section** after the installation completes.

2022-09-25 19:10 UTC, v-abirade commented on msteams-platform/m365-apps/prerequisites.md
> +3. Launch the Office app and sign in with your test tenant credentials
3. Launch the Office app and sign in with your test tenant credentials.

2022-09-25 19:10 UTC, v-abirade commented on msteams-platform/m365-apps/prerequisites.md
> +5. Verify you are running version 16.0.15629.20000 or higher of Office app for Android.
5. Ensure you use Office app version 16.0.15629.20000 or higher for Android.

2022-09-25 19:10 UTC, v-abirade commented on msteams-platform/m365-apps/publish.md
> +Microsoft 365-enabled Teams apps are supported for production use in Microsoft Teams. You can distribute these apps to audience who use the *Targeted Release* (dev preview) versions of Outlook.com an
Microsoft Teams supports Microsoft 365-enabled Teams apps for production.

2022-09-26 17:32 UTC, erikadoyle commented on msteams-platform/m365-apps/extend-m365-teams-personal-tab.md
> +    > Some Client IDs are shared across Microsoft 365 client applications.
I'm not sure there's a good way to use active voice here--the suggested rewrite changes the meaning. How about this as a clarification:
Some of the client IDs in the list are common to multiple Microsoft 365 client applications.

2022-09-26 18:24 UTC, erikadoyle commented on msteams-platform/m365-apps/extend-m365-teams-personal-tab.md
> +> Before installing this app, perform [the steps To install the latest Office app beta build](prerequisites.md#mobile) and be a part of the beta program.
Also, could we move this note to just below the section heading ("Office app for Android")? Since its a prereq, it should go before the steps

2022-09-26 18:28 UTC, erikadoyle commented on msteams-platform/m365-apps/extend-m365-teams-personal-tab.md
> +1. Launch the Office app and sign in using your dev tenant account.
Could we append this sentence to the 1st step: If the Office app for Android was already running prior to sideloading your app in Teams, you'll need to restart it in order to see it among your installed apps.

2022-09-26 18:28 UTC, erikadoyle reviewed
Couple more suggestions before publish

2022-09-26 19:37 UTC, mobajemu-msft commented on msteams-platform/m365-apps/extend-m365-teams-personal-tab.md
> +1. Open your profile **Me > Settings > Allow debugging**, and toggle on the option for **Enable remote debugging**.
I think it's important to specify that it is a physical android that the debugging is happening on because debugging can also be done on a VM

2022-09-26 20:35 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/m365-apps/extend-m365-teams-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5580a99172387782f918c13ba41e7bfa10fdc89f/msteams-platform%2Fm365-apps%2Fextend-m365-teams-personal-tab.md) | 94 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9cf08312-b4f9-4742-ab0f-47f07e7cd7c3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5580a99172387782f918c13ba41e7bfa10fdc89f/msteams-platform%2Fm365-apps%2Foverview.md) | 91 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/751cbd13-1255-47df-b51b-276e21972fac) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5580a99172387782f918c13ba41e7bfa10fdc89f/msteams-platform%2Fm365-apps%2Fprerequisites.md) | 87 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d8847d5b-fd9f-4be5-9365-c6d871c44885) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5580a99172387782f918c13ba41e7bfa10fdc89f/msteams-platform%2Fm365-apps%2Fpublish.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bd044645-cb2f-40e2-9c21-869d6bff644a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/using-teams-client-sdk.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5580a99172387782f918c13ba41e7bfa10fdc89f/msteams-platform%2Ftabs%2Fhow-to%2Fusing-teams-client-sdk.md) | 91 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ede6f579-b994-437b-9b5f-554eb2f3a31d) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-09-26 20:36 UTC, opbld31 commented
Docs Build status updates of commit _[5580a99](https://github.com/JoshuaPartlow/msteams-docs/commits/5580a99172387782f918c13ba41e7bfa10fdc89f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/m365-apps/extend-m365-teams-personal-tab.md](https://github.com/JoshuaPartlow/msteams-docs/blob/mobajemu-mobile-android-preview-3/msteams-platform/m365-apps/extend-m365-teams-personal-tab.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/extend-m365-teams-personal-tab?branch=pr-en-us-7009) |
[msteams-platform/m365-apps/images/office-android-debug.png](https://github.com/JoshuaPartlow/msteams-docs/blob/mobajemu-mobile-android-preview-3/msteams-platform/m365-apps/images/office-android-debug.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/extend-m365-teams-personal-tab?branch=pr-en-us-7009) |
[msteams-platform/m365-apps/images/office-android-enable-remote-debugging.png](https://github.com/JoshuaPartlow/msteams-docs/blob/mobajemu-mobile-android-preview-3/msteams-platform/m365-apps/images/office-android-enable-remote-debugging.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/extend-m365-teams-personal-tab?branch=pr-en-us-7009) |
[msteams-platform/m365-apps/images/office-android-install.png](https://github.com/JoshuaPartlow/msteams-docs/blob/mobajemu-mobile-android-preview-3/msteams-platform/m365-apps/images/office-android-install.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/prerequisites?branch=pr-en-us-7009) |
[msteams-platform/m365-apps/images/office-android-join-beta.png](https://github.com/JoshuaPartlow/msteams-docs/blob/mobajemu-mobile-android-preview-3/msteams-platform/m365-apps/images/office-android-join-beta.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/prerequisites?branch=pr-en-us-7009) |
[msteams-platform/m365-apps/images/office-mobile-apps.png](https://github.com/JoshuaPartlow/msteams-docs/blob/mobajemu-mobile-android-preview-3/msteams-platform/m365-apps/images/office-mobile-apps.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/extend-m365-teams-personal-tab?branch=pr-en-us-7009) |
[msteams-platform/m365-apps/images/office-mobile-personal-tab.png](https://github.com/JoshuaPartlow/msteams-docs/blob/mobajemu-mobile-android-preview-3/msteams-platform/m365-apps/images/office-mobile-personal-tab.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/overview?branch=pr-en-us-7009) |
[msteams-platform/m365-apps/overview.md](https://github.com/JoshuaPartlow/msteams-docs/blob/mobajemu-mobile-android-preview-3/msteams-platform/m365-apps/overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/overview?branch=pr-en-us-7009) |
[msteams-platform/m365-apps/prerequisites.md](https://github.com/JoshuaPartlow/msteams-docs/blob/mobajemu-mobile-android-preview-3/msteams-platform/m365-apps/prerequisites.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/prerequisites?branch=pr-en-us-7009) |
[msteams-platform/m365-apps/publish.md](https://github.com/JoshuaPartlow/msteams-docs/blob/mobajemu-mobile-android-preview-3/msteams-platform/m365-apps/publish.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/publish?branch=pr-en-us-7009) |
[msteams-platform/tabs/how-to/using-teams-client-sdk.md](https://github.com/JoshuaPartlow/msteams-docs/blob/mobajemu-mobile-android-preview-3/msteams-platform/tabs/how-to/using-teams-client-sdk.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/using-teams-client-sdk?branch=pr-en-us-7009) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202209262035378486-7009/BuildReport?accessString=bb8e5d46087f3237d7e226089c57f450e148f30bb360b8a2698d45ec11c4c888).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-27 17:12 UTC, erikadoyle commented on msteams-platform/m365-apps/extend-m365-teams-personal-tab.md
> +    > Microsoft 365 client applications might share Client IDs.
Instead of "might" which sounds indefinite, could we say more affirmatively:

Some Microsoft 365 client applications share Client IDs.

2022-09-27 17:15 UTC, erikadoyle commented on msteams-platform/m365-apps/prerequisites.md
> +2. Ensure you use Office app version 16.0.15629.20000 or higher for Android.
Update min app version to:
16.0.15726.20000

2022-09-27 17:21 UTC, erikadoyle commented on msteams-platform/m365-apps/extend-m365-teams-personal-tab.md
> +To remotely debug your app running in Office app for Android.
Whoops, this isn't a complete sentence. It's also a good place to incorporate the suggestion to mention Toolkit debugging isn't yet supported on mobile. How about this:

Teams Toolkit (`F5`) debugging is not yet supported with Office app for Android. Here's how to remotely debug your app running in Office app for Anrdroid:

2022-09-27 17:23 UTC, erikadoyle reviewed
Few more changes--almost there!

2022-09-27 17:40 UTC, erikadoyle reviewed
In extend-m365-teams-personal-tab.md, 1st paragraph, could we update this sentence:

This tutorial demonstrates the process of taking an existing Teams personal tab and updating it to run in both Outlook desktop and web experiences, and also Office on the web (office.com).

To:

This tutorial demonstrates the process of taking an existing Teams personal tab and updating it to run in both Outlook and Office desktop and web experiences, as well as Office app for Android.

2022-09-27 19:28 UTC, opbld33 commented
Docs Build status updates of commit _[ae61413](https://github.com/JoshuaPartlow/msteams-docs/commits/ae6141333b8a58a2284e440b418ba46f3406f1b7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/m365-apps/extend-m365-teams-personal-tab.md](https://github.com/JoshuaPartlow/msteams-docs/blob/mobajemu-mobile-android-preview-3/msteams-platform/m365-apps/extend-m365-teams-personal-tab.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/extend-m365-teams-personal-tab?branch=pr-en-us-7009) |
[msteams-platform/m365-apps/images/office-android-debug.png](https://github.com/JoshuaPartlow/msteams-docs/blob/mobajemu-mobile-android-preview-3/msteams-platform/m365-apps/images/office-android-debug.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/extend-m365-teams-personal-tab?branch=pr-en-us-7009) |
[msteams-platform/m365-apps/images/office-android-enable-remote-debugging.png](https://github.com/JoshuaPartlow/msteams-docs/blob/mobajemu-mobile-android-preview-3/msteams-platform/m365-apps/images/office-android-enable-remote-debugging.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/extend-m365-teams-personal-tab?branch=pr-en-us-7009) |
[msteams-platform/m365-apps/images/office-android-install.png](https://github.com/JoshuaPartlow/msteams-docs/blob/mobajemu-mobile-android-preview-3/msteams-platform/m365-apps/images/office-android-install.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/prerequisites?branch=pr-en-us-7009) |
[msteams-platform/m365-apps/images/office-android-join-beta.png](https://github.com/JoshuaPartlow/msteams-docs/blob/mobajemu-mobile-android-preview-3/msteams-platform/m365-apps/images/office-android-join-beta.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/prerequisites?branch=pr-en-us-7009) |
[msteams-platform/m365-apps/images/office-mobile-apps.png](https://github.com/JoshuaPartlow/msteams-docs/blob/mobajemu-mobile-android-preview-3/msteams-platform/m365-apps/images/office-mobile-apps.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/extend-m365-teams-personal-tab?branch=pr-en-us-7009) |
[msteams-platform/m365-apps/images/office-mobile-personal-tab.png](https://github.com/JoshuaPartlow/msteams-docs/blob/mobajemu-mobile-android-preview-3/msteams-platform/m365-apps/images/office-mobile-personal-tab.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/overview?branch=pr-en-us-7009) |
[msteams-platform/m365-apps/overview.md](https://github.com/JoshuaPartlow/msteams-docs/blob/mobajemu-mobile-android-preview-3/msteams-platform/m365-apps/overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/overview?branch=pr-en-us-7009) |
[msteams-platform/m365-apps/prerequisites.md](https://github.com/JoshuaPartlow/msteams-docs/blob/mobajemu-mobile-android-preview-3/msteams-platform/m365-apps/prerequisites.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/prerequisites?branch=pr-en-us-7009) |
[msteams-platform/m365-apps/publish.md](https://github.com/JoshuaPartlow/msteams-docs/blob/mobajemu-mobile-android-preview-3/msteams-platform/m365-apps/publish.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/publish?branch=pr-en-us-7009) |
[msteams-platform/tabs/how-to/using-teams-client-sdk.md](https://github.com/JoshuaPartlow/msteams-docs/blob/mobajemu-mobile-android-preview-3/msteams-platform/tabs/how-to/using-teams-client-sdk.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/using-teams-client-sdk?branch=pr-en-us-7009) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202209271926477561-7009/BuildReport?accessString=3f35b46e1e9398f620d9211879996c4f87a2ce59c568e377cb87ab6b683cab66).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-27 19:33 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/m365-apps/extend-m365-teams-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ae6141333b8a58a2284e440b418ba46f3406f1b7/msteams-platform%2Fm365-apps%2Fextend-m365-teams-personal-tab.md) | 94 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6cd614f6-f25a-40de-8f16-d0fdcb741701) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ae6141333b8a58a2284e440b418ba46f3406f1b7/msteams-platform%2Fm365-apps%2Foverview.md) | 91 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bcc7bdd2-60d5-45a1-b709-08f7d943800b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ae6141333b8a58a2284e440b418ba46f3406f1b7/msteams-platform%2Fm365-apps%2Fprerequisites.md) | 87 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7c9a470f-96d8-48ca-9a2b-e5cb3d1874f1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ae6141333b8a58a2284e440b418ba46f3406f1b7/msteams-platform%2Fm365-apps%2Fpublish.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f6533c61-ec07-4a16-b955-690da5078169) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/using-teams-client-sdk.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ae6141333b8a58a2284e440b418ba46f3406f1b7/msteams-platform%2Ftabs%2Fhow-to%2Fusing-teams-client-sdk.md) | 91 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d3e0c968-c2b7-41ed-a870-1194f1ef48be) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-09-27 22:46 UTC, erikadoyle approved these changes
Looks great! @surbhigupta12 this is now ready for publish.

2022-09-28 14:06 UTC, v-abirade approved these changes
Approved.

2022-09-28 14:07 UTC, merged