[Doc Improvement][TTK Visual Studio Code debug and SBS]
MicrosoftDocs/msteams-docs pull request #7026
Opened 2022-09-23 05:58 UTC by v-amprasad

2022-09-23 05:58 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/debug-background-process.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0a2aeec883fba76da008afe3e93bcc5dfe0cbf3e/msteams-platform%2Ftoolkit%2Fdebug-background-process.md) | 98 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ce20174e-0b22-4dc8-9f61-39df9e8fb1ea) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-09-23 06:00 UTC, opbld32 commented
Docs Build status updates of commit _[0a2aeec](https://github.com/MicrosoftDocs/msteams-docs/commits/0a2aeec883fba76da008afe3e93bcc5dfe0cbf3e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/toolkit/debug-background-process.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/toolkit/debug-background-process.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-background-process?branch=pr-en-us-7026) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202209230558548773-7026/BuildReport?accessString=9d955be81fdafbb8995f295660125feaa82a99da27055c61ba886f0937c2fea8).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-23 06:19 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/debug-background-process.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7b0a3610fe9e2f70f9127ebba15874aed676719b/msteams-platform%2Ftoolkit%2Fdebug-background-process.md) | 98 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/371c4c86-6962-420f-973a-546dd5289387) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-09-23 06:20 UTC, opbld33 commented
Docs Build status updates of commit _[7b0a361](https://github.com/MicrosoftDocs/msteams-docs/commits/7b0a3610fe9e2f70f9127ebba15874aed676719b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/teams-toolkit-v2/debug/prerequisites-debugcheck1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/prerequisites-debugcheck1.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-background-process?branch=pr-en-us-7026) |
[msteams-platform/toolkit/debug-background-process.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/toolkit/debug-background-process.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-background-process?branch=pr-en-us-7026) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202209230619386408-7026/BuildReport?accessString=7c5d5cbc72a0ef4c7f24d7501ce0a7b16bbc1d0ab8f19d5627860a1140ec13d3).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-23 06:36 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/debug-background-process.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1880e4da352ec9138036383dabf24dd2c9da0bb9/msteams-platform%2Ftoolkit%2Fdebug-background-process.md) | 98 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4d6b8b56-6f86-4662-895e-e10afe605928) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1880e4da352ec9138036383dabf24dd2c9da0bb9/msteams-platform%2Ftoolkit%2Fdebug-local.md) | 94 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2027184b-7fbb-426b-8ee1-72e060421457) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1880e4da352ec9138036383dabf24dd2c9da0bb9/msteams-platform%2Ftoolkit%2Fdebug-overview.md) | 93 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bb51e902-9104-4c4b-ac17-254da0862e92) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-09-23 06:38 UTC, opbld33 commented
Docs Build status updates of commit _[1880e4d](https://github.com/MicrosoftDocs/msteams-docs/commits/1880e4da352ec9138036383dabf24dd2c9da0bb9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/teams-toolkit-v2/debug/prerequisites-debugcheck1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/prerequisites-debugcheck1.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-background-process?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/Terminal1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/Terminal1.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-local?branch=pr-en-us-7026) |
[msteams-platform/toolkit/debug-background-process.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/toolkit/debug-background-process.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-background-process?branch=pr-en-us-7026) |
[msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/toolkit/debug-local.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-local?branch=pr-en-us-7026) |
[msteams-platform/toolkit/debug-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/toolkit/debug-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202209230636503726-7026/BuildReport?accessString=b87a084d27e0a3475d41be34ef406967d3afc6f9f0d7af4f91a316f1f4fdd697).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-23 07:51 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/debug-background-process.md](https://github.com/MicrosoftDocs/msteams-docs/blob/73b72e7ec8cc87c7e7ef93767c37aa00df2f54be/msteams-platform%2Ftoolkit%2Fdebug-background-process.md) | 98 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c49b0d7d-1d60-4664-a77c-38fb5e9f7910) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/73b72e7ec8cc87c7e7ef93767c37aa00df2f54be/msteams-platform%2Ftoolkit%2Fdebug-local.md) | 94 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/49a5bd23-caef-44ec-aa62-c47e56424948) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/73b72e7ec8cc87c7e7ef93767c37aa00df2f54be/msteams-platform%2Ftoolkit%2Fdebug-overview.md) | 94 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/95a6c1f4-b310-4279-b379-5b4ade4b309c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-09-23 07:52 UTC, opbld33 commented
Docs Build status updates of commit _[73b72e7](https://github.com/MicrosoftDocs/msteams-docs/commits/73b72e7ec8cc87c7e7ef93767c37aa00df2f54be)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/teams-toolkit-v2/debug/app-package-path.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/app-package-path.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/customize-npm-install.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/customize-npm-install.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/modify-ports-bot.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/modify-ports-bot.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/modify-ports-tab.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/modify-ports-tab.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/prerequisites-debugcheck1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/prerequisites-debugcheck1.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-background-process?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/set-up-bot.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/set-up-bot.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/skip-prerequisite-checks.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/skip-prerequisite-checks.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/start-local-tunnel.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/start-local-tunnel.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/Terminal1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/Terminal1.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-local?branch=pr-en-us-7026) |
[msteams-platform/toolkit/debug-background-process.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/toolkit/debug-background-process.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-background-process?branch=pr-en-us-7026) |
[msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/toolkit/debug-local.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-local?branch=pr-en-us-7026) |
[msteams-platform/toolkit/debug-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/toolkit/debug-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202209230751267112-7026/BuildReport?accessString=4e8c609ecc81e13e8799fc17d7859b5d46ff60a14a861f0345f7aef7f43c9ddc).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-23 08:11 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/debug-background-process.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0da924b7b46f29560d586ad0e4616e39587ffcea/msteams-platform%2Ftoolkit%2Fdebug-background-process.md) | 98 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/535c571c-0faa-4762-81cd-0720fdb48bda) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0da924b7b46f29560d586ad0e4616e39587ffcea/msteams-platform%2Ftoolkit%2Fdebug-local.md) | 94 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5dd84d2c-31e8-4aa8-822a-f6278889e3e7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0da924b7b46f29560d586ad0e4616e39587ffcea/msteams-platform%2Ftoolkit%2Fdebug-overview.md) | 94 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/713bd3c6-eea3-492b-88ca-b17514ebde11) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-09-23 08:12 UTC, opbld33 commented
Docs Build status updates of commit _[0da924b](https://github.com/MicrosoftDocs/msteams-docs/commits/0da924b7b46f29560d586ad0e4616e39587ffcea)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/teams-toolkit-v2/debug/app-package-path.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/app-package-path.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/customize-npm-install.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/customize-npm-install.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/modify-ports-bot.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/modify-ports-bot.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/modify-ports-tab.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/modify-ports-tab.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/prerequisites-debugcheck1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/prerequisites-debugcheck1.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-background-process?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/set-up-bot.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/set-up-bot.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/skip-prerequisite-checks.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/skip-prerequisite-checks.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/start-local-tunnel.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/start-local-tunnel.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/Terminal1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/Terminal1.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-local?branch=pr-en-us-7026) |
[msteams-platform/toolkit/debug-background-process.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/toolkit/debug-background-process.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-background-process?branch=pr-en-us-7026) |
[msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/toolkit/debug-local.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-local?branch=pr-en-us-7026) |
[msteams-platform/toolkit/debug-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/toolkit/debug-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202209230811001936-7026/BuildReport?accessString=0dbe5312e4b713d34aed1a4f7e1fd9185fea4361566d1a1fbfd5070893777ee2).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-23 08:30 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/053db7ae09fdd47a686a9146ccdd9c84c8de9263/msteams-platform%2Fsbs-gs-bot.yml) | 91 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e8d8646a-efc3-43ab-9a0b-569d767aa893) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-background-process.md](https://github.com/MicrosoftDocs/msteams-docs/blob/053db7ae09fdd47a686a9146ccdd9c84c8de9263/msteams-platform%2Ftoolkit%2Fdebug-background-process.md) | 98 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6a598e80-67f0-4126-9945-080932411fd5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/053db7ae09fdd47a686a9146ccdd9c84c8de9263/msteams-platform%2Ftoolkit%2Fdebug-local.md) | 94 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/88625a80-19b0-4945-b0d7-473a2a7b7679) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/053db7ae09fdd47a686a9146ccdd9c84c8de9263/msteams-platform%2Ftoolkit%2Fdebug-overview.md) | 94 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6a5974b2-c6f8-497e-9677-9544ea7a877e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-09-23 08:31 UTC, opbld32 commented
Docs Build status updates of commit _[053db7a](https://github.com/MicrosoftDocs/msteams-docs/commits/053db7ae09fdd47a686a9146ccdd9c84c8de9263)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/teams-toolkit-v2/debug/app-package-path.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/app-package-path.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/customize-npm-install.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/customize-npm-install.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/modify-ports-bot.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/modify-ports-bot.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/modify-ports-tab.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/modify-ports-tab.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/prerequisites-debugcheck1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/prerequisites-debugcheck1.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-background-process?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/set-up-bot.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/set-up-bot.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/skip-prerequisite-checks.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/skip-prerequisite-checks.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/start-local-tunnel.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/start-local-tunnel.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/Terminal1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/Terminal1.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-local?branch=pr-en-us-7026) |
[msteams-platform/sbs-gs-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/sbs-gs-bot.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/sbs-gs-bot?branch=pr-en-us-7026) |
[msteams-platform/toolkit/debug-background-process.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/toolkit/debug-background-process.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-background-process?branch=pr-en-us-7026) |
[msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/toolkit/debug-local.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-local?branch=pr-en-us-7026) |
[msteams-platform/toolkit/debug-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/toolkit/debug-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202209230829510160-7026/BuildReport?accessString=1497daf7430b6b18ecd0802ed8c07c8b1f092a70933cb11324d7353c56737bb0).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-23 08:56 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/de4d68bda59982924c3e4f4974b46f5992c3bec2/msteams-platform%2Fsbs-gs-bot.yml) | 91 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6db494b8-2359-45c0-b3f7-c0343a04d6f7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-javascript.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/de4d68bda59982924c3e4f4974b46f5992c3bec2/msteams-platform%2Fsbs-gs-javascript.yml) | 91 | 41 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6e336961-a88d-48ee-b069-d1121e800ec2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-msgext.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/de4d68bda59982924c3e4f4974b46f5992c3bec2/msteams-platform%2Fsbs-gs-msgext.yml) | 90 | 46 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7974bed0-4e4e-4f45-b725-d5c37c09e2f6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-background-process.md](https://github.com/MicrosoftDocs/msteams-docs/blob/de4d68bda59982924c3e4f4974b46f5992c3bec2/msteams-platform%2Ftoolkit%2Fdebug-background-process.md) | 98 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/64bdc67e-7bd6-4bbd-9d8f-6d388e5910dc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/de4d68bda59982924c3e4f4974b46f5992c3bec2/msteams-platform%2Ftoolkit%2Fdebug-local.md) | 94 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e121d9b0-f98a-4e32-8347-338a997c097c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/de4d68bda59982924c3e4f4974b46f5992c3bec2/msteams-platform%2Ftoolkit%2Fdebug-overview.md) | 94 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d5f6a5f4-565b-44ff-963a-15a33555097e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-09-23 08:57 UTC, opbld30 commented
Docs Build status updates of commit _[de4d68b](https://github.com/MicrosoftDocs/msteams-docs/commits/de4d68bda59982924c3e4f4974b46f5992c3bec2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/teams-toolkit-v2/debug/app-package-path.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/app-package-path.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/customize-npm-install.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/customize-npm-install.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/modify-ports-bot.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/modify-ports-bot.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/modify-ports-tab.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/modify-ports-tab.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/prerequisites-debugcheck1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/prerequisites-debugcheck1.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-background-process?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/set-up-bot.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/set-up-bot.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/skip-prerequisite-checks.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/skip-prerequisite-checks.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/start-local-tunnel.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/start-local-tunnel.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/Terminal1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/Terminal1.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-local?branch=pr-en-us-7026) |
[msteams-platform/sbs-gs-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/sbs-gs-bot.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/sbs-gs-bot?branch=pr-en-us-7026) |
[msteams-platform/sbs-gs-javascript.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/sbs-gs-javascript.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/sbs-gs-javascript?branch=pr-en-us-7026) |
[msteams-platform/sbs-gs-msgext.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/sbs-gs-msgext.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/sbs-gs-msgext?branch=pr-en-us-7026) |
[msteams-platform/toolkit/debug-background-process.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/toolkit/debug-background-process.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-background-process?branch=pr-en-us-7026) |
[msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/toolkit/debug-local.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-local?branch=pr-en-us-7026) |
[msteams-platform/toolkit/debug-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/toolkit/debug-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202209230856073850-7026/BuildReport?accessString=288093e2b5d7ebe47fe3f5a11c20c9a22710fc236d8878016db1f321965674c5).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-23 10:32 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/12279b5bfc1b6c6094fa4f30ac967766999aaf24/msteams-platform%2Fsbs-gs-bot.yml) | 91 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e91e295d-324d-457d-829b-8bdcd4e92019) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-javascript.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/12279b5bfc1b6c6094fa4f30ac967766999aaf24/msteams-platform%2Fsbs-gs-javascript.yml) | 91 | 41 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c8f4ac0d-f7dd-4c7d-8bf3-3495cd12e42e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-msgext.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/12279b5bfc1b6c6094fa4f30ac967766999aaf24/msteams-platform%2Fsbs-gs-msgext.yml) | 90 | 46 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0464640c-14ca-4d22-97d9-07e37bd3cb12) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-background-process.md](https://github.com/MicrosoftDocs/msteams-docs/blob/12279b5bfc1b6c6094fa4f30ac967766999aaf24/msteams-platform%2Ftoolkit%2Fdebug-background-process.md) | 98 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bb068eb0-c56f-4fba-819c-7fd0fd6ccc91) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/12279b5bfc1b6c6094fa4f30ac967766999aaf24/msteams-platform%2Ftoolkit%2Fdebug-local.md) | 94 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b532c1f1-bb63-477c-8a02-e6240544f060) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/12279b5bfc1b6c6094fa4f30ac967766999aaf24/msteams-platform%2Ftoolkit%2Fdebug-overview.md) | 94 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1fd0ffd8-46bc-46bd-9fa6-a28d34f86835) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-09-23 10:33 UTC, opbld32 commented
Docs Build status updates of commit _[12279b5](https://github.com/MicrosoftDocs/msteams-docs/commits/12279b5bfc1b6c6094fa4f30ac967766999aaf24)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/teams-toolkit-v2/debug/app-package-path.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/app-package-path.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/customize-npm-install.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/customize-npm-install.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/modify-ports-bot.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/modify-ports-bot.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/modify-ports-tab.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/modify-ports-tab.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/prerequisites-debugcheck1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/prerequisites-debugcheck1.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-background-process?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/set-up-bot.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/set-up-bot.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/skip-prerequisite-checks.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/skip-prerequisite-checks.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/start-local-tunnel.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/start-local-tunnel.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/Terminal1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/Terminal1.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-local?branch=pr-en-us-7026) |
[msteams-platform/sbs-gs-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/sbs-gs-bot.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/sbs-gs-bot?branch=pr-en-us-7026) |
[msteams-platform/sbs-gs-javascript.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/sbs-gs-javascript.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/sbs-gs-javascript?branch=pr-en-us-7026) |
[msteams-platform/sbs-gs-msgext.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/sbs-gs-msgext.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/sbs-gs-msgext?branch=pr-en-us-7026) |
[msteams-platform/toolkit/debug-background-process.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/toolkit/debug-background-process.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-background-process?branch=pr-en-us-7026) |
[msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/toolkit/debug-local.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-local?branch=pr-en-us-7026) |
[msteams-platform/toolkit/debug-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/toolkit/debug-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202209231032376119-7026/BuildReport?accessString=0e56e2ac2c1e20a20fcdf40fa08df2422375cb1e472e1f08873f792c357f6468).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-27 15:01 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/bb746521125032c8b78fe42b683b4b5095966d6c/msteams-platform%2Fsbs-gs-bot.yml) | 91 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d7fca49b-9f26-40a3-87b5-57afab9f4831) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-javascript.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/bb746521125032c8b78fe42b683b4b5095966d6c/msteams-platform%2Fsbs-gs-javascript.yml) | 91 | 41 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/39aa069d-797a-4087-bc82-a99f530e2c47) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-msgext.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/bb746521125032c8b78fe42b683b4b5095966d6c/msteams-platform%2Fsbs-gs-msgext.yml) | 90 | 46 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/72a6b1ae-f56f-42fd-8f52-3d5893460102) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-background-process.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bb746521125032c8b78fe42b683b4b5095966d6c/msteams-platform%2Ftoolkit%2Fdebug-background-process.md) | 98 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b1087f1e-b5d1-4520-af2d-973298c43cd2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bb746521125032c8b78fe42b683b4b5095966d6c/msteams-platform%2Ftoolkit%2Fdebug-local.md) | 94 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/83de3f90-1b5f-4c64-a697-dd7e6ac3a1cf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bb746521125032c8b78fe42b683b4b5095966d6c/msteams-platform%2Ftoolkit%2Fdebug-overview.md) | 94 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c69d5118-1941-4b70-9b23-3e785e478493) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-09-28 03:36 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c01256b7f30217b84e8e3a7995aa7add450420c9/msteams-platform%2Fsbs-gs-bot.yml) | 91 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d7bea704-299a-4b16-a757-9126031efeed) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-javascript.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c01256b7f30217b84e8e3a7995aa7add450420c9/msteams-platform%2Fsbs-gs-javascript.yml) | 91 | 41 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/44714689-eecf-46ba-81f9-d558a5b4093d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-msgext.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c01256b7f30217b84e8e3a7995aa7add450420c9/msteams-platform%2Fsbs-gs-msgext.yml) | 90 | 46 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a923801f-8e0a-40be-90ad-10036031dfb1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-background-process.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c01256b7f30217b84e8e3a7995aa7add450420c9/msteams-platform%2Ftoolkit%2Fdebug-background-process.md) | 98 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0c85bfce-57e0-4895-9724-e48ae8d27cc9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c01256b7f30217b84e8e3a7995aa7add450420c9/msteams-platform%2Ftoolkit%2Fdebug-local.md) | 94 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b8db583b-b073-476f-8fbe-c466b62c5596) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c01256b7f30217b84e8e3a7995aa7add450420c9/msteams-platform%2Ftoolkit%2Fdebug-overview.md) | 94 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/15c05a95-c505-4e91-be8f-e05a6542e755) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-09-28 03:38 UTC, opbld30 commented
Docs Build status updates of commit _[c01256b](https://github.com/MicrosoftDocs/msteams-docs/commits/c01256b7f30217b84e8e3a7995aa7add450420c9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/teams-toolkit-v2/debug/app-package-path.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/app-package-path.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/customize-npm-install.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/customize-npm-install.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/modify-ports-bot.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/modify-ports-bot.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/modify-ports-tab.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/modify-ports-tab.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/prerequisites-debugcheck1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/prerequisites-debugcheck1.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-background-process?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/set-up-bot.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/set-up-bot.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/skip-prerequisite-checks.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/skip-prerequisite-checks.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/start-local-tunnel.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/start-local-tunnel.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/Terminal1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/Terminal1.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-local?branch=pr-en-us-7026) |
[msteams-platform/sbs-gs-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/sbs-gs-bot.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/sbs-gs-bot?branch=pr-en-us-7026) |
[msteams-platform/sbs-gs-javascript.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/sbs-gs-javascript.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/sbs-gs-javascript?branch=pr-en-us-7026) |
[msteams-platform/sbs-gs-msgext.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/sbs-gs-msgext.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/sbs-gs-msgext?branch=pr-en-us-7026) |
[msteams-platform/toolkit/debug-background-process.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/toolkit/debug-background-process.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-background-process?branch=pr-en-us-7026) |
[msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/toolkit/debug-local.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-local?branch=pr-en-us-7026) |
[msteams-platform/toolkit/debug-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/toolkit/debug-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202209280336451081-7026/BuildReport?accessString=d5be43dafc02900d2fa6272efa32224e2c019c5f3b7cc75ef8d63636b64e0b56).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-10-03 06:16 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c4055807ee4650391ece02fdc762775ea33b00b0/msteams-platform%2Fsbs-gs-bot.yml) | 91 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2b6b76cc-f29b-4a72-91cb-90c75ef66aa5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-javascript.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c4055807ee4650391ece02fdc762775ea33b00b0/msteams-platform%2Fsbs-gs-javascript.yml) | 91 | 41 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/da46b294-5ec3-4564-9786-c1f9a547c97e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-msgext.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c4055807ee4650391ece02fdc762775ea33b00b0/msteams-platform%2Fsbs-gs-msgext.yml) | 90 | 46 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/51f3aca8-6648-4231-850e-5858289920dc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-background-process.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c4055807ee4650391ece02fdc762775ea33b00b0/msteams-platform%2Ftoolkit%2Fdebug-background-process.md) | 98 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/da9febaf-8cf1-4bf7-94b5-5d737b6c1204) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c4055807ee4650391ece02fdc762775ea33b00b0/msteams-platform%2Ftoolkit%2Fdebug-local.md) | 94 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/13ccba53-fcec-4c5f-a40c-44167ddebc77) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c4055807ee4650391ece02fdc762775ea33b00b0/msteams-platform%2Ftoolkit%2Fdebug-overview.md) | 94 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bb598907-8603-4d5d-a2cb-e0024651c7bd) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-10-03 06:17 UTC, opbld32 commented
Learn Build status updates of commit _[c405580](https://github.com/MicrosoftDocs/msteams-docs/commits/c4055807ee4650391ece02fdc762775ea33b00b0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/teams-toolkit-v2/debug/app-package-path.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/app-package-path.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/customize-npm-install.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/customize-npm-install.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/modify-ports-bot.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/modify-ports-bot.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/modify-ports-tab.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/modify-ports-tab.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/prerequisites-debugcheck1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/prerequisites-debugcheck1.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-background-process?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/set-up-bot.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/set-up-bot.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/skip-prerequisite-checks.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/skip-prerequisite-checks.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/start-local-tunnel.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/start-local-tunnel.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/Terminal1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/Terminal1.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-local?branch=pr-en-us-7026) |
[msteams-platform/sbs-gs-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/sbs-gs-bot.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/sbs-gs-bot?branch=pr-en-us-7026) |
[msteams-platform/sbs-gs-javascript.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/sbs-gs-javascript.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/sbs-gs-javascript?branch=pr-en-us-7026) |
[msteams-platform/sbs-gs-msgext.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/sbs-gs-msgext.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/sbs-gs-msgext?branch=pr-en-us-7026) |
[msteams-platform/toolkit/debug-background-process.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/toolkit/debug-background-process.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-background-process?branch=pr-en-us-7026) |
[msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/toolkit/debug-local.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-local?branch=pr-en-us-7026) |
[msteams-platform/toolkit/debug-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/toolkit/debug-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202210030616059187-7026/BuildReport?accessString=d61af3af4ff206062020b4d78bb415a4e0354a184321abdb4a440b8e72741d53).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-03 06:31 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/df2c4d176aba7b99775fd6aee8caf720e719dec4/msteams-platform%2Fsbs-gs-bot.yml) | 91 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4eaf7cfe-70b1-498f-bdfb-f41bd5e543fc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-javascript.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/df2c4d176aba7b99775fd6aee8caf720e719dec4/msteams-platform%2Fsbs-gs-javascript.yml) | 91 | 41 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fc4cf0dc-0dd5-455a-b2c8-4e502f6bf908) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-msgext.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/df2c4d176aba7b99775fd6aee8caf720e719dec4/msteams-platform%2Fsbs-gs-msgext.yml) | 90 | 46 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/05eb09ed-a5de-4f24-8aef-013b3f8e3486) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-background-process.md](https://github.com/MicrosoftDocs/msteams-docs/blob/df2c4d176aba7b99775fd6aee8caf720e719dec4/msteams-platform%2Ftoolkit%2Fdebug-background-process.md) | 98 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/be89cc23-3ea6-430d-95c3-99660a6f2a31) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/df2c4d176aba7b99775fd6aee8caf720e719dec4/msteams-platform%2Ftoolkit%2Fdebug-local.md) | 94 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8c6bcc0e-7a7a-40e2-bb31-c88d1d59fb46) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/df2c4d176aba7b99775fd6aee8caf720e719dec4/msteams-platform%2Ftoolkit%2Fdebug-overview.md) | 94 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/321d3e8b-b289-4d00-ab82-173ba2a1e68c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-10-03 06:32 UTC, opbld31 commented
Learn Build status updates of commit _[df2c4d1](https://github.com/MicrosoftDocs/msteams-docs/commits/df2c4d176aba7b99775fd6aee8caf720e719dec4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/teams-toolkit-v2/debug/app-package-path.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/app-package-path.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/customize-npm-install.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/customize-npm-install.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/modify-ports-bot.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/modify-ports-bot.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/modify-ports-tab.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/modify-ports-tab.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/prerequisites-debugcheck1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/prerequisites-debugcheck1.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-background-process?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/set-up-bot.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/set-up-bot.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/skip-prerequisite-checks.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/skip-prerequisite-checks.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/start-local-tunnel.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/start-local-tunnel.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/Terminal1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/Terminal1.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-local?branch=pr-en-us-7026) |
[msteams-platform/sbs-gs-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/sbs-gs-bot.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/sbs-gs-bot?branch=pr-en-us-7026) |
[msteams-platform/sbs-gs-javascript.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/sbs-gs-javascript.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/sbs-gs-javascript?branch=pr-en-us-7026) |
[msteams-platform/sbs-gs-msgext.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/sbs-gs-msgext.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/sbs-gs-msgext?branch=pr-en-us-7026) |
[msteams-platform/toolkit/debug-background-process.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/toolkit/debug-background-process.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-background-process?branch=pr-en-us-7026) |
[msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/toolkit/debug-local.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-local?branch=pr-en-us-7026) |
[msteams-platform/toolkit/debug-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/toolkit/debug-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202210030631258231-7026/BuildReport?accessString=4f62c66b629bad2eec66062367262faa8f03d3c9d8e28013d50a8549b46931cc).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-04 03:57 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/daa8c5112edb339b0e263ee44c45e6e687b72921/msteams-platform%2Fsbs-gs-bot.yml) | 91 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/32baedf7-fd53-4383-837f-86ddba01123f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-javascript.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/daa8c5112edb339b0e263ee44c45e6e687b72921/msteams-platform%2Fsbs-gs-javascript.yml) | 91 | 41 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/69645c8e-1ab1-41be-8fdb-a379613b5314) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-msgext.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/daa8c5112edb339b0e263ee44c45e6e687b72921/msteams-platform%2Fsbs-gs-msgext.yml) | 90 | 46 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/53ddd2bf-8b90-40d5-bd05-12f1d7600095) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-background-process.md](https://github.com/MicrosoftDocs/msteams-docs/blob/daa8c5112edb339b0e263ee44c45e6e687b72921/msteams-platform%2Ftoolkit%2Fdebug-background-process.md) | 98 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bc5e5ea6-df99-4949-a984-91a7b1d01d15) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/daa8c5112edb339b0e263ee44c45e6e687b72921/msteams-platform%2Ftoolkit%2Fdebug-local.md) | 94 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7bd43c79-0931-43d3-a87b-212e5fe11c25) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/daa8c5112edb339b0e263ee44c45e6e687b72921/msteams-platform%2Ftoolkit%2Fdebug-overview.md) | 94 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d9e7bc1b-97e4-45ef-8d5e-574bf6c6a7af) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-10-04 03:58 UTC, opbld33 commented
Learn Build status updates of commit _[daa8c51](https://github.com/MicrosoftDocs/msteams-docs/commits/daa8c5112edb339b0e263ee44c45e6e687b72921)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/teams-toolkit-v2/debug/app-package-path.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/app-package-path.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/customize-npm-install.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/customize-npm-install.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/modify-ports-bot.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/modify-ports-bot.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/modify-ports-tab.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/modify-ports-tab.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/prerequisites-debugcheck1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/prerequisites-debugcheck1.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-background-process?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/set-up-bot.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/set-up-bot.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/skip-prerequisite-checks.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/skip-prerequisite-checks.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/start-local-tunnel.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/start-local-tunnel.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/Terminal1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/Terminal1.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-local?branch=pr-en-us-7026) |
[msteams-platform/sbs-gs-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/sbs-gs-bot.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/sbs-gs-bot?branch=pr-en-us-7026) |
[msteams-platform/sbs-gs-javascript.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/sbs-gs-javascript.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/sbs-gs-javascript?branch=pr-en-us-7026) |
[msteams-platform/sbs-gs-msgext.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/sbs-gs-msgext.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/sbs-gs-msgext?branch=pr-en-us-7026) |
[msteams-platform/toolkit/debug-background-process.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/toolkit/debug-background-process.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-background-process?branch=pr-en-us-7026) |
[msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/toolkit/debug-local.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-local?branch=pr-en-us-7026) |
[msteams-platform/toolkit/debug-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/toolkit/debug-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202210040357385191-7026/BuildReport?accessString=229ecf47e4d39b9c27b645049c7f262d1fe554acb64d2a1871c9b160465b6ab8).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-12 10:03 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1867e369a64f9e2ef707cfe8fd5daf82c8ffc77d/msteams-platform%2Fsbs-gs-bot.yml) | 91 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/20b62e2f-ee96-4b1c-8784-ad910c2837fd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-javascript.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1867e369a64f9e2ef707cfe8fd5daf82c8ffc77d/msteams-platform%2Fsbs-gs-javascript.yml) | 91 | 40 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a670d731-22b9-4b58-aeb4-95511f120e56) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-msgext.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1867e369a64f9e2ef707cfe8fd5daf82c8ffc77d/msteams-platform%2Fsbs-gs-msgext.yml) | 90 | 46 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/075b3927-7347-4d9a-a103-e2039e64404a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-background-process.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1867e369a64f9e2ef707cfe8fd5daf82c8ffc77d/msteams-platform%2Ftoolkit%2Fdebug-background-process.md) | 98 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2475ffe1-0112-4942-ad08-f90d49228ee1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1867e369a64f9e2ef707cfe8fd5daf82c8ffc77d/msteams-platform%2Ftoolkit%2Fdebug-local.md) | 94 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/21678f90-7f34-413b-9c5d-8a4d5d042f9a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1867e369a64f9e2ef707cfe8fd5daf82c8ffc77d/msteams-platform%2Ftoolkit%2Fdebug-overview.md) | 95 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b76f115f-53bb-404a-8c2a-4e11dfe766fb) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-10-12 10:04 UTC, opbld32 commented
Learn Build status updates of commit _[1867e36](https://github.com/MicrosoftDocs/msteams-docs/commits/1867e369a64f9e2ef707cfe8fd5daf82c8ffc77d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/teams-toolkit-v2/debug/app-package-path.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/app-package-path.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/customize-npm-install.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/customize-npm-install.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/modify-ports-bot.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/modify-ports-bot.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/modify-ports-tab.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/modify-ports-tab.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/prerequisites-debugcheck1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/prerequisites-debugcheck1.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-background-process?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/set-up-bot.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/set-up-bot.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/skip-prerequisite-checks.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/skip-prerequisite-checks.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/start-local-tunnel.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/start-local-tunnel.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/Terminal1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/Terminal1.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-local?branch=pr-en-us-7026) |
[msteams-platform/sbs-gs-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/sbs-gs-bot.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/sbs-gs-bot?branch=pr-en-us-7026) |
[msteams-platform/sbs-gs-javascript.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/sbs-gs-javascript.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/sbs-gs-javascript?branch=pr-en-us-7026) |
[msteams-platform/sbs-gs-msgext.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/sbs-gs-msgext.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/sbs-gs-msgext?branch=pr-en-us-7026) |
[msteams-platform/toolkit/debug-background-process.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/toolkit/debug-background-process.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-background-process?branch=pr-en-us-7026) |
[msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/toolkit/debug-local.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-local?branch=pr-en-us-7026) |
[msteams-platform/toolkit/debug-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/toolkit/debug-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202210121003425411-7026/BuildReport?accessString=b2a3e8550ada3f8d8fabc85b91cc31e73dadd658f99e803aaf4a0eee8092181c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-12 12:23 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1829d510a6ffcc75e03fa74a26aee9a9a28b1f4d/msteams-platform%2Fsbs-gs-bot.yml) | 91 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1f52bee7-8e51-4642-a041-5708eea0a00f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-javascript.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1829d510a6ffcc75e03fa74a26aee9a9a28b1f4d/msteams-platform%2Fsbs-gs-javascript.yml) | 91 | 40 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fcea23ab-9695-41b2-990b-0c51d0d1a73d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-msgext.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1829d510a6ffcc75e03fa74a26aee9a9a28b1f4d/msteams-platform%2Fsbs-gs-msgext.yml) | 90 | 46 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0f0ae176-6545-48bc-8ac2-629cfe24ab52) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-background-process.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1829d510a6ffcc75e03fa74a26aee9a9a28b1f4d/msteams-platform%2Ftoolkit%2Fdebug-background-process.md) | 98 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/206265f4-0df0-4286-809d-758957affc76) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1829d510a6ffcc75e03fa74a26aee9a9a28b1f4d/msteams-platform%2Ftoolkit%2Fdebug-local.md) | 94 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b67bda79-8022-4a23-9c1e-65cc0b787582) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1829d510a6ffcc75e03fa74a26aee9a9a28b1f4d/msteams-platform%2Ftoolkit%2Fdebug-overview.md) | 95 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0538b773-cfb7-488a-b50c-41a3d1068186) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-10-12 12:24 UTC, opbld33 commented
Learn Build status updates of commit _[1829d51](https://github.com/MicrosoftDocs/msteams-docs/commits/1829d510a6ffcc75e03fa74a26aee9a9a28b1f4d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/teams-toolkit-v2/debug/app-package-path.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/app-package-path.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/customize-npm-install.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/customize-npm-install.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/modify-ports-bot.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/modify-ports-bot.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/modify-ports-tab.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/modify-ports-tab.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/prerequisites-debugcheck1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/prerequisites-debugcheck1.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-background-process?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/set-up-bot.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/set-up-bot.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/skip-prerequisite-checks.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/skip-prerequisite-checks.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/start-local-tunnel.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/start-local-tunnel.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/Terminal1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/Terminal1.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-local?branch=pr-en-us-7026) |
[msteams-platform/sbs-gs-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/sbs-gs-bot.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/sbs-gs-bot?branch=pr-en-us-7026) |
[msteams-platform/sbs-gs-javascript.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/sbs-gs-javascript.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/sbs-gs-javascript?branch=pr-en-us-7026) |
[msteams-platform/sbs-gs-msgext.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/sbs-gs-msgext.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/sbs-gs-msgext?branch=pr-en-us-7026) |
[msteams-platform/toolkit/debug-background-process.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/toolkit/debug-background-process.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-background-process?branch=pr-en-us-7026) |
[msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/toolkit/debug-local.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-local?branch=pr-en-us-7026) |
[msteams-platform/toolkit/debug-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/toolkit/debug-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202210121223241517-7026/BuildReport?accessString=c8756a1fd86a8455720a0306e14e7cdcf06bdac77848ec88fe8a9d9f904c4908).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-12 13:20 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/b454f85599f0ac021fc8a8665250c440b01f575e/msteams-platform%2Fsbs-gs-bot.yml) | 91 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/20d5379e-e247-440e-9047-28b5d2da6936) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-javascript.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/b454f85599f0ac021fc8a8665250c440b01f575e/msteams-platform%2Fsbs-gs-javascript.yml) | 91 | 40 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3d77f89a-e7a4-4cf2-b5d7-04fc05045ff0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-msgext.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/b454f85599f0ac021fc8a8665250c440b01f575e/msteams-platform%2Fsbs-gs-msgext.yml) | 90 | 46 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8fbdec20-4906-414f-ab50-8e93e7f7ee5e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-background-process.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b454f85599f0ac021fc8a8665250c440b01f575e/msteams-platform%2Ftoolkit%2Fdebug-background-process.md) | 98 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dfc68734-7376-4e74-a646-eb23085681b4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b454f85599f0ac021fc8a8665250c440b01f575e/msteams-platform%2Ftoolkit%2Fdebug-local.md) | 94 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/037868c7-2040-4d2c-9ddd-5a9c19bd9b66) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b454f85599f0ac021fc8a8665250c440b01f575e/msteams-platform%2Ftoolkit%2Fdebug-overview.md) | 95 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aaefa1f0-69f3-4e2a-81e3-1483537a5e90) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-10-12 13:20 UTC, opbld31 commented
Learn Build status updates of commit _[b454f85](https://github.com/MicrosoftDocs/msteams-docs/commits/b454f85599f0ac021fc8a8665250c440b01f575e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/teams-toolkit-v2/debug/app-package-path.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/app-package-path.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/customize-npm-install.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/customize-npm-install.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/modify-ports-bot.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/modify-ports-bot.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/modify-ports-tab.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/modify-ports-tab.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/prerequisites-debugcheck1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/prerequisites-debugcheck1.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-background-process?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/set-up-bot.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/set-up-bot.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/skip-prerequisite-checks.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/skip-prerequisite-checks.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/start-local-tunnel.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/start-local-tunnel.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/Terminal1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/Terminal1.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-local?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/first-msgext/f5-build-and-run-mex.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/first-msgext/f5-build-and-run-mex.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/sbs-gs-msgext?branch=pr-en-us-7026) |
[msteams-platform/sbs-gs-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/sbs-gs-bot.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/sbs-gs-bot?branch=pr-en-us-7026) |
[msteams-platform/sbs-gs-javascript.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/sbs-gs-javascript.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/sbs-gs-javascript?branch=pr-en-us-7026) |
[msteams-platform/sbs-gs-msgext.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/sbs-gs-msgext.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/sbs-gs-msgext?branch=pr-en-us-7026) |
[msteams-platform/toolkit/debug-background-process.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/toolkit/debug-background-process.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-background-process?branch=pr-en-us-7026) |
[msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/toolkit/debug-local.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-local?branch=pr-en-us-7026) |
[msteams-platform/toolkit/debug-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/toolkit/debug-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202210121320028363-7026/BuildReport?accessString=5f59148383daaf314250fb7046f3bd15533667a0e7edfebaec6420fb9e4ac180).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-13 10:29 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/27a69209082f589ca22ae97e28837d206699ff26/msteams-platform%2Fsbs-gs-bot.yml) | 91 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c265bf5a-bc21-48ee-8a9e-f90531e6c899) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-javascript.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/27a69209082f589ca22ae97e28837d206699ff26/msteams-platform%2Fsbs-gs-javascript.yml) | 91 | 40 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/482f61e1-de14-44b4-b784-643d6dee839a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-msgext.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/27a69209082f589ca22ae97e28837d206699ff26/msteams-platform%2Fsbs-gs-msgext.yml) | 90 | 46 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bbe17987-dec5-4c03-9e8e-02d5440c00a5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-background-process.md](https://github.com/MicrosoftDocs/msteams-docs/blob/27a69209082f589ca22ae97e28837d206699ff26/msteams-platform%2Ftoolkit%2Fdebug-background-process.md) | 98 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f863f500-f48e-4da2-befb-e46f0aa94b28) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/27a69209082f589ca22ae97e28837d206699ff26/msteams-platform%2Ftoolkit%2Fdebug-local.md) | 94 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8e45d990-c736-4387-a73c-7c4fc9461e2b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/27a69209082f589ca22ae97e28837d206699ff26/msteams-platform%2Ftoolkit%2Fdebug-overview.md) | 95 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/54916b62-41db-4695-89be-707b915f3c1b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-10-13 10:30 UTC, opbld31 commented
Learn Build status updates of commit _[27a6920](https://github.com/MicrosoftDocs/msteams-docs/commits/27a69209082f589ca22ae97e28837d206699ff26)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/teams-toolkit-v2/debug/app-package-path.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/app-package-path.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/customize-npm-install.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/customize-npm-install.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/modify-ports-bot.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/modify-ports-bot.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/modify-ports-tab.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/modify-ports-tab.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/prerequisites-debugcheck1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/prerequisites-debugcheck1.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-background-process?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/set-up-bot.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/set-up-bot.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/skip-prerequisite-checks.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/skip-prerequisite-checks.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/start-local-tunnel.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/start-local-tunnel.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/Terminal1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/Terminal1.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-local?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/first-msgext/f5-build-and-run-mex.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/first-msgext/f5-build-and-run-mex.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/sbs-gs-msgext?branch=pr-en-us-7026) |
[msteams-platform/sbs-gs-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/sbs-gs-bot.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/sbs-gs-bot?branch=pr-en-us-7026) |
[msteams-platform/sbs-gs-javascript.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/sbs-gs-javascript.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/sbs-gs-javascript?branch=pr-en-us-7026) |
[msteams-platform/sbs-gs-msgext.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/sbs-gs-msgext.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/sbs-gs-msgext?branch=pr-en-us-7026) |
[msteams-platform/toolkit/debug-background-process.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/toolkit/debug-background-process.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-background-process?branch=pr-en-us-7026) |
[msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/toolkit/debug-local.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-local?branch=pr-en-us-7026) |
[msteams-platform/toolkit/debug-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/toolkit/debug-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202210131029290934-7026/BuildReport?accessString=cd63dd2a7e7e61d1effc19354d4cbe5133d2699e70aad8fac42bbdacd40a17d8).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-13 10:54 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e91c049bb916297e0dfe51c554ede48b646670b5/msteams-platform%2Fsbs-gs-bot.yml) | 91 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/de4f2399-4bd5-48c4-bb25-735fa61f95cc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-javascript.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e91c049bb916297e0dfe51c554ede48b646670b5/msteams-platform%2Fsbs-gs-javascript.yml) | 91 | 40 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1e6b95e7-8bca-404b-8621-bdd684973270) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-msgext.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e91c049bb916297e0dfe51c554ede48b646670b5/msteams-platform%2Fsbs-gs-msgext.yml) | 90 | 46 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d9fae43b-d369-4b6f-a6c3-1e7502e74375) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-background-process.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e91c049bb916297e0dfe51c554ede48b646670b5/msteams-platform%2Ftoolkit%2Fdebug-background-process.md) | 98 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0874881f-0ca0-42b9-8da0-69408aa39e0b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e91c049bb916297e0dfe51c554ede48b646670b5/msteams-platform%2Ftoolkit%2Fdebug-local.md) | 94 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/95febc01-5feb-4630-ac00-7a3ad037e6b5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e91c049bb916297e0dfe51c554ede48b646670b5/msteams-platform%2Ftoolkit%2Fdebug-overview.md) | 95 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e9bf9971-3ab3-436b-a690-c7e05e270051) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-10-13 10:54 UTC, opbld31 commented
Learn Build status updates of commit _[e91c049](https://github.com/MicrosoftDocs/msteams-docs/commits/e91c049bb916297e0dfe51c554ede48b646670b5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/teams-toolkit-v2/debug/app-package-path.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/app-package-path.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/customize-npm-install.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/customize-npm-install.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/modify-ports-bot.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/modify-ports-bot.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/modify-ports-tab.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/modify-ports-tab.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/prerequisites-debugcheck1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/prerequisites-debugcheck1.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-background-process?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/set-up-bot.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/set-up-bot.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/skip-prerequisite-checks.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/skip-prerequisite-checks.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/start-local-tunnel.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/start-local-tunnel.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/Terminal1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/Terminal1.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-local?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/first-msgext/f5-build-and-run-mex.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/first-msgext/f5-build-and-run-mex.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/sbs-gs-msgext?branch=pr-en-us-7026) |
[msteams-platform/sbs-gs-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/sbs-gs-bot.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/sbs-gs-bot?branch=pr-en-us-7026) |
[msteams-platform/sbs-gs-javascript.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/sbs-gs-javascript.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/sbs-gs-javascript?branch=pr-en-us-7026) |
[msteams-platform/sbs-gs-msgext.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/sbs-gs-msgext.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/sbs-gs-msgext?branch=pr-en-us-7026) |
[msteams-platform/toolkit/debug-background-process.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/toolkit/debug-background-process.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-background-process?branch=pr-en-us-7026) |
[msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/toolkit/debug-local.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-local?branch=pr-en-us-7026) |
[msteams-platform/toolkit/debug-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/toolkit/debug-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202210131053493829-7026/BuildReport?accessString=7d45f2ef04621bab34d4adf588a3f2e2d95216e705d70fa77e4bd36d473aabe6).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-14 04:10 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/bdab78bfe007f276e29a0f309fba13e0086686cb/msteams-platform%2Fsbs-gs-bot.yml) | 91 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/62e3eb65-6d37-4afa-bef4-2d1e6389b6bb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-javascript.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/bdab78bfe007f276e29a0f309fba13e0086686cb/msteams-platform%2Fsbs-gs-javascript.yml) | 91 | 40 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3edd32b4-8448-4239-b17c-5d69a0cd2182) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-msgext.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/bdab78bfe007f276e29a0f309fba13e0086686cb/msteams-platform%2Fsbs-gs-msgext.yml) | 90 | 46 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/afe0baa2-3f06-41ce-984b-b964e4a2b876) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-background-process.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bdab78bfe007f276e29a0f309fba13e0086686cb/msteams-platform%2Ftoolkit%2Fdebug-background-process.md) | 98 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/62e8baf5-81bb-4f58-9c61-34fa9d7f1fc4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bdab78bfe007f276e29a0f309fba13e0086686cb/msteams-platform%2Ftoolkit%2Fdebug-local.md) | 94 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a52f9ba5-6889-4302-975b-bb8d1430e237) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bdab78bfe007f276e29a0f309fba13e0086686cb/msteams-platform%2Ftoolkit%2Fdebug-overview.md) | 95 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ffe25ed3-a2f1-4f22-9488-5182b4ea7803) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-10-14 04:11 UTC, opbld33 commented
Learn Build status updates of commit _[bdab78b](https://github.com/MicrosoftDocs/msteams-docs/commits/bdab78bfe007f276e29a0f309fba13e0086686cb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/teams-toolkit-v2/debug/app-package-path.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/app-package-path.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/customize-npm-install.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/customize-npm-install.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/modify-ports-bot.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/modify-ports-bot.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/modify-ports-tab.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/modify-ports-tab.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/prerequisites-debugcheck1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/prerequisites-debugcheck1.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-background-process?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/set-up-bot.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/set-up-bot.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/skip-prerequisite-checks.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/skip-prerequisite-checks.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/start-local-tunnel.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/start-local-tunnel.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/Terminal1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/Terminal1.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-local?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/first-msgext/f5-build-and-run-mex.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/first-msgext/f5-build-and-run-mex.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/sbs-gs-msgext?branch=pr-en-us-7026) |
[msteams-platform/sbs-gs-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/sbs-gs-bot.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/sbs-gs-bot?branch=pr-en-us-7026) |
[msteams-platform/sbs-gs-javascript.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/sbs-gs-javascript.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/sbs-gs-javascript?branch=pr-en-us-7026) |
[msteams-platform/sbs-gs-msgext.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/sbs-gs-msgext.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/sbs-gs-msgext?branch=pr-en-us-7026) |
[msteams-platform/toolkit/debug-background-process.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/toolkit/debug-background-process.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-background-process?branch=pr-en-us-7026) |
[msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/toolkit/debug-local.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-local?branch=pr-en-us-7026) |
[msteams-platform/toolkit/debug-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/toolkit/debug-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202210140410268714-7026/BuildReport?accessString=50194396e0be3cfab2b8eb65f8b8c53f6d4ff93dfb74edd32abdb910e4be8b37).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-14 04:44 UTC, jidddddd requested changes
See comment

2022-10-14 04:53 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/380abce7249228e54cf1b70631bae50ac833fcde/msteams-platform%2Fsbs-gs-bot.yml) | 91 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f275a5b4-6619-4b57-8828-a0035c9157b9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-javascript.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/380abce7249228e54cf1b70631bae50ac833fcde/msteams-platform%2Fsbs-gs-javascript.yml) | 91 | 40 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2cf5ff7f-d3c2-420f-95b6-c50b4c2bd2f5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-msgext.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/380abce7249228e54cf1b70631bae50ac833fcde/msteams-platform%2Fsbs-gs-msgext.yml) | 90 | 46 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e335a201-340d-4905-b9c5-9d995cdb55da) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-background-process.md](https://github.com/MicrosoftDocs/msteams-docs/blob/380abce7249228e54cf1b70631bae50ac833fcde/msteams-platform%2Ftoolkit%2Fdebug-background-process.md) | 98 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cb434ff5-0c3d-4e9f-a033-79f9590c9ef9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/380abce7249228e54cf1b70631bae50ac833fcde/msteams-platform%2Ftoolkit%2Fdebug-local.md) | 93 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/44868da8-cd4b-455b-b37b-26241c39a708) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/380abce7249228e54cf1b70631bae50ac833fcde/msteams-platform%2Ftoolkit%2Fdebug-overview.md) | 95 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ff2578dd-db05-428e-ae48-9625672685f9) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-10-14 04:54 UTC, opbld31 commented
Learn Build status updates of commit _[380abce](https://github.com/MicrosoftDocs/msteams-docs/commits/380abce7249228e54cf1b70631bae50ac833fcde)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/teams-toolkit-v2/debug/app-package-path.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/app-package-path.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/customize-npm-install.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/customize-npm-install.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/modify-ports-bot.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/modify-ports-bot.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/modify-ports-tab.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/modify-ports-tab.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/prerequisites-debugcheck1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/prerequisites-debugcheck1.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-background-process?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/set-up-bot.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/set-up-bot.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/skip-prerequisite-checks.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/skip-prerequisite-checks.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/start-local-tunnel.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/start-local-tunnel.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/Terminal1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/Terminal1.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-local?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/first-msgext/f5-build-and-run-mex.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/first-msgext/f5-build-and-run-mex.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/sbs-gs-msgext?branch=pr-en-us-7026) |
[msteams-platform/sbs-gs-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/sbs-gs-bot.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/sbs-gs-bot?branch=pr-en-us-7026) |
[msteams-platform/sbs-gs-javascript.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/sbs-gs-javascript.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/sbs-gs-javascript?branch=pr-en-us-7026) |
[msteams-platform/sbs-gs-msgext.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/sbs-gs-msgext.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/sbs-gs-msgext?branch=pr-en-us-7026) |
[msteams-platform/toolkit/debug-background-process.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/toolkit/debug-background-process.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-background-process?branch=pr-en-us-7026) |
[msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/toolkit/debug-local.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-local?branch=pr-en-us-7026) |
[msteams-platform/toolkit/debug-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/toolkit/debug-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202210140453359761-7026/BuildReport?accessString=ee9ac3a183f8be9fb353d98b27ab2507953f15ce2982f175e95f817ed99e4078).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-14 04:56 UTC, v-amprasad commented on msteams-platform/toolkit/debug-overview.md
> +Teams Toolkit allows you to customize the debug settings to create your tab or bot. For more information on the full list of customizable options, see [debug settings doc](https://github.com/kuojianl
The link has been updated to: https://aka.ms/teamsfx-debug-tasks.

2022-10-14 05:04 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/8d32b250be07cea4fd8d2ab49515efb10a550164/msteams-platform%2Fsbs-gs-bot.yml) | 91 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b5fdc224-0b73-4868-ba23-1af25b6d6830) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-javascript.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/8d32b250be07cea4fd8d2ab49515efb10a550164/msteams-platform%2Fsbs-gs-javascript.yml) | 91 | 40 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f1f225c2-4548-499b-bcb2-6ae4156c304b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-msgext.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/8d32b250be07cea4fd8d2ab49515efb10a550164/msteams-platform%2Fsbs-gs-msgext.yml) | 90 | 46 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0b508f5b-8cd8-422d-ad20-a27bead60580) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-background-process.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8d32b250be07cea4fd8d2ab49515efb10a550164/msteams-platform%2Ftoolkit%2Fdebug-background-process.md) | 98 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0250a57a-0616-46ec-96e9-a6cf31e2ef34) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8d32b250be07cea4fd8d2ab49515efb10a550164/msteams-platform%2Ftoolkit%2Fdebug-local.md) | 93 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/56a9cf52-5212-455b-ab81-0343cf90e5de) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8d32b250be07cea4fd8d2ab49515efb10a550164/msteams-platform%2Ftoolkit%2Fdebug-overview.md) | 95 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4a3c34a3-379d-49a0-9c48-2ae13003b8bb) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-10-14 05:04 UTC, opbld31 commented
Learn Build status updates of commit _[8d32b25](https://github.com/MicrosoftDocs/msteams-docs/commits/8d32b250be07cea4fd8d2ab49515efb10a550164)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/teams-toolkit-v2/debug/app-package-path.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/app-package-path.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/customize-npm-install.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/customize-npm-install.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/modify-ports-bot.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/modify-ports-bot.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/modify-ports-tab.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/modify-ports-tab.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/prerequisites-debugcheck1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/prerequisites-debugcheck1.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-background-process?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/set-up-bot.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/set-up-bot.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/skip-prerequisite-checks.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/skip-prerequisite-checks.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/start-local-tunnel.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/start-local-tunnel.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/Terminal1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/Terminal1.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-local?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/first-msgext/f5-build-and-run-mex.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/first-msgext/f5-build-and-run-mex.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/sbs-gs-msgext?branch=pr-en-us-7026) |
[msteams-platform/sbs-gs-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/sbs-gs-bot.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/sbs-gs-bot?branch=pr-en-us-7026) |
[msteams-platform/sbs-gs-javascript.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/sbs-gs-javascript.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/sbs-gs-javascript?branch=pr-en-us-7026) |
[msteams-platform/sbs-gs-msgext.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/sbs-gs-msgext.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/sbs-gs-msgext?branch=pr-en-us-7026) |
[msteams-platform/toolkit/debug-background-process.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/toolkit/debug-background-process.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-background-process?branch=pr-en-us-7026) |
[msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/toolkit/debug-local.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-local?branch=pr-en-us-7026) |
[msteams-platform/toolkit/debug-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/toolkit/debug-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202210140503550246-7026/BuildReport?accessString=9899272e06dfa5a09660d07d68a574a5c107936e329e07fe2b5531712aa5ed94).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-14 05:22 UTC, v-amprasad commented on msteams-platform/toolkit/debug-overview.md
> +Teams Toolkit allows you to customize the debug settings to create your tab or bot. For more information on the full list of customizable options, see [debug settings doc](https://github.com/kuojianl
SME confirmed changes updated in the doc.

2022-10-20 05:14 UTC, opbld31 commented
Learn Build status updates of commit _[0dfe581](https://github.com/MicrosoftDocs/msteams-docs/commits/0dfe58122331d0d357f639f32bd8abc0d7a043f8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/teams-toolkit-v2/debug/app-package-path.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/app-package-path.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/customize-npm-install.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/customize-npm-install.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/modify-ports-bot.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/modify-ports-bot.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/modify-ports-tab.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/modify-ports-tab.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/prerequisites-debugcheck1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/prerequisites-debugcheck1.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-background-process?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/set-up-bot.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/set-up-bot.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/skip-prerequisite-checks.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/skip-prerequisite-checks.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/start-local-tunnel.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/start-local-tunnel.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/debug/Terminal1.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/debug/Terminal1.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-local?branch=pr-en-us-7026) |
[msteams-platform/assets/images/teams-toolkit-v2/first-msgext/f5-build-and-run-mex.png](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/assets/images/teams-toolkit-v2/first-msgext/f5-build-and-run-mex.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/sbs-gs-msgext?branch=pr-en-us-7026) |
[msteams-platform/sbs-gs-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/sbs-gs-bot.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/sbs-gs-bot?branch=pr-en-us-7026) |
[msteams-platform/sbs-gs-javascript.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/sbs-gs-javascript.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/sbs-gs-javascript?branch=pr-en-us-7026) |
[msteams-platform/sbs-gs-msgext.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/sbs-gs-msgext.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/sbs-gs-msgext?branch=pr-en-us-7026) |
[msteams-platform/toolkit/debug-background-process.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/toolkit/debug-background-process.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-background-process?branch=pr-en-us-7026) |
[msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/toolkit/debug-local.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-local?branch=pr-en-us-7026) |
[msteams-platform/toolkit/debug-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-ttk-visual-studio-code-debug-corrections/msteams-platform/toolkit/debug-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-overview?branch=pr-en-us-7026) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202210200513191072-7026/BuildReport?accessString=e3ef4915ef69f820a3c13dd3eaa58b6ee807b7c40c3ed2cbbd25a74d6421ea76).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-20 05:23 UTC, surbhigupta12 approved these changes

2022-10-20 05:23 UTC, merged