[Doc Improvement][Payload added in Adaptive Card TaskInfo.card section]
MicrosoftDocs/msteams-docs pull request #7475
Opened 2022-11-18 11:45 UTC by v-sdhakshina

2022-11-18 11:46 UTC, opbld32 commented
Learn Build status updates of commit _[56dfdda](https://github.com/MicrosoftDocs/msteams-docs/commits/56dfddad2f2da90bfc06f29fb08b215a8490b8c6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/task-modules-and-cards/task-modules/task-modules-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-task-module-tabs/msteams-platform/task-modules-and-cards/task-modules/task-modules-tabs.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/task-modules/task-modules-tabs?branch=pr-en-us-7475) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202211181145033033-7475/BuildReport?accessString=f37f45c5cc56785ec0039e15dbd69b4aa5313a12a1b8f15e9c1aa31056c7f47f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-21 09:31 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/task-modules-and-cards/task-modules/task-modules-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/158cf37269d945756967fa0eee41280e9742cc5e/msteams-platform%2Ftask-modules-and-cards%2Ftask-modules%2Ftask-modules-tabs.md) | 91 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b83e7136-68f3-42dd-8af8-afe4cde0c37d) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-11-21 09:38 UTC, opbld32 commented
Learn Build status updates of commit _[158cf37](https://github.com/MicrosoftDocs/msteams-docs/commits/158cf37269d945756967fa0eee41280e9742cc5e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/task-modules-and-cards/task-modules/task-modules-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-task-module-tabs/msteams-platform/task-modules-and-cards/task-modules/task-modules-tabs.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/task-modules/task-modules-tabs?branch=pr-en-us-7475) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202211210931192527-7475/BuildReport?accessString=5fe4959dd8c5680bfe0ee062321e80b3b3472668ebc758c60f4ffc21ce33cbc0).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-23 05:13 UTC, Wajeed-msft requested changes

2022-11-23 05:13 UTC, Wajeed-msft commented on msteams-platform/task-modules-and-cards/task-modules/task-modules-tabs.md
> +  "card": "Adaptive Card or Adaptive Card bot card attachment"
Formatting seems to be incorrect, also comma is missing after "card" section.

2022-11-23 05:13 UTC, Wajeed-msft commented on msteams-platform/task-modules-and-cards/task-modules/task-modules-tabs.md
> +if (type.includes('bot'))
Please fix the formatting.

2022-11-23 05:56 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/task-modules-and-cards/task-modules/task-modules-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4a58553b39b03e1f97ded663d9b3632dc5e87bc6/msteams-platform%2Ftask-modules-and-cards%2Ftask-modules%2Ftask-modules-tabs.md) | 91 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/414eb972-2641-46a8-b8d5-02c56b87ff23) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-11-23 05:57 UTC, opbld31 commented
Learn Build status updates of commit _[4a58553](https://github.com/MicrosoftDocs/msteams-docs/commits/4a58553b39b03e1f97ded663d9b3632dc5e87bc6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/task-modules-and-cards/task-modules/task-modules-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-task-module-tabs/msteams-platform/task-modules-and-cards/task-modules/task-modules-tabs.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/task-modules/task-modules-tabs?branch=pr-en-us-7475) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202211230556381161-7475/BuildReport?accessString=ab867fa0dfa75826f84d6790352b3739a07bfdb3e85ccdbbb7a41005f09141d6).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-23 10:02 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/task-modules-and-cards/task-modules/task-modules-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dc34551e6a701553ef3b0b3c04d6334c2efce82d/msteams-platform%2Ftask-modules-and-cards%2Ftask-modules%2Ftask-modules-tabs.md) | 91 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0ff6e69e-366a-4af2-818e-dccabecdfe27) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-11-23 10:03 UTC, opbld31 commented
Learn Build status updates of commit _[dc34551](https://github.com/MicrosoftDocs/msteams-docs/commits/dc34551e6a701553ef3b0b3c04d6334c2efce82d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/task-modules-and-cards/task-modules/task-modules-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-task-module-tabs/msteams-platform/task-modules-and-cards/task-modules/task-modules-tabs.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/task-modules/task-modules-tabs?branch=pr-en-us-7475) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202211231002143692-7475/BuildReport?accessString=bb80f610c82a2a964ddd7d782309531d0af1741adf221fc73c4e67165f0779df).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-24 06:06 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/task-modules-and-cards/task-modules/task-modules-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1430c228f743caa39907f25789dc6df4a10ec25f/msteams-platform%2Ftask-modules-and-cards%2Ftask-modules%2Ftask-modules-tabs.md) | 91 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aa0f5cca-df66-4fad-9a29-651a0a710ec6) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-11-24 06:06 UTC, Wajeed-msft approved these changes

2022-11-24 06:07 UTC, opbld32 commented
Learn Build status updates of commit _[1430c22](https://github.com/MicrosoftDocs/msteams-docs/commits/1430c228f743caa39907f25789dc6df4a10ec25f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/task-modules-and-cards/task-modules/task-modules-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-task-module-tabs/msteams-platform/task-modules-and-cards/task-modules/task-modules-tabs.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/task-modules/task-modules-tabs?branch=pr-en-us-7475) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202211240606126352-7475/BuildReport?accessString=ad22b47793d031220ac2c0c38cc4864a7705671dc98051b1e5da05b93413e503).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-28 06:27 UTC, v-sdhakshina commented
@tomlm Request you to please review and approve.

2022-11-29 08:40 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/task-modules-and-cards/task-modules/task-modules-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8f4ef9375dad91af3fcc46c12e7e91b660f9bbc9/msteams-platform%2Ftask-modules-and-cards%2Ftask-modules%2Ftask-modules-tabs.md) | 91 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/63fabae7-5d5a-4981-a327-2170a5581503) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-11-29 08:41 UTC, opbld31 commented
Learn Build status updates of commit _[8f4ef93](https://github.com/MicrosoftDocs/msteams-docs/commits/8f4ef9375dad91af3fcc46c12e7e91b660f9bbc9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/task-modules-and-cards/task-modules/task-modules-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-task-module-tabs/msteams-platform/task-modules-and-cards/task-modules/task-modules-tabs.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/task-modules/task-modules-tabs?branch=pr-en-us-7475) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202211290840220681-7475/BuildReport?accessString=a7a2e1f7e88e3cc62f2fab9c19ed1633a909ad1707c722cc6e6765dc2bd2cec7).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-29 11:45 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/task-modules-and-cards/task-modules/task-modules-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d869fa491d7e57b3e20443a8dce99ba6c4361ee4/msteams-platform%2Ftask-modules-and-cards%2Ftask-modules%2Ftask-modules-tabs.md) | 91 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9a68297c-9c90-4e26-bd03-4e19df8fabd7) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2022-11-29 11:46 UTC, opbld32 commented
Learn Build status updates of commit _[d869fa4](https://github.com/MicrosoftDocs/msteams-docs/commits/d869fa491d7e57b3e20443a8dce99ba6c4361ee4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/task-modules-and-cards/task-modules/task-modules-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/doc-improvement-task-module-tabs/msteams-platform/task-modules-and-cards/task-modules/task-modules-tabs.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/task-modules/task-modules-tabs?branch=pr-en-us-7475) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/d98cc23d-94e8-765b-0855-bdd8964dc537/202211291145312189-7475/BuildReport?accessString=404ed3eae84a9ab9693e076f6593062f59e326a39c54af52ea4bb55a177785da).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-29 11:48 UTC, merged