[Doc Improvement][create-channel-group]
MicrosoftDocs/msteams-docs pull request #8533
Opened 2023-04-26 06:55 UTC by Namitha-23

2023-04-26 06:56 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a918a72b59b5727c3f397d92bca8f77fd1215c14/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-channel-group-tab.md) | 94 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/82c8777e-6a01-45d9-bf47-19536497bf71) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-04-26 06:59 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-blazorupdate.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ead1cc1e30ae3af85aa2f4231f5e0ea4222a7741/msteams-platform%2Fsbs-gs-blazorupdate.yml) | 96 | 48 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/13e8d23e-a17e-4e98-af40-0779847d0993) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ead1cc1e30ae3af85aa2f4231f5e0ea4222a7741/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-channel-group-tab.md) | 94 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6d181f3f-b83f-4f36-8761-1881e052ec67) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-04-26 07:40 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-blazorupdate.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a29a383a08e2c8d1d92c9b56c6812702223d4081/msteams-platform%2Fsbs-gs-blazorupdate.yml) | 96 | 48 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a132f396-11d2-4c29-a3c3-abde4f5a5673) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a29a383a08e2c8d1d92c9b56c6812702223d4081/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-channel-group-tab.md) | 94 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/28fc2831-7d26-4c77-b66f-8545290d651f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-04-26 08:24 UTC, acrolinx-at-msft2 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bd10b4aca63504c09e5cb4ab871b2fd9e4e021b8/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-channel-group-tab.md) | 94 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/da2b02d9-2b04-44ef-9bbc-daaaa5af536b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-04-27 00:51 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b00a14619f1eb6473cd1d3d6e31e50253de066fe/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-channel-group-tab.md) | 94 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/91125100-501f-469e-86be-38e7e252a618) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-04-27 11:15 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8765a418628e56f4bba605deb68d3cf1b6a3ac13/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-channel-group-tab.md) | 94 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ae1a1f65-f603-44ce-a6a9-a0358a4c5f2a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-04-27 11:35 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3af2364580122773c72ea3a841104b0d96da9e37/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-channel-group-tab.md) | 94 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/54cefde3-dc78-4501-8846-b24c11a0b050) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-04-27 15:39 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/deb195adfa6f494818ea5849afb689d1bd5da5b4/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-channel-group-tab.md) | 94 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4f0580e6-8499-4e14-a801-f8cbef66a50b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/deb195adfa6f494818ea5849afb689d1bd5da5b4/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-personal-tab.md) | 94 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bcddc29c-a92c-461a-8627-3d05c5271ffa) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-04-28 05:12 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cd502d1f8dbd5f9e9be64fd608da8396ca18ca3f/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-channel-group-tab.md) | 94 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b0c62d68-decf-4803-a51f-afb809fe5c6c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cd502d1f8dbd5f9e9be64fd608da8396ca18ca3f/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-personal-tab.md) | 94 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8ffcc516-8963-4409-84b5-8efbcdc29709) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/zone-pivot-groups.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/cd502d1f8dbd5f9e9be64fd608da8396ca18ca3f/msteams-platform%2Fzone-pivot-groups.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/251e4ade-9d05-4485-a11a-aafc2502afb1) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-05-02 05:56 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1cd20e8f4cd40a78fabf14bd73cce3642dc5ca49/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-channel-group-tab.md) | 94 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fe9f3b06-a030-40c9-b9b0-e0b62c2a6abe) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1cd20e8f4cd40a78fabf14bd73cce3642dc5ca49/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-personal-tab.md) | 94 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fd2b6f5b-063c-493c-806a-73f785a0d0a1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/zone-pivot-groups.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1cd20e8f4cd40a78fabf14bd73cce3642dc5ca49/msteams-platform%2Fzone-pivot-groups.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ec4e3d40-e647-4c28-87d5-567131ee53a1) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-05-02 06:29 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c338d06850106a1df703651b1abc863bbc3ebdfc/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-channel-group-tab.md) | 95 | 33 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/88b02895-6164-4b29-9d31-488b24b38a5e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c338d06850106a1df703651b1abc863bbc3ebdfc/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-personal-tab.md) | 94 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4acec51f-4eb5-4b42-8d1f-7bf69ae4eb4e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/zone-pivot-groups.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c338d06850106a1df703651b1abc863bbc3ebdfc/msteams-platform%2Fzone-pivot-groups.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dd39820a-692b-4a24-a24d-391b1a3925c5) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-05-02 06:49 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a1744f449f111033f17d19598341cbd904a049a3/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-channel-group-tab.md) | 95 | 33 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b362a197-cdb1-4bb9-98f0-de280378193c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a1744f449f111033f17d19598341cbd904a049a3/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-personal-tab.md) | 94 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bd59b42b-7944-4691-a42c-c5d297ba9a5e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/zone-pivot-groups.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a1744f449f111033f17d19598341cbd904a049a3/msteams-platform%2Fzone-pivot-groups.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7963c1dd-bfa7-49aa-b3f2-e786d77076df) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-05-02 07:14 UTC, sayali-MSFT submitted a review, later dismissed
Approved

2023-05-02 07:40 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-blazorupdate.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/aee99ef99b014dff96ea79151ee10cf4281ab68b/msteams-platform%2Fsbs-gs-blazorupdate.yml) | 96 | 48 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6bdd3ea5-5ea2-4378-9a21-034d9a4ab5ca) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/aee99ef99b014dff96ea79151ee10cf4281ab68b/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-channel-group-tab.md) | 93 | 41 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/20bd41f5-c16a-4b94-b055-6d6d8c3bcbde) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/aee99ef99b014dff96ea79151ee10cf4281ab68b/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-personal-tab.md) | 93 | 44 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7e78c681-4747-4c23-9a44-6a679417be2e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/zone-pivot-groups.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/aee99ef99b014dff96ea79151ee10cf4281ab68b/msteams-platform%2Fzone-pivot-groups.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1e2c1257-16c3-41d9-9744-1e9b48935f5a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-05-02 09:08 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-blazorupdate.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/00edaf08bc6f8a9fb71babb288533dfca2c1a7d1/msteams-platform%2Fsbs-gs-blazorupdate.yml) | 96 | 48 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/99396515-2ee6-4af6-89ff-5a975ccf6b48) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/00edaf08bc6f8a9fb71babb288533dfca2c1a7d1/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-channel-group-tab.md) | 93 | 41 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5da7657b-428c-4915-b996-fedd7c68d845) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/00edaf08bc6f8a9fb71babb288533dfca2c1a7d1/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-personal-tab.md) | 93 | 44 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/23a24f8f-feff-4b09-a3cd-27c6283123c1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/zone-pivot-groups.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/00edaf08bc6f8a9fb71babb288533dfca2c1a7d1/msteams-platform%2Fzone-pivot-groups.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9ffdbe1d-7a54-4e09-8bb2-12d2d3ca5c47) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-05-04 05:40 UTC, Wajeed-msft requested changes
Fix the [blazor-app.png](https://github.com/MicrosoftDocs/msteams-docs/pull/8533/files#diff-Fd4059a1515be97c22d1248e7e471f1c576860e2b8fa474b9612bde501f07d728) image for personal scope.

2023-05-04 06:34 UTC, sayali-MSFT commented
@Wajeed-msft -Could you please confirm the below image is looks fine or need to do changes?

Please add this image instead of blazor-app.png use below 
![Blazor-App-New](https://user-images.githubusercontent.com/93527375/236127788-01e35c7f-e9cf-4a80-b1a4-fe9dfbb82845.png)

2023-05-10 06:17 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-blazorupdate.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/f3f45e377fa2dc63deb8d8282a68374e868b886e/msteams-platform%2Fsbs-gs-blazorupdate.yml) | 95 | 49 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e152fc98-67ec-4a03-8471-f4c3aa27c394) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f3f45e377fa2dc63deb8d8282a68374e868b886e/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-channel-group-tab.md) | 93 | 41 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ac50bc93-745e-40fd-857a-4c1fb30bf66a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f3f45e377fa2dc63deb8d8282a68374e868b886e/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-personal-tab.md) | 92 | 46 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4a80786b-e3d8-4f44-a3ab-2595f0f1bc17) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/zone-pivot-groups.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/f3f45e377fa2dc63deb8d8282a68374e868b886e/msteams-platform%2Fzone-pivot-groups.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/78d1b8b6-343b-46ad-b9b4-5656244b7628) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-05-11 04:55 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-blazorupdate.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/be111fef4ec6a9c27445155c8d62a5338f236696/msteams-platform%2Fsbs-gs-blazorupdate.yml) | 95 | 49 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b7263970-18ed-4798-862f-21627ccdb12d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/be111fef4ec6a9c27445155c8d62a5338f236696/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-channel-group-tab.md) | 93 | 41 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/37f182ba-bb01-407a-9262-04998f655fe3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/be111fef4ec6a9c27445155c8d62a5338f236696/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-personal-tab.md) | 92 | 46 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3d50e383-5fef-4dad-b78c-b2541c0653da) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/zone-pivot-groups.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/be111fef4ec6a9c27445155c8d62a5338f236696/msteams-platform%2Fzone-pivot-groups.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/78a96b29-8b92-469b-858c-4c400e99f924) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-05-15 05:49 UTC, Wajeed-msft approved these changes

2023-05-18 08:06 UTC, Namitha-23 commented
Received Wajeed's approval: 
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/123049347/a24e42c6-c4bd-4bb6-97ab-3236dd6cf1c7)

2023-05-19 04:37 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-blazorupdate.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/343874199b4ae61edefa32b937849f6cf893084e/msteams-platform%2Fsbs-gs-blazorupdate.yml) | 96 | 48 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4f6dd5db-e0bd-4370-8310-df064e362c3d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/343874199b4ae61edefa32b937849f6cf893084e/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-channel-group-tab.md) | 95 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7b0f81c8-e788-4be6-ab33-d69c1e33af38) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/343874199b4ae61edefa32b937849f6cf893084e/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-personal-tab.md) | 93 | 41 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2f7e2962-10f3-4d87-b29d-24b642b339e4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/zone-pivot-groups.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/343874199b4ae61edefa32b937849f6cf893084e/msteams-platform%2Fzone-pivot-groups.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2b4932c2-ce3a-4687-a786-2d5445d352ae) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-05-19 05:15 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-blazorupdate.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/5ef0f3403969ef439983fec06152a4d933065941/msteams-platform%2Fsbs-gs-blazorupdate.yml) | 96 | 48 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/288f237c-cf24-4c65-b665-f1eda77683e2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5ef0f3403969ef439983fec06152a4d933065941/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-channel-group-tab.md) | 95 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/89046728-a4cf-411c-bc19-b11e36449c74) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5ef0f3403969ef439983fec06152a4d933065941/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-personal-tab.md) | 93 | 41 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1888e930-9c91-4f94-911f-4424a7fecfe6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/zone-pivot-groups.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/5ef0f3403969ef439983fec06152a4d933065941/msteams-platform%2Fzone-pivot-groups.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5ebe0d21-b8f0-486b-9f00-89ff53178a21) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-06-01 13:47 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-blazorupdate.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/2d0f4633f5af64d696db57e0615ac13353baf77b/msteams-platform%2Fsbs-gs-blazorupdate.yml) | 95 | 49 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f7505662-fd79-4571-a543-fb8ebd8f8f77) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2d0f4633f5af64d696db57e0615ac13353baf77b/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-channel-group-tab.md) | 94 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3dc7b1d0-7ca6-47f3-8a83-6e9f760d2553) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2d0f4633f5af64d696db57e0615ac13353baf77b/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-personal-tab.md) | 93 | 40 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0952675b-1188-4f31-b214-e18d7e80bc4f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/zone-pivot-groups.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/2d0f4633f5af64d696db57e0615ac13353baf77b/msteams-platform%2Fzone-pivot-groups.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b682d93f-476e-45f3-842e-67afc3e78dd3) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-06-02 04:01 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-blazorupdate.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/89adecb0d0823cafb7081f58fab0def4b273aced/msteams-platform%2Fsbs-gs-blazorupdate.yml) | 95 | 49 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c05d3e6d-5321-46c9-b598-c8c42028920a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/89adecb0d0823cafb7081f58fab0def4b273aced/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-channel-group-tab.md) | 94 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/24e97a1f-cb01-4611-a067-b43939142383) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/89adecb0d0823cafb7081f58fab0def4b273aced/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-personal-tab.md) | 93 | 40 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ca8a8acf-1a65-447f-87fd-04d601b1ccb7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/zone-pivot-groups.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/89adecb0d0823cafb7081f58fab0def4b273aced/msteams-platform%2Fzone-pivot-groups.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f5b2089c-7d4b-486d-be68-999e717873bb) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-06-02 05:15 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-blazorupdate.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/dbbce7e15f867ced265a8a2e5faa344d15c5d322/msteams-platform%2Fsbs-gs-blazorupdate.yml) | 95 | 49 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a9cc86f3-02a0-4470-9dc0-91eb2e75f0ce) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dbbce7e15f867ced265a8a2e5faa344d15c5d322/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-channel-group-tab.md) | 94 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/db71d042-dbfd-4e8a-aaca-891821313b5e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dbbce7e15f867ced265a8a2e5faa344d15c5d322/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-personal-tab.md) | 93 | 40 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aefd976a-60ba-4b7b-a798-2102f28baa10) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/zone-pivot-groups.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/dbbce7e15f867ced265a8a2e5faa344d15c5d322/msteams-platform%2Fzone-pivot-groups.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8e891cf4-a7b0-4f7f-891b-7b6c2c7b3c8e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-06-02 05:18 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-blazorupdate.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/3b72b6a69fea79f39ba3cedda02a4ff693d74ecb/msteams-platform%2Fsbs-gs-blazorupdate.yml) | 95 | 49 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8d074890-827f-40b6-bcd7-432c21bd5538) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3b72b6a69fea79f39ba3cedda02a4ff693d74ecb/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-channel-group-tab.md) | 94 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dc3d6761-38cf-4515-bbb3-bc643239ef7c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3b72b6a69fea79f39ba3cedda02a4ff693d74ecb/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-personal-tab.md) | 93 | 40 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f258091e-38bd-40b4-9845-167568b4aad0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/zone-pivot-groups.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/3b72b6a69fea79f39ba3cedda02a4ff693d74ecb/msteams-platform%2Fzone-pivot-groups.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fb698228-b8e7-47cd-b03e-7aeb8d7559fd) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-06-02 05:42 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-blazorupdate.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/05f9b11ca53da36a17d817ae5c062e65d8ac5953/msteams-platform%2Fsbs-gs-blazorupdate.yml) | 95 | 49 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ec91e398-bb9a-47d1-8f83-d78fb06d0451) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/05f9b11ca53da36a17d817ae5c062e65d8ac5953/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-channel-group-tab.md) | 95 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/96877715-cc3d-4dbb-85d0-c9add4fe9777) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/05f9b11ca53da36a17d817ae5c062e65d8ac5953/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-personal-tab.md) | 93 | 40 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5b9f7b04-8cfe-4d9e-b7a8-7ba99566b817) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/zone-pivot-groups.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/05f9b11ca53da36a17d817ae5c062e65d8ac5953/msteams-platform%2Fzone-pivot-groups.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/48294d4b-d8ab-46fa-acf3-b735a9175d5b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-06-02 06:47 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-blazorupdate.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/12507a5c118140d7427f33edab1745ddef80356b/msteams-platform%2Fsbs-gs-blazorupdate.yml) | 95 | 49 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4c90982b-a273-4e1e-a4eb-4e32c4fe388b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/12507a5c118140d7427f33edab1745ddef80356b/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-channel-group-tab.md) | 95 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a6304002-8d84-4387-a5ec-e4ecc9fedb67) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/12507a5c118140d7427f33edab1745ddef80356b/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-personal-tab.md) | 93 | 40 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/77cf7aa4-ff73-4efe-8d3a-aabe176887ab) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/zone-pivot-groups.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/12507a5c118140d7427f33edab1745ddef80356b/msteams-platform%2Fzone-pivot-groups.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d76b44f8-c837-40ba-8972-ebe58d3c76a7) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-06-02 06:53 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-blazorupdate.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/6304dbd07e0f22f9efe459c6aece7684a1db5cf8/msteams-platform%2Fsbs-gs-blazorupdate.yml) | 95 | 49 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cfcc1483-e746-41ff-a494-0d522261b1f2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6304dbd07e0f22f9efe459c6aece7684a1db5cf8/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-channel-group-tab.md) | 95 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bfb8f9fa-6078-414b-b70d-12493a992d57) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6304dbd07e0f22f9efe459c6aece7684a1db5cf8/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-personal-tab.md) | 94 | 39 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ac0331fd-05f5-4d33-b2fd-83f142a54d5f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/zone-pivot-groups.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/6304dbd07e0f22f9efe459c6aece7684a1db5cf8/msteams-platform%2Fzone-pivot-groups.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4ff29489-bb4e-4475-9d55-6e6215b11d79) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-06-02 10:54 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-blazorupdate.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/58dceab44fba99cbc27939773bc085216679d089/msteams-platform%2Fsbs-gs-blazorupdate.yml) | 96 | 48 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/38c42aae-020a-4d9f-a844-b98d7abe2002) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/58dceab44fba99cbc27939773bc085216679d089/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-channel-group-tab.md) | 95 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a82ccdf8-0c79-4811-8c28-104e29d14ad6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/58dceab44fba99cbc27939773bc085216679d089/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-personal-tab.md) | 94 | 39 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/14060d68-4c36-4375-a78b-910c5cf24061) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/zone-pivot-groups.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/58dceab44fba99cbc27939773bc085216679d089/msteams-platform%2Fzone-pivot-groups.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9d3a01bf-0299-4173-a69c-7b0ec72a9b14) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-06-02 11:01 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-blazorupdate.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/58ca9dcbdcd269a8019fe5c9e6dcb40f96dcc484/msteams-platform%2Fsbs-gs-blazorupdate.yml) | 96 | 48 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ad0fa1da-e474-403c-9b1c-771d4fbb71d3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/58ca9dcbdcd269a8019fe5c9e6dcb40f96dcc484/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-channel-group-tab.md) | 95 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d6253cc3-1d25-4fad-bda8-cb31c4f7fa3a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/58ca9dcbdcd269a8019fe5c9e6dcb40f96dcc484/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-personal-tab.md) | 94 | 39 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ed9d667e-12ba-46b9-a685-38d9b84ea4f7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/zone-pivot-groups.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/58ca9dcbdcd269a8019fe5c9e6dcb40f96dcc484/msteams-platform%2Fzone-pivot-groups.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0ceda2bc-fbd2-47e6-b6a6-5c86ccb8efd0) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-06-02 11:07 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1363efa964ccc9e6d93c147fcf9067143dfadf56/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-channel-group-tab.md) | 95 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fc5e6b19-5225-4eec-86ca-683828fdd77f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1363efa964ccc9e6d93c147fcf9067143dfadf56/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-personal-tab.md) | 94 | 39 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4c19659e-db97-4f65-8e99-9b1f3f0db530) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/zone-pivot-groups.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1363efa964ccc9e6d93c147fcf9067143dfadf56/msteams-platform%2Fzone-pivot-groups.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3e428888-bc6f-46cc-88cd-70ac48a40200) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-06-02 11:47 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a0d8edb9a008b8d27eaf1f5d0714471f49f1ec27/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-channel-group-tab.md) | 95 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/31b22755-b5fc-4127-b2db-b0104a9232e2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a0d8edb9a008b8d27eaf1f5d0714471f49f1ec27/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-personal-tab.md) | 94 | 39 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/11c2779b-08f5-4a37-906f-7dc9eaa53294) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/zone-pivot-groups.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a0d8edb9a008b8d27eaf1f5d0714471f49f1ec27/msteams-platform%2Fzone-pivot-groups.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/72e39d4c-183e-4d99-b3da-046649026b8b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-06-05 09:22 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f40e5bd4762f6e3dc06a4d13d9a8f931cbd34306/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-channel-group-tab.md) | 95 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f501f49e-1cba-4591-9f90-26e0beba3e16) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f40e5bd4762f6e3dc06a4d13d9a8f931cbd34306/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-personal-tab.md) | 94 | 39 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/75477a56-ad0b-4545-96a2-664e7875db77) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/zone-pivot-groups.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/f40e5bd4762f6e3dc06a4d13d9a8f931cbd34306/msteams-platform%2Fzone-pivot-groups.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a127a708-0411-4ecb-8050-adaffaf42078) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-06-05 09:25 UTC, surbhigupta12 approved these changes

2023-06-05 09:25 UTC, v-habibaumme approved these changes

2023-06-05 09:25 UTC, merged