[Doc Improvement][Get started update]
MicrosoftDocs/msteams-docs pull request #8666
Opened 2023-05-18 07:25 UTC by v-sdhakshina

2023-05-18 07:25 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/5ea5d5e269ea0e283e8069f11c2db478aa56579c/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ce4eaad3-194c-475c-a62c-1c1133155289) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/build-basic-tab-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5ea5d5e269ea0e283e8069f11c2db478aa56579c/msteams-platform%2Fget-started%2Fbuild-basic-tab-app.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dba9a752-28ed-4b31-a43b-d3dce8c25c6c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/get-started-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5ea5d5e269ea0e283e8069f11c2db478aa56579c/msteams-platform%2Fget-started%2Fget-started-overview.md) | 90 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c25c7e11-0bf1-435e-a2ac-10f1682e4e2c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-05-18 07:48 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/25522c2a6626fa747a6277f535e9e32055351fd8/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7f194701-78b4-48b9-afb8-f9beb09cd9a5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/build-basic-tab-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/25522c2a6626fa747a6277f535e9e32055351fd8/msteams-platform%2Fget-started%2Fbuild-basic-tab-app.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ea663b6b-e925-49a0-8796-9c93fd66bca6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/get-started-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/25522c2a6626fa747a6277f535e9e32055351fd8/msteams-platform%2Fget-started%2Fget-started-overview.md) | 90 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8dad5a1d-b1d9-4d6b-b72b-268218f9ad6e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/25522c2a6626fa747a6277f535e9e32055351fd8/msteams-platform%2Ftoolkit%2Ffaq.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3478f48a-e4b7-47b9-8e49-7ac4d67bd70e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-05-18 09:02 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/4424a9ce3b8d7d4190d0360873bd941a1c7ab35b/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0498fbff-7c22-448c-b7b1-c7079d2ac2c5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/build-basic-tab-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4424a9ce3b8d7d4190d0360873bd941a1c7ab35b/msteams-platform%2Fget-started%2Fbuild-basic-tab-app.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4bdffd2d-a0a8-4ab5-8953-91fa875a09b0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/get-started-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4424a9ce3b8d7d4190d0360873bd941a1c7ab35b/msteams-platform%2Fget-started%2Fget-started-overview.md) | 90 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4f0c02aa-39ee-43c1-ae3b-52cc46138ff4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4424a9ce3b8d7d4190d0360873bd941a1c7ab35b/msteams-platform%2Ftoolkit%2Ffaq.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f05d54ea-be11-431e-a35f-78e5b54b2502) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/install-Teams-Toolkit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4424a9ce3b8d7d4190d0360873bd941a1c7ab35b/msteams-platform%2Ftoolkit%2Finstall-Teams-Toolkit.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0bd8445b-7f85-4cdd-9620-9a402effc99a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-05-18 09:45 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ae621171b4a44efe4d869b3d657e6e575b35a0fc/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/03f6378a-51df-4fc7-a2d2-5b984973835a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/build-basic-tab-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ae621171b4a44efe4d869b3d657e6e575b35a0fc/msteams-platform%2Fget-started%2Fbuild-basic-tab-app.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d613083f-50c7-48b9-a02b-111aca3cbe44) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/get-started-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ae621171b4a44efe4d869b3d657e6e575b35a0fc/msteams-platform%2Fget-started%2Fget-started-overview.md) | 90 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/710d6495-d606-43f0-b0a2-bae23b85d4cb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ae621171b4a44efe4d869b3d657e6e575b35a0fc/msteams-platform%2Ftoolkit%2Ffaq.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e82d7326-db21-42ab-b44b-8bd9d9307e0d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/install-Teams-Toolkit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ae621171b4a44efe4d869b3d657e6e575b35a0fc/msteams-platform%2Ftoolkit%2Finstall-Teams-Toolkit.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/87f2bde3-6905-42e0-bc71-e3a4e3666fc4) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-05-18 09:55 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/b4dfca9902cef56872985c6354d839591bcd5f7b/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ded57c03-8047-485b-8459-710fcab35b33) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/build-basic-tab-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b4dfca9902cef56872985c6354d839591bcd5f7b/msteams-platform%2Fget-started%2Fbuild-basic-tab-app.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/63c241f4-5f1f-462d-bff3-c6364b5a96dc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/get-started-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b4dfca9902cef56872985c6354d839591bcd5f7b/msteams-platform%2Fget-started%2Fget-started-overview.md) | 90 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6720324c-1a0c-4080-805b-7d8a28c43401) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b4dfca9902cef56872985c6354d839591bcd5f7b/msteams-platform%2Ftoolkit%2Ffaq.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/78c98377-b828-46f1-b43c-f8b369543d85) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/install-Teams-Toolkit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b4dfca9902cef56872985c6354d839591bcd5f7b/msteams-platform%2Ftoolkit%2Finstall-Teams-Toolkit.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b615dd76-50a3-4aa6-9a64-63858b655f3a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-05-18 10:56 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/bd0962fca31e35a4b7bd6212d4c108a1dd8dd441/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/934ada51-6e66-493f-b76e-275ecd6924da) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/build-basic-tab-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bd0962fca31e35a4b7bd6212d4c108a1dd8dd441/msteams-platform%2Fget-started%2Fbuild-basic-tab-app.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8845f2b0-d149-4b00-9e79-efdd67eb8987) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/get-started-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bd0962fca31e35a4b7bd6212d4c108a1dd8dd441/msteams-platform%2Fget-started%2Fget-started-overview.md) | 90 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/31992d27-061c-4a8f-afbd-9db7a0411b87) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bd0962fca31e35a4b7bd6212d4c108a1dd8dd441/msteams-platform%2Ftoolkit%2Ffaq.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e32eed8c-80dd-446e-9b01-3515459db60f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/install-Teams-Toolkit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bd0962fca31e35a4b7bd6212d4c108a1dd8dd441/msteams-platform%2Ftoolkit%2Finstall-Teams-Toolkit.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0b77fc8e-1bf3-4586-87c7-bbff6c7e28fe) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-05-18 11:14 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/6aa5edd60de2b6267fc13e564858d96a3ed4f0ce/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ea464e4e-5c53-43d5-ae10-c4f3dfc50a39) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/build-basic-tab-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6aa5edd60de2b6267fc13e564858d96a3ed4f0ce/msteams-platform%2Fget-started%2Fbuild-basic-tab-app.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d17bdc70-cb3a-411b-b715-afd027a4b951) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/get-started-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6aa5edd60de2b6267fc13e564858d96a3ed4f0ce/msteams-platform%2Fget-started%2Fget-started-overview.md) | 90 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/db5c6c75-9aea-469c-9fb2-d76beba15063) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6aa5edd60de2b6267fc13e564858d96a3ed4f0ce/msteams-platform%2Ftoolkit%2Ffaq.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ee20ba0c-9170-4ee4-8ace-fcabf0301875) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/install-Teams-Toolkit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6aa5edd60de2b6267fc13e564858d96a3ed4f0ce/msteams-platform%2Ftoolkit%2Finstall-Teams-Toolkit.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c255f603-58c3-4f9d-bac5-23cc00aefc6f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-05-18 11:35 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/8b27ef6a7f71ad52d0ea815a30ebafa7866a8081/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4a7cbb6e-0add-4359-94cd-43be1f78d897) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/build-basic-tab-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8b27ef6a7f71ad52d0ea815a30ebafa7866a8081/msteams-platform%2Fget-started%2Fbuild-basic-tab-app.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9b900ba5-78c2-486c-8b1c-3ab71edca695) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/get-started-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8b27ef6a7f71ad52d0ea815a30ebafa7866a8081/msteams-platform%2Fget-started%2Fget-started-overview.md) | 90 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a459758c-be28-4bac-89ae-e9b7099ce3a1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8b27ef6a7f71ad52d0ea815a30ebafa7866a8081/msteams-platform%2Ftoolkit%2Ffaq.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/02e78b6d-7ccf-4dae-9117-87f1de5cff30) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/install-Teams-Toolkit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8b27ef6a7f71ad52d0ea815a30ebafa7866a8081/msteams-platform%2Ftoolkit%2Finstall-Teams-Toolkit.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f9abbd41-9607-458c-bdcf-c6c56c1a9201) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-05-18 11:57 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/613ed204236ed8ededbafb73b41a401201eb2940/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6c04496c-1b58-4754-a4b3-fa94f5acb850) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/build-basic-tab-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/613ed204236ed8ededbafb73b41a401201eb2940/msteams-platform%2Fget-started%2Fbuild-basic-tab-app.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8d8debdd-5ee4-4523-a162-aa21866b00ea) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/choose-what-suits-you.md](https://github.com/MicrosoftDocs/msteams-docs/blob/613ed204236ed8ededbafb73b41a401201eb2940/msteams-platform%2Fget-started%2Fchoose-what-suits-you.md) | 96 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1029cbfd-e07c-4e11-874f-99cf8a7e9f14) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/get-started-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/613ed204236ed8ededbafb73b41a401201eb2940/msteams-platform%2Fget-started%2Fget-started-overview.md) | 90 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/252e7b62-e1ce-43a6-b207-6398916dcf71) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview-solution.md](https://github.com/MicrosoftDocs/msteams-docs/blob/613ed204236ed8ededbafb73b41a401201eb2940/msteams-platform%2Foverview-solution.md) | 91 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0f502481-a9b5-4237-a1ce-723b32331ad8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/613ed204236ed8ededbafb73b41a401201eb2940/msteams-platform%2Foverview.md) | 96 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bfab1f99-bdb2-4b50-a999-1a1ab00c33cb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/613ed204236ed8ededbafb73b41a401201eb2940/msteams-platform%2Ftoolkit%2Ffaq.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e10b90fd-de40-4ec9-a20c-036c09577abc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/install-Teams-Toolkit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/613ed204236ed8ededbafb73b41a401201eb2940/msteams-platform%2Ftoolkit%2Finstall-Teams-Toolkit.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b5016670-3dc8-4515-b1a1-aba7a7138910) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-05-18 11:59 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/cde61fdd772fd3e8fc1ce8aec1194731c35d9dd3/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5c084d07-59c4-4ada-b8c1-111fd6baf878) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/build-basic-tab-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cde61fdd772fd3e8fc1ce8aec1194731c35d9dd3/msteams-platform%2Fget-started%2Fbuild-basic-tab-app.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/14396427-8dc8-46d2-91cf-5e837c72208a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/choose-what-suits-you.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cde61fdd772fd3e8fc1ce8aec1194731c35d9dd3/msteams-platform%2Fget-started%2Fchoose-what-suits-you.md) | 96 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1089ec1e-c231-41ea-936a-2f1259c6c8ef) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/get-started-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cde61fdd772fd3e8fc1ce8aec1194731c35d9dd3/msteams-platform%2Fget-started%2Fget-started-overview.md) | 90 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ae3f9179-0ec3-41fe-9338-88a7ad8970d1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview-solution.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cde61fdd772fd3e8fc1ce8aec1194731c35d9dd3/msteams-platform%2Foverview-solution.md) | 91 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/580e6441-cbb1-4efc-9b5b-3607a4336b8b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cde61fdd772fd3e8fc1ce8aec1194731c35d9dd3/msteams-platform%2Foverview.md) | 96 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a1c7cc7a-e099-4548-b8b8-a247d46972d8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cde61fdd772fd3e8fc1ce8aec1194731c35d9dd3/msteams-platform%2Ftoolkit%2Ffaq.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e9241a3c-e6a5-4174-a49f-0f37c09ff179) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/install-Teams-Toolkit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cde61fdd772fd3e8fc1ce8aec1194731c35d9dd3/msteams-platform%2Ftoolkit%2Finstall-Teams-Toolkit.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/878dfff4-674f-4f6b-9b7b-a76d8d6ed087) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-05-18 22:10 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/0a8b3d27433bf6508e8c730ddfa907266f15072a/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5184e3ff-b5b2-4663-8494-e88eb1c2a4ee) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/build-basic-tab-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0a8b3d27433bf6508e8c730ddfa907266f15072a/msteams-platform%2Fget-started%2Fbuild-basic-tab-app.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d9c4e430-9f51-4539-8511-aae20ecb0677) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/choose-what-suits-you.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0a8b3d27433bf6508e8c730ddfa907266f15072a/msteams-platform%2Fget-started%2Fchoose-what-suits-you.md) | 96 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b4545211-0e03-462c-911c-b40158e1b782) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/get-started-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0a8b3d27433bf6508e8c730ddfa907266f15072a/msteams-platform%2Fget-started%2Fget-started-overview.md) | 90 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/444b5930-6f39-44d4-9cfa-1927e0319579) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview-solution.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0a8b3d27433bf6508e8c730ddfa907266f15072a/msteams-platform%2Foverview-solution.md) | 91 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8674bdc8-0bc7-4d1e-b341-facf4c833227) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0a8b3d27433bf6508e8c730ddfa907266f15072a/msteams-platform%2Foverview.md) | 96 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/910df286-8c20-46b0-91ae-23dc5f9cb30f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0a8b3d27433bf6508e8c730ddfa907266f15072a/msteams-platform%2Ftoolkit%2Ffaq.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f2607fee-3859-4280-9c48-a62b3d98fa42) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/install-Teams-Toolkit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0a8b3d27433bf6508e8c730ddfa907266f15072a/msteams-platform%2Ftoolkit%2Finstall-Teams-Toolkit.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/56f13a57-59b1-4f63-ace4-1f68b822d640) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-05-18 22:28 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/53c67dcbbcfa5467d97ca9744f680942fb270726/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cf9cdd5d-b505-414f-b97f-976ee5030714) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/build-basic-tab-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/53c67dcbbcfa5467d97ca9744f680942fb270726/msteams-platform%2Fget-started%2Fbuild-basic-tab-app.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6cbc85f5-162a-40fd-b5c9-9572fcc40dc5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/choose-what-suits-you.md](https://github.com/MicrosoftDocs/msteams-docs/blob/53c67dcbbcfa5467d97ca9744f680942fb270726/msteams-platform%2Fget-started%2Fchoose-what-suits-you.md) | 96 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/224fdd8d-cb41-4378-9265-bcfc6b6dc830) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/get-started-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/53c67dcbbcfa5467d97ca9744f680942fb270726/msteams-platform%2Fget-started%2Fget-started-overview.md) | 90 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8a0ee5e4-8bd9-4b31-a9c8-83efa5e086fa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview-solution.md](https://github.com/MicrosoftDocs/msteams-docs/blob/53c67dcbbcfa5467d97ca9744f680942fb270726/msteams-platform%2Foverview-solution.md) | 91 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/195f2384-27aa-41b6-acb6-827770174e10) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/53c67dcbbcfa5467d97ca9744f680942fb270726/msteams-platform%2Foverview.md) | 96 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/99470369-3250-44ce-82b6-14ed6c68b78a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/53c67dcbbcfa5467d97ca9744f680942fb270726/msteams-platform%2Ftoolkit%2Ffaq.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aa992921-fe74-4e25-b65b-66ecb725a283) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/install-Teams-Toolkit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/53c67dcbbcfa5467d97ca9744f680942fb270726/msteams-platform%2Ftoolkit%2Finstall-Teams-Toolkit.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c1e9f020-1470-416c-a8b2-db6d3050326e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-05-18 23:22 UTC, Rick-Kirkham requested changes

2023-05-18 23:22 UTC, Rick-Kirkham commented on msteams-platform/TOC.yml
> +  - name: Build tab app
```suggestion
  - name: Build a tab app
```

2023-05-18 23:22 UTC, Rick-Kirkham commented on msteams-platform/get-started/choose-what-suits-you.md
> +This section takes you through the various options that you've for building your Teams app as per your requirements.
Using "you've" before a preposition is not idiomatic English. This is a case where we should stay with "you have" or else put a verb like "got" between "you've" and the preposition "for".  Also, the "as per your requirements" is pointless.
```suggestion
This section takes you through the various options that you have for building your Teams app.
```

2023-05-18 23:22 UTC, Rick-Kirkham commented on msteams-platform/overview-solution.md
> +Let's go through Teams Developer Documentation based on your requirement for building Teams app:
```suggestion
Let's go through Teams Developer Documentation based on your requirements for building Teams app:
```

2023-05-19 16:05 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/5bddd1d09e46b58577b583ccd3024a83f203bdce/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f968aa34-86bd-41d1-9065-604776b31c9b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/build-basic-tab-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5bddd1d09e46b58577b583ccd3024a83f203bdce/msteams-platform%2Fget-started%2Fbuild-basic-tab-app.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f4cdaca3-de70-4ad2-a7b5-8e08319e7025) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/choose-what-suits-you.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5bddd1d09e46b58577b583ccd3024a83f203bdce/msteams-platform%2Fget-started%2Fchoose-what-suits-you.md) | 97 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fd834a86-ae40-4eda-b0e3-163e80b05638) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/get-started-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5bddd1d09e46b58577b583ccd3024a83f203bdce/msteams-platform%2Fget-started%2Fget-started-overview.md) | 90 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fa221c6d-4693-4821-aa51-c03a9ee6719a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview-solution.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5bddd1d09e46b58577b583ccd3024a83f203bdce/msteams-platform%2Foverview-solution.md) | 91 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7d3907d9-812a-4243-84ab-eb96370fb47b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5bddd1d09e46b58577b583ccd3024a83f203bdce/msteams-platform%2Foverview.md) | 96 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6d631ae7-a3a8-438d-a05d-bd91dafe2673) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5bddd1d09e46b58577b583ccd3024a83f203bdce/msteams-platform%2Ftoolkit%2Ffaq.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8a5ea05b-8ee3-462d-8c91-0a54b743c6ca) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/install-Teams-Toolkit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5bddd1d09e46b58577b583ccd3024a83f203bdce/msteams-platform%2Ftoolkit%2Finstall-Teams-Toolkit.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e46caf1f-bb4c-4706-9ece-13ed79550b49) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-05-19 16:05 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/0bbc3b8d55d5d0e0124fa5a033df1aaacf9439fd/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5d6e0ed5-25d4-45a7-8dc5-90ab271ae43a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/build-basic-tab-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0bbc3b8d55d5d0e0124fa5a033df1aaacf9439fd/msteams-platform%2Fget-started%2Fbuild-basic-tab-app.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bcf69600-ef0d-435e-a557-f177dd4e6901) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/choose-what-suits-you.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0bbc3b8d55d5d0e0124fa5a033df1aaacf9439fd/msteams-platform%2Fget-started%2Fchoose-what-suits-you.md) | 97 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d2b54e3c-b10c-4210-b89c-c572a7db680f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/get-started-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0bbc3b8d55d5d0e0124fa5a033df1aaacf9439fd/msteams-platform%2Fget-started%2Fget-started-overview.md) | 90 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/96bd86ad-91ab-408c-9fd7-e674e05900fd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview-solution.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0bbc3b8d55d5d0e0124fa5a033df1aaacf9439fd/msteams-platform%2Foverview-solution.md) | 91 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d63bcd78-ac74-456d-b863-c840ac7f9fad) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0bbc3b8d55d5d0e0124fa5a033df1aaacf9439fd/msteams-platform%2Foverview.md) | 96 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/17f6b85d-ba5b-47ed-8949-7a5751c6a092) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0bbc3b8d55d5d0e0124fa5a033df1aaacf9439fd/msteams-platform%2Ftoolkit%2Ffaq.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ab57dfe1-37bf-49b3-9571-4de10465d67c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/install-Teams-Toolkit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0bbc3b8d55d5d0e0124fa5a033df1aaacf9439fd/msteams-platform%2Ftoolkit%2Finstall-Teams-Toolkit.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7ddf6f5a-18fe-4881-8330-1132c3994d6e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-05-19 16:08 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/df7c65e290bfc69ae13079968e2afbe4cd19e989/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/14ef221e-9bb2-4180-bb18-574e26c9953d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/build-basic-tab-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/df7c65e290bfc69ae13079968e2afbe4cd19e989/msteams-platform%2Fget-started%2Fbuild-basic-tab-app.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7868f71f-6f3f-4924-a388-ae95d46805b6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/choose-what-suits-you.md](https://github.com/MicrosoftDocs/msteams-docs/blob/df7c65e290bfc69ae13079968e2afbe4cd19e989/msteams-platform%2Fget-started%2Fchoose-what-suits-you.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6ef6b1e2-d6d7-4f0a-aa77-5451383f63c9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/get-started-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/df7c65e290bfc69ae13079968e2afbe4cd19e989/msteams-platform%2Fget-started%2Fget-started-overview.md) | 90 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4edf887c-b8e9-4d6d-bf9c-06b7570a8d2e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview-solution.md](https://github.com/MicrosoftDocs/msteams-docs/blob/df7c65e290bfc69ae13079968e2afbe4cd19e989/msteams-platform%2Foverview-solution.md) | 91 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c3ff7db3-e0d2-4070-bb9a-fc3998b68fac) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/df7c65e290bfc69ae13079968e2afbe4cd19e989/msteams-platform%2Foverview.md) | 96 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/67798efc-5d80-4919-8ea8-6f971e23533a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/df7c65e290bfc69ae13079968e2afbe4cd19e989/msteams-platform%2Ftoolkit%2Ffaq.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/64aef96d-afe5-4881-ab9e-8645e5021759) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/install-Teams-Toolkit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/df7c65e290bfc69ae13079968e2afbe4cd19e989/msteams-platform%2Ftoolkit%2Finstall-Teams-Toolkit.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fa985e0d-f59f-43c0-afcd-61ae99766b8f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-05-19 16:11 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c203f37e2c213a854c4fded320f579248beb7205/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f8392e29-4219-435c-893c-9d2df7050d1b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/build-basic-tab-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c203f37e2c213a854c4fded320f579248beb7205/msteams-platform%2Fget-started%2Fbuild-basic-tab-app.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/60303a0b-4539-4389-87b9-abf11c69c02f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/choose-what-suits-you.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c203f37e2c213a854c4fded320f579248beb7205/msteams-platform%2Fget-started%2Fchoose-what-suits-you.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1f3cb11d-90c4-4201-a5f4-e5db1f8013be) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/get-started-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c203f37e2c213a854c4fded320f579248beb7205/msteams-platform%2Fget-started%2Fget-started-overview.md) | 90 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4bcf9938-0d87-4969-88ab-172fcc0b477c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview-solution.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c203f37e2c213a854c4fded320f579248beb7205/msteams-platform%2Foverview-solution.md) | 91 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e0226ae7-c1b9-4ff3-942d-35025ad48893) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c203f37e2c213a854c4fded320f579248beb7205/msteams-platform%2Foverview.md) | 96 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/18ef55cc-1297-4527-a24a-7b95dc817ead) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c203f37e2c213a854c4fded320f579248beb7205/msteams-platform%2Ftoolkit%2Ffaq.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/216c3d0b-1ff6-45ca-bbbc-0244f1e2965e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/install-Teams-Toolkit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c203f37e2c213a854c4fded320f579248beb7205/msteams-platform%2Ftoolkit%2Finstall-Teams-Toolkit.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c406d4ba-7eac-49ce-a999-b80378716348) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-05-22 22:11 UTC, girliemac submitted a review, later dismissed
LGTM 👍

2023-05-23 05:42 UTC, v-habibaumme submitted a review, later dismissed

2023-05-23 06:01 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/84956f89918f65f293bd3d8d56ed2094a208fc98/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f2be5c3b-4542-4fe6-b715-db12e82a949b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/build-basic-tab-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/84956f89918f65f293bd3d8d56ed2094a208fc98/msteams-platform%2Fget-started%2Fbuild-basic-tab-app.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1b5eaf3a-b187-4c2e-b8f4-03e2ee9e5b20) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/choose-what-suits-you.md](https://github.com/MicrosoftDocs/msteams-docs/blob/84956f89918f65f293bd3d8d56ed2094a208fc98/msteams-platform%2Fget-started%2Fchoose-what-suits-you.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f479daac-8dd8-4b92-b988-e88950b6a13f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/get-started-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/84956f89918f65f293bd3d8d56ed2094a208fc98/msteams-platform%2Fget-started%2Fget-started-overview.md) | 90 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e70655bc-eaa9-4209-9a3f-b5fd5f97eae4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview-solution.md](https://github.com/MicrosoftDocs/msteams-docs/blob/84956f89918f65f293bd3d8d56ed2094a208fc98/msteams-platform%2Foverview-solution.md) | 91 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f54a95d9-76e4-4195-80c7-cde40f869254) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/84956f89918f65f293bd3d8d56ed2094a208fc98/msteams-platform%2Foverview.md) | 96 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2f665e73-2b78-449e-b502-2ddbf6a15864) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/84956f89918f65f293bd3d8d56ed2094a208fc98/msteams-platform%2Ftoolkit%2Ffaq.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/73610db4-b4b3-4c2e-9ed7-ca2a8946cb55) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/install-Teams-Toolkit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/84956f89918f65f293bd3d8d56ed2094a208fc98/msteams-platform%2Ftoolkit%2Finstall-Teams-Toolkit.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1d18c81b-3e3d-4a91-9ec4-1edca7bb5973) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-05-23 06:11 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/3e29b3108ae32d92989900a36c40701f076bbe63/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/64fd82f8-801d-41af-a539-3cf6d776d336) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/build-basic-tab-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3e29b3108ae32d92989900a36c40701f076bbe63/msteams-platform%2Fget-started%2Fbuild-basic-tab-app.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5a80f0e8-3850-4c85-8c41-f3fd98759510) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/choose-what-suits-you.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3e29b3108ae32d92989900a36c40701f076bbe63/msteams-platform%2Fget-started%2Fchoose-what-suits-you.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/07c6c270-fcf2-47de-89c5-943960b1769b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/get-started-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3e29b3108ae32d92989900a36c40701f076bbe63/msteams-platform%2Fget-started%2Fget-started-overview.md) | 90 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5ddf75a5-cee4-4b8e-ada3-e696be33d050) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview-solution.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3e29b3108ae32d92989900a36c40701f076bbe63/msteams-platform%2Foverview-solution.md) | 91 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/975a22a5-2b82-4aff-9626-8a88d9635ae8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3e29b3108ae32d92989900a36c40701f076bbe63/msteams-platform%2Foverview.md) | 96 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a3d35c48-7712-4a6e-b0bf-6a1cc2abfca9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3e29b3108ae32d92989900a36c40701f076bbe63/msteams-platform%2Ftoolkit%2Ffaq.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/22211671-b293-4072-bca6-9ea289653d98) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/install-Teams-Toolkit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3e29b3108ae32d92989900a36c40701f076bbe63/msteams-platform%2Ftoolkit%2Finstall-Teams-Toolkit.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a1938e89-adcb-4a6e-94d9-494315613854) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-05-23 06:36 UTC, surbhigupta12 approved these changes

2023-05-23 06:37 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/658013ca785d75ccb05361f84f0f3f0f93b1983a/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9279ef74-5256-411b-a338-73a796f46aa3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/build-basic-tab-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/658013ca785d75ccb05361f84f0f3f0f93b1983a/msteams-platform%2Fget-started%2Fbuild-basic-tab-app.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2e4b6e44-345e-4eb8-a61b-484ee68f6fcb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/choose-what-suits-you.md](https://github.com/MicrosoftDocs/msteams-docs/blob/658013ca785d75ccb05361f84f0f3f0f93b1983a/msteams-platform%2Fget-started%2Fchoose-what-suits-you.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/81d737a7-449e-48b6-aa2f-d87092947d0c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/get-started-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/658013ca785d75ccb05361f84f0f3f0f93b1983a/msteams-platform%2Fget-started%2Fget-started-overview.md) | 90 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a84fedcb-7e56-46e9-a94c-217cd6315a44) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview-solution.md](https://github.com/MicrosoftDocs/msteams-docs/blob/658013ca785d75ccb05361f84f0f3f0f93b1983a/msteams-platform%2Foverview-solution.md) | 91 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b60197d4-897f-42ee-bce4-d9a4913206f4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/658013ca785d75ccb05361f84f0f3f0f93b1983a/msteams-platform%2Foverview.md) | 96 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d5b4c6a4-73e0-4f26-b4b7-d4ee4f75856c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/658013ca785d75ccb05361f84f0f3f0f93b1983a/msteams-platform%2Ftoolkit%2Ffaq.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c6b4f1c2-2940-4acb-b8c5-14e855de8bad) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/install-Teams-Toolkit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/658013ca785d75ccb05361f84f0f3f0f93b1983a/msteams-platform%2Ftoolkit%2Finstall-Teams-Toolkit.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/15c71bb0-d070-47e0-a090-241fb6ec9478) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-05-23 06:39 UTC, merged