[doc improvements] copy edits
MicrosoftDocs/msteams-docs pull request #8806
Opened 2023-06-07 23:05 UTC by lindalu-MSFT

Per [task 7913518 ](https://office.visualstudio.com/OC/_queries/edit/7913518/?triage=true)

2023-06-07 23:05 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/get-started/build-basic-tab-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7bf60bfd9d79a24fcb471ea367019589be9d67b6/msteams-platform%2Fget-started%2Fbuild-basic-tab-app.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8cb70dfc-396d-4289-b146-0f55b5949252) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/build-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7bf60bfd9d79a24fcb471ea367019589be9d67b6/msteams-platform%2Fget-started%2Fbuild-message-extension.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c8a75a64-220f-453f-97e4-541b9a727c3c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/build-notification-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7bf60bfd9d79a24fcb471ea367019589be9d67b6/msteams-platform%2Fget-started%2Fbuild-notification-bot.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a0973ac4-ef30-4c45-b412-7aa696028035) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/choose-what-suits-you.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7bf60bfd9d79a24fcb471ea367019589be9d67b6/msteams-platform%2Fget-started%2Fchoose-what-suits-you.md) | 98 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/169aaf3f-1d24-412a-a7ea-24cb405c306f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/get-started-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7bf60bfd9d79a24fcb471ea367019589be9d67b6/msteams-platform%2Fget-started%2Fget-started-overview.md) | 93 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4a3f5951-0418-4d0c-b5e0-7bd1ccac2f23) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/teams-toolkit-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7bf60bfd9d79a24fcb471ea367019589be9d67b6/msteams-platform%2Fget-started%2Fteams-toolkit-tutorial.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/95c714d1-4c62-4bb8-bf3e-fe07d86e4320) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-06-08 01:48 UTC, Rick-Kirkham submitted a review, later dismissed
One small spelling error. Approving.

2023-06-08 01:48 UTC, Rick-Kirkham commented on msteams-platform/get-started/choose-what-suits-you.md
> +1. **Recommended Tools**: Choose the tools based on the language that you've selected. You can also use teh Teams Developer Portal to manage and publish your app. The Teams Toolkit allows you to buil
```suggestion
1. **Recommended Tools**: Choose the tools based on the language that you've selected. You can also use the Teams Developer Portal to manage and publish your app. The Teams Toolkit allows you to build your app with JavaScript, TypeScript, or C# in Visual Studio Code (VS Code) or Visual Studio.
```

2023-06-08 21:52 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/get-started/build-basic-tab-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a3c83f16e404160fffbe1afd46131534c037b45b/msteams-platform%2Fget-started%2Fbuild-basic-tab-app.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/783789e4-b99e-4e51-a3a5-0d9d06b430b3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/build-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a3c83f16e404160fffbe1afd46131534c037b45b/msteams-platform%2Fget-started%2Fbuild-message-extension.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/292a152b-abd5-4eab-99b0-81a8ffa6ad88) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/build-notification-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a3c83f16e404160fffbe1afd46131534c037b45b/msteams-platform%2Fget-started%2Fbuild-notification-bot.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0f369e8e-bc92-4649-8a03-97fb6356b003) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/choose-what-suits-you.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a3c83f16e404160fffbe1afd46131534c037b45b/msteams-platform%2Fget-started%2Fchoose-what-suits-you.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/57c37107-1683-4030-9366-6b791e91d725) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/get-started-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a3c83f16e404160fffbe1afd46131534c037b45b/msteams-platform%2Fget-started%2Fget-started-overview.md) | 93 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/58bcc855-cf53-49d3-830e-3912a850a842) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/teams-toolkit-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a3c83f16e404160fffbe1afd46131534c037b45b/msteams-platform%2Fget-started%2Fteams-toolkit-tutorial.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/122ab711-54a9-4197-ae2f-b6aef08bee34) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-06-08 21:53 UTC, lindalu-MSFT commented
@Rick-Kirkham I committed the spelling fix (oops) but now it says I need you to approve it again.

2023-06-09 00:37 UTC, Rick-Kirkham approved these changes

2023-06-12 15:28 UTC, v-sdhakshina requested changes
@lindalu-MSFT,
Provided few suggestions, please review and update.

2023-06-12 15:28 UTC, v-sdhakshina commented on msteams-platform/get-started/choose-what-suits-you.md
> +1. **SDKs you need**: For example, if you're building AI capability for your bot app, you choose Teams AI library.
```suggestion
1. **SDKs you need**: For example, if you're building AI capability for your bot app, you select Teams AI library.
```

2023-06-12 16:50 UTC, surbhigupta12 commented
> @Rick-Kirkham Thanks! I don't have permissions to merge this to Main. Also, is there a sign-off process for this repo? Just wondering how it gets to prod. I also noticed several approved PRs in Main that haven't been merged to prod that a couple weeks old.

I'd merge the PR.

2023-06-19 19:52 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/get-started/build-basic-tab-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/188ab155ccd4f1e74677c95521db224ef6263ff4/msteams-platform%2Fget-started%2Fbuild-basic-tab-app.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2d5cbf55-809a-43ac-a8fe-b97bf5b28518) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/build-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/188ab155ccd4f1e74677c95521db224ef6263ff4/msteams-platform%2Fget-started%2Fbuild-message-extension.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cf8cf5c5-52ba-45e1-b44a-b3030433a1d7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/build-notification-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/188ab155ccd4f1e74677c95521db224ef6263ff4/msteams-platform%2Fget-started%2Fbuild-notification-bot.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e0a9eff8-653b-4fac-8d8a-b268ed90aa3d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/choose-what-suits-you.md](https://github.com/MicrosoftDocs/msteams-docs/blob/188ab155ccd4f1e74677c95521db224ef6263ff4/msteams-platform%2Fget-started%2Fchoose-what-suits-you.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0d16106d-a443-42ef-b838-116cf7fb03e7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/get-started-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/188ab155ccd4f1e74677c95521db224ef6263ff4/msteams-platform%2Fget-started%2Fget-started-overview.md) | 93 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/30372b9e-b57a-474e-9d22-61f64df66db6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/teams-toolkit-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/188ab155ccd4f1e74677c95521db224ef6263ff4/msteams-platform%2Fget-started%2Fteams-toolkit-tutorial.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6e1aaea1-0dbd-4816-a80f-92ac2f536cea) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-06-19 19:52 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/get-started/build-basic-tab-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d790f3171ce2b66b57cdc649f84e967c89398ca8/msteams-platform%2Fget-started%2Fbuild-basic-tab-app.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/99eac076-12b0-463a-bb10-d9bc9c9c8b4b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/build-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d790f3171ce2b66b57cdc649f84e967c89398ca8/msteams-platform%2Fget-started%2Fbuild-message-extension.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b2134a35-414d-4ce3-ab68-b70b6eed0539) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/build-notification-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d790f3171ce2b66b57cdc649f84e967c89398ca8/msteams-platform%2Fget-started%2Fbuild-notification-bot.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8130819a-262a-46f5-b62a-9f55996dac8e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/choose-what-suits-you.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d790f3171ce2b66b57cdc649f84e967c89398ca8/msteams-platform%2Fget-started%2Fchoose-what-suits-you.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/81efdbcf-3be8-4fbb-aabb-7212ce47710b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/get-started-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d790f3171ce2b66b57cdc649f84e967c89398ca8/msteams-platform%2Fget-started%2Fget-started-overview.md) | 93 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f1d6f57b-a4fe-4128-8148-1cb127eb2a51) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/teams-toolkit-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d790f3171ce2b66b57cdc649f84e967c89398ca8/msteams-platform%2Fget-started%2Fteams-toolkit-tutorial.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5185b5a6-2e9a-4645-bad7-98454c4327c0) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-06-19 19:53 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/get-started/build-basic-tab-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3c308af92338f08159f0fa87dcf26575e5d4e47a/msteams-platform%2Fget-started%2Fbuild-basic-tab-app.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b0d17832-57b7-4fdf-a738-25a7950ff772) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/build-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3c308af92338f08159f0fa87dcf26575e5d4e47a/msteams-platform%2Fget-started%2Fbuild-message-extension.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5dabb696-a08f-4cd9-80ed-d1ab671fe05a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/build-notification-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3c308af92338f08159f0fa87dcf26575e5d4e47a/msteams-platform%2Fget-started%2Fbuild-notification-bot.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0eb9d46c-32ae-43ea-b2e2-b6c87d72b7c4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/choose-what-suits-you.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3c308af92338f08159f0fa87dcf26575e5d4e47a/msteams-platform%2Fget-started%2Fchoose-what-suits-you.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/90e6e4c6-df56-4148-b294-20178946c4c2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/get-started-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3c308af92338f08159f0fa87dcf26575e5d4e47a/msteams-platform%2Fget-started%2Fget-started-overview.md) | 93 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c4bbbfd1-3179-4451-a414-ee9ef8a28f35) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/teams-toolkit-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3c308af92338f08159f0fa87dcf26575e5d4e47a/msteams-platform%2Fget-started%2Fteams-toolkit-tutorial.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ebe9e42c-86be-435b-b2b6-3b2109954f67) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-06-19 19:53 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/get-started/build-basic-tab-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/408f7ed25a2aa0f8c8f20f1a701f09a6d20b4de3/msteams-platform%2Fget-started%2Fbuild-basic-tab-app.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6396a9bd-eaaa-46a2-819c-c4d8f3fc606e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/build-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/408f7ed25a2aa0f8c8f20f1a701f09a6d20b4de3/msteams-platform%2Fget-started%2Fbuild-message-extension.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f928bcdd-c921-4185-8771-4f8bf0fba888) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/build-notification-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/408f7ed25a2aa0f8c8f20f1a701f09a6d20b4de3/msteams-platform%2Fget-started%2Fbuild-notification-bot.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/abc54c11-7806-467f-85a6-5c3bd9d36acf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/choose-what-suits-you.md](https://github.com/MicrosoftDocs/msteams-docs/blob/408f7ed25a2aa0f8c8f20f1a701f09a6d20b4de3/msteams-platform%2Fget-started%2Fchoose-what-suits-you.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/32e9d3a9-3739-4c7d-9f72-81444bc96ddf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/get-started-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/408f7ed25a2aa0f8c8f20f1a701f09a6d20b4de3/msteams-platform%2Fget-started%2Fget-started-overview.md) | 93 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/17103880-29f2-47a3-b7f1-bb17cb8d87f0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/teams-toolkit-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/408f7ed25a2aa0f8c8f20f1a701f09a6d20b4de3/msteams-platform%2Fget-started%2Fteams-toolkit-tutorial.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/76900b78-801f-4868-b675-b27066500e68) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-06-19 19:53 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/get-started/build-basic-tab-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7e687e94294837dbb0f7639e98fb29b07b6ea31c/msteams-platform%2Fget-started%2Fbuild-basic-tab-app.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5af8913e-6f82-467e-a144-1370e80df2ee) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/build-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7e687e94294837dbb0f7639e98fb29b07b6ea31c/msteams-platform%2Fget-started%2Fbuild-message-extension.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b62d5429-f5e3-4a37-94eb-c98d860f7344) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/build-notification-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7e687e94294837dbb0f7639e98fb29b07b6ea31c/msteams-platform%2Fget-started%2Fbuild-notification-bot.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ddf3671f-9276-43d2-ba1b-a5b464af08fa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/choose-what-suits-you.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7e687e94294837dbb0f7639e98fb29b07b6ea31c/msteams-platform%2Fget-started%2Fchoose-what-suits-you.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a03d6312-c19c-432d-abcf-5b6e3189d5d2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/get-started-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7e687e94294837dbb0f7639e98fb29b07b6ea31c/msteams-platform%2Fget-started%2Fget-started-overview.md) | 89 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3cabdb88-51c0-4acf-b861-931eff2a4a21) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/teams-toolkit-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7e687e94294837dbb0f7639e98fb29b07b6ea31c/msteams-platform%2Fget-started%2Fteams-toolkit-tutorial.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f2063492-67b4-49fa-a1ec-5ec14e020e4b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-06-19 19:53 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/get-started/build-basic-tab-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7e687e94294837dbb0f7639e98fb29b07b6ea31c/msteams-platform%2Fget-started%2Fbuild-basic-tab-app.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6edd6ffe-c1d0-43dd-a550-5035c7b8bb0a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/build-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7e687e94294837dbb0f7639e98fb29b07b6ea31c/msteams-platform%2Fget-started%2Fbuild-message-extension.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4c503419-fb06-4627-8124-37c32116ec8b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/build-notification-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7e687e94294837dbb0f7639e98fb29b07b6ea31c/msteams-platform%2Fget-started%2Fbuild-notification-bot.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/873e5d56-2fc1-4f24-a753-73bd2f2a6fef) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/choose-what-suits-you.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7e687e94294837dbb0f7639e98fb29b07b6ea31c/msteams-platform%2Fget-started%2Fchoose-what-suits-you.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/19f6963d-cd9a-4421-a273-aab08d2c6e25) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/get-started-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7e687e94294837dbb0f7639e98fb29b07b6ea31c/msteams-platform%2Fget-started%2Fget-started-overview.md) | 89 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/34ded3ba-f82b-414a-ab8d-6fd567d540b2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/teams-toolkit-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7e687e94294837dbb0f7639e98fb29b07b6ea31c/msteams-platform%2Fget-started%2Fteams-toolkit-tutorial.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a0c86139-b9f1-4885-93a6-a5eb6a54af73) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-06-19 19:53 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/get-started/build-basic-tab-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7ad9bce9332365e0223eabcaf190459bbf8e8064/msteams-platform%2Fget-started%2Fbuild-basic-tab-app.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/63405507-1897-4ea2-926f-61fa0e3043e6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/build-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7ad9bce9332365e0223eabcaf190459bbf8e8064/msteams-platform%2Fget-started%2Fbuild-message-extension.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7d50aba2-c366-47f8-bd0d-9da964b553a0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/build-notification-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7ad9bce9332365e0223eabcaf190459bbf8e8064/msteams-platform%2Fget-started%2Fbuild-notification-bot.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3b470345-2a36-44ae-88f1-bdaaeb22b269) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/choose-what-suits-you.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7ad9bce9332365e0223eabcaf190459bbf8e8064/msteams-platform%2Fget-started%2Fchoose-what-suits-you.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/833c617a-a538-453d-899b-d85d55aa4429) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/get-started-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7ad9bce9332365e0223eabcaf190459bbf8e8064/msteams-platform%2Fget-started%2Fget-started-overview.md) | 87 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/589dc341-7cae-4e7a-981d-7100729508d9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/teams-toolkit-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7ad9bce9332365e0223eabcaf190459bbf8e8064/msteams-platform%2Fget-started%2Fteams-toolkit-tutorial.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/087fd22b-dcac-48c0-a6a7-efd1c2763da2) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-06-19 19:54 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/get-started/build-basic-tab-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fca9489bc7f8b14dae7f44318d1fd0fd24a8f8b8/msteams-platform%2Fget-started%2Fbuild-basic-tab-app.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1de231bb-c17e-41f1-8f04-d7beec7fe576) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/build-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fca9489bc7f8b14dae7f44318d1fd0fd24a8f8b8/msteams-platform%2Fget-started%2Fbuild-message-extension.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/91394e42-b29c-45ab-a290-dcb1c144d9eb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/build-notification-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fca9489bc7f8b14dae7f44318d1fd0fd24a8f8b8/msteams-platform%2Fget-started%2Fbuild-notification-bot.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c91d81d8-8e14-4bb9-9a54-d0e56cf85d2b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/choose-what-suits-you.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fca9489bc7f8b14dae7f44318d1fd0fd24a8f8b8/msteams-platform%2Fget-started%2Fchoose-what-suits-you.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dcee0234-9526-4b57-843d-95a701e363d3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/get-started-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fca9489bc7f8b14dae7f44318d1fd0fd24a8f8b8/msteams-platform%2Fget-started%2Fget-started-overview.md) | 87 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e711a3fa-a339-4fd4-bcb9-c475776cb914) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/teams-toolkit-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fca9489bc7f8b14dae7f44318d1fd0fd24a8f8b8/msteams-platform%2Fget-started%2Fteams-toolkit-tutorial.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b96ed0df-fa26-49e0-9103-dfdaa8f9c6e0) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-06-19 19:55 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/get-started/build-basic-tab-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ddc8a70a36a5221bde71746991dfa3136bad5ef4/msteams-platform%2Fget-started%2Fbuild-basic-tab-app.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/74b6f2bc-d4e5-4e4c-a1eb-10cd4e804712) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/build-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ddc8a70a36a5221bde71746991dfa3136bad5ef4/msteams-platform%2Fget-started%2Fbuild-message-extension.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/565975b7-47c0-455c-b6b5-77bbc2dfa387) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/build-notification-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ddc8a70a36a5221bde71746991dfa3136bad5ef4/msteams-platform%2Fget-started%2Fbuild-notification-bot.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6cc9da6d-881c-4992-b7c4-f78fc9aaf7b9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/choose-what-suits-you.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ddc8a70a36a5221bde71746991dfa3136bad5ef4/msteams-platform%2Fget-started%2Fchoose-what-suits-you.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6cb61626-b6b1-4f6b-8ec2-ca14bbf207ab) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/get-started-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ddc8a70a36a5221bde71746991dfa3136bad5ef4/msteams-platform%2Fget-started%2Fget-started-overview.md) | 87 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c4064acf-1518-45d3-abdd-79eea5009607) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/teams-toolkit-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ddc8a70a36a5221bde71746991dfa3136bad5ef4/msteams-platform%2Fget-started%2Fteams-toolkit-tutorial.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6185477e-1dbf-436a-9ee9-354697aeeaa8) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-06-19 19:58 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/get-started/build-basic-tab-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d763de72a7a7011d58cec31327b8ffeceb5dfd2e/msteams-platform%2Fget-started%2Fbuild-basic-tab-app.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/78eeec4a-46b4-4603-b373-27e608dcdd11) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/build-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d763de72a7a7011d58cec31327b8ffeceb5dfd2e/msteams-platform%2Fget-started%2Fbuild-message-extension.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fd07bb70-05ef-4640-b2a0-1480d0cf1ae4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/build-notification-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d763de72a7a7011d58cec31327b8ffeceb5dfd2e/msteams-platform%2Fget-started%2Fbuild-notification-bot.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0ddb54f5-a3c1-4508-a7df-bf6b1b73624d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/choose-what-suits-you.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d763de72a7a7011d58cec31327b8ffeceb5dfd2e/msteams-platform%2Fget-started%2Fchoose-what-suits-you.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d6b02ef4-35eb-4f50-b3df-ba3f2efaa437) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/get-started-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d763de72a7a7011d58cec31327b8ffeceb5dfd2e/msteams-platform%2Fget-started%2Fget-started-overview.md) | 87 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/21142b2e-cd88-4615-b363-77c20f528c2b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/teams-toolkit-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d763de72a7a7011d58cec31327b8ffeceb5dfd2e/msteams-platform%2Fget-started%2Fteams-toolkit-tutorial.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c09cf226-aec7-4b4c-a2b8-419f0b97b478) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-06-19 19:59 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/get-started/build-basic-tab-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e50170416364915029ee6721017b6d7e5e03e72f/msteams-platform%2Fget-started%2Fbuild-basic-tab-app.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/756f7cec-9ff1-4dc2-9acc-d3ba1d16c49c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/build-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e50170416364915029ee6721017b6d7e5e03e72f/msteams-platform%2Fget-started%2Fbuild-message-extension.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/69e3e04d-f828-4d18-ba51-563c215d2b0d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/build-notification-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e50170416364915029ee6721017b6d7e5e03e72f/msteams-platform%2Fget-started%2Fbuild-notification-bot.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/54375f77-2b50-4220-a9f3-1ec01dbe197b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/choose-what-suits-you.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e50170416364915029ee6721017b6d7e5e03e72f/msteams-platform%2Fget-started%2Fchoose-what-suits-you.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/411c71d0-dfc8-4f1e-91ae-608dfc87df53) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/get-started-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e50170416364915029ee6721017b6d7e5e03e72f/msteams-platform%2Fget-started%2Fget-started-overview.md) | 87 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/775caf1e-2c98-4464-bd43-bd95b45b127b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/teams-toolkit-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e50170416364915029ee6721017b6d7e5e03e72f/msteams-platform%2Fget-started%2Fteams-toolkit-tutorial.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9eb6ebf2-a04a-4b5d-bf63-c89df03c269c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-06-19 19:59 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/get-started/build-basic-tab-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a469bcc4a760805d2d008ebdb5f19f813c0cf03e/msteams-platform%2Fget-started%2Fbuild-basic-tab-app.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1787044b-d3db-4737-b694-9bf3cfe94eef) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/build-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a469bcc4a760805d2d008ebdb5f19f813c0cf03e/msteams-platform%2Fget-started%2Fbuild-message-extension.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8685616e-15b5-4c1d-85c1-5d17b64d7a11) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/build-notification-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a469bcc4a760805d2d008ebdb5f19f813c0cf03e/msteams-platform%2Fget-started%2Fbuild-notification-bot.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b2da2989-9746-4e36-aa15-0c74efdfeb22) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/choose-what-suits-you.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a469bcc4a760805d2d008ebdb5f19f813c0cf03e/msteams-platform%2Fget-started%2Fchoose-what-suits-you.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/56d9fda5-14ed-4dc9-b2a8-f56e789da252) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/get-started-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a469bcc4a760805d2d008ebdb5f19f813c0cf03e/msteams-platform%2Fget-started%2Fget-started-overview.md) | 87 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f30c2257-e2f3-4eed-a264-a661ba82f9a9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/teams-toolkit-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a469bcc4a760805d2d008ebdb5f19f813c0cf03e/msteams-platform%2Fget-started%2Fteams-toolkit-tutorial.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fa20c8cf-a6bb-4ddf-8e12-b99815f9b152) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-06-19 19:59 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/get-started/build-basic-tab-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/093f56c9ad2673948aca4b71b4f7af8817681478/msteams-platform%2Fget-started%2Fbuild-basic-tab-app.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/520bb93b-f696-46ce-8a8a-e33d56ec2e28) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/build-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/093f56c9ad2673948aca4b71b4f7af8817681478/msteams-platform%2Fget-started%2Fbuild-message-extension.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/51ffa7f8-ef3c-488b-949d-06e630676f22) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/build-notification-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/093f56c9ad2673948aca4b71b4f7af8817681478/msteams-platform%2Fget-started%2Fbuild-notification-bot.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0e478a4f-772a-403e-960f-726c2cea088b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/choose-what-suits-you.md](https://github.com/MicrosoftDocs/msteams-docs/blob/093f56c9ad2673948aca4b71b4f7af8817681478/msteams-platform%2Fget-started%2Fchoose-what-suits-you.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0672ad2c-d61a-43ed-a8de-08e2014eab25) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/get-started-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/093f56c9ad2673948aca4b71b4f7af8817681478/msteams-platform%2Fget-started%2Fget-started-overview.md) | 87 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a7175bd5-b89f-494e-acc6-f718585cb199) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/teams-toolkit-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/093f56c9ad2673948aca4b71b4f7af8817681478/msteams-platform%2Fget-started%2Fteams-toolkit-tutorial.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a924fb27-5ae8-448b-8939-236b13070a2b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-06-19 20:00 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/get-started/build-basic-tab-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d548e15d64a963e00ac067fc53ce25a9c95b975e/msteams-platform%2Fget-started%2Fbuild-basic-tab-app.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5f8cb7ab-1aaa-4adc-8bcc-71dddc349c29) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/build-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d548e15d64a963e00ac067fc53ce25a9c95b975e/msteams-platform%2Fget-started%2Fbuild-message-extension.md) | 93 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/71463de5-c16a-4e4c-881c-23b09d24dbfe) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/build-notification-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d548e15d64a963e00ac067fc53ce25a9c95b975e/msteams-platform%2Fget-started%2Fbuild-notification-bot.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/59e3e4fa-9394-41f9-a6f7-15fc3c88e0ba) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/choose-what-suits-you.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d548e15d64a963e00ac067fc53ce25a9c95b975e/msteams-platform%2Fget-started%2Fchoose-what-suits-you.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/51118b84-8641-4545-9216-6702cb11d9c2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/get-started-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d548e15d64a963e00ac067fc53ce25a9c95b975e/msteams-platform%2Fget-started%2Fget-started-overview.md) | 87 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/eb3a17aa-0404-4b9a-9ec8-9f1d99a16a60) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/teams-toolkit-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d548e15d64a963e00ac067fc53ce25a9c95b975e/msteams-platform%2Fget-started%2Fteams-toolkit-tutorial.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3e6506f9-e1f6-488d-b3de-2100693b86e8) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-06-19 20:00 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/get-started/build-basic-tab-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/25abaf122fe1ad3b408915cc9177ee396d35c13a/msteams-platform%2Fget-started%2Fbuild-basic-tab-app.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5a17700e-6ee3-4f83-93be-6e6e22c2acdd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/build-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/25abaf122fe1ad3b408915cc9177ee396d35c13a/msteams-platform%2Fget-started%2Fbuild-message-extension.md) | 93 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/75377fec-1551-4a23-bab5-223a580b5469) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/build-notification-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/25abaf122fe1ad3b408915cc9177ee396d35c13a/msteams-platform%2Fget-started%2Fbuild-notification-bot.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c670de45-bfef-4386-8c6e-4a184d7706c1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/choose-what-suits-you.md](https://github.com/MicrosoftDocs/msteams-docs/blob/25abaf122fe1ad3b408915cc9177ee396d35c13a/msteams-platform%2Fget-started%2Fchoose-what-suits-you.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/37b8fa21-d94b-454a-9194-4a81ec34b14d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/get-started-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/25abaf122fe1ad3b408915cc9177ee396d35c13a/msteams-platform%2Fget-started%2Fget-started-overview.md) | 87 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/56bcabfc-ee39-4611-9113-f031ec087510) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/teams-toolkit-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/25abaf122fe1ad3b408915cc9177ee396d35c13a/msteams-platform%2Fget-started%2Fteams-toolkit-tutorial.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/36d50f01-3fd6-4c91-9293-937d3595ced4) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-06-19 20:01 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/get-started/build-basic-tab-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/32f427f11566cdff6c79bcf024b23f99d7bb34d4/msteams-platform%2Fget-started%2Fbuild-basic-tab-app.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2c82cd61-1738-4523-9ce5-c682cebce849) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/build-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/32f427f11566cdff6c79bcf024b23f99d7bb34d4/msteams-platform%2Fget-started%2Fbuild-message-extension.md) | 93 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2031a078-0100-4e92-bced-2aff66d5983c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/build-notification-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/32f427f11566cdff6c79bcf024b23f99d7bb34d4/msteams-platform%2Fget-started%2Fbuild-notification-bot.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/90998e04-8f90-4923-8254-30ecd054f73d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/choose-what-suits-you.md](https://github.com/MicrosoftDocs/msteams-docs/blob/32f427f11566cdff6c79bcf024b23f99d7bb34d4/msteams-platform%2Fget-started%2Fchoose-what-suits-you.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bfdb5f2f-edd3-44bc-ab45-7a8f93333abb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/get-started-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/32f427f11566cdff6c79bcf024b23f99d7bb34d4/msteams-platform%2Fget-started%2Fget-started-overview.md) | 87 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/abeb5d34-935a-46e2-b1ad-8c8b30570a6b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/teams-toolkit-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/32f427f11566cdff6c79bcf024b23f99d7bb34d4/msteams-platform%2Fget-started%2Fteams-toolkit-tutorial.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/90386b49-9c68-4f11-952d-4d5342c3eaa5) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-06-21 14:54 UTC, v-sdhakshina commented on msteams-platform/get-started/build-basic-tab-app.md
> +If a bot is what you're interested in, select the following button.
@lindalu-MSFT, request you to please update this comment.

2023-06-21 14:54 UTC, v-sdhakshina commented on msteams-platform/get-started/build-basic-tab-app.md
> +If you want to build a message extension app, select the following button.
@lindalu-MSFT, request you to please update this comment.

2023-06-21 14:56 UTC, v-sdhakshina commented on msteams-platform/get-started/build-message-extension.md
> +If a bot is what you are interested in, select the following button.
@lindalu-MSFT, request you to please update this comment.

2023-06-21 14:59 UTC, v-sdhakshina commented on msteams-platform/get-started/build-notification-bot.md
> +   The notification bot app sends a notification as an Adaptive Card to your Teams client.
@lindalu-MSFT, request you to please update this comment.

2023-06-21 15:00 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/get-started/build-basic-tab-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d86caed3721f10abc009d22919f06909553cf95c/msteams-platform%2Fget-started%2Fbuild-basic-tab-app.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5d12297f-3d4e-49e0-b44a-a7b6e4022511) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/build-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d86caed3721f10abc009d22919f06909553cf95c/msteams-platform%2Fget-started%2Fbuild-message-extension.md) | 93 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9581d8df-af7b-4913-98b3-e6590667135f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/build-notification-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d86caed3721f10abc009d22919f06909553cf95c/msteams-platform%2Fget-started%2Fbuild-notification-bot.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5084de4f-e2e6-45b5-a245-543646006678) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/choose-what-suits-you.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d86caed3721f10abc009d22919f06909553cf95c/msteams-platform%2Fget-started%2Fchoose-what-suits-you.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2406b85a-5ba9-48b8-806d-83438bd15cea) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/get-started-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d86caed3721f10abc009d22919f06909553cf95c/msteams-platform%2Fget-started%2Fget-started-overview.md) | 87 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fdab3a5c-cdae-43b5-a441-fc6bd2807598) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/teams-toolkit-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d86caed3721f10abc009d22919f06909553cf95c/msteams-platform%2Fget-started%2Fteams-toolkit-tutorial.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f6153fcb-848d-4561-bd29-a21b06c373dc) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-06-21 15:10 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/get-started/build-basic-tab-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/65ea01278d95db879e81fd408180d7d405c0de1f/msteams-platform%2Fget-started%2Fbuild-basic-tab-app.md) | 91 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ac460aac-efe9-4a5e-af8e-1ea54a89628b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/build-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/65ea01278d95db879e81fd408180d7d405c0de1f/msteams-platform%2Fget-started%2Fbuild-message-extension.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c721e717-a185-4f13-b57b-25d304ba457d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/build-notification-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/65ea01278d95db879e81fd408180d7d405c0de1f/msteams-platform%2Fget-started%2Fbuild-notification-bot.md) | 91 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e15c0b9d-df58-4920-8d73-05aede87711c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/choose-what-suits-you.md](https://github.com/MicrosoftDocs/msteams-docs/blob/65ea01278d95db879e81fd408180d7d405c0de1f/msteams-platform%2Fget-started%2Fchoose-what-suits-you.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6087581e-40ec-4030-8fbb-2c443bdcc024) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/get-started-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/65ea01278d95db879e81fd408180d7d405c0de1f/msteams-platform%2Fget-started%2Fget-started-overview.md) | 87 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c2e0942b-4296-4e9a-ae1e-f3ab255387c1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/teams-toolkit-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/65ea01278d95db879e81fd408180d7d405c0de1f/msteams-platform%2Fget-started%2Fteams-toolkit-tutorial.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/314b9d37-2acb-4f96-85c9-455018d32e26) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-06-21 15:39 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/get-started/build-basic-tab-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9473f33ce3812dfd56941f66363fa4b8d0127481/msteams-platform%2Fget-started%2Fbuild-basic-tab-app.md) | 91 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/456b867d-f0d9-4820-9978-8b9abc5c8a28) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/build-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9473f33ce3812dfd56941f66363fa4b8d0127481/msteams-platform%2Fget-started%2Fbuild-message-extension.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ccab23a9-9239-4e7a-8b7e-8fcc664545b0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/build-notification-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9473f33ce3812dfd56941f66363fa4b8d0127481/msteams-platform%2Fget-started%2Fbuild-notification-bot.md) | 91 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7516ee68-e60e-4ac6-86ea-b9404f6c6614) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/choose-what-suits-you.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9473f33ce3812dfd56941f66363fa4b8d0127481/msteams-platform%2Fget-started%2Fchoose-what-suits-you.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5bb0c07b-c01f-4e8f-bcd3-45ee3d5171a1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/get-started-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9473f33ce3812dfd56941f66363fa4b8d0127481/msteams-platform%2Fget-started%2Fget-started-overview.md) | 87 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5647757a-e1f3-4cd3-bc9a-c27373a6f563) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/teams-toolkit-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9473f33ce3812dfd56941f66363fa4b8d0127481/msteams-platform%2Fget-started%2Fteams-toolkit-tutorial.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1d047c44-8386-4f4d-bbbd-a84250b3f33b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-06-21 15:45 UTC, v-sdhakshina approved these changes

2023-06-21 15:49 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/get-started/build-basic-tab-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/330506660756cbeeac61c04bbdc9403c7aa95b81/msteams-platform%2Fget-started%2Fbuild-basic-tab-app.md) | 91 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/27a30b9b-5dda-45c3-96dd-6bbc8b8a9991) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/build-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/330506660756cbeeac61c04bbdc9403c7aa95b81/msteams-platform%2Fget-started%2Fbuild-message-extension.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8b1bd2af-4269-4657-a52b-91694b5a0e76) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/build-notification-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/330506660756cbeeac61c04bbdc9403c7aa95b81/msteams-platform%2Fget-started%2Fbuild-notification-bot.md) | 91 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4ea0f8f2-95c6-4bb9-9799-4d46d3d7ce9c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/choose-what-suits-you.md](https://github.com/MicrosoftDocs/msteams-docs/blob/330506660756cbeeac61c04bbdc9403c7aa95b81/msteams-platform%2Fget-started%2Fchoose-what-suits-you.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/26a6e78f-75eb-4fae-9d07-95d90709a714) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/get-started-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/330506660756cbeeac61c04bbdc9403c7aa95b81/msteams-platform%2Fget-started%2Fget-started-overview.md) | 87 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b2a2f084-b5a0-47b8-a4cf-e196a46177b3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/teams-toolkit-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/330506660756cbeeac61c04bbdc9403c7aa95b81/msteams-platform%2Fget-started%2Fteams-toolkit-tutorial.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f73ad62e-eaed-42bf-ae72-4ade1cfc2321) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-06-21 15:52 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/get-started/build-basic-tab-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/648b32524a0c9ad2ab416cc5760ed7e60316987d/msteams-platform%2Fget-started%2Fbuild-basic-tab-app.md) | 91 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6dcc24ad-1983-400e-a413-f26d81e35fe0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/build-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/648b32524a0c9ad2ab416cc5760ed7e60316987d/msteams-platform%2Fget-started%2Fbuild-message-extension.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ffb4cbf5-9acc-4f87-b85c-4470e07ff525) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/build-notification-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/648b32524a0c9ad2ab416cc5760ed7e60316987d/msteams-platform%2Fget-started%2Fbuild-notification-bot.md) | 91 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e84e7890-820b-4556-b5b5-173af50187a4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/choose-what-suits-you.md](https://github.com/MicrosoftDocs/msteams-docs/blob/648b32524a0c9ad2ab416cc5760ed7e60316987d/msteams-platform%2Fget-started%2Fchoose-what-suits-you.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8c218341-825b-423c-a1c0-edb55e8563c6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/get-started-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/648b32524a0c9ad2ab416cc5760ed7e60316987d/msteams-platform%2Fget-started%2Fget-started-overview.md) | 87 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dff008ea-7e07-419d-8d5b-00d648707586) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/teams-toolkit-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/648b32524a0c9ad2ab416cc5760ed7e60316987d/msteams-platform%2Fget-started%2Fteams-toolkit-tutorial.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/452f61f0-7726-4ae2-946b-38ac77564a6b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-06-21 15:57 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/get-started/build-basic-tab-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/17e981389a6ff59ac2a74a0db16be059f8fa83c2/msteams-platform%2Fget-started%2Fbuild-basic-tab-app.md) | 91 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7ffe76ff-db82-4a7a-bde0-f989da21dea1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/build-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/17e981389a6ff59ac2a74a0db16be059f8fa83c2/msteams-platform%2Fget-started%2Fbuild-message-extension.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/703a4c8a-3eca-478e-a32c-6da65f63d731) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/build-notification-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/17e981389a6ff59ac2a74a0db16be059f8fa83c2/msteams-platform%2Fget-started%2Fbuild-notification-bot.md) | 91 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/30a17ea1-4bac-40dc-9879-b771b4baab7a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/choose-what-suits-you.md](https://github.com/MicrosoftDocs/msteams-docs/blob/17e981389a6ff59ac2a74a0db16be059f8fa83c2/msteams-platform%2Fget-started%2Fchoose-what-suits-you.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e6d424a7-e49f-44d6-8542-9cdd053763fc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/get-started-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/17e981389a6ff59ac2a74a0db16be059f8fa83c2/msteams-platform%2Fget-started%2Fget-started-overview.md) | 87 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3fd198d3-c349-4bf5-bb10-53dc05d4e419) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/teams-toolkit-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/17e981389a6ff59ac2a74a0db16be059f8fa83c2/msteams-platform%2Fget-started%2Fteams-toolkit-tutorial.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b078f6ec-2506-4484-a8e0-a4da40da5f11) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-06-21 16:02 UTC, surbhigupta12 commented
Thanks for your review @lindalu-MSFT. We're merging this PR.

2023-06-21 16:02 UTC, surbhigupta12 approved these changes

2023-06-21 16:02 UTC, merged