[Doc Improvement][Revamp Monetize your app][3142830]
MicrosoftDocs/msteams-docs pull request #8990
Opened 2023-07-06 08:14 UTC by v-preethah

2023-07-06 08:14 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/103bb74195518f2713bc868cfd0edb962b96ffc6/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 94 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2974fa20-c9d1-4ade-ad55-7b4f83fbde7b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/103bb74195518f2713bc868cfd0edb962b96ffc6/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 94 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f50e7557-2665-4ce6-a453-281d35d56a3c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-07-06 12:25 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fd47cc225f5824c746b08606e9aa64b3828d6b47/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 89 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8711b0e0-0880-493b-8727-686c52b51e43) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fd47cc225f5824c746b08606e9aa64b3828d6b47/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 89 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5e75b994-16fb-4e29-8655-e3b9a4a87ae5) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-07-07 04:57 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e63367bc60bcc2fe6cae0b82ae745c3c5cde96e4/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 89 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d7def946-f83d-473d-aee6-bb6c5831ee88) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e63367bc60bcc2fe6cae0b82ae745c3c5cde96e4/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 89 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9b4c64c0-5d9e-4cac-8f4c-3fc6e7b8660c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-07-07 10:49 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a613346b57430acce1fb301a62d47606f158f147/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e3517e7b-5859-48e2-93b9-7cbb12aafdd6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a613346b57430acce1fb301a62d47606f158f147/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 94 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/75133bbf-1f3c-4c5e-becb-acdbadcf0fad) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a613346b57430acce1fb301a62d47606f158f147/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 92 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ca83f670-f810-4e85-ab74-29aa79970b1b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a613346b57430acce1fb301a62d47606f158f147/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 87 | 48 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5ffc6611-5d89-4592-808e-6c698342ccac) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a613346b57430acce1fb301a62d47606f158f147/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 93 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7b659651-9665-4222-8340-02891ece43b0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a613346b57430acce1fb301a62d47606f158f147/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e7734522-073f-4bae-a9cc-345de78b2380) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-07-07 11:12 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e86f014347db7f0639cb1b23059d871e36f54ad7/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8bad37f7-3aaa-45aa-b2c7-be8d762f1400) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e86f014347db7f0639cb1b23059d871e36f54ad7/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/716af011-3c84-4f31-a204-03e5acf4e780) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e86f014347db7f0639cb1b23059d871e36f54ad7/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 92 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/555ad114-71ae-4793-9910-f2b01973767c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e86f014347db7f0639cb1b23059d871e36f54ad7/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 87 | 48 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8bcee694-6f43-40c9-b10c-913cb6a12ab0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e86f014347db7f0639cb1b23059d871e36f54ad7/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 93 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/015bfab2-90ee-48ff-9a9c-ba84c9be7f40) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e86f014347db7f0639cb1b23059d871e36f54ad7/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b4cf8237-9b7a-40ac-a368-476f13b2e0fd) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-07-07 12:26 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ba48a7b14060765cbbb4529cf0ae7293fe43d905/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5f395f1b-7604-4757-9626-f11b8b794f40) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ba48a7b14060765cbbb4529cf0ae7293fe43d905/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 96 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5042119d-8ceb-471d-b9eb-48e150107c96) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ba48a7b14060765cbbb4529cf0ae7293fe43d905/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 90 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/56b0a24c-e218-4d3a-baf3-a3b86fb72c11) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ba48a7b14060765cbbb4529cf0ae7293fe43d905/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 84 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/73019df8-3fb9-47dd-8c8f-0048abfcbc40) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ba48a7b14060765cbbb4529cf0ae7293fe43d905/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 91 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d016bc56-135e-449f-8c17-0caddd357a67) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ba48a7b14060765cbbb4529cf0ae7293fe43d905/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bd068d8b-bf67-4996-a20e-fc6f9425431f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-07-10 04:42 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e0b4a7bdd1c578f5a417a10b0ec7760bd14c8d90/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/43421a5f-b9b9-4023-abe4-46948f53690d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e0b4a7bdd1c578f5a417a10b0ec7760bd14c8d90/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 96 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d7a8776b-00b9-45ec-b260-3129057866f5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e0b4a7bdd1c578f5a417a10b0ec7760bd14c8d90/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 90 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f89137d9-f3b1-43fe-8f98-ed3fb54372be) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e0b4a7bdd1c578f5a417a10b0ec7760bd14c8d90/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 84 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fa3557ea-6cb6-41ba-9870-4b6bb8cd8ae5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e0b4a7bdd1c578f5a417a10b0ec7760bd14c8d90/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 91 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/03488650-423c-48ec-add3-2d1ac3e85a8d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e0b4a7bdd1c578f5a417a10b0ec7760bd14c8d90/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/41544c36-01a3-4799-bb4b-7ba2799fbf9d) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-07-11 05:23 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/3e8bcfba0ec3aebface4bc35a568983083b7bfcc/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a512059a-a741-49b4-a2aa-dcbe785a77cf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3e8bcfba0ec3aebface4bc35a568983083b7bfcc/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4394810e-e68c-43fa-badd-5a1dbd2b7181) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3e8bcfba0ec3aebface4bc35a568983083b7bfcc/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 97 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b479ff58-f852-4027-be06-d7421602e8a5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3e8bcfba0ec3aebface4bc35a568983083b7bfcc/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 93 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1b549022-c825-4d3c-8cc3-8e700e312046) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3e8bcfba0ec3aebface4bc35a568983083b7bfcc/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 88 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/90de5534-8c23-4c2b-8ef5-7e2a4fba71ac) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3e8bcfba0ec3aebface4bc35a568983083b7bfcc/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/734fd981-cee7-498d-86e6-32d79f8cfae7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3e8bcfba0ec3aebface4bc35a568983083b7bfcc/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9f4c3ecd-2e64-47d7-83d1-8d943db2ebe6) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-07-11 05:42 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e72345c70af17049504d4b0eaeead3ae60eb7187/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b569cd2d-0159-44fa-8f3d-958c08cfd7c3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e72345c70af17049504d4b0eaeead3ae60eb7187/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4cd9e949-5672-4e3f-a436-5662a7713ef1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e72345c70af17049504d4b0eaeead3ae60eb7187/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 89 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3ce41cb8-1666-410e-b301-27fb6380e2f2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e72345c70af17049504d4b0eaeead3ae60eb7187/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 97 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/44a3cd20-8f33-40f9-a3e7-aaa5cff3e98f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e72345c70af17049504d4b0eaeead3ae60eb7187/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 93 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/75d3c8dc-bb03-4a3e-8e08-4a33fd4d0a80) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e72345c70af17049504d4b0eaeead3ae60eb7187/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 88 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/53f64bce-d540-40a5-b1ff-6af1c21d4fb4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e72345c70af17049504d4b0eaeead3ae60eb7187/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5f7db96a-f44d-48d5-acd3-c6c81b63555b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e72345c70af17049504d4b0eaeead3ae60eb7187/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ad40b830-71df-4df3-bc2d-37f8a11543ee) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e72345c70af17049504d4b0eaeead3ae60eb7187/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 86 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b48fa00a-419a-4975-80e4-22dd37e04826) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e72345c70af17049504d4b0eaeead3ae60eb7187/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 97 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/08945bc7-b92a-4e5b-ac5a-532b06ef9279) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-07-11 05:44 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/0dc978ed3912086b6c9647a69e1058282e0727fe/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8ea3d699-4683-4500-8429-08e41f3c3025) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0dc978ed3912086b6c9647a69e1058282e0727fe/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/68b9d7bb-7b78-485a-88f7-5321ed1395d5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0dc978ed3912086b6c9647a69e1058282e0727fe/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 89 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/60603faf-77fa-4c9f-8a0f-f403c38018c7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0dc978ed3912086b6c9647a69e1058282e0727fe/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 97 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1388e99c-2442-4df2-b397-f5b4a9a17b0f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0dc978ed3912086b6c9647a69e1058282e0727fe/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 93 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f4f11441-8074-4632-a24f-0c9f4d892560) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0dc978ed3912086b6c9647a69e1058282e0727fe/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 88 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/65eb092f-df14-42bf-a104-26def9337b3e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0dc978ed3912086b6c9647a69e1058282e0727fe/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e54aaf6c-18e7-4564-aab6-ff177c8efa47) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0dc978ed3912086b6c9647a69e1058282e0727fe/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c6bc079a-5fef-40d4-8722-ea572c792d51) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0dc978ed3912086b6c9647a69e1058282e0727fe/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 86 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7d766b1e-86a0-42e7-b5d3-a3ae1d09be52) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0dc978ed3912086b6c9647a69e1058282e0727fe/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 97 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b8d32da6-c8a6-43f0-9ce2-de3fece7ead8) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-07-11 05:51 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/7cac4d7db2db2ec83fb81121b96a4f5f5d88eebe/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a8a08cc9-d7e8-4948-996f-79f1d4853c61) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7cac4d7db2db2ec83fb81121b96a4f5f5d88eebe/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0b48427f-d698-4dec-b208-e718f1336f5e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7cac4d7db2db2ec83fb81121b96a4f5f5d88eebe/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 89 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2240b21e-5285-4918-924a-5ab1aba964eb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7cac4d7db2db2ec83fb81121b96a4f5f5d88eebe/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 97 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/61beb61a-fbd5-4f82-b840-936c55902bf2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7cac4d7db2db2ec83fb81121b96a4f5f5d88eebe/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 93 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/369f4927-a565-4216-aaa8-147250259f33) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7cac4d7db2db2ec83fb81121b96a4f5f5d88eebe/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 88 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cd51c324-e7f9-4663-8568-3c235f9c47ab) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7cac4d7db2db2ec83fb81121b96a4f5f5d88eebe/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/878b76b1-b587-4be6-ab18-4963cf9322c5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7cac4d7db2db2ec83fb81121b96a4f5f5d88eebe/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3c4a4978-df66-48ab-9be4-ad1042998e7c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7cac4d7db2db2ec83fb81121b96a4f5f5d88eebe/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 87 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ed938bfe-fcbe-4796-b78f-1168f0135827) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7cac4d7db2db2ec83fb81121b96a4f5f5d88eebe/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 97 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3d0219b5-a3c3-4566-89f1-066730569d81) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-07-11 11:36 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/7fdbbe8f00026e486ee613e2de694e7fb31890fa/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/31fdfb6f-3104-466a-af89-7db454813499) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7fdbbe8f00026e486ee613e2de694e7fb31890fa/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bcc8a1b5-d331-4e0e-9586-c3fc4af997ad) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7fdbbe8f00026e486ee613e2de694e7fb31890fa/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 89 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dc349125-4ed6-498c-8505-bda96fd32a0c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7fdbbe8f00026e486ee613e2de694e7fb31890fa/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 97 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7949fae9-74bc-42d6-9958-72b1b0f2cf3f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7fdbbe8f00026e486ee613e2de694e7fb31890fa/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 93 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/941b0cf4-1e83-4bc7-b28e-1b638a6d676d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7fdbbe8f00026e486ee613e2de694e7fb31890fa/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 88 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/252de038-0af2-4426-bfa8-f49ca3088e79) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7fdbbe8f00026e486ee613e2de694e7fb31890fa/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5e30e01c-44e5-4d4e-a3bb-b96ef83f6a08) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7fdbbe8f00026e486ee613e2de694e7fb31890fa/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 90 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6f7ad59e-a211-46a4-a32c-2bc00f53637d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7fdbbe8f00026e486ee613e2de694e7fb31890fa/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 88 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/eedb7581-cb65-467d-addb-a487ae04572f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7fdbbe8f00026e486ee613e2de694e7fb31890fa/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 97 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cb47f429-1512-4de4-88cc-52c63c8f4072) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-07-11 11:41 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/248f8c95e5b380a96c0178c025908fa4ef310ad3/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6fbefcc4-f5c7-4e0e-a71e-ef3acd393430) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/248f8c95e5b380a96c0178c025908fa4ef310ad3/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c5a0b54a-d3ee-4e5d-aff6-01668164c165) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/248f8c95e5b380a96c0178c025908fa4ef310ad3/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 89 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2b9ddc9b-2db3-46a2-b4b5-6d7fe224b2de) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/248f8c95e5b380a96c0178c025908fa4ef310ad3/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 97 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4107dfc4-dee0-4c2c-b4cf-19ab57869fb8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/248f8c95e5b380a96c0178c025908fa4ef310ad3/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 93 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6150bad8-a65b-421f-82be-926696361a16) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/248f8c95e5b380a96c0178c025908fa4ef310ad3/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 88 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aa3cff2d-7290-4904-bec2-13d2c4592ce9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/248f8c95e5b380a96c0178c025908fa4ef310ad3/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a42de9bd-7d4a-4eb4-abe8-fd0045879c30) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/248f8c95e5b380a96c0178c025908fa4ef310ad3/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 90 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4eb0cd32-232e-432d-9ff7-cb7cba5d201e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/248f8c95e5b380a96c0178c025908fa4ef310ad3/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 88 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e7e9f4b2-d41f-4f3a-853f-e3fe77639c64) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/248f8c95e5b380a96c0178c025908fa4ef310ad3/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 97 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c63e3475-a471-4c37-9ad0-49cdd6be4962) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-07-12 07:33 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/dc5ed8f93bb11e9c90faa610be30d8202dedaf01/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b4741939-b117-40e7-b442-498d745b7bfc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dc5ed8f93bb11e9c90faa610be30d8202dedaf01/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/92324613-9da3-4ca7-aacc-0e81514d4438) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dc5ed8f93bb11e9c90faa610be30d8202dedaf01/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 89 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/03f2db4a-7753-471f-b188-60c0ba9eca13) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dc5ed8f93bb11e9c90faa610be30d8202dedaf01/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 97 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/25ff5838-d4cc-4aa5-bd14-5f75ebe0562c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dc5ed8f93bb11e9c90faa610be30d8202dedaf01/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 93 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4f9e537a-b49f-467a-bf1f-b26f99f0c32a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dc5ed8f93bb11e9c90faa610be30d8202dedaf01/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 88 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7e09de1a-47d7-4e10-ad3d-30efa19a6f50) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dc5ed8f93bb11e9c90faa610be30d8202dedaf01/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8ce61f61-b9bb-4aae-88fe-d57be4f6077f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dc5ed8f93bb11e9c90faa610be30d8202dedaf01/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 90 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ea1fe6eb-9021-4939-9dee-e8342949ec47) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dc5ed8f93bb11e9c90faa610be30d8202dedaf01/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 88 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f1fd8830-c218-4235-9310-9cdffc18d975) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dc5ed8f93bb11e9c90faa610be30d8202dedaf01/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 97 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/53ffe926-dee1-42ac-8a2b-fb157c1321d3) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-07-12 08:43 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a3ba6bc816d2c25374aef4413217fab0b7b26e8b/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/42dc772c-4be9-463d-bf8e-48fd3918848e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a3ba6bc816d2c25374aef4413217fab0b7b26e8b/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8f47928b-727d-479c-a523-80aa1ba061e2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a3ba6bc816d2c25374aef4413217fab0b7b26e8b/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 89 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b5dc8dd5-c726-45e3-a457-5f46ba2f2040) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a3ba6bc816d2c25374aef4413217fab0b7b26e8b/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 97 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8fc96f00-08d0-4bb8-b320-d22497b6e85f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a3ba6bc816d2c25374aef4413217fab0b7b26e8b/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 93 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/97c11897-3e3e-46bc-bb0c-b40a45f3c1c0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a3ba6bc816d2c25374aef4413217fab0b7b26e8b/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 88 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/599efd4e-5e88-4553-b751-f1d8829fdaf2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a3ba6bc816d2c25374aef4413217fab0b7b26e8b/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3b446f2e-1cde-4a8a-8cf6-f8ec0cb0521f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a3ba6bc816d2c25374aef4413217fab0b7b26e8b/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f64138e0-492a-4425-904c-daafcc2381d0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a3ba6bc816d2c25374aef4413217fab0b7b26e8b/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 88 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7658d8ff-e536-487e-a478-5cfa836c02a2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a3ba6bc816d2c25374aef4413217fab0b7b26e8b/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 97 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d882ea68-95fe-43c2-a9ac-794d28c4b6dd) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-07-12 15:02 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/f64544ee9af36663716b641f6906346bd6076aa1/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d18b9079-aa09-49ec-bfa7-36bb2711dee3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f64544ee9af36663716b641f6906346bd6076aa1/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/90ce49f5-192e-4654-bb9b-a049a37a02a7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f64544ee9af36663716b641f6906346bd6076aa1/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 90 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/eb35f1e1-c156-4e50-a6d3-ffda722b72a6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f64544ee9af36663716b641f6906346bd6076aa1/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 97 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d42285f2-36e7-4b67-be61-012a899f2317) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f64544ee9af36663716b641f6906346bd6076aa1/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 93 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/34fd67bd-9454-4dd9-b2ae-e60ff46a1cc5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f64544ee9af36663716b641f6906346bd6076aa1/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 88 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d00b5419-15bc-4aa3-9b34-b1b29065ba7d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f64544ee9af36663716b641f6906346bd6076aa1/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 91 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5d3ddc45-0f4e-4ffa-8079-aa44266bc9ad) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f64544ee9af36663716b641f6906346bd6076aa1/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/da86ea8d-ab98-499a-aa3b-841a290a9b2d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f64544ee9af36663716b641f6906346bd6076aa1/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 88 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a2677cdb-5291-467f-a690-bcce70bd5aa9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f64544ee9af36663716b641f6906346bd6076aa1/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 93 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f277fa26-dda1-4b8c-a09b-38f7d08b096c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-07-14 11:56 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/7564f918fe4852eb8798f8e2daba8e564fc21b13/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/259f79d0-f2e0-42cf-9d3b-fe30cfbe6cf7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7564f918fe4852eb8798f8e2daba8e564fc21b13/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d515530a-367d-4395-9834-3a69f02003ef) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7564f918fe4852eb8798f8e2daba8e564fc21b13/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 90 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/af1b96cf-aa67-4c31-ad5a-f232fadf1340) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7564f918fe4852eb8798f8e2daba8e564fc21b13/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 97 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/342b9d90-7ce0-42a4-baf3-710e149b441b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7564f918fe4852eb8798f8e2daba8e564fc21b13/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 93 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7dba45a5-8996-4015-867f-c84aa95219fd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7564f918fe4852eb8798f8e2daba8e564fc21b13/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 88 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bd54de80-9203-4454-80cc-234b1d38c5b0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7564f918fe4852eb8798f8e2daba8e564fc21b13/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 91 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d4d9407b-e211-4025-a093-be4958c35c4e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7564f918fe4852eb8798f8e2daba8e564fc21b13/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/644479ea-06b0-4051-96ef-00c85b66bb60) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7564f918fe4852eb8798f8e2daba8e564fc21b13/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 88 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/72d74462-5471-4957-ab36-a18922d486a2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7564f918fe4852eb8798f8e2daba8e564fc21b13/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 93 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6a3183db-361d-4f56-b21d-5b8ea0a88e99) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-07-14 13:19 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/7911689d32cf70f5bb656dae69069974a7e98bcc/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9babd971-753d-4eaa-ae89-dd16719ce0fd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7911689d32cf70f5bb656dae69069974a7e98bcc/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a386c824-0bde-4cd8-ac81-5f1d3d2c2b38) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7911689d32cf70f5bb656dae69069974a7e98bcc/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 90 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2680889f-5480-4128-a026-3dca422069a2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7911689d32cf70f5bb656dae69069974a7e98bcc/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 97 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/37002b0c-6b16-4fd5-8b22-2b20d6948de6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7911689d32cf70f5bb656dae69069974a7e98bcc/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 93 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/54289215-4f83-4659-a3c9-a3f6c3277a05) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7911689d32cf70f5bb656dae69069974a7e98bcc/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2a75da52-2e90-4524-ac75-6858a364a864) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7911689d32cf70f5bb656dae69069974a7e98bcc/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 91 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9b0fbfa3-d614-485c-b7f2-78a4fc367795) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7911689d32cf70f5bb656dae69069974a7e98bcc/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/05790961-e08f-49f6-a49d-d63d0f21a8d4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7911689d32cf70f5bb656dae69069974a7e98bcc/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 88 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a5b0cbe3-1337-4a18-ac28-06956b4ce871) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7911689d32cf70f5bb656dae69069974a7e98bcc/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 93 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/09d6a64e-5305-4ff2-8de8-f31c49e4ab3e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-07-17 12:24 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/5e464141222dc5ea53d109baeba9cb210c7a37b8/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5354ab89-06b7-4e04-a045-f2a5a451a458) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5e464141222dc5ea53d109baeba9cb210c7a37b8/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e596a9c4-bfe9-4be1-b034-a3b924028e9b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5e464141222dc5ea53d109baeba9cb210c7a37b8/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 89 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e351e22c-9db7-4f50-bb51-b6d54af00442) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5e464141222dc5ea53d109baeba9cb210c7a37b8/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 97 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bb78b226-11d8-4a6a-a2c0-2dc2dc48f375) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5e464141222dc5ea53d109baeba9cb210c7a37b8/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 93 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/605b7b94-fd9b-4932-9738-b6a328ccfb08) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5e464141222dc5ea53d109baeba9cb210c7a37b8/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 87 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4d382c36-4c76-4dbe-9e31-c3d0ed6828bd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5e464141222dc5ea53d109baeba9cb210c7a37b8/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 91 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3f98acb0-e136-4ab8-bcf6-73c79a78c938) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5e464141222dc5ea53d109baeba9cb210c7a37b8/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 92 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/23b527ee-468f-4ed6-8099-134426bf322e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5e464141222dc5ea53d109baeba9cb210c7a37b8/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 88 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/debcde5c-a2c7-4f4f-95dd-a9a962730ba9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5e464141222dc5ea53d109baeba9cb210c7a37b8/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 93 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/21c4414a-7e9d-4d09-bcb1-fab4746f78c1) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-07-19 04:59 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1733379bb2fb6f7e6ebacf5f642d5083b2cd5f0d/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1fdda9ac-6cb3-4637-870e-c103e8f66983) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1733379bb2fb6f7e6ebacf5f642d5083b2cd5f0d/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/09bf2965-bf22-40c9-a4e2-141c3897c0ef) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1733379bb2fb6f7e6ebacf5f642d5083b2cd5f0d/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 89 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bd52bca4-f79e-4b1a-a72f-1420a37afe3d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1733379bb2fb6f7e6ebacf5f642d5083b2cd5f0d/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 97 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0e70bd39-a646-46b7-a39f-9b34ce0ac6c4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1733379bb2fb6f7e6ebacf5f642d5083b2cd5f0d/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 93 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f8c054fc-cf1e-4932-a936-57d6272b1f41) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1733379bb2fb6f7e6ebacf5f642d5083b2cd5f0d/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 88 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/09bc21ef-6dae-41b5-b61d-f3040ee8feca) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1733379bb2fb6f7e6ebacf5f642d5083b2cd5f0d/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 91 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dc94b95a-38e7-447f-9167-2339d1a47fc6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1733379bb2fb6f7e6ebacf5f642d5083b2cd5f0d/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 92 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/850a7779-b4f3-470a-b17d-b4b2df594aed) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1733379bb2fb6f7e6ebacf5f642d5083b2cd5f0d/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 88 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/da315ad6-49e6-41e8-89a0-f8d85b6cd8eb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1733379bb2fb6f7e6ebacf5f642d5083b2cd5f0d/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 93 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/00d0f7ed-c90d-4d67-a4e7-886fc4f7bf0e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-07-20 09:04 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/896c81128f67ccc7193d3f5e1076d1c109c03e42/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ee0a2a4d-fec8-45bb-a682-252f1301cfbb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/896c81128f67ccc7193d3f5e1076d1c109c03e42/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6bb9c29a-992a-4403-b4e0-b9ed99ffb3b4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/896c81128f67ccc7193d3f5e1076d1c109c03e42/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 89 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8c16c663-83d3-42af-a4a9-b46e66ea1b3d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/896c81128f67ccc7193d3f5e1076d1c109c03e42/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 97 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/753c3fa6-523a-460c-ae2c-b21a3b2fa463) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/896c81128f67ccc7193d3f5e1076d1c109c03e42/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 93 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/30b34779-916c-4110-b1ed-c454db2fdab3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/896c81128f67ccc7193d3f5e1076d1c109c03e42/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 88 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/76c04cb0-dbd0-49f3-9a61-07e5b43cdaed) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/896c81128f67ccc7193d3f5e1076d1c109c03e42/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 91 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/44f2e3a9-ad39-48c8-82fd-22fab4d2452f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/896c81128f67ccc7193d3f5e1076d1c109c03e42/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 92 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/48a1836b-7f56-42ad-adf2-bb433c66ac1d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/896c81128f67ccc7193d3f5e1076d1c109c03e42/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 88 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2e953c9d-6643-4739-8547-461b87696435) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/896c81128f67ccc7193d3f5e1076d1c109c03e42/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 93 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/91dfb8d5-44a9-4f37-bc07-1592c35c5e7f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-07-20 13:34 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/418df80d56c0cbdac1a020c0f850061365905eb5/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9aec6071-c10f-4a20-a6ee-868e54616af0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/418df80d56c0cbdac1a020c0f850061365905eb5/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dd96b2d8-dd0d-4c87-9d56-564d5fb93ea3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/418df80d56c0cbdac1a020c0f850061365905eb5/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a84c05b6-96b0-4ae2-99c2-e34b04958c42) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/418df80d56c0cbdac1a020c0f850061365905eb5/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 97 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cdb669f2-67b7-4ee0-94f9-b8a59d13e0b1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/418df80d56c0cbdac1a020c0f850061365905eb5/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 93 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ddc85135-f676-4db8-8558-bf1b2241c791) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/418df80d56c0cbdac1a020c0f850061365905eb5/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 98 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0d1211bb-5fce-4170-bd21-d84e70da6df3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/418df80d56c0cbdac1a020c0f850061365905eb5/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 91 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0ef116f8-d24b-4e51-afe8-e0d558d65047) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/418df80d56c0cbdac1a020c0f850061365905eb5/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8bbb0b5a-099d-42d1-97db-e93b8ed5a68f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/418df80d56c0cbdac1a020c0f850061365905eb5/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 97 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d39717a4-ebcf-4f31-aaca-6f76443b363b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/418df80d56c0cbdac1a020c0f850061365905eb5/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 93 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2fb81f5a-4866-4097-8490-2b81093d8997) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-07-21 06:38 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/d11ad73608c26d087aab743a20ee0bc71295c6c9/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dcd3ab28-cfc3-42cc-b9f9-e24aabe92fc3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d11ad73608c26d087aab743a20ee0bc71295c6c9/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7d714575-c793-402c-8996-baeb2458a37b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d11ad73608c26d087aab743a20ee0bc71295c6c9/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6f12dd2e-c8b9-4fa3-9b79-3031e587e94f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d11ad73608c26d087aab743a20ee0bc71295c6c9/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 97 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d2aabf46-a389-4172-b96b-1e2b0e511e7a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d11ad73608c26d087aab743a20ee0bc71295c6c9/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 93 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9c4a2a2d-666c-401d-b7c5-8a276e0da854) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d11ad73608c26d087aab743a20ee0bc71295c6c9/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7744a04a-0b10-444c-8e15-bdc9f04f3252) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d11ad73608c26d087aab743a20ee0bc71295c6c9/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 91 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5376ac9e-3126-499d-b02f-b2f85749a3bc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d11ad73608c26d087aab743a20ee0bc71295c6c9/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/26fbe79c-37d6-4874-a856-7943bf67870f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d11ad73608c26d087aab743a20ee0bc71295c6c9/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 97 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9eb43412-3e40-4bf9-865c-b8f2f594136b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d11ad73608c26d087aab743a20ee0bc71295c6c9/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 93 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b5d2c76d-eb8d-4d01-a9d8-ce324def9adf) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-07-21 13:42 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/59f12db7f1ce4548eb15107d8712e0241fc71fed/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5cd0414a-01fa-4919-b22d-3723774636e2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/59f12db7f1ce4548eb15107d8712e0241fc71fed/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7491c44b-aa65-4cdd-a9d1-6c4996e4efe0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/59f12db7f1ce4548eb15107d8712e0241fc71fed/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4c3c929f-5fac-4c8c-9088-dabb539deff7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/59f12db7f1ce4548eb15107d8712e0241fc71fed/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 97 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7ab583a9-738e-445f-b75f-943761b66e26) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/59f12db7f1ce4548eb15107d8712e0241fc71fed/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 93 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7e32e4e4-bd81-4f91-b637-0ac5252b3188) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/59f12db7f1ce4548eb15107d8712e0241fc71fed/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f7cee263-25a4-4a2d-a142-73b91d5a8450) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/59f12db7f1ce4548eb15107d8712e0241fc71fed/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 91 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/46cf6f18-9d03-4c92-9c5c-d9b61f69ed98) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/59f12db7f1ce4548eb15107d8712e0241fc71fed/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9fea8169-08d4-4564-93d8-d93cfdff81ac) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/59f12db7f1ce4548eb15107d8712e0241fc71fed/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 97 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f27e8ca6-538e-49f7-8332-15d1600fe32e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/59f12db7f1ce4548eb15107d8712e0241fc71fed/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 93 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9d32ff8e-bb15-4426-89c6-8e4fff746b25) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-07-24 05:31 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/869705a4de21923c62b3233bbe5016e3be2a23ff/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/64fe0228-3668-4d82-ae04-a6d7e41ee37d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/869705a4de21923c62b3233bbe5016e3be2a23ff/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b9696f38-d4fa-4196-ab24-3f529ee43d2d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/869705a4de21923c62b3233bbe5016e3be2a23ff/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/12959644-143d-453d-9286-b339fd8ac6de) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/869705a4de21923c62b3233bbe5016e3be2a23ff/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 97 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/13653932-dda5-4138-bfd2-85bf299ea1a5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/869705a4de21923c62b3233bbe5016e3be2a23ff/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 93 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/23711afa-4d2d-45ec-bab6-5833e3c9110e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/869705a4de21923c62b3233bbe5016e3be2a23ff/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/15268cd8-cd29-4c2b-9767-a381bbc362df) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/869705a4de21923c62b3233bbe5016e3be2a23ff/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 91 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/acbfb99e-fc03-40e5-a17a-68ccd668c788) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/869705a4de21923c62b3233bbe5016e3be2a23ff/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8f3234d3-db65-46d3-b5a7-befc7f1cdcae) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/869705a4de21923c62b3233bbe5016e3be2a23ff/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 97 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4c229a5e-abae-4976-8991-57ff85fbac10) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/869705a4de21923c62b3233bbe5016e3be2a23ff/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 93 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/63b20ad1-1719-4ff9-837e-bfe0d8373a52) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-07-24 13:26 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ea9ba6876816444f2b715b47e439471f4b7e5bd9/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1a765ec0-b9c7-402d-950d-c89e08fd4435) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ea9ba6876816444f2b715b47e439471f4b7e5bd9/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/801a624f-bc5a-4206-af74-6ca41a496901) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ea9ba6876816444f2b715b47e439471f4b7e5bd9/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 96 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d676335d-b884-40f3-ae76-107a70c35c0b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ea9ba6876816444f2b715b47e439471f4b7e5bd9/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 97 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8336afad-7a60-4661-9103-8e969eb2e785) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ea9ba6876816444f2b715b47e439471f4b7e5bd9/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 93 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e72cdc00-941b-4962-aa99-d43ddd1fbaff) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ea9ba6876816444f2b715b47e439471f4b7e5bd9/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b74902fb-385c-4e3c-be8c-f1a0a0521037) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ea9ba6876816444f2b715b47e439471f4b7e5bd9/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 91 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b65ad926-ab5c-429d-8635-35e6e10a7c92) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ea9ba6876816444f2b715b47e439471f4b7e5bd9/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/314cc00e-baa0-456c-b894-163152adb512) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ea9ba6876816444f2b715b47e439471f4b7e5bd9/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 99 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/270349ce-21eb-4c3f-b16c-af5292acc9eb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ea9ba6876816444f2b715b47e439471f4b7e5bd9/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 93 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4cd34f35-e504-4ae0-b70e-092d175cae9a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-07-25 06:16 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1837fd0c136b869d64cef5d33bb17f015e074d8e/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8181ca36-fa6f-4061-9962-a6ef29d23fb8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1837fd0c136b869d64cef5d33bb17f015e074d8e/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7b90bd57-b4e3-4968-a75d-eb6f9d64d1ac) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1837fd0c136b869d64cef5d33bb17f015e074d8e/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 95 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/83f99bdf-f5cf-41d6-a519-308ae94a3a6a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1837fd0c136b869d64cef5d33bb17f015e074d8e/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 97 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b9defca1-0cc4-4003-a53d-f9e48f346670) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1837fd0c136b869d64cef5d33bb17f015e074d8e/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 93 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7500dbab-f678-458d-87e5-14e5a8d35eec) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1837fd0c136b869d64cef5d33bb17f015e074d8e/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9eddf0da-5735-4cc0-903d-cdb6046f6124) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1837fd0c136b869d64cef5d33bb17f015e074d8e/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 90 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/06ac5e65-f3b7-464b-9549-034b6b571315) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1837fd0c136b869d64cef5d33bb17f015e074d8e/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ad318701-948b-4e55-a350-111315fd1c64) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1837fd0c136b869d64cef5d33bb17f015e074d8e/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 99 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f5fb195a-5f31-4f69-814e-c09368341143) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1837fd0c136b869d64cef5d33bb17f015e074d8e/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 93 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/55cce3bf-5ad4-41e2-9c41-fb3d21d9ed80) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-07-25 13:08 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/922a259221e84eb5dcbebfcebf6bfe33e186038b/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/be44536b-e924-4b4a-b696-ceba1c400083) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/922a259221e84eb5dcbebfcebf6bfe33e186038b/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 98 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/781e0219-ea39-438d-bbd3-a9ba28a0361e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/922a259221e84eb5dcbebfcebf6bfe33e186038b/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 95 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1e404440-d8e3-4983-85ab-4acd8317e00f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/922a259221e84eb5dcbebfcebf6bfe33e186038b/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 97 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a60b173a-59d8-446b-b020-602a611e8eaa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/922a259221e84eb5dcbebfcebf6bfe33e186038b/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 93 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6dfbe1f3-2a97-4c4f-a940-2c0f8580051a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/922a259221e84eb5dcbebfcebf6bfe33e186038b/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/095bc733-a345-4155-8da5-12a2a8340271) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/922a259221e84eb5dcbebfcebf6bfe33e186038b/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 90 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7a11a607-879a-4f38-8e80-989d1f0bcdf1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/922a259221e84eb5dcbebfcebf6bfe33e186038b/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0a12a36d-0eba-47ad-b0c8-7c4ae249b512) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/922a259221e84eb5dcbebfcebf6bfe33e186038b/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 99 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/88f2bdf9-430e-4c61-bc3c-311ee438bb18) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/922a259221e84eb5dcbebfcebf6bfe33e186038b/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 93 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ccb1f4fb-b08b-4516-9816-045998c984aa) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-07-25 13:21 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/d3fa374f76501b7f87a7c4ca3366ab5fb4a9c327/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/49fa3c42-bb1e-42c1-8316-ebe95165fe0a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d3fa374f76501b7f87a7c4ca3366ab5fb4a9c327/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 98 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4d3323c4-dcef-462f-a3a7-dc5e8ef8af0b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d3fa374f76501b7f87a7c4ca3366ab5fb4a9c327/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 95 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1275e034-fdd9-42af-b8a5-fd0f70f4ae01) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d3fa374f76501b7f87a7c4ca3366ab5fb4a9c327/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 97 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2a4f6192-45dd-4af3-b4dd-19dc44340779) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d3fa374f76501b7f87a7c4ca3366ab5fb4a9c327/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 93 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/27da0558-51f4-43f7-a9e8-50fe96cf23ce) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d3fa374f76501b7f87a7c4ca3366ab5fb4a9c327/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2fe1ef19-eac5-4ea1-a3f6-e2912944f3db) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d3fa374f76501b7f87a7c4ca3366ab5fb4a9c327/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 90 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ceb7ec43-7fed-45e5-bc35-e559f8425f7e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d3fa374f76501b7f87a7c4ca3366ab5fb4a9c327/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fe23f2ea-fb69-47fe-9cc5-5a1dab84ed4b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d3fa374f76501b7f87a7c4ca3366ab5fb4a9c327/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 99 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bbb4d542-608b-4257-b81b-5d589ce9b222) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d3fa374f76501b7f87a7c4ca3366ab5fb4a9c327/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 93 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e5e31e2e-825e-4fd7-9a9b-3df2ebf8357d) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-07-25 14:24 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/5f297c712b721b8a2c1bd1a93df7b89a889deb0b/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/15a54185-635f-4227-9ecd-795c14b54e35) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5f297c712b721b8a2c1bd1a93df7b89a889deb0b/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 98 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/895b9e84-ee7f-4c46-be18-6207dc108447) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5f297c712b721b8a2c1bd1a93df7b89a889deb0b/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 95 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e47973d7-8ea5-4b28-b31d-99910eee9108) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5f297c712b721b8a2c1bd1a93df7b89a889deb0b/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 97 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c678f2ed-c350-4ed9-bca5-e23a08a27b0b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5f297c712b721b8a2c1bd1a93df7b89a889deb0b/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 93 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ddb3025a-1d27-4291-aa41-7efe7afb470a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5f297c712b721b8a2c1bd1a93df7b89a889deb0b/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7e8c8bfd-d5c7-492a-a4bd-924ce61274db) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5f297c712b721b8a2c1bd1a93df7b89a889deb0b/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 90 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8ff1babf-feb2-434b-acf4-d828382df024) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5f297c712b721b8a2c1bd1a93df7b89a889deb0b/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/32201cb8-5eae-4e3e-b833-c6474a96b5fa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5f297c712b721b8a2c1bd1a93df7b89a889deb0b/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 99 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2ead0ce4-70b2-415f-9b09-dcf11d6f6976) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5f297c712b721b8a2c1bd1a93df7b89a889deb0b/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 93 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b7f0e418-239a-4aa3-87f0-b2e9dd5db17c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-07-26 11:44 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/dd4db2dcc8363b2ec8c38c7856598e755c14f9ce/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4311fc96-93a8-40dd-bbee-5fac0419c97f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dd4db2dcc8363b2ec8c38c7856598e755c14f9ce/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 98 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5d83ea11-de6a-4b0e-9d13-b69f0cd639eb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dd4db2dcc8363b2ec8c38c7856598e755c14f9ce/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 97 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/73906def-b2a5-47e5-81c3-b90d80f3d160) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dd4db2dcc8363b2ec8c38c7856598e755c14f9ce/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 97 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f8e90625-7334-42c7-8e54-96a691e9a579) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dd4db2dcc8363b2ec8c38c7856598e755c14f9ce/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 93 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4c17c9a6-a701-47ae-b159-c328a52a33d8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dd4db2dcc8363b2ec8c38c7856598e755c14f9ce/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 96 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d0e3f981-6cf2-478f-8bd8-68293ca934cc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dd4db2dcc8363b2ec8c38c7856598e755c14f9ce/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 90 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bb60d573-4155-4e4b-ac22-59121ef75dd7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dd4db2dcc8363b2ec8c38c7856598e755c14f9ce/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b72c9b52-8f05-459e-bf84-21fa1c5d4bb8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dd4db2dcc8363b2ec8c38c7856598e755c14f9ce/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 99 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0b352a3c-ed43-4d5b-b2c3-d86f8d151b09) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dd4db2dcc8363b2ec8c38c7856598e755c14f9ce/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 93 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d567aac3-8f9b-44b1-8461-a7aff588eed6) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-07-27 07:15 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/d5f82c6eff63f0741b2d58a00dd861e3f72d51ac/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5b8919f1-ca94-4861-8b84-a7870de86f5d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d5f82c6eff63f0741b2d58a00dd861e3f72d51ac/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 98 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/00528d9b-9138-43dd-a71c-13df86938f69) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d5f82c6eff63f0741b2d58a00dd861e3f72d51ac/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 97 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/13aa2dda-7b5a-440a-9ec0-b3c3a5ce255c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d5f82c6eff63f0741b2d58a00dd861e3f72d51ac/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 97 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e8376895-f986-4bd5-a551-a9ab44cec67b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d5f82c6eff63f0741b2d58a00dd861e3f72d51ac/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 93 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8ec370e4-2e68-439d-a8dd-624e8b65e96c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d5f82c6eff63f0741b2d58a00dd861e3f72d51ac/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 96 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/62b73e4f-b08b-4d3a-bac6-362280279bcc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d5f82c6eff63f0741b2d58a00dd861e3f72d51ac/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 90 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f43d0e5e-ddc0-4405-81bc-4bbee1d5c426) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d5f82c6eff63f0741b2d58a00dd861e3f72d51ac/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/04b7085f-c38f-4591-8c5a-0efe6ba3ba93) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d5f82c6eff63f0741b2d58a00dd861e3f72d51ac/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 99 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3a46b738-a6b9-449d-9f94-0351ed4be2d1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d5f82c6eff63f0741b2d58a00dd861e3f72d51ac/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 93 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/eddf5132-1088-4716-82e6-17197433516e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-07-27 08:46 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/da549cc3d672e5795450a962fa0c5e8ba5a7c88b/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7d2a37a9-6db9-48f0-8d3d-a7475a3455f4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/da549cc3d672e5795450a962fa0c5e8ba5a7c88b/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 98 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7a18f6fe-8c38-4559-a5c6-d7b33725c958) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/da549cc3d672e5795450a962fa0c5e8ba5a7c88b/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 97 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2cc38117-6f38-4fe1-abae-30f90a749f22) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/da549cc3d672e5795450a962fa0c5e8ba5a7c88b/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 98 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5ff69253-9071-43d5-9440-27d3bb852718) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/da549cc3d672e5795450a962fa0c5e8ba5a7c88b/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 89 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/22ec4ddc-dc81-45c2-bfa6-06d1496b451b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/da549cc3d672e5795450a962fa0c5e8ba5a7c88b/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 96 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a2e65f27-c9bb-46f4-8c49-3887902c3a47) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/da549cc3d672e5795450a962fa0c5e8ba5a7c88b/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 91 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/be9f029c-f6d3-4781-a008-8abbec8b5b1d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/da549cc3d672e5795450a962fa0c5e8ba5a7c88b/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1e456583-63d1-4cb2-98a1-f56f8f04afaa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/da549cc3d672e5795450a962fa0c5e8ba5a7c88b/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 99 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/48b92608-f693-46d1-97b7-7fa9a0ca0818) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/da549cc3d672e5795450a962fa0c5e8ba5a7c88b/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 89 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f2b123aa-59af-4376-9717-e04a6714bd7e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-07-28 11:19 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/8353e4973ecedfece5bac17249b9ccaebf5e60be/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e95bf2c0-2b83-47b0-8609-84531b226bab) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8353e4973ecedfece5bac17249b9ccaebf5e60be/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 98 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f20e2f1a-505e-438a-ae06-5ba4c2483124) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8353e4973ecedfece5bac17249b9ccaebf5e60be/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 97 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a326b395-77f3-425c-9ea3-962821301bcb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8353e4973ecedfece5bac17249b9ccaebf5e60be/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 98 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ccbfcbb0-d441-45e2-9934-743fb4fe13f9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8353e4973ecedfece5bac17249b9ccaebf5e60be/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 88 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9dc2e8f6-f53b-4c78-8a7a-a32a493a7e0d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8353e4973ecedfece5bac17249b9ccaebf5e60be/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 96 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/79a5c01a-0d86-41b0-9e6c-07cf6ef64249) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8353e4973ecedfece5bac17249b9ccaebf5e60be/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 91 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d29731db-dcdd-4249-a854-d7f1e394e1f4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8353e4973ecedfece5bac17249b9ccaebf5e60be/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aff17111-b7a9-4fbf-8895-ff7d8b90b5e1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8353e4973ecedfece5bac17249b9ccaebf5e60be/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 99 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c7a46510-7f55-499f-826f-b223dcda3204) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8353e4973ecedfece5bac17249b9ccaebf5e60be/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dd4bd1f0-cc9d-45f9-8d7b-1acc2b601c59) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-07-28 11:50 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/78c68a108dfd57eb3568ac93dcfc842545984c17/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5ebeb3f3-a0b9-4ace-88d6-53d5550fa88c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/78c68a108dfd57eb3568ac93dcfc842545984c17/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 98 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1583c644-4aa7-4e45-a4d2-c1beee002230) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/78c68a108dfd57eb3568ac93dcfc842545984c17/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 97 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8405c39e-4789-4c3b-aba4-c14cbb50300e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/78c68a108dfd57eb3568ac93dcfc842545984c17/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 98 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/08df3f1a-0a41-4384-bd19-22317aa7639b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/78c68a108dfd57eb3568ac93dcfc842545984c17/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 88 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/be2c041a-8ea9-4a64-b3b1-08f2f8011b01) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/78c68a108dfd57eb3568ac93dcfc842545984c17/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 96 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fc7c7536-5402-4e22-8b6f-3204f789a520) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/78c68a108dfd57eb3568ac93dcfc842545984c17/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 91 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/917c9036-eda8-478a-938b-da92bedf385e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/78c68a108dfd57eb3568ac93dcfc842545984c17/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/541f4725-5c45-40d9-9c92-f01d06ae34bc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/78c68a108dfd57eb3568ac93dcfc842545984c17/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 99 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bb9f8118-5442-4033-8c59-5861ed34d039) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/78c68a108dfd57eb3568ac93dcfc842545984c17/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ed6f4eb4-b739-43b5-8172-943527aee86f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-08-01 11:19 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c68c0afe101fa77f6a0afa25bc387e21bbd604e3/msteams-platform%2FTOC.yml) |   |   | [link]( ) | [:warning:](# "Could not check with Acrolinx&#10;Please close and reopen pull request") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c68c0afe101fa77f6a0afa25bc387e21bbd604e3/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) |   |   | [link]( ) | [:warning:](# "Could not check with Acrolinx&#10;Please close and reopen pull request") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c68c0afe101fa77f6a0afa25bc387e21bbd604e3/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) |   |   | [link]( ) | [:warning:](# "Could not check with Acrolinx&#10;Please close and reopen pull request") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c68c0afe101fa77f6a0afa25bc387e21bbd604e3/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) |   |   | [link]( ) | [:warning:](# "Could not check with Acrolinx&#10;Please close and reopen pull request") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c68c0afe101fa77f6a0afa25bc387e21bbd604e3/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) |   |   | [link]( ) | [:warning:](# "Could not check with Acrolinx&#10;Please close and reopen pull request") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c68c0afe101fa77f6a0afa25bc387e21bbd604e3/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) |   |   | [link]( ) | [:warning:](# "Could not check with Acrolinx&#10;Please close and reopen pull request") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c68c0afe101fa77f6a0afa25bc387e21bbd604e3/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) |   |   | [link]( ) | [:warning:](# "Could not check with Acrolinx&#10;Please close and reopen pull request") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c68c0afe101fa77f6a0afa25bc387e21bbd604e3/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) |   |   | [link]( ) | [:warning:](# "Could not check with Acrolinx&#10;Please close and reopen pull request") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c68c0afe101fa77f6a0afa25bc387e21bbd604e3/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) |   |   | [link]( ) | [:warning:](# "Could not check with Acrolinx&#10;Please close and reopen pull request") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c68c0afe101fa77f6a0afa25bc387e21bbd604e3/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) |   |   | [link]( ) | [:warning:](# "Could not check with Acrolinx&#10;Please close and reopen pull request") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-08-02 07:59 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/419978e22de1c93fe10a81d02515b488fdd4595c/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1d7168a9-c6f0-4991-95a6-db58d68f2466) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/419978e22de1c93fe10a81d02515b488fdd4595c/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 98 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cc4139ce-3e66-49ac-957e-14f6d676fbc5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/419978e22de1c93fe10a81d02515b488fdd4595c/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 97 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ad652572-dd30-48b3-9221-793f0339ccdf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/419978e22de1c93fe10a81d02515b488fdd4595c/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 98 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/935b1e23-c396-4189-b1ee-045d7f1af78e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/419978e22de1c93fe10a81d02515b488fdd4595c/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 88 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/03bc3b19-c817-4ef7-bb04-dd3d2250122a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/419978e22de1c93fe10a81d02515b488fdd4595c/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 96 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7e088892-d455-4a0d-8737-5fcf4322c1b0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/419978e22de1c93fe10a81d02515b488fdd4595c/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 91 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b147f1a4-ab36-485e-944b-69d95ed99acf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/419978e22de1c93fe10a81d02515b488fdd4595c/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/18601763-75c5-41fd-a112-f36190193322) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/419978e22de1c93fe10a81d02515b488fdd4595c/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 99 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d91fd404-c26e-44af-8495-443c98d7519b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/419978e22de1c93fe10a81d02515b488fdd4595c/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/943381af-fbaf-427a-b786-98e936b9cdf2) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-08-02 13:49 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/cac89cd351cc586b5393f4d5bfc520e6d3734eeb/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3937eed7-0604-478a-b5df-f4bf43f752f9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cac89cd351cc586b5393f4d5bfc520e6d3734eeb/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 98 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f4d19155-5d72-4882-8d08-c8dfb72859db) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cac89cd351cc586b5393f4d5bfc520e6d3734eeb/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 97 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a4d4bc4b-5372-489f-a677-04c8b0f1cc1c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cac89cd351cc586b5393f4d5bfc520e6d3734eeb/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 98 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7af955f5-4c82-4b00-acdb-8e9b1459c6d3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cac89cd351cc586b5393f4d5bfc520e6d3734eeb/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 93 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/68c9c2b0-1b63-4a3f-8fb6-0c92be8cf8c2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cac89cd351cc586b5393f4d5bfc520e6d3734eeb/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 97 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4b809548-94d6-4835-9a1c-569d8e9e3fcd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cac89cd351cc586b5393f4d5bfc520e6d3734eeb/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0754f90c-d15d-4f0d-b91f-26983ad1b68a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cac89cd351cc586b5393f4d5bfc520e6d3734eeb/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d532fb87-800e-4ea7-a7f0-b503be672af0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cac89cd351cc586b5393f4d5bfc520e6d3734eeb/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 99 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/26accf13-37e1-4ef6-a3d5-393b764b8227) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cac89cd351cc586b5393f4d5bfc520e6d3734eeb/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b44e459a-5551-42ca-8bd5-481041bfaa18) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-08-02 14:12 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/3d86b00f1d86fced575902e52461f92a398d0716/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/49477699-60d3-4a02-a4b1-579caff718c3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3d86b00f1d86fced575902e52461f92a398d0716/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 98 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b02bf29d-678d-4265-b6fe-2eff3f32bdc7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3d86b00f1d86fced575902e52461f92a398d0716/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 97 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a5521163-c522-44cf-90d4-1d76b78df225) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3d86b00f1d86fced575902e52461f92a398d0716/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 98 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/18b1dded-778c-4763-a996-c17e76bdce8d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3d86b00f1d86fced575902e52461f92a398d0716/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 93 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8d97bf3a-fa99-4fda-bc72-e89bdbf0ce21) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3d86b00f1d86fced575902e52461f92a398d0716/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 97 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2f975ff5-83bb-4dda-a11b-9cfb229b5521) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3d86b00f1d86fced575902e52461f92a398d0716/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/04280266-3f5e-4229-8153-8ce9fcbaa252) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3d86b00f1d86fced575902e52461f92a398d0716/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/73b68a7a-6a24-4321-9196-589d529f3f50) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3d86b00f1d86fced575902e52461f92a398d0716/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 99 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2cd02ec4-b3d0-4d2a-88b9-0ae8d2f83ae2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3d86b00f1d86fced575902e52461f92a398d0716/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/addbe9d9-e50d-4ea8-8627-1903e5356da3) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-08-04 14:14 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/61f40275f043876fddf5117e8c7b9755f1a38fe9/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/01e4d6a9-998e-4728-9f87-b8a731e9f008) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/61f40275f043876fddf5117e8c7b9755f1a38fe9/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 98 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7801460b-5646-4588-ae30-ed668d8d4843) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/61f40275f043876fddf5117e8c7b9755f1a38fe9/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 97 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fa1ad548-892b-4886-adb6-426641238311) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/61f40275f043876fddf5117e8c7b9755f1a38fe9/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 98 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0eae2b20-79d1-428e-8219-138c9b7ffe37) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/61f40275f043876fddf5117e8c7b9755f1a38fe9/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 93 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/68a27960-8cba-4af1-8f4e-c8f05ecbc34a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/61f40275f043876fddf5117e8c7b9755f1a38fe9/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 97 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fd448eb9-fd65-4637-ad7c-d6ece82cab43) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/61f40275f043876fddf5117e8c7b9755f1a38fe9/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7cab3f72-8a01-48c4-8cd9-463a792aca07) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/61f40275f043876fddf5117e8c7b9755f1a38fe9/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7231a961-b03d-4c66-8332-726f1ca7acd6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/61f40275f043876fddf5117e8c7b9755f1a38fe9/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 99 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/43681269-1839-4931-8316-288205ac0cdb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/61f40275f043876fddf5117e8c7b9755f1a38fe9/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/98e2521b-1438-4067-992b-3f92314c371e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-08-04 14:26 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/0754e5ec3221ecbe250736be47a68da6cd6f4433/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b5175d43-1f3a-45e0-9f12-0d7566988800) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0754e5ec3221ecbe250736be47a68da6cd6f4433/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 98 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5105f511-9330-4690-85b6-e64f992cf38c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0754e5ec3221ecbe250736be47a68da6cd6f4433/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 97 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c8d4ad08-ac1c-49f7-a677-353c54c13e60) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0754e5ec3221ecbe250736be47a68da6cd6f4433/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 98 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0011ccc5-0a33-4668-91df-385ebdbc0679) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0754e5ec3221ecbe250736be47a68da6cd6f4433/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 93 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e03786c4-fb17-42f0-8e4e-db988ff1d86f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0754e5ec3221ecbe250736be47a68da6cd6f4433/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 97 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ee2c8738-ee4a-454d-952d-e323efb0017d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0754e5ec3221ecbe250736be47a68da6cd6f4433/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6b143a72-948b-4955-b023-7bcf31b9fd40) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0754e5ec3221ecbe250736be47a68da6cd6f4433/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4f240dc7-654b-409c-aec8-c9830d1c1336) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0754e5ec3221ecbe250736be47a68da6cd6f4433/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 99 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/57f8a566-7caa-49ac-9ee0-ee02e4c7d3b0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0754e5ec3221ecbe250736be47a68da6cd6f4433/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7a561b23-d03c-4c50-900d-e91038533ffa) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-08-08 06:54 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/6a8db60526496f27d04e74e718e1cf608ee9b4ee/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3bc5016e-515e-443b-8dc8-b2d563f82c14) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6a8db60526496f27d04e74e718e1cf608ee9b4ee/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 98 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/99675d01-1e91-4d84-8cd9-90bb1e2a53f0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6a8db60526496f27d04e74e718e1cf608ee9b4ee/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 97 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/230fca92-008a-4a29-8958-c19f4d558087) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6a8db60526496f27d04e74e718e1cf608ee9b4ee/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 98 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1ead0912-c780-45b9-85bd-ac3ecb5b042d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6a8db60526496f27d04e74e718e1cf608ee9b4ee/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 93 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b30ecf17-3918-4c7b-b991-36a30c14c421) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6a8db60526496f27d04e74e718e1cf608ee9b4ee/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 97 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9dfeace8-7e52-4843-9403-3e24e5b7d9eb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6a8db60526496f27d04e74e718e1cf608ee9b4ee/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0a4aa9f7-7025-48ef-a625-a194278c5388) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6a8db60526496f27d04e74e718e1cf608ee9b4ee/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7bf0c344-9aaf-40ef-9433-995d65a92633) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6a8db60526496f27d04e74e718e1cf608ee9b4ee/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 99 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ee5330a6-d2f4-4407-b18b-ee340575d753) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6a8db60526496f27d04e74e718e1cf608ee9b4ee/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4bd0b132-d3ff-4c94-9ead-66d001e8420c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-08-08 12:47 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/d131a1dbaabe47b24f622d3d12b2f38499096451/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9140bcad-1cff-465a-adcc-fcbc206e8617) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d131a1dbaabe47b24f622d3d12b2f38499096451/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 98 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/907d5a67-db53-42a7-bdf9-a62565bc8474) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d131a1dbaabe47b24f622d3d12b2f38499096451/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 97 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c786089e-8092-4c69-adb2-334421843807) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d131a1dbaabe47b24f622d3d12b2f38499096451/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 98 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/daeabda8-6f6b-4f53-bf04-523146ab159b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d131a1dbaabe47b24f622d3d12b2f38499096451/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 93 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/86a4af7f-60c6-4f4a-a472-7cf889537bdb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d131a1dbaabe47b24f622d3d12b2f38499096451/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 97 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/555d6f74-c1f3-494e-9ee9-91aedeb24776) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d131a1dbaabe47b24f622d3d12b2f38499096451/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/562d7dc6-b351-46d1-80be-c45983e89f25) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d131a1dbaabe47b24f622d3d12b2f38499096451/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0d0efdb3-b1cc-454e-a1f5-06bbfa4ba7b1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d131a1dbaabe47b24f622d3d12b2f38499096451/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 99 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a5c2d8ea-20d1-4c8c-ac74-3c877f98074f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d131a1dbaabe47b24f622d3d12b2f38499096451/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/86e85aec-99f8-4b9f-aa21-c43ae82d46cc) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-08-09 07:45 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/84d829f286396636c3aa2fac1c0b762ee65d034a/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/14bc7f09-4aff-44f5-9d1e-d9c4ee079777) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/84d829f286396636c3aa2fac1c0b762ee65d034a/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 98 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3b603c52-9acc-4637-9405-b21f258deed8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/84d829f286396636c3aa2fac1c0b762ee65d034a/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 97 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/00482309-e426-498c-8f83-a99d0779ff1f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/84d829f286396636c3aa2fac1c0b762ee65d034a/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 98 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/454e6209-19f0-44ff-9767-4ee6bd3c12e4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/84d829f286396636c3aa2fac1c0b762ee65d034a/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 93 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/34fcca58-8242-482f-8905-6dbe4f87ed19) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/84d829f286396636c3aa2fac1c0b762ee65d034a/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ae18f3d4-2b6f-4725-aaeb-ec4e2545f34c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/84d829f286396636c3aa2fac1c0b762ee65d034a/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/94de74d9-0a66-42c6-9c15-730a2a11629c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/84d829f286396636c3aa2fac1c0b762ee65d034a/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7d08ba12-1457-49c0-beb5-177424c34f64) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/84d829f286396636c3aa2fac1c0b762ee65d034a/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 99 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b94f07dc-c4ab-4c7f-aaa3-dd21550d975f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/84d829f286396636c3aa2fac1c0b762ee65d034a/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/58763d5f-d979-4abc-becb-d02ca135722e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-08-10 14:36 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/3846b5578faeff212cab389de1ece6708760ca84/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1adf6ab6-cf8c-4f75-a936-4968c5f0a8b0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3846b5578faeff212cab389de1ece6708760ca84/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 98 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6b035e60-9194-4518-a6b6-f2eb743a9553) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3846b5578faeff212cab389de1ece6708760ca84/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 96 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c6fa78b4-6ded-43f0-aac3-1291b138a092) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3846b5578faeff212cab389de1ece6708760ca84/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 98 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5a112f54-34ea-4579-a4be-e58183b4f67c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3846b5578faeff212cab389de1ece6708760ca84/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 93 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a7814926-196e-49c5-b7ba-d51c663c39bc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3846b5578faeff212cab389de1ece6708760ca84/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/98a1a0e9-fd3b-49e5-87ca-21d755292f78) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3846b5578faeff212cab389de1ece6708760ca84/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 92 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5db3de14-12c8-4bb9-b5b0-dfb1c423cf4a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3846b5578faeff212cab389de1ece6708760ca84/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cbebe7b5-eaea-4856-82c3-8dcc98888b51) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3846b5578faeff212cab389de1ece6708760ca84/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 99 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/19a25ca7-1f84-426b-b60c-d8e3ca3da8e6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3846b5578faeff212cab389de1ece6708760ca84/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/eedc34af-c4c4-4404-a75f-a244395a8b63) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-08-11 12:55 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/efe09cb6517042b970442d290de89d81468cafbe/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6797cfc8-0e8a-483f-8068-04e62365474a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/efe09cb6517042b970442d290de89d81468cafbe/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 98 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1a72013b-97c8-439f-940e-c9309ffcd69b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/efe09cb6517042b970442d290de89d81468cafbe/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 96 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/538449e9-0c51-4d54-a061-a3a4f68bd1e1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/efe09cb6517042b970442d290de89d81468cafbe/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 98 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7dea038f-ca48-4f22-9d91-22c561c68b19) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/efe09cb6517042b970442d290de89d81468cafbe/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 93 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a16a2f10-f018-4760-929d-a2f0701c3e8c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/efe09cb6517042b970442d290de89d81468cafbe/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/657c76a8-eed0-4af3-b0b5-1cad5dcb8c0a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/efe09cb6517042b970442d290de89d81468cafbe/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 92 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/28c95508-7ef6-40d0-8107-51978808b410) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/efe09cb6517042b970442d290de89d81468cafbe/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fffe2586-f5c4-41ca-8cc2-2b7bd495b1ff) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/efe09cb6517042b970442d290de89d81468cafbe/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 99 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4c8c9613-c079-4bb1-a15d-48b8e01694e9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/efe09cb6517042b970442d290de89d81468cafbe/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7ce41016-16f6-49b6-8356-44e3b5f143e9) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-08-14 05:04 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/30e60e581ebb9eedf470af3f9e79485a4462893b/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/92dd5e0b-bcd0-42d9-a7f9-8cef62a606d8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/30e60e581ebb9eedf470af3f9e79485a4462893b/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 98 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c2b8bdd7-c9bc-48e4-acab-b8f9c2616337) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/30e60e581ebb9eedf470af3f9e79485a4462893b/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 96 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/de758d58-37e4-424c-b8f8-2f1f416ee8bf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/30e60e581ebb9eedf470af3f9e79485a4462893b/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 98 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b1bd0d4e-435a-4bcc-b9e4-f3d2ccc6e700) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/30e60e581ebb9eedf470af3f9e79485a4462893b/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 93 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c4d3cf7d-075e-4324-b4f2-a549d753e969) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/30e60e581ebb9eedf470af3f9e79485a4462893b/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/656b08bf-ea53-44e0-a818-207603f6a848) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/30e60e581ebb9eedf470af3f9e79485a4462893b/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 92 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e5fb99a6-56e7-47bf-9a5a-475a90435781) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/30e60e581ebb9eedf470af3f9e79485a4462893b/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9c520ce7-2acd-485e-9e8e-c9725be73c38) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/30e60e581ebb9eedf470af3f9e79485a4462893b/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 99 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3f10e718-f0a6-4387-8e76-2ab08c1a485b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/30e60e581ebb9eedf470af3f9e79485a4462893b/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cf317da4-8e17-4c7e-9de6-59d6c19a2954) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-08-14 08:46 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/5c2e21be748e2d776d91421c2245885521827211/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8a7a4d99-be18-4532-9ba6-9e5363b54634) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5c2e21be748e2d776d91421c2245885521827211/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 98 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/80cc55d9-6845-4b00-930c-31786d3353d5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5c2e21be748e2d776d91421c2245885521827211/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 97 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f5f4038c-b470-4b41-9438-7acb14ecb45a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5c2e21be748e2d776d91421c2245885521827211/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 98 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c3a94939-1f14-4a35-9cc6-18d63f5d4e5b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5c2e21be748e2d776d91421c2245885521827211/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 93 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/895b51a7-efbe-49e1-bc20-8d325774fb46) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5c2e21be748e2d776d91421c2245885521827211/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cdc1c4b5-32b1-4c08-b2e9-74fdd657da45) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5c2e21be748e2d776d91421c2245885521827211/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3e630f8a-6cc8-4368-bfdb-abf3d6ab5f65) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5c2e21be748e2d776d91421c2245885521827211/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9dcfea0b-3500-42e4-87a0-de5496a5621b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5c2e21be748e2d776d91421c2245885521827211/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 99 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2fafa2f0-8666-4d03-8f68-d2584d2c20eb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5c2e21be748e2d776d91421c2245885521827211/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/22d8184b-897e-48bb-887b-68a810a6827d) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-08-16 04:36 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/60dcdab258b65c84b2b3e28fbffeb4b829dab851/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4e6b5a5b-b2df-4000-af43-9556074401f6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/60dcdab258b65c84b2b3e28fbffeb4b829dab851/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 98 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/66236b1d-2c9c-4409-9b74-d9ff8bfba4ca) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/60dcdab258b65c84b2b3e28fbffeb4b829dab851/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 97 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a25c656b-93d3-4dba-a2f1-b846fa4d9584) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/60dcdab258b65c84b2b3e28fbffeb4b829dab851/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 98 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6bb8cf26-ce8e-4390-9022-d6f89ab4ffbf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/60dcdab258b65c84b2b3e28fbffeb4b829dab851/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 93 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4ef2cdd1-5d1a-4603-a4a4-ee973184a8ed) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/60dcdab258b65c84b2b3e28fbffeb4b829dab851/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b3cbfb13-94e4-4b0d-a1ac-34d2e76a605c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/60dcdab258b65c84b2b3e28fbffeb4b829dab851/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/baaf5bc3-9acf-4552-b6ba-f358c0257423) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/60dcdab258b65c84b2b3e28fbffeb4b829dab851/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/478af5ea-fab4-4260-ab33-a1cb1682da0c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/60dcdab258b65c84b2b3e28fbffeb4b829dab851/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 99 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c8bdf0e4-dc7c-491f-ac71-131da96d9bf8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/60dcdab258b65c84b2b3e28fbffeb4b829dab851/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 95 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d9faab60-633e-453e-809e-b71d681a9bac) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-08-16 11:03 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/746709891402d2b9f6a8d6d630b23023553e2f48/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4b0b3f86-7851-4bba-968a-49f6b8828081) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/746709891402d2b9f6a8d6d630b23023553e2f48/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 98 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e12fc49a-c4ae-43e3-a14c-6cb50f2c0369) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/746709891402d2b9f6a8d6d630b23023553e2f48/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 97 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fd5c8e0d-6cf6-48c9-a8b4-b3f0239d8211) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/746709891402d2b9f6a8d6d630b23023553e2f48/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 98 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/99a87ce5-bc6a-4808-ab12-53a448dd7f37) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/746709891402d2b9f6a8d6d630b23023553e2f48/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 93 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3518dec7-c1d4-4b41-9f57-620502fc69cf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/746709891402d2b9f6a8d6d630b23023553e2f48/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/13b574e7-dfc3-4b1a-bc80-541d362a0114) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/746709891402d2b9f6a8d6d630b23023553e2f48/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0a805b92-b155-489a-8f43-ff536d0cd9b8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/746709891402d2b9f6a8d6d630b23023553e2f48/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aa3bf1b3-48eb-4fd2-842a-f6609c740a51) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/746709891402d2b9f6a8d6d630b23023553e2f48/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 99 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9e6e8c7b-c1e1-47bf-9867-0e054a7cf678) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/746709891402d2b9f6a8d6d630b23023553e2f48/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 95 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a7dca6ed-7540-4436-a903-db6c8abc79ab) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-08-17 03:49 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/53bf49f0f71ee1ce1cb5b6ffbb53e1c3c52933e9/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/83cfb259-86bc-4368-a178-94dd90e66c21) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/53bf49f0f71ee1ce1cb5b6ffbb53e1c3c52933e9/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 98 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/05dd7a3f-e408-470d-91eb-849f2c47868f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/53bf49f0f71ee1ce1cb5b6ffbb53e1c3c52933e9/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 97 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7e3b23ce-516a-4b1b-9700-3711da1a3d06) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/53bf49f0f71ee1ce1cb5b6ffbb53e1c3c52933e9/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 98 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d93d4f0d-790f-4481-a848-617a6062a3d9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/53bf49f0f71ee1ce1cb5b6ffbb53e1c3c52933e9/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 93 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cf9b7624-6b5a-44f4-b4f1-870d0d57be88) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/53bf49f0f71ee1ce1cb5b6ffbb53e1c3c52933e9/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/952f272b-d6b1-40ef-89f9-77bd2f9e4c88) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/53bf49f0f71ee1ce1cb5b6ffbb53e1c3c52933e9/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2c3182ee-287b-4e44-b130-60f667b22095) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/53bf49f0f71ee1ce1cb5b6ffbb53e1c3c52933e9/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d2c6f8ca-63c0-44f2-842e-ff8c66d84829) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/53bf49f0f71ee1ce1cb5b6ffbb53e1c3c52933e9/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 100 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/03071e22-1615-4bb2-8a55-57939f02c103) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/53bf49f0f71ee1ce1cb5b6ffbb53e1c3c52933e9/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 95 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/130cdb71-577a-4a7b-9af0-dcca3a664d95) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-08-17 05:54 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/b99168081e11bc0ef1b955ec992f07f9aa377eb5/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/561a019e-c99c-491b-bd6c-0c5e1595c469) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b99168081e11bc0ef1b955ec992f07f9aa377eb5/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 98 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/77bff0b7-b447-4e9d-9c7d-13497bd90ec1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b99168081e11bc0ef1b955ec992f07f9aa377eb5/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 97 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/08b4bafc-d8e1-4222-aeae-2cb6c065a767) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b99168081e11bc0ef1b955ec992f07f9aa377eb5/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 98 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/52e724ff-8a6a-45a4-b195-e6e94efec975) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b99168081e11bc0ef1b955ec992f07f9aa377eb5/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 93 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e8d03eda-d064-4428-8d6a-a6d800d6caae) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b99168081e11bc0ef1b955ec992f07f9aa377eb5/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/50535daa-881f-43b2-878c-7c067e60c2b2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b99168081e11bc0ef1b955ec992f07f9aa377eb5/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6c223567-5eef-4fb7-989e-d20c8fc05d72) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b99168081e11bc0ef1b955ec992f07f9aa377eb5/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0d4f869f-b773-420e-b67f-9a17c3392834) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b99168081e11bc0ef1b955ec992f07f9aa377eb5/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 100 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7b5ad525-36fc-4a62-8ffe-f8ab84954fb0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b99168081e11bc0ef1b955ec992f07f9aa377eb5/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 95 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/92c0c31e-4fd8-4aa5-92ce-09998a62f388) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-08-17 08:26 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/d617c80ebcc8d43d46b21bc8c189218973fb9835/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4763eaf1-9119-4f6b-9bbd-0a8be9daeb4d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d617c80ebcc8d43d46b21bc8c189218973fb9835/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 98 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/05ef7467-3d4c-4d45-93e8-fc5da8c09f3d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d617c80ebcc8d43d46b21bc8c189218973fb9835/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/42883285-dbfa-4ced-95b7-64dcd0886c3c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d617c80ebcc8d43d46b21bc8c189218973fb9835/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 98 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8e381a38-4cd8-4b2b-8a69-8c8714469eef) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d617c80ebcc8d43d46b21bc8c189218973fb9835/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 93 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1a057b3b-2b7e-4304-938d-c6be88c46c53) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d617c80ebcc8d43d46b21bc8c189218973fb9835/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/928a90b5-c2ee-4f82-b85c-8ba26d95f24b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d617c80ebcc8d43d46b21bc8c189218973fb9835/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5842a509-fe40-4acc-afe3-4fc571f74cb0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d617c80ebcc8d43d46b21bc8c189218973fb9835/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7c96ef5a-a111-44e9-8bff-e34ba9b9e669) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d617c80ebcc8d43d46b21bc8c189218973fb9835/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 100 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/db122c96-e9e8-4421-8568-9b0887dcf803) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d617c80ebcc8d43d46b21bc8c189218973fb9835/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 94 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/733175a6-6ecf-451a-8ee6-0ead4dfe5ee7) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-08-17 13:00 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ca835ac34730ad87d0bb5591858ef464bd33a683/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8d8cf0ba-c130-4b0b-a743-272bd9b283b9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ca835ac34730ad87d0bb5591858ef464bd33a683/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 98 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6c506db2-8426-489f-9fa3-52c9b00197a4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ca835ac34730ad87d0bb5591858ef464bd33a683/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ad3212b6-5c63-4dea-8654-bf1fa218ef09) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ca835ac34730ad87d0bb5591858ef464bd33a683/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 98 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1c4321fe-da68-4987-9d40-cf2254ce4231) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ca835ac34730ad87d0bb5591858ef464bd33a683/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 93 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0d764708-09ba-4516-9aa0-b6154ea332b6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ca835ac34730ad87d0bb5591858ef464bd33a683/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d9efea6f-9343-4c8f-9954-8e4c0cefa06f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ca835ac34730ad87d0bb5591858ef464bd33a683/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/44bf97ba-6fa2-4fed-9293-faee00210e86) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ca835ac34730ad87d0bb5591858ef464bd33a683/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2a04ae45-d701-4500-a21f-c86b593d2ef2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ca835ac34730ad87d0bb5591858ef464bd33a683/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 100 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dbf94e9e-1367-47ac-8763-ea1a048a2ce2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ca835ac34730ad87d0bb5591858ef464bd33a683/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 94 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/48e23cb0-2944-40f7-852f-69b0d2dbd558) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-08-21 04:56 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/76996dbd7a991ef3a5fc86b740bc689d7efd9a5e/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0b6bc741-5303-4c71-ae70-784682cb39fa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/76996dbd7a991ef3a5fc86b740bc689d7efd9a5e/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 98 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f2009341-4c5e-46e0-b489-5448962d1206) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/76996dbd7a991ef3a5fc86b740bc689d7efd9a5e/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/42204304-eaf4-4727-b6c9-e1f93c5d4cc4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/76996dbd7a991ef3a5fc86b740bc689d7efd9a5e/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 98 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/361b4f33-f204-4f9c-ac24-c38a35058f89) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/76996dbd7a991ef3a5fc86b740bc689d7efd9a5e/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 93 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0d6b6062-7e34-4ecd-9e61-8658d16275ae) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/76996dbd7a991ef3a5fc86b740bc689d7efd9a5e/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/60943e27-2a41-49b3-9eb5-20d8d13b339e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/76996dbd7a991ef3a5fc86b740bc689d7efd9a5e/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/df4384d5-b77b-4754-99a1-15642936e812) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/76996dbd7a991ef3a5fc86b740bc689d7efd9a5e/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1713e0f4-cf5e-4d26-aab4-553779d672c6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/76996dbd7a991ef3a5fc86b740bc689d7efd9a5e/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 100 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ad059de1-f154-4c19-8f84-90776a717cc7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/76996dbd7a991ef3a5fc86b740bc689d7efd9a5e/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 94 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d91117de-e616-4891-bc3c-fd257cdd1cf5) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-08-21 05:03 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/31a8b7fa41778559949b27796b56995592585076/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5c4b44f4-8cc9-4273-abeb-ba9cb519b5bc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/31a8b7fa41778559949b27796b56995592585076/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 98 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/507e11b7-a7b3-4955-857c-f4161351d36c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/31a8b7fa41778559949b27796b56995592585076/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/97e87e19-6373-45e7-b93c-2132b0ec6e4e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/31a8b7fa41778559949b27796b56995592585076/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 98 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8c34bf54-223e-4fa1-9408-05f23a6173c0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/31a8b7fa41778559949b27796b56995592585076/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 93 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c8fb2d35-1967-4706-ad79-e21808646d12) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/31a8b7fa41778559949b27796b56995592585076/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6358b0f0-30f1-4463-9bf4-e7174352e8a9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/31a8b7fa41778559949b27796b56995592585076/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/95f33c3d-e7fe-486d-8052-fd0024f85e0c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/31a8b7fa41778559949b27796b56995592585076/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8ce9a683-5d94-4152-9825-18a5dcc945de) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/31a8b7fa41778559949b27796b56995592585076/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 100 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b43ad0d6-d898-4a92-86b0-edcbf14779da) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/31a8b7fa41778559949b27796b56995592585076/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 94 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1235fcea-3fea-4664-874e-3ac1fa5221f2) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-08-22 04:07 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/7b8ad18c42f03dca803b8d58378505964983f761/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e3de1536-e98b-4a51-b198-3b70e007dc12) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7b8ad18c42f03dca803b8d58378505964983f761/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 98 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5528f959-4cdc-4c90-bed1-c4ed60594287) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7b8ad18c42f03dca803b8d58378505964983f761/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7b33abd7-64fb-4c39-ac29-a8e089d91a90) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7b8ad18c42f03dca803b8d58378505964983f761/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 98 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fa109fb7-bf80-4578-96d7-fdde841a1c0d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7b8ad18c42f03dca803b8d58378505964983f761/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 93 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/45bfd842-e62f-482b-9881-d46053d69124) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7b8ad18c42f03dca803b8d58378505964983f761/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3b421063-50cb-4289-890d-dc0370e2ef7e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7b8ad18c42f03dca803b8d58378505964983f761/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6d467fa8-235e-4322-bdf7-cc92054ca6a2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7b8ad18c42f03dca803b8d58378505964983f761/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a2daba2f-7816-467c-a666-b49b96327126) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7b8ad18c42f03dca803b8d58378505964983f761/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 100 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/be35525b-1dc5-455f-a0da-ce7e521d82ac) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7b8ad18c42f03dca803b8d58378505964983f761/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 94 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/48e4f45a-11cb-4212-b646-0852cd656b46) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-08-22 07:45 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a448ed4fed7a8076d17ee4cdbdc342c28d5874a2/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4da0eaf7-3d2b-414b-9680-2b34ce4de405) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a448ed4fed7a8076d17ee4cdbdc342c28d5874a2/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2c16039e-cf5f-4f8f-9289-31c6ddeb1dbe) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a448ed4fed7a8076d17ee4cdbdc342c28d5874a2/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b8c14857-1aa9-43b0-bc7b-d2cd6124b6db) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a448ed4fed7a8076d17ee4cdbdc342c28d5874a2/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 98 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/be6d11e4-16ff-4a6e-81f2-4e0b9af805dd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a448ed4fed7a8076d17ee4cdbdc342c28d5874a2/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 95 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1442e216-b8c9-4c23-88a3-625832d650c7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a448ed4fed7a8076d17ee4cdbdc342c28d5874a2/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7a6313f3-b316-436f-b2bf-0032de5d67f5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a448ed4fed7a8076d17ee4cdbdc342c28d5874a2/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f60af7ea-5b7b-4414-879b-1d5c35cf7e71) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a448ed4fed7a8076d17ee4cdbdc342c28d5874a2/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7ba832c2-fcf0-478c-8e61-d1a48adc7ada) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a448ed4fed7a8076d17ee4cdbdc342c28d5874a2/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 100 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ac02e92b-8f06-4843-a482-b20271780661) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a448ed4fed7a8076d17ee4cdbdc342c28d5874a2/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/84c5a0ee-448f-493b-a9fb-131754c431a3) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-08-23 13:27 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/5ed8626b5216653a53bf098d0d8ba3fae6436fb6/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cd786084-47a1-43e7-81ad-3dc4268d5862) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5ed8626b5216653a53bf098d0d8ba3fae6436fb6/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9182933a-b643-43f5-b9d7-b13cd6061ee6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5ed8626b5216653a53bf098d0d8ba3fae6436fb6/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4d14cc8a-b9a6-4d2f-837e-e12a519105a2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5ed8626b5216653a53bf098d0d8ba3fae6436fb6/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 98 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f3e578c4-64ee-4288-9171-d123b8c58ab4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5ed8626b5216653a53bf098d0d8ba3fae6436fb6/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 95 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5055041e-f996-479d-a08c-0bff75eb9784) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5ed8626b5216653a53bf098d0d8ba3fae6436fb6/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7a3d53f4-d112-4be3-aef8-db0bf2bbdfed) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5ed8626b5216653a53bf098d0d8ba3fae6436fb6/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2f253f7b-b5e4-42f4-86cb-a213f0e90fc4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5ed8626b5216653a53bf098d0d8ba3fae6436fb6/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ba648401-5bf1-4d77-92d0-af7677ba63b5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5ed8626b5216653a53bf098d0d8ba3fae6436fb6/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 100 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c705e2b5-c278-481c-9e82-308a0aee8e16) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5ed8626b5216653a53bf098d0d8ba3fae6436fb6/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d1f3b628-2471-4ec6-bd22-1fcef6d66c61) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-08-23 13:40 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/3afa4373a70bbd04b5a329ff094c8c1b5db48116/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0921cfbc-a4f5-4442-8bc4-cd1c1aad65f4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3afa4373a70bbd04b5a329ff094c8c1b5db48116/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ea4354f0-a7ca-44a8-967f-4d8de8f51ffb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3afa4373a70bbd04b5a329ff094c8c1b5db48116/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2034c2e5-b4d3-4719-88d0-85c7f77363aa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3afa4373a70bbd04b5a329ff094c8c1b5db48116/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 98 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4544ebc0-aab9-4093-86ee-7eede9f04313) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3afa4373a70bbd04b5a329ff094c8c1b5db48116/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 95 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ccea29de-1a92-41e8-b025-961bd5157677) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3afa4373a70bbd04b5a329ff094c8c1b5db48116/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/80ccaae6-595d-4e9e-8916-13e78ff13756) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3afa4373a70bbd04b5a329ff094c8c1b5db48116/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7c591fff-abfe-4795-983f-722fc71ab110) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3afa4373a70bbd04b5a329ff094c8c1b5db48116/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c2c90ab2-d9c1-45e9-85ee-cfe56f5a3a66) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3afa4373a70bbd04b5a329ff094c8c1b5db48116/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 100 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1cbb53a8-a9a5-461d-93f4-c0f6628e48e7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3afa4373a70bbd04b5a329ff094c8c1b5db48116/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/286f3abb-4bfb-42d5-a892-793db84a48c2) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-09-12 09:13 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/37dd1b10c79c74f5c604fa603383036da3fe794d/msteams-platform%2FTOC.yml) | 99 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/353c74ed-ba3d-40cb-bd8d-3bff07951aed) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/37dd1b10c79c74f5c604fa603383036da3fe794d/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/142043cc-72d9-431f-b132-486348a2c28a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/37dd1b10c79c74f5c604fa603383036da3fe794d/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 95 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5f70b83d-f242-48b0-856c-7e607cb95b11) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/37dd1b10c79c74f5c604fa603383036da3fe794d/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 95 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/20fbf3cb-e8d0-42bf-8205-cb0fb1b6ddd7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/37dd1b10c79c74f5c604fa603383036da3fe794d/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 94 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c9a76f6d-af38-467d-ba87-6907ae231784) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/37dd1b10c79c74f5c604fa603383036da3fe794d/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6b443e0d-cb32-4702-b928-8d09a57a4152) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/37dd1b10c79c74f5c604fa603383036da3fe794d/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/957ab5bc-b711-40df-8a99-654b101da8b8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/37dd1b10c79c74f5c604fa603383036da3fe794d/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 100 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d6c681d4-aa9b-4dc0-9c2a-53f1a7618a9a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/37dd1b10c79c74f5c604fa603383036da3fe794d/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3827bc7c-0a3c-4ce2-a800-281f10b9e791) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-09-12 12:25 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a09e0db111a9d6abf532a3ca5ea72945bcebfba6/msteams-platform%2FTOC.yml) | 99 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b45a0f33-6fba-4b2d-8ee7-747a2a2df1a9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a09e0db111a9d6abf532a3ca5ea72945bcebfba6/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a65543aa-00ce-44ec-b229-460efa2b0d7d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a09e0db111a9d6abf532a3ca5ea72945bcebfba6/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 95 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/59448db4-49d4-42f9-b967-0f8dded6db84) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a09e0db111a9d6abf532a3ca5ea72945bcebfba6/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 95 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fb791e98-386b-46ac-af67-ce49ab175dc8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a09e0db111a9d6abf532a3ca5ea72945bcebfba6/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 95 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a6c08ad9-2cca-46c9-97d3-82cc94b04c50) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a09e0db111a9d6abf532a3ca5ea72945bcebfba6/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f350e1be-4c0e-469b-88ef-680cc8d1c65c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a09e0db111a9d6abf532a3ca5ea72945bcebfba6/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/06ab3cd9-f186-4834-bd28-5249222ee232) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a09e0db111a9d6abf532a3ca5ea72945bcebfba6/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 100 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/71b74640-3167-41d9-8ffe-a61d8721b494) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a09e0db111a9d6abf532a3ca5ea72945bcebfba6/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3f9fcb81-7cc0-4d2d-a878-594a4276cfc0) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-09-12 12:29 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/6b92a7a2d2606f76dca783bbc7ac4b99dd821f28/msteams-platform%2FTOC.yml) | 99 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/54c21295-a886-4ee6-b3b2-7db4ca32184f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6b92a7a2d2606f76dca783bbc7ac4b99dd821f28/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6bf6ed4f-14b8-4607-8d93-b3d520103271) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6b92a7a2d2606f76dca783bbc7ac4b99dd821f28/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 95 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ff9efca2-740c-406f-b9bb-9ba6831a3433) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6b92a7a2d2606f76dca783bbc7ac4b99dd821f28/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 95 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/118ce17d-d2ed-4764-aa60-5afedc80977d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6b92a7a2d2606f76dca783bbc7ac4b99dd821f28/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 95 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5875466c-0f60-477b-96a4-68bbd6189280) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6b92a7a2d2606f76dca783bbc7ac4b99dd821f28/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d3e94b5f-0c35-42a1-aa66-ae1494006b17) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6b92a7a2d2606f76dca783bbc7ac4b99dd821f28/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/741a077c-851b-4e07-9ca4-cd44fc0b9ed8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6b92a7a2d2606f76dca783bbc7ac4b99dd821f28/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 100 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d66b4f96-81a3-4475-9642-c75c0c6ed1c1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6b92a7a2d2606f76dca783bbc7ac4b99dd821f28/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9a1540ea-0a64-4441-86e4-8ed08974b8af) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-09-12 13:34 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c79fa04e76876ba8e98b301915560ee60cab205d/msteams-platform%2FTOC.yml) | 99 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/98ad2d33-9946-4e61-acd3-f98c2a409483) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c79fa04e76876ba8e98b301915560ee60cab205d/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/83ea650e-df46-4bf7-bb2d-4439e7229bca) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c79fa04e76876ba8e98b301915560ee60cab205d/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 95 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6f0755b1-94a1-496d-bca8-ab8ed868a593) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c79fa04e76876ba8e98b301915560ee60cab205d/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 100 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/09dd07b2-ab21-4265-9d1b-0e26c2b47336) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c79fa04e76876ba8e98b301915560ee60cab205d/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 95 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3b07f46a-cebc-44f1-9458-db81592d3739) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c79fa04e76876ba8e98b301915560ee60cab205d/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 94 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/26680ef6-c24d-4b8f-8976-8ad1edc6ec82) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c79fa04e76876ba8e98b301915560ee60cab205d/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6738c151-f6a6-4cd4-a810-385e7cc3e93b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c79fa04e76876ba8e98b301915560ee60cab205d/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6589b7c5-3bb7-4a4f-bd6a-8a7acccecf37) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c79fa04e76876ba8e98b301915560ee60cab205d/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 100 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/651d63e7-ac58-463d-8ef0-86ef49f3538d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c79fa04e76876ba8e98b301915560ee60cab205d/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f8c5444b-a4ad-4ed8-84c7-f6ce257f164f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-09-13 11:52 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/db4f78ab61cb4cb7ca8031922d6e5a34790d7a84/msteams-platform%2FTOC.yml) | 99 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d70b0b43-1c63-406b-9224-9aa85109602e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/db4f78ab61cb4cb7ca8031922d6e5a34790d7a84/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6f40b1b5-0419-408f-a189-dbfdf45f9f17) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/db4f78ab61cb4cb7ca8031922d6e5a34790d7a84/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 95 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9094bad8-2000-438a-b892-3f8cc31b3743) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/db4f78ab61cb4cb7ca8031922d6e5a34790d7a84/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 100 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/512d82c5-39a7-4f3e-8d63-c2421ae8d3bf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/db4f78ab61cb4cb7ca8031922d6e5a34790d7a84/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 95 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/10549aeb-9ad4-4bd2-8418-347c61c43c91) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/db4f78ab61cb4cb7ca8031922d6e5a34790d7a84/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 94 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/56e54c4b-e748-412d-aced-a662276ed9e8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/db4f78ab61cb4cb7ca8031922d6e5a34790d7a84/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/83cd4c90-3f6b-486b-b26d-666a412cca4e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/db4f78ab61cb4cb7ca8031922d6e5a34790d7a84/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ac6fa7eb-5ee0-4f7f-8428-6b13acc6b336) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/db4f78ab61cb4cb7ca8031922d6e5a34790d7a84/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 100 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ecf89966-91c1-4561-acd9-0e37a2414c67) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/db4f78ab61cb4cb7ca8031922d6e5a34790d7a84/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/de4e4cfa-2e0e-4b56-a3ed-584ddabe6c9c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-09-14 12:50 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/829486d99d50d802f66dc2398bb3bc6d4bcadd8d/msteams-platform%2FTOC.yml) | 99 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7ef3d24d-83ca-4d50-97b3-6f6ad47f6691) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/829486d99d50d802f66dc2398bb3bc6d4bcadd8d/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fb0ecf40-c73f-4aa5-8c43-f31ab0bb74fc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/829486d99d50d802f66dc2398bb3bc6d4bcadd8d/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 95 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b9eb01fd-2550-4922-b888-ca6d33a06f1a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/829486d99d50d802f66dc2398bb3bc6d4bcadd8d/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 100 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0d82afa5-79a9-4b93-86d7-0d26e6f96cdb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/829486d99d50d802f66dc2398bb3bc6d4bcadd8d/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 95 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ab93cd85-7dd0-468d-9c1a-f6d2dd077ff8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/829486d99d50d802f66dc2398bb3bc6d4bcadd8d/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 94 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3b537585-0289-4825-95f0-5909f98e7c2e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/829486d99d50d802f66dc2398bb3bc6d4bcadd8d/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/07c06863-6199-4ac2-bd36-a10bd9198ced) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/829486d99d50d802f66dc2398bb3bc6d4bcadd8d/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/591236a4-e02f-40a4-9145-28d6fa9e7c20) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/829486d99d50d802f66dc2398bb3bc6d4bcadd8d/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 100 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c92d4b58-72fe-4266-a690-edd0e472fc00) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/829486d99d50d802f66dc2398bb3bc6d4bcadd8d/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/593e148e-63d7-4a7c-9df8-26e45f58b0b5) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-09-18 13:28 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/da5d584e97853d9fecfaa67c54b0ed0cb4639e72/msteams-platform%2FTOC.yml) | 99 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7bb4ef48-cb9c-409e-948b-a607b26145a3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/da5d584e97853d9fecfaa67c54b0ed0cb4639e72/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8d6d1cea-1c47-40d1-bf9c-561b5b2aa340) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/da5d584e97853d9fecfaa67c54b0ed0cb4639e72/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 95 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e34e7d08-cd4b-4479-bd3b-6fa2b5c07f70) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/da5d584e97853d9fecfaa67c54b0ed0cb4639e72/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 100 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/859c25f0-eca0-4116-9847-d8b0cf78c1cc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/da5d584e97853d9fecfaa67c54b0ed0cb4639e72/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 95 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d376a24d-cf5d-461a-a16f-77bd0a94482f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/da5d584e97853d9fecfaa67c54b0ed0cb4639e72/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 94 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/863c8109-daf8-4592-a27d-f274e1b9bd6c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/da5d584e97853d9fecfaa67c54b0ed0cb4639e72/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c04c6743-80c0-4af4-97ab-b32fbf3da2a1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/da5d584e97853d9fecfaa67c54b0ed0cb4639e72/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/59818ce1-c4e8-4b49-ab37-7e51ce8b8163) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/da5d584e97853d9fecfaa67c54b0ed0cb4639e72/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 100 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/32ece35f-1de5-4bba-8ba4-c60fe1436119) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/da5d584e97853d9fecfaa67c54b0ed0cb4639e72/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/16ffd3e8-0759-48e2-81ee-d54b5ecb8806) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-09-18 15:59 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/d2db49de4c07866f36a12fdba4379ded188dadef/msteams-platform%2FTOC.yml) | 99 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7839e54c-2b72-4724-a0cf-bf50d015808a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d2db49de4c07866f36a12fdba4379ded188dadef/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d133f1d2-996c-46aa-8352-54043e3bf605) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d2db49de4c07866f36a12fdba4379ded188dadef/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 95 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f2f03d5e-361f-4933-a66a-ba19fcd7b9fd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d2db49de4c07866f36a12fdba4379ded188dadef/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 100 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6ad22042-ff89-4dc6-9ac1-217111ee1f00) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d2db49de4c07866f36a12fdba4379ded188dadef/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 95 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c6ab5238-1dd8-4b9d-831f-449df96c42d4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d2db49de4c07866f36a12fdba4379ded188dadef/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 94 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/852177bd-0bbf-4cc9-a07a-3fcff12c64ce) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d2db49de4c07866f36a12fdba4379ded188dadef/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/484aef81-4737-419a-9d6f-44d6bcd886b6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d2db49de4c07866f36a12fdba4379ded188dadef/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/db82a2e8-10e5-49d0-a458-42886299419e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d2db49de4c07866f36a12fdba4379ded188dadef/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 100 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b364ffd4-96e9-4a26-9cea-c5c2c61d4079) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d2db49de4c07866f36a12fdba4379ded188dadef/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/da47fb0b-3f7a-4b34-a1a6-5390de6e5c22) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-09-19 06:30 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/0656de4fa9aabb8033e894bcbc6bfde0cf4be647/msteams-platform%2FTOC.yml) | 99 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b73669d2-d679-46d5-88c4-c666b4096c54) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0656de4fa9aabb8033e894bcbc6bfde0cf4be647/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dd5bb654-9c2d-48fc-aca1-1b5d40d44e10) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0656de4fa9aabb8033e894bcbc6bfde0cf4be647/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 95 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4014000f-f9d7-47f9-887b-e714d1db2fa4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0656de4fa9aabb8033e894bcbc6bfde0cf4be647/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 100 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ce8ec87e-7be4-4157-91d4-9681a233d16e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0656de4fa9aabb8033e894bcbc6bfde0cf4be647/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 95 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/33feb177-5c9a-4dc8-ab53-3cbe7079045b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0656de4fa9aabb8033e894bcbc6bfde0cf4be647/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 94 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e845359d-63bc-421b-9856-fd4a11a8784a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0656de4fa9aabb8033e894bcbc6bfde0cf4be647/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/42af9351-9bb6-495f-904f-519a0d5be26e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0656de4fa9aabb8033e894bcbc6bfde0cf4be647/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/df4960d5-3daa-4147-acb4-4f4ee352dd6a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0656de4fa9aabb8033e894bcbc6bfde0cf4be647/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 100 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/12692b31-eea9-45c8-a0e2-595cefa274e4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0656de4fa9aabb8033e894bcbc6bfde0cf4be647/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9934d5c7-d33b-4085-8df4-64b32ba717de) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-09-19 13:33 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/3636f10f4f9e1f22ebb628956d67cef5ac67205a/msteams-platform%2FTOC.yml) | 99 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d20da36c-c85b-4f04-ab94-4b397c1cb920) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3636f10f4f9e1f22ebb628956d67cef5ac67205a/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/415be2b3-5a1c-46ca-892b-e186414d76bb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3636f10f4f9e1f22ebb628956d67cef5ac67205a/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e8253087-0882-47e3-ae34-f77de031774e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3636f10f4f9e1f22ebb628956d67cef5ac67205a/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 100 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6ea75049-33eb-4651-8588-07ca13d4e0ac) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3636f10f4f9e1f22ebb628956d67cef5ac67205a/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 95 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b823a6f6-3c1c-4ba8-8e98-c676af007dab) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3636f10f4f9e1f22ebb628956d67cef5ac67205a/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 94 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3daa2ca6-7b16-4d49-89b5-aebad285d53d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3636f10f4f9e1f22ebb628956d67cef5ac67205a/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 99 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d96115e4-f005-4c61-bc09-9d8eba6b3945) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3636f10f4f9e1f22ebb628956d67cef5ac67205a/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4f135257-efcf-4f6c-9d24-d2cb86267efa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3636f10f4f9e1f22ebb628956d67cef5ac67205a/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 100 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ae886029-b58d-4cec-8394-68da45185f61) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3636f10f4f9e1f22ebb628956d67cef5ac67205a/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/32671325-c3ac-48a2-9dd5-73f9bbbfa372) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-09-20 07:18 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/82feedc6274422ac8378588ec0a44e1bb8293ab7/msteams-platform%2FTOC.yml) | 99 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5bddf65e-9be1-41bf-8fda-eef704901f0b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/82feedc6274422ac8378588ec0a44e1bb8293ab7/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e3597cb4-a4e8-40fc-a30c-0df8c8bfe05a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/82feedc6274422ac8378588ec0a44e1bb8293ab7/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 96 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/74616ac7-b487-4103-bfd2-e6e879629386) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/82feedc6274422ac8378588ec0a44e1bb8293ab7/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f91666bf-28ed-4a40-89ec-9ef9186537d2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/82feedc6274422ac8378588ec0a44e1bb8293ab7/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 95 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f64bbfc7-a7aa-4e45-ba72-46a653db55e0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/82feedc6274422ac8378588ec0a44e1bb8293ab7/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 94 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/46d35480-46e4-4009-a024-52f269c8f980) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/82feedc6274422ac8378588ec0a44e1bb8293ab7/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 99 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1e71fd65-c54b-4ba6-b128-7d1848b771a4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/82feedc6274422ac8378588ec0a44e1bb8293ab7/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 97 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cfbcba12-8fe5-4745-8d8e-0d3fee1b42a7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/82feedc6274422ac8378588ec0a44e1bb8293ab7/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 99 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/663a406c-21d0-49bb-9397-96751539e22a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/82feedc6274422ac8378588ec0a44e1bb8293ab7/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/04b34f07-8191-41e2-b983-bc0c570326ad) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-09-20 13:09 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/7d67f8732e8ff0a330f7d535d17386c9b692faf3/msteams-platform%2FTOC.yml) | 99 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d6b8a97a-6636-4671-a7ac-4428c1770e7c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7d67f8732e8ff0a330f7d535d17386c9b692faf3/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3c1d4f86-d3bc-4c48-b953-c4f70607e9bc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7d67f8732e8ff0a330f7d535d17386c9b692faf3/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 96 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/be85c1f7-6406-4add-8cbc-2bcce47eefbf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7d67f8732e8ff0a330f7d535d17386c9b692faf3/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/baff70ce-59b8-4410-befe-cb1101681028) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7d67f8732e8ff0a330f7d535d17386c9b692faf3/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 95 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e94c6ab1-0ecc-4347-843c-e95982ea7386) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7d67f8732e8ff0a330f7d535d17386c9b692faf3/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0f744747-b3db-4d58-9318-5b874774d73e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7d67f8732e8ff0a330f7d535d17386c9b692faf3/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 99 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a512375d-7747-4b07-b794-934b7ed06e0c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7d67f8732e8ff0a330f7d535d17386c9b692faf3/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 97 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ff24c0ae-5f81-41af-831e-03b072c06103) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7d67f8732e8ff0a330f7d535d17386c9b692faf3/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 99 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7cf10920-326a-49aa-ba31-0f6341c6b19b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7d67f8732e8ff0a330f7d535d17386c9b692faf3/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/639e33b6-37ed-4086-8615-6a8da12ad9ea) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-09-28 05:27 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/794a6a23d1948550429132f4ac80ea4df83bc5ce/msteams-platform%2FTOC.yml) | 99 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e578440a-a704-4922-b1fa-4df8451d0e50) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/794a6a23d1948550429132f4ac80ea4df83bc5ce/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ee8f138a-dbbb-4334-bbb3-c7b2b0cd2cfc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/794a6a23d1948550429132f4ac80ea4df83bc5ce/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dc6e2315-10dd-405c-baaf-1fa04ff643dd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/794a6a23d1948550429132f4ac80ea4df83bc5ce/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 95 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/472ac45e-5c43-4837-82d8-714720927c8f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/794a6a23d1948550429132f4ac80ea4df83bc5ce/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 95 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f1e0b380-87a4-40a4-87b8-54a0e1b35e88) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/794a6a23d1948550429132f4ac80ea4df83bc5ce/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 95 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/38d54922-ee22-4fcd-9ff1-58811d7c552f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/794a6a23d1948550429132f4ac80ea4df83bc5ce/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 99 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/eb0bd2d1-e538-4986-8c53-c4398e55f0c3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/794a6a23d1948550429132f4ac80ea4df83bc5ce/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3436ff84-b348-4230-93f5-0c88471d3f5e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/794a6a23d1948550429132f4ac80ea4df83bc5ce/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 100 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f73e8edd-9907-4571-a124-8b61cb12c5f3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/794a6a23d1948550429132f4ac80ea4df83bc5ce/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fd60402b-8858-4e59-9044-f5f34e29e7d4) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-09-28 09:43 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/b91c401cf1c4518db09235fcb02abb89608622b3/msteams-platform%2FTOC.yml) | 99 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/536f7fe7-03d1-453b-9a68-b4b040a724ef) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b91c401cf1c4518db09235fcb02abb89608622b3/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/eb654e90-995a-4039-9560-cc0be6f78f5c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b91c401cf1c4518db09235fcb02abb89608622b3/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c2c57207-ab01-4cda-8bff-0b5e69f62397) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b91c401cf1c4518db09235fcb02abb89608622b3/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 95 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5315ab34-eff8-4e7e-9b48-cac031b3111c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b91c401cf1c4518db09235fcb02abb89608622b3/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 95 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e09c54ba-87e2-4053-b4f4-1aa0a11c08fd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b91c401cf1c4518db09235fcb02abb89608622b3/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 95 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4ecb14f0-08e2-4c81-8c70-8cb555be35f9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b91c401cf1c4518db09235fcb02abb89608622b3/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 99 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9ba475dc-71d3-4b1a-a887-2873805a18fe) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b91c401cf1c4518db09235fcb02abb89608622b3/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0548530e-1aca-4321-ba7e-5bea9945c1f2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b91c401cf1c4518db09235fcb02abb89608622b3/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 100 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d6ea9da3-1258-4565-8475-2618989ebc31) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b91c401cf1c4518db09235fcb02abb89608622b3/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/117cd947-c70f-49b9-b4c4-40dc2db19d3b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-10-03 07:38 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/45d83550bf78427614073ddc31780735d6c4436e/msteams-platform%2FTOC.yml) | 99 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/daa1c924-f28c-4273-9be1-f33c971a9de2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/45d83550bf78427614073ddc31780735d6c4436e/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2c618bd2-c7bd-4d7b-8392-93096d391d01) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/45d83550bf78427614073ddc31780735d6c4436e/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/71b50346-3b65-46f4-a27a-100b4ec2ff29) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/45d83550bf78427614073ddc31780735d6c4436e/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 95 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/584c916f-3100-41da-86c1-24a87550ced6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/45d83550bf78427614073ddc31780735d6c4436e/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 95 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b959f024-96ac-4800-9644-bfaa6159c9ef) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/45d83550bf78427614073ddc31780735d6c4436e/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 95 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/98fbc241-774a-4d41-85e2-9ba69d61d22c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/45d83550bf78427614073ddc31780735d6c4436e/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 99 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/18d4e1f2-e75a-4c63-a80e-d8b276284229) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/45d83550bf78427614073ddc31780735d6c4436e/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/420e1ab4-2f7c-49c0-ba6e-fc58b9c64788) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/45d83550bf78427614073ddc31780735d6c4436e/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 100 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5f948e8b-287c-458a-b594-23b6309bd479) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/45d83550bf78427614073ddc31780735d6c4436e/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b056aa74-008d-4fa7-a7ce-6db2b3dbf108) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-10-03 14:49 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/fa1af499d0b1c033c94e5501a1ab44c65d72f2f3/msteams-platform%2FTOC.yml) | 99 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6bc9b4a4-2703-4cb8-9c29-ebdf651e62c8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fa1af499d0b1c033c94e5501a1ab44c65d72f2f3/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4f160420-b189-47dd-a30e-7b2a9ac8c275) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fa1af499d0b1c033c94e5501a1ab44c65d72f2f3/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 94 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a033c5d0-ad87-459f-be4c-6668cfa734e7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fa1af499d0b1c033c94e5501a1ab44c65d72f2f3/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 95 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4e8e9f8c-bea6-4a35-8789-7b69aff79dca) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fa1af499d0b1c033c94e5501a1ab44c65d72f2f3/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 95 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/05f52f21-0219-40e1-9819-1cf071f34d7e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fa1af499d0b1c033c94e5501a1ab44c65d72f2f3/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 94 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fe98b58a-97cf-498a-a0cb-63dd05f22941) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fa1af499d0b1c033c94e5501a1ab44c65d72f2f3/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 99 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/735e0205-ef96-4cb0-a724-784cbdfcee41) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fa1af499d0b1c033c94e5501a1ab44c65d72f2f3/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/15574348-ed81-4f7a-b4ea-6fd1a4ae3a8d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fa1af499d0b1c033c94e5501a1ab44c65d72f2f3/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 100 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7d250b51-4e50-49fe-a9b0-ce3890d73a96) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fa1af499d0b1c033c94e5501a1ab44c65d72f2f3/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2dc333f7-c3bd-4a3a-86cc-7c6c22ad3516) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-10-04 06:56 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e53289755e4f39acd13272d3b34b0578d7c31656/msteams-platform%2FTOC.yml) | 99 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/91d902f2-df29-4668-ac2b-12a78abcdb1c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e53289755e4f39acd13272d3b34b0578d7c31656/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4f80024c-b213-4ccf-bf2d-0a5f0924abc2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e53289755e4f39acd13272d3b34b0578d7c31656/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 94 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/45a900a9-3853-4cb0-9314-734b542495db) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e53289755e4f39acd13272d3b34b0578d7c31656/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 95 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/637bbda8-b304-4304-84c4-702042126e98) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e53289755e4f39acd13272d3b34b0578d7c31656/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 95 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ed98e6d8-e154-41de-8715-d138b3c7e906) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e53289755e4f39acd13272d3b34b0578d7c31656/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 94 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1b86263a-313f-4acb-bb17-f017e4c0bce3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e53289755e4f39acd13272d3b34b0578d7c31656/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 99 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4760efb6-d882-477d-ae81-51091216d526) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e53289755e4f39acd13272d3b34b0578d7c31656/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/96d94c1e-468d-4fc3-8cc0-068ff537174b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e53289755e4f39acd13272d3b34b0578d7c31656/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 100 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/13fbcf43-c1e7-4bc7-b1e5-b4a2d3aaba09) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e53289755e4f39acd13272d3b34b0578d7c31656/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6426a157-0d41-42f4-a8e3-4add2cbd6ab2) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-10-04 12:57 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/be7ab2e5b93027b76c28d99b1a587629a86c8311/msteams-platform%2FTOC.yml) | 99 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5f274460-7f3a-4947-9122-9c626eda683b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/be7ab2e5b93027b76c28d99b1a587629a86c8311/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/62e90d92-b7a2-45b1-92af-c66ba9203c62) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/be7ab2e5b93027b76c28d99b1a587629a86c8311/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 94 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2490ed02-b10c-4a29-8c6b-0449643b764a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/be7ab2e5b93027b76c28d99b1a587629a86c8311/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 95 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/02eb31d0-ab9f-4ba0-83fc-5614284f040f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/be7ab2e5b93027b76c28d99b1a587629a86c8311/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 95 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/84bb4e27-9ed0-47a7-90aa-146e5d2e156e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/be7ab2e5b93027b76c28d99b1a587629a86c8311/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 95 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/888c063a-b86d-408c-b7de-183217d9821e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/be7ab2e5b93027b76c28d99b1a587629a86c8311/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 98 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2578e254-c56a-49ad-ae3a-b3e61182fc8c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/be7ab2e5b93027b76c28d99b1a587629a86c8311/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ee0aa1a8-9cc1-4980-8088-801ac2a58618) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/be7ab2e5b93027b76c28d99b1a587629a86c8311/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 100 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/00c1dec6-0719-411b-b136-4608cdcae9e5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/be7ab2e5b93027b76c28d99b1a587629a86c8311/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e024e5a7-5994-40c1-9b18-788b09ff2023) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-10-04 13:43 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a0fb6720b3b8b6a86c4a08b3bfb03f3de6e3f290/msteams-platform%2FTOC.yml) | 99 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4dc9e249-7ea9-4194-b1a1-34a12206e38a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a0fb6720b3b8b6a86c4a08b3bfb03f3de6e3f290/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d93ed8ac-68a8-45ab-9f61-295fccdce18f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a0fb6720b3b8b6a86c4a08b3bfb03f3de6e3f290/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 94 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/eee78622-7dd1-49c0-862c-6ba377f5edbe) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a0fb6720b3b8b6a86c4a08b3bfb03f3de6e3f290/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 95 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7e2aef42-d8b3-433d-a69e-3694f6b19c81) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a0fb6720b3b8b6a86c4a08b3bfb03f3de6e3f290/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 95 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5d5a11d7-3b5b-4c0f-b6e2-c88f375ac575) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a0fb6720b3b8b6a86c4a08b3bfb03f3de6e3f290/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 95 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b893a134-65c1-4cdf-85fc-f3becd8f85be) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a0fb6720b3b8b6a86c4a08b3bfb03f3de6e3f290/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 98 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ad3e69c2-b20d-4182-a72d-bef1e3d7538a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a0fb6720b3b8b6a86c4a08b3bfb03f3de6e3f290/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d389a5db-d465-4184-a8a9-4a320c5f1280) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a0fb6720b3b8b6a86c4a08b3bfb03f3de6e3f290/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 100 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/600c0f3e-1f0c-46df-a759-1c83462aba3e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a0fb6720b3b8b6a86c4a08b3bfb03f3de6e3f290/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6df1b2ed-ca2c-4009-9987-2bd6f4cab02c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-10-23 11:56 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ec96600e392379356deca520e5a2ba4668e7ce01/msteams-platform%2FTOC.yml) | 99 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1efd48ee-a756-4cfe-94bd-c4cff38b8ccd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ec96600e392379356deca520e5a2ba4668e7ce01/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/14fe3040-fa13-4c8f-9baa-46e8fa8b4d0e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ec96600e392379356deca520e5a2ba4668e7ce01/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 94 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2c065020-9c68-4903-90e6-4b4b26ae85ce) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ec96600e392379356deca520e5a2ba4668e7ce01/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 95 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ee07c512-a370-4a2f-b961-7e03e194c523) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ec96600e392379356deca520e5a2ba4668e7ce01/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 95 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/29064bf7-8b18-48a4-8504-b758228de967) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ec96600e392379356deca520e5a2ba4668e7ce01/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 95 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3476fb98-2cf1-4271-aa23-e96d42f4a8ba) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ec96600e392379356deca520e5a2ba4668e7ce01/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 98 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/47e61ee8-bdd1-4c00-96e3-2fd5f7a6437a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ec96600e392379356deca520e5a2ba4668e7ce01/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fb0d346e-9ca4-4114-824b-6a8919a1d278) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ec96600e392379356deca520e5a2ba4668e7ce01/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 100 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9e0ac23f-6d4c-436f-b0f8-032361c9a367) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ec96600e392379356deca520e5a2ba4668e7ce01/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2d4f0548-c145-4744-943b-135b8b1e7848) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-10-27 10:43 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/8b655b9577ac5132bb69cc1329f5b00541c1718a/msteams-platform%2FTOC.yml) | 99 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d9475cbb-f618-4ec5-926c-994aa4538d0b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8b655b9577ac5132bb69cc1329f5b00541c1718a/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/06c4f284-625d-4d4e-bb46-0796954d6cd3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8b655b9577ac5132bb69cc1329f5b00541c1718a/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 94 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/41f4611b-2d4d-4304-9b38-86fa6c866e97) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8b655b9577ac5132bb69cc1329f5b00541c1718a/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 95 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1d57d189-da08-45a0-be8b-d42c923680d3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8b655b9577ac5132bb69cc1329f5b00541c1718a/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 95 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/faf17ef9-d4c2-450d-aa99-4426d56c1ef1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8b655b9577ac5132bb69cc1329f5b00541c1718a/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 95 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/02bd3c0c-20c9-4357-9e65-64540dae4c4b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8b655b9577ac5132bb69cc1329f5b00541c1718a/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 98 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/82a35f25-aa23-45e3-bf35-87be92201d72) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8b655b9577ac5132bb69cc1329f5b00541c1718a/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f8a73311-05dd-4aa8-8c59-7c54d10f7726) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8b655b9577ac5132bb69cc1329f5b00541c1718a/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 100 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/818cebed-3730-40ee-b773-6207b8ff90fa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8b655b9577ac5132bb69cc1329f5b00541c1718a/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9a3427fa-07bf-4693-97b7-2ccfc8bd60f6) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-10-27 13:23 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/3895363e571a24d0800d50468eebeef5ede69cb5/msteams-platform%2FTOC.yml) | 99 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7f54a541-a190-4b65-acf2-48ace2060281) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3895363e571a24d0800d50468eebeef5ede69cb5/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9ba94613-2850-4921-8198-786f861865d1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3895363e571a24d0800d50468eebeef5ede69cb5/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 94 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aadedbad-b1a5-4966-a7fb-5d79a9662a5b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3895363e571a24d0800d50468eebeef5ede69cb5/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 95 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/824de7b2-82b3-4efb-b7a9-93931c9fcef1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3895363e571a24d0800d50468eebeef5ede69cb5/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 95 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cec03641-e3e0-4173-bfcc-d3adc031f3b5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3895363e571a24d0800d50468eebeef5ede69cb5/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 95 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bf491bd9-05b7-4c45-adcd-9452a0676896) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3895363e571a24d0800d50468eebeef5ede69cb5/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 98 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3ba8b951-24c8-4f45-8d63-3f33b7feb121) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3895363e571a24d0800d50468eebeef5ede69cb5/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/af97a170-0087-4d26-8dab-e21efbe88167) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3895363e571a24d0800d50468eebeef5ede69cb5/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 100 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/49d1f01d-a224-4607-ae1c-e0bda6a276d8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3895363e571a24d0800d50468eebeef5ede69cb5/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1fcf4dfb-4f81-410a-b82a-11a63de398a5) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-10-27 14:58 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/7428025c2acbca95b9a310cd66707a09eb3df3e9/msteams-platform%2FTOC.yml) | 99 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/88a6f095-b693-45dd-a4ac-c3fe1d304ac7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7428025c2acbca95b9a310cd66707a09eb3df3e9/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a99b280e-12b2-4ccb-b29a-7c2bf00f237b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7428025c2acbca95b9a310cd66707a09eb3df3e9/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 94 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/641c45ec-fe53-4e72-b219-336b97542a4d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7428025c2acbca95b9a310cd66707a09eb3df3e9/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 95 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1576e364-c61d-40b0-96fe-1a81fd9f3a16) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7428025c2acbca95b9a310cd66707a09eb3df3e9/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 95 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ed34deff-9f82-43ec-89d2-c0b4915288b5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7428025c2acbca95b9a310cd66707a09eb3df3e9/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 95 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6a44d153-a062-4e4f-a91a-206edd95ce8a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7428025c2acbca95b9a310cd66707a09eb3df3e9/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 98 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/85e085cd-167d-446e-b7b0-7c8625780945) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7428025c2acbca95b9a310cd66707a09eb3df3e9/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/426b2c5a-03a6-40fa-923c-8a2cbe7bda62) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7428025c2acbca95b9a310cd66707a09eb3df3e9/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 100 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/20b30171-a485-441d-8e9f-44ba393704ae) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7428025c2acbca95b9a310cd66707a09eb3df3e9/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/51f7e442-a8c7-413b-902b-3fe19dbaed3f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-12-07 05:02 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/87ad127b271007eb7de137907a66e3e932fac680/msteams-platform%2FTOC.yml) | 99 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/91cd137f-8da2-4756-b6ea-c3ef52f3667b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/87ad127b271007eb7de137907a66e3e932fac680/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 94 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4ab83d1c-e6c5-4ea7-9d08-4aa4a6c56d6d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/87ad127b271007eb7de137907a66e3e932fac680/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 94 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d842a710-0802-47c0-9d28-380623e8281b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/87ad127b271007eb7de137907a66e3e932fac680/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 90 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4103fcef-326c-4b75-bfb6-8d3b92701886) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/87ad127b271007eb7de137907a66e3e932fac680/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 95 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b709ad71-5e95-46c2-b6c5-972ac4336a29) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/87ad127b271007eb7de137907a66e3e932fac680/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 96 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b5a89a4f-4cc9-403f-a7de-91705d820ac1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/87ad127b271007eb7de137907a66e3e932fac680/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 95 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1a6ee446-e931-40b2-8c95-f0f16930ae54) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/87ad127b271007eb7de137907a66e3e932fac680/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/261ebaf5-1aff-4033-a3e5-86d212875a9c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/87ad127b271007eb7de137907a66e3e932fac680/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 96 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1169195c-a38c-4ed1-b9e7-b209b72a8386) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/87ad127b271007eb7de137907a66e3e932fac680/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 93 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a91c4905-c807-454f-a0ce-81047ee19f3b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-01-08 10:30 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/39b877a7e2756e1d9f62af3d5fd756be41e144f0/msteams-platform%2FTOC.yml) | 99 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/214de24f-aec9-4e1c-b9d9-01ba2b8b1110) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/39b877a7e2756e1d9f62af3d5fd756be41e144f0/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 94 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/503d33b8-79be-42fb-83c1-f8110b8e1625) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/39b877a7e2756e1d9f62af3d5fd756be41e144f0/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 94 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/98c99432-81c6-453c-b22b-41d8b091e5f4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/39b877a7e2756e1d9f62af3d5fd756be41e144f0/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 90 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/60276d88-a319-4e3e-a8dc-d90fd066ef4f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/39b877a7e2756e1d9f62af3d5fd756be41e144f0/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 95 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1acfa510-9ae6-4e90-86a0-57baf4b412cc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/39b877a7e2756e1d9f62af3d5fd756be41e144f0/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 96 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/68fdab58-e662-495d-b81b-a7552399b22d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/39b877a7e2756e1d9f62af3d5fd756be41e144f0/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 95 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/97153aad-2365-4ba1-b01b-a49257144e8d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/39b877a7e2756e1d9f62af3d5fd756be41e144f0/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/46a1d2cc-13e6-4ac7-bb58-85703a477b8f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/39b877a7e2756e1d9f62af3d5fd756be41e144f0/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 96 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/49dcb7ad-d8f8-4ecb-8345-14e26806d374) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/39b877a7e2756e1d9f62af3d5fd756be41e144f0/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 93 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/487e79de-ae34-4ae8-bd4f-0eedcd246961) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-01-18 08:37 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/571b410aa79d60e51b2abbe8e20db0d2fa284c5b/msteams-platform%2FTOC.yml) | 99 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/27a32c8d-d366-4641-96a1-ae27ef26ebd4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/571b410aa79d60e51b2abbe8e20db0d2fa284c5b/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 94 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3a768407-7e58-4414-9dd8-68b066f2a8a4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/571b410aa79d60e51b2abbe8e20db0d2fa284c5b/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 94 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cf248825-9423-401c-901a-94b3b2496149) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/571b410aa79d60e51b2abbe8e20db0d2fa284c5b/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 90 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e966f9ef-ce43-4708-903c-7165f6d74289) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/571b410aa79d60e51b2abbe8e20db0d2fa284c5b/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 95 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c51a6d38-a862-4efd-8369-b367604a7781) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/571b410aa79d60e51b2abbe8e20db0d2fa284c5b/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 96 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d72dfb78-fc23-4355-b9c5-5c513b4e1c6a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/571b410aa79d60e51b2abbe8e20db0d2fa284c5b/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 95 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b47e8181-6cec-44ff-820e-a840928d82a6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/571b410aa79d60e51b2abbe8e20db0d2fa284c5b/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b4393102-bd64-425b-b09c-f2b2cb5d1b26) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/571b410aa79d60e51b2abbe8e20db0d2fa284c5b/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 96 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8b5eca06-f797-45df-acda-e79e992e847a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/571b410aa79d60e51b2abbe8e20db0d2fa284c5b/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 93 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b520a5a2-fe0a-4aae-af1f-c38bb8434039) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-01-18 13:36 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/b2e2d0fd520e8ab30478c1a983ea281ed8b6a801/msteams-platform%2FTOC.yml) | 99 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1b10bfc1-5811-420e-960a-86ae93718e50) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b2e2d0fd520e8ab30478c1a983ea281ed8b6a801/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 94 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/66716d14-8074-45b4-a8d3-ece4b35e925e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b2e2d0fd520e8ab30478c1a983ea281ed8b6a801/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 94 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a8c1140d-63d7-4901-89eb-aded46c2338b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b2e2d0fd520e8ab30478c1a983ea281ed8b6a801/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 90 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1456f68e-7828-466a-896d-d8366e8b8810) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b2e2d0fd520e8ab30478c1a983ea281ed8b6a801/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 95 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3cba8047-0ac9-4324-b192-2e80beb9d24d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b2e2d0fd520e8ab30478c1a983ea281ed8b6a801/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 96 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/163975d6-b90c-4caf-850d-9cfe652871d1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b2e2d0fd520e8ab30478c1a983ea281ed8b6a801/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 95 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d54c9219-8013-4bf2-89aa-f37bd1223ab2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b2e2d0fd520e8ab30478c1a983ea281ed8b6a801/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/49a083c6-1fe2-49a4-8f42-241ae9b1cb5c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b2e2d0fd520e8ab30478c1a983ea281ed8b6a801/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 96 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/058a9cb5-dd87-441d-a65a-58c43e92b785) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b2e2d0fd520e8ab30478c1a983ea281ed8b6a801/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 93 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/658d5b81-9916-4e8b-9a3f-e68e2b84a337) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-01-19 05:28 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1d8528d5a5784a002813ebb8b4d39015127217c0/msteams-platform%2FTOC.yml) | 99 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1a82afab-7801-4d42-861b-79f0178b3d52) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1d8528d5a5784a002813ebb8b4d39015127217c0/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 94 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e77e78be-678e-48dd-b5ea-90202df60108) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1d8528d5a5784a002813ebb8b4d39015127217c0/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 94 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d88011d9-b921-4462-adf9-cbede6177049) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1d8528d5a5784a002813ebb8b4d39015127217c0/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 90 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/98f8cbe7-1050-484d-92a6-4444168996d0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1d8528d5a5784a002813ebb8b4d39015127217c0/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 95 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e805c115-ff46-4186-94ef-43176ae23cb5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1d8528d5a5784a002813ebb8b4d39015127217c0/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 96 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3aa30bcb-f53b-43c1-9ce0-9badfd074a1d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1d8528d5a5784a002813ebb8b4d39015127217c0/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 95 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a9c2da8f-484b-4ec1-b64b-d33025c17bed) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1d8528d5a5784a002813ebb8b4d39015127217c0/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bc2b6e81-89a1-4b21-a8da-708c79c6883d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1d8528d5a5784a002813ebb8b4d39015127217c0/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 96 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ecb67a41-f356-47ec-b9da-ddcdb61a00e3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1d8528d5a5784a002813ebb8b4d39015127217c0/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 93 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6f40e3cc-badb-42d0-8fdb-3451615e9732) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-01-19 12:58 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/7f982a1b638b7260564993a4912308252e1183f7/msteams-platform%2FTOC.yml) | 99 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/835cf214-4a5c-4fbd-bed3-547196df5212) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7f982a1b638b7260564993a4912308252e1183f7/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 94 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/eedfce3c-0809-457e-92b0-cae9c13bd7ef) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7f982a1b638b7260564993a4912308252e1183f7/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 94 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8af09a98-29cf-41a4-91f8-c5b061fffb34) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7f982a1b638b7260564993a4912308252e1183f7/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 90 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2934d5e5-86d7-4fcc-aab4-4e06b9551285) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7f982a1b638b7260564993a4912308252e1183f7/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 95 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9fa22fe6-a34a-4777-945d-48efb670ee2f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7f982a1b638b7260564993a4912308252e1183f7/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 96 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8e4dea6e-7efb-434a-a414-416e87fd2a82) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7f982a1b638b7260564993a4912308252e1183f7/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 95 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/08e40acd-a7cc-4b51-b37f-0ca5ca1359d0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7f982a1b638b7260564993a4912308252e1183f7/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4e0d32ad-4d1c-42fd-b894-423c708b08ee) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7f982a1b638b7260564993a4912308252e1183f7/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 96 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7d6afbbc-b515-47a8-ae21-db49dc42ded0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7f982a1b638b7260564993a4912308252e1183f7/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 93 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/285f1f71-255b-4616-9bcd-ed023129b225) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-01-19 13:06 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a47f9adb4c7e9471bcbd3d5ac55acf013869069a/msteams-platform%2FTOC.yml) | 99 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f2358fdb-c06a-4bb8-9f2c-944378cd09b4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a47f9adb4c7e9471bcbd3d5ac55acf013869069a/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 94 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3b664241-dbb6-4538-a479-e1820c20554d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a47f9adb4c7e9471bcbd3d5ac55acf013869069a/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 94 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9d94af1f-6831-426c-bda3-f590c8969e2c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a47f9adb4c7e9471bcbd3d5ac55acf013869069a/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 90 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fa7d39e6-5faa-46b4-8d19-8cd9403be86e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a47f9adb4c7e9471bcbd3d5ac55acf013869069a/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 95 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5b561382-c24e-4c36-87c6-fc6b677b1c11) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a47f9adb4c7e9471bcbd3d5ac55acf013869069a/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 96 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d8d6340c-54a0-4f7a-9ba3-14599b30678d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a47f9adb4c7e9471bcbd3d5ac55acf013869069a/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 95 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/21d4dd9b-b5d4-4231-bb72-0ac0fa9d41b0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a47f9adb4c7e9471bcbd3d5ac55acf013869069a/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8a4be947-972f-45dd-9c51-05f038e2715a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a47f9adb4c7e9471bcbd3d5ac55acf013869069a/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 96 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8bba11f1-6bf7-4426-a966-220bc775923b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a47f9adb4c7e9471bcbd3d5ac55acf013869069a/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 93 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/69a73bba-95b6-4f78-b999-f63a80978e7d) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-01-22 08:24 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/d65440a9af21056afcaeef9301323d2ca0f9ff13/msteams-platform%2FTOC.yml) | 99 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b921f88a-19cd-4153-a879-9448ebd2d554) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d65440a9af21056afcaeef9301323d2ca0f9ff13/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 94 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7de9b704-5ebd-45d1-bd44-ffd396f62e02) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d65440a9af21056afcaeef9301323d2ca0f9ff13/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 94 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bf336fc4-ffea-4503-b58c-1ce008a613af) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d65440a9af21056afcaeef9301323d2ca0f9ff13/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 90 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5ef016dd-4019-4e23-8f46-a3439ff5fa4b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d65440a9af21056afcaeef9301323d2ca0f9ff13/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 95 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/11d2fef7-f9af-4a67-9e13-1ffa9033b6f5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d65440a9af21056afcaeef9301323d2ca0f9ff13/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 88 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0cf9e007-0ec9-48ac-b793-1b90b36b342a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d65440a9af21056afcaeef9301323d2ca0f9ff13/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 95 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ec5fed80-601c-49f9-a323-6b2310a02df3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d65440a9af21056afcaeef9301323d2ca0f9ff13/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e17a7dfd-65e3-4e23-b187-ec5ff1fd5638) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d65440a9af21056afcaeef9301323d2ca0f9ff13/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 96 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fd2d163e-5527-4189-81e9-06777587e047) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d65440a9af21056afcaeef9301323d2ca0f9ff13/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 93 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/566764a0-3303-4bea-bbe2-067fd9a4df80) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-01-23 08:46 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/dc8f8887bc6a6b79320348758188dfa80b85382c/msteams-platform%2FTOC.yml) | 99 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/71ae60ab-d77a-40b8-abcf-3da180063415) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dc8f8887bc6a6b79320348758188dfa80b85382c/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 94 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9251e9c3-d1bc-4afa-ae08-16f190286449) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dc8f8887bc6a6b79320348758188dfa80b85382c/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 94 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1813edf8-e34f-4ba3-9ea5-518df18c88cf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dc8f8887bc6a6b79320348758188dfa80b85382c/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 90 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c17996de-166b-40f5-b268-66ec81b8171e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dc8f8887bc6a6b79320348758188dfa80b85382c/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 95 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7cb4dc41-2700-4016-94f4-b87439c47998) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dc8f8887bc6a6b79320348758188dfa80b85382c/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 88 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ead8c202-4e06-48f3-b5ee-6c059ab59ebd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dc8f8887bc6a6b79320348758188dfa80b85382c/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 95 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5f2b49b4-bc97-4fde-aa4a-3088e5e29551) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dc8f8887bc6a6b79320348758188dfa80b85382c/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1dcbb88c-6092-46b6-9510-c4eb30982c38) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dc8f8887bc6a6b79320348758188dfa80b85382c/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 96 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9668e965-da86-47f6-94f9-f2e84dad0d1f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dc8f8887bc6a6b79320348758188dfa80b85382c/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 93 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c59ab552-2e1f-4b0b-ac4b-093dd138876b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-01-23 09:06 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a07f407bfbfc558deee46af3532f61ca578c0a17/msteams-platform%2FTOC.yml) | 99 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b0fe3635-e595-4d52-ac60-0fda0a4155d7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a07f407bfbfc558deee46af3532f61ca578c0a17/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 94 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/59f85129-c977-4828-8681-7a337e1b5bd2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a07f407bfbfc558deee46af3532f61ca578c0a17/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 94 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/688f386b-41fa-47ca-82cd-5a9f8eef7ed7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a07f407bfbfc558deee46af3532f61ca578c0a17/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 90 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/53153e1e-fb37-452e-be98-a7918b87c0f4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a07f407bfbfc558deee46af3532f61ca578c0a17/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 95 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c9cf6b71-e121-48c3-9fd7-0c8c51a03285) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a07f407bfbfc558deee46af3532f61ca578c0a17/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 97 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/573186bc-9300-4ec2-a4a7-c73398890f72) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a07f407bfbfc558deee46af3532f61ca578c0a17/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 95 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8526717e-ac1e-4f0f-a7a1-bff6617acbf3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a07f407bfbfc558deee46af3532f61ca578c0a17/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b22fc105-174f-465f-ac91-0e8fdf458aa8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a07f407bfbfc558deee46af3532f61ca578c0a17/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 96 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f0c77184-78ff-44df-82da-a2c457a9edae) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a07f407bfbfc558deee46af3532f61ca578c0a17/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 93 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f269d8ae-f43e-468a-bfcb-99ebcd18af13) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-01-23 09:15 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/f4d89c2767e78bf84d4e1672cfd2db34e43f3d11/msteams-platform%2FTOC.yml) | 99 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8c002ed6-6399-48bc-a342-5091b0595a31) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f4d89c2767e78bf84d4e1672cfd2db34e43f3d11/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 94 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/33baee1e-2f5b-4259-a64a-3d2b2b07764c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f4d89c2767e78bf84d4e1672cfd2db34e43f3d11/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 94 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/efa20249-9739-432f-a9d7-8174a0ff9931) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f4d89c2767e78bf84d4e1672cfd2db34e43f3d11/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 90 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d11f54eb-6689-489e-a652-3a5e3995930a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f4d89c2767e78bf84d4e1672cfd2db34e43f3d11/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 95 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a51a380d-7e9a-4654-8341-ec45cb68198a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f4d89c2767e78bf84d4e1672cfd2db34e43f3d11/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 97 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9bffaedc-6555-496d-9de2-bbc503d63d02) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f4d89c2767e78bf84d4e1672cfd2db34e43f3d11/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 95 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4029eee2-df79-4f6f-a4d9-47025de67e6f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f4d89c2767e78bf84d4e1672cfd2db34e43f3d11/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6694b399-4016-4009-a5d1-7f494d0d61db) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f4d89c2767e78bf84d4e1672cfd2db34e43f3d11/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 96 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6148ac60-aa3f-4b73-beef-0f8171969ea4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f4d89c2767e78bf84d4e1672cfd2db34e43f3d11/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 93 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bc2daba5-fabd-433a-9f30-8097c1760c98) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-01-25 09:39 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/0dc33fff6c7d5ce171992dcde6249be94eff2d6f/msteams-platform%2FTOC.yml) | 99 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cf019746-f8b8-472f-89a6-b86b080e8700) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0dc33fff6c7d5ce171992dcde6249be94eff2d6f/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 94 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4022b118-79e5-4986-b608-ab82c432af86) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0dc33fff6c7d5ce171992dcde6249be94eff2d6f/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 94 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a6bfa349-0f8a-44d5-94a2-cbdb21080043) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0dc33fff6c7d5ce171992dcde6249be94eff2d6f/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 90 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e8141457-1fb7-43a1-96fe-6a56e0d9fd80) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0dc33fff6c7d5ce171992dcde6249be94eff2d6f/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 95 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b1120593-f45f-4287-9120-bb00fc92bbd2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0dc33fff6c7d5ce171992dcde6249be94eff2d6f/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 97 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/842296f6-9200-43a7-8336-b8fe2b6d6dc9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0dc33fff6c7d5ce171992dcde6249be94eff2d6f/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 95 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/301f76ff-3846-432d-ace9-0841dd7aa86c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0dc33fff6c7d5ce171992dcde6249be94eff2d6f/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cc0022fb-8775-42aa-9b59-a44747fdf836) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0dc33fff6c7d5ce171992dcde6249be94eff2d6f/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 96 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/80dce3f9-fc7c-423e-be5d-ffa411e99bdf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0dc33fff6c7d5ce171992dcde6249be94eff2d6f/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 93 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9f0d2b9f-0a16-457e-b701-a55c77416214) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-01-25 15:12 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c439ef1ac6bd1cb2e9524cc60cf415f8b717a37d/msteams-platform%2FTOC.yml) | 99 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c7e0dbde-9ba5-4770-812b-36bbfa065908) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c439ef1ac6bd1cb2e9524cc60cf415f8b717a37d/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 94 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d8f74b58-a74e-4a45-8617-1f18b5fce0d2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c439ef1ac6bd1cb2e9524cc60cf415f8b717a37d/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 94 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cb3105cc-c18d-4477-a61f-c5347f9cde32) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c439ef1ac6bd1cb2e9524cc60cf415f8b717a37d/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 90 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/78c6b36c-fe6b-47be-9637-cf1a767d4fd3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c439ef1ac6bd1cb2e9524cc60cf415f8b717a37d/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 95 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7e7ec41d-8232-4814-90fa-061ac73f77d9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c439ef1ac6bd1cb2e9524cc60cf415f8b717a37d/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9d212456-9fef-4772-9c5f-bbf943a25d99) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c439ef1ac6bd1cb2e9524cc60cf415f8b717a37d/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 95 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6ba73088-5c54-4624-b3a0-bd263e200ee1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c439ef1ac6bd1cb2e9524cc60cf415f8b717a37d/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c343bdab-a09b-4b59-ab8a-985bd4d8a121) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c439ef1ac6bd1cb2e9524cc60cf415f8b717a37d/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 95 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/64ff77ad-bdb9-4630-a504-766ad6c0b7cb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c439ef1ac6bd1cb2e9524cc60cf415f8b717a37d/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 93 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/65e76c34-d850-456c-87c9-2271691dd466) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-01-30 04:20 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/349b28083de0ded7adf79459861c7eb10d2c079e/msteams-platform%2FTOC.yml) | 99 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9814a788-7f4d-4880-bd12-2c55c9ffbfea) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/349b28083de0ded7adf79459861c7eb10d2c079e/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 94 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cd298600-5f41-4485-98a3-154313ee0148) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/349b28083de0ded7adf79459861c7eb10d2c079e/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 94 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/16c98df7-0bd8-46cf-8d0b-8239e7dcd87b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/349b28083de0ded7adf79459861c7eb10d2c079e/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 90 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bdf424a5-064b-4ea1-aca7-ff42e6e35091) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/349b28083de0ded7adf79459861c7eb10d2c079e/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 95 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8b78f50e-2eee-46bd-b238-74750908158c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/349b28083de0ded7adf79459861c7eb10d2c079e/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6141218c-c692-46ad-a15e-87a6dd68f992) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/349b28083de0ded7adf79459861c7eb10d2c079e/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 95 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5fbefd10-6bda-4531-bc99-4d0c841e5665) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/349b28083de0ded7adf79459861c7eb10d2c079e/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bf26cf7f-e4ef-4fd7-90e3-08632e314dfc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/349b28083de0ded7adf79459861c7eb10d2c079e/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 95 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/190dff18-6115-4ebf-9996-249db29aa920) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/349b28083de0ded7adf79459861c7eb10d2c079e/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 93 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b8b9f278-613f-4d4f-b584-7862d4182a59) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-01-30 11:01 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/639fd56aa01ed0d4132d310a34395508c0311120/msteams-platform%2FTOC.yml) | 99 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c002ae21-96d1-4ee4-9d35-c579275a590d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/639fd56aa01ed0d4132d310a34395508c0311120/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 94 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fb53e403-1744-4fca-8258-5237934d0cea) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/639fd56aa01ed0d4132d310a34395508c0311120/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 94 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2074c2db-26b0-44ad-bfd6-e81056c1bc80) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/639fd56aa01ed0d4132d310a34395508c0311120/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 90 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a562f633-81bf-4b7a-a6b1-6d98bd0e70b4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/639fd56aa01ed0d4132d310a34395508c0311120/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 95 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7780ac7d-ae7b-4ce3-9f4b-dc6403601ea1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/639fd56aa01ed0d4132d310a34395508c0311120/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/09e6ea8b-dffe-4593-8948-da136302dfc0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/639fd56aa01ed0d4132d310a34395508c0311120/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 95 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/79296e15-5efa-4b6b-a952-522ecadfd47d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/639fd56aa01ed0d4132d310a34395508c0311120/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/942f730e-9513-4580-aa96-eacc24726656) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/639fd56aa01ed0d4132d310a34395508c0311120/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 95 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/acf7f106-3240-429f-a523-92b429bfa566) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/639fd56aa01ed0d4132d310a34395508c0311120/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 93 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6b046323-922f-4465-8fec-68080effa951) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-01-30 16:32 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/825953c3a892e533fa02288dfe224f30bd4b1968/msteams-platform%2FTOC.yml) | 99 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a5cf4931-2101-49bc-8f71-f636cd77fed6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/825953c3a892e533fa02288dfe224f30bd4b1968/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 94 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8739150a-731f-4768-9909-32c1566ef5b4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/825953c3a892e533fa02288dfe224f30bd4b1968/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 94 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c00dd37b-08f1-4afb-bfec-f53ffb340b86) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/825953c3a892e533fa02288dfe224f30bd4b1968/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 90 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a9ada5d6-c88e-4eb7-92c8-40b6875ff404) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/825953c3a892e533fa02288dfe224f30bd4b1968/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 95 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a494e13a-5052-40dd-952a-61186e982954) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/825953c3a892e533fa02288dfe224f30bd4b1968/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ddc5f1b4-d79a-40d4-b493-d504ff65236e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/825953c3a892e533fa02288dfe224f30bd4b1968/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 95 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/77a54daa-abd7-4f74-a961-976dda85f9bc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/825953c3a892e533fa02288dfe224f30bd4b1968/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/487ae11c-14db-4479-a77e-13cf53ab39e0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/825953c3a892e533fa02288dfe224f30bd4b1968/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 95 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/daf56c5a-c789-4561-91f0-f3a737856fd2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/825953c3a892e533fa02288dfe224f30bd4b1968/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 93 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3a77f359-5a59-4e51-b9cb-416c94aea1b6) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-01-31 17:22 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/b2edc4bc73d831921b536842ca2e35aaaf0443ae/msteams-platform%2FTOC.yml) | 99 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8a9960d2-06bb-48fa-9ae9-868c8e6f7ba7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b2edc4bc73d831921b536842ca2e35aaaf0443ae/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 94 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/48b13fbf-e318-429d-9c12-3bc2f6b8faf7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b2edc4bc73d831921b536842ca2e35aaaf0443ae/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5851efe8-43a7-49d5-b0f7-0a1cad454e60) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b2edc4bc73d831921b536842ca2e35aaaf0443ae/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 90 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/575624ea-666d-4ed5-b955-e09af2b31432) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b2edc4bc73d831921b536842ca2e35aaaf0443ae/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 95 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/77430ff8-7324-49e3-abd0-61cdb9138781) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b2edc4bc73d831921b536842ca2e35aaaf0443ae/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/45cdbd7f-84b0-4919-a8cd-d0e100597c07) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b2edc4bc73d831921b536842ca2e35aaaf0443ae/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 93 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d2dbaec1-38f9-4b82-b352-94af59290e5d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b2edc4bc73d831921b536842ca2e35aaaf0443ae/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/934278da-46c2-48ab-8b70-cb704b5a1936) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b2edc4bc73d831921b536842ca2e35aaaf0443ae/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 96 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a1b7e779-63dd-4988-9071-014e6681d870) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b2edc4bc73d831921b536842ca2e35aaaf0443ae/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 93 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2bdff481-4d9d-4d1a-8bcf-0495fbd7cade) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-02-01 06:32 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/45b6e4374fbde396e96e56de44b7b2576ed78d36/msteams-platform%2FTOC.yml) | 99 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9397e089-160c-4bb1-bfec-a0900eb7ff53) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/45b6e4374fbde396e96e56de44b7b2576ed78d36/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 94 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a9ea398d-091b-4e01-ba36-4264e626a032) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/45b6e4374fbde396e96e56de44b7b2576ed78d36/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b96f94d0-c273-48c4-9792-9d6c3270d033) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/45b6e4374fbde396e96e56de44b7b2576ed78d36/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 90 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0e8fe0b0-98d2-433c-b204-f53dd0a55ebd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/45b6e4374fbde396e96e56de44b7b2576ed78d36/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 95 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/77abb7b9-860f-4204-a7c2-3be00179f7d2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/45b6e4374fbde396e96e56de44b7b2576ed78d36/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3fde2a2f-ec1c-4f0c-94be-5cfe5513c0bd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/45b6e4374fbde396e96e56de44b7b2576ed78d36/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 93 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f741d768-ae62-414d-98af-455183f69527) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/45b6e4374fbde396e96e56de44b7b2576ed78d36/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/385c8876-eaf1-42d0-9d73-9b04cf90b277) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/45b6e4374fbde396e96e56de44b7b2576ed78d36/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 96 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/68303bca-09f9-4d67-bb26-340e15764fdd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/45b6e4374fbde396e96e56de44b7b2576ed78d36/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 93 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9f19ffbf-31fa-435e-a0ac-8d75567e1004) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-02-01 16:43 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/76452776adf9db02b6f122931d1ae5053684b9ce/msteams-platform%2FTOC.yml) | 99 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5b1bf152-f896-4d34-ae93-63cde1a72f04) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/76452776adf9db02b6f122931d1ae5053684b9ce/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9fe1ffcf-2fbc-404a-931b-3e258c47d329) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/76452776adf9db02b6f122931d1ae5053684b9ce/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/995c5018-c6d5-4810-8599-a8d40ceac075) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/76452776adf9db02b6f122931d1ae5053684b9ce/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 90 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/591696db-d416-49c0-9149-cea2d9ee3cb4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/76452776adf9db02b6f122931d1ae5053684b9ce/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 95 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d2bc34f8-ccc6-4d2e-be14-ff9bf66e6ce0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/76452776adf9db02b6f122931d1ae5053684b9ce/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aba86b21-7f5b-476d-9e47-4489665ead97) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/76452776adf9db02b6f122931d1ae5053684b9ce/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 96 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d1497fa6-2787-4e0d-a491-43fe11aa9cd9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/76452776adf9db02b6f122931d1ae5053684b9ce/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ba94b708-06f5-4b4e-9df2-1394e8b77e79) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/76452776adf9db02b6f122931d1ae5053684b9ce/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 94 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8a0649c4-d338-4451-a2fb-db2dfce3a5f3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/76452776adf9db02b6f122931d1ae5053684b9ce/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 87 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/769d7411-b949-4b49-bc96-f33056c90710) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-02-01 17:01 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/2a3e951d9f068f60c9944dc502868c8845d6c168/msteams-platform%2FTOC.yml) | 99 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d616a11b-313c-4b8e-96f3-49b81ffe4ebf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2a3e951d9f068f60c9944dc502868c8845d6c168/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9c3619d5-46c9-4f69-897c-67c865cef529) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2a3e951d9f068f60c9944dc502868c8845d6c168/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8522c91e-48a7-481f-8b78-b83a56bfddc0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2a3e951d9f068f60c9944dc502868c8845d6c168/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 94 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0828a493-0c7e-4077-98f1-9fabe0e88caf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2a3e951d9f068f60c9944dc502868c8845d6c168/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 95 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/254dc8cf-b28a-4305-bf32-3e915b2c7446) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2a3e951d9f068f60c9944dc502868c8845d6c168/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 96 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7a49eda8-f9c9-4913-a203-d345ef311f77) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2a3e951d9f068f60c9944dc502868c8845d6c168/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 99 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/214c8dbb-05e9-4e23-9f82-71c4fa544801) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2a3e951d9f068f60c9944dc502868c8845d6c168/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/278f2d29-27de-4653-8ef5-54b6ce10aeca) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2a3e951d9f068f60c9944dc502868c8845d6c168/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 95 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3055a41e-b698-40bb-9483-23a587964d86) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2a3e951d9f068f60c9944dc502868c8845d6c168/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/46820d3d-ef17-4404-9fde-4386d236d10b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-02-02 04:14 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/4d0ab039284d4249aa300ade1717ac019f4e208e/msteams-platform%2FTOC.yml) | 99 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/583b8548-c0a8-43bf-b603-059f82ed19fa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4d0ab039284d4249aa300ade1717ac019f4e208e/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0a52bbbd-812f-42df-bea2-cb9366185cf3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4d0ab039284d4249aa300ade1717ac019f4e208e/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e8cd3c75-ca5b-4291-a941-932ed686a187) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4d0ab039284d4249aa300ade1717ac019f4e208e/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 94 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a4be4de7-9985-420d-8c2d-99f125c1082b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4d0ab039284d4249aa300ade1717ac019f4e208e/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 95 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d92eeee2-d85b-48dd-a269-b976030dfa39) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4d0ab039284d4249aa300ade1717ac019f4e208e/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 96 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a56ee291-add1-4db8-a7f8-fd08bf1336fc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4d0ab039284d4249aa300ade1717ac019f4e208e/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 99 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1fd783bd-659c-48b1-88bf-c3a5dc6e4fab) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4d0ab039284d4249aa300ade1717ac019f4e208e/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2c3e25c3-56bd-46f3-9947-ed298a3ae286) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4d0ab039284d4249aa300ade1717ac019f4e208e/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 95 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ae2cad27-f24c-4267-b24e-d6620e35a251) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4d0ab039284d4249aa300ade1717ac019f4e208e/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f0ee415a-d62b-436d-a53f-2a8db04871df) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-02-02 12:56 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/86ec2eef758f7999be6b618536f1ca44f69f41ea/msteams-platform%2FTOC.yml) | 99 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c0790523-95cf-492a-959f-d5c09b9deddd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/86ec2eef758f7999be6b618536f1ca44f69f41ea/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 98 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8f06ee5e-9ddb-498a-8774-c76eed89fbc1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/86ec2eef758f7999be6b618536f1ca44f69f41ea/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5a6be803-8f30-47f4-842b-7bc42f182494) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/86ec2eef758f7999be6b618536f1ca44f69f41ea/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 94 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0642fa21-2999-4ec4-9b5f-32f625c7ef1c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/86ec2eef758f7999be6b618536f1ca44f69f41ea/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 95 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d8bf315e-18f9-454e-8d7d-57486dae91f9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/86ec2eef758f7999be6b618536f1ca44f69f41ea/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 94 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d031223c-3975-4c7c-9add-d3c2ef42e95f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/86ec2eef758f7999be6b618536f1ca44f69f41ea/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 99 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1c03693e-80af-48f7-a0d4-233703e14635) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/86ec2eef758f7999be6b618536f1ca44f69f41ea/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/77957690-09cb-418d-92e8-d693dd31cb7c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/86ec2eef758f7999be6b618536f1ca44f69f41ea/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 96 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/16a19c19-fb3c-48d1-8dce-ff4d83190402) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/86ec2eef758f7999be6b618536f1ca44f69f41ea/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/98308d0e-0043-40cb-bb19-5d71d5fc30a3) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-02-05 04:17 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1f393d8d0ae640017fa82f4c95b3560124c557a6/msteams-platform%2FTOC.yml) | 99 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/effb1333-a008-404e-bfce-f9bc41c51dff) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1f393d8d0ae640017fa82f4c95b3560124c557a6/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 98 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f65846b5-36ba-4311-8cd6-207cb65b5567) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1f393d8d0ae640017fa82f4c95b3560124c557a6/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/04918b9d-1feb-4032-867b-4c65cda43edc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1f393d8d0ae640017fa82f4c95b3560124c557a6/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 94 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1b24d2f4-aa36-41c0-8f27-8191aa83f8bb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1f393d8d0ae640017fa82f4c95b3560124c557a6/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 95 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/796480f4-e802-48d2-bb4c-5a1a9b898547) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1f393d8d0ae640017fa82f4c95b3560124c557a6/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 94 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/447a42c5-870c-448f-a336-f16d8cd7bc0e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1f393d8d0ae640017fa82f4c95b3560124c557a6/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 99 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c4b8f50e-06b4-4ef5-9dfe-4bcae528ae29) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1f393d8d0ae640017fa82f4c95b3560124c557a6/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/82e5c29b-d801-41cd-a2e0-a5bd13eff07a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1f393d8d0ae640017fa82f4c95b3560124c557a6/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 96 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2a232bb1-9fe3-42c2-93fa-e9cf3613c228) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1f393d8d0ae640017fa82f4c95b3560124c557a6/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/18551759-2fc9-489d-83f7-22120b607c67) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-02-05 13:29 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e45e33efe9364d7714ace9281d6bc9b8df376e82/msteams-platform%2FTOC.yml) | 99 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/07a3b689-8845-4c06-a6ef-1290ac3ef256) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e45e33efe9364d7714ace9281d6bc9b8df376e82/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 98 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/128ba558-23a3-41f7-bbed-3cac658e8590) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e45e33efe9364d7714ace9281d6bc9b8df376e82/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 99 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3e98bcd5-ad9f-4efd-8235-90b956ca4397) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e45e33efe9364d7714ace9281d6bc9b8df376e82/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 94 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/da7ca155-c2d7-4f04-97a7-982649f44ff4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e45e33efe9364d7714ace9281d6bc9b8df376e82/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 95 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2ef9e082-b234-4072-8a9f-45e8f251df3d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e45e33efe9364d7714ace9281d6bc9b8df376e82/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 96 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bd9ef81d-2040-4116-93d6-403bfb2990b5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e45e33efe9364d7714ace9281d6bc9b8df376e82/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bf8a505e-035c-422f-acb8-646285e5f752) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e45e33efe9364d7714ace9281d6bc9b8df376e82/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 96 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/901a12ac-c9c8-4602-834b-7310ca4a5649) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e45e33efe9364d7714ace9281d6bc9b8df376e82/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6df57f64-529f-47a9-9374-b91dd4ec5585) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-02-07 08:16 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/287557a955fff1428bd060746cc26113dde00b8f/msteams-platform%2FTOC.yml) | 99 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/38a6aa67-9d94-4371-975c-658e80276ada) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/287557a955fff1428bd060746cc26113dde00b8f/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 98 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2a954d6d-eaf0-4242-b816-c2cc1079e4ea) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/287557a955fff1428bd060746cc26113dde00b8f/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 99 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8b98a117-6090-43a7-8b3c-9b0f08ffaa67) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/287557a955fff1428bd060746cc26113dde00b8f/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 94 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/09daebfa-0be8-4d78-98cd-fa9d2a8ce0fd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/287557a955fff1428bd060746cc26113dde00b8f/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 95 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3ad6108b-8fca-490b-92b9-3ae647052ce4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/287557a955fff1428bd060746cc26113dde00b8f/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 96 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c4346de7-5a23-4b4c-aa01-6bff06542ea9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/287557a955fff1428bd060746cc26113dde00b8f/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6001b13f-9bd9-4b4b-9645-7b1e7f205560) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/287557a955fff1428bd060746cc26113dde00b8f/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 98 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1275c525-c6dc-4b36-81a6-c3749766007c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/287557a955fff1428bd060746cc26113dde00b8f/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/98a8391c-0bd3-48b1-9846-da888d572ef1) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-02-08 03:06 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/eb308ed7573fa5270faaaef6448d02c3b756d0f0/msteams-platform%2FTOC.yml) | 79 | 185 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a6efc9be-e8ca-4a98-862e-aea2693ec423) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/eb308ed7573fa5270faaaef6448d02c3b756d0f0/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/538ecab0-21eb-40c7-b9f1-e81d71706f75) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/eb308ed7573fa5270faaaef6448d02c3b756d0f0/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 92 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/29b0b507-f1a4-4872-b9bd-15a6dc120939) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/eb308ed7573fa5270faaaef6448d02c3b756d0f0/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 89 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0d402728-61f1-42f1-a48c-5bd433ca5dd3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/eb308ed7573fa5270faaaef6448d02c3b756d0f0/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 89 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/43d321bb-0d7c-4b05-94fe-8551c071f0c4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/eb308ed7573fa5270faaaef6448d02c3b756d0f0/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 87 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/26b27aa0-34ef-4615-8b9a-d729df889c1e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/eb308ed7573fa5270faaaef6448d02c3b756d0f0/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/11f34a20-b38f-43f4-b228-f63041e59065) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/eb308ed7573fa5270faaaef6448d02c3b756d0f0/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 92 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6df1de74-a2a6-4744-a428-a2f7f7579931) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/eb308ed7573fa5270faaaef6448d02c3b756d0f0/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 91 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/610ea99e-8663-4319-8106-b897302247b9) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-02-08 13:51 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/54fa7d85784e0dc527152219b837c6200d501cbb/msteams-platform%2FTOC.yml) | 79 | 185 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2321f19c-7517-42d0-a22a-f6923c7d9306) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/54fa7d85784e0dc527152219b837c6200d501cbb/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 91 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b9bb9ef6-5054-4b3f-bb69-c1b3d56e4275) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/54fa7d85784e0dc527152219b837c6200d501cbb/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 86 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6abedc16-4838-480a-bdaa-1868200be58b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/54fa7d85784e0dc527152219b837c6200d501cbb/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 89 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/30f4e90a-5b6f-4bca-a0c4-36d7e8195763) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/54fa7d85784e0dc527152219b837c6200d501cbb/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 89 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0bf8731d-dde0-4a1e-92d5-da5eba4c0519) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/54fa7d85784e0dc527152219b837c6200d501cbb/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 86 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/324dab4e-ad6d-4d6b-867d-b91e0b28372b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/54fa7d85784e0dc527152219b837c6200d501cbb/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/64d74547-3a59-49a8-a891-6b1fe7a035b9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/54fa7d85784e0dc527152219b837c6200d501cbb/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 92 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3407cb48-94eb-43e8-a822-cab73bb28925) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/54fa7d85784e0dc527152219b837c6200d501cbb/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 90 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/585042ba-8be3-41dc-8145-e36ade861e60) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-02-09 03:32 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/468931ef957182d04bcf234ab32ac73aa4334182/msteams-platform%2FTOC.yml) | 97 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4b9d9b72-cfe8-4be1-9cc8-475118cc4bb5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/468931ef957182d04bcf234ab32ac73aa4334182/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 94 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2ada7536-63ef-4ffb-8134-03dc622ead6f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/468931ef957182d04bcf234ab32ac73aa4334182/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 92 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6a8d1c67-e256-4668-b006-dd2ec9e9228f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/468931ef957182d04bcf234ab32ac73aa4334182/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 91 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/54f2bcfb-988d-4a3d-a464-d7c57d2d71c4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/468931ef957182d04bcf234ab32ac73aa4334182/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 92 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2ae449a1-69f3-4a24-890f-fd284ef8577b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/468931ef957182d04bcf234ab32ac73aa4334182/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 89 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2b743f91-3b2f-4925-b5aa-ca57ca39afb4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/468931ef957182d04bcf234ab32ac73aa4334182/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 94 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6dcc9e16-3d7d-4ac1-b0ee-f7545ce1a164) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/468931ef957182d04bcf234ab32ac73aa4334182/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 94 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ce156708-f331-42cf-b9bc-102a07303ca4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/468931ef957182d04bcf234ab32ac73aa4334182/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b692fe8b-f3e1-41d4-aaea-b1f2eee334e9) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-02-09 06:46 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/5ebc187611a11a9adcb32a6d52134e339dbbb6a0/msteams-platform%2FTOC.yml) | 97 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/30d58df8-7c41-47b8-9c75-8aea825a9b39) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5ebc187611a11a9adcb32a6d52134e339dbbb6a0/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 94 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4b9117d7-373e-4ca6-8cfc-43f5a4c64b6f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5ebc187611a11a9adcb32a6d52134e339dbbb6a0/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 92 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/200e4ff9-a145-4c19-871c-7660eb406a47) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5ebc187611a11a9adcb32a6d52134e339dbbb6a0/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 91 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3534e8c8-ca7c-4e01-9537-bbd971355dfe) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5ebc187611a11a9adcb32a6d52134e339dbbb6a0/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 92 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/47ebc14e-3804-472f-9e05-aff2b1cd263c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5ebc187611a11a9adcb32a6d52134e339dbbb6a0/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 94 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/75f63367-9d64-4d95-80f2-d2e1f2cd6752) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5ebc187611a11a9adcb32a6d52134e339dbbb6a0/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 94 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9979a1b4-bf08-4b21-b02a-2cb0e4f193fd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5ebc187611a11a9adcb32a6d52134e339dbbb6a0/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 94 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fc0331b0-6bfc-4d52-bdb3-72944c2789e4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5ebc187611a11a9adcb32a6d52134e339dbbb6a0/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 98 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3e243e47-4e2c-4a6f-bcf4-19e027bac16a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-02-09 08:16 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/93787ebaf1bad948911edfa48776bd86f4f2051a/msteams-platform%2FTOC.yml) | 97 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/beefbb5a-a75b-4563-bb6c-b396d0376206) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/93787ebaf1bad948911edfa48776bd86f4f2051a/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 94 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9abee052-4484-4107-8d17-0227e289aec6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/93787ebaf1bad948911edfa48776bd86f4f2051a/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 92 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4da7b18b-eea8-4b2a-a5ae-4af392517947) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/93787ebaf1bad948911edfa48776bd86f4f2051a/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 91 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dfd065fe-102d-47b0-822a-4f1f1c9a865e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/93787ebaf1bad948911edfa48776bd86f4f2051a/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 92 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/68f1b0bb-b4f9-499f-af4b-ba1ada8ce64b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/93787ebaf1bad948911edfa48776bd86f4f2051a/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 94 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/806ede46-2fff-4dc8-95a0-75e84c597cb5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/93787ebaf1bad948911edfa48776bd86f4f2051a/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 94 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a9854f77-16ac-41b4-ad97-89cbb5fb7535) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/93787ebaf1bad948911edfa48776bd86f4f2051a/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 94 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3efc42da-ea00-4769-a5a1-ebc620550fd4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/93787ebaf1bad948911edfa48776bd86f4f2051a/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 98 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/55aee0a7-7c2e-4da4-b3ab-78f7a4536457) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-02-09 11:18 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1a2ecb554c6d95e90971dfd1674966e9acef90e5/msteams-platform%2FTOC.yml) | 97 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ead94247-9679-4311-ad12-287cbf16d3ee) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1a2ecb554c6d95e90971dfd1674966e9acef90e5/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e9f956ce-1f54-4c23-b69d-74ae69d75da2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1a2ecb554c6d95e90971dfd1674966e9acef90e5/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 92 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ff926152-e4ff-4a82-a803-b2f726443593) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1a2ecb554c6d95e90971dfd1674966e9acef90e5/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 91 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/70f7547d-41ac-41ed-be12-6744cd5e7f27) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1a2ecb554c6d95e90971dfd1674966e9acef90e5/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 92 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2a3e7d50-1e7d-4cc5-ba64-577e4efaf21e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1a2ecb554c6d95e90971dfd1674966e9acef90e5/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3c69cde7-bf06-4fd8-8a73-0556df5177c6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1a2ecb554c6d95e90971dfd1674966e9acef90e5/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 94 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ccda420f-b458-42a7-b3bb-cf199258db92) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1a2ecb554c6d95e90971dfd1674966e9acef90e5/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 95 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a5aaba6b-e0f9-4869-abb2-214ac06596b2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1a2ecb554c6d95e90971dfd1674966e9acef90e5/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/43718298-6f8f-4d80-948d-c28d829e36d1) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-02-09 12:03 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c60331bb51e34867d29b042ce149aaee793ac5a9/msteams-platform%2FTOC.yml) | 97 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2b5541c0-8156-4c8b-ae5f-585865d817c3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c60331bb51e34867d29b042ce149aaee793ac5a9/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b07645aa-7b0f-4438-bfb2-5f7a637eed39) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c60331bb51e34867d29b042ce149aaee793ac5a9/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 92 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/165b4fc7-757f-4947-b555-3a933eb13ce2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c60331bb51e34867d29b042ce149aaee793ac5a9/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 91 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4e952f68-e8ef-4913-89eb-4f67fcd4ca03) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c60331bb51e34867d29b042ce149aaee793ac5a9/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 92 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/df495041-9d9d-4f2f-96a9-c6db02a537b2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c60331bb51e34867d29b042ce149aaee793ac5a9/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/72653c21-455e-4e9c-bed7-64766af2cf7e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c60331bb51e34867d29b042ce149aaee793ac5a9/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 94 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/68746101-890e-4086-987f-f9af1bcb33e6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c60331bb51e34867d29b042ce149aaee793ac5a9/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 95 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3a8be868-c159-44f9-8312-b66108ae8c9b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c60331bb51e34867d29b042ce149aaee793ac5a9/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3961a9bc-7197-4e32-9f6b-9d9f64e5c848) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-02-09 12:51 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a030071381342c9301b3abc40cda299deabb354c/msteams-platform%2FTOC.yml) | 97 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f1897bc1-1c62-4861-90e0-dcbe6af06ce7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a030071381342c9301b3abc40cda299deabb354c/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cb9fe6b8-890a-4372-a450-1b84db637dc0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a030071381342c9301b3abc40cda299deabb354c/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 92 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/027247ab-a9fd-4833-a6ae-7fca2b96d622) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a030071381342c9301b3abc40cda299deabb354c/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 91 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f0fb3c9e-f3fd-46ea-aa45-d74971b4951b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a030071381342c9301b3abc40cda299deabb354c/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 92 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/54b9d65f-ad40-4a17-8c09-da736acee154) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a030071381342c9301b3abc40cda299deabb354c/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8bb788d2-c115-4290-88d1-63e4c313088c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a030071381342c9301b3abc40cda299deabb354c/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 94 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/eeeb6eb2-1ae7-43ef-8507-09bdb20aabb5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a030071381342c9301b3abc40cda299deabb354c/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 95 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d4e00716-9cf0-4dbf-a800-a3ec8f62a86d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a030071381342c9301b3abc40cda299deabb354c/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cdbee06a-3dd5-4248-8487-4864a7d2ad9c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-02-19 13:40 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/852154f7d5282b3ed6eb265afb8cb0689c6aadcf/msteams-platform%2FTOC.yml) | 97 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6d3537d5-f780-4cc2-8c08-dd55783d6aea) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/852154f7d5282b3ed6eb265afb8cb0689c6aadcf/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c000eeb9-85b6-4ac7-8204-cd5750ee14f9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/852154f7d5282b3ed6eb265afb8cb0689c6aadcf/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 92 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1da7a857-a984-4f1f-bec0-4fb901f1d2a5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/852154f7d5282b3ed6eb265afb8cb0689c6aadcf/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 91 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/82c627c7-54d9-4618-b7e1-e6a5ddd37e0a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/852154f7d5282b3ed6eb265afb8cb0689c6aadcf/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 92 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/153427be-64f5-4768-99fb-10253dc0842d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/852154f7d5282b3ed6eb265afb8cb0689c6aadcf/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4dab9e9f-9946-4af7-bbbc-ae3b40d65d43) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/852154f7d5282b3ed6eb265afb8cb0689c6aadcf/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 94 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/29cc2f17-15c7-4672-888d-4ddcb6c32d06) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/852154f7d5282b3ed6eb265afb8cb0689c6aadcf/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 95 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d405a38f-ee91-495c-be53-9529094539e6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/852154f7d5282b3ed6eb265afb8cb0689c6aadcf/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f5a69106-eb9a-4b75-ad43-f61bec9353b9) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-02-20 10:11 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ed55d59e14e28bf97ac8f05d029fc855a0ed7687/msteams-platform%2FTOC.yml) | 97 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d0a47fcc-78d2-4aca-b41d-a22c39136a36) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ed55d59e14e28bf97ac8f05d029fc855a0ed7687/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f790ab1f-7b53-4dbe-bbe9-533d877a020e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ed55d59e14e28bf97ac8f05d029fc855a0ed7687/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 92 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4b2ebac8-d2fa-491c-8d55-ba1fc255f989) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ed55d59e14e28bf97ac8f05d029fc855a0ed7687/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 91 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/04040f32-ee8d-464a-b436-da3bf0f4c37d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ed55d59e14e28bf97ac8f05d029fc855a0ed7687/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 92 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d6c3d744-0fb4-43a7-8d0d-d61247081677) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ed55d59e14e28bf97ac8f05d029fc855a0ed7687/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/905e1607-7c16-4666-8ab3-bb48482b0bf8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ed55d59e14e28bf97ac8f05d029fc855a0ed7687/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f536fb6c-274c-4ba1-afab-51b34ed02323) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ed55d59e14e28bf97ac8f05d029fc855a0ed7687/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 95 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aa541d93-5bd2-4687-bb2c-3e8c9feef53a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ed55d59e14e28bf97ac8f05d029fc855a0ed7687/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7172e9e1-277b-4406-a0b9-7b2ba49bac0b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-02-27 07:13 UTC, Wajeed-msft approved these changes

2024-03-05 03:15 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/d4f97616d834a2048c1c0d8428169d3547d67306/msteams-platform%2FTOC.yml) | 97 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6419781d-1424-4b59-9a71-5bdd03fb9883) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d4f97616d834a2048c1c0d8428169d3547d67306/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/862044f7-95f8-451b-bab8-b64fa9e52392) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d4f97616d834a2048c1c0d8428169d3547d67306/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 92 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bdb853ba-eb68-4c2c-87f4-97baaa9844b6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d4f97616d834a2048c1c0d8428169d3547d67306/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 91 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2475af0a-50c5-472c-a7d0-a69e7d307375) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d4f97616d834a2048c1c0d8428169d3547d67306/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 92 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/365b3e0e-2970-40a6-8b82-84efaa7219d2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d4f97616d834a2048c1c0d8428169d3547d67306/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f4159d54-6738-49c3-8dda-3a0d63cf771e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d4f97616d834a2048c1c0d8428169d3547d67306/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/637fde53-fe87-4476-a962-3b6d22339856) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d4f97616d834a2048c1c0d8428169d3547d67306/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 95 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/29250bb3-9d01-4c17-be5b-0aa530b0c406) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d4f97616d834a2048c1c0d8428169d3547d67306/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/adc46e1e-eded-4d27-94c3-07a0850b764f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-03-05 03:59 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/67d5817e8402efbe38ed1a0b65da103c6da00de9/msteams-platform%2FTOC.yml) | 97 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/62c70311-1418-4f73-8d18-aa2cb7146b2d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/67d5817e8402efbe38ed1a0b65da103c6da00de9/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/02804b38-12cf-4c91-aa45-9fdfb77f987f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/67d5817e8402efbe38ed1a0b65da103c6da00de9/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 92 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/120ab6e1-128a-486a-a22d-7e7dd53c05fc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/67d5817e8402efbe38ed1a0b65da103c6da00de9/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 91 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c87cdcb2-06ce-42ec-8969-88cd26ecb2c6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/67d5817e8402efbe38ed1a0b65da103c6da00de9/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 92 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/59ad0584-3226-4155-9637-559c7a9ef96b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/67d5817e8402efbe38ed1a0b65da103c6da00de9/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d78ee5a4-377c-4e68-a268-133456ddab9d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/67d5817e8402efbe38ed1a0b65da103c6da00de9/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2c2654c6-9ab2-4e5c-b4e3-4530654a5c9c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/67d5817e8402efbe38ed1a0b65da103c6da00de9/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 95 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e4347712-ecba-44f1-ad36-90969fdedcc1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/67d5817e8402efbe38ed1a0b65da103c6da00de9/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/995ae40a-7953-4310-bc0d-2f06f864fe19) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-03-06 14:01 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/5ac162c5459605fbdf0ec762ff812298f2a8d354/msteams-platform%2FTOC.yml) | 97 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8fbb1ace-3d81-4586-b915-b8f7771adfec) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5ac162c5459605fbdf0ec762ff812298f2a8d354/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/94f58598-dd4b-4528-819f-c553b9269902) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5ac162c5459605fbdf0ec762ff812298f2a8d354/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 92 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/26da27c8-5949-42dd-9cb7-c9ad662edb8f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5ac162c5459605fbdf0ec762ff812298f2a8d354/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 91 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f567c4d2-9363-4285-832c-d0eea3ee39b9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5ac162c5459605fbdf0ec762ff812298f2a8d354/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 92 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2171efed-6c92-43a4-9ce7-a08f40af1284) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5ac162c5459605fbdf0ec762ff812298f2a8d354/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 94 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/95068d82-92db-4e27-afde-7c1feb4f9396) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5ac162c5459605fbdf0ec762ff812298f2a8d354/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/12bac469-209c-4585-820f-6663f6d2cf9f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5ac162c5459605fbdf0ec762ff812298f2a8d354/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 95 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bb860b55-36d1-4bc7-8754-054234534fd8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5ac162c5459605fbdf0ec762ff812298f2a8d354/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0724c9f8-00ff-4c79-94c5-c4c93baea00f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-03-11 12:56 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/81277def8afeec0d4ce8fcdcd3355b99f66b5ba5/msteams-platform%2FTOC.yml) | 97 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8b6f097b-78d6-4340-b4d6-3bc4d866110b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/81277def8afeec0d4ce8fcdcd3355b99f66b5ba5/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/75983392-170b-4d31-9a66-968a956356fc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/81277def8afeec0d4ce8fcdcd3355b99f66b5ba5/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 92 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6ddcc8e9-b5e4-4111-b0d8-7e891eeeb3fd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/81277def8afeec0d4ce8fcdcd3355b99f66b5ba5/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 91 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a59c9b2c-faba-4a52-80e7-309cd1088946) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/81277def8afeec0d4ce8fcdcd3355b99f66b5ba5/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 92 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2ad4c53d-bf9a-40d2-b79a-8a9005165a5d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/81277def8afeec0d4ce8fcdcd3355b99f66b5ba5/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 94 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/159a718e-68bc-4bd8-89fb-87b9b58e916e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/81277def8afeec0d4ce8fcdcd3355b99f66b5ba5/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0e0d9835-3f17-4799-bc5a-fc6652896b0b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/81277def8afeec0d4ce8fcdcd3355b99f66b5ba5/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 95 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/536274b2-26d5-49ab-a483-69eba8622202) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/81277def8afeec0d4ce8fcdcd3355b99f66b5ba5/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4bf110c7-82c3-44b9-94d5-ee40a8188554) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-03-11 13:04 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/11664ccd3aa238dd601dc0ccecce21ff81dc6d93/msteams-platform%2FTOC.yml) | 97 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cda97068-21c7-4169-9fe8-18d61d177ec6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/11664ccd3aa238dd601dc0ccecce21ff81dc6d93/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e5911204-3aa0-4f9b-a68b-2c6d2f72e39c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/11664ccd3aa238dd601dc0ccecce21ff81dc6d93/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 92 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e5657b87-84d8-46d2-8fc6-a6f273052905) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/11664ccd3aa238dd601dc0ccecce21ff81dc6d93/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 91 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4b088254-71cf-45b6-8a84-01b314edecbe) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/11664ccd3aa238dd601dc0ccecce21ff81dc6d93/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 92 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5e020f51-81ff-471f-a68a-c2e3a0020404) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/11664ccd3aa238dd601dc0ccecce21ff81dc6d93/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 94 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7280435f-7f77-4122-940c-0ae7f91602a4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/11664ccd3aa238dd601dc0ccecce21ff81dc6d93/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cf75ecc4-ae23-4fb9-a291-adec4e7cb114) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/11664ccd3aa238dd601dc0ccecce21ff81dc6d93/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 95 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9f10e1d9-714c-4ca3-b444-665ba171495c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/11664ccd3aa238dd601dc0ccecce21ff81dc6d93/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/412bddfb-dee1-4a34-9061-dbc5e974df81) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-06-06 13:16 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/017d9363a2399e03050bc6bf09e3528ac1ca7e05/msteams-platform%2FTOC.yml) | 97 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ad669d40-4fa7-4eca-b62b-c4c4feaff515) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/017d9363a2399e03050bc6bf09e3528ac1ca7e05/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/de36531c-fcd0-4c63-bda0-9f8e3050c0c6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/017d9363a2399e03050bc6bf09e3528ac1ca7e05/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 92 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e2d5831f-3345-4730-a67e-ac2e11ec0478) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/017d9363a2399e03050bc6bf09e3528ac1ca7e05/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 92 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9957f3d3-b9a8-401d-81af-67dd453c35bf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/017d9363a2399e03050bc6bf09e3528ac1ca7e05/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 92 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1c4efc36-774e-424c-8857-db737e970572) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/017d9363a2399e03050bc6bf09e3528ac1ca7e05/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 94 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4e982d1f-0941-430a-bd5c-1b82801f950d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/017d9363a2399e03050bc6bf09e3528ac1ca7e05/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c3e955b1-b1d8-4cbc-a0ef-b8560de3aed8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/017d9363a2399e03050bc6bf09e3528ac1ca7e05/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 95 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d6826725-dee7-4d60-8aa5-70b3f42d852c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/017d9363a2399e03050bc6bf09e3528ac1ca7e05/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d4c77f97-dc4b-4ef9-8937-d1d92b5f1818) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-06-17 10:24 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/72c7018855b7235f60f00bd47d09dcf47d48a62d/msteams-platform%2FTOC.yml) |   |   | [link]( ) | [:warning:](# "Could not check with Acrolinx&#10;Please close and reopen pull request") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/72c7018855b7235f60f00bd47d09dcf47d48a62d/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ab74bcca-8184-4ced-914c-1890b2ed9112) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/72c7018855b7235f60f00bd47d09dcf47d48a62d/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 92 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/425f4505-7be7-4914-87f5-b6ab6e158a70) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/72c7018855b7235f60f00bd47d09dcf47d48a62d/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 92 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e86ea15b-93b4-4600-870e-b3d6373297ae) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/72c7018855b7235f60f00bd47d09dcf47d48a62d/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 92 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9ead22d3-815e-4d03-bf56-e6b60331c87f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/72c7018855b7235f60f00bd47d09dcf47d48a62d/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 94 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1a8d2eaf-738f-43e6-922e-ac5b884e46c5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/72c7018855b7235f60f00bd47d09dcf47d48a62d/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4ad26f07-8b34-4f70-bd01-5acb536f2856) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/72c7018855b7235f60f00bd47d09dcf47d48a62d/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 95 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/546aad86-6b95-4654-bc37-32cf9631049b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/72c7018855b7235f60f00bd47d09dcf47d48a62d/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/92ff7e33-5098-4009-981b-e191b8e8a39e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-06-17 13:41 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/d39b55e4d59946bdcd9351c48bf7265f12be1778/msteams-platform%2FTOC.yml) |   |   | [link]( ) | [:warning:](# "Could not check with Acrolinx&#10;Please close and reopen pull request") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d39b55e4d59946bdcd9351c48bf7265f12be1778/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/22a261ff-951e-43aa-8d3e-445a4cd55a44) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d39b55e4d59946bdcd9351c48bf7265f12be1778/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 92 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7052f773-ccb6-46d6-bb42-10c786ae0a56) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d39b55e4d59946bdcd9351c48bf7265f12be1778/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 92 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e624fb86-170a-4b37-bc40-ebecf007df64) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d39b55e4d59946bdcd9351c48bf7265f12be1778/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 92 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5316c532-deab-47b5-90d1-ae073ee6a5b4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d39b55e4d59946bdcd9351c48bf7265f12be1778/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/48c32712-c4b8-41ca-a39f-98c3c76c826d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d39b55e4d59946bdcd9351c48bf7265f12be1778/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a9ccf5d4-013b-4c48-8cc1-68b785952daf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d39b55e4d59946bdcd9351c48bf7265f12be1778/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 95 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3ccf2f7d-b64a-4ec6-b365-046289fa2225) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d39b55e4d59946bdcd9351c48bf7265f12be1778/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/03761d19-9c54-48c0-bbd3-bed0011651f6) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-06-18 08:38 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ce9f2a721c9dcbda6435420891f46b22987ee5f3/msteams-platform%2FTOC.yml) |   |   | [link]( ) | [:warning:](# "Could not check with Acrolinx&#10;Please close and reopen pull request") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ce9f2a721c9dcbda6435420891f46b22987ee5f3/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f12d0aa7-8766-452a-a851-a12498797d43) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ce9f2a721c9dcbda6435420891f46b22987ee5f3/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 92 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8cf4a8c1-54d4-4665-8012-cbfffc12213e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ce9f2a721c9dcbda6435420891f46b22987ee5f3/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 92 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7cdec0b9-0d44-4631-a3cd-3e6cc4233189) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ce9f2a721c9dcbda6435420891f46b22987ee5f3/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 92 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b8216dfb-81c8-4695-8113-171dac09ffb9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ce9f2a721c9dcbda6435420891f46b22987ee5f3/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/223c9116-b202-4164-b303-1b8a6236a642) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ce9f2a721c9dcbda6435420891f46b22987ee5f3/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c9f266b1-7c4e-4c08-bbd4-314a69ee53e8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ce9f2a721c9dcbda6435420891f46b22987ee5f3/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 95 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7fb33c8c-1c3e-4414-9d3a-d652bc67e8e9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ce9f2a721c9dcbda6435420891f46b22987ee5f3/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ee966b65-6257-4585-897e-af95c2648840) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-06-20 12:32 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/810ad461ce355f9183a356098928898c64608f8f/msteams-platform%2FTOC.yml) |   |   | [link]( ) | [:warning:](# "Could not check with Acrolinx&#10;Please close and reopen pull request") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/810ad461ce355f9183a356098928898c64608f8f/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/817339e8-d317-4530-920b-e6bd1df3619a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/810ad461ce355f9183a356098928898c64608f8f/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 92 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b0a1cd86-3264-4bb4-823a-c409338cb43b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/810ad461ce355f9183a356098928898c64608f8f/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 92 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/93798d0d-4436-4154-9954-1b35a1d78c8f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/810ad461ce355f9183a356098928898c64608f8f/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 92 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fc37f18a-7f42-4c8e-acd3-0b0c5a77bd3a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/810ad461ce355f9183a356098928898c64608f8f/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/203dcdf9-3ec7-4d8c-8953-b367b037662f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/810ad461ce355f9183a356098928898c64608f8f/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b19a6e38-2913-460c-864e-99b4fc4faa0c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/810ad461ce355f9183a356098928898c64608f8f/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 95 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/54a43603-e1bc-40d8-ad82-608140216a13) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/810ad461ce355f9183a356098928898c64608f8f/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f55c1a05-91c3-4a46-bc59-42c7f42def71) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-06-20 13:41 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/dd884168b161a68c95036c47bec634e61d1da38c/msteams-platform%2FTOC.yml) |   |   | [link]( ) | [:warning:](# "Could not check with Acrolinx&#10;Please close and reopen pull request") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dd884168b161a68c95036c47bec634e61d1da38c/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/55a108a9-ebe3-4fae-a643-4e4144d03230) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dd884168b161a68c95036c47bec634e61d1da38c/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-saas-offer.md) | 92 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/610fd417-2fbd-4b72-b15a-4ef6a596ac65) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dd884168b161a68c95036c47bec634e61d1da38c/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 92 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ceff7da6-3462-4903-8cb5-25b15feea852) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dd884168b161a68c95036c47bec634e61d1da38c/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 92 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1f5dc011-7faa-4d82-8970-91fac7612ae3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dd884168b161a68c95036c47bec634e61d1da38c/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 93 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/914c24ac-951e-41c9-b652-a01b5724389d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dd884168b161a68c95036c47bec634e61d1da38c/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/490043d2-d0f2-4555-8e8b-b5285a460453) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dd884168b161a68c95036c47bec634e61d1da38c/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fprerequisites.md) | 95 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/784e972d-ff84-499a-a904-bd1f48c93337) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dd884168b161a68c95036c47bec634e61d1da38c/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5af704d1-fad9-4d3d-857f-dea8978e1e53) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-06-20 13:57 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/85142cd9747c61ee7b8b22f9dbd240fad9b8ba7d/msteams-platform%2FTOC.yml) |   |   | [link]( ) | [:warning:](# "Could not check with Acrolinx&#10;Please close and reopen pull request") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/85142cd9747c61ee7b8b22f9dbd240fad9b8ba7d/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e0423d05-56aa-4e63-b92c-1e2d51b069f2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/85142cd9747c61ee7b8b22f9dbd240fad9b8ba7d/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 92 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3fe78de1-800b-45ec-9585-6baf47d0c84f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/85142cd9747c61ee7b8b22f9dbd240fad9b8ba7d/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 92 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e360e2fc-138e-4287-a537-97bfd7576ede) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/85142cd9747c61ee7b8b22f9dbd240fad9b8ba7d/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 93 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/abe6d8b3-f61e-416e-a801-9edf8338135d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/85142cd9747c61ee7b8b22f9dbd240fad9b8ba7d/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0b472f9c-fd1a-42c4-97af-cdd314bed95e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/85142cd9747c61ee7b8b22f9dbd240fad9b8ba7d/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a2f32499-f1aa-4878-b4f0-08b1b38f1055) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-06-21 09:38 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/750901a9a95d53c9aff5478879c003b72eee78d0/msteams-platform%2FTOC.yml) |   |   | [link]( ) | [:warning:](# "Could not check with Acrolinx&#10;Please close and reopen pull request") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/750901a9a95d53c9aff5478879c003b72eee78d0/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3e0ab383-0e60-4097-bd86-669a5a22e52e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/750901a9a95d53c9aff5478879c003b72eee78d0/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 92 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a61791dc-0e65-4581-a933-8d2af81ef496) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/750901a9a95d53c9aff5478879c003b72eee78d0/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 92 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ed73ac9b-756d-4a64-97f5-551aac4abcc8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/750901a9a95d53c9aff5478879c003b72eee78d0/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 93 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5a141b45-efd0-44d7-a32e-925cfd8bcd54) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/750901a9a95d53c9aff5478879c003b72eee78d0/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bd70b229-f143-4aac-bd82-be18bdef09d9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/750901a9a95d53c9aff5478879c003b72eee78d0/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a6b4bbbd-90b0-4481-9255-69df11fd78bb) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-06-21 13:41 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/15144f8791438363a688a6d0ad3b993af91b1d86/msteams-platform%2FTOC.yml) |   |   | [link]( ) | [:warning:](# "Could not check with Acrolinx&#10;Please close and reopen pull request") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/15144f8791438363a688a6d0ad3b993af91b1d86/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fb3ef740-0550-4383-af6c-1f41a59b683d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/15144f8791438363a688a6d0ad3b993af91b1d86/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 92 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0e3e712e-ff77-4979-85e4-246cf8ef09a0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/15144f8791438363a688a6d0ad3b993af91b1d86/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 92 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/49b07800-c4dd-4945-8efe-7f40a130a187) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/15144f8791438363a688a6d0ad3b993af91b1d86/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ca351b17-380e-4f20-8478-4b9087568a8a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/15144f8791438363a688a6d0ad3b993af91b1d86/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7c739fd2-111f-4313-a838-15c44220de05) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/15144f8791438363a688a6d0ad3b993af91b1d86/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7762b4e5-78e8-4888-b1f0-dd53b06e8c91) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-06-21 14:51 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/3ef7f28ba9848e72db1a909ba2a9267d0c23095e/msteams-platform%2FTOC.yml) |   |   | [link]( ) | [:warning:](# "Could not check with Acrolinx&#10;Please close and reopen pull request") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3ef7f28ba9848e72db1a909ba2a9267d0c23095e/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b3fd5a20-8ea2-4ca2-8c4f-74ab508f1a5f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3ef7f28ba9848e72db1a909ba2a9267d0c23095e/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 83 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a8b17e5f-40f7-4ccf-aa29-630a2c4da768) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3ef7f28ba9848e72db1a909ba2a9267d0c23095e/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 92 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6e164e67-defe-42fa-b656-683f179d0901) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3ef7f28ba9848e72db1a909ba2a9267d0c23095e/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a3d1faa2-3eb4-40e9-b4a9-609a742b3d9c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3ef7f28ba9848e72db1a909ba2a9267d0c23095e/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/eba1fdf8-1a1c-45da-958b-fa87b95fd18b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3ef7f28ba9848e72db1a909ba2a9267d0c23095e/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/34344e2c-328e-496c-9144-ae76c2448436) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-07-02 14:31 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/751a604d4b7f8ef843a48e00621b79fc473da4a3/msteams-platform%2FTOC.yml) | 97 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c4206d5a-2d32-4b84-9353-24ea43fd3162) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/751a604d4b7f8ef843a48e00621b79fc473da4a3/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/07d31f78-4136-46a8-b003-0fe5cbed3358) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/751a604d4b7f8ef843a48e00621b79fc473da4a3/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 82 | 33 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/df2b00f2-6565-4da2-9e48-3cc4d14dfade) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/751a604d4b7f8ef843a48e00621b79fc473da4a3/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 92 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/24b2ed52-09ce-4192-8f66-b37cf5a15055) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/751a604d4b7f8ef843a48e00621b79fc473da4a3/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 91 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0a058cd2-b3fb-4cf8-9afd-26448c234da0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/751a604d4b7f8ef843a48e00621b79fc473da4a3/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cf6b51a4-730a-40e3-9d26-a396237d02f4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/751a604d4b7f8ef843a48e00621b79fc473da4a3/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3c1b84f5-2f55-46b6-9378-2a75748eebc9) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-07-03 13:45 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ace77c9445a1eb934ee947948c3d49094f6d1066/msteams-platform%2FTOC.yml) | 97 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/898bb091-04e0-4067-9e8c-e2c211021b7f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ace77c9445a1eb934ee947948c3d49094f6d1066/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ebb2cc25-f9bb-4c07-b9e2-249c8093550a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ace77c9445a1eb934ee947948c3d49094f6d1066/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 82 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dc84b69b-1cab-4f83-aa1c-506c04f598e8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ace77c9445a1eb934ee947948c3d49094f6d1066/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 92 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8b298f16-c923-431c-82d7-fabb03460d1f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ace77c9445a1eb934ee947948c3d49094f6d1066/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 88 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f4e33c64-fdaf-436b-a667-9b13cebdb4a7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ace77c9445a1eb934ee947948c3d49094f6d1066/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8cedbad9-5502-40c5-bed5-1a45341b4dde) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ace77c9445a1eb934ee947948c3d49094f6d1066/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c7bab343-602d-4b24-b336-2a6917c1a2f8) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-07-08 04:57 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1348293f5d513adf1bcc17fa62ac6e160ae67856/msteams-platform%2FTOC.yml) | 97 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a3c7bda4-004d-4a16-9f81-01feb86e607e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1348293f5d513adf1bcc17fa62ac6e160ae67856/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/563e4ef1-0815-4c42-88f8-180bef100ae4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1348293f5d513adf1bcc17fa62ac6e160ae67856/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 82 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/71124224-2134-4776-a12a-23491f670b90) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1348293f5d513adf1bcc17fa62ac6e160ae67856/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 89 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7ac37698-a870-4b51-ae83-b1271b3b2281) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1348293f5d513adf1bcc17fa62ac6e160ae67856/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 88 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8ea1a67c-24a3-453c-9e1b-557855c3c656) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1348293f5d513adf1bcc17fa62ac6e160ae67856/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1a22b96b-ecc9-4403-839a-a2b3a671c676) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1348293f5d513adf1bcc17fa62ac6e160ae67856/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/af8deb0a-3daf-48e4-acc4-8988adb95399) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-07-08 11:02 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/672858b35eba5bee8b64fae4a046005b74bd9dde/msteams-platform%2FTOC.yml) | 97 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/349d51a7-4214-433d-874c-707acc69ca28) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/672858b35eba5bee8b64fae4a046005b74bd9dde/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/80a423cd-f5c6-4322-a0dd-76c97e1cf077) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/672858b35eba5bee8b64fae4a046005b74bd9dde/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 84 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9be4d401-300a-4bdc-886b-7d89914c802c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/672858b35eba5bee8b64fae4a046005b74bd9dde/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 89 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4e7c0ad3-03d0-455a-9ad7-3079fb1baa11) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/672858b35eba5bee8b64fae4a046005b74bd9dde/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 88 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d26d028e-cbb8-4ffb-aeb5-cd71e3168697) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/672858b35eba5bee8b64fae4a046005b74bd9dde/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/50765a3d-9270-449a-b2b9-f95366878da8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/672858b35eba5bee8b64fae4a046005b74bd9dde/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6ee57303-f14f-441f-975c-88058071d696) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-07-08 13:39 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ddc37ce32e229d85883957e37724325f29b4b194/msteams-platform%2FTOC.yml) | 97 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/90edbb26-b370-4475-b59d-27c3ffef7dbc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ddc37ce32e229d85883957e37724325f29b4b194/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/556acf4b-f25b-4d67-bce1-8805d129bd47) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ddc37ce32e229d85883957e37724325f29b4b194/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 84 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f247569e-f3d0-4009-a8cf-369bed315700) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ddc37ce32e229d85883957e37724325f29b4b194/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 89 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6bf5a623-2b95-4743-8ed8-6f026a92bf4d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ddc37ce32e229d85883957e37724325f29b4b194/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 88 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3ef8fc61-ae4d-42aa-8ad9-3c7520f6ea9a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ddc37ce32e229d85883957e37724325f29b4b194/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/84defb5b-f929-499f-ad15-5845434c5bd4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ddc37ce32e229d85883957e37724325f29b4b194/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3ce0992f-c378-42c5-8497-bf8d6b7d6963) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-08-08 11:47 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/d05051e6b6264f8628764b67a4435519bf1e37fc/msteams-platform%2FTOC.yml) | 97 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ae9b3680-b559-4e3b-a1eb-b002ea6de0e4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d05051e6b6264f8628764b67a4435519bf1e37fc/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3fdb14f9-ce21-4ec9-9d58-9ac8103874cb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d05051e6b6264f8628764b67a4435519bf1e37fc/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 84 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/127a354b-36cc-4c13-bfc2-39fcd948ab3c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d05051e6b6264f8628764b67a4435519bf1e37fc/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 89 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/11a646fb-70c8-46a9-89cf-5a6a319e9026) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d05051e6b6264f8628764b67a4435519bf1e37fc/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 88 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f34d1070-7220-464d-891a-db74e6483fe4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d05051e6b6264f8628764b67a4435519bf1e37fc/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ec944dce-e8a3-4870-bd73-1d0a85e24124) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d05051e6b6264f8628764b67a4435519bf1e37fc/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e07600a6-1ff8-4002-98bb-ad61ec93aded) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-08-09 13:51 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/f51489fba0f558b1a6e2c59ec1a7bb7d5590ad18/msteams-platform%2FTOC.yml) | 97 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/609337f9-486c-4b26-94bf-7bf049c313e3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f51489fba0f558b1a6e2c59ec1a7bb7d5590ad18/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bd3d0368-72f4-47f6-9257-45acea084cc0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f51489fba0f558b1a6e2c59ec1a7bb7d5590ad18/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 84 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3e5055d1-778a-41fb-af7a-e9ab04f8bd90) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f51489fba0f558b1a6e2c59ec1a7bb7d5590ad18/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 89 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7fbb2e95-bc62-4816-ba4f-a83bea15915f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f51489fba0f558b1a6e2c59ec1a7bb7d5590ad18/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 89 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8f9c378e-3f3c-4876-b89a-903ffd0ad709) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f51489fba0f558b1a6e2c59ec1a7bb7d5590ad18/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/26f7f4e2-d037-4ac7-a9b6-80096a40f28f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f51489fba0f558b1a6e2c59ec1a7bb7d5590ad18/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3ebaedac-12a0-42c0-bb70-8a479f2b5507) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-08-14 09:17 UTC, Wajeed-msft approved these changes

2024-08-20 07:31 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/146db0033255760646c6a6ed986d9742fc9e6cf7/msteams-platform%2FTOC.yml) | 92 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bdf2c141-02ef-4f85-a481-253885dfe00c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/146db0033255760646c6a6ed986d9742fc9e6cf7/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c8c343ad-533c-453c-8dbc-66cb17fc1b79) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/146db0033255760646c6a6ed986d9742fc9e6cf7/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 84 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d0c03687-338d-475b-9c0f-318c66225bc4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/146db0033255760646c6a6ed986d9742fc9e6cf7/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 89 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/18d520ca-07fd-4c5b-a19a-faf1ae6f3027) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/146db0033255760646c6a6ed986d9742fc9e6cf7/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 89 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/031a8e64-ef91-40f4-80a9-5ed6fbe441dc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/146db0033255760646c6a6ed986d9742fc9e6cf7/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 88 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/192d2a81-9570-4e67-a9af-33bab9accd83) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/146db0033255760646c6a6ed986d9742fc9e6cf7/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5eb182f0-3d88-437c-8e0f-244fff51ad93) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-08-28 02:19 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7cb6cb5e416ac7f7205a1174d25fce23a09dc70f/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2c52089f-a859-4141-8d1f-f0fee7302d84) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7cb6cb5e416ac7f7205a1174d25fce23a09dc70f/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 84 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e4134d30-89e0-452a-bfd7-88bd82513bd5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7cb6cb5e416ac7f7205a1174d25fce23a09dc70f/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 89 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e193dabf-225b-4058-9f37-b26d66a4b962) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7cb6cb5e416ac7f7205a1174d25fce23a09dc70f/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ad73dbae-f482-4db8-84e8-c38caa23b84a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7cb6cb5e416ac7f7205a1174d25fce23a09dc70f/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/27eae1a6-e65f-48be-bf0a-efb32b4eb212) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7cb6cb5e416ac7f7205a1174d25fce23a09dc70f/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/50f0defa-5715-422f-861e-dc0e0363febb) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-08-29 08:44 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/66a316b7b92e7ab5bee6fac58a75372edc20cd28/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/024f9f84-96a4-47a4-bb05-f08ec107eb6c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/66a316b7b92e7ab5bee6fac58a75372edc20cd28/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 85 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/eb57ece3-3828-4053-b83a-73da4e7913e9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/66a316b7b92e7ab5bee6fac58a75372edc20cd28/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 89 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2c7d2514-e2ab-41cc-8151-198abda738df) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/66a316b7b92e7ab5bee6fac58a75372edc20cd28/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/05bd8bbf-6975-4119-af4e-e425a5478b44) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/66a316b7b92e7ab5bee6fac58a75372edc20cd28/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a1d7d91c-27db-4630-959e-e78ea8c2ac2f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/66a316b7b92e7ab5bee6fac58a75372edc20cd28/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c7b2fd66-38a3-4d68-99d5-f1b743cb5458) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-08-29 11:26 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/90625c313890d6e09ee291fd6aa27337bccf3f8e/msteams-platform%2FTOC.yml) | 92 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dcb78685-732c-4d5b-8885-67bf6f72112a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/90625c313890d6e09ee291fd6aa27337bccf3f8e/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f3906340-5a01-47a0-9ba0-65e690427c6c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/90625c313890d6e09ee291fd6aa27337bccf3f8e/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 85 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d38fceae-77df-48bf-8c27-f4389889385d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/90625c313890d6e09ee291fd6aa27337bccf3f8e/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 89 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a07b55ea-6276-4136-a19e-e3cb6822441e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/90625c313890d6e09ee291fd6aa27337bccf3f8e/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/54c129fd-e705-451c-992e-5c35a707d257) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/90625c313890d6e09ee291fd6aa27337bccf3f8e/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a42aac6f-bda3-4411-8d13-814da7fe1ed8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/90625c313890d6e09ee291fd6aa27337bccf3f8e/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/03b198fe-6acb-4374-84d2-be94433118e7) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-09-16 06:57 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/32f1659dcdc3bf5e871521918fe97bee02420865/msteams-platform%2FTOC.yml) | 92 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/45d09d49-5d1b-46eb-acf6-61e6a31f9423) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/32f1659dcdc3bf5e871521918fe97bee02420865/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0d9171eb-0196-4e1d-8ae7-20c4b8f73caf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/32f1659dcdc3bf5e871521918fe97bee02420865/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 85 | 33 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/87444b35-5e34-4c9a-8d46-0ee74c0852f7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/32f1659dcdc3bf5e871521918fe97bee02420865/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 89 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/61995925-546c-49e8-b8e3-6a3247eeb758) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/32f1659dcdc3bf5e871521918fe97bee02420865/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0912f8e5-acb4-4cb3-9f76-abc36946a903) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/32f1659dcdc3bf5e871521918fe97bee02420865/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2447d0f6-cad9-4193-b7ed-2605779909e9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/32f1659dcdc3bf5e871521918fe97bee02420865/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/39f26a86-cd18-4165-a02d-ce8fe86cf1a1) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-09-16 08:02 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1a4458cc0e8f52c0c985c5db96ef18951fd7c206/msteams-platform%2FTOC.yml) | 92 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/de13dcb2-6f4f-438c-ac5d-1e7ef2b3ffce) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1a4458cc0e8f52c0c985c5db96ef18951fd7c206/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3f8b12d4-865f-4c5b-ab0e-28ae9133136f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1a4458cc0e8f52c0c985c5db96ef18951fd7c206/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 85 | 33 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2bb8a2ec-036e-4798-8d19-881f8b8240b5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1a4458cc0e8f52c0c985c5db96ef18951fd7c206/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 89 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bca6649f-3f83-49d4-8107-272d2fb3b386) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1a4458cc0e8f52c0c985c5db96ef18951fd7c206/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/51c997ad-c33f-4227-a3a0-3823f27bac50) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1a4458cc0e8f52c0c985c5db96ef18951fd7c206/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/94a3d38c-a08b-4f1d-9f6d-67bcfde392aa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1a4458cc0e8f52c0c985c5db96ef18951fd7c206/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 92 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/14cc5dd7-e553-47d8-8ead-4c8dc86f1843) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-09-23 13:05 UTC, Wajeed-msft approved these changes

2024-10-04 06:38 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/bfed8d7d253e4fd2182b9de6718ac1161e73a17b/msteams-platform%2FTOC.yml) | 92 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2877c935-4ac0-4354-9f65-5676606701a8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bfed8d7d253e4fd2182b9de6718ac1161e73a17b/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7d1ad7ab-4a8b-4b4e-9939-8bec0fb4c0f1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bfed8d7d253e4fd2182b9de6718ac1161e73a17b/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 85 | 33 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/23e47620-d1d5-410a-9805-63697ad4c077) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bfed8d7d253e4fd2182b9de6718ac1161e73a17b/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 89 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6ca4696b-666e-47e5-92e5-ba3b0f591476) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bfed8d7d253e4fd2182b9de6718ac1161e73a17b/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1e735b63-1e37-4124-9c38-15eda53f26a1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bfed8d7d253e4fd2182b9de6718ac1161e73a17b/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d82d5335-2bd0-47a8-acdb-1f4f81d5b447) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bfed8d7d253e4fd2182b9de6718ac1161e73a17b/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 92 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/664707ea-bacf-4778-b6b8-632b3c491ea1) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-10-04 06:48 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/2f83cff97d7f02c6b5746bcc64d6e62de95b56a7/msteams-platform%2FTOC.yml) | 92 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d225d782-5b43-4da7-857a-b60e3fdb3c3f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2f83cff97d7f02c6b5746bcc64d6e62de95b56a7/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/af0c8d1e-813a-4e9b-8e4e-647aa47c764b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2f83cff97d7f02c6b5746bcc64d6e62de95b56a7/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 85 | 33 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b64ccee1-679a-4118-a098-ac9d26a605fa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2f83cff97d7f02c6b5746bcc64d6e62de95b56a7/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 89 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3c87cde2-6868-4c82-b89e-0f44b293c612) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2f83cff97d7f02c6b5746bcc64d6e62de95b56a7/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d4c90cfe-8807-4e33-8fcc-62fa070e307e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2f83cff97d7f02c6b5746bcc64d6e62de95b56a7/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8e1147bc-6921-404c-95ba-55d557aba9b6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2f83cff97d7f02c6b5746bcc64d6e62de95b56a7/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 92 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/36363050-b268-495e-a525-686439e7b24e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-10-10 03:12 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e5f18e5e12d4c83bdcf4b21522825c7367c88fc1/msteams-platform%2FTOC.yml) | 92 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5bc113fd-6464-4996-a5dd-ba9f47c59ab0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e5f18e5e12d4c83bdcf4b21522825c7367c88fc1/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8748434f-2bdd-4af3-9fa0-88c7e6c325f3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e5f18e5e12d4c83bdcf4b21522825c7367c88fc1/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 85 | 33 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9a792724-f47e-45d0-a309-d5520ab8d5ba) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e5f18e5e12d4c83bdcf4b21522825c7367c88fc1/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 89 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2cbae758-6de0-4eba-bc5f-be4c6d6e509c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e5f18e5e12d4c83bdcf4b21522825c7367c88fc1/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6279988d-d0e4-4da6-83ef-e6d215938e2b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e5f18e5e12d4c83bdcf4b21522825c7367c88fc1/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e472f52e-c7a8-46d9-adc7-092728224916) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e5f18e5e12d4c83bdcf4b21522825c7367c88fc1/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 92 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f5006a31-497a-43f3-832a-c08e889008f3) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-10-10 03:21 UTC, akshatsingal-dev requested changes
I have questions on the need for a few of these changes upon closer inspection. Holding off for approval till after the conversation.

2024-10-10 03:28 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/352d9d4d65c5df666ae67daa41f599bb6c7a2333/msteams-platform%2FTOC.yml) | 92 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4ee3eb96-05c5-4f89-81ed-4478e0cb8527) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/352d9d4d65c5df666ae67daa41f599bb6c7a2333/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/066134df-4b38-4804-a7fa-1381bc086b8e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/352d9d4d65c5df666ae67daa41f599bb6c7a2333/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 85 | 33 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/38c8f639-4fff-459c-934a-78f449ddabe3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/352d9d4d65c5df666ae67daa41f599bb6c7a2333/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 89 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/33ed41d0-42de-4dc7-b31c-90d759d6101e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/352d9d4d65c5df666ae67daa41f599bb6c7a2333/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f9ee5f12-1afb-4ece-a547-96aa11e477c4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/352d9d4d65c5df666ae67daa41f599bb6c7a2333/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/57c9f024-44a1-4247-9faa-2a4ec93bb2ea) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/352d9d4d65c5df666ae67daa41f599bb6c7a2333/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 92 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2bfb0aae-10b3-4705-9b0e-e312fcfe5717) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-10-10 13:42 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/6830ef818c738b1aedd4ffd0e0f5b9901c73bcb4/msteams-platform%2FTOC.yml) | 92 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/097c2d42-b95a-4d15-99b7-769d5f2d7156) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6830ef818c738b1aedd4ffd0e0f5b9901c73bcb4/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/290859e1-5525-43f9-8e88-a36fc286e5f7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6830ef818c738b1aedd4ffd0e0f5b9901c73bcb4/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 85 | 33 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dbab8b40-3393-4f6f-a8e8-757c47a9ab1b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6830ef818c738b1aedd4ffd0e0f5b9901c73bcb4/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 89 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d301924f-8456-4311-a9eb-9d2517671689) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6830ef818c738b1aedd4ffd0e0f5b9901c73bcb4/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bdcff899-2858-41ab-968c-62234305e196) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6830ef818c738b1aedd4ffd0e0f5b9901c73bcb4/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 90 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dc098b09-cc8f-4c62-9648-0819b0ebd9cf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6830ef818c738b1aedd4ffd0e0f5b9901c73bcb4/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 92 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/82e4c9ce-b06e-4dab-9200-61f8170ab787) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-10-11 05:15 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/8bbf7db89cdcdb3df7e22131e9ca1c494d5c3cd9/msteams-platform%2FTOC.yml) | 92 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9538f1f3-e3c0-4c3c-9e88-bf890cfc9f1e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8bbf7db89cdcdb3df7e22131e9ca1c494d5c3cd9/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/424c82b0-3562-4f74-aa13-016e0611eec1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8bbf7db89cdcdb3df7e22131e9ca1c494d5c3cd9/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 85 | 33 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9cdfcdce-286e-4ef1-8ecf-33d490b77cc5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8bbf7db89cdcdb3df7e22131e9ca1c494d5c3cd9/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 89 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/baf7248a-b61c-435b-bff4-c81111cb143e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8bbf7db89cdcdb3df7e22131e9ca1c494d5c3cd9/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2726959c-ed46-46e6-b041-530fa29f9330) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8bbf7db89cdcdb3df7e22131e9ca1c494d5c3cd9/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 90 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3129d639-a756-4d0d-9545-aa7a755a9b7b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8bbf7db89cdcdb3df7e22131e9ca1c494d5c3cd9/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 92 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2d66d9a1-ed72-4e2e-9536-9939a295edc9) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-10-14 13:29 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/b10b16b25a4dab15cd18c8d8c5b21a85b023d4df/msteams-platform%2FTOC.yml) | 92 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/617219dd-b9f3-44a8-a811-3193b7217d45) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b10b16b25a4dab15cd18c8d8c5b21a85b023d4df/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5cfaa62d-aa96-497a-9b8b-52fdd22f3dcb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b10b16b25a4dab15cd18c8d8c5b21a85b023d4df/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 85 | 33 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d09dca9c-8aae-4b56-a075-26129d2fe4fb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b10b16b25a4dab15cd18c8d8c5b21a85b023d4df/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 89 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9c7821b6-4810-4313-bb49-e380eac11a58) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b10b16b25a4dab15cd18c8d8c5b21a85b023d4df/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/23aa36a4-e710-4e03-b0cb-f5cccf956c18) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b10b16b25a4dab15cd18c8d8c5b21a85b023d4df/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 90 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6172373b-6210-4709-81ae-d03760b5efa4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b10b16b25a4dab15cd18c8d8c5b21a85b023d4df/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 92 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3359d429-dce1-442d-8ac6-0f3721226ecf) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-10-14 13:54 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/9068e8d79b80b578a3935e1513208e2112961a78/msteams-platform%2FTOC.yml) | 92 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0139f5d7-a155-4066-93b3-7e0c6416db95) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9068e8d79b80b578a3935e1513208e2112961a78/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a959360d-19a1-4425-9a38-c8c602bcd379) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9068e8d79b80b578a3935e1513208e2112961a78/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 85 | 33 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c55c3421-b458-4d11-8a89-d1b608e6f0b6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9068e8d79b80b578a3935e1513208e2112961a78/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 89 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/108a2287-01a1-4bd0-b311-53f6ae87ee06) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9068e8d79b80b578a3935e1513208e2112961a78/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 89 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/90698775-2b1b-4e21-bd7e-df06c7ac483c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9068e8d79b80b578a3935e1513208e2112961a78/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4a8e0c9d-35bd-4601-8264-d5afb495cf05) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9068e8d79b80b578a3935e1513208e2112961a78/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 92 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/14e08eb5-591e-4bd1-bebb-cc55709f481b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-10-16 12:21 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/f9d5470218c433d3b17dfe2540a8716241827f83/msteams-platform%2FTOC.yml) | 92 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e5e9c83b-2d52-4ac7-ab9d-616864e8d460) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f9d5470218c433d3b17dfe2540a8716241827f83/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/edb6c4b5-6732-407a-97da-7d002a5f66cd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f9d5470218c433d3b17dfe2540a8716241827f83/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 85 | 33 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/50747bc4-24be-41dd-9540-e928d1d2400c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f9d5470218c433d3b17dfe2540a8716241827f83/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 89 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d6125704-685b-4e1c-ad93-83e706063d54) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f9d5470218c433d3b17dfe2540a8716241827f83/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 95 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7d44faaa-1faf-4906-b238-d0377a57ec72) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f9d5470218c433d3b17dfe2540a8716241827f83/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 87 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b2684f04-5efc-42b0-85b2-06080fa6317b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f9d5470218c433d3b17dfe2540a8716241827f83/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 92 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d2657dfe-0018-49ef-a937-974268257c82) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-10-18 09:39 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/99b430811dc6bead387402ba90ee31bf03091514/msteams-platform%2FTOC.yml) | 92 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e6635c55-0e39-4c54-9a85-64f1306896bb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/99b430811dc6bead387402ba90ee31bf03091514/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4c7e6b70-8014-45d6-92af-6fd968e4fdd9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/99b430811dc6bead387402ba90ee31bf03091514/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 85 | 33 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/74cd6ae7-a19c-49b0-878d-53ae4a456ba8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/99b430811dc6bead387402ba90ee31bf03091514/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 89 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dbc31d4d-3a3f-4074-b90e-32187e581340) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/99b430811dc6bead387402ba90ee31bf03091514/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 95 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1cdcadda-13cb-4120-af9b-fa6bb9a3b692) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/99b430811dc6bead387402ba90ee31bf03091514/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 87 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3bc714e0-2bc3-4f1b-92c9-c92af181f72c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/99b430811dc6bead387402ba90ee31bf03091514/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 92 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/88fc3e7a-27c2-4221-9d1d-ba5739558162) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-10-18 13:45 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ea84b1c0a0ea9c9f7ca25be1ebfceaafe3f91282/msteams-platform%2FTOC.yml) | 92 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/12f28092-b13f-4de9-9fc6-28f0e6dd2b9f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ea84b1c0a0ea9c9f7ca25be1ebfceaafe3f91282/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/089940fc-c4be-41ec-8b2c-545df61c6587) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ea84b1c0a0ea9c9f7ca25be1ebfceaafe3f91282/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 85 | 33 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6b576f75-ec8b-4abd-b8c6-89278ff3a7a3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ea84b1c0a0ea9c9f7ca25be1ebfceaafe3f91282/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 89 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/52febb70-d2f2-4dd8-8bfc-a6ddb365a4e6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ea84b1c0a0ea9c9f7ca25be1ebfceaafe3f91282/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 95 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aa653c93-f5e3-4148-9f53-fab6f5af4c9c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ea84b1c0a0ea9c9f7ca25be1ebfceaafe3f91282/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 88 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8c05131e-b6e2-4f31-87fe-c5554d0e8f51) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ea84b1c0a0ea9c9f7ca25be1ebfceaafe3f91282/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9792b9e2-869d-46fb-abd8-6d3e5b7c2c01) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-10-18 14:24 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/4016a8a742cc479fa2c6fba8828f7751f8fcd8b5/msteams-platform%2FTOC.yml) | 92 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1c468f41-d2de-4e8c-82cc-1ca50a5b19ae) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4016a8a742cc479fa2c6fba8828f7751f8fcd8b5/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/458554c7-4e3c-4b24-9ad7-97cd5c22f136) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4016a8a742cc479fa2c6fba8828f7751f8fcd8b5/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 86 | 33 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0e228a91-f4a3-4cf5-ab67-238ca28f9b25) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4016a8a742cc479fa2c6fba8828f7751f8fcd8b5/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 89 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0ca22c42-7d0c-4c5e-a23c-3dc2512f5bb3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4016a8a742cc479fa2c6fba8828f7751f8fcd8b5/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 97 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e4aee14d-27ed-4083-a88b-1dabf1e5d631) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4016a8a742cc479fa2c6fba8828f7751f8fcd8b5/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 88 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/25f48f7c-326f-41fd-bc8b-ff9bf8427872) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4016a8a742cc479fa2c6fba8828f7751f8fcd8b5/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9fcab8bb-a11e-4f93-9ad5-405b4993be67) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-10-18 14:34 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/bd301eda1a04642ddc35db9beffd595ba9362612/msteams-platform%2FTOC.yml) | 92 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/409a3b6d-c270-4aed-8578-cff49a2d737b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bd301eda1a04642ddc35db9beffd595ba9362612/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c4803e3e-9b1c-417d-aed3-0babe43f592b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bd301eda1a04642ddc35db9beffd595ba9362612/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 85 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/66c39fcb-4a59-4c49-ba5a-132523828903) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bd301eda1a04642ddc35db9beffd595ba9362612/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 89 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b01955c4-4c42-4aa8-b4fd-5d89ea062f70) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bd301eda1a04642ddc35db9beffd595ba9362612/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 97 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7aa2c6b2-bd49-44ad-8d92-222df35eeaf9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bd301eda1a04642ddc35db9beffd595ba9362612/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 88 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f647031d-7431-46d7-937e-a54d01fc3183) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bd301eda1a04642ddc35db9beffd595ba9362612/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f02196a9-2827-4c94-bc04-c353108b9917) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-11-05 06:20 UTC, ramindarS submitted a review, later dismissed

2024-11-13 10:25 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c3ea3f128e06332bfba379e1adaeda6f7965bc40/msteams-platform%2FTOC.yml) | 91 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4a433127-6181-4809-80e6-7044c5935655) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c3ea3f128e06332bfba379e1adaeda6f7965bc40/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d3b61a16-28cc-4583-b61f-ccd378ae21d8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c3ea3f128e06332bfba379e1adaeda6f7965bc40/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 85 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/19558b1c-cc0b-4458-8cd3-4de15208d70e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c3ea3f128e06332bfba379e1adaeda6f7965bc40/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 89 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/779ce2ae-047a-4d1f-9228-c7e3a16bbf26) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c3ea3f128e06332bfba379e1adaeda6f7965bc40/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 97 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8d01fb9a-fdf5-4e25-9ad3-87959c154899) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c3ea3f128e06332bfba379e1adaeda6f7965bc40/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 88 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1e9a0d72-f918-43cc-896e-b54999630010) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c3ea3f128e06332bfba379e1adaeda6f7965bc40/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b4bbd861-0227-4ead-8e24-34e4910bc296) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-11-13 13:09 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/9f475aa04d436b4aaf747943b1a78487faa549f3/msteams-platform%2FTOC.yml) | 91 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5568460b-fc21-4849-8c9d-90da14ea36f6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9f475aa04d436b4aaf747943b1a78487faa549f3/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d416ef7d-addc-4840-9a70-2ae52e7a96e1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9f475aa04d436b4aaf747943b1a78487faa549f3/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 85 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b1e9e560-0b1d-4c86-9c38-8f1f263888d8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9f475aa04d436b4aaf747943b1a78487faa549f3/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 89 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/704ede8f-0b7e-488e-841b-118f7f03aabc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9f475aa04d436b4aaf747943b1a78487faa549f3/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/98902020-0c67-445c-8cac-91d5df8546e3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9f475aa04d436b4aaf747943b1a78487faa549f3/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 88 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6719519a-dd60-4f39-b8b2-3f4314131de8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9f475aa04d436b4aaf747943b1a78487faa549f3/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6b9692c0-9e1c-48c0-8dfe-508007ba8799) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-11-13 16:35 UTC, akshatsingal-dev approved these changes

2024-11-13 16:48 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/b11cec72105c2558af45532838638742ee2e2133/msteams-platform%2FTOC.yml) | 91 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/76dfcb61-fa8a-4594-8457-5bd6502a71ce) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b11cec72105c2558af45532838638742ee2e2133/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b016af27-dc18-49a2-ba5f-c8c352d8adf6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b11cec72105c2558af45532838638742ee2e2133/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 85 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c34697c0-4c35-477f-af0c-3f0f2fea0586) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b11cec72105c2558af45532838638742ee2e2133/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 93 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9da766bd-b5c4-4276-a740-bed84a3d06b6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b11cec72105c2558af45532838638742ee2e2133/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0f88b95f-afdc-4707-a6a9-68b9413b3d5c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b11cec72105c2558af45532838638742ee2e2133/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 88 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/677ebbd0-b311-4b57-8da7-8b914fa26f11) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b11cec72105c2558af45532838638742ee2e2133/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1132213a-b3a5-49fe-a1e2-80290ad8ee16) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-11-22 14:28 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/6029b7024d9de3ba23bdd4f0c3c399db9b88a0e2/msteams-platform%2FTOC.yml) | 91 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/84bc6bb3-3d66-4ffa-bc13-5e6adc447350) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6029b7024d9de3ba23bdd4f0c3c399db9b88a0e2/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9bc51b8d-607c-4b7a-88bd-92221e7901ae) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6029b7024d9de3ba23bdd4f0c3c399db9b88a0e2/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 85 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5bfdd531-6dfb-4e62-9bf4-d187fae96280) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6029b7024d9de3ba23bdd4f0c3c399db9b88a0e2/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 93 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9ad7ed0c-4262-4f48-ae8c-13adc26d4074) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6029b7024d9de3ba23bdd4f0c3c399db9b88a0e2/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2680f0ba-17bf-4989-94b3-7b5a0ba27fa4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6029b7024d9de3ba23bdd4f0c3c399db9b88a0e2/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 88 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cc9fae3d-94ea-458f-a6b9-000a65a93371) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6029b7024d9de3ba23bdd4f0c3c399db9b88a0e2/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ac7be8d2-156e-45bc-b13f-70b460ee3c3d) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-11-25 11:52 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ebed9525d24c4bb33b5ceff07da03a7068f9fc8a/msteams-platform%2FTOC.yml) | 91 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8c5dc842-685b-4009-9985-e39d90e67af0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ebed9525d24c4bb33b5ceff07da03a7068f9fc8a/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d3bdc39e-8160-4e6e-b0c6-d0b86a4d5541) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ebed9525d24c4bb33b5ceff07da03a7068f9fc8a/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 85 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c81e1e49-0037-497c-b7bb-477e93b00fed) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ebed9525d24c4bb33b5ceff07da03a7068f9fc8a/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 93 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1067a22d-849e-4f07-84f5-c9a545b1bb5a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ebed9525d24c4bb33b5ceff07da03a7068f9fc8a/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8ee243a2-0f59-4c0d-bf57-e86e6408a7d4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ebed9525d24c4bb33b5ceff07da03a7068f9fc8a/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 88 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/49af5d68-86f6-4fc4-ba89-3d89cbe85d40) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ebed9525d24c4bb33b5ceff07da03a7068f9fc8a/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8a091976-826d-448a-add0-9167f13d1346) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-11-25 12:49 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/262550ec5897123179dabeb9f8f05f73186e6a42/msteams-platform%2FTOC.yml) | 91 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e4393f4a-dbcf-4b0e-affc-01b150516d45) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/262550ec5897123179dabeb9f8f05f73186e6a42/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f87351e6-b703-49f1-8ccc-e899fc1047eb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/262550ec5897123179dabeb9f8f05f73186e6a42/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 85 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3b4117a4-3852-4b86-aa95-b55b7bbc4b81) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/262550ec5897123179dabeb9f8f05f73186e6a42/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 93 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0459c132-5567-4ad6-8dee-b485b7e6302c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/262550ec5897123179dabeb9f8f05f73186e6a42/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/517df982-97d7-4190-ada3-729e31374478) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/262550ec5897123179dabeb9f8f05f73186e6a42/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 88 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/481e8dbf-433b-4252-8afc-b24722bcb159) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/262550ec5897123179dabeb9f8f05f73186e6a42/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5786856c-57c5-4118-9fec-68a22ca39577) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-11-26 10:58 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/26a3d2cd661a078e60c96edc8bfa851ea3437968/msteams-platform%2FTOC.yml) | 91 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9ea43596-f72b-46ea-b243-d946cd606fb8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/26a3d2cd661a078e60c96edc8bfa851ea3437968/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7af4936c-bf76-4833-bb35-3fab45df2f69) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/26a3d2cd661a078e60c96edc8bfa851ea3437968/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 85 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/376cd55a-4da1-4aa1-8fe0-c8c28f114b7e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/26a3d2cd661a078e60c96edc8bfa851ea3437968/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 93 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/870651bb-91af-481b-b66f-774cbe9c8579) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/26a3d2cd661a078e60c96edc8bfa851ea3437968/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/93b49189-ee28-4a6a-9ef4-917ac3c01799) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/26a3d2cd661a078e60c96edc8bfa851ea3437968/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 88 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a675ee7a-dc02-48da-b3d7-c3c464e7d50e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/26a3d2cd661a078e60c96edc8bfa851ea3437968/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aea38b7f-6fc8-4ca6-bb6c-5613393328b8) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-11-27 04:59 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a2c0b1b0a014b97832ae315af9f3f6dd1a16aa52/msteams-platform%2FTOC.yml) | 91 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3ca03c28-f2ae-4667-bf7d-c6d67030c02c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a2c0b1b0a014b97832ae315af9f3f6dd1a16aa52/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1105f40d-33f3-405b-a6a4-a390dc42d3aa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a2c0b1b0a014b97832ae315af9f3f6dd1a16aa52/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 85 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9081b7f2-4f11-4488-86b2-7e99f19922b2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a2c0b1b0a014b97832ae315af9f3f6dd1a16aa52/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 93 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/10d4bd37-8a9b-44ae-a01a-c1694f34aa90) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a2c0b1b0a014b97832ae315af9f3f6dd1a16aa52/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5a025368-1e24-4b02-8d12-6aff0ac949fd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a2c0b1b0a014b97832ae315af9f3f6dd1a16aa52/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1190e119-04e4-4642-a24c-604babb0140e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a2c0b1b0a014b97832ae315af9f3f6dd1a16aa52/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/929507f1-a0b7-42a7-8df4-39573e450b0b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-11-27 10:36 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1b5176df24666215ecdb489aee8cf9c1b60426d5/msteams-platform%2FTOC.yml) | 91 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7d425e60-f152-4663-ada4-f428280f6c9e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1b5176df24666215ecdb489aee8cf9c1b60426d5/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fa62d7a5-05f9-4963-9ff3-f929f629ddc1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1b5176df24666215ecdb489aee8cf9c1b60426d5/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 85 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0469acce-e1f9-48e6-89b5-6d5aeba1cc8d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1b5176df24666215ecdb489aee8cf9c1b60426d5/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 93 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/816a6e52-ef93-4b18-9dd1-d9e8c1508caa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1b5176df24666215ecdb489aee8cf9c1b60426d5/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f72db62b-8ce9-44fe-85ad-9e3c7c8aba9c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1b5176df24666215ecdb489aee8cf9c1b60426d5/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3172c755-95ab-441a-9407-629e16ff7f33) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/publish-saas-offer-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1b5176df24666215ecdb489aee8cf9c1b60426d5/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fpublish-saas-offer-app.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3225a1c7-46cb-4a8a-b5ab-7e81cdd5ce2e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-11-27 11:14 UTC, surbhigupta12 approved these changes

2024-11-27 11:14 UTC, v-deabira approved these changes

2024-11-27 11:15 UTC, merged