[Doc Improvement][Update limitation text for anonymous user][3180579]
MicrosoftDocs/msteams-docs pull request #9011
Opened 2023-07-11 09:43 UTC by v-npaladugu

2023-07-11 09:43 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-anonymous-user.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dafbe7ca9b5ba982ea768d259c155de3b14348af/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-anonymous-user.md) | 90 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5f3cc696-20c4-4f82-a8f7-28129bf5737a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-07-11 10:25 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-anonymous-user.md](https://github.com/MicrosoftDocs/msteams-docs/blob/786fa9e78d5aa7867ffe6fe45b5e2f7ae58be05d/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-anonymous-user.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b6e31471-0741-4b86-a28d-897acf9318c1) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-07-11 17:38 UTC, melu613 requested changes

2023-07-11 17:38 UTC, melu613 commented on msteams-platform/apps-in-teams-meetings/build-apps-for-anonymous-user.md
> +* Currently, the `getContext` API doesn't return a user ID for the anonymous user though the bot APIs do and it's not possible to correlate the anonymous user between these two APIs. If you need to t
Please remove "If you need to track the user's identity between your tab and bot, you must prompt the user to authenticate with an external identity provider."

2023-07-12 17:02 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-anonymous-user.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dda7ebc6160856990465c77464c4559f8aa909ae/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-anonymous-user.md) | 91 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/577c44f2-69bf-4cc8-ad1a-a3a50901ed50) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-07-12 20:42 UTC, melu613 approved these changes

2023-07-13 06:34 UTC, surbhigupta12 approved these changes

2023-07-13 06:35 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-anonymous-user.md](https://github.com/MicrosoftDocs/msteams-docs/blob/005e8cec91c5fc2e1cfa9e46128e493aba993651/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-anonymous-user.md) | 91 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/973fbe34-a184-40be-a6ea-541396a77312) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-07-13 06:36 UTC, merged