[Doc Improvement][Clouds overview][3099872]
MicrosoftDocs/msteams-docs pull request #9574
Opened 2023-09-29 08:01 UTC by v-preethah

2023-09-29 08:01 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6b02d7300e3d761bb122e4a8f8d63762f092597b/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 91 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d55f7769-bca5-46b1-b56f-40405c3fdbe9) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-10-05 08:55 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7d2c7046a972ba69354c88d7016a088ff96080a2/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 91 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/704c418a-4b6e-4311-a045-a37a2dd7bd67) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-10-05 11:50 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8752030156dab0e0cc2738bfa798a310574a92d2/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 89 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/549df94a-3165-44b8-b12d-e12dc3ef89ac) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-10-05 11:56 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/959b6cec695e46b49470f8e7fe4d1e647b846bfd/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 89 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/223ad85e-c81f-4fdb-9935-172a82385b8e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-10-06 13:28 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e0a92556a3f4fe8575f1e76056cc45871da60bd9/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 89 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ebfd8844-0776-4d9a-ad4a-5cce36477721) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-10-06 13:53 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e8fe7165cf6c24431d494c7518c2e84c2dd957b4/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 89 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5ffd88a5-1b1d-4551-9a49-8b9ae33c3d83) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-10-11 13:16 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/492119b23b0f59d20432dae5b9d549623bd92eaa/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 86 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/99353a5d-76ad-4541-8860-a0b2c82fa2c1) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-10-11 14:12 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4f66e3768f8b3b5496b5e88a476677fc16e06f31/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 84 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/366a92b0-09d3-45d2-99c3-801ba926d90b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-10-16 08:29 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c9910c953e932a4e19c9303822548cfee32e4e95/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 84 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8e71cab9-d41e-48b4-9229-c67d2ea905a3) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-10-16 13:52 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3bb6efc523445056c3a00ed46be3278dfb67296f/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 83 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d88dbaa2-8a8b-4ce3-b6b5-040409dddf95) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-10-17 05:18 UTC, v-deabira requested changes

2023-10-25 05:48 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7b8768961e9416b08d67fc0c275848f89b61c827/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 83 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/241e55e9-4aa8-4309-84f0-c3556d470f9f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-10-25 12:16 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4a44e73c573050ebe8cac26ea1cb73cbf8946290/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 83 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ff69a892-2c03-4fee-b982-a44f8388d99d) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-10-25 13:25 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/577d7dc2ecb6fd981c69ada5a890e0cd3af293e9/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 84 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d8e96065-aa86-4236-b8a6-d1128981f375) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-10-25 14:09 UTC, v-preethah commented on msteams-platform/concepts/cloud-overview.md
> + All Microsoft 365 Government plans supports Microsoft Teams platform but the capabilities each Government cloud supports differ. Also, government tenant may not have all the Teams features that's av
Updated.

2023-10-25 15:12 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d2b05b3ffedb0c4c84957ce552b30f9837ebb987/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 85 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3a8f8000-a6c2-4719-bd53-867f8e734740) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-10-25 15:24 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cb4588b5bc65079350df151010d966de0e0d0c3f/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 85 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5ff6eab5-86ef-46a6-8a9b-0e3839cfeb91) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-11-02 05:33 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e7df54d9dad88ecad78e95fb7e68a849ba0c7880/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 84 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/266d93cf-70a0-4d0b-8b07-dbb7561aa93b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-11-02 13:57 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e957e030d1b2efb1e32c1e54829694ed2cbefb5e/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 84 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/071b32ca-0ab1-4b07-bb05-5ec226eeaa0e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-11-07 10:28 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cca09f3014f9114dc6597bfcdec5991624258429/msteams-platform%2Fconcepts%2Fcloud-overview.md) |   |   | [link]( ) | [:warning:](# "Could not check with Acrolinx&#10;Please close and reopen pull request") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-11-07 10:31 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d983bddb52505f6126fe4560524124c974c3e506/msteams-platform%2Fconcepts%2Fcloud-overview.md) |   |   | [link]( ) | [:warning:](# "Could not check with Acrolinx&#10;Please close and reopen pull request") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-11-07 10:40 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bbcd17ad2c98034dbe74a22207952e2883520bfa/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 87 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/99a53c1c-31b7-43e2-acac-5bab208378a2) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-01-08 08:03 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5b0a655b7706a789ff0b8011fe5424241482ceac/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 87 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7aba888d-dbf5-4cca-b0b6-ee316ccc2704) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-01-23 04:04 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/abfeb0cd54b9c4ce26c4cf6532b8b2781bf92897/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 87 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/081aba34-c111-4ef4-b37a-340fa32c41af) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-02-20 11:39 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/654ab748f5e08057f70f4265aa0933ed11f13fa8/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 88 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/df4a7314-e74c-4c09-8458-824c118862c1) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-02-20 11:47 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2636e8bf32e55a0cf0a2cf5e404127cdf37718a0/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 88 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/623a279e-aa2f-4e31-8f7f-c1c01b8961e5) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-02-29 14:16 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/97ca8f044a62eb5271075564e65b35b8370a0cbc/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 90 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ccf935ef-8226-4571-b60f-626206362e9d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/97ca8f044a62eb5271075564e65b35b8370a0cbc/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 91 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8dec7f10-8b40-4916-996e-7ab8713d84ad) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/97ca8f044a62eb5271075564e65b35b8370a0cbc/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 85 | 28 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/43c2ef9d-398e-4636-9a4b-0f882c0d264f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-02-29 15:22 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b8f03d802bb7394b7e088e17ed6f2b10ca577fef/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 90 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0df248b5-3906-47c1-a8b9-e2c6121b633c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b8f03d802bb7394b7e088e17ed6f2b10ca577fef/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 91 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/715425c5-397e-48a0-b3b7-f33ac57776d0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b8f03d802bb7394b7e088e17ed6f2b10ca577fef/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 86 | 28 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7c6635fb-1685-402d-9172-afec8fe77d87) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-03-01 08:38 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bc0d69592f2f635e59e5e962a3184c2e64c271f9/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/97a376f8-34ad-4bde-b575-740288dd071f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bc0d69592f2f635e59e5e962a3184c2e64c271f9/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 89 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cbbf55c5-bb9f-4939-bba5-c6c4efe7b518) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bc0d69592f2f635e59e5e962a3184c2e64c271f9/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 83 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5e4fe50d-3a68-4d9e-8a3f-34a585ce961d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bc0d69592f2f635e59e5e962a3184c2e64c271f9/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 90 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8ca8cf5d-f33f-4754-bb0d-c7b4899a0505) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bc0d69592f2f635e59e5e962a3184c2e64c271f9/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 90 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/74f7fd90-4270-416f-919e-e70c42117d88) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bc0d69592f2f635e59e5e962a3184c2e64c271f9/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 91 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0da217cc-2213-4d9c-9a94-97069d027482) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bc0d69592f2f635e59e5e962a3184c2e64c271f9/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 86 | 28 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fd0a6cef-08f8-4cd6-a839-23ca607de13d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/integrating-web-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bc0d69592f2f635e59e5e962a3184c2e64c271f9/msteams-platform%2Fsamples%2Fintegrating-web-apps.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f92c7314-edaf-4eb1-9474-a9e8160333e7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/teams-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bc0d69592f2f635e59e5e962a3184c2e64c271f9/msteams-platform%2Fteams-faq.md) | 92 | 72 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2de603ef-2f2b-4465-b491-34bf78491aac) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/what-are-webhooks-and-connectors.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bc0d69592f2f635e59e5e962a3184c2e64c271f9/msteams-platform%2Fwebhooks-and-connectors%2Fwhat-are-webhooks-and-connectors.md) | 90 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c741e795-8455-4cf2-aaab-459e5fded417) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-03-01 11:59 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c052db2c58831d8a6031317ff8da32c826def2aa/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1e7b6e7d-9887-4d3f-94a7-784bef785f17) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c052db2c58831d8a6031317ff8da32c826def2aa/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 89 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4c70aa80-00a4-4942-9be6-a027cae2f678) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c052db2c58831d8a6031317ff8da32c826def2aa/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 83 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4c79b4c6-6e2b-42df-a57a-6bc0e684c781) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c052db2c58831d8a6031317ff8da32c826def2aa/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 90 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f1fd2ceb-5484-4cae-b61f-4e7ace372c15) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c052db2c58831d8a6031317ff8da32c826def2aa/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 90 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7cb4453a-cb02-4b78-a76c-d53a2e781db4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c052db2c58831d8a6031317ff8da32c826def2aa/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 91 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/02990ac7-bb1a-46e4-96b3-6b34743dd956) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c052db2c58831d8a6031317ff8da32c826def2aa/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 85 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8d27f060-e2d3-418b-84d7-e7da601d2ab5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/integrating-web-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c052db2c58831d8a6031317ff8da32c826def2aa/msteams-platform%2Fsamples%2Fintegrating-web-apps.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fbbb8b0d-26e1-4f43-bf1d-6dea5ad98ced) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/teams-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c052db2c58831d8a6031317ff8da32c826def2aa/msteams-platform%2Fteams-faq.md) | 92 | 72 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e66eb1f7-7297-4104-9ee8-e022538f3a25) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/what-are-webhooks-and-connectors.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c052db2c58831d8a6031317ff8da32c826def2aa/msteams-platform%2Fwebhooks-and-connectors%2Fwhat-are-webhooks-and-connectors.md) | 90 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ca847888-76b5-4a34-9233-2540de14ddbd) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-03-08 10:47 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/736cf0635487357da91958b3aad9bd42a72795e7/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7d7e501e-073c-4b3f-9116-7f26dd4d300f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/736cf0635487357da91958b3aad9bd42a72795e7/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 89 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/da74793d-0f23-4d1f-be94-57b3ab4ff486) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/736cf0635487357da91958b3aad9bd42a72795e7/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 83 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e5514336-bc9e-42fe-9e9e-552070bf743d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/736cf0635487357da91958b3aad9bd42a72795e7/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 90 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/98519fb1-e869-4993-b3ac-2d97d6a39cb7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/736cf0635487357da91958b3aad9bd42a72795e7/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 90 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/52ac8908-98ff-4275-be29-ef45d6b24cf7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/736cf0635487357da91958b3aad9bd42a72795e7/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 91 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2c552f7e-016c-404a-b528-7e3387b9df07) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/736cf0635487357da91958b3aad9bd42a72795e7/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 85 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/38681f91-49f3-4e51-bb6c-1fe6f38833fb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/integrating-web-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/736cf0635487357da91958b3aad9bd42a72795e7/msteams-platform%2Fsamples%2Fintegrating-web-apps.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/057a6040-f238-46a9-8c85-47be0c78309c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/teams-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/736cf0635487357da91958b3aad9bd42a72795e7/msteams-platform%2Fteams-faq.md) | 92 | 72 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/59bcb8c7-8fd6-4167-b8bc-2da498dc5289) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/what-are-webhooks-and-connectors.md](https://github.com/MicrosoftDocs/msteams-docs/blob/736cf0635487357da91958b3aad9bd42a72795e7/msteams-platform%2Fwebhooks-and-connectors%2Fwhat-are-webhooks-and-connectors.md) | 90 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7068e0c6-7ec6-44c5-8968-15aa39d75ab5) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-03-08 13:14 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2a2d38bebedf00dee4d21a0273a16a78f4925aec/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/88f9e96b-0682-4a8c-9d6a-635b60240da4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2a2d38bebedf00dee4d21a0273a16a78f4925aec/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 89 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/368a4310-2b8a-4c44-88b0-14e3b3b7b82d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2a2d38bebedf00dee4d21a0273a16a78f4925aec/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 83 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/290f3fdf-78be-4868-a699-16cb90972654) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2a2d38bebedf00dee4d21a0273a16a78f4925aec/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 90 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/26d8ff83-0e40-425f-b523-66758d4549c2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2a2d38bebedf00dee4d21a0273a16a78f4925aec/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 90 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/eaaa6156-fe38-4583-b104-2e55df8e86f7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2a2d38bebedf00dee4d21a0273a16a78f4925aec/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 91 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/50713065-6c01-4dfd-8cf5-ee6e371741f0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2a2d38bebedf00dee4d21a0273a16a78f4925aec/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 83 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/420f38ce-d68d-4327-9755-c17fa688ef92) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/integrating-web-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2a2d38bebedf00dee4d21a0273a16a78f4925aec/msteams-platform%2Fsamples%2Fintegrating-web-apps.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/572eaa6b-cacc-4d59-bfbe-da1da503be29) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/teams-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2a2d38bebedf00dee4d21a0273a16a78f4925aec/msteams-platform%2Fteams-faq.md) | 92 | 72 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/12bf77b2-893f-4c3c-82df-ce0c9d5fccfa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/what-are-webhooks-and-connectors.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2a2d38bebedf00dee4d21a0273a16a78f4925aec/msteams-platform%2Fwebhooks-and-connectors%2Fwhat-are-webhooks-and-connectors.md) | 90 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ee739efc-9701-4750-a716-ad7a186dc45e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-03-08 16:08 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/db8f9587b5f19691efd604646b9167d633aa90a0/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7911c474-a757-4529-a25d-e41047c135f9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/db8f9587b5f19691efd604646b9167d633aa90a0/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 89 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bd40c8fb-8313-4e47-b305-af3dff70b2e2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/db8f9587b5f19691efd604646b9167d633aa90a0/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 83 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f9759775-cf11-44ea-baed-3bb1cf570d5c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/db8f9587b5f19691efd604646b9167d633aa90a0/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 90 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ef05576b-d41d-4af0-a7e4-4ed4ce0a3407) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/db8f9587b5f19691efd604646b9167d633aa90a0/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 90 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/97607077-2540-4f59-be5d-2435107f00d9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/db8f9587b5f19691efd604646b9167d633aa90a0/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 91 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/65e9bc26-82de-49df-b27c-951b41e60f21) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/db8f9587b5f19691efd604646b9167d633aa90a0/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 83 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ad740fcb-9f16-4b8e-bfab-b02926c6f0a5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/integrating-web-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/db8f9587b5f19691efd604646b9167d633aa90a0/msteams-platform%2Fsamples%2Fintegrating-web-apps.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1a02619d-6388-4cc3-905f-21a5e159d1eb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/teams-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/db8f9587b5f19691efd604646b9167d633aa90a0/msteams-platform%2Fteams-faq.md) | 92 | 72 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e3021560-ca26-4f1a-8a37-7341e2766361) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/what-are-webhooks-and-connectors.md](https://github.com/MicrosoftDocs/msteams-docs/blob/db8f9587b5f19691efd604646b9167d633aa90a0/msteams-platform%2Fwebhooks-and-connectors%2Fwhat-are-webhooks-and-connectors.md) | 90 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/010c9379-ee7a-4329-be34-14ed1c668529) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-03-19 14:15 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5bfcc155300c3415e37a2e01c0f3a123ee7c6cb5/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1a3dd8a7-c8a4-44af-bcde-bb37790a348d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5bfcc155300c3415e37a2e01c0f3a123ee7c6cb5/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 88 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a59f3512-1b3f-46b6-ba59-a63bc1bdfa91) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5bfcc155300c3415e37a2e01c0f3a123ee7c6cb5/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 80 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/78f287e3-2b83-4f07-bd7c-4012f7d00cab) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5bfcc155300c3415e37a2e01c0f3a123ee7c6cb5/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 89 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/80d776d2-a1c4-40b1-9f74-c1d98e4809f4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5bfcc155300c3415e37a2e01c0f3a123ee7c6cb5/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 90 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5376aadf-7185-4c67-a6b9-8204d4d3e0be) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5bfcc155300c3415e37a2e01c0f3a123ee7c6cb5/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 91 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d3b255cd-d0fc-4e79-a816-b4ef6d9ba175) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5bfcc155300c3415e37a2e01c0f3a123ee7c6cb5/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 83 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e002ae65-9c7c-47cf-b021-3864c74973c2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/integrating-web-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5bfcc155300c3415e37a2e01c0f3a123ee7c6cb5/msteams-platform%2Fsamples%2Fintegrating-web-apps.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9f09184f-8117-4dba-a98e-e10aa6c4bddc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/teams-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5bfcc155300c3415e37a2e01c0f3a123ee7c6cb5/msteams-platform%2Fteams-faq.md) | 92 | 72 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4ee67023-145a-485c-bc64-1f734ff0145c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/what-are-webhooks-and-connectors.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5bfcc155300c3415e37a2e01c0f3a123ee7c6cb5/msteams-platform%2Fwebhooks-and-connectors%2Fwhat-are-webhooks-and-connectors.md) | 90 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5109f208-61eb-4e8a-953f-88ae06e87229) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-03-19 15:42 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b23d5f06f6ea61b675a920c602e72ff06af0c7ba/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 90 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8ca25b18-7251-4e15-a3ce-0dbc715c7bfe) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b23d5f06f6ea61b675a920c602e72ff06af0c7ba/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7785a595-e140-452f-806d-a50b726e554d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b23d5f06f6ea61b675a920c602e72ff06af0c7ba/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 88 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/29aa1c93-8b4a-45dc-bc93-173887429248) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b23d5f06f6ea61b675a920c602e72ff06af0c7ba/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 80 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2c077b31-c165-4032-bf72-faba89de6b0c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b23d5f06f6ea61b675a920c602e72ff06af0c7ba/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 89 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/580e2ce6-273b-47f8-a069-a4ea535295aa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b23d5f06f6ea61b675a920c602e72ff06af0c7ba/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 90 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0c4e64c9-0c1a-4eba-bd28-f1c39cf9831c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b23d5f06f6ea61b675a920c602e72ff06af0c7ba/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 91 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a46dffb1-b00f-4e74-a363-d6f069ef2f74) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b23d5f06f6ea61b675a920c602e72ff06af0c7ba/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 86 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/db82eb5b-23a8-415f-a3dd-33cd541b7a52) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/integrating-web-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b23d5f06f6ea61b675a920c602e72ff06af0c7ba/msteams-platform%2Fsamples%2Fintegrating-web-apps.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fa4f3eac-61cb-4ca6-9b24-cb64edd8d304) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/teams-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b23d5f06f6ea61b675a920c602e72ff06af0c7ba/msteams-platform%2Fteams-faq.md) | 92 | 72 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/47143686-d8a9-4d95-9a7e-0e351d085b47) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/what-are-webhooks-and-connectors.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b23d5f06f6ea61b675a920c602e72ff06af0c7ba/msteams-platform%2Fwebhooks-and-connectors%2Fwhat-are-webhooks-and-connectors.md) | 90 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/87d8f0e0-a6d2-4524-bd18-5687b3bd43dc) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-03-20 17:26 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bd0621c31f9835f72f399cd4101b5c477cf6ca5a/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 90 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1b0049a4-b1be-4f70-a96c-5c8e1af5bf7a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bd0621c31f9835f72f399cd4101b5c477cf6ca5a/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/247fa269-563f-4796-afb4-91df5035e016) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bd0621c31f9835f72f399cd4101b5c477cf6ca5a/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 88 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0f8a6d32-b45a-4b46-a30c-3eec17b2a898) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bd0621c31f9835f72f399cd4101b5c477cf6ca5a/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 80 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f4f1fc0d-ee23-4bbb-90e9-ff0451f82312) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bd0621c31f9835f72f399cd4101b5c477cf6ca5a/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 89 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f63595f9-75a2-42a4-b64c-b3454bed55f6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bd0621c31f9835f72f399cd4101b5c477cf6ca5a/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 90 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8d5a4d72-ab69-42b1-87d7-96a44e6158d9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bd0621c31f9835f72f399cd4101b5c477cf6ca5a/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 91 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/40715ecd-9b70-4cc5-b9e5-091811dd2711) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bd0621c31f9835f72f399cd4101b5c477cf6ca5a/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 88 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/71bee7a3-0e05-4aa9-9ee8-533254d69def) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/integrating-web-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bd0621c31f9835f72f399cd4101b5c477cf6ca5a/msteams-platform%2Fsamples%2Fintegrating-web-apps.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3525e002-a345-42cc-a231-edd250498f0c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/teams-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bd0621c31f9835f72f399cd4101b5c477cf6ca5a/msteams-platform%2Fteams-faq.md) | 92 | 72 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0a7e49c9-e1ce-4ad7-ba50-3cd18688d769) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/what-are-webhooks-and-connectors.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bd0621c31f9835f72f399cd4101b5c477cf6ca5a/msteams-platform%2Fwebhooks-and-connectors%2Fwhat-are-webhooks-and-connectors.md) | 90 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f315e314-ae7c-42f7-a1a9-70898237a36d) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-03-21 04:44 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c44f31a8756552c81a051e94ae4a76ee3a5c0d33/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 90 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/84ee435d-7ddf-4629-988f-3c9dcf9bb2f7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c44f31a8756552c81a051e94ae4a76ee3a5c0d33/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5d5f7c0c-d9eb-4afd-9577-f5ebc66bde35) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c44f31a8756552c81a051e94ae4a76ee3a5c0d33/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 88 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/be60f8b9-5c52-4587-9544-c8214c98a5d8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c44f31a8756552c81a051e94ae4a76ee3a5c0d33/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 80 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7bc03aba-5c49-4f29-806e-3875b87d73fa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c44f31a8756552c81a051e94ae4a76ee3a5c0d33/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 89 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8537f464-6a97-4a65-9c9d-67bb0c781638) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c44f31a8756552c81a051e94ae4a76ee3a5c0d33/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 90 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/32f35727-07e6-48d0-985b-32b4384ff8c2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c44f31a8756552c81a051e94ae4a76ee3a5c0d33/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 91 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/81f5b70e-5dd6-43ed-8962-e804a4d90e5e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c44f31a8756552c81a051e94ae4a76ee3a5c0d33/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 95 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/546623b7-f3d5-4674-961d-5f0f359298a8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/integrating-web-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c44f31a8756552c81a051e94ae4a76ee3a5c0d33/msteams-platform%2Fsamples%2Fintegrating-web-apps.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e0711720-e263-4676-8486-6a6f9399cc49) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/teams-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c44f31a8756552c81a051e94ae4a76ee3a5c0d33/msteams-platform%2Fteams-faq.md) | 92 | 72 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8c896649-7c25-41aa-99d5-800252fa3c66) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/what-are-webhooks-and-connectors.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c44f31a8756552c81a051e94ae4a76ee3a5c0d33/msteams-platform%2Fwebhooks-and-connectors%2Fwhat-are-webhooks-and-connectors.md) | 90 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/acef0756-a301-4bc6-baa8-72d2bf208590) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-03-21 04:46 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5bad5b6125a1d8dec68de5d65590a3184de8325f/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 90 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3a9e85f5-0b3b-42c8-bd16-c2b64944ddb5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5bad5b6125a1d8dec68de5d65590a3184de8325f/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/82ebe466-f191-48b2-a2ed-732844b088b8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5bad5b6125a1d8dec68de5d65590a3184de8325f/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 88 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a54008bb-f6cb-4118-ba87-a07289ceb999) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5bad5b6125a1d8dec68de5d65590a3184de8325f/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 80 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4adfeb91-ec68-4c6f-a1f4-7d655d9ecd62) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5bad5b6125a1d8dec68de5d65590a3184de8325f/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 89 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a47f2f5b-6b6d-4686-b814-2f411e7ec4bd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5bad5b6125a1d8dec68de5d65590a3184de8325f/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 90 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d0bb16c2-8e49-452b-b124-ca063c197733) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5bad5b6125a1d8dec68de5d65590a3184de8325f/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 91 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/17eacfe0-94a7-418e-80cb-837ac9eb7820) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5bad5b6125a1d8dec68de5d65590a3184de8325f/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 95 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8f771dd4-a262-4903-bc5c-f88c79e78f82) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/integrating-web-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5bad5b6125a1d8dec68de5d65590a3184de8325f/msteams-platform%2Fsamples%2Fintegrating-web-apps.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/32ce26a9-1500-4b46-8ca6-1e84e68ad6cb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/teams-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5bad5b6125a1d8dec68de5d65590a3184de8325f/msteams-platform%2Fteams-faq.md) | 92 | 72 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/37de791f-3391-4138-b076-12f4575c002b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/what-are-webhooks-and-connectors.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5bad5b6125a1d8dec68de5d65590a3184de8325f/msteams-platform%2Fwebhooks-and-connectors%2Fwhat-are-webhooks-and-connectors.md) | 90 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/beede028-c511-487f-915c-daf95f8acd23) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-03-21 05:21 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/305815aaa635eb4ef0c000ad8b9e19e0c6650b59/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 90 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/089fd5cd-a20b-4a65-96c4-62753bd8a7bb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/305815aaa635eb4ef0c000ad8b9e19e0c6650b59/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8c2aaf42-39d7-449d-bd20-ac35bc859a27) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/305815aaa635eb4ef0c000ad8b9e19e0c6650b59/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 88 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/eaf6205b-a974-4d7f-9089-930af7e55bdf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/305815aaa635eb4ef0c000ad8b9e19e0c6650b59/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 80 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/38c80658-35c0-446f-b388-2a9b4a01ac5b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/305815aaa635eb4ef0c000ad8b9e19e0c6650b59/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 89 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8430a397-7e1d-4155-97ce-fed92ebcc5f9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/305815aaa635eb4ef0c000ad8b9e19e0c6650b59/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 90 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a3c49b52-7dfc-4fbe-aa74-341c6a6bb929) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/305815aaa635eb4ef0c000ad8b9e19e0c6650b59/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 91 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fc68e577-a5f3-4520-8764-6e7870859775) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/305815aaa635eb4ef0c000ad8b9e19e0c6650b59/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 95 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/49aac1a1-59b6-43fc-939a-9d3c7d3e633e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/integrating-web-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/305815aaa635eb4ef0c000ad8b9e19e0c6650b59/msteams-platform%2Fsamples%2Fintegrating-web-apps.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ff96738c-d8dc-4c9b-b094-3d2fec1a432a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/teams-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/305815aaa635eb4ef0c000ad8b9e19e0c6650b59/msteams-platform%2Fteams-faq.md) | 92 | 72 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/db96161e-2d49-4938-bb82-52d4874719c1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/what-are-webhooks-and-connectors.md](https://github.com/MicrosoftDocs/msteams-docs/blob/305815aaa635eb4ef0c000ad8b9e19e0c6650b59/msteams-platform%2Fwebhooks-and-connectors%2Fwhat-are-webhooks-and-connectors.md) | 90 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7b41facb-54fd-4830-b212-761f90170172) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-03-21 05:29 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/870724d60fdef1c59a8ee3ad07aed97f632f5965/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 90 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/67aedc52-9e59-4ba1-b84d-86f61846a07b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/870724d60fdef1c59a8ee3ad07aed97f632f5965/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c1748fe3-5d99-4557-9b58-61421d07ee74) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/870724d60fdef1c59a8ee3ad07aed97f632f5965/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 88 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ea88b2c4-1997-4138-91de-6148f24a0553) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/870724d60fdef1c59a8ee3ad07aed97f632f5965/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 80 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a468be52-0c54-478f-a31b-bf96cc6485a6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/870724d60fdef1c59a8ee3ad07aed97f632f5965/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 89 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e2352ab6-ce7e-4780-aeb2-9e2d2c1e054c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/870724d60fdef1c59a8ee3ad07aed97f632f5965/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 90 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b641cd03-2eac-47df-bea0-493f984034a7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/870724d60fdef1c59a8ee3ad07aed97f632f5965/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 91 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a417ee5e-3384-4b42-91f5-2506366f9731) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/870724d60fdef1c59a8ee3ad07aed97f632f5965/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 95 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/987190d1-95bf-40aa-9c33-c15d5503f4ba) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/integrating-web-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/870724d60fdef1c59a8ee3ad07aed97f632f5965/msteams-platform%2Fsamples%2Fintegrating-web-apps.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6d6db9d7-708f-4a3b-af24-d90b196f8d13) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/teams-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/870724d60fdef1c59a8ee3ad07aed97f632f5965/msteams-platform%2Fteams-faq.md) | 92 | 72 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3703f108-47db-448e-aeaf-7a51bcbc909a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/what-are-webhooks-and-connectors.md](https://github.com/MicrosoftDocs/msteams-docs/blob/870724d60fdef1c59a8ee3ad07aed97f632f5965/msteams-platform%2Fwebhooks-and-connectors%2Fwhat-are-webhooks-and-connectors.md) | 90 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/06b26694-0ebd-4b48-afc0-4c62dc876df3) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-03-21 05:32 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a103f5b5d1d35162acee8f005c2bc046e2b17977/msteams-platform%2FTOC.yml) | 97 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2d53dbe9-770e-48d3-b303-85244feaa23f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a103f5b5d1d35162acee8f005c2bc046e2b17977/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 90 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f3796ea1-6b7b-48a5-9b1e-e1d427816d2b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a103f5b5d1d35162acee8f005c2bc046e2b17977/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f5fcf743-d47d-42c9-ab07-f6c7a06cdc47) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a103f5b5d1d35162acee8f005c2bc046e2b17977/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 88 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8834daa8-b07e-4edc-aafb-be8b068145bb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a103f5b5d1d35162acee8f005c2bc046e2b17977/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 80 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4cbca735-1d0d-4007-a3a3-c3550c31f529) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a103f5b5d1d35162acee8f005c2bc046e2b17977/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 89 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/69493229-979b-4897-9854-e0717b772fc0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a103f5b5d1d35162acee8f005c2bc046e2b17977/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 90 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/adfa59c4-2830-4da0-9ef6-c27eec796990) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a103f5b5d1d35162acee8f005c2bc046e2b17977/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 91 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cc4b77b4-d86c-4a17-b71d-6edf61938377) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a103f5b5d1d35162acee8f005c2bc046e2b17977/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 95 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/96fc72b5-b3be-40ca-ae73-530455ccec4c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/integrating-web-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a103f5b5d1d35162acee8f005c2bc046e2b17977/msteams-platform%2Fsamples%2Fintegrating-web-apps.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b9b4e910-dff9-4270-ab43-3d4f9a10efcb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/teams-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a103f5b5d1d35162acee8f005c2bc046e2b17977/msteams-platform%2Fteams-faq.md) | 92 | 72 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fa816ecf-7a29-4509-baa3-e27d5dc12fee) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/what-are-webhooks-and-connectors.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a103f5b5d1d35162acee8f005c2bc046e2b17977/msteams-platform%2Fwebhooks-and-connectors%2Fwhat-are-webhooks-and-connectors.md) | 90 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8ba1e54d-7780-46df-af54-4ca23300198c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-03-21 05:40 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/b6c4f995b285dd6e574d423bc62273cdbcdd71be/msteams-platform%2FTOC.yml) | 97 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/508d84a6-2918-4fc3-909f-c2382d67bbcc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b6c4f995b285dd6e574d423bc62273cdbcdd71be/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 90 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4bc999c4-f4d3-4dc2-b534-defaed40f4dd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b6c4f995b285dd6e574d423bc62273cdbcdd71be/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bed948d6-a84a-4a9a-a9a4-5d96d156eeff) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b6c4f995b285dd6e574d423bc62273cdbcdd71be/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 88 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/22994745-74b6-48ce-90a3-f3c63d30a682) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b6c4f995b285dd6e574d423bc62273cdbcdd71be/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 80 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d074e4b2-fad0-48b3-bc2f-5937c8a144de) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b6c4f995b285dd6e574d423bc62273cdbcdd71be/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 89 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e98fa1a9-0199-4dec-a58b-3edc8cda5e38) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b6c4f995b285dd6e574d423bc62273cdbcdd71be/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 90 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c96db099-5a1f-4021-a1b3-a9895adbf0a4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b6c4f995b285dd6e574d423bc62273cdbcdd71be/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 91 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1e73edaa-3d35-46aa-add9-1830171d72ef) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b6c4f995b285dd6e574d423bc62273cdbcdd71be/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 95 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4b0ec587-274c-4f86-8db7-62a4c93020da) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/integrating-web-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b6c4f995b285dd6e574d423bc62273cdbcdd71be/msteams-platform%2Fsamples%2Fintegrating-web-apps.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/543a2d41-e10c-418c-8c21-8c8e4149e582) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/teams-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b6c4f995b285dd6e574d423bc62273cdbcdd71be/msteams-platform%2Fteams-faq.md) | 92 | 72 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a8f4a5f2-f095-4378-a46e-0ef9926c0069) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/what-are-webhooks-and-connectors.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b6c4f995b285dd6e574d423bc62273cdbcdd71be/msteams-platform%2Fwebhooks-and-connectors%2Fwhat-are-webhooks-and-connectors.md) | 90 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c484e5b3-f451-4830-8170-4ea418a6952d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b6c4f995b285dd6e574d423bc62273cdbcdd71be/msteams-platform%2Fwhats-new.md) | 92 | 65 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0a97a04e-0676-415c-8c57-89434d172b41) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-03-21 05:44 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/7258249de89d99d224013aea4d5d122bca47e397/msteams-platform%2FTOC.yml) | 97 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/46818b2c-a21e-484b-ae7b-e29c1eb2c07d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7258249de89d99d224013aea4d5d122bca47e397/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 90 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/afffe076-4538-4f23-877a-b8ab4e520a4e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7258249de89d99d224013aea4d5d122bca47e397/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b0677c3a-f1b8-4a1c-b42f-90cb1aea4315) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7258249de89d99d224013aea4d5d122bca47e397/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 88 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a4b18ae7-604d-4394-95e6-379e7461c9da) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7258249de89d99d224013aea4d5d122bca47e397/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 80 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cf87d4e3-4049-4a43-800a-b2b561996145) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7258249de89d99d224013aea4d5d122bca47e397/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 89 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/15c72cc3-58e8-4249-aa73-ad81de8ad428) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7258249de89d99d224013aea4d5d122bca47e397/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4fa3f566-772b-4d32-94a3-18152d510b11) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7258249de89d99d224013aea4d5d122bca47e397/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 91 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ca9c7b66-00c9-4af1-aa20-fb79b0934d73) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7258249de89d99d224013aea4d5d122bca47e397/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 95 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7e5b2458-445c-4245-81be-0ade5a9d6772) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/integrating-web-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7258249de89d99d224013aea4d5d122bca47e397/msteams-platform%2Fsamples%2Fintegrating-web-apps.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e789e041-7a86-46ff-bfdd-7591e032580b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/teams-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7258249de89d99d224013aea4d5d122bca47e397/msteams-platform%2Fteams-faq.md) | 92 | 72 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/855f932f-8c0d-4071-a05d-3e3e655c8b47) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/what-are-webhooks-and-connectors.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7258249de89d99d224013aea4d5d122bca47e397/msteams-platform%2Fwebhooks-and-connectors%2Fwhat-are-webhooks-and-connectors.md) | 90 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/678edf5e-8ae7-4742-b61b-c5750a5cd28c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7258249de89d99d224013aea4d5d122bca47e397/msteams-platform%2Fwhats-new.md) | 92 | 65 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1d87a1cd-194d-4d23-9938-36245d4a92c6) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-03-21 14:19 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/fd4a06bb1272527dab3ead9d41bba626094ea5e5/msteams-platform%2FTOC.yml) | 97 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/319ebc98-4842-429b-8686-b77e8f098275) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fd4a06bb1272527dab3ead9d41bba626094ea5e5/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 90 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b7c45883-7f37-42f6-ab33-e8ddf8c4da37) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fd4a06bb1272527dab3ead9d41bba626094ea5e5/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9be25e8d-a410-4493-ac45-201cc575664a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fd4a06bb1272527dab3ead9d41bba626094ea5e5/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 88 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/076e2ecc-809c-48af-9e50-17ec10fcd717) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fd4a06bb1272527dab3ead9d41bba626094ea5e5/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 80 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/eb7554e3-5bf9-4385-9582-367b010cf19f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fd4a06bb1272527dab3ead9d41bba626094ea5e5/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 89 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e1b7d189-ea9b-4c05-ba26-3aa8a43552e1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fd4a06bb1272527dab3ead9d41bba626094ea5e5/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/821dfc9e-4491-434a-b65c-86fa3c176e11) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fd4a06bb1272527dab3ead9d41bba626094ea5e5/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 91 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8cfe8ec2-89b9-4c7c-8b25-6fc099e6c60e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fd4a06bb1272527dab3ead9d41bba626094ea5e5/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 95 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d9dea627-aea9-43ff-9388-80c4ccae5c7c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/integrating-web-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fd4a06bb1272527dab3ead9d41bba626094ea5e5/msteams-platform%2Fsamples%2Fintegrating-web-apps.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8b9f87dd-160c-4fb2-9b67-c96cf53eba7d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/teams-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fd4a06bb1272527dab3ead9d41bba626094ea5e5/msteams-platform%2Fteams-faq.md) | 92 | 72 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/67a8fbec-b71e-4f8c-94b7-2e80f3f46e0d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/what-are-webhooks-and-connectors.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fd4a06bb1272527dab3ead9d41bba626094ea5e5/msteams-platform%2Fwebhooks-and-connectors%2Fwhat-are-webhooks-and-connectors.md) | 90 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d30d5b4f-76e0-4ae4-9fa2-bd904c6a27f9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fd4a06bb1272527dab3ead9d41bba626094ea5e5/msteams-platform%2Fwhats-new.md) | 92 | 65 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/df0345c5-ef13-4c34-acc6-f7ffe92b303d) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2024-03-25 06:45 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/b4c8c224a5980ea51d0cf9fc8e497b00609e7d30/msteams-platform%2FTOC.yml) | 97 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/20549dfa-1c58-4b46-b632-3c8348ab777e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b4c8c224a5980ea51d0cf9fc8e497b00609e7d30/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 90 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/47c87425-f216-4e35-ad04-2f19a653ee9c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b4c8c224a5980ea51d0cf9fc8e497b00609e7d30/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 91 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5bb88dfb-9f61-4217-bd44-bd697162fd3f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b4c8c224a5980ea51d0cf9fc8e497b00609e7d30/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 88 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bc9a2667-7f05-4139-ade9-63747548e43c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b4c8c224a5980ea51d0cf9fc8e497b00609e7d30/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 86 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/14fff6dd-0959-4c61-a05d-950408af2cc6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b4c8c224a5980ea51d0cf9fc8e497b00609e7d30/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 80 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bacf3821-f022-422e-8b2d-0b7d4bb04975) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b4c8c224a5980ea51d0cf9fc8e497b00609e7d30/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 90 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ea98bf75-5758-4bad-9138-83845cb35f77) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b4c8c224a5980ea51d0cf9fc8e497b00609e7d30/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 93 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b0ca3942-089f-4189-bec7-65592c382d25) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b4c8c224a5980ea51d0cf9fc8e497b00609e7d30/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 89 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/717e9f59-95b6-422c-a5d7-b7797009e68b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b4c8c224a5980ea51d0cf9fc8e497b00609e7d30/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8f86362d-b738-40d3-b8f4-64fb95cc611b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b4c8c224a5980ea51d0cf9fc8e497b00609e7d30/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/33313e7b-cfea-412d-aa6d-61ee22c18e0d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b4c8c224a5980ea51d0cf9fc8e497b00609e7d30/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 91 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3513fc45-1446-4dbc-bb30-5f59651f8272) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/shared-channels.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b4c8c224a5980ea51d0cf9fc8e497b00609e7d30/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshared-channels.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/80f40788-027b-410c-9fd7-d1babf02b8cc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/teams-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b4c8c224a5980ea51d0cf9fc8e497b00609e7d30/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fteams-developer-portal.md) | 91 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5dd67b0f-d801-4141-8117-813fa455fac6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b4c8c224a5980ea51d0cf9fc8e497b00609e7d30/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 95 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/505479dd-7740-4e6d-aa34-ed1a710ded21) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b4c8c224a5980ea51d0cf9fc8e497b00609e7d30/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-publish-overview.md) | 92 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9de52799-45ac-488f-b1a7-507adeb553da) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b4c8c224a5980ea51d0cf9fc8e497b00609e7d30/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/95ec2563-874a-43a6-b292-119448bd6af8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b4c8c224a5980ea51d0cf9fc8e497b00609e7d30/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fsubmission-checklist.md) | 89 | 45 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2925322d-6edb-4d04-872e-c0c84c2327a0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b4c8c224a5980ea51d0cf9fc8e497b00609e7d30/msteams-platform%2Fget-started%2Fglossary.md) | 92 | 68 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f1b94aab-0443-499e-a364-f9ceadcfe18a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/what-are-messaging-extensions.md](https://github.com/Microsoft [...]

2024-03-25 07:16 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/9f14d822869a9d3000706835337f9d4ed689e3c0/msteams-platform%2FTOC.yml) | 97 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c15e70ab-2331-4bce-9f00-8a465cc09f8a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9f14d822869a9d3000706835337f9d4ed689e3c0/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 90 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e79da7e2-2c3b-40c2-8749-e4b2e3a240d7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9f14d822869a9d3000706835337f9d4ed689e3c0/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 91 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e621f2a3-7ae6-4c4c-a6b1-b7ae2f9112ce) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9f14d822869a9d3000706835337f9d4ed689e3c0/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 88 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a361d722-1983-45d0-b1b3-3f7558853535) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9f14d822869a9d3000706835337f9d4ed689e3c0/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 86 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f2220fe5-bea0-49c3-90f9-93a7d5558902) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9f14d822869a9d3000706835337f9d4ed689e3c0/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 80 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7286b527-cc03-4c88-956a-79bc3c134f9f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9f14d822869a9d3000706835337f9d4ed689e3c0/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 90 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0db45359-ae6b-4e4c-9159-b5c8fcb6bc07) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9f14d822869a9d3000706835337f9d4ed689e3c0/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 93 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/eae7f550-70ec-49d7-9837-9b7c319608e0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9f14d822869a9d3000706835337f9d4ed689e3c0/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 89 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9ce06b08-1ee6-48f9-8a99-b6a1e5bddba9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9f14d822869a9d3000706835337f9d4ed689e3c0/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9d3b39f3-b7a5-4318-b713-6ae220c05cb3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9f14d822869a9d3000706835337f9d4ed689e3c0/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d9914ec6-291e-4e3d-bbf4-9ffdb3d11e6c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9f14d822869a9d3000706835337f9d4ed689e3c0/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 91 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/61c7e865-3ed9-4a29-bb3d-5974d3fbea6d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/shared-channels.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9f14d822869a9d3000706835337f9d4ed689e3c0/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshared-channels.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fed33563-6e04-4b4f-8902-2493677fbcf4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/teams-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9f14d822869a9d3000706835337f9d4ed689e3c0/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fteams-developer-portal.md) | 91 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/48897395-de5a-4a4a-8ba6-3b9b60fbb319) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9f14d822869a9d3000706835337f9d4ed689e3c0/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 95 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a43fe57a-2525-44a3-9cfc-37b4e96e2cd4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9f14d822869a9d3000706835337f9d4ed689e3c0/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-publish-overview.md) | 92 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d5aa96d8-63cc-4ddc-b6cd-7f6159732584) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9f14d822869a9d3000706835337f9d4ed689e3c0/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0f58f495-ff36-4899-832f-d8c1bf24a93f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9f14d822869a9d3000706835337f9d4ed689e3c0/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fsubmission-checklist.md) | 89 | 45 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/64df0897-7b96-4f18-9a36-e206c067190e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9f14d822869a9d3000706835337f9d4ed689e3c0/msteams-platform%2Fget-started%2Fglossary.md) | 92 | 68 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cb730873-4327-43f5-b518-72a6826185a6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/what-are-messaging-extensions.md](https://github.com/Microsoft [...]

2024-03-26 03:59 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/4ad6b5b095f5af6e451fcda4b9512472427ba104/msteams-platform%2FTOC.yml) | 97 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a1c25db2-fb8d-49bf-b213-51944af19fa8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4ad6b5b095f5af6e451fcda4b9512472427ba104/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 90 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/23d88a10-1c19-4fb3-b702-3dc48fd83828) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4ad6b5b095f5af6e451fcda4b9512472427ba104/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 91 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e5f9e6ed-05a4-43fc-8ceb-6f0575cfed73) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4ad6b5b095f5af6e451fcda4b9512472427ba104/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 88 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/722faa87-8fca-4dde-bb34-ed04a57754b2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4ad6b5b095f5af6e451fcda4b9512472427ba104/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 86 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/67a8d7ad-ca22-44d3-96f3-903daf13488b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4ad6b5b095f5af6e451fcda4b9512472427ba104/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 80 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3b166db5-9300-4969-9db9-b774b711fa8a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4ad6b5b095f5af6e451fcda4b9512472427ba104/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 90 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cf4f7db3-e09f-4c7a-b73f-3b0750a94db8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4ad6b5b095f5af6e451fcda4b9512472427ba104/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 93 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/836a81e2-decc-4359-9c36-c1b1688d6ece) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4ad6b5b095f5af6e451fcda4b9512472427ba104/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 89 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/79460cd6-f044-45b4-baf5-da7a158e26c8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4ad6b5b095f5af6e451fcda4b9512472427ba104/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6feb7498-e307-47db-8829-38ec4daf11c2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4ad6b5b095f5af6e451fcda4b9512472427ba104/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fe2b28fe-b758-47ed-bfa9-96753761d53a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4ad6b5b095f5af6e451fcda4b9512472427ba104/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 91 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/63c26550-f9ed-4ff1-bede-efa2d0876fb3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/shared-channels.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4ad6b5b095f5af6e451fcda4b9512472427ba104/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshared-channels.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4ad6251a-b0c3-472e-ba41-96a2dcc4cbdf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/teams-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4ad6b5b095f5af6e451fcda4b9512472427ba104/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fteams-developer-portal.md) | 91 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/28d9ec2a-513d-412a-af14-7de7f30c05f7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4ad6b5b095f5af6e451fcda4b9512472427ba104/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 95 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/089cdfe1-0330-4f1d-9350-02f6f30c2735) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4ad6b5b095f5af6e451fcda4b9512472427ba104/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-publish-overview.md) | 92 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/19369502-4037-485a-a282-8e6d307c9149) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4ad6b5b095f5af6e451fcda4b9512472427ba104/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a8a5e7af-63fe-48e7-a895-ad8359e501d1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4ad6b5b095f5af6e451fcda4b9512472427ba104/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fsubmission-checklist.md) | 89 | 45 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/88098f70-7825-4f84-927a-57259368d801) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4ad6b5b095f5af6e451fcda4b9512472427ba104/msteams-platform%2Fget-started%2Fglossary.md) | 92 | 68 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c1b0d7d1-c9d9-45c5-b209-63092c23faa7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/what-are-messaging-extensions.md](https://github.com/Microsoft [...]

2024-03-26 12:20 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/4420d449be65cfeed38629b17e4b8a71b6005678/msteams-platform%2FTOC.yml) | 97 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7ae941d0-e008-4acc-9ffe-e971e2f32fa2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4420d449be65cfeed38629b17e4b8a71b6005678/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 90 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cf6804fa-7922-4d1b-8352-31aee84dca29) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4420d449be65cfeed38629b17e4b8a71b6005678/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 91 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5ae3db1e-3292-4b12-8eb7-b8fd59ea87d9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4420d449be65cfeed38629b17e4b8a71b6005678/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 88 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/33db733e-9e93-49df-b9b4-79917d75b697) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4420d449be65cfeed38629b17e4b8a71b6005678/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 86 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/63073656-47a1-4f73-8fdf-75bc2f584b89) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4420d449be65cfeed38629b17e4b8a71b6005678/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 80 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f18a98f9-6203-4c4e-9d73-d8a68b8cdbb4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4420d449be65cfeed38629b17e4b8a71b6005678/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 90 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cd13871b-d7e3-44ed-9107-c643c3e869ed) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4420d449be65cfeed38629b17e4b8a71b6005678/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 93 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/40a45075-6e76-4668-acc9-40c2a4db8bc2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4420d449be65cfeed38629b17e4b8a71b6005678/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 89 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7c5b027c-cad5-4a47-88c9-cd45b82538b2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4420d449be65cfeed38629b17e4b8a71b6005678/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/de02dbaf-e5de-4ffe-a0a3-b9f625bece41) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4420d449be65cfeed38629b17e4b8a71b6005678/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8ddbcab8-6dbf-4757-96a5-61f7f3d92fe6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4420d449be65cfeed38629b17e4b8a71b6005678/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 91 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/39291987-fffc-4e14-9395-c30fc153fbce) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/shared-channels.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4420d449be65cfeed38629b17e4b8a71b6005678/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshared-channels.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f39d3a4c-40ed-401b-adb8-896c91faed36) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/teams-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4420d449be65cfeed38629b17e4b8a71b6005678/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fteams-developer-portal.md) | 91 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/19fc18db-4ca7-4951-8c05-20fb99128611) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4420d449be65cfeed38629b17e4b8a71b6005678/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 95 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4de7770d-8b83-4695-9723-03a5b72127cf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4420d449be65cfeed38629b17e4b8a71b6005678/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-publish-overview.md) | 92 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/739ecf78-6902-42a5-bf26-670383303586) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4420d449be65cfeed38629b17e4b8a71b6005678/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c0652463-1b56-444e-8072-25d3ec17bc35) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4420d449be65cfeed38629b17e4b8a71b6005678/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fsubmission-checklist.md) | 89 | 45 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/19e897e9-fb3b-4b6e-931a-5c82fe7cee34) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4420d449be65cfeed38629b17e4b8a71b6005678/msteams-platform%2Fget-started%2Fglossary.md) | 92 | 68 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d3ea9ca7-f16b-4585-aac4-0d50030411c3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/what-are-messaging-extensions.md](https://github.com/Microsoft [...]

2024-03-28 09:35 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/da62ad8e5a2cbe3be4c358c91b19c90440aec902/msteams-platform%2FTOC.yml) | 97 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e2c678f3-70fb-4d69-8879-ec727939b193) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/da62ad8e5a2cbe3be4c358c91b19c90440aec902/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 90 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/867c5c4c-7a4f-4b18-837e-ea5a0748f8d5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/da62ad8e5a2cbe3be4c358c91b19c90440aec902/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 91 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/75057967-2e0a-445e-a68d-afe75b24e109) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/da62ad8e5a2cbe3be4c358c91b19c90440aec902/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 88 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/81013c59-35a7-4298-9e35-261283b45aca) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/da62ad8e5a2cbe3be4c358c91b19c90440aec902/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 86 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e563cc71-6aad-48ac-ad1e-0f8e819242e7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/da62ad8e5a2cbe3be4c358c91b19c90440aec902/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 80 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fd6fad40-b8d1-46f3-88f6-764c60fefa59) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/da62ad8e5a2cbe3be4c358c91b19c90440aec902/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 90 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/068500fb-c6a1-4eea-9028-cdf4c1fe15b5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/da62ad8e5a2cbe3be4c358c91b19c90440aec902/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 93 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8d0ca47e-7065-417b-a5fd-6a198f95a994) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/da62ad8e5a2cbe3be4c358c91b19c90440aec902/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 89 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/24cdc992-b0f0-4153-b617-dace2e2f0a4c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/da62ad8e5a2cbe3be4c358c91b19c90440aec902/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/83c2432a-7ea1-40f8-b4eb-d1c1f2b2d476) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/da62ad8e5a2cbe3be4c358c91b19c90440aec902/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/33587e03-5a73-4141-8f9a-0903e1464814) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/da62ad8e5a2cbe3be4c358c91b19c90440aec902/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 91 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/43721209-d955-44d6-93c8-31eb2056a6a2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/shared-channels.md](https://github.com/MicrosoftDocs/msteams-docs/blob/da62ad8e5a2cbe3be4c358c91b19c90440aec902/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshared-channels.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8cb45629-1637-4d7e-88b9-dfae9f5812fe) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/teams-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/da62ad8e5a2cbe3be4c358c91b19c90440aec902/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fteams-developer-portal.md) | 91 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/677ec2c1-e967-480d-965b-f1d4ab9e4102) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/da62ad8e5a2cbe3be4c358c91b19c90440aec902/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 96 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1c03d89b-697a-4c90-b964-7bd8b5d10365) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/da62ad8e5a2cbe3be4c358c91b19c90440aec902/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-publish-overview.md) | 92 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5a33fd07-f76c-4952-a34e-1c55f990781c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/da62ad8e5a2cbe3be4c358c91b19c90440aec902/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e65ecb2f-bcfb-4ed6-84fe-af5ec5f6fc9b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/da62ad8e5a2cbe3be4c358c91b19c90440aec902/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fsubmission-checklist.md) | 89 | 45 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e59d36bf-e737-419e-a830-a353f66f6c14) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/da62ad8e5a2cbe3be4c358c91b19c90440aec902/msteams-platform%2Fget-started%2Fglossary.md) | 92 | 68 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f095518a-87fe-4f02-9cc4-79b5cc536372) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/what-are-messaging-extensions.md](https://github.com/Microsoft [...]

2024-04-01 08:42 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/2ce79e1d0460d2cd2f63ad9b75e7fb26b79abfc9/msteams-platform%2FTOC.yml) | 96 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/25197b73-f654-465b-bb04-30fb2e33890d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2ce79e1d0460d2cd2f63ad9b75e7fb26b79abfc9/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 90 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1e22efc7-1285-4ef0-958d-925f57e22eff) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2ce79e1d0460d2cd2f63ad9b75e7fb26b79abfc9/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 91 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4f403095-bdba-45cf-b032-c5c2e4a04a56) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2ce79e1d0460d2cd2f63ad9b75e7fb26b79abfc9/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 88 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/17639e4a-f6c3-4d96-86e5-894c6995bbe7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2ce79e1d0460d2cd2f63ad9b75e7fb26b79abfc9/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 86 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/05e601b0-c805-4e00-a5a4-baf94fd7e6f9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2ce79e1d0460d2cd2f63ad9b75e7fb26b79abfc9/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 80 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a79d6ba4-899b-417d-9fc3-6f73040c393c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2ce79e1d0460d2cd2f63ad9b75e7fb26b79abfc9/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 90 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b89cf3ab-0efd-40f7-b6e0-cca12d372fa4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2ce79e1d0460d2cd2f63ad9b75e7fb26b79abfc9/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 93 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a334b256-9286-4580-93c8-43effc3cc9fa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2ce79e1d0460d2cd2f63ad9b75e7fb26b79abfc9/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 89 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3ec5d18e-9c0e-41d6-b5ba-71e5904419d8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2ce79e1d0460d2cd2f63ad9b75e7fb26b79abfc9/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f9511196-d38a-4676-9a41-bd41ec9b78ba) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2ce79e1d0460d2cd2f63ad9b75e7fb26b79abfc9/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0955b095-f6ae-4a30-9145-9cbaf2acaa04) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2ce79e1d0460d2cd2f63ad9b75e7fb26b79abfc9/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 91 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1676197c-97b4-4d63-b309-aef7a47aa3c2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/shared-channels.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2ce79e1d0460d2cd2f63ad9b75e7fb26b79abfc9/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshared-channels.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ca208939-bcc2-4f9d-bef4-4c98ca695498) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/teams-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2ce79e1d0460d2cd2f63ad9b75e7fb26b79abfc9/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fteams-developer-portal.md) | 91 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8e47ff96-90e9-4bc3-b1d1-67e6752bf002) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2ce79e1d0460d2cd2f63ad9b75e7fb26b79abfc9/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 96 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/227e45c3-aa50-4673-89d3-9877376ccf0b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2ce79e1d0460d2cd2f63ad9b75e7fb26b79abfc9/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-publish-overview.md) | 92 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fad039b9-8d59-48a2-8e3b-e33d7a2b2bfc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2ce79e1d0460d2cd2f63ad9b75e7fb26b79abfc9/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/686e184f-6c1c-47d2-883b-6f2464244e1d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2ce79e1d0460d2cd2f63ad9b75e7fb26b79abfc9/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fsubmission-checklist.md) | 89 | 45 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0029f4a3-28cb-4f4e-8777-9d80b6e88443) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2ce79e1d0460d2cd2f63ad9b75e7fb26b79abfc9/msteams-platform%2Fget-started%2Fglossary.md) | 90 | 77 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4d628d02-5a4b-4fec-8880-35d508324271) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/what-are-messaging-extensions.md](https://github.com/Microsoft [...]

2024-04-01 09:28 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/7e9802cf83c789bb1e92743b90b343197e17c363/msteams-platform%2FTOC.yml) | 96 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/155919ec-d4ea-4310-9d23-bc356de5337a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7e9802cf83c789bb1e92743b90b343197e17c363/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 90 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6d37f69c-e815-48e6-a6fa-102b12440711) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7e9802cf83c789bb1e92743b90b343197e17c363/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 91 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d6ba1293-4bd6-4b71-9bab-93108d3ad0dd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7e9802cf83c789bb1e92743b90b343197e17c363/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 88 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/976b9477-5e73-4989-bf92-2cc60eed915c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7e9802cf83c789bb1e92743b90b343197e17c363/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 86 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a95a86ea-46d0-4a61-9059-613f15b0d3dc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7e9802cf83c789bb1e92743b90b343197e17c363/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 80 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/54c8f7fb-a6d4-4098-96ee-795690f03870) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7e9802cf83c789bb1e92743b90b343197e17c363/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 90 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c077d8f7-ad6e-4817-9826-2c2f29506937) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7e9802cf83c789bb1e92743b90b343197e17c363/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 93 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bbaa3f96-6d27-4661-a620-c11f996e4495) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7e9802cf83c789bb1e92743b90b343197e17c363/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 89 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/88bd8283-6c8e-4a5f-809f-c60feb2f488d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7e9802cf83c789bb1e92743b90b343197e17c363/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/41bdfd64-f0cc-45b5-a036-c87004bcc3b4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7e9802cf83c789bb1e92743b90b343197e17c363/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f723b235-0ba1-4b24-a507-945c7aba659c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7e9802cf83c789bb1e92743b90b343197e17c363/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 91 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d73f0f5e-354e-4e77-8f03-4972fcc0b534) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/shared-channels.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7e9802cf83c789bb1e92743b90b343197e17c363/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshared-channels.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2b63238d-8a04-4341-852c-d0b98937bb03) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/teams-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7e9802cf83c789bb1e92743b90b343197e17c363/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fteams-developer-portal.md) | 91 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c1329b04-1ab5-45f7-a458-044905e602e6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7e9802cf83c789bb1e92743b90b343197e17c363/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 98 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d9e3552d-dda8-4287-9cf8-596fededfbe4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7e9802cf83c789bb1e92743b90b343197e17c363/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-publish-overview.md) | 92 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5f8e8dba-5162-49d0-b573-54cef4abbb6e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7e9802cf83c789bb1e92743b90b343197e17c363/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/26f77b82-706b-4de2-b91a-f41f68d54f05) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7e9802cf83c789bb1e92743b90b343197e17c363/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fsubmission-checklist.md) | 89 | 45 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5c9c1588-4749-4ec7-b1ff-45a3f58d1169) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7e9802cf83c789bb1e92743b90b343197e17c363/msteams-platform%2Fget-started%2Fglossary.md) | 90 | 77 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/81cd23b5-7896-496a-a842-4f8805019511) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/what-are-messaging-extensions.md](https://github.com/Microsoft [...]

2024-04-01 15:12 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/f2897d161aef17d884aed20dad35340e2b34b47b/msteams-platform%2FTOC.yml) | 96 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7a65399d-8a90-4b7a-a668-4ba46fcb1adc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f2897d161aef17d884aed20dad35340e2b34b47b/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 90 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/27220fe3-ddc0-480f-a2ee-89c0b508f310) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f2897d161aef17d884aed20dad35340e2b34b47b/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 91 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7e189492-568e-4135-9347-2edbb3c57772) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f2897d161aef17d884aed20dad35340e2b34b47b/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 88 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/77b4d150-6608-418d-a8d0-3044b130718e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f2897d161aef17d884aed20dad35340e2b34b47b/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 86 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/97ac7fef-9a29-4e90-9a82-ed26260ebfcf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f2897d161aef17d884aed20dad35340e2b34b47b/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 80 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fbe1f379-2d86-4da4-86a4-094d2a7cf6bb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f2897d161aef17d884aed20dad35340e2b34b47b/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 90 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/79401966-6e1a-498a-b25f-0070bfe040df) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f2897d161aef17d884aed20dad35340e2b34b47b/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 93 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/92a6e224-7762-4d50-8a8a-525255f706cc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f2897d161aef17d884aed20dad35340e2b34b47b/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 89 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dd322e75-f2a0-4c40-a628-5bd793ef873c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f2897d161aef17d884aed20dad35340e2b34b47b/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/de26a1f6-79ce-4df8-9c03-bb833e6b49dd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f2897d161aef17d884aed20dad35340e2b34b47b/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0cf97c24-365a-4637-b9c0-e83e20536280) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f2897d161aef17d884aed20dad35340e2b34b47b/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 91 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cfecc0ff-f5d7-46fe-8f73-f64d749a5ffb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/shared-channels.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f2897d161aef17d884aed20dad35340e2b34b47b/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshared-channels.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c4b59b54-34eb-48fa-a470-c5da20df8180) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/teams-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f2897d161aef17d884aed20dad35340e2b34b47b/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fteams-developer-portal.md) | 91 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a112d9a0-6401-423f-904b-ca37b8a72d60) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f2897d161aef17d884aed20dad35340e2b34b47b/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 99 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f009cda4-6409-414f-8412-932e3c8ecf6f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f2897d161aef17d884aed20dad35340e2b34b47b/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-publish-overview.md) | 92 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4ba6b8bb-6ebd-4261-80e4-6afee0dc86db) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f2897d161aef17d884aed20dad35340e2b34b47b/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7511ff11-ed31-486d-91db-9e70c61edb1c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f2897d161aef17d884aed20dad35340e2b34b47b/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fsubmission-checklist.md) | 89 | 45 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a983cc81-4559-45e2-abaf-fec668db7345) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f2897d161aef17d884aed20dad35340e2b34b47b/msteams-platform%2Fget-started%2Fglossary.md) | 90 | 77 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6f493455-3f32-4bc3-b26f-8afb7f35e456) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/what-are-messaging-extensions.md](https://github.com/Microsoft [...]

2024-04-01 15:31 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/d9b54c6597281a90b067779774782a7c809c242f/msteams-platform%2FTOC.yml) | 96 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3bd2fd5a-9066-4cd9-b288-312b19dce484) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d9b54c6597281a90b067779774782a7c809c242f/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 90 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/95c2f353-6327-4c3e-9930-41ffcca9f499) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d9b54c6597281a90b067779774782a7c809c242f/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 91 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/02af1f44-88a9-438e-b6e1-b45d40a8953d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d9b54c6597281a90b067779774782a7c809c242f/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 88 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9e14e3e7-3099-495b-b31e-928f4403514f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d9b54c6597281a90b067779774782a7c809c242f/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 86 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5f66ddbc-ce91-486a-8fcb-e97b3baebe11) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d9b54c6597281a90b067779774782a7c809c242f/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 80 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3769fca7-991f-4f79-8d8f-a81b35e67629) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d9b54c6597281a90b067779774782a7c809c242f/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 90 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/60a6aba6-be35-4813-a619-4da97441ad42) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d9b54c6597281a90b067779774782a7c809c242f/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 93 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8bc3f701-b93f-4cd1-a8d5-ed75b1e90545) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d9b54c6597281a90b067779774782a7c809c242f/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 89 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/41b87e18-0e0a-4fbc-abb2-11924b40423f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d9b54c6597281a90b067779774782a7c809c242f/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/82c19776-e843-4ca9-b125-0f8d12983dcf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d9b54c6597281a90b067779774782a7c809c242f/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/af0fcb7b-6b99-4c9e-9e80-743b25bc4c6b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d9b54c6597281a90b067779774782a7c809c242f/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 91 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0ab91c95-86bf-4373-9b12-c8bd86475520) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/shared-channels.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d9b54c6597281a90b067779774782a7c809c242f/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshared-channels.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/00551391-a679-4174-ae2d-065bb2b534fc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/teams-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d9b54c6597281a90b067779774782a7c809c242f/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fteams-developer-portal.md) | 91 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c355309b-02c1-41bf-be26-c36a92ee1b0f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d9b54c6597281a90b067779774782a7c809c242f/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 99 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f8c7cc12-3824-4e1d-9347-ec96a7e21e7d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d9b54c6597281a90b067779774782a7c809c242f/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-publish-overview.md) | 92 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d8e3a166-4647-43a3-9de2-532dfe359526) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d9b54c6597281a90b067779774782a7c809c242f/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d6a71d8a-165f-4131-9ca4-27ecce33e28e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d9b54c6597281a90b067779774782a7c809c242f/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fsubmission-checklist.md) | 89 | 45 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8b123918-bd88-4c2d-a06d-9937c4f39826) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d9b54c6597281a90b067779774782a7c809c242f/msteams-platform%2Fget-started%2Fglossary.md) | 90 | 77 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d2327099-0a70-43b1-b26b-2ca2c9d41a2c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/what-are-messaging-extensions.md](https://github.com/Microsoft [...]

2024-04-01 15:54 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/2f4528ee74ef0b1b7c621588c927458375a4fd0f/msteams-platform%2FTOC.yml) | 96 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/53055e9f-da8f-437d-b5fa-0195fcd0090d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2f4528ee74ef0b1b7c621588c927458375a4fd0f/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 90 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ba5b7c08-1915-46ae-938f-31f818d5027c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2f4528ee74ef0b1b7c621588c927458375a4fd0f/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 91 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8832f974-0c15-4906-8916-eaa10dbaba37) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2f4528ee74ef0b1b7c621588c927458375a4fd0f/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 88 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a4804e8d-0408-40ad-af8a-99565886fc74) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2f4528ee74ef0b1b7c621588c927458375a4fd0f/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 86 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b172a86b-e709-4442-acef-3f1b24eb22c0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2f4528ee74ef0b1b7c621588c927458375a4fd0f/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 80 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/538513da-1d01-4595-a580-ae8a88e03b8d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2f4528ee74ef0b1b7c621588c927458375a4fd0f/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 90 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5f9e908d-5bbd-475d-bcce-a8dedf3399c2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2f4528ee74ef0b1b7c621588c927458375a4fd0f/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 93 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/366aae9c-2ed9-4de9-9218-5a9425433314) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2f4528ee74ef0b1b7c621588c927458375a4fd0f/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 89 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/356749f9-8b58-45c6-88ca-6ad681ba8dff) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2f4528ee74ef0b1b7c621588c927458375a4fd0f/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1fc7b6d1-23c6-43f9-ba0a-8978ec1afec8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2f4528ee74ef0b1b7c621588c927458375a4fd0f/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6e222fc5-603b-4bb5-bbe9-7303103ced58) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2f4528ee74ef0b1b7c621588c927458375a4fd0f/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 91 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9fabd8d9-6ed4-426b-a027-158af7f5f66b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/shared-channels.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2f4528ee74ef0b1b7c621588c927458375a4fd0f/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshared-channels.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c1173492-8bd2-4ba7-9e90-8075e563dde6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/teams-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2f4528ee74ef0b1b7c621588c927458375a4fd0f/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fteams-developer-portal.md) | 91 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b57294b8-3867-4841-96ba-0ead7209f9f4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2f4528ee74ef0b1b7c621588c927458375a4fd0f/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 99 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ba3f0097-fa9f-449f-80f0-e3a39591cca2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2f4528ee74ef0b1b7c621588c927458375a4fd0f/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-publish-overview.md) | 92 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/64576f3f-9a31-469c-b806-6a2e9119423a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2f4528ee74ef0b1b7c621588c927458375a4fd0f/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7ef951f9-156a-42f1-beb3-742fb84a76de) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2f4528ee74ef0b1b7c621588c927458375a4fd0f/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fsubmission-checklist.md) | 89 | 45 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3fe09e7a-1df2-40eb-a7fb-0f8ab49686dd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2f4528ee74ef0b1b7c621588c927458375a4fd0f/msteams-platform%2Fget-started%2Fglossary.md) | 90 | 77 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a9f783eb-3bab-466e-99ad-4fd13382cd4e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/what-are-messaging-extensions.md](https://github.com/Microsoft [...]

2024-04-01 16:46 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/4cf1a551e83511b48d79488a7e1ce6c16ed0f8b8/msteams-platform%2FTOC.yml) | 96 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/793e8bcc-337c-426e-a6a2-589d346afabc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4cf1a551e83511b48d79488a7e1ce6c16ed0f8b8/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 90 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6488d427-2744-418d-9ece-4ef06ae2f137) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4cf1a551e83511b48d79488a7e1ce6c16ed0f8b8/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 91 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8bc116a6-ffce-4494-98ab-80dcf312f4de) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4cf1a551e83511b48d79488a7e1ce6c16ed0f8b8/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 88 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cdea2ea7-7348-4968-a1e3-4aa5910b3b74) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4cf1a551e83511b48d79488a7e1ce6c16ed0f8b8/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 86 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/401cd7f1-8cb3-4fe0-adf5-81683012e01e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4cf1a551e83511b48d79488a7e1ce6c16ed0f8b8/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 80 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8a9d688e-7875-40b6-9e93-bc3e0b4793a9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4cf1a551e83511b48d79488a7e1ce6c16ed0f8b8/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 90 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/359b8565-65ac-46a5-9e72-da7383771cc0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4cf1a551e83511b48d79488a7e1ce6c16ed0f8b8/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 93 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/67e49b36-e71d-418b-ae11-2be7702d6a58) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4cf1a551e83511b48d79488a7e1ce6c16ed0f8b8/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 89 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d28578fc-4c36-42fc-a94d-c764467c835d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4cf1a551e83511b48d79488a7e1ce6c16ed0f8b8/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/62ac6421-8c9c-48b6-8c4a-288448254bff) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4cf1a551e83511b48d79488a7e1ce6c16ed0f8b8/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7b75985c-fdec-48b0-9ca9-afbd15114939) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4cf1a551e83511b48d79488a7e1ce6c16ed0f8b8/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 91 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5d570ea9-f0bb-43c3-80d6-24f7344b457a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/shared-channels.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4cf1a551e83511b48d79488a7e1ce6c16ed0f8b8/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshared-channels.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a9cde876-fb29-4d9b-9904-aa09e697af7d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/teams-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4cf1a551e83511b48d79488a7e1ce6c16ed0f8b8/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fteams-developer-portal.md) | 91 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f3855eab-9a95-4ded-8740-0d1b9b2600e5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4cf1a551e83511b48d79488a7e1ce6c16ed0f8b8/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 99 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0c5d6a98-4d88-4035-917c-3530aa2d963b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4cf1a551e83511b48d79488a7e1ce6c16ed0f8b8/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-publish-overview.md) | 92 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8b141a76-c92a-4afb-949d-7af846f661ee) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4cf1a551e83511b48d79488a7e1ce6c16ed0f8b8/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0362880c-7925-4e57-b785-396816d8f5fe) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4cf1a551e83511b48d79488a7e1ce6c16ed0f8b8/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fsubmission-checklist.md) | 89 | 45 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d2c78024-33a1-44c5-b95c-9c6ce051dc09) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4cf1a551e83511b48d79488a7e1ce6c16ed0f8b8/msteams-platform%2Fget-started%2Fglossary.md) | 90 | 77 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/390b5859-063c-4a09-8fac-1caf196acfb8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/what-are-messaging-extensions.md](https://github.com/Microsoft [...]

2024-04-05 10:29 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/3579a19e0a2d99d7957ed1bd4d3fd2dd39d02483/msteams-platform%2FTOC.yml) | 96 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/57d6cd67-7da8-4a95-aa7f-05ad6a48d0a8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3579a19e0a2d99d7957ed1bd4d3fd2dd39d02483/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 90 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/092f8aca-c642-4d9c-939f-3ddcca787639) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3579a19e0a2d99d7957ed1bd4d3fd2dd39d02483/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 91 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/da998bb6-74f1-48a1-b750-308bd7f485af) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3579a19e0a2d99d7957ed1bd4d3fd2dd39d02483/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 88 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d8ed3809-8155-42e4-92a4-2d88fc7b8bbd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3579a19e0a2d99d7957ed1bd4d3fd2dd39d02483/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 86 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/eedc09dd-0ec5-4e66-8936-4be5d05f2fec) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3579a19e0a2d99d7957ed1bd4d3fd2dd39d02483/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 80 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f0af930e-0a12-44bb-99a0-52e9d65950fb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3579a19e0a2d99d7957ed1bd4d3fd2dd39d02483/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 90 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/51e416d0-84bb-4348-9ec1-6fcc9b3c87ef) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3579a19e0a2d99d7957ed1bd4d3fd2dd39d02483/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 93 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c89836ed-3bd7-4e30-b9ac-e09037e95f94) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3579a19e0a2d99d7957ed1bd4d3fd2dd39d02483/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 89 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/00b9f7b9-6ab2-43bb-a65e-a2170f0ab227) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3579a19e0a2d99d7957ed1bd4d3fd2dd39d02483/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a97044cc-5350-41ad-929d-10fc8be591f2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3579a19e0a2d99d7957ed1bd4d3fd2dd39d02483/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a86e5fe7-906e-4bbf-88b1-e4ac26fb5996) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3579a19e0a2d99d7957ed1bd4d3fd2dd39d02483/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 91 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/51d9e00f-c38b-4fe5-84f0-b72d7181a354) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/shared-channels.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3579a19e0a2d99d7957ed1bd4d3fd2dd39d02483/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshared-channels.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3d80f829-f9c7-44cd-8b3d-b6e143ad59cf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/teams-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3579a19e0a2d99d7957ed1bd4d3fd2dd39d02483/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fteams-developer-portal.md) | 91 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/55734042-1d4f-4486-bab5-2c8c1dc3370c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3579a19e0a2d99d7957ed1bd4d3fd2dd39d02483/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 99 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aa6fbe99-8806-4ed5-9246-72ec51d74285) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3579a19e0a2d99d7957ed1bd4d3fd2dd39d02483/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-publish-overview.md) | 92 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/89788274-73a1-49cd-a5c6-ed889ab43738) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3579a19e0a2d99d7957ed1bd4d3fd2dd39d02483/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/57499d0f-360c-4950-bb7c-5a7ce06bf89b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3579a19e0a2d99d7957ed1bd4d3fd2dd39d02483/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fsubmission-checklist.md) | 89 | 45 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/51ebf152-5244-4bef-9435-1385766050fd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3579a19e0a2d99d7957ed1bd4d3fd2dd39d02483/msteams-platform%2Fget-started%2Fglossary.md) | 90 | 77 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9764b58b-f272-4ed2-8dfc-a1013500f792) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/what-are-messaging-extensions.md](https://github.com/Microsoft [...]

2024-04-05 15:23 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e29d933f17c8baa9f106d5353b57d6f032396de4/msteams-platform%2FTOC.yml) | 96 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/44ce889d-9bd7-4d36-8202-0c2c92525aa2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e29d933f17c8baa9f106d5353b57d6f032396de4/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 90 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3a2d2e47-91f4-423d-b2a9-041e7f2b2a5f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e29d933f17c8baa9f106d5353b57d6f032396de4/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 91 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1c162246-e183-4c19-b64d-da084cfe8440) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e29d933f17c8baa9f106d5353b57d6f032396de4/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 88 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c3e71966-a50e-4f8d-95e6-e433dbc42f1b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e29d933f17c8baa9f106d5353b57d6f032396de4/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 86 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/374970b7-083c-49d4-a308-686f1db5cbf3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e29d933f17c8baa9f106d5353b57d6f032396de4/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 80 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f1ee5e1c-207d-4d7e-ae59-d75dbf706942) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e29d933f17c8baa9f106d5353b57d6f032396de4/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 90 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5ff06690-48de-4731-b86c-5b8db1c07961) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e29d933f17c8baa9f106d5353b57d6f032396de4/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 93 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c953ee1e-eba8-45fb-bacc-a502ac1f4047) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e29d933f17c8baa9f106d5353b57d6f032396de4/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 89 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/922fa971-d38e-4894-ba26-cefaa887ed4f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e29d933f17c8baa9f106d5353b57d6f032396de4/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/222d1f75-1c3c-4fe0-88c8-1381ee3f6d5a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e29d933f17c8baa9f106d5353b57d6f032396de4/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/69814c33-940c-49eb-9e0d-b00d3aea75b1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e29d933f17c8baa9f106d5353b57d6f032396de4/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 91 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/545c0e56-cd54-446e-bfb3-5f6945c462af) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/shared-channels.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e29d933f17c8baa9f106d5353b57d6f032396de4/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshared-channels.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ee136aff-e9bf-412d-912d-e39e93cb4fcc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/teams-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e29d933f17c8baa9f106d5353b57d6f032396de4/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fteams-developer-portal.md) | 91 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/de328b03-cc71-4cbe-8afc-e93ec3a151a4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e29d933f17c8baa9f106d5353b57d6f032396de4/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 99 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e994e0e5-fee5-4e12-8a43-b158ffd0ef61) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e29d933f17c8baa9f106d5353b57d6f032396de4/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-publish-overview.md) | 92 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fda20ae6-180f-4ec1-a373-e6c0d603126e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e29d933f17c8baa9f106d5353b57d6f032396de4/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4b1a9211-c658-4511-88d1-af542cbf8f93) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e29d933f17c8baa9f106d5353b57d6f032396de4/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fsubmission-checklist.md) | 89 | 45 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e6e8c56b-18ea-4729-b3e9-5bd3f4a0f1a7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e29d933f17c8baa9f106d5353b57d6f032396de4/msteams-platform%2Fget-started%2Fglossary.md) | 90 | 77 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8c305b71-f739-4f58-a69b-f13820bac9c0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/what-are-messaging-extensions.md](https://github.com/Microsoft [...]

2024-04-08 13:08 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/78056e60a692a35e5539140bdb4eb553d1f656d9/msteams-platform%2FTOC.yml) | 96 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3d42407d-f17d-472d-b995-79736c04d969) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/78056e60a692a35e5539140bdb4eb553d1f656d9/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 90 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2af3c43b-1796-4d68-8542-51a44d1c16df) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/78056e60a692a35e5539140bdb4eb553d1f656d9/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 91 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/71d72b36-2bc6-41b4-8177-2167871dec57) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/78056e60a692a35e5539140bdb4eb553d1f656d9/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 88 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/54b8697e-237b-48fb-868e-e1e7b23af51d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/78056e60a692a35e5539140bdb4eb553d1f656d9/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 86 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e4f52805-7abc-4b63-a9f4-b5a249624562) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/78056e60a692a35e5539140bdb4eb553d1f656d9/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 80 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1b0aacce-8d7d-4863-b3e2-26b703bde276) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/78056e60a692a35e5539140bdb4eb553d1f656d9/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 90 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/300a0e7e-ac79-4c37-ba8a-fd3165b51a91) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/78056e60a692a35e5539140bdb4eb553d1f656d9/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 93 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/76c69bc7-d51f-4724-9613-deeb429d405d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/78056e60a692a35e5539140bdb4eb553d1f656d9/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 89 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3bd3d74d-7505-45b6-9765-6e682a25acaa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/78056e60a692a35e5539140bdb4eb553d1f656d9/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/df10493e-ff99-4d10-85e5-a01dcae78bf6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/78056e60a692a35e5539140bdb4eb553d1f656d9/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e446a5c2-971a-4727-9115-e53d71cb356d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/78056e60a692a35e5539140bdb4eb553d1f656d9/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 91 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d6e89f41-11ff-4193-99b7-7fbb25a3269c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/shared-channels.md](https://github.com/MicrosoftDocs/msteams-docs/blob/78056e60a692a35e5539140bdb4eb553d1f656d9/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshared-channels.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f59ed855-532b-4ee1-b5ac-44e42083dbcb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/teams-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/78056e60a692a35e5539140bdb4eb553d1f656d9/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fteams-developer-portal.md) | 91 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/08b5fc92-bd99-4266-9c2d-b40f2e088f18) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/78056e60a692a35e5539140bdb4eb553d1f656d9/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 99 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/35d41c5f-0a8c-43ed-b734-5cf68cbed519) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/78056e60a692a35e5539140bdb4eb553d1f656d9/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-publish-overview.md) | 92 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5c96df66-3e4c-41b5-bb74-f780548d6f4e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/78056e60a692a35e5539140bdb4eb553d1f656d9/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0533049b-53c3-4a94-8384-728cf2e23416) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/78056e60a692a35e5539140bdb4eb553d1f656d9/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fsubmission-checklist.md) | 89 | 45 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ffcd96a3-e195-4087-8f6a-519e65a66996) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/78056e60a692a35e5539140bdb4eb553d1f656d9/msteams-platform%2Fget-started%2Fglossary.md) | 90 | 77 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fd20e2d7-753b-45ac-a7a1-1d27afd3e980) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/what-are-messaging-extensions.md](https://github.com/Microsoft [...]

2024-04-08 13:46 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/8b826f322f947befcb1352b779f4bfd7f8ee0f1c/msteams-platform%2FTOC.yml) | 96 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4abbacd6-189f-482b-b803-3d5415119aed) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8b826f322f947befcb1352b779f4bfd7f8ee0f1c/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 90 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f9eefba8-7fda-492e-8652-fe7a83875868) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8b826f322f947befcb1352b779f4bfd7f8ee0f1c/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 91 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/affe1810-2598-4707-a8af-21dbc4dc2d0d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8b826f322f947befcb1352b779f4bfd7f8ee0f1c/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 88 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7f9d0a6c-f3be-4682-8b3a-8de47b2d481a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8b826f322f947befcb1352b779f4bfd7f8ee0f1c/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 86 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d965c181-fca8-4e82-87ab-9029733d07cc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8b826f322f947befcb1352b779f4bfd7f8ee0f1c/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 80 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/275fdc30-32c1-4c58-99e6-61d46914c8a0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8b826f322f947befcb1352b779f4bfd7f8ee0f1c/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 90 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/13477417-f78b-4f45-be8a-8cfba92fe4a0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8b826f322f947befcb1352b779f4bfd7f8ee0f1c/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 93 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0563a80b-e604-4f52-9340-ea5238fba32e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8b826f322f947befcb1352b779f4bfd7f8ee0f1c/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 89 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2381f4ff-3060-4737-b5c7-00d9897fe1f2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8b826f322f947befcb1352b779f4bfd7f8ee0f1c/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ee449a10-109c-4dc5-b1f8-437c291b1a70) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8b826f322f947befcb1352b779f4bfd7f8ee0f1c/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1b681031-a4d9-44f3-a92e-d5a8dd0c7bc1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8b826f322f947befcb1352b779f4bfd7f8ee0f1c/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 91 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/40758075-f49f-4949-93ca-00b57ffd8d46) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/shared-channels.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8b826f322f947befcb1352b779f4bfd7f8ee0f1c/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshared-channels.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e4601f3e-a228-40d2-af60-514515fcc08f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/teams-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8b826f322f947befcb1352b779f4bfd7f8ee0f1c/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fteams-developer-portal.md) | 91 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5895010f-195e-4ed3-be61-ffce4e66db07) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8b826f322f947befcb1352b779f4bfd7f8ee0f1c/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 99 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/58f85960-82c3-42bd-be9b-99f8325b8c48) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8b826f322f947befcb1352b779f4bfd7f8ee0f1c/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-publish-overview.md) | 92 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/493f03ec-5968-4685-9d17-3a9959335b8b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8b826f322f947befcb1352b779f4bfd7f8ee0f1c/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0c984238-1e98-470a-b0dd-afecb029422a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8b826f322f947befcb1352b779f4bfd7f8ee0f1c/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fsubmission-checklist.md) | 89 | 45 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2eae3961-1af3-40ac-a611-5eafb37feaf5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8b826f322f947befcb1352b779f4bfd7f8ee0f1c/msteams-platform%2Fget-started%2Fglossary.md) | 90 | 77 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8e0f0d37-a53e-41d6-b908-0864efc8b069) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/what-are-messaging-extensions.md](https://github.com/Microsoft [...]

2024-04-10 04:35 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/df76ff4351bee391d38668118b16c82a4c82dcfc/msteams-platform%2FTOC.yml) | 96 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3d5a36ed-0db7-4b73-8867-2b787e84184c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/df76ff4351bee391d38668118b16c82a4c82dcfc/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 90 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8701d282-d7b3-461f-9531-c2a9a06f7123) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/df76ff4351bee391d38668118b16c82a4c82dcfc/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 91 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/62b508fd-d8b6-4580-aefa-2f755e9fd374) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/df76ff4351bee391d38668118b16c82a4c82dcfc/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 88 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c522022e-6533-4950-994c-f6e314c85247) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/df76ff4351bee391d38668118b16c82a4c82dcfc/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 86 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f7d9ee4f-5559-4f01-ba0d-ba9e9f5598ca) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/df76ff4351bee391d38668118b16c82a4c82dcfc/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 80 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4c54328f-cddc-40e3-a3e6-1b5c20625763) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/df76ff4351bee391d38668118b16c82a4c82dcfc/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 90 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c03e2066-e2da-4a31-8cf3-2398e4acee9a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/df76ff4351bee391d38668118b16c82a4c82dcfc/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 93 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/88b103d6-2b75-46d7-a491-cb9619296259) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/df76ff4351bee391d38668118b16c82a4c82dcfc/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 89 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b0e34997-36ea-4a00-a8a7-ce4e91a2f095) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/df76ff4351bee391d38668118b16c82a4c82dcfc/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/54d7ae2e-ba29-46c4-a989-3e5d75723fd5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/df76ff4351bee391d38668118b16c82a4c82dcfc/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f9a9629c-6ead-45b4-ada7-e9a0da7a253b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/df76ff4351bee391d38668118b16c82a4c82dcfc/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 91 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/82ef088d-4db8-4777-b91d-9edd44415f01) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/shared-channels.md](https://github.com/MicrosoftDocs/msteams-docs/blob/df76ff4351bee391d38668118b16c82a4c82dcfc/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshared-channels.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1dfb0655-2875-40e6-bce9-1578ec58094c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/teams-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/df76ff4351bee391d38668118b16c82a4c82dcfc/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fteams-developer-portal.md) | 91 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/306d7ca2-86ef-4fef-b12f-5243ca90cfbe) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/df76ff4351bee391d38668118b16c82a4c82dcfc/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 99 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c81ed6a3-2f30-4565-af51-4491f929bd48) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/df76ff4351bee391d38668118b16c82a4c82dcfc/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-publish-overview.md) | 92 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cf55fe0b-c2da-486d-a8c7-35d99b9be5ec) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/df76ff4351bee391d38668118b16c82a4c82dcfc/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cb59bec0-13f3-41c5-845d-caa98a474980) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/df76ff4351bee391d38668118b16c82a4c82dcfc/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fsubmission-checklist.md) | 89 | 45 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/70646ba8-5a19-4efb-8972-24f4fb9bac77) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/df76ff4351bee391d38668118b16c82a4c82dcfc/msteams-platform%2Fget-started%2Fglossary.md) | 90 | 77 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/273e412c-07a7-40e6-a9b5-1901ff41c7d9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/what-are-messaging-extensions.md](https://github.com/Microsoft [...]

2024-04-10 14:10 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1d48e8294e381e1c0abfe0bfd27849f84afda519/msteams-platform%2FTOC.yml) | 96 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c6e4f378-cb8e-4555-b2e6-ee9fa8550267) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1d48e8294e381e1c0abfe0bfd27849f84afda519/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 90 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1561511d-84e1-4256-85de-76fdd8a3345d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1d48e8294e381e1c0abfe0bfd27849f84afda519/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 91 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e8b7ea8a-b45e-40f2-a5f2-188d0a0b1daa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1d48e8294e381e1c0abfe0bfd27849f84afda519/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 88 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/98cee89e-dc80-4ab0-b827-75a920405ec9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1d48e8294e381e1c0abfe0bfd27849f84afda519/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 86 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3e2d8e15-72bc-43d5-b393-84634e8d276d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1d48e8294e381e1c0abfe0bfd27849f84afda519/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 80 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c8b966f4-1f9d-4195-a70f-49a0d934501c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1d48e8294e381e1c0abfe0bfd27849f84afda519/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 90 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3f568734-c7c3-44fe-9c15-6cb161b45f52) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1d48e8294e381e1c0abfe0bfd27849f84afda519/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 93 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0dfb0033-b6d1-4e40-a5a9-a256c35eb83d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1d48e8294e381e1c0abfe0bfd27849f84afda519/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 89 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/33daa8ec-0ecd-42cd-adcf-7168b07fb64a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1d48e8294e381e1c0abfe0bfd27849f84afda519/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4adefb24-a7cc-4368-8235-0f48143618fd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1d48e8294e381e1c0abfe0bfd27849f84afda519/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2baf128c-3ef6-42af-8b4e-720c971b3c23) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1d48e8294e381e1c0abfe0bfd27849f84afda519/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 91 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b81627f2-4f15-4761-b2c4-e391229f6d52) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/shared-channels.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1d48e8294e381e1c0abfe0bfd27849f84afda519/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshared-channels.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2517d05e-c8b5-400a-9d52-5ae316d543c2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/teams-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1d48e8294e381e1c0abfe0bfd27849f84afda519/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fteams-developer-portal.md) | 91 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aeaa8b88-2dea-486b-94b1-3306f59ba11a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1d48e8294e381e1c0abfe0bfd27849f84afda519/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 99 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/15904ef5-45c6-49b5-a37d-51f34292c3e6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1d48e8294e381e1c0abfe0bfd27849f84afda519/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-publish-overview.md) | 92 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5c912efc-46ea-4604-8a16-77bdc8887180) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1d48e8294e381e1c0abfe0bfd27849f84afda519/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d65766b4-993a-4b48-ba4c-37ab9f1d03ad) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1d48e8294e381e1c0abfe0bfd27849f84afda519/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fsubmission-checklist.md) | 89 | 45 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ec208dcb-4896-40d6-ab85-be77135cc60f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1d48e8294e381e1c0abfe0bfd27849f84afda519/msteams-platform%2Fget-started%2Fglossary.md) | 90 | 77 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/21dcab48-6801-4c73-aac8-6a1b377fd97a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/what-are-messaging-extensions.md](https://github.com/Microsoft [...]

2024-04-10 15:17 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/2770b08d0bb48a8039b29b6b20e0411bfc99f668/msteams-platform%2FTOC.yml) | 96 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/90af4b0f-a17c-48e6-95e7-d67d119031ce) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2770b08d0bb48a8039b29b6b20e0411bfc99f668/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 90 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cc39b4b6-d280-4cea-9642-f9db398337f7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2770b08d0bb48a8039b29b6b20e0411bfc99f668/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 91 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/17e41f4b-e479-4c57-b63f-f789c8a4239d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2770b08d0bb48a8039b29b6b20e0411bfc99f668/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 88 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8df8f459-8255-4d5b-9935-d7e3aa450698) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2770b08d0bb48a8039b29b6b20e0411bfc99f668/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 86 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1eef1f50-586b-4ba2-b59f-638f05f57931) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2770b08d0bb48a8039b29b6b20e0411bfc99f668/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 80 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/66f33472-9c12-4aa5-9334-04ec47697d2b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2770b08d0bb48a8039b29b6b20e0411bfc99f668/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 90 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b9f2d00c-3093-4909-b9bc-cf4c641b93d2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2770b08d0bb48a8039b29b6b20e0411bfc99f668/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 93 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/00221741-89cb-4554-8eaf-b4c81cb49dbe) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2770b08d0bb48a8039b29b6b20e0411bfc99f668/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 89 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fb1dd3da-8e32-422f-a6ef-5cb55b777ef1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2770b08d0bb48a8039b29b6b20e0411bfc99f668/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dea98b8c-0982-48a4-bfbc-58bf9c299b08) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2770b08d0bb48a8039b29b6b20e0411bfc99f668/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/14868e80-f96e-468c-8893-94b081fa3387) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2770b08d0bb48a8039b29b6b20e0411bfc99f668/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 91 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dd25c774-a498-4738-9549-dbf01cb400e8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/shared-channels.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2770b08d0bb48a8039b29b6b20e0411bfc99f668/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshared-channels.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/02dcf09a-2d73-452b-98ef-4919a849668e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/teams-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2770b08d0bb48a8039b29b6b20e0411bfc99f668/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fteams-developer-portal.md) | 91 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/da304469-f7e4-4cb9-9bb4-f8008b2479a1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2770b08d0bb48a8039b29b6b20e0411bfc99f668/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 99 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/301f0a53-4659-4062-bae3-77422bdbd44a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2770b08d0bb48a8039b29b6b20e0411bfc99f668/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-publish-overview.md) | 92 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0e360266-6559-4234-835b-9d73c6ff110a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2770b08d0bb48a8039b29b6b20e0411bfc99f668/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4464737f-93ca-415c-b754-e28c478df24d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2770b08d0bb48a8039b29b6b20e0411bfc99f668/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fsubmission-checklist.md) | 89 | 45 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0f6d3891-caa8-49ff-a9bb-c6a5e4523186) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2770b08d0bb48a8039b29b6b20e0411bfc99f668/msteams-platform%2Fget-started%2Fglossary.md) | 90 | 77 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/105dc0f2-da7b-454f-9ba1-1bc2cab3e80d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/what-are-messaging-extensions.md](https://github.com/Microsoft [...]

2024-04-18 05:47 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/3004abad93c881ed53b331a966195fcb949cc44a/msteams-platform%2FTOC.yml) | 96 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/456d7969-b29e-4a96-b340-d5fa79d438d7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3004abad93c881ed53b331a966195fcb949cc44a/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 90 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2e77a9d6-d9d7-49e2-b079-fbaaf400ad73) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3004abad93c881ed53b331a966195fcb949cc44a/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 91 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cdf13df8-fa12-4c84-bfa4-76015b3eff7d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3004abad93c881ed53b331a966195fcb949cc44a/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 88 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f365b4e3-3ea8-48fc-9265-a38f322b1da9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3004abad93c881ed53b331a966195fcb949cc44a/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 86 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9bc27641-8a30-4e0d-8dd0-1e0f03cf92de) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3004abad93c881ed53b331a966195fcb949cc44a/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 80 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/96682aea-9dd5-4928-9baa-024359472f6a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3004abad93c881ed53b331a966195fcb949cc44a/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 90 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5d63dc11-e8fc-41b7-99bb-8fce06bbfb4c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3004abad93c881ed53b331a966195fcb949cc44a/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 93 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6d58bf40-8fab-4e10-a602-e1497e01b5b3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3004abad93c881ed53b331a966195fcb949cc44a/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 89 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/83df6da6-97bd-43da-b22b-6fe39f68b320) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3004abad93c881ed53b331a966195fcb949cc44a/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 90 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/eec9b9e2-426a-4284-bacd-4771fe23efa3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3004abad93c881ed53b331a966195fcb949cc44a/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/921f59ff-997a-4583-8458-bef7a124d33f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3004abad93c881ed53b331a966195fcb949cc44a/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 91 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/763ce773-7e09-4380-a84c-70010e597327) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/shared-channels.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3004abad93c881ed53b331a966195fcb949cc44a/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshared-channels.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/716c4eac-7642-4c26-b6a9-c405e265ca9e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/teams-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3004abad93c881ed53b331a966195fcb949cc44a/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fteams-developer-portal.md) | 91 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9d3b0dcd-21b2-487a-98b2-f86a06490cb8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3004abad93c881ed53b331a966195fcb949cc44a/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 99 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c9bfcec9-4290-46e1-a5d7-24e88c1d007e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3004abad93c881ed53b331a966195fcb949cc44a/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-publish-overview.md) | 92 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ee1dc894-a279-458d-bbcb-ac08ac97ca19) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3004abad93c881ed53b331a966195fcb949cc44a/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2f1e30d4-ca2d-494a-b0cd-7ab92547ae4d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3004abad93c881ed53b331a966195fcb949cc44a/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fsubmission-checklist.md) | 89 | 45 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d9f8751a-b1be-4c02-ad94-7b007d81c1d2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3004abad93c881ed53b331a966195fcb949cc44a/msteams-platform%2Fget-started%2Fglossary.md) | 90 | 77 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bbe1c1d9-ef88-409e-8e68-c8bca7cf6ddf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/what-are-messaging-extensions.md](https://github.com/Microsof [...]

2024-04-18 07:33 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/92a0d849c1ea0a96e4791a8430b4e0a38c5b2759/msteams-platform%2FTOC.yml) | 96 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/debbde60-4c6e-43b0-aef8-a6489dec7e10) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/92a0d849c1ea0a96e4791a8430b4e0a38c5b2759/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 90 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b1866a45-6855-4950-b5fe-f46edf1945be) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/92a0d849c1ea0a96e4791a8430b4e0a38c5b2759/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 91 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8d9de496-e4af-4da5-a3b7-6fedf4e7e092) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/92a0d849c1ea0a96e4791a8430b4e0a38c5b2759/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 88 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3eca5e07-48f2-4a34-a71a-16ee9bbe89fe) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/92a0d849c1ea0a96e4791a8430b4e0a38c5b2759/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 86 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8029f2a9-ae55-4a31-88da-0351c3d36874) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/92a0d849c1ea0a96e4791a8430b4e0a38c5b2759/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 80 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8fc132ec-af8c-4bb5-a19c-5ffbff225913) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/92a0d849c1ea0a96e4791a8430b4e0a38c5b2759/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 90 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0d06b73f-8950-4391-9098-0f3a18cf9fb4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/92a0d849c1ea0a96e4791a8430b4e0a38c5b2759/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 93 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/473adbe5-6dd8-464d-9ed5-0394211ea4c2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/92a0d849c1ea0a96e4791a8430b4e0a38c5b2759/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 89 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8428fcde-aedf-4a87-a3b9-3246155901f4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/92a0d849c1ea0a96e4791a8430b4e0a38c5b2759/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 90 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/017a37cc-bfb1-4b50-aad1-6d58c518ada9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/92a0d849c1ea0a96e4791a8430b4e0a38c5b2759/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c3c291c1-7940-4e67-aa9e-e57256466d03) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/92a0d849c1ea0a96e4791a8430b4e0a38c5b2759/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 91 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f9244339-93ae-44ce-add9-b78aa235e528) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/shared-channels.md](https://github.com/MicrosoftDocs/msteams-docs/blob/92a0d849c1ea0a96e4791a8430b4e0a38c5b2759/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshared-channels.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/170f428b-8b48-495c-81df-d504099ac15a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/teams-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/92a0d849c1ea0a96e4791a8430b4e0a38c5b2759/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fteams-developer-portal.md) | 91 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dc63ba92-b60a-4559-b0a5-cb1213a44853) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/92a0d849c1ea0a96e4791a8430b4e0a38c5b2759/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 99 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/35a863dd-7526-4ced-8373-d983f35b9a60) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/92a0d849c1ea0a96e4791a8430b4e0a38c5b2759/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-publish-overview.md) | 92 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9b96405f-0eaa-4349-af73-7804d83acf43) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/92a0d849c1ea0a96e4791a8430b4e0a38c5b2759/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ffae33df-50b6-4da4-9c64-54bbba1f7737) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/92a0d849c1ea0a96e4791a8430b4e0a38c5b2759/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fsubmission-checklist.md) | 89 | 45 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/57f13f3d-b192-49f3-8af1-65576eeda5b9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/92a0d849c1ea0a96e4791a8430b4e0a38c5b2759/msteams-platform%2Fget-started%2Fglossary.md) | 90 | 77 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4b8fcb3a-49f4-4d05-9a33-1504a1e051ca) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/what-are-messaging-extensions.md](https://github.com/Microsof [...]

2024-04-18 07:44 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/026c826e164ced77a848c7d1f893f97c82b393c1/msteams-platform%2FTOC.yml) | 96 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3537bdbe-5575-4269-86f8-ede3d22e8697) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/026c826e164ced77a848c7d1f893f97c82b393c1/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 90 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5b096134-67e4-46f0-bbca-6712665248d6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/026c826e164ced77a848c7d1f893f97c82b393c1/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 91 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a7a26306-12b7-4d53-9fc0-8ce2ba06ffe1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/026c826e164ced77a848c7d1f893f97c82b393c1/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 88 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b5279e1c-d514-4b43-89dc-128784934d63) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/026c826e164ced77a848c7d1f893f97c82b393c1/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 86 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/db4d2d82-78b3-4403-ad90-8e8f5ea576f4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/026c826e164ced77a848c7d1f893f97c82b393c1/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 80 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7fd21466-65fc-4f0b-a752-70af76299916) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/026c826e164ced77a848c7d1f893f97c82b393c1/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 90 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/930fd88c-49fd-4f95-a3b9-d1ca61eab345) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/026c826e164ced77a848c7d1f893f97c82b393c1/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 93 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3e8b0ae4-0cb6-4852-b2c3-3ff874fac829) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/026c826e164ced77a848c7d1f893f97c82b393c1/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 89 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b9e2dbf7-90ce-42da-82f4-05d579aa1db1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/026c826e164ced77a848c7d1f893f97c82b393c1/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 90 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a6d63990-b34a-4383-aed1-4372cd02be68) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/026c826e164ced77a848c7d1f893f97c82b393c1/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0e7a1c21-c3c1-49ba-a10d-8f111cbc059d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/026c826e164ced77a848c7d1f893f97c82b393c1/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 91 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ddbe57b9-65c2-4c58-a860-e054c617a1da) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/shared-channels.md](https://github.com/MicrosoftDocs/msteams-docs/blob/026c826e164ced77a848c7d1f893f97c82b393c1/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshared-channels.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/154db116-7a00-4c50-b29c-6cbe61ba9ce6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/teams-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/026c826e164ced77a848c7d1f893f97c82b393c1/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fteams-developer-portal.md) | 91 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/261a3545-eb03-4ed1-9fc8-396082145165) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/026c826e164ced77a848c7d1f893f97c82b393c1/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 99 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/82b81880-511d-4cde-bf3b-5dc4f5f19efe) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/026c826e164ced77a848c7d1f893f97c82b393c1/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-publish-overview.md) | 92 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/04c635ff-8d43-4b2f-b597-cf191ba4769e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/026c826e164ced77a848c7d1f893f97c82b393c1/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dfd9e3bf-f212-42d9-8b04-2f5fdef2d98a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/026c826e164ced77a848c7d1f893f97c82b393c1/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fsubmission-checklist.md) | 89 | 45 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9badb0bd-818f-4fb7-823c-b25e7d59a75f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/026c826e164ced77a848c7d1f893f97c82b393c1/msteams-platform%2Fget-started%2Fglossary.md) | 90 | 77 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2fefbab9-a6dd-40c1-b358-a4d1c1d1d329) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/what-are-messaging-extensions.md](https://github.com/Microsof [...]

2024-04-18 08:21 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/bc79c082fed64f6773472eb9f2db70b88dd4dde3/msteams-platform%2FTOC.yml) | 96 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/46c65827-8e92-41ca-b941-3b003b24252f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bc79c082fed64f6773472eb9f2db70b88dd4dde3/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 90 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/530ba5d0-9d57-45f6-bce4-299d97b9df8d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bc79c082fed64f6773472eb9f2db70b88dd4dde3/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 91 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/de4c8f02-9fb8-4050-aac1-16f3647a7ad8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bc79c082fed64f6773472eb9f2db70b88dd4dde3/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 88 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1560e313-ca4b-4ba6-8e8b-5a258a669586) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bc79c082fed64f6773472eb9f2db70b88dd4dde3/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 86 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/959f3022-496e-417d-8122-d13ce940e80c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bc79c082fed64f6773472eb9f2db70b88dd4dde3/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 80 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8de071e0-9e5c-4338-8db9-e0727ab9c39c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bc79c082fed64f6773472eb9f2db70b88dd4dde3/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 90 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/273ca18a-ab86-4305-94d1-17c26965db4c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bc79c082fed64f6773472eb9f2db70b88dd4dde3/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 93 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c54722ff-e717-4b09-884b-46659abab16d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bc79c082fed64f6773472eb9f2db70b88dd4dde3/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 89 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a72e0909-96e3-4d09-8cb0-f5b7e6f6aa56) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bc79c082fed64f6773472eb9f2db70b88dd4dde3/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 90 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c050d186-73fc-439e-8b32-4ffc0e5adb24) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bc79c082fed64f6773472eb9f2db70b88dd4dde3/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/87be7d1a-2311-45c3-b143-6bf70758fc0e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bc79c082fed64f6773472eb9f2db70b88dd4dde3/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 91 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/556ac4f6-5a33-41da-9ede-9bdbf4d8196d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/shared-channels.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bc79c082fed64f6773472eb9f2db70b88dd4dde3/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshared-channels.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a5cecdd6-6f9f-4669-ae1e-9a25c08c80e3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/teams-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bc79c082fed64f6773472eb9f2db70b88dd4dde3/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fteams-developer-portal.md) | 91 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6ce9bd70-4b67-473b-8ca4-b55a355ba61e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bc79c082fed64f6773472eb9f2db70b88dd4dde3/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 99 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d2c093e5-4737-409d-97f9-3507b9231194) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bc79c082fed64f6773472eb9f2db70b88dd4dde3/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-publish-overview.md) | 92 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7a3cc7e0-6398-47c5-a777-89fa8e47b110) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bc79c082fed64f6773472eb9f2db70b88dd4dde3/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5e767e80-2c8f-449e-9d07-084872f7f032) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bc79c082fed64f6773472eb9f2db70b88dd4dde3/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fsubmission-checklist.md) | 89 | 45 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/85bb59a4-2fe6-4f30-b9e4-eff5aa791f98) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bc79c082fed64f6773472eb9f2db70b88dd4dde3/msteams-platform%2Fget-started%2Fglossary.md) | 90 | 77 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d8eef48c-573b-401c-bfd9-c370fa34355c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/what-are-messaging-extensions.md](https://github.com/Microsof [...]

2024-04-18 09:10 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/693c92263df17a9d984f4395e373a983747da49d/msteams-platform%2FTOC.yml) | 96 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ca94c149-2c3e-454c-8e42-dd42016a225c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/693c92263df17a9d984f4395e373a983747da49d/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 90 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5b11526b-1055-4933-a77d-6fe683921a71) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/693c92263df17a9d984f4395e373a983747da49d/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 91 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9b1b5819-83fc-477a-9368-ccf053973b3f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/693c92263df17a9d984f4395e373a983747da49d/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 88 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a38756b0-dc67-4f62-a607-a52f53a2f763) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/693c92263df17a9d984f4395e373a983747da49d/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 86 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/435f90a1-f5fb-4bab-a625-eb00db5afa71) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/693c92263df17a9d984f4395e373a983747da49d/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 80 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/23d872f7-9d6a-4743-b5ca-f4cea2557733) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/693c92263df17a9d984f4395e373a983747da49d/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 90 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b811797d-52da-40b5-ba90-8c77614aef3f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/693c92263df17a9d984f4395e373a983747da49d/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 93 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9299c717-d22d-43ce-af4d-22632776d3e2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/693c92263df17a9d984f4395e373a983747da49d/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 89 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b7e13d95-78eb-4e69-8b92-8272f7be60a8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/693c92263df17a9d984f4395e373a983747da49d/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 90 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d671dbf1-d7bb-4255-9ba2-14c6203da1db) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/693c92263df17a9d984f4395e373a983747da49d/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/80e77019-81fe-4f1a-b1f3-ba92d7a4df6e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/693c92263df17a9d984f4395e373a983747da49d/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 91 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ff159603-3ae0-4faf-b1d8-27ffb1f8b9a2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/shared-channels.md](https://github.com/MicrosoftDocs/msteams-docs/blob/693c92263df17a9d984f4395e373a983747da49d/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshared-channels.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d3408c96-3707-48b8-a525-10039eabcf49) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/teams-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/693c92263df17a9d984f4395e373a983747da49d/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fteams-developer-portal.md) | 91 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9e3d55db-433d-4235-bc3b-411564115d89) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/693c92263df17a9d984f4395e373a983747da49d/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 99 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6dc65528-025a-46ff-90f6-80b414307561) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/693c92263df17a9d984f4395e373a983747da49d/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-publish-overview.md) | 92 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ff79e899-8633-46a1-bd2b-0faaf63346ca) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/693c92263df17a9d984f4395e373a983747da49d/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b950c705-a4a5-49bd-9f12-46d94f170099) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/693c92263df17a9d984f4395e373a983747da49d/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fsubmission-checklist.md) | 89 | 45 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/56d755cb-86a3-438f-885e-0ba237d5c66b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/693c92263df17a9d984f4395e373a983747da49d/msteams-platform%2Fget-started%2Fglossary.md) | 90 | 77 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/50846fc5-63bb-421d-b7c1-46da964e6ef6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/what-are-messaging-extensions.md](https://github.com/Microsof [...]

2024-05-03 05:44 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a1dc05b775de00fe2f35912c05b3266642eafe25/msteams-platform%2FTOC.yml) | 96 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a7defd97-a817-4578-93d8-640a621db327) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a1dc05b775de00fe2f35912c05b3266642eafe25/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 90 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/550aacae-5e9d-40d6-9c26-88b3e88c77c5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a1dc05b775de00fe2f35912c05b3266642eafe25/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 91 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2ad682e3-6845-4c65-89ad-67348fc4b361) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a1dc05b775de00fe2f35912c05b3266642eafe25/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 88 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9f9ea939-09eb-4ac1-86a4-834638e915f6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a1dc05b775de00fe2f35912c05b3266642eafe25/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 86 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fe8f54e7-17ee-40a2-8444-78fa9be1e5ae) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a1dc05b775de00fe2f35912c05b3266642eafe25/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 80 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/452d1a32-6226-4630-8251-d0692e3f96ee) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a1dc05b775de00fe2f35912c05b3266642eafe25/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 90 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8dbe56f1-70eb-4abc-891e-f0083b058770) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a1dc05b775de00fe2f35912c05b3266642eafe25/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 93 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/04f06448-81f1-43a2-9f4e-bc903a57d979) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a1dc05b775de00fe2f35912c05b3266642eafe25/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 89 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/558830df-9776-42e3-addc-b496d4948c9a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a1dc05b775de00fe2f35912c05b3266642eafe25/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 90 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3036ad37-9ff6-44d8-b9d7-4c997dee0166) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a1dc05b775de00fe2f35912c05b3266642eafe25/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e9279d70-eef4-4406-82b3-f76c2362c1db) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a1dc05b775de00fe2f35912c05b3266642eafe25/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 91 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6c598899-522b-43b3-9697-7812e5c5c4d4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/shared-channels.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a1dc05b775de00fe2f35912c05b3266642eafe25/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshared-channels.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cc4bff83-0d05-4e7f-96e4-ec6e24c81313) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/teams-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a1dc05b775de00fe2f35912c05b3266642eafe25/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fteams-developer-portal.md) | 91 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ac0c98ce-d3ed-40f7-af5e-b02404c4ea94) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a1dc05b775de00fe2f35912c05b3266642eafe25/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 99 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1daca725-f9d3-40b4-bd66-4623dc7cd5d0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a1dc05b775de00fe2f35912c05b3266642eafe25/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-publish-overview.md) | 92 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8e09a165-f752-4d0e-b475-8a13494348fb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a1dc05b775de00fe2f35912c05b3266642eafe25/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4ccd8c4a-f881-4cc1-8381-35122e431eec) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a1dc05b775de00fe2f35912c05b3266642eafe25/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fsubmission-checklist.md) | 89 | 45 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dda45eb9-e4d4-45a8-8fab-a3ea7c0e027a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a1dc05b775de00fe2f35912c05b3266642eafe25/msteams-platform%2Fget-started%2Fglossary.md) | 90 | 77 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f3f4540b-07df-4826-b7ad-5d0bd4475c26) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/what-are-messaging-extensions.md](https://github.com/Microsof [...]

2024-05-03 06:55 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ba58e50c6f0f592a41c0435f1943679e8432ed5e/msteams-platform%2FTOC.yml) | 96 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0e823ee7-4dab-4ef2-9ee9-11592472b921) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ba58e50c6f0f592a41c0435f1943679e8432ed5e/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 90 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5a407e4f-7df8-40ab-8af2-5d0b48e37d6c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ba58e50c6f0f592a41c0435f1943679e8432ed5e/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 91 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b4bddb8d-b3be-4e9c-b9ac-4160e4392c7d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ba58e50c6f0f592a41c0435f1943679e8432ed5e/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 88 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cc924499-7393-416e-b08c-0e0770680da6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ba58e50c6f0f592a41c0435f1943679e8432ed5e/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 86 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/33dd83fa-296c-4aa4-8b3c-b9683fc59c42) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ba58e50c6f0f592a41c0435f1943679e8432ed5e/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 80 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d475df31-043b-473f-9ca5-62e0f3fb81de) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ba58e50c6f0f592a41c0435f1943679e8432ed5e/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 90 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e84a9b2e-5dcf-426c-9176-aabd37bbb938) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ba58e50c6f0f592a41c0435f1943679e8432ed5e/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 93 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fe969115-ef6b-4036-a5e9-0e580d20dc36) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ba58e50c6f0f592a41c0435f1943679e8432ed5e/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 89 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/03fdfe54-36af-4bf3-8e46-b30089139a7c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ba58e50c6f0f592a41c0435f1943679e8432ed5e/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 90 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d316aa10-2b82-4914-a9fb-fccd428d7024) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ba58e50c6f0f592a41c0435f1943679e8432ed5e/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/42ca5b81-654e-4238-a855-a5caf400635a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ba58e50c6f0f592a41c0435f1943679e8432ed5e/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 91 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a9b53e5f-5ae9-4680-a3d7-7cd9b02594a8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/shared-channels.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ba58e50c6f0f592a41c0435f1943679e8432ed5e/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshared-channels.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f5c4585d-89cc-4776-b475-4dded234b2f3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/teams-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ba58e50c6f0f592a41c0435f1943679e8432ed5e/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fteams-developer-portal.md) | 91 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b49be030-db94-42ac-9b0e-47e992c7ea30) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ba58e50c6f0f592a41c0435f1943679e8432ed5e/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 97 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3c0cf943-8d38-4a9a-882f-fd43bb1a2641) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ba58e50c6f0f592a41c0435f1943679e8432ed5e/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-publish-overview.md) | 92 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b9729623-ee3b-4f76-82dd-54ca1b626d90) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ba58e50c6f0f592a41c0435f1943679e8432ed5e/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e109149f-d7c3-49d5-abf1-dffaf9fc6fa4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ba58e50c6f0f592a41c0435f1943679e8432ed5e/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fsubmission-checklist.md) | 89 | 45 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2f67ac40-b9b5-4cf8-b09c-a1db190326ce) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ba58e50c6f0f592a41c0435f1943679e8432ed5e/msteams-platform%2Fget-started%2Fglossary.md) | 90 | 77 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d80fcbe7-9310-4b77-bc5b-42fce3d46491) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/what-are-messaging-extensions.md](https://github.com/Microsof [...]

2024-05-29 05:47 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1096047462ecf4dfeafaf51cc5388d671bf0acad/msteams-platform%2FTOC.yml) | 97 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/695720b4-8e4f-4985-8248-72bb0a64e4ee) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1096047462ecf4dfeafaf51cc5388d671bf0acad/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/18d43380-f371-4fd9-a908-89ab14de21c7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1096047462ecf4dfeafaf51cc5388d671bf0acad/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 91 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ee602779-386b-45ae-909d-8ba1f052765d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1096047462ecf4dfeafaf51cc5388d671bf0acad/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 88 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ddc0fd6f-9857-4e16-a045-5fe34423efae) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1096047462ecf4dfeafaf51cc5388d671bf0acad/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 86 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/30a61a45-c7b6-4593-88ff-8124e3d00b7e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1096047462ecf4dfeafaf51cc5388d671bf0acad/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 80 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e1acd2e6-27f6-420b-b4d0-bb76890e00f4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1096047462ecf4dfeafaf51cc5388d671bf0acad/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 90 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5ebea951-dd7a-437e-8e55-4d42bf26aca3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1096047462ecf4dfeafaf51cc5388d671bf0acad/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5cbe3b0c-99e7-493f-8e3a-125ef1a5a091) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1096047462ecf4dfeafaf51cc5388d671bf0acad/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 89 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f6b027c9-4d64-4812-b485-0a525cd153c8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1096047462ecf4dfeafaf51cc5388d671bf0acad/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 90 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/65096456-30f6-456d-a4c4-9199b845c596) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1096047462ecf4dfeafaf51cc5388d671bf0acad/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5afc49e6-306a-4d2c-a123-5cd88e903f67) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1096047462ecf4dfeafaf51cc5388d671bf0acad/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5f14d8c2-5c63-4a0b-a3b2-4831940c3305) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/shared-channels.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1096047462ecf4dfeafaf51cc5388d671bf0acad/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshared-channels.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/68e2923e-bc92-43d3-8c5d-7a290cd17a90) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/teams-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1096047462ecf4dfeafaf51cc5388d671bf0acad/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fteams-developer-portal.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7ec9e6ee-20d8-4556-968a-9e7eeaab1307) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1096047462ecf4dfeafaf51cc5388d671bf0acad/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 97 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bbe668a4-1dac-41df-9cef-930bd614550f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1096047462ecf4dfeafaf51cc5388d671bf0acad/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-publish-overview.md) | 92 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4572a956-eba4-4264-910f-298c6ff5b40d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1096047462ecf4dfeafaf51cc5388d671bf0acad/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aacb604c-9f19-4ccb-9d92-47572c6699d3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1096047462ecf4dfeafaf51cc5388d671bf0acad/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fsubmission-checklist.md) | 89 | 43 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/12237b13-ecb1-43c2-9ea2-e64c899e2dc4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1096047462ecf4dfeafaf51cc5388d671bf0acad/msteams-platform%2Fget-started%2Fglossary.md) | 90 | 81 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f9a748aa-2cfe-4566-b053-296cea1cc396) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/what-are-messaging-extensions.md](https://github.com/Microsof [...]

2024-05-29 10:13 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/4c97868c07c1cf9bc043b13bdec762ac8a01386b/msteams-platform%2FTOC.yml) | 97 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0bf64222-fea3-4706-88ed-98743f08e135) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4c97868c07c1cf9bc043b13bdec762ac8a01386b/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dbcb2c95-7b76-4356-83be-48d1daddf444) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4c97868c07c1cf9bc043b13bdec762ac8a01386b/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 91 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9c420b38-38b7-422c-8869-46742a143ea1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4c97868c07c1cf9bc043b13bdec762ac8a01386b/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 88 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a9099411-a92b-42dc-bba7-42816c110416) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4c97868c07c1cf9bc043b13bdec762ac8a01386b/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 86 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8b85f4e0-e737-4a2f-93fd-1810b177a503) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4c97868c07c1cf9bc043b13bdec762ac8a01386b/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 80 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1cd3c2b5-01f9-4b06-bfeb-0d89a01b60ca) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4c97868c07c1cf9bc043b13bdec762ac8a01386b/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 90 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c6c0443a-b7ea-4834-9750-4813eaa8d069) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4c97868c07c1cf9bc043b13bdec762ac8a01386b/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8cc3b5e8-4896-4f44-863f-5970c297536e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4c97868c07c1cf9bc043b13bdec762ac8a01386b/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 89 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2cbcc8f1-b9d0-4079-a28d-1a587ad0449b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4c97868c07c1cf9bc043b13bdec762ac8a01386b/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 90 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1f8ec0f7-53e9-411d-a7ad-a97eefbaa537) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4c97868c07c1cf9bc043b13bdec762ac8a01386b/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d54e296f-dee5-4f71-b5e0-f91dd741dfce) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4c97868c07c1cf9bc043b13bdec762ac8a01386b/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d9511ef1-55c4-409b-a23b-35e143207610) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/shared-channels.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4c97868c07c1cf9bc043b13bdec762ac8a01386b/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshared-channels.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e025802f-3c42-460d-9225-b0a5e1518176) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/teams-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4c97868c07c1cf9bc043b13bdec762ac8a01386b/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fteams-developer-portal.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/093c2d29-2ec8-4fe5-83bf-94b685884332) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4c97868c07c1cf9bc043b13bdec762ac8a01386b/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 97 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cf85c991-4436-4871-a367-91c31c456f8b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4c97868c07c1cf9bc043b13bdec762ac8a01386b/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-publish-overview.md) | 92 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bff4c791-8c9b-471b-9d54-5a50005e62a9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4c97868c07c1cf9bc043b13bdec762ac8a01386b/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7372bd94-0f7f-45c3-925a-174f50b76b6e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4c97868c07c1cf9bc043b13bdec762ac8a01386b/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fsubmission-checklist.md) | 89 | 43 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3f4f8b4c-9d7b-45b1-a39b-3fb6ff96e279) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4c97868c07c1cf9bc043b13bdec762ac8a01386b/msteams-platform%2Fget-started%2Fglossary.md) | 90 | 81 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b1a70645-5f78-414f-964f-34ad36eb01ac) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/what-are-messaging-extensions.md](https://github.com/Microsof [...]

2024-05-30 10:48 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/35726d61a61d165d85220df1fb504024ed508a6d/msteams-platform%2FTOC.yml) | 97 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3aaee8cd-84a1-49b9-bb5a-0c67a0569258) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/35726d61a61d165d85220df1fb504024ed508a6d/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8a4fdf9a-2478-44ba-bcce-0f9a9f6bacde) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/35726d61a61d165d85220df1fb504024ed508a6d/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 91 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/36bf86e1-b8db-41e5-bbc9-6198d30783ad) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/35726d61a61d165d85220df1fb504024ed508a6d/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 88 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/08b32218-99f2-47f3-95d8-281bcc947ed8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/35726d61a61d165d85220df1fb504024ed508a6d/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 86 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f5deaf8c-5518-46f8-95d3-b69f452e3523) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/35726d61a61d165d85220df1fb504024ed508a6d/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 80 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2012bec3-5927-40a8-9107-ce81b3483c23) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/35726d61a61d165d85220df1fb504024ed508a6d/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 90 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/56f18a4c-34f0-4411-8991-be23be5454d5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/35726d61a61d165d85220df1fb504024ed508a6d/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fd19a044-86c8-4e68-8463-4e5b5cf5815c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/35726d61a61d165d85220df1fb504024ed508a6d/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 89 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8698d8d0-3d0e-4473-8412-bab9448635f7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/35726d61a61d165d85220df1fb504024ed508a6d/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 90 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/517fe98c-c742-4879-8661-a9145c1de614) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/35726d61a61d165d85220df1fb504024ed508a6d/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0add7608-9771-4925-a1b8-4c160c00cd00) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/35726d61a61d165d85220df1fb504024ed508a6d/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4023560d-8b96-417a-b05c-1cc36bba62e4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/shared-channels.md](https://github.com/MicrosoftDocs/msteams-docs/blob/35726d61a61d165d85220df1fb504024ed508a6d/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshared-channels.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aa9f7bc7-5109-438f-ae5f-ddf71df18a5b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/teams-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/35726d61a61d165d85220df1fb504024ed508a6d/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fteams-developer-portal.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a02d31e4-d3d9-4f9f-b776-a2f46d00dd15) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/35726d61a61d165d85220df1fb504024ed508a6d/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 97 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cb1fd81a-533a-4c99-83d2-0f80a5cc281b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/35726d61a61d165d85220df1fb504024ed508a6d/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-publish-overview.md) | 92 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cc176a94-c1ce-4217-95e9-aead0351f188) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/35726d61a61d165d85220df1fb504024ed508a6d/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a17e7f4c-ea53-47ea-89bc-8abd8e52eaae) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/35726d61a61d165d85220df1fb504024ed508a6d/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fsubmission-checklist.md) | 89 | 43 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d301f5ac-d528-4470-a7b7-2a7cda4bd80a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/35726d61a61d165d85220df1fb504024ed508a6d/msteams-platform%2Fget-started%2Fglossary.md) | 90 | 81 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f0cf0bca-1e5a-4d9f-961f-056671da62cb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/what-are-messaging-extensions.md](https://github.com/Microsof [...]

2024-05-30 15:03 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/352e474891af914acd45f7ba2d3e17388ae30bc8/msteams-platform%2FTOC.yml) | 97 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e0177fa6-4e30-4698-b015-80897bba3acf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/352e474891af914acd45f7ba2d3e17388ae30bc8/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8505e8a6-2bbc-4ef6-963b-ce47ddfc16eb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/352e474891af914acd45f7ba2d3e17388ae30bc8/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 91 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7ecb9b44-f122-4272-9677-276ea3766f6e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/352e474891af914acd45f7ba2d3e17388ae30bc8/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 88 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/87c94133-26af-4379-b969-142076fb7511) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/352e474891af914acd45f7ba2d3e17388ae30bc8/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 86 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2199c6a8-88bc-4011-b6dc-83987d8aff8a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/352e474891af914acd45f7ba2d3e17388ae30bc8/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 80 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/420a1c03-9c78-4405-b5e2-234cb0438a79) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/352e474891af914acd45f7ba2d3e17388ae30bc8/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 90 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/137eba57-b901-4f69-8a23-a497fdc5ddf6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/352e474891af914acd45f7ba2d3e17388ae30bc8/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/78572d65-4d91-451c-a5e7-eab1a04c78b4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/352e474891af914acd45f7ba2d3e17388ae30bc8/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 89 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c9422e3c-ddaa-45a4-bee7-658141f5d798) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/352e474891af914acd45f7ba2d3e17388ae30bc8/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 90 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bda89f33-027c-404d-8eb8-66bdbb6560f1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/352e474891af914acd45f7ba2d3e17388ae30bc8/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e6d055f7-36d5-4348-a7c2-9f86494bbd82) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/352e474891af914acd45f7ba2d3e17388ae30bc8/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b3a939e9-f79f-4408-bc58-70924ca25539) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/share-to-teams-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/352e474891af914acd45f7ba2d3e17388ae30bc8/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshare-to-teams-overview.md) | 96 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4fba3dec-05d6-4dee-82d7-f31457307b7c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/shared-channels.md](https://github.com/MicrosoftDocs/msteams-docs/blob/352e474891af914acd45f7ba2d3e17388ae30bc8/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshared-channels.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/11b6bc10-676a-4a4f-9bf9-aed47070203f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/teams-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/352e474891af914acd45f7ba2d3e17388ae30bc8/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fteams-developer-portal.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/21c07926-5da3-4011-a831-79793e32a53e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/352e474891af914acd45f7ba2d3e17388ae30bc8/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 97 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/350e37c6-9109-4993-ba8a-083cc5df17dd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/352e474891af914acd45f7ba2d3e17388ae30bc8/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-publish-overview.md) | 92 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/29e09a8e-c2a8-4ae6-8201-70aa45ca8ac4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/352e474891af914acd45f7ba2d3e17388ae30bc8/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/02ff82b8-1bb8-47f9-a3de-0a506cf3ce98) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/352e474891af914acd45f7ba2d3e17388ae30bc8/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fsubmission-checklist.md) | 89 | 43 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/be4cacee-5ed9-4109-8802-38d4dcb706b0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](ht [...]

2024-05-30 15:28 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/d75666f9569b1939582abd9d778c45caf5cc3641/msteams-platform%2FTOC.yml) | 97 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1f52a7ba-b205-4484-925d-0ad57d2bffb7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d75666f9569b1939582abd9d778c45caf5cc3641/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0c345b14-dddc-49af-8e4a-7d341666dd89) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d75666f9569b1939582abd9d778c45caf5cc3641/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 91 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/17299f98-f08f-408b-a091-90bfba51ad49) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d75666f9569b1939582abd9d778c45caf5cc3641/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 88 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d328b4a9-6011-4b48-b1db-85a8f8156fca) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d75666f9569b1939582abd9d778c45caf5cc3641/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 86 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4feb4ea1-79f1-445a-a49d-536706a7cc87) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d75666f9569b1939582abd9d778c45caf5cc3641/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 80 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d3aac7a4-3869-4a00-b19a-d101e317ad66) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d75666f9569b1939582abd9d778c45caf5cc3641/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 90 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4e203af2-a3ce-432c-9630-d1721ea02045) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d75666f9569b1939582abd9d778c45caf5cc3641/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b767fd99-5534-4078-8ee2-c7567b36e55b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d75666f9569b1939582abd9d778c45caf5cc3641/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 89 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/002a992a-dc41-41e7-8f00-b0bd89e8fee4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d75666f9569b1939582abd9d778c45caf5cc3641/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 90 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/96cba091-1905-40eb-86df-901b918bc7f3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d75666f9569b1939582abd9d778c45caf5cc3641/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/03ac4376-5fb3-4562-b375-485b6e738f5c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d75666f9569b1939582abd9d778c45caf5cc3641/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2c8cf8fa-2c70-4f02-a3d1-346ea94873f9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/share-to-teams-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d75666f9569b1939582abd9d778c45caf5cc3641/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshare-to-teams-overview.md) | 96 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/94ae58f2-b393-4016-9ce5-ed4270609b33) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/shared-channels.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d75666f9569b1939582abd9d778c45caf5cc3641/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshared-channels.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/523803c1-19e1-48df-86c9-ad53a91b0d64) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/teams-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d75666f9569b1939582abd9d778c45caf5cc3641/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fteams-developer-portal.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/46c9f8a0-2862-4ceb-9883-2af47a45e06d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d75666f9569b1939582abd9d778c45caf5cc3641/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 97 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/eaf64112-6573-4f58-b428-21ce39b09dd7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d75666f9569b1939582abd9d778c45caf5cc3641/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-publish-overview.md) | 92 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7199f905-9457-4259-b25c-79d426c7f2ce) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d75666f9569b1939582abd9d778c45caf5cc3641/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c440899d-5f41-44ba-852d-c4320c53d98e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d75666f9569b1939582abd9d778c45caf5cc3641/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fsubmission-checklist.md) | 89 | 43 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6dd871d7-73fb-4707-8baf-881e1fbe8f84) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](ht [...]

2024-05-31 13:30 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/7cc8a8419cdd5410c6889bbe19be09e5e2f0b2b6/msteams-platform%2FTOC.yml) | 97 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/15ca05e8-e884-4085-be07-6e1f2403bc06) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7cc8a8419cdd5410c6889bbe19be09e5e2f0b2b6/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/39b5d774-c8cd-4713-8e54-3ac6be8c708f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7cc8a8419cdd5410c6889bbe19be09e5e2f0b2b6/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 91 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1e2135d8-6d74-439a-a82e-34aa105aa608) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7cc8a8419cdd5410c6889bbe19be09e5e2f0b2b6/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 88 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b72c5944-3493-41c4-b80f-99e38d40de08) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7cc8a8419cdd5410c6889bbe19be09e5e2f0b2b6/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 86 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c1dd92ce-7bb0-4dbf-bb7f-e5c94267c396) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7cc8a8419cdd5410c6889bbe19be09e5e2f0b2b6/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 80 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/98ac3c9d-52e8-4420-8615-5e5a165f4f3a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7cc8a8419cdd5410c6889bbe19be09e5e2f0b2b6/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 90 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/10ac7032-4e8d-4767-98e9-91ee67e0bf3a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7cc8a8419cdd5410c6889bbe19be09e5e2f0b2b6/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a8da451a-de64-407f-8247-8494bfb671f6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7cc8a8419cdd5410c6889bbe19be09e5e2f0b2b6/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 89 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2b88f246-ee6b-4dde-8330-d00117ddcd4b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7cc8a8419cdd5410c6889bbe19be09e5e2f0b2b6/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 90 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/981ead2e-59c5-4656-a48b-0ce83183fea6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7cc8a8419cdd5410c6889bbe19be09e5e2f0b2b6/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/718dfb42-0278-409b-9cf0-8723961a4d0b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7cc8a8419cdd5410c6889bbe19be09e5e2f0b2b6/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b8151545-8142-48f4-95cd-1c48551765b4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/share-to-teams-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7cc8a8419cdd5410c6889bbe19be09e5e2f0b2b6/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshare-to-teams-overview.md) | 96 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/23a3184c-720b-4974-ae33-343f51e5b99c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/shared-channels.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7cc8a8419cdd5410c6889bbe19be09e5e2f0b2b6/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshared-channels.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b17b8da5-ba5b-439d-9f88-6dcac592379f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/teams-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7cc8a8419cdd5410c6889bbe19be09e5e2f0b2b6/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fteams-developer-portal.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1e457388-0c68-4f3d-a985-8f81f50d3cec) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7cc8a8419cdd5410c6889bbe19be09e5e2f0b2b6/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 95 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dc5028b9-9944-4b0b-997d-d53a84d173d5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7cc8a8419cdd5410c6889bbe19be09e5e2f0b2b6/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-publish-overview.md) | 92 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/731db3ff-7ce3-4fad-a804-3e47dd0c70a5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7cc8a8419cdd5410c6889bbe19be09e5e2f0b2b6/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0770bef5-d0dc-4ace-aa53-35e8c1605f6e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7cc8a8419cdd5410c6889bbe19be09e5e2f0b2b6/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fsubmission-checklist.md) | 89 | 43 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/04ca9efc-3cea-4b00-bd5a-7376b69707cf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](ht [...]

2024-06-11 06:06 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/4c5fa2429da8dbb5d9c90f041a9113c92ea7d881/msteams-platform%2FTOC.yml) | 97 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a8dedf88-e435-4461-b671-a3721a4b7f6b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4c5fa2429da8dbb5d9c90f041a9113c92ea7d881/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9441a622-7157-460b-95be-ab2d01b32e9d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4c5fa2429da8dbb5d9c90f041a9113c92ea7d881/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 91 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/062558c7-2f80-4655-b031-a73988212fc4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4c5fa2429da8dbb5d9c90f041a9113c92ea7d881/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 88 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5d7e1d8e-3886-42d4-8cc8-395b7f72bf4a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4c5fa2429da8dbb5d9c90f041a9113c92ea7d881/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 86 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/88913a09-a793-4ef1-a41b-161299716ca4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4c5fa2429da8dbb5d9c90f041a9113c92ea7d881/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 80 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/eea5274c-fad5-4ffb-b2af-c3584a6aaeb9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4c5fa2429da8dbb5d9c90f041a9113c92ea7d881/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 90 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f07f5d7d-5c97-4b95-8025-7c949055a347) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4c5fa2429da8dbb5d9c90f041a9113c92ea7d881/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/673eda20-d29a-4d82-b8cb-c24a15ce8c77) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4c5fa2429da8dbb5d9c90f041a9113c92ea7d881/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 90 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/07c136ca-ee77-437d-be58-8ef4bfb92065) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4c5fa2429da8dbb5d9c90f041a9113c92ea7d881/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 90 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5952c17e-f548-45f3-8f54-870df2ed3565) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4c5fa2429da8dbb5d9c90f041a9113c92ea7d881/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d27fb612-60da-4e52-a484-3b7b3c390b0e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4c5fa2429da8dbb5d9c90f041a9113c92ea7d881/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/41f659df-2ac5-4c61-830a-bde4a7dd16a4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/share-to-teams-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4c5fa2429da8dbb5d9c90f041a9113c92ea7d881/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshare-to-teams-overview.md) | 96 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ea268ae1-17a3-4e20-b3df-5ba0bf3b1650) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/shared-channels.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4c5fa2429da8dbb5d9c90f041a9113c92ea7d881/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshared-channels.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/375e65c3-5258-441b-b236-a7db710850c8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/teams-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4c5fa2429da8dbb5d9c90f041a9113c92ea7d881/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fteams-developer-portal.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5e86cdae-c901-4034-880a-2f6afc3132bc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4c5fa2429da8dbb5d9c90f041a9113c92ea7d881/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 95 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9ee2cba8-0fa0-41a4-b3c4-3e2af6c67a5b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4c5fa2429da8dbb5d9c90f041a9113c92ea7d881/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-publish-overview.md) | 92 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ed894ee4-fb5d-417e-92fe-eca7cb96e878) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4c5fa2429da8dbb5d9c90f041a9113c92ea7d881/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f168e629-f18c-4085-a4ff-9c49dcde0ffb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4c5fa2429da8dbb5d9c90f041a9113c92ea7d881/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fsubmission-checklist.md) | 89 | 43 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6e8a56e7-2a76-40df-9f15-4ac3e33c84a2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](ht [...]

2024-06-11 06:41 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/14e90a6f69e25847bf5660679966a7cfd2033817/msteams-platform%2FTOC.yml) | 97 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6001dbbf-e873-4a81-b755-4796e96d00ba) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/14e90a6f69e25847bf5660679966a7cfd2033817/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2a485207-1d7f-41d5-9554-0c0a8c77546c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/14e90a6f69e25847bf5660679966a7cfd2033817/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 91 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1c5b6a1b-33a4-4533-b398-9d5446a073a7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/14e90a6f69e25847bf5660679966a7cfd2033817/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 88 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/095bc511-cc54-4f27-9d69-6d9db1220562) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/14e90a6f69e25847bf5660679966a7cfd2033817/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 86 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c31448e6-755c-4d96-806a-0c19d559645d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/14e90a6f69e25847bf5660679966a7cfd2033817/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 80 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9801a9f2-ca02-4b45-9159-4c46fd6846b1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/14e90a6f69e25847bf5660679966a7cfd2033817/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 90 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/11451999-33d4-45f6-9a02-79ba3ce9f549) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/14e90a6f69e25847bf5660679966a7cfd2033817/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d109e7b1-43c8-4a02-b14c-4eda23367bc5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/14e90a6f69e25847bf5660679966a7cfd2033817/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 90 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/def5c710-2804-48fb-b79e-c1c0c974f981) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/14e90a6f69e25847bf5660679966a7cfd2033817/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 90 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/deb407fe-f824-4dcb-a208-de94a7139983) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/14e90a6f69e25847bf5660679966a7cfd2033817/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ffe97c32-0734-4285-bfde-89d54670553d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/14e90a6f69e25847bf5660679966a7cfd2033817/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5b03564c-0293-4277-a697-ca77eafaca6b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/share-to-teams-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/14e90a6f69e25847bf5660679966a7cfd2033817/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshare-to-teams-overview.md) | 96 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/460eb834-d446-41db-9740-5e7a5f153dfd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/shared-channels.md](https://github.com/MicrosoftDocs/msteams-docs/blob/14e90a6f69e25847bf5660679966a7cfd2033817/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshared-channels.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/41bd45da-123a-4a4c-875c-5f1e45119b8e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/teams-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/14e90a6f69e25847bf5660679966a7cfd2033817/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fteams-developer-portal.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/be7ba8f8-9c70-4769-b944-0e3186ae797f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/14e90a6f69e25847bf5660679966a7cfd2033817/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 95 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c1f37def-3b07-4ad0-8966-7c99751a38b6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/14e90a6f69e25847bf5660679966a7cfd2033817/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-publish-overview.md) | 92 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8d3bc425-53ab-4ec8-96af-cb51ea5d6a06) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/14e90a6f69e25847bf5660679966a7cfd2033817/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1fb5d26f-81d9-49c7-ae06-7869d0e10e1e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/14e90a6f69e25847bf5660679966a7cfd2033817/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fsubmission-checklist.md) | 89 | 43 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9265ee6e-6968-4cb2-b53a-111156d9bded) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](ht [...]

2024-06-13 04:58 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/774ea82b254981ab7a42d9d6e0d8a536f6510007/msteams-platform%2FTOC.yml) | 97 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fbf87858-42d0-499f-8fca-b74554840f08) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/774ea82b254981ab7a42d9d6e0d8a536f6510007/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/733ae499-9c99-4a5e-a91c-b91b782e4df9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/774ea82b254981ab7a42d9d6e0d8a536f6510007/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 91 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0e819fd8-fd8c-4f0c-b847-4c81d980e312) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/774ea82b254981ab7a42d9d6e0d8a536f6510007/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 88 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c6687784-4f40-42cb-9451-d3c521fd6298) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/774ea82b254981ab7a42d9d6e0d8a536f6510007/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 86 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8f16b189-79a9-4b68-acf0-ddd2c8307db6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/774ea82b254981ab7a42d9d6e0d8a536f6510007/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 80 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3ecc80e8-3f70-4656-8c2f-9a8bc9170d96) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/774ea82b254981ab7a42d9d6e0d8a536f6510007/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 90 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a516e942-4e9b-4664-a6a0-f07c764dbb47) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/774ea82b254981ab7a42d9d6e0d8a536f6510007/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/42f407f3-c7ff-483a-aae7-994e18657a76) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/774ea82b254981ab7a42d9d6e0d8a536f6510007/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 90 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/67268e1f-6e07-4bfd-bc81-f271c95cc89c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/774ea82b254981ab7a42d9d6e0d8a536f6510007/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 90 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5e2ca63a-7179-4b3e-bb71-f41a749bc387) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/774ea82b254981ab7a42d9d6e0d8a536f6510007/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2165f614-fe0e-4663-8219-879ad70e8a9f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/774ea82b254981ab7a42d9d6e0d8a536f6510007/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e9c94d2f-dce0-4db9-b00d-7866f0afc610) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/share-to-teams-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/774ea82b254981ab7a42d9d6e0d8a536f6510007/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshare-to-teams-overview.md) | 96 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/84a2d496-439b-4d10-ba4f-215f6f1b0663) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/shared-channels.md](https://github.com/MicrosoftDocs/msteams-docs/blob/774ea82b254981ab7a42d9d6e0d8a536f6510007/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshared-channels.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5d546bd2-c6b9-4e89-acac-8743899e3463) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/teams-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/774ea82b254981ab7a42d9d6e0d8a536f6510007/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fteams-developer-portal.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0697687a-b1c0-4e6a-93e1-d063e83cbfaa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/774ea82b254981ab7a42d9d6e0d8a536f6510007/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 95 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/04a131de-b6a1-47f1-a88c-0ea244298def) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/774ea82b254981ab7a42d9d6e0d8a536f6510007/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-publish-overview.md) | 92 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d6aed463-302f-4dc6-9fb4-de571e62eeb0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/774ea82b254981ab7a42d9d6e0d8a536f6510007/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/00de2b0f-640e-4b5c-90ee-ddca070639cc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/774ea82b254981ab7a42d9d6e0d8a536f6510007/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fsubmission-checklist.md) | 89 | 43 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/18c34ca9-d20e-4c83-b048-beb7c8995ab6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](ht [...]

2024-06-19 06:53 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1c842c41f5691dc02780a80e99e11ca0bdb35e61/msteams-platform%2FTOC.yml) |   |   | [link]( ) | [:warning:](# "Could not check with Acrolinx&#10;Please close and reopen pull request") |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1c842c41f5691dc02780a80e99e11ca0bdb35e61/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/784cf4d9-7058-4cad-a035-c5496de5fea5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1c842c41f5691dc02780a80e99e11ca0bdb35e61/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 91 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/628611f6-8298-44b1-a2ad-decfe1e83fce) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1c842c41f5691dc02780a80e99e11ca0bdb35e61/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 88 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e5f691de-50a6-4ae9-b698-ca3c5e821cf6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1c842c41f5691dc02780a80e99e11ca0bdb35e61/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 86 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5ba04ec9-b5e8-40a9-863d-d9d9e6548f60) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1c842c41f5691dc02780a80e99e11ca0bdb35e61/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 80 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bb78ea67-6a96-4ffa-9b22-a05402126c8a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1c842c41f5691dc02780a80e99e11ca0bdb35e61/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 89 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0e6ff346-bf14-4007-903e-a5d69705b399) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1c842c41f5691dc02780a80e99e11ca0bdb35e61/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fa38b7f4-0647-4b23-ae74-14dbf2e017b2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1c842c41f5691dc02780a80e99e11ca0bdb35e61/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 91 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/620cd9a2-b5c1-40bf-9d30-3d4dc720ae7e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1c842c41f5691dc02780a80e99e11ca0bdb35e61/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 90 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/976b3264-a102-4087-a196-d8f2d177ab80) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1c842c41f5691dc02780a80e99e11ca0bdb35e61/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 91 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/30fc2d9c-eb34-4504-9af8-ea5fd2e6b56d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1c842c41f5691dc02780a80e99e11ca0bdb35e61/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/69a9bf62-71f2-49f9-b401-dea8cd2c64c5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/share-to-teams-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1c842c41f5691dc02780a80e99e11ca0bdb35e61/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshare-to-teams-overview.md) | 96 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/21341c8e-b2a8-453e-8036-b62aefccf5c2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/shared-channels.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1c842c41f5691dc02780a80e99e11ca0bdb35e61/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshared-channels.md) | 92 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b68cfcde-eee8-4438-834e-3f5b79fa33e3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/teams-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1c842c41f5691dc02780a80e99e11ca0bdb35e61/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fteams-developer-portal.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/53359057-ffaa-4e8d-8660-55425fe4bb5c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1c842c41f5691dc02780a80e99e11ca0bdb35e61/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 95 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/12edd509-786f-4408-b608-fef524972fda) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1c842c41f5691dc02780a80e99e11ca0bdb35e61/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-publish-overview.md) | 94 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c147f605-516b-4855-86da-414fb0e95765) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1c842c41f5691dc02780a80e99e11ca0bdb35e61/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/049746cc-5146-4f7c-b978-0a5e9c33eadf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1c842c41f5691dc02780a80e99e11ca0bdb35e61/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fsubmission-checklist.md) | 89 | 44 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4afc425a-d82d-44a4-8683-58004d193c4d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1c842c41f5691dc [...]

2024-06-19 11:52 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1de96cdea4b4e4df45c8f2719edb6327c31f95ec/msteams-platform%2FTOC.yml) |   |   | [link]( ) | [:warning:](# "Could not check with Acrolinx&#10;Please close and reopen pull request") |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1de96cdea4b4e4df45c8f2719edb6327c31f95ec/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fd62f70a-7b3b-4562-bf53-213124a01b60) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1de96cdea4b4e4df45c8f2719edb6327c31f95ec/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 91 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/39d36b9d-3f65-4b07-b6b5-d654481ecb24) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1de96cdea4b4e4df45c8f2719edb6327c31f95ec/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 88 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fbba1599-d233-4303-a5a4-0691e9a47f01) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1de96cdea4b4e4df45c8f2719edb6327c31f95ec/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 86 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/15d6cecf-147a-430e-aa8a-183064c34b8c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1de96cdea4b4e4df45c8f2719edb6327c31f95ec/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 80 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e2d2fa08-0433-4f3f-b1d0-4fef74227562) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1de96cdea4b4e4df45c8f2719edb6327c31f95ec/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 89 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/10986ba6-4003-4990-960e-cb2e712f26ca) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1de96cdea4b4e4df45c8f2719edb6327c31f95ec/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/65653f9d-fa86-4c63-9f13-82d2dcf78251) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1de96cdea4b4e4df45c8f2719edb6327c31f95ec/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 91 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b05bc3eb-a01b-47cf-8085-a85c2cfc1699) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1de96cdea4b4e4df45c8f2719edb6327c31f95ec/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 90 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9434a313-6084-4c99-b7e7-f0933db96c20) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1de96cdea4b4e4df45c8f2719edb6327c31f95ec/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 91 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/54e6ebcb-8186-4b6c-bf7d-767d5888a6d7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1de96cdea4b4e4df45c8f2719edb6327c31f95ec/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/86a7ddce-a018-4a53-80b9-47d234cb9f1c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/share-to-teams-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1de96cdea4b4e4df45c8f2719edb6327c31f95ec/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshare-to-teams-overview.md) | 96 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1c804b4a-b8a0-4783-8414-c3ed32e264ec) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/shared-channels.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1de96cdea4b4e4df45c8f2719edb6327c31f95ec/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshared-channels.md) | 92 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/77965505-5f36-4915-94fb-6b826830c194) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/teams-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1de96cdea4b4e4df45c8f2719edb6327c31f95ec/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fteams-developer-portal.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e5db4276-0e33-4030-af51-3a1d36fccf5b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1de96cdea4b4e4df45c8f2719edb6327c31f95ec/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 95 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/61edd2be-6b8f-44bf-bb27-fe6bfc59667d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1de96cdea4b4e4df45c8f2719edb6327c31f95ec/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-publish-overview.md) | 94 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c5a10dcb-71b0-47ea-a056-78b62cdcd35a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1de96cdea4b4e4df45c8f2719edb6327c31f95ec/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b592e0c0-890e-4ea1-a3d2-48e85e0907ff) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1de96cdea4b4e4df45c8f2719edb6327c31f95ec/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fsubmission-checklist.md) | 89 | 44 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/be5f5feb-8b7e-48e0-b986-5ceb003f79e3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1de96cdea4b4e4d [...]

2024-06-21 14:19 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/57ef6fa64be0e921cfa164f1187b121a60c49736/msteams-platform%2FTOC.yml) |   |   | [link]( ) | [:warning:](# "Could not check with Acrolinx&#10;Please close and reopen pull request") |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/57ef6fa64be0e921cfa164f1187b121a60c49736/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ce7f1c39-81bf-4997-b845-d99b592211ed) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/57ef6fa64be0e921cfa164f1187b121a60c49736/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 91 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4e553fd5-0841-4537-aac3-675a862e0857) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/57ef6fa64be0e921cfa164f1187b121a60c49736/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 88 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e9beb1bb-96be-4f50-9414-89a5fd82ee47) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/57ef6fa64be0e921cfa164f1187b121a60c49736/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 86 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/86013870-0730-4eca-bc1d-04df3eb65c61) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/57ef6fa64be0e921cfa164f1187b121a60c49736/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 80 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6a795aaf-a819-4d8f-bda3-26b4b40ad8d0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/57ef6fa64be0e921cfa164f1187b121a60c49736/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 89 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9a79aa08-10d5-489c-a1b3-bfebbe28e92a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/57ef6fa64be0e921cfa164f1187b121a60c49736/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/03171805-ea12-406c-9414-216a12325a8d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/57ef6fa64be0e921cfa164f1187b121a60c49736/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 91 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0d163b8d-0d0a-4517-a204-6269c810b167) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/57ef6fa64be0e921cfa164f1187b121a60c49736/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 90 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1258a6eb-9c71-44ef-a13c-1f03f597201b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/57ef6fa64be0e921cfa164f1187b121a60c49736/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 91 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cd2f6a43-ecaa-4e83-81b3-0a4d7baff6c9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/57ef6fa64be0e921cfa164f1187b121a60c49736/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ecb4fb6b-34e2-4729-8e72-eb4c3f22ae48) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/share-to-teams-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/57ef6fa64be0e921cfa164f1187b121a60c49736/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshare-to-teams-overview.md) | 96 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b0bc057f-becf-4947-90c4-edb6e4da96aa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/shared-channels.md](https://github.com/MicrosoftDocs/msteams-docs/blob/57ef6fa64be0e921cfa164f1187b121a60c49736/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshared-channels.md) | 92 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0d3b906f-ca77-40ae-8a48-38f5e235f04b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/teams-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/57ef6fa64be0e921cfa164f1187b121a60c49736/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fteams-developer-portal.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5dd909ed-4d3e-4d09-899b-bea865185599) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/57ef6fa64be0e921cfa164f1187b121a60c49736/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 95 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/32c539af-0f31-45a6-834a-42d90dd6db30) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/57ef6fa64be0e921cfa164f1187b121a60c49736/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-publish-overview.md) | 94 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0beb159a-15bd-4bd3-b1bc-73331fc5964b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/57ef6fa64be0e921cfa164f1187b121a60c49736/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/24c0ec18-2c73-48ee-88c5-ecd24686f257) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/57ef6fa64be0e921cfa164f1187b121a60c49736/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fsubmission-checklist.md) | 89 | 44 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f6e6cb75-2fbe-4c47-a977-a1a46630abc4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/sovereign -cloud.md](https://github.com/MicrosoftDocs/msteams-docs/blob/57ef6fa64b [...]

2024-07-02 10:23 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/82f29e661d945da23113710a56f10aa8a9453090/msteams-platform%2FTOC.yml) |   |   | [link]( ) | [:warning:](# "Could not check with Acrolinx&#10;Please close and reopen pull request") |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/82f29e661d945da23113710a56f10aa8a9453090/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1d2ec332-3ee2-4477-bc7b-3a79aa9bc9d1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/82f29e661d945da23113710a56f10aa8a9453090/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 91 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/08bcc49c-d4b3-4ec3-af00-e01c93e6cef1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/82f29e661d945da23113710a56f10aa8a9453090/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 86 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a609b53c-8a46-467d-bb44-f546bb1a9526) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/82f29e661d945da23113710a56f10aa8a9453090/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 86 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/33ba4f47-2c48-47d3-a075-9db36aadd5af) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/82f29e661d945da23113710a56f10aa8a9453090/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 80 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6c360969-3eb2-424e-afd4-bfe66c6aa62b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/82f29e661d945da23113710a56f10aa8a9453090/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 89 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3e22a2d5-8b9c-4df1-b38f-771bbde9a5ca) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/82f29e661d945da23113710a56f10aa8a9453090/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a5d2f831-3aaa-47b9-abe1-d18b6fe4a882) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/82f29e661d945da23113710a56f10aa8a9453090/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 91 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ffb9de1c-dd8c-4657-b43e-01d449eb55f3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/82f29e661d945da23113710a56f10aa8a9453090/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 90 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f80965d5-794d-46ba-a34e-170641b9dfbb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/82f29e661d945da23113710a56f10aa8a9453090/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 91 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/93e39816-ff6c-4ddd-9ef9-db04fb9d4974) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/82f29e661d945da23113710a56f10aa8a9453090/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5c32d47d-e7e7-4cc6-bcab-9237449774ad) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/share-to-teams-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/82f29e661d945da23113710a56f10aa8a9453090/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshare-to-teams-overview.md) | 96 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d89f0f52-fa3a-4021-8581-454702a18e7e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/shared-channels.md](https://github.com/MicrosoftDocs/msteams-docs/blob/82f29e661d945da23113710a56f10aa8a9453090/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshared-channels.md) | 92 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2a2c23d2-27cf-4cd0-ae0a-538e2f20cd5d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/teams-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/82f29e661d945da23113710a56f10aa8a9453090/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fteams-developer-portal.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5091c840-c091-4b56-97da-5b58bdf48fa7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/82f29e661d945da23113710a56f10aa8a9453090/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 95 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/578db286-2078-47c3-a9be-61a2a6c09349) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/82f29e661d945da23113710a56f10aa8a9453090/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-publish-overview.md) | 94 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9c2ef7ba-ebe8-4b67-a265-a0ccabcf6bf4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/82f29e661d945da23113710a56f10aa8a9453090/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c70c21fa-0944-489a-9ca7-4e4f34ca1c47) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/82f29e661d945da23113710a56f10aa8a9453090/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fsubmission-checklist.md) | 88 | 46 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/43fac83e-6c33-4106-a762-f2661e32d086) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/sovereign-cloud.md](https://github.com/MicrosoftDocs/msteams-docs/blob/82f29e661d9 [...]

2024-07-02 12:17 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/bb7d67a9368dc8aeb9d5f19079961c2ef452df02/msteams-platform%2FTOC.yml) | 97 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/15d3a7f3-e60a-4ba1-b152-1a1eeba0e608) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bb7d67a9368dc8aeb9d5f19079961c2ef452df02/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 86 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/24be6276-24ff-4983-901c-c3af6c9f73b0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bb7d67a9368dc8aeb9d5f19079961c2ef452df02/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 91 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f04b14e0-41de-49a4-b2a1-a5e89c1f6bfb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bb7d67a9368dc8aeb9d5f19079961c2ef452df02/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 90 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6dcf81dc-9183-49ad-b53b-183dd8debcf3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bb7d67a9368dc8aeb9d5f19079961c2ef452df02/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 86 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cfcd73cb-0d2c-41fb-bbaa-a73c999b247b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bb7d67a9368dc8aeb9d5f19079961c2ef452df02/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 81 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e7c8eab3-20ae-48e4-b441-3b40d2602737) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bb7d67a9368dc8aeb9d5f19079961c2ef452df02/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 89 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/29e443a6-10eb-4a7a-990f-a38646f70f9c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bb7d67a9368dc8aeb9d5f19079961c2ef452df02/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/956056cd-94f3-40cb-8147-62e99ada1330) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bb7d67a9368dc8aeb9d5f19079961c2ef452df02/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 91 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/361cd7b5-0d41-43fb-8c08-d4a870f416a8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bb7d67a9368dc8aeb9d5f19079961c2ef452df02/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 90 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e90989c6-bcaa-4777-b0f4-d6b96961a1c1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bb7d67a9368dc8aeb9d5f19079961c2ef452df02/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 91 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d5822637-d04f-420a-b71b-53a49f66d64f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bb7d67a9368dc8aeb9d5f19079961c2ef452df02/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8184cc80-ceaa-45c3-829f-6f0a9afc375c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/share-to-teams-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bb7d67a9368dc8aeb9d5f19079961c2ef452df02/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshare-to-teams-overview.md) | 94 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/048e4dfd-7b63-4f91-b7d0-90c8801ede0c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/shared-channels.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bb7d67a9368dc8aeb9d5f19079961c2ef452df02/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshared-channels.md) | 92 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/574738c7-906d-42b3-8b58-1b3c1cc32466) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/teams-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bb7d67a9368dc8aeb9d5f19079961c2ef452df02/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fteams-developer-portal.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/499dbcc9-e98d-4f1a-acb7-df7319c7b34e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bb7d67a9368dc8aeb9d5f19079961c2ef452df02/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 95 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0be67820-8b2a-4f73-94c2-618d70f9edb6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bb7d67a9368dc8aeb9d5f19079961c2ef452df02/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-publish-overview.md) | 94 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ca01f092-e9eb-4481-80b3-4799254d089c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bb7d67a9368dc8aeb9d5f19079961c2ef452df02/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2471550e-7955-4790-994b-774bdcbf555f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bb7d67a9368dc8aeb9d5f19079961c2ef452df02/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fsubmission-checklist.md) | 88 | 46 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a3621dea-aa01-43fe-91cc-427895702c36) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/sovereign-cloud.m [...]

2024-07-02 12:47 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a79360dfe1f396f9aa764b599089e1402733b95e/msteams-platform%2FTOC.yml) | 97 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fe9cdd14-2891-4c11-9656-471eae9aa473) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a79360dfe1f396f9aa764b599089e1402733b95e/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 86 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6095974b-f37b-47ad-8d0a-08fef3f3d2b6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a79360dfe1f396f9aa764b599089e1402733b95e/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 91 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0857eecd-8615-4cbe-95ce-7fa497eaa04d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a79360dfe1f396f9aa764b599089e1402733b95e/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 90 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d6e414a4-70e2-41ab-9d1e-157896f58b5d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a79360dfe1f396f9aa764b599089e1402733b95e/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 86 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2890d3e1-9caa-481b-961a-3acfb13eae18) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bot-messages-ai-generated-content.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a79360dfe1f396f9aa764b599089e1402733b95e/msteams-platform%2Fbots%2Fhow-to%2Fbot-messages-ai-generated-content.md) | 96 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3a7197c4-5bbd-4a2c-9c6b-3ca93bb84ce8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a79360dfe1f396f9aa764b599089e1402733b95e/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 81 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/df2c1a31-34cb-4f5c-9d70-d711bf00cd9b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a79360dfe1f396f9aa764b599089e1402733b95e/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 89 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/da3bcd6e-e9e3-49ec-9261-7c334e031f35) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a79360dfe1f396f9aa764b599089e1402733b95e/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/32a735bc-0eb5-4136-b701-776af3dc32cf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a79360dfe1f396f9aa764b599089e1402733b95e/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 91 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9f96915b-41ca-48eb-bc13-2d410159f3b2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a79360dfe1f396f9aa764b599089e1402733b95e/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 90 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/df249f98-628a-4305-a203-aa71484fd7af) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a79360dfe1f396f9aa764b599089e1402733b95e/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 91 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/397e2010-75a5-4ea8-857e-6ccb0d1ecb33) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a79360dfe1f396f9aa764b599089e1402733b95e/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/51d9d835-44d7-4f33-b971-e325d9932389) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/share-to-teams-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a79360dfe1f396f9aa764b599089e1402733b95e/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshare-to-teams-overview.md) | 94 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2af40a01-65c5-418a-b8e6-247f235052b2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/shared-channels.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a79360dfe1f396f9aa764b599089e1402733b95e/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshared-channels.md) | 92 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/510ce431-d40f-440e-98e0-f71b0e250063) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/teams-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a79360dfe1f396f9aa764b599089e1402733b95e/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fteams-developer-portal.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3d053d87-1ae1-4998-b19b-2069294cdb95) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a79360dfe1f396f9aa764b599089e1402733b95e/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 95 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d6c4f073-af7a-4357-bbfc-e2d8bb5de5f1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a79360dfe1f396f9aa764b599089e1402733b95e/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-publish-overview.md) | 94 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5cc8ca1b-719d-4945-b78e-df9dfc92ca52) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a79360dfe1f396f9aa764b599089e1402733b95e/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/94a96d66-049a-4f38-a329-35bc542c98ec) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](ht [...]

2024-07-05 04:55 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/973ab4274adfaa76afd281fa649c93178ec5c12a/msteams-platform%2FTOC.yml) | 97 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c9e9f510-0f5d-4384-ab0d-96916bfc6ae3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/973ab4274adfaa76afd281fa649c93178ec5c12a/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 86 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fc68c789-e9c0-4da0-8daa-c7a11f98ae5a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/973ab4274adfaa76afd281fa649c93178ec5c12a/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 92 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4e4e0bd8-3be1-41d2-a74d-439280716b9c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/973ab4274adfaa76afd281fa649c93178ec5c12a/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 90 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9532c751-1ed3-4ed3-b06d-c03e59f3d6bc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/973ab4274adfaa76afd281fa649c93178ec5c12a/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 86 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/25d6cc8e-c552-4c76-804a-fbbe3841b927) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bot-messages-ai-generated-content.md](https://github.com/MicrosoftDocs/msteams-docs/blob/973ab4274adfaa76afd281fa649c93178ec5c12a/msteams-platform%2Fbots%2Fhow-to%2Fbot-messages-ai-generated-content.md) | 96 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/741a29f1-704c-4593-87f4-04d5d7ff3f59) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/973ab4274adfaa76afd281fa649c93178ec5c12a/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 81 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/43861502-6d6e-431b-8671-7ac8baafa0de) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/973ab4274adfaa76afd281fa649c93178ec5c12a/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 89 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8a17fdea-b3d3-4d8b-a227-49d7afed7863) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/973ab4274adfaa76afd281fa649c93178ec5c12a/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/65d09d2d-9885-4a66-86be-58ea5835d168) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/973ab4274adfaa76afd281fa649c93178ec5c12a/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 91 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/408f8bdc-4405-4556-b487-b96dec68c227) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/973ab4274adfaa76afd281fa649c93178ec5c12a/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 90 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/82cc9fdb-6255-42c5-807d-e076e454e6e5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/973ab4274adfaa76afd281fa649c93178ec5c12a/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 91 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/611cd1a5-0924-44c7-b977-ec06a28e0386) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/973ab4274adfaa76afd281fa649c93178ec5c12a/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1a6ed1b2-e41a-42f9-b7bc-12177c2902fb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/share-to-teams-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/973ab4274adfaa76afd281fa649c93178ec5c12a/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshare-to-teams-overview.md) | 94 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4a6b3da8-62f9-40c5-a7c0-ec705be04957) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/shared-channels.md](https://github.com/MicrosoftDocs/msteams-docs/blob/973ab4274adfaa76afd281fa649c93178ec5c12a/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshared-channels.md) | 92 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5da41684-e5e0-4818-9cdc-df7176d38ba5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/teams-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/973ab4274adfaa76afd281fa649c93178ec5c12a/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fteams-developer-portal.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3adbb672-9489-4cfa-b5a6-7c8b59423e2c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/973ab4274adfaa76afd281fa649c93178ec5c12a/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 95 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9d3dc671-6b00-4bca-bb8c-309e7e99def9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/973ab4274adfaa76afd281fa649c93178ec5c12a/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-publish-overview.md) | 94 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1327670d-ddf1-4b1c-b7ad-0a836d0e9814) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/973ab4274adfaa76afd281fa649c93178ec5c12a/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e0e61aef-b944-4d92-b72c-7ba543994879) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](ht [...]

2024-07-05 06:00 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/dd6e270e66819a4fb8a1c3ed779e19fed4d550b1/msteams-platform%2FTOC.yml) | 97 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9b586211-14d9-4d9d-8779-ee1c091b8938) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dd6e270e66819a4fb8a1c3ed779e19fed4d550b1/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 86 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7cf05884-1f4e-4332-8618-2c54ca75c158) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dd6e270e66819a4fb8a1c3ed779e19fed4d550b1/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 92 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5433409c-2a00-4d68-ba9c-58c45e4ed26e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dd6e270e66819a4fb8a1c3ed779e19fed4d550b1/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 90 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cbf8bf6a-2e13-43e7-9ce1-e00bbfcfa8fe) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dd6e270e66819a4fb8a1c3ed779e19fed4d550b1/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 86 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b99cdd1b-9592-4546-83e8-1dab55f596f3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bot-messages-ai-generated-content.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dd6e270e66819a4fb8a1c3ed779e19fed4d550b1/msteams-platform%2Fbots%2Fhow-to%2Fbot-messages-ai-generated-content.md) | 96 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f4cbf4ff-1b6f-42c0-a39e-48d76010b16c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dd6e270e66819a4fb8a1c3ed779e19fed4d550b1/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 81 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ccf86032-38fb-4548-984e-69215217c925) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dd6e270e66819a4fb8a1c3ed779e19fed4d550b1/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 89 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0976a657-06dc-4e91-9aa5-f0ff38a3b48e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dd6e270e66819a4fb8a1c3ed779e19fed4d550b1/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a0bc28f3-6898-4095-8967-0ad47ad59ed4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dd6e270e66819a4fb8a1c3ed779e19fed4d550b1/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 91 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/02504d8f-d2d3-4b5d-bea7-98398e7f1b83) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dd6e270e66819a4fb8a1c3ed779e19fed4d550b1/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 90 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f8878d1e-a481-4cc7-9d3c-a70d5470614a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dd6e270e66819a4fb8a1c3ed779e19fed4d550b1/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 91 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/81db37ce-c40e-491e-88f2-1d37b919ee94) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dd6e270e66819a4fb8a1c3ed779e19fed4d550b1/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7b896c50-c88a-4b78-98b9-8904065e91eb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/share-to-teams-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dd6e270e66819a4fb8a1c3ed779e19fed4d550b1/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshare-to-teams-overview.md) | 94 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f80e14e6-e4e9-4708-b915-93321d0f85fa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/shared-channels.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dd6e270e66819a4fb8a1c3ed779e19fed4d550b1/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshared-channels.md) | 92 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/17076503-4ca2-4e06-9de1-0d0db4c4ae12) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/teams-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dd6e270e66819a4fb8a1c3ed779e19fed4d550b1/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fteams-developer-portal.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bf0cfd46-6f0d-4ecb-8a1f-5e1cec36006f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dd6e270e66819a4fb8a1c3ed779e19fed4d550b1/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 95 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/438fe4f1-4f68-4d7a-a27e-6ec8b5a52812) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dd6e270e66819a4fb8a1c3ed779e19fed4d550b1/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-publish-overview.md) | 94 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fc525868-93a1-4546-961a-11c3e7cf9a74) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dd6e270e66819a4fb8a1c3ed779e19fed4d550b1/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/58572129-708e-447b-af24-153d1e075c5c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](ht [...]

2024-07-05 07:22 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/dfdebc8591d651bc5ad2e68c06a68cac36b909d6/msteams-platform%2FTOC.yml) | 97 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8f7383e9-6906-4e0d-9191-ac1bc0b7d9dd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dfdebc8591d651bc5ad2e68c06a68cac36b909d6/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 86 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/116f708c-df3c-417a-b6a1-59c5be41ec8d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dfdebc8591d651bc5ad2e68c06a68cac36b909d6/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 92 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/df9bcc0c-8700-40e1-a7ed-ee33b0bafe91) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dfdebc8591d651bc5ad2e68c06a68cac36b909d6/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 90 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3fb89f2f-1a7f-4ea3-8eb0-4948b8d20165) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dfdebc8591d651bc5ad2e68c06a68cac36b909d6/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 86 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7634be36-2e00-4ad2-9235-3c739047a027) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bot-messages-ai-generated-content.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dfdebc8591d651bc5ad2e68c06a68cac36b909d6/msteams-platform%2Fbots%2Fhow-to%2Fbot-messages-ai-generated-content.md) | 96 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/582d512b-4e03-43e5-b763-b5feade436b7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dfdebc8591d651bc5ad2e68c06a68cac36b909d6/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 81 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ccbaa5d2-4592-4e8d-a192-217d10e6db50) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dfdebc8591d651bc5ad2e68c06a68cac36b909d6/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 89 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f513e2e1-20d9-4d45-8dfb-2bab1ad2e75d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dfdebc8591d651bc5ad2e68c06a68cac36b909d6/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9b21a032-d9eb-45c6-afb5-529bc5392a1e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dfdebc8591d651bc5ad2e68c06a68cac36b909d6/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 91 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a060bf85-3b52-4e0a-9c1e-922b82769ec7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dfdebc8591d651bc5ad2e68c06a68cac36b909d6/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 90 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f9f1c4a0-130b-4d6a-a4a9-23daf3ffb805) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dfdebc8591d651bc5ad2e68c06a68cac36b909d6/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 91 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a68a65bb-eda0-48d8-ac49-8f71bb07efee) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dfdebc8591d651bc5ad2e68c06a68cac36b909d6/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5b9c8733-bf0e-4174-89c6-903e9047ed37) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/share-to-teams-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dfdebc8591d651bc5ad2e68c06a68cac36b909d6/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshare-to-teams-overview.md) | 94 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/122ffb4f-a5e5-4424-a3eb-be248d8b56ca) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/shared-channels.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dfdebc8591d651bc5ad2e68c06a68cac36b909d6/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshared-channels.md) | 92 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aa4b3f01-e40b-4954-8264-e6bdf3a25f6a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/teams-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dfdebc8591d651bc5ad2e68c06a68cac36b909d6/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fteams-developer-portal.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c0c05d93-5563-4861-bcb0-78ed794acef3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dfdebc8591d651bc5ad2e68c06a68cac36b909d6/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 95 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/410c018b-a65f-47a4-b6fb-7dcc8f8d4ebb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dfdebc8591d651bc5ad2e68c06a68cac36b909d6/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-publish-overview.md) | 94 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4d84bf76-d782-4faa-ba90-3818d1efb7ed) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dfdebc8591d651bc5ad2e68c06a68cac36b909d6/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a6efb52e-d900-432c-93f4-bb96b3844c14) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](ht [...]

2024-07-05 07:46 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/dfa5f6ea6cc09b225e23bb99da4c8b8743cae77b/msteams-platform%2FTOC.yml) | 97 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a34f81e9-8fd8-4179-aea0-0a6ad8bce3f7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dfa5f6ea6cc09b225e23bb99da4c8b8743cae77b/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 86 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1f2667b0-a24f-4858-bd05-72a9de93f684) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dfa5f6ea6cc09b225e23bb99da4c8b8743cae77b/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 92 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1da2c82c-e467-45ac-bc40-3b80c327c0eb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dfa5f6ea6cc09b225e23bb99da4c8b8743cae77b/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 90 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/71221c08-6d10-4acc-a9aa-70d689bcc040) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dfa5f6ea6cc09b225e23bb99da4c8b8743cae77b/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 86 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/30e079cc-e867-4349-8306-e6d604532748) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bot-messages-ai-generated-content.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dfa5f6ea6cc09b225e23bb99da4c8b8743cae77b/msteams-platform%2Fbots%2Fhow-to%2Fbot-messages-ai-generated-content.md) | 96 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e15fe599-7908-4b61-bb36-f3fd71c651a9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dfa5f6ea6cc09b225e23bb99da4c8b8743cae77b/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 81 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1ba6a933-bab7-4515-972d-b52febe3b5ea) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dfa5f6ea6cc09b225e23bb99da4c8b8743cae77b/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 89 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c7ab301c-a944-48c5-ab2e-93ca264af7d9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dfa5f6ea6cc09b225e23bb99da4c8b8743cae77b/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8eabcbe9-cf5e-4127-994c-b2a1f14f7a98) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dfa5f6ea6cc09b225e23bb99da4c8b8743cae77b/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 91 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/67709160-bae7-481b-b26e-f0c993962bae) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dfa5f6ea6cc09b225e23bb99da4c8b8743cae77b/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 90 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5cf0c8e9-4384-4004-80e7-75b429ab87c9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dfa5f6ea6cc09b225e23bb99da4c8b8743cae77b/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 91 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6abb02f9-5042-4438-9d22-d0a9e8742c2c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dfa5f6ea6cc09b225e23bb99da4c8b8743cae77b/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/90511b8e-34f4-404c-9b7e-3c7a6225f36e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/share-to-teams-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dfa5f6ea6cc09b225e23bb99da4c8b8743cae77b/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshare-to-teams-overview.md) | 94 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0d1c8532-7929-4e13-9cac-3a886ce53f5b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/shared-channels.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dfa5f6ea6cc09b225e23bb99da4c8b8743cae77b/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshared-channels.md) | 92 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3d3dd414-f2c1-4467-8bfb-123438896def) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/teams-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dfa5f6ea6cc09b225e23bb99da4c8b8743cae77b/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fteams-developer-portal.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e45bfcb6-018b-43ed-ac79-4bc43bdfba78) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dfa5f6ea6cc09b225e23bb99da4c8b8743cae77b/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 95 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/befff40c-e7c5-4175-9ef7-01dd1574678f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dfa5f6ea6cc09b225e23bb99da4c8b8743cae77b/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-publish-overview.md) | 94 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/918e2823-6376-4630-8d0c-46878c434b9e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dfa5f6ea6cc09b225e23bb99da4c8b8743cae77b/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/26bb72f8-3730-4ac1-82cb-6d57c26712d4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](ht [...]

2024-07-05 07:56 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1b44c4c7b831a24bd3252aad638692a01b3afeff/msteams-platform%2FTOC.yml) | 97 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4d9f2d84-06e6-49a0-b807-a07a3e7ab187) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1b44c4c7b831a24bd3252aad638692a01b3afeff/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 86 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8db9b00f-af0e-412d-8a30-6bb45474081f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1b44c4c7b831a24bd3252aad638692a01b3afeff/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 92 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b37fccdf-7a69-4e87-aada-3e052fbbe476) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1b44c4c7b831a24bd3252aad638692a01b3afeff/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 90 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9b90d92a-a57d-48be-8a1e-ed62e46ebe7d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1b44c4c7b831a24bd3252aad638692a01b3afeff/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 86 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/91771edc-b8f6-49d0-aa50-f7a5d5518ec7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bot-messages-ai-generated-content.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1b44c4c7b831a24bd3252aad638692a01b3afeff/msteams-platform%2Fbots%2Fhow-to%2Fbot-messages-ai-generated-content.md) | 96 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/55bba2f2-eace-4288-93b1-ab5e1245ff44) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1b44c4c7b831a24bd3252aad638692a01b3afeff/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 81 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7bfae8ca-0f13-43cb-8570-c6f133db8006) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1b44c4c7b831a24bd3252aad638692a01b3afeff/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 89 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d31875e8-8ffd-4e3a-af97-58b6b5ce9cc4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1b44c4c7b831a24bd3252aad638692a01b3afeff/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/12d59fdb-c4d1-4732-ab30-78e557f4c9e6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1b44c4c7b831a24bd3252aad638692a01b3afeff/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 91 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b692dda9-6c43-4e0a-9c5b-db8f108328fd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1b44c4c7b831a24bd3252aad638692a01b3afeff/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 90 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7c770429-16d5-4a9d-8d7b-c04ca903579e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1b44c4c7b831a24bd3252aad638692a01b3afeff/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 91 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9934a2db-e104-4f03-9c37-3010ad8f1293) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1b44c4c7b831a24bd3252aad638692a01b3afeff/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4c9866a2-d0dd-464d-8988-2c5566c70386) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/share-to-teams-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1b44c4c7b831a24bd3252aad638692a01b3afeff/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshare-to-teams-overview.md) | 94 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/517207a6-3135-4f26-a440-f18aeb6c9514) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/shared-channels.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1b44c4c7b831a24bd3252aad638692a01b3afeff/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshared-channels.md) | 92 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/85bdd03c-842e-4436-bbc4-87dfc1b2921a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/teams-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1b44c4c7b831a24bd3252aad638692a01b3afeff/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fteams-developer-portal.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d982eebd-7d0e-4e7f-9bab-3870398a2938) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1b44c4c7b831a24bd3252aad638692a01b3afeff/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 95 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/93ce2abd-0d0b-428b-96bb-38bbbfe3f406) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1b44c4c7b831a24bd3252aad638692a01b3afeff/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-publish-overview.md) | 94 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3c460ca4-2456-4feb-922c-b4d2dd33e9a9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1b44c4c7b831a24bd3252aad638692a01b3afeff/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/73e0489f-cfb4-4205-b5a3-48ac2db317f3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](ht [...]

2024-07-08 13:41 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ee24e36bf971591d291fb679d03c9f6751d55460/msteams-platform%2FTOC.yml) | 97 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/17e617e9-10cc-437c-b346-7c7c1a4f8aa6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ee24e36bf971591d291fb679d03c9f6751d55460/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 86 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/93e59d20-5a24-4592-a338-6d4b07a61349) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ee24e36bf971591d291fb679d03c9f6751d55460/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 92 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fa5bed40-2be2-44e8-8349-cbdea7990759) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ee24e36bf971591d291fb679d03c9f6751d55460/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 90 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/69e34a83-1e8e-4b40-9eb4-dadc0d8daf75) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ee24e36bf971591d291fb679d03c9f6751d55460/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 86 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fffe8b69-d94d-4409-ad7e-f7ce0814a945) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bot-messages-ai-generated-content.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ee24e36bf971591d291fb679d03c9f6751d55460/msteams-platform%2Fbots%2Fhow-to%2Fbot-messages-ai-generated-content.md) | 96 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/82c1c9bc-9540-45dd-9c8a-3bebde7022bc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ee24e36bf971591d291fb679d03c9f6751d55460/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 81 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d9ec4072-a549-4959-beae-69b66ffad57f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ee24e36bf971591d291fb679d03c9f6751d55460/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 89 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5e43fa50-ead8-47a4-a494-dcf0a80a97c5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ee24e36bf971591d291fb679d03c9f6751d55460/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/faa4ea84-dcd0-4676-b869-f5d8890a74ba) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ee24e36bf971591d291fb679d03c9f6751d55460/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 91 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c956ec0e-5de4-4dd2-bd2f-43c4215582e1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ee24e36bf971591d291fb679d03c9f6751d55460/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 90 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/37392677-d60e-4153-825d-610f6e4f377c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ee24e36bf971591d291fb679d03c9f6751d55460/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 91 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/82616d03-7666-417e-97a8-577d144f9e90) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ee24e36bf971591d291fb679d03c9f6751d55460/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/538434b5-536b-4718-90d2-fc8c924a8c47) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/share-to-teams-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ee24e36bf971591d291fb679d03c9f6751d55460/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshare-to-teams-overview.md) | 94 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9ed678d7-57af-4073-9b2d-9123b8e3b2c2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/shared-channels.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ee24e36bf971591d291fb679d03c9f6751d55460/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshared-channels.md) | 92 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/acddda1c-be56-4217-ba68-1d835a9ea095) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/teams-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ee24e36bf971591d291fb679d03c9f6751d55460/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fteams-developer-portal.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5c0a0c95-1491-4bb6-afb7-6ffbd6985bf2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ee24e36bf971591d291fb679d03c9f6751d55460/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 95 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fdf9542d-ccc8-4e7b-859e-b84fe1bbf2a0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ee24e36bf971591d291fb679d03c9f6751d55460/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-publish-overview.md) | 94 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7afa159d-bb0d-430b-986f-69bf02bad1b3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ee24e36bf971591d291fb679d03c9f6751d55460/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fa936f22-8de4-4572-9ba5-58e6e7f08136) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](ht [...]

2024-07-08 14:32 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/7deb2ad1bec79a4282bb7d8cd8710a2a02ea4305/msteams-platform%2FTOC.yml) | 97 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f7a1dc18-5549-4872-b261-d79e2d730a32) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7deb2ad1bec79a4282bb7d8cd8710a2a02ea4305/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 86 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c34f506d-29c4-4193-afc7-8d8d1a969bc1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7deb2ad1bec79a4282bb7d8cd8710a2a02ea4305/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 92 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4af469cc-ce06-4d10-aea2-d7988107feb2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7deb2ad1bec79a4282bb7d8cd8710a2a02ea4305/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 90 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ce14758e-dd7b-468c-8b96-d73fe509699a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7deb2ad1bec79a4282bb7d8cd8710a2a02ea4305/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 86 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a86206db-ac48-41b8-b847-6d250abd090a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bot-messages-ai-generated-content.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7deb2ad1bec79a4282bb7d8cd8710a2a02ea4305/msteams-platform%2Fbots%2Fhow-to%2Fbot-messages-ai-generated-content.md) | 96 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6d7e4fe6-22c6-4b68-9602-1cec1930d4f4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7deb2ad1bec79a4282bb7d8cd8710a2a02ea4305/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 81 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8b2314d6-6467-4fed-a1fa-f718e478285b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7deb2ad1bec79a4282bb7d8cd8710a2a02ea4305/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 89 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1177322d-cad9-4c24-9f4c-a53d694eea38) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7deb2ad1bec79a4282bb7d8cd8710a2a02ea4305/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d7b58231-c434-4396-b8c0-48af4a77bd70) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7deb2ad1bec79a4282bb7d8cd8710a2a02ea4305/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 91 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9ae73620-e7d2-4efb-85d4-7240269367ea) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7deb2ad1bec79a4282bb7d8cd8710a2a02ea4305/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 90 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/038bf9cb-03de-41cf-be09-3a3b918a0113) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7deb2ad1bec79a4282bb7d8cd8710a2a02ea4305/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 91 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d8e4933f-7636-411a-9d12-e129fe89e29d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7deb2ad1bec79a4282bb7d8cd8710a2a02ea4305/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/54ab66fd-30e8-4da0-b598-3d35adc91f77) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/share-to-teams-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7deb2ad1bec79a4282bb7d8cd8710a2a02ea4305/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshare-to-teams-overview.md) | 94 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a6db2206-8f9e-484f-9d0a-592b6d845e7a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/shared-channels.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7deb2ad1bec79a4282bb7d8cd8710a2a02ea4305/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshared-channels.md) | 92 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f066bb04-4a57-48d2-992e-8b4f5c4c4c4c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/teams-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7deb2ad1bec79a4282bb7d8cd8710a2a02ea4305/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fteams-developer-portal.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7a314278-3498-40b2-80c6-a2f43ccab948) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7deb2ad1bec79a4282bb7d8cd8710a2a02ea4305/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 97 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1f72488f-5ac8-455e-9d7d-0c386fb72b27) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7deb2ad1bec79a4282bb7d8cd8710a2a02ea4305/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-publish-overview.md) | 94 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4cf30f96-ffd6-4ef7-bd20-b98cb48a311b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7deb2ad1bec79a4282bb7d8cd8710a2a02ea4305/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/618f1f2b-7091-42dd-a05e-1957f46f1873) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](htt [...]

2024-07-16 10:13 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/37d4ddd78fdd7020c021033822b68bf578c410f1/msteams-platform%2FTOC.yml) | 97 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6ffe9c79-10f7-4aba-a0af-cb45e1029059) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/37d4ddd78fdd7020c021033822b68bf578c410f1/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 86 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/658f0c68-8bd7-4941-b135-7fcffe82f04c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/37d4ddd78fdd7020c021033822b68bf578c410f1/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 92 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4d1069ff-9003-42dc-9ebe-94d1bf9ec6ac) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/37d4ddd78fdd7020c021033822b68bf578c410f1/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 90 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3c4271bb-c6fe-44d9-80d2-b32b129a259e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/37d4ddd78fdd7020c021033822b68bf578c410f1/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 86 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0f4cd54d-b8d8-42e9-b6e9-869b2c62b060) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bot-messages-ai-generated-content.md](https://github.com/MicrosoftDocs/msteams-docs/blob/37d4ddd78fdd7020c021033822b68bf578c410f1/msteams-platform%2Fbots%2Fhow-to%2Fbot-messages-ai-generated-content.md) | 96 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a6dd0a2e-deff-4079-b2a4-70868bff5398) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/37d4ddd78fdd7020c021033822b68bf578c410f1/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 81 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/314611a0-6576-4790-a2b4-06babd12c2c1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/37d4ddd78fdd7020c021033822b68bf578c410f1/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 89 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a330220a-0bca-46cb-938c-103e89d46820) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/37d4ddd78fdd7020c021033822b68bf578c410f1/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2ddb59b2-c13d-4f1c-91ac-c6307586ff35) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/37d4ddd78fdd7020c021033822b68bf578c410f1/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 91 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7e357fe3-f4e6-419f-af82-bbcb1cba34bc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/37d4ddd78fdd7020c021033822b68bf578c410f1/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 90 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4c97bf08-cdea-4261-af73-80ad62095253) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/37d4ddd78fdd7020c021033822b68bf578c410f1/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 91 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bbe4e9da-e79e-4740-9bfd-212a8a50344f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/37d4ddd78fdd7020c021033822b68bf578c410f1/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/772376a1-6487-4695-bced-09662bbba04f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/share-to-teams-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/37d4ddd78fdd7020c021033822b68bf578c410f1/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshare-to-teams-overview.md) | 94 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/85d6f5cb-f1d3-4340-a3ce-afaec92880a6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/shared-channels.md](https://github.com/MicrosoftDocs/msteams-docs/blob/37d4ddd78fdd7020c021033822b68bf578c410f1/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshared-channels.md) | 92 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/534541d7-d727-40e2-b015-6d2b4294d9e2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/teams-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/37d4ddd78fdd7020c021033822b68bf578c410f1/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fteams-developer-portal.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/85688d58-78fd-4d49-a6e4-96204fb10a97) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/37d4ddd78fdd7020c021033822b68bf578c410f1/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 97 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/df9e12ec-6b9d-4c34-8d94-2c696364a56e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/37d4ddd78fdd7020c021033822b68bf578c410f1/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-publish-overview.md) | 94 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/408ac7c1-a0c8-4c62-b0ab-00f456ea8518) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/37d4ddd78fdd7020c021033822b68bf578c410f1/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/788fbeb7-6c92-4a32-84c7-07777aadad00) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](htt [...]

2024-07-16 10:30 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/5a76f5e085511b5d03e2e6590c395053212d9790/msteams-platform%2FTOC.yml) | 97 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/158f76f5-e130-4c9a-8d84-67fbde9d3796) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5a76f5e085511b5d03e2e6590c395053212d9790/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 86 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8e00ae1c-e7a0-4959-bd9f-657c3bef87c0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5a76f5e085511b5d03e2e6590c395053212d9790/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 92 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fd9c2a30-8a2e-485f-85e2-f32817c7362c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5a76f5e085511b5d03e2e6590c395053212d9790/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 90 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a023ab3b-2935-4d8c-8014-feb34a603764) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5a76f5e085511b5d03e2e6590c395053212d9790/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 86 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0a30a1ae-8898-4f35-b0ff-1cf1c61160bd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bot-messages-ai-generated-content.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5a76f5e085511b5d03e2e6590c395053212d9790/msteams-platform%2Fbots%2Fhow-to%2Fbot-messages-ai-generated-content.md) | 96 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/df10a5f9-0a20-4da3-a51c-691e7511a640) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5a76f5e085511b5d03e2e6590c395053212d9790/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 81 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b8a6ac50-3fa6-41c0-83e6-b36478f9891a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5a76f5e085511b5d03e2e6590c395053212d9790/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 89 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c8d5cb41-dffd-4aaf-bf56-1fd828b51dc7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5a76f5e085511b5d03e2e6590c395053212d9790/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/10f331c7-13ec-40d7-8eea-8c490b887966) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5a76f5e085511b5d03e2e6590c395053212d9790/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 91 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5daf4d92-a118-4b2e-bc56-97e71f762dae) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5a76f5e085511b5d03e2e6590c395053212d9790/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 90 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fcd5a065-3711-4ee5-8d49-176fd352f851) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5a76f5e085511b5d03e2e6590c395053212d9790/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 91 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/09c9e05b-fea9-462f-ba59-2906cb3d02f8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5a76f5e085511b5d03e2e6590c395053212d9790/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bd814152-4d77-4cb5-b19b-b3871076c62c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/share-to-teams-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5a76f5e085511b5d03e2e6590c395053212d9790/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshare-to-teams-overview.md) | 94 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0532f7dc-f8e0-488d-8da5-87660fac4f14) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/shared-channels.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5a76f5e085511b5d03e2e6590c395053212d9790/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshared-channels.md) | 92 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c2fa158b-3a76-46bb-8ec3-0b468754e2cc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/teams-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5a76f5e085511b5d03e2e6590c395053212d9790/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fteams-developer-portal.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b37ca5cc-f0c3-4299-b4ac-385de4189584) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5a76f5e085511b5d03e2e6590c395053212d9790/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 97 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fd8475af-61ea-4c6a-904a-014d5adcfb15) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5a76f5e085511b5d03e2e6590c395053212d9790/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-publish-overview.md) | 94 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/72dfebbc-c425-43b8-94c4-79ab2d89695b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5a76f5e085511b5d03e2e6590c395053212d9790/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d107df66-8298-426a-9500-702fc2ebb09c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](htt [...]

2024-07-29 17:12 UTC, jk-msft submitted a review, later dismissed

2024-07-30 21:49 UTC, RamjotSingh submitted a review, later dismissed

2024-07-31 14:07 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/fc904eb5b24770a77347713143336e2871b5e2b3/msteams-platform%2FTOC.yml) | 97 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3b830da9-f464-470b-89b2-d8ebb86204d0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fc904eb5b24770a77347713143336e2871b5e2b3/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 86 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ede0da7e-bfe0-4843-a5e4-c418d181ab30) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fc904eb5b24770a77347713143336e2871b5e2b3/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 92 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cc9fc398-f914-4157-bd02-2bd491bbea9e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fc904eb5b24770a77347713143336e2871b5e2b3/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 90 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5c9d8b98-61b0-4aeb-9cb6-ce8515ea9a4a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fc904eb5b24770a77347713143336e2871b5e2b3/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 86 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e01e15ac-8109-4289-8e04-74bb4e70c438) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bot-messages-ai-generated-content.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fc904eb5b24770a77347713143336e2871b5e2b3/msteams-platform%2Fbots%2Fhow-to%2Fbot-messages-ai-generated-content.md) | 96 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e1f0b000-8a8d-4db1-bd64-088828d8c789) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fc904eb5b24770a77347713143336e2871b5e2b3/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 81 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3b60e330-e6d4-4451-9520-d77aed37c6d3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fc904eb5b24770a77347713143336e2871b5e2b3/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 89 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1991fa0d-5d2b-430e-bc75-bad545eb94ea) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fc904eb5b24770a77347713143336e2871b5e2b3/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ff32317e-ab6f-4c52-a8eb-165e7745b036) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fc904eb5b24770a77347713143336e2871b5e2b3/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 91 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/beddacab-c981-4772-b8eb-2de15abaf032) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fc904eb5b24770a77347713143336e2871b5e2b3/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 90 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/61466bd4-44bb-4fa7-a541-3c69a304b0fe) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fc904eb5b24770a77347713143336e2871b5e2b3/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 91 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6d9cdf60-522e-4f9f-a762-bc541095cc14) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fc904eb5b24770a77347713143336e2871b5e2b3/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 91 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/076052ae-f879-4956-aa4a-8478e207dccc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/share-to-teams-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fc904eb5b24770a77347713143336e2871b5e2b3/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshare-to-teams-overview.md) | 94 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/96b79d10-fd74-49a1-a0d4-a82ad5aa800e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/shared-channels.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fc904eb5b24770a77347713143336e2871b5e2b3/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshared-channels.md) | 92 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a2f65252-8dba-4d48-b631-24fc7fd98c44) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/teams-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fc904eb5b24770a77347713143336e2871b5e2b3/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fteams-developer-portal.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/efce6d1c-62ad-47c4-ae5b-c8bb9591f620) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fc904eb5b24770a77347713143336e2871b5e2b3/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 97 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c0ff46c3-9319-4f39-a390-d7c4a933c979) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fc904eb5b24770a77347713143336e2871b5e2b3/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-publish-overview.md) | 94 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fe551ede-1edd-40a8-a4b6-f173a9760050) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fc904eb5b24770a77347713143336e2871b5e2b3/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5eb6c932-d67b-4349-8614-3fbc905e2cef) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](htt [...]

2024-07-31 14:18 UTC, rkquach submitted a review, later dismissed

2024-08-02 18:19 UTC, subray2014 approved these changes

2024-08-06 10:50 UTC, Wajeed-msft approved these changes

2024-08-21 14:33 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/4474c370918d97671d0a5c79c1f3ab86aaccaad7/msteams-platform%2FTOC.yml) | 92 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/10c0a6bb-5fba-433d-bfbc-b3cfe5b6da18) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4474c370918d97671d0a5c79c1f3ab86aaccaad7/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 86 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/299ab330-f084-465d-bef1-bd4807a416d8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4474c370918d97671d0a5c79c1f3ab86aaccaad7/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 92 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/222d7e0f-950e-443c-b462-5723cd2135dd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4474c370918d97671d0a5c79c1f3ab86aaccaad7/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/500c1d34-3d7a-48b3-96e7-c7bb214a1bbe) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4474c370918d97671d0a5c79c1f3ab86aaccaad7/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 86 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e08abd83-0857-4291-bc54-0c023ffbcb9d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bot-messages-ai-generated-content.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4474c370918d97671d0a5c79c1f3ab86aaccaad7/msteams-platform%2Fbots%2Fhow-to%2Fbot-messages-ai-generated-content.md) | 96 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9284dd08-3358-46cd-82d5-721cb7a27b4b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4474c370918d97671d0a5c79c1f3ab86aaccaad7/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 81 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/81b63ded-c956-4e37-89c4-d35f031e9f35) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4474c370918d97671d0a5c79c1f3ab86aaccaad7/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 90 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8f9eb7f6-0112-4488-a29a-6c0d54dea900) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4474c370918d97671d0a5c79c1f3ab86aaccaad7/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/112fd89d-e077-4599-8835-47ef6d62dc54) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4474c370918d97671d0a5c79c1f3ab86aaccaad7/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 91 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/04595423-7de5-43d8-90cd-a7026faee75b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4474c370918d97671d0a5c79c1f3ab86aaccaad7/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 90 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/336c48af-a2db-4266-b1a1-86dcbe119c1e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4474c370918d97671d0a5c79c1f3ab86aaccaad7/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 91 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/236b2ca9-a913-4c06-b91f-446dedfa76ea) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4474c370918d97671d0a5c79c1f3ab86aaccaad7/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 90 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/817d10c4-db17-455a-8d41-73a0bf2e9a17) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/share-to-teams-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4474c370918d97671d0a5c79c1f3ab86aaccaad7/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshare-to-teams-overview.md) | 94 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a953037d-7b63-441a-809c-fba50c781834) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/shared-channels.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4474c370918d97671d0a5c79c1f3ab86aaccaad7/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshared-channels.md) | 85 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d6963d38-0910-45ab-a64f-045e0ed66dce) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/teams-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4474c370918d97671d0a5c79c1f3ab86aaccaad7/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fteams-developer-portal.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7b027724-1840-437a-9113-46396e2d2f00) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4474c370918d97671d0a5c79c1f3ab86aaccaad7/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 95 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f29db6a7-6322-4edd-92d0-208b72169fbc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4474c370918d97671d0a5c79c1f3ab86aaccaad7/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-publish-overview.md) | 94 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/726c17ac-d76b-4fb1-9de8-0e8991a12131) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4474c370918d97671d0a5c79c1f3ab86aaccaad7/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/373022d1-4375-4b5e-a3eb-a8927c490f6a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](htt [...]

2024-08-21 17:38 UTC, rm3f submitted a review, later dismissed

2024-08-29 11:32 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/baba60aefca5b75d0a0202099270b2fb927376e3/msteams-platform%2FTOC.yml) | 91 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/db2ceda4-1cf1-414d-b261-54fa7f4a0d2e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/baba60aefca5b75d0a0202099270b2fb927376e3/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 86 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/385e51c1-e65c-4403-911a-0dfa0f78cf9b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/baba60aefca5b75d0a0202099270b2fb927376e3/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 92 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fbdcf3b7-b6ee-4a98-bae5-eac108757436) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/baba60aefca5b75d0a0202099270b2fb927376e3/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f8ea8445-1b73-45fa-8d2f-75628a97406a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/baba60aefca5b75d0a0202099270b2fb927376e3/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 86 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d1c237a5-4f07-4d2f-b46f-d313f0b56efe) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bot-messages-ai-generated-content.md](https://github.com/MicrosoftDocs/msteams-docs/blob/baba60aefca5b75d0a0202099270b2fb927376e3/msteams-platform%2Fbots%2Fhow-to%2Fbot-messages-ai-generated-content.md) | 96 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1f9acd39-fc47-4b7d-a054-ffaeaba35755) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/baba60aefca5b75d0a0202099270b2fb927376e3/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 81 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a223e329-9e36-4acb-b47b-2f52b22f352b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/baba60aefca5b75d0a0202099270b2fb927376e3/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 90 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1f56802a-603f-425e-be41-fa5022b23cb3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/baba60aefca5b75d0a0202099270b2fb927376e3/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ee20a8fc-12ab-478a-88ff-8040cd94e378) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/baba60aefca5b75d0a0202099270b2fb927376e3/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 91 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3485eb89-5c93-48f6-bc61-ac700c1e1302) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/baba60aefca5b75d0a0202099270b2fb927376e3/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 90 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/11099c8f-56aa-4e6e-a93b-0e54babdef9c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/baba60aefca5b75d0a0202099270b2fb927376e3/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 91 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/67a317b2-3111-4086-a58c-0f0cebbe52e3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/baba60aefca5b75d0a0202099270b2fb927376e3/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 90 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c0777fc2-9c66-423e-8922-67e061cf306e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/share-to-teams-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/baba60aefca5b75d0a0202099270b2fb927376e3/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshare-to-teams-overview.md) | 94 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/241f43f2-810a-49fb-be82-672b3039c41e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/shared-channels.md](https://github.com/MicrosoftDocs/msteams-docs/blob/baba60aefca5b75d0a0202099270b2fb927376e3/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshared-channels.md) | 85 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8c301b11-302d-4b0c-a052-22715a0f0bbf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/teams-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/baba60aefca5b75d0a0202099270b2fb927376e3/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fteams-developer-portal.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/471e5aab-92ec-420d-9915-2e760102040b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/baba60aefca5b75d0a0202099270b2fb927376e3/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 95 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c5dedef5-19d9-4f6c-a445-804f303c644d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/baba60aefca5b75d0a0202099270b2fb927376e3/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-publish-overview.md) | 94 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f51f1505-139f-4146-ac0c-9be7cf9a6b78) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/baba60aefca5b75d0a0202099270b2fb927376e3/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4fa6374e-4efd-4035-acd4-c0ab635fc4b1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](htt [...]

2024-11-05 06:29 UTC, ramindarS submitted a review, later dismissed

2024-11-28 09:47 UTC, v-deabira submitted a review, later dismissed

2024-12-04 06:19 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1c982da0fd0fcf9ac0f32fbeb55b2f7d7ce08a67/msteams-platform%2FTOC.yml) | 91 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ac8b18ba-1213-484e-b084-fae03cf87627) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1c982da0fd0fcf9ac0f32fbeb55b2f7d7ce08a67/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 86 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4bdeef1c-d004-4e30-add6-f76e49e9b805) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1c982da0fd0fcf9ac0f32fbeb55b2f7d7ce08a67/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 92 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/123bcaa7-46dc-4b74-a816-c4496395343e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1c982da0fd0fcf9ac0f32fbeb55b2f7d7ce08a67/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/81c1e281-073e-43d5-8bf0-0ea84747b77a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1c982da0fd0fcf9ac0f32fbeb55b2f7d7ce08a67/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 86 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a26b52cd-b01a-483c-83a2-df434fe1d2f5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1c982da0fd0fcf9ac0f32fbeb55b2f7d7ce08a67/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 81 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/28cdcc9f-6e0b-4bce-9168-c915666470ef) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1c982da0fd0fcf9ac0f32fbeb55b2f7d7ce08a67/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 88 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c404205b-dd5b-4a80-b2f4-6895ce174a42) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1c982da0fd0fcf9ac0f32fbeb55b2f7d7ce08a67/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4432c8c8-bece-485b-9105-a03cc19b3aa3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1c982da0fd0fcf9ac0f32fbeb55b2f7d7ce08a67/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 91 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6090b88a-bc4e-4e5e-84a8-2e3b13339795) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1c982da0fd0fcf9ac0f32fbeb55b2f7d7ce08a67/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 88 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/06bf63e7-8056-4d09-90f4-e27798a2eb44) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1c982da0fd0fcf9ac0f32fbeb55b2f7d7ce08a67/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 91 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/916247f8-ddf1-47cb-bb88-eef1989f66c5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1c982da0fd0fcf9ac0f32fbeb55b2f7d7ce08a67/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 90 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fd97a6de-49de-4fd6-8cfe-3a8193334ecd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/share-to-teams-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1c982da0fd0fcf9ac0f32fbeb55b2f7d7ce08a67/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshare-to-teams-overview.md) | 95 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a12ceded-976a-4396-8ab6-a5e6ced7ad50) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/shared-channels.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1c982da0fd0fcf9ac0f32fbeb55b2f7d7ce08a67/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshared-channels.md) | 85 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c6c195c1-0979-4b9a-8d7f-d7435b2903b4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/teams-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1c982da0fd0fcf9ac0f32fbeb55b2f7d7ce08a67/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fteams-developer-portal.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4d5ea2d0-6581-457f-8f6e-712c030b0e12) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1c982da0fd0fcf9ac0f32fbeb55b2f7d7ce08a67/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 95 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bb28b36d-a5f7-4851-b93a-4949b996daa3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1c982da0fd0fcf9ac0f32fbeb55b2f7d7ce08a67/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-publish-overview.md) | 94 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/987c0d80-adc7-4f04-b142-8455185fee0e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1c982da0fd0fcf9ac0f32fbeb55b2f7d7ce08a67/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f5b82559-8f98-41db-9321-3e10312df38b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1c982da0fd0fcf9ac0f32fbeb55b2f7d7ce08a67/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fsubmission-checklist.md) | 88 | 46 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e8703765-ce89-4f53-8719-95011d248c49) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/sovereign-cloud.md [...]

2025-01-03 17:31 UTC, papatneMS approved these changes

2025-01-07 06:29 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/5738b2573ba3df4de3cadf0b377e7fab973724e1/msteams-platform%2FTOC.yml) | 92 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/51762ff6-a7a0-4b94-be6d-482e47c604b5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5738b2573ba3df4de3cadf0b377e7fab973724e1/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 86 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/36bf5929-1007-4599-9c13-32feead8b903) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5738b2573ba3df4de3cadf0b377e7fab973724e1/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 88 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a32e0e85-a18c-4c59-bf6b-8d277fda59a5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5738b2573ba3df4de3cadf0b377e7fab973724e1/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d74e55b0-e697-472b-b5ff-a2505566d64c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5738b2573ba3df4de3cadf0b377e7fab973724e1/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 87 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ac2b4705-fd2a-461c-b0ab-42b2d38c39e4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5738b2573ba3df4de3cadf0b377e7fab973724e1/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 81 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/60ec83a4-c3ad-4645-8084-8a6ac041cf73) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5738b2573ba3df4de3cadf0b377e7fab973724e1/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 86 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/593bb2c4-bcda-4bc3-ae00-a36dd1fa564c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5738b2573ba3df4de3cadf0b377e7fab973724e1/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/19d5a31d-91f2-4e5c-b678-3a925f5e2925) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5738b2573ba3df4de3cadf0b377e7fab973724e1/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 90 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/450c240c-c420-4882-a0c7-a575139a3576) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5738b2573ba3df4de3cadf0b377e7fab973724e1/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 91 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6032146e-5ff8-47f4-816b-70d53d017bc8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5738b2573ba3df4de3cadf0b377e7fab973724e1/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 89 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f886566e-6570-4f64-96cc-a8dbc5eef843) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/shared-channels.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5738b2573ba3df4de3cadf0b377e7fab973724e1/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshared-channels.md) | 84 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ad8c376e-7d1f-440e-b259-a9910b2ac833) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/teams-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5738b2573ba3df4de3cadf0b377e7fab973724e1/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fteams-developer-portal.md) | 89 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/73e66495-7345-4d85-9f1a-562d6844cf49) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5738b2573ba3df4de3cadf0b377e7fab973724e1/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 95 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9abcc1c2-0b32-4423-ac81-bda754356bf1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5738b2573ba3df4de3cadf0b377e7fab973724e1/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-publish-overview.md) | 94 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/96204b15-81c4-4bae-8fcc-779c61266476) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5738b2573ba3df4de3cadf0b377e7fab973724e1/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/98aa6fb7-5af9-47ac-a69c-91f401e3c540) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5738b2573ba3df4de3cadf0b377e7fab973724e1/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fsubmission-checklist.md) | 87 | 48 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/86dba2fa-d418-4857-87f4-4a44511a1067) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/sovereign-cloud.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5738b2573ba3df4de3cadf0b377e7fab973724e1/msteams-platform%2Fconcepts%2Fsovereign-cloud.md) | 91 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d8f983b1-b953-410c-9b47-d0a493aeb915) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5738b2573ba3df4de3cadf0b377e7fab973724e1/msteams-platform%2Fget-started%2Fglossary.md) | 89 | 97 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/22e2adff-50c4-496e-bb8d-073e141c69ee) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/what-are-messaging-extensions.md](https://github.c [...]

2025-01-07 08:01 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/08163187380f9e0de7dcf48dacb157f6ce9af18b/msteams-platform%2FTOC.yml) | 92 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9a6df5e4-d9d7-4b63-9cf1-797c51a05d9a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/08163187380f9e0de7dcf48dacb157f6ce9af18b/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 86 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0e7f4dae-fe7a-45f7-b3bf-a0d819a8d6b0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/08163187380f9e0de7dcf48dacb157f6ce9af18b/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 88 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c838e8f1-3b1b-4dcc-95f0-9fb692e6ddfb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/08163187380f9e0de7dcf48dacb157f6ce9af18b/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f2ae8a30-bbbf-4bfc-b6f8-3530de095449) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/08163187380f9e0de7dcf48dacb157f6ce9af18b/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 87 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/93a4b287-e2a3-4698-a8da-0c073caeea20) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/08163187380f9e0de7dcf48dacb157f6ce9af18b/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 81 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/437e6c56-ab5e-480d-99c3-31aea4868460) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/08163187380f9e0de7dcf48dacb157f6ce9af18b/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 86 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a0ff578e-3774-4f7c-acc9-1068ca121f1a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/08163187380f9e0de7dcf48dacb157f6ce9af18b/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/671d2c0a-ffeb-417e-8665-bb49e5e55f6d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/08163187380f9e0de7dcf48dacb157f6ce9af18b/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 90 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/813fc13f-9bb2-424d-9d64-4d65be3abdc5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/08163187380f9e0de7dcf48dacb157f6ce9af18b/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 91 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dbc6a1a7-709c-46d1-ba20-4f1f9b9096ac) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/08163187380f9e0de7dcf48dacb157f6ce9af18b/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 89 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c939816e-3399-4777-b463-881920cd2f1b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/shared-channels.md](https://github.com/MicrosoftDocs/msteams-docs/blob/08163187380f9e0de7dcf48dacb157f6ce9af18b/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshared-channels.md) | 84 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a5e39de2-c327-4774-8d26-280c7d95612d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/teams-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/08163187380f9e0de7dcf48dacb157f6ce9af18b/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fteams-developer-portal.md) | 89 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8f631184-c285-474c-bef3-172667545e23) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/08163187380f9e0de7dcf48dacb157f6ce9af18b/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 95 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/512c75ea-e89d-461f-a4c2-b6c872a5c412) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/08163187380f9e0de7dcf48dacb157f6ce9af18b/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-publish-overview.md) | 94 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f3ec8db6-8b8d-4485-a777-7a8eda1d0b7b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/08163187380f9e0de7dcf48dacb157f6ce9af18b/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/de944c45-406c-4535-af62-4ab30ab15ed2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/08163187380f9e0de7dcf48dacb157f6ce9af18b/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fsubmission-checklist.md) | 87 | 48 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/131c91c5-2862-48c4-92cb-e02ad183ec79) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/sovereign-cloud.md](https://github.com/MicrosoftDocs/msteams-docs/blob/08163187380f9e0de7dcf48dacb157f6ce9af18b/msteams-platform%2Fconcepts%2Fsovereign-cloud.md) | 91 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3c9b2377-405e-45e9-9097-52603774921b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/08163187380f9e0de7dcf48dacb157f6ce9af18b/msteams-platform%2Fget-started%2Fglossary.md) | 89 | 97 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d4e0fa11-de66-4a12-a36e-68dfc294d71b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/what-are-messaging-extensions.md](https://github.c [...]

2025-01-07 10:26 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/dae61707a3d1738ab001afde84f8c5008c76b6ef/msteams-platform%2FTOC.yml) | 92 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9e5c0b7e-eb4e-4635-97d4-fde57a817a2f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dae61707a3d1738ab001afde84f8c5008c76b6ef/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 86 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4d316033-cfc0-4fd6-bd94-77c896db810b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dae61707a3d1738ab001afde84f8c5008c76b6ef/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) |   |   | [link]( ) | [:warning:](# "Could not check with Acrolinx&#10;Please close and reopen pull request") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dae61707a3d1738ab001afde84f8c5008c76b6ef/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/62e1a034-1ff9-4c12-b9a2-e7d89477996d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dae61707a3d1738ab001afde84f8c5008c76b6ef/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 87 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/68af4468-c4e1-493c-b1f0-56c826f5f384) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bot-messages-ai-generated-content.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dae61707a3d1738ab001afde84f8c5008c76b6ef/msteams-platform%2Fbots%2Fhow-to%2Fbot-messages-ai-generated-content.md) | 92 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/874866a4-c048-47cf-91ee-d882f180398b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dae61707a3d1738ab001afde84f8c5008c76b6ef/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 81 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2de9ff4a-1bf4-4485-88eb-f05758fbd229) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dae61707a3d1738ab001afde84f8c5008c76b6ef/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 86 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/676a5d8a-adf4-4229-87c0-fb191e937823) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dae61707a3d1738ab001afde84f8c5008c76b6ef/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/774ce6c6-6f16-485f-b1a3-47c94ce29fb0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dae61707a3d1738ab001afde84f8c5008c76b6ef/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 90 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3c4d8986-a641-4d75-b145-51cc6bcdfb17) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dae61707a3d1738ab001afde84f8c5008c76b6ef/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 91 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7840f74b-9fe2-4853-a005-02c3ef305df8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dae61707a3d1738ab001afde84f8c5008c76b6ef/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 89 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ec3ad61d-bd01-4ece-b785-5ee0f0e70ccc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/shared-channels.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dae61707a3d1738ab001afde84f8c5008c76b6ef/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshared-channels.md) | 84 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e5550daf-ea15-4ca6-ab03-d4a056c9fa6c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/teams-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dae61707a3d1738ab001afde84f8c5008c76b6ef/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fteams-developer-portal.md) | 89 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/21805df4-7cd6-4a6e-8303-73308e255d76) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dae61707a3d1738ab001afde84f8c5008c76b6ef/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 95 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/496196c6-a3a4-483a-bb0a-75a962fa1007) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dae61707a3d1738ab001afde84f8c5008c76b6ef/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-publish-overview.md) | 94 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/acd19b1a-810d-4bb4-b9b9-be1d23c894aa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dae61707a3d1738ab001afde84f8c5008c76b6ef/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6d0091c5-4665-45c6-b51e-d633a4967109) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dae61707a3d1738ab001afde84f8c5008c76b6ef/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fsubmission-checklist.md) | 87 | 48 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e173de84-2bd5-49eb-a6ef-cc55bee1f7e4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/sovereign-cloud.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dae61707a3d1738ab001afde84f8c5008c76b6ef/msteams-platform%2Fconcepts%2Fsovereign-cloud.md) | 91 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/476feafa-fdbb-40d0-9970-559509c6b224) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dae61707 [...]

2025-01-07 10:49 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/0f12a7141871e8fd41d6303ba560bc98dd20352f/msteams-platform%2FTOC.yml) | 92 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0f9a757b-572d-4e34-9e3c-9a92b84a3454) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0f12a7141871e8fd41d6303ba560bc98dd20352f/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 86 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/21fd1dc4-4006-478b-bfa5-09a7a37b248e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0f12a7141871e8fd41d6303ba560bc98dd20352f/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 88 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e435d10d-e943-4b76-bdb0-6cf6a4fce432) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0f12a7141871e8fd41d6303ba560bc98dd20352f/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cb848103-11a3-4e71-b4b4-1b9a0a0bb073) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0f12a7141871e8fd41d6303ba560bc98dd20352f/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 87 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6c91655c-44bb-490d-844f-6a24a8efa421) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bot-messages-ai-generated-content.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0f12a7141871e8fd41d6303ba560bc98dd20352f/msteams-platform%2Fbots%2Fhow-to%2Fbot-messages-ai-generated-content.md) | 92 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/56110d29-59e9-4b73-8138-3c2bb60ee651) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0f12a7141871e8fd41d6303ba560bc98dd20352f/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 81 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/63eb2c36-6575-4321-ac0b-d75ea21b06d0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0f12a7141871e8fd41d6303ba560bc98dd20352f/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 86 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4375a9fe-ebe1-4d89-87fb-6a7be30b3d96) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0f12a7141871e8fd41d6303ba560bc98dd20352f/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2c881332-2b13-4335-9701-e1e6344946f1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0f12a7141871e8fd41d6303ba560bc98dd20352f/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 90 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/892c710c-4622-4e60-99aa-95cd725f8f58) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0f12a7141871e8fd41d6303ba560bc98dd20352f/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 91 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0b821a6d-e839-4c1f-947f-f8ab5da6da78) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0f12a7141871e8fd41d6303ba560bc98dd20352f/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 89 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/97fbae69-bbc6-42f2-bf44-236de73b5385) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/shared-channels.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0f12a7141871e8fd41d6303ba560bc98dd20352f/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshared-channels.md) | 84 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e050a242-0bb8-4df4-b89d-438d1e4760f4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/teams-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0f12a7141871e8fd41d6303ba560bc98dd20352f/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fteams-developer-portal.md) | 89 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9b671cfa-4815-4ee2-9d36-522874c7ffce) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0f12a7141871e8fd41d6303ba560bc98dd20352f/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 95 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6f561daf-b23e-4fdc-be48-4ddb99166cea) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0f12a7141871e8fd41d6303ba560bc98dd20352f/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-publish-overview.md) | 94 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/215a2cf3-436e-4add-b627-8f90db7e5e6b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0f12a7141871e8fd41d6303ba560bc98dd20352f/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e7b7c4b6-2ccf-4db8-8927-93d3b21bbd15) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0f12a7141871e8fd41d6303ba560bc98dd20352f/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fsubmission-checklist.md) | 87 | 48 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8f40247b-6d20-4be0-a771-c3e86a8e3d82) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/sovereign-cloud.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0f12a7141871e8fd41d6303ba560bc98dd20352f/msteams-platform%2Fconcepts%2Fsovereign-cloud.md) | 91 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9930af18-2d73-43f7-988f-da6b89da090d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossar [...]

2025-01-07 12:57 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e5de7ac50ca77a0da3f2483f3e205ff7d69b1f02/msteams-platform%2FTOC.yml) | 92 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/91dc131b-e0cf-4c01-9196-f7c9640ba55e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e5de7ac50ca77a0da3f2483f3e205ff7d69b1f02/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/79c76cc5-24b1-407c-911d-3591e4f843de) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e5de7ac50ca77a0da3f2483f3e205ff7d69b1f02/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 90 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/19796199-3c0f-4b64-9bdf-7b0afc138992) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e5de7ac50ca77a0da3f2483f3e205ff7d69b1f02/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9abc36db-a7d0-4d77-b743-f77bafc70a9d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e5de7ac50ca77a0da3f2483f3e205ff7d69b1f02/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 88 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cbb09e53-4a22-4b7e-a73c-875ee7f24f4f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bot-messages-ai-generated-content.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e5de7ac50ca77a0da3f2483f3e205ff7d69b1f02/msteams-platform%2Fbots%2Fhow-to%2Fbot-messages-ai-generated-content.md) | 92 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/db30ac7f-ee58-4137-a473-ca7da92b461e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e5de7ac50ca77a0da3f2483f3e205ff7d69b1f02/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 81 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/28c3dbee-1779-42f7-b761-9a348802efae) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e5de7ac50ca77a0da3f2483f3e205ff7d69b1f02/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 86 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4a121a5d-b0ec-4b6c-bedd-cc5f095c94b6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e5de7ac50ca77a0da3f2483f3e205ff7d69b1f02/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c3bd325a-31d0-4056-8ac3-25827610a5ca) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e5de7ac50ca77a0da3f2483f3e205ff7d69b1f02/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 90 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d4ca296c-34ed-44ec-83f0-411415cd5634) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e5de7ac50ca77a0da3f2483f3e205ff7d69b1f02/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 91 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/73f0d656-f8d6-45d2-bb33-abd269bf3fca) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e5de7ac50ca77a0da3f2483f3e205ff7d69b1f02/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 89 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2f291aef-f8cb-4352-b367-2fceb7622a54) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/shared-channels.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e5de7ac50ca77a0da3f2483f3e205ff7d69b1f02/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshared-channels.md) | 84 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/be754b49-a18c-41a9-957f-9820ed56f9a3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/teams-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e5de7ac50ca77a0da3f2483f3e205ff7d69b1f02/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fteams-developer-portal.md) | 89 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f1ffca21-70c3-4c48-965e-58b6895517fe) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e5de7ac50ca77a0da3f2483f3e205ff7d69b1f02/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 95 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/46c700fe-7f96-4dcd-837c-0f98d9d5c65c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e5de7ac50ca77a0da3f2483f3e205ff7d69b1f02/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-publish-overview.md) | 94 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b4f6779f-c283-47f0-86f4-be97c979fe62) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e5de7ac50ca77a0da3f2483f3e205ff7d69b1f02/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/af6308dc-1c26-4a79-b4a3-daf044cb4c80) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e5de7ac50ca77a0da3f2483f3e205ff7d69b1f02/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fsubmission-checklist.md) | 87 | 48 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2d66bf5f-0b4c-462a-ae76-968db24bae83) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/sovereign-cloud.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e5de7ac50ca77a0da3f2483f3e205ff7d69b1f02/msteams-platform%2Fconcepts%2Fsovereign-cloud.md) | 91 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/872b58fc-94d8-48ca-891b-6931762ecf2b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossar [...]

2025-01-07 13:08 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/55b5a62dbb5a5434fb04bc4a41f3c822ece886fd/msteams-platform%2FTOC.yml) | 92 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8148b7c3-e40d-4d4f-931e-32c8c9c7ba38) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/55b5a62dbb5a5434fb04bc4a41f3c822ece886fd/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/687b51fc-c6c3-48a4-9af2-4006d2e7e8a9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/55b5a62dbb5a5434fb04bc4a41f3c822ece886fd/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 90 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/24cec717-215a-4639-b412-94386f380710) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/55b5a62dbb5a5434fb04bc4a41f3c822ece886fd/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e929568f-1a5e-45e6-ab08-23928aebb5eb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/55b5a62dbb5a5434fb04bc4a41f3c822ece886fd/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 88 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0daaeaf6-07f6-4d23-8c48-bda2eef4a4b4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bot-messages-ai-generated-content.md](https://github.com/MicrosoftDocs/msteams-docs/blob/55b5a62dbb5a5434fb04bc4a41f3c822ece886fd/msteams-platform%2Fbots%2Fhow-to%2Fbot-messages-ai-generated-content.md) | 92 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d1820205-ccd4-4a51-a3d1-cb46cd4c6a5e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/55b5a62dbb5a5434fb04bc4a41f3c822ece886fd/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 81 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/03831797-5731-4029-8fe9-88fd25dc33d1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/55b5a62dbb5a5434fb04bc4a41f3c822ece886fd/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 86 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ad6a9234-ab47-4829-85fe-a5d0fba01f20) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/55b5a62dbb5a5434fb04bc4a41f3c822ece886fd/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/13624056-1e98-4d1f-9b15-bbf02e77f5e1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/55b5a62dbb5a5434fb04bc4a41f3c822ece886fd/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 90 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f78ba010-215e-432c-8853-496ddd00ca36) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/55b5a62dbb5a5434fb04bc4a41f3c822ece886fd/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 91 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fc68f942-f6db-40d9-9b72-33e7e865e95d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/55b5a62dbb5a5434fb04bc4a41f3c822ece886fd/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 89 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2df5dd76-bddc-4f93-8d73-43c8bcc4af0b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/shared-channels.md](https://github.com/MicrosoftDocs/msteams-docs/blob/55b5a62dbb5a5434fb04bc4a41f3c822ece886fd/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshared-channels.md) | 84 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9d764dd6-84b0-440a-aa4c-f64211967d01) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/teams-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/55b5a62dbb5a5434fb04bc4a41f3c822ece886fd/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fteams-developer-portal.md) | 89 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e1a572b1-035b-4291-838e-07abaa514c00) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/55b5a62dbb5a5434fb04bc4a41f3c822ece886fd/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 95 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0a3abaa3-c116-4a74-b6bf-85057d536299) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/55b5a62dbb5a5434fb04bc4a41f3c822ece886fd/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-publish-overview.md) | 94 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6a9928eb-a2c9-4522-959b-3d73b36737b0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/55b5a62dbb5a5434fb04bc4a41f3c822ece886fd/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8d03864f-e703-447d-84ae-cab093771a65) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/55b5a62dbb5a5434fb04bc4a41f3c822ece886fd/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fsubmission-checklist.md) | 87 | 48 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b61041f0-0b52-4606-9b42-1fed3bae9f59) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/sovereign-cloud.md](https://github.com/MicrosoftDocs/msteams-docs/blob/55b5a62dbb5a5434fb04bc4a41f3c822ece886fd/msteams-platform%2Fconcepts%2Fsovereign-cloud.md) | 91 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fd7736ef-3cbc-4dd4-b0e5-c1b30f406681) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossar [...]

2025-01-08 07:12 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/8f3ae41b229c7a4ac77adddde17a73baf7e42aeb/msteams-platform%2FTOC.yml) | 92 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/83ac904a-8aa0-4df3-8efe-321449e4144d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8f3ae41b229c7a4ac77adddde17a73baf7e42aeb/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b86df30f-d58c-42ef-8399-479a301a50c4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8f3ae41b229c7a4ac77adddde17a73baf7e42aeb/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 90 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/611f1afe-dd36-4cde-ad64-930c07870656) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8f3ae41b229c7a4ac77adddde17a73baf7e42aeb/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bc90a047-bf13-4ad2-9c57-cc7efe9602ba) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8f3ae41b229c7a4ac77adddde17a73baf7e42aeb/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 88 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bc726b19-f289-4d51-9d19-db05da8b4ecb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bot-messages-ai-generated-content.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8f3ae41b229c7a4ac77adddde17a73baf7e42aeb/msteams-platform%2Fbots%2Fhow-to%2Fbot-messages-ai-generated-content.md) | 92 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/eda68d98-fffd-4884-b2c4-41b5e64cc8d5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8f3ae41b229c7a4ac77adddde17a73baf7e42aeb/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 81 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/10ef2344-838e-4005-9449-ad68a0a340a2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8f3ae41b229c7a4ac77adddde17a73baf7e42aeb/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 86 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/12891d48-5e67-45e7-b445-4848a59cc7b2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8f3ae41b229c7a4ac77adddde17a73baf7e42aeb/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cc52e0bf-f6dd-4e3e-be28-a92d6080f04e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8f3ae41b229c7a4ac77adddde17a73baf7e42aeb/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 90 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e8bcd6c8-06cd-45a4-af9e-39e8c5800d01) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8f3ae41b229c7a4ac77adddde17a73baf7e42aeb/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 91 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/773aae03-a770-41c1-8a07-29b9fafd2b52) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8f3ae41b229c7a4ac77adddde17a73baf7e42aeb/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 89 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/58863078-838c-4864-af4d-bd3f9b0245d1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/shared-channels.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8f3ae41b229c7a4ac77adddde17a73baf7e42aeb/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshared-channels.md) | 84 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b75ee6aa-2d89-4fea-ba8f-f359e2d45424) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/teams-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8f3ae41b229c7a4ac77adddde17a73baf7e42aeb/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fteams-developer-portal.md) | 89 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ae5cef69-b7b2-4672-b334-284e062cee7a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8f3ae41b229c7a4ac77adddde17a73baf7e42aeb/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 95 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/64bbdc70-b3b0-4e88-be00-01fbee2ecfa3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8f3ae41b229c7a4ac77adddde17a73baf7e42aeb/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-publish-overview.md) | 94 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d04a1feb-1c49-40e6-a680-5cc8454ae794) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8f3ae41b229c7a4ac77adddde17a73baf7e42aeb/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/af3957ca-696e-4645-ad47-f2c97b4676d6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8f3ae41b229c7a4ac77adddde17a73baf7e42aeb/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fsubmission-checklist.md) | 87 | 48 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a59c95e7-9e1b-438e-9692-ee2130204e10) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/sovereign-cloud.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8f3ae41b229c7a4ac77adddde17a73baf7e42aeb/msteams-platform%2Fconcepts%2Fsovereign-cloud.md) | 91 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/01e06b9b-a2ca-479e-8bb0-dfa1dc508d0f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossar [...]

2025-01-21 11:53 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/bf7ebe7b463d1268f4185cd7ecf0a2f6fbcc0cd3/msteams-platform%2FTOC.yml) | 92 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/54f192dc-84ea-4a02-b34a-c37e2e02f36c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bf7ebe7b463d1268f4185cd7ecf0a2f6fbcc0cd3/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7a7816cb-4feb-46a8-ae2d-ea2ab8589b2b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bf7ebe7b463d1268f4185cd7ecf0a2f6fbcc0cd3/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 90 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e6dcf722-fb33-453e-93d2-7a7c608f73de) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bf7ebe7b463d1268f4185cd7ecf0a2f6fbcc0cd3/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3570d5cc-73bd-4269-a44d-9ec76436f773) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bf7ebe7b463d1268f4185cd7ecf0a2f6fbcc0cd3/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 88 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/879c9da0-f187-44b4-834c-bc51e2750a7d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bf7ebe7b463d1268f4185cd7ecf0a2f6fbcc0cd3/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 81 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ec061dec-5ff7-43a5-9271-16a86050d362) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bf7ebe7b463d1268f4185cd7ecf0a2f6fbcc0cd3/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 86 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/99ba5c91-0411-4eb1-a05b-203558770cfa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bf7ebe7b463d1268f4185cd7ecf0a2f6fbcc0cd3/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2ac81a4b-43b7-479b-8c67-98fa44a3d1fd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bf7ebe7b463d1268f4185cd7ecf0a2f6fbcc0cd3/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 90 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7103b051-4a74-4e31-8e2b-27144af8e6e3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bf7ebe7b463d1268f4185cd7ecf0a2f6fbcc0cd3/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 91 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/257a75c0-ac89-48e1-91e6-e461cb1a06f9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bf7ebe7b463d1268f4185cd7ecf0a2f6fbcc0cd3/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 89 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a2764742-81ea-43d3-8010-0a7be414a033) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/shared-channels.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bf7ebe7b463d1268f4185cd7ecf0a2f6fbcc0cd3/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshared-channels.md) | 84 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b8b8859f-02d5-4313-8359-beb338164b07) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/teams-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bf7ebe7b463d1268f4185cd7ecf0a2f6fbcc0cd3/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fteams-developer-portal.md) | 91 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/62d1977b-e5af-4b45-8fe4-f7e78d9dd7e0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bf7ebe7b463d1268f4185cd7ecf0a2f6fbcc0cd3/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 95 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1cd6cb5f-4b2e-4bd2-aef7-7286192fcc8f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bf7ebe7b463d1268f4185cd7ecf0a2f6fbcc0cd3/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-publish-overview.md) | 94 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c5932284-ad4a-419c-9b08-82bc13823577) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bf7ebe7b463d1268f4185cd7ecf0a2f6fbcc0cd3/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fc89f572-e2c2-4467-b12e-9c1211e9bb59) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bf7ebe7b463d1268f4185cd7ecf0a2f6fbcc0cd3/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fsubmission-checklist.md) | 87 | 48 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/55d14b59-f7ce-4a27-a4f2-559217786412) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/sovereign-cloud.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bf7ebe7b463d1268f4185cd7ecf0a2f6fbcc0cd3/msteams-platform%2Fconcepts%2Fsovereign-cloud.md) | 91 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b67599f7-567c-4a49-ac22-2a144ec5c123) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bf7ebe7b463d1268f4185cd7ecf0a2f6fbcc0cd3/msteams-platform%2Fget-started%2Fglossary.md) | 89 | 97 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a42b3fff-b90d-478c-ad79-f9837c452841) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/what-are-messaging-extensions.md](https://github.c [...]

2025-01-21 13:57 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a45dc77227b803551438679a6ac7b467646067a8/msteams-platform%2FTOC.yml) | 92 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/047a82e6-adbd-4ae7-9205-10a786e5e9a8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a45dc77227b803551438679a6ac7b467646067a8/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f5b5577c-0a69-46cc-a70e-e2a014c17bc1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a45dc77227b803551438679a6ac7b467646067a8/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 90 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2cd627f2-18f8-45db-a394-8676c57ab83a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a45dc77227b803551438679a6ac7b467646067a8/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6bb6eb02-477e-4ac7-87d7-ec61be9e1fef) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a45dc77227b803551438679a6ac7b467646067a8/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 88 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/49f86b28-f4fd-4e3e-ad13-767a64541493) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a45dc77227b803551438679a6ac7b467646067a8/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 81 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/784cb8f0-e094-4af5-abdf-3413def113b7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a45dc77227b803551438679a6ac7b467646067a8/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 86 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/35b17de0-5e0d-4099-8fae-eb232aeab5ae) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a45dc77227b803551438679a6ac7b467646067a8/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0c058856-0fdb-4ee1-8ed8-4b23016c29f1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a45dc77227b803551438679a6ac7b467646067a8/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 90 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/095a00d1-f46b-476b-a056-d43881c67419) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a45dc77227b803551438679a6ac7b467646067a8/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 91 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/053003be-5e8d-4a28-9763-7df14dd21e7c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a45dc77227b803551438679a6ac7b467646067a8/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 89 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/48b32aaf-d981-4ad1-99f1-55b483ad89dc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/shared-channels.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a45dc77227b803551438679a6ac7b467646067a8/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshared-channels.md) | 84 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4258cf19-2822-409f-b3a8-68017bd73d22) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/teams-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a45dc77227b803551438679a6ac7b467646067a8/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fteams-developer-portal.md) | 91 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3caf61dd-5307-46f6-abef-bcde2a94fe7e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a45dc77227b803551438679a6ac7b467646067a8/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 95 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/827de5c8-e1da-4036-b6f2-11e538425329) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a45dc77227b803551438679a6ac7b467646067a8/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-publish-overview.md) | 94 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bd7eda4d-a5bd-4071-8b27-94edf23ac29b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a45dc77227b803551438679a6ac7b467646067a8/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a1d6d86f-159a-4bd4-9111-a6c7e73c62b1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a45dc77227b803551438679a6ac7b467646067a8/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fsubmission-checklist.md) | 87 | 48 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a275cc24-3767-4cc5-95d2-0450b9b7a565) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/sovereign-cloud.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a45dc77227b803551438679a6ac7b467646067a8/msteams-platform%2Fconcepts%2Fsovereign-cloud.md) | 91 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/34695d8f-d32c-4ad0-a4e2-08f0ffdad9f4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a45dc77227b803551438679a6ac7b467646067a8/msteams-platform%2Fget-started%2Fglossary.md) | 89 | 97 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/61b28527-9575-4cd1-a429-2259258c7f78) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/what-are-messaging-extensions.md](https://github.c [...]

2025-01-21 14:26 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/f130735682593292cf6caf5662f25460a3c5cc8c/msteams-platform%2FTOC.yml) | 92 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e53a33ce-03a3-4bef-b535-21e6feee2eb8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f130735682593292cf6caf5662f25460a3c5cc8c/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fdcacce1-3dae-4eb8-9e79-fe1b8e6c374b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f130735682593292cf6caf5662f25460a3c5cc8c/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 90 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0dfff52c-feb1-4c45-b253-2aab4a251681) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f130735682593292cf6caf5662f25460a3c5cc8c/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) |   |   | [link]( ) | [:warning:](# "Could not check with Acrolinx&#10;Please close and reopen pull request") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f130735682593292cf6caf5662f25460a3c5cc8c/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 88 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8909396d-3803-46cc-baf2-4b285676322a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f130735682593292cf6caf5662f25460a3c5cc8c/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 81 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2ee6b495-c9dc-4aa1-8ccb-2e7a41c78bad) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f130735682593292cf6caf5662f25460a3c5cc8c/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) |   |   | [link]( ) | [:warning:](# "Could not check with Acrolinx&#10;Please close and reopen pull request") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f130735682593292cf6caf5662f25460a3c5cc8c/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1b8cfe8d-261a-4481-885a-7eb83a0fcdcd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f130735682593292cf6caf5662f25460a3c5cc8c/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) |   |   | [link]( ) | [:warning:](# "Could not check with Acrolinx&#10;Please close and reopen pull request") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f130735682593292cf6caf5662f25460a3c5cc8c/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 91 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/db3bac28-c70d-46fb-9b1e-47c343d3b9c8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f130735682593292cf6caf5662f25460a3c5cc8c/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 89 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5a846542-0270-4006-a228-5ae1f1b3bc73) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/shared-channels.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f130735682593292cf6caf5662f25460a3c5cc8c/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshared-channels.md) | 84 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b469b3aa-e70a-4320-a42e-82efe5e17a67) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/teams-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f130735682593292cf6caf5662f25460a3c5cc8c/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fteams-developer-portal.md) |   |   | [link]( ) | [:warning:](# "Could not check with Acrolinx&#10;Please close and reopen pull request") |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f130735682593292cf6caf5662f25460a3c5cc8c/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 95 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/97135d33-6dd5-4d3f-a341-185b667f06f5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f130735682593292cf6caf5662f25460a3c5cc8c/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-publish-overview.md) | 94 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0dd30cbc-c5da-48dd-ba70-700940420a30) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f130735682593292cf6caf5662f25460a3c5cc8c/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) |   |   | [link]( ) | [:warning:](# "Could not check with Acrolinx&#10;Please close and reopen pull request") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f130735682593292cf6caf5662f25460a3c5cc8c/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fsubmission-checklist.md) | 87 | 48 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/143a0e48-da37-488f-b194-04f8c16c255a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/sovereign-cloud.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f130735682593292cf6caf5662f25460a3c5cc8c/msteams-platform%2Fconcepts%2Fsovereign-cloud.md) | 91 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/822541b2-a79f-4efa-a56f-28adf6bafd00) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f130735682593292cf6caf5662f25460a3c5cc8c/msteams-platform%2Fget-started%2Fglossary.md) | 89 | 97 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b1345c9c-205b-4f6d-84cc-912ced5a7594) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/what-are-messaging-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f130735682593292cf6caf5662f25460a3c5cc8c/msteams-platform%2Fmessaging-extensions%2Fwhat-are-messaging-extensions.md) | 89 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3fae46f0-f840-4e25-835c-9c98f3212918) | [:white_check_mark:](# "Successfully processe [...]

2025-01-21 14:37 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/00dfa95ad7b130b7f8941f86fd834013de8f5a6a/msteams-platform%2FTOC.yml) | 92 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/57f55cd4-2df9-46ed-b764-095162e6e979) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/00dfa95ad7b130b7f8941f86fd834013de8f5a6a/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5c994b47-4826-41f6-8ea0-b60b53909733) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/00dfa95ad7b130b7f8941f86fd834013de8f5a6a/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 90 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/42f3a889-da8b-46d8-82e2-716ac364f1ef) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/00dfa95ad7b130b7f8941f86fd834013de8f5a6a/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4589dd54-3b22-40a4-bed0-541f0653a554) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/00dfa95ad7b130b7f8941f86fd834013de8f5a6a/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 88 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dbfd6cc1-2a3a-40a0-bcd7-9f4ee65093a5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bot-messages-ai-generated-content.md](https://github.com/MicrosoftDocs/msteams-docs/blob/00dfa95ad7b130b7f8941f86fd834013de8f5a6a/msteams-platform%2Fbots%2Fhow-to%2Fbot-messages-ai-generated-content.md) | 94 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4b005497-a0f9-4871-8331-5212c6fd2c78) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/00dfa95ad7b130b7f8941f86fd834013de8f5a6a/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 81 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1ad8249e-760b-4efd-918d-0866dd3ac8e5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/00dfa95ad7b130b7f8941f86fd834013de8f5a6a/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 86 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b7bc1db5-8d30-4beb-b8d7-8bf9ad91fdd3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/00dfa95ad7b130b7f8941f86fd834013de8f5a6a/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f9c8cb95-91bd-42fa-814f-5877ab8ee3e8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/00dfa95ad7b130b7f8941f86fd834013de8f5a6a/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 90 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7133b7fa-9498-41c1-a07d-cee96cf23307) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/00dfa95ad7b130b7f8941f86fd834013de8f5a6a/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 91 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f66e9b39-bdd8-4cdd-b5ca-7ac1041acfc8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/00dfa95ad7b130b7f8941f86fd834013de8f5a6a/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 89 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/97797175-2e94-47eb-806c-20f08c7588e4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/shared-channels.md](https://github.com/MicrosoftDocs/msteams-docs/blob/00dfa95ad7b130b7f8941f86fd834013de8f5a6a/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshared-channels.md) | 84 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ce3a3f0b-fee8-4983-8ec2-ae7a90d062f6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/teams-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/00dfa95ad7b130b7f8941f86fd834013de8f5a6a/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fteams-developer-portal.md) | 91 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d44812cf-b17e-4e24-bc93-3962455f2ff0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/00dfa95ad7b130b7f8941f86fd834013de8f5a6a/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 95 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2ce9bc0d-161f-4cca-ba2e-35381d642d6b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/00dfa95ad7b130b7f8941f86fd834013de8f5a6a/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-publish-overview.md) | 94 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e12d0ddc-8b32-4694-87df-1b8208287e39) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/00dfa95ad7b130b7f8941f86fd834013de8f5a6a/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a6cfd4f2-7656-4157-9d68-54a0ee6a865b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/00dfa95ad7b130b7f8941f86fd834013de8f5a6a/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fsubmission-checklist.md) | 87 | 48 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c7b59695-3f10-4ef9-8a65-0aa7dedc297e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/sovereign-cloud.md](https://github.com/MicrosoftDocs/msteams-docs/blob/00dfa95ad7b130b7f8941f86fd834013de8f5a6a/msteams-platform%2Fconcepts%2Fsovereign-cloud.md) | 91 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5482232f-e46d-447f-9b19-63b8176f5dc8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary [...]

2025-01-23 07:08 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c3d2a62013773c19c3230251af7b960ee9e0fbcc/msteams-platform%2FTOC.yml) | 92 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/04cf6f9b-dbf7-433b-b21c-a4a0d5298eac) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c3d2a62013773c19c3230251af7b960ee9e0fbcc/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1f93e071-cf36-4139-bf66-bbe3ce0d41c8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c3d2a62013773c19c3230251af7b960ee9e0fbcc/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 90 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c57008de-8a9f-46b3-895e-9f990bbf84e3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c3d2a62013773c19c3230251af7b960ee9e0fbcc/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/843a5856-2b5d-40ee-bf62-fb776d51fdc5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c3d2a62013773c19c3230251af7b960ee9e0fbcc/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 88 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/64c6dd64-e34d-49a8-8cb2-fcf9609742a3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bot-messages-ai-generated-content.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c3d2a62013773c19c3230251af7b960ee9e0fbcc/msteams-platform%2Fbots%2Fhow-to%2Fbot-messages-ai-generated-content.md) | 95 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f6014318-e27a-4131-8227-f9b1560e8968) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c3d2a62013773c19c3230251af7b960ee9e0fbcc/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 81 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/341cd6fc-f9c4-42a5-a7ea-15d2df820898) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c3d2a62013773c19c3230251af7b960ee9e0fbcc/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 86 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b1c9960f-3b7c-4338-9679-7767ec3761c0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c3d2a62013773c19c3230251af7b960ee9e0fbcc/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/941e0041-873f-4918-977a-0159605e288b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c3d2a62013773c19c3230251af7b960ee9e0fbcc/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 90 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/976a72c0-3382-4bf9-af8d-669bc43c60d9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c3d2a62013773c19c3230251af7b960ee9e0fbcc/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 91 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dbffb242-3a0b-46c5-9214-e61c32831355) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c3d2a62013773c19c3230251af7b960ee9e0fbcc/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 89 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5473603d-2c0f-4fc3-aaaa-cdf7f190f424) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/shared-channels.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c3d2a62013773c19c3230251af7b960ee9e0fbcc/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshared-channels.md) | 84 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e3a5ae7b-d03f-4f9e-bd6d-1b16d1ab2853) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/teams-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c3d2a62013773c19c3230251af7b960ee9e0fbcc/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fteams-developer-portal.md) | 91 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/651ccbd1-ccc1-42e6-9819-a2f5886de36f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c3d2a62013773c19c3230251af7b960ee9e0fbcc/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 95 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/30ed66bd-604e-44a1-b190-245cea836884) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c3d2a62013773c19c3230251af7b960ee9e0fbcc/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-publish-overview.md) | 94 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1bb495c0-34ca-45c3-b32d-2087128b18cb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c3d2a62013773c19c3230251af7b960ee9e0fbcc/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0d3cfba3-f642-441d-9fa8-baa9bcf829ba) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c3d2a62013773c19c3230251af7b960ee9e0fbcc/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fsubmission-checklist.md) | 87 | 48 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cb9b21e9-f9e3-4f00-91a1-227259c18454) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/sovereign-cloud.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c3d2a62013773c19c3230251af7b960ee9e0fbcc/msteams-platform%2Fconcepts%2Fsovereign-cloud.md) | 91 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d0d9677a-c765-49f5-bb7c-5e8d64ccea9f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary [...]

2025-01-23 10:56 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/2cbe4f0b51dae4642ef292e510824d1b77f1f55f/msteams-platform%2FTOC.yml) | 92 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/96537379-e7e4-4085-95b1-5c5b884b79b1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2cbe4f0b51dae4642ef292e510824d1b77f1f55f/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7662ca66-c982-4378-b7e3-5efa48f71df3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2cbe4f0b51dae4642ef292e510824d1b77f1f55f/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 90 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/334f2513-91af-4825-876b-2a0139b8ea4b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2cbe4f0b51dae4642ef292e510824d1b77f1f55f/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a97919c7-7a8a-4d1f-8569-3282fb782f59) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2cbe4f0b51dae4642ef292e510824d1b77f1f55f/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 88 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0e094b98-03ba-4775-bfcf-b44965271bca) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bot-messages-ai-generated-content.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2cbe4f0b51dae4642ef292e510824d1b77f1f55f/msteams-platform%2Fbots%2Fhow-to%2Fbot-messages-ai-generated-content.md) | 95 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ca743105-8f40-4982-9cf8-fc91e2bef97e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2cbe4f0b51dae4642ef292e510824d1b77f1f55f/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 81 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d5e9d970-eaec-4c08-9489-4781e7f32bc7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2cbe4f0b51dae4642ef292e510824d1b77f1f55f/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 86 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ebf57be3-4928-45cc-8271-c6699cebfcce) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2cbe4f0b51dae4642ef292e510824d1b77f1f55f/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7e881234-f085-4fcc-ab07-b12206fde34d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2cbe4f0b51dae4642ef292e510824d1b77f1f55f/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 90 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0a1e2df5-1102-4556-80cf-6be5a2d20cc7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2cbe4f0b51dae4642ef292e510824d1b77f1f55f/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 91 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f32a6f1d-2730-4c02-82eb-7bd8c7b6100f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2cbe4f0b51dae4642ef292e510824d1b77f1f55f/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 89 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e98e0df6-46a5-4f8d-b831-407d59b70ebe) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/shared-channels.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2cbe4f0b51dae4642ef292e510824d1b77f1f55f/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshared-channels.md) | 84 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2330c244-b783-42e0-95c7-9dda892a0aaf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/teams-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2cbe4f0b51dae4642ef292e510824d1b77f1f55f/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fteams-developer-portal.md) | 91 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/afd70602-a031-4e07-b5fa-e8e8fcefc15a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2cbe4f0b51dae4642ef292e510824d1b77f1f55f/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 95 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/029babcd-cdc3-4e31-ae21-fe9c92cfa84c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2cbe4f0b51dae4642ef292e510824d1b77f1f55f/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-publish-overview.md) | 94 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b957d4f0-fd58-4081-82a5-2714e4dc7026) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2cbe4f0b51dae4642ef292e510824d1b77f1f55f/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2b498da0-b189-4092-afa4-95cbf0acc79f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2cbe4f0b51dae4642ef292e510824d1b77f1f55f/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fsubmission-checklist.md) | 87 | 48 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7ac36be6-d6ce-4fd2-a775-167994793f8d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/sovereign-cloud.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2cbe4f0b51dae4642ef292e510824d1b77f1f55f/msteams-platform%2Fconcepts%2Fsovereign-cloud.md) | 91 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a3a4e869-929a-4378-bc26-e66cfb7143ca) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary [...]

2025-01-23 11:25 UTC, surbhigupta12 approved these changes

2025-01-23 12:58 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/8af07cdffdbdc161709ccd040fedd48e8d0f51ea/msteams-platform%2FTOC.yml) | 92 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/62e763f9-740c-46db-806d-38051b7d7f4d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8af07cdffdbdc161709ccd040fedd48e8d0f51ea/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7acd2419-2b4d-492f-9b57-0c8924bfb2c9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8af07cdffdbdc161709ccd040fedd48e8d0f51ea/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 90 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0b319b25-77ef-4a77-b1ab-f7b60fd96a2c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8af07cdffdbdc161709ccd040fedd48e8d0f51ea/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/821c91f0-01a7-4d01-addd-ddf3b286e3c3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8af07cdffdbdc161709ccd040fedd48e8d0f51ea/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 88 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/155e0dfc-c2b8-4d45-b343-18ca3e188d06) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bot-messages-ai-generated-content.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8af07cdffdbdc161709ccd040fedd48e8d0f51ea/msteams-platform%2Fbots%2Fhow-to%2Fbot-messages-ai-generated-content.md) | 95 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/77cb3183-1f87-4fe0-bb3e-fa71790afe69) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8af07cdffdbdc161709ccd040fedd48e8d0f51ea/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 81 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f7130096-eda7-48de-b037-6d01931249bf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8af07cdffdbdc161709ccd040fedd48e8d0f51ea/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 86 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/570ab03f-a5b9-4748-9000-168ff3bcb327) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8af07cdffdbdc161709ccd040fedd48e8d0f51ea/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0cd3afc7-4d59-4dce-bd62-aa1728c971a0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8af07cdffdbdc161709ccd040fedd48e8d0f51ea/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 90 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cfe0541d-7e89-4a1e-a529-767a40a09cdf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/includes/conversational-bot-include.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8af07cdffdbdc161709ccd040fedd48e8d0f51ea/msteams-platform%2Fbots%2Fhow-to%2Fincludes%2Fconversational-bot-include.md) | 88 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3ec834df-f41b-484e-905e-351df957b18e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8af07cdffdbdc161709ccd040fedd48e8d0f51ea/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 91 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/74080e22-d1c7-4fb0-8160-1877784d7989) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8af07cdffdbdc161709ccd040fedd48e8d0f51ea/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 89 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/344e668c-f565-47eb-985c-2287a3dad57d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/shared-channels.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8af07cdffdbdc161709ccd040fedd48e8d0f51ea/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshared-channels.md) | 84 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a22bcb28-ec7f-458c-8d91-6d9f4382ac82) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/teams-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8af07cdffdbdc161709ccd040fedd48e8d0f51ea/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fteams-developer-portal.md) | 91 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ff141949-b598-43f9-908f-ac5eb654e316) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8af07cdffdbdc161709ccd040fedd48e8d0f51ea/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 95 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/316769a5-c813-4faf-9cb1-a216f54221a3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8af07cdffdbdc161709ccd040fedd48e8d0f51ea/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-publish-overview.md) | 94 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3a0d6d93-abae-49c2-8853-c9dc3b36906f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8af07cdffdbdc161709ccd040fedd48e8d0f51ea/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3963bcf5-906b-4fc9-9dc2-d197a39e8d23) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8af07cdffdbdc161709ccd040fedd48e8d0f51ea/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fsubmission-checklist.md) | 87 | 48 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7476b465-4728-4d87-beea-52382283f4ea) | [:white_check_mark:](# "Successfully pro [...]

2025-01-23 13:05 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/5278d087106fbc5975ea88d8a4a245aa139c7df0/msteams-platform%2FTOC.yml) | 92 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/08ab5a62-393a-4798-9da9-0e59166be939) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/app-icon-badging-for-your-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5278d087106fbc5975ea88d8a4a245aa139c7df0/msteams-platform%2Fapps-in-teams-meetings%2Fapp-icon-badging-for-your-app.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/235a57d7-5e8a-454c-9934-a6e7ba3e1b52) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5278d087106fbc5975ea88d8a4a245aa139c7df0/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 90 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b224e7e7-f796-4b6a-9078-b4e373c24db5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5278d087106fbc5975ea88d8a4a245aa139c7df0/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/61a01322-fd3a-4fb6-81d1-839950ab47fa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5278d087106fbc5975ea88d8a4a245aa139c7df0/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 88 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/53dfdec2-f2ef-4128-b8e2-cfcbd6e545b7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bot-messages-ai-generated-content.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5278d087106fbc5975ea88d8a4a245aa139c7df0/msteams-platform%2Fbots%2Fhow-to%2Fbot-messages-ai-generated-content.md) | 95 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/18df5ac2-a9a0-4aed-8d56-c56a1431d33f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5278d087106fbc5975ea88d8a4a245aa139c7df0/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 81 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/18c754e5-6f39-4a90-9e42-213ac7c5f01d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5278d087106fbc5975ea88d8a4a245aa139c7df0/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 86 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1348c751-776d-435a-9809-971180ae8c67) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5278d087106fbc5975ea88d8a4a245aa139c7df0/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/43986223-9147-4674-aac3-ac36f9bbcc4f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5278d087106fbc5975ea88d8a4a245aa139c7df0/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 90 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/58dab7f0-595e-4988-9db4-a0e6caa9e120) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/includes/conversational-bot-include.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5278d087106fbc5975ea88d8a4a245aa139c7df0/msteams-platform%2Fbots%2Fhow-to%2Fincludes%2Fconversational-bot-include.md) | 88 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/136ea5ae-43e9-487e-b678-1d13b6841c9f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5278d087106fbc5975ea88d8a4a245aa139c7df0/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 91 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/45d806cc-07c3-4bdd-9546-e807bf4d24ba) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5278d087106fbc5975ea88d8a4a245aa139c7df0/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 89 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8cc3e534-6898-49b4-8328-bd825f121516) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/shared-channels.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5278d087106fbc5975ea88d8a4a245aa139c7df0/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshared-channels.md) | 84 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b893524c-e347-4a57-b9e1-0f4ad45beb45) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/teams-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5278d087106fbc5975ea88d8a4a245aa139c7df0/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fteams-developer-portal.md) | 91 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3efa68c5-c517-4be6-bf33-8f77e0c2cdba) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/cloud-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5278d087106fbc5975ea88d8a4a245aa139c7df0/msteams-platform%2Fconcepts%2Fcloud-overview.md) | 95 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/69ce9007-4ab5-494a-8f58-531b7a983eca) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5278d087106fbc5975ea88d8a4a245aa139c7df0/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-publish-overview.md) | 94 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7071e583-d36b-4e39-93c9-74e274238f7d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5278d087106fbc5975ea88d8a4a245aa139c7df0/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0ff155df-f32c-47ff-920d-a5257755bf9d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5278d087106fbc5975ea88d8a4a245aa139c7df0/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fsubmission-checklist.md) | 87 | 48 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/580ff834-ec8e-4a08-8530-3ae985c6fe56) | [:white_check_mark:](# "Successfully pro [...]

2025-01-23 14:09 UTC, surbhigupta12 approved these changes

2025-01-23 14:12 UTC, merged