[Doc Improvement][Update send activity feed notification]
MicrosoftDocs/msteams-docs pull request #9593
Opened 2023-10-04 18:25 UTC by v-sdhakshina

2023-10-04 18:25 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/tabs/send-activity-feed-notification.md](https://github.com/MicrosoftDocs/msteams-docs/blob/771b61716a4e64a558dc6ed866603f0c29063ac7/msteams-platform%2Ftabs%2Fsend-activity-feed-notification.md) | 94 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0a46131f-982e-4c39-87ec-897ae8d001b5) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-10-05 09:06 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/tabs/send-activity-feed-notification.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8472a8a830de801087b557ac23ae71979ba42d64/msteams-platform%2Ftabs%2Fsend-activity-feed-notification.md) | 94 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a1f15ffc-5505-4d8d-8e59-5a5739348aa2) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-10-12 03:32 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/tabs/send-activity-feed-notification.md](https://github.com/MicrosoftDocs/msteams-docs/blob/64dae60ac0b9ee35f686ad158c3ad8b49f39f495/msteams-platform%2Ftabs%2Fsend-activity-feed-notification.md) | 94 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ce7b191c-8812-45d3-862a-afa25edc7722) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-10-12 04:05 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/tabs/send-activity-feed-notification.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7b969919053e6910f398f5f682d5fbd0c0d5e9f4/msteams-platform%2Ftabs%2Fsend-activity-feed-notification.md) | 94 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8e3f2e15-5029-463d-8fc9-433b99b130c5) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-10-12 06:00 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/tabs/send-activity-feed-notification.md](https://github.com/MicrosoftDocs/msteams-docs/blob/07dd15d05210251d284a42293ee0ef0bb474c6ea/msteams-platform%2Ftabs%2Fsend-activity-feed-notification.md) | 94 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/30f15f58-2979-49ec-bd60-6ed178b7d1c6) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-10-16 12:34 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/tabs/send-activity-feed-notification.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7d0059bef457c38f1fdba453d5a3be546707c734/msteams-platform%2Ftabs%2Fsend-activity-feed-notification.md) | 94 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/beb25692-ef71-4871-8eb0-a36b7089f82f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-10-16 15:03 UTC, mehakagarwal requested changes

2023-10-17 07:11 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/90ee571485cb8b9655358a2d2e7966890645d983/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema.md) | 91 | 40 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/41c7b26b-0085-4361-96b6-d984867253fe) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/send-activity-feed-notification.md](https://github.com/MicrosoftDocs/msteams-docs/blob/90ee571485cb8b9655358a2d2e7966890645d983/msteams-platform%2Ftabs%2Fsend-activity-feed-notification.md) | 94 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0fd0e388-9d71-43af-be04-b086d74bb62f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-10-17 07:34 UTC, v-sdhakshina commented on msteams-platform/tabs/send-activity-feed-notification.md
> +* With the `systemDefault` activity type you can't:
@mehakagarwal As per Microsoft style of document standard, we have to use contractions.

2023-10-17 07:37 UTC, v-sdhakshina commented on msteams-platform/tabs/send-activity-feed-notification.md
> +> * The reserved `systemDefault` activity type mustn't be included in the `activities` section of the app manifest. The reserved `systemDefault` activity type can provide free-form text in the `Actor
Updated as suggested

2023-10-17 07:37 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f2f13b14ddd5c0a6f891d425eccf97668c60e886/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema.md) | 91 | 40 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9d4e1aa8-e3f9-4e72-b8df-973bbf7fe0a6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/send-activity-feed-notification.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f2f13b14ddd5c0a6f891d425eccf97668c60e886/msteams-platform%2Ftabs%2Fsend-activity-feed-notification.md) | 94 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/592c72ea-5c22-4cd4-88a2-4604af656d22) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-10-17 07:46 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f2f13b14ddd5c0a6f891d425eccf97668c60e886/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema.md) | 91 | 40 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d1618f36-4bcd-41b5-8e3f-2b925ebf17ac) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/send-activity-feed-notification.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f2f13b14ddd5c0a6f891d425eccf97668c60e886/msteams-platform%2Ftabs%2Fsend-activity-feed-notification.md) | 94 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9179b77c-6fa0-4be1-b02e-46320398137b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-10-19 15:56 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b164aa1867c02c2813182a4fc10cbb2c66f4f612/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema.md) | 91 | 40 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c1b6ac61-c607-4836-a603-906954fee5ba) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/send-activity-feed-notification.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b164aa1867c02c2813182a4fc10cbb2c66f4f612/msteams-platform%2Ftabs%2Fsend-activity-feed-notification.md) | 94 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/83977b09-1300-42a6-a829-1f1df3630a0a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-10-19 16:17 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6851d085ffd0335bedd1b40f063273a1d91c1582/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema.md) | 91 | 40 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3b85cb96-c95d-4135-a0a4-353fe48a434f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/send-activity-feed-notification.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6851d085ffd0335bedd1b40f063273a1d91c1582/msteams-platform%2Ftabs%2Fsend-activity-feed-notification.md) | 94 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fbe54e87-3da7-4bbb-aca8-e82b40343e3c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-10-19 18:27 UTC, mehakagarwal approved these changes

2023-10-25 13:45 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f8e1ab6ef786406922e30d54f8c929a167cdbb7c/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema.md) | 91 | 40 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cf401e98-3d88-41fa-bdde-45b31b86f242) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/send-activity-feed-notification.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f8e1ab6ef786406922e30d54f8c929a167cdbb7c/msteams-platform%2Ftabs%2Fsend-activity-feed-notification.md) | 94 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b3f7f515-1f0e-43b5-8a6b-7dbf2ce539b3) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-10-26 06:54 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6bebbda38f22fb200b772e62f697bf478773b021/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema.md) | 91 | 40 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a50cab00-2625-4d22-8703-dff85937fe94) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/send-activity-feed-notification.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6bebbda38f22fb200b772e62f697bf478773b021/msteams-platform%2Ftabs%2Fsend-activity-feed-notification.md) | 94 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/97d6a407-bdda-4077-adab-ddcc54ea47da) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-10-27 12:11 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c2f7e4a652752dfacd13070de27b77df4be5a309/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema.md) | 91 | 40 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/128ef53b-34ce-4168-89f9-77116c6b30d2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/send-activity-feed-notification.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c2f7e4a652752dfacd13070de27b77df4be5a309/msteams-platform%2Ftabs%2Fsend-activity-feed-notification.md) | 94 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/727f3fa0-9d31-41c2-a332-6c023ba32fec) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-10-27 12:35 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2ee8f584bcaff8cb3067cc1b4e19ae64840b5b5c/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema.md) | 91 | 40 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1d931cd2-aece-4ea1-bc43-43d6b4253bb6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/send-activity-feed-notification.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2ee8f584bcaff8cb3067cc1b4e19ae64840b5b5c/msteams-platform%2Ftabs%2Fsend-activity-feed-notification.md) | 93 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5a56b2ff-df53-4a59-907a-7cb0025f588c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-10-30 05:21 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cb28362014ddb0c5e7571934b7162cfec3f81523/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema.md) | 90 | 41 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6f876d60-974e-47ea-b9cb-d375d685ecb2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/send-activity-feed-notification.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cb28362014ddb0c5e7571934b7162cfec3f81523/msteams-platform%2Ftabs%2Fsend-activity-feed-notification.md) | 93 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/57d30a92-3a7c-4153-a49a-dfa758c2718f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-10-31 06:33 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4e065f5506089562e8527c2f6c0919b097ee69db/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema.md) | 90 | 41 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/849f9c82-9478-4cb0-b49a-2dc06ac88205) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/send-activity-feed-notification.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4e065f5506089562e8527c2f6c0919b097ee69db/msteams-platform%2Ftabs%2Fsend-activity-feed-notification.md) | 93 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a6a46a6e-2387-4005-a244-a371c07a4712) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-10-31 07:07 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ea46e18a270b2dd05473abeae93756330088c6bd/msteams-platform%2Fmstdd-landing.yml) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/10875239-0d26-4f29-9fb5-deb99123ee87) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ea46e18a270b2dd05473abeae93756330088c6bd/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema.md) | 90 | 41 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7b18e160-edb4-42ef-959d-22ed8a811356) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/send-activity-feed-notification.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ea46e18a270b2dd05473abeae93756330088c6bd/msteams-platform%2Ftabs%2Fsend-activity-feed-notification.md) | 93 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/655459dd-6631-4541-b4db-029ce3bfd1cc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ea46e18a270b2dd05473abeae93756330088c6bd/msteams-platform%2Fwhats-new.md) | 94 | 40 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4d7b9ae1-e932-4aee-b757-fce39dd55919) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-10-31 12:15 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/335001435d550b40e4d988142d5d8b8ae0e23e81/msteams-platform%2Fmstdd-landing.yml) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/564767c6-1928-49ad-8e0f-d825f38925e1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/335001435d550b40e4d988142d5d8b8ae0e23e81/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema.md) | 90 | 43 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/94b4b7e1-a0da-4ea1-871f-7cde14cbfed0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/send-activity-feed-notification.md](https://github.com/MicrosoftDocs/msteams-docs/blob/335001435d550b40e4d988142d5d8b8ae0e23e81/msteams-platform%2Ftabs%2Fsend-activity-feed-notification.md) | 91 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/361e6aa4-1a23-4eca-8c2e-3273896c37dd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/335001435d550b40e4d988142d5d8b8ae0e23e81/msteams-platform%2Fwhats-new.md) | 94 | 42 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8caf1118-7114-4b3e-97a9-69a3a80b2717) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-11-02 05:56 UTC, Wajeed-msft submitted a review, later dismissed

2023-11-02 07:27 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/b1941bff8aafa777c40d9867f2fb22f9214fc369/msteams-platform%2Fmstdd-landing.yml) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/040720bd-c58e-4e9c-a1cb-5d4ab16a451f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b1941bff8aafa777c40d9867f2fb22f9214fc369/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema.md) | 90 | 43 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d34051cc-90cc-4a5b-b18f-23f9910c7ea3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/send-activity-feed-notification.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b1941bff8aafa777c40d9867f2fb22f9214fc369/msteams-platform%2Ftabs%2Fsend-activity-feed-notification.md) | 91 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/875ae587-7c46-46cb-8c3c-27635115b06d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b1941bff8aafa777c40d9867f2fb22f9214fc369/msteams-platform%2Fwhats-new.md) | 94 | 42 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a0e2a687-62bb-4852-b420-3935c64a3e79) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-11-02 07:36 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/d84b13089a6cd6410cb9d4a03f8cbab63a637cb4/msteams-platform%2Fmstdd-landing.yml) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/18ce4ac8-bf42-49c3-b842-cf7780298dd0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d84b13089a6cd6410cb9d4a03f8cbab63a637cb4/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema.md) | 90 | 43 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bbc067f3-546d-4deb-8d5a-9d2ac84f784a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/send-activity-feed-notification.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d84b13089a6cd6410cb9d4a03f8cbab63a637cb4/msteams-platform%2Ftabs%2Fsend-activity-feed-notification.md) | 91 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a66f88f4-53c0-4e5c-9d3a-eddc463a201a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d84b13089a6cd6410cb9d4a03f8cbab63a637cb4/msteams-platform%2Fwhats-new.md) | 94 | 42 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/16ea591e-d6d0-4e2c-97d0-81d97b3ba94c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-11-02 07:46 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c3409377b63c2232d2f805cdcddf7ac23243245b/msteams-platform%2Fmstdd-landing.yml) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/08d34b62-ccca-4c31-be81-46132e25ba27) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c3409377b63c2232d2f805cdcddf7ac23243245b/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema.md) | 90 | 43 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/34511616-1eb2-4baf-b1e8-284d0b44f7df) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/send-activity-feed-notification.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c3409377b63c2232d2f805cdcddf7ac23243245b/msteams-platform%2Ftabs%2Fsend-activity-feed-notification.md) | 91 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/785e9dad-f4ef-44e2-8fda-17ac3e754706) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c3409377b63c2232d2f805cdcddf7ac23243245b/msteams-platform%2Fwhats-new.md) | 94 | 42 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3c8e9163-d779-4acf-a738-682a619c5763) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-11-02 07:56 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/8690242acd065053237b65133eea9024fcbe1fa3/msteams-platform%2Fmstdd-landing.yml) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/07d0548d-4a1d-4421-881c-35a39cafe359) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8690242acd065053237b65133eea9024fcbe1fa3/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema.md) | 90 | 43 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/88509d57-b68a-473c-ac7f-212bd5b4470b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/send-activity-feed-notification.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8690242acd065053237b65133eea9024fcbe1fa3/msteams-platform%2Ftabs%2Fsend-activity-feed-notification.md) | 91 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/72ff2bb6-ee8c-45b7-aa02-876cb6193bb7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8690242acd065053237b65133eea9024fcbe1fa3/msteams-platform%2Fwhats-new.md) | 94 | 42 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/57aa3d58-9c3b-4b62-bb0a-a771931de1db) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-11-02 10:18 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/0a9e06cdf288f3d376d4c85aa669ee8212d73bf1/msteams-platform%2Fmstdd-landing.yml) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2a49515c-3902-4eb3-be13-6004c3d10f28) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0a9e06cdf288f3d376d4c85aa669ee8212d73bf1/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema.md) | 90 | 43 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/942f7242-e68a-4394-b390-ff2b002f6a2d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/send-activity-feed-notification.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0a9e06cdf288f3d376d4c85aa669ee8212d73bf1/msteams-platform%2Ftabs%2Fsend-activity-feed-notification.md) | 91 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9f3d9793-9819-4a88-9047-2aecaea53b4f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0a9e06cdf288f3d376d4c85aa669ee8212d73bf1/msteams-platform%2Fwhats-new.md) | 94 | 42 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0f562857-f7b3-46d2-ba25-aa244fdfb1fb) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-11-02 10:29 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/8c14eb49409206d185a71660c7dc3cdba8457c57/msteams-platform%2Fmstdd-landing.yml) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d83594ad-b3d0-4af8-a310-9a9399634f8f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8c14eb49409206d185a71660c7dc3cdba8457c57/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema.md) | 90 | 43 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/38bb75df-248b-471b-8f43-805431e95432) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/send-activity-feed-notification.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8c14eb49409206d185a71660c7dc3cdba8457c57/msteams-platform%2Ftabs%2Fsend-activity-feed-notification.md) | 91 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d8f33e9f-21f6-45d0-8f60-dcf230c33c17) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8c14eb49409206d185a71660c7dc3cdba8457c57/msteams-platform%2Fwhats-new.md) | 94 | 42 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/64b93431-a25f-4822-9da7-553c81c3b376) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-11-02 13:34 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/9bf090ef4261ec0769bf30ff9be472c470c5aca3/msteams-platform%2Fmstdd-landing.yml) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/913c24eb-426b-4761-bcab-67286a513ea7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9bf090ef4261ec0769bf30ff9be472c470c5aca3/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema.md) | 90 | 43 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1581434f-8db8-4b6a-a418-e295c8417773) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/send-activity-feed-notification.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9bf090ef4261ec0769bf30ff9be472c470c5aca3/msteams-platform%2Ftabs%2Fsend-activity-feed-notification.md) | 92 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7c89a917-6164-43d8-8df0-4b2af5edeacb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9bf090ef4261ec0769bf30ff9be472c470c5aca3/msteams-platform%2Fwhats-new.md) | 94 | 42 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6be6d133-8221-4034-b926-5bdfb10ea2fd) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-11-02 13:44 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/09d68d0b6fb012e9f54ef5773ccd9b140d667390/msteams-platform%2Fmstdd-landing.yml) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8a230044-0d69-4ac6-9f69-d38739597d4f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/09d68d0b6fb012e9f54ef5773ccd9b140d667390/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema.md) | 90 | 43 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2b345d7a-59b6-416a-b63f-8aa795d40f7f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/send-activity-feed-notification.md](https://github.com/MicrosoftDocs/msteams-docs/blob/09d68d0b6fb012e9f54ef5773ccd9b140d667390/msteams-platform%2Ftabs%2Fsend-activity-feed-notification.md) | 92 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9dba5db8-37c7-4b17-8e4d-7f2eac8d1317) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/09d68d0b6fb012e9f54ef5773ccd9b140d667390/msteams-platform%2Fwhats-new.md) | 94 | 42 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5ece3f22-c8fb-416a-8fe1-19453a2c7123) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-11-02 14:17 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/3db523e7e0793760caa413d8abc9f8f50c260a9c/msteams-platform%2Fmstdd-landing.yml) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/22344888-a16f-473e-94de-245375dc2669) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3db523e7e0793760caa413d8abc9f8f50c260a9c/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema.md) | 90 | 43 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/091b3132-3cf6-49fc-9f49-c1d8127a4dfa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/send-activity-feed-notification.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3db523e7e0793760caa413d8abc9f8f50c260a9c/msteams-platform%2Ftabs%2Fsend-activity-feed-notification.md) | 92 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/26a8c879-41d2-4b9d-9cbb-83ff58fb839c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3db523e7e0793760caa413d8abc9f8f50c260a9c/msteams-platform%2Fwhats-new.md) | 94 | 42 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/afb17bf2-3919-4888-8732-75c6fc8e3abc) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-11-03 07:42 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/05e320b07f4d8c26d3cd2e633baeef8856fdab94/msteams-platform%2Fmstdd-landing.yml) | 92 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/178dadd2-558a-46bf-ab43-09bdd8cdd590) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/05e320b07f4d8c26d3cd2e633baeef8856fdab94/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema.md) | 90 | 43 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/31288a9c-e1ea-492c-a7b5-646d84a1cb12) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/send-activity-feed-notification.md](https://github.com/MicrosoftDocs/msteams-docs/blob/05e320b07f4d8c26d3cd2e633baeef8856fdab94/msteams-platform%2Ftabs%2Fsend-activity-feed-notification.md) | 92 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/53ac4b71-6a3a-4769-8100-27cf8e3fcc2f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/05e320b07f4d8c26d3cd2e633baeef8856fdab94/msteams-platform%2Fwhats-new.md) | 94 | 42 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/859c7203-27ea-4d14-8ff6-9aab0f9fce0f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-11-03 07:44 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/420e07aa0f0d479e6c1dcab72fc02f249510d609/msteams-platform%2Fmstdd-landing.yml) | 92 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f6da7f24-5e5f-4a26-9c6e-6344b218de86) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/420e07aa0f0d479e6c1dcab72fc02f249510d609/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema.md) | 90 | 43 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/59e11033-cdc1-4c9b-9160-7f6aac6ccdff) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/send-activity-feed-notification.md](https://github.com/MicrosoftDocs/msteams-docs/blob/420e07aa0f0d479e6c1dcab72fc02f249510d609/msteams-platform%2Ftabs%2Fsend-activity-feed-notification.md) | 92 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/19a66393-88a7-47c8-b591-8e51a9f3120b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/420e07aa0f0d479e6c1dcab72fc02f249510d609/msteams-platform%2Fwhats-new.md) | 94 | 42 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/be6a9902-92c7-4d54-b295-4c6cbb5d6806) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-11-03 07:45 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/cf645ceefd80ab84bd9c3bf024a328d89202a29a/msteams-platform%2Fmstdd-landing.yml) | 92 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d099f91e-8e99-4893-a885-97b76a0d0492) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cf645ceefd80ab84bd9c3bf024a328d89202a29a/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema.md) | 90 | 43 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cf0433d0-0f3a-46ff-a499-39e211597f04) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/send-activity-feed-notification.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cf645ceefd80ab84bd9c3bf024a328d89202a29a/msteams-platform%2Ftabs%2Fsend-activity-feed-notification.md) | 92 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2afb66d8-4f6b-4ecc-b00d-0481f6cfe3e4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cf645ceefd80ab84bd9c3bf024a328d89202a29a/msteams-platform%2Fwhats-new.md) | 94 | 42 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cb1e6f97-eee3-4b58-bedb-34749b50d3a0) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-11-03 08:38 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/40fbad0f849c8b19d55391ace7df19d8fb69f463/msteams-platform%2Fmstdd-landing.yml) | 92 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/da2341fb-f8b7-4a0e-86f3-7a4727035ad9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/40fbad0f849c8b19d55391ace7df19d8fb69f463/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema.md) | 90 | 43 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0d1bec16-3b35-4240-9f7a-37b7822e5649) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/send-activity-feed-notification.md](https://github.com/MicrosoftDocs/msteams-docs/blob/40fbad0f849c8b19d55391ace7df19d8fb69f463/msteams-platform%2Ftabs%2Fsend-activity-feed-notification.md) | 92 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0f5e02c0-908f-4b7a-b963-65fc3382ef89) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/40fbad0f849c8b19d55391ace7df19d8fb69f463/msteams-platform%2Fwhats-new.md) | 94 | 42 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0e508f8f-20da-4f29-af42-9ab84b08fab3) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-11-03 12:34 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c16d6d5746b507db1324fc5a505da859570297bb/msteams-platform%2Fmstdd-landing.yml) | 92 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/56379dbe-e0b5-48da-8c5b-fec9bf5c02f4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c16d6d5746b507db1324fc5a505da859570297bb/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema.md) | 90 | 43 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4f398dd5-ef1b-4766-9736-2600e2d53724) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/send-activity-feed-notification.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c16d6d5746b507db1324fc5a505da859570297bb/msteams-platform%2Ftabs%2Fsend-activity-feed-notification.md) | 92 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/efb44950-4de3-4960-8105-91fb78c7a4c6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c16d6d5746b507db1324fc5a505da859570297bb/msteams-platform%2Fwhats-new.md) | 94 | 42 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cd279fca-bac7-46fe-995a-ffa1c108a647) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-11-03 12:39 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e6d16d4041900f4065f2028e80c02bf1991c7557/msteams-platform%2Fmstdd-landing.yml) | 92 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ae261c8d-c445-4685-9ccd-4096e4d1f4d2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e6d16d4041900f4065f2028e80c02bf1991c7557/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema.md) | 90 | 43 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a2564a55-4040-4458-b31e-18c16f3a13d3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/send-activity-feed-notification.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e6d16d4041900f4065f2028e80c02bf1991c7557/msteams-platform%2Ftabs%2Fsend-activity-feed-notification.md) | 92 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dcc2c08f-6a01-4e28-b004-5c97a7e57d17) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e6d16d4041900f4065f2028e80c02bf1991c7557/msteams-platform%2Fwhats-new.md) | 94 | 42 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/511887f6-f16f-450c-ad0d-4ce39892b22d) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

2023-11-03 12:41 UTC, surbhigupta12 approved these changes

2023-11-03 12:41 UTC, merged