[Doc Feature] [Build Actions]
MicrosoftDocs/msteams-docs pull request #9677
Opened 2023-10-16 00:16 UTC by mobajemu-msft

*  stand-up Overview and How-to page for Actions

2023-10-19 20:03 UTC, erikadoyle commented
@v-bvishnu could you please help merge this into the feature branch (doc-feature-actions-m365)? From there we'll pass the baton to your team for next steps. /Cc @surbhigupta12  Thanks!

2023-11-14 17:56 UTC, mobajemu-msft commented
@v-bvishnu Thank you for your recent changes but I have reverted most of them. It is best if the how-to section you added to the overview doc remains in the how-to doc, the overview should give general guidance what Action is and the how-to should have instruction for how to build it. I was able to pull in all your other changes and thank you for those.

2023-11-30 07:17 UTC, erikadoyle commented on msteams-platform/m365-apps/actions.md
> +Actions seamlessly integrate your app into the user's workflow, ensuring effortless discovery and smooth interaction with their content. By guiding users to your app based on their intent and context
"seamlessly" and "effortless" might be overselling this a bit...suggest dropping those adjectives. Also "Which integration increases your app's visibility and engagement with minimal development effort." . . . I don't think that's a sentence?

2023-11-30 07:19 UTC, erikadoyle commented on msteams-platform/TOC.yml
> +  - name: M365 Actions
Global comment: Always spell out Microsoft 365 ("M365" isn't sanctioned by branding for public comms)

2023-11-30 07:21 UTC, erikadoyle commented on msteams-platform/m365-apps/actions.md
> +1. Users can take immediate action on content files through your app, expanding the range of interactions they can have with their content.  
This para seems redundant to the intro above; can probably cut

2023-11-30 07:29 UTC, erikadoyle commented on msteams-platform/TOC.yml
> +  - name: M365 Actions
Also I think the spacing is misaligned here, so the new articles appear orphaned rather than hooked into the TOC.

2023-11-30 07:53 UTC, erikadoyle requested changes
Let's work w/Surbhi and Vishnu on merging the two drafts + including some missing sections from Irene's doc. Meeting forthcoming--

2024-01-31 14:54 UTC, surbhigupta12 commented
Closing this PR.

2024-01-31 14:54 UTC, closed without merging